### ISSUE TITLE
训练mobilenet_v1_ssd时关闭config中的with_extra_blocks 报错

### ISSUE THREAD

**Issue by FibonacciSun** [PaddlePaddle/PaddleDetection#103]
with_extra_blocks 设置为true是没问题的

Trace如下：

Traceback (most recent call last):
  File "tools/train.py", line 340, in <module>
    main()
  File "tools/train.py", line 128, in main
    train_fetches = model.train(feed_vars)
  File "$paddlepaddle/work/PaddleDetection/ppdet/modeling/architectures/ssd.py", line 94, in train
    return self.build(feed_vars, 'train')
  File "$paddlepaddle/work/PaddleDetection/ppdet/modeling/architectures/ssd.py", line 82, in build
    inputs=body_feats, image=im, num_classes=self.num_classes)
  File "$paddlepaddle/work/PaddleDetection/ppdet/core/workspace.py", line 113, in partial_apply
    return op(*args, **kwargs_)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/layers/detection.py", line 2154, in multi_box_head
    'aspect_ratios should be list or tuple, and the length of inputs '
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/layers/detection.py", line 2131, in _is_list_or_tuple_and_equal
    raise ValueError(err_info)
ValueError: aspect_ratios should be list or tuple, and the length of inputs and aspect_ratios should be the same.

另外请教下，这里extra block是啥意思，有论文之类的原理介绍吗？
感谢

**Comment by willthefrog** [comment]
如果禁用`with_extra_blocks`，需同时修改 `MultiBoxHead`的`aspect_ratios`选项，使其同feature map的数量对应，启用时是6个，禁用时是3个。鉴于目前预训练模型也是对应6个的，所以不建议禁用。

模型设计原理请参考SSD，mobilenet v1及v2的paper。

**Comment by FibonacciSun** [comment]
明白了，谢谢
