### ISSUE TITLE
关于测试PaddleDetection

### ISSUE THREAD

**Issue by butterniu** [PaddlePaddle/PaddleDetection#1120]
我想请问一下，我安装好了环境，克隆了PaddleDetection项目，在进行测试时，出现了一些问题，
(paddle_env) E:\Paddle\PaddleDetection>python ppdet/modeling/tests/test_architectures.py
ss........EE
======================================================================
ERROR: test_test (__main__.TestYolov3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\Paddle\PaddleDetection\ppdet\modeling\tests\decorator_helper.py", line 29, in __fn__
    fn(*args, **kwargs)
  File "ppdet/modeling/tests/test_architectures.py", line 57, in test_test
    test_fetches = model.eval(feed_vars)
  File "E:\Paddle\PaddleDetection\ppdet\modeling\architectures\yolo.py", line 162, in eval
    return self.build(feed_vars, mode='test')
  File "E:\Paddle\PaddleDetection\ppdet\modeling\architectures\yolo.py", line 93, in build
    body_feats, im_size, exclude_nms=exclude_nms)
  File "E:\Paddle\PaddleDetection\ppdet\modeling\anchor_heads\yolo_head.py", line 437, in get_prediction
    scale_x_y=scale_x_y)
TypeError: yolo_box() got an unexpected keyword argument 'scale_x_y'

======================================================================
ERROR: test_train (__main__.TestYolov3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\Paddle\PaddleDetection\ppdet\modeling\tests\decorator_helper.py", line 29, in __fn__
    fn(*args, **kwargs)
  File "ppdet/modeling/tests/test_architectures.py", line 49, in test_train
    train_fetches = model.train(feed_vars)
  File "E:\Paddle\PaddleDetection\ppdet\modeling\architectures\yolo.py", line 159, in train
    return self.build(feed_vars, mode='train')
  File "E:\Paddle\PaddleDetection\ppdet\modeling\architectures\yolo.py", line 85, in build
    gt_score, targets)
  File "E:\Paddle\PaddleDetection\ppdet\modeling\anchor_heads\yolo_head.py", line 401, in get_loss
    self.prefix_name)
  File "E:\Paddle\PaddleDetection\ppdet\modeling\losses\yolo_loss.py", line 88, in __call__
    name=prefix_name + "yolo_loss" + str(i))
TypeError: yolov3_loss() got an unexpected keyword argument 'scale_x_y'

----------------------------------------------------------------------
Ran 12 tests in 4.906s

FAILED (errors=2, skipped=2)

在工程PaddleDetection下的ppdet\modeling\losses\yolo_loss.py的76行，loss = fluid.layers.yolov3_loss()，我查看了paddle源码的路径layers的文件夹下没有yolov3_loss()的方法，重新安装了几遍也无法解决，小白的我暂时没有了应对办法，请求您或者遇到过此类问题的大神帮忙解决一下，不胜感激。

**Comment by butterniu** [comment]
我翻阅了所有的问题，在一个close的问题中找到了答案，master分支需要用paddle 2.0 alpha版本以上，scale_x_y是最近添加的。
可以通过更新paddle的版本或者注释掉scale_x_y解决这个问题。

**Comment by jerrywgz** [comment]
是的，在PaddleDetection release/0.3分支下未更新scale_x_y接口，如果希望使用该接口的话需要使用paddle 2.0.0.a0或develop版本

**Comment by butterniu** [comment]
感谢您的回答，我已经解决了
