### ISSUE TITLE
paddl2onnx 转换失败

### ISSUE THREAD

**Issue by zhengkai15** [PaddlePaddle/PaddleDetection#1143]
paddle2onnx --fluid_model inference_model/faster_rcnn_r50_fpn_1x/ --onnx_model model.pb
-----------  Configuration Arguments -----------
check_task: image_classification
debug: False
fluid_model: inference_model/faster_rcnn_r50_fpn_1x/
fluid_model_name: 
fluid_params_name: 
image_path: 
name_prefix: 
onnx_model: model.pb
return_variable: False
to_print_model: False
------------------------------------------------
/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "/usr/local/bin/paddle2onnx", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/fluid_onnx/fluid_to_onnx.py", line 230, in main
    convert(args)
  File "/usr/local/lib/python3.6/dist-packages/fluid_onnx/fluid_to_onnx.py", line 99, in convert
    ] = fluid.io.load_inference_model(args.fluid_model, exe)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/io.py", line 1402, in load_inference_model
    load_persistables(executor, load_dirname, program, params_filename)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/io.py", line 928, in load_persistables
    filename=filename)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/io.py", line 751, in load_vars
    filename=filename)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/io.py", line 805, in load_vars
    executor.run(load_prog)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 1229, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
3   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, double>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, int>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, signed char>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, long> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
6   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
7   paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
8   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
9   paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/io.py", line 785, in load_vars
    attrs={'file_path': os.path.join(dirname, new_var.name)})
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/io.py", line 751, in load_vars
    filename=filename)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/io.py", line 928, in load_persistables
    filename=filename)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/io.py", line 1402, in load_inference_model
    load_persistables(executor, load_dirname, program, params_filename)
  File "/usr/local/lib/python3.6/dist-packages/fluid_onnx/fluid_to_onnx.py", line 99, in convert
    ] = fluid.io.load_inference_model(args.fluid_model, exe)
  File "/usr/local/lib/python3.6/dist-packages/fluid_onnx/fluid_to_onnx.py", line 230, in main
    convert(args)
  File "/usr/local/bin/paddle2onnx", line 8, in <module>
    sys.exit(main())

----------------------
Error Message Summary:
----------------------
UnavailableError: Load operator fail to open file inference_model/faster_rcnn_r50_fpn_1x/cls_score_b, please check whether the model file is complete or damaged.
  [Hint: Expected static_cast<bool>(fin) == true, but received static_cast<bool>(fin):0 != true:1.] at (/paddle/paddle/fluid/operators/load_op.h:41)
  [operator < load > error]

**Comment by zhengkai15** [comment]
有大神碰到过这个问题吗，一直不知道为什么，也么查到类似问题的解决方案

**Comment by qingqing01** [comment]
@zhengkai15 可以在https://github.com/PaddlePaddle/X2Paddle/issues 提问下

**Comment by jiangjiajun** [comment]
> 有大神碰到过这个问题吗，一直不知道为什么，也么查到类似问题的解决方案

目前Paddle2ONNX功能已迁移至X2Paddle，请安装X2Paddle进行模型转换 https://github.com/PaddlePaddle/X2Paddle

此外，转ONNX的模型支持中，对于检测模型目前只支持YOLOv3和SSD系列，RCNN暂不支持。

**Comment by zhengkai15** [comment]
> > 有大神碰到过这个问题吗，一直不知道为什么，也么查到类似问题的解决方案
> 
> 目前Paddle2ONNX功能已迁移至X2Paddle，请安装X2Paddle进行模型转换 https://github.com/PaddlePaddle/X2Paddle
> 
> 此外，转ONNX的模型支持中，对于检测模型目前只支持YOLOv3和SSD系列，RCNN暂不支持。

好的谢谢你

**Comment by zhengkai15** [comment]
> > 有大神碰到过这个问题吗，一直不知道为什么，也么查到类似问题的解决方案
> 
> 目前Paddle2ONNX功能已迁移至X2Paddle，请安装X2Paddle进行模型转换 https://github.com/PaddlePaddle/X2Paddle
> 
> 此外，转ONNX的模型支持中，对于检测模型目前只支持YOLOv3和SSD系列，RCNN暂不支持。

我看这个下面的issue 说已经可以支持yolov4了呢，我先测试一下
