### ISSUE TITLE
在 ppdet/modeling/ops.py 里面用的 fluid.layers.matrix_nms op 不存在

### ISSUE THREAD

**Issue by XiminLin** [PaddlePaddle/PaddleDetection#1148]
我正准备 eval ppyolo.yml, 但是 ops.py/MatrixNMS class 需要的 fluid.layers.matrix_nms op 不存在... 
执行命令: 
` python tools/eval.py --config=configs/ppyolo/ppyolo.yml
`
报错:

Traceback (most recent call last):
  File "tools/eval.py", line 180, in <module>
    main()
  File "tools/eval.py", line 71, in main
    fetches = model.eval(feed_vars)
  File "/Users/ximinlin/Documents/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 172, in eval
    return self.build(feed_vars, mode='test')
  File "/Users/ximinlin/Documents/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 103, in build
    body_feats, im_size, exclude_nms=exclude_nms)
  File "/Users/ximinlin/Documents/PaddleDetection/ppdet/modeling/anchor_heads/yolo_head.py", line 455, in get_prediction
    pred = self.nms(bboxes=yolo_boxes, scores=yolo_scores)
TypeError: 'MatrixNMS' object is not callable

当前 paddle 版本: 2.0.0a0 CPU version, python: 3.7; 谢谢

**Comment by qingqing01** [comment]
@XiminLin  

MatrixNMS需要使用最新的develop版本的whl包，可以参考 https://github.com/PaddlePaddle/PaddleDetection/issues/1103#issuecomment-663858241 安装试用。  否则，使用2.0.alpha版本的话，得去掉MatrixNMS。

**Comment by XiminLin** [comment]
好, 谢谢
