### ISSUE TITLE
在用自己数据集训练mask_rcnn时一直出现问题

### ISSUE THREAD

**Issue by lky-bit** [PaddlePaddle/PaddleDetection#1178]
原始数据集采用labelme标注生成
数据集使用X2coco的代码生成
路径：C:\Users\HX\PaddleDetection\cocome
--annotations
--train
--val

报错：
(paddle) C:\Users\HX\PaddleDetection>python -u tools/train.py -c configs/mask_rcnn_r50_1x.yml --eval
2020-08-09 13:29:09,650-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000100] in Optimizer will not take effect, and it will only be applied to other Parameters!
2020-08-09 13:29:10,163-INFO: Dataset C:\Users\HX\PaddleDetection\dataset\railway is not valid for reason above, try searching C:\Users\HX/.cache/paddle/dataset or downloading dataset...
Traceback (most recent call last):
  File "tools/train.py", line 368, in <module>
    main()
  File "tools/train.py", line 145, in main
    eval_reader = create_reader(cfg.EvalReader, devices_num=1)
  File "C:\Users\HX\PaddleDetection\ppdet\data\reader.py", line 434, in create_reader
    reader = Reader(**cfg)()
  File "C:\Users\HX\PaddleDetection\ppdet\data\reader.py", line 208, in __init__
    self._roidbs = self._dataset.get_roidb()
  File "C:\Users\HX\PaddleDetection\ppdet\data\source\dataset.py", line 65, in get_roidb
    self.image_dir)
  File "C:\Users\HX\PaddleDetection\ppdet\utils\download.py", line 145, in get_dataset_path
    format(path, osp.split(path)[-1]))
ValueError: Dataset dataset/railway is not valid and cannot parse dataset type 'railway' for automaticly downloading, which only supports 'voc' , 'coco', 'wider_face' and 'fruit' currently

环境：windows10、python3.7、paddledetection

**Comment by jerrywgz** [comment]
从报错信息来看应该是由于你的数据路径配置错了触发了数据集自动下载。你的数据路径应该在C:\Users\HX\PaddleDetection\cocome， 而配置的路径为C:\Users\HX\PaddleDetection\dataset\railway

**Comment by lky-bit** [comment]
> 从报错信息来看应该是由于你的数据路径配置错了触发了数据集自动下载。你的数据路径应该在C:\Users\HX\PaddleDetection\cocome， 而配置的路径为C:\Users\HX\PaddleDetection\dataset\railway

这个配置文件是修改mask_fpn_reader.yml里面吗？我修改之后还是不行
TrainReader:
  inputs_def:
    fields: ['image', 'im_info', 'im_id', 'gt_bbox', 'gt_class', 'is_crowd', 'gt_mask']
  dataset:
    !COCODataSet
    image_dir: train
    anno_path: annotations/instance_train.json
    dataset_dir: cocome

EvalReader:
  inputs_def:
    fields: ['image', 'im_info', 'im_id', 'im_shape']
    # for voc
    #fields: ['image', 'im_info', 'im_id', 'gt_bbox', 'gt_class', 'is_difficult']
  dataset:
    !COCODataSet
    image_dir: val
    anno_path: annotations/instance_val.json
    dataset_dir: cocome

TestReader:
  inputs_def:
    fields: ['image', 'im_info', 'im_id', 'im_shape']
  dataset:
    !ImageFolder
    anno_path: annotations/instance_val.json

**Comment by jerrywgz** [comment]
你的模型是mask rcnn的话应该修改mask_reader.yml

**Comment by lky-bit** [comment]
> 你的模型是mask rcnn的话应该修改mask_reader.yml

修改后可以了，但又出现新的问题，这是标注的问题吗？
2020-08-09 16:14:45,653-WARNING: Found an invalid bbox in annotations: im_id: 118, area: -3034.072471606267 x1: 1042.0232558139535, y1: 1055.7441860465117, x2: 1042.0232558139535, y2: 1131.4883720930234.
2020-08-09 16:14:45,662-INFO: places would be ommited when DataLoader is not iterable
W0809 16:14:45.673089 21688 build_strategy.cc:170] fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU.
2020-08-09 16:14:46,664-INFO: iter: 0, lr: 0.000333, 'loss_cls': '1.113505', 'loss_bbox': '0.038984', 'loss_rpn_cls': '0.689729', 'loss_rpn_bbox': '0.099477', 'loss_mask': '1.218861', 'loss': '3.160557', time: 0.000, eta: 0:00:00

**Comment by jerrywgz** [comment]
是的，这里会自动检查不合法的数据，例如x2>x1或者area<=0等

**Comment by lky-bit** [comment]
> 是的，这里会自动检查不合法的数据，例如x2>x1或者area<=0等

多谢多谢

**Comment by tangxiaochu123230** [comment]
dataset_dir得用绝对地址

**Comment by jerrywgz** [comment]
issue先关闭了，如果还有新的问题可以再提issue，我们会及时跟进
