### ISSUE TITLE
vehicle_yolov3_darknet.yml file Scanner issue

### ISSUE THREAD

**Issue by pritul2** [PaddlePaddle/PaddleDetection#1180]
```
!export CUDA_VISIBLE_DEVICES=0
!python -u tools/infer.py -c /content/vehicle_yolov3_darknet.yml \
                         -o weights=/content/vehicle_yolov3_darknet.tar \
                         --infer_dir /content/img.png \
                         --draw_threshold 0.25 \
                         --output_dir contrib/VehicleDetection/demo/output
```

Traceback (most recent call last):
  File "tools/infer.py", line 261, in <module>
    main()
  File "tools/infer.py", line 91, in main
    cfg = load_config(FLAGS.config)
  File "/content/PaddleDetection/ppdet/core/workspace.py", line 86, in load_config
    cfg = merge_config(yaml.load(f, Loader=yaml.Loader), cfg)
  File "/usr/local/lib/python3.6/dist-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.6/dist-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.6/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.6/dist-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/usr/local/lib/python3.6/dist-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.6/dist-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/usr/local/lib/python3.6/dist-packages/yaml/scanner.py", line 128, in peek_token
    self.fetch_more_tokens()
  File "/usr/local/lib/python3.6/dist-packages/yaml/scanner.py", line 220, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/local/lib/python3.6/dist-packages/yaml/scanner.py", line 576, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "/content/vehicle_yolov3_darknet.yml", line 123, column 34

**Comment by qingqing01** [comment]
@pritul2 

>  in "/content/vehicle_yolov3_darknet.yml", line 123, column 34


从错误看，您更改了 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/contrib/VehicleDetection/vehicle_yolov3_darknet.yml 这个配置，可以具体看下你对应配置中123行是不是配置有误。

**Comment by pritul2** [comment]
@qingqing01 It is now showing this error
```
!export CUDA_VISIBLE_DEVICES=0
!python -u tools/infer.py -c /content/PaddleDetection/vehicle_yolov3_darknet.yml \
                         -o weights=/content/vehicle_yolov3_darknet.tar \
                         --infer_dir /content \
                         --draw_threshold 0.25 \
                         --output_dir contrib/VehicleDetection/demo/output

```

2020-08-10 06:23:09,982-INFO: Found 1 inference images in total.
Traceback (most recent call last):
  File "tools/infer.py", line 261, in <module>
    main()
  File "tools/infer.py", line 116, in main
    inputs_def = cfg['TestReader']['inputs_def']
KeyError: 'inputs_def'

**Comment by qingqing01** [comment]
@pritul2 

I tested on release/0.4 by:

```
export CUDA_VISIBLE_DEVICES=1
python -u tools/infer.py -c contrib/VehicleDetection/vehicle_yolov3_darknet.yml \
                         -o weights=https://paddlemodels.bj.bcebos.com/object_detection/vehicle_yolov3_darknet.tar \
                         --infer_dir contrib/VehicleDetection/demo \
                         --draw_threshold 0.2 \
                         --output_dir contrib/VehicleDetection/demo/output
```

I found no problem.

```
2020-08-10 09:06:34,382-INFO: Found 4 inference images in total.
W0810 09:06:35.178603 107922 device_context.cc:268] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 9.0
W0810 09:06:35.210638 107922 device_context.cc:276] device: 0, cuDNN Version: 7.5.
2020-08-10 09:06:49,420-INFO: Downloading vehicle_yolov3_darknet.tar from https://paddlemodels.bj.bcebos.com/object_detection/vehicle_yolov3_darknet.tar
100%|##########| 241000/241000 [03:08<00:00, 1275.90KB/s]
2020-08-10 09:10:00,746-INFO: Decompressing /root/.cache/paddle/weights/vehicle_yolov3_darknet.tar...
2020-08-10 09:10:02,517-INFO: Load categories from contrib/VehicleDetection/vehicle.json
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2020-08-10 09:10:03,456-INFO: Infer iter 0
2020-08-10 09:10:03,507-INFO: Detection bbox results save in contrib/VehicleDetection/demo/output/001.jpeg
2020-08-10 09:10:03,598-INFO: Infer iter 1
2020-08-10 09:10:03,616-INFO: Detection bbox results save in contrib/VehicleDetection/demo/output/004.png
2020-08-10 09:10:03,859-INFO: Infer iter 2
2020-08-10 09:10:03,877-INFO: Detection bbox results save in contrib/VehicleDetection/demo/output/003.png
2020-08-10 09:10:04,198-INFO: Infer iter 3
2020-08-10 09:10:04,217-INFO: Detection bbox results save in contrib/VehicleDetection/demo/output/005.png
```


Which PaddleDetection version do you use?

**Comment by pritul2** [comment]
Updating version of paddlepaddle solved the issue...
