### ISSUE TITLE
PaddleDetection train，报错:TypeError: yolov3_loss() got an unexpected keyword argument 'scale_x_y'

### ISSUE THREAD

**Issue by trollhe** [PaddlePaddle/PaddleDetection#1189]
版本信息:
```
python3.7
PaddlePaddle 1.8.0
gpu环境
```

在aistudio中，运行如下命令训练
```
# 准备数据集
!python dataset/fruit/download_fruit.py

# 训练模型
!python -u tools/train.py -c configs/yolov3_mobilenet_v1_fruit.yml
```
报错信息如下:
```
2020-08-11 11:38:03,638-WARNING: paddle.fluid.layers.matrix_nms OP not found, maybe a newer version of paddle is required.
Traceback (most recent call last):
  File "tools/train.py", line 368, in <module>
    main()
  File "tools/train.py", line 114, in main
    train_fetches = model.train(feed_vars)
  File "/home/aistudio/work/det/ppdet/modeling/architectures/yolo.py", line 159, in train
    return self.build(feed_vars, mode='train')
  File "/home/aistudio/work/det/ppdet/modeling/architectures/yolo.py", line 85, in build
    gt_score, targets)
  File "/home/aistudio/work/det/ppdet/modeling/anchor_heads/yolo_head.py", line 401, in get_loss
    self.prefix_name)
  File "/home/aistudio/work/det/ppdet/modeling/losses/yolo_loss.py", line 88, in __call__
    name=prefix_name + "yolo_loss" + str(i))
TypeError: yolov3_loss() got an unexpected keyword argument 'scale_x_y'
```
  看了没有关于这方面的报错解决方法，烦请帮忙处理下。

**Comment by jerrywgz** [comment]
目前yolov3的模型需要使用paddle2.0.0.a0的版本，我们近期会再发布1.8.4版本，新版本也是可以使用的

**Comment by trollhe** [comment]
好的

**Comment by sunfuxin111** [comment]
paddle.fluid.layers.matrix_nms OP not found, maybe a newer version of paddle is required.
ssEEEEEEEEss
======================================================================
ERROR: test_test (__main__.TestFasterRCNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\PaddleX\PaddleDemo\PaddleDetection\ppdet\modeling\tests\test_architectures.py", line 39, in setUp
    self.cfg = load_config(self.cfg_file)
  File "E:\PaddleX\PaddleDemo\PaddleDetection\ppdet\core\workspace.py", line 85, in load_config
    with open(file_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/faster_rcnn_r50_1x.yml'

======================================================================
ERROR: test_train (__main__.TestFasterRCNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\PaddleX\PaddleDemo\PaddleDetection\ppdet\modeling\tests\test_architectures.py", line 39, in setUp
    self.cfg = load_config(self.cfg_file)
  File "E:\PaddleX\PaddleDemo\PaddleDetection\ppdet\core\workspace.py", line 85, in load_config
    with open(file_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/faster_rcnn_r50_1x.yml'

======================================================================
ERROR: test_test (__main__.TestMaskRCNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\PaddleX\PaddleDemo\PaddleDetection\ppdet\modeling\tests\test_architectures.py", line 39, in setUp
    self.cfg = load_config(self.cfg_file)
  File "E:\PaddleX\PaddleDemo\PaddleDetection\ppdet\core\workspace.py", line 85, in load_config
    with open(file_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/mask_rcnn_r50_1x.yml'

======================================================================
ERROR: test_train (__main__.TestMaskRCNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\PaddleX\PaddleDemo\PaddleDetection\ppdet\modeling\tests\test_architectures.py", line 39, in setUp
    self.cfg = load_config(self.cfg_file)
  File "E:\PaddleX\PaddleDemo\PaddleDetection\ppdet\core\workspace.py", line 85, in load_config
    with open(file_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/mask_rcnn_r50_1x.yml'

=====================================================================
请问出现这种问题怎么解决，PaddlePaddle 1.5.0 cuda9 cudnn7.6 gpu环境
