### ISSUE TITLE
training with my own dataset

### ISSUE THREAD

**Issue by sukkyusun1** [PaddlePaddle/PaddleDetection#1191]
I changed my training data to voc format(xml)
and trying to train ppyolo
here are my configuration

 dataset:
    !VOCDataSet
      anno_path: trainval.txt
      dataset_dir: /home/sk/PaddleDetection-release-0.4/dataset/voc
      with_background: false
      use_default_label : false

   !VOCDataSet
      anno_path: test.txt
      dataset_dir: /home/sk/PaddleDetection-release-0.4/dataset/voc
      with_background: false
      use_default_label : false

result

2020-08-11 19:29:34,653-INFO: Dataset /home/sk/PaddleDetection-release-0.4/dataset/voc is not valid for reason above, try searching /home/sk/.cache/paddle/dataset or downloading dataset...

following occured and download started

it seems to be voc2012 folder is empty?

is there any method that  solely training with my own data?

**Comment by jerrywgz** [comment]
Please check the path in your annotation. For voc2007, dataset_dir is set to ```dataset/voc``` and path in annotation is set to ```VOCdevkit/VOC2007/JPEGImages/000031.jpg VOCdevkit/VOC2007/Annotations/000031.xml```, and the path of picture should be ```dataset/voc/VOCdevkit/VOC2007/JPEGImages/000031.jpg```

**Comment by sukkyusun1** [comment]
i changed it 

VOCdevkit/VOC2007/JPEGImages/000031.jpg VOCdevkit/VOC2007/Annotations/000031.xml
to following format
but another error occured



Traceback (most recent call last):
  File "/home/sk/PaddleDetection-release-0.4/tools/train.py", line 368, in <module>
    main()
  File "/home/sk/PaddleDetection-release-0.4/tools/train.py", line 145, in main
    eval_reader = create_reader(cfg.EvalReader, devices_num=1)
  File "/home/sk/PaddleDetection-release-0.4/ppdet/data/reader.py", line 434, in create_reader
    reader = Reader(**cfg)()
  File "/home/sk/PaddleDetection-release-0.4/ppdet/data/reader.py", line 208, in __init__
    self._roidbs = self._dataset.get_roidb()
  File "/home/sk/PaddleDetection-release-0.4/ppdet/data/source/dataset.py", line 68, in get_roidb
    self.load_roidb_and_cname2cid()
  File "/home/sk/PaddleDetection-release-0.4/ppdet/data/source/voc.py", line 143, in load_roidb_and_cname2cid
    _difficult = int(obj.find('difficult').text)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
