### ISSUE TITLE
执行PP-YOLO出错，提示ValueError: Extraneous param for class<YOLOv3Head>: spp, coord_conv

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/PaddleDetection#1211]
- PaddlePaddle-GPU 1.8.4
 - Python 3.7
 - Windows 10
 -  release 0.4

```
Traceback (most recent call last):
  File "D:/yeyupiaoling/PyCharm/PP-YOLO/train.py", line 368, in <module>
    main()
  File "D:/yeyupiaoling/PyCharm/PP-YOLO/train.py", line 104, in main
    model = create(main_arch)
  File "D:\yeyupiaoling\PyCharm\PP-YOLO\ppdet\core\workspace.py", line 250, in create
    kwargs[k] = create(target_key)
  File "D:\yeyupiaoling\PyCharm\PP-YOLO\ppdet\core\workspace.py", line 214, in create
    config.validate()
  File "D:\yeyupiaoling\PyCharm\PP-YOLO\ppdet\core\config\schema.py", line 143, in validate
    self.name, ", ".join(extra_keys)))
ValueError: Extraneous param for class<YOLOv3Head>: spp, coord_conv
```

**Comment by qingqing01** [comment]
@yeyupiaoling 给下启动的命令吧，以及你PaddleDetection是那个版本？

**Comment by yeyupiaoling** [comment]
@qingqing01 

PaddleDetection 版本release 0.4
```
python train.py -c configs/ppyolo.yml
```

**Comment by qingqing01** [comment]
@yeyupiaoling  https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/ppdet/modeling/anchor_heads/yolo_head.py#L69


你源码和这块不一样，需要更新下代码。

**Comment by yeyupiaoling** [comment]
@qingqing01 谢谢，重新clone，正常了。执行`git pull`明明显示已经是最新的了，佛了。
