### ISSUE TITLE
use_fine_grained_loss

### ISSUE THREAD

**Issue by zxz-cc** [PaddlePaddle/PaddleDetection#1249]
2020-08-19 09:48:32,293-WARNING: fail to map op [Gt2YoloTarget_709595] with error: index 33212 is out of bounds for axis 2 with size 19 and stack:
Traceback (most recent call last):
  File "/mnt/chenru/PaddleDetection/ppdet/data/reader.py", line 46, in __call__
    data = f(data, ctx)
  File "/mnt/chenru/PaddleDetection/ppdet/data/transform/batch_operators.py", line 259, in __call__
    target[best_n, 0, gj, gi] = gx * grid_w - gi
IndexError: index 33212 is out of bounds for axis 2 with size 19
anyone can help me?

**Comment by willthefrog** [comment]
please make sure `NormalizeBox` is in `sample_transforms` and that the dataset does not contain invalid bbox (e.g., with dims going outside the image boundaries)

**Comment by heavengate** [comment]
你有修改reader里面预处理的transform么，是否是在`Gt2YoloTarget`之前没有做`NormalizeBox`
