### ISSUE TITLE
InvalidArgumentError: Broadcast dimension mismatch

### ISSUE THREAD

**Issue by shuxsu** [PaddlePaddle/PaddleDetection#1305]
错误信息：Error Message Summary:
----------------------
InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [-1, 256, 100, 167] and the shape of Y = [-1, 256, 100, 168]. Received [167] in X is not equal to [168] in Y at i:3.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] at (/paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:160)
  [operator < elementwise_add > error]

**Comment by heavengate** [comment]
请问用的是哪个模型呢，看报错像是这个模型要求输入是长宽是32的整数倍，因为backbone会做32倍降采样，head会做升采样，不能整除的话升采样回来shape会有diff

**Comment by shuxsu** [comment]
> 请问用的是哪个模型呢，看报错像是这个模型要求输入是长宽是32的整数倍，因为backbone会做32倍降采样，head会做升采样，不能整除的话升采样回来shape会有diff

模型是mask rcnn
数据集是cityscape转coco

**Comment by qingqing01** [comment]
@shuxsu  如果是MaskRCNN+FPN模型的话，注意预处理配置需包含:

https://github.com/PaddlePaddle/PaddleDetection/blob/bc453fb20086b9466fa052fe08e67b5b7b1fee4a/configs/mask_fpn_reader.yml#L28-L32

注意config别选错了

**Comment by LongXuYu** [comment]
Traceback (most recent call last): 
  File ".\tools\train.py", line 209, in <module> 
    main()
  File ".\tools\train.py", line 205, in main
    run(FLAGS, cfg)
  File ".\tools\train.py", line 158, in run
    trainer.train(FLAGS.eval)
  File "I:\PaddleDetection\ppdet\engine\trainer.py", line 639, in train
    self._eval_with_loader(self._eval_loader)
  File "I:\PaddleDetection\ppdet\engine\trainer.py", line 672, in _eval_with_loader
    outs = self.model(data)
  File "C:\Users\yuxulong\.conda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "I:\PaddleDetection\ppdet\modeling\architectures\meta_arch.py", line 76, in forward
    outs.append(self.get_pred())
  File "I:\PaddleDetection\ppdet\modeling\architectures\detr.py", line 118, in get_pred
    return self._forward()
  File "I:\PaddleDetection\ppdet\modeling\architectures\detr.py", line 85, in _forward
    body_feats = self.neck(body_feats)
  File "C:\Users\yuxulong\.conda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "I:\PaddleDetection\ppdet\modeling\transformers\hybrid_encoder.py", line 256, in forward
    memory = self.encoder[i](src_flatten, pos_embed=pos_embed)
  File "C:\Users\yuxulong\.conda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "I:\PaddleDetection\ppdet\modeling\transformers\detr_transformer.py", line 102, in forward
    output = layer(output, src_mask=src_mask, pos_embed=pos_embed)
  File "C:\Users\yuxulong\.conda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "I:\PaddleDetection\ppdet\modeling\transformers\hybrid_encoder.py", line 110, in forward
    q = k = self.with_pos_embed(src, pos_embed)
  File "I:\PaddleDetection\ppdet\modeling\transformers\hybrid_encoder.py", line 104, in with_pos_embed
    return tensor if pos_embed is None else tensor + pos_embed
  File "C:\Users\yuxulong\.conda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\math_op_patch.py", line 304, in __impl__
    return math_op(self, other_var, -1)
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [4, 169, 256] and the shape of Y = [1, 400, 256]. Received [169] in X is not equal to [400] in Y at i:1.     
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at ..\paddl
e/phi/kernels/funcs/common_shape.h:84)
保存权重的时候报错，训练命令
python .\tools\train.py -c .\configs\rtdetr\rtdetr_hgnetv2_l_6x_coco.yml --eval --use_vdl=true
