### ISSUE TITLE
Yml File Issue

### ISSUE THREAD

**Issue by singlautsav** [PaddlePaddle/PaddleDetection#1326]
Command used to train the dataset, the dataset is in coco format
`python -u tools/train.py -c configs/faster_rcnn_r50_1x.yml -o pretrain_weights=https://paddlemodels.bj.bcebos.com/object_detection/faster_rcnn_r50_1x.tar`

Error I have currently

`Traceback (most recent call last):
  File "tools/train.py", line 370, in <module>
    main()
  File "tools/train.py", line 69, in main
    cfg = load_config(FLAGS.config)
  File "D:\gith\PaddleDetection\ppdet\core\workspace.py", line 86, in load_config
    cfg = merge_config(yaml.load(f, Loader=yaml.Loader), cfg)
  File "C:\Users\Utsav Singla\AppData\Local\Programs\Python\Python37\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Users\Utsav Singla\AppData\Local\Programs\Python\Python37\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\Utsav Singla\AppData\Local\Programs\Python\Python37\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\Utsav Singla\AppData\Local\Programs\Python\Python37\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\Utsav Singla\AppData\Local\Programs\Python\Python37\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\Utsav Singla\AppData\Local\Programs\Python\Python37\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node       
    while not self.check_event(MappingEndEvent):
  File "C:\Users\Utsav Singla\AppData\Local\Programs\Python\Python37\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\Utsav Singla\AppData\Local\Programs\Python\Python37\lib\site-packages\yaml\parser.py", line 439, in parse_block_mapping_key      
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block mapping
  in "configs/faster_rcnn_r50_1x.yml", line 1, column 1
expected <block end>, but found '<block mapping start>'
  in "configs/faster_rcnn_r50_1x.yml", line 94, column 3`

My YML file is 

`architecture: FasterRCNN
use_gpu: False
max_iters: 180000
log_smooth_window: 20
save_dir: output
snapshot_iter: 10000
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_cos_pretrained.tar
metric: COCO
weights: output/faster_rcnn_r50_1x/model_final
num_classes: 81

FasterRCNN:
  backbone: ResNet
  rpn_head: RPNHead
  roi_extractor: RoIAlign
  bbox_head: BBoxHead
  bbox_assigner: BBoxAssigner

ResNet:
  norm_type: affine_channel
  depth: 50
  feature_maps: 4
  freeze_at: 2

ResNetC5:
  depth: 50
  norm_type: affine_channel

RPNHead:
  anchor_generator:
    anchor_sizes: [32, 64, 128, 256, 512]
    aspect_ratios: [0.5, 1.0, 2.0]
    stride: [16.0, 16.0]
    variance: [1.0, 1.0, 1.0, 1.0]
  rpn_target_assign:
    rpn_batch_size_per_im: 256
    rpn_fg_fraction: 0.5
    rpn_negative_overlap: 0.3
    rpn_positive_overlap: 0.7
    rpn_straddle_thresh: 0.0
    use_random: true
  train_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 12000
    post_nms_top_n: 2000
  test_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 6000
    post_nms_top_n: 1000

RoIAlign:
  resolution: 14
  sampling_ratio: 0
  spatial_scale: 0.0625

BBoxAssigner:
  batch_size_per_im: 512
  bbox_reg_weights: [0.1, 0.1, 0.2, 0.2]
  bg_thresh_hi: 0.5
  bg_thresh_lo: 0.0
  fg_fraction: 0.25
  fg_thresh: 0.5

BBoxHead:
  head: ResNetC5
  nms:
    keep_top_k: 100
    nms_threshold: 0.5
    score_threshold: 0.05

LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [120000, 160000]
  - !LinearWarmup
    start_factor: 0.3333333333333333
    steps: 500

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2

_READER_: 'faster_reader.yml'
TrainReader:
    fields: ['image', 'gt_bbox', 'gt_class', 'gt_score']
  dataset:
    !COCODataSet
      dataset_dir: dataset/coco/cocoDataset
      anno_path: annotations/instances_train2017.json
      image_dir: train2017
      with_background: false

EvalReader:
  inputs_def:
    fields: ['image', 'gt_bbox', 'gt_class', 'gt_score']
    # num_max_boxes: 50
  dataset:
    !COCODataSet
      dataset_dir: dataset/coco/cocoDataset
      anno_path: annotations/instances_val2017.json
      image_dir: val2017
      use_default_label: true
      with_background: false`

Some modifications made in code, because this line was throwing errors earlier
    `with open(file_path, errors='ignore') as f:`

Update:
a. Deleted the duplicate yml

**Comment by jerrywgz** [comment]
I found that you need to add input_def before fields in TrainReader, and If you trained dataset in coco format, no need for input_def and just update the correct data path in COCODataSet.

BTW, it seems that you paste duplicated yml in the issue.

**Comment by singlautsav** [comment]
Thank you @jerrywgz but since you mentioned I dont need the input_def in the yml because of coco dataset, I am still struggling with the issue, the path is correct. Also sorry for duplicate I have corrected it

**Comment by jerrywgz** [comment]
![image](https://user-images.githubusercontent.com/22989727/91818148-10278200-ec68-11ea-9c80-124ef5da32e9.png)
I guess you miss input_def here. The configure in evalreader is correct

**Comment by singlautsav** [comment]
@jerrywgz can you redirect me to some config file where I can get the sense of what I am missing, I followed the Transfer learning documentation and I found this. Also the YAML error is also in the line 1,

`configs/faster_rcnn_r50_1x.yml", line 1, column 1 expected <block end>, but found '<block mapping start>' in "configs/faster_rcnn_r50_1x.yml", line 94, column 3`

**Comment by jerrywgz** [comment]
The error message means the format in yaml is incorrect. Could you please upload your config file? 
You could also refer to the config file here https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/configs/faster_rcnn_r50_1x.yml, and the corresponding reader config is https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/configs/faster_reader.yml

**Comment by singlautsav** [comment]
I have used the two links only, you can find the yml https://easyupload.io/q5vmt2

**Comment by jerrywgz** [comment]
Just like I said, the trainreader missed inputs_def here:
![image](https://user-images.githubusercontent.com/22989727/92191927-7cd49380-ee97-11ea-947d-301a578d900c.png)

The correct config for reader is as follows:
![image](https://user-images.githubusercontent.com/22989727/92192013-ad1c3200-ee97-11ea-9383-7bf98896b080.png)

**Comment by singlautsav** [comment]
@jerrywgz Thanks, the issue has been resolved, but now I have another error related to yml

`{'dataset_dir': 'dataset/coco/cocoDataset', 'anno_path': 'annotations/instances_train2017.json', 'image_dir': 'train2017', 'with_background': False}
{'dataset_dir': 'dataset/coco/cocoDataset', 'anno_path': 'annotations/instances_val2017.json', 'image_dir': 'val2017', 'use_default_label': True, 'with_background': False}
Error when construct COCODataSet instance from yaml config
Traceback (most recent call last):
  File "tools/train.py", line 370, in <module>
    main()
  File "tools/train.py", line 69, in main
    cfg = load_config(FLAGS.config)
  File "D:\gith\PaddleDetection\ppdet\core\workspace.py", line 86, in load_config
    cfg = merge_config(yaml.load(f, Loader=yaml.Loader), cfg)
  File "C:\Users\Utsav Singla\AppData\Local\Programs\Python\Python37\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Users\Utsav Singla\AppData\Local\Programs\Python\Python37\lib\site-packages\yaml\constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "C:\Users\Utsav Singla\AppData\Local\Programs\Python\Python37\lib\site-packages\yaml\constructor.py", line 60, in construct_document
    for dummy in generator:
  File "C:\Users\Utsav Singla\AppData\Local\Programs\Python\Python37\lib\site-packages\yaml\constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
  File "C:\Users\Utsav Singla\AppData\Local\Programs\Python\Python37\lib\site-packages\yaml\constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "C:\Users\Utsav Singla\AppData\Local\Programs\Python\Python37\lib\site-packages\yaml\constructor.py", line 143, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "C:\Users\Utsav Singla\AppData\Local\Programs\Python\Python37\lib\site-packages\yaml\constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "D:\gith\PaddleDetection\ppdet\core\config\yaml_helpers.py", line 46, in python_constructor    raise ex
  File "D:\gith\PaddleDetection\ppdet\core\config\yaml_helpers.py", line 42, in python_constructor    return cls(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'use_default_label'`
