### ISSUE TITLE
training error 

### ISSUE THREAD

**Issue by toplinuxsir** [PaddlePaddle/PaddleDetection#1337]
Traing with eval 
error : 
```  
File "/data/trainings/paddle_detection/PaddleDetection/ppdet/data/reader.py", line 445, in _reader
    reader.reset()
  File "/data/trainings/paddle_detection/PaddleDetection/ppdet/data/parallel_map.py", line 267, in reset
    assert self._consumer_healthy(), "cannot start another pass of data" \
AssertionError: cannot start another pass of data for some consumers exited abnormally before!!!
```

**Comment by willthefrog** [comment]
应该是预处理步骤报错了，是原始的设置和数据集吗？

**Comment by toplinuxsir** [comment]
@willthefrog 
不是，自己标注的VOC 数据集， test.txt 可以和 trainval.txt 一样，也就是eval 的数据集和训练的数据集一样，有问题吗？

**Comment by willthefrog** [comment]
应该是数据预处理出错了，报错信息只有这些吗？ 配置修改了哪些？

**Comment by toplinuxsir** [comment]
--eval 参数，需要设置 EvalReader 还是 TestReader ？

**Comment by willthefrog** [comment]
eval reader的`fields`里没有对应的label啊。

**Comment by toplinuxsir** [comment]
@willthefrog 
1.  需要那些label ？
use_default_label:false
默认label_list.txt 这个文件是存在的，已经建立好了

2. 没有启用 --eval 昨天训练了iter :15000, 实际output 下面只有以下三个文件：
```
10000.pdmodel  10000.pdopt  10000.pdparams
``` 
 训练自动保存best 那个吗？ 还是每10000 iter 保存一次？ 这个如何设置？

谢谢！

**Comment by willthefrog** [comment]
1. voc的配置和coco是不一样的，可以参考[这里](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/configs/yolov3_r34_voc.yml#L79)

2.  设置`snapshot_iter`参数。

**Comment by toplinuxsir** [comment]
@willthefrog  谢谢！

**Comment by toplinuxsir** [comment]
@willthefrog 
我设置的EvalReader 明明是 VOC ， 为什么load时候是COCO ？ 
```
2020-09-02 14:32:11,593-INFO: Total number of images: 121, inference time: 29.546101417996436 fps.                                                                                     
loading annotations into memory...                                                                                                                                                     
Traceback (most recent call last):                                                         
  File "tools/train.py", line 370, in <module>                                                                                                                                         
    main()                                                                                 
  File "tools/train.py", line 292, in main                                                 
    cfg['EvalReader']['dataset'])                                                          
  File "/data/trainings/paddle_detection/PaddleDetection/ppdet/utils/eval_utils.py", line 220, in eval_results
    save_only=save_only)                                                                   
  File "/data/trainings/paddle_detection/PaddleDetection/ppdet/utils/coco_eval.py", line 77, in bbox_eval
    coco_gt = COCO(anno_file)                                                              
  File "/home/lhs/python-envs/devpy37/lib/python3.7/site-packages/pycocotools-2.0-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 84, in __init__
    dataset = json.load(open(annotation_file, 'r'))                                                                                                                                    
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load                                                                                                                        
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)                                                                                                          
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads                                                                                                                       
    return _default_decoder.decode(s)                                                      
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode                                                                                                                       
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                                                                                                  
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode                                                                                                                   
    raise JSONDecodeError("Expecting value", s, err.value) from None                                                                                                                   
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)   
```

**Comment by willthefrog** [comment]
需要修改`metric`设置

**Comment by toplinuxsir** [comment]
@willthefrog 
metrics 改成VOC ，仍然是同样的错误

**Comment by willthefrog** [comment]
能否发下完整配置？

**Comment by toplinuxsir** [comment]
@willthefrog

**Comment by willthefrog** [comment]
是怎么运行的呢？

**Comment by toplinuxsir** [comment]
@willthefrog 
```
python tools/train.py -c ./configs/ppyolo/xt/ppyolo.yml   --eval --use_vdl=True --vdl_log_dir=vdl_fruit_dir/scalar_xt
```

**Comment by willthefrog** [comment]
> @willthefrog
> metrics 改成VOC ，仍然是同样的错误

“同样的错误” 是指 load 了 COCO ？

**Comment by toplinuxsir** [comment]
@willthefrog 
这个错误：
```
2020-09-02 16:20:21,166-WARNING: consumer[8977] exit abnormally with exitcode[-9]
2020-09-02 16:20:21,198-WARNING: 1 consumers have exited abnormally!!!
2020-09-02 16:20:21,199-WARNING: consumer[8977] exit abnormally with exitcode[-9]
2020-09-02 16:20:21,200-WARNING: 1 consumers have exited abnormally!!!
2020-09-02 16:20:21,223-WARNING: Your reader has raised an exception!
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lhs/python-envs/devpy37/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1145, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/home/lhs/python-envs/devpy37/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/lhs/python-envs/devpy37/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1125, in __thread_main__
    for tensors in self._tensor_reader():
  File "/home/lhs/python-envs/devpy37/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1195, in __tensor_reader_impl__
    for slots in paddle_reader():
  File "/home/lhs/python-envs/devpy37/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 506, in __reader_creator__
    for item in reader():
  File "/data/trainings/paddle_detection/PaddleDetection/ppdet/data/reader.py", line 445, in _reader
    reader.reset()
  File "/data/trainings/paddle_detection/PaddleDetection/ppdet/data/parallel_map.py", line 267, in reset
    assert self._consumer_healthy(), "cannot start another pass of data" \
AssertionError: cannot start another pass of data for some consumers exited abnormally before!!!

/home/lhs/python-envs/devpy37/lib/python3.7/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tools/train.py", line 370, in <module>
    main()
  File "tools/train.py", line 243, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "/home/lhs/python-envs/devpy37/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/home/lhs/python-envs/devpy37/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/lhs/python-envs/devpy37/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/home/lhs/python-envs/devpy37/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1167, in _run_impl
    return_merged=return_merged)
  File "/home/lhs/python-envs/devpy37/lib/python3.7/site-packages/paddle/fluid/executor.py", line 879, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/lhs/python-envs/devpy37/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/lhs/python-envs/devpy37/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1080, in _init_non_iterable
    attrs={'drop_last': self._drop_last})
  File "/home/lhs/python-envs/devpy37/lib/python3.7/site-packages/paddle/fluid/reader.py", line 978, in __init__
    self._init_non_iterable()
  File "/home/lhs/python-envs/devpy37/lib/python3.7/site-packages/paddle/fluid/reader.py", line 620, in from_generator
    iterable, return_list, drop_last)
  File "/data/trainings/paddle_detection/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 155, in build_inputs
    iterable=iterable) if use_dataloader else None
  File "tools/train.py", line 115, in main
    feed_vars, train_loader = model.build_inputs(**inputs_def)
  File "tools/train.py", line 370, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]
```

**Comment by willthefrog** [comment]
可以参考看下 #1307

另外，如果图片很大， 可以试着调小 `worker_num` `bufsize`，不然会占用大量内存造成OOM

**Comment by toplinuxsir** [comment]
@willthefrog 
图片来自2000W 像素的相机，6M 左右，另外 关于ppyolo.yml 里面各参数的介绍说明，有没有文档？ 谢谢了

**Comment by willthefrog** [comment]
在 `ppyolo_reader_xt.yml`里。

目前没有，可以先参考[RCNN的配置文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/advanced_tutorials/config_doc/RCNN_PARAMS_DOC.md)

**Comment by toplinuxsir** [comment]
@willthefrog 
worker_num from 8 to 4
bufsize from 4 to 2

貌似正常工作了，Titan RTX ， 32G Mem ， 8Core CPU 但是训练速度非常慢。
