### ISSUE TITLE
训练ppyolo换了台电脑就报以下错了

### ISSUE THREAD

**Issue by 17695996717** [PaddlePaddle/PaddleDetection#1344]
大佬请问这是什么情况呢？

C:\apps\envs\ppdet\lib\site-packages\paddle\fluid\executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "D:/data/PPdet/PaddleDetection-release-0.4/tools/train.py", line 372, in <module>
    main()
  File "D:/data/PPdet/PaddleDetection-release-0.4/tools/train.py", line 244, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "C:\apps\envs\ppdet\lib\site-packages\paddle\fluid\executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "C:\apps\envs\ppdet\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\apps\envs\ppdet\lib\site-packages\paddle\fluid\executor.py", line 1066, in run
    return_merged=return_merged)
  File "C:\apps\envs\ppdet\lib\site-packages\paddle\fluid\executor.py", line 1156, in _run_impl
    program._compile(scope, self.place)
  File "C:\apps\envs\ppdet\lib\site-packages\paddle\fluid\compiler.py", line 443, in _compile
    places=self._places)
  File "C:\apps\envs\ppdet\lib\site-packages\paddle\fluid\compiler.py", line 396, in _compile_data_parallel
    self._exec_strategy, self._build_strategy, self._graph)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
UnavailableError: Windows can support Single GPU only.
  [Hint: Expected places.size() == 1, but received places.size():4 != 1:1.] at (D:\1.8.4\paddle\paddle\fluid\framework\parallel_executor.cc:469)

W0903 09:03:44.115615 23244 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 11.0, Runtime API Version: 10.0
W0903 09:03:44.177574 23244 device_context.cc:260] device: 0, cuDNN Version: 7.6.

**Comment by still-wait** [comment]
@17695996717 在windows环境下，paddle暂不支持多卡训练，可以试下单卡训练。

**Comment by 17695996717** [comment]
> @17695996717 在windows环境下，paddle暂不支持多卡训练，可以试下单卡训练。

谢谢解决了
