### ISSUE TITLE
Failed to map with error:[target0 not in samples]]

### ISSUE THREAD

**Issue by aboutmei** [PaddlePaddle/PaddleDetection#1365]
architecture: YOLOv3
use_gpu: true
max_iters: 70000
log_smooth_window: 20
save_dir: output
snapshot_iter: 2000
metric: VOC
map_type: 11point
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/DarkNet53_pretrained.tar
weights: output/yolov3_darknet_voc/model_final
num_classes: 20
use_fine_grained_loss: true

YOLOv3:
  backbone: DarkNet
  yolo_head: YOLOv3Head

DarkNet:
  norm_type: sync_bn
  norm_decay: 0.
  depth: 53

YOLOv3Head:
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  anchors: [[10, 13], [16, 30], [33, 23],
            [30, 61], [62, 45], [59, 119],
            [116, 90], [156, 198], [373, 326]]
  norm_decay: 0.
  yolo_loss: YOLOv3Loss
  nms:
    background_label: -1
    keep_top_k: 100
    nms_threshold: 0.45
    nms_top_k: 1000
    normalized: false
    score_threshold: 0.01

YOLOv3Loss:
  batch_size: 8
  ignore_thresh: 0.7
  label_smooth: false
  iou_loss: DiouLossYolo

DiouLossYolo:
  loss_weight: 5

LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 55000
    - 62000
  - !LinearWarmup
    start_factor: 0.
    steps: 1000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

_READER_: 'yolov3_reader.yml'
TrainReader:
  inputs_def:
    fields: ['image', 'gt_bbox', 'gt_class', 'gt_score']
    num_max_boxes: 50
  dataset:
    !VOCDataSet
    dataset_dir: dataset/voc
    anno_path: trainval.txt
    use_default_label: true
    with_background: false

EvalReader:
  inputs_def:
    fields: ['image', 'im_size', 'im_id', 'gt_bbox', 'gt_class', 'is_difficult']
    num_max_boxes: 50
  dataset:
    !VOCDataSet
    dataset_dir: dataset/voc
    anno_path: test.txt
    use_default_label: true
    with_background: false

TestReader:
  dataset:
    !ImageFolder
    use_default_label: true
    with_background: false

recv endsignal from outq with errmsg[consumer[consumer-0d6-3] failed to map with error:[target0 not in samples]]
请问这是什么原因导致的，怎么解决？

**Comment by qingqing01** [comment]
@justinmeibi 

> READER: 'yolov3_reader.yml'
TrainReader:
inputs_def:
fields: ['image', 'gt_bbox', 'gt_class', 'gt_score']
num_max_boxes: 50
dataset:
!VOCDataSet
dataset_dir: dataset/voc
anno_path: trainval.txt
use_default_label: true
with_background: false

这里复用了`yolov3_reader.yml`，参考 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/configs/dcn/yolov3_enhance_reader.yml#L5 

这个将`yolov3_reader.yml`中增加如下设置:

```
use_fine_grained_loss: true
```

**Comment by gaofssvm** [comment]
设置如下：

```
######################
architecture: YOLOv3
use_gpu: true
max_iters: 85000
log_smooth_window: 20
save_dir: output
snapshot_iter: 10000
metric: VOC
pretrain_weights: https://paddlemodels.bj.bcebos.com/object_detection/ResNet50_vd_dcn_db_obj365_pretrained.tar
weights: output/yolov3_r50vd_dcn_db_obj365_pretrained_coco/model_final
finetune_exclude_pretrained_params: ['yolo_output']   #预训练时，加载权重时，忽略的字段，这表示输出层的参数不进行加载
num_classes: 7
use_fine_grained_loss: true

YOLOv3:
  backbone: ResNet
  yolo_head: YOLOv3Head
  use_fine_grained_loss: true

ResNet:
  norm_type: sync_bn
  freeze_at: 0
  freeze_norm: false
  norm_decay: 0.
  depth: 50
  feature_maps: [3, 4, 5]
  variant: d
  dcn_v2_stages: [5]

YOLOv3Head:
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  anchors: [[10, 13], [16, 30], [33, 23],
            [30, 61], [62, 45], [59, 119],
            [116, 90], [156, 198], [373, 326]]
  norm_decay: 0.
  yolo_loss: YOLOv3Loss
  nms:
    background_label: -1
    keep_top_k: 100
    nms_threshold: 0.45
    nms_top_k: 1000
    normalized: false
    score_threshold: 0.01

YOLOv3Loss:
  ignore_thresh: 0.7
  label_smooth: false
  use_fine_grained_loss: true

LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 55000
    - 75000
  - !LinearWarmup
    start_factor: 0.
    steps: 4000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

_READER_: 'yolov3_enhance_reader.yml'
TrainReader:
  inputs_def:
    image_shape: [3, 608, 608]
    fields: ['image', 'gt_bbox', 'gt_class', 'gt_score']
    num_max_boxes: 50
  dataset:
    !VOCDataSet
    dataset_dir: dataset/voc
    anno_path: trainval.txt
    with_background: false
    use_default_label: false
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !NormalizeBox {}
  - !ExpandImage
    max_ratio: 4.0
    mean: [123.675, 116.28, 103.53]
    prob: 0.5
  - !RandomInterpImage
    max_size: 0
    target_size: 608
  - !RandomFlipImage
    is_normalized: true
    prob: 0.5
  - !NormalizeImage
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    is_scale: true
    is_channel_first: false
  - !PadBox
    num_max_boxes: 50
  - !BboxXYXY2XYWH {}
  batch_transforms:
  - !RandomShape
    sizes: [608]
  - !Permute
    channel_first: true
    to_bgr: false
  batch_size: 4
  shuffle: true
  mixup_epoch: -1

EvalReader:
  batch_size: 4
  inputs_def:
    image_shape: [3, 608, 608]
    fields: ['image', 'im_size', 'im_id', 'gt_bbox', 'gt_class', 'is_difficult']
    num_max_boxes: 50
  dataset:
    !VOCDataSet
    dataset_dir: dataset/voc
    anno_path: test.txt
    use_default_label: false
    with_background: false

TestReader:
  batch_size: 1
  dataset:
    !ImageFolder
    anno_path: dataset/voc//VOCdevkit/VOC2007/label_list.txt
    use_default_label: false
    with_background: false
```
######################################

还是出现：

```
Traceback (most recent call last):
  File "/home/zrway/miniconda3/envs/paddle/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/zrway/miniconda3/envs/paddle/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zrway/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1145, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/home/zrway/miniconda3/envs/paddle/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/zrway/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1125, in __thread_main__
    for tensors in self._tensor_reader():
  File "/home/zrway/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1195, in __tensor_reader_impl__
    for slots in paddle_reader():
  File "/home/zrway/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 506, in __reader_creator__
    for item in reader():
  File "/home/zrway/zrway/GFS/paddleobjection/PaddleDetection/ppdet/data/reader.py", line 449, in _reader
    for _batch in reader:
  File "/home/zrway/zrway/GFS/paddleobjection/PaddleDetection/ppdet/data/reader.py", line 318, in __next__
    return self.next()
  File "/home/zrway/zrway/GFS/paddleobjection/PaddleDetection/ppdet/data/reader.py", line 332, in next
    return self.worker(self._drop_empty, batch)
  File "/home/zrway/zrway/GFS/paddleobjection/PaddleDetection/ppdet/data/reader.py", line 399, in worker
    batch = batch_arrange(batch, self._fields)
  File "/home/zrway/zrway/GFS/paddleobjection/PaddleDetection/ppdet/data/reader.py", line 150, in batch_arrange
    assert field in samples, '{} not in samples'.format(field)
AssertionError: target0 not in samples

Traceback (most recent call last):
  File "tools/train.py", line 375, in <module>
    main()
  File "tools/train.py", line 248, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "/home/zrway/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/home/zrway/miniconda3/envs/paddle/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/zrway/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/home/zrway/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1167, in _run_impl
    return_merged=return_merged)
  File "/home/zrway/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/executor.py", line 879, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

 File "/home/zrway/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/zrway/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1080, in _init_non_iterable
    attrs={'drop_last': self._drop_last})
  File "/home/zrway/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/reader.py", line 978, in __init__
    self._init_non_iterable()
  File "/home/zrway/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/reader.py", line 620, in from_generator
    iterable, return_list, drop_last)
  File "/home/zrway/zrway/GFS/paddleobjection/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 155, in build_inputs
    iterable=iterable) if use_dataloader else None
  File "tools/train.py", line 117, in main
    feed_vars, train_loader = model.build_inputs(**inputs_def)
  File "tools/train.py", line 375, in <module>
    main()

Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]
```

#####################################

出错位置：
     -》tool/train.py 中，117行：feed_vars, train_loader = model.build_inputs(**inputs_def) 

---》PaddleDetection/ppdet/modeling/architectures/yolo.py  中的build_inputs（）函数中，target0和target1，target2属于yolov3输出层的特征图个数，然而在PaddleDetection/ppdet/data/reader.py中，batch_arrange(batch_samples, fields)函数里面要去asser field中是否有target0、target1、target2.

#########################################


另外：采用自己的数据集来进行训练模型，自己数据集的标签label_list.txt是在哪个位置读取的？

############################################

最后，谢谢百度paddle的工程师

**Comment by qingqing01** [comment]
@aboutmei 不知道问题是否已经解决，觉得还是数据格式那里不太对，如果还有问题，可以开新的issue
