### ISSUE TITLE
AssertionError: Please specify --config=configure_file_path.

### ISSUE THREAD

**Issue by shuxsu** [PaddlePaddle/PaddleDetection#1370]
https://github.com/PaddlePaddle/PaddleDetection/blob/c764ccdb4f66a203b6bb5804468da78b574af9b2/ppdet/utils/cli.py#L57

在服务器端使用nohup python3 train.py& -c=/home/shujisheng/download/PaddleDetection/configs/mask_rcnn_r101_fpn_1x.yml --eval

不适用nohup运行没发现此错误信息

报错信息：
`2020-09-07 16:00:17,642-INFO: iter: 20, lr: 0.003600, 'loss_cls': '0.707638', 'loss_bbox': '0.392558', 'loss_rpn_cls': '0.161033', 'loss_rpn_bbox': '0.223415', 'loss_mask': '0.660756', 'loss': '2.119743', time: 2.074, eta: 2 days, 3:50:38
Traceback (most recent call last):
  File "train.py", line 369, in <module>
    FLAGS = parser.parse_args()
  File "/home/shujisheng/download/PaddleDetection/ppdet/utils/cli.py", line 57, in parse_args
    "Please specify --config=configure_file_path."
AssertionError: Please specify --config=configure_file_path.
Traceback (most recent call last):
  File "train.py", line 369, in <module>
    FLAGS = parser.parse_args()
  File "/home/shujisheng/download/PaddleDetection/ppdet/utils/cli.py", line 57, in parse_args
    "Please specify --config=configure_file_path."
AssertionError: Please specify --config=configure_file_path.
Traceback (most recent call last):
  File "train.py", line 369, in <module>
    FLAGS = parser.parse_args()
  File "/home/shujisheng/download/PaddleDetection/ppdet/utils/cli.py", line 57, in parse_args
    "Please specify --config=configure_file_path."
AssertionError: Please specify --config=configure_file_path.
Traceback (most recent call last):
  File "train.py", line 369, in <module>
    FLAGS = parser.parse_args()
  File "/home/shujisheng/download/PaddleDetection/ppdet/utils/cli.py", line 57, in parse_args
    "Please specify --config=configure_file_path."
AssertionError: Please specify --config=configure_file_path.`

**Comment by William9Baker** [comment]
请问如何解决呀？
