### ISSUE TITLE
训练是加eval报找不到数据错误

### ISSUE THREAD

**Issue by xiaomujiang** [PaddlePaddle/PaddleDetection#1388]
环境 paddlepaddle-gpu       1.8.1.post107

自己定义的数据集后，进行训练，加入eval报错
（1）使用python tools/train.py -c yolov3_dog_voc.yml 进行训练，显示正常
2020-09-10 19:28:02,672-INFO: iter: 0, lr: 0.000000, 'loss': '17924.841797', time: 0.000, eta: 0:00:05
使用
（2）python tools/train.py -c yolov3_dog_voc.yml --eval  加入eval参数后就会报错？？？
2020-09-10 19:24:09,794-INFO: Dataset /hadoop/disk01/PaddleDetectionstart/dataset/dog is not valid for reason above, try searching /root/.cache/paddle/dataset or downloading dataset...
Traceback (most recent call last):
  File "tools/train.py", line 368, in <module>
    main()
  File "tools/train.py", line 145, in main
    eval_reader = create_reader(cfg.EvalReader, devices_num=1)
  File "/hadoop/disk01/PaddleDetectionstart/ppdet/data/reader.py", line 410, in create_reader
    reader = Reader(**cfg)()
  File "/hadoop/disk01/PaddleDetectionstart/ppdet/data/reader.py", line 204, in __init__
    self._roidbs = self._dataset.get_roidb()
  File "/hadoop/disk01/PaddleDetectionstart/ppdet/data/source/dataset.py", line 65, in get_roidb
    self.image_dir)
  File "/hadoop/disk01/PaddleDetectionstart/ppdet/utils/download.py", line 145, in get_dataset_path
    format(path, osp.split(path)[-1]))
ValueError: Dataset dataset/dog is not valid and cannot parse dataset type 'dog' for automaticly downloading, which only supports 'voc' , 'coco', 'wider_face' and 'fruit' currently

**Comment by still-wait** [comment]
@xiaomujiang `/hadoop/disk01/PaddleDetectionstart/dataset/dog`是数据集路径吗？在EvalReader中请设置正确的`dataset_dir`路径，报错原因是无法找到数据集正确路径，
