### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 41: illegal multibyte sequence

### ISSUE THREAD

**Issue by youyouf** [PaddlePaddle/PaddleDetection#1470]
(paddlepaddle) C:\Users\1\Desktop\PaddleDetection-release-0.4>python tools/train.py -c configs/yolov3_mobilenet_v1_roadsign.yml --eval -o use_gpu=true
Traceback (most recent call last):
  File "tools/train.py", line 372, in <module>
    main()
  File "tools/train.py", line 70, in main
    cfg = load_config(FLAGS.config)
  File "C:\Users\1\Desktop\PaddleDetection-release-0.4\ppdet\core\workspace.py", line 86, in load_config
    cfg = merge_config(yaml.load(f, Loader=yaml.Loader), cfg)
  File "C:\software\Anaconda3\envs\paddlepaddle\lib\site-packages\yaml\__init__.py", line 112, in load
    loader = Loader(stream)
  File "C:\software\Anaconda3\envs\paddlepaddle\lib\site-packages\yaml\loader.py", line 44, in __init__
    Reader.__init__(self, stream)
  File "C:\software\Anaconda3\envs\paddlepaddle\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\software\Anaconda3\envs\paddlepaddle\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "C:\software\Anaconda3\envs\paddlepaddle\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 41: illegal multibyte sequence

**Comment by still-wait** [comment]
@youyouf 这个报错表示在你的`configs/yolov3_mobilenet_v1_roadsign.yml`中第41行有中文字符，请去掉或注释掉中文字符重新尝试。

**Comment by qingqing01** [comment]
@youyouf 

https://github.com/PaddlePaddle/PaddleDetection/blob/66d2e7270351226387638d7c6b682774d680fe90/ppdet/core/workspace.py#L85

这行代码改成下面试下呢？

```
with open(file_path,  'r', encoding='UTF-8') as f:
```

**Comment by youyouf** [comment]
> 
> 
> @youyouf 这个报错表示在你的`configs/yolov3_mobilenet_v1_roadsign.yml`中第41行有中文字符，请去掉或注释掉中文字符重新尝试。
好像没有中文字符

**Comment by youyouf** [comment]
> @youyouf这个报错表示在你的`configs/yolov3_mobilenet_v1_roadsign.yml`中第41行有中文字符，请去掉或注释掉中文字符重新尝试。

好像没有这个问题

**Comment by youyouf** [comment]
> 
> 
> @youyouf
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/66d2e7270351226387638d7c6b682774d680fe90/ppdet/core/workspace.py#L85
> 
> 这行代码改成下面试下呢？
> 
> ```
> with open(file_path,  'r', encoding='UTF-8') as f:
> ```

根据您的建议，修改了，这个问题成功解决，同时遇到了新的问题了。
 C:\Users\1\Desktop\PaddleDetection-release-0.4>python tools/train.py -c configs/yolov3_mobilenet_v1_roadsign.yml --eval -o use_gpu=true
Traceback (most recent call last):
  File "tools/train.py", line 372, in <module>
    main()
  File "tools/train.py", line 107, in main
    model = create(main_arch)
  File "C:\Users\1\Desktop\PaddleDetection-release-0.4\ppdet\core\workspace.py", line 259, in create
    kwargs[k] = create(target_key)
  File "C:\Users\1\Desktop\PaddleDetection-release-0.4\ppdet\core\workspace.py", line 259, in create
    kwargs[k] = create(target_key)
  File "C:\Users\1\Desktop\PaddleDetection-release-0.4\ppdet\core\workspace.py", line 223, in create
    config.validate()
  File "C:\Users\1\Desktop\PaddleDetection-release-0.4\ppdet\core\config\schema.py", line 143, in validate
    self.name, ", ".join(extra_keys)))
ValueError: Extraneous param for class<YOLOv3Loss>: batch_size

**Comment by qingqing01** [comment]
@youyouf 抱歉，由于昨天代码有一些更新，需要把YOLOv3Loss中的batch_size参数去掉

**Comment by qingqing01** [comment]
@youyouf 以修复https://github.com/PaddlePaddle/PaddleDetection/pull/1473

**Comment by youyouf** [comment]
> @youyouf 以修复#1473
 好的，谢谢，我有空再试试！
