### ISSUE TITLE
VOC数据集在fsat RCNN 模型中图片不识别的问题

### ISSUE THREAD

**Issue by CVdandelion** [PaddlePaddle/PaddleDetection#1514]

**Comment by CVdandelion** [comment]
VOC数据集在yolo V3 模型中是可以正常跑的。可是在fast RCNN 模型中，他判断我所有的图片是不合法的，请问是什么原因？
  
下面是报出的错误
2020-09-26 14:09:05,855-WARNING: Illegal image file: /home/robot/workspace/voc/VOCdevkit/VOC2007/JPEGImages/VOCdevkit/VOC2007/JPEGImages/001881.jpg, and it will be ignored
2020-09-26 14:09:05,855-WARNING: Illegal image file: /home/robot/workspace/voc/VOCdevkit/VOC2007/JPEGImages/VOCdevkit/VOC2007/JPEGImages/000584.jpg, and it will be ignored
2020-09-26 14:09:05,855-WARNING: Illegal image file: /home/robot/workspace/voc/VOCdevkit/VOC2007/JPEGImages/VOCdevkit/VOC2007/JPEGImages/006330.jpg, and it will be ignored
Traceback (most recent call last):
  File "tools/train.py", line 368, in <module>
    main()
  File "tools/train.py", line 204, in main
    devices_num=devices_num)
  File "/home/robot/workspace/PaddleDetection-release-0.3/ppdet/data/reader.py", line 410, in create_reader
    reader = Reader(**cfg)()
  File "/home/robot/workspace/PaddleDetection-release-0.3/ppdet/data/reader.py", line 204, in __init__
    self._roidbs = self._dataset.get_roidb()
  File "/home/robot/workspace/PaddleDetection-release-0.3/ppdet/data/source/dataset.py", line 68, in get_roidb
    self.load_roidb_and_cname2cid()
  File "/home/robot/workspace/PaddleDetection-release-0.3/ppdet/data/source/voc.py", line 186, in load_roidb_and_cname2cid
    self.anno_path)
AssertionError: not found any voc record in trainval.txt

**Comment by CVdandelion** [comment]
这个是，reader的配置
TrainReader:
  inputs_def:
    fields: ['image', 'gt_bbox', 'gt_class', 'gt_score']
  dataset:
    !VOCDataSet
    dataset_dir: /home/robot/workspace/voc
    anno_path: trainval.txt
    use_default_label: false
    with_background: false

**Comment by still-wait** [comment]
@CVdandelion `not found any voc record in trainval.txt`，请确认` /home/robot/workspace/voc`目录下是正确的voc标注格式：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/tutorials/PrepareDataSet.md#voc%E6%95%B0%E6%8D%AE%E6%95%B0%E6%8D%AE
