### ISSUE TITLE
【求助】pp-yolo 模型批量检测

### ISSUE THREAD

**Issue by Fauny** [PaddlePaddle/PaddleDetection#1516]
前提：自制数据集训练得到pp-yolo模型，尝试用于视频检测，目前使用160尺寸，在cpu模式下运行，速度需要50+ms，目标是平均每帧检测时间30ms左右

尝试基于`deploy/python/infer.py`修改，使用批量检测，每次检测4帧或8帧。

发现 AnalysisConfig 的 zero_copy_run 输出的 get_output_tensor 只有[n, 6]维， n是目标结果数量，zero_copy_run不支持批量多图检测吗？

**Comment by qingqing01** [comment]
@Fauny 

1. deploy/python/infer.py中还没支持batch预测。这个我们后续加下。
2. Python中的预测，如果是CPU，还可以增加以下代码进行加速:


    https://github.com/PaddlePaddle/PaddleDetection/blob/1cd05b21493e4f809655dbe5a37bc0e2b9432744/deploy/python/infer.py#L361

    在361行之后增加:

    ```
        # config.disable_gpu()
        config.set_cpu_math_library_num_threads(8)  # 设置线程的个数，4，6，8，可以尝试
    ```
    还可以开启mkldnn，在config.set_cpu_math_library_num_threads(8)代码之后增加:
 
    ```
        use_mkldnn = True
        if use_mkldnn:
            config.enable_mkldnn()
    ```

**Comment by Fauny** [comment]
@qingqing01 非常感谢回复！

1. infer.py 现在不支持，我尝试自己修改，调用的indicator部分应该是paddle.fluid的，和PaddleDetection应该是独立的，我这么理解不对么？
2. 尝试了set_cpu_math_library_num_threads这个有所改善，但还是不够。cpu不支持mkl , enable_mkldnn 用不了 :(

批量检测功能在官方推出之前，如果可能请给一下提示，我尝试自己改一下，再次感谢！

**Comment by qingqing01** [comment]
1. depoly下面的infer部分确实和PaddleDetection独立。
2. 是安装的如果CPU本身支持mkl的话，可以安装Paddle的mkl的预测/whl包。  mkl的速度还是快的。

改成batch的话， https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/deploy/python/infer.py#L493 预处理之后，先组成batch:

image: NCHW 其他字段也类似，batch的维度是batch_size。先组成batch，再做后续的执行（zero_copy_run()等）。

**Comment by Fauny** [comment]
再次感谢 @qingqing01 
```py
  inputs[input_names[i]] = inputs[input_names[i]].repeat(4, axis=0)
```
已经尝试模拟输入，现在的问题是输出的get_output_tensor维度少一个batch的维度，只有Boxes

**Comment by BerryRB** [comment]
@Fauny 你好，请问你解决批量预测的问题了吗？
@qingqing01 你好，请问官方大概什么时间更新这个功能？

**Comment by Adarine99** [comment]
`/usr/bin/python3.5 /home/bigdisk/liprogram/pycharm-community-2018.2.4/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 34229 --file /home/bigdisk/yuli/surface_defect_detect/PaddleDetection/deploy/python/infer.py --model_dir=/home/bigdisk/yuli/surface_defect_detect/PaddleDetection/tools/output/ppyolo/ --infer_dir=../../demo --image_file=../../demo/1.jpg --use_gpu=True
pydev debugger: process 13299 is connecting

Connected to pydev debugger (build 182.4505.26)
-----------  Running Arguments -----------
batchsize: 16
camera_id: -1
image_file: ../../demo/1.jpg
infer_dir: ../../demo
model_dir: /home/bigdisk/yuli/surface_defect_detect/PaddleDetection/tools/output/ppyolo/
output_dir: output
run_benchmark: False
run_mode: fluid
threshold: 0.5
use_gpu: True
video_file: 
------------------------------------------
-----------  Model Configuration -----------
Model Arch: YOLO
Use Padddle Executor: False
Transform Order: 
--transform op: Resize
--transform op: Normalize
--transform op: Permute
--------------------------------------------
2020-11-05 17:11:27,471-INFO: Found 100 inference images in total.
Traceback (most recent call last):
  File "/home/bigdisk/liprogram/pycharm-community-2018.2.4/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/home/bigdisk/liprogram/pycharm-community-2018.2.4/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/bigdisk/liprogram/pycharm-community-2018.2.4/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/bigdisk/liprogram/pycharm-community-2018.2.4/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/bigdisk/yuli/surface_defect_detect/PaddleDetection/deploy/python/infer.py", line 743, in <module>
    predict_image()
  File "/home/bigdisk/yuli/surface_defect_detect/PaddleDetection/deploy/python/infer.py", line 626, in predict_image
    results = detector.predict(test_images, FLAGS.batchsize, FLAGS.threshold)
  File "/home/bigdisk/yuli/surface_defect_detect/PaddleDetection/deploy/python/infer.py", line 587, in predict
    self.predictor.zero_copy_run()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::ConcatOp::InferShape(paddle::framework::InferShapeContext*) const
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
5   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
6   paddle::framework::NaiveExecutor::Run()
7   paddle::AnalysisPredictor::ZeroCopyRun()

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/jiangtaoq/.local/lib/python3.5/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/jiangtaoq/.local/lib/python3.5/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/jiangtaoq/.local/lib/python3.5/site-packages/paddle/fluid/layers/tensor.py", line 375, in concat
    type='concat', inputs=inputs, outputs={'Out': [out]}, attrs=attrs)
  File "/home/bigdisk/yuli/surface_defect_detect/PaddleDetection/ppdet/modeling/anchor_heads/yolo_head.py", line 158, in _add_coord
    return fluid.layers.concat([input, x_range, y_range], axis=1)
  File "/home/bigdisk/yuli/surface_defect_detect/PaddleDetection/ppdet/modeling/anchor_heads/yolo_head.py", line 235, in _detection_block
    conv = self._add_coord(conv, is_test=is_test)
  File "/home/bigdisk/yuli/surface_defect_detect/PaddleDetection/ppdet/modeling/anchor_heads/yolo_head.py", line 345, in _get_outputs
    name=self.prefix_name + "yolo_block.{}".format(i))
  File "/home/bigdisk/yuli/surface_defect_detect/PaddleDetection/ppdet/modeling/anchor_heads/yolo_head.py", line 419, in get_prediction
    outputs = self._get_outputs(input, is_train=False)
  File "/home/bigdisk/yuli/surface_defect_detect/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 93, in build
    body_feats, im_size, exclude_nms=exclude_nms)
  File "/home/bigdisk/yuli/surface_defect_detect/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 165, in test
    return self.build(feed_vars, mode='test', exclude_nms=exclude_nms)
  File "/home/bigdisk/yuli/surface_defect_detect/PaddleDetection/tools/export_model.py", line 202, in main
    test_fetches = model.test(feed_vars, exclude_nms=FLAGS.exclude_nms)
  File "/home/bigdisk/yuli/surface_defect_detect/PaddleDetection/tools/export_model.py", line 227, in <module>
    main()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The 0-th dimension of input[0] and input[1] is expected to be equal.But received input[0]'s shape = [16, 2048, 19, 19], input[1]'s shape = [1, 1, 19, 19].
  [Hint: Expected inputs_dims[0][j] == inputs_dims[i][j], but received inputs_dims[0][j]:16 != inputs_dims[i][j]:1.] at (/paddle/paddle/fluid/operators/concat_op.h:63)
  [operator < concat > error]
`
你好，我也在deploy/python/infer.py中做了一些修改，batchsize设为16，将[16,3,608,608]数据输入，在**self.predictor.zero_copy_run()**这里断掉了，请问有修改方法吗

**Comment by xialei2821212670** [comment]
> F
> 
> 1. deploy / python / infer.py中还没支持批量预测。这个我们后续加下。
> 2. Python中的预测，如果是CPU，还可以增加以下代码进行加速：
>    https://github.com/PaddlePaddle/PaddleDetection/blob/1cd05b21493e4f809655dbe5a37bc0e2b9432744/deploy/python/infer.py#L361
>    
>    在361行之后增加：
>    ```
>        # config.disable_gpu()
>        config.set_cpu_math_library_num_threads(8)  # 设置线程的个数，4，6，8，可以尝试
>    ```
>    
>    
>    还可以开启mkldnn，在config.set_cpu_math_library_num_threads（8）代码之后增加：
>    ```
>        use_mkldnn = True
>        if use_mkldnn:
>            config.enable_mkldnn()
>    ```你好，
![image](https://user-images.githubusercontent.com/57654726/103982554-ab080e00-51be-11eb-9951-3f5bbb625432.png)
sh是这样去使用？

**Comment by qingqing01** [comment]
即将发布的2.1会支持batch推理、支持mkldnn加速~  大家有问题，可以提新的issue~
