### ISSUE TITLE
TestReader中inputs_def未定义bug

### ISSUE THREAD

**Issue by edencfc** [PaddlePaddle/PaddleDetection#1518]
configs/obj365/cascade_rcnn_dcnv2_se154_vd_fpn_gn_cas.yml中TestReader中inputs_def未定义，模型导出时报错
```
/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/sklearn/feature_extraction/text.py:17: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping, defaultdict
Traceback (most recent call last):
  File "tools/export_model.py", line 227, in <module>
    main()
  File "tools/export_model.py", line 198, in main
    inputs_def = cfg['TestReader']['inputs_def']
KeyError: 'inputs_def
```

**Comment by qingqing01** [comment]
@edencfc 感谢指出，可以参考 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/configs/dcn/cascade_rcnn_cls_aware_r200_vd_fpn_dcnv2_nonlocal_softnms.yml#L188 这个加下。我们也尽快修复下

**Comment by yghstill** [comment]
fix in https://github.com/PaddlePaddle/PaddleDetection/pull/2330
