### ISSUE TITLE
这个报错怎么解决

### ISSUE THREAD

**Issue by qdd1234** [PaddlePaddle/PaddleDetection#1537]
2020-10-02 21:14:39,365-WARNING: fail to map op [Gt2YoloTarget_d0afa3] with error: index 26 is out of bounds for axis 1 with size 26 and stack:
Traceback (most recent call last):
  File "/home/aistudio/data/PaddleDetection/ppdet/data/reader.py", line 46, in __call__
    data = f(data, ctx)
  File "/home/aistudio/data/PaddleDetection/ppdet/data/transform/batch_operators.py", line 270, in __call__
    target[best_n, 6 + cls, gj, gi] = 1.
IndexError: index 26 is out of bounds for axis 1 with size 26

2020-10-02 21:14:39,433-WARNING: fail to map op [Gt2YoloTarget_d0afa3] with error: index 26 is out of bounds for axis 1 with size 26 and stack:
Traceback (most recent call last):
  File "/home/aistudio/data/PaddleDetection/ppdet/data/reader.py", line 46, in __call__
    data = f(data, ctx)
  File "/home/aistudio/data/PaddleDetection/ppdet/data/transform/batch_operators.py", line 270, in __call__
    target[best_n, 6 + cls, gj, gi] = 1.
IndexError: index 26 is out of bounds for axis 1 with size 26

**Comment by jerrywgz** [comment]
可以先检查下yolo配置文件中reader部分是否增加了with_background: false的配置https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/configs/yolov3_reader.yml#L10
另外num_class也是不包含背景类的

**Comment by ybxbupt** [comment]
你确定num_class是不包含背景类的吗？

**Comment by 15678380105** [comment]
尝试修改一下yml配置文件里面的num_classes，使之与label_list里面的字段数量对应
