### ISSUE TITLE
使用anchor_free训练pcb数据集到5000个iter报错

### ISSUE THREAD

**Issue by liguoyu666** [PaddlePaddle/PaddleDetection#1548]
训练加了--eval，每500次后测试，第一次训练5000个iter后测试时报错退出，用5000保存的模型不能接着训练，用4500保存的模型接着训练，到第5000个iter后测试时又报错。
![image](https://user-images.githubusercontent.com/47743761/95643580-98f4d180-0ae2-11eb-8149-7bc156960ec9.png)

**Comment by liguoyu666** [comment]
第一次训练时报错：
2020-10-10 00:18:01,789-INFO: iter: 5000, lr: 0.000250, 'loss_centerness': '0.006607', 'loss_cls': '0.001482', 'loss_box': '0.066453', 'loss': '0.077545', time: 2.064, eta: 1:12:47
2020-10-10 00:18:01,790-INFO: Save model to output/fcos_dcn_r50_fpn_1x/5000.
2020-10-10 00:18:04,578-INFO: Test iter 0
2020-10-10 00:18:43,210-INFO: Test finish iter 100
2020-10-10 00:18:43,211-INFO: Total number of images: 100, inference time: 2.582567325741308 fps.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Traceback (most recent call last):
  File "tools/train.py", line 372, in <module>
    main()
  File "tools/train.py", line 294, in main
    cfg['EvalReader']['dataset'])
  File "/home/aistudio/work/PaddleDetection/ppdet/utils/eval_utils.py", line 220, in eval_results
    save_only=save_only)
  File "/home/aistudio/work/PaddleDetection/ppdet/utils/coco_eval.py", line 87, in bbox_eval
    results, clsid2catid, is_bbox_normalized=is_bbox_normalized)
  File "/home/aistudio/work/PaddleDetection/ppdet/utils/coco_eval.py", line 265, in bbox2out
    catid = (clsid2catid[int(clsid)])
KeyError: 32
terminate called without an active exception
W1010 00:18:44.147058  2996 init.cc:216] Warning: PaddlePaddle catches a failure signal, it may not work properly
W1010 00:18:44.147104  2996 init.cc:218] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W1010 00:18:44.147109  2996 init.cc:221] The detail failure signal is:

W1010 00:18:44.147116  2996 init.cc:224] *** Aborted at 1602260324 (unix time) try "date -d @1602260324" if you are using GNU date ***
W1010 00:18:44.148939  2996 init.cc:224] PC: @                0x0 (unknown)
W1010 00:18:44.149053  2996 init.cc:224] *** SIGABRT (@0x3e800000902) received by PID 2306 (TID 0x7f7046ffd700) from PID 2306; stack trace: ***
W1010 00:18:44.150367  2996 init.cc:224]     @     0x7f7312c01390 (unknown)
W1010 00:18:44.151568  2996 init.cc:224]     @     0x7f731285b428 gsignal
W1010 00:18:44.152737  2996 init.cc:224]     @     0x7f731285d02a abort
W1010 00:18:44.153640  2996 init.cc:224]     @     0x7f72d35da84a __gnu_cxx::__verbose_terminate_handler()
W1010 00:18:44.154395  2996 init.cc:224]     @     0x7f72d35d8f47 __cxxabiv1::__terminate()
W1010 00:18:44.155210  2996 init.cc:224]     @     0x7f72d35d8f7d std::terminate()
W1010 00:18:44.155975  2996 init.cc:224]     @     0x7f72d35d8c5a __gxx_personality_v0
W1010 00:18:44.156697  2996 init.cc:224]     @     0x7f72d390bb97 _Unwind_ForcedUnwind_Phase2
W1010 00:18:44.157400  2996 init.cc:224]     @     0x7f72d390be7d _Unwind_ForcedUnwind
W1010 00:18:44.158586  2996 init.cc:224]     @     0x7f7312c00070 __GI___pthread_unwind
W1010 00:18:44.159865  2996 init.cc:224]     @     0x7f7312bf8845 __pthread_exit
W1010 00:18:44.160145  2996 init.cc:224]     @     0x556e6e31ee59 PyThread_exit_thread
W1010 00:18:44.160218  2996 init.cc:224]     @     0x556e6e1a4c17 PyEval_RestoreThread.cold.798
W1010 00:18:44.161283  2996 init.cc:224]     @     0x7f73056f429c (unknown)
W1010 00:18:44.161553  2996 init.cc:224]     @     0x556e6e2a0744 _PyMethodDef_RawFastCallKeywords
W1010 00:18:44.161784  2996 init.cc:224]     @     0x556e6e2a0861 _PyCFunction_FastCallKeywords
W1010 00:18:44.162006  2996 init.cc:224]     @     0x556e6e30c2bd _PyEval_EvalFrameDefault
W1010 00:18:44.162209  2996 init.cc:224]     @     0x556e6e250539 _PyEval_EvalCodeWithName
W1010 00:18:44.162412  2996 init.cc:224]     @     0x556e6e251635 _PyFunction_FastCallDict
W1010 00:18:44.162616  2996 init.cc:224]     @     0x556e6e26fe53 _PyObject_Call_Prepend
W1010 00:18:44.162727  2996 init.cc:224]     @     0x556e6e2a7a3a slot_tp_call
W1010 00:18:44.162930  2996 init.cc:224]     @     0x556e6e2a88fb _PyObject_FastCallKeywords
W1010 00:18:44.163147  2996 init.cc:224]     @     0x556e6e30be86 _PyEval_EvalFrameDefault
W1010 00:18:44.163348  2996 init.cc:224]     @     0x556e6e25156b _PyFunction_FastCallDict
W1010 00:18:44.163544  2996 init.cc:224]     @     0x556e6e26fe53 _PyObject_Call_Prepend
W1010 00:18:44.163662  2996 init.cc:224]     @     0x556e6e2a7a3a slot_tp_call
W1010 00:18:44.163866  2996 init.cc:224]     @     0x556e6e2a88fb _PyObject_FastCallKeywords
W1010 00:18:44.164081  2996 init.cc:224]     @     0x556e6e30c6e8 _PyEval_EvalFrameDefault
W1010 00:18:44.164281  2996 init.cc:224]     @     0x556e6e250539 _PyEval_EvalCodeWithName
W1010 00:18:44.164482  2996 init.cc:224]     @     0x556e6e251635 _PyFunction_FastCallDict
W1010 00:18:44.164687  2996 init.cc:224]     @     0x556e6e26fe53 _PyObject_Call_Prepend
W1010 00:18:44.164909  2996 init.cc:224]     @     0x556e6e262dbe PyObject_Call
Aborted (core dumped)

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------

接着4500保存的模型训练时报错：
2020-10-10 00:26:51,909-WARNING: paddle.fluid.layers.matrix_nms OP not found, maybe a newer version of paddle is required.
2020-10-10 00:26:53,005-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000100] in Optimizer will not take effect, and it will only be applied to other Parameters!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2020-10-10 00:26:54,646-INFO: places would be ommited when DataLoader is not iterable
W1010 00:26:54.675325  8264 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 9.0
W1010 00:26:54.680256  8264 device_context.cc:260] device: 0, cuDNN Version: 7.6.
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
2020-10-10 00:27:05,485-INFO: places would be ommited when DataLoader is not iterable
/home/aistudio/work/PaddleDetection/ppdet/data/transform/batch_operators.py:464: RuntimeWarning: invalid value encountered in sqrt
  reg_targets[:, [1, 3]].max(axis=1))).astype(np.float32)
/home/aistudio/work/PaddleDetection/ppdet/data/transform/batch_operators.py:464: RuntimeWarning: invalid value encountered in sqrt
  reg_targets[:, [1, 3]].max(axis=1))).astype(np.float32)
/home/aistudio/work/PaddleDetection/ppdet/data/transform/batch_operators.py:464: RuntimeWarning: invalid value encountered in sqrt
  reg_targets[:, [1, 3]].max(axis=1))).astype(np.float32)
/home/aistudio/work/PaddleDetection/ppdet/data/transform/batch_operators.py:464: RuntimeWarning: invalid value encountered in sqrt
  reg_targets[:, [1, 3]].max(axis=1))).astype(np.float32)
2020-10-10 00:27:13,329-INFO: iter: 4500, lr: 0.002500, 'loss_centerness': '0.004693', 'loss_cls': '0.001839', 'loss_box': '0.114244', 'loss': '0.120776', time: 0.000, eta: 0:00:00
2020-10-10 00:27:13,330-INFO: Save model to output/fcos_dcn_r50_fpn_1x/4500.
2020-10-10 00:27:21,108-INFO: Test iter 0
2020-10-10 00:28:11,067-INFO: Test finish iter 100
2020-10-10 00:28:11,068-INFO: Total number of images: 100, inference time: 1.9568603016104698 fps.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2020-10-10 00:28:11,084-INFO: Start evaluate...
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.12s).
Accumulating evaluation results...
DONE (t=0.03s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.469
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.950
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.430
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.480
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.472
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.451
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.131
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.536
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.536
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.487
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.542
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.476
2020-10-10 00:28:11,240-INFO: Save model to output/fcos_dcn_r50_fpn_1x/best_model.
2020-10-10 00:28:14,128-INFO: Best test box ap: 0.46938552875539075, in iter: 4500
2020-10-10 00:28:55,547-INFO: iter: 4520, lr: 0.002500, 'loss_centerness': '0.006916', 'loss_cls': '0.003589', 'loss_box': '0.104757', 'loss': '0.113725', time: 5.396, eta: 3:53:27
2020-10-10 00:29:37,251-INFO: iter: 4540, lr: 0.002500, 'loss_centerness': '0.006543', 'loss_cls': '0.003754', 'loss_box': '0.101159', 'loss': '0.111465', time: 2.086, eta: 1:29:33
2020-10-10 00:30:18,400-INFO: iter: 4560, lr: 0.002500, 'loss_centerness': '0.006305', 'loss_cls': '0.003762', 'loss_box': '0.106223', 'loss': '0.121027', time: 2.057, eta: 1:27:37
2020-10-10 00:30:59,380-INFO: iter: 4580, lr: 0.002500, 'loss_centerness': '0.006910', 'loss_cls': '0.006433', 'loss_box': '0.100154', 'loss': '0.113255', time: 2.049, eta: 1:26:35
2020-10-10 00:31:41,315-INFO: iter: 4600, lr: 0.002500, 'loss_centerness': '0.006774', 'loss_cls': '0.006578', 'loss_box': '0.096619', 'loss': '0.113029', time: 2.097, eta: 1:27:56
2020-10-10 00:32:22,605-INFO: iter: 4620, lr: 0.002500, 'loss_centerness': '0.006305', 'loss_cls': '0.004474', 'loss_box': '0.099866', 'loss': '0.113771', time: 2.064, eta: 1:25:52
2020-10-10 00:33:04,586-INFO: iter: 4640, lr: 0.002500, 'loss_centerness': '0.006476', 'loss_cls': '0.004866', 'loss_box': '0.095416', 'loss': '0.110021', time: 2.117, eta: 1:27:21
2020-10-10 00:33:45,543-INFO: iter: 4660, lr: 0.002500, 'loss_centerness': '0.006470', 'loss_cls': '0.005392', 'loss_box': '0.097422', 'loss': '0.114286', time: 2.042, eta: 1:23:36
2020-10-10 00:34:27,585-INFO: iter: 4680, lr: 0.002500, 'loss_centerness': '0.006364', 'loss_cls': '0.003048', 'loss_box': '0.100637', 'loss': '0.110125', time: 2.089, eta: 1:24:49
2020-10-10 00:35:08,957-INFO: iter: 4700, lr: 0.002500, 'loss_centerness': '0.006781', 'loss_cls': '0.004611', 'loss_box': '0.098379', 'loss': '0.113273', time: 2.069, eta: 1:23:17
2020-10-10 00:35:51,148-INFO: iter: 4720, lr: 0.002500, 'loss_centerness': '0.006847', 'loss_cls': '0.004416', 'loss_box': '0.097959', 'loss': '0.109385', time: 2.122, eta: 1:24:44
2020-10-10 00:36:30,687-INFO: iter: 4740, lr: 0.002500, 'loss_centerness': '0.006593', 'loss_cls': '0.002754', 'loss_box': '0.109695', 'loss': '0.121956', time: 1.965, eta: 1:17:48
2020-10-10 00:37:12,642-INFO: iter: 4760, lr: 0.000250, 'loss_centerness': '0.006490', 'loss_cls': '0.002960', 'loss_box': '0.092849', 'loss': '0.102495', time: 2.098, eta: 1:22:21
2020-10-10 00:37:54,344-INFO: iter: 4780, lr: 0.000250, 'loss_centerness': '0.006294', 'loss_cls': '0.001986', 'loss_box': '0.087706', 'loss': '0.095739', time: 2.085, eta: 1:21:10
2020-10-10 00:38:34,765-INFO: iter: 4800, lr: 0.000250, 'loss_centerness': '0.006393', 'loss_cls': '0.001988', 'loss_box': '0.075811', 'loss': '0.086066', time: 2.021, eta: 1:18:00
2020-10-10 00:39:16,548-INFO: iter: 4820, lr: 0.000250, 'loss_centerness': '0.006186', 'loss_cls': '0.001048', 'loss_box': '0.074595', 'loss': '0.081895', time: 2.089, eta: 1:19:56
2020-10-10 00:39:58,456-INFO: iter: 4840, lr: 0.000250, 'loss_centerness': '0.006634', 'loss_cls': '0.001548', 'loss_box': '0.074048', 'loss': '0.084480', time: 2.096, eta: 1:19:30
2020-10-10 00:40:39,838-INFO: iter: 4860, lr: 0.000250, 'loss_centerness': '0.006311', 'loss_cls': '0.001766', 'loss_box': '0.073112', 'loss': '0.081829', time: 2.068, eta: 1:17:44
2020-10-10 00:41:19,674-INFO: iter: 4880, lr: 0.000250, 'loss_centerness': '0.006984', 'loss_cls': '0.001470', 'loss_box': '0.070264', 'loss': '0.078192', time: 1.993, eta: 1:14:16
2020-10-10 00:42:01,790-INFO: iter: 4900, lr: 0.000250, 'loss_centerness': '0.006069', 'loss_cls': '0.002014', 'loss_box': '0.066833', 'loss': '0.076305', time: 2.106, eta: 1:17:47
2020-10-10 00:42:42,352-INFO: iter: 4920, lr: 0.000250, 'loss_centerness': '0.006514', 'loss_cls': '0.001038', 'loss_box': '0.063515', 'loss': '0.071190', time: 2.056, eta: 1:15:14
2020-10-10 00:43:24,469-INFO: iter: 4940, lr: 0.000250, 'loss_centerness': '0.006436', 'loss_cls': '0.001467', 'loss_box': '0.066352', 'loss': '0.075601', time: 2.077, eta: 1:15:19
2020-10-10 00:44:04,744-INFO: iter: 4960, lr: 0.000250, 'loss_centerness': '0.006643', 'loss_cls': '0.000989', 'loss_box': '0.062560', 'loss': '0.072218', time: 2.015, eta: 1:12:24
2020-10-10 00:44:46,886-INFO: iter: 4980, lr: 0.000250, 'loss_centerness': '0.006644', 'loss_cls': '0.001449', 'loss_box': '0.063029', 'loss': '0.072162', time: 2.126, eta: 1:15:40
2020-10-10 00:45:29,225-INFO: iter: 5000, lr: 0.000250, 'loss_centerness': '0.006660', 'loss_cls': '0.001088', 'loss_box': '0.060810', 'loss': '0.071252', time: 2.098, eta: 1:13:59
2020-10-10 00:45:29,225-INFO: Save model to output/fcos_dcn_r50_fpn_1x/5000.
2020-10-10 00:45:32,190-INFO: Test iter 0
2020-10-10 00:46:11,262-INFO: Test finish iter 100
2020-10-10 00:46:11,262-INFO: Total number of images: 100, inference time: 2.5531930383818575 fps.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Traceback (most recent call last):
  File "tools/train.py", line 372, in <module>
    main()
  File "tools/train.py", line 294, in main
    cfg['EvalReader']['dataset'])
  File "/home/aistudio/work/PaddleDetection/ppdet/utils/eval_utils.py", line 220, in eval_results
    save_only=save_only)
  File "/home/aistudio/work/PaddleDetection/ppdet/utils/coco_eval.py", line 87, in bbox_eval
    results, clsid2catid, is_bbox_normalized=is_bbox_normalized)
  File "/home/aistudio/work/PaddleDetection/ppdet/utils/coco_eval.py", line 265, in bbox2out
    catid = (clsid2catid[int(clsid)])
KeyError: 32
terminate called without an active exception
W1010 00:46:12.103125  8470 init.cc:216] Warning: PaddlePaddle catches a failure signal, it may not work properly
W1010 00:46:12.103168  8470 init.cc:218] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W1010 00:46:12.103176  8470 init.cc:221] The detail failure signal is:

W1010 00:46:12.103183  8470 init.cc:224] *** Aborted at 1602261972 (unix time) try "date -d @1602261972" if you are using GNU date ***
W1010 00:46:12.105029  8470 init.cc:224] PC: @                0x0 (unknown)
W1010 00:46:12.105151  8470 init.cc:224] *** SIGABRT (@0x3e800002048) received by PID 8264 (TID 0x7f6cecff9700) from PID 8264; stack trace: ***
W1010 00:46:12.106545  8470 init.cc:224]     @     0x7f6fa444f390 (unknown)
W1010 00:46:12.107745  8470 init.cc:224]     @     0x7f6fa40a9428 gsignal
W1010 00:46:12.108911  8470 init.cc:224]     @     0x7f6fa40ab02a abort
W1010 00:46:12.109819  8470 init.cc:224]     @     0x7f6f64e2884a __gnu_cxx::__verbose_terminate_handler()
W1010 00:46:12.110574  8470 init.cc:224]     @     0x7f6f64e26f47 __cxxabiv1::__terminate()
W1010 00:46:12.111397  8470 init.cc:224]     @     0x7f6f64e26f7d std::terminate()
W1010 00:46:12.112169  8470 init.cc:224]     @     0x7f6f64e26c5a __gxx_personality_v0
W1010 00:46:12.112869  8470 init.cc:224]     @     0x7f6f65159b97 _Unwind_ForcedUnwind_Phase2
W1010 00:46:12.113581  8470 init.cc:224]     @     0x7f6f65159e7d _Unwind_ForcedUnwind
W1010 00:46:12.114878  8470 init.cc:224]     @     0x7f6fa444e070 __GI___pthread_unwind
W1010 00:46:12.116083  8470 init.cc:224]     @     0x7f6fa4446845 __pthread_exit
W1010 00:46:12.116351  8470 init.cc:224]     @     0x559a153c3e59 PyThread_exit_thread
W1010 00:46:12.116425  8470 init.cc:224]     @     0x559a15249c17 PyEval_RestoreThread.cold.798
W1010 00:46:12.117467  8470 init.cc:224]     @     0x7f6f938c529c (unknown)
W1010 00:46:12.117733  8470 init.cc:224]     @     0x559a15345744 _PyMethodDef_RawFastCallKeywords
W1010 00:46:12.117961  8470 init.cc:224]     @     0x559a15345861 _PyCFunction_FastCallKeywords
W1010 00:46:12.118183  8470 init.cc:224]     @     0x559a153b12bd _PyEval_EvalFrameDefault
W1010 00:46:12.118387  8470 init.cc:224]     @     0x559a152f5539 _PyEval_EvalCodeWithName
W1010 00:46:12.118592  8470 init.cc:224]     @     0x559a152f6635 _PyFunction_FastCallDict
W1010 00:46:12.118790  8470 init.cc:224]     @     0x559a15314e53 _PyObject_Call_Prepend
W1010 00:46:12.118901  8470 init.cc:224]     @     0x559a1534ca3a slot_tp_call
W1010 00:46:12.119108  8470 init.cc:224]     @     0x559a1534d8fb _PyObject_FastCallKeywords
W1010 00:46:12.119328  8470 init.cc:224]     @     0x559a153b0e86 _PyEval_EvalFrameDefault
W1010 00:46:12.119530  8470 init.cc:224]     @     0x559a152f656b _PyFunction_FastCallDict
W1010 00:46:12.119729  8470 init.cc:224]     @     0x559a15314e53 _PyObject_Call_Prepend
W1010 00:46:12.119835  8470 init.cc:224]     @     0x559a1534ca3a slot_tp_call
W1010 00:46:12.120043  8470 init.cc:224]     @     0x559a1534d8fb _PyObject_FastCallKeywords
W1010 00:46:12.120261  8470 init.cc:224]     @     0x559a153b16e8 _PyEval_EvalFrameDefault
W1010 00:46:12.120463  8470 init.cc:224]     @     0x559a152f5539 _PyEval_EvalCodeWithName
W1010 00:46:12.120672  8470 init.cc:224]     @     0x559a152f6635 _PyFunction_FastCallDict
W1010 00:46:12.120877  8470 init.cc:224]     @     0x559a15314e53 _PyObject_Call_Prepend
W1010 00:46:12.121106  8470 init.cc:224]     @     0x559a15307dbe PyObject_Call
Aborted (core dumped)

**Comment by still-wait** [comment]
@liguoyu666 你配置文件中的`num_classes `改成PCB数据集的类别数了吗?

**Comment by liguoyu666** [comment]
> num_classes

这些都改了的，每500个ｉｔｅｒ就要测试保存一次
