### ISSUE TITLE
关于训练好的模型量化的问题

### ISSUE THREAD

**Issue by CVdandelion** [PaddlePaddle/PaddleDetection#1560]
请问一下我看到这里提供的量化的方法，在训练的过程中进行量化。可是我现在的情况是已经把模型训练好了，请问一下我该怎么把他量化，我还查看了PaddleSlim部分，他需要调用如下接口
slim.quant.quant_post_static(
        executor=exe,
        model_dir='./inference_model',
        quantize_model_path='./quant_post_static_model',
        sample_generator=reader.test(),
        batch_nums=10)
此时是需要指定执行器exe和reade参数，可是对于用PaddleDetection训练好的模型，我该如何指定这两个参数那

**Comment by liuhuiCNN** [comment]
您参考的是PaddleDetection的slim下文档吗？ https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.4/slim/quantization

**Comment by CVdandelion** [comment]
是的，这个不是在训练的过程进行量化吗？

**Comment by willthefrog** [comment]
可以尝试使用test reader和exe, 参考[infer.py](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/tools/infer.py#L122)

**Comment by CVdandelion** [comment]
我直接把这个语句加在了infer这个文件的main函数的最后部分，出现了这个错误：
Traceback (most recent call last):
  File "tools/infer.py", line 276, in <module>
    main()
  File "tools/infer.py", line 239, in main
    sample_generator=reader.test(),
AttributeError: 'function' object has no attribute 'test'
也就是在这个接口函数的sample_generator参数不对，请问这个该怎么改阿？

**Comment by willthefrog** [comment]
reader直接传入

**Comment by CVdandelion** [comment]
恩，可是又出现了新的错误
2020-10-14 19:56:09,082-INFO: Infer iter 152
2020-10-14 19:56:09,094-INFO: Detection bbox results save in output/004984.jpg
2020-10-14 19:56:09,123-INFO: Load model and set data loader ...
2020-10-14 19:56:09,213-INFO: Collect quantized variable names ...
2020-10-14 19:56:09,498-WARNING: Your reader has raised an exception!
Exception in thread Thread-2:
TypeError: only size-1 arrays can be converted to Python scalars

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/robot/anaconda3/envs/paddle/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/robot/anaconda3/envs/paddle/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/robot/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1145, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/home/robot/anaconda3/envs/paddle/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/robot/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1125, in __thread_main__
    for tensors in self._tensor_reader():
  File "/home/robot/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 204, in __call__
    yield self._done()
  File "/home/robot/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 192, in _done
    return [c.done() for c in self.converters]
  File "/home/robot/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 192, in <listcomp>
    return [c.done() for c in self.converters]
  File "/home/robot/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 157, in done
    arr = np.array(self.data, dtype=self.dtype)
ValueError: setting an array element with a sequence.

Traceback (most recent call last):
  File "tools/infer.py", line 278, in <module>
    main()
  File "tools/infer.py", line 242, in main
    batch_nums=10)
  File "/home/robot/anaconda3/envs/paddle/lib/python3.7/site-packages/paddleslim/quant/quanter.py", line 331, in quant_post
    post_training_quantization.quantize()
  File "/home/robot/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/contrib/slim/quantization/post_training_quantization.py", line 280, in quantize
    for data in self._data_loader():
  File "/home/robot/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1104, in __next__
    return self._reader.read_next()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)

**Comment by qingqing01** [comment]
@CVdand
