### ISSUE TITLE
使用yolov3_mobilenet_v1_voc.yml训练时出错

### ISSUE THREAD

**Issue by txssg** [PaddlePaddle/PaddleDetection#1565]
Traceback (most recent call last):
  File "tools/train.py", line 372, in <module>
    main()
  File "tools/train.py", line 70, in main
    cfg = load_config(FLAGS.config)
  File "/home/aistudio/PaddleDetection/ppdet/core/workspace.py", line 86, in load_config
    cfg = merge_config(yaml.load(f, Loader=yaml.Loader), cfg)
  File "/home/aistudio/PaddleDetection/ppdet/core/workspace.py", line 143, in merge_config
    dct['train_batch_size'] = dct['TrainReader']['batch_size']
KeyError: 'batch_size'

**Comment by yghstill** [comment]
@txssg 请在config配置文件的TrainReader中加入`batch_size: 8`,这个问题我们会马上修复。

**Comment by yghstill** [comment]
问题已修复，请更新代码再试一下吧。
