### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'with_background'

### ISSUE THREAD

**Issue by txssg** [PaddlePaddle/PaddleDetection#1573]
Traceback (most recent call last):
  File "tools/train.py", line 372, in <module>
    main()
  File "tools/train.py", line 208, in main
    num_trainers=num_trainers)
  File "/home/aistudio/PaddleDetection/ppdet/data/reader.py", line 441, in create_reader
    reader = Reader(**cfg)()
  File "/home/aistudio/PaddleDetection/ppdet/data/reader.py", line 210, in __init__
    self._roidbs = self._dataset.get_roidb()
  File "/home/aistudio/PaddleDetection/ppdet/data/source/dataset.py", line 68, in get_roidb
    self.load_roidb_and_cname2cid()
  File "/home/aistudio/PaddleDetection/ppdet/data/source/voc.py", line 186, in load_roidb_and_cname2cid
    self.anno_path)
AssertionError: not found any voc record in train_list.txt

**Comment by qingqing01** [comment]
@txssg 

这里的错误是指: 读取数据之后，发现样本数是0，可能的错误: 数据路径设置不正确、train_list.txt里格式不正确，你可以检查下TrainReader设置，也可以贴出来，一起看下。
