### ISSUE TITLE
eval的时候出现问题

### ISSUE THREAD

**Issue by gaofssvm** [PaddlePaddle/PaddleDetection#1592]
config文件：
################################################

```
architecture: YOLOv3
use_gpu: true
max_iters: 50000
log_smooth_window: 20
save_dir: output
snapshot_iter: 40
metric: VOC
pretrain_weights: https://paddlemodels.bj.bcebos.com/object_detection/ResNet50_vd_dcn_db_obj365_pretrained.tar
weights: output/yolov3_r50vd_dcn_db_obj365_pretrained_coco/model_final
finetune_exclude_pretrained_params: ['yolo_output']   #预训练时，加载权重时，忽略的字段，这表示输出层的参数不进行加载
num_classes: 8
use_fine_grained_loss: false

YOLOv3:
  backbone: ResNet
  yolo_head: YOLOv3Head
  use_fine_grained_loss: false

ResNet:
  norm_type: sync_bn
  freeze_at: 0
  freeze_norm: false
  norm_decay: 0.
  depth: 50
  feature_maps: [3, 4, 5]
  variant: d
  dcn_v2_stages: [5]

YOLOv3Head:
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  anchors: [[10, 13], [16, 30], [33, 23],
            [30, 61], [62, 45], [59, 119],
            [116, 90], [156, 198], [373, 326]]
  norm_decay: 0.
  yolo_loss: YOLOv3Loss
  nms:
    background_label: -1
    keep_top_k: 100
    nms_threshold: 0.3
    nms_top_k: 1000
    normalized: false
    score_threshold: 0.01

YOLOv3Loss:
  ignore_thresh: 0.7
  label_smooth: true
  use_fine_grained_loss: false

LearningRate:
  base_lr: 0.0005
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 25000
    - 37500
  - !LinearWarmup
    start_factor: 0.
    steps: 4000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

_READER_: 'yolov3_enhance_reader.yml'

TrainReader:
  inputs_def:
    fields: ['image', 'gt_bbox', 'gt_class', 'gt_score']
    num_max_boxes: 50
  dataset:
    !VOCDataSet
    dataset_dir: dataset/voc
    anno_path: trainval.txt
    with_background: false
    use_default_label: false
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !NormalizeBox {}
  - !RandomFlipImage
    is_normalized: true
    prob: 0.5
  - !NormalizeImage
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    is_scale: true
    is_channel_first: false
  - !PadBox
    num_max_boxes: 50
  - !BboxXYXY2XYWH {}
  batch_transforms:
  - !RandomShape
    sizes: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608]
    random_inter: True
  - !NormalizeImage
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    is_scale: True
    is_channel_first: false
  - !Permute
    channel_first: true
    to_bgr: false
  batch_size: 8
  shuffle: true
  drop_last: true

EvalReader:
  batch_size: 8
  inputs_def:
    fields: ['image', 'im_size', 'im_id']
    num_max_boxes: 50
  dataset:
    !VOCDataSet
    dataset_dir: dataset/voc
    anno_path: trainval.txt
    use_default_label: false
    with_background: false
  sample_transforms:
  - !ResizeImage
    target_size: 608
    interp: 2
  - !NormalizeImage
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    is_scale: True
    is_channel_first: false
  - !PadBox
    num_max_boxes: 50
  - !Permute
    to_bgr: false
    channel_first: True
  worker_num: 4


TestReader:
  inputs_def:
    fields: ['image', 'im_size', 'im_id']
  dataset:
    !ImageFolder
      anno_path: dataset/voc//VOCdevkit/VOC2007/label_list.txt
      use_default_label: false
      with_background: false
  sample_transforms:
  - !DecodeImage
    to_rgb: True
  - !ResizeImage
    target_size: 608
    interp: 2
  - !NormalizeImage
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    is_scale: True
    is_channel_first: false
  - !Permute
    to_bgr: false
    channel_first: True
  batch_size: 1
```
##############################################################

训练能够正常进行，当进行评估的时候，运行eval.py文件时，出现以下问题

```
Traceback (most recent call last):
  File "/home/zrway/zrway/GFS/paddleobjection/PaddleDetection/ppdet/data/reader.py", line 46, in __call__
    data = f(data, ctx)
  File "/home/zrway/zrway/GFS/paddleobjection/PaddleDetection/ppdet/data/transform/operators.py", line 305, in __call__
    im = sample['image']
KeyError: 'image'

2020-10-21 16:24:49,206-WARNING: recv endsignal from outq with errmsg[consumer[consumer-ea5-3] failed to map with error:['image']]
2020-10-21 16:24:49,207-WARNING: fail to map op [ResizeImage_9deb04] with error: 'image' and stack:
Traceback (most recent call last):
  File "/home/zrway/zrway/GFS/paddleobjection/PaddleDetection/ppdet/data/reader.py", line 46, in __call__
    data = f(data, ctx)
  File "/home/zrway/zrway/GFS/paddleobjection/PaddleDetection/ppdet/data/transform/operators.py", line 305, in __call__
    im = sample['image']
KeyError: 'image'

2020-10-21 16:24:49,208-WARNING: fail to map op [ResizeImage_9deb04] with error: 'image' and stack:
Traceback (most recent call last):
  File "/home/zrway/zrway/GFS/paddleobjection/PaddleDetection/ppdet/data/reader.py", line 46, in __call__
    data = f(data, ctx)
  File "/home/zrway/zrway/GFS/paddleobjection/PaddleDetection/ppdet/data/transform/operators.py", line 305, in __call__
    im = sample['image']
KeyError: 'image'

2020-10-21 16:24:49,208-WARNING: fail to map op [ResizeImage_9deb04] with error: 'image' and stack:
Traceback (most recent call last):
  File "/home/zrway/zrway/GFS/paddleobjection/PaddleDetection/ppdet/data/reader.py", line 46, in __call__
    data = f(data, ctx)
  File "/home/zrway/zrway/GFS/paddleobjection/PaddleDetection/ppdet/data/transform/operators.py", line 305, in __call__
    im = sample['image']
KeyError: 'image'
```

**Comment by willthefrog** [comment]
代码修改了什么？如何运行的？看上去是数据集配置有问题。

**Comment by gaofssvm** [comment]
@willthefrog ,代码没有修改，但是为什么能进行训练，数据集我检测过，应该是没有问题

**Comment by willthefrog** [comment]
代码没改的话，配置修改了什么呢？

**Comment by gaofssvm** [comment]
配置就是上面这些，贴出来了的

**Comment by qingqing01** [comment]
@gaofssvm 请问现在还是否有问题？

关于，YOLOv3系列+VOC的配置可以参考：

https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/configs/yolov3_darknet_voc.yml#L76

注意EvalReader中的fields字段，可以参考上面。
