### ISSUE TITLE
内存占用不断增长直到溢出报错问题

### ISSUE THREAD

**Issue by Jorsen0** [PaddlePaddle/PaddleDetection#1596]
报错信息如下：

```
2020-10-22 13:09:42,698-INFO: iter: 1700, lr: 0.000042, 'loss_xy': '2.738464', 'loss_wh': '4.352371', 'loss_obj': '19.474234',     'loss_cls': '9.305740', 'loss_iou': '9.994627', 'loss_iou_aware': '0.377208', 'loss': '46.144291', time: 1.748, eta: 5 days, 1:    02:59
2020-10-22 13:12:40,419-INFO: iter: 1800, lr: 0.000045, 'loss_xy': '2.704323', 'loss_wh': '4.081926', 'loss_obj': '19.392391',     'loss_cls': '9.118781', 'loss_iou': '9.685465', 'loss_iou_aware': '0.343045', 'loss': '45.485718', time: 1.782, eta: 5 days, 3:    22:05
2020-10-22 13:15:52,835-WARNING: fail to map op [ColorDistort_ec01cc] with error:  and stack:
Traceback (most recent call last):
  File "/paddle/PaddleDetection/ppdet/data/reader.py", line 46, in __call__
    data = f(data, ctx)
  File "/paddle/PaddleDetection/ppdet/data/transform/operators.py", line 1557, in __call__
    img = func(img)
  File "/paddle/PaddleDetection/ppdet/data/transform/operators.py", line 1507, in apply_hue
    img = np.dot(img, t)
MemoryError

2020-10-22 13:15:53,032-WARNING: recv endsignal from outq with errmsg[consumer[consumer-934-9] failed to map with error:[]]
2020-10-22 13:15:56,349-WARNING: recv endsignal from outq with errmsg[consumer[consumer-934-5] exits for reason[consumer[consum    er-934-9] failed to map with error:[]]]
2020-10-22 13:16:01,743-WARNING: recv endsignal from outq with errmsg[consumer[consumer-934-10] exits for reason[consumer[consu    mer-934-5] exits for reason[consumer[consumer-934-9] failed to map with error:[]]]]
2020-10-22 13:16:07,098-WARNING: recv endsignal from outq with errmsg[consumer[consumer-934-1] exits for reason[consumer[consum    er-934-10] exits for reason[consumer[consumer-934-5] exits for reason[consumer[consumer-934-9] failed to map with error:[]]]]]
2020-10-22 13:16:09,513-INFO: iter: 1900, lr: 0.000048, 'loss_xy': '2.830123', 'loss_wh': '4.210248', 'loss_obj': '20.236515',     'loss_cls': '9.068985', 'loss_iou': '10.140768', 'loss_iou_aware': '0.322120', 'loss': '46.772873', time: 2.094, eta: 6 days, 0    :54:54
2020-10-22 13:16:11,415-WARNING: recv endsignal from outq with errmsg[consumer[consumer-934-13] exits for reason[consumer[consu    mer-934-1] exits for reason[consumer[consumer-934-10] exits for reason[consumer[consumer-934-5] exits for reason[consumer[consu    mer-934-9] failed to map with error:[]]]]]]
2020-10-22 13:16:19,657-WARNING: recv endsignal from outq with errmsg[consumer[consumer-934-15] exits for reason[consumer[consu    mer-934-13] exits for reason[consumer[consumer-934-1] exits for reason[consumer[consumer-934-10] exits for reason[consumer[cons    umer-934-5] exits for reason[consumer[consumer-934-9] failed to map with error:[]]]]]]]
2020-10-22 13:16:26,541-WARNING: recv endsignal from outq with errmsg[consumer[consumer-934-4] exits for reason[consumer[consum    er-934-15] exits for reason[consumer[consumer-934-13] exits for reason[consumer[consumer-934-1] exits for reason[consumer[consu    mer-934-10] exits for reason[consumer[consumer-934-5] exits for reason[consumer[consumer-934-9] failed to map with error:[]]]]]    ]]]
2020-10-22 13:16:33,607-WARNING: recv endsignal from outq with errmsg[consumer[consumer-934-6] exits for reason[consumer[consum    er-934-4] exits for reason[consumer[consumer-934-15] exits for reason[consumer[consumer-934-13] exits for reason[consumer[consu    mer-934-1] exits for reason[consumer[consumer-934-10] exits for reason[consumer[consumer-934-5] exits for reason[consumer[consu    mer-934-9] failed to map with error:[]]]]]]]]]
2020-10-22 13:16:41,173-WARNING: recv endsignal from outq with errmsg[consumer[consumer-934-7] exits for reason[consumer[consum    er-934-6] exits for reason[consumer[consumer-934-4] exits for reason[consumer[consumer-934-15] exits for reason[consumer[consum    er-934-13] exits for reason[consumer[consumer-934-1] exits for reason[consumer[consumer-934-10] exits for reason[consumer[consu    mer-934-5] exits for reason[consumer[consumer-934-9] failed to map with error:[]]]]]]]]]]
2020-10-22 13:16:49,306-WARNING: recv endsignal from outq with errmsg[consumer[consumer-934-0] exits for reason[consumer[consum    er-934-7] exits for reason[consumer[consumer-934-6] exits for reason[consumer[consumer-934-4] exits for reason[consumer[consume    r-934-15] exits for reason[consumer[consumer-934-13] exits for reason[consumer[consumer-934-1] exits for reason[consumer[consum    er-934-10] exits for reason[consumer[consumer-934-5] exits for reason[consumer[consumer-934-9] failed to map with error:[]]]]]]    ]]]]]
2020-10-22 13:17:00,355-WARNING: recv endsignal from outq with errmsg[consumer[consumer-934-3] exits for reason[consumer[consum    er-934-0] exits for reason[consumer[consumer-934-7] exits for reason[consumer[consumer-934-6] exits for reason[consumer[consume    r-934-4] exits for reason[consumer[consumer-934-15] exits for reason[consumer[consumer-934-13] exits for reason[consumer[consum    er-934-1] exits for reason[consumer[consumer-934-10] exits for reason[consumer[consumer-934-5] exits for reason[consumer[consum    er-934-9] failed to map with error:[]]]]]]]]]]]]
2020-10-22 13:17:15,365-WARNING: recv endsignal from outq with errmsg[consumer[consumer-934-8] exits for reason[consumer[consum    er-934-3] exits for reason[consumer[consumer-934-0] exits for reason[consumer[consumer-934-7] exits for reason[consumer[consume    r-934-6] exits for reason[consumer[consumer-934-4] exits for reason[consumer[consumer-934-15] exits for reason[consumer[consume    r-934-13] exits for reason[consumer[consumer-934-1] exits for reason[consumer[consumer-934-10] exits for reason[consumer[consum    er-934-5] exits for reason[consumer[consumer-934-9] failed to map with error:[]]]]]]]]]]]]]
2020-10-22 13:17:30,909-WARNING: recv endsignal from outq with errmsg[consumer[consumer-934-12] exits for reason[consumer[consu    mer-934-8] exits for reason[consumer[consumer-934-3] exits for reason[consumer[consumer-934-0] exits for reason[consumer[consum    er-934-7] exits for reason[consumer[consumer-934-6] exits for reason[consumer[consumer-934-4] exits for reason[consumer[consume    r-934-15] exits for reason[consumer[consumer-934-13] exits for reason[consumer[consumer-934-1] exits for reason[consumer[consum    er-934-10] exits for reason[consumer[consumer-934-5] exits for reason[consumer[consumer-934-9] failed to map with error:[]]]]]]    ]]]]]]]]
2020-10-22 13:17:51,998-WARNING: recv endsignal from outq with errmsg[consumer[consumer-934-2] exits for reason[consumer[consum    er-934-12] exits for reason[consumer[consumer-934-8] exits for reason[consumer[consumer-934-3] exits for reason[consumer[consum    er-934-0] exits for reason[consumer[consumer-934-7] exits for reason[consumer[consumer-934-6] exits for reason[consumer[consume    r-934-4] exits for reason[consumer[consumer-934-15] exits for reason[consumer[consumer-934-13] exits for reason[consumer[consum    er-934-1] exits for reason[consumer[consumer-934-10] exits for reason[consumer[consumer-934-5] exits for reason[consumer[consum    er-934-9] failed to map with error:[]]]]]]]]]]]]]]]
2020-10-22 13:18:26,156-WARNING: recv endsignal from outq with errmsg[consumer[consumer-934-11] exits for reason[consumer[consu    mer-934-2] exits for reason[consumer[consumer-934-12] exits for reason[consumer[consumer-934-8] exits for reason[consumer[consu    mer-934-3] exits for reason[consumer[consumer-934-0] exits for reason[consumer[consumer-934-7] exits for reason[consumer[consum    er-934-6] exits for reason[consumer[consumer-934-4] exits for reason[consumer[consumer-934-15] exits for reason[consumer[consum    er-934-13] exits for reason[consumer[consumer-934-1] exits for reason[consumer[consumer-934-10] exits for reason[consumer[consu    mer-934-5] exits for reason[consumer[consumer-934-9] failed to map with error:[]]]]]]]]]]]]]]]]
2020-10-22 13:19:30,706-WARNING: recv endsignal from outq with errmsg[consumer[consumer-934-14] exits for reason[consumer[consu    mer-934-11] exits for reason[consumer[consumer-934-2] exits for reason[consumer[consumer-934-12] exits for reason[consumer[cons    umer-934-8] exits for reason[consumer[consumer-934-3] exits for reason[consumer[consumer-934-0] exits for reason[consumer[consu    mer-934-7] exits for reason[consumer[consumer-934-6] exits for reason[consumer[consumer-934-4] exits for reason[consumer[consum    er-934-15] exits for reason[consumer[consumer-934-13] exits for reason[consumer[consumer-934-1] exits for reason[consumer[consu    mer-934-10] exits for reason[consumer[consumer-934-5] exits for reason[consumer[consumer-934-9] failed to map with error:[]]]]]    ]]]]]]]]]]]]
2020-10-22 13:19:30,715-WARNING: Your reader has raised an exception!
Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/reader.py", line 1145, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/reader.py", line 1125, in __thread_main__
    for tensors in self._tensor_reader():
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/reader.py", line 1195, in __tensor_reader_impl__
    for slots in paddle_reader():
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/data_feeder.py", line 506, in __reader_creator__
    for item in reader():
  File "/paddle/PaddleDetection/ppdet/data/reader.py", line 452, in _reader
    reader.reset()
  File "/paddle/PaddleDetection/ppdet/data/parallel_map.py", line 259, in reset
    assert not self._exit, "cannot reset for already stopped dataset"
AssertionError: cannot reset for already stopped dataset

/usr/local/lib/python3.6/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF except    ion.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tools/train.py", line 372, in <module>
    main()
  File "tools/train.py", line 245, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1167, in _run_impl
    return_merged=return_merged)
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/executor.py", line 879, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTen    sor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::L    oDTensor> >*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), st    d::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_D    eleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_ba    se::_Result_base::_Deleter> ()>&, bool&)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/reader.py", line 1080, in _init_non_iterable
    attrs={'drop_last': self._drop_last})
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/reader.py", line 978, in __init__
    self._init_non_iterable()
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/reader.py", line 620, in from_generator
    iterable, return_list, drop_last)
  File "/paddle/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 155, in build_inputs
    iterable=iterable) if use_dataloader else None
  File "tools/train.py", line 116, in main
    feed_vars, train_loader = model.build_inputs(**inputs_def)
  File "tools/train.py", line 372, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.    h:141)
  [operator < read > error]

```

----------------------
版本信息：Python 3.6.0，paddle版本：1.8.4.post107 GPU版
----------------------

----------------------
问题描述：在训练yolov3和PPyolo的过程中内存占用一直增加，直到内存溢出。
----------------------

----------------------
原因分析：

之前训练网络一直没有问题，然后在某个莫名时刻，再次开启网络训练就开始内存占用不断增加，直到溢出了。
还以为是配置问题，或者不小心更改了某些代码。重新配置后依然不能解决问题。
然后冥思苦想究竟有何变化。
突然想到之前为了装tensorflow1.14版本被迫将numpy退更回了1.16版本。于是迅速行动，numpy更新会1.19版本，问题完美解决，内存占用再也不一直涨了。

----------------------

paddlepaddle-gpu | 1.8.4.post107 |  
-- | -- | --

**Comment by qingqing01** [comment]
@Jorsen0  

您是说Numpy 1.19版本不会出现内存增长直到溢出的现象吗？另外，请问下你是几张卡训练？config中配置的worker_num和bufsize分别是多大？

**Comment by heavengate** [comment]
您好，请问一下你的机器上内存大小是多少，可以跑下`free -h`看下

**Comment by Jorsen0** [comment]
> @Jorsen0
> 
> 您是说Numpy 1.19版本不会出现内存增长直到溢出的现象吗？另外，请问下你是几张卡训练？config中配置的worker_num和bufsize分别是多大？

不是的，我指的是我的paddle版本可能和numpy1.16版本兼容性存在问题。当时用的4张卡，work_num=16，bufsize=8，内存250G。不过我感觉和这3个配置关系不大，因为用1.16版本的时候我试着降低课work_num和bufsize，依然内存一直增长，直到内存溢出。更新成numpy1.19，内存占用维持在25G左右，就稳定了。

**Comment by Jorsen0** [comment]
> 您好，请问一下你的机器上内存大小是多少，可以跑下`free -h`看下

内存250G呢

**Comment by funny000** [comment]
这个应该是和本机内存大小有关系吧。
