### ISSUE TITLE
自己设计的mask_rcnn类型的网络提示如下错误

### ISSUE THREAD

**Issue by a2824256** [PaddlePaddle/PaddleDetection#1612]
自己设计的网络训练一会就会报错，请问能从中看到问题可能出现在哪吗？
```
2020-10-27 15:23:44,433-INFO: iter: 460, lr: 0.000100, 'loss_cls': '0.011143', 'loss_bbox': '0.000000', 'loss_rpn_cls': '0.000000', 'loss_mask': '0.000000', 'loss': '0.398923', time: 0.
140, eta: 0:03:34
2020-10-27 15:23:47,205-INFO: iter: 480, lr: 0.000100, 'loss_cls': '0.006551', 'loss_bbox': '0.000000', 'loss_rpn_cls': '0.000000', 'loss_mask': '0.000000', 'loss': '0.513409', time: 0.
139, eta: 0:03:31
E:\ProgramData\Miniconda3\envs\ppdet\lib\site-packages\paddle\fluid\executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "./tools/train.py", line 373, in <module>
    main()
  File "./tools/train.py", line 246, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "E:\ProgramData\Miniconda3\envs\ppdet\lib\site-packages\paddle\fluid\executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "E:\ProgramData\Miniconda3\envs\ppdet\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "E:\ProgramData\Miniconda3\envs\ppdet\lib\site-packages\paddle\fluid\executor.py", line 1066, in run
    return_merged=return_merged)
  File "E:\ProgramData\Miniconda3\envs\ppdet\lib\site-packages\paddle\fluid\executor.py", line 1167, in _run_impl
    return_merged=return_merged)
  File "E:\ProgramData\Miniconda3\envs\ppdet\lib\site-packages\paddle\fluid\executor.py", line 879, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "E:\ProgramData\Miniconda3\envs\ppdet\lib\site-packages\paddle\fluid\framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "E:\ProgramData\Miniconda3\envs\ppdet\lib\site-packages\paddle\fluid\layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "E:\ProgramData\Miniconda3\envs\ppdet\lib\site-packages\paddle\fluid\layers\nn.py", line 9316, in gather
    attrs={'overwrite': overwrite})
  File "E:\ProgramData\Miniconda3\envs\ppdet\lib\site-packages\paddle\fluid\layers\detection.py", line 466, in rpn_target_assign
    predicted_cls_logits = nn.gather(cls_logits, score_index)
  File "D:\PaddleDetection-release-0.4\ppdet\core\workspace.py", line 174, in partial_apply
    return op(*args, **kwargs_)
  File "D:\PaddleDetection-release-0.4\ppdet\modeling\anchor_heads\rpn_head.py", line 228, in get_loss
    im_info=im_info)
  File "D:\PaddleDetection-release-0.4\ppdet\modeling\architectures\mask_rcnn_pam.py", line 154, in build
    rpn_loss5 = self.rpn_head_l2.get_loss(im_info, feed_vars['gt_bbox'], feed_vars['is_crowd'])
  File "D:\PaddleDetection-release-0.4\ppdet\modeling\architectures\mask_rcnn_pam.py", line 401, in train
    return self.build(feed_vars, 'train')
  File "./tools/train.py", line 118, in main
    train_fetches = model.train(feed_vars)
  File "./tools/train.py", line 373, in <module>
    main()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The index of gather_op should not be emptywhen the index's rank is 1.
  [Hint: Expected index.dims()[0] > 0, but received index.dims()[0]:0 <= 0:0.] at (D:/1.8.5/paddle\paddle/fluid/operators/gather.cu.h:79)
  [operator < gather > error]
```

**Comment by a2824256** [comment]
配置文件学习率调整为如下后，程序会突然结束，每次都是执行到480就报错
![image](https://user-images.githubusercontent.com/7108023/97270312-ec4c7b00-1869-11eb-9b75-e4c4f8eedd5e.png)

![image](https://user-images.githubusercontent.com/7108023/97270203-c0c99080-1869-11eb-8108-436248495de9.png)

**Comment by a2824256** [comment]
配置文件
```
architecture: IMPMaskRCNN
use_gpu: true
max_iters: 2000
snapshot_iter: 2000
log_smooth_window: 20
save_dir: output
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_cos_pretrained.tar
metric: COCO
weights: output/mask_rcnn_r50_fpn_1x/model_final
num_classes: 81

IMPMaskRCNN:
  backbone: ResNet
  fpn: FPN
  rpn_head_s1: FPNRPNHeadS
  rpn_head_s2: FPNRPNHeadS
  rpn_head_m: FPNRPNHeadM
  rpn_head_l1: FPNRPNHeadL
  rpn_head_l2: FPNRPNHeadL
  roi_extractor: FPNRoIAlign
  bbox_head: BBoxHead
  bbox_assigner: BBoxAssigner

ResNet:
  depth: 50
  feature_maps: [2, 3, 4, 5]
  freeze_at: 2
  norm_type: bn

FPN:
  max_level: 6
  min_level: 2
  num_chan: 256
  spatial_scale: [0.03125, 0.0625, 0.125, 0.25]

FPNRPNHeadS:
  anchor_generator:
    aspect_ratios: [0.5, 1.0, 2.0]
    variance: [1.0, 1.0, 1.0, 1.0]
  anchor_start_size: 32
  max_level: 1
  min_level: 1
  num_chan: 256
  rpn_target_assign:
    rpn_batch_size_per_im: 256
    rpn_fg_fraction: 0.5
    rpn_negative_overlap: 0.3
    rpn_positive_overlap: 0.7
    rpn_straddle_thresh: 0.0
  train_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 400
    post_nms_top_n: 400
  test_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 200
    post_nms_top_n: 200


FPNRPNHeadM:
  anchor_generator:
    aspect_ratios: [0.5, 1.0, 2.0]
    variance: [1.0, 1.0, 1.0, 1.0]
  anchor_start_size: 32
  max_level: 1
  min_level: 1
  num_chan: 256
  rpn_target_assign:
    rpn_batch_size_per_im: 256
    rpn_fg_fraction: 0.5
    rpn_negative_overlap: 0.3
    rpn_positive_overlap: 0.7
    rpn_straddle_thresh: 0.0
  train_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 400
    post_nms_top_n: 400
  test_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 200
    post_nms_top_n: 200


FPNRPNHeadL:
  anchor_generator:
    aspect_ratios: [0.5, 1.0, 2.0]
    variance: [1.0, 1.0, 1.0, 1.0]
  anchor_start_size: 32
  max_level: 1
  min_level: 1
  num_chan: 256
  rpn_target_assign:
    rpn_batch_size_per_im: 256
    rpn_fg_fraction: 0.5
    rpn_negative_overlap: 0.3
    rpn_positive_overlap: 0.7
    rpn_straddle_thresh: 0.0
  train_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 400
    post_nms_top_n: 400
  test_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 200
    post_nms_top_n: 200

FPNRoIAlign:
  canconical_level: 4
  canonical_size: 224
  max_level: 5
  min_level: 2
  sampling_ratio: 2
  box_resolution: 7
  mask_resolution: 14


MaskHead:
  dilation: 1
  conv_dim: 256
  num_convs: 4
  resolution: 28

BBoxAssigner:
  batch_size_per_im: 512
  bbox_reg_weights: [0.1, 0.1, 0.2, 0.2]
  bg_thresh_hi: 0.5
  bg_thresh_lo: 0.0
  fg_fraction: 0.25
  fg_thresh: 0.5

MaskAssigner:
  resolution: 28

BBoxHead:
  head: TwoFCHead
  nms:
    keep_top_k: 100
    nms_threshold: 0.5
    score_threshold: 0.05

TwoFCHead:
  mlp_dim: 1024

LearningRate:
  base_lr: 0.0001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [1000, 1500]
  - !LinearWarmup
    start_factor: 0.03
    steps: 100

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2

_READER_: 'mask_fpn_reader.yml'
```

**Comment by jerrywgz** [comment]
我看使用了新的一个architecture，代码上有什么改动吗

**Comment by a2824256** [comment]
@jerrywgz 主要是做了以下几点改动
1. mask_rcnn_r50_fpn_1x基础上，将fpn输出的5个特征图分别放入三种rpn_head, 前两层特征图放到用FPNRPNHeadS，中间的一层用FPNRPNHeadM，最后两层用FPNRPNHeadL。目前这三种还没有区别，因为配置一样。然后将5个经过FPNRPNHeadX(X代表S、M、L三种)的rois用collect_fpn_proposals合并成为一个rois集合，然后loss用get_loss方法计算出分别的loss_rpn_cls和loss_rpn_bbox，再用fluid.layers.mean来计算(这里好像这样算不太合理)。
2. 在FPN上面加了一个自己设计的注意力模块，但这个可以正常训练。
-----------------------------------------------------------------------------------
架构文件代码：
https://github.com/a2824256/Improved-Mask-RCNN/blob/main/mask_rcnn_pam_new.py
加了FPNRPNHeadX的rpn_head代码：
https://github.com/a2824256/Improved-Mask-RCNN/blob/main/rpn_head.py
加了注意力模块的FPN代码：
https://github.com/a2824256/Improved-Mask-RCNN/blob/main/fpn.py
配置文件代码：
https://github.com/a2824256/Improved-Mask-RCNN/blob/main/mask_rcnn_r50_fpn_pam_1x.yml

**Comment by a2824256** [comment]
顺便请教一个问题，我5个FPNRPNHeadX，loss能否分开用loss.update()这样处理？

**Comment by jerrywgz** [comment]
这里的gather是rpn_target_assign里的，这一步是根据选择正负样本后的anchor得到对应的训练target，如果这里为空说明rpn部分没有找到正样本anchor。可以尝试将几个rpn的输出cls和box结果concat在一起然后一起计算loss

**Comment by a2824256** [comment]
好的，感谢，我先尝试一下

**Comment by a2824256** [comment]
已解决

**Comment by Chen-Song** [comment]
@a2824256 请问怎么解决的呢？
