### ISSUE TITLE
模型量化报错

### ISSUE THREAD

**Issue by HelloAI-twj** [PaddlePaddle/PaddleDetection#1623]
我在使用paddledetection进行模型量化的时候报错
我使用的代码是：
!python slim/quantization/train.py --not_quant_pattern yolo_output \
    --eval \
    -c configs/yolov4/yolov4_cspdarknet_voc.yml \
    -o max_iters=30000 \
    save_dir=./output/mobilenetv1 \
    LearningRate.base_lr=0.0001 \
    LearningRate.schedulers="[!PiecewiseDecay {gamma: 0.1, milestones: [10000]}]" \
    pretrain_weights=output/yolov4_cspdarknet_voc/model_final

报错提示如下：
```
[10-28 20:34:26 MainThread @logger.py:224] Argv: slim/quantization/train.py --not_quant_pattern yolo_output --eval -c configs/yolov4/yolov4_cspdarknet_voc.yml -o max_iters=30000 save_dir=./output/mobilenetv1 LearningRate.base_lr=0.0001 LearningRate.schedulers=[!PiecewiseDecay {gamma: 0.1, milestones: [10000]}] pretrain_weights=output/yolov4_cspdarknet_voc/model_final
/opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pandas/core/tools/datetimes.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/rcsetup.py:20: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, Mapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/colors.py:53: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Sized
/opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/clip.py:779: UserWarning: Caution! 'set_gradient_clip' is not recommended and may be deprecated in future! We recommend a new strategy: set 'grad_clip' when initializing the 'optimizer'. This method can reduce the mistakes, please refer to documention of 'optimizer'.
  warnings.warn("Caution! 'set_gradient_clip' is not recommended "
2020-10-28 20:34:30,337-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000500] in Optimizer will not take effect, and it will only be applied to other Parameters!
2020-10-28 20:34:33,437-INFO: places would be ommited when DataLoader is not iterable
W1028 20:34:33.503239  2727 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 9.0
W1028 20:34:33.508147  2727 device_context.cc:260] device: 0, cuDNN Version: 7.6.
2020-10-28 20:34:38,708-WARNING: variable yolo_output.2.conv.0.conv.weights not used
2020-10-28 20:34:38,708-WARNING: variable yolo_block.stack_conv.1.0.bn.mean not used
2020-10-28 20:34:38,708-WARNING: variable yolo_block.stack_conv.1.3.conv.weights not used
2020-10-28 20:34:38,708-WARNING: variable yolo_block.stack_conv.1.2.bn.var not used
2020-10-28 20:34:38,708-WARNING: variable yolo_block.stack_conv.2.4.bn.var not used
2020-10-28 20:34:38,708-WARNING: variable yolo_block.stack_conv.2.1.conv.weights not used
2020-10-28 20:34:38,708-WARNING: variable yolo_block.stack_conv.2.0.bn.mean not used
2020-10-28 20:34:38,708-WARNING: variable yolo_block.stack_conv.2.0.bn.var not used
2020-10-28 20:34:38,708-WARNING: variable yolo_block.route.2.conv.weights not used
2020-10-28 20:34:38,708-WARNING: variable yolo_block.stack_conv.1.4.bn.offset not used
2020-10-28 20:34:38,708-WARNING: variable yolo_block.stack_conv.1.2.bn.offset not used
2020-10-28 20:34:38,708-WARNING: variable yolo_block.stack_conv.2.2.conv.weights not used
2020-10-28 20:34:38,708-WARNING: variable yolo_block.stack_conv.2.2.bn.offset not used
2020-10-28 20:34:38,708-WARNING: variable yolo_block.stack_conv.2.3.bn.offset not used
2020-10-28 20:34:38,708-WARNING: variable yolo_block.stack_conv.2.2.bn.scale not used
2020-10-28 20:34:38,708-WARNING: variable yolo_block.stack_conv.1.3.bn.mean not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.1.3.bn.scale not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.2.0.bn.scale not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.1.1.bn.mean not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.2.0.bn.offset not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.2.3.bn.var not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.1.2.bn.scale not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.1.3.bn.offset not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.2.1.bn.mean not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.2.3.bn.scale not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.2.3.conv.weights not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.2.4.conv.weights not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.2.1.bn.scale not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.1.4.bn.scale not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.1.0.conv.weights not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.2.1.bn.offset not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.1.1.conv.weights not used
2020-10-28 20:34:38,709-WARNING: variable yolo_output.1.conv.0.conv.weights not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.2.4.bn.mean not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.1.2.conv.weights not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.2.2.bn.mean not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.2.4.bn.scale not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.1.0.bn.scale not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.2.4.bn.offset not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.2.0.conv.weights not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.1.1.bn.offset not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.1.1.bn.scale not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.1.4.bn.mean not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.1.4.bn.var not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.2.2.bn.var not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.1.3.bn.var not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.1.1.bn.var not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.1.4.conv.weights not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.1.0.bn.var not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.1.2.bn.mean not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.2.3.bn.mean not used
2020-10-28 20:34:38,709-WARNING: variable yolo_block.stack_conv.1.0.bn.offset not used
2020-10-28 20:34:38,710-WARNING: variable yolo_block.stack_conv.2.1.bn.var not used
2020-10-28 20:34:38,938-INFO: quant_aware config {'weight_quantize_type': 'channel_wise_abs_max', 'activation_quantize_type': 'moving_average_abs_max', 'weight_bits': 8, 'activation_bits': 8, 'not_quant_pattern': ['yolo_output'], 'quantize_op_types': ['depthwise_conv2d', 'mul', 'conv2d'], 'dtype': 'int8', 'window_size': 10000, 'moving_rate': 0.9, 'for_tensorrt': False, 'is_full_quantize': False}
2020-10-28 20:41:42,992-INFO: quant_aware config {'weight_quantize_type': 'channel_wise_abs_max', 'activation_quantize_type': 'moving_average_abs_max', 'weight_bits': 8, 'activation_bits': 8, 'not_quant_pattern': ['yolo_output'], 'quantize_op_types': ['depthwise_conv2d', 'mul', 'conv2d'], 'dtype': 'int8', 'window_size': 10000, 'moving_rate': 0.9, 'for_tensorrt': False, 'is_full_quantize': False}
2020-10-28 20:42:05,516-INFO: places would be ommited when DataLoader is not iterable
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "slim/quantization/train.py", line 317, in <module>
    main()
  File "slim/quantization/train.py", line 241, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1156, in _run_impl
    program._compile(scope, self.place)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/compiler.py", line 443, in _compile
    places=self._places)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/compiler.py", line 396, in _compile_data_parallel
    self._exec_strategy, self._build_strategy, self._graph)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
3   paddle::framework::details::BuildStrategy::Apply(paddle::framework::ir::Graph*, std::vector<paddle::platform::Place, std::allocator<paddle::platform::Place> > const&, std::string const&, std::vector<paddle::framework::Scope*, std::allocator<paddle::framework::Scope*> > const&, unsigned long const&, bool, paddle::platform::NCCLCommunicator*) const
4   paddle::framework::ParallelExecutor::ParallelExecutor(std::vector<paddle::platform::Place, std::allocator<paddle::platform::Place> > const&, std::vector<std::string, std::allocator<std::string> > const&, std::string const&, paddle::framework::Scope*, std::vector<paddle::framework::Scope*, std::allocator<paddle::framework::Scope*> > const&, paddle::framework::details::ExecutionStrategy const&, paddle::framework::details::BuildStrategy const&, paddle::framework::ir::Graph*)

----------------------
Error Message Summary:
----------------------
Error: Illegal Pass fuse_elewise_add_act_pass. Generated graph shouldn't have cycle. at (/paddle/paddle/fluid/framework/ir/pass.cc:44)

/home/aistudio/PaddleDetection/ppdet/data/parallel_map.py:214: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn(errmsg)
2020-10-28 20:42:11,464-WARNING: consumer[3033] exit abnormally with exitcode[1]
2020-10-28 20:42:11,465-WARNING: consumer[3035] exit abnormally with exitcode[1]
2020-10-28 20:42:11,465-WARNING: consumer[3036] exit abnormally with exitcode[1]
/home/aistudio/PaddleDetection/ppdet/data/parallel_map.py:218: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  .format(abnormal_num))
2020-10-28 20:42:11,465-WARNING: 3 consumers have exited abnormally!!!
2020-10-28 20:42:11,465-WARNING: consumer[3033] exit abnormally with exitcode[1]
2020-10-28 20:42:11,465-WARNING: consumer[3035] exit abnormally with exitcode[1]
2020-10-28 20:42:11,465-WARNING: consumer[3036] exit abnormally with exitcode[1]
2020-10-28 20:42:11,465-WARNING: 3 consumers have exited abnormally!!!
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py:1144: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
  logging.warn('Your reader has raised an exception!')
2020-10-28 20:42:11,466-WARNING: Your reader has raised an exception!
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1145, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1125, in __thread_main__
    for tensors in self._tensor_reader():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1195, in __tensor_reader_impl__
    for slots in paddle_reader():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 506, in __reader_creator__
    for item in reader():
  File "/home/aistudio/PaddleDetection/ppdet/data/reader.py", line 445, in _reader
    reader.reset()
  File "/home/aistudio/PaddleDetection/ppdet/data/parallel_map.py", line 267, in reset
    assert self._consumer_healthy(), "cannot start another pass of data" \
AssertionError: cannot start another pass of data for some consumers exited abnormally before!!!
```
想请问一下怎么解决呢

**Comment by willthefrog** [comment]
可否提供下版本信息？

**Comment by HelloAI-twj** [comment]
> 可否提供下版本信息？

paddledetection用的是release0.4,paddleslim是1.2.0

**Comment by willthefrog** [comment]
paddle 版本？

**Comment by HelloAI-twj** [comment]
> paddle 版本？

1.8.4

**Comment by baiyfbupt** [comment]
看报错信息是fuse_elewise_add_act_pass引起的，    在代码中配置下`build_strategy.fuse_elewise_add_act_ops = False`试下呢

**Comment by HelloAI-twj** [comment]
> build_strategy.fuse_elewise_add_act_ops = False

改了后还是同样的报错

**Comment by HelloAI-twj** [comment]
> build_strategy.fuse_elewise_add_act_ops = False

改了后还是同样的报错

**Comment by baiyfbupt** [comment]
> paddledetection用的是release0.4,paddleslim是1.2.0
您使PaddleDetection库的最后commit id是？

**Comment by HelloAI-twj** [comment]
> > paddledetection用的是release0.4,paddleslim是1.2.0
> 
> 您使PaddleDetection库的最后commit id是？

commit id 是指？我是刚接触这个可能有些东西还不太了解

**Comment by qingqing01** [comment]
可以试用下最新版本，如果还有问题，我们继续解决~
