### ISSUE TITLE
windows部署serving时报错，ModuleNotFoundError: No module named 'fcntl'

### ISSUE THREAD

**Issue by TigerKylin** [PaddlePaddle/PaddleDetection#1644]
执行python -m paddle_serving_server.serve --model serving_server --port 9393时，报错：

```
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "E:\vitualenv\paddledetection\lib\site-packages\paddle_serving_server\__init__.py", line 26, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'
```

**Comment by qingqing01** [comment]
@TigerKylin pip install fcntl安装下，看下呢？

**Comment by qingqing01** [comment]
@TigerKylin  fcntl是Linux上的库，Windows上支持，我们看下。

**Comment by liuhuiCNN** [comment]
@TigerKylin 该问题是PaddleServing中使用到了fcntl库，windows中python库中没有这个库。问题已转到  https://github.com/PaddlePaddle/Serving/issues/867，感谢反馈。

**Comment by duolabmeng6** [comment]
请问怎么解决
