### ISSUE TITLE
module 'paddle' has no attribute 'enable_static'

### ISSUE THREAD

**Issue by Dabulv** [PaddlePaddle/PaddleDetection#1683]
Traceback (most recent call last):
  File "/home/work/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/work//anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/work//PaddleDetection/ppdet/modeling/tests/test_architectures.py", line 94, in <module>
    paddle.enable_static()
AttributeError: module 'paddle' has no attribute 'enable_static'

**Comment by jerrywgz** [comment]
这里需要更新paddle版本至2.0rc
