### ISSUE TITLE
PP-YOLO inference by batch

### ISSUE THREAD

**Issue by p1n0cch10** [PaddlePaddle/PaddleDetection#1694]
Hi,

I am using ppyolo for inference. But when I set batch_size more than 1 in ppyolo_reader.yml, an error occurs.

My command is
`python tools/infer_renqun.py  -c config    s/ppyolo/ppyolo.yml -o weights=model/ppyolo.pdparams --infer_dir=demo`

The los is
```
`/home/ecom/liuxiang12/env/tf_yolo/lib/python3.6/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tools/infer_renqun.py", line 298, in <module>
    main()
  File "tools/infer_renqun.py", line 184, in main
    return_numpy=False)
  File "/home/ecom/liuxiang12/env/tf_yolo/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/home/ecom/.local/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/ecom/liuxiang12/env/tf_yolo/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/home/ecom/liuxiang12/env/tf_yolo/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/ecom/liuxiang12/env/tf_yolo/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1229, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::ConcatOp::InferShape(paddle::framework::InferShapeContext*) const
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
5   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
6   paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
7   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
8   paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/ecom/liuxiang12/env/tf_yolo/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/ecom/liuxiang12/env/tf_yolo/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/ecom/liuxiang12/env/tf_yolo/lib/python3.6/site-packages/paddle/fluid/layers/tensor.py", line 375, in concat
    type='concat', inputs=inputs, outputs={'Out': [out]}, attrs=attrs)
  File "/home/ecom/liuxiang12/code/profession_detection/paddle/PaddleDetection/ppdet/modeling/anchor_heads/yolo_head.py", line 158, in _add_coord
    return fluid.layers.concat([input, x_range, y_range], axis=1)
  File "/home/ecom/liuxiang12/code/profession_detection/paddle/PaddleDetection/ppdet/modeling/anchor_heads/yolo_head.py", line 235, in _detection_block
    conv = self._add_coord(conv, is_test=is_test)
  File "/home/ecom/liuxiang12/code/profession_detection/paddle/PaddleDetection/ppdet/modeling/anchor_heads/yolo_head.py", line 345, in _get_outputs
    name=self.prefix_name + "yolo_block.{}".format(i))
  File "/home/ecom/liuxiang12/code/profession_detection/paddle/PaddleDetection/ppdet/modeling/anchor_heads/yolo_head.py", line 419, in get_prediction
    outputs = self._get_outputs(input, is_train=False)
  File "/home/ecom/liuxiang12/code/profession_detection/paddle/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 93, in build
    body_feats, im_size, exclude_nms=exclude_nms)
  File "/home/ecom/liuxiang12/code/profession_detection/paddle/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 165, in test
    return self.build(feed_vars, mode='test', exclude_nms=exclude_nms)
  File "tools/infer_renqun.py", line 122, in main
    test_fetches = model.test(feed_vars)
  File "tools/infer_renqun.py", line 298, in <module>
    main()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The 0-th dimension of input[0] and input[1] is expected to be equal.But received input[0]'s shape = [5, 2048, 19, 19], input[1]'s shape = [1, 1, 19, 19].
  [Hint: Expected inputs_dims[0][j] == inputs_dims[i][j], but received inputs_dims[0][j]:5 != inputs_dims[i][j]:1.] at (/paddle/paddle/fluid/operators/concat_op.h:63)
  [operator < concat > error]
terminate called without an active exception
W1112 21:22:41.268883 113379 init.cc:226] Warning: PaddlePaddle catches a failure signal, it may not work properly
W1112 21:22:41.268939 113379 init.cc:228] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W1112 21:22:41.268956 113379 init.cc:231] The detail failure signal is:

W1112 21:22:41.268970 113379 init.cc:234] *** Aborted at 1605187361 (unix time) try "date -d @1605187361" if you are using GNU date ***
W1112 21:22:41.272145 113379 init.cc:234] PC: @                0x0 (unknown)
W1112 21:22:41.272285 113379 init.cc:234] *** SIGABRT (@0x1f80001b538) received by PID 111928 (TID 0x7f14dfa3a700) from PID 111928; stack trace: ***
W1112 21:22:41.274392 113379 init.cc:234]     @     0x7f1550c87500 (unknown)
W1112 21:22:41.277282 113379 init.cc:234]     @     0x7f15509188a5 __GI_raise
W1112 21:22:41.279474 113379 init.cc:234]     @     0x7f155091a085 __GI_abort
W1112 21:22:41.280947 113379 init.cc:234]     @     0x7f145c34c892 __gnu_cxx::__verbose_terminate_handler()
W1112 21:22:41.282047 113379 init.cc:234]     @     0x7f145c34af69 __cxxabiv1::__terminate()
W1112 21:22:41.283306 113379 init.cc:234]     @     0x7f145c34afab std::terminate()
W1112 21:22:41.284548 113379 init.cc:234]     @     0x7f145c34ac7c __gxx_personality_v0
W1112 21:22:41.286187 113379 init.cc:234]     @     0x7f1547c54bc8 _Unwind_ForcedUnwind_Phase2
W1112 21:22:41.287925 113379 init.cc:234]     @     0x7f1547c54eae _Unwind_ForcedUnwind
W1112 21:22:41.289738 113379 init.cc:234]     @     0x7f1550c85c80 __GI___pthread_unwind
W1112 21:22:41.291528 113379 init.cc:234]     @     0x7f1550c7ff25 __pthread_exit
W1112 21:22:41.293741 113379 init.cc:234]     @     0x7f155127eb59 PyThread_exit_thread
W1112 21:22:41.295708 113379 init.cc:234]     @     0x7f155111f5e9 PyEval_RestoreThread.cold.759
W1112 21:22:41.295961 113379 init.cc:234]     @     0x7f14574a8cde (unknown)
W1112 21:22:41.297996 113379 init.cc:234]     @     0x7f1551241500 call_function
W1112 21:22:41.300132 113379 init.cc:234]     @     0x7f155126fcaa _PyEval_EvalFrameDefault
W1112 21:22:41.302067 113379 init.cc:234]     @     0x7f15511b774b _PyEval_EvalCodeWithName
W1112 21:22:41.304194 113379 init.cc:234]     @     0x7f15511b8f4d _PyFunction_FastCallDict
W1112 21:22:41.306232 113379 init.cc:234]     @     0x7f1551241e41 method_call
W1112 21:22:41.308352 113379 init.cc:234]     @     0x7f15511bd5ae PyObject_Call
W1112 21:22:41.310374 113379 init.cc:234]     @     0x7f155123bb66 slot_tp_call
W1112 21:22:41.312464 113379 init.cc:234]     @     0x7f155124079c _PyObject_FastCallKeywords
W1112 21:22:41.314512 113379 init.cc:234]     @     0x7f1551241481 call_function
W1112 21:22:41.316735 113379 init.cc:234]     @     0x7f155126fcaa _PyEval_EvalFrameDefault
W1112 21:22:41.318931 113379 init.cc:234]     @     0x7f15511b8d04 _PyFunction_FastCallDict
W1112 21:22:41.321065 113379 init.cc:234]     @     0x7f1551241e41 method_call
W1112 21:22:41.323312 113379 init.cc:234]     @     0x7f15511bd5ae PyObject_Call
W1112 21:22:41.325407 113379 init.cc:234]     @     0x7f155123bb66 slot_tp_call
W1112 21:22:41.327559 113379 init.cc:234]     @     0x7f155124079c _PyObject_FastCallKeywords
W1112 21:22:41.329676 113379 init.cc:234]     @     0x7f1551241481 call_function
W1112 21:22:41.331867 113379 init.cc:234]     @     0x7f155126fcaa _PyEval_EvalFrameDefault
W1112 21:22:41.334444 113379 init.cc:234]     @     0x7f15511b774b _PyEval_EvalCodeWithName`
```

**Comment by yghstill** [comment]
@p1n0cch10 , In YOLOv3 inference support batch size more than 1, but PP-YOLO not support it.

**Comment by p1n0cch10** [comment]
> @p1n0cch10 In YOLOv3 inference support batch size more than 1, but PP-YOLO not support it.

Thanks. So.. I would like to use `configs/dcn/yolov3_r50vd_dcn_db_iouaware_obj365_pretrained_coco.yml`.

How can I get the .pdparams file, if I want to make inference like this,
 
`python tools/infer.py -c configs/ppyolo/ppyolo.yml -o use_gpu=true weights=https://paddlemodels.bj.bcebos.com/object_detection/ppyolo.pdparams --infer_img=demo/000000014439.jpg`

in the yaml file, there is only a pretrained weights with tons of variables.

**Comment by yghstill** [comment]
@p1n0cch10  https://paddlemodels.bj.bcebos.com/object_detection/yolov3_r50vd_dcn_db_iouaware_obj365_pretrained_coco.pdparams in https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/featured_model/YOLOv3_ENHANCEMENT.md#%E6%A8%A1%E5%9E%8B%E6%95%88%E6%9E%9C
