### ISSUE TITLE
导出的模型在agx部署python报错

### ISSUE THREAD

**Issue by liangruofei** [PaddlePaddle/PaddleDetection#1701]
deploy的python部署报错如下

```
PP-YOLO$ python3 infer.py --model_dir=output/
-----------  Configuration Arguments -----------
image_file: dataset/images/1590392775029.jpg
label_file: dataset/label_list.txt
model_dir: output/
run_mode: fluid
threshold: 0.5
use_gpu: True
------------------------------------------------
-----------  Model Configuration -----------
Model Arch: YOLO
Use Padddle Executor: False
Transform Order: 
--transform op: Resize
--transform op: Normalize
--transform op: Permute
--------------------------------------------
------------**********------------
['image', 'im_size']
Traceback (most recent call last):
  File "infer.py", line 558, in <module>
    result = predict_image(args.image_file)
  File "infer.py", line 519, in predict_image
    results = detector.predict(image_path, args.threshold)
  File "infer.py", line 498, in predict
    self.predictor.zero_copy_run()
RuntimeError: basic_string::_M_construct null not valid
```

**Comment by liuhuiCNN** [comment]
您好，您是否方便提供代码和模型，方便我们复现错误，谢谢。您可以检查下看看是不是图像文件路径导致的问题。
