### ISSUE TITLE
The finally Error is:Blocking queue is killed because the data reader raises an exception, before has two error.

### ISSUE THREAD

**Issue by funny000** [PaddlePaddle/PaddleDetection#1709]
C:\Users\admin\AppData\Local\Programs\Python\Python37\python.exe D:/Py_Project/Jiqixuexi/paddle_study/paddle_pascalvoc.py
start ssd, train params: {'input_size': [3, 300, 300], 'class_dim': 21, 'label_dict': {'background': 0, 'aeroplane': 1, 'bicycle': 2, 'bird': 3, 'boat': 4, 'bottle': 5, 'bus': 6, 'car': 7, 'cat': 8, 'chair': 9, 'cow': 10, 'diningtable': 11, 'dog': 12, 'horse': 13, 'motorbike': 14, 'person': 15, 'pottedplant': 16, 'sheep': 17, 'sofa': 18, 'train': 19, 'tvmonitor': 20}, 'image_count': 21503, 'log_feed_image': False, 'pretrained': True, 'pretrained_model_dir': './pretrained-model', 'save_model_dir': './ssd-model', 'model_prefix': 'mobilenet-ssd', 'data_dir': 'D:/Py_Project/data/data4379/pascalvoc', 'mean_rgb': [127.5, 127.5, 127.5], 'file_list': 'train.txt', 'mode': 'train', 'multi_data_reader_count': 1, 'num_epochs': 1, 'train_batch_size': 1, 'use_gpu': False, 'apply_distort': True, 'apply_expand': True, 'apply_corp': True, 'image_distort_strategy': {'expand_prob': 0.5, 'expand_max_ratio': 4, 'hue_prob': 0.5, 'hue_delta': 18, 'contrast_prob': 0.5, 'contrast_delta': 0.5, 'saturation_prob': 0.5, 'saturation_delta': 0.5, 'brightness_prob': 0.5, 'brightness_delta': 0.125}, 'rsm_strategy': {'learning_rate': 0.001, 'lr_epochs': [40, 60, 80, 100], 'lr_decay': [1, 0.5, 0.25, 0.1, 0.01]}, 'momentum_strategy': {'learning_rate': 0.1, 'decay_steps': 128, 'decay_rate': 0.8}, 'early_stop': {'sample_frequency': 50, 'successive_limit': 3, 'min_loss': 1.28, 'min_curr_map': 0.86}}
import ujson error: No module named 'ujson' use json
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\layers\io.py", line 496, in __provider_thread__
    six.reraise(*sys.exc_info())
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\layers\io.py", line 477, in __provider_thread__
    for tensors in func():
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\layers\io.py", line 528, in __tensor_provider__
    for slots in paddle_reader():
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\data_feeder.py", line 506, in __reader_creator__
    for item in reader():
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\reader\decorator.py", line 578, in queue_reader
    p.start()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'multiprocess_reader.<locals>._read_into_queue'

C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "D:/Py_Project/Jiqixuexi/paddle_study/paddle_pascalvoc.py", line 703, in <module>
    loss = exe.run(train_program, fetch_list=train_fetch_list)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line 1066, in run
    return_merged=return_merged)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line 1229, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\layers\io.py", line 894, in read_file
    type='read', inputs={'Reader': [reader]}, outputs={'Out': out})
  File "D:/Py_Project/Jiqixuexi/paddle_study/paddle_pascalvoc.py", line 543, in build_train_program_with_async_reader
    img, gt_box, gt_label, difficult = fluid.layers.read_file(data_reader)
  File "D:/Py_Project/Jiqixuexi/paddle_study/paddle_pascalvoc.py", line 670, in <module>
    train_reader, img, loss, locs, confs, box, box_var = build_train_program_with_async_reader(train_program, start_program)

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (D:\1.8.5\paddle\paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\multiprocessing\reduction.py", line 87, in steal_handle
    _winapi.DUPLICATE_SAME_ACCESS | _winapi.DUPLICATE_CLOSE_SOURCE)
PermissionError: [WinError 5] 拒绝访问。

**Comment by jerrywgz** [comment]
thanks for your feedback. Could you please provide your Paddle version and PaddleDetection version. It seems that you used previous version and you could try release/0.4 branch on PaddleDetection
