### ISSUE TITLE
快速开始 文档中的  yolov3_mobilenet_v1_fruit.yml 跑不起来。

### ISSUE THREAD

**Issue by RichardsATcn** [PaddlePaddle/PaddleDetection#174]
报告的错误很奇怪，压根就没进入到训练过程。
数据是脚本下载的没有进行更改

配置是AMD的2700  显卡2080ti 
win10 64bit
```
PS G:\Paddle\PaddleDetection> python -u tools/train.py -c configs/yolov3_mobilenet_v1_fruit.yml
EvalReader:
  batch_size: 1
  bufsize: 32
  dataset: !VOCDataSet
    anno_path: val.txt
    dataset_dir: dataset/fruit
    image_dir: ''
    label_list: label_list.txt
    sample_num: -1
    use_default_label: false
    with_background: false
  drop_empty: false
  inputs_def:
    fields:
    - image
    - im_size
    - im_id
    - gt_bbox
    - gt_class
    - is_difficult
    image_shape:
    - 3
    - 608
    - 608
    num_max_boxes: 50
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !ResizeImage
    interp: 2
    max_size: 0
    target_size: 608
    use_cv2: true
  - !NormalizeImage
    is_channel_first: false
    is_scale: true
    mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
  - !PadBox
    num_max_boxes: 50
  - !Permute
    channel_first: true
    to_bgr: false
  worker_num: 8
LearningRate:
  [32mbase_lr[0m: 1.0e-05
  [32mschedulers[0m:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 15000
    - 18000
    values: null
  - !LinearWarmup
    start_factor: 0.0
    steps: 100
MobileNet:
  [32mnorm_type[0m: sync_bn
  conv_group_scale: 1
  conv_learning_rate: 1.0
  extra_block_filters:
  - - 256
    - 512
  - - 128
    - 256
  - - 128
    - 256
  - - 64
    - 128
  norm_decay: 0.0
  weight_prefix_name: ''
  with_extra_blocks: false
OptimizerBuilder:
  [32mregularizer[0m:
    factor: 0.0005
    type: L2
  optimizer:
    momentum: 0.9
    type: Momentum
TestReader:
  batch_size: 1
  dataset: !ImageFolder
    anno_path: null
    dataset_dir: ''
    image_dir: ''
    sample_num: -1
    with_background: false
  inputs_def:
    fields:
    - image
    - im_size
    - im_id
    image_shape:
    - 3
    - 608
    - 608
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !ResizeImage
    interp: 2
    max_size: 0
    target_size: 608
    use_cv2: true
  - !NormalizeImage
    is_channel_first: false
    is_scale: true
    mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
  - !Permute
    channel_first: true
    to_bgr: false
TrainReader:
  batch_size: 1
  batch_transforms:
  - !RandomShape
    random_inter: false
    sizes:
    - 608
  - !Permute
    channel_first: true
    to_bgr: false
  bufsize: 64
  dataset: !VOCDataSet
    anno_path: train.txt
    dataset_dir: dataset/fruit
    image_dir: ''
    label_list: label_list.txt
    sample_num: -1
    use_default_label: false
    with_background: false
  drop_last: true
  inputs_def:
    fields:
    - image
    - gt_bbox
    - gt_class
    - gt_score
    image_shape:
    - 3
    - 608
    - 608
    num_max_boxes: 50
  mixup_epoch: -1
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !NormalizeBox {}
  - !ExpandImage
    max_ratio: 4.0
    mean:
    - 123.675
    - 116.28
    - 103.53
    prob: 0.5
  - !RandomInterpImage
    max_size: 0
    target_size: 608
  - !RandomFlipImage
    is_mask_flip: false
    is_normalized: true
    prob: 0.5
  - !NormalizeImage
    is_channel_first: false
    is_scale: true
    mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
  - !PadBox
    num_max_boxes: 50
  - !BboxXYXY2XYWH {}
  shuffle: true
  use_process: true
  worker_num: 4
YOLOv3:
  [32mbackbone[0m: MobileNet
  use_fine_grained_loss: false
  yolo_head: YOLOv3Head
YOLOv3Head:
  [32mnms[0m:
    background_label: -1
    keep_top_k: 100
    nms_threshold: 0.45
    nms_top_k: 1000
    normalized: false
    score_threshold: 0.01
  anchor_masks:
  - - 6
    - 7
    - 8
  - - 3
    - 4
    - 5
  - - 0
    - 1
    - 2
  anchors:
  - - 10
    - 13
  - - 16
    - 30
  - - 33
    - 23
  - - 30
    - 61
  - - 62
    - 45
  - - 59
    - 119
  - - 116
    - 90
  - - 156
    - 198
  - - 373
    - 326
  norm_decay: 0.0
  num_classes: 80
  weight_prefix_name: ''
  yolo_loss: YOLOv3Loss
YOLOv3Loss:
  batch_size: 8
  ignore_thresh: 0.7
  label_smooth: true
  use_fine_grained_loss: false
architecture: YOLOv3
finetune_exclude_pretrained_params:
- yolo_output
log_smooth_window: 20
map_type: 11point
max_iters: 20000
metric: VOC
num_classes: 3
pretrain_weights: https://paddlemodels.bj.bcebos.com/object_detection/yolov3_mobilenet_v1.tar
save_dir: output
snapshot_iter: 200
use_gpu: true
weights: output/yolov3_mobilenet_v1_fruit/best_model

W0110 11:11:52.504719 15392 device_context.cc:236] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.1, Runtime API Version: 10.0
W0110 11:11:52.512717 15392 device_context.cc:244] device: 0, cuDNN Version: 7.6.
2020-01-10 11:11:54,239-INFO: Found ./cache/paddle/weights\yolov3_mobilenet_v1
2020-01-10 11:11:54,239-INFO: Loading parameters from ./cache/paddle/weights\yolov3_mobilenet_v1...
2020-01-10 11:11:54,253-INFO: In load_params, ignore yolo_output.0.conv.weights
2020-01-10 11:11:54,254-INFO: In load_params, ignore yolo_output.0.conv.bias
2020-01-10 11:11:54,257-INFO: In load_params, ignore yolo_output.1.conv.weights
2020-01-10 11:11:54,257-INFO: In load_params, ignore yolo_output.1.conv.bias
2020-01-10 11:11:54,260-INFO: In load_params, ignore yolo_output.2.conv.weights
2020-01-10 11:11:54,260-INFO: In load_params, ignore yolo_output.2.conv.bias
2020-01-10 11:11:54,620-INFO: Use multi-thread reader instead of multi-process reader on Windows.
2020-01-10 11:11:54,620-INFO: places would be ommited when DataLoader is not iterable
I0110 11:11:54.654721 15392 parallel_executor.cc:421] The number of CUDAPlace, which is used in ParallelExecutor, is 1. And the Program will be copied 1 copies
I0110 11:11:54.690719 15392 build_strategy.cc:363] SeqOnlyAllReduceOps:0, num_trainers:1
I0110 11:11:54.720719 15392 parallel_executor.cc:285] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I0110 11:11:54.740721 15392 parallel_executor.cc:368] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "G:\Paddle\PaddleDetection\ppdet\data\parallel_map.py", line 161, in _consume
    signal.signal(signal.SIGTERM, lambda signum, frame: sys.exit())
  File "C:\Program Files\Python37\lib\signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "G:\Paddle\PaddleDetection\ppdet\data\parallel_map.py", line 161, in _consume
    signal.signal(signal.SIGTERM, lambda signum, frame: sys.exit())
  File "C:\Program Files\Python37\lib\signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread

Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "G:\Paddle\PaddleDetection\ppdet\data\parallel_map.py", line 161, in _consume
    signal.signal(signal.SIGTERM, lambda signum, frame: sys.exit())
  File "C:\Program Files\Python37\lib\signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread

Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "G:\Paddle\PaddleDetection\ppdet\data\parallel_map.py", line 161, in _consume
    signal.signal(signal.SIGTERM, lambda signum, frame: sys.exit())
  File "C:\Program Files\Python37\lib\signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread


2020-01-10 11:11:57,749-WARNING: Your reader has raised an exception!
Traceback (most recent call last):
  File "tools/train.py", line 323, in <module>
    main()
  File "tools/train.py", line 233, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "C:\Program Files\Python37\lib\site-packages\paddle\fluid\executor.py", line 780, in run
    six.reraise(*sys.exc_info())
  File "C:\Program Files\Python37\lib\site-packages\six.py", line 696, in reraise
Exception in thread Thread-8:
Traceback (most recent call last):
  File "G:\Paddle\PaddleDetection\ppdet\data\parallel_map.py", line 225, in next
    sample = self._outq.get(timeout=3)
  File "C:\Program Files\Python37\lib\queue.py", line 178, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python37\lib\site-packages\paddle\fluid\reader.py", line 488, in __thread_main__
    six.reraise(*sys.exc_info())
  File "C:\Program Files\Python37\lib\site-packages\six.py", line 696, in reraise
    raise value
  File "C:\Program Files\Python37\lib\site-packages\paddle\fluid\reader.py", line 468, in __thread_main__
    for tensors in self._tensor_reader():
  File "C:\Program Files\Python37\lib\site-packages\paddle\fluid\reader.py", line 542, in __tensor_reader_impl__
    for slots in paddle_reader():
  File "C:\Program Files\Python37\lib\site-packages\paddle\fluid\data_feeder.py", line 488, in __reader_creator__
    for item in reader():
  File "G:\Paddle\PaddleDetection\ppdet\data\reader.py", line 413, in _reader
    for _batch in reader:
  File "G:\Paddle\PaddleDetection\ppdet\data\parallel_map.py", line 84, in __next__
    return self.next()
  File "G:\Paddle\PaddleDetection\ppdet\data\parallel_map.py", line 227, in next
    if not self._consumer_healthy():
  File "G:\Paddle\PaddleDetection\ppdet\data\parallel_map.py", line 202, in _consumer_healthy
    .format(w.pid, w.exitcode)
AttributeError: 'Thread' object has no attribute 'pid'

raise value
  File "C:\Program Files\Python37\lib\site-packages\paddle\fluid\executor.py", line 775, in run
    use_program_cache=use_program_cache)
  File "C:\Program Files\Python37\lib\site-packages\paddle\fluid\executor.py", line 834, in _run_impl
    return_numpy=return_numpy)
  File "C:\Program Files\Python37\lib\site-packages\paddle\fluid\executor.py", line 674, in _run_parallel
    tensors = exe.run(fetch_var_names)._move_to_list()
paddle.fluid.core_avx.EOFException: There is no next data. at [D:\1.6.2\paddle\paddle\fluid\operators\reader\read_op.cc:90]

```

**Comment by heavengate** [comment]
您好，请问下您使用的Paddle和PaddleDetection的版本方便提供下么

**Comment by heavengate** [comment]
您好，由于multiprocess在windows系统上不可用，可以在配置文件里面关闭`use_process`
https://github.com/PaddlePaddle/PaddleDetection/blob/47741382cf15eda852fefdada6ce83ef86350af6/configs/yolov3_mobilenet_v1_fruit.yml#L71
或者参照https://github.com/PaddlePaddle/PaddleDetection/pull/181 修改下代码
