### ISSUE TITLE
案例eval和infer的时候报同样错误

### ISSUE THREAD

**Issue by FUQiaobo** [PaddlePaddle/PaddleDetection#1777]
```
(paddle) E:\PyCharm_Projects\Paddle\PaddleDetection>python tools/eval.py -c configs/yolov3_mobilenet_v1_roadsign.yml -o use_gpu=true
2020-11-28 13:07:27,009-WARNING: config YOLOv3Loss.batch_size is deprecated, training batch size should be set by TrainReader.batch_size
W1128 13:07:27.579334 71964 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 11.0, Runtime API Version: 10.0
W1128 13:07:27.586342 71964 device_context.cc:260] device: 0, cuDNN Version: 7.6.
2020-11-28 13:07:29,355-WARNING: output/yolov3_mobilenet_v1_roadsign_coco_template/.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
D:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\io.py", line 1891, in load_program_state
    filename=file_name)
  File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\io.py", line 805, in load_vars
    executor.run(load_prog)
  File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "D:\Anaconda3\envs\paddle\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\executor.py", line 1066, in run
    return_merged=return_merged)
  File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\executor.py", line 1229, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\io.py", line 785, in load_vars
    attrs={'file_path': os.path.join(dirname, new_var.name)})
  File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\io.py", line 1891, in load_program_state
    filename=file_name)
  File "E:\PyCharm_Projects\Paddle\PaddleDetection\ppdet\utils\checkpoint.py", line 91, in _load_state
    state = fluid.io.load_program_state(path)
  File "E:\PyCharm_Projects\Paddle\PaddleDetection\ppdet\utils\checkpoint.py", line 126, in load_params
    state = _load_state(path)
  File "tools/eval.py", line 140, in main
    checkpoint.load_params(exe, startup_prog, cfg.weights)
  File "tools/eval.py", line 179, in <module>
    main()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: tensor version 1522126346 is not supported, Only version 0 is supported
  [Hint: Expected version == 0U, but received version:1522126346 != 0U:0.] at (D:\1.8.4\paddle\paddle\fluid\framework\lod_tensor.cc:287)
  [operator < load > error]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/eval.py", line 179, in <module>
    main()
  File "tools/eval.py", line 140, in main
    checkpoint.load_params(exe, startup_prog, cfg.weights)
  File "E:\PyCharm_Projects\Paddle\PaddleDetection\ppdet\utils\checkpoint.py", line 126, in load_params
    state = _load_state(path)
  File "E:\PyCharm_Projects\Paddle\PaddleDetection\ppdet\utils\checkpoint.py", line 91, in _load_state
    state = fluid.io.load_program_state(path)
  File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\io.py", line 1894, in load_program_state
    "Failed to load model file , please make sure model file is saved with the "
RuntimeError: Failed to load model file , please make sure model file is saved with the following APIs: save_params, save_persistables, save_vars
```

**Comment by qingqing01** [comment]
@FUQiaobo 

快速开始里，您需要先训练得到模型，才能做eval和infer。


请注意检测 output/yolov3_mobilenet_v1_roadsign_coco_template/.pdparams  是否存在

**Comment by FUQiaobo** [comment]
> @FUQiaobo
> 
> 快速开始里，您需要先训练得到模型，才能做eval和infer。
> 
> 请注意检测 output/yolov3_mobilenet_v1_roadsign_coco_template/.pdparams 是否存在
自己已经训练过了，但是就是没有template文件，只生成了一个yolov3_mobilenet_v1_roadsign文件夹，其中是由生成好的模型的，,但是后面eval和infer时读不到这个文件夹的模型。

**Comment by qingqing01** [comment]
@FUQiaobo 那在yml中正确设置下 weights的路径，或命令行中通过 `-o weights=` 设置下模型的路径看下吧。

**Comment by Wenxin-piggy** [comment]
加上weights=./output/yolov3_mobilenet_v1_roadsign/best_model.pdmodel就好了好像……

**Comment by Kiddo33** [comment]
> 加上weights=./output/yolov3_mobilenet_v1_roadsign/best_model.pdmodel就好了好像……

请问是在哪个位置加呢
