### ISSUE TITLE
ppyolo训练coco数据集出现图像格式错误

### ISSUE THREAD

**Issue by ybxbupt** [PaddlePaddle/PaddleDetection#1784]
ppyolo训练coco数据集出现下面错误：

```
2020-11-30 10:25:58,884-WARNING: Illegal image file: dataset/coco\train2017\000000516168.jpg, and it will be ignored
2020-11-30 10:25:58,884-WARNING: Illegal image file: dataset/coco\train2017\000000547503.jpg, and it will be ignored
2020-11-30 10:25:58,884-WARNING: Illegal image file: dataset/coco\train2017\000000475546.jpg, and it will be ignored
Traceback (most recent call last):
  File "H:/yuanbaoxi/test_code/paddlepaddle-PaddleDetection-master/PaddleDetection/train_ppyolo_coco.py", line 391, in <module>
    main()
  File "H:/yuanbaoxi/test_code/paddlepaddle-PaddleDetection-master/PaddleDetection/train_ppyolo_coco.py", line 211, in main
    num_trainers=num_trainers)
  File "H:\yuanbaoxi\test_code\paddlepaddle-PaddleDetection-master\PaddleDetection\ppdet\data\reader.py", line 441, in create_reader
    reader = Reader(**cfg)()
  File "H:\yuanbaoxi\test_code\paddlepaddle-PaddleDetection-master\PaddleDetection\ppdet\data\reader.py", line 210, in __init__
    self._roidbs = self._dataset.get_roidb()
  File "H:\yuanbaoxi\test_code\paddlepaddle-PaddleDetection-master\PaddleDetection\ppdet\data\source\dataset.py", line 68, in get_roidb
    self.load_roidb_and_cname2cid()
  File "H:\yuanbaoxi\test_code\paddlepaddle-PaddleDetection-master\PaddleDetection\ppdet\data\source\coco.py", line 184, in load_roidb_and_cname2cid
    assert len(records) > 0, 'not found any coco record in %s' % (anno_path)
AssertionError: not found any coco record in dataset/coco\annotations/instances_train2017.json
```
但是在faster-rcnn中训练正常，可以确定coco数据集下载的是正确的版本

**Comment by qingqing01** [comment]
@ybxbupt  Windows系统下，请注意数据路径配置时 / 和 \使用保持一致吧

https://github.com/PaddlePaddle/PaddleDetection/blob/8eb57b8354231ade335cd490b3056c7bf39b82ac/configs/ppyolo/ppyolo_reader.yml#L8-L9

**Comment by ybxbupt** [comment]
确实是图像路径问题，感谢您的及时回复

**Comment by qingqing01** [comment]
@ybxbupt 这个要是没问题的话，辛苦关闭下issue吧

**Comment by kylewangt** [comment]
> @ybxbupt Windows系统下，请注意数据路径配置时 / 和 \使用保持一致吧
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/8eb57b8354231ade335cd490b3056c7bf39b82ac/configs/ppyolo/ppyolo_reader.yml#L8-L9
我就是这样设置的，但是还是报错
![image](https://user-images.githubusercontent.com/44918749/170652971-5dc68ee4-7087-4c54-8529-4ed8fc439ca9.png)
