### ISSUE TITLE
ppyolo训练自己的数据集出错

### ISSUE THREAD

**Issue by ybxbupt** [PaddlePaddle/PaddleDetection#1785]
自己的数据集制作成coco格式，在faster-rcnn下训练正确，但是在ppyolo下无法训练

```
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
H:\yuanbaoxi\test_code\paddlepaddle-PaddleDetection-master\PaddleDetection\ppdet\data\reader.py:89: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  if isinstance(item, collections.Sequence) and len(item) == 0:
Traceback (most recent call last):
  File "H:/yuanbaoxi/test_code/paddlepaddle-PaddleDetection-master/PaddleDetection/train_QR_ppyolo.py", line 391, in <module>
    main()
  File "H:/yuanbaoxi/test_code/paddlepaddle-PaddleDetection-master/PaddleDetection/train_QR_ppyolo.py", line 249, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "C:\ProgramData\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\executor.py", line 1107, in run
    six.reraise(*sys.exc_info())
  File "C:\ProgramData\Anaconda3\envs\PaddleDetection\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\executor.py", line 1105, in run
    return_merged=return_merged)
  File "C:\ProgramData\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\executor.py", line 1242, in _run_impl
    return_merged=return_merged)
  File "C:\ProgramData\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\executor.py", line 910, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

  Compile Traceback (most recent call last):
    File "H:/yuanbaoxi/test_code/paddlepaddle-PaddleDetection-master/PaddleDetection/train_QR_ppyolo.py", line 391, in <module>
      main()
    File "H:/yuanbaoxi/test_code/paddlepaddle-PaddleDetection-master/PaddleDetection/train_QR_ppyolo.py", line 118, in main
      feed_vars, train_loader = model.build_inputs(**inputs_def)
    File "H:\yuanbaoxi\test_code\paddlepaddle-PaddleDetection-master\PaddleDetection\ppdet\modeling\architectures\yolo.py", line 155, in build_inputs
      iterable=iterable) if use_dataloader else None
    File "C:\ProgramData\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\reader.py", line 682, in from_generator
      iterable, return_list, drop_last)
    File "C:\ProgramData\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\reader.py", line 1022, in __init__
      self._init_non_iterable()
    File "C:\ProgramData\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\reader.py", line 1124, in _init_non_iterable
      attrs={'drop_last': self._drop_last})
    File "C:\ProgramData\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\framework.py", line 2917, in append_op
      attrs=kwargs.get("attrs", None))
    File "C:\ProgramData\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\framework.py", line 2014, in __init__
      for frame in traceback.extract_stack():

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The fed Variable gt_bbox should have dimensions = 3, shape = [-1, 2, 4], but received fed shape [24, 50, 4]
  [Hint: Expected DimensionIsCompatibleWith(shapes[i], in_dims) == true, but received DimensionIsCompatibleWith(shapes[i], in_dims):0 != true:1.] (at D:\2.0.0-rc0\paddle\paddle\fluid\operators\reader\read_op.cc:140)
  [operator < read > error]
```

**Comment by qingqing01** [comment]
@ybxbupt  

看您复制了一个`PaddleDetection/train_QR_ppyolo.py`, 请问有什么改动吗？ 

>  gt_bbox should have dimensions = 3, shape = [-1, 2, 4], but received fed shape [24, 50, 4]

从错误信息看， 需注意reader相关配置里的 num_max_boxes 是否设置一致

https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.5/configs/ppyolo/ppyolo_reader.yml#L4

**Comment by ybxbupt** [comment]
非常感谢及时回复，就是num_max_boxes设置问题，都改成50就好了

**Comment by qingqing01** [comment]
@ybxbupt 要是没问题的话，辛苦关闭下issue
