### ISSUE TITLE
Exception: 'feed_targets' does not have im_info variable

### ISSUE THREAD

**Issue by Tobesempurna** [PaddlePaddle/PaddleDetection#1808]
为了适配导出模型在pyqt上进行检测，使用fluid.io.load_inference_model作为模型的加载方式。在得到的feed_target_names中，有'image', 'im_info', 'im_shape'。按照官网API的写法(如下)，只给feed传入image时，报了这个错。查看了infer.py的源码，feed_target_names(data)通过枚举loader()定义，而loader也通过了多层封装，无法得知 ‘im_info’ 的相关信息。请问对于一张实例化的图片，如何给feed传入‘im_info’。(计算机小白，麻烦老师耐心讲解，谢谢)

# API
[inference_program, feed_target_names, fetch_targets] = (fluid.io.load_inference_model(dirname=path, executor=exe))
tensor_img = np.array(np.random.random((1, 64, 784)), dtype=np.float32)
results = exe.run(inference_program,
          feed={feed_target_names[0]: tensor_img},
          fetch_list=fetch_targets)

# infer.py 源码
 for iter_id, data in enumerate(loader()):
        outs = exe.run(infer_prog,
                       feed=data,
                       fetch_list=values,
                       return_numpy=False)

# Error
E:\opensources\Anaconda3\envs\paddledet\lib\site-packages\paddle\fluid\executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "E:/deeplearning/workspace/detection/PaddleDetection/tools/ui/main.py", line 132, in <module>
    a.infer(image_path)
  File "E:/deeplearning/workspace/detection/PaddleDetection/tools/ui/main.py", line 110, in infer
    return_numpy=False)
  File "E:\opensources\Anaconda3\envs\paddledet\lib\site-packages\paddle\fluid\executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "E:\opensources\Anaconda3\envs\paddledet\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "E:\opensources\Anaconda3\envs\paddledet\lib\site-packages\paddle\fluid\executor.py", line 1066, in run
    return_merged=return_merged)
  File "E:\opensources\Anaconda3\envs\paddledet\lib\site-packages\paddle\fluid\executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "E:\opensources\Anaconda3\envs\paddledet\lib\site-packages\paddle\fluid\executor.py", line 1224, in _run_program
    fetch_var_name=fetch_var_name)
  File "E:\opensources\Anaconda3\envs\paddledet\lib\site-packages\paddle\fluid\executor.py", line 601, in _add_feed_fetch_ops
    if not has_feed_operators(global_block, feed, feed_var_name):
  File "E:\opensources\Anaconda3\envs\paddledet\lib\site-packages\paddle\fluid\executor.py", line 266, in has_feed_operators
    format(feed_target_name))
Exception: 'feed_targets' does not have im_info variable
W1203 15:12:22.177162 10652 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 11.0, Runtime API Version: 10.0
W1203 15:12:22.185150 10652 device_context.cc:260] device: 0, cuDNN Version: 7.6.

**Comment by yghstill** [comment]
@Tobesempurna 试下deploy/python/infer.py试下呢，利用https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.5/docs/advanced_tutorials/deploy/EXPORT_MODEL.md  导出模型然后再预测。
