### ISSUE TITLE
ssd训练转换成COCO格式的自定义数据集时，出现如下错误

### ISSUE THREAD

**Issue by gyr-kdgc** [PaddlePaddle/PaddleDetection#1817]
2020-12-04 06:25:06,986-WARNING: recv endsignal from outq with errmsg[consumer[consumer-e9b-0] exits for reason[producer[producer-e9b] failed with error: 'NoneType' object is not iterable]]
2020-12-04 06:25:06,994-WARNING: recv endsignal from outq with errmsg[consumer[consumer-e9b-1] exits for reason[consumer[consumer-e9b-0] exits for reason[producer[producer-e9b] failed with error: 'NoneType' object is not iterable]]]
2020-12-04 06:25:07,004-WARNING: recv endsignal from outq with errmsg[consumer[consumer-e9b-2] exits for reason[consumer[consumer-e9b-1] exits for reason[consumer[consumer-e9b-0] exits for reason[producer[producer-e9b] failed with error: 'NoneType' object is not iterable]]]]
2020-12-04 06:25:07,013-WARNING: recv endsignal from outq with errmsg[consumer[consumer-e9b-3] exits for reason[consumer[consumer-e9b-2] exits for reason[consumer[consumer-e9b-1] exits for reason[consumer[consumer-e9b-0] exits for reason[producer[producer-e9b] failed with error: 'NoneType' object is not iterable]]]]]
2020-12-04 06:25:07,027-WARNING: recv endsignal from outq with errmsg[consumer[consumer-e9b-4] exits for reason[consumer[consumer-e9b-3] exits for reason[consumer[consumer-e9b-2] exits for reason[consumer[consumer-e9b-1] exits for reason[consumer[consumer-e9b-0] exits for reason[producer[producer-e9b] failed with error: 'NoneType' object is not iterable]]]]]]
2020-12-04 06:25:07,039-WARNING: recv endsignal from outq with errmsg[consumer[consumer-e9b-5] exits for reason[consumer[consumer-e9b-4] exits for reason[consumer[consumer-e9b-3] exits for reason[consumer[consumer-e9b-2] exits for reason[consumer[consumer-e9b-1] exits for reason[consumer[consumer-e9b-0] exits for reason[producer[producer-e9b] failed with error: 'NoneType' object is not iterable]]]]]]]
2020-12-04 06:25:07,046-WARNING: recv endsignal from outq with errmsg[consumer[consumer-e9b-6] exits for reason[consumer[consumer-e9b-5] exits for reason[consumer[consumer-e9b-4] exits for reason[consumer[consumer-e9b-3] exits for reason[consumer[consumer-e9b-2] exits for reason[consumer[consumer-e9b-1] exits for reason[consumer[consumer-e9b-0] exits for reason[producer[producer-e9b] failed with error: 'NoneType' object is not iterable]]]]]]]]
2020-12-04 06:25:07,058-WARNING: recv endsignal from outq with errmsg[consumer[consumer-e9b-7] exits for reason[consumer[consumer-e9b-6] exits for reason[consumer[consumer-e9b-5] exits for reason[consumer[consumer-e9b-4] exits for reason[consumer[consumer-e9b-3] exits for reason[consumer[consumer-e9b-2] exits for reason[consumer[consumer-e9b-1] exits for reason[consumer[consumer-e9b-0] exits for reason[producer[producer-e9b] failed with error: 'NoneType' object is not iterable]]]]]]]]]
2020-12-04 06:25:07,061-WARNING: Your reader has raised an exception!
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/paddle/fluid/reader.py", line 1145, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/usr/local/python3/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/python3/lib/python3.6/site-packages/paddle/fluid/reader.py", line 1125, in __thread_main__
    for tensors in self._tensor_reader():
  File "/usr/local/python3/lib/python3.6/site-packages/paddle/fluid/reader.py", line 1195, in __tensor_reader_impl__
    for slots in paddle_reader():
  File "/usr/local/python3/lib/python3.6/site-packages/paddle/fluid/data_feeder.py", line 506, in __reader_creator__
    for item in reader():
  File "/root/paddle_ssd/PaddleDetection-release-0.5/ppdet/data/reader.py", line 452, in _reader
    reader.reset()
  File "/root/paddle_ssd/PaddleDetection-release-0.5/ppdet/data/parallel_map.py", line 259, in reset
    assert not self._exit, "cannot reset for already stopped dataset"
AssertionError: cannot reset for already stopped dataset

/usr/local/python3/lib/python3.6/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tools/train.py", line 377, in <module>
    main()
  File "tools/train.py", line 248, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "/usr/local/python3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/python3/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/python3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/usr/local/python3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1167, in _run_impl
    return_merged=return_merged)
  File "/usr/local/python3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 879, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/usr/local/python3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/python3/lib/python3.6/site-packages/paddle/fluid/reader.py", line 1080, in _init_non_iterable
    attrs={'drop_last': self._drop_last})
  File "/usr/local/python3/lib/python3.6/site-packages/paddle/fluid/reader.py", line 978, in __init__
    self._init_non_iterable()
  File "/usr/local/python3/lib/python3.6/site-packages/paddle/fluid/reader.py", line 620, in from_generator
    iterable, return_list, drop_last)
  File "/root/paddle_ssd/PaddleDetection-release-0.5/ppdet/modeling/architectures/ssd.py", line 128, in build_inputs
    iterable=iterable) if use_dataloader else None
  File "tools/train.py", line 117, in main
    feed_vars, train_loader = model.build_inputs(**inputs_def)
  File "tools/train.py", line 377, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]

**Comment by gyr-kdgc** [comment]
failed with error: 'NoneType' object is not iterable主要不知道这个错误发生在哪地方，是不是我转换coco数据集的步骤有问题，官方的道路标识的coco数据集跑不起来，会一直卡住

**Comment by gyr-kdgc** [comment]
已解决，把drop_empty设置为false即可，貌似是数据集准备的问题，读取的segms列表全是None，导致报错: 'NoneType' object is not iterable
