### ISSUE TITLE
训练时异常终止

### ISSUE THREAD

**Issue by iceriver97** [PaddlePaddle/PaddleDetection#1862]
报错：

```
2020-12-10 16:03:36,940-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000100] in Optimizer will not take effect, and it will only be applied to other Parameters!
loading annotations into memory...
Done (t=0.14s)
creating index...
index created!
W1210 16:03:38.015040  9143 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 11.0, Runtime API Version: 9.0
W1210 16:03:38.020366  9143 device_context.cc:260] device: 0, cuDNN Version: 7.6.
2020-12-10 16:03:40,224-WARNING: /home/aistudio/.cache/paddle/weights/ResNet50_cos_pretrained.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-12-10 16:03:40,500-WARNING: /home/aistudio/.cache/paddle/weights/ResNet50_cos_pretrained.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-12-10 16:03:40,505-WARNING: variable file [ /home/aistudio/.cache/paddle/weights/ResNet50_cos_pretrained/fc_0.w_0 /home/aistudio/.cache/paddle/weights/ResNet50_cos_pretrained/fc_0.b_0 ] not used
loading annotations into memory...
Done (t=0.16s)
creating index...
index created!
2020-12-10 16:03:41,675-INFO: iter: 0, lr: 0.000417, 'loss_cls': '2.543962', 'loss_bbox': '0.000012', 'loss_rpn_cls': '0.696123', 'loss_rpn_bbox': '0.033125', 'loss_mask': '0.305029', 'loss': '3.578252', eta: 0:01:27, batch_cost: 0.00548 sec, ips: 182.55948 images/sec
2020-12-10 16:03:47,588-INFO: iter: 20, lr: 0.000428, 'loss_cls': '0.184330', 'loss_bbox': '0.027854', 'loss_rpn_cls': '0.692276', 'loss_rpn_bbox': '0.035280', 'loss_mask': '0.578454', 'loss': '1.587881', eta: 1:22:45, batch_cost: 0.31074 sec, ips: 3.21817 images/sec
W1210 16:03:47.881937  9214 init.cc:226] Warning: PaddlePaddle catches a failure signal, it may not work properly
W1210 16:03:47.881979  9214 init.cc:228] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W1210 16:03:47.881983  9214 init.cc:231] The detail failure signal is:

W1210 16:03:47.881997  9214 init.cc:234] *** Aborted at 1607587427 (unix time) try "date -d @1607587427" if you are using GNU date ***
W1210 16:03:47.884702  9214 init.cc:234] PC: @                0x0 (unknown)
W1210 16:03:47.884970  9214 init.cc:234] *** SIGSEGV (@0x100000009) received by PID 9143 (TID 0x7fd070bfd700) from PID 9; stack trace: ***
W1210 16:03:47.887205  9214 init.cc:234]     @     0x7fd18ddaa390 (unknown)
W1210 16:03:47.893491  9214 init.cc:234]     @     0x7fd118846bb4 paddle::memory::detail::BuddyAllocator::Free()
W1210 16:03:47.900727  9214 init.cc:234]     @     0x7fd118836ac5 paddle::memory::legacy::Free<>()
W1210 16:03:47.904498  9214 init.cc:234]     @     0x7fd118837965 paddle::memory::allocation::NaiveBestFitAllocator::FreeImpl()
W1210 16:03:47.907430  9214 init.cc:234]     @     0x7fd1150a75c9 std::_Sp_counted_base<>::_M_release()
W1210 16:03:47.912317  9214 init.cc:234]     @     0x7fd1150b7b50 std::vector<>::~vector()
W1210 16:03:47.916389  9214 init.cc:234]     @     0x7fd118645eb8 paddle::operators::reader::PyReader::ReadNext()
W1210 16:03:47.918349  9214 init.cc:234]     @     0x7fd11864aa95 _ZZN6paddle9operators6reader14BufferedReader9ReadAsyncEmENKUlvE_clEv
W1210 16:03:47.924085  9214 init.cc:234]     @     0x7fd11864be73 std::_Function_handler<>::_M_invoke()
W1210 16:03:47.930723  9214 init.cc:234]     @     0x7fd1151b52f7 std::__future_base::_State_base::_M_do_set()
W1210 16:03:47.933014  9214 init.cc:234]     @     0x7fd18dda7a99 __pthread_once_slow
W1210 16:03:47.934983  9214 init.cc:234]     @     0x7fd118648102 _ZNSt13__future_base11_Task_stateISt5_BindIFZN6paddle9operators6reader14BufferedReader9ReadAsyncEmEUlvE_vEESaIiEFmvEE6_M_runEv
W1210 16:03:47.941555  9214 init.cc:234]     @     0x7fd1151b7754 _ZZN10ThreadPoolC1EmENKUlvE_clEv
W1210 16:03:47.942706  9214 init.cc:234]     @     0x7fd14e79e421 execute_native_thread_routine_compat
W1210 16:03:47.944875  9214 init.cc:234]     @     0x7fd18dda06ba start_thread
W1210 16:03:47.946988  9214 init.cc:234]     @     0x7fd18dad641d clone
W1210 16:03:47.949064  9214 init.cc:234]     @                0x0 (unknown)
Segmentation fault (core dumped)
```

**Comment by iceriver97** [comment]
类似的情况还有：

正常训练一小段时间。这段时间显存占用稳定在 4893MB，但是突然一下程序就终止了，报错如下：

```
s': '1.891515', eta: 1:24:37, batch_cost: 0.31774 sec, ips: 3.14726 images/sec
2020-12-10 16:31:15,748-INFO: iter: 40, lr: 0.000439, 'loss_cls': '0.190443', 'loss_bbox': '0.052367', 'loss_rpn_cls': '0.677856', 'loss_rpn_bbox': '0.044716', 'loss_mask': '0.654964', 'loss': '1.664189', eta: 1:22:39, batch_cost: 0.31072 sec, ips: 3.21834 images/sec
2020-12-10 16:31:21,957-INFO: iter: 60, lr: 0.000450, 'loss_cls': '0.165818', 'loss_bbox': '0.043650', 'loss_rpn_cls': '0.659236', 'loss_rpn_bbox': '0.025368', 'loss_mask': '0.518633', 'loss': '1.536624', eta: 1:22:21, batch_cost: 0.30999 sec, ips: 3.22590 images/sec
2020-12-10 16:31:28,031-INFO: iter: 80, lr: 0.000461, 'loss_cls': '0.236255', 'loss_bbox': '0.045061', 'loss_rpn_cls': '0.629134', 'loss_rpn_bbox': '0.026023', 'loss_mask': '0.557085', 'loss': '1.581375', eta: 1:21:03, batch_cost: 0.30551 sec, ips: 3.27322 images/sec
2020-12-10 16:31:33,984-INFO: iter: 100, lr: 0.000472, 'loss_cls': '0.147598', 'loss_bbox': '0.049784', 'loss_rpn_cls': '0.582867', 'loss_rpn_bbox': '0.015676', 'loss_mask': '0.523203', 'loss': '1.439640', eta: 1:19:18, batch_cost: 0.29930 sec, ips: 3.34114 images/sec
2020-12-10 16:31:39,334-INFO: iter: 120, lr: 0.000483, 'loss_cls': '0.119083', 'loss_bbox': '0.018622', 'loss_rpn_cls': '0.481222', 'loss_rpn_bbox': '0.017329', 'loss_mask': '0.439810', 'loss': '1.127490', eta: 1:10:49, batch_cost: 0.26757 sec, ips: 3.73729 images/sec
2020-12-10 16:31:44,701-INFO: iter: 140, lr: 0.000494, 'loss_cls': '0.192155', 'loss_bbox': '0.043849', 'loss_rpn_cls': '0.320894', 'loss_rpn_bbox': '0.043110', 'loss_mask': '0.528437', 'loss': '1.216000', eta: 1:10:04, batch_cost: 0.26512 sec, ips: 3.77187 images/sec
2020-12-10 16:31:50,789-INFO: iter: 160, lr: 0.000506, 'loss_cls': '0.082101', 'loss_bbox': '0.003487', 'loss_rpn_cls': '0.280482', 'loss_rpn_bbox': '0.046991', 'loss_mask': '0.153218', 'loss': '0.905808', eta: 1:20:19, batch_cost: 0.30426 sec, ips: 3.28664 images/sec
2020-12-10 16:31:56,710-INFO: iter: 180, lr: 0.000517, 'loss_cls': '0.097761', 'loss_bbox': '0.007469', 'loss_rpn_cls': '0.282853', 'loss_rpn_bbox': '0.048685', 'loss_mask': '0.407539', 'loss': '0.896422', eta: 1:18:35, batch_cost: 0.29806 sec, ips: 3.35504 images/sec
2020-12-10 16:32:02,414-INFO: iter: 200, lr: 0.000528, 'loss_cls': '0.115527', 'loss_bbox': '0.002049', 'loss_rpn_cls': '0.251307', 'loss_rpn_bbox': '0.030676', 'loss_mask': '0.412574', 'loss': '0.964912', eta: 1:14:39, batch_cost: 0.28350 sec, ips: 3.52728 images/sec
2020-12-10 16:32:08,316-INFO: iter: 220, lr: 0.000539, 'loss_cls': '0.134288', 'loss_bbox': '0.032685', 'loss_rpn_cls': '0.230699', 'loss_rpn_bbox': '0.063197', 'loss_mask': '0.444989', 'loss': '1.023756', eta: 1:17:32, batch_cost: 0.29481 sec, ips: 3.39206 images/sec
2020-12-10 16:32:14,071-INFO: iter: 240, lr: 0.000550, 'loss_cls': '0.121770', 'loss_bbox': '0.032425', 'loss_rpn_cls': '0.223862', 'loss_rpn_bbox': '0.051662', 'loss_mask': '0.489479', 'loss': '1.137074', eta: 1:15:41, batch_cost: 0.28817 sec, ips: 3.47015 images/sec
2020-12-10 16:32:19,699-INFO: iter: 260, lr: 0.000561, 'loss_cls': '0.153555', 'loss_bbox': '0.030670', 'loss_rpn_cls': '0.205969', 'loss_rpn_bbox': '0.021068', 'loss_mask': '0.471632', 'loss': '0.983557', eta: 1:14:38, batch_cost: 0.28453 sec, ips: 3.51455 images/sec
2020-12-10 16:32:25,322-INFO: iter: 280, lr: 0.000572, 'loss_cls': '0.171517', 'loss_bbox': '0.026288', 'loss_rpn_cls': '0.195350', 'loss_rpn_bbox': '0.020710', 'loss_mask': '0.441016', 'loss': '0.875865', eta: 1:13:19, batch_cost: 0.27987 sec, ips: 3.57311 images/sec
2020-12-10 16:32:31,078-INFO: iter: 300, lr: 0.000583, 'loss_cls': '0.117856', 'loss_bbox': '0.033234', 'loss_rpn_cls': '0.210216', 'loss_rpn_bbox': '0.038611', 'loss_mask': '0.435820', 'loss': '0.918018', eta: 1:14:43, batch_cost: 0.28557 sec, ips: 3.50179 images/sec
2020-12-10 16:32:36,840-INFO: iter: 320, lr: 0.000594, 'loss_cls': '0.170022', 'loss_bbox': '0.058146', 'loss_rpn_cls': '0.189552', 'loss_rpn_bbox': '0.034136', 'loss_mask': '0.453407', 'loss': '0.905615', eta: 1:15:41, batch_cost: 0.28966 sec, ips: 3.45229 images/sec
2020-12-10 16:32:42,655-INFO: iter: 340, lr: 0.000606, 'loss_cls': '0.133182', 'loss_bbox': '0.036616', 'loss_rpn_cls': '0.174277', 'loss_rpn_bbox': '0.017726', 'loss_mask': '0.436194', 'loss': '0.995786', eta: 1:15:39, batch_cost: 0.28988 sec, ips: 3.44966 images/sec
W1210 16:32:44.706710   336 init.cc:226] Warning: PaddlePaddle catches a failure signal, it may not work properly
W1210 16:32:44.706764   336 init.cc:228] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W1210 16:32:44.706768   336 init.cc:231] The detail failure signal is:

W1210 16:32:44.706782   336 init.cc:234] *** Aborted at 1607589164 (unix time) try "date -d @1607589164" if you are using GNU date ***
W1210 16:32:44.708598   336 init.cc:234] PC: @                0x0 (unknown)
W1210 16:32:44.708952   336 init.cc:234] *** SIGSEGV (@0x100000029) received by PID 268 (TID 0x7fdd02a6f700) from PID 41; stack trace: ***
W1210 16:32:44.710377   336 init.cc:234]     @     0x7fddb7612390 (unknown)
W1210 16:32:44.713127   336 init.cc:234]     @     0x7fdd4292eef8 paddle::memory::detail::MemoryBlock::Split()
W1210 16:32:44.716619   336 init.cc:234]     @     0x7fdd4292d422 _ZN6paddle6memory6detail14BuddyAllocator12SplitToAllocESt23_Rb_tree_const_iteratorISt5tupleIJmmPvEEEm
W1210 16:32:44.720257   336 init.cc:234]     @     0x7fdd4292d905 paddle::memory::detail::BuddyAllocator::Alloc()
W1210 16:32:44.722748   336 init.cc:234]     @     0x7fdd4291d8f5 paddle::memory::legacy::Alloc<>()
W1210 16:32:44.725813   336 init.cc:234]     @     0x7fdd4291e895 paddle::memory::allocation::NaiveBestFitAllocator::AllocateImpl()
W1210 16:32:44.727475   336 init.cc:234]     @     0x7fdd429163df paddle::memory::allocation::AllocatorFacade::Alloc()
W1210 16:32:44.729792   336 init.cc:234]     @     0x7fdd4291662a paddle::memory::allocation::AllocatorFacade::AllocShared()
W1210 16:32:44.731346   336 init.cc:234]     @     0x7fdd42915dfc paddle::memory::AllocShared()
W1210 16:32:44.733083   336 init.cc:234]     @     0x7fdd429025b2 paddle::framework::Tensor::mutable_data()
W1210 16:32:44.734946   336 init.cc:234]     @     0x7fdd41f59633 paddle::operators::SampleMaskForOneImage<>()
W1210 16:32:44.738785   336 init.cc:234]     @     0x7fdd41f5b27f paddle::operators::GenerateMaskLabelsKernel<>::Compute()
W1210 16:32:44.740259   336 init.cc:234]     @     0x7fdd41f5caf3 _ZNSt17_Function_handlerIFvRKN6paddle9framework16ExecutionContextEEZNKS1_24OpKernelRegistrarFunctorINS0_8platform8CPUPlaceELb0ELm0EINS0_9operators24GenerateMaskLabelsKernelIfEEEEclEPKcSE_iEUlS4_E_E9_M_invokeERKSt9_Any_dataS4_
W1210 16:32:44.742941   336 init.cc:234]     @     0x7fdd4287aac0 paddle::framework::OperatorWithKernel::RunImpl()
W1210 16:32:44.746873   336 init.cc:234]     @     0x7fdd4287b2b1 paddle::framework::OperatorWithKernel::RunImpl()
W1210 16:32:44.748977   336 init.cc:234]     @     0x7fdd42874271 paddle::framework::OperatorBase::Run()
W1210 16:32:44.751912   336 init.cc:234]     @     0x7fdd42583b56 paddle::framework::details::ComputationOpHandle::RunImpl()
W1210 16:32:44.754602   336 init.cc:234]     @     0x7fdd42529d31 paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync()
W1210 16:32:44.757570   336 init.cc:234]     @     0x7fdd4252782f paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp()
W1210 16:32:44.758713   336 init.cc:234]     @     0x7fdd42527af4 _ZNSt17_Function_handlerIFvvESt17reference_wrapperISt12_Bind_simpleIFS1_ISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS6_12OpHandleBaseESt6atomicIiESt4hashISA_ESt8equal_toISA_ESaISt4pairIKSA_SC_EEESA_RKSt10shared_ptrINS5_13BlockingQueueImEEEEUlvE_vEEEvEEEE9_M_invokeERKSt9_Any_data
W1210 16:32:44.762122   336 init.cc:234]     @     0x7fdd3f4a2603 std::_Function_handler<>::_M_invoke()
W1210 16:32:44.765487   336 init.cc:234]     @     0x7fdd3f29c2f7 std::__future_base::_State_base::_M_do_set()
W1210 16:32:44.766968   336 init.cc:234]     @     0x7fddb760fa99 __pthread_once_slow
W1210 16:32:44.767976   336 init.cc:234]     @     0x7fdd42523cc2 _ZNSt13__future_base11_Task_stateISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS4_12OpHandleBaseESt6atomicIiESt4hashIS8_ESt8equal_toIS8_ESaISt4pairIKS8_SA_EEES8_RKSt10shared_ptrINS3_13BlockingQueueImEEEEUlvE_vEESaIiEFvvEE6_M_runEv
W1210 16:32:44.771194   336 init.cc:234]     @     0x7fdd3f29e754 _ZZN10ThreadPoolC1EmENKUlvE_clEv
W1210 16:32:44.772045   336 init.cc:234]     @     0x7fdd78006421 execute_native_thread_routine_compat
W1210 16:32:44.773315   336 init.cc:234]     @     0x7fddb76086ba start_thread
W1210 16:32:44.774500   336 init.cc:234]     @     0x7fddb733e41d clone
W1210 16:32:44.775686   336 init.cc:234]     @                0x0 (unknown)
Segmentation fault (core dumped)


```

**Comment by iceriver97** [comment]
官方看到了麻烦回复一下，能解决不能解决都说一下，谢谢啦
```
2020-12-10 20:26:24,811-INFO: iter: 0, lr: 0.000417, 'loss_cls': '2.461162', 'loss_bbox': '0.057673', 'loss_rpn_cls': '0.693961', 'loss_rpn_bbox': '0.034180', 'loss_mask': '0.725688', 'loss': '3.972664', eta: 0:01:23, batch_cost: 0.00523 sec, ips: 191.35472 images/sec
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tools/train.py", line 377, in <module>
    main()
  File "tools/train.py", line 248, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1167, in _run_impl
    return_merged=return_merged)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 879, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::memory::detail::MemoryBlock::Split(paddle::memory::detail::MetadataCache*, unsigned long)
3   paddle::memory::detail::BuddyAllocator::SplitToAlloc(std::_Rb_tree_const_iterator<std::tuple<unsigned long, unsigned long, void*> >, unsigned long)
4   paddle::memory::detail::BuddyAllocator::Alloc(unsigned long)
5   void* paddle::memory::legacy::Alloc<paddle::platform::CPUPlace>(paddle::platform::CPUPlace const&, unsigned long)
6   paddle::memory::allocation::NaiveBestFitAllocator::AllocateImpl(unsigned long)
7   paddle::memory::allocation::AllocatorFacade::Alloc(paddle::platform::Place const&, unsigned long)
8   paddle::memory::allocation::AllocatorFacade::AllocShared(paddle::platform::Place const&, unsigned long)
9   paddle::memory::AllocShared(paddle::platform::Place const&, unsigned long)
10  paddle::framework::Tensor::mutable_data(paddle::platform::Place const&, paddle::framework::proto::VarType_Type, unsigned long)
11  paddle::framework::TensorCopySync(paddle::framework::Tensor const&, paddle::platform::Place const&, paddle::framework::Tensor*)
12  paddle::framework::TransDataDevice(paddle::framework::Tensor const&, paddle::platform::Place const&, paddle::framework::Tensor*)
13  paddle::framework::TransformData(paddle::framework::OpKernelType const&, paddle::framework::OpKernelType const&, paddle::framework::Tensor const&, paddle::framework::Tensor*)
14  paddle::framework::OperatorWithKernel::PrepareData(paddle::framework::Scope const&, paddle::framework::OpKernelType const&, std::vector<std::string, std::allocator<std::string> >*, paddle::framework::RuntimeContext*) const
15  paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
16  paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
17  paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
18  paddle::framework::details::ComputationOpHandle::RunImpl()
19  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*)
20  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*)
21  std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&)
22  std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
23  ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/detection.py", line 455, in rpn_target_assign
    'use_random': use_random
  File "/home/aistudio/work/PaddleDetection/ppdet/core/workspace.py", line 174, in partial_apply
    return op(*args, **kwargs_)
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/anchor_heads/rpn_head.py", line 227, in get_loss
    im_info=im_info)
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/architectures/mask_rcnn.py", line 108, in build
    feed_vars['is_crowd'])
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/architectures/mask_rcnn.py", line 333, in train
    return self.build(feed_vars, 'train')
  File "tools/train.py", line 118, in main
    train_fetches = model.train(feed_vars)
  File "tools/train.py", line 377, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: An error occurred here. There is no accurate error hint for this error yet. We are continuously in the process of increasing hint for this kind of error check. It would be helpful if you could inform us of how this conversion went by opening a github issue. And we will resolve it with high priority.
  - New issue link: https://github.com/PaddlePaddle/Paddle/issues/new
  - Recommended issue content: all error stack information
  [Hint: Expected desc->total_size >= size, but received desc->total_size:0 < size:819200.] at (/paddle/paddle/fluid/memory/detail/memory_block.cc:41)
  [operator < rpn_target_assign > error]
terminate called without an active exception
W1210 20:26:30.261107   376 init.cc:226] Warning: PaddlePaddle catches a failure signal, it may not work properly
W1210 20:26:30.261164   376 init.cc:228] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W1210 20:26:30.261168   376 init.cc:231] The detail failure signal is:

W1210 20:26:30.261175   376 init.cc:234] *** Aborted at 1607603190 (unix time) try "date -d @1607603190" if you are using GNU date ***
W1210 20:26:30.263669   376 init.cc:234] PC: @                0x0 (unknown)
W1210 20:26:30.263767   376 init.cc:234] *** SIGABRT (@0x3e800000139) received by PID 313 (TID 0x7f17587bc700) from PID 313; stack trace: ***
W1210 20:26:30.265808   376 init.cc:234]     @     0x7f17817a5390 (unknown)
W1210 20:26:30.267740   376 init.cc:234]     @     0x7f17813ff428 gsignal
W1210 20:26:30.269656   376 init.cc:234]     @     0x7f178140102a abort
W1210 20:26:30.270943   376 init.cc:234]     @     0x7f174217e84a __gnu_cxx::__verbose_terminate_handler()
W1210 20:26:30.272022   376 init.cc:234]     @     0x7f174217cf47 __cxxabiv1::__terminate()
W1210 20:26:30.273262   376 init.cc:234]     @     0x7f174217cf7d std::terminate()
W1210 20:26:30.274350   376 init.cc:234]     @     0x7f174217cc5a __gxx_personality_v0
W1210 20:26:30.275326   376 init.cc:234]     @     0x7f17424afb97 _Unwind_ForcedUnwind_Phase2
W1210 20:26:30.276301   376 init.cc:234]     @     0x7f17424afe7d _Unwind_ForcedUnwind
W1210 20:26:30.278234   376 init.cc:234]     @     0x7f17817a4070 __GI___pthread_unwind
W1210 20:26:30.280158   376 init.cc:234]     @     0x7f178179c845 __pthread_exit
W1210 20:26:30.280638   376 init.cc:234]     @     0x55ece75f6e59 PyThread_exit_thread
W1210 20:26:30.280759   376 init.cc:234]     @     0x55ece747cc17 PyEval_RestoreThread.cold.798
W1210 20:26:30.282881   376 init.cc:234]     @     0x7f1708eac059 pybind11::gil_scoped_release::~gil_scoped_release()
W1210 20:26:30.283426   376 init.cc:234]     @     0x7f1708f94d05 _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybind10BindReaderEPNS_6moduleEEUlRNS2_9operators6reader40OrderedMultiDeviceLoDTensorBlockingQueueERKSt6vectorINS2_9framework9LoDTensorESaISC_EEE2_bIS9_SG_EINS_4nameENS_9is_methodENS_7siblingENS_10call_guardIINS_18gil_scoped_releaseEEEEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNES11_
W1210 20:26:30.285457   376 init.cc:234]     @     0x7f1708ec9869 pybind11::cpp_function::dispatcher()
W1210 20:26:30.286051   376 init.cc:234]     @     0x55ece7578744 _PyMethodDef_RawFastCallKeywords
W1210 20:26:30.286507   376 init.cc:234]     @     0x55ece7578861 _PyCFunction_FastCallKeywords
W1210 20:26:30.286931   376 init.cc:234]     @     0x55ece75e46e8 _PyEval_EvalFrameDefault
W1210 20:26:30.287328   376 init.cc:234]     @     0x55ece752881a _PyEval_EvalCodeWithName
W1210 20:26:30.287763   376 init.cc:234]     @     0x55ece7529635 _PyFunction_FastCallDict
W1210 20:26:30.288215   376 init.cc:234]     @     0x55ece75e1232 _PyEval_EvalFrameDefault
W1210 20:26:30.288585   376 init.cc:234]     @     0x55ece7577ccb _PyFunction_FastCallKeywords
W1210 20:26:30.289005   376 init.cc:234]     @     0x55ece75dfa93 _PyEval_EvalFrameDefault
W1210 20:26:30.289373   376 init.cc:234]     @     0x55ece7577ccb _PyFunction_FastCallKeywords
W1210 20:26:30.289808   376 init.cc:234]     @     0x55ece75dfa93 _PyEval_EvalFrameDefault
W1210 20:26:30.290233   376 init.cc:234]     @     0x55ece752956b _PyFunction_FastCallDict
W1210 20:26:30.290632   376 init.cc:234]     @     0x55ece7547e53 _PyObject_Call_Prepend
W1210 20:26:30.291075   376 init.cc:234]     @     0x55ece753adbe PyObject_Call
W1210 20:26:30.291252   376 init.cc:234]     @     0x55ece7637817 t_bootstrap
W1210 20:26:30.291332   376 init.cc:234]     @     0x55ece75f2788 pythread_wrapper
W1210 20:26:30.293330   376 init.cc:234]     @     0x7f178179b6ba start_thread
Aborted (core dumped)
```

**Comment by yghstill** [comment]
@iceriver97 更新下Paddle版本到2.0.0.rc再试下呢
