### ISSUE TITLE
ppyolo报错AttributeError: object has no attribute 'log_smooth_window'

### ISSUE THREAD

**Issue by pt1003482256** [PaddlePaddle/PaddleDetection#1879]
2020-12-11 16:48:56,348-WARNING: /home/administrator/.cache/paddle/weights/ResNet50_vd_ssld_pretrained.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
/home/administrator/anaconda3/lib/python3.7/site-packages/paddle/fluid/io.py:1998: UserWarning: This list is not set, Because of Paramerter not found in program. There are: fc_0.w_0 fc_0.b_0
  format(" ".join(unused_para_list)))
2020-12-11 16:49:00,073-INFO: places would be ommited when DataLoader is not iterable
Traceback (most recent call last):
  File "tools/train.py", line 372, in <module>
    main()
  File "tools/train.py", line 220, in main
    train_stats = TrainingStats(cfg.log_smooth_window, train_keys)
  File "/home/administrator/Projects/PaddleDetection-release-0.4/ppdet/core/workspace.py", line 64, in __getattr__
    raise AttributeError("object has no attribute '{}'".format(key))
AttributeError: object has no attribute 'log_smooth_window'

**Comment by yghstill** [comment]
@pt1003482256 应该是你的代码版本与配置文件不匹配了，请直接使用release 0.5的代码与配置文件吧

**Comment by heavengate** [comment]
你好，最近将配置字段`log_smooth_window`重命名为了`log_iter`，应该是你代码版本和配置文件版本不匹配

**Comment by pt1003482256** [comment]
> @pt1003482256 应该是你的代码版本与配置文件不匹配了，请直接使用release 0.5的代码与配置文件吧

是的我也发现了这个问题，我更新到了0.5就行了，问一下我看ppyolo的收敛需要380个epoch是么，谢谢

**Comment by pt1003482256** [comment]
> 你好，最近将配置字段`log_smooth_window`重命名为了`log_iter`，应该是你代码版本和配置文件版本不匹配

是的我也发现了这个问题，我更新到了0.5就行了，问一下我看ppyolo的收敛需要380个epoch是么，谢谢

**Comment by heavengate** [comment]
> > 你好，最近将配置字段`log_smooth_window`重命名为了`log_iter`，应该是你代码版本和配置文件版本不匹配
> 
> 是的我也发现了这个问题，我更新到了0.5就行了，问一下我看ppyolo的收敛需要380个epoch是么，谢谢

yolo收敛比较慢，一般至少训练300个epoch，如果是finetune可以适当减少一些
