### ISSUE TITLE
训练自己的数据集报错

### ISSUE THREAD

**Issue by sifanlook** [PaddlePaddle/PaddleDetection#1906]
E:\baiduai\PaddleDetection>python tools/train.py -c configs/yolov3_mobilenet_v1_roadsign.yml --eval -o use_gpu=true
2020-12-16 17:15:47,566-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000500] in Optimizer will not take effect, and it will only be applied to other Parameters!
**Traceback (most recent call last):**
  File "tools/train.py", line 377, in <module>
    main()
  File "tools/train.py", line 149, in main
    eval_reader = create_reader(cfg.EvalReader, devices_num=1)
  File "E:\baiduai\PaddleDetection\ppdet\data\reader.py", line 441, in create_reader
    reader = Reader(**cfg)()
  File "E:\baiduai\PaddleDetection\ppdet\data\reader.py", line 210, in __init__
    self._roidbs = self._dataset.get_roidb()
  File "E:\baiduai\PaddleDetection\ppdet\data\source\dataset.py", line 68, in get_roidb
    self.load_roidb_and_cname2cid()
  File "E:\baiduai\PaddleDetection\ppdet\data\source\voc.py", line 154, in load_roidb_and_cname2cid
    gt_class.append([cname2cid[cname]])
**KeyError: 'Light_delivery_box'**

**Comment by sifanlook** [comment]
![image](https://user-images.githubusercontent.com/21136881/102329015-c9fdf080-3fc2-11eb-88db-f351561a15f9.png)

**Comment by sifanlook** [comment]
TrainReader:
  inputs_def:
    fields: ['image', 'gt_bbox', 'gt_class', 'gt_score']
    num_max_boxes: 50
  dataset:
    !VOCDataSet
      dataset_dir: dataset/roadsign_voc/train_4
      anno_path: train.txt
      with_background: false
      use_default_label: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
      with_mixup: True
    - !MixupImage
      alpha: 1.5
      beta: 1.5
    - !ColorDistort {}
    - !RandomExpand
      fill_value: [123.675, 116.28, 103.53]
      ratio: 1.5
    - !RandomCrop {}
    - !RandomFlipImage
      is_normalized: false
    - !NormalizeBox {}
    - !PadBox
      num_max_boxes: 50
    - !BboxXYXY2XYWH {}
  batch_transforms:
  - !RandomShape
    sizes: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608]
    random_inter: True
  - !NormalizeImage
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    is_scale: True
    is_channel_first: false
  - !Permute
    to_bgr: false
    channel_first: True
  # Gt2YoloTarget is only used when use_fine_grained_loss set as true,
  # this operator will be deleted automatically if use_fine_grained_loss
  # is set as false
  - !Gt2YoloTarget
    anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
    anchors: [[10, 13], [16, 30], [33, 23],
              [30, 61], [62, 45], [59, 119],
              [116, 90], [156, 198], [373, 326]]
    downsample_ratios: [32, 16, 8]
  batch_size: 1
  shuffle: true
  mixup_epoch: 250
  drop_last: true
  worker_num: 4
  bufsize: 2
  use_process: true


EvalReader:
  inputs_def:
    fields: ['image', 'im_size', 'im_id', 'gt_bbox', 'gt_class', 'is_difficult']
    num_max_boxes: 50
  dataset:
    !VOCDataSet
      dataset_dir: dataset/roadsign_voc/train_4
      anno_path: valid.txt
      with_background: false
      use_default_label: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !ResizeImage
      target_size: 608
      interp: 2
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: True
      is_channel_first: false
    - !PadBox
      num_max_boxes: 50
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 1
  drop_empty: false
  worker_num: 4
  bufsize: 2

TestReader:
  inputs_def:
    image_shape: [3, 608, 608]
    fields: ['image', 'im_size', 'im_id']
  dataset:
    !ImageFolder
      anno_path: dataset/roadsign_voc/train/label_list.txt
      with_background: false
      use_default_label: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !ResizeImage
      target_size: 608
      interp: 2
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: True
      is_channel_first: false
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 1

**Comment by sifanlook** [comment]
部分标注文件
./images/1522484079437.jpg ./annotations/1522484079437.xml
./images/1522484109059.jpg ./annotations/1522484109059.xml
./images/1522485032019.jpg ./annotations/1522485032019.xml
./images/1522485052029.jpg ./annotations/1522485052029.xml
./images/1522485087077.jpg ./annotations/1522485087077.xml
./images/1522485121383.jpg ./annotations/1522485121383.xml
./images/1522485150412.jpg ./annotations/1522485150412.xml
./images/1524017338060.jpg ./annotations/1524017338060.xml
./images/1524017406699.jpg ./annotations/1524017406699.xml
./images/1524105543577.jpg ./annotations/1524105543577.xml
./images/1524107125257.jpg ./annotations/1524107125257.xml
./images/1524185943196.jpg ./annotations/1524185943196.xml
./images/1524200514558.jpg ./annotations/1524200514558.xml
./images/1524203599745.jpg ./annotations/1524203599745.xml
./images/1524213082508.jpg ./annotations/1524213082508.xml
./images/1524274361937.jpg ./annotations/1524274361937.xml
./images/1524362434768.jpg ./annotations/1524362434768.xml
./images/1524468352110.jpg ./annotations/1524468352110.xml
./images/1524469522467.jpg ./annotations/1524469522467.xml
./images/1524964741644.jpg ./annotations/1524964741644.xml
./images/1524964878168.jpg ./annotations/1524964878168.xml
./images/1534234500403.jpg ./annotations/1534234500403.xml
./images/20201016093713168066_images.jpg ./annotations/20201016093713168066_images.xml
./images/20201016093810150208_images.jpg ./annotations/20201016093810150208_images.xml
./images/20201016093837224045_images.jpg ./annotations/20201016093837224045_images.xml
./images/20201016094850809408_images.jpg ./annotations/20201016094850809408_images.xml
./images/20201016095040135009_images.jpg ./annotations/20201016095040135009_images.xml
./images/20201016112528185984_images.jpg ./annotations/20201016112528185984_images.xml
./images/20201016114231206907_images.jpg ./annotations/20201016114231206907_images.xml
./images/20201016114301112473_images.jpg ./annotations/20201016114301112473_images.xml
./images/20201017091709825830_images.jpg ./annotations/20201017091709825830_images.xml
./images/20201017091745203311_images.jpg ./annotations/20201017091745203311_images.xml
./images/20201017091809100012_images.jpg ./annotations/20201017091809100012_images.xml
./images/20201017091833611204_images.jpg ./annotations/20201017091833611204_images.xml
./images/20201017091904790709_images.jpg ./annotations/20201017091904790709_images.xml
./images/20201017091939533388_images.jpg ./annotations/20201017091939533388_images.xml
./images/20201017133601119436_images.jpg ./annotations/20201017133601119436_images.xml
./images/20201017133734441014_images.jpg ./annotations/20201017133734441014_images.xml
./images/20201017133800155636_images.jpg ./annotations/20201017133800155636_images.xml
./images/20201017133842202401_images.jpg ./annotations/20201017133842202401_images.xml
./images/20201018131414132344_images.jpg ./annotations/20201018131414132344_images.xml
./images/20201018131433140584_images.jpg ./annotations/20201018131433140584_images.xml
./images/20201018131503193746_images.jpg ./annotations/20201018131503193746_images.xml
./images/20201018131523130376_images.jpg ./annotations/20201018131523130376_images.xml
./images/20201018131545130445_images.jpg ./annotations/20201018131545130445_images.xml
./images/20201018131607866259_images.jpg ./annotations/20201018131607866259_images.xml
./images/20201018133600438156_images.jpg ./annotations/20201018133600438156_images.xml
./images/20201018133636893316_images.jpg ./annotations/20201018133636893316_images.xml
./images/20201018133654149422_images.jpg ./annotations/20201018133654149422_images.xml
./images/20201018133745196471_images.jpg ./annotations/20201018133745196471_images.xml
./images/20201018140216869200_images.jpg ./annotations/20201018140216869200_images.xml
./images/20201018140257118774_images.jpg ./annotations/20201018140257118774_images.xml
./images/20201018140316149708_images.jpg ./annotations/20201018140316149708_images.xml
./images/20201018140429219562_images.jpg ./annotations/20201018140429219562_images.xml
./images/20201019101527536043_images.jpg ./annotations/20201019101527536043_images.xml

**Comment by sifanlook** [comment]
用官方数据集是没问题的

**Comment by heavengate** [comment]
用的默认的官方VOC里的20类，用自己的数据集的话把类别名更新到`dataset/voc/label_list.txt`里面，把Reader里的`use_default_label`设置成False

**Comment by sifanlook** [comment]
> 用的默认的官方VOC里的20类，用自己的数据集的话把类别名更新到`dataset/voc/label_list.txt`里面，把Reader里的`use_default_label`设置成False


按照您的方法跑起来了，但是训练途中一直报这个错误。
tools/train.py:261: RuntimeWarning: divide by zero encountered in double_scalars
  ips = float(cfg['TrainReader']['batch_size']) / time_cost
2020-12-16 18:33:50,776-INFO: iter: 0, lr: 0.000033, 'loss': '14032.178711', eta: 0:00:00, batch_cost: 0.00000 sec, ips: inf images/sec
2020-12-16 18:34:02,397-INFO: iter: 20, lr: 0.000047, 'loss': '63.760021', eta: 0:38:27, batch_cost: 0.64445 sec, ips: 6.20686 images/sec
2020-12-16 18:34:17,429-INFO: iter: 40, lr: 0.000060, 'loss': '59.166908', eta: 0:42:21, batch_cost: 0.71390 sec, ips: 5.60302 images/sec
2020-12-16 18:34:30,765-INFO: iter: 60, lr: 0.000073, 'loss': '48.425682', eta: 0:38:27, batch_cost: 0.65190 sec, ips: 6.13591 images/sec
2020-12-16 18:34:43,534-INFO: iter: 80, lr: 0.000087, 'loss': '34.117207', eta: 0:39:47, batch_cost: 0.67840 sec, ips: 5.89623 images/sec
2020-12-16 18:34:55,446-INFO: iter: 100, lr: 0.000100, 'loss': '40.600662', eta: 0:36:15, batch_cost: 0.62150 sec, ips: 6.43604 images/sec
2020-12-16 18:35:05,902-INFO: iter: 120, lr: 0.000100, 'loss': '37.454903', eta: 0:28:34, batch_cost: 0.49255 sec, ips: 8.12100 images/sec
2020-12-16 18:35:16,782-INFO: iter: 140, lr: 0.000100, 'loss': '28.579811', eta: 0:31:34, batch_cost: 0.54740 sec, ips: 7.30727 images/sec
2020-12-16 18:35:34,230-INFO: iter: 160, lr: 0.000100, 'loss': '36.598282', eta: 0:48:27, batch_cost: 0.84525 sec, ips: 4.73233 images/sec
2020-12-16 18:35:47,442-INFO: iter: 180, lr: 0.000100, 'loss': '44.275574', eta: 0:39:50, batch_cost: 0.69885 sec, ips: 5.72369 images/sec
2020-12-16 18:35:58,608-INFO: iter: 200, lr: 0.000100, 'loss': '32.123978', eta: 0:32:23, batch_cost: 0.57170 sec, ips: 6.99668 images/sec
2020-12-16 18:35:58,611-INFO: Save model to output\yolov3_mobilenet_v1_roadsign\200.
W1216 18:36:03.129699 10896 build_strategy.cc:170] fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU.
2020-12-16 18:36:04,349-INFO: Test iter 0
2020-12-16 18:36:14,625-INFO: Test finish iter 38
2020-12-16 18:36:14,625-INFO: Total number of images: 152, inference time: 13.210499095714741 fps.
2020-12-16 18:36:14,627-INFO: Start evaluate...
Traceback (most recent call last):
  File "tools/train.py", line 377, in <module>
    main()
  File "tools/train.py", line 298, in main
    cfg['EvalReader']['dataset'])
  File "E:\baiduai\PaddleDetection\ppdet\utils\eval_utils.py", line 267, in eval_results
    map_type=map_type)
  File "E:\baiduai\PaddleDetection\ppdet\utils\voc_eval.py", line 88, in bbox_eval
    detection_map.update(bbox, gt_box, gt_label, difficult)
  File "E:\baiduai\PaddleDetection\ppdet\utils\map_utils.py", line 104, in update
    self.class_gt_counts[int(np.array(gtl))] += 1
**IndexError: list index out of range**

**Comment by gaoxinghua951** [comment]
请问eval的错误解决了吗
