### ISSUE TITLE
yolov3训练报错

### ISSUE THREAD

**Issue by 1360011612** [PaddlePaddle/PaddleDetection#1908]
2020-12-17 02:26:46,235-INFO: iter: 100, lr: 0.000100, 'loss_xy': '135.935394', 'loss_wh': '47.301704', 'loss_obj': '354.842133', 'loss_cls': '55.082664', 'loss_iou': '911.067627', 'loss': '1598.079102', eta: 1:57:13, batch_cost: 0.10062 sec, ips: 9.93797 images/sec
2020-12-17 02:26:48,146-WARNING: recv endsignal from outq with errmsg[consumer[consumer-4f9-7] exits for reason[consumer[consumer-4f9-1] exits for reason[consumer[consumer-4f9-6] exits for reason[consumer[consumer-4f9-4] exits for reason[consumer[consumer-4f9-2] failed to map with error:[index 64 is out of bounds for axis 2 with size 64]]]]]]
2020-12-17 02:26:48,935-INFO: iter: 120, lr: 0.000120, 'loss_xy': '126.997360', 'loss_wh': '57.258072', 'loss_obj': '368.667328', 'loss_cls': '40.080303', 'loss_iou': '881.374634', 'loss': '1551.426880', eta: 2:35:56, batch_cost: 0.13390 sec, ips: 7.46830 images/sec
2020-12-17 02:26:51,830-WARNING: recv endsignal from outq with errmsg[consumer[consumer-4f9-0] exits for reason[consumer[consumer-4f9-7] exits for reason[consumer[consumer-4f9-1] exits for reason[consumer[consumer-4f9-6] exits for reason[consumer[consumer-4f9-4] exits for reason[consumer[consumer-4f9-2] failed to map with error:[index 64 is out of bounds for axis 2 with size 64]]]]]]]
2020-12-17 02:26:53,243-INFO: iter: 140, lr: 0.000140, 'loss_xy': '137.881683', 'loss_wh': '49.964123', 'loss_obj': '319.969482', 'loss_cls': '38.703865', 'loss_iou': '921.292236', 'loss': '1480.170166', eta: 4:10:55, batch_cost: 0.21552 sec, ips: 4.64001 images/sec
2020-12-17 02:26:56,793-WARNING: recv endsignal from outq with errmsg[consumer[consumer-4f9-5] exits for reason[consumer[consumer-4f9-0] exits for reason[consumer[consumer-4f9-7] exits for reason[consumer[consumer-4f9-1] exits for reason[consumer[consumer-4f9-6] exits for reason[consumer[consumer-4f9-4] exits for reason[consumer[consumer-4f9-2] failed to map with error:[index 64 is out of bounds for axis 2 with size 64]]]]]]]]
2020-12-17 02:27:00,257-INFO: iter: 160, lr: 0.000160, 'loss_xy': '138.785248', 'loss_wh': '65.805779', 'loss_obj': '304.362183', 'loss_cls': '50.232704', 'loss_iou': '900.173889', 'loss': '1536.736328', eta: 6:43:56, batch_cost: 0.34703 sec, ips: 2.88158 images/sec
2020-12-17 02:27:05,633-WARNING: recv endsignal from outq with errmsg[consumer[consumer-4f9-3] exits for reason[consumer[consumer-4f9-5] exits for reason[consumer[consumer-4f9-0] exits for reason[consumer[consumer-4f9-7] exits for reason[consumer[consumer-4f9-1] exits for reason[consumer[consumer-4f9-6] exits for reason[consumer[consumer-4f9-4] exits for reason[consumer[consumer-4f9-2] failed to map with error:[index 64 is out of bounds for axis 2 with size 64]]]]]]]]]
/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/reader.py:1188: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
  logging.warn('Your reader has raised an exception!')
2020-12-17 02:27:05,634-WARNING: Your reader has raised an exception!
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1189, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/root/miniconda3/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1169, in __thread_main__
    for tensors in self._tensor_reader():
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1239, in __tensor_reader_impl__
    for slots in paddle_reader():
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 546, in __reader_creator__
    for item in reader():
  File "/root/PaddleDetection/ppdet/data/reader.py", line 452, in _reader
    reader.reset()
  File "/root/PaddleDetection/ppdet/data/parallel_map.py", line 259, in reset
    assert not self._exit, "cannot reset for already stopped dataset"
AssertionError: cannot reset for already stopped dataset

Traceback (most recent call last):
  File "tools/train.py", line 377, in <module>
    main()
  File "tools/train.py", line 248, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1107, in run
    six.reraise(*sys.exc_info())
  File "/root/miniconda3/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1105, in run
    return_merged=return_merged)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1242, in _run_impl
    return_merged=return_merged)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", line 910, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

  Compile Traceback (most recent call last):
    File "tools/train.py", line 377, in <module>
      main()
    File "tools/train.py", line 117, in main
      feed_vars, train_loader = model.build_inputs(**inputs_def)
    File "/root/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 155, in build_inputs
      iterable=iterable) if use_dataloader else None
    File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/reader.py", line 682, in from_generator
      iterable, return_list, drop_last)
    File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1022, in __init__
      self._init_non_iterable()
    File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1124, in _init_non_iterable
      attrs={'drop_last': self._drop_last})
    File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2917, in append_op
      attrs=kwargs.get("attrs", None))
    File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2014, in __init__
      for frame in traceback.extract_stack():

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const
1   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
2   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
5   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
6   paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
FatalError: Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:154)
  [operator < read > error]

**Comment by yghstill** [comment]
@1360011612 确认一下类别数num_classes是否设置的正确？

**Comment by 1360011612** [comment]
类别数是正确的，程序也可以运行，只是运行一段时间后就报这个错误

**Comment by Wenxin-piggy** [comment]
> @1360011612 确认一下类别数num_classes是否设置的正确？

您好，我留意到原先yolov3的配置文件中，num_classes = 80，那么他是默认不算背景吗

**Comment by 1360011612** [comment]
@Wenxin-piggy 不算背景
