### ISSUE TITLE
PaddleDetection自制数据集标签问题

### ISSUE THREAD

**Issue by visionary0421** [PaddlePaddle/PaddleDetection#1994]
在制作自己数据集的时候，先用labelme进行标注，先后转换成VOC和COCO格式的数据集都显示同一个问题。我将数据集格式和昆虫数据集调制一样，不知道问题出在哪里。
```
 python -u tools/train.py -c configs/faster_rcnn_r50_fpn_1x.yml --eval 
2021-01-02 21:37:24,127-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000100] in Optimizer will not take effect, and it will only be applied to other Parameters!
Traceback (most recent call last):
  File "tools/train.py", line 377, in <module>
    main()
  File "tools/train.py", line 149, in main
    eval_reader = create_reader(cfg.EvalReader, devices_num=1)
  File "E:\lhq_code\PaddleDetection\ppdet\data\reader.py", line 441, in create_reader
    reader = Reader(**cfg)()
  File "E:\lhq_code\PaddleDetection\ppdet\data\reader.py", line 210, in __init__
    self._roidbs = self._dataset.get_roidb()
  File "E:\lhq_code\PaddleDetection\ppdet\data\source\dataset.py", line 68, in get_roidb
    self.load_roidb_and_cname2cid()
  File "E:\lhq_code\PaddleDetection\ppdet\data\source\voc.py", line 122, in load_roidb_and_cname2cid
    tree = ET.parse(xml_file)
  File "D:\Anaconda\lib\xml\etree\ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "D:\Anaconda\lib\xml\etree\ElementTree.py", line 595, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: mismatched tag: line 17, column 19
```

下面是xml文件的内容。
```
<annotation>
  <folder/>
  <filename>n_1.jpg</filename>
  <database/>
  <annotation/>
  <image/>
  <size>
    <height>910</height>
    <width>924</width>
    <depth>3</depth>
  </size>
  <segmented/>
  <object>
    <name>n</name>
    <pose/>
    <truncated/>
    <difficult/>0</difficult>
    <bndbox>
      <xmin>118.0</xmin>
      <ymin>108.0</ymin>
      <xmax>789.0</xmax>
      <ymax>740.0</ymax>
    </bndbox>
  </object>
</annotation>

```
请问是否是我的标签有问题，是否能指导怎么修改~谢谢各位大大

**Comment by yghstill** [comment]
@visionary0421 检查一下xml文件的格式吧，比如`<pose/>`前要有`<pose>`，报错显示是xml文件第17行格式错误。

**Comment by visionary0421** [comment]
> @visionary0421 检查一下xml文件的格式吧，比如`<pose/>`前要有`<pose>`，报错显示是xml文件第17行格式错误。

好的，谢谢您。我再去看看其他数据集的格式。
