### ISSUE TITLE
paddledetection安装后例程无法运行的问题

### ISSUE THREAD

**Issue by CVdandelion** [PaddlePaddle/PaddleDetection#1995]
paddledetection安装成功后运行，快速开始目录下的：
python tools/train.py -c configs/yolov3_mobilenet_v1_roadsign.yml --eval -o use_gpu=true
报以下错误：
(newpaddle) robot@robot:~/workspace/PaddleDetection$ python tools/train.py -c configs/yolov3_mobilenet_v1_roadsign.yml --eval -o use_gpu=true
2021-01-04 08:39:29,922-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000500] in Optimizer will not take effect, and it will only be applied to other Parameters!
2021-01-04 08:39:30,231-ERROR: Config dataset_dir dataset/roadsign_voc is not exits!
2021-01-04 08:39:30,232-WARNING: Config annotation dataset/roadsign_voc/valid.txt is not a file, dataset config is not valid
2021-01-04 08:39:30,232-INFO: Dataset /home/robot/workspace/PaddleDetection/dataset/roadsign_voc is not valid for reason above, try searching /home/robot/.cache/paddle/dataset or downloading dataset...
2021-01-04 08:39:30,232-INFO: Found /home/robot/.cache/paddle/dataset/roadsign_voc/annotations
2021-01-04 08:39:30,232-INFO: Found /home/robot/.cache/paddle/dataset/roadsign_voc/images
W0104 08:39:30.257422 14566 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.2, Runtime API Version: 10.0
W0104 08:39:30.257510 14566 device_context.cc:260] device: 0, cuDNN Version: 7.6.
2021-01-04 08:39:31,293-WARNING: /home/robot/.cache/paddle/weights/yolov3_mobilenet_v1.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2021-01-04 08:39:31,382-WARNING: variable yolo_output.0.conv.bias not used
2021-01-04 08:39:31,383-WARNING: variable yolo_output.2.conv.bias not used
2021-01-04 08:39:31,383-WARNING: variable yolo_output.2.conv.weights not used
2021-01-04 08:39:31,383-WARNING: variable yolo_output.1.conv.bias not used
2021-01-04 08:39:31,383-WARNING: variable yolo_output.0.conv.weights not used
2021-01-04 08:39:31,383-WARNING: variable yolo_output.1.conv.weights not used
2021-01-04 08:39:31,440-ERROR: Config dataset_dir dataset/roadsign_voc is not exits!
2021-01-04 08:39:31,440-WARNING: Config annotation dataset/roadsign_voc/train.txt is not a file, dataset config is not valid
2021-01-04 08:39:31,440-INFO: Dataset /home/robot/workspace/PaddleDetection/dataset/roadsign_voc is not valid for reason above, try searching /home/robot/.cache/paddle/dataset or downloading dataset...
2021-01-04 08:39:31,440-INFO: Found /home/robot/.cache/paddle/dataset/roadsign_voc/annotations
2021-01-04 08:39:31,441-INFO: Found /home/robot/.cache/paddle/dataset/roadsign_voc/images
Traceback (most recent call last):
  File "tools/train.py", line 399, in <module>
    main()
  File "tools/train.py", line 232, in main
    num_trainers=num_trainers)
  File "/home/robot/workspace/PaddleDetection/ppdet/data/reader.py", line 442, in create_reader
    reader = Reader(**cfg)()
  File "/home/robot/workspace/PaddleDetection/ppdet/data/reader.py", line 272, in __init__
    use_process, memsize)
  File "/home/robot/workspace/PaddleDetection/ppdet/data/parallel_map.py", line 86, in __init__
    self._setup()
  File "/home/robot/workspace/PaddleDetection/ppdet/data/parallel_map.py", line 105, in _setup
    self._inq = Queue(bufsize, memsize=memsize)
  File "/home/robot/workspace/PaddleDetection/ppdet/data/shared_queue/queue.py", line 63, in __init__
    capacity=memsize, pagesize=pagesize)
  File "/home/robot/workspace/PaddleDetection/ppdet/data/shared_queue/sharedmemory.py", line 415, in __init__
    self._setup()
  File "/home/robot/workspace/PaddleDetection/ppdet/data/shared_queue/sharedmemory.py", line 418, in _setup
    self._shared_mem = RawArray('c', self._cap)
  File "/home/robot/anaconda3/envs/newpaddle/lib/python3.6/multiprocessing/context.py", line 129, in RawArray
    return RawArray(typecode_or_type, size_or_initializer)
  File "/home/robot/anaconda3/envs/newpaddle/lib/python3.6/multiprocessing/sharedctypes.py", line 60, in RawArray
    obj = _new_value(type_)
  File "/home/robot/anaconda3/envs/newpaddle/lib/python3.6/multiprocessing/sharedctypes.py", line 40, in _new_value
    wrapper = heap.BufferWrapper(size)
  File "/home/robot/anaconda3/envs/newpaddle/lib/python3.6/multiprocessing/heap.py", line 248, in __init__
    block = BufferWrapper._heap.malloc(size)
  File "/home/robot/anaconda3/envs/newpaddle/lib/python3.6/multiprocessing/heap.py", line 230, in malloc
    (arena, start, stop) = self._malloc(size)
  File "/home/robot/anaconda3/envs/newpaddle/lib/python3.6/multiprocessing/heap.py", line 128, in _malloc
    arena = Arena(length)
  File "/home/robot/anaconda3/envs/newpaddle/lib/python3.6/multiprocessing/heap.py", line 77, in __init__
    f.write(zeros)
OSError: [Errno 28] No space left on device
Exception ignored in: <bound method SharedMemoryMgr.__del__ of <ppdet.data.shared_queue.sharedmemory.SharedMemoryMgr object at 0x7f7b6792f588>>
Traceback (most recent call last):
  File "/home/robot/workspace/PaddleDetection/ppdet/data/shared_queue/sharedmemory.py", line 524, in __del__
    if not self._released and not self._allocator.empty():
AttributeError: 'SharedMemoryMgr' object has no attribute '_allocator'
请问是什么原因？

**Comment by yghstill** [comment]
@CVdandelion 根据报错信息，是共享内存不够，将https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-beta/configs/yolov3_mobilenet_v1_roadsign.yml#L118  use_process设为False再试下吧
