### ISSUE TITLE
AssertionError: cannot reset for already stopped dataset

### ISSUE THREAD

**Issue by abanger** [PaddlePaddle/PaddleDetection#1997]
训练出现如下错误是什么原因？

(paddlex) root@test:/home/PaddleDetection# python tools/train.py -c mask_rcnn_r50_vd_fpn_2x.yml -o use_gpu=true --eval
/home/detection/PaddleDetection/ppdet/core/workspace.py:118: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  isinstance(merge_dct[k], collections.Mapping)):
/opt/anaconda3/envs/paddlehelix/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:297: UserWarning: /home/detection/PaddleDetection/ppdet/modeling/backbones/fpn.py:108
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
2021-01-04 02:55:17,824-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000100] in Optimizer will not take effect, and it will only be applied to other Parameters!
/opt/anaconda3/envs/paddlehelix/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:297: UserWarning: /home/detection/PaddleDetection/ppdet/modeling/roi_heads/bbox_head.py:315
The behavior of expression A / B has been unified with elementwise_div(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_div(X, Y, axis=0) instead of A / B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/opt/anaconda3/envs/paddlehelix/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:297: UserWarning: /home/detection/PaddleDetection/ppdet/modeling/architectures/mask_rcnn.py:253
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
W0104 02:55:18.693403 26235 device_context.cc:320] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 10.1, Runtime API Version: 10.1
W0104 02:55:18.700395 26235 device_context.cc:330] device: 0, cuDNN Version: 7.6.
2021-01-04 02:55:29,632-WARNING: variable file [ /root/.cache/paddle/weights/ResNet50_vd_pretrained/fc_0.w_0 /root/.cache/paddle/weights/ResNet50_vd_pretrained/fc_0.b_0 ] not used
/home/detection/PaddleDetection/ppdet/data/reader.py:89: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  if isinstance(item, collections.Sequence) and len(item) == 0:
/home/detection/PaddleDetection/ppdet/data/parallel_map.py:243: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  .format(sample.errmsg))
2021-01-04 02:55:35,105-WARNING: recv endsignal from outq with errmsg[consumer[consumer-0f1-0] exits for reason[producer[producer-0f1] failed with error: ]]
2021-01-04 02:55:35,106-WARNING: recv endsignal from outq with errmsg[consumer[consumer-0f1-1] exits for reason[consumer[consumer-0f1-0] exits for reason[producer[producer-0f1] failed with error: ]]]
/opt/anaconda3/envs/paddlehelix/lib/python3.7/site-packages/paddle/fluid/reader.py:1255: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
  logging.warn('Your reader has raised an exception!')
2021-01-04 02:55:35,106-WARNING: Your reader has raised an exception!
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/paddlehelix/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/anaconda3/envs/paddlehelix/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda3/envs/paddlehelix/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1256, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/opt/anaconda3/envs/paddlehelix/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/anaconda3/envs/paddlehelix/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1236, in __thread_main__
    for tensors in self._tensor_reader():
  File "/opt/anaconda3/envs/paddlehelix/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1306, in __tensor_reader_impl__
    for slots in paddle_reader():
  File "/opt/anaconda3/envs/paddlehelix/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 550, in __reader_creator__
    for item in reader():
  File "/home/detection/PaddleDetection/ppdet/data/reader.py", line 453, in _reader
    reader.reset()
  File "/home/detection/PaddleDetection/ppdet/data/parallel_map.py", line 259, in reset
    assert not self._exit, "cannot reset for already stopped dataset"
AssertionError: cannot reset for already stopped dataset

Traceback (most recent call last):
  File "tools/train.py", line 399, in <module>
    main()
  File "tools/train.py", line 270, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "/opt/anaconda3/envs/paddlehelix/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1108, in run
    six.reraise(*sys.exc_info())
  File "/opt/anaconda3/envs/paddlehelix/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/anaconda3/envs/paddlehelix/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1106, in run
    return_merged=return_merged)
  File "/opt/anaconda3/envs/paddlehelix/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1249, in _run_impl
    return_merged=return_merged)
  File "/opt/anaconda3/envs/paddlehelix/lib/python3.7/site-packages/paddle/fluid/executor.py", line 911, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
SystemError: In user code:

    File "tools/train.py", line 399, in <module>
      main()
    File "tools/train.py", line 135, in main
      feed_vars, train_loader = model.build_inputs(**inputs_def)
    File "/home/detection/PaddleDetection/ppdet/modeling/architectures/mask_rcnn.py", line 329, in build_inputs
      iterable=iterable) if use_dataloader else None
    File "/opt/anaconda3/envs/paddlehelix/lib/python3.7/site-packages/paddle/fluid/reader.py", line 741, in from_generator
      iterable, return_list, drop_last)
    File "/opt/anaconda3/envs/paddlehelix/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1089, in __init__
      self._init_non_iterable()
    File "/opt/anaconda3/envs/paddlehelix/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1191, in _init_non_iterable
      attrs={'drop_last': self._drop_last})
    File "/opt/anaconda3/envs/paddlehelix/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2846, in append_op
      attrs=kwargs.get("attrs", None))
    File "/opt/anaconda3/envs/paddlehelix/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1931, in __init__
      for frame in traceback.extract_stack():

    FatalError: Blocking queue is killed because the data reader raises an exception.
      [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:154)
      [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
      [operator < read > error]
(paddlex) root@test:/home/detection/PaddleDetection#

**Comment by abanger** [comment]
运行如下测试程序
```

 from ppdet.core.workspace import load_config
from ppdet.data.reader import create_reader
config_path='mask_rcnn_r50_vd_fpn_2x.yml'
cfg = load_config(config_path)
train_reader = create_reader(cfg.TrainReader, 10)()  # 10代表10个iter
for samples in train_reader:
    for sample in samples:
        print(sample)  # sample是image，im_info等组成的tuple
```
出错如下

(paddlex) root@test:/home/PaddleDetection# python detection_test.py
recv endsignal from outq with errmsg[consumer[consumer-cba-0] exits for reason[producer[producer-cba] failed with error: ]]
recv endsignal from outq with errmsg[consumer[consumer-cba-1] exits for reason[consumer[consumer-cba-0] exits for reason[producer[producer-cba] failed with error: ]]]
Traceback (most recent call last):
  File "detection_test.py", line 6, in <module>
    for samples in train_reader:
  File "/home/PaddleDetection/ppdet/data/reader.py", line 453, in _reader
    reader.reset()
  File "/home/detection/PaddleDetection/ppdet/data/parallel_map.py", line 259, in reset
    assert not self._exit, "cannot reset for already stopped dataset"
AssertionError: cannot reset for already stopped dataset
(paddlex) root@test:/home/PaddleDetection#
(paddlex) root@test:/home/PaddleDetection#

注释掉：
  #worker_num: 2
(paddlex) root@test:/home/PaddleDetection# python detection_test.py
Traceback (most recent call last):
  File "detection_test.py", line 6, in <module>
    for samples in train_reader:
  File "/home/detection/PaddleDetection/ppdet/data/reader.py", line 447, in _reader
    for _batch in reader:
  File "/home/detection/PaddleDetection/ppdet/data/reader.py", line 316, in __next__
    return self.next()
  File "/home/detection/PaddleDetection/ppdet/data/reader.py", line 323, in next
    batch = self._load_batch()
  File "/home/detection/PaddleDetection/ppdet/data/reader.py", line 351, in _load_batch
    if _has_empty(_segm(sample)):
  File "/home/detection/PaddleDetection/ppdet/data/reader.py", line 99, in _segm
    assert 'gt_poly' in samples
AssertionError

**Comment by abanger** [comment]
配置文件：
architecture: MaskRCNN
use_gpu: true
max_iters: 360000
snapshot_iter: 10000
log_smooth_window: 20
save_dir: ./saved_model/mask_rcnn_r50_vd_fpn_2x
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_vd_pretrained.tar
#metric: COCO
metric: VOC
weights: ./saved_model/mask_rcnn_r50_vd_fpn_2x/model_final
num_classes: 7

MaskRCNN:
  backbone: ResNet
  fpn: FPN
  rpn_head: FPNRPNHead
  roi_extractor: FPNRoIAlign
  bbox_head: BBoxHead
  bbox_assigner: BBoxAssigner

ResNet:
  depth: 50
  feature_maps: [2, 3, 4, 5]
  freeze_at: 2
  norm_type: affine_channel
  variant: d

FPN:
  max_level: 6
  min_level: 2
  num_chan: 256
  spatial_scale: [0.03125, 0.0625, 0.125, 0.25]

FPNRPNHead:
  anchor_generator:
    aspect_ratios: [0.5, 1.0, 2.0]
    variance: [1.0, 1.0, 1.0, 1.0]
  anchor_start_size: 32
  max_level: 6
  min_level: 2
  num_chan: 256
  rpn_target_assign:
    rpn_batch_size_per_im: 256
    rpn_fg_fraction: 0.5
    rpn_negative_overlap: 0.3
    rpn_positive_overlap: 0.7
    rpn_straddle_thresh: 0.0
  train_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 2000
    post_nms_top_n: 2000
  test_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 1000
    post_nms_top_n: 1000

FPNRoIAlign:
  canconical_level: 4
  canonical_size: 224
  max_level: 5
  min_level: 2
  box_resolution: 7
  sampling_ratio: 2
  mask_resolution: 14

MaskHead:
  dilation: 1
  conv_dim: 256
  num_convs: 4
  resolution: 28

BBoxAssigner:
  batch_size_per_im: 512
  bbox_reg_weights: [0.1, 0.1, 0.2, 0.2]
  bg_thresh_hi: 0.5
  bg_thresh_lo: 0.0
  fg_fraction: 0.25
  fg_thresh: 0.5

MaskAssigner:
  resolution: 28

BBoxHead:
  head: TwoFCHead
  nms:
    keep_top_k: 100
    nms_threshold: 0.5
    score_threshold: 0.05

TwoFCHead:
  mlp_dim: 1024

LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [240000, 320000]
  - !LinearWarmup
    start_factor: 0.3333333333333333
    steps: 500

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2

_READER_: 'mask_fpn_reader.yml'

TrainReader:
  inputs_def:
    fields: ['image', 'im_info', 'im_id', 'gt_bbox', 'gt_class', 'is_crowd', 'gt_mask']
  dataset:
    #!COCODataSet
    !VOCDataSet
    image_dir: train_20201231
    anno_path: train_20201231/train_list.txt
    dataset_dir: train_20201231
  sample_transforms:
  - !DecodeImage
    to_rgb: true
#  - !RandomFlipImage
#    prob: 0.5
#    is_mask_flip: true
#    is_normalized: false
#  - !NormalizeImage
#    is_channel_first: false
#    is_scale: true
#    mean: [0.485,0.456,0.406]
#    std: [0.229, 0.224,0.225]
#  - !ResizeImage
#    target_size: 800
#    max_size: 1333
#    interp: 1
#    use_cv2: true
#  - !Permute
#    to_bgr: false
#    channel_first: true
#  batch_transforms:
#  - !PadBatch
#    pad_to_stride: 32
#    use_padded_im_info: false
  batch_size: 2
  shuffle: true
  #worker_num: 2
  drop_last: false
  use_process: false

EvalReader:
  inputs_def:
    #fields: ['image', 'im_info', 'im_id', 'im_shape']
    # for voc
    #fields: ['image', 'im_info', 'im_id', 'gt_bbox', 'gt_class', 'is_difficult']
    fields: ['image', 'im_info', 'im_id', 'im_shape']
  dataset:
    #!COCODataSet
    !VOCDataSet
    image_dir: train_20201231
    anno_path: train_20201231/val_list.txt
    dataset_dir: train_20201231
  sample_transforms:
  - !DecodeImage
    to_rgb: true
  - !NormalizeImage
    is_channel_first: false
    is_scale: true
    mean: [0.485,0.456,0.406]
    std: [0.229, 0.224,0.225]
  - !ResizeImage
    interp: 1
    max_size: 1333
    target_size: 800
    use_cv2: true
  - !Permute
    channel_first: true
    to_bgr: false
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
    use_padded_im_info: true
  batch_size: 1
  shuffle: false
  drop_last: false
  drop_empty: false
  worker_num: 2

TestReader:
  inputs_def:
    fields: ['image', 'im_info', 'im_id', 'im_shape']
  dataset:
    !ImageFolder
    anno_path: annotations/instances_val2017.json
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !NormalizeImage
    is_channel_first: false
    is_scale: true
    mean: [0.485,0.456,0.406]
    std: [0.229, 0.224,0.225]
  - !ResizeImage
    interp: 1
    max_size: 1333
    target_size: 800
    use_cv2: true
  - !Permute
    channel_first: true
    to_bgr: false
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
    use_padded_im_info: true
  batch_size: 1
  shuffle: false
  drop_last: false

**Comment by abanger** [comment]
MaskRCNN 无法使用？

**Comment by kaixin-bai** [comment]
看你close掉了，是问题解决了吗？
