### ISSUE TITLE
利用mask rcnn进行训练，训练过程中突然检测不到目标。

### ISSUE THREAD

**Issue by shen-wenxin** [PaddlePaddle/PaddleDetection#2035]
您好，我在利用mask_rcnn_r50_vd_fpn_2进行训练的时候，开了eval。
在并设置snapshot_iter为10000
在前5万次iters中，eval均正常都可以有如下的提示信息：

```
2021-01-10 10:18:15,145-INFO: iter: 49800, lr: 0.025000, 'loss_cls': '0.035417', 'loss_bbox': '0.014732', 'loss_rpn_cls': '0.000304', 'loss_rpn_bbox': '0.003781', 'loss_mask': '0.090412', 'loss': '0.147450', eta: 5:43:39, batch_cost: 0.21889 sec, ips: 4.56858 images/sec
2021-01-10 10:18:37,716-INFO: iter: 49900, lr: 0.025000, 'loss_cls': '0.039336', 'loss_bbox': '0.015773', 'loss_rpn_cls': '0.000243', 'loss_rpn_bbox': '0.002901', 'loss_mask': '0.095032', 'loss': '0.151797', eta: 5:54:19, batch_cost: 0.22592 sec, ips: 4.42629 images/sec
2021-01-10 10:19:00,379-INFO: iter: 50000, lr: 0.025000, 'loss_cls': '0.038313', 'loss_bbox': '0.017387', 'loss_rpn_cls': '0.000255', 'loss_rpn_bbox': '0.003021', 'loss_mask': '0.096848', 'loss': '0.164063', eta: 5:54:57, batch_cost: 0.22657 sec, ips: 4.41360 images/sec
2021-01-10 10:19:00,379-INFO: Save model to output/mask_rcnn_r50_vd_fpn_2x/50000.
2021-01-10 10:19:02,514-INFO: Test iter 0
2021-01-10 10:19:07,630-INFO: Test iter 100
2021-01-10 10:19:12,799-INFO: Test iter 200
2021-01-10 10:19:17,933-INFO: Test iter 300
2021-01-10 10:19:23,109-INFO: Test iter 400
2021-01-10 10:19:28,243-INFO: Test iter 500
2021-01-10 10:19:33,416-INFO: Test iter 600
2021-01-10 10:19:38,576-INFO: Test iter 700
2021-01-10 10:19:43,698-INFO: Test iter 800
2021-01-10 10:19:45,285-INFO: Test finish iter 832
2021-01-10 10:19:45,285-INFO: Total number of images: 832, inference time: 19.424173635543394 fps.
loading annotations into memory...
Done (t=0.05s)
creating index...
index created!
2021-01-10 10:19:45,406-INFO: Start evaluate...
Loading and preparing results...
DONE (t=0.01s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=1.17s).
Accumulating evaluation results...
DONE (t=0.27s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.773
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.981
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.864
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.453
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.762
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.880
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.708
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.819
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.819
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.509
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.809
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.911
loading annotations into memory...
Done (t=0.06s)
creating index...
index created!
2021-01-10 10:19:47,006-INFO: Start evaluate...
Loading and preparing results...
DONE (t=0.06s)
```

迭代5万次iter之后，突然变成：

```
s: 4.85185 images/sec
2021-01-10 10:54:26,191-INFO: iter: 59800, lr: 0.025000, 'loss_cls': '0.132893', 'loss_bbox': '0.022256', 'loss_rpn_cls': '0.286517', 'loss_rpn_bbox': '0.033159', 'loss_mask': '0.506194', 'loss': '1.003589', eta: 4:46:21, batch_cost: 0.20405 sec, ips: 4.90065 images/sec
2021-01-10 10:54:46,635-INFO: iter: 59900, lr: 0.025000, 'loss_cls': '0.143271', 'loss_bbox': '0.026346', 'loss_rpn_cls': '0.277631', 'loss_rpn_bbox': '0.030456', 'loss_mask': '0.525563', 'loss': '1.011675', eta: 4:47:24, batch_cost: 0.20505 sec, ips: 4.87684 images/sec
2021-01-10 10:55:07,453-INFO: iter: 60000, lr: 0.025000, 'loss_cls': '0.138300', 'loss_bbox': '0.023768', 'loss_rpn_cls': '0.281662', 'loss_rpn_bbox': '0.029877', 'loss_mask': '0.509423', 'loss': '0.989154', eta: 4:50:51, batch_cost: 0.20775 sec, ips: 4.81342 images/sec
2021-01-10 10:55:07,453-INFO: Save model to output/mask_rcnn_r50_vd_fpn_2x/60000.
2021-01-10 10:55:09,190-INFO: Test iter 0
2021-01-10 10:55:13,406-INFO: Test iter 100
2021-01-10 10:55:17,664-INFO: Test iter 200
2021-01-10 10:55:21,931-INFO: Test iter 300
2021-01-10 10:55:26,212-INFO: Test iter 400
2021-01-10 10:55:30,544-INFO: Test iter 500
2021-01-10 10:55:34,900-INFO: Test iter 600
2021-01-10 10:55:39,251-INFO: Test iter 700
2021-01-10 10:55:43,619-INFO: Test iter 800
2021-01-10 10:55:44,997-INFO: Test finish iter 832
2021-01-10 10:55:44,997-INFO: Total number of images: 832, inference time: 23.203130894537754 fps.
loading annotations into memory...
Done (t=0.12s)
creating index...
index created!
2021-01-10 10:55:45,128-WARNING: The number of valid bbox detected is zero.
             Please use reasonable model and check input data.
             stop eval!
loading annotations into memory...
Done (t=0.06s)
creating index...
```
valid box消失了，这是为什么呢。

**Comment by qingqing01** [comment]
@Wenxin-piggy 


> output/mask_rcnn_r50_vd_fpn_2x/60000

可以单独评测下这个模型看下，上面错误是感觉训练的模型出了问题，没有检测到任何框。

**Comment by Wenxin-piggy** [comment]
> @Wenxin-piggy
> 
> > output/mask_rcnn_r50_vd_fpn_2x/60000
> 
> 可以单独评测下这个模型看下，上面错误是感觉训练的模型出了问题，没有检测到任何框。

python tools/eval.py -c configs/mask_rcnn_r50_vd_fpn_2x.yml -o use_gpu=true
TensorRT dynamic library (libnvinfer.so) that Paddle depends on is not configured correctly. (error code is libnvinfer.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if TensorRT is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure TensorRT dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;loading annotations into memory...
Done (t=0.06s)
creating index...
index created!
2021-01-11 09:27:10,419-WARNING: Illegal image file: /home/ubuntu/ShareFiles/shenwenxin/coco/val/440.jpg, and it will be ignored
2021-01-11 09:27:10,437-WARNING: Illegal image file: /home/ubuntu/ShareFiles/shenwenxin/coco/val/380.jpg, and it will be ignored
W0111 09:27:10.455029  2412 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.1, Runtime API Version: 10.0
W0111 09:27:10.457320  2412 device_context.cc:260] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "tools/eval.py", line 179, in <module>
    main()
  File "tools/eval.py", line 145, in main
    results = eval_run(exe, compile_program, loader, keys, values, cls, cfg,
  File "/home/ubuntu/shenwenxin/PaddleDetection/ppdet/utils/eval_utils.py", line 178, in eval_run
    res['mask'] = mask_encode(res, resolution)
  File "/home/ubuntu/shenwenxin/PaddleDetection/ppdet/utils/post_process.py", line 284, in mask_encode
    expand_bbox = expand_boxes(bbox, scale)
  File "/home/ubuntu/shenwenxin/PaddleDetection/ppdet/utils/coco_eval.py", line 470, in expand_boxes
    w_half = (boxes[:, 2] - boxes[:, 0]) * .5
IndexError: index 2 is out of bounds for axis 1 with size 0
terminate called without an active exception
W0111 09:27:14.421909  2506 init.cc:226] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0111 09:27:14.421924  2506 init.cc:228] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0111 09:27:14.421928  2506 init.cc:231] The detail failure signal is:

W0111 09:27:14.421933  2506 init.cc:234] *** Aborted at 1610357234 (unix time) try "date -d @1610357234" if you are using GNU date ***
W0111 09:27:14.423094  2506 init.cc:234] PC: @                0x0 (unknown)
W0111 09:27:14.423192  2506 init.cc:234] *** SIGABRT (@0x3e80000096c) received by PID 2412 (TID 0x7f9db97f6700) from PID 2412; stack trace: ***
W0111 09:27:14.424494  2506 init.cc:234]     @     0x7f9f4c7fa890 (unknown)
W0111 09:27:14.425539  2506 init.cc:234]     @     0x7f9f4c435e97 gsignal
W0111 09:27:14.426496  2506 init.cc:234]     @     0x7f9f4c437801 abort
W0111 09:27:14.427896  2506 init.cc:234]     @     0x7f9f1fdde84a __gnu_cxx::__verbose_terminate_handler()
W0111 09:27:14.428697  2506 init.cc:234]     @     0x7f9f1fddcf47 __cxxabiv1::__terminate()
W0111 09:27:14.429875  2506 init.cc:234]     @     0x7f9f1fddcf7d std::terminate()
W0111 09:27:14.430774  2506 init.cc:234]     @     0x7f9f1fddcc5a __gxx_personality_v0
W0111 09:27:14.431622  2506 init.cc:234]     @     0x7f9f47e05b97 _Unwind_ForcedUnwind_Phase2
W0111 09:27:14.432406  2506 init.cc:234]     @     0x7f9f47e05e7d _Unwind_ForcedUnwind
W0111 09:27:14.433372  2506 init.cc:234]     @     0x7f9f4c7f8f10 __GI___pthread_unwind
W0111 09:27:14.434361  2506 init.cc:234]     @     0x7f9f4c7f0ae5 __pthread_exit
W0111 09:27:14.435658  2506 init.cc:234]     @     0x563787397909 PyThread_exit_thread
W0111 09:27:14.435874  2506 init.cc:234]     @     0x56378722ad3a PyEval_RestoreThread.cold.962
W0111 09:27:14.436432  2506 init.cc:234]     @     0x7f9f1a1b5bc3 (unknown)
W0111 09:27:14.437320  2506 init.cc:234]     @     0x56378732ef76 PyCFunction_Call
W0111 09:27:14.438395  2506 init.cc:234]     @     0x5637872ec85f _PyObject_MakeTpCall
W0111 09:27:14.439436  2506 init.cc:234]     @     0x563787370b90 _PyEval_EvalFrameDefault
W0111 09:27:14.440371  2506 init.cc:234]     @     0x563787339f9f _PyEval_EvalCodeWithName
W0111 09:27:14.441337  2506 init.cc:234]     @     0x56378733b3ba _PyObject_FastCallDict
W0111 09:27:14.442263  2506 init.cc:234]     @     0x56378733b733 _PyObject_Call_Prepend
W0111 09:27:14.442740  2506 init.cc:234]     @     0x56378733b83a slot_tp_call
W0111 09:27:14.443743  2506 init.cc:234]     @     0x5637872ec85f _PyObject_MakeTpCall
terminate called recursively
W0111 09:27:14.444727  2506 init.cc:234]     @     0x56378736fe35 _PyEval_EvalFrameDefault
W0111 09:27:14.445664  2506 init.cc:234]     @     0x56378733b60d _PyObject_FastCallDict
W0111 09:27:14.446549  2506 init.cc:234]     @     0x56378733b733 _PyObject_Call_Prepend
W0111 09:27:14.447031  2506 init.cc:234]     @     0x56378733b83a slot_tp_call
W0111 09:27:14.448026  2506 init.cc:234]     @     0x5637872ec85f _PyObject_MakeTpCall
W0111 09:27:14.449008  2506 init.cc:234]     @     0x563787373f56 _PyEval_EvalFrameDefault
W0111 09:27:14.449896  2506 init.cc:234]     @     0x563787339a92 _PyEval_EvalCodeWithName
W0111 09:27:14.450457  2506 init.cc:234]     @     0x56378733a943 _PyFunction_Vectorcall.localalias.355
W0111 09:27:14.450749  2506 init.cc:234]     @     0x56378733ae79 method_vectorcall
W0111 09:27:14.451725  2506 init.cc:234]     @     0x56378733b5fa _PyObject_FastCallDict
Aborted (core dumped)
(paddle_env) ubuntu@shenwenxin:~/shenwenxin/PaddleDetection$ 
您好，会报如下错误

**Comment by qingqing01** [comment]
@Wenxin-piggy  

> python tools/eval.py -c configs/mask_rcnn_r50_vd_fpn_2x.yml -o use_gpu=true

单独评测的时候，weights设置成 output/mask_rcnn_r50_vd_fpn_2x/60000 了吗？错误和issue最开始贴的训练中评估的错误不一样。

```
python tools/eval.py -c configs/mask_rcnn_r50_vd_fpn_2x.yml -o use_gpu=true weights=output/mask_rcnn_r50_vd_fpn_2x/60000
```
