### ISSUE TITLE
Quick Start文档运行yolov3在fruit数据集上报错

### ISSUE THREAD

**Issue by brightgems** [PaddlePaddle/PaddleDetection#204]
运行yolov3在fruit数据集上报错
`%run tools/train.py -c configs/yolov3_mobilenet_v1_fruit.yml  --eval`

```
WARNING:ppdet.data.transform:fail to map op [ArrangeEvalYOLO_915ddc] with error: tuple indices must be integers or slices, not str and stack:
Traceback (most recent call last):
  File "/home/aistudio/PaddleDetection/ppdet/data/transform/__init__.py", line 77, in _mapper
    out = f(sample, ctx)
  File "/home/aistudio/PaddleDetection/ppdet/data/transform/arrange_sample.py", line 339, in __call__
    im = sample['image']
TypeError: tuple indices must be integers or slices, not str

WARNING:ppdet.data.transform:fail to map op [ArrangeEvalYOLO_915ddc] with error: tuple indices must be integers or slices, not str and stack:
Traceback (most recent call last):
  File "/home/aistudio/PaddleDetection/ppdet/data/transform/__init__.py", line 77, in _mapper
```

**Comment by qingqing01** [comment]
@brightgems 我在release/0.1分支和master分支上验证均没有问题。请问您使用的是release分支，还是master分支？请问是否有改动代码、以及检查下数据集下载是否正确？另外，看错误是 "ArrangeEvalYOLO_915ddc"也是做评估时出错，您可以去掉 --eval看下

**Comment by brightgems** [comment]
@qingqing01 qingqing01 已经解决，在shell环境下执行没有问题，但在Notebook里执行两次会出现上面的错误

**Comment by qingqing01** [comment]
@brightgems 之前在AIStudio上跑过NoteBook，是没问题。后面我们也再验证下吧，这个issue先关闭了~
