### ISSUE TITLE
AssertionError: Results do not correspond to current coco set

### ISSUE THREAD

**Issue by xiaowanzizz** [PaddlePaddle/PaddleDetection#2043]
Traceback (most recent call last):
  File "tools/eval.py", line 193, in <module>
    main()
  File "tools/eval.py", line 175, in main
    save_only=save_only)
  File "/home/zzf/Desktop/PaddleDetection/ppdet/utils/eval_utils.py", line 241, in eval_results
    save_only=save_only)
  File "/home/zzf/Desktop/PaddleDetection/ppdet/utils/coco_eval.py", line 102, in bbox_eval
    map_stats = cocoapi_eval(outfile, 'bbox', coco_gt=coco_gt)
  File "/home/zzf/Desktop/PaddleDetection/ppdet/utils/coco_eval.py", line 238, in cocoapi_eval
    coco_dt = coco_gt.loadRes(jsonfile)
  File "/home/zzf/miniconda3/envs/torch1.7.1/lib/python3.7/site-packages/pycocotools/coco.py", line 388, in loadRes
    'Results do not correspond to current coco set'
AssertionError: Results do not correspond to current coco set

你好，出现如下问题。
我自己清空了自己数据集里没有gt框的文件仍然出现如下问题
顺便上传我的json文件

[json.zip](https://github.com/PaddlePaddle/PaddleDetection/files/5796270/json.zip)

**Comment by qingqing01** [comment]
@xiaowanzizz 


```
coco_dt = coco_gt.loadRes(jsonfile)
File "/home/zzf/miniconda3/envs/torch1.7.1/lib/python3.7/site-packages/pycocotools/coco.py", line 388, in loadRes
'Results do not correspond to current coco set'
AssertionError: Results do not correspond to current coco set
```

这个错误是，评估结果时，推理生成的json文件，和gt，不匹配。 可以查看下推理得到的json文件、和标注的gt中image_id是否匹配。

**Comment by xiaowanzizz** [comment]
请问推理得到的json文件位于哪个位置呢？我现在只有训练完output的modelparam那三个权重文件和我在issue里上传的三个数据集的json文件？
