### ISSUE TITLE
求助：windows下训练SOLOv2报错

### ISSUE THREAD

**Issue by lky-bit** [PaddlePaddle/PaddleDetection#2044]
系统环境：windows10，CUDA9，cudnn7.6.4
一直报错cudnn64_7.dll有问题，但是我找了是有这个文件的，就很奇怪

```
(PaddleDetection) C:\Users\a\PaddleDetection>python -u tools/train.py -c configs/solov2/solov2_mobilenetv3_fpn_448_3x.yml --use_vdl=true --vdl_log_dir=vdl_dir/scalar --eval -o use_gpu=true
C:\Users\a\PaddleDetection\ppdet\core\workspace.py:118: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  isinstance(merge_dct[k], collections.Mapping)):
C:\Users\a\.conda\envs\PaddleDetection\lib\site-packages\paddle\fluid\framework.py:2383: DeprecationWarning: an integer is required (got type paddle.fluid.core_avx.op_proto_and_checker_maker.OpRole).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  self.desc._set_attr(name, val)
C:\Users\a\.conda\envs\PaddleDetection\lib\site-packages\paddle\fluid\framework.py:2383: DeprecationWarning: an integer is required (got type paddle.fluid.core_avx.VarType).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  self.desc._set_attr(name, val)
C:\Users\a\.conda\envs\PaddleDetection\lib\site-packages\paddle\fluid\layers\math_op_patch.py:273: UserWarning: C:\Users\a\PaddleDetection\ppdet\modeling\backbones\mobilenet_v3.py:228
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  warnings.warn(
C:\Users\a\.conda\envs\PaddleDetection\lib\site-packages\paddle\fluid\layers\math_op_patch.py:273: UserWarning: C:\Users\a\PaddleDetection\ppdet\modeling\backbones\fpn.py:108
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  warnings.warn(
C:\Users\a\.conda\envs\PaddleDetection\lib\site-packages\paddle\fluid\layers\math_op_patch.py:273: UserWarning: C:\Users\a\PaddleDetection\ppdet\modeling\ops.py:328
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  warnings.warn(
C:\Users\a\.conda\envs\PaddleDetection\lib\site-packages\paddle\fluid\layers\math_op_patch.py:273: UserWarning: C:\Users\a\PaddleDetection\ppdet\modeling\losses\solov2_loss.py:51
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  warnings.warn(
C:\Users\a\.conda\envs\PaddleDetection\lib\site-packages\paddle\fluid\layers\math_op_patch.py:273: UserWarning: C:\Users\a\PaddleDetection\ppdet\modeling\losses\solov2_loss.py:52
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  warnings.warn(
C:\Users\a\.conda\envs\PaddleDetection\lib\site-packages\paddle\fluid\layers\math_op_patch.py:273: UserWarning: C:\Users\a\PaddleDetection\ppdet\modeling\losses\solov2_loss.py:53
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  warnings.warn(
C:\Users\a\.conda\envs\PaddleDetection\lib\site-packages\paddle\fluid\layers\math_op_patch.py:273: UserWarning: C:\Users\a\PaddleDetection\ppdet\modeling\losses\solov2_loss.py:54
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  warnings.warn(
C:\Users\a\.conda\envs\PaddleDetection\lib\site-packages\paddle\fluid\layers\math_op_patch.py:273: UserWarning: C:\Users\a\PaddleDetection\ppdet\modeling\losses\solov2_loss.py:54
The behavior of expression A / B has been unified with elementwise_div(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_div(X, Y, axis=0) instead of A / B. This transitional warning will be dropped in the future.
  warnings.warn(
C:\Users\a\.conda\envs\PaddleDetection\lib\site-packages\paddle\fluid\backward.py:300: DeprecationWarning: an integer is required (got type paddle.fluid.core_avx.VarType).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  op_desc._set_attr(name, val)
C:\Users\a\.conda\envs\PaddleDetection\lib\site-packages\paddle\fluid\backward.py:300: DeprecationWarning: an integer is required (got type paddle.fluid.core_avx.op_proto_and_checker_maker.OpRole).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  op_desc._set_attr(name, val)
C:\Users\a\.conda\envs\PaddleDetection\lib\site-packages\paddle\fluid\backward.py:1070: DeprecationWarning: an integer is required (got type paddle.fluid.core_avx.op_proto_and_checker_maker.OpRole).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  new_op_desc._set_attr(op_role_attr_name, backward)
2021-01-12 01:59:05,395-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000100] in Optimizer will not take effect, and it will only be applied to other Parameters!
C:\Users\a\.conda\envs\PaddleDetection\lib\site-packages\paddle\fluid\layers\math_op_patch.py:273: UserWarning: C:\Users\a\PaddleDetection\ppdet\modeling\anchor_heads\solov2_head.py:138
The behavior of expression A == B has been unified with equal(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use equal(X, Y, axis=0) instead of A == B. This transitional warning will be dropped in the future.
  warnings.warn(
C:\Users\a\.conda\envs\PaddleDetection\lib\site-packages\paddle\fluid\layers\math_op_patch.py:273: UserWarning: C:\Users\a\PaddleDetection\ppdet\modeling\anchor_heads\solov2_head.py:139
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  warnings.warn(
W0112 01:59:08.523591  1588 dynamic_loader.cc:198] Note: [Recommend] copy cudnn into CUDA installation directory.
 For instance, download cudnn-10.0-windows10-x64-v7.6.5.32.zip from NVIDIA's official website,
then, unzip it and copy it into C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA/v10.0
You should do this according to your CUDA installation directory and CUDNN version.
Traceback (most recent call last):
  File "tools/train.py", line 377, in <module>
    main()
  File "tools/train.py", line 146, in main
    fetches = model.eval(feed_vars)
  File "C:\Users\a\PaddleDetection\ppdet\modeling\architectures\solov2.py", line 168, in eval
    return self.build(feed_vars, mode='test')
  File "C:\Users\a\PaddleDetection\ppdet\modeling\architectures\solov2.py", line 108, in build
    return self.bbox_head.get_prediction(*seg_inputs)
  File "C:\Users\a\PaddleDetection\ppdet\modeling\anchor_heads\solov2_head.py", line 337, in get_prediction
    seg_masks, cate_labels, cate_scores = self.get_seg_single(
  File "C:\Users\a\PaddleDetection\ppdet\modeling\anchor_heads\solov2_head.py", line 389, in get_seg_single
    seg_preds = paddle.nn.functional.conv2d(seg_preds, kernel_preds)
  File "C:\Users\a\.conda\envs\PaddleDetection\lib\site-packages\paddle\nn\functional\conv.py", line 476, in conv2d
    cudnn_version = get_cudnn_version()
  File "C:\Users\a\.conda\envs\PaddleDetection\lib\site-packages\paddle\device.py", line 94, in get_cudnn_version
    cudnn_version = int(core.cudnn_version())
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
PreconditionNotMetError: The third-party dynamic library (cudnn64_7.dll) that Paddle depends on is not configured correctly. (error code is 126)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at D:\2.0.0-rc0\paddle\paddle\fluid\platform\dynload\dynamic_loader.cc:225)

```

**Comment by qingqing01** [comment]
@lky-bit 

您看下是否在Windows系统里设置下lib cudnn64_7.dll  到环境变量里。

**Comment by lky-bit** [comment]
> @lky-bit
> 
> 您看下是否在Windows系统里设置下lib cudnn64_7.dll 到环境变量里。

我设置过了的，而且用set path+echo的方法激活了变量，但不知道为啥还是不行。

**Comment by lky-bit** [comment]
> @lky-bit
> 
> 您看下是否在Windows系统里设置下lib cudnn64_7.dll 到环境变量里。

遇到了新的问题：
FileNotFoundError: Could not find module 'C:\Users\a\.conda\envs\PaddleDetection\Library\bin\geos_c.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by laodu233** [comment]
您好，请问您是怎么解决的鸭

**Comment by ChengzhenDu** [comment]
将cudnn64_7.dll保存至CUDA\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin目录下
