### ISSUE TITLE
请问为什么训练会报错？

### ISSUE THREAD

**Issue by Bq1207** [PaddlePaddle/PaddleDetection#2063]
aistudio@jupyter-621803-1452308:~/data/data68027/PaddleDetection$ python -u tools/train.py -c configs/ssd/ssd_mobilenet_v1_voc.yml --use_tb=True --eval
EvalReader:
  batch_size: 32
  bufsize: 32
  dataset: !VOCDataSet
    anno_path: test.txt
    dataset_dir: dataset/voc
    image_dir: ''
    label_list: label_list.txt
    sample_num: -1
    use_default_label: true
    with_background: true
  inputs_def:
    fields:
    - image
    - gt_bbox
    - gt_class
    - im_shape
    - im_id
    - is_difficult
    image_shape:
    - 3
    - 300
    - 300
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !NormalizeBox {}
  - !ResizeImage
    interp: 1
    max_size: 0
    target_size: 300
    use_cv2: false
  - !Permute
    channel_first: true
    to_bgr: true
  - !NormalizeImage
    is_channel_first: true
    is_scale: false
    mean:
    - 127.5
    - 127.5
    - 127.5
    std:
    - 127.502231
    - 127.502231
    - 127.502231
  use_process: false
  worker_num: 8
LearningRate:
  [32mschedulers[0m:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 10000
    - 15000
    - 20000
    - 25000
    values:
    - 0.001
    - 0.0005
    - 0.00025
    - 0.0001
    - 1.0e-05
  base_lr: 0.01
MobileNet:
  [32mconv_learning_rate[0m: 0.1
  [32mwith_extra_blocks[0m: true
  conv_group_scale: 1
  extra_block_filters:
  - - 256
    - 512
  - - 128
    - 256
  - - 128
    - 256
  - - 64
    - 128
  norm_decay: 0.0
  norm_type: bn
  weight_prefix_name: ''
MultiBoxHead:
  aspect_ratios:
  - - 2.0
  - - 2.0
    - 3.0
  - - 2.0
    - 3.0
  - - 2.0
    - 3.0
  - - 2.0
    - 3.0
  - - 2.0
    - 3.0
  base_size: 300
  flip: true
  kernel_size: 1
  max_ratio: 90
  max_sizes:
  - []
  - 150.0
  - 195.0
  - 240.0
  - 285.0
  - 300.0
  min_max_aspect_ratios_order: false
  min_ratio: 20
  min_sizes:
  - 60.0
  - 105.0
  - 150.0
  - 195.0
  - 240.0
  - 285.0
  offset: 0.5
  pad: 0
  steps: null
OptimizerBuilder:
  [32moptimizer[0m:
    momentum: 0.0
    type: RMSPropOptimizer
  [32mregularizer[0m:
    factor: 5.0e-05
    type: L2
SSD:
  [32mbackbone[0m: MobileNet
  multi_box_head: MultiBoxHead
  num_classes: 21
  output_decoder:
    background_label: 0
    keep_top_k: 200
    nms_eta: 1.0
    nms_threshold: 0.45
    nms_top_k: 400
    score_threshold: 0.01
TestReader:
  batch_size: 1
  dataset: !ImageFolder
    anno_path: test.txt
    dataset_dir: ''
    image_dir: ''
    sample_num: -1
    use_default_label: true
    with_background: true
  inputs_def:
    fields:
    - image
    - im_id
    - im_shape
    image_shape:
    - 3
    - 300
    - 300
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !ResizeImage
    interp: 1
    max_size: 0
    target_size: 300
    use_cv2: false
  - !Permute
    channel_first: true
    to_bgr: true
  - !NormalizeImage
    is_channel_first: true
    is_scale: false
    mean:
    - 127.5
    - 127.5
    - 127.5
    std:
    - 127.502231
    - 127.502231
    - 127.502231
TrainReader:
  batch_size: 32
  bufsize: 16
  dataset: !VOCDataSet
    anno_path: trainval.txt
    dataset_dir: dataset/voc
    image_dir: ''
    label_list: label_list.txt
    sample_num: -1
    use_default_label: true
    with_background: true
  drop_last: true
  inputs_def:
    fields:
    - image
    - gt_bbox
    - gt_class
    image_shape:
    - 3
    - 300
    - 300
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !RandomDistort
    brightness_lower: 0.875
    brightness_prob: 0.5
    brightness_upper: 1.125
    contrast_lower: 0.5
    contrast_prob: 0.5
    contrast_upper: 1.5
    count: 4
    hue_lower: -18
    hue_prob: 0.5
    hue_upper: 18
    is_order: true
    saturation_lower: 0.5
    saturation_prob: 0.5
    saturation_upper: 1.5
  - !RandomExpand
    fill_value: !!python/tuple
    - 127.5
    - 127.5
    - 127.5
    prob: 0.5
    ratio: 4.0
  - !RandomCrop
    allow_no_crop: false
    aspect_ratio:
    - 0.5
    - 2.0
    cover_all_box: false
    num_attempts: 50
    scaling:
    - 0.3
    - 1.0
    thresholds:
    - 0.0
    - 0.1
    - 0.3
    - 0.5
    - 0.7
    - 0.9
  - !NormalizeBox {}
  - !ResizeImage
    interp: 1
    max_size: 0
    target_size: 300
    use_cv2: false
  - !RandomFlipImage
    is_mask_flip: false
    is_normalized: true
    prob: 0.5
  - !Permute
    channel_first: true
    to_bgr: true
  - !NormalizeImage
    is_channel_first: true
    is_scale: false
    mean:
    - 127.5
    - 127.5
    - 127.5
    std:
    - 127.502231
    - 127.502231
    - 127.502231
  shuffle: true
  use_process: true
  worker_num: 8
architecture: SSD
log_smooth_window: 1
map_type: 11point
max_iters: 28000
metric: VOC
num_classes: 5
pretrain_weights: https://paddlemodels.bj.bcebos.com/object_detection/ssd_mobilenet_v1_coco_pretrained.tar
save_dir: output
snapshot_iter: 2000
weights: output/ssd_mobilenet_v1_voc/model_final

2021-01-14 11:23:15,025-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000050] in Optimizer will not take effect, and it will only be applied to other Parameters!
2021-01-14 11:23:15,687-INFO: 62 samples in file dataset/voc/test.txt
2021-01-14 11:23:15,688-INFO: places would be ommited when DataLoader is not iterable
2021-01-14 11:23:15,836-INFO: Found /home/aistudio/.cache/paddle/weights/ssd_mobilenet_v1_coco_pretrained
2021-01-14 11:23:15,836-INFO: Loading parameters from /home/aistudio/.cache/paddle/weights/ssd_mobilenet_v1_coco_pretrained...
2021-01-14 11:23:15,836-WARNING: /home/aistudio/.cache/paddle/weights/ssd_mobilenet_v1_coco_pretrained.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2021-01-14 11:23:16,516-INFO: 1177 samples in file dataset/voc/trainval.txt
2021-01-14 11:23:22,112-INFO: places would be ommited when DataLoader is not iterable
W0114 11:23:22.221544  7736 build_strategy.cc:170] fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU.
W0114 11:23:22.295682  7736 fuse_all_reduce_op_pass.cc:74] Find all_reduce operators: 129. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 117.
2021-01-14 11:23:26,755-INFO: fail to map op [RandomCrop_2d84e6] with error: Range cannot be empty (low >= high) unless no samples are taken and stack:
Traceback (most recent call last):
  File "/home/aistudio/data/data68027/PaddleDetection/ppdet/data/reader.py", line 45, in __call__
    data = f(data, ctx)
  File "/home/aistudio/data/data68027/PaddleDetection/ppdet/data/transform/operators.py", line 1342, in __call__
    crop_y = np.random.randint(0, h - crop_h)
  File "mtrand.pyx", line 992, in mtrand.RandomState.randint
ValueError: Range cannot be empty (low >= high) unless no samples are taken

2021-01-14 11:23:26,837-WARNING: recv endsignal from outq with errmsg[consumer[consumer-a5b-1] failed to map with error:[Range cannot be empty (low >= high) unless no samples are taken]]
2021-01-14 11:24:12,210-INFO: iter: 0, lr: 0.001000, 'loss': '27.428022', time: 0.010, eta: 0:04:34
2021-01-14 11:24:30,837-WARNING: recv endsignal from outq with errmsg[consumer[consumer-a5b-7] exits for reason[consumer[consumer-a5b-1] failed to map with error:[Range cannot be empty (low >= high) unless no samples are taken]]]
2021-01-14 11:24:48,742-INFO: fail to map op [RandomCrop_2d84e6] with error: Range cannot be empty (low >= high) unless no samples are taken and stack:
Traceback (most recent call last):
  File "/home/aistudio/data/data68027/PaddleDetection/ppdet/data/reader.py", line 45, in __call__
    data = f(data, ctx)
  File "/home/aistudio/data/data68027/PaddleDetection/ppdet/data/transform/operators.py", line 1342, in __call__
    crop_y = np.random.randint(0, h - crop_h)
  File "mtrand.pyx", line 992, in mtrand.RandomState.randint
ValueError: Range cannot be empty (low >= high) unless no samples are taken

2021-01-14 11:24:48,746-WARNING: recv endsignal from outq with errmsg[consumer[consumer-a5b-4] failed to map with error:[Range cannot be empty (low >= high) unless no samples are taken]]
2021-01-14 11:24:55,038-WARNING: recv endsignal from outq with errmsg[consumer[consumer-a5b-5] exits for reason[consumer[consumer-a5b-7] exits for reason[consumer[consumer-a5b-1] failed to map with error:[Range cannot be empty (low >= high) unless no samples are taken]]]]
2021-01-14 11:24:56,549-WARNING: recv endsignal from outq with errmsg[consumer[consumer-a5b-6] exits for reason[consumer[consumer-a5b-4] failed to map with error:[Range cannot be empty (low >= high) unless no samples are taken]]]
2021-01-14 11:24:56,862-WARNING: recv endsignal from outq with errmsg[consumer[consumer-a5b-2] exits for reason[consumer[consumer-a5b-5] exits for reason[consumer[consumer-a5b-7] exits for reason[consumer[consumer-a5b-1] failed to map with error:[Range cannot be empty (low >= high) unless no samples are taken]]]]]
2021-01-14 11:25:00,341-WARNING: recv endsignal from outq with errmsg[consumer[consumer-a5b-0] exits for reason[consumer[consumer-a5b-6] exits for reason[consumer[consumer-a5b-4] failed to map with error:[Range cannot be empty (low >= high) unless no samples are taken]]]]
2021-01-14 11:25:02,952-WARNING: recv endsignal from outq with errmsg[consumer[consumer-a5b-3] exits for reason[consumer[consumer-a5b-2] exits for reason[consumer[consumer-a5b-5] exits for reason[consumer[consumer-a5b-7] exits for reason[consumer[consumer-a5b-1] failed to map with error:[Range cannot be empty (low >= high) unless no samples are taken]]]]]]
2021-01-14 11:25:02,952-WARNING: Your reader has raised an exception!
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1145, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1125, in __thread_main__
    for tensors in self._tensor_reader():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1195, in __tensor_reader_impl__
    for slots in paddle_reader():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 506, in __reader_creator__
    for item in reader():
  File "/home/aistudio/data/data68027/PaddleDetection/ppdet/data/reader.py", line 417, in _reader
    reader.reset()
  File "/home/aistudio/data/data68027/PaddleDetection/ppdet/data/parallel_map.py", line 253, in reset
    assert not self._exit, "cannot reset for already stopped dataset"
AssertionError: cannot reset for already stopped dataset

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tools/train.py", line 323, in <module>
    main()
  File "tools/train.py", line 233, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1167, in _run_impl
    return_merged=return_merged)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 879, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1080, in _init_non_iterable
    attrs={'drop_last': self._drop_last})
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 978, in __init__
    self._init_non_iterable()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 620, in from_generator
    iterable, return_list, drop_last)
  File "/home/aistudio/data/data68027/PaddleDetection/ppdet/modeling/architectures/ssd.py", line 123, in build_inputs
    iterable=iterable) if use_dataloader else None
  File "tools/train.py", line 115, in main
    feed_vars, train_loader = model.build_inputs(**inputs_def)
  File "tools/train.py", line 323, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]

**Comment by yghstill** [comment]
@Bq1207 看报错信息是执行RandomCrop预处理时出错，把RandomCrop这个算子删掉再试下，因为您的代码比较老，或者更新一下PaddleDetection代码到最新release/2.0-beta最新代码再试下

**Comment by heavengate** [comment]
鉴于当前问题已经解决，issue关闭，如果还有问题可以reopen这个issue~
