### ISSUE TITLE
训练时将eval时会报错

### ISSUE THREAD

**Issue by liu824** [PaddlePaddle/PaddleDetection#2079]
运行：
!python tools/eval.py \
    -c ../work/faster_rcnn_r50_fpn_2x.yml \
    -o weights=output/faster_rcnn_r50_fpn_2x/24000.pdparams \
    save_prediction_only=False
报错：

```
Traceback (most recent call last):
  File "tools/train.py", line 399, in <module>
    main()
  File "tools/train.py", line 316, in main
    resolution=resolution)
  File "/home/aistudio/work/PaddleDetection/ppdet/utils/eval_utils.py", line 158, in eval_run
    cfg.num_classes)
  File "/home/aistudio/work/PaddleDetection/ppdet/utils/post_process.py", line 218, in mstest_box_post_process
    boxes = np.reshape(boxes, (-1, 4 * num_classes))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 292, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 600 into shape (28
```

**Comment by jerrywgz** [comment]
如果使用multi-scale test的话 目前还只支持batch_size=1的情况，另外可以打印下mstest_box_post_process输入的res['bbox']的shape，和你的num class

**Comment by yghstill** [comment]
@liu824 由于您长时间未回复，此issue关闭，如还有问题可以重新open或新提issue，谢谢。
