### ISSUE TITLE
ppyolo量化报错

### ISSUE THREAD

**Issue by GoldFish9566** [PaddlePaddle/PaddleDetection#2092]
ppyolo检测模型的训练量化，遇到问题：
『Paddle1.8.5』  + 『PaddleDetection master分支』+『PaddleSlim1.2.0』
报错信息如下：
```
----------------------
Error Message Summary:
----------------------
Error: op moving_average_abs_max_scale does not have kernel for data_type[int]
:data_layout[ANY_LAYOUT]:place[CUDAPlace(0)]:library_type[PLAIN] at (/paddle/p
addle/fluid/framework/operator.cc:1081)
  [operator < moving_average_abs_max_scale > error]

完整报错信息：
Traceback (most recent call last):
  File "slim/quantization/train.py", line 332, in <module>
    main()
  File "slim/quantization/train.py", line 261, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "/home/vis/zhouzhichao01/softwares/miniconda2_cuda10_paddle1.8.5/minico
nda2/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/home/vis/zhouzhichao01/softwares/miniconda2_cuda10_paddle1.8.5/minico
nda2/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/home/vis/zhouzhichao01/softwares/miniconda2_cuda10_paddle1.8.5/minico
nda2/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1167, in _run
_impl
    return_merged=return_merged)
  File "/home/vis/zhouzhichao01/softwares/miniconda2_cuda10_paddle1.8.5/minico
nda2/lib/python2.7/site-packages/paddle/fluid/executor.py", line 879, in _run_
parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet
--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string>(std::string&
&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSumm
ary const&, char const*, int)
2   paddle::framework::OperatorWithKernel::ChooseKernel(paddle::framework::Run
timeContext const&, paddle::framework::Scope const&, paddle::platform::Place c
onst&) const
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope co
nst&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) cons
t
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope co
nst&, paddle::platform::Place const&) const
5   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, padd
le::platform::Place const&)
6   paddle::framework::details::ComputationOpHandle::RunImpl()
7   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle
::framework::details::OpHandleBase*)
8   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::fr
amework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQu
eue<unsigned long> > const&, unsigned long*)
9   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, s
td::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_sette
r<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Resu
lt_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&)
10  std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<s
td::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (
)>&, bool&)
11  ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

```

**Comment by yghstill** [comment]
@GoldFish9566 
- Paddle 1.8 系列版本，需要安装PaddleSlim 1.1.1版本
```
pip install paddleslim==1.1.1 -i https://pypi.tuna.tsinghua.edu.cn/simple
```
- Paddle 2.0 系列版本，需要安装PaddleSlim 1.2.0版本
```
pip install paddleslim==1.2.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
```

**Comment by yghstill** [comment]
@GoldFish9566 由于您长时间未回复，此issue关闭，如还有问题可以重新open或新提issue，谢谢。
