### ISSUE TITLE
cascade_rcnn_dcn_r50_vd_fpn_3x_server_side.yml训练问题：

### ISSUE THREAD

**Issue by wangkan83** [PaddlePaddle/PaddleDetection#2105]
配置文件未作修改，运行报错，同样的数据集跑其他模型OK
(paddle_env) G:\paddle\PaddleDetection0.5>python tools/train.py -c configs/rcnn_enhance/cascade_rcnn_dcn_r50_vd_fpn_3x_server_side123.yml --eval -o use_gpu=true
Traceback (most recent call last):
  File "tools/train.py", line 377, in <module>
    main()
  File "tools/train.py", line 71, in main
    cfg = load_config(FLAGS.config)
  File "G:\paddle\PaddleDetection0.5\ppdet\core\workspace.py", line 86, in load_config
    cfg = merge_config(yaml.load(f, Loader=yaml.Loader), cfg)
  File "D:\anaconda\envs\paddle_env\lib\site-packages\yaml\__init__.py", line 112, in load
    loader = Loader(stream)
  File "D:\anaconda\envs\paddle_env\lib\site-packages\yaml\loader.py", line 44, in __init__
    Reader.__init__(self, stream)
  File "D:\anaconda\envs\paddle_env\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "D:\anaconda\envs\paddle_env\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "D:\anaconda\envs\paddle_env\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
UnicodeDecodeError: 'gbk' codec can't decode byte 0x8c in position 784: illegal multibyte sequence

**Comment by yghstill** [comment]
@wangkan83 你这个配置文件修改了哪里？有中文字符导致解析yaml报错，改成英文字符即可。

**Comment by wangkan83** [comment]
@yghstill ，找到问题了，thanks a lot!
