### ISSUE TITLE
faster rcnn tta问题

### ISSUE THREAD

**Issue by SunCity1** [PaddlePaddle/PaddleDetection#2119]
我想用faster rcnn去配置tta ，在reader配置文件里，我仿照了[#1110](https://github.com/PaddlePaddle/PaddleDetection/issues/1110)这个方法，但是失败了，我想问问有没有关于这个的教程，感想

**Comment by user-RuiZhao** [comment]
报了这个错
Traceback (most recent call last):
  File "tools/eval.py", line 194, in <module>
    main()
  File "tools/eval.py", line 47, in main
    cfg = load_config(FLAGS.config)
  File "/home/aistudio/PaddleDetection/ppdet/core/workspace.py", line 96, in load_config
    merge_config(yaml.load(f, Loader=yaml.Loader))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 52, in construct_document
    for dummy in generator:
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 399, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 122, in construct_sequence
    for child in node.value]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 122, in <listcomp>
    for child in node.value]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 420, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!MultiScaleTEST'
  in "../work/faster_fpn_reader_test.yml", line 67, column 5

**Comment by qingqing01** [comment]
@user-RuiZhao 

可以参考Cascade_RCNN_R50_FPN_1x 的配置:

https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-beta/configs/cascade_rcnn_r50_fpn_1x_ms_test.yml

搜索MultiscaleTest相关，或和cascade_rcnn_r50_fpn_1x的配置对比看下。

**Comment by user-RuiZhao** [comment]
@qingqing01 
谢谢谢谢，配置问题解决后，用MultiscaleTest配置会出现这个错误，不用MultiscaleTest配置就不会出现
错误如下
2021-01-26 12:41:30,809-WARNING: fail to map op [MultiscaleTestResize_50dc22] with error: OpenCV(4.1.1) /io/opencv/modules/imgproc/src/resize.cpp:3363: error: (-215:Assertion failed) !dsize.empty() in function 'resize'
 and stack:
Traceback (most recent call last):
  File "/home/aistudio/PaddleDetection/ppdet/data/reader.py", line 46, in __call__
    data = f(data, ctx)
  File "/home/aistudio/PaddleDetection/ppdet/data/transform/operators.py", line 232, in __call__
    interpolation=self.interp)
cv2.error: OpenCV(4.1.1) /io/opencv/modules/imgproc/src/resize.cpp:3363: error: (-215:Assertion failed) !dsize.empty() in function 'resize'


2021-01-26 12:41:30,810-WARNING: recv endsignal from outq with errmsg[consumer[consumer-caa-0] failed to map with error:[OpenCV(4.1.1) /io/opencv/modules/imgproc/src/resize.cpp:3363: error: (-215:Assertion failed) !dsize.empty() in function 'resize'
]]
2021-01-26 12:41:32,596-WARNING: fail to map op [MultiscaleTestResize_50dc22] with error: OpenCV(4.1.1) /io/opencv/modules/imgproc/src/resize.cpp:3363: error: (-215:Assertion failed) !dsize.empty() in function 'resize'
 and stack:
Traceback (most recent call last):
  File "/home/aistudio/PaddleDetection/ppdet/data/reader.py", line 46, in __call__
    data = f(data, ctx)
  File "/home/aistudio/PaddleDetection/ppdet/data/transform/operators.py", line 232, in __call__
    interpolation=self.interp)
cv2.error: OpenCV(4.1.1) /io/opencv/modules/imgproc/src/resize.cpp:3363: error: (-215:Assertion failed) !dsize.empty() in function 'resize'

**Comment by thinkthinking** [comment]
你好，欢迎在PaddleDetection最新版体验该功能。
