### ISSUE TITLE
用PP YOLOV3训练自己的数据集时报错，数据集为COCO格式

### ISSUE THREAD

**Issue by thugbobby** [PaddlePaddle/PaddleDetection#2130]
```
W0128 01:05:07.871857 13432 build_strategy.cc:171] fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU.
E:\workspace\PaddleDetection\ppdet\data\reader.py:89: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  if isinstance(item, collections.Sequence) and len(item) == 0:
E:\workspace\PaddleDetection\ppdet\data\reader.py:49: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn("fail to map op [{}] with error: {} and stack:\n{}".
2021-01-28 01:05:08,063-WARNING: fail to map op [MixupImage_579933] with error: 'image' and stack:
Traceback (most recent call last):
  File "E:\workspace\PaddleDetection\ppdet\data\reader.py", line 46, in __call__
    data = f(data, ctx)
  File "E:\workspace\PaddleDetection\ppdet\data\transform\operators.py", line 1294, in __call__
    im = self._mixup_img(sample['image'], sample['mixup']['image'], factor)
KeyError: 'image'
C:\Users\thugbobby\anaconda3\lib\site-packages\paddle\fluid\reader.py:1255: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
  logging.warn('Your reader has raised an exception!')
2021-01-28 01:05:08,065-WARNING: Your reader has raised an exception!
Traceback (most recent call last):
Exception in thread   File ".\tools\train.py", line 399, in <module>
Thread-3    :
main()Traceback (most recent call last):

  File "C:\Users\thugbobby\anaconda3\lib\threading.py", line 932, in _bootstrap_inner
  File ".\tools\train.py", line 270, in main
    self.run()
      File "C:\Users\thugbobby\anaconda3\lib\threading.py", line 870, in run
outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "C:\Users\thugbobby\anaconda3\lib\site-packages\paddle\fluid\executor.py", line 1108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\thugbobby\anaconda3\lib\site-packages\paddle\fluid\reader.py", line 1256, in __thread_main__
    six.reraise(*sys.exc_info())
  File "C:\Users\thugbobby\anaconda3\lib\site-packages\six.py", line 703, in reraise
    six.reraise(*sys.exc_info())
  File "C:\Users\thugbobby\anaconda3\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\Users\thugbobby\anaconda3\lib\site-packages\paddle\fluid\executor.py", line 1096, in run
    raise value
  File "C:\Users\thugbobby\anaconda3\lib\site-packages\paddle\fluid\reader.py", line 1236, in __thread_main__
    return self._run_impl(
  File "C:\Users\thugbobby\anaconda3\lib\site-packages\paddle\fluid\executor.py", line 1242, in _run_impl
    for tensors in self._tensor_reader():
  File "C:\Users\thugbobby\anaconda3\lib\site-packages\paddle\fluid\reader.py", line 1306, in __tensor_reader_impl__
    return self._run_parallel(
  File "C:\Users\thugbobby\anaconda3\lib\site-packages\paddle\fluid\executor.py", line 911, in _run_parallel
    for slots in paddle_reader():
  File "C:\Users\thugbobby\anaconda3\lib\site-packages\paddle\fluid\data_feeder.py", line 550, in __reader_creator__
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
SystemError    : for item in reader():In user code:
    File ".\tools\train.py", line 399, in <module>
      main()
    File ".\tools\train.py", line 135, in main
      feed_vars, train_loader = model.build_inputs(**inputs_def)
    File "E:\workspace\PaddleDetection\ppdet\modeling\architectures\yolo.py", line 151, in build_inputs
      loader = fluid.io.DataLoader.from_generator(
    File "C:\Users\thugbobby\anaconda3\lib\site-packages\paddle\fluid\reader.py", line 740, in from_generator
      return GeneratorLoader(feed_list, capacity, use_double_buffer,
    File "C:\Users\thugbobby\anaconda3\lib\site-packages\paddle\fluid\reader.py", line 1089, in __init__
      self._init_non_iterable()
    File "C:\Users\thugbobby\anaconda3\lib\site-packages\paddle\fluid\reader.py", line 1187, in _init_non_iterable
      default_main_program().current_block().append_op(
    File "C:\Users\thugbobby\anaconda3\lib\site-packages\paddle\fluid\framework.py", line 2840, in append_op
      op = Operator(
    File "C:\Users\thugbobby\anaconda3\lib\site-packages\paddle\fluid\framework.py", line 1931, in __init__
      for frame in traceback.extract_stack():

    FatalError: Blocking queue is killed because the data reader raises an exception.
      [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at D:\2.0.0rc1\paddle\paddle/fluid/operators/reader/blocking_queue.h:154)
      [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
      [operator < read > error]

  File "E:\workspace\PaddleDetection\ppdet\data\reader.py", line 447, in _reader`
```

请问是什么问题？谢谢。

**Comment by yghstill** [comment]
@thugbobby 你修改了配置文件中的TrainReader了吗? 报错报在MixupImage找不到image的key，可以发下你的TrainReader设置

**Comment by thugbobby** [comment]
@yghstill 你好，这是我的TrainReader 修改过的 
```
TrainReader:
  inputs_def:
    image_shape: [3, 608, 608]
    fields: ['image', 'gt_bbox', 'gt_class', 'gt_score']
    num_max_boxes: 50
  dataset:
    !COCODataSet
    image_dir: train
    anno_path: annotations/instance_train.json
    dataset_dir: dataset/cocome
    with_background: false
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !MixupImage
    alpha: 1.5
    beta: 1.5
  - !ColorDistort {}
  - !RandomExpand
    fill_value: [123.675, 116.28, 103.53]
    ratio: 1.5
  - !RandomCrop {}
  - !RandomFlipImage
    is_normalized: false
  - !NormalizeBox {}
  - !PadBox
    num_max_boxes: 50
  - !BboxXYXY2XYWH {}
  batch_transforms:
  - !RandomShape
    sizes: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608]
    random_inter: True
  - !NormalizeImage
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    is_scale: True
    is_channel_first: false
  - !Permute
    channel_first: true
    to_bgr: false
  - !Gt2YoloTarget
    anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
    anchors: [[10, 13], [16, 30], [33, 23],
              [30, 61], [62, 45], [59, 119],
              [116, 90], [156, 198], [373, 326]]
    downsample_ratios: [32, 16, 8]
  batch_size: 8
  shuffle: true
  mixup_epoch: 250
```

**Comment by yghstill** [comment]
@thugbobby 如果你在DecodeImage中设置with_mixup: false，那么就需要把MixupImage操作删掉，mixup_epoch也删掉
