### ISSUE TITLE
nvidia_docker中，PaddleDetection执行时提示PaddlePaddle version 2.0.0-rc0 or higher is required！ 当前是paddlepaddle-gpu  1.8.5.post107

### ISSUE THREAD

**Issue by GreenValue** [PaddlePaddle/PaddleDetection#2154]
- 推理模型：

https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0-beta/configs/rcnn_enhance/generic
- docker环境

nvidia-docker pull hub.baidubce.com/paddlepaddle/paddle:1.8.5-gpu-cuda10.0-cudnn7

- docker中 执行命令：

```
python tools/infer.py -c configs/rcnn_enhance/generic/cascade_rcnn_dcn_r50_vd_fpn_gen_server_side.yml -o use_gpu=true  --infer_img=demo/ring2.jpg
```
报错：
```
Traceback (most recent call last):
  File "tools/infer.py", line 271, in <module>
    main()
  File "tools/infer.py", line 111, in main
    model = create(main_arch)
  File "/paddle/PaddleDetection/PaddleDetection/ppdet/core/workspace.py", line 273, in create
    return cls(**kwargs)
  File "/paddle/PaddleDetection/PaddleDetection/ppdet/modeling/architectures/cascade_rcnn.py", line 61, in __init__
    check_version('2.0.0-rc0')
  File "/paddle/PaddleDetection/PaddleDetection/ppdet/utils/check.py", line 98, in check_version
    raise Exception(err)
Exception: PaddlePaddle version 2.0.0-rc0 or higher is required, or a suitable develop version is satisfied as well. 
Please make sure the version is good with your code.
```

- 版本查看命令

```
import paddle
print(paddle.__file__)
print(paddle.__version__)
```

- 版本内容

```
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/__init__.pyc
1.8.5

```

**Comment by GreenValue** [comment]
或者，如何在 PaddlePaddle version 1.8.5下，进行用cascade_rcnn_dcn_r50_vd_fpn_gen_server_side模型，进行Detect？
python tools/infer.py -c configs/rcnn_enhance/generic/cascade_rcnn_dcn_r50_vd_fpn_gen_server_side.yml -o use_gpu=true  --infer_img=demo/ring2.jpg

**Comment by qingqing01** [comment]
方法1: PaddleDetection切换到0.5分支

```
git fetch
git checkout origin/release/0.5 -b  release/0.5
```

方法2: 升级PaddlePaddle版本:

安装2.0 或 2.0rc0版本, 参考

https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/2.0/install/pip/linux-pip.html

**Comment by GreenValue** [comment]
PaddleDetection切换到0.5分支后，依旧提示**PaddlePaddle version 2.0.0-rc0 or higher is required！**
λ my_ubuntu /paddle/PaddleDetection/b5/PaddleDetection {release/0.5} `git branch -v`
```
* release/0.5      f997fb7 Small update (#1919)
  release/2.0-beta da0e1ee Fix bug when executing eval.py with CPU & fix some grammatical mistakes (#2150)
```
λ my_ubuntu /paddle/PaddleDetection/b5/PaddleDetection {release/0.5} `python tools/infer.py -c configs/rcnn_enhance/generic/cascade_rcnn_dcn_r50_vd_fpn_gen_server_side.yml -o use_gpu=true  --infer_img=demo/ring2.jpg`
```
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
  File "tools/infer.py", line 271, in <module>
    main()
  File "tools/infer.py", line 111, in main
    model = create(main_arch)
  File "/paddle/PaddleDetection/b5/PaddleDetection/ppdet/core/workspace.py", line 268, in create
    return cls(**kwargs)
  File "/paddle/PaddleDetection/b5/PaddleDetection/ppdet/modeling/architectures/cascade_rcnn.py", line 61, in __init__
    check_version('2.0.0-rc0')
  File "/paddle/PaddleDetection/b5/PaddleDetection/ppdet/utils/check.py", line 78, in check_version
    raise Exception(err)
Exception: PaddlePaddle version 2.0.0-rc0 or higher is required, or a suitable develop version is satisfied as well. 
Please make sure the version is good with your code.

```

**Comment by GreenValue** [comment]
我想继续使用PaddlePaddle 1.8

**Comment by GreenValue** [comment]
按照[快速安装](https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/2.0/install/pip/windows-pip.html#cuda10)，升级paddlepaddle到2.0.0
`python -m pip install paddlepaddle-gpu==2.0.0.post100 -f https://paddlepaddle.org.cn/whl/stable.html`

版本升级成功：
pip list|grep paddlepaddle-gpu
`paddlepaddle-gpu                   2.0.0.post100`

但问题依旧，劳请帮忙看下：
root@ubutnu:/paddle/PaddleDetection/PaddleDetection# python tools/infer.py -c configs/rcnn_enhance/generic/cascade_rcnn_dcn_r50_vd_fpn_gen_server_side.yml -o use_gpu=true  --infer_img=demo/ring2.jpg
```
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
  File "tools/infer.py", line 271, in <module>
    main()
  File "tools/infer.py", line 111, in main
    model = create(main_arch)
  File "/paddle/PaddleDetection/PaddleDetection/ppdet/core/workspace.py", line 273, in create
    return cls(**kwargs)
  File "/paddle/PaddleDetection/PaddleDetection/ppdet/modeling/architectures/cascade_rcnn.py", line 61, in __init__
    check_version('2.0.0-rc0')
  File "/paddle/PaddleDetection/PaddleDetection/ppdet/utils/check.py", line 98, in check_version
    raise Exception(err)
**Exception: PaddlePaddle version 2.0.0-rc0 or higher is required**, or a suitable develop version is satisfied as well. 
Please make sure the version is good with your code.
```

**Comment by qingqing01** [comment]
您可以把这里的版本检查去掉试下

https://github.com/PaddlePaddle/PaddleDetection/blob/da0e1eed6472d492abc9db1db324569f9be62a5f/ppdet/modeling/architectures/cascade_rcnn.py#L61
