### ISSUE TITLE
when I train solov2, the learning rate is 0.00, and the training process stopped

### ISSUE THREAD

**Issue by JimXu1989** [PaddlePaddle/PaddleDetection#2228]
I annotate 10 images in coco format, and I tried to train solov2.
 while the terminal shows that the learning rate is 0.00, which is not the learning rate in the configure file, and the training process stopped. 

Is this because my training images too few??

**Comment by yghstill** [comment]
Can you post a complete printed log?

**Comment by JimXu1989** [comment]
> Can you post a complete printed log?

C:\Users\jim\anaconda3\python.exe G:/PaddleDetection-release-2.0-beta/train.py -c configs/solov2/solov2_r101_vd_fpn_3x.yml --use_vdl=true --vdl_log_dir=vdl_dir/scalar --eval
2021-02-18 16:12:46,252-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000100] in Optimizer will not take effect, and it will only be applied to other Parameters!
C:\Users\jim\anaconda3\Lib\site-packages\paddle\fluid\layers\utils.py:77: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  return (isinstance(seq, collections.Sequence) and
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
C:\Users\jim\anaconda3\Lib\site-packages\paddle\fluid\io.py:2282: UserWarning: This list is not set, Because of Paramerter not found in program. There are: fc_0.b_0 fc_0.w_0
  warnings.warn(
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2021-02-18 16:13:24,315-INFO: iter: 0, lr: 0.000000, 'loss_ins': '1.578603', 'loss_cate': '1.029281', 'loss': '2.607884', eta: 1 day, 2:01:45, batch_cost: 0.34706 sec, ips: 5.76276 images/sec
[INFO 2021-02-18 16:13:24,315 train.py:286] iter: 0, lr: 0.000000, 'loss_ins': '1.578603', 'loss_cate': '1.029281', 'loss': '2.607884', eta: 1 day, 2:01:45, batch_cost: 0.34706 sec, ips: 5.76276 images/sec
Traceback (most recent call last):
  File "G:/PaddleDetection-release-2.0-beta/train.py", line 399, in <module>
    main()
  File "G:/PaddleDetection-release-2.0-beta/train.py", line 270, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "C:\Users\jim\anaconda3\Lib\site-packages\paddle\fluid\executor.py", line 1110, in run
    six.reraise(*sys.exc_info())
  File "C:\Users\jim\anaconda3\Lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\Users\jim\anaconda3\Lib\site-packages\paddle\fluid\executor.py", line 1098, in run
    return self._run_impl(
  File "C:\Users\jim\anaconda3\Lib\site-packages\paddle\fluid\executor.py", line 1244, in _run_impl
    return self._run_parallel(
  File "C:\Users\jim\anaconda3\Lib\site-packages\paddle\fluid\executor.py", line 913, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
OSError: (External)  Cuda error(4), unspecified launch failure.
  [Advise: An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. All existing device memory allocations are invalid. To continue using CUDA, theprocess must be terminated and relaunched.] (at D:\v2.0.0\paddle\paddle\fluid\platform\stream\cuda_stream.cc:65)


Process finished with exit code -1073740791 (0xC0000409)

**Comment by JimXu1989** [comment]
> Can you post a complete printed log?
更多的时候没有报错只是像下面这样卡在这里，还有的时候偶尔会报显存不足
C:\Users\jim\anaconda3\python.exe G:/PaddleDetection-release-2.0-beta/train.py -c configs/solov2/solov2_r101_vd_fpn_3x.yml --use_vdl=true --vdl_log_dir=vdl_dir/scalar --eval
2021-02-18 16:21:08,527-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000100] in Optimizer will not take effect, and it will only be applied to other Parameters!
C:\Users\jim\anaconda3\Lib\site-packages\paddle\fluid\layers\utils.py:77: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  return (isinstance(seq, collections.Sequence) and
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
C:\Users\jim\anaconda3\Lib\site-packages\paddle\fluid\io.py:2282: UserWarning: This list is not set, Because of Paramerter not found in program. There are: fc_0.b_0 fc_0.w_0
  warnings.warn(
2021-02-18 16:21:40,511-INFO: iter: 0, lr: 0.000000, 'loss_ins': '1.509780', 'loss_cate': '1.031236', 'loss': '2.541016', eta: 14:12:43, batch_cost: 0.18949 sec, ips: 10.55438 images/sec
[INFO 2021-02-18 16:21:40,511 train.py:286] iter: 0, lr: 0.000000, 'loss_ins': '1.509780', 'loss_cate': '1.031236', 'loss': '2.541016', eta: 14:12:43, batch_cost: 0.18949 sec, ips: 10.55438 images/sec

**Comment by JimXu1989** [comment]
> Can you post a complete printed log?

我认为卡主不动的原因很可能是learning rate 是0，但我又不知道如何设置这个学习率

**Comment by JimXu1989** [comment]
> Can you post a complete printed log?

我使用val2017数据集训练也是这个样子，learning rate 还是0，train2017数据集太大了，所以用的val2017
C:\Users\jim\anaconda3\python.exe G:/PaddleDetection-release-2.0-beta/train.py -c configs/solov2/solov2_r101_vd_fpn_3x.yml --use_vdl=true --vdl_log_dir=vdl_dir/scalar --eval
2021-02-18 17:14:27,775-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000100] in Optimizer will not take effect, and it will only be applied to other Parameters!
C:\Users\jim\anaconda3\Lib\site-packages\paddle\fluid\layers\utils.py:77: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  return (isinstance(seq, collections.Sequence) and
loading annotations into memory...
Done (t=0.64s)
creating index...
index created!
C:\Users\jim\anaconda3\Lib\site-packages\paddle\fluid\io.py:2282: UserWarning: This list is not set, Because of Paramerter not found in program. There are: fc_0.b_0 fc_0.w_0
  warnings.warn(
loading annotations into memory...
Done (t=0.71s)
creating index...
index created!
2021-02-18 17:15:13,011-INFO: iter: 0, lr: 0.000000, 'loss_ins': '2.494960', 'loss_cate': '1.167318', 'loss': '3.662278', eta: 13:18:52, batch_cost: 0.17753 sec, ips: 11.26593 images/sec
[INFO 2021-02-18 17:15:13,011 train.py:286] iter: 0, lr: 0.000000, 'loss_ins': '2.494960', 'loss_cate': '1.167318', 'loss': '3.662278', eta: 13:18:52, batch_cost: 0.17753 sec, ips: 11.26593 images/sec
Traceback (most recent call last):
  File "G:/PaddleDetection-release-2.0-beta/train.py", line 399, in <module>
    main()
  File "G:/PaddleDetection-release-2.0-beta/train.py", line 270, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "C:\Users\jim\anaconda3\Lib\site-packages\paddle\fluid\executor.py", line 1110, in run
    six.reraise(*sys.exc_info())
  File "C:\Users\jim\anaconda3\Lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\Users\jim\anaconda3\Lib\site-packages\paddle\fluid\executor.py", line 1098, in run
    return self._run_impl(
  File "C:\Users\jim\anaconda3\Lib\site-packages\paddle\fluid\executor.py", line 1244, in _run_impl
    return self._run_parallel(
  File "C:\Users\jim\anaconda3\Lib\site-packages\paddle\fluid\executor.py", line 913, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
RuntimeError: ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 3.908447MB memory on GPU 0, available memory is only 166.399414kB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at D:\v2.0.0\paddle\paddle\fluid\memory\allocation\cuda_allocator.cc:69)

我的显卡是2070的，显存也是8G，batch_size我也设置为1了

**Comment by yghstill** [comment]
- 看报错信息应该是cuda共享内存的原因，训练其他模型或在其他机器上训练是否有问题呢？或者将worker_num进程数设为1再试下，https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-rc/configs/solov2/solov2_reader.yml#L3、
- solov2_r101_vd_fpn_3x可能需要比8G更多的显存，可以先训下solov2_r50是否正常。

**Comment by heavengate** [comment]
您好，鉴于问题已经解决，当前issue关闭，如果还有问题你可以reopen此issue~
