### ISSUE TITLE
Cascade R-CNN系列模型与2.0.0版本

### ISSUE THREAD

**Issue by yinggo** [PaddlePaddle/PaddleDetection#2253]
Cascade R-CNN系列模型在2.0.0版本上能否运行，aistudio上最新的版本是2.0.0， 能否在[aistudio](aistudio.baidu.com)平台上运行Cascade R-CNN模型？

**Comment by qingqing01** [comment]
@yinggo 可以的。您这边有什么问题吗？

**Comment by yinggo** [comment]
我在aistudio,paddle==2.0.0版本下，测试报错：
```
aistudio@jupyter-271427-1477212:~/work/PaddleDetection$ python -u tools/train.py -c configs/dcn/cascade_mask_rcnn_dcnv2_se154_vd_fpn_gn_s1x.yml \>                     --use_vdl=true \>                     --vdl_log_dir=vdl_dir/cascade_mask_rcnn_dcnv2_se154_vd_fpn_gn_s1x/scalar \
>                     --eval
Traceback (most recent call last):
  File "tools/train.py", line 399, in <module>
    main()
  File "tools/train.py", line 126, in main
    model = create(main_arch)
  File "/home/aistudio/work/PaddleDetection/ppdet/core/workspace.py", line 273, in create
    return cls(**kwargs)
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/architectures/cascade_mask_rcnn.py", line 66, in __init__
    check_version('2.0.0-rc0')
  File "/home/aistudio/work/PaddleDetection/ppdet/utils/check.py", line 98, in check_version
    raise Exception(err)
Exception: PaddlePaddle version 2.0.0-rc0 or higher is required, or a suitable develop version is satisfied as well. 
Please make sure the version is good with your code.
```
请问您那边能测试下解决吗？

**Comment by qingqing01** [comment]
@yinggo 这个是由于版本号检查问题， 可以去掉下面代码看下。我们也立即修复下

https://github.com/PaddlePaddle/PaddleDetection/blob/da0e1eed6472d492abc9db1db324569f9be62a5f/ppdet/modeling/architectures/cascade_mask_rcnn.py#L66

**Comment by qingqing01** [comment]
@yinggo 请问还是否有问题， https://github.com/PaddlePaddle/PaddleDetection/pull/2157/files 这个PR在下次要发布的版本里已修复。

**Comment by yinggo** [comment]
@qingqing01 已解决，谢谢
