### ISSUE TITLE
yaml文件读取错误：UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 41: illegal multibyte sequence

### ISSUE THREAD

**Issue by pythonprogrammingbook** [PaddlePaddle/PaddleDetection#2268]
开发环境
OS: Window10 
Paddle = 2.0.0, git clone 最新版PaddleDetection
---
**问题复现：**
(pp) D:\pp\PaddleDetection>python -u tools/train.py -c configs/hw_configs/faster_rcnn_r50_vd_fpn_roadsign_coco_template.yml -o use_gpu=true --eval
Traceback (most recent call last):
  File "tools/train.py", line 399, in <module>
    main()
  File "tools/train.py", line 71, in main
    cfg = load_config(FLAGS.config)
  File "D:\pp\PaddleDetection\ppdet\core\workspace.py", line 91, in load_config
    cfg = merge_config(yaml.load(f, Loader=yaml.Loader), cfg)
  File "C:\Users\Administrator\.conda\envs\pp\lib\site-packages\yaml\__init__.py", line 112, in load
    loader = Loader(stream)
  File "C:\Users\Administrator\.conda\envs\pp\lib\site-packages\yaml\loader.py", line 44, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\Administrator\.conda\envs\pp\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\Users\Administrator\.conda\envs\pp\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "C:\Users\Administrator\.conda\envs\pp\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 41: illegal multibyte sequence

**推荐解决方案：**
PaddleDetection\ppdet\core\workspace.py", line 90改为：
with open(file_path, 'r', encoding='utf-8') as f:

**Comment by heavengate** [comment]
好的，感谢反馈，我们修复一下~

**Comment by heavengate** [comment]
您好，请问一下你用的python版本是多少，以及麻烦打印一下`import sys; print(sys.getdefaultencoding())`看下呢

**Comment by pythonprogrammingbook** [comment]
Python版本：3.7.9

结果：utf-8




python_programming@163.com
 
发件人： Kaipeng Deng
发送时间： 2021-02-28 22:26
收件人： PaddlePaddle/PaddleDetection
抄送： pythonprogrammingbook; Author
主题： Re: [PaddlePaddle/PaddleDetection] yaml文件读取错误：UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 41: illegal multibyte sequence (#2268)
您好，请问一下你用的python版本是多少，以及麻烦打印一下import sys; print(sys.getdefaultencoding())看下呢

**Comment by RDXiaoLu** [comment]
我也出现了同样的问题 win10  yaml这个模块 python 3.7.13  utf-8

**Comment by GroganZY** [comment]
现在还没修吗？
