### ISSUE TITLE
基于paddledetection训练的自己的模型，剪裁出现问题

### ISSUE THREAD

**Issue by guotongjian** [PaddlePaddle/PaddleDetection#2345]
1、使用paddletection训练好的模型，使用剪裁时发现如下：

```
2021-03-14 16:35:02,283-INFO: sensitive - param: res2c_branch2c_weights; ratios: 0.6
2021-03-14 16:35:02,343-INFO: pruning: res2c_branch2c_weights
2021-03-14 16:35:12,415 - INFO - Test iter 0
2021-03-14 16:35:14,065 - INFO - Test finish iter 19
2021-03-14 16:35:14,065 - INFO - Total number of images: 19, inference time: 10.222864249571384 fps.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2021-03-14 16:35:14,068 - WARNING - The number of valid bbox detected is zero.
Please use reasonable model and check input data.
stop eval!
```
正常情况，我的test image number是147，这里显示19，而且提示bbox无效，检查数据，是什么原因呢
2、在1的基础下继续往后执行，首先依照官方教程计算敏感度信息，然后执行命令如下：

```
python slim/prune/prune.py  \ 
    -c configs/dcn/mymodel.yml  \ 
    --pruned_params "conv1_1_weights,conv1_2_weights,res2a_branch2a_weights,res2a_branch2b_weights,res2b_branch2a_weights,res2b_branch2b_weights,res2c_branch2a_weights,res2c_branch2b_weights,res3a_branch2a_weights,res3a_branch2b_weights,res3b_branch2a_weights,res3b_branch2b_weights,res3c_branch2a_weights,res3c_branch2b_weights,res3d_branch2a_weights,res3d_branch2b_weights,res4a_branch2a_weights,res4a_branch2b_weights,res4a_branch1_weights,res4b_branch2a_weights,res4b_branch2b_weights,res4c_branch2a_weights,res4c_branch2b_weights,res4d_branch2a_weights,res4d_branch2b_weights,res4e_branch2a_weights,res4e_branch2b_weights,res4f_branch2a_weights,res4f_branch2b_weights,res5a_branch2a_weights,res5a_branch2b_conv_offset.w_0,res5a_branch2b_conv_offset.b_0,res5a_branch2b_weights,res5b_branch2a_weights,res5b_branch2b_conv_offset.w_0,res5b_branch2b_conv_offset.b_0,res5b_branch2b_weights,res5c_branch2a_weights,res5c_branch2b_conv_offset.w_0,res5c_branch2b_conv_offset.b_0,res5c_branch2b_weights,yolo_block.0.0.1.conv.weights,yolo_block.0.1.0.conv.weights,yolo_block.0.1.1.conv.weights,yolo_block.0.2.conv.weights,yolo_transition.0.conv.weights,yolo_block.1.0.1.conv.weights,yolo_block.1.1.0.conv.weights,yolo_block.1.1.1.conv.weights,yolo_block.1.2.conv.weights,yolo_block.1.tip.conv.weights,yolo_transition.1.conv.weights,yolo_block.2.0.1.conv.weights,yolo_block.2.2.conv.weights,yolo_block.2.tip.conv.weights,yolo_output.2.conv.weights" \ 
    --
pruned_ratios="0.3358649194844731,0.2339780010533772,0.23606618086491846,0.3391804944634715,0.6150057856781177,0.2936964621561007,0.8209326739504567,0.18784995148759304,0.9,0.9,0.6738703254350586,0.8045394570899849,0.3055661323305,0.4716109533887517,0.7525318024093136,0.5681596283579269,0.20368089132274939,0.6109348317524175,0.10189828674907515,0.21786649209581851,0.2946036283182185,0.28630456795703846,0.7498492919542514,0.7238426743122531,0.7681168823679925,0.656914613419909,0.9,0.9,0.24535839048004268,0.11198110435415323,0.6251246956805364,0.6580772211815603,0.9,0.16927295990673127,0.625856083834839,0.6310738155243336,0.9,0.11243303946085358,0.34813118930049636,0.9,0.9,0.3030570813253197,0.12604462968399122,0.11274702913601214,0.2534227176260217,0.4190814406602485,0.2620534430087345,0.2621800083595275,0.3595636723599184,0.2902062266643235,0.317639218526475,0.3543520713222885,0.5087817938047486,0.524531815921334,0.4223076040356991,0.10074569265829028"
```
**在prune过程中又出现错误:**
```
2021-03-14 20:48:15,801-INFO: pruning: res4f_branch2b_weights
2021-03-14 20:48:17,121-INFO: pruning: res5a_branch2a_weights
2021-03-14 20:48:19,659-INFO: pruning: res5a_branch2b_conv_offset.w_0
2021-03-14 20:48:20,711-INFO: pruning: res5a_branch2b_conv_offset.b_0
2021-03-14 20:48:20,747-INFO: pruning: res5a_branch2b_weights
**2021-03-14 20:48:20,781-INFO: No walker for operator: deformable_conv**
2021-03-14 20:48:20,781-INFO: pruning: res5b_branch2a_weights
2021-03-14 20:48:23,262-INFO: pruning: res5b_branch2b_conv_offset.w_0
2021-03-14 20:48:24,298-INFO: pruning: res5b_branch2b_conv_offset.b_0
2021-03-14 20:48:24,333-INFO: pruning: res5b_branch2b_weights
**2021-03-14 20:48:24,370-INFO: No walker for operator: deformable_conv**
2021-03-14 20:48:24,370-INFO: pruning: res5c_branch2a_weights
2021-03-14 20:48:26,850-INFO: pruning: res5c_branch2b_conv_offset.w_0
2021-03-14 20:48:27,893-INFO: pruning: res5c_branch2b_conv_offset.b_0
2021-03-14 20:48:27,929-INFO: pruning: res5c_branch2b_weights
**2021-03-14 20:48:27,964-INFO: No walker for operator: deformable_conv**
2021-03-14 20:48:27,964-INFO: pruning: yolo_block.0.0.1.conv.weights
2021-03-14 20:48:29,309-INFO: pruning: yolo_block.0.1.0.conv.weights
2021-03-14 20:48:30,775-INFO: pruning: yolo_block.0.1.1.conv.weights
2021-03-14 20:48:32,186-INFO: pruning: yolo_block.0.2.conv.weights
2021-03-14 20:48:33,948-INFO: pruning: yolo_transition.0.conv.weights
2021-03-14 20:48:35,416-INFO: pruning: yolo_block.1.0.1.conv.weights
2021-03-14 20:48:36,922-INFO: pruning: yolo_block.1.1.0.conv.weights
2021-03-14 20:48:38,219-INFO: pruning: yolo_block.1.1.1.conv.weights
2021-03-14 20:48:39,617-INFO: pruning: yolo_block.1.2.conv.weights
2021-03-14 20:48:41,315-INFO: pruning: yolo_block.1.tip.conv.weights
2021-03-14 20:48:42,789-INFO: pruning: yolo_transition.1.conv.weights
2021-03-14 20:48:44,290-INFO: pruning: yolo_block.2.0.1.conv.weights
2021-03-14 20:48:45,736-INFO: pruning: yolo_block.2.2.conv.weights
2021-03-14 20:48:47,143-INFO: pruning: yolo_block.2.tip.conv.weights
2021-03-14 20:48:48,538-INFO: pruning: yolo_output.2.conv.weights
Traceback (most recent call last):
  File "slim/prune/prune.py", line 415, in <module>
    main()
  File "slim/prune/prune.py", line 199, in main
    only_graph=False)[0]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/pruner.py", line 98, in prune
    visited)[0]  # [(name, axis, pruned_idx)]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/group_param.py", line 87, in collect_convs
    walker.prune(param, pruned_axis=0, pruned_idx=[])
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 161, in _prune
    self._prune_op(op, output_var, channel_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 316, in _prune
    self._visit_and_search(out_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 75, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 365, in _prune
    self._visit_and_search(out_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 75, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 365, in _prune
    self._visit_and_search(out_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 75, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 306, in _prune
    self._visit_and_search(in_var, y_pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 72, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 290, in _prune
    self._visit_and_search(in_var, actual_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 72, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 365, in _prune
    self._visit_and_search(out_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 75, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 365, in _prune
    self._visit_and_search(out_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 75, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 365, in _prune
    self._visit_and_search(out_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 75, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 365, in _prune
    self._visit_and_search(out_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 75, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 306, in _prune
    self._visit_and_search(in_var, y_pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 75, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 313, in _prune
    self._visit_and_search(in_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 72, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 362, in _prune
    self._visit_and_search(in_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 72, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 362, in _prune
    self._visit_and_search(in_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 72, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 362, in _prune
    self._visit_and_search(in_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 72, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 361, in _prune
    if len(in_var.shape()) == len(var.shape()):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/core/graph_wrapper.py", line 64, in shape
    return self._var.shape
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1561, in shape
    return tuple(self.desc.shape())
**RuntimeError: (Unavailable) Getting 'tensor_desc' is not supported by the double_buffer_0 type variable. (at /paddle/paddle/fluid/framework/var_desc.cc:213)**
```

**Comment by qingqing01** [comment]
@guotongjian 
1. 第一个问题，做预测时batch-size多大？ 可以单图预测看下，每张图是否有预测输出？

计算总共预测图片的代码如下，如果预测有输出，会依据计算结果，累计预测的图片数，否则 +1，你上面错误，有可能预测输出是空的。

https://github.com/PaddlePaddle/PaddleDetection/blob/3693d7886ba8a0e6ee9ff37580e21b9025703231/ppdet/utils/eval_utils.py#L193


2. 第二个问题，warning信息提升，暂不支持deformable_conv的裁剪。您裁剪的是PP-YOLO R50吗？

**Comment by guotongjian** [comment]
> @guotongjian
> 
> 1. 第一个问题，做预测时batch-size多大？ 可以单图预测看下，每张图是否有预测输出？
> 
> 计算总共预测图片的代码如下，如果预测有输出，会依据计算结果，累计预测的图片数，否则 +1，你上面错误，有可能预测输出是空的。
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/3693d7886ba8a0e6ee9ff37580e21b9025703231/ppdet/utils/eval_utils.py#L193
> 
> 1. 第二个问题，warning信息提升，暂不支持deformable_conv的裁剪。您裁剪的是PP-YOLO R50吗？

第一个问题是在按ratios从0.1到0.9做敏感度分析时出现的，在整个分析过程中，剪裁别的层或者在别的ratio下有时候是正常的没有问题，显示的测试图片数量也是147，只是在有的层和有的ratio下会出现第一个问题。预测的batchsize是1，在剪裁之前预测过，有些图是没有显示框的，我以为是模型本身就检测不出。
第二个问题，我剪裁的是yolo3+res50+dcn的模型，我把所有的卷积层都添加到敏感度分析那里进行计算了。

**Comment by qingqing01** [comment]
第一个问题,  可能是 "有的层和有的ratio下"  模型预测输出很差导致的。

第二个问题，可以暂时去掉deformabel_conv的weight，不做裁剪。

**Comment by guotongjian** [comment]
> 第一个问题, 可能是 "有的层和有的ratio下" 模型预测输出很差导致的。
> 
> 第二个问题，可以暂时去掉deformabel_conv的weight，不做裁剪。

好的，感谢

**Comment by qingqing01** [comment]
@guotongjian  另外，提醒下, https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0-rc/slim#%E8%AE%AD%E7%BB%83%E7%AD%96%E7%95%A5

这里是我们之前的裁剪之眼，R50只裁剪了head部分，见r578策略。
