### ISSUE TITLE
模型剪裁出现错误，请大佬指教

### ISSUE THREAD

**Issue by guotongjian** [PaddlePaddle/PaddleDetection#2358]
`aistudio@jupyter-526081-1607870:~/data/data72217/bao$ python slim/prune/prune.py -c configs/dcn/mymodel.yml --pruned_params "conv1_1_weights,conv1_2_weights,res2a_branch2a_weights,res2a_branch2b_weights,res2b_branch2a_weights,res2b_branch2b_weights,res2c_branch2a_weights,res2c_branch2b_weights,res3a_branch2a_weights,res3a_branch2b_weights,res3b_branch2a_weights,res3b_branch2b_weights,res3c_branch2a_weights,res3c_branch2b_weights,res3d_branch2a_weights,res3d_branch2b_weights,res4a_branch2a_weights,res4a_branch2b_weights,res4a_branch1_weights,res4b_branch2a_weights,res4b_branch2b_weights,res4c_branch2a_weights,res4c_branch2b_weights,res4d_branch2a_weights,res4d_branch2b_weights,res4e_branch2a_weights,res4e_branch2b_weights,res4f_branch2a_weights,res4f_branch2b_weights,yolo_block.0.0.1.conv.weights,yolo_block.0.1.0.conv.weights,yolo_block.0.1.1.conv.weights,yolo_block.0.2.conv.weights,yolo_transition.0.conv.weights,yolo_block.1.0.1.conv.weights,yolo_block.1.1.0.conv.weights,yolo_block.1.1.1.conv.weights,yolo_block.1.2.conv.weights,yolo_block.1.tip.conv.weights,yolo_transition.1.conv.weights,yolo_block.2.0.1.conv.weights,yolo_block.2.2.conv.weights,yolo_block.2.tip.conv.weights,yolo_output.2.conv.weights" --pruned_ratios="0.3358649194844731,0.2339780010533776,0.23606618086491846,0.3391804944634715,0.6150057856781177,0.2936964621561007,0.8209326739504567,0.18784995148759304,0.9,0.9,0.6738703254350586,0.8045394570899849,0.3055661323305,0.4716109533887517,0.7525318024093136,0.5681596283579269,0.20368089132274939,0.6109348317524175,0.10189828674907515,0.21786649209581851,0.2946036283182185,0.28630456795703846,0.7498492919542514,0.7238426743122531,0.7681168823679925,0.656914613419909,0.9,0.9,0.24535839048004268,0.3030570813253197,0.12604462968399122,0.11274702913601214,0.2534227176260217,0.4190814406602485,0.2620534430087345,0.2621800083595275,0.3595636723599184,0.2902062266643235,0.317639218526475,0.3543520713222885,0.5087817938047486,0.524531815921334,0.4223076040356991,0.10074569265829028"`
执行以上命令，执行到最后一个要剪枝的层时报错
```
2021-03-15 22:16:28,410-INFO: pruning: conv1_1_weights
2021-03-15 22:16:29,725-INFO: pruning: conv1_2_weights
2021-03-15 22:16:31,226-INFO: pruning: res2a_branch2a_weights
2021-03-15 22:16:32,692-INFO: pruning: res2a_branch2b_weights
2021-03-15 22:16:34,353-INFO: pruning: res2b_branch2a_weights
2021-03-15 22:16:35,739-INFO: pruning: res2b_branch2b_weights
2021-03-15 22:16:37,224-INFO: pruning: res2c_branch2a_weights
2021-03-15 22:16:38,606-INFO: pruning: res2c_branch2b_weights
2021-03-15 22:16:39,995-INFO: pruning: res3a_branch2a_weights
2021-03-15 22:16:41,488-INFO: pruning: res3a_branch2b_weights
2021-03-15 22:16:42,856-INFO: pruning: res3b_branch2a_weights
2021-03-15 22:16:44,365-INFO: pruning: res3b_branch2b_weights
2021-03-15 22:16:45,681-INFO: pruning: res3c_branch2a_weights
2021-03-15 22:16:47,203-INFO: pruning: res3c_branch2b_weights
2021-03-15 22:16:48,489-INFO: pruning: res3d_branch2a_weights
2021-03-15 22:16:49,923-INFO: pruning: res3d_branch2b_weights
2021-03-15 22:16:51,383-INFO: pruning: res4a_branch2a_weights
2021-03-15 22:16:52,763-INFO: pruning: res4a_branch2b_weights
2021-03-15 22:16:54,230-INFO: pruning: res4a_branch1_weights
2021-03-15 22:17:05,365-INFO: pruning: res4b_branch2a_weights
2021-03-15 22:17:06,810-INFO: pruning: res4b_branch2b_weights
2021-03-15 22:17:08,376-INFO: pruning: res4c_branch2a_weights
2021-03-15 22:17:09,807-INFO: pruning: res4c_branch2b_weights
2021-03-15 22:17:11,342-INFO: pruning: res4d_branch2a_weights
2021-03-15 22:17:12,767-INFO: pruning: res4d_branch2b_weights
2021-03-15 22:17:14,283-INFO: pruning: res4e_branch2a_weights
2021-03-15 22:17:15,698-INFO: pruning: res4e_branch2b_weights
2021-03-15 22:17:17,037-INFO: pruning: res4f_branch2a_weights
2021-03-15 22:17:18,594-INFO: pruning: res4f_branch2b_weights
2021-03-15 22:17:19,936-INFO: pruning: yolo_block.0.0.1.conv.weights
2021-03-15 22:17:21,491-INFO: pruning: yolo_block.0.1.0.conv.weights
2021-03-15 22:17:22,909-INFO: pruning: yolo_block.0.1.1.conv.weights
2021-03-15 22:17:24,377-INFO: pruning: yolo_block.0.2.conv.weights
2021-03-15 22:17:26,245-INFO: pruning: yolo_transition.0.conv.weights
2021-03-15 22:17:27,870-INFO: pruning: yolo_block.1.0.1.conv.weights
2021-03-15 22:17:29,261-INFO: pruning: yolo_block.1.1.0.conv.weights
2021-03-15 22:17:30,797-INFO: pruning: yolo_block.1.1.1.conv.weights
2021-03-15 22:17:32,143-INFO: pruning: yolo_block.1.2.conv.weights
2021-03-15 22:17:33,924-INFO: pruning: yolo_block.1.tip.conv.weights
2021-03-15 22:17:35,434-INFO: pruning: yolo_transition.1.conv.weights
2021-03-15 22:17:37,047-INFO: pruning: yolo_block.2.0.1.conv.weights
2021-03-15 22:17:38,571-INFO: pruning: yolo_block.2.2.conv.weights
2021-03-15 22:17:39,986-INFO: pruning: yolo_block.2.tip.conv.weights
2021-03-15 22:17:41,353-INFO: pruning: yolo_output.2.conv.weights
Traceback (most recent call last):
  File "slim/prune/prune.py", line 415, in <module>
    main()
  File "slim/prune/prune.py", line 199, in main
    only_graph=False)[0]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/pruner.py", line 98, in prune
    visited)[0]  # [(name, axis, pruned_idx)]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/group_param.py", line 87, in collect_convs
    walker.prune(param, pruned_axis=0, pruned_idx=[])
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 161, in _prune
    self._prune_op(op, output_var, channel_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 316, in _prune
    self._visit_and_search(out_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 75, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 365, in _prune
    self._visit_and_search(out_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 75, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 365, in _prune
    self._visit_and_search(out_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 75, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 306, in _prune
    self._visit_and_search(in_var, y_pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 72, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 290, in _prune
    self._visit_and_search(in_var, actual_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 72, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 365, in _prune
    self._visit_and_search(out_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 75, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 365, in _prune
    self._visit_and_search(out_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 75, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 365, in _prune
    self._visit_and_search(out_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 75, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 365, in _prune
    self._visit_and_search(out_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 75, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 306, in _prune
    self._visit_and_search(in_var, y_pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 75, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 313, in _prune
    self._visit_and_search(in_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 72, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 362, in _prune
    self._visit_and_search(in_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 72, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 362, in _prune
    self._visit_and_search(in_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 72, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 362, in _prune
    self._visit_and_search(in_var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 72, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 101, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 55, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 361, in _prune
    if len(in_var.shape()) == len(var.shape()):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/core/graph_wrapper.py", line 64, in shape
    return self._var.shape
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1561, in shape
    return tuple(self.desc.shape())
RuntimeError: (Unavailable) Getting 'tensor_desc' is not supported by the double_buffer_0 type variable. (at /paddle/paddle/fluid/framework/var_desc.cc:213)
```
然后我在命令里去掉最后一个要剪枝的层，执行命令
```
2021-03-15 22:21:02,150-INFO: pruning: conv1_1_weights
2021-03-15 22:21:03,307-INFO: pruning: conv1_2_weights
2021-03-15 22:21:04,541-INFO: pruning: res2a_branch2a_weights
2021-03-15 22:21:05,688-INFO: pruning: res2a_branch2b_weights
2021-03-15 22:21:06,924-INFO: pruning: res2b_branch2a_weights
2021-03-15 22:21:08,087-INFO: pruning: res2b_branch2b_weights
2021-03-15 22:21:09,340-INFO: pruning: res2c_branch2a_weights
2021-03-15 22:21:10,540-INFO: pruning: res2c_branch2b_weights
2021-03-15 22:21:11,783-INFO: pruning: res3a_branch2a_weights
2021-03-15 22:21:13,089-INFO: pruning: res3a_branch2b_weights
2021-03-15 22:21:14,244-INFO: pruning: res3b_branch2a_weights
2021-03-15 22:21:15,482-INFO: pruning: res3b_branch2b_weights
2021-03-15 22:21:16,639-INFO: pruning: res3c_branch2a_weights
2021-03-15 22:21:17,883-INFO: pruning: res3c_branch2b_weights
2021-03-15 22:21:19,055-INFO: pruning: res3d_branch2a_weights
2021-03-15 22:21:20,219-INFO: pruning: res3d_branch2b_weights
2021-03-15 22:21:21,527-INFO: pruning: res4a_branch2a_weights
2021-03-15 22:21:22,705-INFO: pruning: res4a_branch2b_weights
2021-03-15 22:21:23,973-INFO: pruning: res4a_branch1_weights
2021-03-15 22:21:33,218-INFO: pruning: res4b_branch2a_weights
2021-03-15 22:21:34,411-INFO: pruning: res4b_branch2b_weights
2021-03-15 22:21:35,671-INFO: pruning: res4c_branch2a_weights
2021-03-15 22:21:36,844-INFO: pruning: res4c_branch2b_weights
2021-03-15 22:21:38,106-INFO: pruning: res4d_branch2a_weights
2021-03-15 22:21:39,293-INFO: pruning: res4d_branch2b_weights
2021-03-15 22:21:40,561-INFO: pruning: res4e_branch2a_weights
2021-03-15 22:21:41,743-INFO: pruning: res4e_branch2b_weights
2021-03-15 22:21:42,936-INFO: pruning: res4f_branch2a_weights
2021-03-15 22:21:44,200-INFO: pruning: res4f_branch2b_weights
2021-03-15 22:21:45,368-INFO: pruning: yolo_block.0.0.1.conv.weights
2021-03-15 22:21:46,705-INFO: pruning: yolo_block.0.1.0.conv.weights
2021-03-15 22:21:47,979-INFO: pruning: yolo_block.0.1.1.conv.weights
2021-03-15 22:21:49,302-INFO: pruning: yolo_block.0.2.conv.weights
2021-03-15 22:21:50,918-INFO: pruning: yolo_transition.0.conv.weights
2021-03-15 22:21:52,266-INFO: pruning: yolo_block.1.0.1.conv.weights
2021-03-15 22:21:53,477-INFO: pruning: yolo_block.1.1.0.conv.weights
2021-03-15 22:21:54,753-INFO: pruning: yolo_block.1.1.1.conv.weights
2021-03-15 22:21:55,939-INFO: pruning: yolo_block.1.2.conv.weights
2021-03-15 22:21:57,445-INFO: pruning: yolo_block.1.tip.conv.weights
2021-03-15 22:21:58,731-INFO: pruning: yolo_transition.1.conv.weights
2021-03-15 22:22:00,013-INFO: pruning: yolo_block.2.0.1.conv.weights
2021-03-15 22:22:01,280-INFO: pruning: yolo_block.2.2.conv.weights
2021-03-15 22:22:02,463-INFO: pruning: yolo_block.2.tip.conv.weights
```
程序运行到这里，夯住
我是基于paddletection用yolov3增强版config文件训练的自己的数据，没有用dropblock

**Comment by heavengate** [comment]
裁剪完成之后需要会进行网络编译和训练启动，会消耗一定的时间，请问你这里hang住多久呢

**Comment by guotongjian** [comment]
> 裁剪完成之后需要会进行网络编译和训练启动，会消耗一定的时间，请问你这里hang住多久呢

hang住20分钟还没有反应，然后我就关了

**Comment by heavengate** [comment]
Paddle  PaddleSlim  PaddleDetection 版本还有跑的命令麻烦发一下

**Comment by guotongjian** [comment]
> Paddle PaddleSlim PaddleDetection 版本还有跑的命令麻烦发一下

Paddle2.0.0，PaddleSlim2.0，PaddleDetection2.0-release
命令：
`python slim/prune/prune.py -c configs/dcn/mymodel.yml --pruned_params "conv1_1_weights,conv1_2_weights,res2a_branch2a_weights,res2a_branch2b_weights,res2b_branch2a_weights,res2b_branch2b_weights,res2c_branch2a_weights,res2c_branch2b_weights,res3a_branch2a_weights,res3a_branch2b_weights,res3b_branch2a_weights,res3b_branch2b_weights,res3c_branch2a_weights,res3c_branch2b_weights,res3d_branch2a_weights,res3d_branch2b_weights,res4a_branch2a_weights,res4a_branch2b_weights,res4a_branch1_weights,res4b_branch2a_weights,res4b_branch2b_weights,res4c_branch2a_weights,res4c_branch2b_weights,res4d_branch2a_weights,res4d_branch2b_weights,res4e_branch2a_weights,res4e_branch2b_weights,res4f_branch2a_weights,res4f_branch2b_weights,yolo_block.0.0.1.conv.weights,yolo_block.0.1.0.conv.weights,yolo_block.0.1.1.conv.weights,yolo_block.0.2.conv.weights,yolo_transition.0.conv.weights,yolo_block.1.0.1.conv.weights,yolo_block.1.1.0.conv.weights,yolo_block.1.1.1.conv.weights,yolo_block.1.2.conv.weights,yolo_block.1.tip.conv.weights,yolo_transition.1.conv.weights,yolo_block.2.0.1.conv.weights,yolo_block.2.2.conv.weights,yolo_block.2.tip.conv.weights,yolo_output.2.conv.weights" --pruned_ratios="0.3358649194844731,0.2339780010533776,0.23606618086491846,0.3391804944634715,0.6150057856781177,0.2936964621561007,0.8209326739504567,0.18784995148759304,0.9,0.9,0.6738703254350586,0.8045394570899849,0.3055661323305,0.4716109533887517,0.7525318024093136,0.5681596283579269,0.20368089132274939,0.6109348317524175,0.10189828674907515,0.21786649209581851,0.2946036283182185,0.28630456795703846,0.7498492919542514,0.7238426743122531,0.7681168823679925,0.656914613419909,0.9,0.9,0.24535839048004268,0.3030570813253197,0.12604462968399122,0.11274702913601214,0.2534227176260217,0.4190814406602485,0.2620534430087345,0.2621800083595275,0.3595636723599184,0.2902062266643235,0.317639218526475,0.3543520713222885,0.5087817938047486,0.524531815921334,0.4223076040356991,0.10074569265829028"`

**Comment by heavengate** [comment]
`configs/dcn/mymodel.yml`是基于哪个模型修改的呢

**Comment by guotongjian** [comment]
> `configs/dcn/mymodel.yml`是基于哪个模型修改的呢

yolov3增强版，没有用dropblock的那个版本
