### ISSUE TITLE
faster_rcnn_r101_fpn_1x预测数据生成和识别问题

### ISSUE THREAD

**Issue by maiben** [PaddlePaddle/PaddleDetection#237]
我使用faster_rcnn_r101_fpn_1x训练了一只物体检测模型，使用了https://github.com/PaddlePaddle/PaddleDetection/issues/165   提问中的方法对预测数据进行转换，同时也用https://github.com/PaddlePaddle/PaddleDetection/issues/205   提到的PadToStride对resize后的图片进行了处理，但是仍然遇到了报错，错误如下：

Traceback (most recent call last): File "tools/infertest.py", line 374, in <module> main() File "tools/infertest.py", line 291, in main shape,test_img, im_info, im_id= Prepocess(path,0) File "tools/infertest.py", line 147, in Prepocess test_img = NormalizeImage(test_img) File "tools/infertest.py", line 135, in NormalizeImage im -= mean ValueError: operands could not be broadcast together with shapes (750,1344,32) (1,1,3) (750,1344,32) 

能否指导下如何正确的使用PadToStride，以达到预期的效果，谢谢！
（详细问题可以看https://github.com/PaddlePaddle/PaddleDetection/issues/205     最后的提问，谢谢。）

**Comment by qingqing01** [comment]
@maiben

可以看配置里的顺序: https://github.com/PaddlePaddle/PaddleDetection/blob/master/configs/faster_fpn_reader.yml#L79

FPN模型预测是，图片处理顺序是: DecodeImage（读取图片）->NormalizeImage(减均值，除方差) -> ResizeImage （resize图片 ） -> PadToStride(做对stride整除的padding操作)

你上面错误是，是操作的顺序不对。

**Comment by maiben** [comment]
@qingqing01   好的，多谢指导。

**Comment by maiben** [comment]
@qingqing01  再请教一下，请问改变 ResizeImage中的target_size: 800对识别结果有何影响？我分别试验了target_size=640，750，800，1000，发现不同尺寸对不同图片的识别效果都不一样，请问有没有相关的参考设置标准，对于4000*3000像素左右的图片应该如何设置才能达到最好的效果？

**Comment by qingqing01** [comment]
@maiben  训练时采用`target_size: 800`，预测时尺寸相近，可能相对较好。 你改变尺寸后差异多大？ 如果想在预测时尺寸变小，也可以适当减小训练时的target_size。

**Comment by qingqing01** [comment]
@maiben 请问问题解决了吗？ 该issue可否close了？

**Comment by maiben** [comment]
@qingqing01 ok，已经解决了，谢谢。
