### ISSUE TITLE
coco格式训练集 训练的时候出现了 FatalError: Blocking queue is killed because the data reader raises an exception.

### ISSUE THREAD

**Issue by wzzwh110** [PaddlePaddle/PaddleDetection#2380]
这是我第一次使用ppdet
我在做自己的coco格式的数据集的时候出现了这个问题（训练集和验证集就2张图片）
在训练的时候
```
D:\anaconda3\envs\paddle\python.exe D:/workflow/tct_code/PaddleDetection/tools/train.py -c D:\workflow\tct_code\PaddleDetection\configs\cascade_rcnn_r50_fpn_1x.yml -o use_gpu=true --eval --use_vdl=True --vdl_log_dir=vdl_dir/scalar
2021-03-19 10:53:23,541 - INFO - If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000100] in Optimizer will not take effect, and it will only be applied to other Parameters!
D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\layers\math_op_patch.py:293: UserWarning: D:\workflow\tct_code\PaddleDetection\ppdet\modeling\roi_heads\cascade_head.py:199
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  warnings.warn(
D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\layers\math_op_patch.py:293: UserWarning: D:\workflow\tct_code\PaddleDetection\ppdet\modeling\roi_heads\cascade_head.py:206
The behavior of expression A / B has been unified with elementwise_div(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_div(X, Y, axis=0) instead of A / B. This transitional warning will be dropped in the future.
  warnings.warn(
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2021-03-19 10:53:28,055-WARNING: variable file [ C:/Users/16121/.cache/paddle/weights/ResNet50_cos_pretrained/fc_0.w_0 C:/Users/16121/.cache/paddle/weights/ResNet50_cos_pretrained/fc_0.b_0 ] not used
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
D:\workflow\tct_code\PaddleDetection\ppdet\data\reader.py:89: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  if isinstance(item, collections.Sequence) and len(item) == 0:
D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\reader.py:1288: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
  logging.warn('Your reader has raised an exception!')
2021-03-19 10:53:29,918 - WARNING - Your reader has raised an exception!
[WARNING 2021-03-19 10:53:29,918 reader.py:1288] Your reader has raised an exception!
Exception in thread Thread-9:
Traceback (most recent call last):
  File "D:\anaconda3\envs\paddle\lib\threading.py", line 932, in _bootstrap_inner
Traceback (most recent call last):
    self.run()
  File "D:\anaconda3\envs\paddle\lib\threading.py", line 870, in run
  File "D:/workflow/tct_code/PaddleDetection/tools/train.py", line 399, in <module>
    main()
  File "D:/workflow/tct_code/PaddleDetection/tools/train.py", line 270, in main
    self._target(*self._args, **self._kwargs)
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\reader.py", line 1289, in __thread_main__
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\executor.py", line 1110, in run
    six.reraise(*sys.exc_info())
  File "D:\anaconda3\envs\paddle\lib\site-packages\six.py", line 703, in reraise
    six.reraise(*sys.exc_info())
  File "D:\anaconda3\envs\paddle\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\reader.py", line 1269, in __thread_main__
    raise value
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\executor.py", line 1098, in run
    return self._run_impl(
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\executor.py", line 1244, in _run_impl
    for tensors in self._tensor_reader():
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\reader.py", line 1348, in __tensor_reader_impl__
    return self._run_parallel(
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\executor.py", line 913, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
SystemError: In user code:

    File "D:/workflow/tct_code/PaddleDetection/tools/train.py", line 399, in <module>
      main()
    File "D:/workflow/tct_code/PaddleDetection/tools/train.py", line 135, in main
      feed_vars, train_loader = model.build_inputs(**inputs_def)
    File "D:\workflow\tct_code\PaddleDetection\ppdet\modeling\architectures\cascade_rcnn.py", line 326, in build_inputs
      loader = fluid.io.DataLoader.from_generator(
    File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\reader.py", line 748, in from_generator
      return GeneratorLoader(feed_list, capacity, use_double_buffer,
    File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\reader.py", line 1119, in __init__
      self._init_non_iterable()
    File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\reader.py", line 1217, in _init_non_iterable
      default_main_program().current_block().append_op(
    File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 3017, in append_op
      op = Operator(
    File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 2107, in __init__
      for frame in traceback.extract_stack():

    FatalError: Blocking queue is killed because the data reader raises an exception.
      [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at D:\v2.0.1\paddle\paddle/fluid/operators/reader/blocking_queue.h:158)
      [operator < read > error]
    
Process finished with exit code -1073740791 (0xC0000409)
```
在coco.py下了断点是可以读入并且对应到图像路径的。麻烦了大佬帮忙看下

**Comment by wangxinxin08** [comment]
收到，正在定位问题中

**Comment by wzzwh110** [comment]
好的需要提供其他文件吗？

> 收到，正在定位问题中

能提供下图片和coco的json文件吗？我们好做复现，另外，贴一下paddle 和paddledetection的版本

**Comment by wzzwh110** [comment]
> 好的需要提供其他文件吗？
> 
> > 收到，正在定位问题中
> 
> 能提供下图片和coco的json文件吗？我们好做复现，另外，贴一下paddle和paddledetection的版本

我写成单行的了，图片截图不好看，我转成txt传上来。
[val2017.txt](https://github.com/PaddlePaddle/PaddleDetection/files/6168906/val2017.txt)
另外，我是在windows下进行的，paddle的版本是2.0.1，ppdet的版本是昨天直接git clone的 应该是2.0-rc

**Comment by wzzwh110** [comment]
> 好的需要提供其他文件吗？
> 
> > 收到，正在定位问题中
> 
> 能提供下图片和coco的json文件吗？我们好做复现，另外，贴一下paddle 和paddledetection的版本

我写成单行的了，图片截图不好看，我转成txt传上来。
[val2017.txt](https://github.com/PaddlePaddle/PaddleDetection/files/6168939/val2017.txt)

另外，我是在windows下进行的，paddle的版本是2.0.1，ppdet的版本是昨天直接git clone的 应该是2.0-rc

**Comment by wangxinxin08** [comment]
定位发现是由于你的image_id过大，超出了int64的表示范围，导致溢出，建议你修改json文件的image_id

**Comment by wzzwh110** [comment]
> 定位发现是由于你的image_id过大，超过了int64的表示范围，导致重叠，建议您修改json文件的image_id


> 定位发现是由于你的image_id过大，超过了int64的表示范围，导致重叠，建议您修改json文件的image_id

谢谢 已解决
