### ISSUE TITLE
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

### ISSUE THREAD

**Issue by zxsitu** [PaddlePaddle/PaddleDetection#2393]
您好，我按照教程
首先配置了环境：`python -m pip install paddlepaddle-gpu==2.0.1 -i https://mirror.baidu.com/pypi/simple`
然后使用labelme制作图片，然后使用x2coco.py顺利转成coco格式。`python ./tools/x2coco.py --dataset_type labelme --json_input_dir ../sewer-defects-10/labels --image_input_dir ../sewer-defects-10/images  --output_dir ./dataset/sewer-defects/ --train_proportion 0.8 --val_proportion 0.2 --test_proportion 0.0`
接着修改`faster_rcnn_r50_fpn_1x.ym`和`faster_fpn_reader`，两个文件。然后开始训练：`python tools/train.py -c configs/faster_rcnn_r50_fpn_1x.yml --use_vdl=true --vdl_log_dir=vdl_dir/scalar --eval`
然后就报错了，请问怎么解决呢？感谢。

```
python tools/train.py -c configs/faster_rcnn_r50_fpn_1x.yml --use_vdl=true --vdl_log_dir=vdl_dir/scalar --eval
D:\Anaconda3\envs\pytorch1.6\lib\site-packages\win32\lib\pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for al
ternative uses
  import imp, sys, os
2021-03-20 17:15:36,182 - INFO - If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coef
f=0.000100] in Optimizer will not take effect, and it will only be applied to other Parameters!
D:\Anaconda3\envs\pytorch1.6\lib\site-packages\paddle\fluid\layers\math_op_patch.py:293: UserWarning: F:\PycharmProjects\pythonProject4\PaddleDetection\ppdet\modeling\roi_heads\bbox_he
ad.py:315
The behavior of expression A / B has been unified with elementwise_div(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to
 use elementwise_div(X, Y, axis=0) instead of A / B. This transitional warning will be dropped in the future.
  warnings.warn(
Traceback (most recent call last):
  File "tools/train.py", line 399, in <module>
    main()
  File "tools/train.py", line 167, in main
    eval_reader = create_reader(cfg.EvalReader, devices_num=1)
  File "F:\PycharmProjects\pythonProject4\PaddleDetection\ppdet\data\reader.py", line 442, in create_reader
    reader = Reader(**cfg)()
  File "F:\PycharmProjects\pythonProject4\PaddleDetection\ppdet\data\reader.py", line 210, in __init__
    self._roidbs = self._dataset.get_roidb()
  File "F:\PycharmProjects\pythonProject4\PaddleDetection\ppdet\data\source\dataset.py", line 68, in get_roidb
    self.load_roidb_and_cname2cid()
  File "F:\PycharmProjects\pythonProject4\PaddleDetection\ppdet\data\source\coco.py", line 80, in load_roidb_and_cname2cid
    from pycocotools.coco import COCO
  File "D:\Anaconda3\envs\pytorch1.6\lib\site-packages\pycocotools\coco.py", line 56, in <module>
    from . import mask as maskUtils
  File "D:\Anaconda3\envs\pytorch1.6\lib\site-packages\pycocotools\mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools\_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

**Comment by zxsitu** [comment]
已解决，安装最新版numpy，不能完全参考requirement的安装。
