### ISSUE TITLE
预测报错 KeyError: 1

### ISSUE THREAD

**Issue by akingyin1987** [PaddlePaddle/PaddleDetection#2418]
E:\Development\StudioApp\PaddleDetection>python tools/infer.py -c configs/yolov3
_mobilenet_v1_roadsign.yml --infer_img=demo/123.jpg -o use_gpu=false
config.metric=VOC
2021-03-24 16:15:27,514 - INFO - Load categories from dataset/water_meter_voc/la
bel_list.txt
2021-03-24 16:15:28,684 - INFO - Infer iter 0
Traceback (most recent call last):
  File "tools/infer.py", line 272, in <module>
    main()
  File "tools/infer.py", line 195, in main
    bbox_results = bbox2out([res], clsid2catid, is_bbox_normalized)
  File "E:\Development\StudioApp\PaddleDetection\ppdet\utils\coco_eval.py", line
 315, in bbox2out
    catid = (clsid2catid[int(clsid)])
KeyError: 1

**Comment by liuhuiCNN** [comment]
（1）config.metric=VOC 这个参数在infer.py中并不起作用，您去掉这个设置试试呢？如果您想测试mAP，请使用 tools/eval.py。
按照日志，` Load categories from dataset/water_meter_voc/label_list.txt`，说明类别已经加载正确了。
（1）请问您使用的paddle版本，paddledetection版本是多少呢？
（2）我测试了paddle2.0.1 PaddleDetection develop分支，`python tools/infer.py -c configs/yolov3/yolov3_mobilenet_v1_270e_voc.yml -o weights=../yolov3_mobilenet_v1_270e_coco.pdparams --infer_img=demo/000000087038.jpg`是正常的。

**Comment by akingyin1987** [comment]
config.metric=VOC 这是我改原码打印的信息，就是觉得很奇怪，怎么报错的地方最后有显示 在 coco_eval.py,paddledetection 是前几天才clone 下来的 V2.0.0-rc0    ，我完全的新手
