### ISSUE TITLE
aistudio评估retinanet_r50_fpn_1x的checkpoint报错

### ISSUE THREAD

**Issue by abc1035** [PaddlePaddle/PaddleDetection#2448]
我在aistudio用retinanet_r50_fpn_1x训练模型后使用eval.py评估模型生成的checkpoint，结果报错，版本是PaddleDetection-release-2.0-rc，yml配置文件我只修改了lr和数据集路径
Traceback (most recent call last):
  File "tools/eval.py", line 193, in <module>
    main()
  File "tools/eval.py", line 160, in main
    sub_eval_prog, sub_keys, sub_values, resolution)
  File "/home/aistudio/work/PaddleDetection1/ppdet/utils/eval_utils.py", line 148, in eval_run
    return_numpy=False)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1110, in run
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1108, in run
    return_merged=return_merged)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1251, in _run_impl
    return_merged=return_merged)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 913, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
RuntimeError: (PreconditionNotMet) Tensor not initialized yet when Tensor::place() is called.
  [Hint: holder_ should not be null.] (at /paddle/paddle/fluid/framework/tensor.h:194)

terminate called without an active exception

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1616826130 (unix time) try "date -d @1616826130" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e800000846) received by PID 2118 (TID 0x7fb6037fe700) from PID 2118 ***]

Aborted (core dumped)

**Comment by heavengate** [comment]
你好，请问你Paddle用的哪个版本呢

**Comment by abc1035** [comment]
使用的是paddlepaddle2.0.1,python3.7，用PaddleDetection-release-2.0-beta训练的模型，但用rc和beta评估都报上面同样的错误
