### ISSUE TITLE
InvalidArgumentError: The input's size along the split dimension must be evenly divisible by Attr(num_or_sections). But received Attr(num_or_sections) = 8, input(X)'s shape = [12, 30, 4], Attr(dim) = 0.

### ISSUE THREAD

**Issue by dhao-island** [PaddlePaddle/PaddleDetection#2507]
整体报错日志：
2021-04-03 15:05:29,054 - WARNING - variable yolo_output.0.conv.1.weights not used
2021-04-03 15:05:29,054 - WARNING - variable yolo_output.2.conv.1.bias not used
2021-04-03 15:05:29,054 - WARNING - variable yolo_output.1.conv.1.bias not used
2021-04-03 15:05:29,054 - WARNING - variable yolo_output.0.conv.1.bias not used
2021-04-03 15:05:29,054 - WARNING - variable yolo_output.1.conv.1.weights not used
2021-04-03 15:05:29,054 - WARNING - variable yolo_output.2.conv.1.weights not used
2021-04-03 15:05:35,331 - INFO - places would be ommited when DataLoader is not iterable
Traceback (most recent call last):
  File "PaddleDetection/tools/train.py", line 374, in <module>
    main()
  File "PaddleDetection/tools/train.py", line 247, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1110, in run
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1108, in run
    return_merged=return_merged)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1251, in _run_impl
    return_merged=return_merged)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 913, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
ValueError: In user code:

    File "PaddleDetection/tools/train.py", line 374, in <module>
      main()
    File "PaddleDetection/tools/train.py", line 120, in main
      train_fetches = model.train(feed_vars)
    File "/home/aistudio/work/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 159, in train
      return self.build(feed_vars, mode='train')
    File "/home/aistudio/work/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 85, in build
      gt_score, targets)
    File "/home/aistudio/work/PaddleDetection/ppdet/modeling/anchor_heads/yolo_head.py", line 401, in get_loss
      self.prefix_name)
    File "/home/aistudio/work/PaddleDetection/ppdet/modeling/losses/yolo_loss.py", line 69, in __call__
      mask_anchors, self._ignore_thresh)
    File "/home/aistudio/work/PaddleDetection/ppdet/modeling/losses/yolo_loss.py", line 191, in _get_fine_grained_loss
      num_classes, downsample, self._ignore_thresh, scale_x_y)
    File "/home/aistudio/work/PaddleDetection/ppdet/modeling/losses/yolo_loss.py", line 322, in _calc_obj_loss
      gts = fluid.layers.split(gt_box, batch_size, dim=0)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 4944, in split
      type='split', inputs=inputs, outputs={'Out': outs}, attrs=attrs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3023, in append_op
      attrs=kwargs.get("attrs", None))
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2107, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The input's size along the split dimension must be evenly divisible by Attr(num_or_sections). But received Attr(num_or_sections) = 8, input(X)'s shape = [12, 30, 4], Attr(dim) = 0.
      [Hint: Expected input_axis_dim % num == 0, but received input_axis_dim % num:4 != 0:0.] (at /paddle/paddle/fluid/operators/split_op.h:43)
      [operator < split > error]

配置：
paddle2.0 gpu，paddledetection release/0.4    

感觉是维度问题，但又不知道咋改，向百度大佬请教

**Comment by dhao-island** [comment]
这是yolov4_cspdarknet_voc.yml的配置文件（训练自己的数据，改了一些配置）
architecture: YOLOv4
use_gpu: true
max_iters: 50000
log_smooth_window: 20
save_dir: output
snapshot_iter: 1000
metric: VOC
pretrain_weights: https://paddlemodels.bj.bcebos.com/object_detection/yolov4_cspdarknet.pdparams
weights: output/yolov4_cspdarknet_voc/model_final
num_classes: 1
use_fine_grained_loss: true

YOLOv4:
  backbone: CSPDarkNet
  yolo_head: YOLOv4Head

CSPDarkNet:
  norm_type: sync_bn
  norm_decay: 0.
  depth: 53

YOLOv4Head:
  anchors: [[12, 16], [19, 36], [40, 28], [36, 75], [76, 55],
            [72, 146], [142, 110], [192, 243], [459, 401]]
  anchor_masks: [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
  nms:
    background_label: -1
    keep_top_k: -1
    nms_threshold: 0.45
    nms_top_k: -1
    normalized: true
    score_threshold: 0.001
  downsample: [8,16,32]
  scale_x_y: [1.2, 1.1, 1.05]

YOLOv3Loss:
  ignore_thresh: 0.7
  label_smooth: true
  downsample: [8,16,32]
  scale_x_y: [1.2, 1.1, 1.05]
  iou_loss: IouLoss
  match_score: true

IouLoss:
  loss_weight: 0.07
  max_height: 608
  max_width: 608
  ciou_term: true
  loss_square: true

LearningRate:
  base_lr: 0.0002
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 40000
    - 50000
  - !LinearWarmup
    start_factor: 0.
    steps: 1000

OptimizerBuilder:
  clip_grad_by_norm: 10.
  optimizer:
    momentum: 0.949
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

_READER_: '../yolov3_reader.yml'
TrainReader:
  inputs_def:
    fields: ['image', 'gt_bbox', 'gt_class', 'gt_score', 'im_id']
    num_max_boxes: 30
  dataset:
    !VOCDataSet
      dataset_dir: PaddleDetection/dataset/mydata_fire
      anno_path: ImageSets/train.txt
      image_dir: ImageSets
      label_list: ImageSets/label_list.txt
      use_default_label: false
      with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !ColorDistort {}
    - !RandomExpand
      fill_value: [123.675, 116.28, 103.53]
    - !RandomCrop {}
    - !RandomFlipImage
      is_normalized: false
    - !NormalizeBox {}
    - !PadBox
      num_max_boxes: 30
    - !BboxXYXY2XYWH {}
  batch_transforms:
  - !RandomShape
    sizes: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608]
    random_inter: True
  - !NormalizeImage
    mean: [0.,0.,0.]
    std: [1.,1.,1.]
    is_scale: True
    is_channel_first: false
  - !Permute
    to_bgr: false
    channel_first: True
  # Gt2YoloTarget is only used when use_fine_grained_loss set as true,
  # this operator will be deleted automatically if use_fine_grained_loss
  # is set as false
  - !Gt2YoloTarget
    anchor_masks: [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
    anchors: [[12, 16], [19, 36], [40, 28],
              [36, 75], [76, 55], [72, 146],
              [142, 110], [192, 243], [459, 401]]
    downsample_ratios: [8, 16, 32]
  batch_size: 12
  shuffle: true
  drop_last: true
  worker_num: 8
  bufsize: 16
  use_process: true
  drop_empty: false

EvalReader:
  inputs_def:
    fields: ['image', 'im_size', 'im_id', 'gt_bbox', 'gt_class', 'is_difficult']
    num_max_boxes: 30
  dataset:
    !VOCDataSet
      dataset_dir: PaddleDetection/dataset/mydata_fire
      anno_path: ImageSets/val.txt
      image_dir: ImageSets
      label_list: ImageSets/label_list.txt
      use_default_label: false
      with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !ResizeImage
      target_size: 608
      interp: 1
    - !NormalizeImage
      mean: [0., 0., 0.]
      std: [1., 1., 1.]
      is_scale: True
      is_channel_first: false
    - !PadBox
      num_max_boxes: 30
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 12
  drop_empty: false
  worker_num: 8
  bufsize: 16

TestReader:
  dataset:
    !ImageFolder
      with_background: false
      use_default_label: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !ResizeImage
      target_size: 608
      interp: 1
    - !NormalizeImage
      mean: [0., 0., 0.]
      std: [1., 1., 1.]
      is_scale: True
      is_channel_first: false
    - !Permute
      to_bgr: false
      channel_first: True

**Comment by jerrywgz** [comment]
You need to set train_batch_size in YOLOv3Loss or you could update the code in PaddleDetection release/0.4

**Comment by dinghao19960829** [comment]
> You need to set train_batch_size in YOLOv3Loss or you could update the code in PaddleDetection release/0.4

I try to update the code in PaddleDetection release/0.4(update train.py and yolov4_cspdarknet_voc.yml), but the problem still exist.  Setting train_batch_size in YOLOv3Loss shows a unexpected param.

**Comment by dhao-island** [comment]
> You need to set train_batch_size in YOLOv3Loss or you could update the code in PaddleDetection release/0.4

InvalidArgumentError: The input's size along the split dimension must be evenly divisible by Attr(num_or_sections). But received Attr(num_or_sections) = 16, input(X)'s shape = [12, 30, 4], Attr(dim) = 0.
hello！ this is my error info , which number should I set to match the input's shape, and how to understand that ?
