### ISSUE TITLE
部署Serving服务时，测试报错

### ISSUE THREAD

**Issue by thugbobby** [PaddlePaddle/PaddleDetection#2510]
在部署在线Serving服务时，执行到最后一步报错，执行指令为：
`python ../../deploy/serving/test_client.py ../../demo/1.png
`
报错信息为：
```
Traceback (most recent call last):
  File "../../deploy/serving/test_client.py", line 27, in <module>
    client = Client()
  File "/Users/wispig/opt/anaconda3/envs/paddle-env/lib/python3.7/site-packages/paddle_serving_client/__init__.py", line 139, in __init__
    from .serving_client import PredictorRes
ImportError: dlopen(/Users/wispig/opt/anaconda3/envs/paddle-env/lib/python3.7/site-packages/paddle_serving_client/serving_client.so, 2): no suitable image found.  Did find:
	/Users/wispig/opt/anaconda3/envs/paddle-env/lib/python3.7/site-packages/paddle_serving_client/serving_client.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
	/Users/wispig/opt/anaconda3/envs/paddle-env/lib/python3.7/site-packages/paddle_serving_client/serving_client.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
```
请问如何解决

**Comment by liuhuiCNN** [comment]
您用的paddleserving版本是多呢？
根据提示，应该是读图是发生错误，有尝试 jpg 格式的图片吗？图片文件是否有损？

**Comment by thugbobby** [comment]
> 您用的paddleserving版本是多呢？
> 根据提示，应该是读图是发生错误，有尝试 jpg 格式的图片吗？图片文件是否有损？

paddleserving版本0.5的，图片文件应该不会有损 换了几张图片都是 都是之前训练的图片

**Comment by liuhuiCNN** [comment]
> > 您用的paddleserving版本是多呢？
> > 根据提示，应该是读图是发生错误，有尝试 jpg 格式的图片吗？图片文件是否有损？
> 
> paddleserving版本0.5的，图片文件应该不会有损 换了几张图片都是 都是之前训练的图片

都是png格式照片吗？使用的opencv版本是否支持读取png格式图片呢？
