### ISSUE TITLE
训练提示预训练模型不存在

### ISSUE THREAD

**Issue by dmxj** [PaddlePaddle/PaddleDetection#252]
faster-rcnn-r50模型训练，报错提示预训练模型地址不存在，使用的最新的master版本进行的训练。
基础训练参数：

> architecture: FasterRCNN
log_iter: 50
log_smooth_window: 50
max_iters: 20000
max_size: 1333
metric: COCO
num_classes: 3
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_vd_pretrained.tar
save_dir: output
snapshot_iter: 400
target_size: 800
use_gpu: true
weights: ''
FasterRCNN:
  backbone: ResNet
  bbox_assigner: BBoxAssigner
  bbox_head: BBoxHead
  fpn: FPN
  roi_extractor: FPNRoIAlign
  rpn_head: FPNRPNHead
ResNet:
  dcn_v2_stages:[3,4,5]
  depth: 50
  gcb_stages: []
  norm_type: affine_channel
  variant: b

报错信息：

> max_size: 1333
metric: COCO
num_classes: 3
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_vd_pretrained.tar
save_dir: output
snapshot_iter: 400
target_size: 800
use_gpu: true
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2020-02-22 01:39:44,809-INFO: 71 samples in file /root/datasets/jingyan/dibu/coco/annotations/val.json
2020-02-22 01:39:44,809-INFO: places would be ommited when DataLoader is not iterable
W0222 01:39:46.168161 46917 device_context.cc:236] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 9.2, Runtime API Version: 9.0
W0222 01:39:46.171754 46917 device_context.cc:244] device: 0, cuDNN Version: 7.4.
2020-02-22 01:39:47,616-INFO: Load model and fuse batch norm if have from https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_vd_pretrained.tar...
2020-02-22 01:39:47,616-INFO: Found /root/.cache/paddle/weights/ResNet50_vd_pretrained
2020-02-22 01:39:47,621-INFO: Loading parameters from /root/.cache/paddle/weights/ResNet50_vd_pretrained...
Traceback (most recent call last):
  File "/root/opensource/PaddleDetection/tools/train.py", line 323, in <module>
    main()
  File "/root/opensource/PaddleDetection/tools/train.py", line 191, in main
    checkpoint.load_and_fusebn(exe, train_prog, cfg.pretrain_weights)
  File "/root/opensource/PaddleDetection/ppdet/utils/checkpoint.py", line 275, in load_and_fusebn
    load_params(exe, prog, path)
  File "/root/opensource/PaddleDetection/ppdet/utils/checkpoint.py", line 125, in load_params
    fluid.load(prog, path, executor=exe)
  File "/opt/conda/lib/python3.6/site-packages/paddle/fluid/io.py", line 1577, in load
    "Parameter file [{}] not exits".format(parameter_file_name)
AssertionError: Parameter file [/root/.cache/paddle/weights/ResNet50_vd_pretrained.pdparams] not exits

paddlepaddle-gpu版本为1.6.2.post97，操作系统为ubuntu，前几天还是可以正常训练的，今天就报了这个错

**Comment by liym27** [comment]
> 前几天还是可以正常训练的，今天就报了这个错
请问 前几天训练的PaddleDetection版本与今天一致吗？

**Comment by dmxj** [comment]
> > 前几天还是可以正常训练的，今天就报了这个错
> > 请问 前几天训练的PaddleDetection版本与今天一致吗？

一致的，前几天master和v0.1.0版本都可以正常训练，后来应该是pull过最新的master，目前本地是最新的master，但无法训练，尝试过其他的模型（yolo SSD等）也都报了同样的错。不过v0.1.0是可以正常训练的

**Comment by liym27** [comment]
好的，感谢反馈。请问您是否对模型做相关改动？以及呢能否提供您的训练环境？

**Comment by dmxj** [comment]
> 好的，感谢反馈。请问您是否对模型做相关改动？以及呢能否提供您的训练环境？

未做过改动，已经拉下最新版本，和线上是一致的。

**训练环境：
Python 3.6.3
paddlepaddle-gpu 1.6.2.post97
操作系统 Ubuntu 16.04.5 LTS (docker容器)
显卡 Tesla V100(单卡)
CPU个数 8**

**Comment by qingqing01** [comment]
@dmxj    错误是master分支升级即将发布的1.7相关接口导致的。可以先reset回退下版本。 git reset 59b704957426a2e87148c64d0bbef7154224afae

**Comment by dmxj** [comment]
> @dmxj 错误是master分支升级即将发布的1.7相关接口导致的。可以先reset回退下版本。 git reset [59b7049](https://github.com/PaddlePaddle/PaddleDetection/commit/59b704957426a2e87148c64d0bbef7154224afae)

好的，麻烦请问下一个发布的版本不是0.2.0吗？0.2.0预计什么时候release出来呢？

**Comment by qingqing01** [comment]
@dmxj 下个版本是0.2.0，等PaddlePaddle的whl包发布，会release。预计这周。

**Comment by TianyouChen** [comment]
python3 slim/quantization/train.py --not_quant_pattern slim_output --eval --c ./configs/ssd/ssd_mobilenet_v1_voc.yml -o max_iters=30000 save_dir=./output/mobilenetv1_slim LearningRate.base_lr=0.0001 LearningRate.schedulers="[!PiecewiseDecay {gamma: 0.1, milestones: [10000]}]" pretrain_weights=https://paddlemodels.bj.bcebos.com/object_detection/ssd_mobilenet_v1_voc.tar
进行量化训练时出现
AssertionError: Parameter file [/home/chenchaocun/.cache/paddle/weights/ssd_mobilenet_v1_voc.pdparams] not exits错误，
官方下载的预训练模型不是.pdparams后缀的文件，这个怎么解决？

**Comment by willthefrog** [comment]
无法复现，请确认下 /home/chenchaocun/.cache/paddle/weights/ssd_mobilenet_v1_voc 是否是正常文件夹？ 如果文件夹正常请提供详细版本及报错信息。 @TianyouChen

**Comment by willthefrog** [comment]
> @dmxj 错误是master分支升级即将发布的1.7相关接口导致的。可以先reset回退下版本。 git reset [59b7049](https://github.com/PaddlePaddle/PaddleDetection/commit/59b704957426a2e87148c64d0bbef7154224afae)

也可以参考这个回滚下。

**Comment by TianyouChen** [comment]
> 无法复现，检测库的实现是支持文件夹及单个文件格式的，参见[这里](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/ppdet/utils/checkpoint.py#L123)
> 请确认下 /home/chenchaocun/.cache/paddle/weights/ssd_mobilenet_v1_voc 是否是文件夹并且可以正常读取（检查读取权限）？ 如果是文件夹且可以正常读取，请提供详细版本及报错信息。 @TianyouChen

确认文件夹和文件权限没问题，模型是在https://paddlemodels.bj.bcebos.com/object_detection/ssd_mobilenet_v1_voc.tar上下载解压的。
一下是详细信息######
paddledetection 版本：
release/0.2
运行指令：
python3 slim/quantization/train.py --not_quant_pattern slim_output --eval --c ./configs/ssd/ssd_mobilenet_v1_voc.yml -o max_iters=30000 save_dir=./output/mobilenetv1_slim LearningRate.base_lr=0.0001 LearningRate.schedulers="[!PiecewiseDecay {gamma: 0.1, milestones: [10000]}]" pretrain_weights=https://paddlemodels.bj.bcebos.com/object_detection/ssd_mobilenet_v1_voc.tar

得到结果：
Traceback (most recent call last):
File "slim/quantization/train.py", line 314, in 
main()
File "slim/quantization/train.py", line 193, in main
ignore_params=ignore_params)
File "/home/chenchaocun/PaddleDetection_slim_branch/slim/quantization/ppdet/utils/checkpoint.py", line 125, in load_params
fluid.load(prog, path, executor=exe)
File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/io.py", line 1577, in load
"Parameter file [{}] not exits".format(parameter_file_name)
AssertionError: Parameter file

硬件配置：
CPU 8
RAM 32GB
GPU v100
显存 16GB
磁盘 1TB

**Comment by TianyouChen** [comment]
> > 无法复现，检测库的实现是支持文件夹及单个文件格式的，参见[这里](https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/ppdet/utils/checkpoint.py#L123)
> > 请确认下 /home/chenchaocun/.cache/paddle/weights/ssd_mobilenet_v1_voc 是否是文件夹并且可以正常读取（检查读取权限）？ 如果是文件夹且可以正常读取，请提供详细版本及报错信息。 @TianyouChen
> 
> 确认文件夹和文件权限没问题，模型是在[https://paddlemodels.bj.bcebos.com/object_detection/ssd_mobilenet_v1_voc.tar上下载解压的。](https://paddlemodels.bj.bcebos.com/object_detection/ssd_mobilenet_v1_voc.tar%E4%B8%8A%E4%B8%8B%E8%BD%BD%E8%A7%A3%E5%8E%8B%E7%9A%84%E3%80%82)
> 一下是详细信息######
> paddledetection 版本：
> release/0.2
> 运行指令：
> python3 slim/quantization/train.py --not_quant_pattern slim_output --eval --c ./configs/ssd/ssd_mobilenet_v1_voc.yml -o max_iters=30000 save_dir=./output/mobilenetv1_slim LearningRate.base_lr=0.0001 LearningRate.schedulers="[!PiecewiseDecay {gamma: 0.1, milestones: [10000]}]" pretrain_weights=https://paddlemodels.bj.bcebos.com/object_detection/ssd_mobilenet_v1_voc.tar
> 
> 得到结果：
> Traceback (most recent call last):
> File "slim/quantization/train.py", line 314, in
> main()
> File "slim/quantization/train.py", line 193, in main
> ignore_params=ignore_params)
> File "/home/chenchaocun/PaddleDetection_slim_branch/slim/quantization/ppdet/utils/checkpoint.py", line 125, in load_params
> fluid.load(prog, path, executor=exe)
> File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/io.py", line 1577, in load
> "Parameter file [{}] not exits".format(parameter_file_name)
> AssertionError: Parameter file
> 
> 硬件配置：
> CPU 8
> RAM 32GB
> GPU v100
> 显存 16GB
> 磁盘 1TB
@willthefrog

**Comment by willthefrog** [comment]
检测库的代码分支路径应该是对的，执行的是加载文件夹的逻辑，感觉是paddle版本问题，确定用的是1.7版？ @TianyouChen

**Comment by TianyouChen** [comment]
> 检测库的代码分支路径应该是对的，执行的是加载文件夹的逻辑，感觉是paddle版本问题，确定用的是1.7版？ 报错的[代码位置](https://github.com/PaddlePaddle/Paddle/blob/release/1.7/python/paddle/fluid/io.py#L1577)对不上啊。 @TianyouChen
我的paddle版本是1.6.1 文档不是说大于等于1.6就可以吗，我试一下1.7吧那？

**Comment by TianyouChen** [comment]
> 检测库的代码分支路径应该是对的，执行的是加载文件夹的逻辑，感觉是paddle版本问题，确定用的是1.7版？ 报错的[代码位置](https://github.com/PaddlePaddle/Paddle/blob/release/1.7/python/paddle/fluid/io.py#L1577)对不上啊。 @TianyouChen
> 我的paddle版本是1.6.1 文档不是说大于等于1.6就可以吗，我试一下1.7吧那？

@willthefrog

**Comment by willthefrog** [comment]
0.2的API已升级到paddle 1.7，存在一定的不兼容，升级paddle版本或回滚PaddleDetection都可以。

**Comment by TianyouChen** [comment]
> 0.2的API已升级到paddle 1.7，存在一定的不兼容，升级paddle版本或回滚PaddleDetection都可以。
我装了paddle1.7版本，又重新拉了最新的PaddleDetection （release/0.2）代码，一样的指令跑，之前的提示没有了，但是又出现如下报错信息：
2020-03-02 17:14:04,367-INFO: 4952 samples in file dataset/voc/test.txt
2020-03-02 17:14:04,368-INFO: places would be ommited when DataLoader is not iterable
W0302 17:14:05.122560 16661 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 9.0
W0302 17:14:05.126299 16661 device_context.cc:245] device: 0, cuDNN Version: 7.6.
2020-03-02 17:14:06,675-INFO: Found /home/chenchaocun/.cache/paddle/weights/ssd_mobilenet_v1_voc
2020-03-02 17:14:06,675-INFO: Loading parameters from /home/chenchaocun/.cache/paddle/weights/ssd_mobilenet_v1_voc...
2020-03-02 17:14:06,675-WARNING: /home/chenchaocun/.cache/paddle/weights/ssd_mobilenet_v1_voc.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-03-02 17:14:06,675-WARNING: /home/chenchaocun/.cache/paddle/weights/ssd_mobilenet_v1_voc.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
Traceback (most recent call last):
  File "slim/quantization/train.py", line 314, in <module>
    main()
  File "slim/quantization/train.py", line 195, in main
    train_prog_quant = quant_aware(train_prog, place, config, for_test=False)
  File "/usr/local/lib/python3.5/dist-packages/paddleslim/quant/quanter.py", line 131, in quant_aware
    config = _parse_configs(config)
  File "/usr/local/lib/python3.5/dist-packages/paddleslim/quant/quanter.py", line 105, in _parse_configs
    assert isinstance(configs['quant_weight_only'], bool), \
KeyError: 'quant_weight_only'
麻烦帮我看看这是啥问题 @willthefrog

**Comment by willthefrog** [comment]
配置文件问题？ 缺少`quant_weight_only`键值？ 建议另起个issue吧。这是另外的错误了。

**Comment by willthefrog** [comment]
@dmxj  如果问题已经解决了，麻烦close下这个issue，谢谢。

**Comment by TianyouChen** [comment]
我装了paddle1.7版本，又重新拉了最新的PaddleDetection （release/0.2）代码，一样的指令跑，之前的提示没有了，但是又出现如下报错信息：
2020-03-02 17:14:04,367-INFO: 4952 samples in file dataset/voc/test.txt
2020-03-02 17:14:04,368-INFO: places would be ommited when DataLoader is not iterable
W0302 17:14:05.122560 16661 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 9.0
W0302 17:14:05.126299 16661 device_context.cc:245] device: 0, cuDNN Version: 7.6.
2020-03-02 17:14:06,675-INFO: Found /home/chenchaocun/.cache/paddle/weights/ssd_mobilenet_v1_voc
2020-03-02 17:14:06,675-INFO: Loading parameters from /home/chenchaocun/.cache/paddle/weights/ssd_mobilenet_v1_voc...
2020-03-02 17:14:06,675-WARNING: /home/chenchaocun/.cache/paddle/weights/ssd_mobilenet_v1_voc.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-03-02 17:14:06,675-WARNING: /home/chenchaocun/.cache/paddle/weights/ssd_mobilenet_v1_voc.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
Traceback (most recent call last):
File "slim/quantization/train.py", line 314, in 
main()
File "slim/quantization/train.py", line 195, in main
train_prog_quant = quant_aware(train_prog, place, config, for_test=False)
File "/usr/local/lib/python3.5/dist-packages/paddleslim/quant/quanter.py", line 131, in quant_aware
config = _parse_configs(config)
File "/usr/local/lib/python3.5/dist-packages/paddleslim/quant/quanter.py", line 105, in _parse_configs
assert isinstance(configs['quant_weight_only'], bool), 
KeyError: 'quant_weight_only'
 这个键值在哪里配置的？我是在/usr/local/lib/python3.5/dist-packages/paddleslim/quant/quanter.py的_quant_config_default（line 34 ）参数里加了了一行 'quant_weight_only'：'True'，出现如下报错，看错误应该还是一样的问题：
2020-03-02 18:32:36,324-INFO: 4952 samples in file dataset/voc/test.txt
2020-03-02 18:32:36,325-INFO: places would be ommited when DataLoader is not iterable
W0302 18:32:37.145490 25355 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 9.0
W0302 18:32:37.149606 25355 device_context.cc:245] device: 0, cuDNN Version: 7.6.
2020-03-02 18:32:38,862-INFO: Found /home/chenchaocun/.cache/paddle/weights/ssd_mobilenet_v1_voc
2020-03-02 18:32:38,863-INFO: Loading parameters from /home/chenchaocun/.cache/paddle/weights/ssd_mobilenet_v1_voc...
2020-03-02 18:32:38,863-WARNING: /home/chenchaocun/.cache/paddle/weights/ssd_mobilenet_v1_voc.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-03-02 18:32:38,863-WARNING: /home/chenchaocun/.cache/paddle/weights/ssd_mobilenet_v1_voc.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
Traceback (most recent call last):
  File "slim/quantization/train.py", line 314, in <module>
    main()
  File "slim/quantization/train.py", line 195, in main
    train_prog_quant = quant_aware(train_prog, place, config, for_test=False)
  File "/usr/local/lib/python3.5/dist-packages/paddleslim/quant/quanter.py", line 132, in quant_aware
    config = _parse_configs(config)
  File "/usr/local/lib/python3.5/dist-packages/paddleslim/quant/quanter.py", line 107, in _parse_configs
    "quant_weight_only must be bool value, if set quant_weight_only True, " \
AssertionError: quant_weight_only must be bool value, if set quant_weight_only True, then only quantize parameters of layers which need to be quantized,  and activations will not be quantized.
@willthefrog

**Comment by qingqing01** [comment]
@TianyouChen 如果还有问题，建议开一个issue。先关闭此issue。

**Comment by lowyes** [comment]
ppdet.utils.checkpoint INFO: ['last_conv.weight'] in pretrained weight is not used in the model, and its will not be loaded
