### ISSUE TITLE
裁剪出错：使用PaddleDetection下slim里的裁剪出现问题

### ISSUE THREAD

**Issue by GZHUZhao** [PaddlePaddle/PaddleDetection#2525]
执行命令：（jupyter notebook）
!python slim/prune/prune.py \
-c ./configs/ssd/ssd_mobilenet_v1_voc.yml \
--pruned_params "conv1_weights" \
--pruned_ratios="0.2"

报错：
C:\Users\Administrator\.conda\envs\paddle_gpu_2\lib\site-packages\paddle\fluid\layers\math_op_patch.py:298: UserWarning: C:\Users\Administrator\.conda\envs\paddle_gpu_2\lib\site-packages\paddle\fluid\layers\detection.py:1751
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
2021-04-06 13:29:54,175-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000050] in Optimizer will not take effect, and it will only be applied to other Parameters!
2021-04-06 13:30:19,093-INFO: pruned params: ['conv7_2_extra1_weights']
2021-04-06 13:30:19,094-INFO: pruned ratios: [0.2]
2021-04-06 13:30:19,354-INFO: pruning: conv7_2_extra1_weights
C:\Users\Administrator\.conda\envs\paddle_gpu_2\lib\site-packages\paddleslim\prune\prune_walker.py:96: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  _logger.warn("Skip operator [{}]".format(op.type()))
2021-04-06 13:30:21,463-WARNING: Skip operator [conditional_block]
2021-04-06 13:30:21,463-WARNING: Skip operator [conditional_block]
2021-04-06 13:30:21,463-WARNING: Skip operator [conditional_block]
2021-04-06 13:30:21,463-WARNING: Skip operator [conditional_block]
2021-04-06 13:30:21,463-WARNING: Skip operator [conditional_block]
Traceback (most recent call last):
  File "slim/prune/prune.py", line 415, in <module>
    main()
  File "slim/prune/prune.py", line 199, in main
    only_graph=False)[0]
  File "C:\Users\Administrator\.conda\envs\paddle_gpu_2\lib\site-packages\paddleslim\prune\pruner.py", line 102, in prune
    visited)[0]  # [(name, axis, pruned_idx)]
  File "C:\Users\Administrator\.conda\envs\paddle_gpu_2\lib\site-packages\paddleslim\prune\group_param.py", line 87, in collect_convs
    walker.prune(param, pruned_axis=0, pruned_idx=[])
  File "C:\Users\Administrator\.conda\envs\paddle_gpu_2\lib\site-packages\paddleslim\prune\prune_walker.py", line 60, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "C:\Users\Administrator\.conda\envs\paddle_gpu_2\lib\site-packages\paddleslim\prune\prune_walker.py", line 169, in _prune
    self._prune_op(op, output_var, channel_axis, pruned_idx)
  File "C:\Users\Administrator\.conda\envs\paddle_gpu_2\lib\site-packages\paddleslim\prune\prune_walker.py", line 109, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "C:\Users\Administrator\.conda\envs\paddle_gpu_2\lib\site-packages\paddleslim\prune\prune_walker.py", line 60, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "C:\Users\Administrator\.conda\envs\paddle_gpu_2\lib\site-packages\paddleslim\prune\prune_walker.py", line 258, in _prune
    self._prune_op(op, param_var, 0, pruned_idx)
  File "C:\Users\Administrator\.conda\envs\paddle_gpu_2\lib\site-packages\paddleslim\prune\prune_walker.py", line 109, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "C:\Users\Administrator\.conda\envs\paddle_gpu_2\lib\site-packages\paddleslim\prune\prune_walker.py", line 60, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "C:\Users\Administrator\.conda\envs\paddle_gpu_2\lib\site-packages\paddleslim\prune\prune_walker.py", line 610, in _prune
    self._prune_op(op, out_var, pruned_axis, pruned_idx)
  File "C:\Users\Administrator\.conda\envs\paddle_gpu_2\lib\site-packages\paddleslim\prune\prune_walker.py", line 109, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "C:\Users\Administrator\.conda\envs\paddle_gpu_2\lib\site-packages\paddleslim\prune\prune_walker.py", line 60, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "C:\Users\Administrator\.conda\envs\paddle_gpu_2\lib\site-packages\paddleslim\prune\prune_walker.py", line 443, in _prune
    self._prune_op(op, in_var, pruned_axis, pruned_idx)
  File "C:\Users\Administrator\.conda\envs\paddle_gpu_2\lib\site-packages\paddleslim\prune\prune_walker.py", line 109, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "C:\Users\Administrator\.conda\envs\paddle_gpu_2\lib\site-packages\paddleslim\prune\prune_walker.py", line 60, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "C:\Users\Administrator\.conda\envs\paddle_gpu_2\lib\site-packages\paddleslim\prune\prune_walker.py", line 437, in _prune
    self._prune_op(op, in_var, pruned_axis, pruned_idx)
  File "C:\Users\Administrator\.conda\envs\paddle_gpu_2\lib\site-packages\paddleslim\prune\prune_walker.py", line 109, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "C:\Users\Administrator\.conda\envs\paddle_gpu_2\lib\site-packages\paddleslim\prune\prune_walker.py", line 60, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "C:\Users\Administrator\.conda\envs\paddle_gpu_2\lib\site-packages\paddleslim\prune\prune_walker.py", line 614, in _prune
    self._prune_op(op, in_var, pruned_axis, pruned_idx)
  File "C:\Users\Administrator\.conda\envs\paddle_gpu_2\lib\site-packages\paddleslim\prune\prune_walker.py", line 109, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "C:\Users\Administrator\.conda\envs\paddle_gpu_2\lib\site-packages\paddleslim\prune\prune_walker.py", line 60, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "C:\Users\Administrator\.conda\envs\paddle_gpu_2\lib\site-packages\paddleslim\prune\prune_walker.py", line 370, in _prune
    self._visit_and_search(in_var, pruned_axis, pruned_idx)
  File "C:\Users\Administrator\.conda\envs\paddle_gpu_2\lib\site-packages\paddleslim\prune\prune_walker.py", line 80, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "C:\Users\Administrator\.conda\envs\paddle_gpu_2\lib\site-packages\paddleslim\prune\prune_walker.py", line 109, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "C:\Users\Administrator\.conda\envs\paddle_gpu_2\lib\site-packages\paddleslim\prune\prune_walker.py", line 58, in prune
    if self._visit(var, pruned_axis):
  File "C:\Users\Administrator\.conda\envs\paddle_gpu_2\lib\site-packages\paddleslim\prune\prune_walker.py", line 65, in _visit
    key = "_".join([key, self.op.all_inputs()[0].name()])
IndexError: list index out of range
W0406 13:29:55.975282 10404 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 5.0, Driver API Version: 10.2, Runtime API Version: 10.0
W0406 13:29:55.987251 10404 device_context.cc:372] device: 0, cuDNN Version: 7.6.

请问如何排除问题？用的是PaddleDetection自带的模型配置文件。

**Comment by wangxinxin08** [comment]
请问你的Paddle版本和PaddleDetection版本以及PaddleSlim的版本都是什么？

**Comment by GZHUZhao** [comment]
> 请问你的Paddle版本和PaddleDetection版本以及PaddleSlim的版本都是什么？
@wangxinxin08
paddlepaddle-gpu    2.0.0.post100
PaddleDetection release/2.0-rc
paddleslim          2.0.0
麻烦您了
