### ISSUE TITLE
部署serving服务出错

### ISSUE THREAD

**Issue by Huihuihh** [PaddlePaddle/PaddleDetection#2568]
按照文档对paddledetection训练的yolov3的模型转换为paddle serving的模型
然后执行test_client.py报错
```
(base) [root@ai-dev-node1 yolov3_darknet]# python ../../deploy/serving/test_client.py  frame_299.jpg
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0409 04:14:51.186856 28225 naming_service_thread.cpp:209] brpc::policy::ListNamingService("127.0.0.1:9393"): added 1
Traceback (most recent call last):
  File "../../deploy/serving/test_client.py", line 40, in <module>
    postprocess(fetch_map)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle_serving_app/reader/image_reader.py", line 429, in __call__
    self.clsid2catid)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle_serving_app/reader/image_reader.py", line 352, in _get_bbox_result
    bbox_results = self._bbox2out([result], clsid2catid, is_bbox_normalized)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle_serving_app/reader/image_reader.py", line 315, in _bbox2out
    catid = (clsid2catid[int(clsid)])
KeyError: 5
```

**Comment by jerrywgz** [comment]
请确认下导出模型时，label_list是否对应当前数据集

**Comment by Huihuihh** [comment]
这个是我自己的问题，训练的时候忘记修改num_classes值了
