### ISSUE TITLE
develop版本运行报错，No module named 'paddle.fluid.dataloader.collate'

### ISSUE THREAD

**Issue by zxsitu** [PaddlePaddle/PaddleDetection#2588]
开发者您好，我已经教程一步步安装develop版本了，
`cd PaddleDetection-develop`
`python -m pip install paddlepaddle-gpu==2.0.1 -f https://paddlepaddle.org.cn/whl/mkl/stable.html`
`pip install -r requirements.txt`
`python setup.py install`
不知道为什么还出现如下的错误，请问怎么解决呢？
我的电脑是win10系统，CUDA为10.2。

```
(pytorch1.6) F:\PycharmProjects\pythonProject4\PaddleDetection-develop>python tools/train.py -c configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.yml --use_vdl=true --vdl_log_dir=vdl_dir/scalar --eval -o use_gpu=true pretrain_weights=''
Traceback (most recent call last):
  File "tools/train.py", line 30, in <module>
    from ppdet.core.workspace import load_config, merge_config, create
  File "D:\Anaconda3\envs\pytorch1.6\lib\site-packages\ppdet-2.0rc0-py3.8.egg\ppdet\__init__.py", line 15, in <module>
    from . import (core, data, engine, modeling, model_zoo, optimizer, metrics,
  File "D:\Anaconda3\envs\pytorch1.6\lib\site-packages\ppdet-2.0rc0-py3.8.egg\ppdet\data\__init__.py", line 17, in <module>
    from . import reader
  File "D:\Anaconda3\envs\pytorch1.6\lib\site-packages\ppdet-2.0rc0-py3.8.egg\ppdet\data\reader.py", line 28, in <module>
    from paddle.fluid.dataloader.collate import default_collate_fn
ModuleNotFoundError: No module named 'paddle.fluid.dataloader.collate'
```

**Comment by wangxinxin08** [comment]
请运行PaddleDetection的develop分支请使用paddle-develop版本，可以在https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html 这里下载

**Comment by ilem777** [comment]
@wangxinxin08 谢谢你，我知道了。

**Comment by zxsitu** [comment]
@wangxinxin08 您好，我打开您的网页了，并选择了win10，cuda10.2版本的paddle-develop版本
`python -m pip install paddlepaddle-gpu -f https://paddlepaddle.org.cn/whl/cu102/mkl/develop.html`

```
(pytorch1.6) F:\PycharmProjects\pythonProject4>python -m pip install paddlepaddle-gpu -f https://paddlepaddle.org.cn/whl/cu102/mkl/develop.html
Looking in links: https://paddlepaddle.org.cn/whl/cu102/mkl/develop.html
Requirement already satisfied: paddlepaddle-gpu in d:\anaconda3\envs\pytorch1.6\lib\site-packages (2.0.2)
Requirement already satisfied: Pillow in d:\anaconda3\envs\pytorch1.6\lib\site-packages (from paddlepaddle-gpu) (8.1.0)
Requirement already satisfied: decorator in d:\anaconda3\envs\pytorch1.6\lib\site-packages (from paddlepaddle-gpu) (4.4.2)
Requirement already satisfied: numpy<=1.19.3,>=1.13 in d:\anaconda3\envs\pytorch1.6\lib\site-packages (from paddlepaddle-gpu) (1.19.3)
Requirement already satisfied: gast==0.3.3 in d:\anaconda3\envs\pytorch1.6\lib\site-packages (from paddlepaddle-gpu) (0.3.3)
Requirement already satisfied: protobuf>=3.1.0 in d:\anaconda3\envs\pytorch1.6\lib\site-packages (from paddlepaddle-gpu) (3.15.6)
Requirement already satisfied: astor in d:\anaconda3\envs\pytorch1.6\lib\site-packages (from paddlepaddle-gpu) (0.8.1)
Requirement already satisfied: requests>=2.20.0 in d:\anaconda3\envs\pytorch1.6\lib\site-packages (from paddlepaddle-gpu) (2.25.1)
Requirement already satisfied: six in d:\anaconda3\envs\pytorch1.6\lib\site-packages (from paddlepaddle-gpu) (1.15.0)
Requirement already satisfied: chardet<5,>=3.0.2 in d:\anaconda3\envs\pytorch1.6\lib\site-packages (from requests>=2.20.0->paddlepaddle-gpu) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\anaconda3\envs\pytorch1.6\lib\site-packages (from requests>=2.20.0->paddlepaddle-gpu) (1.26.3)
Requirement already satisfied: idna<3,>=2.5 in d:\anaconda3\envs\pytorch1.6\lib\site-packages (from requests>=2.20.0->paddlepaddle-gpu) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda3\envs\pytorch1.6\lib\site-packages (from requests>=2.20.0->paddlepaddle-gpu) (2020.12.5)
```

为什么训练还是报错了。。。

```
(pytorch1.6) F:\PycharmProjects\pythonProject4\PaddleDetection-develop>python tools/train.py -c configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.yml --use_vdl=true --vdl_log_dir=vdl_dir/scalar --eval -o use_gpu=true pretrain_weights=''
Traceback (most recent call last):
  File "tools/train.py", line 30, in <module>
    from ppdet.core.workspace import load_config, merge_config, create
  File "D:\Anaconda3\envs\pytorch1.6\lib\site-packages\ppdet-2.0rc0-py3.8.egg\ppdet\__init__.py", line 15, in <module>
    from . import (core, data, engine, modeling, model_zoo, optimizer, metrics,
  File "D:\Anaconda3\envs\pytorch1.6\lib\site-packages\ppdet-2.0rc0-py3.8.egg\ppdet\data\__init__.py", line 17, in <module>
    from . import reader
  File "D:\Anaconda3\envs\pytorch1.6\lib\site-packages\ppdet-2.0rc0-py3.8.egg\ppdet\data\reader.py", line 28, in <module>
    from paddle.fluid.dataloader.collate import default_collate_fn
ModuleNotFoundError: No module named 'paddle.fluid.dataloader.collate'
```
难受唉

**Comment by wangxinxin08** [comment]
应该是没装上去，可以uninstall再下载一次
