### ISSUE TITLE
使用自定义数据集训练ssd_vgg16_300 是报错

### ISSUE THREAD

**Issue by dengxinlong** [PaddlePaddle/PaddleDetection#2706]
使用的命令：
    python tools/train.py -c configs/ssd/ssd_vgg16_300_voc.yml -o pretrain_weights='' --eval

报错信息：
```
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
Traceback (most recent call last):
  File "tools/train.py", line 399, in <module>
    main()
  File "tools/train.py", line 167, in main
    eval_reader = create_reader(cfg.EvalReader, devices_num=1)
  File "/home/xuzhi/Dengxinlong/PaddleDetection/ppdet/data/reader.py", line 442, in create_reader
    reader = Reader(**cfg)()
  File "/home/xuzhi/Dengxinlong/PaddleDetection/ppdet/data/reader.py", line 210, in __init__
    self._roidbs = self._dataset.get_roidb()
  File "/home/xuzhi/Dengxinlong/PaddleDetection/ppdet/data/source/dataset.py", line 68, in get_roidb
    self.load_roidb_and_cname2cid()
  File "/home/xuzhi/Dengxinlong/PaddleDetection/ppdet/data/source/voc.py", line 143, in load_roidb_and_cname2cid
    _difficult = int(obj.find('difficult').text)
AttributeError: 'NoneType' object has no attribute 'text'
```

配置文件：
```
architecture: SSD
use_gpu: true
max_iters: 120001
snapshot_iter: 10000
log_iter: 20
metric: VOC
map_type: 11point
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/VGG16_caffe_pretrained.tar
save_dir: output
weights: output/ssd_vgg16_300_voc/model_final
# 20(label_class) + 1(background)
num_classes: 6

SSD:
  backbone: VGG
  multi_box_head: MultiBoxHead
  output_decoder:
    background_label: 0
    keep_top_k: 200
    nms_eta: 1.0
    nms_threshold: 0.45
    nms_top_k: 400
    score_threshold: 0.01

VGG:
  depth: 16
  with_extra_blocks: true
  normalizations: [20., -1, -1, -1, -1, -1]

MultiBoxHead:
  base_size: 300
  aspect_ratios: [[2.], [2., 3.], [2., 3.], [2., 3.], [2.], [2.]]
  min_ratio: 20
  max_ratio: 90
  min_sizes: [30.0, 60.0, 111.0, 162.0, 213.0, 264.0]
  max_sizes: [60.0, 111.0, 162.0, 213.0, 264.0, 315.0]
  steps: [8, 16, 32, 64, 100, 300]
  offset: 0.5
  flip: true
  min_max_aspect_ratios_order: true
  kernel_size: 3
  pad: 1

LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [80000, 100000]

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

TrainReader:
  inputs_def:
    image_shape: [3, 300, 300]
    fields: ['image', 'gt_bbox', 'gt_class']
  dataset:
    !VOCDataSet
    dataset_dir: dataset/Udacity/CITYdevkit/CITY
    anno_path: trainval.txt
    use_default_label: false
  sample_transforms:
  - !DecodeImage
    to_rgb: true
  - !RandomDistort
    brightness_lower: 0.875
    brightness_upper: 1.125
    is_order: true
  - !RandomExpand
    fill_value: [104, 117, 123]
  - !RandomCrop
    allow_no_crop: true
  - !NormalizeBox {}
  - !ResizeImage
    interp: 1
    target_size: 300
    use_cv2: false
  - !RandomFlipImage
    is_normalized: true
  - !Permute
    to_bgr: false
  - !NormalizeImage
    is_scale: false
    mean: [104, 117, 123]
    std: [1, 1, 1]
  batch_size: 8
  shuffle: true
  worker_num: 8
  bufsize: 16
  use_process: true

EvalReader:
  inputs_def:
    image_shape: [3, 300, 300]
    fields: ['image', 'gt_bbox', 'gt_class', 'im_shape', 'im_id', 'is_difficult']
  dataset:
    !VOCDataSet
    anno_path: test.txt
    dataset_dir: dataset/Udacity/CITYdevkit/CITY
    use_default_label: false
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !NormalizeBox {}
  - !ResizeImage
    interp: 1
    target_size: 300
    use_cv2: false
  - !Permute
    to_bgr: false
  - !NormalizeImage
    is_scale: false
    mean: [104, 117, 123]
    std: [1, 1, 1]
  batch_size: 32
  worker_num: 8
  bufsize: 16

TestReader:
  inputs_def:
    image_shape: [3,300,300]
    fields: ['image', 'im_id', 'im_shape']
  dataset:
    !ImageFolder
    anno_path: test.txt
    use_default_label: false
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !ResizeImage
    interp: 1
    max_size: 0
    target_size: 300
    use_cv2: true
  - !Permute
    to_bgr: false
  - !NormalizeImage
    is_scale: false
    mean: [104, 117, 123]
    std: [1, 1, 1]
  batch_size: 1
```

说明：数据集已经按照官方的教程组织好，但是但是出现了问题，我是不是哪里没有配置对啊？？

**Comment by heavengate** [comment]
你的数据集里没有`difficult`字段？

**Comment by dengxinlong** [comment]
> 你的数据集里没有`difficult`字段？
您好，我查了一下，在voc数据集合是有difficult字段，但是我所使用的数据集（已转为为了voc格式）是没有这个字段的。

**Comment by heavengate** [comment]
https://github.com/PaddlePaddle/PaddleDetection/pull/2714   可以参考这个修复pr修改一下`ppdet/data/source/voc.py`里的

**Comment by dengxinlong** [comment]
> #2714 可以参考这个修复pr修改一下`ppdet/data/source/voc.py`里的

嗯嗯，好的，感谢您的回复！！

**Comment by heavengate** [comment]
问题已经解决，当前issue就先关闭了，如果还有问题，可以reopen这个issue~

**Comment by heavengate** [comment]
https://github.com/PaddlePaddle/PaddleDetection/pull/2714  pr已合入
