### ISSUE TITLE
paddle.io module not found

### ISSUE THREAD

**Issue by nataliyah123** [PaddlePaddle/PaddleDetection#2713]
When I run the following command 
`!python /content/PaddleDetection/dataset/voc/create_list.py -d /content/PaddleDetection/ 
`
I get the following error

`Traceback (most recent call last):
  File "/content/PaddleDetection/dataset/voc/create_list.py", line 23, in <module>
    from ppdet.utils.download import create_voc_list
  File "/content/PaddleDetection/ppdet/__init__.py", line 15, in <module>
    from . import (core, data, engine, modeling, model_zoo, optimizer, metrics,
  File "/content/PaddleDetection/ppdet/data/__init__.py", line 15, in <module>
    from . import source
  File "/content/PaddleDetection/ppdet/data/source/__init__.py", line 15, in <module>
    from . import coco
  File "/content/PaddleDetection/ppdet/data/source/coco.py", line 18, in <module>
    from .dataset import DetDataset
  File "/content/PaddleDetection/ppdet/data/source/dataset.py", line 22, in <module>
    from paddle.io import Dataset
ModuleNotFoundError: No module named 'paddle.io'`
It was not there yesterday

**Comment by heavengate** [comment]
您好，`release/2.0`依赖Paddle的`2.0.1`及以上版本，更新一下Paddle版本能解决上述问题
