### ISSUE TITLE
EvalReader配置中batch_size大于1时在训练中进行evel发生读取数据异常，而train程序可以正常训练,train配置中batch_size为24

### ISSUE THREAD

**Issue by red-hai** [PaddlePaddle/PaddleDetection#2719]
此为EvalReader配置中batch_size=1时可以成功评估
[04/21 00:17:35] ppdet.utils.checkpoint INFO: Save checkpoint: output/ppyolo_r50vd_dcn_voc
[04/21 00:17:38] ppdet.engine INFO: Eval iter: 0
[04/21 00:18:01] ppdet.engine INFO: Eval iter: 100
[04/21 00:18:23] ppdet.engine INFO: Eval iter: 200
[04/21 00:18:46] ppdet.engine INFO: Eval iter: 300
[04/21 00:19:09] ppdet.engine INFO: Eval iter: 400
[04/21 00:19:32] ppdet.engine INFO: Eval iter: 500
[04/21 00:19:55] ppdet.engine INFO: Eval iter: 600
[04/21 00:20:17] ppdet.engine INFO: Eval iter: 700
[04/21 00:20:39] ppdet.engine INFO: Eval iter: 800
[04/21 00:21:00] ppdet.metrics.metrics INFO: Accumulating evaluatation results...
[04/21 00:21:01] ppdet.metrics.metrics INFO: mAP(0.50, 11point) = 25.15%
[04/21 00:21:01] ppdet.engine INFO: Total sample number: 894, averge FPS: 4.4202395352272
[04/21 00:21:01] ppdet.engine INFO: Best test bbox ap is 0.251.

而当EvalReader配置中batch_size=2即大于2时在evel时发生如下情况
[04/21 01:36:32] ppdet.utils.checkpoint INFO: Save checkpoint: output/ppyolo_r50vd_dcn_voc
2021-04-21 01:36:36,229 - ERROR - DataLoader reader thread raised an exception!
[ERROR 2021-04-21 01:36:36,229 dataloader_iter.py:605] DataLoader reader thread raised an exception!
Traceback (most recent call last):
  File "/home/aistudio/work/PaddleDetection/tools/train.py", line 137, in <module>
    main()
  File "/home/aistudio/work/PaddleDetection/tools/train.py", line 133, in main
    run(FLAGS, cfg)
  File "/home/aistudio/work/PaddleDetection/tools/train.py", line 111, in run
    trainer.train(FLAGS.eval)
  File "/home/aistudio/work/PaddleDetection/ppdet/engine/trainer.py", line 304, in train
    self._eval_with_loader(self._eval_loader)
  File "/home/aistudio/work/PaddleDetection/ppdet/engine/trainer.py", line 312, in _eval_with_loader
    for step_id, data in enumerate(loader):
  File "/home/aistudio/work/PaddleDetection/ppdet/data/reader.py", line 216, in __next__
    data = next(self.loader)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 779, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)

谢谢！

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/pull/2731
https://github.com/PaddlePaddle/PaddleDetection/pull/2732
感谢反馈，目前问题已经在pr中修复
