### ISSUE TITLE
cascade-rcnn 多GPU训练时，eval出错，KeyError: 'mask'

### ISSUE THREAD

**Issue by wanggp01** [PaddlePaddle/PaddleDetection#2743]
使用的训练指令：python -m paddle.distributed.launch --gpus 6,7 tools/train.py -c configs/dcn/cascade_rcnn_dcn_r50_fpn_1x_coco.yml --eval --use_vdl True --vdl_log_dir vdl_log_dir/scalar
错误信息：
[04/23 13:58:08] ppdet.engine INFO: Total sample number: 3471, averge FPS: 6.7864325083890105
Traceback (most recent call last):
  File "tools/train.py", line 137, in <module>
    main()
  File "tools/train.py", line 133, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 111, in run
    trainer.train(FLAGS.eval)
  File "/data/wangguangping/anaconda3/envs/paddle_201/lib/python3.6/site-packages/paddledet-2.0.0-py3.6.egg/ppdet/engine/trainer.py", line 304, in train
    self._eval_with_loader(self._eval_loader)
  File "/data/wangguangping/anaconda3/envs/paddle_201/lib/python3.6/site-packages/paddledet-2.0.0-py3.6.egg/ppdet/engine/trainer.py", line 332, in _eval_with_loader
    self._compose_callback.on_epoch_end(self.status)
  File "/data/wangguangping/anaconda3/envs/paddle_201/lib/python3.6/site-packages/paddledet-2.0.0-py3.6.egg/ppdet/engine/callbacks.py", line 76, in on_epoch_end
    c.on_epoch_end(status)
  File "/data/wangguangping/anaconda3/envs/paddle_201/lib/python3.6/site-packages/paddledet-2.0.0-py3.6.egg/ppdet/engine/callbacks.py", line 182, in on_epoch_end
    if map_res[key][0] > self.best_ap:
KeyError: 'mask'
也尝试过将ppdet/engine/callbacks.py复制到上述出错的路径下，依然没有解决

**Comment by liuhuiCNN** [comment]
感谢反馈，根据报错信息，应该是检测结果为空导致的，请检查学习率是否正确。
