### ISSUE TITLE
cpp demo 错误

### ISSUE THREAD

**Issue by longegit** [PaddlePaddle/PaddleDetection#2744]
./build/main --model_dir=/home/ubuntu/下载/PaddleDetection-release-2.0/inference_model/yolov3_darknet53_270e_coco --image_path=/home/huitou/test/testpic/1.jpg

错误如下
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

  Compile Traceback (most recent call last):
    File "tools/export_model.py", line 105, in <module>
      main()
    File "tools/export_model.py", line 101, in main
      run(FLAGS, cfg)
    File "tools/export_model.py", line 69, in run
      trainer.export(FLAGS.output_dir)
    File "/home/huitou/.local/lib/python3.6/site-packages/ppdet/engine/trainer.py", line 443, in export
      input_spec, static_model.forward.main_program,
    File "/home/huitou/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 534, in main_program
      concrete_program = self.concrete_program
    File "/home/huitou/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 454, in concrete_program
      return self.concrete_program_specify_input_spec(input_spec=None)
    File "/home/huitou/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program_specify_input_spec
      *desired_input_spec)
    File "/home/huitou/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/home/huitou/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/home/huitou/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 702, in _build_once
      class_instance=cache_key.class_instance)
    File "<decorator-gen-64>", line 2, in from_func_spec
      
    File "/home/huitou/.local/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/home/huitou/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
      return func(*args, **kwargs)
    File "/home/huitou/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 652, in from_func_spec
      outputs = static_func(*inputs)
    File "/tmp/tmprts7giq9.py", line 27, in forward
      false_fn_1, (), (), (out,))
    File "/home/huitou/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/home/huitou/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/home/huitou/.local/lib/python3.6/site-packages/ppdet/modeling/architectures/meta_arch.py", line 29, in forward
      out = self.get_pred()
    File "/home/huitou/.local/lib/python3.6/site-packages/ppdet/modeling/architectures/yolo.py", line 75, in get_pred
      bbox_pred, bbox_num = self._forward()
    File "/home/huitou/.local/lib/python3.6/site-packages/ppdet/modeling/architectures/yolo.py", line 59, in _forward
      body_feats = self.backbone(self.inputs)
    File "/home/huitou/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/home/huitou/.local/lib/python3.6/site-packages/ppdet/modeling/backbones/darknet.py", line 307, in forward
      out = self.conv0(x)
    File "/home/huitou/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/tmp/tmp077eqfb3.py", line 23, in forward
      true_fn_7, false_fn_7, (out,), (out, self), (out,))
    File "/home/huitou/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/home/huitou/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/home/huitou/.local/lib/python3.6/site-packages/ppdet/modeling/backbones/darknet.py", line 77, in forward
      out = F.leaky_relu(out, 0.1)
    File "/home/huitou/.local/lib/python3.6/site-packages/paddle/nn/functional/activation.py", line 423, in leaky_relu
      attrs={'alpha': negative_slope})
    File "/home/huitou/.local/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/home/huitou/.local/lib/python3.6/site-packages/paddle/fluid/framework.py", line 3225, in append_op
      attrs=kwargs.get("attrs", None))
    File "/home/huitou/.local/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2305, in __init__
      for frame in traceback.extract_stack():

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun()
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   paddle::framework::OperatorWithKernel::ChooseKernel(paddle::framework::RuntimeContext const&, paddle::framework::Scope const&, paddle::platform::Place const&) const
6   paddle::operators::ActivationOp::GetExpectedKernelType(paddle::framework::ExecutionContext const&) const
7   paddle::operators::GetKernelType(paddle::framework::ExecutionContext const&, paddle::framework::OperatorWithKernel const&, std::string const&)
8   paddle::framework::OperatorWithKernel::IndicateVarDataType(paddle::framework::ExecutionContext const&, std::string const&) const
9   paddle::framework::OperatorWithKernel::ParseInputDataType(paddle::framework::ExecutionContext const&, std::string const&, paddle::framework::proto::VarType_Type*) const
10  paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
11  paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The Tensor in the leaky_relu Op's Input Variable X(batch_norm_0.tmp_2) is not initialized.
  [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at /home/huitou/Paddle/paddle/fluid/framework/operator.cc:1511)
  [operator < leaky_relu > error]

**Comment by liuhuiCNN** [comment]
请问您使用的模型是哪个呢？预测库版本是多少？

**Comment by longegit** [comment]
> 请问您使用的模型是哪个呢？预测库版本是多少？
paddle用的是开发版 python -m pip install --pre paddlepaddle-gpu==2.1.0.dev0.post101 -f https://paddlepaddle.org.cn/whl/cu101/mkl/develop.html
模型用的是 https://paddledet.bj.bcebos.com/models/yolov3_darknet53_270e_coco.pdparams，用export_model.py导出

**Comment by longegit** [comment]
> 请问您使用的模型是哪个呢？预测库版本是多少？

我c++编译的库是2.0.2版本，然后我想导出模型的时候，export_model.py只能用在开发版上，所以python安装的开发版，两个版本不一样

**Comment by liuhuiCNN** [comment]
> > 请问您使用的模型是哪个呢？预测库版本是多少？
> 
> 我c++编译的库是2.0.2版本，然后我想导出模型的时候，export_model.py只能用在开发版上，所以python安装的开发版，两个版本不一样

您好，ppdet release/2.0，paddle 2.0.1，paddle预测库2.0.1是正常的。建议您用相同版本的paddle导出模型。
