### ISSUE TITLE
ppyolo_v2迁移训练后，模型导出出错

### ISSUE THREAD

**Issue by ybc-ybc** [PaddlePaddle/PaddleDetection#2750]
采用ppyolov2_r50vd_dcn_365e_coco.pdparams作为预训练模型在新的数据集训练，
如下：
```
[04/24 18:05:15] ppdet.utils.checkpoint INFO: yolo_head.yolo_output.0.weight not used, shape (258, 1024, 1, 1) unmatched with [21, 1024, 1, 1] in model.
[04/24 18:05:15] ppdet.utils.checkpoint INFO: yolo_head.yolo_output.0.bias not used, shape (258,) unmatched with [21] in model.
[04/24 18:05:15] ppdet.utils.checkpoint INFO: yolo_head.yolo_output.1.weight not used, shape (258, 512, 1, 1) unmatched with [21, 512, 1, 1] in model.
[04/24 18:05:15] ppdet.utils.checkpoint INFO: yolo_head.yolo_output.1.bias not used, shape (258,) unmatched with [21] in model.
[04/24 18:05:15] ppdet.utils.checkpoint INFO: yolo_head.yolo_output.2.weight not used, shape (258, 256, 1, 1) unmatched with [21, 256, 1, 1] in model.
[04/24 18:05:15] ppdet.utils.checkpoint INFO: yolo_head.yolo_output.2.bias not used, shape (258,) unmatched with [21] in model.
[04/24 18:05:15] ppdet.utils.checkpoint INFO: Finish loading model weights: ./weights/ppyolov2_r50vd_dcn_365e_coco.pdparams
```
训练的输出模型，导出出错
```
(paddle) C:\Users\nybc\Desktop\PaddleDetection>python tools/export_model.py -c ./configs/ppyolo/ppyolov2_r50vd_dcn_365e_coco.yml --output_dir=C:/Users/nybc/Desktop/tracking/model/detection -o weights=weights/best_model.pdparams
Traceback (most recent call last):
  File "tools/export_model.py", line 105, in <module>
    main()
  File "tools/export_model.py", line 101, in main
    run(FLAGS, cfg)
  File "tools/export_model.py", line 66, in run
    trainer.load_weights(cfg.weights)
  File "C:\Users\nybc\Desktop\PaddleDetection\ppdet\engine\trainer.py", line 198, in load_weights
    load_pretrain_weight(self.model, weights)
  File "C:\Users\nybc\Desktop\PaddleDetection\ppdet\utils\checkpoint.py", line 159, in load_pretrain_weight
    param_state_dict = paddle.load(weights_path)
  File "C:\Users\nybc\anaconda3\envs\paddle\lib\site-packages\paddle\framework\io.py", line 365, in load
    f, encoding='latin1')
ValueError: buffer size does not match array size
```

**Comment by wangxinxin08** [comment]
1. 第一张图是由于你的类别与coco类别不一致导致最后一层输出的channel不一致，是正常的
2. 第二个模型报错推测是由于你的权重文件的路径没有正确指定，需要提供模型文件和配置文件做进一步确认

**Comment by ybc-ybc** [comment]
> 1. 第一张图是由于你的类别与coco类别不一致导致最后一层输出的channel不一致，是正常的
> 2. 第二个模型报错推测是由于你的权重文件的路径没有正确指定，需要提供模型文件和配置文件做进一步确认

感谢
