### ISSUE TITLE
ppyolov2训练完，infer出现图像尺度不匹配

### ISSUE THREAD

**Issue by 617475jordan** [PaddlePaddle/PaddleDetection#2760]
```
Traceback (most recent call last):
  File "infer.py", line 155, in <module>
    main()
  File "infer.py", line 151, in main
    run(FLAGS, cfg)
  File "infer.py", line 132, in run
    save_txt=FLAGS.save_txt)
  File "E:\github\20210104\PaddleDetection\ppdet\engine\trainer.py", line 360, in predict
    outs = self.model(data)
  File "F:\Programs\miniconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "E:\github\20210104\PaddleDetection\ppdet\modeling\architectures\meta_arch.py", line 29, in forward
    out = self.get_pred()
  File "E:\github\20210104\PaddleDetection\ppdet\modeling\architectures\yolo.py", line 75, in get_pred
    bbox_pred, bbox_num = self._forward()
  File "E:\github\20210104\PaddleDetection\ppdet\modeling\architectures\yolo.py", line 60, in _forward
    body_feats = self.neck(body_feats)
  File "F:\Programs\miniconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "E:\github\20210104\PaddleDetection\ppdet\modeling\necks\yolo_fpn.py", line 929, in forward
    block = paddle.concat([route, block], axis=1)
  File "F:\Programs\miniconda3\envs\paddle\lib\site-packages\paddle\tensor\manipulation.py", line 124, in concat
    return paddle.fluid.layers.concat(input=x, axis=axis, name=name)
  File "F:\Programs\miniconda3\envs\paddle\lib\site-packages\paddle\fluid\layers\tensor.py", line 306, in concat
    return core.ops.concat(input, 'axis', axis)
ValueError: (InvalidArgument) The 3-th dimension of input[0] and input[1] is expected to be equal.But received input[0]'s shape = [1, 256, 240, 136], input[1]'s shape = [1, 512, 240, 135].
  [Hint: Expected inputs_dims[0][j] == inputs_dims[i][j], but received inputs_dims[0][j]:136 != inputs_dims[i][j]:135.] (at D:\v2.0.2\paddle\paddle/fluid/operators/concat_op.h:63)
  [operator < concat > error]
```

导致无法进行infer.py 验证

**Comment by qingqing01** [comment]
@617475jordan 您是自定义数据吗？ 有更改啥吗？具体是那个配置？

**Comment by wangxinxin08** [comment]
看了下是w的维度不匹配，一个是135，一个是136，这是由于输入图像的尺寸不是32的整数倍导致的，你infer的时候是修改了图像的输入尺寸吗？

**Comment by 617475jordan** [comment]
明白了，谢谢。是的。我在训练的时候调整了输图片的尺寸

**Comment by qingqing01** [comment]
@617475jordan 如果问题已解决，就关闭了此issue
