### ISSUE TITLE
快速开始水果识别报错

### ISSUE THREAD

**Issue by xiaomujiang** [PaddlePaddle/PaddleDetection#278]
python -u tools/train.py -c configs/yolov3_mobilenet_v1_fruit.yml  启动快速开始的例子报错 版本1.7
错误如下：

```
2020-02-29 23:18:27,400-INFO: iter: 1100, lr: 0.000010, 'loss': '11.210521', time: 21.426, eta: 5:21:23
2020-02-29 23:20:51,825-WARNING: consumer[12221] exit abnormally with exitcode[-9]
2020-02-29 23:20:51,875-WARNING: 1 consumers have exited abnormally!!!
2020-02-29 23:20:51,897-WARNING: consumer[12221] exit abnormally with exitcode[-9]
2020-02-29 23:20:51,897-WARNING: 1 consumers have exited abnormally!!!
2020-02-29 23:20:52,937-WARNING: Your reader has raised an exception!
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/zhangshilin/anaconda3/envs/paddle/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/zhangshilin/anaconda3/envs/paddle/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zhangshilin/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/reader.py", line 805, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/home/zhangshilin/anaconda3/envs/paddle/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/zhangshilin/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/reader.py", line 785, in __thread_main__
    for tensors in self._tensor_reader():
  File "/home/zhangshilin/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/reader.py", line 853, in __tensor_reader_impl__
    for slots in paddle_reader():
  File "/home/zhangshilin/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 488, in __reader_creator__
    for item in reader():
  File "/home/zhangshilin/paddledetection/PaddleDetection/ppdet/data/reader.py", line 417, in _reader
    reader.reset()
  File "/home/zhangshilin/paddledetection/PaddleDetection/ppdet/data/parallel_map.py", line 261, in reset
    assert self._consumer_healthy(), "cannot start another pass of data" \
AssertionError: cannot start another pass of data for some consumers exited abnormally before!!!

/home/zhangshilin/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/executor.py:782: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tools/train.py", line 323, in <module>
    main()
  File "tools/train.py", line 233, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "/home/zhangshilin/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/executor.py", line 783, in run
    six.reraise(*sys.exc_info())
  File "/home/zhangshilin/anaconda3/envs/paddle/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/zhangshilin/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/executor.py", line 778, in run
    use_program_cache=use_program_cache)
  File "/home/zhangshilin/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/executor.py", line 843, in _run_impl
    return_numpy=return_numpy)
  File "/home/zhangshilin/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/executor.py", line 677, in _run_parallel
    tensors = exe.run(fetch_var_names)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/zhangshilin/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/zhangshilin/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/reader.py", line 733, in _init_non_iterable
    outputs={'Out': self._feed_list})
  File "/home/zhangshilin/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/reader.py", line 646, in __init__
    self._init_non_iterable()
  File "/home/zhangshilin/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/reader.py", line 280, in from_generator
    iterable, return_list)
  File "/home/zhangshilin/paddledetection/PaddleDetection/ppdet/modeling/architectures/yolov3.py", line 152, in build_inputs
    iterable=iterable) if use_dataloader else None
  File "tools/train.py", line 115, in main
    feed_vars, train_loader = model.build_inputs(**inputs_def)
  File "tools/train.py", line 323, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]
2020-02-29 23:22:42,797-INFO: fail to map op [RandomInterpImage_4d415e] with error: ResizeImage_8e64f4: image is not 3-dimensional. and stack:
Traceback (most recent call last):
  File "/home/zhangshilin/paddledetection/PaddleDetection/ppdet/data/reader.py", line 45, in __call__
    data = f(data, ctx)
  File "/home/zhangshilin/paddledetection/PaddleDetection/ppdet/data/transform/operators.py", line 1041, in __call__
    return resizer(sample, context)
  File "/home/zhangshilin/paddledetection/PaddleDetection/ppdet/data/transform/operators.py", line 281, in __call__
    raise ImageError('{}: image is not 3-dimensional.'.format(self))
ppdet.data.transform.operators.ImageError: ResizeImage_8e64f4: image is not 3-dimensional.

2020-02-29 23:23:10,125-INFO: fail to map op [RandomInterpImage_4d415e] with error: ResizeImage_1a47c9: image is not 3-dimensional. and stack:
Traceback (most recent call last):
  File "/home/zhangshilin/paddledetection/PaddleDetection/ppdet/data/reader.py", line 45, in __call__
    data = f(data, ctx)
  File "/home/zhangshilin/paddledetection/PaddleDetection/ppdet/data/transform/operators.py", line 1041, in __call__
    return resizer(sample, context)
  File "/home/zhangshilin/paddledetection/PaddleDetection/ppdet/data/transform/operators.py", line 281, in __call__
    raise ImageError('{}: image is not 3-dimensional.'.format(self))
ppdet.data.transfo
```

**Comment by jerrywgz** [comment]
可以适当的减小配置文件中的work_num，如果仍出现问题可以将use_process设置为False，后续我们会将该配置文件的训练方式更换成单进程训练

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/pull/288
