### ISSUE TITLE
python setup.py install , UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfb in...

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleDetection#2797]
...
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "setup.py", line 76, in <module>
    setup(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 408, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 650, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 697, in install_item
    self.process_distribution(spec, dist, deps)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 755, in process_distribution
    self.easy_install(dist.as_requirement())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 669, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 700, in install_item
    self.process_distribution(spec, dists[0], deps, "Using")
  File "/home/ubuntu/.local/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 725, in process_distribution
    self.install_egg_scripts(dist)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 599, in install_egg_scripts
    dist.get_metadata('scripts/' + script_name)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1409, in get_metadata
    return value.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfb in position 41: invalid start byte in scripts/shellcheck file at path: /usr/local/lib/python3.8/dist-packages/shellcheck_py-0.7.2.1-py3.8-linux-x86_64.egg/EGG-INFO/scripts/shellcheck

**Comment by yghstill** [comment]
@ynzzxc 感谢反馈，您是下载的最新代码吗？我们先复现一下这个问题。

**Comment by Hyper-Devil** [comment]
Using /home/sy/anaconda3/envs/paddle/lib/python3.7/site-packages
Searching for shellcheck-py==0.7.2.1
Best match: shellcheck-py 0.7.2.1
Processing shellcheck_py-0.7.2.1-py3.7-linux-x86_64.egg
shellcheck-py 0.7.2.1 is already the active version in easy-install.pth
Traceback (most recent call last):
  File "setup.py", line 93, in <module>
    ext_modules=[])
  File "/home/sy/anaconda3/envs/paddle/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in setup
    return distutils.core.setup(**attrs)
  File "/home/sy/anaconda3/envs/paddle/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/sy/anaconda3/envs/paddle/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/sy/anaconda3/envs/paddle/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/sy/anaconda3/envs/paddle/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/sy/anaconda3/envs/paddle/lib/python3.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/home/sy/anaconda3/envs/paddle/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 425, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/sy/anaconda3/envs/paddle/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 667, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/sy/anaconda3/envs/paddle/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 714, in install_item
    self.process_distribution(spec, dist, deps)
  File "/home/sy/anaconda3/envs/paddle/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 769, in process_distribution
    self.easy_install(dist.as_requirement())
  File "/home/sy/anaconda3/envs/paddle/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 686, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/sy/anaconda3/envs/paddle/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 717, in install_item
    self.process_distribution(spec, dists[0], deps, "Using")
  File "/home/sy/anaconda3/envs/paddle/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 739, in process_distribution
    self.install_egg_scripts(dist)
  File "/home/sy/anaconda3/envs/paddle/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 616, in install_egg_scripts
    dist.get_metadata('scripts/' + script_name)
  File "/home/sy/anaconda3/envs/paddle/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1424, in get_metadata
    return value.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfb in position 41: invalid start byte in scripts/shellcheck file at path: /home/sy/anaconda3/envs/paddle/lib/python3.7/site-packages/shellcheck_py-0.7.2.1-py3.7-linux-x86_64.egg/EGG-INFO/scripts/shellcheck

使用新下载的代码，遇到了相似的问题

**Comment by czyczyczy** [comment]
同样的问题

**Comment by ghost** [comment]
> 
> 
> @ynzzxc 感谢反馈，您是下载的最新代码吗？我们先复现一下这个问题。

是最新的代码，自己鼓捣了好久都没解决问题

**Comment by soeaver** [comment]
遇到了一样的问题

**Comment by eminem171333491** [comment]
我也遇到了同样的问题

**Comment by HAOCHENYE** [comment]
pip uninstall shellcheck-py。
pip install shellcheck-py.
手动重装就好了

**Comment by heavengate** [comment]
你好，最新的代码上修复了这个问题~

**Comment by ghost** [comment]
> 
> 
> 你好，最新的代码上修复了这个问题~

谢谢

**Comment by JensenGao** [comment]
> 你好，最新的代码上修复了这个问题~

最新的工程在“[源码编译安装](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)”（release 2.1）的时候也会报上面相同的问题；
我的解决方法是：先安装工程依赖（requirements.txt），再继续执行 “python setup.py install” 就ok了，这里好像是 shellcheck-py有个依赖问题。
你们可以验证下，我遇到了就提一下。
