### ISSUE TITLE
快速开始的第二步就走不通

### ISSUE THREAD

**Issue by hablee** [PaddlePaddle/PaddleDetection#2819]
下载PaddleDetection
下载数据集
什么都没改都走不通。
报错信息：
`Traceback (most recent call last):
  File "tools/train.py", line 137, in <module>
    main()
  File "tools/train.py", line 133, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 111, in run
    trainer.train(FLAGS.eval)
  File "/home/jp/lihaibaoProjects/tmp/new_projects/demo/ppdet/engine/trainer.py", line 274, in train
    outputs = model(data)
  File "/home/jp/.conda/envs/lihaibao_tfp/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/jp/lihaibaoProjects/tmp/new_projects/demo/ppdet/modeling/architectures/meta_arch.py", line 27, in forward
    out = self.get_loss()
  File "/home/jp/lihaibaoProjects/tmp/new_projects/demo/ppdet/modeling/architectures/yolo.py", line 72, in get_loss
    return self._forward()
  File "/home/jp/lihaibaoProjects/tmp/new_projects/demo/ppdet/modeling/architectures/yolo.py", line 59, in _forward
    body_feats = self.backbone(self.inputs)
  File "/home/jp/.conda/envs/lihaibao_tfp/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/jp/lihaibaoProjects/tmp/new_projects/demo/ppdet/modeling/backbones/mobilenet_v1.py", line 391, in forward
    y = self.conv1(inputs['image'])
  File "/home/jp/.conda/envs/lihaibao_tfp/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/jp/lihaibaoProjects/tmp/new_projects/demo/ppdet/modeling/backbones/mobilenet_v1.py", line 76, in forward
    x = self._batch_norm(x)
  File "/home/jp/.conda/envs/lihaibao_tfp/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/jp/.conda/envs/lihaibao_tfp/lib/python3.7/site-packages/paddle/nn/layer/norm.py", line 1058, in forward
    variance_out, *attrs)
RuntimeError: (NotFound) Operator sync_batch_norm does not have kernel for data_type[float]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN].
  [Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] (at /paddle/paddle/fluid/imperative/prepared_operator.cc:128)
  [operator < sync_batch_norm > error]
`

**Comment by liuhuiCNN** [comment]
（1）请问您是用的是CPU训练的吗？您使用的Paddle 版本，ppdet版本分别是多少呢？
（2）sync_batch_norm 在CPU上报错是已知问题，建议您用GPU试一下。[AIStudio](https://aistudio.baidu.com/aistudio/index) 上有免费GPU可以使用，且环境是配置好的，建议您使用一下看看。

**Comment by wangxinxin08** [comment]
如果使用cpu训练，需要设置norm_type为bn，如下所示：
python tools/train.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml -o use_gpu=false norm_type=bn

**Comment by yghstill** [comment]
@hablee 问题已修复，请重新下载或clone最新代码再试下吧

**Comment by kaikaizhu** [comment]
@yghstill 
非常感谢，目前不报错了，但是直接按照教程跑测试的话，满图都是框
