### ISSUE TITLE
AttributeError: module 'paddle.fluid.core_avx.ops' has no attribute 'sync_batch_norm'

### ISSUE THREAD

**Issue by 2-mo** [PaddlePaddle/PaddleDetection#2824]
使用CPU跑实例文件时出现以下属性错误，具体报错如下：
Traceback (most recent call last):
  File "tools/infer.py", line 160, in <module>
    main()
  File "tools/infer.py", line 156, in main
    run(FLAGS, cfg)
  File "tools/infer.py", line 132, in run
    save_txt=FLAGS.save_txt)
  File "/Users/tiumo/opt/anaconda3/envs/master36/lib/python3.6/site-packages/ppdet/engine/trainer.py", line 375, in predict
    outs = self.model(data)
  File "/Users/tiumo/opt/anaconda3/envs/master36/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/Users/tiumo/opt/anaconda3/envs/master36/lib/python3.6/site-packages/ppdet/modeling/architectures/meta_arch.py", line 29, in forward
    out = self.get_pred()
  File "/Users/tiumo/opt/anaconda3/envs/master36/lib/python3.6/site-packages/ppdet/modeling/architectures/yolo.py", line 75, in get_pred
    bbox_pred, bbox_num = self._forward()
  File "/Users/tiumo/opt/anaconda3/envs/master36/lib/python3.6/site-packages/ppdet/modeling/architectures/yolo.py", line 59, in _forward
    body_feats = self.backbone(self.inputs)
  File "/Users/tiumo/opt/anaconda3/envs/master36/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/Users/tiumo/opt/anaconda3/envs/master36/lib/python3.6/site-packages/ppdet/modeling/backbones/resnet.py", line 573, in forward
    conv1 = self.conv1(x)
  File "/Users/tiumo/opt/anaconda3/envs/master36/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/Users/tiumo/opt/anaconda3/envs/master36/lib/python3.6/site-packages/paddle/fluid/dygraph/container.py", line 95, in forward
    input = layer(input)
  File "/Users/tiumo/opt/anaconda3/envs/master36/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/Users/tiumo/opt/anaconda3/envs/master36/lib/python3.6/site-packages/ppdet/modeling/backbones/resnet.py", line 133, in forward
    out = self.norm(out)
  File "/Users/tiumo/opt/anaconda3/envs/master36/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/Users/tiumo/opt/anaconda3/envs/master36/lib/python3.6/site-packages/paddle/nn/layer/norm.py", line 1056, in forward
    sync_batch_norm_out, _, _, _, _, _ = core.ops.sync_batch_norm(
AttributeError: module 'paddle.fluid.core_avx.ops' has no attribute 'sync_batch_norm'

**Comment by liuhuiCNN** [comment]
你好，感谢反馈，这是已知bug，请参考 #2819，我们尽快修复。
命令：`python tools/train.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml -o use_gpu=false norm_type=bn`

**Comment by 2-mo** [comment]
> 你好，感谢反馈，这是已知bug，请参考 #2819，我们尽快修复。
> 命令：`python tools/train.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml -o use_gpu=false norm_type=bn`

谢谢！已解决。

**Comment by rishikeshF** [comment]
> > Hello, thanks for the feedback, this is a known bug, please refer to #2819 , we will fix it as soon as possible. 
> > command:`python tools/train.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml -o use_gpu=false norm_type=bn`
> 
> Thank you! solved.

I tried aforementioned command, it gave me below error : 

Traceback (most recent call last):
  File "tools/train.py", line 137, in <module>
    main()
  File "tools/train.py", line 133, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 111, in run
    trainer.train(FLAGS.eval)
  File "/usr/local/lib/python3.7/dist-packages/ppdet/engine/trainer.py", line 274, in train
    outputs = model(data)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/ppdet/modeling/architectures/meta_arch.py", line 27, in forward
    out = self.get_loss()
  File "/usr/local/lib/python3.7/dist-packages/ppdet/modeling/architectures/yolo.py", line 72, in get_loss
    return self._forward()
  File "/usr/local/lib/python3.7/dist-packages/ppdet/modeling/architectures/yolo.py", line 60, in _forward
    body_feats = self.neck(body_feats)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/ppdet/modeling/necks/yolo_fpn.py", line 640, in forward
    route, tip = self.yolo_blocks[i](block)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/ppdet/modeling/necks/yolo_fpn.py", line 272, in forward
    route = self.conv_module(inputs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/container.py", line 95, in forward
    input = layer(input)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/ppdet/modeling/necks/yolo_fpn.py", line 200, in forward
    data_format=self.data_format)
  File "/usr/local/lib/python3.7/dist-packages/paddle/nn/functional/pooling.py", line 733, in max_pool2d
    'data_format', data_format)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/multiprocess_utils.py", line 134, in __handler__
    core._throw_error_if_process_failed()
SystemError: (Fatal) DataLoader process (pid 1101) exited is killed by signal: Killed. (at /paddle/paddle/fluid/imperative/data_loader.cc:165)

Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/usr/lib/python3.7/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/multiprocessing/managers.py", line 675, in _finalize_manager
    process.join(timeout=1.0)
  File "/usr/lib/python3.7/multiprocessing/process.py", line 140, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 48, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/multiprocess_utils.py", line 134, in __handler__
    core._throw_error_if_process_failed()
SystemError: (Fatal) DataLoader process (pid 1101) exited is killed by signal: Killed. (at /paddle/paddle/fluid/imperative/data_loader.cc:165)

**Comment by heavengate** [comment]
https://github.com/PaddlePaddle/PaddleDetection/pull/2825  修复pr已合入，可以更新develop代码试下~

**Comment by ustblogistics87** [comment]
> #2825 修复pr已合入，可以更新develop代码试下~

您好，我现在依旧遇到这个问题，不知道是我哪里操作得问题
执行命令：
python tools/train.py -c configs/solov2/solov2_r50_enhance_coco.yml  -o use_gpu=false norm_type=bn
遇到error：
AttributeError: module 'paddle.fluid.core_avx.ops' has no attribute 'sync_batch_norm'

感谢回答！

paddle版本：2.2.1
paddledet版本：2.3.0
