### ISSUE TITLE
训练自己制作的coco数据集出问题

### ISSUE THREAD

**Issue by zyzjly** [PaddlePaddle/PaddleDetection#2831]
$ python tools/train.py -c configs/ppyolo/ppyolov2_r101vd_dcn_365e_coco.yml -o use_gpu=true
[04/30 10:55:31] ppdet.utils.download INFO: Dataset C:\Users\ADMIN\PaddleDetection\dataset\coco is not valid for reason above, try searching C:\Users\ADMIN/.cache/paddle/dataset or downloading dataset...
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[04/30 10:55:33] ppdet.utils.checkpoint INFO: Finish loading model weights: C:\Users\ADMIN/.cache/paddle/weights\ResNet101_vd_ssld_pretrained.pdparams
True
Traceback (most recent call last):
  File "tools/train.py", line 137, in <module>
    main()
  File "tools/train.py", line 133, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 111, in run
    trainer.train(FLAGS.eval)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python38\lib\site-packages\ppdet\engine\trainer.py", line 300, in train
    self.model.set_dict(self.ema.apply())
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python38\lib\site-packages\ppdet\optimizer.py", line 258, in apply
    print(self._decay)
AttributeError: 'ModelEMA' object has no attribute '_decay'
W0430 10:55:28.630926 81268 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.1, Runtime API Version: 10.0
W0430 10:55:28.636900 81268 device_context.cc:372] device: 0, cuDNN Version: 7.6.

**Comment by wangxinxin08** [comment]
这个错误是由于自制的数据集的样本数目小于一个iter的大小，导致模型一个iter都没有运行，不过后续会修掉这个报错

**Comment by zyzjly** [comment]
我设置use_ema为false后，模型训练起来了。请问可以直接设置iter的大小吗？ @wangxinxin08

**Comment by wangxinxin08** [comment]
不能直接设置iter的大小，可以直接设置epoch的大小，你可以在configs/ppyolo/optimizer_365e里面修改epoch，或者在训练时使用python tools/train.py -c configs/ppyolo/ppyolov2_r101vd_dcn_365e_coco.yml -o use_gpu=true epoch=1来指定epoch的数目。
你报这个错误的原因应该是样本的总数量小于总的batch_size的大小，设置成ema为false，虽然没有报错，但是其实并没有训练。
