### ISSUE TITLE
PPYOLO模型单卡训练自制数据，image evaluation时. KeyError: 'area'

### ISSUE THREAD

**Issue by GreenValue** [PaddlePaddle/PaddleDetection#2832]
- Environment，Images 同 #2804 
- 我该如何在annotations中定义area呢？
![image](https://user-images.githubusercontent.com/16701660/116653036-f9812880-a9b8-11eb-945c-789ee30ab336.png)

- Output
```
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
W0430 02:50:27.740244    34 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.0, Runtime API Version: 10.0
W0430 02:50:27.873313    34 device_context.cc:372] device: 0, cuDNN Version: 7.6.
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/io.py:2284: UserWarning: This list is not set, Because of Paramerter not found in program. There are: fc_0.b_0 fc_0.w_0
  format(" ".join(unused_para_list)))
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2021-04-30 02:50:43,101-INFO: iter: 0, lr: 0.000000, 'loss': '8015.203613', 'loss_cls': '2.063663', 'loss_xy': '0.985615', 'loss_iou': '2.906958', 'loss_iou_aware': '2.247878', 'loss_wh': '2.260870', 'loss_obj': '8004.738770', eta: 0:00:22, batch_cost: 0.00045 sec, ips: 8811.56303 images/sec
/usr/local/python2.7.15/lib/python2.7/site-packages/numpy/lib/function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
2021-04-30 02:51:10,429-INFO: iter: 100, lr: 0.000005, 'loss': 'nan', 'loss_cls': 'nan', 'loss_xy': 'nan', 'loss_iou': 'nan', 'loss_iou_aware': 'nan', 'loss_wh': 'nan', 'loss_obj': 'nan', eta: 4:02:25, batch_cost: 0.29149 sec, ips: 13.72283 images/sec
2021-04-30 02:51:39,722-INFO: iter: 200, lr: 0.000010, 'loss': 'nan', 'loss_cls': 'nan', 'loss_xy': 'nan', 'loss_iou': 'nan', 'loss_iou_aware': 'nan', 'loss_wh': 'nan', 'loss_obj': 'nan', eta: 4:01:22, batch_cost: 0.29082 sec, ips: 13.75426 images/sec
省略300->9600
2021-04-30 03:38:51,591-INFO: iter: 9700, lr: 0.000200, 'loss': 'nan', 'loss_cls': 'nan', 'loss_xy': 'nan', 'loss_iou': 'nan', 'loss_iou_aware': 'nan', 'loss_wh': 'nan', 'loss_obj': 'nan', eta: 3:23:52, batch_cost: 0.30354 sec, ips: 13.17803 images/sec
2021-04-30 03:39:20,387-INFO: iter: 9800, lr: 0.000200, 'loss': 'nan', 'loss_cls': 'nan', 'loss_xy': 'nan', 'loss_iou': 'nan', 'loss_iou_aware': 'nan', 'loss_wh': 'nan', 'loss_obj': 'nan', eta: 3:11:28, batch_cost: 0.28578 sec, ips: 13.99693 images/sec
2021-04-30 03:39:51,800-INFO: iter: 9900, lr: 0.000200, 'loss': 'nan', 'loss_cls': 'nan', 'loss_xy': 'nan', 'loss_iou': 'nan', 'loss_iou_aware': 'nan', 'loss_wh': 'nan', 'loss_obj': 'nan', eta: 3:29:45, batch_cost: 0.31385 sec, ips: 12.74514 images/sec
2021-04-30 03:40:21,426-INFO: iter: 10000, lr: 0.000200, 'loss': 'nan', 'loss_cls': 'nan', 'loss_xy': 'nan', 'loss_iou': 'nan', 'loss_iou_aware': 'nan', 'loss_wh': 'nan', 'loss_obj': 'nan', eta: 3:17:30, batch_cost: 0.29625 sec, ips: 13.50191 images/sec
2021-04-30 03:40:21,678-INFO: Save model to output/ppyolo/10000.
2021-04-30 03:40:25,949-INFO: Test iter 0
2021-04-30 03:41:18,446-INFO: Test finish iter 33
2021-04-30 03:41:18,446-INFO: Total number of images: 130, inference time: 2.39195352898 fps.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2021-04-30 03:41:18,678-INFO: Start evaluate...
Loading and preparing results...
DONE (t=0.13s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
Traceback (most recent call last):
  File "tools/train.py", line 399, in <module>
    main()
  File "tools/train.py", line 320, in main
    cfg['EvalReader']['dataset'])
  File "/paddle/PaddleDetection/PaddleDetection/ppdet/utils/eval_utils.py", line 241, in eval_results
    save_only=save_only)
  File "/paddle/PaddleDetection/PaddleDetection/ppdet/utils/coco_eval.py", line 102, in bbox_eval
    map_stats = cocoapi_eval(outfile, 'bbox', coco_gt=coco_gt)
  File "/paddle/PaddleDetection/PaddleDetection/ppdet/utils/coco_eval.py", line 245, in cocoapi_eval
    coco_eval.evaluate()
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/pycocotools/cocoeval.py", line 157, in evaluate
    for imgId in p.imgIds
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/pycocotools/cocoeval.py", line 251, in evaluateImg
    if g['ignore'] or (g['area']<aRng[0] or g['area']>aRng[1]):
KeyError: 'area'
```

**Comment by wangxinxin08** [comment]
生成的coco数据集的标注文件中没有area字段，请按照coco的标注格式为每一个annotations添加area字段

**Comment by GreenValue** [comment]
annotations添加area字段，当然可以。area的值是多少呢？

**Comment by GreenValue** [comment]
有何高见？area是啥意思？也没找打相关的注释。

**Comment by wangxinxin08** [comment]
请仔细查阅coco数据集的定义https://cocodataset.org/#format-data，或者利用别人验证过的脚本生成coco数据。area字段的意思是bbox的面积。

**Comment by GreenValue** [comment]
instances_train2017.json中 area != width * heigth
那该怎么计算area呢？
![image](https://user-images.githubusercontent.com/16701660/116673563-21cb5000-a9d6-11eb-85cf-65460e898e7d.png)

**Comment by nemonameless** [comment]
COCO数据集的area由于还有实例分割segmentation字段标注，所以是指实例分割mask的面积。area字段是为了测指标时区分大中小物体的AP AR。
自制的检测数据集一般不需要segmentation字段，area字段就是宽高乘积。segmentation字段加上也可以就当成矩形mask给4个点坐标就行，
