### ISSUE TITLE
EfficientNet b7 测试时image ResizeAndPad target_dim不是512就报异常

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleDetection#2833]
试过1024，800，608，480，都报错

architecture: EfficientDet
max_iters: 14000
use_gpu: true
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/EfficientNetB7_pretrained.tar
weights: output/efficientdet_d7/model_final
log_iter: 20
snapshot_iter: 280
metric: COCO
save_dir: output
num_classes: 5
use_ema: true
ema_decay: 0.9998

EfficientDet:
  backbone: EfficientNet
  fpn: BiFPN
  efficient_head: EfficientHead
  anchor_grid: AnchorGrid
  box_loss_weight: 50.

EfficientNet:
  # norm_type: sync_bn
  # TODO
  norm_type: bn
  scale: b7
  use_se: true

BiFPN:
  num_chan: 64
  repeat: 3
  levels: 5

EfficientHead:
  repeat: 3
  num_chan: 64
  prior_prob: 0.01
  num_anchors: 9
  gamma: 1.5
  alpha: 0.25
  delta: 0.1
  output_decoder:
    score_thresh: 0.05   # originally 0.
    nms_thresh: 0.5
    pre_nms_top_n: 1000  # originally 5000
    detections_per_im: 100
    nms_eta: 1.0

AnchorGrid:
  anchor_base_scale: 4
  num_scales: 3
  aspect_ratios: [[1, 1], [1.4, 0.7], [0.7, 1.4]]

LearningRate:
  base_lr: 0.001
  schedulers:
  - !CosineDecayWithSkip
    total_steps: 14000
    skip_steps: 560
  - !LinearWarmup
    start_factor: 0.05
    steps: 560

OptimizerBuilder:
  clip_grad_by_norm: 10.
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.00004
    type: L2

TrainReader:
  inputs_def:
    fields: ['image', 'im_id', 'fg_num', 'gt_label', 'gt_target']
  dataset:
    !COCODataSet
    dataset_dir: /home/aistudio/data/wd
    anno_path: annotations/train_c_f5_1.json
    image_dir: images
  sample_transforms:
  - !DecodeImage
    to_rgb: true
  - !RandomFlipImage
    prob: 0.5
  - !NormalizeImage
    is_channel_first: false
    is_scale: true
    mean: [0.485,0.456,0.406]
    std: [0.229, 0.224,0.225]
  - !RandomScaledCrop
    target_dim: 512
    scale_range: [1., 2.8]
    interp: 1
  - !Permute
    to_bgr: false
    channel_first: true
  - !TargetAssign
    image_size: 512
  batch_size: 4
  shuffle: true
  worker_num: 32
  bufsize: 16
  use_process: true
  drop_empty: false

EvalReader:
  inputs_def:
    fields: ['image', 'im_info', 'im_id']
  dataset:
    !COCODataSet
    dataset_dir: /home/aistudio/data/wd
    anno_path: annotations/eval_c_f5_1.json
    image_dir: images
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !NormalizeImage
    is_channel_first: false
    is_scale: true
    mean: [0.485,0.456,0.406]
    std: [0.229, 0.224,0.225]
  - !ResizeAndPad
    target_dim: 1024
    interp: 1
  - !Permute
    channel_first: true
    to_bgr: false
  drop_empty: false
  batch_size: 4
  shuffle: false
  worker_num: 2

TestReader:
  inputs_def:
    fields: ['image', 'im_info', 'im_id']
    image_shape: [3, 512, 512]
  dataset:
    !ImageFolder
    anno_path: /home/aistudio/data/wd/annotations/eval_c_f5_1.json
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !NormalizeImage
    is_channel_first: false
    is_scale: true
    mean: [0.485,0.456,0.406]
    std: [0.229, 0.224,0.225]
  - !ResizeAndPad
    target_dim: 512
    interp: 1
  - !Permute
    channel_first: true
    to_bgr: false
  batch_size: 4
  shuffle: false

Traceback (most recent call last):
  File "/home/aistudio/PaddleDetection-master/tools/train.py", line 405, in <module>
    main()
  File "/home/aistudio/PaddleDetection-master/tools/train.py", line 322, in main
    resolution=resolution)
  File "/home/aistudio/PaddleDetection-master/ppdet/utils/eval_utils.py", line 148, in eval_run
    return_numpy=False)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1110, in run
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1108, in run
    return_merged=return_merged)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1252, in _run_impl
    return_merged=return_merged)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 913, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
ValueError: In user code:

    File "/home/aistudio/PaddleDetection-master/tools/train.py", line 405, in <module>
      main()
    File "/home/aistudio/PaddleDetection-master/tools/train.py", line 170, in main
      fetches = model.eval(feed_vars)
    File "/home/aistudio/PaddleDetection-master/ppdet/modeling/architectures/efficientdet.py", line 147, in eval
      return self.build(feed_vars, 'test')
    File "/home/aistudio/PaddleDetection-master/ppdet/modeling/architectures/efficientdet.py", line 86, in build
      im_info)
    File "/home/aistudio/PaddleDetection-master/ppdet/modeling/anchor_heads/efficient_head.py", line 162, in get_prediction
      im_info=im_info)
    File "/home/aistudio/PaddleDetection-master/ppdet/core/workspace.py", line 179, in partial_apply
      return op(*args, **kwargs_)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/detection.py", line 3257, in retinanet_detection_output
      outputs={'Out': output})
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3225, in append_op
      attrs=kwargs.get("attrs", None))
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2305, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The 1st dimension of each Variables in Input(Anchors) must be equal to the 2nd dimension of corresponding Variables in Input(BBoxes), which represents the number of the predicted boxes, but received Anchors 1st dimension is:36864, BBoxes 2nd dimension is:147456.
      [Hint: Expected anchor_dims[0] == bbox_dims[1], but received anchor_dims[0]:36864 != bbox_dims[1]:147456.] (at /paddle/paddle/fluid/operators/detection/retinanet_detection_output_op.cc:134)
      [operator < retinanet_detection_output > error]
terminate called without an active exception

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1619760295 (unix time) try "date -d @1619760295" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e800006dbe) received by PID 28094 (TID 0x7fc33dcb3700) from PID 28094 ***]

Segmentation fault (core dumped)

**Comment by wangxinxin08** [comment]
请问使用PaddleDetection版本是什么？

**Comment by bbbxixixixi** [comment]
> 请问使用PaddleDetection版本是什么？

paddle master， aistudio环境，换了devolop版本的paddlepaddle_gpu-2.1.0.dev0.post101-cp37-cp37m-linux_x86_64.whl
