### ISSUE TITLE
报错：ValueError: Module class already registered: ImageFolder

### ISSUE THREAD

**Issue by 670133189** [PaddlePaddle/PaddleDetection#2846]
最新版，执行“快速体验”的infer.py，提示：
`
Traceback (most recent call last):
  File "/Library/yinian/python/function/paddlepaddle/paddle_detection/tools/train.py", line 38, in <module>
    from python.function.paddlepaddle.paddle_detection.ppdet.core.workspace import (
  File "/Library/yinian/python/function/paddlepaddle/paddle_detection/ppdet/__init__.py", line 15, in <module>
    from . import (core, data, engine, modeling, model_zoo, optimizer, metrics,
  File "/Library/yinian/python/function/paddlepaddle/paddle_detection/ppdet/data/__init__.py", line 15, in <module>
    from . import source
  File "/Library/yinian/python/function/paddlepaddle/paddle_detection/ppdet/data/source/__init__.py", line 15, in <module>
    from . import coco
  File "/Library/yinian/python/function/paddlepaddle/paddle_detection/ppdet/data/source/coco.py", line 18, in <module>
    from .dataset import DetDataset
  File "/Library/yinian/python/function/paddlepaddle/paddle_detection/ppdet/data/source/dataset.py", line 133, in <module>
    class ImageFolder(DetDataset):
  File "/Library/yinian/python/function/paddlepaddle/paddle_detection/ppdet/core/workspace.py", line 195, in register
    cls.__name__))
ValueError: Module class already registered: ImageFolder
`

**Comment by just1226** [comment]
请问你怎么解决的？

**Comment by mllife** [comment]
any solution to this?

**Comment by chhchhchh** [comment]
请问怎么解决的？
