### ISSUE TITLE
请问一下转换到onnx模块报错的问题怎么处理

### ISSUE THREAD

**Issue by duolabmeng6** [PaddlePaddle/PaddleDetection#2865]
```
PS C:\2021dl\PaddleDetection\output_inference\paddle2onnx> paddle2onnx -m C:/2021dl/PaddleDetection/output_inference/yolov3_mobilenet_v1_roadsign --model_filename model.pdmodel --params_filename model.pdiparams -s C:/2021dl/PaddleDetection/output_inference/model.onnx --opset_version 11
Traceback (most recent call last):
  File "C:\Users\csuil\Anaconda3\Scripts\paddle2onnx-script.py", line 11, in <module>
    load_entry_point('paddle2onnx==0.6', 'console_scripts', 'paddle2onnx')()
  File "c:\users\csuil\anaconda3\lib\site-packages\paddle2onnx-0.6-py3.7.egg\paddle2onnx\command.py", line 142, in main
  File "c:\users\csuil\anaconda3\lib\site-packages\paddle2onnx-0.6-py3.7.egg\paddle2onnx\command.py", line 114, in program2onnx
  File "c:\users\csuil\anaconda3\lib\site-packages\paddle2onnx-0.6-py3.7.egg\paddle2onnx\convert.py", line 77, in program2onnx
  File "c:\users\csuil\anaconda3\lib\site-packages\paddle2onnx-0.6-py3.7.egg\paddle2onnx\convert.py", line 32, in export_onnx
  File "c:\users\csuil\anaconda3\lib\site-packages\paddle2onnx-0.6-py3.7.egg\paddle2onnx\graph\onnx_graph.py", line 229, in build
  File "c:\users\csuil\anaconda3\lib\site-packages\paddle2onnx-0.6-py3.7.egg\paddle2onnx\graph\onnx_graph.py", line 183, in build_op_nodes
  File "c:\users\csuil\anaconda3\lib\site-packages\paddle2onnx-0.6-py3.7.egg\paddle2onnx\op_mapper\op_mapper.py", line 144, in check_support_status
NotImplementedError:
There's 3 ops are not supported yet
=========== logical_not ===========
=========== conditional_block ===========
=========== select_input ===========
```

请问一下这个报错怎么解决 看不懂~~

**Comment by yghstill** [comment]
@duolabmeng6 目前动态图模型转onnx有个别两三个OP不支持，我们正在适配中，可以先使用静态图模型：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0/static
