### ISSUE TITLE
PP-YOLO的模型部署失败

### ISSUE THREAD

**Issue by DeathKnightChen** [PaddlePaddle/PaddleDetection#2893]
在按照README进行PP-YOLO的模型部署时报错，报错信息似乎是动态图转静态图失败，但是不太清楚原因。环境配置是拉取的docker环境进行的配置。报错信息如下：

λ afe5ee05416f /home/ubt/detection/PaddleDetection python tools/export_model.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml -o weights=./models/ppyolo_r50vd_dcn_1x_coco.pdparams

```
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
[05/07 11:56:02] ppdet.utils.checkpoint INFO: Finish loading model weights: ./models/ppyolo_r50vd_dcn_1x_coco.pdparams
[05/07 11:56:02] ppdet.engine INFO: Export inference config file to output_inference/ppyolo_r50vd_dcn_1x_coco/infer_cfg.yml
Traceback (most recent call last):
  File "tools/export_model.py", line 105, in <module>
    main()
  File "tools/export_model.py", line 101, in main
    run(FLAGS, cfg)
  File "tools/export_model.py", line 69, in run
    trainer.export(FLAGS.output_dir)
  File "/home/ubt/detection/PaddleDetection/ppdet/engine/trainer.py", line 460, in export
    input_spec, static_model.forward.main_program,
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 534, in main_program
    concrete_program = self.concrete_program
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 454, in concrete_program
    return self.concrete_program_specify_input_spec(input_spec=None)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program_specify_input_spec
    *desired_input_spec)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 702, in _build_once
    class_instance=cache_key.class_instance)
  File "<decorator-gen-58>", line 2, in from_func_spec
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/dygraph/base.py", line 39, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 658, in from_func_spec
    error_data.raise_new_exception()
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 191, in raise_new_exception
    raise new_exception
AttributeError: In transformed code:

    File "/tmp/tmpJCZlQ8.py", line 27, in forward
        false_fn_1, (), (), (out,))
    File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
        return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
        return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/home/ubt/detection/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 29, in forward (* user code *)
        out = self.get_pred()
    File "/home/ubt/detection/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 75, in get_pred (* user code *)
        bbox_pred, bbox_num = self._forward()
    File "/home/ubt/detection/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 59, in _forward (* user code *)
        body_feats = self.backbone(self.inputs)
    File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_call_func.py", line 220, in convert_call
        forward_func = convert_to_static(forward_func)
    File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 141, in convert_to_static
        static_func = _FUNCTION_CACHE.convert_with_cache(function)
    File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 78, in convert_with_cache
        static_func = self._convert(func)
    File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 116, in _convert
        root_wrapper = self._dygraph_to_static.get_static_ast(root)
    File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/ast_transformer.py", line 61, in get_static_ast
        self.transfer_from_node_type(self.static_analysis_root)
    File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/ast_transformer.py", line 92, in transfer_from_node_type
        self._apply(transformer, node_wrapper, log_level=index + 1)
    File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/ast_transformer.py", line 65, in _apply
        transformer(node_wrapper).transform()
    File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/loop_transformer.py", line 435, in transform
        self.visit(self.root)
    File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/loop_transformer.py", line 438, in visit
        self.generic_visit(node)
    File "/usr/local/python2.7.15/lib/python2.7/ast.py", line 297, in generic_visit
        value = self.visit(value)
    File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/loop_transformer.py", line 441, in visit
        self.replace_stmt_list(node.body)
    File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/loop_transformer.py", line 457, in replace_stmt_list
        new_stmts = self.get_for_stmt_nodes(body_list[i])
    File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/loop_transformer.py", line 479, in get_for_stmt_nodes
        stmts_tuple = current_for_node_parser.parse()
    File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/utils.py", line 1032, in parse
        return self._parse_for_enumerate_stmts()
    File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/utils.py", line 1115, in _parse_for_enumerate_stmts
        target_node, assign_node = self._build_assign_var_slice_node()
    File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/utils.py", line 1245, in _build_assign_var_slice_node
        slice=gast.Index(value=gast.Name(
    AttributeError: 'module' object has no attribute 'Index'
```

期待回复，感谢。

**Comment by qingqing01** [comment]
@DeathKnightChen 看样子是模型导出时失败，您Paddle版本是多少？需要Paddle >= 2.0.1。


```
# ppyolov1
python tools/export_model.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml -o weights=https://paddledet.bj.bcebos.com/models/ppyolo_r50vd_dcn_1x_coco.pdparams
# ppyolov2
python tools/export_model.py -c configs/ppyolo/ppyolov2_r50vd_dcn_365e_coco.yml -o weights=https://paddledet.bj.bcebos.com/models/ppyolov2_r50vd_dcn_365e_coco.pdparams
```

**Comment by DeathKnightChen** [comment]
@qingqing01 是的，模型导出失败，paddle版本2.0.2，我是参照https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/configs/ppyolo/README_cn.md 操作的。

**Comment by qingqing01** [comment]
参考这个文档没错。我本地使用上面我贴的命令是可以导出。你试下上面命令呢？

**Comment by DeathKnightChen** [comment]
@qingqing01 试了下一样的命令还是不行，我之前只是把.pdparams的模型下载下来然后跑，其实是一样的

**Comment by DeathKnightChen** [comment]
补充下，我执行的是python tools/export_model.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml -o weights=https://paddledet.bj.bcebos.com/models/ppyolo_r50vd_dcn_1x_coco.pdparams

**Comment by Aurelius84** [comment]
@DeathKnightChen 可以看下pip list 中gast的版本是多少么？pip install gast==0.4.0 试下

**Comment by DeathKnightChen** [comment]
@Aurelius84 我看了下，我这边已经是0.4.0了，还是不可以：
![image](https://user-images.githubusercontent.com/11343387/117525223-cd3a5d00-aff3-11eb-85e8-2f750f9dd1eb.png)

**Comment by Aurelius84** [comment]
pip install gast==0.3.3 试下呢？ @DeathKnightChen

**Comment by DeathKnightChen** [comment]
@Aurelius84 换成gast==0.3.3之后解决了，感谢！

**Comment by oldZhangYH** [comment]
万分感谢！

**Comment by oldZhangYH** [comment]
万分感谢！
