### ISSUE TITLE
请问下ppyolov2是否支持转onnx

### ISSUE THREAD

**Issue by DeathKnightChen** [PaddlePaddle/PaddleDetection#2904]
我想将ppyolov2转换为onnx模型，过程中遇到如下问题：

我首先执行如下命令将ppyolov2成功导出模型
python3 tools/export_model.py -c configs/ppyolo/ppyolov2_r50vd_dcn_365e_coco.yml -o weights=./models/ppyolov2_r50vd_dcn_365e_coco.pdparams

然后参照https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/README_zh.md，执行如下命令：
paddle2onnx --model_dir output_inference/ppyolov2_r50vd_dcn_365e_coco/  --model_filename model.pdmodel --params_filename model.pdiparams --save_file onnx_file --opset_version 10 --enable_onnx_checker True

产生报错，似乎是模型里有无法支持转换的op，想请问下如何解决：

λ afe5ee05416f /home/ubt/detection/PaddleDetection paddle2onnx --model_dir output_inference/ppyolov2_r50vd_dcn_365e_coco/  --model_filename model.pdmodel --params_filename model.pdiparams --save_file onnx_file --opset_version 10 --enable_onnx_checker True
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
  File "/usr/local/python2.7.15/bin/paddle2onnx", line 8, in <module>
    sys.exit(main())
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle2onnx/command.py", line 142, in main
    enable_onnx_checker=args.enable_onnx_checker)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle2onnx/command.py", line 114, in program2onnx
    enable_onnx_checker=enable_onnx_checker)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle2onnx/convert.py", line 77, in program2onnx
    export_onnx(paddle_graph, save_file, opset_version, enable_onnx_checker)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle2onnx/convert.py", line 32, in export_onnx
    onnx_graph = ONNXGraph.build(paddle_graph, opset_version, verbose)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle2onnx/graph/onnx_graph.py", line 229, in build
    onnx_graph.build_op_nodes(paddle_graph.node_map)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle2onnx/graph/onnx_graph.py", line 183, in build_op_nodes
    OpMapper.check_support_status(node_map, self.opset_version)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 144, in check_support_status
    raise NotImplementedError(error_info)
NotImplementedError:
There's 4 ops are not supported yet
=========== softplus ===========
=========== logical_not ===========
=========== select_input ===========
=========== conditional_block ===========

**Comment by heavengate** [comment]
您好，这些op是onnx不支持的op，PP-YOLOv2组网中用到了这些op，目前看应该是没法转onnx的，你如果需要部署上线可以考虑使用Paddle 的预测库，我们也在`deploy`文件夹下提供了python和c++的部署方案
https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0/deploy

**Comment by DeathKnightChen** [comment]
@heavengate 我看ppyolov2里有公开tensorrt的性能，这个好像也是paddle预测库跑的，但是我看了下tensorrt好像不支持deformable conv操作，那用paddle预测库跑ppyolov2的tensorrt是如何跑起来的呢，想请教下
