### ISSUE TITLE
用PP YOLOV3 训练自己的数据集时报错，数据集为VOC格式

### ISSUE THREAD

**Issue by ANewAnonymous** [PaddlePaddle/PaddleDetection#2906]
`[05/09 00:10:24] ppdet.utils.checkpoint INFO: Finish loading model weights: C:\Users\Administrator/.cache/paddle/weights\MobileNetV3_large_x1_0_ssld_pretrained.pdparams
[05/09 00:10:24] ppdet.engine INFO: Epoch: [0] [   0/9253] learning_rate: 0.000000 loss_xy: 2.381373 loss_wh: 1.357681 loss_obj: 5604.918945 loss_cls: 94.689812 loss: 5703.348145 eta: 12 days, 16:13:11 batch_cost: 0.4384 data_cost: 0.0000 ips: 2.2812 images/s
[05/09 00:10:33] ppdet.engine INFO: Epoch: [0] [  20/9253] learning_rate: 0.000020 loss_xy: 2.545311 loss_wh: 3.204695 loss_obj: 199.944992 loss_cls: 87.086288 loss: 305.245789 eta: 12 days, 2:09:00 batch_cost: 0.4171 data_cost: 0.0001 ips: 2.3976 images/s
[05/09 00:10:41] ppdet.engine INFO: Epoch: [0] [  40/9253] learning_rate: 0.000040 loss_xy: 2.651653 loss_wh: 2.547644 loss_obj: 11.167763 loss_cls: 72.390358 loss: 91.002365 eta: 12 days, 1:28:26 batch_cost: 0.4161 data_cost: 0.0003 ips: 2.4032 images/s
[05/09 00:10:51] ppdet.engine INFO: Epoch: [0] [  60/9253] learning_rate: 0.000060 loss_xy: 2.350936 loss_wh: 2.487527 loss_obj: 15.108137 loss_cls: 60.733986 loss: 80.522614 eta: 12 days, 14:50:45 batch_cost: 0.4759 data_cost: 0.0003 ips: 2.1012 images/s
[05/09 00:11:08] ppdet.engine INFO: Epoch: [0] [  80/9253] learning_rate: 0.000080 loss_xy: 3.167575 loss_wh: 3.702170 loss_obj: 12.421366 loss_cls: 47.325302 loss: 66.312775 eta: 15 days, 18:11:38 batch_cost: 0.8762 data_cost: 0.4045 ips: 1.1413 images/s
[05/09 00:11:18] ppdet.engine INFO: Epoch: [0] [ 100/9253] learning_rate: 0.000100 loss_xy: 2.372241 loss_wh: 1.932639 loss_obj: 9.906717 loss_cls: 29.659752 loss: 43.857235 eta: 15 days, 13:36:18 batch_cost: 0.5116 data_cost: 0.0457 ips: 1.9546 images/s
[05/09 00:11:28] ppdet.engine INFO: Epoch: [0] [ 120/9253] learning_rate: 0.000120 loss_xy: 2.818606 loss_wh: 3.681616 loss_obj: 9.013128 loss_cls: 20.899113 loss: 36.215240 eta: 15 days, 3:47:20 batch_cost: 0.4528 data_cost: 0.0002 ips: 2.2084 images/s
[05/09 00:11:36] ppdet.engine INFO: Epoch: [0] [ 140/9253] learning_rate: 0.000140 loss_xy: 2.993014 loss_wh: 3.415243 loss_obj: 6.683055 loss_cls: 18.022484 loss: 36.612831 eta: 14 days, 18:49:30 batch_cost: 0.4332 data_cost: 0.0006 ips: 2.3084 images/s
[05/09 00:11:45] ppdet.engine INFO: Epoch: [0] [ 160/9253] learning_rate: 0.000160 loss_xy: 2.868083 loss_wh: 3.355999 loss_obj: 6.923729 loss_cls: 11.347593 loss: 26.361303 eta: 14 days, 12:43:23 batch_cost: 0.4406 data_cost: 0.0002 ips: 2.2698 images/s
[05/09 00:12:29] ppdet.engine INFO: Epoch: [0] [ 180/9253] learning_rate: 0.000180 loss_xy: 2.818301 loss_wh: 6.482400 loss_obj: 7.661506 loss_cls: 11.026241 loss: 27.840763 eta: 19 days, 23:00:09 batch_cost: 2.2016 data_cost: 1.3847 ips: 0.4542 images/s
[05/09 00:12:56] ppdet.engine INFO: Epoch: [0] [ 200/9253] learning_rate: 0.000200 loss_xy: 2.617385 loss_wh: 6.140785 loss_obj: 9.099451 loss_cls: 12.590986 loss: 36.769894 eta: 21 days, 17:51:40 batch_cost: 1.3111 data_cost: 0.0010 ips: 0.7627 images/s
[05/09 00:13:18] ppdet.engine INFO: Epoch: [0] [ 220/9253] learning_rate: 0.000220 loss_xy: 2.929544 loss_wh: 4.452159 loss_obj: 8.278836 loss_cls: 9.071093 loss: 27.495686 eta: 22 days, 15:46:55 batch_cost: 1.1012 data_cost: 0.0012 ips: 0.9081 images/s
D:\Development\DevelopmentEnvironment\anaconda3\envs\paddle202\lib\site-packages\ppdet\data\reader.py:59: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn("fail to map op [{}] with error: {} and stack:\n{}".
[05/09 00:13:28] reader WARNING: fail to map op [Decode_1068e4] with error: OpenCV(4.5.2) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-vi271kac\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'
 and stack:
Traceback (most recent call last):
  File "D:\Development\DevelopmentEnvironment\anaconda3\envs\paddle202\lib\site-packages\ppdet\data\reader.py", line 56, in __call__
    data = f(data)
  File "D:\Development\DevelopmentEnvironment\anaconda3\envs\paddle202\lib\site-packages\ppdet\data\transform\operators.py", line 99, in __call__
    sample[i] = self.apply(sample[i], context)
  File "D:\Development\DevelopmentEnvironment\anaconda3\envs\paddle202\lib\site-packages\ppdet\data\transform\operators.py", line 126, in apply
    im = cv2.cvtColor(im, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.5.2) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-vi271kac\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

2021-05-09 00:13:28,554 - WARNING - DataLoader reader thread raised an exception.
[WARNING 2021-05-09 00:13:28,554 dataloader_iter.py:345] DataLoader reader thread raised an exception.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "D:\Development\DevelopmentEnvironment\anaconda3\envs\paddle202\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\Development\DevelopmentEnvironment\anaconda3\envs\paddle202\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Development\DevelopmentEnvironment\anaconda3\envs\paddle202\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 346, in _thread_loop
    six.reraise(*sys.exc_info())
  File "D:\Development\DevelopmentEnvironment\anaconda3\envs\paddle202\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "D:\Development\DevelopmentEnvironment\anaconda3\envs\paddle202\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 317, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices)
  File "D:\Development\DevelopmentEnvironment\anaconda3\envs\paddle202\lib\site-packages\paddle\fluid\dataloader\fetcher.py", line 60, in fetch
    data = [self.dataset[idx] for idx in batch_indices]
  File "D:\Development\DevelopmentEnvironment\anaconda3\envs\paddle202\lib\site-packages\paddle\fluid\dataloader\fetcher.py", line 60, in <listcomp>
    data = [self.dataset[idx] for idx in batch_indices]
  File "D:\Development\DevelopmentEnvironment\anaconda3\envs\paddle202\lib\site-packages\ppdet\data\source\dataset.py", line 87, in __getitem__
    return self.transform(roidb)
  File "D:\Development\DevelopmentEnvironment\anaconda3\envs\paddle202\lib\site-packages\ppdet\data\reader.py", line 61, in __call__
    raise e
  File "D:\Development\DevelopmentEnvironment\anaconda3\envs\paddle202\lib\site-packages\ppdet\data\reader.py", line 56, in __call__
    data = f(data)
  File "D:\Development\DevelopmentEnvironment\anaconda3\envs\paddle202\lib\site-packages\ppdet\data\transform\operators.py", line 99, in __call__
    sample[i] = self.apply(sample[i], context)
  File "D:\Development\DevelopmentEnvironment\anaconda3\envs\paddle202\lib\site-packages\ppdet\data\transform\operators.py", line 126, in apply
    im = cv2.cvtColor(im, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.5.2) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-vi271kac\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 111, in run
    trainer.train(FLAGS.eval)
  File "D:\Development\DevelopmentEnvironment\anaconda3\envs\paddle202\lib\site-packages\ppdet\engine\trainer.py", line 256, in train
    for step_id, data in enumerate(self.loader):
  File "D:\Development\DevelopmentEnvironment\anaconda3\envs\paddle202\lib\site-packages\ppdet\data\reader.py", line 216, in __next__
    data = next(self.loader)
  File "D:\Development\DevelopmentEnvironment\anaconda3\envs\paddle202\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 351, in __next__
    return self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at D:\v2.0.2\paddle\paddle/fluid/operators/reader/blocking_queue.h:158)`

**Comment by ANewAnonymous** [comment]
我发现了，是由于我的数据集中的图片格式问题，部分图片格式为gif格式，所以导致训练时出错
