### ISSUE TITLE
infer.py

### ISSUE THREAD

**Issue by EdwardVincentMa** [PaddlePaddle/PaddleDetection#2925]
你好，之前是静态图动态图的问题。
然后我用了你给的全重和参数文件，文什么报这个错误？

(base) mayc1@xt021pc2101001:~/PyProject/PaddleDetection$ python3 tools/infer.py -c configs/ppyolo/ppyolov2_r50vd_dcn_365e_coco.yml -o use_gpu=true weights=config/ppyolo/ppyolov2_r50vd_dcn_365e_coco.pdparams --infer_img=demo/000000014439.jpg

W0510 15:11:36.582141 1675283 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.0
W0510 15:11:36.583467 1675283 device_context.cc:372] device: 0, cuDNN Version: 8.0.
Traceback (most recent call last):
  File "tools/infer.py", line 162, in <module>
    main()
  File "tools/infer.py", line 158, in main
    run(FLAGS, cfg)
  File "tools/infer.py", line 123, in run
    trainer.load_weights(cfg.weights)
  File "/home/mayc1/anaconda3/lib/python3.8/site-packages/ppdet/engine/trainer.py", line 204, in load_weights
    load_pretrain_weight(self.model, weights)
  File "/home/mayc1/anaconda3/lib/python3.8/site-packages/ppdet/utils/checkpoint.py", line 151, in load_pretrain_weight
    raise ValueError("Model pretrain path `{}` does not exists. "
ValueError: Model pretrain path `config/ppyolo/ppyolov2_r50vd_dcn_365e_coco` does not exists. If you don't want to load pretrain model, please delete `pretrain_weights` field in config file.

**Comment by qingzwang** [comment]
Have the same problem, can any one help to solve it?
