### ISSUE TITLE
Unable to install paddledet, (windows and linux) - receive 'no module named paddle'

### ISSUE THREAD

**Issue by lessw2020** [PaddlePaddle/PaddleDetection#2958]
Hi there,
I've attempted to install paddledet on both a Windows10 and a Linux server and both end up with the same final issue.
1 - I installed via the instructions here:
https://aistudio.baidu.com/aistudio/projectdetail/1885319

(paddle) C:\Users\ls\PaddleDetection>python ppdet/modeling/tests/test_architectures.py
Traceback (most recent call last):
  File "C:\Users\ls\PaddleDetection\ppdet\modeling\tests\test_architectures.py", line 20, in <module>
    import ppdet
  File "C:\Users\ls\anaconda3\envs\paddle\lib\site-packages\ppdet\__init__.py", line 15, in <module>
    from . import (core, data, engine, modeling, model_zoo, optimizer, metrics,
  File "C:\Users\ls\anaconda3\envs\paddle\lib\site-packages\ppdet\data\__init__.py", line 15, in <module>
    from . import source
  File "C:\Users\ls\anaconda3\envs\paddle\lib\site-packages\ppdet\data\source\__init__.py", line 15, in <module>
    from . import coco
  File "C:\Users\ls\anaconda3\envs\paddle\lib\site-packages\ppdet\data\source\coco.py", line 18, in <module>
    from .dataset import DetDataset
  File "C:\Users\ls\anaconda3\envs\paddle\lib\site-packages\ppdet\data\source\dataset.py", line 22, in <module>
    from paddle.io import Dataset
ModuleNotFoundError: No module named 'paddle'

I also attempted to install via the requirements.txt and then setup.py with no success.

Can you clarify how to actually get a working install?   

Note that I also checked the Install link to find a solution on the homepage, but it does not work:
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/docs/tutorials/INSTALL_en.md

This looks like a really nice framework for mobile, but at this point it's quite hard to actually get it running via the install directions..so hope you can assist.
Thanks!

**Comment by wangxinxin08** [comment]
please refer to https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/docs/tutorials/INSTALL.md#1-install-paddlepaddle. First, you should install PaddlePaddle, which is a deep learning framework.

**Comment by heavengate** [comment]
鉴于问题已经解决，当前issue关闭，如果还有问题可以reopen此issue~
