### ISSUE TITLE
如何训练自己的数据集（voc格式）

### ISSUE THREAD

**Issue by EdwardVincentMa** [PaddlePaddle/PaddleDetection#2971]
你好，请问有训练自己数据集的文档吗，我现在可以训练voc数据集，他会download voc然后训练，但是我想训练自己的数据集，我将ppyolo_tiny_650e_voc_bdd.yml文件修改如下：
![Screenshot from 2021-05-12 18-08-40](https://user-images.githubusercontent.com/39480728/117957980-2506fa00-b34d-11eb-9743-9c1d03e9d2dc.png)

下面是bdd.yml也修改了：
![Screenshot from 2021-05-12 18-09-43](https://user-images.githubusercontent.com/39480728/117958217-626b8780-b34d-11eb-8363-91fcff79fb74.png)数据集

然后在.cache/paddle/dataset下建一个bdd的文件夹，装着数据，trainval.txt, test.txt
![Screenshot from 2021-05-12 18-17-50](https://user-images.githubusercontent.com/39480728/117959243-64821600-b34e-11eb-9329-e9a422a3234d.png)
ppyolo_tiny_650e_voc_bdd.yml

但是训练的时候还是会download并报错：

python -m paddle.distributed.launch --log_dir=./ppyolo_dygraph/ --gpus 0 tools/train.py -c configs/ppyolo/ppyolo_tiny_650e_voc_bdd.yml |&tee train_ppyolo_tiny_voc_20210512.lo

launch train in GPU mode
W0512 18:12:33.928426 802777 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.0
W0512 18:12:33.929523 802777 device_context.cc:372] device: 0, cuDNN Version: 8.0.
[05/12 18:12:35] ppdet.utils.download INFO: Dataset /home/mayc1/PyProject/PaddleDetection/dataset/bdd is not valid for reason above, try searching /home/mayc1/.cache/paddle/dataset or downloading dataset...
Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 102, in run
    trainer = Trainer(cfg, mode='train')
  File "/home/mayc1/anaconda3/lib/python3.8/site-packages/ppdet/engine/trainer.py", line 73, in __init__
    self.loader = create('{}Reader'.format(self.mode.capitalize()))(
  File "/home/mayc1/anaconda3/lib/python3.8/site-packages/ppdet/data/reader.py", line 169, in __call__
    self.dataset.check_or_download_dataset()
  File "/home/mayc1/anaconda3/lib/python3.8/site-packages/ppdet/data/source/dataset.py", line 90, in check_or_download_dataset
    self.dataset_dir = launch train in GPU mode
W0512 18:12:33.928426 802777 device_cont数据集ext.cc:362] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.0
W0512 18:12:33.929523 802777 device_context.cc:372] device: 0, cuDNN Version: 8.0.
[05/12 18:12:35] ppdet.utils.download INFO: Dataset /home/mayc1/PyProject/PaddleDetection/dataset/bdd is not valid for reason above, try searching /home/mayc1/.cache/paddle/dataset or downloading dataset...
Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 102, in run
    trainer = Trainer(cfg, mode='train')
  File "/home/mayc1/anaconda3/lib/python3.8/site-packages/ppdet/engine/trainer.py", line 73, in __init__
    self.loader = create('{}Reader'.format(self.mode.capitalize()))(
  File "/home/mayc1/anaconda3/lib/python3.8/site-packages/ppdet/data/reader.py", line 169, in __call__
    self.dataset.check_or_download_dataset()
  File "/home/mayc1/anaconda3/lib/python3.8/site-packages/ppdet/data/source/dataset.py", line 90, in check_or_download_dataset
    self.dataset_dir = get_dataset_path(self.dataset_dir, self.anno_path,
  File "/home/mayc1/anaconda3/lib/python3.8/site-packages/ppdet/utils/download.py", line 206, in get_dataset_path
    raise ValueError(
ValueError: Dataset dataset/bdd is not valid and cannot parse dataset type 'bdd' for automaticly downloading, which only supports 'voc' , 'coco', 'wider_face', 'fruit' and 'roadsign_voc' currently
get_dataset_path(self.dataset_dir, self.anno_path,
  File "/home/mayc1/anaconda3/lib/python3.8/site-packages/ppdet/utils/download.py", line 206, in get_dataset_path
    raise ValueError(
ValueError: Dataset dataset/bdd is not valid and cannot parse dataset type 'bdd' for automaticly downloading, which only supports 'voc' , 'coco', 'wider_face', 'fruit' and 'roadsign_voc' currently

在create_list.py中有download代码：
import sys
import os.path as osp
import logging
# add python path of PadleDetection to sys.path
parent_path = osp.abspath(osp.join(__file__, *(['..'] * 3)))
if parent_path not in sys.path:
    sys.path.append(parent_path)

from ppdet.utils.download import create_voc_list

logging.basicConfig(level=logging.INFO)

voc_path = osp.split(osp.realpath(sys.argv[0]))[0]
create_voc_list(voc_path)

但是注释了以后不起作用，请问应该如何训练自己的数据集

**Comment by EdwardVincentMa** [comment]
> 你好，请问有训练自己数据集的文档吗，我现在可以训练voc数据集，他会download voc然后训练，但是我想训练自己的数据集，我将ppyolo_tiny_650e_voc_bdd.yml文件修改如下：
> ![Screenshot from 2021-05-12 18-08-40](https://user-images.githubusercontent.com/39480728/117957980-2506fa00-b34d-11eb-9743-9c1d03e9d2dc.png)
> 
> 下面是bdd.yml也修改了：
> ![Screenshot from 2021-05-12 18-09-43](https://user-images.githubusercontent.com/39480728/117958217-626b8780-b34d-11eb-8363-91fcff79fb74.png)数据集
> 
> 然后在.cache/paddle/dataset下建一个bdd的文件夹，装着数据，trainval.txt, test.txt
> ![Screenshot from 2021-05-12 18-17-50](https://user-images.githubusercontent.com/39480728/117959243-64821600-b34e-11eb-9329-e9a422a3234d.png)
> ppyolo_tiny_650e_voc_bdd.yml
> 
> 但是训练的时候还是会download并报错：
> 
> python -m paddle.distributed.launch --log_dir=./ppyolo_dygraph/ --gpus 0 tools/train.py -c configs/ppyolo/ppyolo_tiny_650e_voc_bdd.yml |&tee train_ppyolo_tiny_voc_20210512.lo
> 
> launch train in GPU mode
> W0512 18:12:33.928426 802777 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.0
> W0512 18:12:33.929523 802777 device_context.cc:372] device: 0, cuDNN Version: 8.0.
> [05/12 18:12:35] ppdet.utils.download INFO: Dataset /home/mayc1/PyProject/PaddleDetection/dataset/bdd is not valid for reason above, try searching /home/mayc1/.cache/paddle/dataset or downloading dataset...
> Traceback (most recent call last):
> File "tools/train.py", line 140, in
> main()
> File "tools/train.py", line 136, in main
> run(FLAGS, cfg)
> File "tools/train.py", line 102, in run
> trainer = Trainer(cfg, mode='train')
> File "/home/mayc1/anaconda3/lib/python3.8/site-packages/ppdet/engine/trainer.py", line 73, in **init**
> self.loader = create('{}Reader'.format(self.mode.capitalize()))(
> File "/home/mayc1/anaconda3/lib/python3.8/site-packages/ppdet/data/reader.py", line 169, in **call**
> self.dataset.check_or_download_dataset()
> File "/home/mayc1/anaconda3/lib/python3.8/site-packages/ppdet/data/source/dataset.py", line 90, in check_or_download_dataset
> self.dataset_dir = launch train in GPU mode
> W0512 18:12:33.928426 802777 device_cont数据集ext.cc:362] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.0
> W0512 18:12:33.929523 802777 device_context.cc:372] device: 0, cuDNN Version: 8.0.
> [05/12 18:12:35] ppdet.utils.download INFO: Dataset /home/mayc1/PyProject/PaddleDetection/dataset/bdd is not valid for reason above, try searching /home/mayc1/.cache/paddle/dataset or downloading dataset...
> Traceback (most recent call last):
> File "tools/train.py", line 140, in
> main()
> File "tools/train.py", line 136, in main
> run(FLAGS, cfg)
> File "tools/train.py", line 102, in run
> trainer = Trainer(cfg, mode='train')
> File "/home/mayc1/anaconda3/lib/python3.8/site-packages/ppdet/engine/trainer.py", line 73, in **init**
> self.loader = create('{}Reader'.format(self.mode.capitalize()))(
> File "/home/mayc1/anaconda3/lib/python3.8/site-packages/ppdet/data/reader.py", line 169, in **call**
> self.dataset.check_or_download_dataset()
> File "/home/mayc1/anaconda3/lib/python3.8/site-packages/ppdet/data/source/dataset.py", line 90, in check_or_download_dataset
> self.dataset_dir = get_dataset_path(self.dataset_dir, self.anno_path,
> File "/home/mayc1/anaconda3/lib/python3.8/site-packages/ppdet/utils/download.py", line 206, in get_dataset_path
> raise ValueError(
> ValueError: Dataset dataset/bdd is not valid and cannot parse dataset type 'bdd' for automaticly downloading, which only supports 'voc' , 'coco', 'wider_face', 'fruit' and 'roadsign_voc' currently
> get_dataset_path(self.dataset_dir, self.anno_path,
> File "/home/mayc1/anaconda3/lib/python3.8/site-packages/ppdet/utils/download.py", line 206, in get_dataset_path
> raise ValueError(
> ValueError: Dataset dataset/bdd is not valid and cannot parse dataset type 'bdd' for automaticly downloading, which only supports 'voc' , 'coco', 'wider_face', 'fruit' and 'roadsign_voc' currently
> 
> 在create_list.py中有download代码：
> import sys
> import os.path as osp
> import logging
> 
> # add python path of PadleDetection to sys.path
> parent_path = osp.abspath(osp.join(**file**, *(['..'] * 3)))
> if parent_path not in sys.path:
> sys.path.append(parent_path)
> 
> from ppdet.utils.download import create_voc_list
> 
> logging.basicConfig(level=logging.INFO)
> 
> voc_path = osp.split(osp.realpath(sys.argv[0]))[0]
> create_voc_list(voc_path)
> 
> 但是注释了以后不起作用，请问应该如何训练自己的数据集



可以训练了，数据集不能放到.cache下面，要放到paddledetetion/dataset下面。
