### ISSUE TITLE
关于动态图的MultiscaleTestResize使用问题

### ISSUE THREAD

**Issue by kali20gakki** [PaddlePaddle/PaddleDetection#3000]
关于动态图的MultiscaleTestResize使用，静态图里面有使用示例，动态图里貌似现在还没有示例，直接添加到EvalReader里也不行

**Comment by heavengate** [comment]
你好，你添加之后的配置文件是怎么样的呢，已经报错信息麻烦给一下

**Comment by kali20gakki** [comment]
@heavengate 感谢回复，
我是按下面这样添加：
EvalReader:
  sample_transforms:
  - Decode: {}
  #- Resize: {interp: 2, target_size: [800, 1333], keep_ratio: True}
  - MultiscaleTestResize: {interp: 2, target_size: [[640, 1333], [672, 1333], [720, 1280], [800, 1333]]}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32, pad_gt: false}
  batch_size: 1
  shuffle: false
  drop_last: false
  drop_empty: false

报错：
  File "tools/eval.py", line 88, in run
    trainer.evaluate()
  File "C:\Users\Mrtutu\anaconda3\envs\paddle\lib\site-packages\ppdet-2.0rc0-py3.7.egg\ppdet\engine\trainer.py", line 283, in evaluate
    self._eval_with_loader(self.loader)
  File "C:\Users\Mrtutu\anaconda3\envs\paddle\lib\site-packages\ppdet-2.0rc0-py3.7.egg\ppdet\engine\trainer.py", line 258, in _eval_with_loader
    for step_id, data in enumerate(loader):
  File "C:\Users\Mrtutu\anaconda3\envs\paddle\lib\site-packages\ppdet-2.0rc0-py3.7.egg\ppdet\data\reader.py", line 181, in __next__
    data = next(self.loader)
  File "C:\Users\Mrtutu\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 351, in __next__
    return self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at D:\v2.0.2\paddle\paddle/fluid/operators/reader/blocking_queue.h:158)

**Comment by heavengate** [comment]
你好，麻烦`reader.yml`里`num_worker: 0`设置一下看看具体报什么错

**Comment by kali20gakki** [comment]
@heavengate  已经设置了 worker_num: 0， 但是报的错貌似和上面一样：
Traceback (most recent call last):
  File "tools/eval.py", line 113, in <module>
    main()
  File "tools/eval.py", line 109, in main
    run(FLAGS, cfg)
  File "tools/eval.py", line 88, in run
    trainer.evaluate()
  File "C:\Users\Mrtutu\anaconda3\envs\paddle\lib\site-packages\ppdet-2.0rc0-py3.7.egg\ppdet\engine\trainer.py", line 283, in evaluate
    self._eval_with_loader(self.loader)
  File "C:\Users\Mrtutu\anaconda3\envs\paddle\lib\site-packages\ppdet-2.0rc0-py3.7.egg\ppdet\engine\trainer.py", line 258, in _eval_with_loader
    for step_id, data in enumerate(loader):
  File "C:\Users\Mrtutu\anaconda3\envs\paddle\lib\site-packages\ppdet-2.0rc0-py3.7.egg\ppdet\data\reader.py", line 181, in __next__
    data = next(self.loader)
  File "C:\Users\Mrtutu\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 351, in __next__
    return self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at D:\v2.0.2\paddle\paddle/fluid/operators/reader/blocking_queue.h:158)

**Comment by heavengate** [comment]
看着是数据集里数据读取有问题，不加`MultiscaleTestResize`能正常跑么

**Comment by kali20gakki** [comment]
> 看着是数据集里数据读取有问题，不加`MultiscaleTestResize`能正常跑么

使用Resize: {interp: 2, target_size: [800, 1333], keep_ratio: True}是可以正常eval的，使用MultiscaleTestResize就报错了
