### ISSUE TITLE
ExternalError:  Cudnn error, CUDNN_STATUS_BAD_PARAM  (at /paddle/paddle/fluid/operators/batch_norm_op.cu:199)       [operator < batch_norm > error]

### ISSUE THREAD

**Issue by Williamlizl** [PaddlePaddle/PaddleDetection#3002]
`ExternalError:  Cudnn error, CUDNN_STATUS_BAD_PARAM  (at /paddle/paddle/fluid/operators/batch_norm_op.cu:199)
      [operator < batch_norm > error]`

--use_gpu=True, 报错; False, 可以运行

安装环境；
ubantu: 16.04.6
cudnn: 7.6.5
cuda: 10.0.130
paddlepaddle:  cuda10.0-cudnn7.6-trt6.0.1.5(paddlepaddle_gpu-2.0.2.post100-cp36-cp36m-linux_x86_64.whl)

**Comment by qingqing01** [comment]
@wilhelmzh 

你本地cuDNN版本是多少？ 一开始一般会打印环境信息，如果安装的PaddlePaddle的cuDNN版本和本地的版本不匹配，会有信息打印，您看下是否匹配

**Comment by heavengate** [comment]
看报错信息像是cuDNN版本不匹配，程序启动的时候应该会打出warning信息，可以看先有没有cuDNN版本的warning信息

**Comment by Williamlizl** [comment]
> 看报错信息像是cuDNN版本不匹配，程序启动的时候应该会打出warning信息，可以看先有没有cuDNN版本的warning信息

--use_gpu=True, 报错; False, 可以运行

安装环境；
ubantu: 16.04.6
cudnn: 7.6.5
cuda: 10.0.130
paddlepaddle: cuda10.0-cudnn7.6-trt6.0.1.5(paddlepaddle_gpu-2.0.2.post100-cp36-cp36m-linux_x86_64.whl)

**Comment by Williamlizl** [comment]
> @wilhelmzh
> 
> 你本地cuDNN版本是多少？ 一开始一般会打印环境信息，如果安装的PaddlePaddle的cuDNN版本和本地的版本不匹配，会有信息打印，您看下是否匹配

`Traceback (most recent call last):
  File "deploy/python/infer.py", line 552, in <module>
    main()
  File "deploy/python/infer.py", line 481, in main
    predict_image(detector)
  File "deploy/python/infer.py", line 410, in predict_image
    results = detector.predict(FLAGS.image_file, FLAGS.threshold)
  File "deploy/python/infer.py", line 139, in predict
    self.predictor.run()
OSError: In user code:

    File "tools/export_model.py", line 104, in <module>
      main()
    File "tools/export_model.py", line 100, in main
      run(FLAGS, cfg)
    File "tools/export_model.py", line 68, in run
      trainer.export(FLAGS.output_dir)
    File "/wilber/repo/PaddleDetection/dygraph/ppdet/engine/trainer.py", line 368, in export
      input_spec, static_model.forward.main_program,
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 534, in main_program
      concrete_program = self.concrete_program
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 454, in concrete_program
      return self.concrete_program_specify_input_spec(input_spec=None)
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 487, in concrete_program_specify_input_spec
      concrete_program, _ = self.get_concrete_program(
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 698, in _build_once
      concrete_program = ConcreteProgram.from_func_spec(
    File "<decorator-gen-58>", line 2, in from_func_spec
      
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/base.py", line 39, in __impl__
      return func(*args, **kwargs)
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 652, in from_func_spec
      outputs = static_func(*inputs)
    File "/tmp/tmphslskxaj.py", line 16, in forward
      out = paddle.jit.dy2static.convert_ifelse(self.training, true_fn_0,
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/wilber/repo/PaddleDetection/dygraph/ppdet/modeling/architectures/meta_arch.py", line 25, in forward
      out = self.get_pred()
    File "/wilber/repo/PaddleDetection/dygraph/ppdet/modeling/architectures/yolo.py", line 63, in get_pred
      bbox_pred, bbox_num = self._forward()
    File "/wilber/repo/PaddleDetection/dygraph/ppdet/modeling/architectures/yolo.py", line 47, in _forward
      body_feats = self.backbone(self.inputs)
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/layers.py", line 902, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/tmp/tmpzzae28eg.py", line 40, in forward
      [__for_loop_var_index_0, x, idx] = paddle.jit.dy2static.convert_while_loop(
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 44, in convert_while_loop
      loop_vars = _run_py_while(cond, body, loop_vars)
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 58, in _run_py_while
      loop_vars = body(*loop_vars)
    File "/wilber/repo/PaddleDetection/dygraph/ppdet/modeling/backbones/resnet.py", line 534, in forward
      x = stage(x)
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/layers.py", line 902, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/tmp/tmp_7anvikg.py", line 18, in forward
      ] = paddle.jit.dy2static.convert_while_loop(for_loop_condition_1,
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 44, in convert_while_loop
      loop_vars = _run_py_while(cond, body, loop_vars)
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 58, in _run_py_while
      loop_vars = body(*loop_vars)
    File "/wilber/repo/PaddleDetection/dygraph/ppdet/modeling/backbones/resnet.py", line 406, in forward
      block_out = block(block_out)
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/layers.py", line 902, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/wilber/repo/PaddleDetection/dygraph/ppdet/modeling/backbones/resnet.py", line 330, in forward
      out = self.branch2b(out)
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/layers.py", line 902, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/tmp/tmp30zfbz1g.py", line 12, in forward
      out = paddle.jit.dy2static.convert_ifelse(self.norm_type in ['bn',
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/wilber/repo/PaddleDetection/dygraph/ppdet/modeling/backbones/resnet.py", line 117, in forward
      out = self.norm(out)
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/layers.py", line 902, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/nn.py", line 1393, in forward
      self._helper.append_op(
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/layer_object_helper.py", line 47, in append_op
      return self.main_program.current_block().append_op(
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/framework.py", line 3017, in append_op
      op = Operator(
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/framework.py", line 2107, in __init__
      for frame in traceback.extract_stack():

    ExternalError:  Cudnn error, CUDNN_STATUS_BAD_PARAM  (at /paddle/paddle/fluid/operators/batch_norm_op.cu:199)
      [operator < batch_norm > error]`

**Comment by heavengate** [comment]
看报错信息里是`batch_norm`里获取cuDNN的状态出错，一般是cuDNN版本不对或者cuDNN没有正确安装之类的问题，可以参考安装文档排查一下cuDNN的安装
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/windows-pip.html

**Comment by Williamlizl** [comment]
> 看报错信息里是`batch_norm`里获取cuDNN的状态出错，一般是cuDNN版本不对或者cuDNN没有正确安装之类的问题，可以参考安装文档排查一下cuDNN的安装
> https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/windows-pip.html

如果服务器中有多版本cuda,包括10.0,10.1,10.2，怎样才能确保paddle 使用的某一个版本的cuda

**Comment by Williamlizl** [comment]
> 看报错信息里是`batch_norm`里获取cuDNN的状态出错，一般是cuDNN版本不对或者cuDNN没有正确安装之类的问题，可以参考安装文档排查一下cuDNN的安装
> https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/windows-pip.html

有针对cudnn 10.5 编译的paddle trt版本吗，cuda =10.0.130
