### ISSUE TITLE
PaddleDetecton install error

### ISSUE THREAD

**Issue by GreenValue** [PaddlePaddle/PaddleDetection#3016]
- Enviroment
paddlepaddle/paddle:2.0.1-gpu-cuda10.0-cudnn7

- cmd

```
pip3 install paddledet==2.0.1 -i https://mirror.baidu.com/pypi/simple
```

- Output
`https://github.com/koalaman/shellcheck/releases/download/` ， 无法访问该url

```
/usr/local/python3.5.1/lib/python3.5/site-packages/OpenSSL/crypto.py:14: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
  from cryptography import utils, x509
Looking in indexes: https://mirror.baidu.com/pypi/simple
Collecting paddledet==2.0.1
  Using cached https://mirror.baidu.com/pypi/packages/e4/d5/7b5175c8ce6c45c59ff5dd161083c7c9503f501a8b3ef4c3984fdee83556/paddledet-2.0.1-py3-none-any.whl (307 kB)
Requirement already satisfied: setuptools>=42.0.0 in /usr/local/python3.5.1/lib/python3.5/site-packages/setuptools-50.3.2-py3.5.egg (from paddledet==2.0.1) (50.3.2)
Collecting opencv-python
  Using cached https://mirror.baidu.com/pypi/packages/e4/b1/291886c324675faadce5f43d0af5fa5078ae4833fc58b2a4d35061ec881d/opencv_python-4.4.0.42-cp35-cp35m-manylinux2014_x86_64.whl (49.4 MB)
Collecting typeguard; python_version >= "3.4"
  Using cached https://mirror.baidu.com/pypi/packages/de/60/8b67e520d3d45bb385322cd0603ad055cebcd4006dc46a74d4f32a3792a9/typeguard-2.2.2-py3-none-any.whl (10 kB)
Collecting pycocotools
  Using cached https://mirror.baidu.com/pypi/packages/de/df/056875d697c45182ed6d2ae21f62015896fdb841906fe48e7268e791c467/pycocotools-2.0.2.tar.gz (23 kB)
Requirement already satisfied: PyYAML in /usr/local/python3.5.1/lib/python3.5/site-packages (from paddledet==2.0.1) (5.3.1)
Collecting shapely
  Using cached https://mirror.baidu.com/pypi/packages/cf/00/4ccaedf7c2805c93aef21116477283b3beb9b6c5a761b08447d51c9f3e0f/Shapely-1.7.1-cp35-cp35m-manylinux1_x86_64.whl (1.0 MB)
Collecting tqdm
  Using cached https://mirror.baidu.com/pypi/packages/72/8a/34efae5cf9924328a8f34eeb2fdaae14c011462d9f0e3fcded48e1266d1c/tqdm-4.60.0-py2.py3-none-any.whl (75 kB)
Collecting visualdl>=2.1.0
  Using cached https://mirror.baidu.com/pypi/packages/41/fa/0e10eb638117be8a6b738022171bf82706609ae4a73f167380fd430541d3/visualdl-2.1.1-py3-none-any.whl (2.6 MB)
Collecting terminaltables
  Using cached https://mirror.baidu.com/pypi/packages/9b/c4/4a21174f32f8a7e1104798c445dacdc1d4df86f2f26722767034e4de4bff/terminaltables-3.1.0.tar.gz (12 kB)
Collecting scipy
  Using cached https://mirror.baidu.com/pypi/packages/c1/60/8cbf00c0deb50a971e6e3a015fb32513960a92867df979870a454481817c/scipy-1.4.1-cp35-cp35m-manylinux1_x86_64.whl (26.0 MB)
Requirement already satisfied: numpy>=1.13.1 in /usr/local/python3.5.1/lib/python3.5/site-packages (from opencv-python->paddledet==2.0.1) (1.18.5)
Collecting cython>=0.27.3
  Using cached https://mirror.baidu.com/pypi/packages/be/f3/a51db275b8fa43391770dd93a88ad42ae41d506345502b88408fc09df1de/Cython-0.29.23-cp35-cp35m-manylinux1_x86_64.whl (1.9 MB)
Collecting matplotlib>=2.1.0
  Using cached https://mirror.baidu.com/pypi/packages/89/61/465fb3bfba684b0f53b5c4829c3c89e86e6fe9fdcdfda93e38f1788090f0/matplotlib-3.0.3-cp35-cp35m-manylinux1_x86_64.whl (13.0 MB)
Requirement already satisfied: protobuf>=3.11.0 in /usr/local/python3.5.1/lib/python3.5/site-packages (from visualdl>=2.1.0->paddledet==2.0.1) (3.15.5)
Collecting flake8>=3.7.9
  Using cached https://mirror.baidu.com/pypi/packages/fc/80/35a0716e5d5101e643404dabd20f07f5528a21f3ef4032d31a49c913237b/flake8-3.9.2-py2.py3-none-any.whl (73 kB)
Requirement already satisfied: Pillow>=7.0.0 in /usr/local/python3.5.1/lib/python3.5/site-packages (from visualdl>=2.1.0->paddledet==2.0.1) (7.2.0)
Requirement already satisfied: pre-commit in /usr/local/python3.5.1/lib/python3.5/site-packages (from visualdl>=2.1.0->paddledet==2.0.1) (1.10.4)
Collecting shellcheck-py
  Using cached https://mirror.baidu.com/pypi/packages/59/5e/cae594fd8a389dec2e7c26368e25cc6285013e0f596008670a21b443d0ad/shellcheck_py-0.7.1.1.tar.gz (3.8 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-okqbv7h9/shellcheck-py/setup.py'"'"'; __file__='"'"'/tmp/pip-install-okqbv7h9/shellcheck-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-okqbv7h9/shellcheck-py/pip-egg-info
         cwd: /tmp/pip-install-okqbv7h9/shellcheck-py/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-okqbv7h9/shellcheck-py/setup.py", line 39
        f'https://github.com/koalaman/shellcheck/releases/download/'
                                                                   ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by jerrywgz** [comment]
you could refer to https://github.com/koalaman/shellcheck/issues/1803 this issue and try python >=3.6
