### ISSUE TITLE
PP yolo 部署批量预测和精度测量

### ISSUE THREAD

**Issue by LIU-FAYANG** [PaddlePaddle/PaddleDetection#3056]
你好，请问现在有支持ppyolo tensorrt部署批量预测的方法吗？有没有可以直接run tensorrt 精度测量的方法呢？

**Comment by wangxinxin08** [comment]
使用TensorRT进行批量预测的方式集讲支持，精度测量在规划中，我理解使用TensorRT测试精度应该没有必要把

**Comment by LIU-FAYANG** [comment]
你好，感谢回复。
我稍微改了一下deploy/python/infer.py尝试批量预测，一部分成功预测，之后出现这个error，请问有遇到过类似的问题吗？


command:
CUDA_VISIBLE_DEVICE=0 python3 deploy/python/infer.py --model_dir=output_inference/ppyolo_r50vd_dcn_1x_coco/ --infer_dir=/home/psl/Desktop/coco2017/val2017_img/ --use_gpu=True --run_mode=trt_int8

Environment: Ubuntu18.04 Cuda 11.1 Tensorrt 7.2.3 Cudnn8 GPU Nvidia Titan X


Inference: 15.664339065551758 ms per batch image
class_id:61, confidence:0.9391, left_top:[20.17,32.34],right_bottom:[462.67,639.00]
save result to: output/000000323202.jpg
Inference: 14.894962310791016 ms per batch image
save result to: output/000000058636.jpg
Inference: 15.837907791137695 ms per batch image
save result to: output/000000431545.jpg
Traceback (most recent call last):
  File "deploy/python/infer.py", line 564, in <module>
    main()
  File "deploy/python/infer.py", line 487, in main
    predict_image(detector)
  File "deploy/python/infer.py", line 412, in predict_image
    results = detector.predict(FLAGS.infer_dir + imge, FLAGS.threshold)
  File "deploy/python/infer.py", line 126, in predict
    input_tensor.copy_from_cpu(inputs[input_names[i]])
OSError: (External)  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/9.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/gpu_info.cc:382)

terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  (External)  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/9.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/gpu_info.cc:553)



--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::~AnalysisPredictor()
1   paddle::AnalysisPredictor::~AnalysisPredictor()
2   paddle::memory::allocation::AllocatorFacade::Release(paddle::platform::Place const&)
3   paddle::memory::allocation::AutoGrowthBestFitAllocator::FreeIdleChunks()
4   paddle::memory::allocation::AlignedAllocation::~AlignedAllocation()
5   paddle::memory::allocation::CUDAAllocator::FreeImpl(paddle::memory::allocation::Allocation*)
6   paddle::framework::SignalHandle(char const*, int)
7   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1621328738 (unix time) try "date -d @1621328738" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e800002275) received by PID 8821 (TID 0x7fa187e05740) from PID 8821 ***]

Aborted (core dumped)

**Comment by wangxinxin08** [comment]
可能存在数组越界，bs>1的预测在develop已经支持，你可以切到develop试下

**Comment by LIU-FAYANG** [comment]
请问切到develop是指什么，要重新安装paddle吗？

**Comment by wangxinxin08** [comment]
在PaddleDetetcion的目录下面使用git checkout -b develop origin/develop切换得到develop分支

**Comment by LIU-FAYANG** [comment]
你好，我试了一下问题依旧存在。

**Comment by wangxinxin08** [comment]
> 你好，我试了一下问题依旧存在。

可以给一下PaddleDetection的commit hash，我们定位下

**Comment by LIU-FAYANG** [comment]
commit f0a30f3ba6095ebfdc8fffb6d02766406afc438a

**Comment by LIU-FAYANG** [comment]
你好，这个问题可能和检测目标为空有关，当连续三张图片检测目标为空时这个问题就会出现，移除这些图片后可以跑。请定位一下问题出在哪
