### ISSUE TITLE
libra_rcnn_r101_vd_fpn_1x multisacletest 报异常'FasterRCNN' object has no attribute 'im_info_names'

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleDetection#3066]
!CUDA_VISIBLE_DEVICES=0 python3 /home/aistudio/PaddleDetection-master/tools/eval.py -c /home/aistudio/libra_rcnn_r101_vd_fpn_1x.yml -o use_gpu=true weights=best_bak/best_model10_10

配置文件

```
MultiScaleTEST:
  score_thresh: 0.05
  nms_thresh: 0.5
  detections_per_im: 100
  enable_voting: true
  vote_thresh: 0.9

EvalReader:
  batch_size: 1
  inputs_def:
    fields: ['image', 'im_info', 'im_id', 'im_shape']
  dataset:
    !COCODataSet
    image_dir: train
    anno_path: split_anno/eval_f5_5.json
    dataset_dir: /home/aistudio/data
  sample_transforms:
  - !DecodeImage
    to_rgb: True
    with_mixup: False
  - !NormalizeImage
    is_channel_first: false
    is_scale: True
    mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
  - !MultiscaleTestResize
    origin_target_size: 720
    origin_max_size: 2400
    target_size:
    - 704
    - 800
    - 864
    - 928
    - 992
    - 1056
    max_size: 2400
    use_flip: true
  - !Permute
    to_bgr: false
  batch_transforms:
  - !PadMultiScaleTest
    pad_to_stride: 32
  worker_num: 1
```

异常信息

```
Traceback (most recent call last):
  File "/home/aistudio/PaddleDetection-master/tools/eval.py", line 193, in <module>
    main()
  File "/home/aistudio/PaddleDetection-master/tools/eval.py", line 86, in main
    fetches = model.eval(feed_vars, multi_scale_test)
  File "/home/aistudio/PaddleDetection-master/ppdet/modeling/architectures/faster_rcnn.py", line 244, in eval
    return self.build_multi_scale(feed_vars)
  File "/home/aistudio/PaddleDetection-master/ppdet/modeling/architectures/faster_rcnn.py", line 155, in build_multi_scale
    for i in range(len(self.im_info_names) // 2):
AttributeError: 'FasterRCNN' object has no attribute 'im_info_names'
```

**Comment by qingqing01** [comment]
@bbbxixixixi 您的PaddleDetection是那个版本？

**Comment by bbbxixixixi** [comment]
> @bbbxixixixi 您的PaddleDetection是那个版本？

paddlepaddle gpu-2.1.0.dev0 post101 
paddledetection master
aistudio删了自带版本重装了上面的

**Comment by qingqing01** [comment]
@bbbxixixixi PaddleDetection现在master分支已废弃，建议使用release稳定分支。 develop是开发分支。
