### ISSUE TITLE
fasterrcnn inference报错-(Fatal) Blocking queue is killed because the data reader raises an exception.

### ISSUE THREAD

**Issue by ximitiejiang** [PaddlePaddle/PaddleDetection#3090]
你好: 
我训练的fasterrcnn模型在infer时偶然报错，一共200张图像进行预测，到中间才报错。
错误提示不太理解，请问可能是什么原因？
```
Traceback (most recent call last):
  File "/home/suliang/suliang_git/PaddleDetection-2.0.0/sl_package/infer.py", line 192, in <module>
    main()
  File "/home/suliang/suliang_git/PaddleDetection-2.0.0/sl_package/infer.py", line 188, in main
    run(FLAGS, cfg)
  File "/home/suliang/suliang_git/PaddleDetection-2.0.0/sl_package/infer.py", line 137, in run
    save_txt=FLAGS.save_txt)
  File "/home/suliang/suliang_git/PaddleDetection-2.0.0/ppdet/engine/trainer.py", line 355, in predict
    for step_id, data in enumerate(loader):
  File "/home/suliang/suliang_git/PaddleDetection-2.0.0/ppdet/data/reader.py", line 216, in __next__
    data = next(self.loader)
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 351, in __next__
    return self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)


Process finished with exit code 1
```

**Comment by heavengate** [comment]
你好，把`configs/faster_rcnn/_base_/faster_reader.yml`里`num_workers`改成0看下具体报啥错呢

**Comment by ximitiejiang** [comment]
config里边我训练时已经是设成0
```
_BASE_: [
  '../configs/datasets/coco_detection.yml',
  '../configs/runtime.yml',
  '../configs/faster_rcnn/_base_/optimizer_1x.yml',
  '../configs/faster_rcnn/_base_/faster_rcnn_r50_fpn.yml',
  '../configs/faster_rcnn/_base_/faster_fpn_reader.yml',
]
weights: /home/suliang/suliang_git/PaddleDetection-2.0.0/sl_package/output/sl_package_faster_rcnn_r50_fpn_1x_coco/model_final.pdparams

num_classes: 3

TrainDataset:
  !COCODataSet
    image_dir: train
    anno_path: annotations/instance_train.json
    dataset_dir: ../dataset/Package/coco_format
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val
    anno_path: annotations/instance_val.json
    dataset_dir: ../dataset/Package/coco_format

TestDataset:
  !ImageFolder
    anno_path: ../dataset/Package/coco_format/annotations/instance_val.json
# from 2 to 0 for debug, but not succeed， seems a bug to paddledet(with multiprocessing lock all the time.)
worker_num: 0

LearningRate:
  # from 0.01 to 0.01/8
  base_lr: 0.00125

RPNHead:
  anchor_generator:
    aspect_ratios: [0.5, 1.0, 2.0]
    anchor_sizes: [[32], [64], [128], [256], [512]]
    strides: [4, 8, 16, 32, 64]```

**Comment by heavengate** [comment]
上面还有其他报错信息么

**Comment by ximitiejiang** [comment]
重试了一下，有时候还有一段如下。
但这段之后还会继续运行直到我前面的报错出现。
```
2021-05-21 13:42:56,560 - WARNING - DataLoader reader thread raised an exception.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 346, in _thread_loop
    six.reraise(*sys.exc_info())
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 317, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices)
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 60, in fetch
    data = [self.dataset[idx] for idx in batch_indices]
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 60, in <listcomp>
    data = [self.dataset[idx] for idx in batch_indices]
  File "/home/suliang/suliang_git/PaddleDetection-2.0.0/ppdet/data/source/dataset.py", line 87, in __getitem__
    return self.transform(roidb)
  File "/home/suliang/suliang_git/PaddleDetection-2.0.0/ppdet/data/reader.py", line 61, in __call__
    raise e
  File "/home/suliang/suliang_git/PaddleDetection-2.0.0/ppdet/data/reader.py", line 56, in __call__
    data = f(data)
  File "/home/suliang/suliang_git/PaddleDetection-2.0.0/ppdet/data/transform/operators.py", line 101, in __call__
    sample = self.apply(sample, context)
  File "/home/suliang/suliang_git/PaddleDetection-2.0.0/ppdet/data/transform/operators.py", line 124, in apply
    im = cv2.imdecode(data, 1)  # BGR mode, but need RGB mode
cv2.error: OpenCV(4.2.0) /io/opencv/modules/imgcodecs/src/loadsave.cpp:730: error: (-215:Assertion failed) !buf.empty() in function 'imdecode_'
```
