### ISSUE TITLE
ssd eval时会出错

### ISSUE THREAD

**Issue by lao-xu** [PaddlePaddle/PaddleDetection#3119]
动态图下ssd训练，执行
!python tools/train.py -c configs/ssd/ssd_vgg16_300_240e_voc.yml --eval -o use_gpu=true
eval时报错：
Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 111, in run
    trainer.train(FLAGS.eval)
  File "/home/aistudio/PaddleDetection/ppdet/engine/trainer.py", line 317, in train
    self._eval_with_loader(self._eval_loader)
  File "/home/aistudio/PaddleDetection/ppdet/engine/trainer.py", line 337, in _eval_with_loader
    metric.update(data, outs)
  File "/home/aistudio/PaddleDetection/ppdet/metrics/metrics.py", line 229, in update
    difficult)
  File "/home/aistudio/PaddleDetection/ppdet/metrics/map_utils.py", line 154, in update
    self.class_gt_counts[int(np.array(gtl))] += 1
IndexError: list index out of range

**Comment by lao-xu** [comment]
抱歉，已经解决了

**Comment by lNeveryday** [comment]
请问如何解决呢

**Comment by Vergissmeinnic** [comment]
我也想知道如何解决……我是2.4的版本

**Comment by lao-xu** [comment]
时间长，忘记了，大概IndexError: list index out of range，是自己的错误
