### ISSUE TITLE
raise Exception("File {} is not a paddle parameter file"

### ISSUE THREAD

**Issue by xuanyuanbao** [PaddlePaddle/PaddleDetection#3120]
Traceback (most recent call last):
  File "D:/develop/PythonProject/MyPaddleX/FasterRCNN01.py", line 50, in <module>
2021-05-21 21:07:14 [INFO]	Load pretrain weights from output/faster_rcnn_hrnet_fpn\pretrain\HRNet_W18.
    model.train(
  File "D:\develop\PythonProject\venv\lib\site-packages\paddlex\cv\models\faster_rcnn.py", line 355, in train
    self.net_initialize(
  File "D:\develop\PythonProject\venv\lib\site-packages\paddlex\cv\models\base.py", line 253, in net_initialize
    paddlex.utils.utils.load_pretrain_weights(
  File "D:\develop\PythonProject\venv\lib\site-packages\paddlex\utils\utils.py", line 258, in load_pretrain_weights
    raise Exception("File {} is not a paddle parameter file".format(
Exception: File output/faster_rcnn_hrnet_fpn\pretrain\HRNet_W18 is not a paddle parameter file
W0521 21:05:32.087198 15112 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.1, Runtime API Version: 11.0
W0521 21:05:32.498626 15112 device_context.cc:372] device: 0, cuDNN Version: 8.2.

使用pycharm训练昆虫识别，出现上述的错误
代码链接：https://github.com/PaddlePaddle/PaddleX/blob/develop/tutorials/train/object_detection/faster_rcnn_hrnet_fpn.py

Windows10环境，使用的paddlex

**Comment by jerrywgz** [comment]
这里从代码上看应该是需要在output/faster_rcnn_hrnet_fpn\pretrain\ 下添加HRNet_W18预训练权重，详细问题可以在https://github.com/PaddlePaddle/PaddleX/issues 中提问～
