### ISSUE TITLE
使用fairMot进行检测视频时失败

### ISSUE THREAD

**Issue by CandyCook** [PaddlePaddle/PaddleDetection#3134]
使用ffmpeg将mot图片以每秒25帧的速度合成为一个视频，进行预测时会报错

[05/24 09:27:40] ppdet.engine.tracker INFO: Starting tracking out.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5615b4c5f800] moov atom not found
VIDIOC_REQBUFS: Inappropriate ioctl for device
[05/24 09:27:40] ppdet.data.source.mot INFO: Length of the video: 0 frames
Traceback (most recent call last):
  File "tools/infer_mot.py", line 115, in <module>
    main()
  File "tools/infer_mot.py", line 111, in main
    run(FLAGS, cfg)
  File "tools/infer_mot.py", line 97, in run
    det_results_dir=FLAGS.det_results_dir)
  File "/home/aistudio/PaddleDetection-release-2.1/ppdet/engine/tracker.py", line 349, in mot_predict
    self.dataset.set_video(video_file)
  File "/home/aistudio/PaddleDetection-release-2.1/ppdet/data/source/mot.py", line 360, in set_video
    self.roidbs = self._load_video_images()
  File "/home/aistudio/PaddleDetection-release-2.1/ppdet/data/source/mot.py", line 353, in _load_video_images
    assert len(records) > 0, "No image file found"
AssertionError: No image file found

**Comment by liuhuiCNN** [comment]
你， 提示的问题是读取video失败，去掉视频脚本是： https://github.com/PaddlePaddle/PaddleDetection/blob/653ebe9fa2a15d966797153fe47d5aa4af2604bc/ppdet/data/source/mot.py#L325
（1）请检查video路径是否正确；（2）请写个简单读取视频脚本，测试一下cv2是否能够正常读取视频文件（确认下解码库安装是否正常）。

**Comment by CandyCook** [comment]
在本地windows执行测试脚本OK，在AI STUDIO里面运行测试脚本报错
aistudio@jupyter-801182-1980974:~/PaddleDetection-release-2.1$ python testcv2.py 
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5557c56d5340] moov atom not found
VIDIOC_REQBUFS: Inappropriate ioctl for device
false

**Comment by nemonameless** [comment]
可能是AI STUDIO的环境下，cv2不能正常读取视频文件，可以尝试升级或更换cv2版本。
