### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by WonDaniel** [PaddlePaddle/PaddleDetection#3139]
在跑训练的时候，第二天发现类似如下出现报错，
W0523 11:10:54.705610 843051 default_variables.cpp:429] Fail to open /proc/self/io: Too many open files [24]
以及
OSError: [Errno 24] Too many open files
Exception ignored in: <bound method _DataLoaderIterMultiProcess.__del__ of <paddle.fluid.dataloader.dataloader_iter._DataLoaderIterMultiProcess object at 0x7f48802afc88>>
Traceback (most recent call last):
  File "/home/lesmart/anaconda3/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 566, in __del__
    self._try_shutdown_all()
  File "/home/lesmart/anaconda3/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 371, in _try_shutdown_all
    if not self._shutdown:
AttributeError: '_DataLoaderIterMultiProcess' object has no attribute '_shutdown'

如果是因为句柄打开过多的话，在pytorch中，类似的问题，好像是可以设置
torch.multiprocessing.set_sharing_strategy(‘file_system‘)
这样来解决，不知道paddle有没有类似的

**Comment by wangxinxin08** [comment]
感谢你的反馈，我们之后定位下问题

**Comment by funhacke-png** [comment]
我也遇到了相同的问题
Traceback (most recent call last):
  File "tools/train.py", line 142, in <module>
    main()
  File "tools/train.py", line 138, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 113, in run
    trainer.train(FLAGS.eval)
  File "/home/ps/Desktop/PaddleDetection-release-2.0/ppdet/engine/trainer.py", line 256, in train
    for step_id, data in enumerate(self.loader):
  File "/home/ps/Desktop/PaddleDetection-release-2.0/ppdet/data/reader.py", line 222, in __next__
    self.loader = iter(self.dataloader)
  File "/home/ps/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/reader.py", line 426, in __iter__
    return _DataLoaderIterMultiProcess(self)
  File "/home/ps/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 283, in __init__
    self._init_workers()
  File "/home/ps/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 327, in _init_workers
    worker.start()
  File "/home/ps/anaconda3/envs/paddle/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/ps/anaconda3/envs/paddle/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/ps/anaconda3/envs/paddle/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/ps/anaconda3/envs/paddle/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/ps/anaconda3/envs/paddle/lib/python3.8/multiprocessing/popen_fork.py", line 69, in _launch
    child_r, parent_w = os.pipe()
OSError: [Errno 24] Too many open files
Exception ignored in: <function _DataLoaderIterMultiProcess.__del__ at 0x7f0c2cab6f70>
Traceback (most recent call last):
  File "/home/ps/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 566, in __del__
    self._try_shutdown_all()
  File "/home/ps/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 371, in _try_shutdown_all
    if not self._shutdown:
AttributeError: '_DataLoaderIterMultiProcess' object has no attribute '_shutdown'
