### ISSUE TITLE
infer.py mask_rcnn

### ISSUE THREAD

**Issue by xuanxiaoliqu** [PaddlePaddle/PaddleDetection#3140]
Traceback (most recent call last):
  File "infer.py", line 640, in <module>
    main()
  File "infer.py", line 601, in main
    predict_video(detector, FLAGS.camera_id)
  File "infer.py", line 556, in predict_video
    im = visualize_box_mask(
  File "D:\projects\PaddleDetection\deploy\python\visualize.py", line 42, in visualize_box_mask
    im = draw_mask(
  File "D:\projects\PaddleDetection\deploy\python\visualize.py", line 108, in draw_mask
    im[idx[0], idx[1], :] *= 1.0 - alpha
IndexError: index 640 is out of bounds for axis 1 with size 640

**Comment by quhaohao** [comment]
是padding的问题，代码对于seg没有考虑padding的部分，因此seg的大小大于原图
