### ISSUE TITLE
车辆识别demo的视频流输入

### ISSUE THREAD

**Issue by ZERO6666** [PaddlePaddle/PaddleDetection#315]
自己尝试通过读入视频帧进行推理，发现框架的reader是要求路径的，想知道如何对视频流的帧输入进行推理。
`/home/ref/下载/PaddleDetection/ppdet/data/source/simple_source.py:42: FutureWarning: elementwise comparison failed; returning scalar instead, b in the future will perform elementwise comparison
  assert image != '' and os.path.isfile(image), \
Traceback (most recent call last):
  File "tools/infer.py", line 326, in <module>
    main()
  File "tools/infer.py", line 182, in main
    reader = create_reader(test_feed)
  File "/home/ref/下载/PaddleDetection/ppdet/data/data_feed.py", line 149, in create_reader
    my_source)
  File "/home/ref/下载/PaddleDetection/ppdet/data/reader.py", line 140, in create
    return reader._make_reader(mode, my_source)
  File "/home/ref/下载/PaddleDetection/ppdet/data/reader.py", line 51, in _make_reader
    sc = build_source(sc_conf)
  File "/home/ref/下载/PaddleDetection/ppdet/data/source/__init__.py", line 69, in build_source
    return SimpleSource(**args)
  File "/home/ref/下载/PaddleDetection/ppdet/data/source/simple_source.py", line 42, in __init__
    assert image != '' and os.path.isfile(image), \
  File "/home/ref/anaconda2/envs/py37/lib/python3.7/genericpath.py", line 30, in isfile
    st = os.stat(path)
ValueError: stat: embedded null character in path
`

**Comment by jerrywgz** [comment]
目前检测库已经更新到release/0.2版本，如果只需要推理的话可以尝试在最新版中在ppdet/data/source/dataset.py中修改imagefolder解析图片的方式，我们后续会对视频流输入增强下

**Comment by ZERO6666** [comment]
> 目前检测库已经更新到release/0.2版本，如果只需要推理的话可以尝试在最新版中在ppdet/data/source/dataset.py中修改imagefolder解析图片的方式，我们后续会对视频流输入增强下

不好意思，再问一下　你们新的这个版本我运行怎么显示缺乏TestReader这个属性呢，yml文件里也确实没有，是你们的失误，还是我这边漏掉了啥呢？
