### ISSUE TITLE
AIstudio  PaddlePaddle 1.7.0 框架 yolov3_r34_voc 训练报错

### ISSUE THREAD

**Issue by pele228** [PaddlePaddle/PaddleDetection#316]
W0310 11:11:16.339478   441 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 9.2, Runtime API Version: 9.0
W0310 11:11:16.343116   441 device_context.cc:245] device: 0, cuDNN Version: 7.3.
2020-03-10 11:11:17,832-INFO: Found /home/aistudio/.cache/paddle/weights/ResNet34_pretrained
2020-03-10 11:11:17,832-INFO: Loading parameters from /home/aistudio/.cache/paddle/weights/ResNet34_pretrained...
2020-03-10 11:11:17,832-WARNING: /home/aistudio/.cache/paddle/weights/ResNet34_pretrained.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-03-10 11:11:17,832-WARNING: /home/aistudio/.cache/paddle/weights/ResNet34_pretrained.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-03-10 11:11:17,839-WARNING: variable file [ /home/aistudio/.cache/paddle/weights/ResNet34_pretrained/fc_0.w_0 /home/aistudio/.cache/paddle/weights/ResNet34_pretrained/fc_0.b_0 ] not used
2020-03-10 11:11:17,839-WARNING: variable file [ /home/aistudio/.cache/paddle/weights/ResNet34_pretrained/fc_0.w_0 /home/aistudio/.cache/paddle/weights/ResNet34_pretrained/fc_0.b_0 ] not used
Traceback (most recent call last):
  File "tools/train.py", line 323, in <module>
    main()
  File "tools/train.py", line 197, in main
    devices_num, cfg)
  File "/home/aistudio/work/PaddleDetection/ppdet/data/reader.py", line 406, in create_reader
    reader = Reader(**cfg)()
  File "/home/aistudio/work/PaddleDetection/ppdet/data/reader.py", line 202, in __init__
    self._roidbs = self._dataset.get_roidb()
  File "/home/aistudio/work/PaddleDetection/ppdet/data/source/dataset.py", line 68, in get_roidb
    self.load_roidb_and_cname2cid()
  File "/home/aistudio/work/PaddleDetection/ppdet/data/source/voc.py", line 131, in load_roidb_and_cname2cid
    gt_class[i][0] = cname2cid[cname]
KeyError: '25'

同样的数据在1.6框架下没问题，1.7下的config文件如下：
architecture: YOLOv3
use_gpu: true
max_iters: 240000
log_smooth_window: 20
save_dir: output
snapshot_iter: 10000
metric: VOC
map_type: 11point
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet34_pretrained.tar
weights: output/yolov3_r34_voc_an/model_final
num_classes: 28
use_fine_grained_loss: false

YOLOv3:
  backbone: ResNet
  yolo_head: YOLOv3Head

ResNet:
  norm_type: sync_bn
  freeze_at: 0
  freeze_norm: false
  norm_decay: 0.
  depth: 34
  feature_maps: [3, 4, 5]

YOLOv3Head:
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  anchors: [[10, 13], [16, 30], [33, 23],
            [30, 61], [62, 45], [59, 119],
            [116, 90], [156, 198], [373, 326]]
  norm_decay: 0.
  yolo_loss: YOLOv3Loss
  nms:
    background_label: -1
    keep_top_k: 100
    nms_threshold: 0.45
    nms_top_k: 1000
    normalized: false
    score_threshold: 0.01

YOLOv3Loss:
  batch_size: 8
  ignore_thresh: 0.7
  label_smooth: false

LearningRate:
  base_lr: 0.0001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 180000
    - 205000
  - !LinearWarmup
    start_factor: 0.
    steps: 1000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

_READER_: 'yolov3_reader.yml'
TrainReader:
  dataset:
    !VOCDataSet
    dataset_dir: dataset/an
    anno_path: trainval.txt
    use_default_label: false
    with_background: false

EvalReader:
  inputs_def:
    image_shape: [3, 608, 608]
    fields: ['image', 'im_size', 'im_id', 'gt_bbox', 'gt_class', 'is_difficult']
    num_max_boxes: 50
  dataset:
    !VOCDataSet
    dataset_dir: dataset/an
    anno_path: test.txt
    use_default_label: false
    with_background: false

TestReader:
  dataset:
    !ImageFolder
    use_default_label: false
    dataset_dir: dataset/an
    anno_path: label_list.txt
    with_background: false

**Comment by jerrywgz** [comment]
可以在voc.py中检查下cname2cid，它是根据数据集中的label_list.txt自动生成的label和id的对应关系，然后可以再检查下anno文件中box对应的class id和cname2cid中的是否能对应起来
