### ISSUE TITLE
c++预测部署报错

### ISSUE THREAD

**Issue by ximitiejiang** [PaddlePaddle/PaddleDetection#3161]
你好，
我用自定义数据集训练的模型导出部署模型，预测时报错。
单步进去后在object_detector.cc的line237报错：`predictor_->Run();`
这个模型我之前也在其他数据集训练导出部署过，部署代码应该是ok的，请问下可能是什么原因？
报错信息如下：
```
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

  Compile Traceback (most recent call last):
    File "/home/suliang/suliang_git/PaddleDetection-2.0.0/sl_package/export_model.py", line 109, in <module>
      main()
    File "/home/suliang/suliang_git/PaddleDetection-2.0.0/sl_package/export_model.py", line 105, in main
      run(FLAGS, cfg)
    File "/home/suliang/suliang_git/PaddleDetection-2.0.0/sl_package/export_model.py", line 73, in run
      trainer.export(FLAGS.output_dir)
    File "/home/suliang/suliang_git/PaddleDetection-2.0.0/ppdet/engine/trainer.py", line 465, in export
      input_spec, static_model.forward.main_program,
    File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 534, in main_program
      concrete_program = self.concrete_program
    File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 454, in concrete_program
      return self.concrete_program_specify_input_spec(input_spec=None)
    File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program_specify_input_spec
      *desired_input_spec)
    File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 702, in _build_once
      class_instance=cache_key.class_instance)
    File "<decorator-gen-65>", line 2, in from_func_spec
      
    File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
      return func(*args, **kwargs)
    File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 652, in from_func_spec
      outputs = static_func(*inputs)
    File "/tmp/tmpf7jfz4m_.py", line 27, in forward
      false_fn_1, (), (), (out,))
    File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/home/suliang/suliang_git/PaddleDetection-2.0.0/ppdet/modeling/architectures/meta_arch.py", line 29, in forward
      out = self.get_pred()
    File "/home/suliang/suliang_git/PaddleDetection-2.0.0/ppdet/modeling/architectures/faster_rcnn.py", line 104, in get_pred
      bbox_pred, bbox_num = self._forward()
    File "/tmp/tmpymm2_t26.py", line 54, in _forward
      rois, rois_num))
    File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/home/suliang/suliang_git/PaddleDetection-2.0.0/ppdet/modeling/architectures/faster_rcnn.py", line 87, in _forward
      im_shape, scale_factor)
    File "/tmp/tmpy9jwelks.py", line 38, in __call__
      bbox_num, bbox_pred))
    File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/home/suliang/suliang_git/PaddleDetection-2.0.0/ppdet/modeling/post_process.py", line 58, in __call__
      bboxes, score = self.decode(head_out, rois, im_shape, scale_factor)
    File "/tmp/tmpld4k6n83.py", line 31, in __call__
      roi])
    File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 44, in convert_while_loop
      loop_vars = _run_py_while(cond, body, loop_vars)
    File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 58, in _run_py_while
      loop_vars = body(*loop_vars)
    File "/home/suliang/suliang_git/PaddleDetection-2.0.0/ppdet/modeling/layers.py", line 364, in __call__
      [rois_num_per_im, 2])
    File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/tensor/manipulation.py", line 1490, in expand
      type='expand_v2', inputs=inputs, outputs={'Out': out}, attrs=attrs)
    File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3232, in append_op
      attrs=kwargs.get("attrs", None))
    File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2312, in __init__
      for frame in traceback.extract_stack():

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun()
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   paddle::operators::ExpandV2Op::InferShape(paddle::framework::InferShapeContext*) const
6   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
7   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The 0th element of 'shape' for expand_v2 op must be greater than 0, but the value given is -2.
  [Hint: Expected expand_shape[i] > 0, but received expand_shape[i]:-2 <= 0:0.] (at /paddle/paddle/fluid/operators/expand_v2_op.cc:75)
  [operator < expand_v2 > error]

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

谢谢！

**Comment by ximitiejiang** [comment]
模型使用的是fasterrcnn
cuda10.2
cudnn7.6.5
trt6
paddle inference库的版本信息如下
```
GIT COMMIT ID: 5c7ad3bcb482dd93ea21b3b66b5a7ff964e0f239
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: ON
CUDA version: 10.1
CUDNN version: v7.6
CXX compiler version: 8.2.0
WITH_TENSORRT: ON
TensorRT version: v6
```

**Comment by lyuwenyu** [comment]
- 训练结果正确嘛 能够正常eval或者inference嘛
- 看着像没有ROI

**Comment by liuhuiCNN** [comment]
建议您用paddle2.1.0 ppdet2.1.0 试下

**Comment by ximitiejiang** [comment]
更新一下解决方案：
paddle inference更新成最新版本cuda10.2_cudnn7_avx_mkl_trt7
```
GIT COMMIT ID: 4ccd9a0a86ad550a861c954d70e28ef15741b310
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: ON
CUDA version: 10.2
CUDNN version: v7.6
CXX compiler version: 19.16.27045.0
WITH_TENSORRT: ON
TensorRT version: v7
```
然后编译时对应的tensorRT链接到trt7的版本，报错就没有了
