### ISSUE TITLE
s2anet在release2.1上出现检测框混乱问题

### ISSUE THREAD

**Issue by 617475jordan** [PaddlePaddle/PaddleDetection#3178]
![samples_0](https://user-images.githubusercontent.com/26131654/119649302-0f1d2d00-be55-11eb-889d-17ab820276b4.png)
![samples_2](https://user-images.githubusercontent.com/26131654/119649345-17756800-be55-11eb-8c44-9f46a7c73450.png)

**Comment by liuhuiCNN** [comment]
请问您使用的命令是什么呢？ 我刚测试是正常的：
`python tools/infer.py -c configs/dota/s2anet_1x_dota.yml -o weights=s2anet_conv_1x_dota.pdparams --infer_img=demo/P0072__1.0__0___0.png`

**Comment by 617475jordan** [comment]
> 请问您使用的命令是什么呢？ 我刚测试是正常的：
> `python tools/infer.py -c configs/dota/s2anet_1x_dota.yml -o weights=s2anet_conv_1x_dota.pdparams --infer_img=demo/P0072__1.0__0___0.png`
我刚看了，如何采用你运行的命令会出现     image = draw_bbox(image, im_id, catid2name, bbox_res, threshold)
  File "D:\nihongjie\PaddleDetection\ppdet\utils\visualizer.py", line 124, in draw_bbox
    text = "{} {:.2f}".format(catid2name[catid], score)
KeyError: 12
我特地仔细看了一下你的配置文件跟你的模型是不一致的，应该都需要使用s2anet_conv_1x_dota。
还有我是把模型下载后，改为model.pdparams ,分别再release/2.0跟2.1测试了。仅存在与release/2.1版本

**Comment by fanxiaochen-123** [comment]
@617475jordan 您好，我将配置文件和模型修改为一致，执行命令为>python tools/infer.py -c configs/dota/s2anet_conv_1x_dota.yml -o weights=model.pdparams  --infer_img=demo/1.png --draw_threshold=0.05 --save_txt=True --output_dir=output
他会出现以下错误：
Traceback (most recent call last):
  File "tools/infer.py", line 161, in <module>
    main()
  File "tools/infer.py", line 157, in main
    run(FLAGS, cfg)
  File "tools/infer.py", line 135, in run
    save_txt=FLAGS.save_txt)
  File "C:\Users\admin\anaconda3\envs\padd2.0\lib\site-packages\ppdet\engine\trainer.py", line 399, in predict
    draw_threshold)
  File "C:\Users\admin\anaconda3\envs\padd2.0\lib\site-packages\ppdet\utils\visualizer.py", line 41, in visualize_results
    image = draw_bbox(image, im_id, catid2name, bbox_res, threshold)
  File "C:\Users\admin\anaconda3\envs\padd2.0\lib\site-packages\ppdet\utils\visualizer.py", line 118, in draw_bbox
    text = "{} {:.2f}".format(catid2name[catid], score)
KeyError: 12
代码选取为release2.1，paddledet：2.0.1，paddlepaddle-gpu：2.0.1，请问您知道这是什么原因吗？

**Comment by fanxiaochen-123** [comment]
我测试了同样的配置文件和模型，在release2.0的情况下也报了相同的错误

**Comment by 617475jordan** [comment]
你看，你的paddlepaddle版本偏低，试试把版本切换一下

fanxiaochen-123 ***@***.***> 于2021年11月8日周一 下午2:36写道：
