### ISSUE TITLE
使用mask_rcnn_r50_vd_fpn_ssld_2x_coco做实例分割时，eval报错

### ISSUE THREAD

**Issue by jerryandjune** [PaddlePaddle/PaddleDetection#3184]
训练过程没有问题，到eval时，就会报以下错误，我训练的是coco格式的数据集，类别为1,2,3,4,5
我打印了category_id = label_to_cat_id_map[int(num_id)]中的label_to_cat_id_map为{0:1, 1:2, 2:3, 3:4, 4:5}
eval是key为5，就报这个错误了，我尝试使用其他的实例分割，都出现类似的问题

[05/27 11:24:45] ppdet.utils.checkpoint INFO: Save checkpoint: output/mask_rcnn_r50_vd_fpn_ssld_2x_coco
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
[05/27 11:24:46] ppdet.engine INFO: Eval iter: 0
Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 111, in run
    trainer.train(FLAGS.eval)
  File "/home/aistudio/PaddleDetection/ppdet/engine/trainer.py", line 350, in train
    self._eval_with_loader(self._eval_loader)
  File "/home/aistudio/PaddleDetection/ppdet/engine/trainer.py", line 370, in _eval_with_loader
    metric.update(data, outs)
  File "/home/aistudio/PaddleDetection/ppdet/metrics/metrics.py", line 100, in update
    outs, self.clsid2catid, bias=self.bias)
  File "/home/aistudio/PaddleDetection/ppdet/metrics/coco_utils.py", line 53, in get_infer_results
    outs['bbox'], outs['bbox_num'], im_id, catid, bias=bias)
  File "/home/aistudio/PaddleDetection/ppdet/metrics/json_results.py", line 32, in get_det_res
    category_id = label_to_cat_id_map[int(num_id)]
KeyError: 5

**Comment by heavengate** [comment]
你好，你使用的是自己的数据集么，数据集只有5类的话吧对应的`configs/datasets/xxx.yml`里的`num_classes`修改成5，如
https://github.com/PaddlePaddle/PaddleDetection/blob/4c18e94b5dcdb9426f5ac0bbafc403de126215f8/configs/datasets/coco_instance.yml#L2
也可以在你使用的`mask_rcnn_r50_vd_fpn_ssld_2x_coco.yml`里加一行`num_classes: 5`
