### ISSUE TITLE
Config dataset_dir /mnt/PaddleDetection/dataset/data_movie is not exits!

### ISSUE THREAD

**Issue by yangsuhui** [PaddlePaddle/PaddleDetection#3188]
我的路径设置是对的，为什么跑训练时报路径找不到的错误和下面的错误？
ValueError: Dataset /mnt/PaddleDetection/dataset/data_movie is not valid and cannot parse dataset type 'data_movie' for automaticly downloading, which only supports 'voc' , 'coco', 'wider_face', 'fruit' and 'roadsign_voc' currently

**Comment by heavengate** [comment]
这条日志上面应该还有日志提示是为什么这个数据集路径没有识别到

**Comment by yangsuhui** [comment]
@heavengate 这是完整的提示信息
2021-05-27 12:19:57,179-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000100] in Optimizer will not take effect, and it will only be applied to other Parameters!
W0527 12:19:57.332414   565 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.2, Runtime API Version: 10.0
W0527 12:19:57.337711   565 device_context.cc:260] device: 0, cuDNN Version: 7.6.
2021-05-27 12:20:00,852-WARNING: /root/.cache/paddle/weights/ResNet50_cos_pretrained.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2021-05-27 12:20:01,150-WARNING: /root/.cache/paddle/weights/ResNet50_cos_pretrained.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2021-05-27 12:20:01,159-WARNING: variable file [ /root/.cache/paddle/weights/ResNet50_cos_pretrained/fc_0.b_0 /root/.cache/paddle/weights/ResNet50_cos_pretrained/fc_0.w_0 ] not used
2021-05-27 12:20:01,463-ERROR: Config dataset_dir /mnt/PaddleDetection/dataset/data_movie is not exits!
2021-05-27 12:20:01,464-WARNING: Config annotation /mnt/PaddleDetection/dataset/data_movie/train/annotations/instances_default.json is not a file, dataset config is not valid
2021-05-27 12:20:01,464-INFO: Dataset /mnt/PaddleDetection/dataset/data_movie is not valid for reason above, try searching /root/.cache/paddle/dataset or downloading dataset...
Traceback (most recent call last):
  File "tools/train.py", line 372, in <module>
    main()
  File "tools/train.py", line 208, in main
    num_trainers=num_trainers)
  File "/root/PaddleDetection/ppdet/data/reader.py", line 441, in create_reader
    reader = Reader(**cfg)()
  File "/root/PaddleDetection/ppdet/data/reader.py", line 210, in __init__
    self._roidbs = self._dataset.get_roidb()
  File "/root/PaddleDetection/ppdet/data/source/dataset.py", line 65, in get_roidb
    self.image_dir)
  File "/root/PaddleDetection/ppdet/utils/download.py", line 154, in get_dataset_path
    format(path, osp.split(path)[-1]))
ValueError: Dataset /mnt/PaddleDetection/dataset/data_movie is not valid and cannot parse dataset type 'data_movie' for automaticly downloading, which only supports 'voc' , 'coco', 'wider_face', 'fruit' and 'roadsign_voc' currently

**Comment by fsultana44** [comment]
@yangsuhui, I am facing the same problem whenever I try to load the custom data set. Could you please tell me how did you solve this problem?
