### ISSUE TITLE
BatchRandomResize 设置keep_ratio 为true时报错

### ISSUE THREAD

**Issue by Harry-675** [PaddlePaddle/PaddleDetection#3194]
如标题所述，想要保持图像长宽比进行训练，keep_ratio设置为true时报错如下：
ERROR:root:DataLoader reader thread raised an exception!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/baidu/anaconda2/envs/paddle/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/baidu/anaconda2/envs/paddle/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/baidu/anaconda2/envs/paddle/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 411, in _thread_loop
    batch = self._get_data()
  File "/home/baidu/anaconda2/envs/paddle/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 525, in _get_data
    batch.reraise()
  File "/home/baidu/anaconda2/envs/paddle/lib/python3.9/site-packages/paddle/fluid/dataloader/worker.py", line 168, in reraise
    raise self.exc_type(msg)
ValueError: DataLoader worker(1) caught ValueError with message:
Traceback (most recent call last):
  File "/home/baidu/anaconda2/envs/paddle/lib/python3.9/site-packages/paddle/fluid/dataloader/worker.py", line 228, in _worker_loop
    batch = fetcher.fetch(indices)
  File "/home/baidu/anaconda2/envs/paddle/lib/python3.9/site-packages/paddle/fluid/dataloader/fetcher.py", line 66, in fetch
    data = self.collate_fn(data)
  File "/media/baidu/ssd1/Harry/Vehicle_Track/Code/PaddleDetection-release-2.1/ppdet/data/reader.py", line 93, in __call__
    batch_data = default_collate_fn(data)
  File "/home/baidu/anaconda2/envs/paddle/lib/python3.9/site-packages/paddle/fluid/dataloader/collate.py", line 68, in default_collate_fn
    return {
  File "/home/baidu/anaconda2/envs/paddle/lib/python3.9/site-packages/paddle/fluid/dataloader/collate.py", line 69, in <dictcomp>
    key: default_collate_fn([d[key] for d in batch])
  File "/home/baidu/anaconda2/envs/paddle/lib/python3.9/site-packages/paddle/fluid/dataloader/collate.py", line 58, in default_collate_fn
    batch = np.stack(batch, axis=0)
  File "<__array_function__ internals>", line 5, in stack
  File "/home/baidu/anaconda2/envs/paddle/lib/python3.9/site-packages/numpy/core/shape_base.py", line 427, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape

**Comment by jerrywgz** [comment]
如果使用batch random resize + keep_ratio=true的方式，每张图都会等比例resize成不同大小，而并没有将他们的尺寸做统一，导致dataloader组batch的过程中报错。解决方式可以考虑在batch random resize后增加PadBatch解决

**Comment by blackhitomi** [comment]
请问如何增加

> 如果使用batch random resize + keep_ratio=true的方式，每张图都会等比例resize成不同大小，而并没有将他们的尺寸做统一，导致dataloader组batch的过程中报错。解决方式可以考虑在batch random resize后增加PadBatch解决

我也遇到一样的问题，请问如何增加PadBatch来解决，方便详细说明一下吗
