### ISSUE TITLE
eval时报错：ppdet/modeling/backbones/dla.py line 237, in forward     im = inputs['image'] KeyError: 'image'

### ISSUE THREAD

**Issue by gong-bit** [PaddlePaddle/PaddleDetection#3208]
-----------  Configuration Arguments -----------
gpus: 0
heter_worker_num: None
heter_workers: 
http_port: None
ips: 127.0.0.1
log_dir: ./fairmot_dla34_30e_1088x608QianY/
nproc_per_node: None
run_mode: None
server_num: None
servers: 
training_script: tools/eval.py
training_script_args: ['-c', 'configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml', '-o', 'use_gpu=True', 'weights=/home/aistudio/model_final.pdparams']
worker_num: None
workers: 
------------------------------------------------
WARNING 2021-05-29 20:03:14,032 launch.py:357] Not found distinct arguments and compiled with cuda or xpu. Default use collective mode
launch train in GPU mode!
INFO 2021-05-29 20:03:14,034 launch_utils.py:510] Local start 1 processes. First process distributed environment info (Only For Debug): 
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:57111               |
    |                     PADDLE_TRAINERS_NUM                        1                      |
    |                PADDLE_TRAINER_ENDPOINTS                 127.0.0.1:57111               |
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                        0                      |
    |                     FLAGS_selected_gpus                        0                      |
    |             FLAGS_selected_accelerators                        0                      |
    +=======================================================================================+

INFO 2021-05-29 20:03:14,034 launch_utils.py:514] details abouts PADDLE_TRAINER_ENDPOINTS can be found in ./fairmot_dla34_30e_1088x608QianY//endpoints.log, and detail running logs maybe found in ./fairmot_dla34_30e_1088x608QianY//workerlog.0
launch proc_id:7556 idx:0
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/__init__.py:107: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/rcsetup.py:20: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, Mapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/colors.py:53: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Sized
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
W0529 20:03:18.211830  7556 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0529 20:03:18.217396  7556 device_context.cc:422] device: 0, cuDNN Version: 7.6.
[05/29 20:03:22] ppdet.data.source.mot INFO: ================================================================================
[05/29 20:03:22] ppdet.data.source.mot INFO: MOT dataset summary: 
[05/29 20:03:22] ppdet.data.source.mot INFO: OrderedDict([('mot17.val', 547)])
[05/29 20:03:22] ppdet.data.source.mot INFO: total images: 2659
[05/29 20:03:22] ppdet.data.source.mot INFO: image start index: OrderedDict([('mot17.val', 0)])
[05/29 20:03:22] ppdet.data.source.mot INFO: total identities: 548
[05/29 20:03:22] ppdet.data.source.mot INFO: identity start index: OrderedDict([('mot17.val', 0)])
[05/29 20:03:22] ppdet.data.source.mot INFO: ================================================================================
/home/aistudio/PaddleDetection/ppdet/engine/trainer.py:202: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  self.cfg.metric))
[05/29 20:03:24] ppdet.engine WARNING: Metric not support for metric type MOT
[05/29 20:03:25] ppdet.utils.checkpoint INFO: reid.classifier.weight not used, shape [128, 2217] unmatched with [128, 14455] in model.
[05/29 20:03:25] ppdet.utils.checkpoint INFO: reid.classifier.bias not used, shape [2217] unmatched with [14455] in model.
[05/29 20:03:25] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/aistudio/model_final.pdparams
Traceback (most recent call last):
  File "tools/eval.py", line 134, in <module>
    main()
  File "tools/eval.py", line 130, in main
    run(FLAGS, cfg)
  File "tools/eval.py", line 105, in run
    trainer.evaluate()
  File "/home/aistudio/PaddleDetection/ppdet/engine/trainer.py", line 388, in evaluate
    self._eval_with_loader(self.loader)
  File "/home/aistudio/PaddleDetection/ppdet/engine/trainer.py", line 366, in _eval_with_loader
    outs = self.model(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 29, in forward
    out = self.get_pred()
  File "/home/aistudio/PaddleDetection/ppdet/modeling/architectures/fairmot.py", line 102, in get_pred
    output = self._forward()
  File "/home/aistudio/PaddleDetection/ppdet/modeling/architectures/fairmot.py", line 74, in _forward
    det_outs = self.detector(self.inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 29, in forward
    out = self.get_pred()
  File "/home/aistudio/PaddleDetection/ppdet/modeling/architectures/centernet.py", line 76, in get_pred
    head_out = self._forward()
  File "/home/aistudio/PaddleDetection/ppdet/modeling/architectures/centernet.py", line 68, in _forward
    body_feats = self.backbone(self.inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleDetection/ppdet/modeling/backbones/dla.py", line 237, in forward
    im = inputs['image']
KeyError: 'image'
INFO 2021-05-29 20:03:32,083 launch_utils.py:327] terminate all the procs
ERROR 2021-05-29 20:03:32,084 launch_utils.py:584] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-05-29 20:03:35,087 launch_utils.py:327] terminate all the procs

**Comment by nemonameless** [comment]
您好，可以发一下config配置文件以及运行的命令，以及paddle和paddledetection的版本？方便我们复现该问题，谢谢

**Comment by gong-bit** [comment]
> 您好，可以发一下config配置文件以及运行的命令，以及paddle和paddledetection的版本？方便我们复现该问题，谢谢

!python -m paddle.distributed.launch --log_dir=./fairmot_dla34_30e_1088x608QianY/ --gpus 0 tools/eval.py\
-c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml\
-o use_gpu=True weights=/home/aistudio/model_final.pdparams
运行命令。model_final.pdparams自己训练出的结果，已在train.py测试是可以正常使用的
然后配置文件里就修改了一下/dataset/mot.yml:
TrainDataset:
  !MOTDataSet
    dataset_dir: dataset/mot
    image_lists: ['mot20.train']
    data_fields: ['image', 'gt_bbox', 'gt_class', 'gt_ide']
for detection or reid evaluation, no use in MOT evaluation
EvalDataset:
  !MOTDataSet
    dataset_dir: dataset/mot
    image_lists: ['mot17.val'] # for detection evaluation
    # image_lists: ['caltech.10k.val', 'cuhksysu.val', 'prw.val'] # for reid evaluation
    data_fields: ['image', 'gt_bbox', 'gt_class', 'gt_ide']

 for detection inference, no use in MOT inference
TestDataset:
  !ImageFolder
    dataset_dir: dataset/mot
将mot17.val作为训练数据时也是可以正常训练的
notebook地址：https://aistudio.baidu.com/bdcpu7/user/504880/1993641/notebooks/1993641.ipynb

**Comment by nemonameless** [comment]
@gong-bit  您的命令改成运行tools/eval_mot.py就可以跑了。
对跟踪MOTA指标的eval命令，不需要python -m paddle.distributed.launch --log_dir= ，使用的是tools/eval_mot.py，而tools/eval.py是检测模型的eval代码。运行跟踪模型的eval过程请参照文档 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/configs/mot
```
# use weights released in PaddleDetection model zoo
CUDA_VISIBLE_DEVICES=0 python tools/eval_mot.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml -o weights=https://paddledet.bj.bcebos.com/models/mot/fairmot_dla34_30e_1088x608.pdparams

# use saved checkpoint in training
CUDA_VISIBLE_DEVICES=0 python tools/eval_mot.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml -o weights=output/fairmot_dla34_30e_1088x608/model_final.pdparams
```
eval跟踪指标要改数据集，可以改configs/datasets/mot.yml：
```
EvalMOTDataset:
  !MOTImageFolder
    task: MO17_train
    dataset_dir: dataset/mot
    data_root: MOT17/images/train
    keep_ori_im: False # set True if save visualization images or video
```
主要是改task和data_root。

EvalMOTDataset和EvalDataset的区别是，后者只是验证纯检测能力mAP或者纯reid指标用的，是JDE论文里的做法，参见[注释](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/configs/datasets/mot.yml#L22)，其实不太常用，fairmot原文以及复现时都不需要单独评估检测指标，后期在会删除configs/datasets/mot.yml里的EvalDataset和TestDataset
