### ISSUE TITLE
contrib下的车辆和行人检测yml和release2.0版本不匹配，无法使用toos/infer.py推理

### ISSUE THREAD

**Issue by laycoding** [PaddlePaddle/PaddleDetection#322]
环境：
paddlepaddle版本：1.7.0
paddleDetection版本：release 0.2

问题描述：
按照https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/featured_model/CONTRIB_cn.md
提示无TestReader
![image](https://user-images.githubusercontent.com/17764091/76483650-8a621100-6452-11ea-8eb6-11c44b461998.png)

**Comment by laycoding** [comment]
按照https://github.com/PaddlePaddle/PaddleDetection/issues/321#issuecomment-597985629，yml中增加：
```
TestReader:
  inputs_def:
    image_shape: [3, 608, 608]
    fields: ['image', 'im_size', 'im_id']
  dataset:
    !ImageFolder
      anno_path: contrib/PedestrianDetection/pedestrian.json
      with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !ResizeImage
      target_size: 608
      interp: 2
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: True
      is_channel_first: false
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 1
```
之后提示：
```
Traceback (most recent call last):
  File "tools/infer.py", line 271, in <module>
    main()
  File "tools/infer.py", line 121, in main
    model = create(main_arch)
  File "/opt/data/rd-wdzhang/PaddlePaddle/PaddleDetection/ppdet/core/workspace.py", line 236, in create
    kwargs[k] = create(target_key)
  File "/opt/data/rd-wdzhang/PaddlePaddle/PaddleDetection/ppdet/core/workspace.py", line 200, in create
    config.validate()
  File "/opt/data/rd-wdzhang/PaddlePaddle/PaddleDetection/ppdet/core/config/schema.py", line 143, in validate
    self.name, ", ".join(extra_keys)))
ValueError: Extraneous param for class<YOLOv3Head>: ignore_thresh, label_smooth
```

**Comment by laycoding** [comment]
删除yml中igmore_thresh和label_smooth之后
```
2020-03-12 03:30:02,106-INFO: Found 4 inference images in total.
W0312 03:30:03.565336 19278 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.0, Runtime API Version: 9.0
W0312 03:30:03.568406 19278 device_context.cc:245] device: 0, cuDNN Version: 7.1.
W0312 03:30:03.568423 19278 device_context.cc:271] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.3, but CUDNN version in your machine is 7.1, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
2020-03-12 03:30:04,355-INFO: Found /root/.cache/paddle/weights/vehicle_yolov3_darknet
2020-03-12 03:30:04,356-INFO: Loading parameters from /root/.cache/paddle/weights/vehicle_yolov3_darknet...
2020-03-12 03:30:04,356-WARNING: /root/.cache/paddle/weights/vehicle_yolov3_darknet.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-03-12 03:30:04,356-WARNING: /root/.cache/paddle/weights/vehicle_yolov3_darknet.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-03-12 03:30:04,956-INFO: Load categories from contrib/PedestrianDetection/pedestrian.json
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2020-03-12 03:30:05,513-INFO: Infer iter 0
Traceback (most recent call last):
  File "tools/infer.py", line 271, in <module>
    main()
  File "tools/infer.py", line 195, in main
    bbox_results = bbox2out([res], clsid2catid, is_bbox_normalized)
  File "/opt/data/rd-wdzhang/PaddlePaddle/PaddleDetection/ppdet/utils/coco_eval.py", line 216, in bbox2out
    catid = (clsid2catid[int(clsid)])
KeyError: 1
```

**Comment by FDInSky** [comment]
@laycoding 收到，再有问题，请讲
