### ISSUE TITLE
多卡训练报错

### ISSUE THREAD

**Issue by qiyuezhiguang** [PaddlePaddle/PaddleDetection#3221]
Ubuntu18,2080Ti2块，cuda10.1， cudnn7.6.5，nccl2.7.8，paddledetection2.1
按照官方例子
export CUDA_VISIBLE_DEVICES=0 #windows和Mac下不需要执行该命令
python tools/train.py -c configs/yolov3/yolov3_mobilenet_v1_roadsign.yml
正常运行

但使用多卡训练
export CUDA_VISIBLE_DEVICES=0,1
python -m paddle.distributed.launch --gpus 0,1 tools/train.py -c configs/yolov3/yolov3_mobilenet_v1_roadsign.yml
就会报如下错误：
-------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::Tensor::mutable_data(paddle::platform::Place const&, paddle::framework::proto::VarType_Type, unsigned long)
1   paddle::memory::AllocShared(paddle::platform::Place const&, unsigned long)
2   paddle::memory::allocation::AllocatorFacade::AllocShared(paddle::platform::Place const&, unsigned long)
3   paddle::memory::allocation::AllocatorFacade::Alloc(paddle::platform::Place const&, unsigned long)
4   paddle::memory::allocation::RetryAllocator::AllocateImpl(unsigned long)
5   paddle::memory::allocation::NaiveBestFitAllocator::AllocateImpl(unsigned long)
6   void* paddle::memory::legacy::Alloc<paddle::platform::CUDAPlace>(paddle::platform::CUDAPlace const&, unsigned long)
7   paddle::memory::legacy::GetGPUBuddyAllocator(int)
8   paddle::memory::legacy::GPUBuddyAllocatorList::Get(int)
9   std::call_once<paddle::memory::legacy::GPUBuddyAllocatorList::Get(int)::{lambda()#1}>(std::once_flag&, paddle::memory::legacy::GPUBuddyAllocatorList::Get(int)::{lambda()#1}&&)::{lambda()#2}::_FUN()
10  paddle::platform::GpuMaxChunkSize()
11  paddle::platform::GpuMaxAllocSize()
12  paddle::platform::GpuAvailableMemToAlloc()
13  paddle::platform::GpuMemoryUsage(unsigned long*, unsigned long*)
14  paddle::platform::RecordedCudaMemGetInfo(unsigned long*, unsigned long*, unsigned long*, unsigned long*, int)
15  paddle::framework::SignalHandle(char const*, int)
16  paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1622475357 (unix time) try "date -d @1622475357" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x3e800001215) received by PID 4709 (TID 0x7f4eddded740) from PID 4629 ***]

Traceback (most recent call last):
  File "tools/train.py", line 33, in <module>
    from ppdet.core.workspace import load_config, merge_config, create
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddledet-2.1.0-py3.7.egg/ppdet/__init__.py", line 15, in <module>
    from . import (core, data, engine, modeling, model_zoo, optimizer, metrics,
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddledet-2.1.0-py3.7.egg/ppdet/data/__init__.py", line 16, in <module>
    from . import transform
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddledet-2.1.0-py3.7.egg/ppdet/data/transform/__init__.py", line 15, in <module>
    from . import operators
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddledet-2.1.0-py3.7.egg/ppdet/data/transform/operators.py", line 41, in <module>
    from ppdet.modeling.layers import AnchorGrid
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddledet-2.1.0-py3.7.egg/ppdet/modeling/__init__.py", line 22, in <module>
    from . import proposal_generator
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddledet-2.1.0-py3.7.egg/ppdet/modeling/proposal_generator/__init__.py", line 1, in <module>
    from . import rpn_head
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddledet-2.1.0-py3.7.egg/ppdet/modeling/proposal_generator/rpn_head.py", line 58, in <module>
    class RPNHead(nn.Layer):
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddledet-2.1.0-py3.7.egg/ppdet/modeling/proposal_generator/rpn_head.py", line 74, in RPNHead
    anchor_generator=AnchorGenerator().__dict__,
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddledet-2.1.0-py3.7.egg/ppdet/modeling/proposal_generator/anchor_generator.py", line 57, in __init__
    self.cell_anchors = self._calculate_anchors(len(strides))
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddledet-2.1.0-py3.7.egg/ppdet/modeling/proposal_generator/anchor_generator.py", line 83, in _calculate_anchors
    for s, a in zip(sizes, aspect_ratios)
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddledet-2.1.0-py3.7.egg/ppdet/modeling/proposal_generator/anchor_generator.py", line 83, in <listcomp>
    for s, a in zip(sizes, aspect_ratios)
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddledet-2.1.0-py3.7.egg/ppdet/modeling/proposal_generator/anchor_generator.py", line 76, in generate_cell_anchors
    return paddle.to_tensor(anchors, dtype='float32')
  File "<decorator-gen-128>", line 2, in to_tensor
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 225, in __impl__
    return func(*args, **kwargs)
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/tensor/creation.py", line 160, in to_tensor
    stop_gradient=stop_gradient)
IndexError: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::Tensor::mutable_data(paddle::platform::Place const&, paddle::framework::proto::VarType_Type, unsigned long)
1   paddle::memory::AllocShared(paddle::platform::Place const&, unsigned long)
2   paddle::memory::allocation::AllocatorFacade::AllocShared(paddle::platform::Place const&, unsigned long)
3   paddle::memory::allocation::AllocatorFacade::Alloc(paddle::platform::Place const&, unsigned long)
4   paddle::memory::allocation::RetryAllocator::AllocateImpl(unsigned long)
5   paddle::memory::allocation::NaiveBestFitAllocator::AllocateImpl(unsigned long)
6   void* paddle::memory::legacy::Alloc<paddle::platform::CUDAPlace>(paddle::platform::CUDAPlace const&, unsigned long)
7   paddle::memory::legacy::GetGPUBuddyAllocator(int)
8   paddle::memory::legacy::GPUBuddyAllocatorList::Get(int)
9   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
10  paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
OutOfRangeError: The index exceeds the size of devices, the size of devices is 1, the index is 1
  [Hint: Expected pos < devices_.size(), but received pos:1 >= devices_.size():1.] (at /paddle/paddle/fluid/memory/allocation/naive_best_fit_allocator.cc:384)

使用该环境运行paddle seg进行多卡训练正常

**Comment by wangxinxin08** [comment]
你好，无法复现你的问题，可以echo $CUDA_VISIBLE_DEVICES看下可见的gpu有哪些？或者使用unset CUDA_VISIBLE_DEVICES取消环境变量试下

**Comment by lyuwenyu** [comment]
- 从错误信息看 只能发现一张卡 
- 建议 
  1. `重新起一个bash` 
  2. 查看一下设置是否起作用了 `echo $CUDA_VISIBLE_DEVICES` 
  3. 如果你只有2快卡 去掉这行`export CUDA_VISIBLE_DEVICES=0,1 `

**Comment by qiyuezhiguang** [comment]
paddle版本的问题。之前我下载了一个支持tensorrt的whl的paddle进行安装，paddlepaddle_gpu-2.1.0.post101-cp37-cp37m-linux_x86_64.whl，进行离线安装使用，用于paddleseg的tensorrt推理。目前更换为在线安装版本即可正常使用。感谢回复。如果你们有时间，可以去看看原因。

**Comment by qiyuezhiguang** [comment]
又发生一件很怪异的事情，在训练的时候增加评估，发现运行时报错，之后完全按照教程中的：python -m paddle.distributed.launch --gpus 0,1 tools/train.py -c configs/yolov3/yolov3_mobilenet_v1_roadsign.yml --eval
依然报错：
[06/01 16:12:08] ppdet.engine INFO: Epoch: [0] [ 0/43] learning_rate: 0.000033 loss_xy: 4.433845 loss_wh: 5.362845 loss_obj: 18005.015625 loss_cls: 4.765846 loss: 18019.578125 eta: 0:22:29 batch_cost: 0.7847 data_cost: 0.4470 ips: 10.1956 images/s
[06/01 16:12:14] ppdet.engine INFO: Epoch: [0] [20/43] learning_rate: 0.000047 loss_xy: 4.363085 loss_wh: 4.336348 loss_obj: 24.957405 loss_cls: 4.760259 loss: 39.241230 eta: 0:08:53 batch_cost: 0.2905 data_cost: 0.0470 ips: 27.5381 images/s
[06/01 16:12:19] ppdet.engine INFO: Epoch: [0] [40/43] learning_rate: 0.000060 loss_xy: 3.760677 loss_wh: 3.238577 loss_obj: 27.302900 loss_cls: 3.629137 loss: 38.599808 eta: 0:08:28 batch_cost: 0.2912 data_cost: 0.0720 ips: 27.4691 images/s
[06/01 16:12:23] ppdet.utils.checkpoint INFO: Save checkpoint: output/yolov3_mobilenet_v1_roadsign


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
1   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, paddle::platform::Place const&, bool, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
2   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap const&)
3   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 2ul, paddle::operators::SliceKernel<paddle::platform::CPUDeviceContext, int>, paddle::operators::SliceKernel<paddle::platform::CPUDeviceContext, long>, paddle::operators::SliceKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::SliceKernel<paddle::platform::CPUDeviceContext, double>, paddle::operators::SliceKernel<paddle::platform::CPUDeviceContext, paddle::platform::complex64>, paddle::operators::SliceKernel<paddle::platform::CPUDeviceContext, paddle::platform::complex128> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
4   void paddle::operators::SliceKernel<paddle::platform::CPUDeviceContext, float>::SliceCompute<2ul>(paddle::framework::ExecutionContext const&) const
5   Eigen::internal::TensorExecutor<Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 2, 1, int>, 16, Eigen::MakePointer>, Eigen::TensorSlicingOp<Eigen::DSizes<int, 2> const, Eigen::DSizes<int, 2> const, Eigen::TensorMap<Eigen::Tensor<float const, 2, 1, int>, 16, Eigen::MakePointer> const> const> const, Eigen::DefaultDevice, true, (Eigen::internal::TiledEvaluation)1>::run(Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 2, 1, int>, 16, Eigen::MakePointer>, Eigen::TensorSlicingOp<Eigen::DSizes<int, 2> const, Eigen::DSizes<int, 2> const, Eigen::TensorMap<Eigen::Tensor<float const, 2, 1, int>, 16, Eigen::MakePointer> const> const> const&, Eigen::DefaultDevice const&)
6   paddle::framework::SignalHandle(char const*, int)
7   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1622535143 (unix time) try "date -d @1622535143" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x4) received by PID 4676 (TID 0x7ff8e44f2740) from PID 4 ***]

INFO 2021-06-01 16:12:27,693 launch_utils.py:327] terminate all the procs
ERROR 2021-06-01 16:12:27,693 launch_utils.py:584] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0] was aborted. Please check its log.
![image](https://user-images.githubusercontent.com/46549313/120292897-4b3e0b00-c2f7-11eb-844a-b84ee9e1050d.png)
虽然在pycharm中代码已经停止运行，但查看显存发现程序还在运行，并且没有显示其pid，无法终止该进程。
感谢答复！
本人也是paddle的老用户了，遇到这个问题也是无奈了

**Comment by wangxinxin08** [comment]
可以将batch_size设置成>1，后续我们会修复这个问题

**Comment by qiyuezhiguang** [comment]
使用paddledetection2.1版本只要添加--eval就报错，并且代码错误后显存依然存在。
报错如下：
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
1   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, paddle::platform::Place const&, bool, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
2   std::shared_ptr<paddle::imperative::details::NameVarMapTrait<paddle::imperative::VarBase>::Type> paddle::imperative::PrepareData<paddle::imperative::VarBase>(paddle::framework::OperatorWithKernel const&, paddle::imperative::details::NameVarMapTrait<paddle::imperative::VarBase>::Type const&, paddle::framework::OpKernelType const&)
3   paddle::framework::TransformData(paddle::framework::OpKernelType const&, paddle::framework::OpKernelType const&, paddle::framework::Tensor const&, paddle::framework::Tensor*)
4   paddle::framework::TransDataDevice(paddle::framework::Tensor const&, paddle::platform::Place const&, paddle::framework::Tensor*)
5   paddle::framework::TensorCopySync(paddle::framework::Tensor const&, paddle::platform::Place const&, paddle::framework::Tensor*)
6   void paddle::memory::Copy<paddle::platform::CUDAPlace, paddle::platform::CUDAPinnedPlace>(paddle::platform::CUDAPlace, void*, paddle::platform::CUDAPinnedPlace, void const*, unsigned long, CUstream_st*)
7   paddle::platform::GpuMemcpySync(void*, void const*, unsigned long, cudaMemcpyKind)
8   paddle::framework::SignalHandle(char const*, int)
9   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1622554795 (unix time) try "date -d @1622554795" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x3e800005774) received by PID 22486 (TID 0x7fd445f3e740) from PID 22388 ***]


修改eval的batchsize为2，则提示shape不等，提示如下：
/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
[06/01 21:55:22] ppdet.engine INFO: Epoch: [0] [ 0/87] learning_rate: 0.000033 loss_xy: 5.248943 loss_wh: 4.947157 loss_obj: 16149.511719 loss_cls: 6.645195 loss: 16166.353516 eta: 0:12:43 batch_cost: 0.2193 data_cost: 0.0003 ips: 36.4747 images/s
[06/01 21:55:26] ppdet.engine INFO: Epoch: [0] [20/87] learning_rate: 0.000047 loss_xy: 4.143173 loss_wh: 3.738384 loss_obj: 25.039745 loss_cls: 4.128018 loss: 37.252663 eta: 0:11:28 batch_cost: 0.1980 data_cost: 0.0431 ips: 40.3952 images/s
[06/01 21:55:31] ppdet.engine INFO: Epoch: [0] [40/87] learning_rate: 0.000060 loss_xy: 3.630267 loss_wh: 2.616858 loss_obj: 15.786327 loss_cls: 3.160918 loss: 25.451355 eta: 0:12:33 batch_cost: 0.2401 data_cost: 0.0979 ips: 33.3193 images/s
[06/01 21:55:35] ppdet.engine INFO: Epoch: [0] [60/87] learning_rate: 0.000073 loss_xy: 3.453525 loss_wh: 1.832966 loss_obj: 8.183016 loss_cls: 2.816595 loss: 16.733578 eta: 0:12:20 batch_cost: 0.2114 data_cost: 0.0729 ips: 37.8359 images/s
[06/01 21:55:39] ppdet.engine INFO: Epoch: [0] [80/87] learning_rate: 0.000087 loss_xy: 3.182344 loss_wh: 1.516601 loss_obj: 6.398062 loss_cls: 2.457794 loss: 13.616261 eta: 0:12:07 batch_cost: 0.2065 data_cost: 0.0529 ips: 38.7378 images/s
[06/01 21:55:43] ppdet.utils.checkpoint INFO: Save checkpoint: output/yolov3_mobilenet_v1_roadsign
ERROR:root:DataLoader reader thread raised an exception!
Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 111, in run
    trainer.train(FLAGS.eval)
  File "/home/zhuhuijie/code/PaddleDetection/ppdet/engine/trainer.py", line 350, in train
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 411, in _thread_loop
    batch = self._get_data()
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 525, in _get_data
    batch.reraise()
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 168, in reraise
    raise self.exc_type(msg)
ValueError: DataLoader worker(1) caught ValueError with message:
Traceback (most recent call last):
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 228, in _worker_loop
    batch = fetcher.fetch(indices)
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 66, in fetch
    data = self.collate_fn(data)
  File "/home/zhuhuijie/code/PaddleDetection/ppdet/data/reader.py", line 93, in __call__
    batch_data = default_collate_fn(data)
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 70, in default_collate_fn
    for key in sample
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 70, in <dictcomp>
    for key in sample
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 58, in default_collate_fn
    batch = np.stack(batch, axis=0)
  File "<__array_function__ internals>", line 6, in stack
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/numpy/core/shape_base.py", line 427, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape


    self._eval_with_loader(self._eval_loader)
  File "/home/zhuhuijie/code/PaddleDetection/ppdet/engine/trainer.py", line 362, in _eval_with_loader
    for step_id, data in enumerate(loader):
  File "/home/zhuhuijie/code/PaddleDetection/ppdet/data/reader.py", line 211, in __next__
    return next(self.loader)
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 585, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)


 另外下载paddledetection2.0版本添加--eval一切都正常
因此感觉是paddledetection2.1版本中代码中的bug

**Comment by qiyuezhiguang** [comment]
paddledetection版本为
python -m pip install paddlepaddle-gpu==2.1.0.post101 -f https://paddlepaddle.org.cn/whl/mkl/stable.html
感谢回复

**Comment by qiyuezhiguang** [comment]
echo $CUDA_VISIBLE_DEVICES命令无显示，unset CUDA_VISIBLE_DEVICES后运行依然报错。单卡运行正常。

**Comment by wangxinxin08** [comment]
可以检验下你nccl的安装是否正常
