### ISSUE TITLE
paddle2.1中使用faster-rcnn_r50_fpn_1x_coco.yml训练时出现Please set find_unused_parameters=True 错误

### ISSUE THREAD

**Issue by wxf764571829** [PaddlePaddle/PaddleDetection#3260]
(paddle) ubuntu01@ubuntu01-System-Product-Name:/home/code/paddle/PaddleDetection-release-2.1$ python -m paddle.distributed.                                                                               launch --gpus 0,1 tools/train.py -c /home/code/paddle/PaddleDetection-release-2.1/configs/faster_rcnn/faster_rcnn_r50_fpn_1                                                                               x_coco.yml
-----------  Configuration Arguments -----------
gpus: 0,1
heter_worker_num: None
heter_workers:
http_port: None
ips: 127.0.0.1
log_dir: log
nproc_per_node: None
run_mode: None
server_num: None
servers:
training_script: tools/train.py
training_script_args: ['-c', '/home/code/paddle/PaddleDetection-release-2.1/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco                                                                               .yml']
worker_num: None
workers:
------------------------------------------------
WARNING 2021-06-03 13:58:34,911 launch.py:356] Not found distinct arguments and compiled with cuda or xpu. Default use coll                                                                               ective mode
launch train in GPU mode!
INFO 2021-06-03 13:58:34,913 launch_utils.py:507] Local start 2 processes. First process distributed environment info (Only                                                                                For Debug):
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:50131               |
    |                     PADDLE_TRAINERS_NUM                        2                      |
    |                PADDLE_TRAINER_ENDPOINTS         127.0.0.1:50131,127.0.0.1:59571       |
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                       0,1                     |
    |                     FLAGS_selected_gpus                        0                      |
    |             FLAGS_selected_accelerators                        0                      |
    +=======================================================================================+

INFO 2021-06-03 13:58:34,913 launch_utils.py:512] details abouts PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log                                                                               , and detail running logs maybe found in log/workerlog.0
launch proc_id:2019 idx:0
launch proc_id:2024 idx:1
/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.obj                                                                               ect` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not m                                                                               odify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
I0603 13:58:52.869782  2019 nccl_context.cc:74] init nccl context nranks: 2 local rank: 0 gpu id: 0 ring id: 0
W0603 13:58:53.099723  2019 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version:                                                                                10.1, Runtime API Version: 10.1
W0603 13:58:53.560335  2019 device_context.cc:422] device: 0, cuDNN Version: 7.6.
loading annotations into memory...
Done (t=0.05s)
creating index...
index created!
[06/03 13:59:00] ppdet.data.source.coco WARNING: Illegal image file: dataset/coco/dianpian/JPEGImages/5.jpg, and it will be                                                                                ignored
[06/03 13:59:00] ppdet.data.source.coco WARNING: Illegal image file: dataset/coco/dianpian/JPEGImages/61.jpg, and it will b                                                                               e ignored
[06/03 13:59:00] ppdet.data.source.coco WARNING: Illegal image file: dataset/coco/dianpian/JPEGImages/62.jpg, and it will b                                                                               e ignored
[06/03 13:59:00] ppdet.data.source.coco WARNING: Illegal image file: dataset/coco/dianpian/JPEGImages/91.jpg, and it will b                                                                               e ignored
[06/03 13:59:00] ppdet.data.source.coco WARNING: Illegal image file: dataset/coco/dianpian/JPEGImages/931.jpg, and it will                                                                                be ignored
/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.obj                                                                               ect` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not m                                                                               odify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
[06/03 13:59:02] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/ubuntu01/.cache/paddle/weights/ResNet50_c                                                                               os_pretrained.pdparams
[06/03 13:59:03] ppdet.engine INFO: Epoch: [0] [   0/1654] learning_rate: 0.000500 loss_rpn_cls: 0.678405 loss_rpn_reg: 0.0                                                                               00000 loss_bbox_cls: 0.701387 loss_bbox_reg: 0.000065 loss: 1.379857 eta: 10:49:14 batch_cost: 1.1776 data_cost: 0.0002 ips                                                                               : 1.6984 images/s
Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 111, in run
    trainer.train(FLAGS.eval)
  File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddledet-2.1.0-py3.8.egg/ppdet/engine/trainer.py"                                                                               , line 310, in train
    loss.backward()
  File "<decorator-gen-123>", line 2, in backward
  File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __                                                                               impl__
    return wrapped_func(*args, **kwargs)
  File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/framework.py", line 225, in __impl__
    return func(*args, **kwargs)
  File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", li                                                                               ne 235, in backward
    core.dygraph_run_backward([self], [grad_tensor], retain_graph,
RuntimeError: (PreconditionNotMet) Error happened, when parameter[74][conv2d_63.b_0@GRAD] has been ready before. Please set   find_unused_parameters=True to traverse backward graph in each step to prepare reduce in advance. If you have set, there may be several reasons for this error: 1) In multiple reentrant backward phase, some parameters are reused.2) Using model pa                                                                               rameters outside of forward function. Please make sure that model parameters are not shared in concurrent forward-backward                                                                                passes.
  [Hint: Expected has_marked_unused_vars_ == false, but received has_marked_unused_vars_:1 != false:0.] (at /paddle/paddle/                                                                               fluid/imperative/reducer.cc:645)

INFO 2021-06-03 13:59:11,064 launch_utils.py:327] terminate all the procs
ERROR 2021-06-03 13:59:11,065 launch_utils.py:582] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0] was ab                                                                               orted. Please check its log.
INFO 2021-06-03 13:59:14,068 launch_utils.py:327] terminate all the procs
(paddle) ubuntu01@ubuntu01-System-Product-Name:/home/code/paddle/PaddleDetection-release-2.1$ RuntimeError: (PreconditionNotMet) Error happenedPlease set                                                                                find_unused_parameters=True

**Comment by wxf764571829** [comment]
参照设置后 没问题：https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/mot/jde/_base_/jde_darknet53.yml#L3
