### ISSUE TITLE
PAFnet 前向出错

### ISSUE THREAD

**Issue by zhangming8** [PaddlePaddle/PaddleDetection#3262]
使用pafnet时，当执行 python tools/eval.py -c configs/ttfnet/pafnet_10x_coco.yml -o weights=https://paddledet.bj.bcebos.com/models/pafnet_10x_coco.pdparams --bias

出现了如下报错：
W0603 14:48:51.690886 12064 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.2, Runtime API Version: 10.1
W0603 14:48:51.696866 12064 device_context.cc:422] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "tools/eval.py", line 134, in <module>
    main()
  File "tools/eval.py", line 130, in main
    run(FLAGS, cfg)
  File "tools/eval.py", line 99, in run
    trainer = Trainer(cfg, mode='eval')
  File "C:\Users\DELL\anaconda3\envs\paddle-gpu-2.0.0\lib\site-packages\ppdet-2.0rc0-py3.7.egg\ppdet\engine\trainer.py", line 59, in __init__
    self.model = create(cfg.architecture)
  File "C:\Users\DELL\anaconda3\envs\paddle-gpu-2.0.0\lib\site-packages\ppdet-2.0rc0-py3.7.egg\ppdet\core\workspace.py", line 239, in create
    cls_kwargs.update(cls.from_config(config, **kwargs))
  File "C:\Users\DELL\anaconda3\envs\paddle-gpu-2.0.0\lib\site-packages\ppdet-2.0rc0-py3.7.egg\ppdet\modeling\architectures\ttfnet.py", line 57, in from_config
    neck = create(cfg['neck'], **kwargs)
  File "C:\Users\DELL\anaconda3\envs\paddle-gpu-2.0.0\lib\site-packages\ppdet-2.0rc0-py3.7.egg\ppdet\core\workspace.py", line 276, in create
    return cls(**cls_kwargs)
TypeError: __init__() got an unexpected keyword argument 'planes'

貌似定义网络时，中的planes字段识别不了。

**Comment by heavengate** [comment]
你好，你用的是哪个版本的代码，我本地测了下应该是可以跑通的

**Comment by nemonameless** [comment]
建议使用最新的release/2.1分支

**Comment by zhangming8** [comment]
解决了，是我的代码版本问题
