### ISSUE TITLE
s2anet训练的几个小bug

### ISSUE THREAD

**Issue by qiyuezhiguang** [PaddlePaddle/PaddleDetection#3275]
1数据转化bug
（1）在dataset文件夹下的dota_coco中的data_to_coco.py中，30行from ppdet.modeling.bbox_utils import poly_to_rbox，但提示无poly_to_rbox函数，后查看bbox_utils发现该函数命名为poly2rbox，将名字统一后不再报错。
（2）data_to_coco.py脚本中第135行和139行都为data_dict['annotations'].append(single_obj)，这样会导致每个annotations会保存2个，且第一个annotations缺少id，故将135行注释掉正常运行。
（3）该脚本中后续的json.dump(data_dict, f, indent=4)，建议增加indent=4，会自动对齐格式。
2训练中的bug
（1）无论单卡还是多卡训练，当把train的batchsize修改>1时，输入命令为
 python -m paddle.distributed.launch --gpus 0,1 tools/train.py          -c configs/dota/s2anet_1x_dota.yml           --eval
则报错：

-----------  Configuration Arguments -----------
gpus: 0,1
heter_worker_num: None
heter_workers: 
http_port: None
ips: 127.0.0.1
log_dir: log
nproc_per_node: None
run_mode: None
server_num: None
servers: 
training_script: tools/train.py
training_script_args: ['-c', 'configs/dota/s2anet_1x_dota.yml', '--eval']
worker_num: None
workers: 
------------------------------------------------
WARNING 2021-06-04 10:38:06,057 launch.py:357] Not found distinct arguments and compiled with cuda or xpu. Default use collective mode
launch train in GPU mode!
INFO 2021-06-04 10:38:06,057 launch_utils.py:621] Change selected_gpus into reletive values. --ips:0,1 will change into relative_ips:[0, 1] according to your CUDA_VISIBLE_DEVICES:['0', '1']
INFO 2021-06-04 10:38:06,058 launch_utils.py:510] Local start 2 processes. First process distributed environment info (Only For Debug): 
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:48629               |
    |                     PADDLE_TRAINERS_NUM                        2                      |
    |                PADDLE_TRAINER_ENDPOINTS         127.0.0.1:48629,127.0.0.1:36117       |
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                       0,1                     |
    |                     FLAGS_selected_gpus                        0                      |
    |             FLAGS_selected_accelerators                        0                      |
    +=======================================================================================+

INFO 2021-06-04 10:38:06,058 launch_utils.py:514] details abouts PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
launch proc_id:24210 idx:0
launch proc_id:24215 idx:1
/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
I0604 10:38:08.862262 24210 nccl_context.cc:74] init nccl context nranks: 2 local rank: 0 gpu id: 0 ring id: 0
W0604 10:38:09.242194 24210 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.2, Runtime API Version: 10.1
W0604 10:38:09.246592 24210 device_context.cc:422] device: 0, cuDNN Version: 7.6.
loading annotations into memory...
Done (t=1.06s)
creating index...
index created!
/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
[06/04 10:38:13] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/zhuhuijie/.cache/paddle/weights/ResNet50_cos_pretrained.pdparams
loading annotations into memory...
Done (t=0.91s)
creating index...
index created!
/home/zhuhuijie/PaddleDetection/ppdet/modeling/bbox_utils.py:296: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.float(pt2[1] - pt1[1]), np.float(pt2[0] - pt1[0]))
/home/zhuhuijie/PaddleDetection/ppdet/modeling/bbox_utils.py:306: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x_ctr = np.float(pt1[0] + pt3[0]) / 2
/home/zhuhuijie/PaddleDetection/ppdet/modeling/bbox_utils.py:307: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_ctr = np.float(pt1[1] + pt3[1]) / 2
/home/zhuhuijie/PaddleDetection/ppdet/modeling/bbox_utils.py:299: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.float(pt4[1] - pt1[1]), np.float(pt4[0] - pt1[0]))
WARNING:root:DataLoader reader thread raised an exception.
Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 199, in _thread_loop
    six.reraise(*sys.exc_info())
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 167, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices)
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 66, in fetch
    data = self.collate_fn(data)
  File "/home/zhuhuijie/PaddleDetection/ppdet/data/reader.py", line 93, in __call__
    batch_data = default_collate_fn(data)
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 70, in default_collate_fn
    for key in sample
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 70, in <dictcomp>
    for key in sample
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 58, in default_collate_fn
    batch = np.stack(batch, axis=0)
  File "<__array_function__ internals>", line 6, in stack
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/numpy/core/shape_base.py", line 427, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape
    
run(FLAGS, cfg)
  File "tools/train.py", line 111, in run
    trainer.train(FLAGS.eval)
  File "/home/zhuhuijie/PaddleDetection/ppdet/engine/trainer.py", line 289, in train
    for step_id, data in enumerate(self.loader):
  File "/home/zhuhuijie/PaddleDetection/ppdet/data/reader.py", line 211, in __next__
    return next(self.loader)
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 204, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

INFO 2021-06-04 10:38:21,109 launch_utils.py:327] terminate all the procs
ERROR 2021-06-04 10:38:21,110 launch_utils.py:584] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0, 1] was aborted. Please check its log.
INFO 2021-06-04 10:38:24,113 launch_utils.py:327] terminate all the procs
（2）训练的时候增加eval也会报错
输入命令为
 python -m paddle.distributed.launch --gpus 0,1 tools/train.py          -c configs/dota/s2anet_1x_dota.yml           --eval
报错为
[06/04 08:26:51] ppdet.utils.checkpoint INFO: Save checkpoint: output/s2anet_1x_dota_me
[06/04 08:26:51] ppdet.engine INFO: Eval iter: 0
[06/04 08:27:30] ppdet.engine INFO: Eval iter: 100
[06/04 08:28:09] ppdet.engine INFO: Eval iter: 200
[06/04 08:28:50] ppdet.engine INFO: Eval iter: 300
[06/04 08:29:30] ppdet.engine INFO: Eval iter: 400
[06/04 08:30:10] ppdet.engine INFO: Eval iter: 500
[06/04 08:30:50] ppdet.engine INFO: Eval iter: 600
[06/04 08:31:29] ppdet.engine INFO: Eval iter: 700
[06/04 08:32:08] ppdet.engine INFO: Eval iter: 800
[06/04 08:32:47] ppdet.engine INFO: Eval iter: 900
[06/04 08:33:26] ppdet.engine INFO: Eval iter: 1000
[06/04 08:34:05] ppdet.engine INFO: Eval iter: 1100
[06/04 08:34:44] ppdet.engine INFO: Eval iter: 1200
[06/04 08:35:22] ppdet.engine INFO: Eval iter: 1300
[06/04 08:36:02] ppdet.engine INFO: Eval iter: 1400
[06/04 08:36:04] ppdet.metrics.metrics INFO: The bbox result is saved to bbox.json.
loading annotations into memory...
Done (t=0.90s)
creating index...
index created!
[06/04 08:36:06] ppdet.metrics.coco_utils INFO: Start evaluate...
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 111, in run
    trainer.train(FLAGS.eval)
  File "/home/zhuhuijie/code/PaddleDetection1/ppdet/engine/trainer.py", line 317, in train
    self._eval_with_loader(self._eval_loader)
  File "/home/zhuhuijie/code/PaddleDetection1/ppdet/engine/trainer.py", line 347, in _eval_with_loader
    metric.accumulate()
  File "/home/zhuhuijie/code/PaddleDetection1/ppdet/metrics/metrics.py", line 116, in accumulate
    classwise=self.classwise)
  File "/home/zhuhuijie/code/PaddleDetection1/ppdet/metrics/coco_utils.py", line 96, in cocoapi_eval
    coco_eval.evaluate()
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/pycocotools/cocoeval.py", line 149, in evaluate
    for imgId in p.imgIds
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/pycocotools/cocoeval.py", line 150, in <dictcomp>
    for catId in catIds}
  File "/home/zhuhuijie/anaconda3/envs/paddle_env/lib/python3.7/site-packages/pycocotools/cocoeval.py", line 189, in computeIoU
    ious = maskUtils.iou(d,g,iscrowd)
  File "pycocotools/_mask.pyx", line 215, in pycocotools._mask.iou
  File "pycocotools/_mask.pyx", line 193, in pycocotools._mask.iou._preproc
Exception: list input can be bounding box (Nx4) or RLEs ([RLE])
INFO 2021-06-04 08:36:11,837 launch_utils.py:327] terminate all the procs
ERROR 2021-06-04 08:36:11,838 launch_utils.py:584] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-06-04 08:36:14,841 launch_utils.py:327] terminate all the procs

**Comment by liuhuiCNN** [comment]
您好，感谢反馈。（1）脚本中问题develop中已修复；（2）bs>1功能正在适配；（3）目前s2anet暂不支持边训练边测试，您可以通过`dataset/dota_coco/dota_generate_test_result.py`生成测试文件，上传网站测评。

**Comment by liuhuiCNN** [comment]
fix in #3401
