### ISSUE TITLE
yolov3 模型训练过程中，报错 No space left on device

### ISSUE THREAD

**Issue by Lutl** [PaddlePaddle/PaddleDetection#3279]
```
[06/04 07:20:11] ppdet.engine INFO: Epoch: [79] [300/313] learning_rate: 0.001000 loss_xy: 4.894498 loss_wh: 1.288355 loss_obj: 8.732889 loss_cls: 2.779666 loss: 17.233498 eta: 14:49:16 batch_cost: 0.8656 data_cost: 0.0003 ips: 9.2424 images/s
Traceback (most recent call last):
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddledet-2.1.0-py3.7.egg/ppdet/data/reader.py", line 211, in __next__
    return next(self.loader)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 609, in __next__
    six.reraise(*sys.exc_info())
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 585, in __next__
    data = self._reader.read_next_var_list()
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 111, in run
    trainer.train(FLAGS.eval)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddledet-2.1.0-py3.7.egg/ppdet/engine/trainer.py", line 289, in train
    for step_id, data in enumerate(self.loader):
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddledet-2.1.0-py3.7.egg/ppdet/data/reader.py", line 213, in __next__
    self.loader = iter(self.dataloader)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/reader.py", line 426, in __iter__
    return _DataLoaderIterMultiProcess(self)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 283, in __init__
    self._init_workers()
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 313, in _init_workers
    self._workers_done_event = multiprocessing.Event()
  File "/usr/local/python3.7.0/lib/python3.7/multiprocessing/context.py", line 92, in Event
    return Event(ctx=self.get_context())
  File "/usr/local/python3.7.0/lib/python3.7/multiprocessing/synchronize.py", line 324, in __init__
    self._cond = ctx.Condition(ctx.Lock())
  File "/usr/local/python3.7.0/lib/python3.7/multiprocessing/context.py", line 77, in Condition
    return Condition(lock, ctx=self.get_context())
  File "/usr/local/python3.7.0/lib/python3.7/multiprocessing/synchronize.py", line 214, in __init__
    self._sleeping_count = ctx.Semaphore(0)
  File "/usr/local/python3.7.0/lib/python3.7/multiprocessing/context.py", line 82, in Semaphore
    return Semaphore(value, ctx=self.get_context())
  File "/usr/local/python3.7.0/lib/python3.7/multiprocessing/synchronize.py", line 126, in __init__
    SemLock.__init__(self, SEMAPHORE, value, SEM_VALUE_MAX, ctx=ctx)
  File "/usr/local/python3.7.0/lib/python3.7/multiprocessing/synchronize.py", line 59, in __init__
    unlink_now)
OSError: [Errno 28] No space left on device
Exception ignored in: <function _DataLoaderIterMultiProcess.__del__ at 0x7fadacdf4050>
Traceback (most recent call last):
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 566, in __del__
    self._try_shutdown_all()
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 371, in _try_shutdown_all
    if not self._shutdown:
AttributeError: '_DataLoaderIterMultiProcess' object has no attribute '_shutdown'
INFO 2021-06-04 07:20:26,705 launch_utils.py:327] terminate all the procs
ERROR 2021-06-04 07:20:26,706 launch_utils.py:584] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-06-04 07:20:29,709 launch_utils.py:327] terminate all the procs
```
使用双卡训练，训练过程中间报错 No space left on device，但是硬盘空间是够的，不太清楚是哪里的问题，请问要修改哪些文件配置才能解决这个问题吗

**Comment by heavengate** [comment]
你好，`df -h`看下硬盘空间占用情况呢

**Comment by Lutl** [comment]
> 你好，`df -h`看下硬盘空间占用情况呢

```
Filesystem                                       Size  Used Avail Use% Mounted on
overlay                                          2.8T  670G  2.2T  24% /
tmpfs                                             64M     0   64M   0% /dev
tmpfs                                            126G     0  126G   0% /sys/fs/cgroup
/dev/mapper/centos-root                          442G  331G  112G  75% /paddle
/dev/mapper/bml--docker--data-bml--docker--data  2.8T  670G  2.2T  24% /etc/hosts
shm                                               64M   60M  4.4M  94% /dev/shm
tmpfs                                            126G   12K  126G   1% /proc/driver/nvidia
devtmpfs                                         126G     0  126G   0% /dev/nvidia0
tmpfs                                            126G     0  126G   0% /proc/acpi
tmpfs                                            126G     0  126G   0% /proc/scsi
tmpfs                                            126G     0  126G   0% /sys/firmware
```
因为是内网环境，所以直接pull的docker，然后自己装的paddledetection，空间都肯定够的啊

**Comment by heavengate** [comment]
看着你的`/dev/shm/`下空间不太够，修改下`configs/yolov3/_base_/yolov3_reader.yml`里面的`use_shared_memroy`设置为False试下呢

**Comment by ice-tong** [comment]
重启一下docker释放shared_memory，docker默认64m，不够的话启动容器的时候指定一下shm_size。
