### ISSUE TITLE
多尺度测试

### ISSUE THREAD

**Issue by sxlyiyiyi** [PaddlePaddle/PaddleDetection#3292]
当我尝试使用多尺度测试时，出现以下错误

[06/05 21:01:13] reader WARNING: fail to map op [PadBatch_f39505] with error: list indices must be integers or slices, not str and stack:
Traceback (most recent call last):
  File "E:\PaddleDetection\ppdet\data\reader.py", line 75, in __call__
    data = f(data)
  File "E:\PaddleDetection\ppdet\data\transform\batch_operators.py", line 62, in __call__
    max_shape = np.array([data['image'].shape for data in samples]).max(
  File "E:\PaddleDetection\ppdet\data\transform\batch_operators.py", line 62, in <listcomp>
    max_shape = np.array([data['image'].shape for data in samples]).max(
TypeError: list indices must be integers or slices, not str

Exception in thread Thread-10:
Traceback (most recent call last):
  File "C:\Users\sxl\anaconda3\envs\pd2\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\sxl\anaconda3\envs\pd2\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\sxl\anaconda3\envs\pd2\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 199, in _thread_loop
    six.reraise(*sys.exc_info())
  File "C:\Users\sxl\anaconda3\envs\pd2\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "C:\Users\sxl\anaconda3\envs\pd2\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 167, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices)
  File "C:\Users\sxl\anaconda3\envs\pd2\lib\site-packages\paddle\fluid\dataloader\fetcher.py", line 66, in fetch
    data = self.collate_fn(data)
  File "E:\PaddleDetection\ppdet\data\reader.py", line 80, in __call__
    raise e
  File "E:\PaddleDetection\ppdet\data\reader.py", line 75, in __call__
    data = f(data)
  File "E:\PaddleDetection\ppdet\data\transform\batch_operators.py", line 62, in __call__
    max_shape = np.array([data['image'].shape for data in samples]).max(
  File "E:\PaddleDetection\ppdet\data\transform\batch_operators.py", line 62, in <listcomp>
    max_shape = np.array([data['image'].shape for data in samples]).max(
TypeError: list indices must be integers or slices, not str

**Comment by yghstill** [comment]
@sxlyiyiyi 是release/2.0或者2.1中动态图模型使用MultiscaleTestResize时报错吗？动态图下多尺度测试支持还不完备，我们近期会高优支持下，可以暂时先使用单尺度预测。

**Comment by sxlyiyiyi** [comment]
> @sxlyiyiyi 是release/2.0或者2.1中动态图模型使用MultiscaleTestResize时报错吗？动态图下多尺度测试支持还不完备，我们近期会高优支持下，可以暂时先使用单尺度预测。

是的，是在动态图模型下使用的
