### ISSUE TITLE
ppdet2.0rc 的 solov2 在CPU推理的时候如何修改使用多线程推理？

### ISSUE THREAD

**Issue by hitsz-zuoqi** [PaddlePaddle/PaddleDetection#3293]
在pytorch里面torch.set_num_threads(n)可以设置cpu推理时使用的线程数，但是看2.0rc的inference脚本好像没有这个参数？

**Comment by liuhuiCNN** [comment]
您可以通过 `config.set_cpu_math_library_num_threads(4)` 设置CPU线程数，请参考文档： https://paddle-inference.readthedocs.io/en/latest/api_reference/python_api_doc/Config/CPUConfig.html#id1

**Comment by hitsz-zuoqi** [comment]
仔细看了一下deploy模块，确实很好用，但有一点疑惑：
1、2.1版本的infer.py脚本是否支持2.0rc的模型，比如说solov2_r101_vd_fpn_3x.yml？
2、如果可以，2.0版本导出的是__model__  __params__  infer_cfg.yml,而2.1版本导出的是四个文件infer_cfg.yml, model.pdiparams, model.pdiparams.info, model.pdmodel，请问我可以替换infer脚本为2.1版本的但是可以使用solov2_r101_vd_fpn_3x.yml这个模型嘛？？我发现r101在2.1的ppdet还没有pretrained

**Comment by hitsz-zuoqi** [comment]
# 引用 paddle inference 预测库
import paddle.inference as paddle_infer

# 创建 config
config = paddle_infer.Config()

# 通过 API 设置模型文件夹路径
config.set_prog_file("./mobilenet_v2/__model__")
config.set_params_file("./mobilenet_v2/__params__")

# 通过 API 获取 config 中的模型文件和参数文件路径
print(config.prog_file())
print(config.params_file())

# 根据 config 创建 predictor
predictor = paddle_infer.create_predictor(config)

我在paddle inference下找到了这段代码，好像与我导出模型是一致的，我先尝试一下

**Comment by hitsz-zuoqi** [comment]
Traceback (most recent call last):
  File "inference.py", line 24, in <module>
    predictor.run()
ValueError: In user code:

    File "tools/export_model.py", line 89, in <module>
      main()
    File "tools/export_model.py", line 63, in main
      test_fetches = model.test(feed_vars, exclude_nms=FLAGS.exclude_nms)
    File "/workspace/PaddleDetection-release-2.0-rc/ppdet/modeling/architectures/solov2.py", line 175, in test
      return self.build(feed_vars, mode='test')
    File "/workspace/PaddleDetection-release-2.0-rc/ppdet/modeling/architectures/solov2.py", line 110, in build
      return self.bbox_head.get_prediction(*seg_inputs)
    File "/workspace/PaddleDetection-release-2.0-rc/ppdet/modeling/anchor_heads/solov2_head.py", line 337, in get_prediction
      im_info[idx])
    File "/opt/conda/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/framework.py", line 1832, in __getitem__
      return _getitem_impl_(self, item)
    File "/opt/conda/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/framework.py", line 944, in _getitem_impl_
      target_block.append_op(
    File "/opt/conda/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3226, in append_op
      op = Operator(
    File "/opt/conda/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2312, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The tensor Input (Input) of Slice op is not initialized.
      [Hint: Expected in_tensor.IsInitialized() == true, but received in_tensor.IsInitialized():0 != true:1.] (at /paddle/paddle/fluid/operators/slice_op.cc:178)
      [operator < slice > error]

**Comment by hitsz-zuoqi** [comment]
inference.py 
`import paddle.inference as paddle_infer
import numpy
config = paddle_infer.Config("./inference_model/solov2_r101_vd_fpn_3x/__model__","./inference_model/solov2_r101_vd_fpn_3x/__params__")

#config.set_prog_file("./inference_model/solov2_r101_vd_fpn_3x/__model__")
#config.set_params_file("./inference_model/solov2_r101_vd_fpn_3x/__params__")

print(config.prog_file())
print(config.params_file())
config.set_cpu_math_library_num_threads(16)
print(config.cpu_math_library_num_threads())
config.enable_mkldnn()
print(config.mkldnn_enabled())
config.enable_mkldnn_bfloat16()
config.set_bfloat16_op({"conv2d"})
config.enable_memory_optim()
#config.enable_profile()

predictor = paddle_infer.create_predictor(config)
input_names = predictor.get_input_names()
input_tensor = predictor.get_input_handle(input_names[0])
fake_input = numpy.random.randn(1, 3, 224, 224).astype("float32")
input_tensor.copy_from_cpu(fake_input)
predictor.run()

output_names = predictor.get_output_names()
output_tensor = predictor.get_output_handle(output_names[0])
predictor.clear_intermediate_tensor()
predictor.try_shrink_memory()`

我怎么才能知道输入的大小？请问这个报错是什么意思呢，我按照文档导出模型后实验会报这个错。
