### ISSUE TITLE
S2ANet网络自制数据集，训练没问题，但是到了推理阶段报错。

### ISSUE THREAD

**Issue by ZJH970922** [PaddlePaddle/PaddleDetection#3308]
(paddle) G:\PaddleDetection\PaddleDetection-release-2.1>python tools/infer.py -c configs/dota/s2anet_1x_GIS.yml -o weights=G:\PaddleDetection\PaddleDetection-release-2.1\output\s2anet_1x_GIS\model_final.pdparams --infer_dir=G:\PaddleDetection\GIS_images\test --draw_threshold=0.05 --save_txt=True --output_dir=output
G:\Anaconda\envs\paddle\lib\site-packages\paddle\tensor\creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
W0607 20:34:31.286404 10560 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.2
W0607 20:34:31.301676 10560 device_context.cc:422] device: 0, cuDNN Version: 8.1.
G:\Anaconda\envs\paddle\lib\site-packages\paddle\tensor\creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
[06/07 20:34:34] ppdet.utils.checkpoint INFO: Finish loading model weights: G:\PaddleDetection\PaddleDetection-release-2.1\output\s2anet_1x_GIS\model_final.pdparams
[06/07 20:34:34] train INFO: Found 1 inference images in total.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Traceback (most recent call last):
  File "tools/infer.py", line 158, in <module>
    main()
  File "tools/infer.py", line 154, in main
    run(FLAGS, cfg)
  File "tools/infer.py", line 132, in run
    save_txt=FLAGS.save_txt)
  File "G:\Anaconda\envs\paddle\lib\site-packages\paddledet-2.1.0-py3.7.egg\ppdet\engine\trainer.py", line 418, in predict
    batch_res = get_infer_results(outs, clsid2catid)
  File "G:\Anaconda\envs\paddle\lib\site-packages\paddledet-2.1.0-py3.7.egg\ppdet\metrics\coco_utils.py", line 50, in get_infer_results
    outs['bbox'], outs['bbox_num'], im_id, catid, bias=bias)
  File "G:\Anaconda\envs\paddle\lib\site-packages\paddledet-2.1.0-py3.7.egg\ppdet\metrics\json_results.py", line 58, in get_det_poly_res
    category_id = label_to_cat_id_map[int(num_id)]
KeyError: 2

s2anet_1x_GIS.yml的num_classes: 1
请问各位大佬，这个报错怎么解决...

**Comment by liuhuiCNN** [comment]
请问您test reader中数据路径配置正确吗？

**Comment by ZJH970922** [comment]
test reader中数据路径配置是正确的，
在 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/configs/dota/README.md 中，进行 python tools/infer.py -c configs/dota/s2anet_1x_dota.yml -o weights=model.pdparams --infer_img=demo/P0072__1.0__0___0.png 可以输出相应的结果。
同时，我的数据集制作是根据 https://aistudio.baidu.com/aistudio/projectdetail/1890589?channelType=0&channel=0 进行的，但是到了最后一步的推理，出现了以上的问题...

**Comment by ZJH970922** [comment]
> 请问您test reader中数据路径配置正确吗？

同时，我对num_id和label_to_cat_id_map进行了打印，输出结果如下：
(paddle) G:\PaddleDetection\PaddleDetection-release-2.1>python tools/infer.py -c configs/dota/s2anet_1x_GIS.yml -o weights=G:\PaddleDetection\PaddleDetection-release-2.1\output\s2anet_1x_GIS\model_final.pdparams --infer_img=G:\Paddl
eDetection\GIS_images\test\0004.jpg
W0609 21:24:59.169337 12080 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.2
W0609 21:24:59.169337 12080 device_context.cc:422] device: 0, cuDNN Version: 8.1.
[06/09 21:25:01] ppdet.utils.checkpoint INFO: Finish loading model weights: G:\PaddleDetection\PaddleDetection-release-2.1\output\s2anet_1x_GIS\model_final.pdparams
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
num_id 2.0
label_to_cat_id_map {0: 1}
Traceback (most recent call last):
  File "tools/infer.py", line 158, in <module>
    main()
  File "tools/infer.py", line 154, in main
    run(FLAGS, cfg)
  File "tools/infer.py", line 132, in run
    save_txt=FLAGS.save_txt)
  File "G:\Anaconda\envs\paddle\lib\site-packages\paddledet-2.1.0-py3.7.egg\ppdet\engine\trainer.py", line 418, in predict
    batch_res = get_infer_results(outs, clsid2catid)
  File "G:\Anaconda\envs\paddle\lib\site-packages\paddledet-2.1.0-py3.7.egg\ppdet\metrics\coco_utils.py", line 50, in get_infer_results
    outs['bbox'], outs['bbox_num'], im_id, catid, bias=bias)
  File "G:\Anaconda\envs\paddle\lib\site-packages\paddledet-2.1.0-py3.7.egg\ppdet\metrics\json_results.py", line 60, in get_det_poly_res
    category_id = label_to_cat_id_map[int(num_id)]
KeyError: 2

请问是什么原因造成的，应该怎么解决？

**Comment by liuhuiCNN** [comment]
感谢反馈，这个问题是由于label_to_cat_id_map字段错误导致的，我们近期会解决。

**Comment by ZJH970922** [comment]
> 感谢反馈，这个问题是由于label_to_cat_id_map字段错误导致的，我们近期会解决。

不客气，如果完善好了，也和我说一声，非常感谢。

**Comment by liuhuiCNN** [comment]
fix in #3401
