### ISSUE TITLE
FairMOT训练：在Aistudio上，用MOT20作为训练集时，训练报错。

### ISSUE THREAD

**Issue by zouzhuo777** [PaddlePaddle/PaddleDetection#3310]
修改configs/datasets/mot.yaml如下：
TrainDataset:
  !MOTDataSet
    dataset_dir: /home/aistudio/MOT20
    image_lists: ['mot20.train']
    data_fields: ['image', 'gt_bbox', 'gt_class', 'gt_ide']
    
用GPU单卡训练：
CUDA_VISIBLE_DEVICES=0 python tools/train.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml

报错信息为：
Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 102, in run
    trainer = Trainer(cfg, mode='train')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/engine/trainer.py", line 62, in __init__
    self.loader = create('{}Reader'.format(self.mode.capitalize()))(
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/core/workspace.py", line 276, in create
    return cls(**cls_kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/data/reader.py", line 236, in __init__
    num_classes, collate_batch, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/data/reader.py", line 147, in __init__
    sample_transforms, num_classes=num_classes)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/data/reader.py", line 46, in __init__
    op_cls = getattr(transform, k)
AttributeError: module 'ppdet.data.transform' has no attribute 'RGBReverse'

安装paddledet
安装的paddledetection版本为2.1.0，安装步骤为：
! pip install paddledet==2.1.0 -i https://mirror.baidu.com/pypi/simple
由于git clone速度慢，我把paddleDetection 2.1.0版本的压缩包上传到AiStudio并解压，代替了git clone。

奇怪的是，单独运行：
from ppdet.data.transform import RGBReverse
没有报错

**Comment by zouzhuo777** [comment]
安装的paddledetection版本为2.1.0，安装步骤为：
! pip install paddledet==2.1.0 -i https://mirror.baidu.com/pypi/simple
由于git clone速度慢，我把paddleDetection 2.1.0版本的压缩包上传到AiStudio并解压，代替了git clone。

**Comment by zouzhuo777** [comment]
奇怪的是，单独运行：
from ppdet.data.transform import RGBReverse
没有报错

**Comment by nemonameless** [comment]
#3278 你好，可以尝试卸载重装paddledet。paddleDetection 2.1.0版本的压缩包解压后，运行`python setup.py install` 安装。
