### ISSUE TITLE
ValueError: (InvalidArgument) The rois_batch_size and imgs batch_size must be the same

### ISSUE THREAD

**Issue by okooo5km** [PaddlePaddle/PaddleDetection#3332]
# 配置

使用 `cascade_rcnn_r50_fpn_1x_voc.yml` 进行评估，尝试 EvalReader 中设置大于 **1** 的 **batch_size**，其中 `EvalReader `自定义配置如下:

```yaml
EvalReader:
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 2, target_size: [720, 1280], keep_ratio: True}
  - NormalizeImage: {is_scale: true, mean: [0.4986, 0.4900, 0.4883], std: [0.0278, 0.0254, 0.0250]}
  - Permute: {}
  batch_size: 8
  collate_batch: false
```

进行评估：

```shell
python tools/eval.py -c configs/cascade_rcnn/cascade_rcnn_r50_fpn_1x_voc_bank.yml
```

# 报错

```shell
/data/tianye/.miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
W0609 00:59:05.337664 34703 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.2
W0609 00:59:05.339975 34703 device_context.cc:422] device: 0, cuDNN Version: 8.0.
W0609 00:59:06.074892 34703 device_context.h:360] WARNING: device: 0. The installed Paddle is compiled with CUDNN 8.1, but CUDNN version in your machine is 8.0, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
/data/tianye/.miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
[06/09 00:59:11] ppdet.utils.checkpoint INFO: Finish loading model weights: output/cascade_rcnn_r50_fpn_1x_voc_bank/best_model.pdparams
Traceback (most recent call last):
  File "tools/eval.py", line 134, in <module>
    main()
  File "tools/eval.py", line 130, in main
    run(FLAGS, cfg)
  File "tools/eval.py", line 105, in run
    trainer.evaluate()
  File "/data/tianye/paddle/PaddleDetection/ppdet/engine/trainer.py", line 388, in evaluate
    self._eval_with_loader(self.loader)
  File "/data/tianye/paddle/PaddleDetection/ppdet/engine/trainer.py", line 366, in _eval_with_loader
    outs = self.model(data)
  File "/data/tianye/.miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/data/tianye/paddle/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 29, in forward
    out = self.get_pred()
  File "/data/tianye/paddle/PaddleDetection/ppdet/modeling/architectures/cascade_rcnn.py", line 136, in get_pred
    bbox_pred, bbox_num, mask_pred = self._forward()
  File "/data/tianye/paddle/PaddleDetection/ppdet/modeling/architectures/cascade_rcnn.py", line 105, in _forward
    preds, _ = self.bbox_head(body_feats, rois, rois_num, self.inputs)
  File "/data/tianye/.miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/data/tianye/paddle/PaddleDetection/ppdet/modeling/heads/cascade_head.py", line 228, in forward
    rois_feat = self.roi_extractor(body_feats, rois, rois_num)
  File "/data/tianye/paddle/PaddleDetection/ppdet/modeling/heads/roi_extractor.py", line 106, in __call__
    aligned=self.aligned)
  File "/data/tianye/paddle/PaddleDetection/ppdet/modeling/ops.py", line 266, in roi_align
    "sampling_ratio", sampling_ratio, "aligned", aligned)
ValueError: (InvalidArgument) The rois_batch_size and imgs batch_size must be the same. But received rois_batch_size = 1, batch_size = 8
  [Hint: Expected rois_batch_size == batch_size, but received rois_batch_size:1 != batch_size:8.] (at /paddle/paddle/fluid/operators/roi_align_op.cu:277)
  [operator < roi_align > error]
```

**Comment by liuhuiCNN** [comment]
develop分支最新代码已支持faster rcnn bs>1，请用develop分支试下。

**Comment by okooo5km** [comment]
> develop分支最新代码已支持faster rcnn bs>1，请用develop分支试下。

好的，谢谢！

**Comment by 1450976314** [comment]
你好，我想问一下为什么会出现这个问题？

**Comment by okooo5km** [comment]
> 你好，我想问一下为什么会出现这个问题？

@1450976314 具体为什么，没有调试去细查原因，这应该是 bug，之前旧版本可以 eval batch_size 大于 1 的

**Comment by gujingxiao** [comment]
@smslit 您好，最新版的develop分支确实修复了cascade rcnn在eval时bs大于1的问题，但是当使用export model将模型进行输出，再使用deploy下infer的时候，当bs大于1时，依然会报同样的错误，还请进行排查。

    InvalidArgumentError: The rois_batch_size and imgs batch_size must be the same. But received rois_batch_size = 1, batch_size = 4
      [Hint: Expected rois_batch_size == batch_size, but received rois_batch_size:1 != batch_size:4.] (at /paddle/paddle/fluid/operators/roi_align_op.cu:277)
      [operator < roi_align > error]

**Comment by chaoshixie** [comment]
@gujingxiao 您好我也出现了同样的问题，您解决了吗？
	InvalidArgumentError: The rois_batch_size and imgs batch_size must be the same. But received rois_batch_size = 2, atch_size
