### ISSUE TITLE
使用ppyolo训练自己的数据集在第一轮结束时报错

### ISSUE THREAD

**Issue by RhythmF** [PaddlePaddle/PaddleDetection#3349]
第一轮训练结束时报错如下：
IndexError: index 1 is out of bounds for axis 0 with size 1

自己的数据集格式是voc的，此前调用了conflgs中的其他模型可以正常训练和预测
这次调用的是ppyolo_r50vd_dcn_voc.yml(好像只有这一个支持VOC)
训练大概在第一轮要结束时出现如下报错

```
Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 111, in run
    trainer.train(FLAGS.eval)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/engine/trainer.py", line 317, in train
    self._eval_with_loader(self._eval_loader)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/engine/trainer.py", line 337, in _eval_with_loader
    metric.update(data, outs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/metrics/metrics.py", line 222, in update
    bbox_num = bbox_lengths[i]
IndexError: index 1 is out of bounds for axis 0 with size 1
```

求大佬解答

**Comment by qingqing01** [comment]
@RhythmF 您使用的PaddleDetection版本是多少？

您看下yml配置里是否包含:

https://github.com/PaddlePaddle/PaddleDetection/blob/27d4a24d31c9c68160acf77eeb1b33575aed7333/configs/ppyolo/ppyolo_r50vd_dcn_voc.yml#L20
