### ISSUE TITLE
请问这个target怎么预先初始化？

### ISSUE THREAD

**Issue by zsbjmy** [PaddlePaddle/PaddleDetection#3350]
```
Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 111, in run
    trainer.train(FLAGS.eval)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/engine/trainer.py", line 274, in train
    outputs = model(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/modeling/architectures/meta_arch.py", line 27, in forward
    out = self.get_loss()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/modeling/architectures/yolo.py", line 72, in get_loss
    return self._forward()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/modeling/architectures/yolo.py", line 63, in _forward
    return self.yolo_head(body_feats, self.inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/modeling/heads/yolo_head.py", line 95, in forward
    return self.loss(yolo_outputs, targets, self.anchors)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/modeling/losses/yolo_loss.py", line 187, in forward
    gt_targets = [targets['target{}'.format(i)] for i in range(np)]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/modeling/losses/yolo_loss.py", line 187, in <listcomp>
    gt_targets = [targets['target{}'.format(i)] for i in range(np)]
KeyError: 'target3'
```

**Comment by qingqing01** [comment]
请问您有改动什么吗？数据集是COCO还是VOC？理论上数据集准备正确的话，不会出错

**Comment by zsbjmy** [comment]
您好,ppyolo骨干我使用resent50，骨干返回【0，1，2，3】四个特征层，想使用4倍降采样的特征层。我想对网络进行适当的更改，请问我应该更改哪个路径下的源文件？

**Comment by qingqing01** [comment]
@zsbjmy 您如果是将ppyolo原先的3个尺度改成4个尺度的话:


YOLOHead中的anchor需要调整支持4个尺度:

https://github.com/PaddlePaddle/PaddleDetection/blob/27d4a24d31c9c68160acf77eeb1b33575aed7333/configs/ppyolo/_base_/ppyolo_r50vd_dcn.yml#L29

预处理产出生target的地方，也需要相应调整:
https://github.com/PaddlePaddle/PaddleDetection/blob/27d4a24d31c9c68160acf77eeb1b33575aed7333/configs/ppyolo/_base_/ppyolo_reader.yml#L19

**Comment by zsbjmy** [comment]
非常感谢您的帮助！请问如果我想在neck:YOLOV3FPN中加入注意力机制，我可以修改哪个文件？

**Comment by qingqing01** [comment]
FPN相关的实现都在 `ppdet/modeling/necks` 下面:

https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/modeling/necks/yolo_fpn.py#L429

modeling下面的结构，看名字:

```
architectures: 每类算法主体代码，子模块由下面backbone，heads等组成
backbones: 主干网络
heads: 检测头
losses: 损失函数
mot: 多目标跟踪相关
necks: FPN相关
```

**Comment by qingqing01** [comment]
related to https://github.com/PaddlePaddle/PaddleDetection/issues/3368
