### ISSUE TITLE
ssd_mobilenet_v1_voc.pdparams to load model not exists

### ISSUE THREAD

**Issue by idreamerhx** [PaddlePaddle/PaddleDetection#3361]
(pyvenv) λ 6194893dc6c0 /opt/PaddleDetection {release/2.1} python tools/export_model.py -c configs/ssd/ssd_mobilenet_v1_300_120e_voc.yml         --output_dir=./inference_model         -o weights=https://paddlemodels.bj.bcebos.com/object_detection/ssd_mobilenet_v1_voc.tar            TestReader.inputs_def.image_shape=[3,300,300]
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
/opt/PaddleDetection/pyvenv/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Traceback (most recent call last):
  File "tools/export_model.py", line 105, in <module>
    main()
  File "tools/export_model.py", line 101, in main
    run(FLAGS, cfg)
  File "tools/export_model.py", line 66, in run
    trainer.load_weights(cfg.weights)
  File "/opt/PaddleDetection/ppdet/engine/trainer.py", line 234, in load_weights
    load_pretrain_weight(self.model, weights)
  File "/opt/PaddleDetection/ppdet/utils/checkpoint.py", line 159, in load_pretrain_weight
    param_state_dict = paddle.load(weights_path)
  File "/opt/PaddleDetection/pyvenv/lib/python3.7/site-packages/paddle/framework/io.py", line 840, in load
    load_result = _legacy_load(path, **configs)
  File "/opt/PaddleDetection/pyvenv/lib/python3.7/site-packages/paddle/framework/io.py", line 859, in _legacy_load
    model_path, config = _build_load_path_and_config(path, config)
  File "/opt/PaddleDetection/pyvenv/lib/python3.7/site-packages/paddle/framework/io.py", line 161, in _build_load_path_and_config
    raise ValueError(error_msg % path)
ValueError: The ``path`` (/root/.cache/paddle/weights/ssd_mobilenet_v1_voc.pdparams) to load model not exists.

(pyvenv) λ 6194893dc6c0 /opt/PaddleDetection {release/2.1} ls /root/.cache/paddle/weights/ssd_mobilenet_v1_voc/__model__
ls: cannot access '/root/.cache/paddle/weights/ssd_mobilenet_v1_voc/__model__': No such file or directory

**Comment by nemonameless** [comment]
您好，建议使用release/2.1或develop分支的最新代码，默认使用动态图。您好像使用是权重是旧版的静态图的，动态图权重为`https://paddledet.bj.bcebos.com/models/ssd_mobilenet_v1_300_120e_voc.pdparams`

**Comment by idreamerhx** [comment]
收到，已验证转换可用。谢谢。还请更新文档。
