### ISSUE TITLE
fairmot验证报错

### ISSUE THREAD

**Issue by d2623587501** [PaddlePaddle/PaddleDetection#3385]
执行下述语句，训练正常运行，验证时报错
# 训练
CUDA_VISIBLE_DEVICES=0
!python -u tools/train.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml --use_vdl True --eval

`Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 111, in run
    trainer.train(FLAGS.eval)
  File "/home/aistudio/work/PaddleDetection/ppdet/engine/trainer.py", line 352, in train
    self._eval_with_loader(self._eval_loader)
  File "/home/aistudio/work/PaddleDetection/ppdet/engine/trainer.py", line 368, in _eval_with_loader
    outs = self.model(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 29, in forward
    out = self.get_pred()
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/architectures/fairmot.py", line 102, in get_pred
    output = self._forward()
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/architectures/fairmot.py", line 74, in _forward
    det_outs = self.detector(self.inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 29, in forward
    out = self.get_pred()
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/architectures/centernet.py", line 76, in get_pred
    head_out = self._forward()
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/architectures/centernet.py", line 68, in _forward
    body_feats = self.backbone(self.inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/backbones/dla.py", line 237, in forward
    im = inputs['image']
KeyError: 'image'`

**Comment by nemonameless** [comment]
fairmot暂时不支持边训边eval，近期会考虑增加该功能。不过跟踪模型也不建议边训边eval，前期精度低耗时多。可以单独跑eval_mot.py去评估验证

**Comment by d2623587501** [comment]
好的 谢谢
