### ISSUE TITLE
重新聚类anchor的时候，会报错TypeError: __init__() got an unexpected keyword argument 'with_background'

### ISSUE THREAD

**Issue by xupengao** [PaddlePaddle/PaddleDetection#3386]
用的是release/2.1的代码，在3090服务器上，在static内使用静态图进行anchor聚类，命令python tools/anchor_cluster.py -c configs/ppyolo/ppyolo.yml  -n 9 -s 640 -m v5 -i 1000
无法正常运行，出现
Traceback (most recent call last):
  File "tools/anchor_cluster.py", line 376, in <module>
    main()
  File "tools/anchor_cluster.py", line 339, in main
    cfg = load_config(FLAGS.config)
  File "/data/xupengao/anaconda3/envs/py3.7/lib/python3.7/site-packages/ppdet/core/workspace.py", line 115, in load_config
    cfg = _load_config_with_base(file_path)
  File "/data/xupengao/anaconda3/envs/py3.7/lib/python3.7/site-packages/ppdet/core/workspace.py", line 80, in _load_config_with_base
    file_cfg = yaml.load(f, Loader=yaml.Loader)
  File "/data/xupengao/anaconda3/envs/py3.7/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/data/xupengao/anaconda3/envs/py3.7/lib/python3.7/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/data/xupengao/anaconda3/envs/py3.7/lib/python3.7/site-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/data/xupengao/anaconda3/envs/py3.7/lib/python3.7/site-packages/yaml/constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/data/xupengao/anaconda3/envs/py3.7/lib/python3.7/site-packages/yaml/constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/data/xupengao/anaconda3/envs/py3.7/lib/python3.7/site-packages/yaml/constructor.py", line 143, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/data/xupengao/anaconda3/envs/py3.7/lib/python3.7/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/data/xupengao/anaconda3/envs/py3.7/lib/python3.7/site-packages/ppdet/core/config/yaml_helpers.py", line 45, in python_constructor
    raise ex
  File "/data/xupengao/anaconda3/envs/py3.7/lib/python3.7/site-packages/ppdet/core/config/yaml_helpers.py", line 41, in python_constructor
    return cls(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'with_background'

**Comment by wangxinxin08** [comment]
问题报错原因应该是TrainReader中的dataset的with_background的缩进不对导致的

**Comment by xupengao** [comment]
我检查了，缩进是没有问题的，我在别的服务器上测试，cuda10,release/2.1版本的就没有问题，但是在3090服务器上，静态图cuda11.2，就出问题
| |
徐鹏翱
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年6月16日 ***@***.***> 写道：

问题报错原因应该是TrainReader中的dataset的with_background的缩进不对导致的

**Comment by wangxinxin08** [comment]
你可以贴下出错的机器上的ppyolo.yml

**Comment by xupengao** [comment]
完整的我已经放到附件中，我把部分贴在下面，我觉得Trainreader没出错
| |
徐鹏翱
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年6月16日 ***@***.***> 写道：

你可以贴下出错的机器上的ppyolo.yml

**Comment by wangxinxin08** [comment]
没有看到这个贴的附件，如果TrainReader没有问题的话，那可能的原因是你用动态图下的anchor_clustor.py加载了静态图下的配置文件，否则不会报你截图显示的错误的
