### ISSUE TITLE
用mask_rcnn模型训练自己的数据集时报错，之后用官方的coco数据集也报一样的错误

### ISSUE THREAD

**Issue by wexin-c** [PaddlePaddle/PaddleDetection#3395]
(paddle) D:\PaddleDetection-release-2.1>python tools/train.py -c configs/dcn/mask_rcnn_dcn_r50_vd_fpn_2x_6000.yml -o use_gpu=true --eval --use_vdl=true --vdl_log_dir=vdl_dir/6000/
loading annotations into memory...
Done (t=0.31s)
creating index...
index created!
W0616 09:12:18.372654 10096 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.2, Runtime API Version: 10.2
W0616 09:12:18.378158 10096 device_context.cc:422] device: 0, cuDNN Version: 7.6.
[06/16 09:12:38] ppdet.utils.checkpoint INFO: Finish loading model weights: C:\Users\Bazenr/.cache/paddle/weights\ResNet50_vd_pretrained.pdparams
loading annotations into memory...
Done (t=0.08s)
creating index...
index created!
Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 111, in run
    trainer.train(FLAGS.eval)
  File "C:\Users\Bazenr\AppData\Roaming\Python\Python37\site-packages\paddledet-2.1.0-py3.7.egg\ppdet\engine\trainer.py", line 307, in train
    outputs = model(data)
  File "d:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "C:\Users\Bazenr\AppData\Roaming\Python\Python37\site-packages\paddledet-2.1.0-py3.7.egg\ppdet\modeling\architectures\meta_arch.py", line 27, in forward
    out = self.get_loss()
  File "C:\Users\Bazenr\AppData\Roaming\Python\Python37\site-packages\paddledet-2.1.0-py3.7.egg\ppdet\modeling\architectures\mask_rcnn.py", line 123, in get_loss
    bbox_loss, mask_loss, rpn_loss = self._forward()
  File "C:\Users\Bazenr\AppData\Roaming\Python\Python37\site-packages\paddledet-2.1.0-py3.7.egg\ppdet\modeling\architectures\mask_rcnn.py", line 100, in _forward
    bbox_targets, bbox_feat)
  File "d:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "C:\Users\Bazenr\AppData\Roaming\Python\Python37\site-packages\paddledet-2.1.0-py3.7.egg\ppdet\modeling\heads\mask_head.py", line 249, in forward
    targets, bbox_feat)
  File "C:\Users\Bazenr\AppData\Roaming\Python\Python37\site-packages\paddledet-2.1.0-py3.7.egg\ppdet\modeling\heads\mask_head.py", line 187, in forward_train
    rois, tgt_labels, tgt_gt_inds, inputs)
  File "C:\Users\Bazenr\AppData\Roaming\Python\Python37\site-packages\paddledet-2.1.0-py3.7.egg\ppdet\modeling\proposal_generator\target_layer.py", line 254, in __call__
    gt_segms = inputs['gt_poly']
KeyError: 'gt_poly'

**Comment by wangxinxin08** [comment]
mask_rcnn需要使用datasets/coco_instance.yml这一个配置文件，你可以贴一下你的配置文件

**Comment by wexin-c** [comment]
> mask_rcnn需要使用datasets/coco_instance.yml这一个配置文件，你可以贴一下你的配置文件

###########6000_detection.yml
metric: COCO
num_classes: 13

TrainDataset:
  !COCODataSet
    image_dir: train
    anno_path: annotations/instance_train.json
    dataset_dir: dataset/liuqian
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val
    anno_path: annotations/instance_val.json
    dataset_dir: dataset/liuqian

TestDataset:
  !ImageFolder
    anno_path: annotations/instance_val.json

**Comment by wangxinxin08** [comment]
你使用的是coco_detection的配置文件，不是coco_instance的配置文件，参考https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/configs/datasets/coco_instance.yml#L9，里面的data_fields是不一样的

**Comment by wexin-c** [comment]
> 你使用的是coco_detection的配置文件，不是coco_instance的配置文件，参考https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/configs/datasets/coco_instance.yml#L9

好的  谢谢 我试试
