### ISSUE TITLE
训练过程中出现_shutdown错误

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/PaddleDetection#3396]
是随机出现的。前面已经训练100多个epoch了，Ubuntu才出现，windows没有出现过。
```
OSError: [Errno 24] Too many open files
Exception ignored in: <function _DataLoaderIterMultiProcess.__del__ at 0x7f48b0486320>
Traceback (most recent call last):
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 566, in __del__
    self._try_shutdown_all()
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 371, in _try_shutdown_all
    if not self._shutdown:
AttributeError: '_DataLoaderIterMultiProcess' object has no attribute '_shutdown'
```

**Comment by wangxinxin08** [comment]
可以贴一下Paddle版本，PaddleDetection版本，我们定位下问题

**Comment by yeyupiaoling** [comment]
@wangxinxin08 
 - PaddlePaddle 2.1.0
 - PaddleDetection 2.1.0

**Comment by yeyupiaoling** [comment]
@wangxinxin08 我用的是则个模型`ppyolo_tiny_650e_voc.yml`，这个`ppyolo_r50vd_dcn_1x_voc.yml`模型也出现，其他的没试过。
