### ISSUE TITLE
paddledetection  Mask-Rcnn 单卡GPU训练数据eval和推理报错！

### ISSUE THREAD

**Issue by ResonLee** [PaddlePaddle/PaddleDetection#3397]
GPU：RTX 2060
paddlepaddle: 2.1.0
paddledetection: paddledetection-develop
错误承接上次使用paddlepaddle2.0.0时的报错，[https://github.com/PaddlePaddle/PaddleDetection/issues/3311#issuecomment-861615195](url),更改版本后依然报错，尝试train和eval分开，训练是正常的没问题，eval出现错误，尝试使用infe推理，同样卡在这一错误的地方，查了下相关的资料，还是没搞清楚该怎么消除，请问官方怎么处理，能否给点建议，这边也在尝试解决！
eval报错：
`Traceback (most recent call last):
  File "tools/eval.py", line 134, in <module>
    main()
  File "tools/eval.py", line 130, in main
    run(FLAGS, cfg)
  File "tools/eval.py", line 105, in run
    trainer.evaluate()
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\engine\trainer.py", line 396, in evaluate
    self._eval_with_loader(self.loader)
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\engine\trainer.py", line 374, in _eval_with_loader
    outs = self.model(data)
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\modeling\architectures\meta_arch.py", line 29, in forward
    out = self.get_pred()
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\modeling\architectures\mask_rcnn.py", line 133, in get_pred
    bbox_pred, bbox_num, mask_pred = self._forward()
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\modeling\architectures\mask_rcnn.py", line 103, in _forward
    rois, rois_num, _ = self.rpn_head(body_feats, self.inputs)
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\modeling\proposal_generator\rpn_head.py", line 136, in forward
    rois, rois_num = self._gen_proposal(scores, deltas, anchors, inputs)
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\modeling\proposal_generator\rpn_head.py", line 168, in _gen_proposal
    rpn_rois, rpn_rois_prob, rpn_rois_num, post_nms_top_n = prop_gen(
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\modeling\proposal_generator\proposal_generator.py", line 69, in __call__
    rpn_rois, rpn_rois_prob, rpn_rois_num = ops.generate_proposals(
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\modeling\ops.py", line 1516, in generate_proposals
    rpn_rois, rpn_roi_probs, rpn_rois_num = core.ops.generate_proposals_v2(
OSError: (External)  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at C:\home\workspace\Paddle_release\paddle\fluid\platform\gpu_info.cc:382)
  [operator < generate_proposals_v2 > error]`
infer,报错：
`[06/16 10:56:43] ppdet.engine INFO: Detection bbox results save in E:/data_hulan/test_mask\4498.jpg
Traceback (most recent call last):
  File "tools/infer.py", line 158, in <module>
    main()
  File "tools/infer.py", line 154, in main
    run(FLAGS, cfg)
  File "tools/infer.py", line 128, in run
    trainer.predict(
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\engine\trainer.py", line 418, in predict
    outs = self.model(data)
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\modeling\architectures\meta_arch.py", line 29, in forward
    out = self.get_pred()
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\modeling\architectures\mask_rcnn.py", line 133, in get_pred
    bbox_pred, bbox_num, mask_pred = self._forward()
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\modeling\architectures\mask_rcnn.py", line 103, in _forward
    rois, rois_num, _ = self.rpn_head(body_feats, self.inputs)
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\modeling\proposal_generator\rpn_head.py", line 136, in forward
    rois, rois_num = self._gen_proposal(scores, deltas, anchors, inputs)
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\modeling\proposal_generator\rpn_head.py", line 168, in _gen_proposal
    rpn_rois, rpn_rois_prob, rpn_rois_num, post_nms_top_n = prop_gen(
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\modeling\proposal_generator\proposal_generator.py", line 69, in __call__
    rpn_rois, rpn_rois_prob, rpn_rois_num = ops.generate_proposals(
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\modeling\ops.py", line 1516, in generate_proposals
    rpn_rois, rpn_roi_probs, rpn_rois_num = core.ops.generate_proposals_v2(
OSError: (External)  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at C:\home\workspace\Paddle_release\paddle\fluid\platform\gpu_info.cc:382)
  [operator < generate_proposals_v2 > error]`

**Comment by ResonLee** [comment]
cuda :10.1
cudnn:7.6.5

**Comment by lyuwenyu** [comment]
- 使用paddle的 develop版本
