### ISSUE TITLE
执行 python ppdet/modeling/tests/test_architectures.py测试报错

### ISSUE THREAD

**Issue by Suyn** [PaddlePaddle/PaddleDetection#340]
环境：Ubuntu18.04   python3.6  paddlepaddle1.7
环境安装好后执行 python ppdet/modeling/tests/test_architectures.py报错，以下是报错内容：

```
EE....EE....
======================================================================
ERROR: test_test (__main__.TestCascadeRCNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/tests/decorator_helper.py", line 29, in __fn__
    fn(*args, **kwargs)
  File "ppdet/modeling/tests/test_architectures.py", line 50, in test_test
    test_fetches = model.eval(feed_vars)
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/architectures/cascade_rcnn.py", line 286, in eval
    return self.build(feed_vars, 'test')
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/architectures/cascade_rcnn.py", line 105, in build
    body_feats, spatial_scale = self.fpn.get_output(body_feats)
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/backbones/fpn.py", line 144, in get_output
    top_output)
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/backbones/fpn.py", line 93, in _add_topdown_lateral
    return lateral + topdown
  File "/home/gta123/.virtualenvs/pd/lib/python3.6/site-packages/paddle/fluid/layers/math_op_patch.py", line 243, in __impl__
    attrs={'axis': axis})
  File "/home/gta123/.virtualenvs/pd/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/gta123/.virtualenvs/pd/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1880, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::operators::GetBroadcastDimsArrays(paddle::framework::DDim const&, paddle::framework::DDim const&, int*, int*, int*, int, int)
3   paddle::operators::ElementwiseOp::InferShape(paddle::framework::InferShapeContext*) const
4   paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/gta123/.virtualenvs/pd/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/gta123/.virtualenvs/pd/lib/python3.6/site-packages/paddle/fluid/layers/math_op_patch.py", line 243, in __impl__
    attrs={'axis': axis})
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/backbones/fpn.py", line 93, in _add_topdown_lateral
    return lateral + topdown
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/backbones/fpn.py", line 144, in get_output
    top_output)
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/architectures/cascade_rcnn.py", line 105, in build
    body_feats, spatial_scale = self.fpn.get_output(body_feats)
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/architectures/cascade_rcnn.py", line 286, in eval
    return self.build(feed_vars, 'test')
  File "ppdet/modeling/tests/test_architectures.py", line 50, in test_test
    test_fetches = model.eval(feed_vars)
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/tests/decorator_helper.py", line 29, in __fn__
    fn(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/usr/lib/python3.6/unittest/case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.6/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.6/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.6/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.6/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.6/unittest/runner.py", line 176, in run
    test(result)
  File "/usr/lib/python3.6/unittest/main.py", line 256, in runTests
    self.result = testRunner.run(self.test)
  File "/usr/lib/python3.6/unittest/main.py", line 95, in __init__
    self.runTests()
  File "ppdet/modeling/tests/test_architectures.py", line 79, in <module>
    unittest.main()

----------------------
Error Message Summary:
----------------------
Error: ShapeError: broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [-1, 256, 100, 167] and the shape of Y = [-1, 256, 100, 168]. Received [167] in X is not equal to [168] in Y at (/paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:145)
  [operator < elementwise_add > error]

======================================================================
ERROR: test_train (__main__.TestCascadeRCNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/tests/decorator_helper.py", line 29, in __fn__
    fn(*args, **kwargs)
  File "ppdet/modeling/tests/test_architectures.py", line 43, in test_train
    train_fetches = model.train(feed_vars)
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/architectures/cascade_rcnn.py", line 281, in train
    return self.build(feed_vars, 'train')
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/architectures/cascade_rcnn.py", line 105, in build
    body_feats, spatial_scale = self.fpn.get_output(body_feats)
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/backbones/fpn.py", line 144, in get_output
    top_output)
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/backbones/fpn.py", line 93, in _add_topdown_lateral
    return lateral + topdown
  File "/home/gta123/.virtualenvs/pd/lib/python3.6/site-packages/paddle/fluid/layers/math_op_patch.py", line 243, in __impl__
    attrs={'axis': axis})
  File "/home/gta123/.virtualenvs/pd/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/gta123/.virtualenvs/pd/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1880, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::operators::GetBroadcastDimsArrays(paddle::framework::DDim const&, paddle::framework::DDim const&, int*, int*, int*, int, int)
3   paddle::operators::ElementwiseOp::InferShape(paddle::framework::InferShapeContext*) const
4   paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/gta123/.virtualenvs/pd/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/gta123/.virtualenvs/pd/lib/python3.6/site-packages/paddle/fluid/layers/math_op_patch.py", line 243, in __impl__
    attrs={'axis': axis})
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/backbones/fpn.py", line 93, in _add_topdown_lateral
    return lateral + topdown
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/backbones/fpn.py", line 144, in get_output
    top_output)
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/architectures/cascade_rcnn.py", line 105, in build
    body_feats, spatial_scale = self.fpn.get_output(body_feats)
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/architectures/cascade_rcnn.py", line 281, in train
    return self.build(feed_vars, 'train')
  File "ppdet/modeling/tests/test_architectures.py", line 43, in test_train
    train_fetches = model.train(feed_vars)
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/tests/decorator_helper.py", line 29, in __fn__
    fn(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/usr/lib/python3.6/unittest/case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.6/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.6/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.6/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.6/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.6/unittest/runner.py", line 176, in run
    test(result)
  File "/usr/lib/python3.6/unittest/main.py", line 256, in runTests
    self.result = testRunner.run(self.test)
  File "/usr/lib/python3.6/unittest/main.py", line 95, in __init__
    self.runTests()
  File "ppdet/modeling/tests/test_architectures.py", line 79, in <module>
    unittest.main()

----------------------
Error Message Summary:
----------------------
Error: ShapeError: broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [-1, 256, 100, 167] and the shape of Y = [-1, 256, 100, 168]. Received [167] in X is not equal to [168] in Y at (/paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:145)
  [operator < elementwise_add > error]

======================================================================
ERROR: test_test (__main__.TestRetinaNet)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/tests/decorator_helper.py", line 29, in __fn__
    fn(*args, **kwargs)
  File "ppdet/modeling/tests/test_architectures.py", line 50, in test_test
    test_fetches = model.eval(feed_vars)
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/architectures/retinanet.py", line 89, in eval
    return self.build(feed_vars, 'test')
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/architectures/retinanet.py", line 71, in build
    body_feats, spatial_scale = self.fpn.get_output(body_feats)
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/backbones/fpn.py", line 144, in get_output
    top_output)
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/backbones/fpn.py", line 93, in _add_topdown_lateral
    return lateral + topdown
  File "/home/gta123/.virtualenvs/pd/lib/python3.6/site-packages/paddle/fluid/layers/math_op_patch.py", line 243, in __impl__
    attrs={'axis': axis})
  File "/home/gta123/.virtualenvs/pd/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/gta123/.virtualenvs/pd/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1880, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::operators::GetBroadcastDimsArrays(paddle::framework::DDim const&, paddle::framework::DDim const&, int*, int*, int*, int, int)
3   paddle::operators::ElementwiseOp::InferShape(paddle::framework::InferShapeContext*) const
4   paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/gta123/.virtualenvs/pd/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/gta123/.virtualenvs/pd/lib/python3.6/site-packages/paddle/fluid/layers/math_op_patch.py", line 243, in __impl__
    attrs={'axis': axis})
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/backbones/fpn.py", line 93, in _add_topdown_lateral
    return lateral + topdown
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/backbones/fpn.py", line 144, in get_output
    top_output)
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/architectures/retinanet.py", line 71, in build
    body_feats, spatial_scale = self.fpn.get_output(body_feats)
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/architectures/retinanet.py", line 89, in eval
    return self.build(feed_vars, 'test')
  File "ppdet/modeling/tests/test_architectures.py", line 50, in test_test
    test_fetches = model.eval(feed_vars)
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/tests/decorator_helper.py", line 29, in __fn__
    fn(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/usr/lib/python3.6/unittest/case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.6/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.6/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.6/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.6/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.6/unittest/runner.py", line 176, in run
    test(result)
  File "/usr/lib/python3.6/unittest/main.py", line 256, in runTests
    self.result = testRunner.run(self.test)
  File "/usr/lib/python3.6/unittest/main.py", line 95, in __init__
    self.runTests()
  File "ppdet/modeling/tests/test_architectures.py", line 79, in <module>
    unittest.main()

----------------------
Error Message Summary:
----------------------
Error: ShapeError: broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [-1, 256, 100, 167] and the shape of Y = [-1, 256, 100, 168]. Received [167] in X is not equal to [168] in Y at (/paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:145)
  [operator < elementwise_add > error]

======================================================================
ERROR: test_train (__main__.TestRetinaNet)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/tests/decorator_helper.py", line 29, in __fn__
    fn(*args, **kwargs)
  File "ppdet/modeling/tests/test_architectures.py", line 43, in test_train
    train_fetches = model.train(feed_vars)
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/architectures/retinanet.py", line 86, in train
    return self.build(feed_vars, 'train')
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/architectures/retinanet.py", line 71, in build
    body_feats, spatial_scale = self.fpn.get_output(body_feats)
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/backbones/fpn.py", line 144, in get_output
    top_output)
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/backbones/fpn.py", line 93, in _add_topdown_lateral
    return lateral + topdown
  File "/home/gta123/.virtualenvs/pd/lib/python3.6/site-packages/paddle/fluid/layers/math_op_patch.py", line 243, in __impl__
    attrs={'axis': axis})
  File "/home/gta123/.virtualenvs/pd/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/gta123/.virtualenvs/pd/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1880, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::operators::GetBroadcastDimsArrays(paddle::framework::DDim const&, paddle::framework::DDim const&, int*, int*, int*, int, int)
3   paddle::operators::ElementwiseOp::InferShape(paddle::framework::InferShapeContext*) const
4   paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/gta123/.virtualenvs/pd/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/gta123/.virtualenvs/pd/lib/python3.6/site-packages/paddle/fluid/layers/math_op_patch.py", line 243, in __impl__
    attrs={'axis': axis})
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/backbones/fpn.py", line 93, in _add_topdown_lateral
    return lateral + topdown
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/backbones/fpn.py", line 144, in get_output
    top_output)
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/architectures/retinanet.py", line 71, in build
    body_feats, spatial_scale = self.fpn.get_output(body_feats)
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/architectures/retinanet.py", line 86, in train
    return self.build(feed_vars, 'train')
  File "ppdet/modeling/tests/test_architectures.py", line 43, in test_train
    train_fetches = model.train(feed_vars)
  File "/home/gta123/liquid/paddle/models/PaddleCV/PaddleDetection/ppdet/modeling/tests/decorator_helper.py", line 29, in __fn__
    fn(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/usr/lib/python3.6/unittest/case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.6/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.6/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.6/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.6/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.6/unittest/runner.py", line 176, in run
    test(result)
  File "/usr/lib/python3.6/unittest/main.py", line 256, in runTests
    self.result = testRunner.run(self.test)
  File "/usr/lib/python3.6/unittest/main.py", line 95, in __init__
    self.runTests()
  File "ppdet/modeling/tests/test_architectures.py", line 79, in <module>
    unittest.main()

----------------------
Error Message Summary:
----------------------
Error: ShapeError: broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [-1, 256, 100, 167] and the shape of Y = [-1, 256, 100, 168]. Received [167] in X is not equal to [168] in Y at (/paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:145)
  [operator < elementwise_add > error]

----------------------------------------------------------------------
Ran 12 tests in 3.231s
```

怎么解决？这个错误的原因是什么引起的？

**Comment by qingqing01** [comment]
@Suyn  看您代码目录的话，使用的是models下面的代码。 models develop分支下的代码，已经很老了，会删除。需要使用PaddleDetection repo的代码:

git clone https://github.com/PaddlePaddle/PaddleDetection.git

**Comment by qingqing01** [comment]
@Suyn 请问是否还有问题？

**Comment by TianZhenGG** [comment]
ImportError: cannot import name 'symbol_database' from 'google.protobuf' (/home/tianzhen/.local/lib/python3.7/site-packages/google/protobuf/__init__.py)
这又是为啥啊

**Comment by qingqing01** [comment]
由于时间较久，暂且关闭issue。有新的问题，再开issue。
