### ISSUE TITLE
ppyolov2  voc  tools/eval.py    KeyError: 'difficult'

### ISSUE THREAD

**Issue by lhx123456-lang** [PaddlePaddle/PaddleDetection#3409]
(env37) root@c-MS-7C39:/home/c/DL/PPYOLOV2# python tools/eval.py -c configs/ppyolo/ppyolov2_r50vd_dcn_voc.yml -o weights=/media/c/DLImage/PPYOLOV2output/ppyolov2_r50vd_dcn_voc/98.pdparams 
/root/miniconda3/envs/env37/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
W0617 09:49:33.697757 18145 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.3, Runtime API Version: 10.2
W0617 09:49:33.699952 18145 device_context.cc:422] device: 0, cuDNN Version: 7.6.
[06/17 09:49:36] ppdet.utils.checkpoint INFO: Finish loading model weights: /media/c/DLImage/PPYOLOV2output/ppyolov2_r50vd_dcn_voc/98.pdparams
Traceback (most recent call last):
  File "tools/eval.py", line 134, in <module>
    main()
  File "tools/eval.py", line 130, in main
    run(FLAGS, cfg)
  File "tools/eval.py", line 105, in run
    trainer.evaluate()
  File "/root/miniconda3/envs/env37/lib/python3.7/site-packages/ppdet/engine/trainer.py", line 388, in evaluate
    self._eval_with_loader(self.loader)
  File "/root/miniconda3/envs/env37/lib/python3.7/site-packages/ppdet/engine/trainer.py", line 370, in _eval_with_loader
    metric.update(data, outs)
  File "/root/miniconda3/envs/env37/lib/python3.7/site-packages/ppdet/metrics/metrics.py", line 247, in update
    difficults = inputs['difficult'] if not self.evaluate_difficult \
KeyError: 'difficult'

**Comment by lyuwenyu** [comment]
检查一下dataset的data_fields配置对了没
参考 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/configs/datasets/voc.yml#L17

**Comment by lhx123456-lang** [comment]
确实是这个原因,已经解决,谢谢
