### ISSUE TITLE
使用.yml文件时关于pyYAML的 ‘!****’ 语句出现报错

### ISSUE THREAD

**Issue by Eric-Hjx** [PaddlePaddle/PaddleDetection#345]
是在aistudio的环境里运行 python ppdet / modeling / tests / test_architectures.py 命令

/home/aistudio/PaddleDetection
EEEEEEEEEEEE
======================================================================
ERROR: test_test (__main__.TestCascadeRCNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 42, in setUp
    self.cfg = load_config(self.cfg_file)
  File "/home/aistudio/PaddleDetection/ppdet/core/workspace.py", line 86, in load_config
    cfg = merge_config(yaml.load(f, Loader=yaml.Loader), cfg)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 52, in construct_document
    for dummy in generator:
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 399, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 122, in construct_sequence
    for child in node.value]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 122, in <listcomp>
    for child in node.value]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 420, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!PiecewiseDecay'
  in "configs/cascade_rcnn_r50_fpn_1x.yml", line 89, column 5

======================================================================
ERROR: test_train (__main__.TestCascadeRCNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 42, in setUp
    self.cfg = load_config(self.cfg_file)
  File "/home/aistudio/PaddleDetection/ppdet/core/workspace.py", line 86, in load_config
    cfg = merge_config(yaml.load(f, Loader=yaml.Loader), cfg)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 52, in construct_document
    for dummy in generator:
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 399, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 122, in construct_sequence
    for child in node.value]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 122, in <listcomp>
    for child in node.value]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 420, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!PiecewiseDecay'
  in "configs/cascade_rcnn_r50_fpn_1x.yml", line 89, column 5

======================================================================
ERROR: test_test (__main__.TestFasterRCNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 42, in setUp
    self.cfg = load_config(self.cfg_file)
  File "/home/aistudio/PaddleDetection/ppdet/core/workspace.py", line 86, in load_config
    cfg = merge_config(yaml.load(f, Loader=yaml.Loader), cfg)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 52, in construct_document
    for dummy in generator:
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 399, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 122, in construct_sequence
    for child in node.value]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 122, in <listcomp>
    for child in node.value]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 420, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!PiecewiseDecay'
  in "configs/faster_rcnn_r50_1x.yml", line 76, column 5

======================================================================
ERROR: test_train (__main__.TestFasterRCNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 42, in setUp
    self.cfg = load_config(self.cfg_file)
  File "/home/aistudio/PaddleDetection/ppdet/core/workspace.py", line 86, in load_config
    cfg = merge_config(yaml.load(f, Loader=yaml.Loader), cfg)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 52, in construct_document
    for dummy in generator:
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 399, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 122, in construct_sequence
    for child in node.value]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 122, in <listcomp>
    for child in node.value]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 420, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!PiecewiseDecay'
  in "configs/faster_rcnn_r50_1x.yml", line 76, column 5

======================================================================
ERROR: test_test (__main__.TestMaskRCNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 42, in setUp
    self.cfg = load_config(self.cfg_file)
  File "/home/aistudio/PaddleDetection/ppdet/core/workspace.py", line 86, in load_config
    cfg = merge_config(yaml.load(f, Loader=yaml.Loader), cfg)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 52, in construct_document
    for dummy in generator:
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 399, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 122, in construct_sequence
    for child in node.value]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 122, in <listcomp>
    for child in node.value]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 420, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!PiecewiseDecay'
  in "configs/mask_rcnn_r50_1x.yml", line 87, column 5

======================================================================
ERROR: test_train (__main__.TestMaskRCNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 42, in setUp
    self.cfg = load_config(self.cfg_file)
  File "/home/aistudio/PaddleDetection/ppdet/core/workspace.py", line 86, in load_config
    cfg = merge_config(yaml.load(f, Loader=yaml.Loader), cfg)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 52, in construct_document
    for dummy in generator:
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 399, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 122, in construct_sequence
    for child in node.value]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 122, in <listcomp>
    for child in node.value]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 420, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!PiecewiseDecay'
  in "configs/mask_rcnn_r50_1x.yml", line 87, column 5

======================================================================
ERROR: test_test (__main__.TestRetinaNet)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 42, in setUp
    self.cfg = load_config(self.cfg_file)
  File "/home/aistudio/PaddleDetection/ppdet/core/workspace.py", line 86, in load_config
    cfg = merge_config(yaml.load(f, Loader=yaml.Loader), cfg)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 52, in construct_document
    for dummy in generator:
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 399, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 122, in construct_sequence
    for child in node.value]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 122, in <listcomp>
    for child in node.value]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 420, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!PiecewiseDecay'
  in "configs/retinanet_r50_fpn_1x.yml", line 58, column 5

======================================================================
ERROR: test_train (__main__.TestRetinaNet)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 42, in setUp
    self.cfg = load_config(self.cfg_file)
  File "/home/aistudio/PaddleDetection/ppdet/core/workspace.py", line 86, in load_config
    cfg = merge_config(yaml.load(f, Loader=yaml.Loader), cfg)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 52, in construct_document
    for dummy in generator:
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 399, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 122, in construct_sequence
    for child in node.value]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 122, in <listcomp>
    for child in node.value]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 420, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!PiecewiseDecay'
  in "configs/retinanet_r50_fpn_1x.yml", line 58, column 5

======================================================================
ERROR: test_test (__main__.TestSSD)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 42, in setUp
    self.cfg = load_config(self.cfg_file)
  File "/home/aistudio/PaddleDetection/ppdet/core/workspace.py", line 86, in load_config
    cfg = merge_config(yaml.load(f, Loader=yaml.Loader), cfg)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 52, in construct_document
    for dummy in generator:
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 404, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 210, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 135, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 420, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!VOCDataSet'
  in "configs/ssd/ssd_mobilenet_v1_voc.yml", line 61, column 5

======================================================================
ERROR: test_train (__main__.TestSSD)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 42, in setUp
    self.cfg = load_config(self.cfg_file)
  File "/home/aistudio/PaddleDetection/ppdet/core/workspace.py", line 86, in load_config
    cfg = merge_config(yaml.load(f, Loader=yaml.Loader), cfg)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 52, in construct_document
    for dummy in generator:
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 404, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 210, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 135, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 420, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!VOCDataSet'
  in "configs/ssd/ssd_mobilenet_v1_voc.yml", line 61, column 5

======================================================================
ERROR: test_test (__main__.TestYolov3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 42, in setUp
    self.cfg = load_config(self.cfg_file)
  File "/home/aistudio/PaddleDetection/ppdet/core/workspace.py", line 86, in load_config
    cfg = merge_config(yaml.load(f, Loader=yaml.Loader), cfg)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 52, in construct_document
    for dummy in generator:
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 399, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 122, in construct_sequence
    for child in node.value]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 122, in <listcomp>
    for child in node.value]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 420, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!PiecewiseDecay'
  in "configs/yolov3_darknet.yml", line 45, column 5

======================================================================
ERROR: test_train (__main__.TestYolov3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 42, in setUp
    self.cfg = load_config(self.cfg_file)
  File "/home/aistudio/PaddleDetection/ppdet/core/workspace.py", line 86, in load_config
    cfg = merge_config(yaml.load(f, Loader=yaml.Loader), cfg)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 52, in construct_document
    for dummy in generator:
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 399, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 122, in construct_sequence
    for child in node.value]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 122, in <listcomp>
    for child in node.value]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 420, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!PiecewiseDecay'
  in "configs/yolov3_darknet.yml", line 45, column 5

----------------------------------------------------------------------
Ran 12 tests in 0.127s

FAILED (errors=12)

**Comment by Eric-Hjx** [comment]
是在aistudio的环境里运行 !python ppdet/modeling/tests/test_architectures.py 命令

**Comment by willthefrog** [comment]
应该是路径问题，请尝试在ppdet根目录下运行
```sh
PYTHONPATH=. python ppdet/modeling/tests/test_architectures.py
```

**Comment by Eric-Hjx** [comment]
> 应该是路径问题，请尝试在ppdet根目录下运行
> 
> ```shell
> PYTHONPATH =。python ppdet / modeling / tests / test_architectures.py
> ```

还是一样的错误，没有变化
![1](https://user-images.githubusercontent.com/48123846/76925206-9ac33180-6913-11ea-9a27-d5069524a3e0.png)

**Comment by willthefrog** [comment]
本地无法复现，可能是环境问题，除了test失败以外是否能正常工作？模型可以正常运行吗？

**Comment by Eric-Hjx** [comment]
> 本地无法复现，可能是环境问题，除了测试失败以外是否能正常工作？模型可以正常运行吗？

都无法进行
这是源代码的报错信息
![image](https://user-images.githubusercontent.com/48123846/76930908-876b9280-6922-11ea-9fe1-a24c9232c7ee.png)
![image](https://user-images.githubusercontent.com/48123846/76931069-dfa29480-6922-11ea-97cc-8498bbbbc058.png)

这个是更改了两行代码后，出现了learnning_rate未注册的报错
![image](https://user-images.githubusercontent.com/48123846/76931024-cac60100-6922-11ea-96d7-56f926a8abe4.png)
 
![image](https://user-images.githubusercontent.com/48123846/76931083-e6310c00-6922-11ea-8f10-1612713269ec.png)

**Comment by qingqing01** [comment]
@Eric-Hjx  先看下你PaddleDetection路径在哪里，比如是  `=/home/aistudio/work/PaddleDetection`

然后设置:

``
%env PYTHONPATH=/home/aistudio/work/PaddleDetection:$PYTHONPATH
```

比如这个教程： https://aistudio.baidu.com/aistudio/projectdetail/187558 (这个教程的代码较早了)
