### ISSUE TITLE
voc数据集执行eval.py命令报错

### ISSUE THREAD

**Issue by claudehotline** [PaddlePaddle/PaddleDetection#3456]
paddle版本：2.1.0GPU版本
paddleDetection版本：release/2.1版本
```
(paddle) E:\PaddleDetection>python tools/eval.py -c configs/ppyolo/ppyolo_tiny_650e_coco.yml -o weights=output\ppyolo_ti
ny_650e_coco\307.pdparams
W0621 19:37:04.323076 21412 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.3, Runtime API Version: 10.2
W0621 19:37:04.328078 21412 device_context.cc:422] device: 0, cuDNN Version: 7.6.
[06/21 19:37:09] ppdet.utils.checkpoint INFO: Finish loading model weights: output\ppyolo_tiny_650e_coco\307.pdparams
WARNING:root:DataLoader reader thread raised an exception.
Traceback (most recent call last):
  File "tools/eval.py", line 134, in <module>
    main()
  File "tools/eval.py", line 130, in main
    run(FLAGS, cfg)
  File "tools/eval.py", line 105, in run
    trainer.evaluate()
  File "E:\PaddleDetection\ppdet\engine\trainer.py", line 390, in evaluate
    self._eval_with_loader(self.loader)
  File "E:\PaddleDetection\ppdet\engine\trainer.py", line 364, in _eval_with_loader
    for step_id, data in enumerate(loader):
  File "E:\PaddleDetection\ppdet\data\reader.py", line 211, in __next__
    return next(self.loader)
  File "C:\Users\claud\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 204, in __next__
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\claud\Anaconda3\envs\paddle\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\claud\Anaconda3\envs\paddle\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\claud\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 199, in _thread_loop
    six.reraise(*sys.exc_info())
  File "C:\Users\claud\Anaconda3\envs\paddle\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "C:\Users\claud\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 167, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices)
  File "C:\Users\claud\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dataloader\fetcher.py", line 66, in fetch
    data = self.collate_fn(data)
  File "E:\PaddleDetection\ppdet\data\reader.py", line 93, in __call__
    batch_data = default_collate_fn(data)
  File "C:\Users\claud\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dataloader\collate.py", line 70, in default_collate_fn
    for key in sample
  File "C:\Users\claud\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dataloader\collate.py", line 70, in <dictcomp>
    for key in sample
  File "C:\Users\claud\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dataloader\collate.py", line 58, in default_collate_fn
    batch = np.stack(batch, axis=0)
  File "<__array_function__ internals>", line 6, in stack
  File "C:\Users\claud\Anaconda3\envs\paddle\lib\site-packages\numpy\core\shape_base.py", line 427, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape

data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at C:\home\workspace\Paddle_release\paddle/fluid/operators/reader/blocking_queue.h:166)
```
---
#### ppyolo_tiny_reader.yml文件内容如下：
```
worker_num: 1
TrainReader:
  inputs_def:
    num_max_boxes: 100
  sample_transforms:
    - Decode: {}
    - Mixup: {alpha: 1.5, beta: 1.5}
    - RandomDistort: {}
    - RandomExpand: {fill_value: [123.675, 116.28, 103.53]}
    - RandomCrop: {}
    - RandomFlip: {}
  batch_transforms:
    - BatchRandomResize: {target_size: [192, 224, 256, 288, 320, 352, 384, 416, 448, 480, 512], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeBox: {}
    - PadBox: {num_max_boxes: 100}
    - BboxXYXY2XYWH: {}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
    - Gt2YoloTarget: {anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]], anchors: [[10, 15], [24, 36], [72, 42], [35, 87], [102, 96], [60, 170], [220, 125], [128, 222], [264, 266]], downsample_ratios: [32, 16, 8]}
  batch_size: 4
  shuffle: true
  drop_last: true
  mixup_epoch: 500
  use_shared_memory: true

EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [320, 320], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 4

TestReader:
  inputs_def:
    image_shape: [3, 320, 320]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [320, 320], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 1
```

**Comment by yghstill** [comment]
@claudehotline 数据集配置文件改过吗？是不是改成voc数据集了？

**Comment by claudehotline** [comment]
是的 是voc数据集

```
metric: VOC
map_type: 11point
num_classes: 3

TrainDataset:
  !VOCDataSet
    dataset_dir: dataset/HelmetDetection
    anno_path: trainval.txt
    label_list: label_list.txt
    data_fields: ['image', 'gt_bbox', 'gt_class']

EvalDataset:
  !VOCDataSet
    dataset_dir: dataset/HelmetDetection
    anno_path: test.txt
    label_list: label_list.txt
    data_fields: ['image', 'gt_bbox', 'gt_class']

TestDataset:
  !ImageFolder
    anno_path: dataset/HelmetDetection/label_list.txt

```

**Comment by yghstill** [comment]
@claudehotline 配置文件中加上这两行：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/configs/ppyolo/ppyolo_r50vd_dcn_voc.yml#L19-L20

**Comment by claudehotline** [comment]
谢谢问题解决了。

**Comment by ketejun** [comment]
在paddleyolo里，遇到这种情况，那下的参数是设置成false还是False，区分大小写吗？
EvalReader:
  collate_batch: false/False
