### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by cslixin1997** [PaddlePaddle/PaddleDetection#3463]
WARNING 2021-06-22 03:57:39,633 launch.py:357] Not found distinct arguments and compiled with cuda or xpu. Default use collective mode
launch train in GPU mode!
INFO 2021-06-22 03:57:39,634 launch_utils.py:621] Change selected_gpus into reletive values. --ips:0,1,2,3,4,5,6,7 will change into relative_ips:[0, 1, 2, 3, 4, 5, 6, 7] according to your CUDA_VISIBLE_DEVICES:['0', '1', '2', '3', '4', '5', '6', '7']
can't find avilable port and use the specified static port now!
Traceback (most recent call last):
  File "/ai_zhang401/conda_files/envs/paddle_py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/ai_zhang401/conda_files/envs/paddle_py36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/ai_zhang401/conda_files/envs/paddle_py36/lib/python3.6/site-packages/paddle/distributed/launch.py", line 16, in <module>
    launch.launch()
  File "/ai_zhang401/conda_files/envs/paddle_py36/lib/python3.6/site-packages/paddle/distributed/fleet/launch.py", line 369, in launch
    launch_collective(args)
  File "/ai_zhang401/conda_files/envs/paddle_py36/lib/python3.6/site-packages/paddle/distributed/fleet/launch.py", line 241, in launch_collective
    devices_per_proc)
  File "/ai_zhang401/conda_files/envs/paddle_py36/lib/python3.6/site-packages/paddle/distributed/fleet/launch.py", line 210, in get_cluster_from_args
    trainer_endpoints.append(["%s:%d" % (ip, port) for port in free_ports])
TypeError: 'NoneType' object is not iterable

**Comment by liuhuiCNN** [comment]
请问您使用的命令是什么呢？

**Comment by cslixin1997** [comment]
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m paddle.distributed.launch --gpus 0,1,2,3,4,5,6,7 tools/train.py -c configs/solov2/solov2_r50_fpn_3x_coco.yml -o pretrain_weights=pre_weights/solov2_r50_fpn_3x_coco/solov2_r50_fpn_3x_coco.pdparams --vdl_log_dir=vdl_dir/scalar

**Comment by cslixin1997** [comment]
我在另一个容器里面，同样命令，是可以训练的，但是在这个容器里就会报这个错误，请问这个错误是什么导致的

**Comment by liuhuiCNN** [comment]
> 我在另一个容器里面，同样命令，是可以训练的，但是在这个容器里就会报这个错误，请问这个错误是什么导致的

那应该是跟环境有关系，两个容器环境是不是不一致？

**Comment by cslixin1997** [comment]
能运行的容器在老集群中，不能运行的容器在升级后的集群中，两个容器我都是用conda创建的paddle2.1.0的独立环境，然后同样的程序、同样的环境、同样的数据，一个能跑，一个报错，但是这个错误不知道是什么原因导致，没办法去解决，这边你能告诉我是什么原因吗

**Comment by cslixin1997** [comment]
@liuhuiCNN 能加上您的联系方式吗，我这边不知道问题，也不好跟集群工程师说明问题
