### ISSUE TITLE
在Ubuntu训练中随机出现_shutdown的错误

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/PaddleDetection#3475]
- PaddlePaddle 2.1.0
 - PaddeDetection 2.1.0
 - Python 3.7
 - 

我用的是这个模型`ppyolo_tiny_650e_voc.yml`，这个`ppyolo_r50vd_dcn_1x_voc.yml`模型也出现，其他的没试过。

在训练过程中，前面已经训练100多个epoch了，然后随机出现下面的错误。
```
Traceback (most recent call last):
  File "/home/fg010/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/ppdet/data/reader.py", line 211, in __next__
    return next(self.loader)
  File "/home/fg010/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 609, in __next__
    six.reraise(*sys.exc_info())
  File "/home/fg010/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/fg010/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 585, in __next__
    data = self._reader.read_next_var_list()
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 101, in <module>
W0622 19:34:15.590987 19289 default_variables.cpp:78] Fail to open /proc/self/stat: Too many open files [24]
W0622 19:34:15.639925 19289 default_variables.cpp:331] Fail to open /proc/self/fd: Too many open files [24]
W0622 19:34:15.639962 19289 default_variables.cpp:209] Fail to open /proc/self/statm: Too many open files [24]
W0622 19:34:15.639991 19289 default_variables.cpp:276] Fail to open /proc/loadavg: Too many open files [24]
W0622 19:34:15.640009 19289 default_variables.cpp:429] Fail to open /proc/self/io: Too many open files [24]
    main()
  File "train.py", line 97, in main
    run(FLAGS, cfg)
  File "train.py", line 70, in run
    trainer.train(FLAGS.eval)
  File "/home/fg010/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/ppdet/engine/trainer.py", line 303, in train
    for step_id, data in enumerate(self.loader):
  File "/home/fg010/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/ppdet/data/reader.py", line 213, in __next__
    self.loader = iter(self.dataloader)
  File "/home/fg010/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/reader.py", line 426, in __iter__
    return _DataLoaderIterMultiProcess(self)
  File "/home/fg010/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 283, in __init__
    self._init_workers()
  File "/home/fg010/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 317, in _init_workers
    indices_queue = multiprocessing.Queue()
  File "/home/fg010/anaconda3/envs/PaddlePaddle2/lib/python3.7/multiprocessing/context.py", line 102, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/home/fg010/anaconda3/envs/PaddlePaddle2/lib/python3.7/multiprocessing/queues.py", line 41, in __init__
    self._reader, self._writer = connection.Pipe(duplex=False)
  File "/home/fg010/anaconda3/envs/PaddlePaddle2/lib/python3.7/multiprocessing/connection.py", line 517, in Pipe
    fd1, fd2 = os.pipe()
OSError: [Errno 24] Too many open files
Exception ignored in: <function _DataLoaderIterMultiProcess.__del__ at 0x7f271e195e60>
Traceback (most recent call last):
  File "/home/fg010/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 566, in __del__
    self._try_shutdown_all()
  File "/home/fg010/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 371, in _try_shutdown_all
    if not self._shutdown:
AttributeError: '_DataLoaderIterMultiProcess' object has no attribute '_shutdown'
```

**Comment by wangxinxin08** [comment]
可以尝试减小下worker_num试下

**Comment by yeyupiaoling** [comment]
我试试

**Comment by zhuqiang00099** [comment]
worker_num=4没用，RTX 2080ti  paddle 2.1.0    python3.6 ubuntu18.04     跑的ppyolo_tiny_650e那个 ，我也是这个 错误。

**Comment by yeyupiaoling** [comment]
@zhuqiang00099 我设置worker_num=2都不行。我也是ppyolo_tiny_650e这个模型

**Comment by wangxinxin08** [comment]
@yeyupiaoling 所以减小worker_num能够解决你的问题吗？

**Comment by yeyupiaoling** [comment]
@wangxinxin08 不能。

**Comment by zhuqiang00099** [comment]
回退 到2.0.0好像 就可以，但是 如果 要导出 模型还是要用 2.1

**Comment by yeyupiaoling** [comment]
那这样有什么用，难道要搞两个环境？等他们修复吧

**Comment by thorory** [comment]
同问，发生了一样的错误
