### ISSUE TITLE
fairmot预测视频报错

### ISSUE THREAD

**Issue by GexLoong** [PaddlePaddle/PaddleDetection#3496]
输入视频路径后用fairmot进行预测报错
[06/25 10:47:03] ppdet.utils.checkpoint INFO: Finish resuming model weights: output/fairmot_dla34_30e_1088x608/model_final.pdparams
[06/25 10:47:03] ppdet.engine.tracker INFO: Starting tracking dataset/test/mot_images/0.mp4
[06/25 10:47:03] ppdet.data.source.mot INFO: Length of the video: 300 frames
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/data/reader.py:61: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  f, e, str(stack_info)))
[06/25 10:47:07] reader WARNING: fail to map sample transform [Decode_cde39e] with error: 'NoneType' object has no attribute 'shape' and stack:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/data/reader.py", line 56, in __call__
    data = f(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/data/transform/operators.py", line 101, in __call__
    sample = self.apply(sample, context)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/data/transform/operators.py", line 135, in apply
    elif sample['h'] != im.shape[0]:
AttributeError: 'NoneType' object has no attribute 'shape'

WARNING:root:DataLoader reader thread raised an exception.
Traceback (most recent call last):
  File "tools/infer_mot.py", line 115, in <module>
    main()
  File "tools/infer_mot.py", line 111, in main
    run(FLAGS, cfg)
  File "tools/infer_mot.py", line 97, in run
    det_results_dir=FLAGS.det_results_dir)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/engine/tracker.py", line 359, in mot_predict
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 199, in _thread_loop
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 167, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 61, in fetch
    data = [self.dataset[idx] for idx in batch_indices]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 61, in <listcomp>
    data = [self.dataset[idx] for idx in batch_indices]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/data/source/dataset.py", line 87, in __getitem__
    return self.transform(roidb)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/data/reader.py", line 62, in __call__
    raise e
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/data/reader.py", line 56, in __call__
    data = f(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/data/transform/operators.py", line 101, in __call__
    sample = self.apply(sample, context)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/data/transform/operators.py", line 135, in apply
    elif sample['h'] != im.shape[0]:
AttributeError: 'NoneType' object has no attribute 'shape'
    frame_rate=frame_rate)

  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/engine/tracker.py", line 125, in _eval_seq_jde
    for step_id, data in enumerate(dataloader):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/ppdet/data/reader.py", line 211, in __next__
    return next(self.loader)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 204, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

**Comment by nemonameless** [comment]
使用的版本和命令?

**Comment by GexLoong** [comment]
paddle2.1
!python tools/infer_mot.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml -o weights=output/fairmot_dla34_30e_1088x608/model_final.pdparams --video_file=dataset/test/mot_images/0.mp4 --save_videos

**Comment by nemonameless** [comment]
> paddle2.1
> !python tools/infer_mot.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml -o weights=output/fairmot_dla34_30e_1088x608/model_final.pdparams --video_file=dataset/test/mot_images/0.mp4 --save_videos

更新下代码试试，PaddleDetection develop和release2.1分支最新代码自测均没有问题

**Comment by nemonameless** [comment]
> paddle2.1
> !python tools/infer_mot.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml -o weights=output/fairmot_dla34_30e_1088x608/model_final.pdparams --video_file=dataset/test/mot_images/0.mp4 --save_videos

是否还有问题？如果有问题可以继续跟进，没问题可以关了issue？
