### ISSUE TITLE
推理过程中，置信度过滤掉所有的框，推理报错

### ISSUE THREAD

**Issue by ChengYi1996** [PaddlePaddle/PaddleDetection#3500]
Traceback (most recent call last):
  File "tools/eval.py", line 133, in <module>
    main()
  File "tools/eval.py", line 129, in main
    run(FLAGS, cfg)
  File "tools/eval.py", line 104, in run
    trainer.evaluate()
  File "/home/h410/anaconda3/envs/paddle/lib/python3.7/site-packages/paddledet-2.1.0-py3.7.egg/ppdet/engine/trainer.py", line 388, in evaluate
    self._eval_with_loader(self.loader)
  File "/home/h410/anaconda3/envs/paddle/lib/python3.7/site-packages/paddledet-2.1.0-py3.7.egg/ppdet/engine/trainer.py", line 366, in _eval_with_loader
    outs = self.model(data)
  File "/home/h410/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/h410/anaconda3/envs/paddle/lib/python3.7/site-packages/paddledet-2.1.0-py3.7.egg/ppdet/modeling/architectures/meta_arch.py", line 29, in forward
    out = self.get_pred()
  File "/home/h410/anaconda3/envs/paddle/lib/python3.7/site-packages/paddledet-2.1.0-py3.7.egg/ppdet/modeling/architectures/cascade_rcnn.py", line 136, in get_pred
    bbox_pred, bbox_num, mask_pred = self._forward()
  File "/home/h410/anaconda3/envs/paddle/lib/python3.7/site-packages/paddledet-2.1.0-py3.7.egg/ppdet/modeling/architectures/cascade_rcnn.py", line 115, in _forward
    im_shape, scale_factor)
  File "/home/h410/anaconda3/envs/paddle/lib/python3.7/site-packages/paddledet-2.1.0-py3.7.egg/ppdet/modeling/post_process.py", line 120, in get_pred
    scaled_bbox = pred_bbox / scale_factor_list
  File "/home/h410/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 250, in __impl__
    return math_op(self, other_var, 'axis', axis)
RuntimeError: (PreconditionNotMet) The Tensor's element number must be equal or greater than zero. The Tensor's shape is [-1, 4] now
  [Hint: Expected numel() >= 0, but received numel():-4 < 0:0.] (at /paddle/paddle/fluid/framework/tensor.cc:59)
  [operator < elementwise_div > error]
INFO 2021-06-25 16:15:59,302 launch_utils.py:327] terminate all the procs
ERROR 2021-06-25 16:15:59,302 launch_utils.py:584] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0, 1] was aborted. Please check its log.
INFO 2021-06-25 16:16:02,306 launch_utils.py:327] terminate all the procs

**Comment by alicekillen** [comment]
我也遇见了这个问题，可以问下您的解决方法吗
