### ISSUE TITLE
S2ANet develop版本中， unknown metric type RBOX

### ISSUE THREAD

**Issue by ZJH970922** [PaddlePaddle/PaddleDetection#3503]
对spinecoco数据集进行训练后，调用预测指令，反馈以下问题：
 G:\PaddleDetection\PaddleDetection-develop>python tools/infer.py -c configs/dota/s2anet_1x_spine.yml -o weitghts=output/s2anet_1x_spine/model_final.pdparams --infer_img=demo/39006.jpg
W0625 21:09:26.594723  9492 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.2
W0625 21:09:26.594723  9492 device_context.cc:422] device: 0, cuDNN Version: 8.1.
[06/25 21:09:29] ppdet.utils.checkpoint INFO: Finish loading model weights: output/s2anet_1x_spine/model_final.pdparams
Traceback (most recent call last):
  File "tools/infer.py", line 158, in <module>
    main()
  File "tools/infer.py", line 154, in main
    run(FLAGS, cfg)
  File "tools/infer.py", line 132, in run
    save_txt=FLAGS.save_txt)
  File "G:\Anaconda\envs\paddle\lib\site-packages\paddledet-2.1.0-py3.7.egg\ppdet\engine\trainer.py", line 414, in predict
    self.cfg.metric, anno_file=anno_file)
  File "G:\Anaconda\envs\paddle\lib\site-packages\paddledet-2.1.0-py3.7.egg\ppdet\data\source\category.py", line 93, in get_categories
    raise ValueError("unknown metric type {}".format(metric_type))
ValueError: unknown metric type RBOX

**Comment by liuhuiCNN** [comment]
请在数据集中设置`metric: RBOX`

**Comment by ZJH970922** [comment]
> 请在数据集中设置`metric: RBOX`

是把configs/datasets里面的yml文件设置为metric: RBOX吗？ 
还是将数据集转换成metric: RBOX？应该怎么转换呢？

**Comment by qingqing01** [comment]
@Breathless922 可以参考下面：

configs/datasets/dota.yml 文件

https://github.com/PaddlePaddle/PaddleDetection/blob/6e8607b4c042453dc8ea5c2ffb244cc7e792dbc6/configs/datasets/dota.yml#L1
