### ISSUE TITLE
多目标检测fairmot windows下演示代码问题

### ISSUE THREAD

**Issue by caterwang13K73** [PaddlePaddle/PaddleDetection#3504]
参考： https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/configs/mot 3. 预测
运行环境：
win10,cuda10.1,python3.8,opencv3.4.8(pip安装),1050TI(4G)显卡

参考以下代码：
# 预测一个视频
CUDA_VISIBLE_DEVICES=0 python tools/infer_mot.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml -o weights=https://paddledet.bj.bcebos.com/models/mot/fairmot_dla34_30e_1088x608.pdparams --video_file={your video name}.mp4  --save_videos

实际执行代码：
python tools/infer_mot.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml -o weights=./weights/fairmot_dla34_30e_1088x608.pdparams --video_file=./video_file/3.mp4  --save_videos

报错信息：
Invalid number of channels in input image:

完整输出信息：
W0625 22:34:05.103384 36016 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.2, Runtime API Version: 10.1
W0625 22:34:05.109366 36016 device_context.cc:422] device: 0, cuDNN Version: 7.6.
[06/25 22:34:07] ppdet.utils.checkpoint INFO: Finish resuming model weights: ./weights/fairmot_dla34_30e_1088x608.pdparams
[06/25 22:34:07] ppdet.engine.tracker INFO: Starting tracking ./video_file/3.mp4
[06/25 22:34:07] ppdet.data.source.mot INFO: Length of the video: 630 frames
Traceback (most recent call last):
  File "tools/infer_mot.py", line 115, in <module>
    main()
  File "tools/infer_mot.py", line 111, in main
    run(FLAGS, cfg)
  File "tools/infer_mot.py", line 89, in run
    tracker.mot_predict(
  File "E:\PaddlePaddle_Study\PaddleDetection\ppdet\engine\tracker.py", line 349, in mot_predict
    self.dataset.set_video(video_file)
  File "E:\PaddlePaddle_Study\PaddleDetection\ppdet\data\source\mot.py", line 360, in set_video
    self.roidbs = self._load_video_images()
  File "E:\PaddlePaddle_Study\PaddleDetection\ppdet\data\source\mot.py", line 336, in _load_video_images
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(3.4.8) c:\projects\opencv-python\opencv\modules\imgproc\src\color.simd_helpers.hpp:88: error: (-2:Unspecified error) in function '__cdecl cv::impl::`anonymous-namespace'::CvtHelper<struct cv::impl::`anonymous namespace'::Set<3,4,-1>,struct cv::impl::A0xe227985e::Set<3,4,-1>,struct cv::impl::A0xe227985e::Set<0,2,5>,2>::CvtHelper(const class cv::_InputArray &,const class cv::_OutputArray &,int)'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 1

**Comment by nemonameless** [comment]
请更新下release/2.1 分支代码或使用develop分支。我们自测是正常的。
