### ISSUE TITLE
yaml.constructor.ConstructorError和No module named 'ppdet.experimental'

### ISSUE THREAD

**Issue by MichaelZhero** [PaddlePaddle/PaddleDetection#3522]
1、在window 10下面使用\PaddleDetection-release-2.1；
2、使用动态图训练时，报yaml.constructor.ConstructorError: could not determine a constructor for the tag '!DecodeImage'
3、切换成静态图训练时，报 File "tools/train.py", line 44, in <module>
    from ppdet.experimental import mixed_precision_context
ModuleNotFoundError: No module named 'ppdet.experimental'

(paddle) E:\github\PaddleDetection-release-2.1\PaddleDetection-release-2.1>python tools/train.py -c configs/rcnn_enhance/cascade_rcnn_dcn_r50_vd_fpn_3x_server_side.yml --eval
Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 116, in main
    cfg = load_config(FLAGS.config)
  File "C:\Users\OPT\Anaconda3\envs\paddle\lib\site-packages\ppdet\core\workspace.py", line 115, in load_config
    cfg = _load_config_with_base(file_path)
  File "C:\Users\OPT\Anaconda3\envs\paddle\lib\site-packages\ppdet\core\workspace.py", line 80, in _load_config_with_base
    file_cfg = yaml.load(f, Loader=yaml.Loader)
  File "C:\Users\OPT\Anaconda3\envs\paddle\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Users\OPT\Anaconda3\envs\paddle\lib\site-packages\yaml\constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "C:\Users\OPT\Anaconda3\envs\paddle\lib\site-packages\yaml\constructor.py", line 60, in construct_document
    for dummy in generator:
  File "C:\Users\OPT\Anaconda3\envs\paddle\lib\site-packages\yaml\constructor.py", line 408, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "C:\Users\OPT\Anaconda3\envs\paddle\lib\site-packages\yaml\constructor.py", line 129, in construct_sequence
    return [self.construct_object(child, deep=deep)
  File "C:\Users\OPT\Anaconda3\envs\paddle\lib\site-packages\yaml\constructor.py", line 129, in <listcomp>
    return [self.construct_object(child, deep=deep)
  File "C:\Users\OPT\Anaconda3\envs\paddle\lib\site-packages\yaml\constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "C:\Users\OPT\Anaconda3\envs\paddle\lib\site-packages\yaml\constructor.py", line 427, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!DecodeImage'
  in "configs/rcnn_enhance/cascade_rcnn_dcn_r50_vd_fpn_3x_server_side.yml", line 124, column 5

(paddle) E:\github\PaddleDetection-release-2.1\PaddleDetection-release-2.1>cd static

(paddle) E:\github\PaddleDetection-release-2.1\PaddleDetection-release-2.1\static>python tools/train.py -c configs/rcnn_enhance/cascade_rcnn_dcn_r50_vd_fpn_3x_server_side1.yml --eval
Traceback (most recent call last):
  File "tools/train.py", line 65, in <module>
    raise e
  File "tools/train.py", line 44, in <module>
    from ppdet.experimental import mixed_precision_context
ModuleNotFoundError: No module named 'ppdet.experimental'

**Comment by jerrywgz** [comment]
动态图下的报错原因是，configs/rcnn_enhance/cascade_rcnn_dcn_r50_vd_fpn_3x_server_side1.yml 这个配置文件只支持静态图，在动态图下是不兼容的。可以尝试使用https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/configs/rcnn_enhance/faster_rcnn_enhance_3x_coco.yml 这个配置。如果在动态图和静态图之间切换，建议先pip uninstall paddledet。

**Comment by MichaelZhero** [comment]
使用pip uninstall paddledet后，可以正常训练。多谢。

在aistudio没有使用‘pip uninstall paddledet’
而采用下面这句命令，也可以完成正常训练
!export PYTHONPATH.=$PYTHONPATH
!export CUDA_VISIBLE_DEVICES=0

**Comment by MichaelZhero** [comment]
> 动态图下的报错原因是，configs/rcnn_enhance/cascade_rcnn_dcn_r50_vd_fpn_3x_server_side1.yml这个配置文件只支持静态图，在动态图下是不兼容的。如果在动态图和静态图之间切换，建议先pip uninstall paddledet。

使用pip uninstall paddledet后，可以正常训练。多谢。

在aistudio没有使用‘pip uninstall paddledet’
而采用下面这句命令，也可以完成正常训练
!export PYTHONPATH.=$PYTHONPATH
!export CUDA_VISIBLE_DEVICES=0

**Comment by MichaelZhero** [comment]
使用pip uninstall paddledet后，可以正常训练。多谢。

在aistudio没有使用‘pip uninstall paddledet’
而采用下面这句命令，也可以完成正常训练
!export PYTHONPATH.=$PYTHONPATH
!export CUDA_VISIBLE_DEVICES=0
