### ISSUE TITLE
YOLOV3-训练自定义coco格式数据集报错

### ISSUE THREAD

**Issue by ximitiejiang** [PaddlePaddle/PaddleDetection#3531]
该自定义数据集在fasterrcnn模型上已经跑过没有问题，但不知道为什么在yolov3上报错。
```
[06/29 10:12:55] ppdet.engine INFO: Epoch: [14] [  0/261] learning_rate: 0.001142 loss_xy: 3.539429 loss_wh: 1.569762 loss_obj: 7.965590 loss_cls: 0.847763 loss: 14.178358 eta: 7:35:29 batch_cost: 0.4247 data_cost: 0.2433 ips: 9.4186 images/s
[06/29 10:13:03] ppdet.engine INFO: Epoch: [14] [ 20/261] learning_rate: 0.001148 loss_xy: 4.150413 loss_wh: 1.634536 loss_obj: 8.588768 loss_cls: 0.780585 loss: 14.390470 eta: 7:35:14 batch_cost: 0.3903 data_cost: 0.1949 ips: 10.2492 images/s
[06/29 10:13:10] ppdet.engine INFO: Epoch: [14] [ 40/261] learning_rate: 0.001154 loss_xy: 5.121928 loss_wh: 1.915970 loss_obj: 9.221029 loss_cls: 1.040466 loss: 17.048763 eta: 7:34:44 batch_cost: 0.3476 data_cost: 0.1670 ips: 11.5071 images/s
[06/29 10:13:17] ppdet.engine INFO: Epoch: [14] [ 60/261] learning_rate: 0.001161 loss_xy: 3.654006 loss_wh: 1.515937 loss_obj: 8.141011 loss_cls: 0.916687 loss: 15.310648 eta: 7:34:19 batch_cost: 0.3627 data_cost: 0.1700 ips: 11.0279 images/s
[06/29 10:13:24] ppdet.engine INFO: Epoch: [14] [ 80/261] learning_rate: 0.001167 loss_xy: 3.943925 loss_wh: 1.593351 loss_obj: 9.177536 loss_cls: 0.809466 loss: 16.202129 eta: 7:33:58 batch_cost: 0.3715 data_cost: 0.1608 ips: 10.7685 images/s
[06/29 10:13:32] ppdet.engine INFO: Epoch: [14] [100/261] learning_rate: 0.001173 loss_xy: 4.507587 loss_wh: 1.768098 loss_obj: 9.911394 loss_cls: 0.836492 loss: 17.249420 eta: 7:33:38 batch_cost: 0.3763 data_cost: 0.1780 ips: 10.6307 images/s
Traceback (most recent call last):
  File "/home/suliang/suliang_git/PaddleDetection-2.0.0/sl_package/train.py", line 155, in <module>
    main()
  File "/home/suliang/suliang_git/PaddleDetection-2.0.0/sl_package/train.py", line 151, in main
    run(FLAGS, cfg)
  File "/home/suliang/suliang_git/PaddleDetection-2.0.0/sl_package/train.py", line 111, in run
    trainer.train(FLAGS.eval)
  File "/home/suliang/suliang_git/PaddleDetection-2.0.0/ppdet/engine/trainer.py", line 250, in train
    for step_id, data in enumerate(self.loader):
  File "/home/suliang/suliang_git/PaddleDetection-2.0.0/ppdet/data/reader.py", line 216, in __next__
    data = next(self.loader)
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 585, in __next__
    data = self._reader.read_next_var_list()
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/multiprocess_utils.py", line 138, in __handler__
    core._throw_error_if_process_failed()
SystemError: (Fatal) DataLoader process (pid 21781) exited is killed by signal: Killed. (at /paddle/paddle/fluid/imperative/data_loader.cc:181)

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/multiprocess_utils.py", line 74, in _func_exectuor
    function()
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 569, in _shutdown_on_exit
    self._try_shutdown_all(1)
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 385, in _try_shutdown_all
    w.join(timeout)
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/multiprocessing/process.py", line 140, in join
    res = self._popen.wait(timeout)
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/multiprocessing/popen_fork.py", line 45, in wait
    if not wait([self.sentinel], timeout):
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/multiprocessing/connection.py", line 921, in wait
    ready = selector.select(timeout)
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/multiprocess_utils.py", line 138, in __handler__
    core._throw_error_if_process_failed()
SystemError: (Fatal) DataLoader process (pid 21781) exited is killed by signal: Killed. (at /paddle/paddle/fluid/imperative/data_loader.cc:181)
```

我的yolov3设置如下：
```
_BASE_: [
  '../configs/datasets/coco_detection.yml',
  '../configs/runtime.yml',
  '../configs/yolov3/_base_/optimizer_270e.yml',
  '../configs/yolov3/_base_/yolov3_darknet53.yml',
  '../configs/yolov3/_base_/yolov3_reader.yml',
]

snapshot_epoch: 5
weights: /home/suliang/suliang_git/PaddleDetection-2.0.0/sl_package/output/sl_package_yolov3_darknet53_270e_coco/model_final.pdparams

# 数据集调整
# change n_classes： 增加了ok-noexposed1、ok-noexposed2类后变为6类
num_classes: 6
TrainDataset:
  !COCODataSet
    image_dir: train
    anno_path: annotations/instance_train.json
    dataset_dir: ../dataset/Package/coco_format
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val
    anno_path: annotations/instance_val.json
    dataset_dir: ../dataset/Package/coco_format
TestDataset:
  !ImageFolder
    anno_path: ../dataset/Package/coco_format/annotations/instance_val.json

worker_num: 2
TrainReader:
  # 初次训练在epoch15意外退出，然后尝试把batch size从8变到4，依然报错，GPU占用显存8G/11G
  batch_size: 4

LearningRate:
  # from 0.01 to 0.01/8
  base_lr: 0.00125

# 保持yolov3现有anchor设置不变
YOLOv3Head:
  anchors: [[10, 13], [16, 30], [33, 23],
            [30, 61], [62, 45], [59, 119],
            [116, 90], [156, 198], [373, 326]]
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  loss: YOLOv3Loss
```
请问下可能是什么问题？

**Comment by yghstill** [comment]
@ximitiejiang 看你的配置文件应该没有问题，更新PaddleDetection版本到release-2.1，PaddlePaddle版本到2.1.0再试下训练，是否还出问题。

**Comment by ximitiejiang** [comment]
升级到paddledet2.1版本重新训练，原来在epoch14的报错就没有了，但到epoch36又报错了

```
[06/29 14:39:49] ppdet.engine INFO: Epoch: [36] [  0/261] learning_rate: 0.001250 loss_xy: 4.193555 loss_wh: 1.279707 loss_obj: 7.153632 loss_cls: 0.593782 loss: 13.100969 eta: 6:47:06 batch_cost: 0.4350 data_cost: 0.2310 ips: 9.1946 images/s
[06/29 14:39:57] ppdet.engine INFO: Epoch: [36] [ 20/261] learning_rate: 0.001250 loss_xy: 4.469457 loss_wh: 1.308918 loss_obj: 7.579385 loss_cls: 0.637176 loss: 14.546173 eta: 6:46:59 batch_cost: 0.4078 data_cost: 0.1913 ips: 9.8083 images/s
[06/29 14:40:05] ppdet.engine INFO: Epoch: [36] [ 40/261] learning_rate: 0.001250 loss_xy: 4.698157 loss_wh: 1.505161 loss_obj: 7.241337 loss_cls: 0.248068 loss: 14.359529 eta: 6:46:51 batch_cost: 0.4003 data_cost: 0.1717 ips: 9.9929 images/s
[06/29 14:40:12] ppdet.engine INFO: Epoch: [36] [ 60/261] learning_rate: 0.001250 loss_xy: 3.746909 loss_wh: 1.253618 loss_obj: 6.357468 loss_cls: 0.415609 loss: 11.694826 eta: 6:46:40 batch_cost: 0.3743 data_cost: 0.1772 ips: 10.6855 images/s
[06/29 14:40:27] ppdet.engine INFO: Epoch: [36] [ 80/261] learning_rate: 0.001250 loss_xy: 4.775592 loss_wh: 1.245894 loss_obj: 7.685760 loss_cls: 0.471089 loss: 14.012933 eta: 6:47:12 batch_cost: 0.7121 data_cost: 0.4662 ips: 5.6168 images/s
[06/29 14:40:34] ppdet.engine INFO: Epoch: [36] [100/261] learning_rate: 0.001250 loss_xy: 4.097913 loss_wh: 1.191368 loss_obj: 6.684952 loss_cls: 0.398719 loss: 12.415850 eta: 6:47:02 batch_cost: 0.3841 data_cost: 0.1776 ips: 10.4145 images/s
[06/29 14:40:42] ppdet.engine INFO: Epoch: [36] [120/261] learning_rate: 0.001250 loss_xy: 3.557496 loss_wh: 1.066980 loss_obj: 7.000424 loss_cls: 0.357550 loss: 12.419004 eta: 6:46:49 batch_cost: 0.3629 data_cost: 0.1627 ips: 11.0210 images/s
[06/29 14:40:50] ppdet.engine INFO: Epoch: [36] [140/261] learning_rate: 0.001250 loss_xy: 3.968297 loss_wh: 1.341620 loss_obj: 6.608496 loss_cls: 0.690580 loss: 12.245900 eta: 6:46:42 batch_cost: 0.4101 data_cost: 0.1954 ips: 9.7546 images/s
[06/29 14:40:58] ppdet.engine INFO: Epoch: [36] [160/261] learning_rate: 0.001250 loss_xy: 3.806834 loss_wh: 1.214791 loss_obj: 6.996197 loss_cls: 0.505875 loss: 12.815691 eta: 6:46:34 batch_cost: 0.3980 data_cost: 0.1746 ips: 10.0501 images/s
[06/29 14:41:05] ppdet.engine INFO: Epoch: [36] [180/261] learning_rate: 0.001250 loss_xy: 3.960924 loss_wh: 1.396337 loss_obj: 7.485311 loss_cls: 0.407327 loss: 13.582262 eta: 6:46:23 batch_cost: 0.3799 data_cost: 0.1645 ips: 10.5303 images/s
[06/29 14:41:13] ppdet.engine INFO: Epoch: [36] [200/261] learning_rate: 0.001250 loss_xy: 3.634242 loss_wh: 1.132988 loss_obj: 7.162887 loss_cls: 0.643671 loss: 13.877409 eta: 6:46:14 batch_cost: 0.3938 data_cost: 0.1937 ips: 10.1584 images/s
[ERROR 2021-06-29 14:41:43,206 dataloader_iter.py:400] DataLoader reader thread raised an exception!
Traceback (most recent call last):
  File "/home/suliang/suliang_git/PaddleDetection-release-2.1/sl_package/train.py", line 159, in <module>
    main()
  File "/home/suliang/suliang_git/PaddleDetection-release-2.1/sl_package/train.py", line 155, in main
    run(FLAGS, cfg)
  File "/home/suliang/suliang_git/PaddleDetection-release-2.1/sl_package/train.py", line 111, in run
    trainer.train(FLAGS.eval)
  File "/home/suliang/suliang_git/PaddleDetection-release-2.1/ppdet/engine/trainer.py", line 290, in train
Exception in thread Thread-38:
Traceback (most recent call last):
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 482, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 411, in _thread_loop
    batch = self._get_data()
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 498, in _get_data
    "pids: {}".format(len(failed_workers), pids))
RuntimeError: DataLoader 1 workers exit unexpectedly, pids: 31756

    for step_id, data in enumerate(self.loader):
  File "/home/suliang/suliang_git/PaddleDetection-release-2.1/ppdet/data/reader.py", line 211, in __next__
    return next(self.loader)
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 585, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)
```

**Comment by yghstill** [comment]
@ximitiejiang 再-r指定中间权重，重启下训练吧，DataLoader的queue出空的问题我们正在排查中

**Comment by ximitiejiang** [comment]
我把数据集从机械硬盘搬到固态硬盘，且换成batchsize=8的原始设置，然后训练坚持到60个epoch退出，没有报错但还是训练不完
```
[06/29 16:55:05] ppdet.engine INFO: Epoch: [60] [  0/130] learning_rate: 0.001250 loss_xy: 3.838952 loss_wh: 1.149841 loss_obj: 6.497204 loss_cls: 0.494893 loss: 11.804527 eta: 5:48:47 batch_cost: 0.7410 data_cost: 0.3538 ips: 10.7961 images/s
[06/29 16:55:19] ppdet.engine INFO: Epoch: [60] [ 20/130] learning_rate: 0.001250 loss_xy: 3.853410 loss_wh: 1.236646 loss_obj: 6.168977 loss_cls: 0.348237 loss: 11.764378 eta: 5:48:26 batch_cost: 0.6879 data_cost: 0.3376 ips: 11.6296 images/s
[06/29 16:55:33] ppdet.engine INFO: Epoch: [60] [ 40/130] learning_rate: 0.001250 loss_xy: 4.063771 loss_wh: 1.232631 loss_obj: 6.789543 loss_cls: 0.479522 loss: 12.405113 eta: 5:48:08 batch_cost: 0.7183 data_cost: 0.3791 ips: 11.1373 images/s
[06/29 16:55:48] ppdet.engine INFO: Epoch: [60] [ 60/130] learning_rate: 0.001250 loss_xy: 4.001770 loss_wh: 1.335941 loss_obj: 6.553658 loss_cls: 0.545535 loss: 12.141327 eta: 5:47:51 batch_cost: 0.7493 data_cost: 0.4085 ips: 10.6772 images/s
[06/29 16:56:04] ppdet.engine INFO: Epoch: [60] [ 80/130] learning_rate: 0.001250 loss_xy: 4.220201 loss_wh: 1.431622 loss_obj: 6.701253 loss_cls: 0.452689 loss: 12.882275 eta: 5:47:36 batch_cost: 0.7727 data_cost: 0.4111 ips: 10.3533 images/s

Process finished with exit code 137 (interrupted by signal 9: SIGKILL)
```

**Comment by heavengate** [comment]
你好，你Paddle用的哪个版本呢，另外看报错信息是进程被kill信号杀了，一般可能是内存不够或者手动kill 的情况，`free -h`看下空闲内存大小呢

**Comment by ximitiejiang** [comment]
你好，我的paddle2.1, paddledet2.1.0，batchsize=8时：
- GPU显存占用率是比较高了(10.9G/11.17G)
- cpu的占比情况：
```
              total        used        free      shared  buff/cache   available
Mem:           7.7G        4.5G        1.1G        273M        2.1G        2.6G
Swap:          2.0G        1.0G        1.0G
```

**Comment by oldZhangYH** [comment]
您好，请问自定义coco数据的配置文件中吗，下面加粗的`dataset_dir`具体指什么？
TrainDataset:
  !COCODataSet
    image_dir: train
    anno_path: annotations/instance_train.json
    **`dataset_dir: ../dataset/Package/coco_format`**
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

**Comment by heavengate** [comment]
> 你好，我的paddle2.1, paddledet2.1.0，batchsize=8时：
> 
> * GPU显存占用率是比较高了(10.9G/11.17G)
> * cpu的占比情况：
> 
> ```
>               total        used        free      shared  buff/cache   available
> Mem:           7.7G        4.5G        1.1G        273M        2.1G        2.6G
> Swap:          2.0G        1.0G        1.0G
> ```

看你free内存比较少，应该是内存不够了进程被操作系统kill了，可以把对应`configs/yolov3/_base_/xxx_reader.yml`里的`num_workers`设小一点试下

**Comment by ximitiejiang** [comment]
@kekekahuatian dataset_dir就是数据集根目录
