### ISSUE TITLE
自定义数据集增加属性报错

### ISSUE THREAD

**Issue by raymondchu-z** [PaddlePaddle/PaddleDetection#3535]
` def parse_dataset()`如下。原本是正常的，仿照difficult 尝试增加了 occluded 和 truncated 两个属性之后报错
`ValueError: all input arrays must have the same shape`。
代码中有检查 occluded 和 truncated的维度与其他一致。
~~~
    def parse_dataset(self):
        anno_path = os.path.join(self.dataset_dir, self.anno_path)
        image_dir = os.path.join(self.dataset_dir, self.image_dir)

        # mapping category name to class id
        # first_class:1, second_class:2, ...
        records = []
        ct = 0
        cname2cid = {}
        if self.label_list:
            label_path = os.path.join(self.dataset_dir, self.label_list)
            if not os.path.exists(label_path):
                raise ValueError("label_list {} does not exists".format(
                    label_path))
            with open(label_path, 'r') as fr:
                label_id = 0
                for line in fr.readlines():
                    cname2cid[line.strip()] = label_id
                    label_id += 1
        else:
            cname2cid = dto_label()
        #读取写有标注文件和图片路径的txt文件
        with open(anno_path, 'r') as fr:
            while True:
                #处理每对标注和图片，保证文件有效性
                line = fr.readline()
                if not line:
                    break
                img_file, json_file = [os.path.join(image_dir, x) \
                        for x in line.strip().split()[:2]]
                if not os.path.exists(img_file):
                    logger.warn(
                        'Illegal image file: {}, and it will be ignored'.format(
                            img_file))
                    continue
                if not os.path.isfile(json_file):
                    logger.warn('Illegal xml file: {}, and it will be ignored'.
                                format(json_file))
                    continue
                    
                #处理每个标注
                with open(json_file) as f:
                    data = json.load(f)
                    #若有图片唯一id则使用，没有则使用计数ct作为id
                    if 'id' not in data:
                        im_id = np.array([ct])
                    else:
                        im_id = np.array([int(data[id])])
                    #标注中的每个目标对应'labels'下的每个字典
                    objs = data['labels']
                    #图像尺寸
                    image_info = data['image_meta_info']
                    im_w = image_info['size']['width']
                    im_h = image_info['size']['height']
                    im_d = image_info['size']['depth']
                    if im_w < 0 or im_h < 0:
                        logger.warn(
                            'Illegal width: {} or height: {} in annotation, '
                            'and {} will be ignored'.format(im_w, im_h, json_file))
                        continue
                    gt_bbox = []
                    gt_class = []
                    gt_score = []
                    difficult = []
                    occluded = []
                    truncated = []
                    _difficult = data['difficult']
                    #遍历每个目标
                    for i, obj in enumerate(objs):
                        #滤除非包围框目标类
                        # print(obj['shape_type'])
                        if obj['shape_type'] != "bndbox":
                            continue
                        #滤除未定义目标类别
                        cname = check_obj_detected(obj['name'])
                        if not cname : 
                            continue
                        #滤除使用了label_list条件下，只检测部分类
                        if not cname in cname2cid : 
                            continue
                        x1 = float(obj["bndbox"]["xmin"])
                        y1 = float(obj["bndbox"]["ymin"])
                        x2 = float(obj["bndbox"]["xmax"])
                        y2 = float(obj["bndbox"]["ymax"])
                        x1 = max(0, x1)
                        y1 = max(0, y1)
                        x2 = min(im_w - 1, x2)
                        y2 = min(im_h - 1, y2)
                        attr = obj["attribute"]
                        attr = ast.literal_eval(attr)
                        #bndbox参数有效性检测
                        if x2 > x1 and y2 > y1:
                            gt_bbox.append([x1, y1, x2, y2])
                            gt_class.append([cname2cid[cname]])
                            gt_score.append([1.])
                            difficult.append([_difficult])
                            occluded.append([attr["occluded"]])
                            truncated.append([attr["truncated"]])
                        else:
                            logger.warn(
                                'Found an invalid bbox in annotations: json_file: {}'
                                ', x1: {}, y1: {}, x2: {}, y2: {}.'.format(
                                    json_file, x1, y1, x2, y2))
                    # 有些标注bndbox参数无效，滤除
                    if len(gt_bbox) == 0:
                        continue        
                    # print(json_file)
                    gt_bbox = np.array(gt_bbox).astype('float32')
                    gt_class = np.array(gt_class).astype('int32')
                    gt_score = np.array(gt_score).astype('float32')#voc有的属性，暂未知何用
                    difficult = np.array(difficult).astype('int32')
                    occluded = np.array(occluded).astype('int32')
                    truncated = np.array(truncated).astype('int32')
#检查维度
                    print(difficult.shape)
                    print(occluded.shape)
                    print(truncated.shape)
                    #基本属性
                    dto_rec = {
                        'im_file': img_file,
                        'im_id': im_id,
                        'h': im_h,
                        'w': im_w
                    } if 'image' in self.data_fields else {}
                    #可选属性，根据data_fields选择
                    gt_rec = {
                        'gt_class': gt_class,
                        'gt_score': gt_score,
                        'gt_bbox': gt_bbox,
                        'difficult': difficult,
                        'occluded': occluded,
                        'truncated' : truncated
                    } 
                    
                    for k, v in gt_rec.items():
                        if k in self.data_fields:
                            dto_rec[k] = v

                    if len(objs) != 0:
                        records.append(dto_rec)         
                    ct += 1
                    if self.sample_num > 0 and ct >= self.sample_num:
                        break
            assert len(records) > 0, 'not found any voc record in %s' % (
                self.anno_path)
            logger.debug('{} samples in file {}'.format(ct, anno_path))
            self.roidbs, self.cname2cid = records, cname2cid
    def get_label_list(self):
        return os.path.join(self.dataset_dir, self.label_list)
~~~

**Comment by yghstill** [comment]
@raymondchu-z 你报错信息发下，报错位置是在这里吗？打印records看打印出来是否正确

**Comment by raymondchu-z** [comment]
在这里报错的。https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/engine/trainer.py#L357\
报错信息如下：
```
> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/zlm/anaconda3/envs/paddle_env/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/zlm/anaconda3/envs/paddle_env/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zlm/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 411, in _thread_loop
    batch = self._get_data()
  File "/home/zlm/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 525, in _get_data
    batch.reraise()
  File "/home/zlm/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dataloader/worker.py", line 168, in reraise
    raise self.exc_type(msg)
ValueError: DataLoader worker(1) caught ValueError with message:
Traceback (most recent call last):
  File "/home/zlm/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dataloader/worker.py", line 228, in _worker_loop
    batch = fetcher.fetch(indices)
  File "/home/zlm/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dataloader/fetcher.py", line 66, in fetch
    data = self.collate_fn(data)
  File "/home/zlm/9.github/PaddleDetection/ppdet/data/reader.py", line 101, in __call__
    tmp_data = np.stack(tmp_data, axis=0)
  File "<__array_function__ internals>", line 6, in stack
  File "/home/zlm/anaconda3/envs/paddle_env/lib/python3.6/site-packages/numpy/core/shape_base.py", line 425, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape

> [06/29 17:04:01] ppdet.utils.checkpoint INFO: Finish loading model weights: output/ppyolov2_r50vd_dcn_4e_coco_dto_finetune_cosine_4gpu/model_final.pdparams
Traceback (most recent call last):
  File "tools/eval.py", line 139, in <module>
    main()
  File "tools/eval.py", line 135, in main
    run(FLAGS, cfg)
  File "tools/eval.py", line 110, in run
    trainer.evaluate()
  File "/home/zlm/9.github/PaddleDetection/ppdet/engine/trainer.py", line 426, in evaluate
    self._eval_with_loader(self.loader)
  File "/home/zlm/9.github/PaddleDetection/ppdet/engine/trainer.py", line 367, in _eval_with_loader
    for step_id, data in enumerate(loader):
  File "/home/zlm/9.github/PaddleDetection/ppdet/data/reader.py", line 211, in __next__
    return next(self.loader)
  File "/home/zlm/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 585, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)
```
这是record的一条：
```
> [{'im_file': 'dataset/dto/./dataset-3320/version-1/VOC/data-info/1616571330910_2/hash2231-1589789604004.jpg', 'im_id': array([0]), 'h': 1080, 'w': 1920, 'gt_class': array([[2],
       [1],
       [4],
       [4],
       [1],
       [1],
       [1],
       [4],
       [4],
       [6],
       [4]], dtype=int32), 'gt_bbox': array([[1435.      ,  541.      , 1517.      ,  576.      ],
       [1540.      ,  540.      , 1568.      ,  576.      ],
       [1821.6506  ,  534.4138  , 1919.      ,  578.82886 ],
       [1587.023   ,  530.89044 , 1721.8694  ,  581.94403 ],
       [ 775.4385  ,  546.32666 ,  816.5343  ,  580.20294 ],
       [1394.351   ,  542.6675  , 1432.1152  ,  579.3504  ],
       [1100.0792  ,  541.1613  , 1135.7683  ,  576.9896  ],
       [1671.458   ,  533.1381  , 1818.5181  ,  580.9558  ],
       [ 342.2151  ,  548.8417  ,  448.56958 ,  581.01135 ],
       [ 609.6234  ,  524.7898  ,  667.4725  ,  572.51324 ],
       [  24.445574,  532.8788  ,  330.9312  ,  628.2571  ]],
      dtype=float32), 'difficult': array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]], dtype=int32), 'occluded': array([[1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1]], dtype=int32), 'truncated': array([[0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]], dtype=int32)},
```

**Comment by yghstill** [comment]
@raymondchu-z occluded和truncated的作用是什么？这两个组不了batch，所以会报错，这两个字段需要传入到网络中吗？

**Comment by raymondchu-z** [comment]
@yghstill 配置如下。这两个在评估的时候来用，训练不需要。
> metric: VOC
map_type: integral
num_classes: 7
TrainDataset:
  !DTODataSet
    dataset_dir: dataset/dto
    anno_path: train.txt
    label_list: label_list.txt
    # with_background: false
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']
EvalDataset:
  !DTODataSet
    dataset_dir: dataset/dto
    anno_path: test.txt
    label_list: label_list.txt
    # with_background: false
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']
TestDataset:
  !ImageFolder
    anno_path: dataset/dto/label_list.txt

**Comment by yghstill** [comment]
@raymondchu-z 如果训练中不需要将你那两个字段在Gt2YoloTarget组target这里pop一下：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/data/transform/batch_operators.py#L265

**Comment by raymondchu-z** [comment]
不行嗷，
~~~
            sample.pop('gt_class')
            sample.pop('gt_score')
            sample.pop('occluded')
            sample.pop('truncated')
        return samples
~~~

**Comment by yghstill** [comment]
@raymondchu-z 你是训练报错还是eval报错，eval的话加上这两行https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/configs/ppyolo/ppyolo_r50vd_dcn_voc.yml#L19-L20

**Comment by raymondchu-z** [comment]
@yghstill  是在eval报错。

> @raymondchu-z 你是训练报错还是eval报错，eval的话加上这两行https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/configs/ppyolo/ppyolo_r50vd_dcn_voc.yml#L19-L20

这两行已经加过了，这里和新添加的属性没关系。

**Comment by raymondchu-z** [comment]
@yghstill 您好，是否有进一步的解决方法？

**Comment by yghstill** [comment]
@raymondchu-z 加上
```
sample.pop('occluded')
sample.pop('truncated')
```
后在Gt2YoloTarget中打印下sample里这两个字段是否真的还存在

**Comment by yeyupiaoling** [comment]
在我的项目中报同一的错，安装上面说的，加上：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/configs/ppyolo/ppyolo_r50vd_dcn_voc.yml#L19-L20
解决问题。因为我的图片大小是不唯一的。

**Comment by raymondchu-z** [comment]
> @raymondchu-z 加上
> 
> ```
> sample.pop('occluded')
> sample.pop('truncated')
> ```
> 
> 后在Gt2YoloTarget中打印下sample里这两个字段是否真的还存在

@yghstill我单步调试都走不到Gt2YoloTarget()就已经报错了，在这里报错，读不到下一个loader：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/engine/trainer.py#L361

**Comment by raymondchu-z** [comment]
@yghstill 我将eval的batchsize设置为1就不报错。但是我的验证集很大，这样会很慢。
请问怎么在batchsize>1时，解决这个问题？

**Comment by JensenGao** [comment]
> @yghstill 我将eval的batchsize设置为1就不报错。但是我的验证集很大，这样会很慢。
> 请问怎么在batchsize>1时，解决这个问题？

俺也一样，设置batch size = 1就可以
