### ISSUE TITLE
export_model.py导出模型报错

### ISSUE THREAD

**Issue by NikolaTeslein** [PaddlePaddle/PaddleDetection#3537]
**使用的模型是configs\ppyolo\ppyolov2_r50vd_dcn_365e_coco.yml。

报错代码：**
ppdet.utils.checkpoint INFO: Finish loading model weights: PaddleDetection/Model/6-50.pdparams
[06/29 16:42:46] ppdet.engine INFO: Export inference config file to output_inference\ppyolov2_r50vd_dcn_365e_coco\infer_cfg.yml
**Traceback (most recent call last):**
  File "PaddleDetection/tools/export_model.py", line 105, in <module>
    main()
  File "PaddleDetection/tools/export_model.py", line 101, in main
    run(FLAGS, cfg)
  File "PaddleDetection/tools/export_model.py", line 69, in run
    trainer.export(FLAGS.output_dir)
  File "D:\Miniconda\envs\ImageDL\Lib\site-packages\paddledet-2.0.1-py3.6.egg\ppdet\engine\trainer.py", line 460, in export
    input_spec, static_model.forward.main_program,
  File "D:\Miniconda\envs\ImageDL\Lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 534, in main_program
    concrete_program = self.concrete_program
  File "D:\Miniconda\envs\ImageDL\Lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 454, in concrete_program
    return self.concrete_program_specify_input_spec(input_spec=None)
  File "D:\Miniconda\envs\ImageDL\Lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 488, in concrete_program_specify_input_spec
    *desired_input_spec)
  File "D:\Miniconda\envs\ImageDL\Lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 402, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "D:\Miniconda\envs\ImageDL\Lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 711, in __getitem__
    self._caches[item] = self._build_once(item)
  File "D:\Miniconda\envs\ImageDL\Lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 702, in _build_once
    class_instance=cache_key.class_instance)
  File "D:\Miniconda\envs\ImageDL\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\Miniconda\envs\ImageDL\Lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\Miniconda\envs\ImageDL\Lib\site-packages\paddle\fluid\dygraph\base.py", line 39, in __impl__
    return func(*args, **kwargs)
  File "D:\Miniconda\envs\ImageDL\Lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 658, in from_func_spec
    error_data.raise_new_exception()
  File "D:\Miniconda\envs\ImageDL\Lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\error.py", line 189, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
ValueError: In transformed code:

    File "C:\Users\Public\Documents\Wondershare\CreatorTemp\tmpscq09ft5.py", line 27, in forward
        false_fn_1, (), (), (out,))
    File "D:\Miniconda\envs\ImageDL\Lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 210, in convert_ifelse
        return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "D:\Miniconda\envs\ImageDL\Lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 235, in _run_py_ifelse
        return true_fn(*true_args) if pred else false_fn(*false_args)
    File "D:\Miniconda\envs\ImageDL\Lib\site-packages\paddledet-2.0.1-py3.6.egg\ppdet\modeling\architectures\meta_arch.py", line 29, in forward (* user code *)
        out = self.get_pred()
    File "D:\Miniconda\envs\ImageDL\Lib\site-packages\paddledet-2.0.1-py3.6.egg\ppdet\modeling\architectures\yolo.py", line 75, in get_pred (* user code *)
        bbox_pred, bbox_num = self._forward()
    File "D:\Miniconda\envs\ImageDL\Lib\site-packages\paddledet-2.0.1-py3.6.egg\ppdet\modeling\architectures\yolo.py", line 60, in _forward (* user code *)
        body_feats = self.neck(body_feats)
    File "D:\Miniconda\envs\ImageDL\Lib\site-packages\paddle\fluid\dygraph\layers.py", line 902, in __call__
        outputs = self.forward(*inputs, **kwargs)
    File "C:\Users\Public\Documents\Wondershare\CreatorTemp\tmppnfv6fh3.py", line 64, in forward
        for_loop_body_2, [blocks, route, tip, __for_loop_var_index_2, i])
    File "D:\Miniconda\envs\ImageDL\Lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 44, in convert_while_loop
        loop_vars = _run_py_while(cond, body, loop_vars)
    File "D:\Miniconda\envs\ImageDL\Lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 58, in _run_py_while
        loop_vars = body(*loop_vars)
    File "C:\Users\Public\Documents\Wondershare\CreatorTemp\tmppnfv6fh3.py", line 43, in for_loop_body_2
        (__for_loop_iter_var_2,), (__for_loop_iter_var_2,))
    File "D:\Miniconda\envs\ImageDL\Lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 210, in convert_ifelse
        return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "D:\Miniconda\envs\ImageDL\Lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 235, in _run_py_ifelse
        return true_fn(*true_args) if pred else false_fn(*false_args)
    File "C:\Users\Public\Documents\Wondershare\CreatorTemp\tmppnfv6fh3.py", line 36, in true_fn_11
        route), (__for_loop_iter_var_2,))
    File "D:\Miniconda\envs\ImageDL\Lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 210, in convert_ifelse
        return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "D:\Miniconda\envs\ImageDL\Lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 235, in _run_py_ifelse
        return true_fn(*true_args) if pred else false_fn(*false_args)
    File "D:\Miniconda\envs\ImageDL\Lib\site-packages\paddledet-2.0.1-py3.6.egg\ppdet\modeling\necks\yolo_fpn.py", line 929, in forward (* user code *)
        block = paddle.concat([route, block], axis=1)
    File "D:\Miniconda\envs\ImageDL\Lib\site-packages\paddle\tensor\manipulation.py", line 124, in concat
        return paddle.fluid.layers.concat(input=x, axis=axis, name=name)
    File "D:\Miniconda\envs\ImageDL\Lib\site-packages\paddle\fluid\layers\tensor.py", line 355, in concat
        type='concat', inputs=inputs, outputs={'Out': [out]}, attrs=attrs)
    File "D:\Miniconda\envs\ImageDL\Lib\site-packages\paddle\fluid\layer_helper.py", line 43, in append_op
        return self.main_program.current_block().append_op(*args, **kwargs)
    File "D:\Miniconda\envs\ImageDL\Lib\site-packages\paddle\fluid\framework.py", line 3027, in append_op
        attrs=kwargs.get("attrs", None))
    File "D:\Miniconda\envs\ImageDL\Lib\site-packages\paddle\fluid\framework.py", line 2222, in __init__
        self.desc.infer_shape(self.block.desc)
    _ValueError_: (InvalidArgument) The 3-th dimension of input[0] and input[1] is expected to be equal.But received input[0]'s shape = [-1, 256, 240, 136], input[1]'s shape = [-1, 512, 240, 135].
  [Hint: Expected inputs_dims[0][j] == inputs_dims[i][j], but received inputs_dims[0][j]:136 != inputs_dims[i][j]:135.] (at D:\v2.0.2\paddle\paddle/fluid/operators/concat_op.h:63)
  [operator < concat > error]

注：更换了其他pdparams再运行export_model.py报同样的错误，即使尝试导出与训练模型也一样。

**Comment by wangxinxin08** [comment]
你应该修改了预测时的图像尺寸，这个错误是由于你指定的TestReader的image_shape不是32的整数倍导致的

**Comment by NikolaTeslein** [comment]
> 你应该修改了预测时的图像尺寸，这个错误是由于你指定的TestReader的image_shape不是32的整数倍导致的

看到之前已经解决了，不过还是要感谢一下~

**Comment by NikolaTeslein** [comment]
您好，我想报告一个paddlepaddle的BUG，我已经在gitee上提交了issue，但是没有得到回复：
https://gitee.com/paddlepaddle/Paddle/issues/I41C9H





------------------ 原始邮件 ------------------
发件人: qingqing01 ***@***.***&gt;
发送时间: 2021年7月2日 17:56
收件人: PaddlePaddle/PaddleDetection ***@***.***&gt;
抄送: Teslein ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[PaddlePaddle/PaddleDetection] export_model.py导出模型报错 (#3537)





 
Closed #3537.

**Comment by wangxinxin08** [comment]
@NikolaTeslein 最好在github上提交issue
