### ISSUE TITLE
预测mask和原图片高宽反了报错

### ISSUE THREAD

**Issue by youyuan-zhang** [PaddlePaddle/PaddleDetection#3539]
我们用maskrcnn预测一个(2304, 3072, 3)大小的图片，但在visualize mask时候报错如下

我们打印了mask的shape，发现是(3072, 2304)；进一步打印test loader里这个图片的shape Tensor(shape=[1, 3, 1088, 800]）就发现长宽颠倒了。请问有什么解决办法吗？是在input resize的时候有些问题吗？

ppdet=2.1.0

报错如下
```
Traceback (most recent call last):
  File "PaddleDetection/tools/infer.py", line 158, in <module>
    main()
  File "PaddleDetection/tools/infer.py", line 154, in main
    run(FLAGS, cfg)
  File "PaddleDetection/tools/infer.py", line 132, in run
    save_txt=FLAGS.save_txt)
  File "/root/ikcest/PaddleDetection/ppdet/engine/trainer.py", line 448, in predict
    int(im_id), catid2name, draw_threshold)
  File "/root/ikcest/PaddleDetection/ppdet/utils/visualizer.py", line 47, in visualize_results
    image = draw_mask(image, im_id, mask_res, threshold)
  File "/root/ikcest/PaddleDetection/ppdet/utils/visualizer.py", line 83, in draw_mask
    img_array[idx[0], idx[1], :] *= 1.0 - alpha
IndexError: index 2304 is out of bounds for axis 0 with size 2304
```

**Comment by yghstill** [comment]
@sophistz 是reader配置文件中TestReader改了什么内容吗？

**Comment by youyuan-zhang** [comment]
> @sophistz 是reader配置文件中TestReader改了什么内容吗？

不是的，我infer了一万多张图只有这一张是这样的，我猜应该是预处理的pipeline有一些大分别率的edge cases没有考虑到。
