### ISSUE TITLE
paddledetection训练好faster RCNN后，使用命令行无法推理，使用pycharm run却可以

### ISSUE THREAD

**Issue by hrdwsong** [PaddlePaddle/PaddleDetection#3541]
您好！我使用paddledetection 2.1在自己的数据集上训练的faster RCNN，遇到以下问题：
1、训练完成后，在控制台中使用下面的命令运行预测函数，会报错。但将命令行参数写入到pycharm的RUN->edit configuration中，然后直接run，则运行OK；
```
python tools/infer.py -c configs/faster_rcnn/faster_rcnn_r50_vd_fpn_ssld_2x_kongtianbei_voc.yml  --infer_img=demo/004.bmp --output_dir=infer_output/ --draw_threshold=0.5 -o weights=output/faster_rcnn_r50_vd_fpn_ssld_2x_kongtianbei_voc/best_model --use_vdl=True

(paddle_gpu) F:\FormalDL\PaddleDetection>python tools/train.py -c configs/faster_rcnn/faster_rcnn_r50_vd_fpn_ssld_2x_kongtianbei_voc.yml --evalpython tools/infer.py -c configs/faster_rcnn/faster_rcnn_r50_vd_fpn_ssld_2x_kongtianbei_voc.
yml  --infer_img=demo/004.bmp --output_dir=infer_output/ --draw_threshold=0.5 -o weights=output/faster_rcnn_r50_vd_fpn_ssld_2x_kongtianbei_voc/best_model --use_vdl=Truepython tools/infer.py -c configs/faster_rcnn/faster_rcnn_r50_vd_fpn
_ssld_2x_kongtianbei_voc.yml  --infer_img=demo/004.bmp --output_dir=infer_output/ --draw_threshold=0.5 -o weights=output/faster_rcnn_r50_vd_fpn_ssld_2x_kongtianbei_voc/best_model --use_vdl=True
usage: train.py [-h] [-c CONFIG] [-o [OPT [OPT ...]]] [--eval] [-r RESUME]
                [--slim_config SLIM_CONFIG] [--enable_ce ENABLE_CE] [--fp16]
                [--fleet] [--use_vdl USE_VDL] [--vdl_log_dir VDL_LOG_DIR]
                [--save_prediction_only]
train.py: error: unrecognized arguments: --evalpython tools/infer.py --infer_img=demo/004.bmp --output_dir=infer_output/ --draw_threshold=0.5 tools/infer.py --infer_img=demo/004.bmp --output_dir=infer_output/ --draw_threshold=0.5

(paddle_gpu) F:\FormalDL\PaddleDetection>python tools/infer.py -c configs/faster_rcnn/faster_rcnn_r50_vd_fpn_ssld_2x_kongtianbei_voc.yml  --infer_img=demo/004.bmp --output_dir=infer_output/ --draw_threshold=0.5 -o weights=output/faster
_rcnn_r50_vd_fpn_ssld_2x_kongtianbei_voc/best_model --use_vdl=True
W0630 08:07:34.268959 27284 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.2
W0630 08:07:34.275939 27284 device_context.cc:422] device: 0, cuDNN Version: 8.1.
[06/30 08:07:40] ppdet.utils.checkpoint INFO: Finish loading model weights: output/faster_rcnn_r50_vd_fpn_ssld_2x_kongtianbei_voc/best_model.pdparams
Traceback (most recent call last):
  File "tools/infer.py", line 158, in <module>
    main()
  File "tools/infer.py", line 154, in main
    run(FLAGS, cfg)
  File "tools/infer.py", line 132, in run
    save_txt=FLAGS.save_txt)
  File "D:\ProgramData\Anaconda3\envs\paddle_gpu\lib\site-packages\ppdet\engine\trainer.py", line 396, in predict
    loader = create('TestReader')(self.dataset, 0)
  File "D:\ProgramData\Anaconda3\envs\paddle_gpu\lib\site-packages\ppdet\core\workspace.py", line 276, in create
    return cls(**cls_kwargs)
  File "D:\ProgramData\Anaconda3\envs\paddle_gpu\lib\site-packages\ppdet\data\reader.py", line 270, in __init__
    num_classes, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\paddle_gpu\lib\site-packages\ppdet\data\reader.py", line 151, in __init__
    collate_batch)
  File "D:\ProgramData\Anaconda3\envs\paddle_gpu\lib\site-packages\ppdet\data\reader.py", line 69, in __init__
    super(BatchCompose, self).__init__(transforms, num_classes)
  File "D:\ProgramData\Anaconda3\envs\paddle_gpu\lib\site-packages\ppdet\data\reader.py", line 47, in __init__
    f = op_cls(**v)
TypeError: __init__() got an unexpected keyword argument 'pad_gt'

(paddle_gpu) F:\FormalDL\PaddleDetection>
(paddle_gpu) F:\FormalDL\PaddleDetection>
```

2、将上述训练好的模型，导出后在另外的工程下调用。在win10 pycharm下运行良好，但将工程拷贝到linux环境中却会报错如下，报错信息中出现了windows路径。

```
", line 91, in _forward
      im_shape, scale_factor)
    File "D:\ProgramData\Anaconda3\envs\paddle_gpu\lib\site-packages\ppdet\modeling\post_process.py", line 120, in get_pred
      scaled_bbox = pred_bbox / scale_factor_list
    File "D:\ProgramData\Anaconda3\envs\paddle_gpu\lib\site-packages\paddle\fluid\layers\math_op_patch.py", line 305, in __impl__
      attrs={'axis': axis})
    File "D:\ProgramData\Anaconda3\envs\paddle_gpu\lib\site-packages\paddle\fluid\framework.py", line 3232, in append_op
      attrs=kwargs.get("attrs", None))
    File "D:\ProgramData\Anaconda3\envs\paddle_gpu\lib\site-packages\paddle\fluid\framework.py", line 2312, in __init__
      for frame in traceback.extract_stack():

    PreconditionNotMetError: The Tensor's element number must be equal or greater than zero. The Tensor's shape is [-1, 4] now
      [Hint: Expected numel() >= 0, but received numel():-4 < 0:0.] (at /paddle/paddle/fluid/framework/tensor.cc:59)
      [operator < elementwise_div > error]
```

3、上面两个问题只针对faster RCNN有报错，同样的流程对YOLOV3缺运行良好。

辛苦百度大佬看下，这可能是什么问题导致的？

**Comment by hrdwsong** [comment]
补充一下，faster RCNN训练也需要通过在pycharm中对RUN->edit configuration进行参数配置后执行训练。直接在命令行中敲入以下命令训练，还是会报错。
python tools/train.py -c configs/faster_rcnn/faster_rcnn_r50_vd_fpn_ssld_2x_kongtianbei_voc.yml -r output/faster_rcnn_r50_vd_fpn_ssld_2x_kongtianbei_voc/11

**Comment by hrdwsong** [comment]
问题2的完整报错LOG如下，这是在linux系统下的结果：

```
home/aistudio/data/kongtianbei_code
-----------  Model Configuration -----------
Model Arch: RCNN
Transform Order: 
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--transform op: PadStride
--------------------------------------------
I0630 09:23:56.480343   350 analysis_config.cc:424] use_dlnne_:0
I0630 09:23:56.480427   350 analysis_config.cc:424] use_dlnne_:0
I0630 09:23:56.480453   350 analysis_config.cc:424] use_dlnne_:0
I0630 09:23:56.480466   350 analysis_config.cc:424] use_dlnne_:0
Traceback (most recent call last):
  File "main.py", line 148, in <module>
    main(args)
  File "main.py", line 58, in main
    outputs = deepsort.update(frame)
  File "/home/aistudio/data/kongtianbei_code/deepsort.py", line 68, in update
    self.threshold
  File "/home/aistudio/data/kongtianbei_code/model/detection.py", line 132, in predict
    self.predictor.run()
RuntimeError: In user code:

    File "tools/export_model.py", line 105, in <module>
      main()
    File "tools/export_model.py", line 101, in main
      run(FLAGS, cfg)
    File "tools/export_model.py", line 69, in run
      trainer.export(FLAGS.output_dir)
    File "D:\ProgramData\Anaconda3\envs\paddle_gpu\lib\site-packages\ppdet\engine\trainer.py", line 507, in export
      input_spec, static_model.forward.main_program,
    File "D:\ProgramData\Anaconda3\envs\paddle_gpu\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 534, in main_program
      concrete_program = self.concrete_program
    File "D:\ProgramData\Anaconda3\envs\paddle_gpu\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 454, in concrete_program
      return self.concrete_program_specify_input_spec(input_spec=None)
    File "D:\ProgramData\Anaconda3\envs\paddle_gpu\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 488, in concrete_program_specify_input_spec
      *desired_input_spec)
    File "D:\ProgramData\Anaconda3\envs\paddle_gpu\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 402, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "D:\ProgramData\Anaconda3\envs\paddle_gpu\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 711, in __getitem__
      self._caches[item] = self._build_once(item)
    File "D:\ProgramData\Anaconda3\envs\paddle_gpu\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 702, in _build_once
      class_instance=cache_key.class_instance)
    File "<decorator-gen-65>", line 2, in from_func_spec
      
    File "D:\ProgramData\Anaconda3\envs\paddle_gpu\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "D:\ProgramData\Anaconda3\envs\paddle_gpu\lib\site-packages\paddle\fluid\dygraph\base.py", line 40, in __impl__
      return func(*args, **kwargs)
    File "D:\ProgramData\Anaconda3\envs\paddle_gpu\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 652, in from_func_spec
      outputs = static_func(*inputs)
    File "C:\Users\ADMINI~1\AppData\Local\Temp\tmpo8um6t_u.py", line 27, in forward
      false_fn_1, (), (), (out,))
    File "D:\ProgramData\Anaconda3\envs\paddle_gpu\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "D:\ProgramData\Anaconda3\envs\paddle_gpu\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "D:\ProgramData\Anaconda3\envs\paddle_gpu\lib\site-packages\ppdet\modeling\architectures\meta_arch.py", line 29, in forward
      out = self.get_pred()
    File "D:\ProgramData\Anaconda3\envs\paddle_gpu\lib\site-packages\ppdet\modeling\architectures\faster_rcnn.py", line 104, in get_pred
      bbox_pred, bbox_num = self._forward()
    File "C:\Users\ADMINI~1\AppData\Local\Temp\tmpfazspkn2.py", line 54, in _forward
      rois, rois_num))
    File "D:\ProgramData\Anaconda3\envs\paddle_gpu\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "D:\ProgramData\Anaconda3\envs\paddle_gpu\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "D:\ProgramData\Anaconda3\envs\paddle_gpu\lib\site-packages\ppdet\modeling\architectures\faster_rcnn.py", line 91, in _forward
      im_shape, scale_factor)
    File "D:\ProgramData\Anaconda3\envs\paddle_gpu\lib\site-packages\ppdet\modeling\post_process.py", line 120, in get_pred
      scaled_bbox = pred_bbox / scale_factor_list
    File "D:\ProgramData\Anaconda3\envs\paddle_gpu\lib\site-packages\paddle\fluid\layers\math_op_patch.py", line 305, in __impl__
      attrs={'axis': axis})
    File "D:\ProgramData\Anaconda3\envs\paddle_gpu\lib\site-packages\paddle\fluid\framework.py", line 3232, in append_op
      attrs=kwargs.get("attrs", None))
    File "D:\ProgramData\Anaconda3\envs\paddle_gpu\lib\site-packages\paddle\fluid\framework.py", line 2312, in __init__
      for frame in traceback.extract_stack():

    PreconditionNotMetError: The Tensor's element number must be equal or greater than zero. The Tensor's shape is [-1, 4] now
      [Hint: Expected numel() >= 0, but received numel():-4 < 0:0.] (at /paddle/paddle/fluid/framework/tensor.cc:59)
      [operator < elementwise_div > error]

```

**Comment by liuhuiCNN** [comment]
（1）问题1，release2.1中将pad_gt参数去掉了，您可以参考下release2.1的配置文件。
（2）请问使用的Paddle是release2.1.0吗？请使用Paddle release2.1试下。

**Comment by hrdwsong** [comment]
我的paddlepaddle和paddledetection都用的是2.1版本的。如果按您说的pad _gt参数去掉了，这个报错就很奇怪

**Comment by liuhuiCNN** [comment]
> pad _gt参

去掉后还报错吗？

**Comment by hrdwsong** [comment]
手动删掉faster_fpn_reader.py中的pad_gt: true后，不报错了。这就引出个问题，之前为啥在pycharm中直接run没问题，命令行却有问题。这两个应该没有差异呀。

另外，关于问题2，目前尚未有解决思路。

**Comment by liuhuiCNN** [comment]
> 手动删掉faster_fpn_reader.py中的pad_gt: true后，不报错了。这就引出个问题，之前为啥在pycharm中直接run没问题，命令行却有问题。这两个应该没有差异呀。
> 
> 另外，关于问题2，目前尚未有解决思路。

请确认两个环境下代码是否完全一样？以及paddle版本 ppdet版本是否完全一致？按照正常情况，不应该出现这种情况的。

**Comment by hrdwsong** [comment]
两个环境的代码确认完全一样的。paddle版本不一样，windows使用的是paddlepaddle-gpu==2.1.0.post112，linux由于CUDA版本是10.1，所以安装的是paddlepaddle-gpu==2.1.0.post101。我把同样的工程放到aistudio上运行，也会报相同的错，我理解应该是工程代码问题。
下面这几行尤其不能理解：在调用faster RCNN模型的预测函数时，会出现运行时错误，指示调用了tools/export_model.py文件，执行推理过程为何调用这个文件？以及为何这个文件会响应的调用windows路径库文件？

```
File "main.py", line 148, in
main(args)
File "main.py", line 58, in main
outputs = deepsort.update(frame)
File "/home/aistudio/data/kongtianbei_code/deepsort.py", line 68, in update
self.threshold
File "/home/aistudio/data/kongtianbei_code/model/detection.py", line 132, in predict
self.predictor.run()
RuntimeError: In user code:

File "tools/export_model.py", line 105, in <module>
  main()
File "tools/export_model.py", line 101, in main
  run(FLAGS, cfg)
File "tools/export_model.py", line 69, in run
  trainer.export(FLAGS.output_dir)
File "D:\ProgramData\Anaconda3\envs\paddle_gpu\lib\site-packages\ppdet\engine\trainer.py", line 507, in export
  input_spec, static_model.forward.main_program,
```

**Comment by hrdwsong** [comment]
我分析是self.predictor.run()函数调用了我在windows下的库，所以在windows下能够顺利执行，而linux下会报运行时错误，但单步调试无法跟踪到该函数的子操作。

**Comment by hrdwsong** [comment]
我的paddledetection是2.0版本的，按github上的命令拉取的版本，默认拉取的是2.0不是2.1。这个问题请修正。
现在准备更新2.1后，重新在windows上训练，看是否出现问题（2）

**Comment by hrdwsong** [comment]
重新训练后仍然出现问题，问题似乎是使用export.py导出模型后，inference阶段执行predictor.run()时出的问题。问题只发生在linux上（aistudio和我的linux虚拟机都复现）。目前实在没有思路了，看上去像是paddledetection的bug，因为yolo_v3没有问题，其他yam文件配置除了训练数据外，其他都没有变过。

**Comment by liuhuiCNN** [comment]
> 重新训练后仍然出现问题，问题似乎是使用export.py导出模型后，inference阶段执行predictor.run()时出的问题。问题只发生在linux上（aistudio和我的linux虚拟机都复现）。目前实在没有思路了，看上去像是paddledetection的bug，因为yolo_v3没有问题，其他yam文件配置除了训练数据外，其他都没有变过。

建议用最新的paddle==2.1.0 + 最新的 ppdet develop
