### ISSUE TITLE
使用YOLOV3模型如何通过yml文件修改输入图片尺寸

### ISSUE THREAD

**Issue by ximitiejiang** [PaddlePaddle/PaddleDetection#3552]
你好，现在yolov3输入图片尺寸通常是608/416或者更小，为了让yolov3能够检测更小的目标，我希望输入1k的图片作为训练图片，比如1280x1280，通常情况我是不是通过修改yml文件就可以实现这个需求？
比如下面这种修改是否可行：
```
_BASE_: [
  '../configs/datasets/coco_detection.yml',
  '../configs/runtime.yml',
  '../configs/yolov3/_base_/optimizer_270e.yml',
  '../configs/yolov3/_base_/yolov3_darknet53.yml',
  '../configs/yolov3/_base_/yolov3_reader.yml',
]
weights: /home/suliang/suliang_git/PaddleDetection-release-2.1/sl_package/output/sl_package_yolov3_darknet53_270e_coco/model_final.pdparams

num_classes: 6
TrainDataset:
  !COCODataSet
    image_dir: train
    anno_path: annotations/instance_train.json
    dataset_dir: ../dataset/Package_local/coco_format
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val
    anno_path: annotations/instance_val.json
    dataset_dir: ../dataset/Package_local/coco_format
TestDataset:
  !ImageFolder
    anno_path: ../dataset/Package_local/coco_format/annotations/instance_val.json

worker_num: 2
TrainReader:
  # 由于图片大小加倍了，这里batch size改为4，因为原来608尺寸的在batchsize=8时已经接近11G显存占用
  batch_size: 4
  # 加大输入图像尺寸：随机图像尺寸需要是32的倍数，所有608都改为1280
  batch_transforms:
    - BatchRandomResize: {target_size: [992, 1024, 1056, 1088, 1120, 1152, 1184, 1216, 1248, 1280], random_size: True, random_interp: True, keep_ratio: False}
EvalReader:
  sample_transforms:
    - Resize: {target_size: [1280, 1280], keep_ratio: False, interp: 2}
TestReader:
  inputs_def:
    image_shape: [3, 1280, 1280]
  sample_transforms:
    - Resize: {target_size: [1280, 1280], keep_ratio: False, interp: 2}

LearningRate:
  # from 0.01 to 0.01/8
  base_lr: 0.00125
```

初次尝试发现报错
```
ERROR:root:DataLoader reader thread raised an exception!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 411, in _thread_loop
    batch = self._get_data()
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 525, in _get_data
    batch.reraise()
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 168, in reraise
    raise self.exc_type(msg)
ValueError: DataLoader worker(0) caught ValueError with message:
Traceback (most recent call last):
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 228, in _worker_loop
    batch = fetcher.fetch(indices)
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 66, in fetch
    data = self.collate_fn(data)
  File "/home/suliang/suliang_git/PaddleDetection-release-2.1/ppdet/data/reader.py", line 93, in __call__
    batch_data = default_collate_fn(data)
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 70, in default_collate_fn
    for key in sample
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 70, in <dictcomp>
    for key in sample
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 58, in default_collate_fn
    batch = np.stack(batch, axis=0)
  File "<__array_function__ internals>", line 6, in stack
  File "/home/suliang/anaconda3/envs/paddle_env/lib/python3.7/site-packages/numpy/core/shape_base.py", line 427, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape
```
关于这种需求，有什么建议吗？

**Comment by liuhuiCNN** [comment]
你好，配置文件看起来没问题的。（1）首先先用原来的配置文件，看是否能够正常训练；（2）然后再改配置文件，开始可以将尺寸改小点试试。
