### ISSUE TITLE
训练ppyolo_tiny模型时报错

### ISSUE THREAD

**Issue by chenxuezhao** [PaddlePaddle/PaddleDetection#3562]
执行如下命令时报错：`python3 -m paddle.distributed.launch --log_dir=./ppyolo_dygraph/  tools/train.py -c configs/ppyolo/ppyolo_tiny_650e_coco.yml --use_gpu=False`

> /home/chenzhao/Anconda3/envs/paddle2.x/lib/python3.8/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
-----------  Configuration Arguments -----------
gpus: None
heter_worker_num: None
heter_workers: 
http_port: None
ips: 127.0.0.1
log_dir: ./ppyolo_dygraph/
nproc_per_node: None
server_num: None
servers: 
training_script: tools/train.py
training_script_args: ['-c', 'configs/ppyolo/ppyolo_tiny_650e_coco.yml', '--use_gpu=False']
worker_num: None
workers: 
-*--------------------------------------*-
WARING 2021-07-01 15:31:58,373 launch.py:310] Not found distinct arguments and not compiled with cuda. Default use ps mode
Traceback (most recent call last):
  File "/home/chenzhao/Anconda3/envs/paddle2.x/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/chenzhao/Anconda3/envs/paddle2.x/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/chenzhao/Anconda3/envs/paddle2.x/lib/python3.8/site-packages/paddle/distributed/launch.py", line 16, in <module>
    launch.launch()
  File "/home/chenzhao/Anconda3/envs/paddle2.x/lib/python3.8/site-packages/paddle/distributed/fleet/launch.py", line 330, in launch
    launch_ps(args, distribute_mode)
  File "/home/chenzhao/Anconda3/envs/paddle2.x/lib/python3.8/site-packages/paddle/distributed/fleet/launch.py", line 263, in launch_ps
    ps_launcher = ParameterServerLauncher(args, distribute_mode)
  File "/home/chenzhao/Anconda3/envs/paddle2.x/lib/python3.8/site-packages/paddle/distributed/fleet/launch_utils.py", line 716, in __init__
    self.get_role_endpoints(args)
  File "/home/chenzhao/Anconda3/envs/paddle2.x/lib/python3.8/site-packages/paddle/distributed/fleet/launch_utils.py", line 733, in get_role_endpoints
    assert args.servers != "", "The setting of Parameter-Server must has server_num or servers."
AssertionError: The setting of Parameter-Server must has server_num or servers.

**Comment by wangxinxin08** [comment]
单卡训练或者不使用GPU训练直接运行`python3 tools/train.py -c configs/ppyolo/ppyolo_tiny_650e_coco.yml --use_gpu=False`

**Comment by chenxuezhao** [comment]
ok,谢谢

**Comment by chenxuezhao** [comment]
你好，训练的时候有个警告：
`WARNING: Detect dataset only contains single fileds, return format changed since Paddle 2.1. In Paddle <= 2.0, DataLoader add a list surround output data(e.g. return [data]), and in Paddle >= 2.1, DataLoader return the single filed directly (e.g. return data). `
请问这会对训练结果造成影响吗？

**Comment by wangxinxin08** [comment]
没有影响
