### ISSUE TITLE
蒸馏剪裁模型

### ISSUE THREAD

**Issue by pele228** [PaddlePaddle/PaddleDetection#357]
如何用自己的数据集蒸馏剪裁模型？
按照文档步骤https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/slim/extensions/distill_pruned_model/README.md

aistudio@jupyter-135123-311635:~/work/PaddleDetection/slim/extensions/distill_pruned_model$ python distill_pruned_model.py -c ../../../configs/yolov3_mobilenet_v1_voc_mydata.yml -t ../../../configs/yolov3_r34_voc_mydata.yml --teacher_pretrained=https://paddlemodels.bj.bcebos.com/object_detection/yolov3_r34_voc.tar --pruned_params "yolo_block.0.0.0.conv.weights,yolo_block.0.0.1.conv.weights,yolo_block.0.1.0.conv.weights" --pruned_ratios="0.2,0.3,0.4" -o use_fine_grained_loss=true pretrain_weights=https://paddlemodels.bj.bcebos.com/object_detection/yolov3_mobilenet_v1_voc.tar
2020-03-19 15:36:27,347-INFO: Config dataset_dir dataset/mydata is not exits, dataset config is not valid
2020-03-19 15:36:27,347-INFO: Dataset /home/aistudio/work/PaddleDetection/slim/extensions/distill_pruned_model/dataset/mydata is not valid for reason above, try searching /home/aistudio/.cache/paddle/dataset or downloading dataset...
Traceback (most recent call last):
  File "distill_pruned_model.py", line 365, in <module>
    main()
  File "distill_pruned_model.py", line 149, in main
    devices_num, cfg)
  File "/home/aistudio/work/PaddleDetection/ppdet/data/reader.py", line 406, in create_reader
    reader = Reader(**cfg)()
  File "/home/aistudio/work/PaddleDetection/ppdet/data/reader.py", line 202, in __init__
    self._roidbs = self._dataset.get_roidb()
  File "/home/aistudio/work/PaddleDetection/ppdet/data/source/dataset.py", line 65, in get_roidb
    self.image_dir)
  File "/home/aistudio/work/PaddleDetection/ppdet/utils/download.py", line 145, in get_dataset_path
    format(path, osp.split(path)[-1]))
ValueError: Dataset dataset/mydata is not valid and cannot parse dataset type 'mydata' for automaticly downloading, which only supports 'voc' , 'coco', 'wider_face' and 'fruit' currently

**Comment by FDInSky** [comment]
应该是你的数据集配置有问题，参考https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.2/docs/advanced_tutorials/READER.md检查一下你的数据集配置

**Comment by pele228** [comment]
@FDInSky  是文件配置路径的问题。
