### ISSUE TITLE
按照教程部署到最后一步接口调用出错

### ISSUE THREAD

**Issue by learningpro** [PaddlePaddle/PaddleDetection#3581]
**复现步骤：**

参考官方说明 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/deploy/serving  进行服务端预测部署
从第一步到第三步都顺利通过
第四步的时候gpu版本不能用，遂选择cpu版本

```
λ  /code/PaddleDetection/output_inference/yolov3_darknet53_270e_coco {release/2.1} python3 -m paddle_serving_server_gpu.serve --model serving_server --port 9393 --gpu_ids 0
/usr/bin/python3: Error while finding module specification for 'paddle_serving_server_gpu.serve' (ModuleNotFoundError: No module named 'paddle_serving_server_gpu')

```

使用的是dockerhub上的 paddlepaddle/paddle:2.1.1-gpu-cuda11.2-cudnn8  镜像，按照https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md 快速体验最后的图片能用GPU跑出正确结果
```

/code/PaddleDetection/output_inference/yolov3_darknet53_270e_coco {release/2.1} pip list | grep paddle
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
paddle-serving-app        0.6.2
paddle-serving-client     0.6.2
paddle-serving-server     0.6.2
paddle-serving-server-gpu 0.6.2.post102
paddledet                 2.1.0
paddlepaddle-gpu          2.1.1.post112

Python 3.7.10 (default, May  3 2021, 02:48:31)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ...
W0703 10:54:09.146241  2189 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.2, Runtime API Version: 11.2
W0703 10:54:09.149813  2189 device_context.cc:422] device: 0, cuDNN Version: 8.1.
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
>>> paddle.__version__
'2.1.1'
>>>

```

**出现问题：**
接着按照教程进行到第五步，test_client.py第36行将  im_size 改为 im_shape 才能顺利跑起来，最终报错如下
因都是官方源码，99.9%都是未修改的，一时不知如何排查问题，望指点 ❤

```

λ  /code/PaddleDetection/output_inference/yolov3_darknet53_270e_coco {release/2.1} python -m paddle_serving_server.serve --model serving_server --port 9393
/usr/lib/python3.7/runpy.py:125: RuntimeWarning: 'paddle_serving_server.serve' found in sys.modules after import of package 'paddle_serving_server', but prior to execution of 'paddle_serving_server.serve'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
gpu_ids not set, going to run cpu service.
Going to Run Comand
/usr/local/lib/python3.7/dist-packages/paddle_serving_server/serving-cpu-avx-mkl-0.6.2/serving -enable_model_toolkit -inferservice_path workdir -inferservice_file infer_service.prototxt -max_concurrency 0 -num_threads 2 -port 9393 -precision fp32 -use_calib False -reload_interval_s 10 -resource_path workdir -resource_file resource.prototxt -workflow_path workdir -workflow_file workflow.prototxt -bthread_concurrency 2 -max_body_size 536870912
I0100 00:00:00.000000  2106 op_repository.h:68] RAW: Succ regist op: GeneralCopyOp
I0100 00:00:00.000000  2106 op_repository.h:68] RAW: Succ regist op: GeneralDistKVInferOp
I0100 00:00:00.000000  2106 op_repository.h:68] RAW: Succ regist op: GeneralDistKVQuantInferOp
I0100 00:00:00.000000  2106 op_repository.h:68] RAW: Succ regist op: GeneralInferOp
I0100 00:00:00.000000  2106 op_repository.h:68] RAW: Succ regist op: GeneralReaderOp
I0100 00:00:00.000000  2106 op_repository.h:68] RAW: Succ regist op: GeneralResponseOp
I0100 00:00:00.000000  2106 op_repository.h:68] RAW: Succ regist op: GeneralTextReaderOp
I0100 00:00:00.000000  2106 op_repository.h:68] RAW: Succ regist op: GeneralTextResponseOp
I0100 00:00:00.000000  2106 service_manager.h:79] RAW: Service[LoadGeneralModelService] insert successfully!
I0100 00:00:00.000000  2106 load_general_model_service.pb.h:333] RAW: Success regist service[LoadGeneralModelService][PN5baidu14paddle_serving9predictor26load_general_model_service27LoadGeneralModelServiceImplE]
I0100 00:00:00.000000  2106 service_manager.h:79] RAW: Service[GeneralModelService] insert successfully!
I0100 00:00:00.000000  2106 general_model_service.pb.h:1507] RAW: Success regist service[GeneralModelService][PN5baidu14paddle_serving9predictor13general_model23GeneralModelServiceImplE]
I0100 00:00:00.000000  2106 factory.h:155] RAW: Succ insert one factory, tag: PADDLE_INFER, base type N5baidu14paddle_serving9predictor11InferEngineE
W0100 00:00:00.000000  2106 paddle_engine.cpp:29] RAW: Succ regist factory: ::baidu::paddle_serving::predictor::FluidInferEngine<PaddleInferenceEngine>->::baidu::paddle_serving::predictor::InferEngine, tag: PADDLE_INFER in macro!
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
--- Running analysis [ir_graph_to_program_pass]
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():

  Compile Traceback (most recent call last):
    File "tools/export_model.py", line 105, in <module>
      main()
    File "tools/export_model.py", line 101, in main
      run(FLAGS, cfg)
    File "tools/export_model.py", line 69, in run
      trainer.export(FLAGS.output_dir)
    File "/usr/local/lib/python3.7/dist-packages/ppdet/engine/trainer.py", line 507, in export
      input_spec, static_model.forward.main_program,
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 534, in main_program
      concrete_program = self.concrete_program
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 454, in concrete_program
      return self.concrete_program_specify_input_spec(input_spec=None)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program_specify_input_spec
      *desired_input_spec)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 702, in _build_once
      class_instance=cache_key.class_instance)
    File "<decorator-gen-65>", line 2, in from_func_spec

    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 652, in from_func_spec
      outputs = static_func(*inputs)
    File "/tmp/tmpmp716jh6.py", line 27, in forward
      false_fn_1, (), (), (out,))
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/usr/local/lib/python3.7/dist-packages/ppdet/modeling/architectures/meta_arch.py", line 29, in forward
      out = self.get_pred()
    File "/usr/local/lib/python3.7/dist-packages/ppdet/modeling/architectures/yolo.py", line 104, in get_pred
      return self._forward()
    File "/tmp/tmpls9gf_44.py", line 80, in _forward
      __return_value_0, neck_feats, self), (__return_value_0,))
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/tmp/tmpls9gf_44.py", line 73, in false_fn_5
      yolo_head_outs), (bbox, bbox_num, output))
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/usr/local/lib/python3.7/dist-packages/ppdet/modeling/architectures/yolo.py", line 95, in _forward
      self.inputs['im_shape'], self.inputs['scale_factor'])
    File "/tmp/tmpzyb0r88h.py", line 38, in __call__
      bbox_num, bbox_pred))
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/usr/local/lib/python3.7/dist-packages/ppdet/modeling/post_process.py", line 65, in __call__
      bboxes, score = self.decode(head_out, rois, im_shape, scale_factor)
    File "/usr/local/lib/python3.7/dist-packages/ppdet/modeling/layers.py", line 488, in __call__
      origin_shape = im_shape / scale_factor
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/math_op_patch.py", line 305, in __impl__
      attrs={'axis': axis})
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 2905, in append_op
      attrs=kwargs.get("attrs", None))
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 1977, in __init__
      for frame in traceback.extract_stack():

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
```

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The Tensor in the elementwise_div Op's Input Variable Y(scale_factor) is not initialized.
  [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at /paddle/paddle/fluid/framework/operator.cc:1644)
  [operator < elementwise_div > error]
Aborted

**Comment by liuhuiCNN** [comment]
如果镜像CUDA是11.2，您安装的paddle-serving-server-gpu是10.2的，请问这个是否正常？建议您paddle，paddledetection，paddleserving的CUDA先保持一致。

**Comment by learningpro** [comment]
> 如果镜像CUDA是11.2，您安装的paddle-serving-server-gpu是10.2的，请问这个是否正常？建议您paddle，paddledetection，paddleserving的CUDA先保持一致。

感谢回复，我看https://github.com/PaddlePaddle/Serving/blob/develop/README_CN.md 这里并没有cuda11的对应版本paddle serving gpu，可能不能直接pip install了，我再试试这个  https://github.com/PaddlePaddle/Serving/blob/develop/doc/LATEST_PACKAGES.md

**Comment by learningpro** [comment]
> 如果镜像CUDA是11.2，您安装的paddle-serving-server-gpu是10.2的，请问这个是否正常？建议您paddle，paddledetection，paddleserving的CUDA先保持一致。

卸载了旧版本paddle-serving-*之后，用最新的whl包安装了一遍，同样的问题，gpu版本提示找不到Module

```
/code/PaddleDetection/output_inference/yolov3_darknet53_270e_coco {release/2.1} python -m paddle_serving_server_gpu.serve --model serving_server --port 9393 --gpu_ids 0
/usr/bin/python: Error while finding module specification for 'paddle_serving_server_gpu.serve' (ModuleNotFoundError: No module named 'paddle_serving_server_gpu')
```
检查了一下各个包都安装成功了
```
 /code/PaddleDetection/output_inference/yolov3_darknet53_270e_coco {release/2.1} pip list | grep paddle
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
paddle-serving-app        0.0.0
paddle-serving-client     0.0.0
paddle-serving-server-gpu 0.0.0.post11
paddledet                 2.1.0
paddlepaddle-gpu          2.1.1.post112
```

于是执行了一下CPU版
有趣的是他下载了gpu的压缩包，但是报错了
 ```
/code/PaddleDetection/output_inference/yolov3_darknet53_270e_coco {release/2.1} python -m paddle_serving_server.serve --model serving_server --port 9393
/usr/lib/python3.7/runpy.py:125: RuntimeWarning: 'paddle_serving_server.serve' found in sys.modules after import of package 'paddle_serving_server', but prior to execution of 'paddle_serving_server.serve'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
gpu_ids not set, going to run cpu service.
Frist time run, downloading PaddleServing components ...
--2021-07-05 15:11:12--  https://paddle-serving.bj.bcebos.com/test-dev/bin/serving-gpu-cuda11-0.0.0.tar.gz
Resolving paddle-serving.bj.bcebos.com (paddle-serving.bj.bcebos.com)... 220.181.33.43, 220.181.33.44, 2409:8c04:1001:1002:0:ff:b001:368a, ...
Connecting to paddle-serving.bj.bcebos.com (paddle-serving.bj.bcebos.com)|220.181.33.43|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 563699214 (538M) [application/octet-stream]
Saving to: ‘serving-gpu-cuda11-0.0.0.tar.gz’

serving-gpu-cuda11-0.0.0.tar.gz           100%[===================================================================================>] 537.58M  82.7MB/s    in 7.9s

2021-07-05 15:11:21 (68.2 MB/s) - ‘serving-gpu-cuda11-0.0.0.tar.gz’ saved [563699214/563699214]

Decompressing files ..
Going to Run Comand
/usr/local/lib/python3.7/dist-packages/paddle_serving_server/serving-gpu-cuda11-0.0.0/serving -enable_model_toolkit -inferservice_path workdir_9393 -inferservice_file infer_service.prototxt -max_concurrency 0 -num_threads 2 -port 9393 -precision fp32 -use_calib False -reload_interval_s 10 -resource_path workdir_9393 -resource_file resource.prototxt -workflow_path workdir_9393 -workflow_file workflow.prototxt -bthread_concurrency 2 -max_body_size 536870912
/usr/local/lib/python3.7/dist-packages/paddle_serving_server/serving-gpu-cuda11-0.0.0/serving: error while loading shared libraries: libnvrtc.so.11.1: cannot open shared object file: No such file or directory
```

于是找了一下这个丢失的so文件相关的文件名

```
/code/PaddleDetection/output_inference/yolov3_darknet53_270e_coco {release/2.1} cd /usr/
/usr find . -name "libnvrtc.so.*"
./lib/pkgconfig/lib64/nvrtc-prev/libnvrtc.so.11.2.142
./lib/pkgconfig/lib64/nvrtc-prev/libnvrtc.so.11.2
./lib/pkgconfig/lib64/libnvrtc.so.11.2.142
./lib/pkgconfig/lib64/libnvrtc.so.11.2
./local/cuda-11.2/targets/x86_64-linux/lib/nvrtc-prev/libnvrtc.so.11.2.142
./local/cuda-11.2/targets/x86_64-linux/lib/nvrtc-prev/libnvrtc.so.11.2
./local/cuda-11.2/targets/x86_64-linux/lib/libnvrtc.so.11.2.142
./local/cuda-11.2/targets/x86_64-linux/lib/libnvrtc.so.11.2
```

发现他需要的是11.1，但是这个CUDA11.2版本的docker里只有11.2的，在docker hub 页面https://hub.docker.com/r/paddlepaddle/paddle/tags?page=1&ordering=last_updated 并没有11.1

请教一下这种情况应该怎么办呢，如果把现有的libnvrtc.so.11.2 软连接为 11.1，依然会报错，不能这么改

```
/usr/local/lib/python3.7/dist-packages/paddle_serving_server/serving-gpu-cuda11-0.0.0/serving: /usr/local/cuda-11.2/targets/x86_64-linux/lib/libnvrtc.so.11.1: version `libnvrtc.so.11.1' not found (required by /usr/lib/libnvinfer.so.7)
/usr/local/lib/python3.7/dist-packages/paddle_serving_server/serving-gpu-cuda11-0.0.0/serving: /usr/local/cuda-11.2/targets/x86_64-linux/lib/libnvrtc.so.11.1: version `libnvrtc.so.11.1' not found (required by /usr/lib/libnvinfer_plugin.so.7)
/usr/local/lib/python3.7/dist-packages/paddle_serving_server/serving-gpu-cuda11-0.0.0/serving: /usr/local/cuda-11.2/targets/x86_64-linux/lib/libnvrtc.so.11.1: version `libnvrtc.so.11.1' not found (required by /usr/lib/libmyelin.so.1)
```

求助 💖

**Comment by learningpro** [comment]
求助，any idea？

**Comment by liuhuiCNN** [comment]
为了较方便解决环境问题，建议使用docker，https://github.com/PaddlePaddle/Serving/blob/develop/README.md#installation

**Comment by learningpro** [comment]
> 为了较方便解决环境问题，建议使用docker，https://github.com/PaddlePaddle/Serving/blob/develop/README.md#installation

of course in docker, please see the first post 
使用的是dockerhub上的 paddlepaddle/paddle:2.1.1-gpu-cuda11.2-cudnn8 镜像

**Comment by liuhuiCNN** [comment]
> > 为了较方便解决环境问题，建议使用docker，https://github.com/PaddlePaddle/Serving/blob/develop/README.md#installation
> 
> of course in docker, please see the first post
> 使用的是dockerhub上的 paddlepaddle/paddle:2.1.1-gpu-cuda11.2-cudnn8 镜像

建议使用PaddleServing的docker：
`nvidia-docker pull registry.baidubce.com/paddlepaddle/serving:0.6.0-cuda10.2-cudnn8-devel`
文档可以参考：https://github.com/PaddlePaddle/Serving/blob/v0.6.0/README.md#installation
