### ISSUE TITLE
训练前出现的问题： cv2.error:  error: (-215:Assertion failed) !buf.empty() in function 'imdecode_'    下面是完整的报错信息

### ISSUE THREAD

**Issue by LiangYong1216** [PaddlePaddle/PaddleDetection#3583]
(PP-YOLO) wtc@wtc-All-Series:~/PaddleDetection$ python tools/train.py -c configs/ppyolo/ppyolo_r50vd_dcn_voc.yml

```
/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
W0705 08:58:19.027431  2517 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.0, Runtime API Version: 11.0
/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/ppdet/data/reader.py:59: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn("fail to map sample transform [{}] "
[07/05 08:58:19] reader WARNING: fail to map sample transform [Decode_a6ac4f] with error: OpenCV(3.4.14) /tmp/pip-req-build-m7h7rfem/opencv/modules/imgcodecs/src/loadsave.cpp:756: error: (-215:Assertion failed) !buf.empty() in function 'imdecode_'
 and stack:
Traceback (most recent call last):
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/ppdet/data/reader.py", line 56, in __call__
    data = f(data)
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/ppdet/data/transform/operators.py", line 99, in __call__
    sample[i] = self.apply(sample[i], context)
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/ppdet/data/transform/operators.py", line 126, in apply
    im = cv2.imdecode(data, 1)  # BGR mode, but need RGB mode
cv2.error: OpenCV(3.4.14) /tmp/pip-req-build-m7h7rfem/opencv/modules/imgcodecs/src/loadsave.cpp:756: error: (-215:Assertion failed) !buf.empty() in function 'imdecode_'


WARNING:root:DataLoader reader thread raised an exception.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 199, in _thread_loop
    six.reraise(*sys.exc_info())
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 167, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices)
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/paddle/fluid/dataloader/fetcher.py", line 99, in fetch
    data = [self.dataset[idx] for idx in batch_indices]
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/paddle/fluid/dataloader/fetcher.py", line 99, in <listcomp>
    data = [self.dataset[idx] for idx in batch_indices]
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/ppdet/data/source/dataset.py", line 87, in __getitem__
    return self.transform(roidb)
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/ppdet/data/reader.py", line 62, in __call__
    raise e
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/ppdet/data/reader.py", line 56, in __call__
    data = f(data)
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/ppdet/data/transform/operators.py", line 99, in __call__
    sample[i] = self.apply(sample[i], context)
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/ppdet/data/transform/operators.py", line 126, in apply
    im = cv2.imdecode(data, 1)  # BGR mode, but need RGB mode
cv2.error: OpenCV(3.4.14) /tmp/pip-req-build-m7h7rfem/opencv/modules/imgcodecs/src/loadsave.cpp:756: error: (-215:Assertion failed) !buf.empty() in function 'imdecode_'

W0705 08:58:19.052762  2517 device_context.cc:422] device: 0, cuDNN Version: 8.1.
Traceback (most recent call last):
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='paddledet.bj.bcebos.com', port=443): Max retries exceeded with url: /models/pretrained/ResNet50_vd_ssld_pretrained.pdparams (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 108, in run
    trainer.load_weights(cfg.pretrain_weights)
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/ppdet/engine/trainer.py", line 234, in load_weights
    load_pretrain_weight(self.model, weights)
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/ppdet/utils/checkpoint.py", line 146, in load_pretrain_weight
    pretrain_weight = get_weights_path_dist(pretrain_weight)
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/ppdet/utils/checkpoint.py", line 89, in get_weights_path_dist
    path = get_weights_path(path)
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/ppdet/utils/download.py", line 112, in get_weights_path
    path, _ = get_path(url, WEIGHTS_HOME)
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/ppdet/utils/download.py", line 276, in get_path
    _check_exist_file_md5(fullpath, md5sum, url):
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/ppdet/utils/download.py", line 386, in _check_exist_file_md5
    return _md5check_from_url(filename, url) if md5sum is None \
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/ppdet/utils/download.py", line 394, in _md5check_from_url
    req = requests.get(url, stream=True)
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='paddledet.bj.bcebos.com', port=443): Max retries exceeded with url: /models/pretrained/ResNet50_vd_ssld_pretrained.pdparams (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')))
```

我的环境：paddlepaddle-gpu    2.1.1.post110         cuda 11.0   
我需要怎么处理？新手还请多多指教，感谢

**Comment by qingqing01** [comment]
@LiangYong1216 像是图片读取不正确，您可以在这里检查下输入图片:

```
  File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/ppdet/data/transform/operators.py", line 126, in apply
    im = cv2.imdecode(data, 1)  # BGR mode, but need RGB mode
```

**Comment by LiangYong1216** [comment]
> @LiangYong1216 像是图片读取不正确，您可以在这里检查下输入图片:
> 
> ```
>   File "/home/wtc/anaconda3/envs/PP-YOLO/lib/python3.8/site-packages/ppdet/data/transform/operators.py", line 126, in apply
>     im = cv2.imdecode(data, 1)  # BGR mode, but need RGB mode
> ```

检查了一波，确实这块读取的时候   f.read() = b' ',所以导致sample['image'] = b' ' ,这是为什么阿？我贴一下我的配置，您帮我看看，不胜感激！！
![Screenshot from 2021-07-06 14-39-22](https://user-images.githubusercontent.com/66230782/124553992-09f5c980-de68-11eb-85de-cbae4c817463.png)

**Comment by qingqing01** [comment]
您单独用cv2对 dataset/voc/JPEGImages/P05123.jpg 读取看下:

```
import cv2
import numpy as np

with open('dataset/voc/JPEGImages/P05123.jpg ', 'rb') as f:
    im = f.read()
    data = np.frombuffer(im, dtype='uint8')
    im = cv2.imdecode(data, 1)  # BGR mode, but need RGB mode
```

看下能否正确读取，从错误，很大可能这张图片有问题。

**Comment by LiangYong1216** [comment]
> 您单独用cv2对 dataset/voc/JPEGImages/P05123.jpg 读取看下:
> 
> ```
> import cv2
> import numpy as np
> 
> with open('dataset/voc/JPEGImages/P05123.jpg ', 'rb') as f:
>     im = f.read()
>     data = np.frombuffer(im, dtype='uint8')
>     im = cv2.imdecode(data, 1)  # BGR mode, but need RGB mode
> ```
> 
> 看下能否正确读取，从错误，很大可能这张图片有问题。

已经解决，谢谢您，原因是由于将数据从Windows下拷贝到linux系统下，不知道为什么只有文件名称， .jpg文件为空，所以才导致出现了问题，感谢您的耐心解答！感谢！
