### ISSUE TITLE
图片完整，推理时出现OSError: broken data stream when reading image file

### ISSUE THREAD

**Issue by wxf764571829** [PaddlePaddle/PaddleDetection#3589]
01/YFwxf01/2021缺陷result/5010.JPG
Traceback (most recent call last):
  File "tools/infer.py", line 158, in <module>
    main()
  File "tools/infer.py", line 154, in main
    run(FLAGS, cfg)
  File "tools/infer.py", line 128, in run
    trainer.predict(
  File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddledet-2.1.0-py3.8.egg/ppdet/engine/trainer.py", line 424, in predict
    image = Image.open(image_path).convert('RGB')
  File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/PIL/Image.py", line 904, in convert
    self.load()
  File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/PIL/ImageFile.py", line 274, in load
    raise_oserror(err_code)
  File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/PIL/ImageFile.py", line 67, in raise_oserror
    raise OSError(message + " when reading image file")
OSError: broken data stream when reading image file

**Comment by heavengate** [comment]
看报错在PIL库里读图片的时候，直接用python命令行里里`Image.open(image_path)`试下呢
