### ISSUE TITLE
请问在使用yolov3时候报错，错误信息如下

### ISSUE THREAD

**Issue by lipandeng** [PaddlePaddle/PaddleDetection#36]
Traceback (most recent call last):
  File "tools/train.py", line 340, in <module>
    main()
  File "tools/train.py", line 149, in main
    fetches = model.eval(feed_vars)
  File "/data/project/PaddleDetection/ppdet/modeling/architectures/yolov3.py", line 83, in eval
    return self.build(feed_vars, mode='test')
  File "/data/project/PaddleDetection/ppdet/modeling/architectures/yolov3.py", line 56, in build
    body_feats = self.backbone(im)
  File "/data/project/PaddleDetection/ppdet/modeling/backbones/mobilenet.py", line 157, in __call__
    input, 3, int(32 * scale), 2, 1, name=self.prefix_name + "conv1")
  File "/data/project/PaddleDetection/ppdet/modeling/backbones/mobilenet.py", line 83, in _conv_norm
    bias_attr=False)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/layers/nn.py", line 2783, in conv2d
    default_initializer=_get_default_param_initializer())
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/layer_helper_base.py", line 330, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/framework.py", line 2384, in create_parameter
    param = Parameter(global_block, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/framework.py", line 4480, in __init__
    self, block, persistable=True, shape=shape, dtype=dtype, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/framework.py", line 673, in __init__
    "matched.".format(self.name, old_shape, shape))
ValueError: Variable conv1_weights has been created before. the previous shape is (32, 3, 3, 3); the new shape is (32, 608, 3, 3). They are not matched.

**Comment by lipandeng** [comment]
python3 ppdet/modeling/tests/test_architectures.py
 python3 -u tools/train.py -c configs/yolov3_mobilenet_v1_fruit.yml --use_tb=True --tb_log_dir=tb_fruit_dir/scalar --eval
运行这2个都是报同样的错误

**Comment by Hyuhan** [comment]
我是在运行ppdet/modeling/tests/test_architectures.py的时候出现：
======================================================================
ERROR: test_test (__main__.TestYolov3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/tests/decorator_helper.py", line 29, in __fn__
    fn(*args, **kwargs)
  File "ppdet/modeling/tests/test_architectures.py", line 50, in test_test
    test_fetches = model.eval(feed_vars)
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/architectures/yolov3.py", line 83, in eval
    return self.build(feed_vars, mode='test')
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/architectures/yolov3.py", line 56, in build
    body_feats = self.backbone(im)
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/backbones/darknet.py", line 151, in __call__
    name=self.prefix_name + "yolo_input")
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/backbones/darknet.py", line 69, in _conv_norm
    bias_attr=False)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 2801, in conv2d
    "data_format": data_format,
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2426, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1809, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core_avx.EnforceNotMet: 
----------------------
Error Message Summary:
----------------------
PaddleCheckError: Expected in_dims.size() == 4 || in_dims.size() == 5 == true, but received in_dims.size() == 4 || in_dims.size() == 5:0 != true:1.
ShapeError: Conv input should be 4-D or 5-D tensor. But received: 3-D Tensor,the shape of Conv input is [3, 608, 608] at [/paddle/paddle/fluid/operators/conv_op.cc:57]
  [operator < conv2d > error]

请求赐教/(ㄒoㄒ)/~~

**Comment by Hyuhan** [comment]
我是在运行ppdet/modeling/tests/test_architectures.py的时候出现：
ERROR: test_test (__main__.TestYolov3)
Traceback (most recent call last):
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/tests/decorator_helper.py", line 29, in __fn__
    fn(*args, **kwargs)
  File "ppdet/modeling/tests/test_architectures.py", line 50, in test_test
    test_fetches = model.eval(feed_vars)
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/architectures/yolov3.py", line 83, in eval
    return self.build(feed_vars, mode='test')
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/architectures/yolov3.py", line 56, in build
    body_feats = self.backbone(im)
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/backbones/darknet.py", line 151, in __call__
    name=self.prefix_name + "yolo_input")
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/backbones/darknet.py", line 69, in _conv_norm
    bias_attr=False)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 2801, in conv2d
    "data_format": data_format,
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2426, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1809, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core_avx.EnforceNotMet:

Error Message Summary:
PaddleCheckError: Expected in_dims.size() == 4 || in_dims.size() == 5 == true, but received in_dims.size() == 4 || in_dims.size() == 5:0 != true:1.
ShapeError: Conv input should be 4-D or 5-D tensor. But received: 3-D Tensor,the shape of Conv input is [3, 608, 608] at [/paddle/paddle/fluid/operators/conv_op.cc:57]
  [operator < conv2d > error]

请求赐教/(ㄒoㄒ)/~~

**Comment by qingqing01** [comment]
是上周的PR https://github.com/PaddlePaddle/PaddleDetection/pull/34  导致的，我们尽快修复下。 方便的话，麻烦大家先reset到comments `703d379c07d2446c36b16290943686641bc86283`

 git reset --hard 703d379c07d2446c36b16290943686641bc86283
