### ISSUE TITLE
对模型进行评估迭代完成后报错

### ISSUE THREAD

**Issue by qq345481843** [PaddlePaddle/PaddleDetection#363]
......
2020-03-20 14:41:51,107-INFO: Test iter 9300
2020-03-20 14:42:10,149-INFO: Test iter 9400
2020-03-20 14:42:29,215-INFO: Test iter 9500
2020-03-20 14:42:48,115-INFO: Test iter 9600
2020-03-20 14:43:04,916-INFO: Test finish iter 9690
2020-03-20 14:43:04,916-INFO: Total number of images: 9690, inference time: 5.2448062193586455 fps.
loading annotations into memory...
Done (t=0.29s)
creating index...
index created!
2020-03-20 14:43:06,715-INFO: Start evaluate...
Loading and preparing results...
DONE (t=0.60s)
creating index...
index created!
Traceback (most recent call last):
  File "/home/cyye/.local/lib/python3.6/site-packages/numpy/core/function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/eval.py", line 190, in <module>
    main()
  File "tools/eval.py", line 173, in main
    dataset=dataset)
  File "/home/cyye/jhwang/PaddleDetection/ppdet/utils/eval_utils.py", line 205, in eval_results
    is_bbox_normalized=is_bbox_normalized)
  File "/home/cyye/jhwang/PaddleDetection/ppdet/utils/coco_eval.py", line 94, in bbox_eval
    map_stats = cocoapi_eval(outfile, 'bbox', coco_gt=coco_gt)
  File "/home/cyye/jhwang/PaddleDetection/ppdet/utils/coco_eval.py", line 147, in cocoapi_eval
    coco_eval = COCOeval(coco_gt, coco_dt, style)
  File "/home/cyye/.local/lib/python3.6/site-packages/pycocotools/cocoeval.py", line 76, in __init__
    self.params = Params(iouType=iouType) # parameters
  File "/home/cyye/.local/lib/python3.6/site-packages/pycocotools/cocoeval.py", line 527, in __init__
    self.setDetParams()
  File "/home/cyye/.local/lib/python3.6/site-packages/pycocotools/cocoeval.py", line 507, in setDetParams
    self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)
  File "<__array_function__ internals>", line 6, in linspace
  File "/home/cyye/.local/lib/python3.6/site-packages/numpy/core/function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.
出现这个报错可能的原因是什么？

希望能得到回复，谢谢。

**Comment by heavengate** [comment]
numpy最新版本修改了`linspace`用法，`pyccocotools`没有适配的报错，参考 https://github.com/PaddlePaddle/PaddleDetection/issues/245
