### ISSUE TITLE
模型eval时报错：

### ISSUE THREAD

**Issue by jackie8310** [PaddlePaddle/PaddleDetection#3640]
静态图采用边train边eval，eval时报错后停止train，于是将--eval去除，待train完成后，采用python tools/eval.py ,仍然报错如下，请指教？
W0708 16:51:21.206642 17238 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0708 16:51:21.212035 17238 device_context.cc:372] device: 0, cuDNN Version: 7.6.
2021-07-08 16:51:29,216 - INFO - Test iter 0
2021-07-08 16:51:38,996 - INFO - Test finish iter 80
2021-07-08 16:51:38,996 - INFO - Total number of images: 160, inference time: 15.304161039443557 fps.
2021-07-08 16:51:38,996 - INFO - Start evaluate...
Traceback (most recent call last):
  File "tools/eval.py", line 179, in <module>
    main()
  File "tools/eval.py", line 156, in main
    eval.eval_results(classwise=FLAGS.classwise)
  File "/home/aistudio/work/PaddleDetection0.5beta/ppdet/evaluation/evaluate.py", line 194, in eval_results
    num_classes=self.num_classes)
  File "/home/aistudio/work/PaddleDetection0.5beta/ppdet/data/source/coco.py", line 222, in evaluate
    results, is_bbox_normalized=is_bbox_normalized)
  File "/home/aistudio/work/PaddleDetection0.5beta/ppdet/data/source/coco.py", line 307, in save_eval_json
    results, clsid2catid, is_bbox_normalized=is_bbox_normalized)
  File "/home/aistudio/work/PaddleDetection0.5beta/ppdet/evaluation/result_out.py", line 110, in bbox2out
    catid = (clsid2catid[int(clsid)])
KeyError: 11

**Comment by jackie8310** [comment]
已发现问题，类别数不对。
