### ISSUE TITLE
模型训练完成并导出后 如何在windows下使用python进行预测，我在windows下安装了paddle后直接调用./deploy/python/infer.py进行预测报了以下错误

### ISSUE THREAD

**Issue by wxf764571829** [PaddlePaddle/PaddleDetection#3646]
```
C:\Users\zfsw\AppData\Local\Programs\Python\Python37\python.exe F:/code/PaddleDetection-release-2.1/deploy/python/infer.py --model_dir=F:\code\PaddleDetection-release-2.1\faster_rcnn_r101_vd_fpn_1x_coco --image_file=H:\2021\1.JPG --use_gpu=True
-----------  Running Arguments -----------
batch_size: 1
camera_id: -1
cpu_threads: 1
enable_mkldnn: False
image_dir: None
image_file: H:\2021\1.JPG
model_dir: F:\code\PaddleDetection-release-2.1\faster_rcnn_r101_vd_fpn_1x_coco
output_dir: output
run_benchmark: False
run_mode: fluid
threshold: 0.5
trt_calib_mode: False
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
use_dynamic_shape: False
use_gpu: True
video_file: None
------------------------------------------
-----------  Model Configuration -----------
Model Arch: RCNN
Transform Order: 
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--transform op: PadStride
--------------------------------------------
Traceback (most recent call last):
  File "F:/code/PaddleDetection-release-2.1/deploy/python/infer.py", line 639, in <module>
    main()
  File "F:/code/PaddleDetection-release-2.1/deploy/python/infer.py", line 606, in main
    predict_image(detector, img_list, FLAGS.batch_size)
  File "F:/code/PaddleDetection-release-2.1/deploy/python/infer.py", line 520, in predict_image
    results = detector.predict(batch_image_list, FLAGS.threshold)
  File "F:/code/PaddleDetection-release-2.1/deploy/python/infer.py", line 160, in predict
    self.predictor.run()
ValueError: In user code:

    File "tools/export_model.py", line 105, in <module>
      main()
    File "tools/export_model.py", line 101, in main
      run(FLAGS, cfg)
    File "tools/export_model.py", line 69, in run
      trainer.export(FLAGS.output_dir)
    File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddledet-2.1.0-py3.8.egg/ppdet/engine/trainer.py", line 506, in export
      input_spec, static_model.forward.main_program,
    File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 534, in main_program
      concrete_program = self.concrete_program
    File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 454, in concrete_program
      return self.concrete_program_specify_input_spec(input_spec=None)
    File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 487, in concrete_program_specify_input_spec
      concrete_program, _ = self.get_concrete_program(
    File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 698, in _build_once
      concrete_program = ConcreteProgram.from_func_spec(
    File "<decorator-gen-65>", line 2, in from_func_spec
      
    File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
      return func(*args, **kwargs)
    File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 652, in from_func_spec
      outputs = static_func(*inputs)
    File "/tmp/tmppf19xzqh.py", line 26, in forward
      out = paddle.jit.dy2static.convert_ifelse(self.training, true_fn_1,
    File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddledet-2.1.0-py3.8.egg/ppdet/modeling/architectures/meta_arch.py", line 29, in forward
      out = self.get_pred()
    File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddledet-2.1.0-py3.8.egg/ppdet/modeling/architectures/faster_rcnn.py", line 104, in get_pred
      bbox_pred, bbox_num = self._forward()
    File "/tmp/tmpvun9zvo4.py", line 51, in _forward
      _, __return_value_0, rois, rois_num = paddle.jit.dy2static.convert_ifelse(
    File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddledet-2.1.0-py3.8.egg/ppdet/modeling/architectures/faster_rcnn.py", line 86, in _forward
      bbox, bbox_num = self.bbox_post_process(preds, (rois, rois_num),
    File "/tmp/tmpufu5mqqf.py", line 35, in __call__
      bbox_num, bbox_pred = paddle.jit.dy2static.convert_ifelse(self.nms is not
    File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddledet-2.1.0-py3.8.egg/ppdet/modeling/post_process.py", line 65, in __call__
      bboxes, score = self.decode(head_out, rois, im_shape, scale_factor)
    File "/tmp/tmpnaxnj8ca.py", line 31, in __call__
      ] = paddle.jit.dy2static.convert_while_loop(for_loop_condition_10,
    File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 44, in convert_while_loop
      loop_vars = _run_py_while(cond, body, loop_vars)
    File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 58, in _run_py_while
      loop_vars = body(*loop_vars)
    File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddledet-2.1.0-py3.8.egg/ppdet/modeling/layers.py", line 347, in __call__
      expand_im_shape = paddle.expand(im_shape[idx, :],
    File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/tensor/manipulation.py", line 1489, in expand
      helper.append_op(
    File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3226, in append_op
      op = Operator(
    File "/home/ubuntu01/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2312, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The 0th element of 'shape' for expand_v2 op must be greater than 0, but the value given is -2.
      [Hint: Expected expand_shape[i] > 0, but received expand_shape[i]:-2 <= 0:0.] (at D:\v2.0.0\paddle\paddle\fluid\operators\expand_v2_op.cc:75)
      [operator < expand_v2 > error]
```

**Comment by xiegegege** [comment]
@wxf764571829 麻烦问下你的paddle版本是什么呢？可以更新到2.1.1重新导出下，我试了可以跑。python deploy/python/infer.py --model_dir=./inference_model/faster_rcnn_r101_vd_fpn_1x_coco/ --image_file=demo/000000570688.jpg --use_gpu=True --run_mode=fluid

**Comment by wxf764571829** [comment]
> @wxf764571829 麻烦问下你的paddle版本是什么呢？可以更新到2.1.1重新导出下，我试了可以跑。python deploy/python/infer.py --model_dir=./inference_model/faster_rcnn_r101_vd_fpn_1x_coco/ --image_file=demo/000000570688.jpg --use_gpu=True --run_mode=fluid

windows下的版本是paddlepaddle-gpu 2.0.0   好的 我更新尝试以下
