### ISSUE TITLE
windows下安装环境报错ValueError: numpy.ndarray has the wrong size, try recompiling. Expected 80, got 88

### ISSUE THREAD

**Issue by python-bookworm** [PaddlePaddle/PaddleDetection#3656]
环境：win10 conda环境，python3.7，paddlepaddle-gpu ==2.1.0.post101,numpy==1.19.3
编译安装paddledet之后验证报错：
ValueError: numpy.ndarray has the wrong size, try recompiling. Expected 80, got 88
相关的安装配置：
appdirs             1.4.4
astor               0.8.1
atomicwrites        1.4.0
attrs               21.2.0
Babel               2.9.1
bce-python-sdk      0.8.61
certifi             2021.5.30
cfgv                3.3.0
chardet             4.0.0
click               8.0.1
colorama            0.4.4
cycler              0.10.0
Cython              0.29.23
decorator           4.4.2
distlib             0.3.2
et-xmlfile          1.1.0
filelock            3.0.12
flake8              3.9.2
flake8-import-order 0.18.1
Flask               2.0.1
Flask-Babel         2.0.0
future              0.18.2
gast                0.3.3
identify            2.2.10
idna                2.10
importlib-metadata  4.6.1
iniconfig           1.1.1
itsdangerous        2.0.1
Jinja2              3.0.1
joblib              1.0.1
kiwisolver          1.3.1
lap                 0.4.0
MarkupSafe          2.0.1
matplotlib          3.4.2
mccabe              0.6.1
motmetrics          1.2.0
nodeenv             1.6.0
numpy               1.19.3
opencv-python       4.5.2.54
openpyxl            3.0.7
packaging           21.0
paddledet           2.1.0
paddlepaddle-gpu    2.1.0.post101
pandas              1.3.0
Pillow              8.3.1
pip                 21.1.3
pluggy              0.13.1
pre-commit          2.13.0
protobuf            3.17.3
py                  1.10.0
py-cpuinfo          8.0.0
pycocotools         2.0
pycodestyle         2.7.0
pycryptodome        3.10.1
pyflakes            2.3.1
pyparsing           2.4.7
pytest              6.2.4
pytest-benchmark    3.4.1
python-dateutil     2.8.1
pytz                2021.1
PyYAML              5.4.1
requests            2.25.1
scikit-learn        0.24.2
scipy               1.7.0
setuptools          52.0.0.post20210125
Shapely             1.7.1
shellcheck-py       0.7.2.1
six                 1.16.0
sklearn             0.0
terminaltables      3.1.0
threadpoolctl       2.1.0
toml                0.10.2
tqdm                4.61.2
typeguard           2.12.1
typing-extensions   3.10.0.0
urllib3             1.26.6
virtualenv          20.4.7
visualdl            2.2.0
Werkzeug            2.0.1
wheel               0.36.2
wincertstore        0.2
xmltodict           0.12.0
zipp                3.5.0

具体的报错类型：

```
(ppd) D:\workcodes\pyprojects\PaddleDetection>python ppdet/modeling/tests/test_architectures.py
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 20, in <module>
    import ppdet
  File "D:\software\Anaconda3\envs\ppd\lib\site-packages\paddledet-2.1.0-py3.7.egg\ppdet\__init__.py", line 15, in <module>
    from . import (core, data, engine, modeling, model_zoo, optimizer, metrics,
  File "D:\software\Anaconda3\envs\ppd\lib\site-packages\paddledet-2.1.0-py3.7.egg\ppdet\data\__init__.py", line 16, in <module>
    from . import transform
  File "D:\software\Anaconda3\envs\ppd\lib\site-packages\paddledet-2.1.0-py3.7.egg\ppdet\data\transform\__init__.py", line 15, in <module>
    from . import operators
  File "D:\software\Anaconda3\envs\ppd\lib\site-packages\paddledet-2.1.0-py3.7.egg\ppdet\data\transform\operators.py", line 41, in <module>
    from ppdet.modeling import bbox_utils
  File "D:\software\Anaconda3\envs\ppd\lib\site-packages\paddledet-2.1.0-py3.7.egg\ppdet\modeling\__init__.py", line 25, in <module>
    from . import architectures
  File "D:\software\Anaconda3\envs\ppd\lib\site-packages\paddledet-2.1.0-py3.7.egg\ppdet\modeling\architectures\__init__.py", line 20, in <module>
    from . import jde
  File "D:\software\Anaconda3\envs\ppd\lib\site-packages\paddledet-2.1.0-py3.7.egg\ppdet\modeling\architectures\jde.py", line 20, in <module>
    from ppdet.modeling.mot.utils import scale_coords
  File "D:\software\Anaconda3\envs\ppd\lib\site-packages\paddledet-2.1.0-py3.7.egg\ppdet\modeling\mot\__init__.py", line 15, in <module>
    from . import matching
  File "D:\software\Anaconda3\envs\ppd\lib\site-packages\paddledet-2.1.0-py3.7.egg\ppdet\modeling\mot\matching\__init__.py", line 15, in <module>
    from . import jde_matching
  File "D:\software\Anaconda3\envs\ppd\lib\site-packages\paddledet-2.1.0-py3.7.egg\ppdet\modeling\mot\matching\jde_matching.py", line 18, in <module>
    import lap
  File "D:\software\Anaconda3\envs\ppd\lib\site-packages\lap\__init__.py", line 25, in <module>
    from ._lapjv import (
  File "__init__.pxd", line 199, in init lap._lapjv
ValueError: numpy.ndarray has the wrong size, try recompiling. Expected 80, got 88
```

**Comment by lyuwenyu** [comment]
在你上边那个环境下可以试一下单独import lap会出错嘛？
如果有问题的话 可以尝试一下不同 python numpy的环境

> linux下python numpy lap按照你现在的版本验证没有问题

**Comment by jerrywgz** [comment]
能否提供下lap和numpy的版本呢

**Comment by Mike-cell** [comment]
请问解决了吗

**Comment by wangxinit** [comment]
numpy   版本的问题，安装 >=1.22.3

卸载numpy  ，pip uninstall numpy  -y
重新安装numpy ，    pip install numpy

**Comment by fkldhvu** [comment]
我的问题和你一模一样，不能升级numpy, 因为paddlepaddle_gpu要求的numpy版本必须<=1.19.3
