### ISSUE TITLE
关键点检测keypoint_infer.py 时出现EvalAffine未定义错误

### ISSUE THREAD

**Issue by zshuang80826** [PaddlePaddle/PaddleDetection#3657]
执行页面上例程代码：
#部署推理
#keypoint top-down/bottom-up 单独推理，该模式下top-down模型只支持单人截图预测。
python deploy/python/keypoint_infer.py --model_dir=output_inference/higherhrnet_hrnet_w32_512/ --image_file=./demo/000000014439_640x640.jpg --use_gpu=True --threshold=0.5

出现如下错误：
Traceback (most recent call last):
  File "deploy/python/keypoint_infer.py", line 428, in <module>
    main()
  File "deploy/python/keypoint_infer.py", line 396, in main
    predict_image(detector, img_list)
  File "deploy/python/keypoint_infer.py", line 328, in predict_image
    results = detector.predict(img_file, FLAGS.threshold)
  File "deploy/python/keypoint_infer.py", line 128, in predict
    inputs = self.preprocess(image)
  File "deploy/python/keypoint_infer.py", line 85, in preprocess
    preprocess_ops.append(eval(op_type)(**new_op_info))
  File "<string>", line 1, in <module>
NameError: name 'EvalAffine' is not defined

环境版本:
Paddledetection  Paddlepaddle  v2.1
CUDA 10.2

**Comment by nemonameless** [comment]
建议使用develop分支，以及重新python setup.py install更新下。另外--use_gpu=True已不支持，可使用--device=GPU
```
python deploy/python/keypoint_infer.py --model_dir=output_inference/higherhrnet_hrnet_w32_512/ --image_file=./demo/000000014439_640x640.jpg --device=GPU --threshold=0.5
```
自测没有问题。

**Comment by z0y1** [comment]
关键点推理，同样出现EvalAffine未定义错误。
切换到develop分支后，执行python setup.py install。再次运行推理
python deploy/python/keypoint_infer.py --model_dir=./output_inference/higherhrnet_hrnet_w32_512_swahr --device=CPU --camera_id=0

出现如下错误:
------------------------------------------
Traceback (most recent call last):
  File "deploy/python/keypoint_infer.py", line 378, in <module>
    main()
  File "deploy/python/keypoint_infer.py", line 322, in main
    pred_config = PredictConfig_KeyPoint(FLAGS.model_dir)
  File "deploy/python/keypoint_infer.py", line 241, in __init__
    self.use_dynamic_shape = yml_conf['use_dynamic_shape']
KeyError: 'use_dynamic_shape'

运行环境: 
paddlepaddle-gpu  2.1.1.post110

**Comment by jerrywgz** [comment]
需要在新版本的paddledet上重新导出模型
