### ISSUE TITLE
使用ppyolo训练出错

### ISSUE THREAD

**Issue by zzzfo** [PaddlePaddle/PaddleDetection#3694]
输入训练命令以后出现这个错误，数据集的路径都已经设置好了，label_list也只有fire

```
Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 102, in run
    trainer = Trainer(cfg, mode='train')
  File "/home/wumei/anaconda3/envs/pp/lib/python3.7/site-packages/paddledet-2.1.0-py3.7.egg/ppdet/engine/trainer.py", line 63, in __init__
    self.dataset, cfg.worker_num)
  File "/home/wumei/anaconda3/envs/pp/lib/python3.7/site-packages/paddledet-2.1.0-py3.7.egg/ppdet/data/reader.py", line 165, in __call__
    self.dataset.parse_dataset()
  File "/home/wumei/anaconda3/envs/pp/lib/python3.7/site-packages/paddledet-2.1.0-py3.7.egg/ppdet/data/source/voc.py", line 136, in parse_dataset
    gt_class.append([cname2cid[cname]])
KeyError: 'person'
```

**Comment by jerrywgz** [comment]
person这个字段是voc数据集下的字段，label_list的路径需要设置为dataset_dir的相对路径，也就是绝对路径为os.path.join(self.dataset_dir, self.label_list)

**Comment by zzzfo** [comment]
我改了也没有用呀，而且运行anchor_cluster.py也是报这个错。。。

**Comment by zzzfo** [comment]
这是我的配置文件

```
metric: VOC
map_type: 11point
num_classes: 1

TrainDataset:
  !VOCDataSet
    dataset_dir: dataset/fire_detection/VOCdevkit/VOC2007
    anno_path: trainval.txt
    label_list: label_list.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

EvalDataset:
  !VOCDataSet
    dataset_dir: dataset/fire_detection/VOCdevkit/VOC2007
    anno_path: test.txt
    label_list: label_list.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

TestDataset:
  !ImageFolder
    anno_path: label_list.txt
```

label_list.txt,test.txt,train.txt,,trainval.txt,,val.txt均在dataset/fire_detection/VOCdevkit/VOC2007目录下

**Comment by zzzfo** [comment]
> person这个字段是voc数据集下的字段，label_list的路径需要设置为dataset_dir的相对路径，也就是绝对路径为os.path.join(self.dataset_dir, self.label_list)

我改了label_list的路径，没有用，而且运行anchor_cluster.py也是报这个错。。。

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/data/source/voc.py#L71 可以打印看下这里的label_list和label_path

**Comment by zzzfo** [comment]
已经解决了，是我lable没写完

**Comment by zzzfo** [comment]
已经解决了，是我的数据集有问题
