### ISSUE TITLE
尝试在aistudio上使用paddle_detection时报错

### ISSUE THREAD

**Issue by qqwantu** [PaddlePaddle/PaddleDetection#3708]
alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
W0716 23:29:34.475000   349 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0716 23:29:34.480676   349 device_context.cc:422] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 102, in run
    trainer = Trainer(cfg, mode='train')
  File "/home/aistudio/PaddleDetection/ppdet/engine/trainer.py", line 74, in __init__
    self.dataset, cfg.worker_num)
  File "/home/aistudio/PaddleDetection/ppdet/data/reader.py", line 170, in __call__
    self.dataset.parse_dataset()
  File "/home/aistudio/PaddleDetection/ppdet/data/source/voc.py", line 91, in parse_dataset
    if not os.path.exists(img_file):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/genericpath.py", line 19, in exists
    os.stat(path)
ValueError: embedded null byte
![Uploading 2IXRCLNRUD)1MX_TU8[]B@B.png…]()

**Comment by wangxinxin08** [comment]
看起来是图片路径没有正确设置导致加载图片报错
