### ISSUE TITLE
使用create_list生成trainval.txt和test.txt文件出错

### ISSUE THREAD

**Issue by wyh669** [PaddlePaddle/PaddleDetection#3724]
aistudio@jupyter-879124-2205815:~/work/PaddleDetection$ python dataset/voc/create_list.py -d ~/fire_dataset

```
Traceback (most recent call last):
  File "dataset/voc/create_list.py", line 45, in <module>
    main(config)
  File "dataset/voc/create_list.py", line 31, in main
    create_voc_list(voc_path)
  File "/home/aistudio/work/PaddleDetection/ppdet/utils/download.py", line 157, in create_voc_list
    create_list(year_dirs, data_dir)
  File "/home/aistudio/work/PaddleDetection/ppdet/utils/voc_utils.py", line 37, in create_list
    trainval, test = _walk_voc_dir(year_dir, output_dir)
  File "/home/aistudio/work/PaddleDetection/ppdet/utils/voc_utils.py", line 84, in _walk_voc_dir
    osp.relpath(img_dir, output_dir), img_dict[name_prefix])
KeyError: 'img'

```

**Comment by qingqing01** [comment]
确保VOC数据格式没问题吧。代码里没有 `img` 变量，建议voc_utils.py:84行debug看下。

https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/utils/voc_utils.py#L84
