### ISSUE TITLE
联合Hrnet模型推理报错  TopDownEvalAffine没定义 在.py内找不到这个参数

### ISSUE THREAD

**Issue by Wei-JL** [PaddlePaddle/PaddleDetection#3725]
```
-----------  Running Arguments -----------
camera_id: -1
cpu_threads: 1
det_model_dir: output_inference/ppyolov2_r50vd_dcn_voc/
det_threshold: 0.5
enable_mkldnn: False
image_dir: None
image_file: None
keypoint_model_dir: output_inference/hrnet_w32_384x288/
keypoint_threshold: 0.5
output_dir: output
run_benchmark: False
run_mode: fluid
trt_calib_mode: False
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
use_dynamic_shape: False
use_gpu: True
video_file: ../../Test/test.mp4
------------------------------------------
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order: 
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
I0720 16:32:28.865988  6308 analysis_config.cc:424] use_dlnne_:0
I0720 16:32:28.866051  6308 analysis_config.cc:424] use_dlnne_:0
I0720 16:32:28.866075  6308 analysis_config.cc:424] use_dlnne_:0
I0720 16:32:28.866089  6308 analysis_config.cc:424] use_dlnne_:0
-----------  Model Configuration -----------
Model Arch: HRNet
Transform Order: 
--transform op: TopDownEvalAffine
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
detect frame:1
Traceback (most recent call last):
  File "deploy/python/keypoint_det_unite_infer.py", line 199, in <module>
    main()
  File "deploy/python/keypoint_det_unite_infer.py", line 186, in main
    FLAGS.camera_id)
  File "deploy/python/keypoint_det_unite_infer.py", line 130, in topdown_unite_predict_video
    batch_images, FLAGS.keypoint_threshold)
  File "/home/aistudio/work/PaddleDetection/deploy/python/keypoint_infer.py", line 128, in predict
    inputs = self.preprocess(image)
  File "/home/aistudio/work/PaddleDetection/deploy/python/keypoint_infer.py", line 85, in preprocess
    preprocess_ops.append(eval(op_type)(**new_op_info))
  File "<string>", line 1, in <module>
NameError: name 'TopDownEvalAffine' is not defined
```

**Comment by nemonameless** [comment]
请拉取最新代码或切换到最新develop分支，现在是运行的 deploy/python/det_keypoint_unite_infer.py，自测没有问题。
