### ISSUE TITLE
使用yolov3/_base_/yolov3_reader.yml 设置num worker=3 跑一段时间后报错，如何去分析这个错误呢？

### ISSUE THREAD

**Issue by 15162162323** [PaddlePaddle/PaddleDetection#3759]
[07/23 09:38:44] ppdet.engine INFO: Epoch: [3] [ 0/10] learning_rate: 0.000053 loss_xy: 9.220256 loss_wh: 5.332484 loss_obj: 33.812561 loss_cls: 2.637844 loss: 51.312519 eta: 0:52:43 batch_cost: 6.8649 data_cost: 6.2173 ips: 1.1654 images/s
ERROR:root:DataLoader reader thread raised an exception!
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dataloader/dataloader_iter.py", line 482, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 105, in get
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dataloader/dataloader_iter.py", line 411, in _thread_loop
    batch = self._get_data()
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dataloader/dataloader_iter.py", line 498, in _get_data
    "pids: {}".format(len(failed_workers), pids))
RuntimeError: DataLoader 1 workers exit unexpectedly, pids: 1193

Traceback (most recent call last):
  File "/project/train/src_repo/PaddleDetection/tools/train.py", line 139, in <module>
    main()
  File "/project/train/src_repo/PaddleDetection/tools/train.py", line 135, in main
    run(FLAGS, cfg)
  File "/project/train/src_repo/PaddleDetection/tools/train.py", line 110, in run
    trainer.train(FLAGS.eval)
  File "/usr/local/lib/python3.6/dist-packages/ppdet/engine/trainer.py", line 289, in train
    for step_id, data in enumerate(self.loader):
  File "/usr/local/lib/python3.6/dist-packages/ppdet/data/reader.py", line 211, in __next__
    return next(self.loader)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dataloader/dataloader_iter.py", line 585, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

**Comment by 15162162323** [comment]
设置num_worker=1没问题

**Comment by 15162162323** [comment]
num worker数量和cpu的数量有关系吗？

**Comment by thorory** [comment]
同样的问题，现在有解吗？

**Comment by yghstill** [comment]
@15162162323 dataloader存在内存泄露的问题，目前已修复https://github.com/PaddlePaddle/Paddle/pull/34140 ，改下paddle安装路径中的fluid/dataloader/dataloader_iter.py文件，删掉以下内容试下：
```python
CleanupFuncRegistrar.register(self.__del__)
```

**Comment by 15162162323** [comment]
@yghstill 多谢指点~，那num_worker设置多少，怎么估算呢？

**Comment by yghstill** [comment]
@15162162323 没有一个内存与num_worker的映射关系，看你机器的内存大小，如果很小就设置成1就行
