### ISSUE TITLE
eval评估出错

### ISSUE THREAD

**Issue by Weilongxin** [PaddlePaddle/PaddleDetection#3768]
W0723 16:30:03.859206  1127 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 9.0
W0723 16:30:03.864948  1127 device_context.cc:260] device: 0, cuDNN Version: 7.6.
2021-07-23 16:30:12,625-INFO: Test iter 0
2021-07-23 16:30:14,206-INFO: Test finish iter 91
2021-07-23 16:30:14,206-INFO: Total number of images: 91, inference time: 50.773135477533835 fps.
2021-07-23 16:30:14,206-INFO: Start evaluate...
Traceback (most recent call last):
  File "/home/aistudio/work/PaddleDetection/static/tools/eval.py", line 206, in <module>
    main()
  File "/home/aistudio/work/PaddleDetection/static/tools/eval.py", line 188, in main
    save_only=save_only)
  File "/home/aistudio/work/PaddleDetection/static/ppdet/utils/eval_utils.py", line 267, in eval_results
    map_type=map_type)
  File "/home/aistudio/work/PaddleDetection/static/ppdet/utils/voc_eval.py", line 71, in bbox_eval
    gt_boxes = t['gt_bbox'][0]
KeyError: 'gt_bbox'

这个是什么原因呢？有什么解决办法吗？

**Comment by liuhuiCNN** [comment]
你好，请问是用的静态图吗？如果是静态图的话，请使用`static/tools/eval.py`进行评估。

**Comment by Weilongxin** [comment]
> 你好，请问是用的静态图吗？如果是静态图的话，请使用`static/tools/eval.py`进行评估。

对的，我试试，谢谢啦

**Comment by Weilongxin** [comment]
> 你好，请问是用的静态图吗？如果是静态图的话，请使用`static/tools/eval.py`进行评估。

我用的就是static/tools/eval.py这个，就是有这个问题。

**Comment by liuhuiCNN** [comment]
> > 你好，请问是用的静态图吗？如果是静态图的话，请使用`static/tools/eval.py`进行评估。
> 
> 我用的就是static/tools/eval.py这个，就是有这个问题。

模型和配置文件都是静态图的吗？
我在static文件夹下：
`python tools/eval.py -c configs/ppyolo/ppyolo_2x.yml -o weights=https://paddlemodels.bj.bcebos.com/object_detection/ppyolo.pdparams` 测试是正常的。

**Comment by Weilongxin** [comment]
> > > 你好，请问是用的静态图吗？如果是静态图的话，请使用`static/tools/eval.py`进行评估。
> > 
> > 
> > 我用的就是static/tools/eval.py这个，就是有这个问题。
> 
> 模型和配置文件都是静态图的吗？
> 我在static文件夹下：
> `python tools/eval.py -c configs/ppyolo/ppyolo_2x.yml -o weights=https://paddlemodels.bj.bcebos.com/object_detection/ppyolo.pdparams` 测试是正常的。

都是静态的，就是这个键错误是为什么呢？

**Comment by Weilongxin** [comment]
> > > 你好，请问是用的静态图吗？如果是静态图的话，请使用`static/tools/eval.py`进行评估。
> > 
> > 
> > 我用的就是static/tools/eval.py这个，就是有这个问题。
> 
> 模型和配置文件都是静态图的吗？
> 我在static文件夹下：
> `python tools/eval.py -c configs/ppyolo/ppyolo_2x.yml -o weights=https://paddlemodels.bj.bcebos.com/object_detection/ppyolo.pdparams` 测试是正常的。


!python -u /home/aistudio/work/PaddleDetection/static/tools/eval.py \
        -c /home/aistudio/work/PaddleDetection/static/configs/yolov3_mobilenet_v1_2.yml \
        -o weights=/home/aistudio/output/yolov3_mobilenet_v1_2/model_final

**Comment by liuhuiCNN** [comment]
你好，静态图下和动态图下读取数据字段有区别，请检查一下字段设置是否正确（参考静态图中配置）。

**Comment by Weilongxin** [comment]
> 你好，静态图下和动态图下读取数据字段有区别，请检查一下字段设置是否正确（参考静态图中配置）。

好的谢谢，静态图的配置在哪个位置呢？
