### ISSUE TITLE
模型预测时报错：TypeError: join() argument must be str or bytes, not 'list'

### ISSUE THREAD

**Issue by yumeng88** [PaddlePaddle/PaddleDetection#3814]
(pandle) asus@asus-System-Product-Name:/media/asus/225A6D42D4FA828F/2021Intern/renyumeng/PaddleDetection-release-2.2$ python tools/infer.py -c configs/dota/s2anet_SARplane.yml -o weights=output/s2anet_SARplane/300.pdparams --infer_img=dataset/SARplane/images/4.jpg  --draw_threshold=0.5 --save_txt=True  --output_dir=output
W0729 03:18:37.054687 20598 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.2, Runtime API Version: 10.2
W0729 03:18:37.056581 20598 device_context.cc:422] device: 0, cuDNN Version: 7.6.
[07/29 03:18:38] ppdet.utils.checkpoint INFO: Finish loading model weights: output/s2anet_SARplane/300.pdparams
Traceback (most recent call last):
  File "tools/infer.py", line 161, in <module>
    main()
  File "tools/infer.py", line 157, in main
    run(FLAGS, cfg)
  File "tools/infer.py", line 135, in run
    save_txt=FLAGS.save_txt)
  File "/home/asus/anaconda3/envs/pandle/lib/python3.6/site-packages/paddledet-2.1.0-py3.6.egg/ppdet/engine/trainer.py", line 454, in predict
    loader = create('TestReader')(self.dataset, 0)
  File "/home/asus/anaconda3/envs/pandle/lib/python3.6/site-packages/paddledet-2.1.0-py3.6.egg/ppdet/data/reader.py", line 162, in __call__
    self.dataset.check_or_download_dataset()
  File "/home/asus/anaconda3/envs/pandle/lib/python3.6/site-packages/paddledet-2.1.0-py3.6.egg/ppdet/data/source/dataset.py", line 91, in check_or_download_dataset
    self.image_dir)
  File "/home/asus/anaconda3/envs/pandle/lib/python3.6/site-packages/paddledet-2.1.0-py3.6.egg/ppdet/utils/download.py", line 165, in get_dataset_path
    if _dataset_exists(path, annotation, image_dir):
  File "/home/asus/anaconda3/envs/pandle/lib/python3.6/site-packages/paddledet-2.1.0-py3.6.egg/ppdet/utils/download.py", line 322, in _dataset_exists
    image_path = osp.join(path, image_dir)
  File "/home/asus/anaconda3/envs/pandle/lib/python3.6/posixpath.py", line 92, in join
    genericpath._check_arg_types('join', a, *p)
  File "/home/asus/anaconda3/envs/pandle/lib/python3.6/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'list'

**Comment by yumeng88** [comment]
使用的是最新的2.2版本

**Comment by liuhuiCNN** [comment]
请检查一下数据配置中数据路径是否正常。使用新版本代码时，记得uninstall之前通过python setup.py install 的库，请参考：https://stackoverflow.com/questions/1550226/python-setup-py-uninstall

**Comment by yumeng88** [comment]
@liuhuiCNN 你好，检查过后数据路径正常，并且重新pip setup.py install ,使用develop版本进行预测的时候是没有问题的，这里不知道是哪里出了问题

**Comment by yumeng88** [comment]
更新新的版本之后问题解决，多谢多谢
