### ISSUE TITLE
tools/x2coco.py voc转coco数据格式，如果xml <obj>标签中检测目标名带空格，会报错，有待解决

### ISSUE THREAD

**Issue by yyyssq** [PaddlePaddle/PaddleDetection#3827]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://paddledetection.readthedocs.io/FAQ.html) /I have read the [FAQ documentation](https://paddledetection.readthedocs.io/FAQ.html) but cannot get the expected help.
3. 确认bug是否在新版本里还未修复/The bug has not been fixed in the latest version.

## 复现/Reproduction
当我把xml，要检测的目标对象的名字中间的空格去掉，此错误消失，加上空格，错误出现

1. 您使用的命令是？/What command or script did you run?
2. python tools/x2coco.py --dataset_type voc --voc_anno_dir ./dataset/voc/VOCdevkit/VOC2007/AnnotationsTest/ --voc_anno_list ./dataset/voc/VOCdevkit/VOC2007/ImageSets/Main/trainvalTest.txt --voc_label_list ./dataset/voc/label_list.txt --voc_out_name voc_train.json

```none
请填写命令/A placeholder for the command.
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.
3. 修改过tools/x2coco.py 中间加入打印语句

3. 您使用的数据集是？/What dataset did you use?
4. 自定义数据集

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.
5. Traceback (most recent call last):
  File "tools/x2coco.py", line 450, in <module>
    main()
  File "tools/x2coco.py", line 346, in main
    output_file=args.voc_out_name)
  File "tools/x2coco.py", line 270, in voc_xmls_to_cocojson
    ann = voc_get_coco_annotation(obj=obj, label2id=label2id)
  File "tools/x2coco.py", line 231, in voc_get_coco_annotation
    assert label in label2id, "label is not in label2id."
AssertionError: label is not in label2id.

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
2. paddle 2.0

2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：
4. aistudio平台，顺带吐槽一下，paddlex 可视化界面只能用18.0.4版本，可是aistudio是16.0.4如果两个匹配起来，不是更好吗

4. 请问您使用的Python版本是？/ Please provide the version of Python you used.
5. 3.7

5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.
6. 10.1 7.6

如果您的issue是关于安装或环境，您可以先查询[安装文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)尝试解决~

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL.md

**Comment by heavengate** [comment]
你好，请问一下是什么应用场景需要类别里面带空格呢，我们确认一下支持一下~

**Comment by yyyssq** [comment]
比如说虫子的英文名金针虫  Golden needle worm

**Comment by yyyssq** [comment]
> 你好，请问一下是什么应用场景需要类别里面带空格呢，我们确认一下支持一下~

比如说虫子的英文名金针虫 Golden needle worm
