### ISSUE TITLE
MultiscaleTestResize报错

### ISSUE THREAD

**Issue by huilin16** [PaddlePaddle/PaddleDetection#3831]
MultiscaleTestResize报错

配置如下：
EvalReader:
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 2, target_size: [1600, 1333], keep_ratio: True}
  - MultiscaleTestResize: {origin_target_size: [1600, 1333], target_size: [[1280, 2666], [1344, 2666], [1408, 2666], [1472, 2666], [1536, 2666], [1600, 2666]]}

报错如下

/home/aistudio/PaddleDetection/ppdet/data/reader.py:80: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  f, e, str(stack_info)))
[07/30 10:17:35] reader WARNING: fail to map batch transform [PadBatch_da1d21] with error: list indices must be integers or slices, not str and stack:
Traceback (most recent call last):
  File "/home/aistudio/PaddleDetection/ppdet/data/reader.py", line 75, in __call__
    data = f(data)
  File "/home/aistudio/PaddleDetection/ppdet/data/transform/batch_operators.py", line 61, in __call__
    max_shape = np.array([data['image'].shape for data in samples]).max(
  File "/home/aistudio/PaddleDetection/ppdet/data/transform/batch_operators.py", line 61, in <listcomp>
    max_shape = np.array([data['image'].shape for data in samples]).max(
TypeError: list indices must be integers or slices, not str

ERROR:root:DataLoader reader thread raised an exception!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 411, in _thread_loop
    batch = self._get_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 525, in _get_data
    batch.reraise()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 168, in reraise
    raise self.exc_type(msg)
TypeError: DataLoader worker(0) caught TypeError with message:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 228, in _worker_loop
    batch = fetcher.fetch(indices)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 66, in fetch
    data = self.collate_fn(data)
  File "/home/aistudio/PaddleDetection/ppdet/data/reader.py", line 81, in __call__
    raise e
  File "/home/aistudio/PaddleDetection/ppdet/data/reader.py", line 75, in __call__
    data = f(data)
  File "/home/aistudio/PaddleDetection/ppdet/data/transform/batch_operators.py", line 61, in __call__
    max_shape = np.array([data['image'].shape for data in samples]).max(
  File "/home/aistudio/PaddleDetection/ppdet/data/transform/batch_operators.py", line 61, in <listcomp>
    max_shape = np.array([data['image'].shape for data in samples]).max(
TypeError: list indices must be integers or slices, not str

[07/30 10:17:36] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/aistudio/PaddleDetection/output/ship_vis_14/best_model.pdparams
Traceback (most recent call last):
  File "tools/eval.py", line 134, in <module>
    main()
  File "tools/eval.py", line 130, in main
    run(FLAGS, cfg)
  File "tools/eval.py", line 105, in run
    trainer.evaluate()
  File "/home/aistudio/PaddleDetection/ppdet/engine/trainer.py", line 389, in evaluate
    self._eval_with_loader(self.loader)
  File "/home/aistudio/PaddleDetection/ppdet/engine/trainer.py", line 363, in _eval_with_loader
    for step_id, data in enumerate(loader):
  File "/home/aistudio/PaddleDetection/ppdet/data/reader.py", line 211, in __next__
    return next(self.loader)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 585, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

[07/30 10:17:36] reader WARNING: fail to map batch transform [PadBatch_da1d21] with error: list indices must be integers or slices, not str and stack:
Traceback (most recent call last):
  File "/home/aistudio/PaddleDetection/ppdet/data/reader.py", line 75, in __call__
    data = f(data)
  File "/home/aistudio/PaddleDetection/ppdet/data/transform/batch_operators.py", line 61, in __call__
    max_shape = np.array([data['image'].shape for data in samples]).max(
  File "/home/aistudio/PaddleDetection/ppdet/data/transform/batch_operators.py", line 61, in <listcomp>
    max_shape = np.array([data['image'].shape for data in samples]).max(
TypeError: list indices must be integers or slices, not str

/home/aistudio/PaddleDetection/ppdet/data/reader.py:80: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  f, e, str(stack_info)))
[07/30 10:17:37] reader WARNING: fail to map batch transform [PadBatch_da1d21] with error: list indices must be integers or slices, not str and stack:
Traceback (most recent call last):
  File "/home/aistudio/PaddleDetection/ppdet/data/reader.py", line 75, in __call__
    data = f(data)
  File "/home/aistudio/PaddleDetection/ppdet/data/transform/batch_operators.py", line 61, in __call__
    max_shape = np.array([data['image'].shape for data in samples]).max(
  File "/home/aistudio/PaddleDetection/ppdet/data/transform/batch_operators.py", line 61, in <listcomp>
    max_shape = np.array([data['image'].shape for data in samples]).max(
TypeError: list indices must be integers or slices, not str

**Comment by jerrywgz** [comment]
请问使用的是哪个配置文件呢，我排查下

**Comment by huilin16** [comment]
> 请问使用的是哪个配置文件呢，我排查下

configs/cascade_rcnn/_base_/cascade_mask_fpn_reader.yml

**Comment by jerrywgz** [comment]
确认了下，目前multiscaletest在动态图下还不支持，我们会计划排期做的
