### ISSUE TITLE
在使用eval.py时候遇到 no display name and no $DISPLAY environment variable错误

### ISSUE THREAD

**Issue by yyyssq** [PaddlePaddle/PaddleDetection#3850]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://paddledetection.readthedocs.io/FAQ.html) /I have read the [FAQ documentation](https://paddledetection.readthedocs.io/FAQ.html) but cannot get the expected help.

## 描述问题/Describe the bug
在训练好之后，使用eval.py 报错

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?
2. python -u tools/eval.py -c configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.yml --classwise

```none
请填写命令/A placeholder for the command.
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.
3. 没有更改过代码，配置文件使用的是faster_rcnn_r50_fpn_1x_coco.yml ，加入了train，test，eval的文件路径

3. 您使用的数据集是？/What dataset did you use?
4. 自定义数据集

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.
5. Traceback (most recent call last):
  File "tools/eval.py", line 134, in <module>
    main()
  File "tools/eval.py", line 130, in main
    run(FLAGS, cfg)
  File "tools/eval.py", line 105, in run
    trainer.evaluate()
  File "/home/aistudio/PaddleDetection-2.0/PaddleDetection-release-2.0/ppdet/engine/trainer.py", line 354, in evaluate
    self._eval_with_loader(self.loader)
  File "/home/aistudio/PaddleDetection-2.0/PaddleDetection-release-2.0/ppdet/engine/trainer.py", line 347, in _eval_with_loader
    metric.accumulate()
  File "/home/aistudio/PaddleDetection-2.0/PaddleDetection-release-2.0/ppdet/metrics/metrics.py", line 116, in accumulate
    classwise=self.classwise)
  File "/home/aistudio/PaddleDetection-2.0/PaddleDetection-release-2.0/ppdet/metrics/coco_utils.py", line 131, in cocoapi_eval
    file_name='{}_precision_recall_curve.jpg'.format(nm["name"]))
  File "/home/aistudio/PaddleDetection-2.0/PaddleDetection-release-2.0/ppdet/metrics/map_utils.py", line 48, in draw_pr_curve
    plt.cla()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/pyplot.py", line 3811, in cla
    ret = gca().cla()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/pyplot.py", line 969, in gca
    return gcf().gca(**kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/pyplot.py", line 586, in gcf
    return figure()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 1046, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
2. 使用的是paddle2.0  运行环境是paddle ai studio 平台

2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：

4. 请问您使用的Python版本是？/ Please provide the version of Python you used.
5. 3.7

5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.
6. 10.1  7.6

如果您的issue是关于安装或环境，您可以先查询[安装文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)尝试解决~

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL.md

**Comment by yyyssq** [comment]
错误已解决，找到matplotlib的包，在import matplotlib这一段后面加入matplotlib.use(
        'Agg'
        ) 就好啦

**Comment by Dekadenc** [comment]
> 错误已解决，找到matplotlib的包，在import matplotlib这一段后面加入matplotlib.use( 'Agg' ) 就好啦

请问这个地方具体在哪个文件的哪个地方呀，可以截图看下嘛，感谢~
