### ISSUE TITLE
tools/export_model.py

### ISSUE THREAD

**Issue by DRNOWI** [PaddlePaddle/PaddleDetection#3852]
Traceback (most recent call last):
  File "tools/export_model.py", line 108, in <module>
    main()
  File "tools/export_model.py", line 104, in main
    run(FLAGS, cfg)
  File "tools/export_model.py", line 72, in run
    trainer.export(FLAGS.output_dir)
  File "/usr/local/lib/python3.6/dist-packages/ppdet/engine/trainer.py", line 507, in export
    input_spec, static_model.forward.main_program,
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 534, in main_program
    concrete_program = self.concrete_program
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 454, in concrete_program
    return self.concrete_program_specify_input_spec(input_spec=None)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program_specify_input_spec
    *desired_input_spec)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 702, in _build_once
    class_instance=cache_key.class_instance)
  File "<decorator-gen-65>", line 2, in from_func_spec
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 620, in from_func_spec
    static_func = convert_to_static(dygraph_function)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 141, in convert_to_static
    static_func = _FUNCTION_CACHE.convert_with_cache(function)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 78, in convert_with_cache
    static_func = self._convert(func)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 122, in _convert
    create_and_update_origin_info_map(root_wrapper.node, static_func)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/origin_info.py", line 163, in create_and_update_origin_info_map
    for t_node, s_node in ast_walk(transformed_node, static_node):
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/dygraph_to_static/origin_info.py", line 241, in ast_walk
    t_node_child = getattr(t_node, field)
AttributeError: 'Assign' object has no attribute 'type_comment'

**Comment by cjt222** [comment]
应该是版本适配问题，paddle2.0.0版本是ok的

**Comment by wangxinxin08** [comment]
请按照issue模版提issue？描述自己的Paddle版本，PaddleDetection版本，运行命令等信息。另外，请使用PaddleDetection release/2.1以及PaddlePaddle 2.1.1版本，并注意保持gast版本为0.4.0(pip install gast==0.4.0)

**Comment by yhygta** [comment]
> 请按照issue模版提issue？描述自己的Paddle版本，PaddleDetection版本，运行命令等信息。另外，请使用PaddleDetection release/2.1以及PaddlePaddle 2.1.1版本，并注意保持gast版本为0.4.0(pip install gast==0.4.0)

我也遇到同样的问题，的确是需要保持gast版本为0.4.0，就解决了
