### ISSUE TITLE
[BUG]使用python/eval报Cuda error(700)

### ISSUE THREAD

**Issue by thorory** [PaddlePaddle/PaddleDetection#3854]
## 描述问题/Describe the bug
训练完的模型使用eval进行模型评估时报 Cuad error（700）错误

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?

```
python3 tools/eval.py  -c configs/yolov3/yolov3_mobilenet_v1_smoke.yml -o weights=output/yolov3_mobilenet_v1_smoke/model_final.pdparams
```

4. 请提供您出现的报错信息及相关log。

```
[08/02 09:29:36] ppdet.engine INFO: Eval iter: 0
[08/02 09:29:37] ppdet.data.transform.operators WARNING: The actual image height: 4032 is not equal to the height: 3024.0 in annotation, and update sample['h'] by actual image height.
[08/02 09:29:37] ppdet.data.transform.operators WARNING: The actual image width: 3024 is not equal to the width: 4032.0 in annotation, and update sample['w'] by actual image width.
[08/02 09:29:38] ppdet.data.transform.operators WARNING: The actual image height: 480 is not equal to the height: 0.0 in annotation, and update sample['h'] by actual image height.
[08/02 09:29:38] ppdet.data.transform.operators WARNING: The actual image width: 853 is not equal to the width: 0.0 in annotation, and update sample['w'] by actual image width.
[08/02 09:29:38] ppdet.engine INFO: Eval iter: 100
[08/02 09:29:38] ppdet.data.transform.operators WARNING: The actual image height: 561 is not equal to the height: 0.0 in annotation, and update sample['h'] by actual image height.
[08/02 09:29:38] ppdet.data.transform.operators WARNING: The actual image width: 853 is not equal to the width: 0.0 in annotation, and update sample['w'] by actual image width.
Traceback (most recent call last):
  File "tools/eval.py", line 134, in <module>
    main()
  File "tools/eval.py", line 130, in main
    run(FLAGS, cfg)
  File "tools/eval.py", line 105, in run
    trainer.evaluate()
  File "/home/dell/anaconda3/lib/python3.8/site-packages/paddledet-2.1.0-py3.8.egg/ppdet/engine/trainer.py", line 387, in evaluate
    self._eval_with_loader(self.loader)
  File "/home/dell/anaconda3/lib/python3.8/site-packages/paddledet-2.1.0-py3.8.egg/ppdet/engine/trainer.py", line 369, in _eval_with_loader
    metric.update(data, outs)
  File "/home/dell/anaconda3/lib/python3.8/site-packages/paddledet-2.1.0-py3.8.egg/ppdet/metrics/metrics.py", line 257, in update
    gt_box = gt_boxes[i].numpy()
OSError: (External)  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/9.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/gpu_info.cc:394)
```

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
paddlepaddle：2.1.1.post112
PaddleDetection：2.1.0
python：3.8.5
cuda： release 11.1, V11.1.74
cudnn：8.1.1
os：ubuntu 18.04

**Comment by wangxinxin08** [comment]
这个是由于标注的gt有问题导致的，建议自行检查下gt_boxes

**Comment by thorory** [comment]
> 这个是由于标注的gt有问题导致的，建议自行检查下gt_boxes

修复标注后，已验证通过，谢谢。
