### ISSUE TITLE
动态图eval验证的时候报错

### ISSUE THREAD

**Issue by xupengao** [PaddlePaddle/PaddleDetection#3868]
训练自定义数据集 faster rcnn 用的paddledetection 2.1 环境3090服务器，cuda11.2 

命令：python -m paddle.distributed.launch --gpus 1,2  tools/train.py -c configs/faster_rcnn/faster_rcnn_r50_vd_fpn_1x_coco.yml  --eval   

报错：

Traceback (most recent call last):
  File "tools/train.py", line 139, in <module>
    main()
  File "tools/train.py", line 135, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 110, in run
    trainer.train(FLAGS.eval)
  File "/data/xupengao/anaconda3/envs/py3.7/lib/python3.7/site-packages/ppdet/engine/trainer.py", line 350, in train
    self._eval_with_loader(self._eval_loader)
  File "/data/xupengao/anaconda3/envs/py3.7/lib/python3.7/site-packages/ppdet/engine/trainer.py", line 366, in _eval_with_loader
    outs = self.model(data)
  File "/data/xupengao/anaconda3/envs/py3.7/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/data/xupengao/anaconda3/envs/py3.7/lib/python3.7/site-packages/ppdet/modeling/architectures/meta_arch.py", line 29, in forward
    out = self.get_pred()
  File "/data/xupengao/anaconda3/envs/py3.7/lib/python3.7/site-packages/ppdet/modeling/architectures/faster_rcnn.py", line 104, in get_pred
    bbox_pred, bbox_num = self._forward()
  File "/data/xupengao/anaconda3/envs/py3.7/lib/python3.7/site-packages/ppdet/modeling/architectures/faster_rcnn.py", line 91, in _forward
    im_shape, scale_factor)
  File "/data/xupengao/anaconda3/envs/py3.7/lib/python3.7/site-packages/ppdet/modeling/post_process.py", line 120, in get_pred
    scaled_bbox = pred_bbox / scale_factor_list
  File "/data/xupengao/anaconda3/envs/py3.7/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 250, in __impl__
    return math_op(self, other_var, 'axis', axis)
RuntimeError: (PreconditionNotMet) The Tensor's element number must be equal or greater than zero. The Tensor's shape is [-1, 4] now
  [Hint: Expected numel() >= 0, but received numel():-4 < 0:0.] (at /paddle/paddle/fluid/framework/tensor.cc:59)
  [operator < elementwise_div > error]
INFO 2021-08-03 01:21:58,448 launch_utils.py:327] terminate all the procs
ERROR 2021-08-03 01:21:58,449 launch_utils.py:584] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-08-03 01:22:01,451 launch_utils.py:327] terminate all the procs
 
单独运行eval也是报错的，训练没问题，只有eval不行

**Comment by lyuwenyu** [comment]
这个你用最新的develop试一下
