### ISSUE TITLE
ttfnet_darkner53使用VOC数据集训练报错

### ISSUE THREAD

**Issue by TangJiamin** [PaddlePaddle/PaddleDetection#3871]
# 使用自己的VOC数据集训练ttfnet_darknet53时报错，报错如下：
```
[08/03 13:25:06] reader WARNING: fail to map op [Gt2TTFTarget_005a29] with error: 'is_crowd' and stack:
Traceback (most recent call last):
  File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/ppdet/data/reader.py", line 75, in __call__
    data = f(data)
  File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/ppdet/data/transform/batch_operators.py", line 590, in __call__
    sample.pop('is_crowd')
KeyError: 'is_crowd'

ERROR:root:DataLoader reader thread raised an exception!
Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 411, in _thread_loop
    batch = self._get_data()
  File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 525, in _get_data
    batch.reraise()
  File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 168, in reraise
    raise self.exc_type(msg)
KeyError: 'DataLoader worker(0) caught KeyError with message:\nTraceback (most recent call last):\n  File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 228, in _worker_loop\n    batch = fetcher.fetch(indices)\n  File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 66, in fetch\n    data = self.collate_fn(data)\n  File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/ppdet/data/reader.py", line 80, in __call__\n    raise e\n  File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/ppdet/data/reader.py", line 75, in __call__\n    data = f(data)\n  File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/ppdet/data/transform/batch_operators.py", line 590, in __call__\n    sample.pop(\'is_crowd\')\nKeyError: \'is_crowd\'\n'
    run(FLAGS, cfg)

  File "tools/train.py", line 111, in run
    trainer.train(FLAGS.eval)
  File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/ppdet/engine/trainer.py", line 256, in train
    for step_id, data in enumerate(self.loader):
  File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/ppdet/data/reader.py", line 216, in __next__
    data = next(self.loader)
  File "/home/tangjiamin/anaconda3/envs/paddle2.1/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 585, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)
```
# 配置文件
## config文件
```
_BASE_: [
  '../datasets/voc.yml',
  '../runtime.yml',
  '_base_/optimizer_1x.yml',
  '_base_/ttfnet_darknet53.yml',
  '_base_/ttfnet_reader.yml',
]
weights: output/ttfnet_darknet53_1x_voc/best_model
```
## Reader文件
```
worker_num: 1
TrainReader:
  sample_transforms:
  - Decode: {}
  - RandomFlip: {prob: 0.5}
  - Resize: {interp: 1, target_size: [512, 512], keep_ratio: False}
  - NormalizeImage: {mean: [123.675, 116.28, 103.53], std: [58.395, 57.12, 57.375], is_scale: false}
  - Permute: {}
  batch_transforms:
  - Gt2TTFTarget: {down_ratio: 4}
  - PadBatch: {pad_to_stride: 32}
  batch_size: 12
  shuffle: true
  drop_last: true
  use_shared_memory: true

EvalReader:
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 1, target_size: [512, 512], keep_ratio: False}
  - NormalizeImage: {is_scale: false, mean: [123.675, 116.28, 103.53], std: [58.395, 57.12, 57.375]}
  - Permute: {}
  batch_size: 1
  drop_last: false

TestReader:
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 1, target_size: [512, 512], keep_ratio: False}
  - NormalizeImage: {is_scale: false, mean: [123.675, 116.28, 103.53], std: [58.395, 57.12, 57.375]}
  - Permute: {}
  batch_size: 1
  drop_last: false
```
## Dataset文件
```
metric: VOC
#map_type: 11point
map_type: integral
num_classes: 1
#num_classes: 20

TrainDataset:
  !VOCDataSet
    #dataset_dir: dataset/voc
    dataset_dir: ./data/2/trainval
    anno_path: trainval.txt
    label_list: label_list.txt
    #data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !VOCDataSet
    #dataset_dir: dataset/voc
    dataset_dir: ./data/2/test
    anno_path: test.txt
    label_list: label_list.txt
    #data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

TestDataset:
  !ImageFolder
    #anno_path: dataset/voc/label_list.txt
    anno_path: ./data/2/test/label_list.txt
```

**Comment by nemonameless** [comment]
您的Dataset config文件data_fields不需要改动就可以训起来的。改配置文件前请先确保直接训VOC数据集就可以训起来，然后使用自定义数据集如果报错则可能是转voc格式这步的问题了。建议还是转coco格式训练ttfnet稳妥点。

**Comment by TangJiamin** [comment]
> 您的Dataset config文件data_fields不需要改动就可以训起来的。改配置文件前请先确保直接训VOC数据集就可以训起来，然后使用自定义数据集如果报错则可能是转voc格式这步的问题了。建议还是转coco格式训练ttfnet稳妥点。

直接训VOC也是报这个错，我就尝试改了config。我看了一下数据格式，我的VOC标签里面没有‘iscrowd’，但coco的标签里面有，把VOC转成COCO以后就可以训练了
