### ISSUE TITLE
[BUG] 无标签学习训练遇到传两张以上的（bs>1），图片既有标注的又有没标注的，会传到bbox回归的loss里会报错

### ISSUE THREAD

**Issue by Gaojun211** [PaddlePaddle/PaddleDetection#3884]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://paddledetection.readthedocs.io/FAQ.html) /I have read the [FAQ documentation](https://paddledetection.readthedocs.io/FAQ.html) but cannot get the expected help.
3. 确认bug是否在新版本里还未修复/The bug has not been fixed in the latest version.

## 描述问题/Describe the bug
无标签学习训练过程中，无标注的rois坐标信息传到bbox回归的loss里。单张没标签的不传，遇到传两张以上的（bs>1），图片既有标注的又有没标注的，会传到bbox回归的loss里，从而报错。
## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?
python tools/train.py -c configs/faster_rcnn/faster_rcnn_r50_vd_fpn_sfmodel.yml  --use_vdl=True  --vdl_log_dir=vdl_dir/scalar_fasterrcnn
```none
请填写命令/A placeholder for the command.
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.
**faster_rcnn_r50_vd_fpn_sfmodel.yml**
```shell
_BASE_: [
  '../datasets/coco_detection_sfmodel.yml',
  '../runtime.yml',
  '_base_/optimizer_1x.yml',
  '_base_/faster_rcnn_r50_fpn.yml',
  '_base_/faster_fpn_reader.yml',
]
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_vd_pretrained.pdparams
weights: output/faster_rcnn_r50_vd_fpn_2x_sfmodel/model_final

TrainReader:
    batch_size: 2

ResNet:
  # index 0 stands for res2
  depth: 50
  variant: d
  norm_type: bn
  freeze_at: 0
  return_idx: [0,1,2,3]
  num_stages: 4

epoch: 48
LearningRate:
  base_lr: 0.00125
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [222000, 296000]
  - !LinearWarmup
    start_factor: 0.1
    steps: 1000
```
**coco_detection_sfmodel.yml**
```shell
metric: COCO
num_classes: 2

TrainDataset:
  !COCODataSet
    image_dir: images
    anno_path: train.json
    dataset_dir: dataset/sfmodel
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']
    allow_empty: true
    empty_ratio: 0.1

EvalDataset:
  !COCODataSet
    image_dir: eval_imgs
    anno_path: eval.json
    dataset_dir: dataset/sfmodel

TestDataset:
  !ImageFolder
    anno_path: dataset/sfmodel/eval.json
```
3. 您使用的数据集是？/What dataset did you use?
烟火2类数据集，加上无标签数据。
4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.
[https://github.com/PaddlePaddle/PaddleDetection/issues/3790] (url)

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
Paddle2.1.1 ppdet2.1
2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：
ubuntu服务器
4. 请问您使用的Python版本是？/ Please provide the version of Python you used.
python3.6
5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.

cuda11.2 cudnn8.0
如果您的issue是关于安装或环境，您可以先查询[安装文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)尝试解决~

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL.md

**Comment by jerrywgz** [comment]
问题已经复现，正在排查，感谢反馈～

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/pull/3890 已修复

**Comment by Gaojun211** [comment]
> #3890 已修复

运行几轮后出现新的error
```shell
[08/05 07:32:53] ppdet.engine INFO: Epoch: [0] [  640/24691] learning_rate: 0.000845 loss_rpn_cls: 0.027266 loss_rpn_reg: 0.016378 loss_bbox_cls: 0.043653 loss_bbox_reg: 0.032974 loss: 0.132321 eta: 4 days, 14:57:55 batch_cost: 0.3261 data_cost: 0.0004 ips: 6.1336 images/s
[08/05 07:32:59] ppdet.engine INFO: Epoch: [0] [  660/24691] learning_rate: 0.000868 loss_rpn_cls: 0.026518 loss_rpn_reg: 0.009928 loss_bbox_cls: 0.068825 loss_bbox_reg: 0.063680 loss: 0.172749 eta: 4 days, 14:52:08 batch_cost: 0.3277 data_cost: 0.0003 ips: 6.1025 images/s
[08/05 07:33:06] ppdet.engine INFO: Epoch: [0] [  680/24691] learning_rate: 0.000890 loss_rpn_cls: 0.034191 loss_rpn_reg: 0.021317 loss_bbox_cls: 0.066081 loss_bbox_reg: 0.051245 loss: 0.195302 eta: 4 days, 14:47:25 batch_cost: 0.3290 data_cost: 0.0003 ips: 6.0784 images/s
[08/05 07:33:12] ppdet.engine INFO: Epoch: [0] [  700/24691] learning_rate: 0.000913 loss_rpn_cls: 0.023690 loss_rpn_reg: 0.007840 loss_bbox_cls: 0.054181 loss_bbox_reg: 0.036432 loss: 0.132393 eta: 4 days, 14:31:55 batch_cost: 0.3094 data_cost: 0.0003 ips: 6.4643 images/s
Traceback (most recent call last):
  File "tools/train.py", line 139, in <module>
    main()
  File "tools/train.py", line 135, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 110, in run
    trainer.train(FLAGS.eval)
  File "/data/gaojun/paddle/PaddleDetection/ppdet/engine/trainer.py", line 306, in train
    outputs = model(data)
  File "/data/gaojun/miniconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/data/gaojun/paddle/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 26, in forward
    out = self.get_loss()
  File "/data/gaojun/paddle/PaddleDetection/ppdet/modeling/architectures/faster_rcnn.py", line 95, in get_loss
    rpn_loss, bbox_loss = self._forward()
  File "/data/gaojun/paddle/PaddleDetection/ppdet/modeling/architectures/faster_rcnn.py", line 78, in _forward
    self.inputs)
  File "/data/gaojun/miniconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/data/gaojun/paddle/PaddleDetection/ppdet/modeling/heads/bbox_head.py", line 237, in forward
    rois, rois_num, targets = self.bbox_assigner(rois, rois_num, inputs)
  File "/data/gaojun/paddle/PaddleDetection/ppdet/modeling/proposal_generator/target_layer.py", line 152, in __call__
    self.cascade_iou[stage])
  File "/data/gaojun/paddle/PaddleDetection/ppdet/modeling/proposal_generator/target.py", line 208, in generate_proposal_target
    num_classes, use_random, is_cascade)
  File "/data/gaojun/paddle/PaddleDetection/ppdet/modeling/proposal_generator/target.py", line 260, in sample_bbox
    num_classes, use_random)
  File "/data/gaojun/paddle/PaddleDetection/ppdet/modeling/proposal_generator/target.py", line 131, in subsample_labels
    paddle.logical_and(labels != -1, labels != bg_label))
  File "/data/gaojun/miniconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 12194, in logical_and
    op_name="logical_and", x=x, y=y, name=name, out=out, binary_op=True)
  File "/data/gaojun/miniconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 12133, in _logical_op
    return op(x, y)
SystemError: (Fatal) Operator logical_and raises an thrust::system::system_error exception.
The exception content is
:transform: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered. (at /paddle/paddle/fluid/imperative/tracer.cc:192)
```
咨询了同事，他觉得layer层，device和内存之间数据通信的过程有问题，不知道是否是这样？

**Comment by jerrywgz** [comment]
我这边测试没有出现这样的问题，可能是和无标签数据导致某些计算访问越界导致的。可以先初步排查下：1.报错是否稳定复现，是不是每次报错都在相同位置；2.可以打印下输入图片的image_id,看下是不是每次报错对应的都是相同类型的图片；3.如果能稳定报错，可以打印下报错前的tensor shape

**Comment by Gaojun211** [comment]
当前设置，单卡bs=4
1、报错不稳定，有时候遇到全存在标签，有时候混着无标签数据；
2、训练过程有时候出现lossNAN的情况，
```shell
OSError: (External)  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/9.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/gpu_info.cc:394)
  [operator < squeeze2 > error]
```
![image](https://user-images.githubusercontent.com/44492927/128466343-d94c6674-765d-433b-8f02-9e73066be34c.png)
![image](https://user-images.githubusercontent.com/44492927/128466434-3086e6d0-2849-459b-a28e-a929fa05247c.png)
调小empty_ratio: 0.4->0.2或者bs4->3后报之前的error
您这边有什么建议吗

**Comment by jerrywgz** [comment]
能否提供一小部分可以复现的数据吗，看起来应该还是某个计算为空导致的异常

**Comment by Gaojun211** [comment]
数据集地址：https://aistudio.baidu.com/aistudio/datasetdetail/103629
提取了部分训练集，原本有39506张有标签的图像。

**Comment by Gaojun211** [comment]
不好意思，数据需要保密。
