### ISSUE TITLE
在训练过程中随机出现错误：RuntimeError: DataLoader 1 workers exit unexpectedly

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/PaddleDetection#3918]
- PaddlePaddle 2.1.2
 - Ubuntu 18.04
 - 2080ti CUDA 10.2

错误如下，设置1线程，2线程读取数据都会出错，2张显卡训练。
```
ERROR:root:DataLoader reader thread raised an exception!
Traceback (most recent call last):
  File "train.py", line 102, in <module>
    main()
  File "train.py", line 98, in main
    run(FLAGS, cfg)
  File "train.py", line 71, in run
    trainer.train(FLAGS.eval)
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/ppdet/engine/trainer.py", line 339, in train
    for step_id, data in enumerate(self.loader):
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/ppdet/data/reader.py", line 209, in __next__
    return next(self.loader)
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 565, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 462, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
INFO 2021-08-06 18:10:23,310 launch_utils.py:327] terminate all the procs
ERROR 2021-08-06 18:10:23,325 launch_utils.py:584] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-08-06 18:10:26,326 launch_utils.py:327] terminate all the procs
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 391, in _thread_loop
    batch = self._get_data()
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 478, in _get_data
    "pids: {}".format(len(failed_workers), pids))
RuntimeError: DataLoader 1 workers exit unexpectedly, pids: 20968

```

**Comment by wangxinxin08** [comment]
可以把log_dir的workerlog.0发一下看下

**Comment by yeyupiaoling** [comment]
[workerlog.zip](https://github.com/PaddlePaddle/PaddleDetection/files/6952444/workerlog.zip)

**Comment by wangxinxin08** [comment]
看了下log文件缺乏有效的报错信息，可以贴下你运行的PaddlePaddle版本，PaddleDetection版本以及运行的命令，除此之外也可以贴下修改的内容

**Comment by yeyupiaoling** [comment]
- PaddlePaddle 2.1.2
 - PaddleDetection 2.2

```
nohup python -m paddle.distributed.launch --gpus '0,1' train.py --config=config_ppyolo/ppyolo_r50vd_dcn_1x_voc.yml >> nohup.out 2>&1 &
```

配置文件train中的batch_size改为8

训练代码：
```python
import ppdet.utils.check as check
from ppdet.core.workspace import load_config, merge_config
from ppdet.engine import Trainer, init_parallel_env, init_fleet_env
from ppdet.slim import build_slim_model
from ppdet.utils.logger import setup_logger

from utils import ArgsParser

logger = setup_logger('train')


def parse_args():
    parser = ArgsParser()
    parser.add_argument("--config",
                        type=str,
                        default="config_ppyolo/ppyolo_r50vd_dcn_1x_voc.yml",
                        help="configuration file to use")
    parser.add_argument("--eval",
                        action='store_true',
                        default=True,
                        help="Whether to perform evaluation in train")
    parser.add_argument("--resume",
                        default=None,
                        help="weights path for resume")
    parser.add_argument("--slim_config",
                        default=None,
                        type=str,
                        help="Configuration file of slim method.")
    parser.add_argument("--fp16",
                        action='store_true',
                        default=False,
                        help="Enable mixed precision training.")
    parser.add_argument("--fleet",
                        action='store_true',
                        default=False,
                        help="Use fleet or not")
    parser.add_argument("--use_vdl",
                        type=bool,
                        default=False,
                        help="whether to record the data to VisualDL.")
    parser.add_argument('--vdl_log_dir',
                        type=str,
                        default="log",
                        help='VisualDL logging directory for scalar.')
    parser.add_argument('--save_prediction_only',
                        action='store_true',
                        default=False,
                        help='Whether to save the evaluation results only')
    args = parser.parse_args()
    return args


def run(FLAGS, cfg):
    # init fleet environment
    if cfg.fleet:
        init_fleet_env()
    else:
        # init parallel environment if nranks > 1
        init_parallel_env()

    # build trainer
    trainer = Trainer(cfg, mode='train')

    # load weights
    if FLAGS.resume is not None:
        trainer.resume_weights(FLAGS.resume)
    elif 'pretrain_weights' in cfg and cfg.pretrain_weights:
        trainer.load_weights(cfg.pretrain_weights)

    # training
    trainer.train(FLAGS.eval)


def main():
    FLAGS = parse_args()
    cfg = load_config(FLAGS.config)
    for key in cfg.keys():
        value = cfg[key]
        if value != {}:
            print(key, ":", value)
    cfg['fp16'] = FLAGS.fp16
    cfg['fleet'] = FLAGS.fleet
    cfg['use_vdl'] = FLAGS.use_vdl
    cfg['vdl_log_dir'] = FLAGS.vdl_log_dir
    cfg['save_prediction_only'] = FLAGS.save_prediction_only
    merge_config(FLAGS.opt)

    if 'norm_type' in cfg and cfg['norm_type'] == 'sync_bn' and not cfg.use_gpu:
        cfg['norm_type'] = 'bn'

    if FLAGS.slim_config:
        cfg = build_slim_model(cfg, FLAGS.slim_config)

    check.check_config(cfg)
    check.check_gpu(cfg.use_gpu)
    check.check_version()

    run(FLAGS, cfg)


if __name__ == "__main__":
    main()

```

**Comment by heavengate** [comment]
上面还有其他报错信息么？
另外可以看下`free -h`查下内存信息和`df -h`看下共享内存大小

**Comment by yeyupiaoling** [comment]
@heavengate 没有了，我已经把全部的日志都提供了。

```
              总计         已用        空闲      共享    缓冲/缓存    可用
内存：         31G        9.5G         11G        371M         10G         20G
交换：        2.0G         58M        1.9G
```

**Comment by yeyupiaoling** [comment]
@heavengate 有时候还会突然出这种错，

```
[08/10 11:01:30] ppdet.engine INFO: Epoch: [102] [ 60/392] learning_rate: 0.001000 loss_xy: 0.371703 loss_wh: 0.343739 loss_iou: 2.827374 loss_iou_aware: 0.408658 loss_obj: 1.766710 loss_cls: 0.012176 loss: 5.874555 eta: 5 days, 20:27:04 batch_cost: 3.8631 data_cost: 2.7971 ips: 2.0709 images/s
[08/10 11:02:45] ppdet.engine INFO: Epoch: [102] [ 80/392] learning_rate: 0.001000 loss_xy: 0.434823 loss_wh: 0.401190 loss_iou: 3.477818 loss_iou_aware: 0.474944 loss_obj: 1.945752 loss_cls: 0.012716 loss: 6.829866 eta: 5 days, 15:32:46 batch_cost: 3.6595 data_cost: 3.1218 ips: 2.1861 images/s


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
1   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, paddle::platform::Place const&, bool, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
2   std::shared_ptr<paddle::imperative::details::NameVarMapTrait<paddle::imperative::VarBase>::Type> paddle::imperative::PrepareData<paddle::imperative::VarBase>(paddle::framework::OperatorWithKernel const&, paddle::imperative::details::NameVarMapTrait<paddle::imperative::VarBase>::Type const&, paddle::framework::OpKernelType const&)
3   paddle::framework::TransformData(paddle::framework::OpKernelType const&, paddle::framework::OpKernelType const&, paddle::framework::Tensor const&, paddle::framework::Tensor*)
4   paddle::framework::TransDataDevice(paddle::framework::Tensor const&, paddle::platform::Place const&, paddle::framework::Tensor*)
5   paddle::platform::CUDADeviceContext::Wait() const
6   paddle::platform::stream::CUDAStream::Wait() const
7   paddle::framework::SignalHandle(char const*, int)
8   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1628564619 (unix time) try "date -d @1628564619" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x3e8000004ad) received by PID 1217 (TID 0x7f2af44e7740) from PID 1197 ***]


```

**Comment by yeyupiaoling** [comment]
@heavengate 如果用单卡也会出现这种情况：

```
[08/10 23:36:44] ppdet.engine INFO: Epoch: [109] [240/784] learning_rate: 0.001000 loss_xy: 0.401997 loss_wh: 0.512031 loss_iou: 3.864309 loss_iou_aware: 0.515340 loss_obj: 2.387406 loss_cls: 0.014231 loss: 7.705738 eta: 8 days, 18:49:14 batch_cost: 3.3411 data_cost: 2.9746 ips: 2.3944 images/s
ERROR:root:DataLoader reader thread raised an exception!
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 462, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 391, in _thread_loop
    batch = self._get_data()
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 478, in _get_data
    "pids: {}".format(len(failed_workers), pids))
RuntimeError: DataLoader 1 workers exit unexpectedly, pids: 13046

Traceback (most recent call last):
  File "train.py", line 102, in <module>
    main()
  File "train.py", line 98, in main
    run(FLAGS, cfg)
  File "train.py", line 71, in run
    trainer.train(FLAGS.eval)
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/ppdet/engine/trainer.py", line 339, in train
    for step_id, data in enumerate(self.loader):
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/ppdet/data/reader.py", line 209, in __next__
    return next(self.loader)
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 565, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

```

**Comment by yeyupiaoling** [comment]
我把图片缩放到相对比较小再训练好像就没有问题了

**Comment by tyrink** [comment]
> 把图片缩放到相对比较小再训练好

您好，我最近也遇到了这个问题，请问“把图片缩放到相对比较小”是先resize到更小的空间尺寸，加载数据时再resize回原始大小吗？

**Comment by CXfighting** [comment]
> > 把图片缩放到相对比较小再训练好
> 
> 您好，我最近也遇到了这个问题，请问“把图片缩放到相对比较小”是先resize到更小的空间尺寸，加载数据时再resize回原始大小吗？



> > 把图片缩放到相对比较小再训练好
> 
> 您好，我最近也遇到了这个问题，请问“把图片缩放到相对比较小”是先resize到更小的空间尺寸，加载数据时再resize回原始大小吗？

您好，我也遇到了同样的问题，请问您解决了吗，您是否方便交流下，我的qq/微信838700598，还望您不吝赐教。
