### ISSUE TITLE
ppyolo_r50vd_dcn_2x_coco训练308个epoch停止，该怎么没解决？

### ISSUE THREAD

**Issue by yumeng88** [PaddlePaddle/PaddleDetection#3926]
Process Process-660:
Traceback (most recent call last):
  File "/media/asus/225A6D42D4FA828F/2021Intern/renyumeng/PaddleDetection-release-2.2/ppdet/data/reader.py", line 210, in __next__
  File "/home/asus/anaconda3/envs/pandle/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 609, in __next__
  File "/home/asus/.local/lib/python3.6/site-packages/six.py", line 719, in reraise
  File "/home/asus/anaconda3/envs/pandle/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 585, in __next__
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/asus/anaconda3/envs/pandle/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
  File "/home/asus/anaconda3/envs/pandle/lib/python3.6/multiprocessing/process.py", line 93, in run
  File "/home/asus/anaconda3/envs/pandle/lib/python3.6/site-packages/paddle/fluid/dataloader/worker.py", line 254, in _worker_loop
  File "/home/asus/.local/lib/python3.6/site-packages/six.py", line 719, in reraise
  File "/home/asus/anaconda3/envs/pandle/lib/python3.6/site-packages/paddle/fluid/dataloader/worker.py", line 244, in _worker_loop
  File "/home/asus/anaconda3/envs/pandle/lib/python3.6/site-packages/paddle/fluid/dataloader/worker.py", line 244, in <listcomp>
RuntimeError: (Unavailable) File descriptor /paddle_6050_2680174094 open failed
  [Hint: Expected fd != -1, but received fd:-1 == -1:-1.] (at /paddle/paddle/fluid/memory/allocation/mmap_allocator.cc:73)

Traceback (most recent call last):
  File "tools/train.py", line 139, in <module>
    main()
  File "tools/train.py", line 135, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 110, in run
    trainer.train(FLAGS.eval)
  File "/media/asus/225A6D42D4FA828F/2021Intern/renyumeng/PaddleDetection-release-2.2/ppdet/engine/trainer.py", line 339, in train
    for step_id, data in enumerate(self.loader):
  File "/media/asus/225A6D42D4FA828F/2021Intern/renyumeng/PaddleDetection-release-2.2/ppdet/data/reader.py", line 210, in __next__
    return next(self.loader)
  File "/home/asus/anaconda3/envs/pandle/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 585, in __next__
    data = self._reader.read_next_var_list()
  File "/home/asus/anaconda3/envs/pandle/lib/python3.6/site-packages/paddle/fluid/multiprocess_utils.py", line 138, in __handler__
    core._throw_error_if_process_failed()
SystemError: (Fatal) DataLoader process (pid 6050) exited unexpectedly with code 1. Error detailed are lost due to multiprocessing. Rerunning with:
  1. If run DataLoader by DataLoader.from_generator(...), run with DataLoader.from_generator(..., use_multiprocess=False) may give better error trace.
  2. If run DataLoader by DataLoader(dataset, ...), run with DataLoader(dataset, ..., num_workers=0) may give better error trace (at /paddle/paddle/fluid/imperative/data_loader.cc:156)

**Comment by lyuwenyu** [comment]
reusme继续从断得地方训练

`-r`

**Comment by yumeng88** [comment]
@lyuwenyu 谢谢，已经从断的地方开始训练，为什么会出现这种情况是dataloader的问题还是什么问题呀

**Comment by lyuwenyu** [comment]
这个问题相关同学已经在处理了   后续有进展了会更新到QA列表里

**Comment by yumeng88** [comment]
@lyuwenyu 好的，多谢
