### ISSUE TITLE
在百度平台上运行infer.py出错

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleDetection#3928]
2021-08-09 08:30:00,507-WARNING: config YOLOv3Loss.batch_size is deprecated, training batch size should be set by TrainReader.batch_size
/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/framework.py:689: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  elif dtype == np.bool:
/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:299: UserWarning: /home/work/PaddleDetection/static/ppdet/modeling/losses/yolo_loss.py:155
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:299: UserWarning: /home/work/PaddleDetection/static/ppdet/modeling/losses/yolo_loss.py:172
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:299: UserWarning: /home/work/PaddleDetection/static/ppdet/modeling/losses/yolo_loss.py:172
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:299: UserWarning: /home/work/PaddleDetection/static/ppdet/modeling/losses/yolo_loss.py:174
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:299: UserWarning: /home/work/PaddleDetection/static/ppdet/modeling/losses/yolo_loss.py:174
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:299: UserWarning: /home/work/PaddleDetection/static/ppdet/modeling/losses/yolo_loss.py:178
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:299: UserWarning: /home/work/PaddleDetection/static/ppdet/modeling/losses/yolo_loss.py:178
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:299: UserWarning: /home/work/PaddleDetection/static/ppdet/modeling/losses/yolo_loss.py:180
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:299: UserWarning: /home/work/PaddleDetection/static/ppdet/modeling/losses/yolo_loss.py:180
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:299: UserWarning: /home/work/PaddleDetection/static/ppdet/modeling/losses/iou_loss.py:216
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:299: UserWarning: /home/work/PaddleDetection/static/ppdet/modeling/losses/iou_loss.py:217
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:299: UserWarning: /home/work/PaddleDetection/static/ppdet/modeling/losses/iou_loss.py:218
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:299: UserWarning: /home/work/PaddleDetection/static/ppdet/modeling/losses/iou_loss.py:219
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:299: UserWarning: /home/work/PaddleDetection/static/ppdet/modeling/losses/iou_loss.py:99
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:299: UserWarning: /home/work/PaddleDetection/static/ppdet/modeling/losses/iou_loss.py:99
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:299: UserWarning: /home/work/PaddleDetection/static/ppdet/modeling/losses/iou_loss.py:101
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:299: UserWarning: /home/work/PaddleDetection/static/ppdet/modeling/losses/iou_loss.py:103
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:299: UserWarning: /home/work/PaddleDetection/static/ppdet/modeling/losses/iou_loss.py:103
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:299: UserWarning: /home/work/PaddleDetection/static/ppdet/modeling/losses/iou_loss.py:103
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:299: UserWarning: /home/work/PaddleDetection/static/ppdet/modeling/losses/iou_loss.py:104
The behavior of expression A / B has been unified with elementwise_div(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_div(X, Y, axis=0) instead of A / B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:299: UserWarning: /home/work/PaddleDetection/static/ppdet/modeling/losses/iou_loss.py:81
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:299: UserWarning: /home/work/PaddleDetection/static/ppdet/modeling/losses/yolo_loss.py:196
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:299: UserWarning: /home/work/PaddleDetection/static/ppdet/modeling/losses/yolo_loss.py:389
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:299: UserWarning: /home/work/PaddleDetection/static/ppdet/modeling/losses/yolo_loss.py:391
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:299: UserWarning: /home/work/PaddleDetection/static/ppdet/modeling/losses/yolo_loss.py:217
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:299: UserWarning: /home/work/PaddleDetection/static/ppdet/modeling/losses/yolo_loss.py:218
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:299: UserWarning: /home/work/PaddleDetection/static/ppdet/modeling/losses/yolo_loss.py:220
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
2021-08-09 08:30:03,886-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000500] in Optimizer will not take effect, and it will only be applied to other Parameters!
2021-08-09 08:30:04,802-WARNING: config YOLOv3Loss.batch_size is deprecated, training batch size should be set by TrainReader.batch_size
2021-08-09 08:30:05,360-WARNING: Found an invalid bbox in annotations: xml_file: dataset/ocr_keyword_voc/Annotations/1611566503.57_05ade_00196.xml, x1: 967.0, y1: 688.0, x2: 970.0, y2: 688.0.
W0809 08:30:05.961516  2115 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.2, Runtime API Version: 10.1
W0809 08:30:05.966624  2115 device_context.cc:422] device: 0, cuDNN Version: 7.6.
/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/io.py:2358: UserWarning: This list is not set, Because of Paramerter not found in program. There are: fc_0.b_0 fc_0.w_0
  format(" ".join(unused_para_list)))
2021-08-09 08:30:09,141-WARNING: Found an invalid bbox in annotations: xml_file: dataset/ocr_keyword_voc/Annotations/1611647006.94_a644a_00000.xml, x1: 1079.0, y1: 653.0, x2: 1084.0, y2: 653.0.
2021-08-09 08:30:09,304-WARNING: Found an invalid bbox in annotations: xml_file: dataset/ocr_keyword_voc/Annotations/1611647228.63_8fa23_00134.xml, x1: 1156.0, y1: 486.0, x2: 1156.0, y2: 488.0.
2021-08-09 08:30:09,754-WARNING: Found an invalid bbox in annotations: xml_file: dataset/ocr_keyword_voc/Annotations/1611648710.88_f17dc_00224.xml, x1: 214.0, y1: 126.0, x2: 215.0, y2: 126.0.
2021-08-09 08:30:10,669-WARNING: Found an invalid bbox in annotations: xml_file: dataset/ocr_keyword_voc/Annotations/1611577039.36_af18a_00110.xml, x1: 1101.0, y1: 78.0, x2: 1101.0, y2: 78.0.
2021-08-09 08:30:10,811-WARNING: Found an invalid bbox in annotations: xml_file: dataset/ocr_keyword_voc/Annotations/1611566290.42_a41b2_00110.xml, x1: 1005.0, y1: 676.0, x2: 1005.0, y2: 676.0.
2021-08-09 08:30:10,885-WARNING: Found an invalid bbox in annotations: xml_file: dataset/ocr_keyword_voc/Annotations/1611651952.09_447e3_00050.xml, x1: 1272.0, y1: 690.0, x2: 1272.0, y2: 690.0.
2021-08-09 08:30:11,091-WARNING: Found an invalid bbox in annotations: xml_file: dataset/ocr_keyword_voc/Annotations/1611646917.32_f62bb_00190.xml, x1: 791.0, y1: 517.0, x2: 791.0, y2: 517.0.
2021-08-09 08:30:11,304-WARNING: Found an invalid bbox in annotations: xml_file: dataset/ocr_keyword_voc/Annotations/1611654684.96_e0ed1_00080.xml, x1: 743.0, y1: 599.0, x2: 747.0, y2: 599.0.
2021-08-09 08:30:11,310-WARNING: Found an invalid bbox in annotations: xml_file: dataset/ocr_keyword_voc/Annotations/1611561370.3_398ba_00016.xml, x1: 1390.0, y1: 364.0, x2: 1279.0, y2: 374.0.
2021-08-09 08:30:11,556-WARNING: Found an invalid bbox in annotations: xml_file: dataset/ocr_keyword_voc/Annotations/1611569643.51_e8eb4_00168.xml, x1: 1012.0, y1: 555.0, x2: 1012.0, y2: 555.0.
2021-08-09 08:30:12,040-WARNING: Found an invalid bbox in annotations: xml_file: dataset/ocr_keyword_voc/Annotations/1611575354.21_41258_00152.xml, x1: 171.0, y1: 680.0, x2: 171.0, y2: 680.0.
2021-08-09 08:30:12,284-WARNING: Found an invalid bbox in annotations: xml_file: dataset/ocr_keyword_voc/Annotations/1611566071.99_4fb36_00190.xml, x1: 235.0, y1: 628.0, x2: 237.0, y2: 628.0.
2021-08-09 08:30:12,655-WARNING: Found an invalid bbox in annotations: xml_file: dataset/ocr_keyword_voc/Annotations/1611565390.75_72401_00000.xml, x1: 1109.0, y1: 88.0, x2: 1109.0, y2: 88.0.
2021-08-09 08:30:12,697-WARNING: Found an invalid bbox in annotations: xml_file: dataset/ocr_keyword_voc/Annotations/1611573272.43_a1417_00102.xml, x1: 1094.0, y1: 103.0, x2: 1094.0, y2: 103.0.
2021-08-09 08:30:13,398-WARNING: Found an invalid bbox in annotations: xml_file: dataset/ocr_keyword_voc/Annotations/1611567046.44_1ccee_00212.xml, x1: 1054.0, y1: 100.0, x2: 1054.0, y2: 100.0.
2021-08-09 08:30:13,675-WARNING: Found an invalid bbox in annotations: xml_file: dataset/ocr_keyword_voc/Annotations/1611569412.86_27ee4_00082.xml, x1: 342.0, y1: 671.0, x2: 344.0, y2: 671.0.
2021-08-09 08:30:13,768-WARNING: Found an invalid bbox in annotations: xml_file: dataset/ocr_keyword_voc/Annotations/1611646371.17_89e84_00154.xml, x1: 210.0, y1: 682.0, x2: 214.0, y2: 682.0.
2021-08-09 08:30:13,928-WARNING: Found an invalid bbox in annotations: xml_file: dataset/ocr_keyword_voc/Annotations/1611566806.85_a9d0e_00102.xml, x1: 1432.0, y1: 489.0, x2: 1279.0, y2: 528.0.
2021-08-09 08:30:14,528-WARNING: Found an invalid bbox in annotations: xml_file: dataset/ocr_keyword_voc/Annotations/1611574278.71_2ce06_00154.xml, x1: 207.0, y1: 76.0, x2: 208.0, y2: 76.0.
2021-08-09 08:30:15,103-WARNING: Found an invalid bbox in annotations: xml_file: dataset/ocr_keyword_voc/Annotations/1611646391.78_89e84_00216.xml, x1: 226.0, y1: 675.0, x2: 226.0, y2: 675.0.
2021-08-09 08:30:15,458-WARNING: Found an invalid bbox in annotations: xml_file: dataset/ocr_keyword_voc/Annotations/1611652784.81_59890_00056.xml, x1: 117.0, y1: 630.0, x2: 118.0, y2: 630.0.
2021-08-09 08:30:15,532-WARNING: Found an invalid bbox in annotations: xml_file: dataset/ocr_keyword_voc/Annotations/1611568046.77_38430_00172.xml, x1: 118.0, y1: 672.0, x2: 118.0, y2: 672.0.
2021-08-09 08:30:15,554-WARNING: Found an invalid bbox in annotations: xml_file: dataset/ocr_keyword_voc/Annotations/1611646823.2_45434_00144.xml, x1: 1212.0, y1: 108.0, x2: 1214.0, y2: 108.0.
2021-08-09 08:30:15,633-WARNING: Found an invalid bbox in annotations: xml_file: dataset/ocr_keyword_voc/Annotations/1611646338.59_89e84_00046.xml, x1: 240.0, y1: 682.0, x2: 241.0, y2: 682.0.
2021-08-09 08:30:16,166-WARNING: Found an invalid bbox in annotations: xml_file: dataset/ocr_keyword_voc/Annotations/1611573604.54_95631_00128.xml, x1: 1100.0, y1: 612.0, x2: 1100.0, y2: 613.0.
2021-08-09 08:30:16,774-WARNING: Found an invalid bbox in annotations: xml_file: dataset/ocr_keyword_voc/Annotations/1611571455.09_e7c85_00088.xml, x1: 453.0, y1: 23488319.0, x2: 792.0, y2: 719.0.
Traceback (most recent call last):
  File "tools/train.py", line 413, in <module>
    main()
  File "tools/train.py", line 284, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1110, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/python-3.7/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1108, in run
    return_merged=return_merged)
  File "/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1241, in _run_impl
    program._compile(scope, self.place)
  File "/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/compiler.py", line 465, in _compile
    use_device=use_device, scope=self._scope, places=self._places)
  File "/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/compiler.py", line 415, in _compile_data_parallel
    self._exec_strategy, self._build_strategy, self._graph)
OSError: (External)  Nccl error, unhandled system error  (at /paddle/paddle/fluid/platform/nccl_helper.h:123)

    six.reraise(*sys.exc_info())
  File "/usr/local/python-3.7/lib/python3.7/site-packages/six.py", line 719, in reraise
    program._compile(scope, self.place)
  File "/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/compiler.py", line 465, in _compile
    raise value
  File "/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1108, in run
/home/work/PaddleDetection/static/ppdet/data/reader.py:90: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  if isinstance(item, collections.Sequence) and len(item) == 0:
/home/work/PaddleDetection/static/ppdet/data/shared_queue/sharedmemory.py:251: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  header_str = self._base[0:self.s_allocator_header].tostring()
/home/work/PaddleDetection/static/ppdet/data/shared_queue/sharedmemory.py:297: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  status = self._base[start:end].tostring().decode()
2021-08-09 08:31:08,168-WARNING: consumer[2185] exit abnormally with exitcode[1]
2021-08-09 08:31:08,169-WARNING: consumer[2186] exit abnormally with exitcode[1]
2021-08-09 08:31:08,169-WARNING: consumer[2187] exit abnormally with exitcode[1]
2021-08-09 08:31:08,169-WARNING: consumer[2188] exit abnormally with exitcode[1]
2021-08-09 08:31:08,169-WARNING: consumer[2189] exit abnormally with exitcode[1]
2021-08-09 08:31:08,169-WARNING: consumer[2190] exit abnormally with exitcode[1]
2021-08-09 08:31:08,169-WARNING: consumer[2191] exit abnormally with exitcode[1]
2021-08-09 08:31:08,169-WARNING: consumer[2192] exit abnormally with exitcode[1]
2021-08-09 08:31:08,169-WARNING: consumer[2193] exit abnormally with exitcode[1]
2021-08-09 08:31:08,169-WARNING: 9 consumers have exited abnormally!!!
2021-08-09 08:31:08,170-WARNING: consumer[2185] exit abnormally with exitcode[1]
2021-08-09 08:31:08,170-WARNING: consumer[2186] exit abnormally with exitcode[1]
2021-08-09 08:31:08,170-WARNING: consumer[2187] exit abnormally with exitcode[1]
2021-08-09 08:31:08,170-WARNING: consumer[2188] exit abnormally with exitcode[1]
2021-08-09 08:31:08,170-WARNING: consumer[2189] exit abnormally with exitcode[1]
2021-08-09 08:31:08,170-WARNING: consumer[2190] exit abnormally with exitcode[1]
2021-08-09 08:31:08,170-WARNING: consumer[2191] exit abnormally with exitcode[1]
2021-08-09 08:31:08,170-WARNING: consumer[2192] exit abnormally with exitcode[1]
2021-08-09 08:31:08,170-WARNING: consumer[2193] exit abnormally with exitcode[1]
2021-08-09 08:31:08,170-WARNING: 9 consumers have exited abnormally!!!
/usr/local/python-3.7/lib/python3.7/site-packages/paddle/fluid/reader.py:1294: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
  logging.warn('Your reader has raised an exception!')
2021-08-09 08:31:08,171-WARNING: Your reader has raised an exception!

**Comment by ghost** [comment]
请问应该如何解决

**Comment by lyuwenyu** [comment]
xml格式不对？

**Comment by lyuwenyu** [comment]
数据有问题？

**Comment by lyuwenyu** [comment]
执行的命令是啥？
