### ISSUE TITLE
pip install willthefrog-docstring_parser-0.3-4-g5fe3bb5.tar.gz failed

### ISSUE THREAD

**Issue by haojian20161987** [PaddlePaddle/PaddleDetection#394]
安装docstring_parser的时候报错了，看不出原因来。下面是错误信息。
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Processing j:\detech\paddledetection\willthefrog-docstring_parser-0.3-4-g5fe3bb5.tar.gz
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'i:\python36\python.exe' 'i:\python36\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\hao\AppData\Local\Temp\pip-build-env-ondqtivn\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (41 lines):
  Traceback (most recent call last):
    File "i:\python36\lib\runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "i:\python36\lib\runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "i:\python36\lib\site-packages\pip\__main__.py", line 19, in <module>
      sys.exit(_main())
    File "i:\python36\lib\site-packages\pip\_internal\cli\main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "i:\python36\lib\site-packages\pip\_internal\commands\__init__.py", line 96, in create_command
      module = importlib.import_module(module_path)
    File "i:\python36\lib\importlib\__init__.py", line 126, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 994, in _gcd_import
    File "<frozen importlib._bootstrap>", line 971, in _find_and_load
    File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 678, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "i:\python36\lib\site-packages\pip\_internal\commands\install.py", line 24, in <module>
      from pip._internal.cli.req_command import RequirementCommand
    File "i:\python36\lib\site-packages\pip\_internal\cli\req_command.py", line 21, in <module>
      from pip._internal.req.constructors import (
    File "i:\python36\lib\site-packages\pip\_internal\req\__init__.py", line 11, in <module>
      from .req_file import parse_requirements
    File "i:\python36\lib\site-packages\pip\_internal\req\req_file.py", line 25, in <module>
      from pip._internal.req.constructors import (
    File "i:\python36\lib\site-packages\pip\_internal\req\constructors.py", line 28, in <module>
      from pip._internal.req.req_install import InstallRequirement
    File "i:\python36\lib\site-packages\pip\_internal\req\req_install.py", line 30, in <module>
      from pip._internal.operations.install.wheel import install_wheel
    File "i:\python36\lib\site-packages\pip\_internal\operations\install\wheel.py", line 10, in <module>
      import compileall
    File "i:\python36\lib\compileall.py", line 20, in <module>
      from concurrent.futures import ProcessPoolExecutor
    File "i:\python36\lib\site-packages\concurrent\futures\__init__.py", line 8, in <module>
      from concurrent.futures._base import (FIRST_COMPLETED,
    File "i:\python36\lib\site-packages\concurrent\futures\_base.py", line 381
      raise exception_type, self._exception, self._traceback
                          ^
  SyntaxError: invalid syntax
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'i:\python36\python.exe' 'i:\python36\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\hao\AppData\Local\Temp\pip-build-env-ondqtivn\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com -- 'setuptools>=40.8.0' wheel Check the logs for full command output.

**Comment by jerrywgz** [comment]
请问你是使用pip install -r requirement.txt安装的吗

**Comment by haojian20161987** [comment]
是的，win10环境。

**Comment by willthefrog** [comment]
试下把`requirement.txt`里的对应行改为试试呢
```
docstring_parser @ https://github.com/willthefrog/docstring_parser/archive/master.zip
```

**Comment by willthefrog** [comment]
@haojian20161987 

怀疑是window不支持tar包。

**Comment by willthefrog** [comment]
另外，不装这个包也不影响运行的，也可以直接删掉那行依赖。

**Comment by haojian20161987** [comment]
不行，没见过这种报错。
J:\detech\PaddleDetection>pip install -r requirements.txt
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Collecting tqdm
  Downloading http://mirrors.aliyun.com/pypi/packages/47/55/fd9170ba08a1a64a18a7f8a18f088037316f2a41be04d2fe6ece5a653e8f/tqdm-4.43.0-py2.py3-none-any.whl (59 kB)
     |████████████████████████████████| 59 kB 787 kB/s
Collecting docstring_parser@ https://github.com/willthefrog/docstring_parser/archive/master.zip
  Downloading https://github.com/willthefrog/docstring_parser/archive/master.zip (11 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'i:\python36\python.exe' 'i:\python36\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\hao\AppData\Local\Temp\pip-build-env-qtvlaa27\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (41 lines):
  Traceback (most recent call last):
    File "i:\python36\lib\runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "i:\python36\lib\runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "i:\python36\lib\site-packages\pip\__main__.py", line 19, in <module>
      sys.exit(_main())
    File "i:\python36\lib\site-packages\pip\_internal\cli\main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "i:\python36\lib\site-packages\pip\_internal\commands\__init__.py", line 96, in create_command
      module = importlib.import_module(module_path)
    File "i:\python36\lib\importlib\__init__.py", line 126, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 994, in _gcd_import
    File "<frozen importlib._bootstrap>", line 971, in _find_and_load
    File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 678, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "i:\python36\lib\site-packages\pip\_internal\commands\install.py", line 24, in <module>
      from pip._internal.cli.req_command import RequirementCommand
    File "i:\python36\lib\site-packages\pip\_internal\cli\req_command.py", line 21, in <module>
      from pip._internal.req.constructors import (
    File "i:\python36\lib\site-packages\pip\_internal\req\__init__.py", line 11, in <module>
      from .req_file import parse_requirements
    File "i:\python36\lib\site-packages\pip\_internal\req\req_file.py", line 25, in <module>
      from pip._internal.req.constructors import (
    File "i:\python36\lib\site-packages\pip\_internal\req\constructors.py", line 28, in <module>
      from pip._internal.req.req_install import InstallRequirement
    File "i:\python36\lib\site-packages\pip\_internal\req\req_install.py", line 30, in <module>
      from pip._internal.operations.install.wheel import install_wheel
    File "i:\python36\lib\site-packages\pip\_internal\operations\install\wheel.py", line 10, in <module>
      import compileall
    File "i:\python36\lib\compileall.py", line 20, in <module>
      from concurrent.futures import ProcessPoolExecutor
    File "i:\python36\lib\site-packages\concurrent\futures\__init__.py", line 8, in <module>
      from concurrent.futures._base import (FIRST_COMPLETED,
    File "i:\python36\lib\site-packages\concurrent\futures\_base.py", line 381
      raise exception_type, self._exception, self._traceback
                          ^
  SyntaxError: invalid syntax
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'i:\python36\python.exe' 'i:\python36\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\hao\AppData\Local\Temp\pip-build-env-qtvlaa27\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com -- 'setuptools>=40.8.0' wheel Check the logs for full command output.

**Comment by haojian20161987** [comment]
那我先试试继续往下运行吧。

> 另外，不装这个包也不影响运行的，也可以直接删掉那行依赖。

行，那我继续往下安装了，谢啦！

**Comment by willthefrog** [comment]
好的，如果没有其他问题麻烦close下issue吧，谢谢。 @haojian20161987

**Comment by haojian20161987** [comment]
关于docstring_parser，requirement.txt上的下载地址本身是fork自另一个项目，而那个项目对应的pip安装命令是pip install docstring-parser==0.6，通过这个我安装上了docstring_parser，能否运行成功还不确定，我现在还没有用到它的地方。

**Comment by willthefrog** [comment]
原版的docstring-parser不支持python2, fork主要是加入和python2 支持。你用的python 3的话是没啥问题的。 @haojian20161987
