### ISSUE TITLE
ValueError: fruit-dection is not valid and cannot parse dataset type 'fruit-dection' for automaticly downloading, which only supports 'voc' , 'coco', 'wider_face', 'fruit', 'roadsign_voc' and 'mot' currently

### ISSUE THREAD

**Issue by yumeng88** [PaddlePaddle/PaddleDetection#3965]
两周前我拿训练好的模型是可以评估的，现在无法评估不知道除了什么问题。
已经参考上一个提问此问题的同志，注释掉ppdet/data/source/dataset.py里的函数
![image](https://user-images.githubusercontent.com/56550062/129170789-150251ae-589d-4e97-ae9d-9b655291e661.png)

想问一下还有可能是哪里的问题。期间数据集是没有改动的

(pandle) asus@asus-System-Product-Name:/media/asus/225A6D42D4FA828F/2021Intern/renyumeng/PaddleDetection-release-2.2$ python -u tools/eval.py -c configs/yolov3/yolov3_darknet53_270e_four.yml -o weights=output/yolov3_darknet53_270e_coco_four/model_final.pdparams
W0812 08:42:36.636431 11865 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.2, Runtime API Version: 10.1
W0812 08:42:36.639150 11865 device_context.cc:422] device: 0, cuDNN Version: 7.6.
[08/12 08:42:37] ppdet.utils.download WARNING: Config annotation /media/asus/225A6D42D4FA828F/2021Intern/renyumeng/PaddleDetection-release-2.1/dataset/fruit/fruit-dection/valid.txt is not a file, dataset config is not valid
[08/12 08:42:37] ppdet.utils.download INFO: Dataset /media/asus/225A6D42D4FA828F/2021Intern/renyumeng/PaddleDetection-release-2.1/dataset/fruit/fruit-dection is not valid for reason above, try searching /home/asus/.cache/paddle/dataset or downloading dataset...
Traceback (most recent call last):
  File "tools/eval.py", line 136, in <module>
    main()
  File "tools/eval.py", line 132, in main
    run(FLAGS, cfg)
  File "tools/eval.py", line 101, in run
    trainer = Trainer(cfg, mode='eval')
  File "/media/asus/225A6D42D4FA828F/2021Intern/renyumeng/PaddleDetection-release-2.2/ppdet/engine/trainer.py", line 101, in __init__
    self.dataset, cfg.worker_num, self._eval_batch_sampler)
  File "/media/asus/225A6D42D4FA828F/2021Intern/renyumeng/PaddleDetection-release-2.2/ppdet/data/reader.py", line 163, in __call__
    self.dataset.check_or_download_dataset()
  File "/media/asus/225A6D42D4FA828F/2021Intern/renyumeng/PaddleDetection-release-2.2/ppdet/data/source/dataset.py", line 91, in check_or_download_dataset
    self.image_dir)
  File "/media/asus/225A6D42D4FA828F/2021Intern/renyumeng/PaddleDetection-release-2.2/ppdet/utils/download.py", line 220, in get_dataset_path
    format(path, osp.split(path)[-1]))
ValueError: Dataset /media/asus/225A6D42D4FA828F/2021Intern/renyumeng/PaddleDetection-release-2.1/dataset/fruit/fruit-dection is not valid and cannot parse dataset type 'fruit-dection' for automaticly downloading, which only supports 'voc' , 'coco', 'wider_face', 'fruit', 'roadsign_voc' and 'mot' currently

**Comment by ghostxsl** [comment]
你要是跑tools/eval.py的话，得注释掉https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/ppdet/data/source/dataset.py#L90-L91 这两行，再加上 return ，或者你确保 self.dataset_dir, self.anno_path, self.image_dir 这三个路径均存在的话，也不会调用check_or_download_dataset而导致报错

**Comment by yumeng88** [comment]
好的，多谢同志搞好了 @ghostxsl
