### ISSUE TITLE
关于ppyolo多卡训练的报错问题

### ISSUE THREAD

**Issue by lujx1024** [PaddlePaddle/PaddleDetection#3973]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## 相关issue:

1. [issue1263 ppyolo单卡可以训练，指定多卡训练就出错了](https://github.com/PaddlePaddle/PaddleDetection/issues/1263)
2. [两卡训练ppyolo的报错](https://github.com/PaddlePaddle/PaddleDetection/issues/3952)

## 描述问题/Describe the bug

如同上述issue中出现的情况类似，ppyolo在使用单卡GPU训练时正常，指定多卡GPU训练时报错

## 环境/Environment
1. Paddle和PaddleDetection的版本号：
```
paddledet  2.1.0
paddlepaddle-gpu  2.1.2.post101
```
2. 操作系统信息：`CentOS 7 64位`

3. Python版本. `Python 3.6.8`

4. CUDA/cuDNN的版本号.
```
CUDA:  CUDA Version 10.1.243

cuDNN: 7.6.5

#define CUDNN_MAJOR 7
#define CUDNN_MINOR 6
#define CUDNN_PATCHLEVEL 5
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

```
5. NCCL
在已查询过的issue中，不少提到关于NCCL的安装与版本匹配问题，在尝试解决此问题过程中，根据cuda版本分别使用 RPM 方式安装了 nccl 2.7.6 和 nccl 2.8.3 两个版本，均没有解决这个报错问题，报错信息如下：
```
Traceback (most recent call last):
  File "tools/train.py", line 139, in <module>
    main()
  File "tools/train.py", line 135, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 95, in run
    init_parallel_env()
  File "/home/aoto_dialogue/.virtualenvs/detection_head/lib/python3.6/site-packages/paddledet-2.1.0-py3.6.egg/ppdet/engine/env.py", line 42, in init_parallel_env
    paddle.distributed.init_parallel_env()
  File "/home/aoto_dialogue/.virtualenvs/detection_head/lib/python3.6/site-packages/paddle/distributed/parallel.py", line 196, in init_parallel_env
    parallel_helper._init_parallel_ctx()
  File "/home/aoto_dialogue/.virtualenvs/detection_head/lib/python3.6/site-packages/paddle/fluid/dygraph/parallel_helper.py", line 42, in _init_parallel_ctx
    __parallel_ctx__clz__.init()
OSError: (External)  Nccl error, unhandled cuda error  (at /paddle/paddle/fluid/platform/collective_helper.cc:100)
```

请问这种情况需要如何进行问题的排查与定位？ 如果能有具体的建议，非常感谢！

**Comment by pangyoki** [comment]
你好，确定安装nccl成功了吗？`find / -name libnccl*`用这个命令找下试试看？

**Comment by lujx1024** [comment]
@pangyoki 您好，执行这个指令后，是能够找到文件的，如下所示：
```
[root@centos PaddleDetection]# find / -name libnccl*
/var/nccl-repo-2.8.3-ga-cuda10.1/libnccl-2.8.3-1+cuda10.1.x86_64.rpm
/var/nccl-repo-2.8.3-ga-cuda10.1/libnccl-devel-2.8.3-1+cuda10.1.x86_64.rpm
/var/nccl-repo-2.8.3-ga-cuda10.1/libnccl-static-2.8.3-1+cuda10.1.x86_64.rpm
/usr/lib64/libnccl.so.2.9.9
/usr/lib64/libnccl.so.2
/usr/lib64/libnccl.so
/usr/lib64/libnccl_static.a
/usr/share/doc/libnccl-2.9.9
/usr/share/doc/libnccl-devel-2.9.9
/usr/share/doc/libnccl-static-2.9.9
```
请问这个结果时表示安装成功了么？ 当时是使用rpm本地安装包的形式进行安装的，也仔细对比了版本的问题。

**Comment by pangyoki** [comment]
嗯嗯，看起来可以。这个路径`/usr/lib64`有添加到环境变量里吗？可以`echo $LD_LIBRARY_PATH`看下。

**Comment by lujx1024** [comment]
指令执行后，结果如下：
```
(detection) [root@centos PaddleDetection]# echo $LD_LIBRARY_PATH
/usr/local/cuda/lib64:/usr/local/cuda-10.1/lib64:
```
这个应该是没有加入到环境变量么？

**Comment by pangyoki** [comment]
是的，用`export LD_LIBRARY_PATH=/usr/lib64:$LD_LIBRARY_PATH`把这个路径加到环境变量试试

**Comment by lujx1024** [comment]
添加环境变量:
```
(detection) [root@centos PaddleDetection]# vim ~/.bashrc

添加 export LD_LIBRARY_PATH=/usr/lib64:$LD_LIBRARY_PATH 到最后一行
```

更新配置:
```
(detection) [root@centos PaddleDetection]# source ~/.bashrc
```
查看结果
```
(detection) [root@centos nccl-tests]# echo $LD_LIBRARY_PATH
/usr/lib64:/usr/local/cuda/lib64:/usr/local/cuda-10.1/lib64:/usr/local/cuda/lib64:/usr/local/cuda-10.1/lib64:
```

多卡训练仍然报错，请您再帮忙看一下，错误的原因会是在什么地方，谢谢、 报错信息详情如下：
```
(detection) [root@centos_aoto PaddleDetection210811]# python -m paddle.distributed.launch --gpus 1,2,3  tools/train.py -c configs/ppyolo/ppyolov2_r50vd_dcn_voc_head.yml
-----------  Configuration Arguments -----------
gpus: 1,2,3
heter_worker_num: None
heter_workers:
http_port: None
ips: 127.0.0.1
log_dir: log
nproc_per_node: None
run_mode: None
server_num: None
servers:
training_script: tools/train.py
training_script_args: ['-c', 'configs/ppyolo/ppyolov2_r50vd_dcn_voc_head.yml']
worker_num: None
workers:
------------------------------------------------
WARNING 2021-08-16 14:22:01,960 launch.py:359] Not found distinct arguments and compiled with cuda or xpu. Default use collective mode
launch train in GPU mode!
INFO 2021-08-16 14:22:01,960 launch_utils.py:621] Change selected_gpus into reletive values. --ips:1,2,3 will change into relative_ips:[0, 1, 2] according to your CUDA_VISIBLE_DEVICES:['1', '2', '3']
INFO 2021-08-16 14:22:01,962 launch_utils.py:511] Local start 3 processes. First process distributed environment info (Only For Debug):
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:39106               |
    |                     PADDLE_TRAINERS_NUM                        3                      |
    |                PADDLE_TRAINER_ENDPOINTS  ... 0.1:39106,127.0.0.1:43115,127.0.0.1:47206|
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                      0,1,2                    |
    |                     FLAGS_selected_gpus                        0                      |
    |             FLAGS_selected_accelerators                        0                      |
    +=======================================================================================+

INFO 2021-08-16 14:22:01,962 launch_utils.py:514] details abouts PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
launch proc_id:41472 idx:0
launch proc_id:41475 idx:1
launch proc_id:41478 idx:2
W0816 14:22:05.795648 41472 gen_comm_id_helper.cc:120] connect addr=127.0.0.1:43115 failed 1 times with reason: Connection refused retry after 0.5 seconds
I0816 14:22:06.296320 41472 nccl_context.cc:74] init nccl context nranks: 3 local rank: 0 gpu id: 0 ring id: 0
Traceback (most recent call last):
  File "tools/train.py", line 139, in <module>
    main()
  File "tools/train.py", line 135, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 95, in run
    init_parallel_env()
  File "/home/aoto_dialogue/.virtualenvs/detection/lib/python3.6/site-packages/ppdet/engine/env.py", line 42, in init_parallel_env
    paddle.distributed.init_parallel_env()
  File "/home/aoto_dialogue/.virtualenvs/detection/lib/python3.6/site-packages/paddle/distributed/parallel.py", line 196, in init_parallel_env
    parallel_helper._init_parallel_ctx()
  File "/home/aoto_dialogue/.virtualenvs/detection/lib/python3.6/site-packages/paddle/fluid/dygraph/parallel_helper.py", line 42, in _init_parallel_ctx
    __parallel_ctx__clz__.init()
OSError: (External)  Nccl error, unhandled cuda error  (at /paddle/paddle/fluid/platform/collective_helper.cc:100)

INFO 2021-08-16 14:22:11,043 launch_utils.py:327] terminate all the procs
ERROR 2021-08-16 14:22:11,044 launch_utils.py:584] ABORT!!! Out of all 3 trainers, the trainer process with rank=[0, 1, 2] was aborted. Please check its log.
INFO 2021-08-16 14:22:14,047 launch_utils.py:327] terminate all the procs
```

**Comment by pangyoki** [comment]
看这个报错就是nccl的问题，用`paddle.utils.run_check()`会报啥问题？

**Comment by pangyoki** [comment]
gpu卡确定都是空闲可用的吗？

**Comment by lujx1024** [comment]
sorry，我仔细排查了一下，确实是NCCL的安装问题。
`paddle.utils.run_check()`运行的报错和`nccl_tests`一样都是`unhandled cuda error`。

## 主要原因
可能是这台机器此前被其他人安装了与当前CUDA版本不匹配的NCCL,执行`find / -name libnccl*` 指令的输出结果是：
```
/var/nccl-repo-2.8.3-ga-cuda10.1/libnccl-2.8.3-1+cuda10.1.x86_64.rpm
/var/nccl-repo-2.8.3-ga-cuda10.1/libnccl-devel-2.8.3-1+cuda10.1.x86_64.rpm
/var/nccl-repo-2.8.3-ga-cuda10.1/libnccl-static-2.8.3-1+cuda10.1.x86_64.rpm
/usr/lib64/libnccl.so.2.9.9
/usr/lib64/libnccl.so.2
/usr/lib64/libnccl.so
/usr/lib64/libnccl_static.a
/usr/share/doc/libnccl-2.9.9
/usr/share/doc/libnccl-devel-2.9.9
/usr/share/doc/libnccl-static-2.9.9
```
可以看到`/usr/lib64` 文件夹下的NCCL版本是2.9.9，并非是我期望的 2.8.3.，而且从NVIDIA官方网站下载的RPM安装包，使用`rpm -ivh nccl-repo-rhel7-2.8.3-ga-cuda10.1-1-1.x86_64.rpm` 执行后，似乎并没有执行安装流程，而是解压成了三个RPM安装包(从结果推测的，并未在机器上验证)。 从而导致，调用的NCCL模块始终是`2.9.9 for cude 11.3 `，而不是依赖所需要的`2.8.3 for cuda 10.1`.

## 我的解决方案

既然是因为版本问题，那就先写在原先的版本，再重新安装适配的即可，由于文件目录中存在RPM文件安装包，所以推测原先的版本的安装方式也是通过RPM方式安装的，以下是操作步骤：

1. `rpm -qa | grep nccl` 查看nccl的安装包列表
```
libnccl-2.9.9-1+cuda11.3.x86_64
libnccl-static-2.9.9-1+cuda11.3.x86_64
libnccl-devel-2.9.9-1+cuda11.3.x86_64
```
2. 依次卸载
推荐使用以下顺序，避免因包依赖关系导致卸载失败
```
rpm -e libnccl-devel-2.9.9-1+cuda11.3.x86_64
rpm -e libnccl-2.9.9-1+cuda11.3.x86_64
rpm -e libnccl-static-2.9.9-1+cuda11.3.x86_64
```
3.使用 yum 安装
NVIDIA NCCL官方文档提供了多种不同的安装方式，推荐使用`yum`方式安装
```
[root@centos  nccl-tests]# yum install libnccl-2.8.3-1+cuda10.1 libnccl-devel-2.8.3-1+cuda10.1 libn ccl-static-2.8.3-1+cuda10.1
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirrors.aliyun.com
 * epel: mirrors.bfsu.edu.cn
 * extras: mirrors.aliyun.com
 * updates: mirrors.aliyun.com
Resolving Dependencies
--> Running transaction check
---> Package libnccl.x86_64 0:2.8.3-1+cuda10.1 will be installed
---> Package libnccl-devel.x86_64 0:2.8.3-1+cuda10.1 will be installed
---> Package libnccl-static.x86_64 0:2.8.3-1+cuda10.1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

========================================================================================================================= 
Package                     Arch                Version                       Repository                           Size 
=========================================================================================================================
Installing:
 libnccl                     x86_64              2.8.3-1+cuda10.1              nccl-2.8.3-ga-cuda10.1               32 M  
 libnccl-devel               x86_64              2.8.3-1+cuda10.1              nccl-2.8.3-ga-cuda10.1              7.7 k  
 libnccl-static              x86_64              2.8.3-1+cuda10.1              nccl-2.8.3-ga-cuda10.1               37 M

Transaction Summary
=========================================================================================================================
Install  3 Packages

Total download size: 69 M
Installed size: 181 M
Is this ok [y/d/N]: y
Downloading packages:
-------------------------------------------------------------------------------------------------------------------------
Total                                                                                    418 MB/s |  69 MB  00:00:00
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
Warning: RPMDB altered outside of yum.
  Installing : libnccl-2.8.3-1+cuda10.1.x86_64                                                                       
  1/3 /sbin/ldconfig: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7 is not a symbolic link

  Installing : libnccl-devel-2.8.3-1+cuda10.1.x86_64                                                                 
  2/3 /sbin/ldconfig: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7 is not a symbolic link

  Installing : libnccl-static-2.8.3-1+cuda10.1.x86_64                                                                3/3
  Verifying  : libnccl-static-2.8.3-1+cuda10.1.x86_64                                                                1/3
  Verifying  : libnccl-devel-2.8.3-1+cuda10.1.x86_64                                                                 2/3
  Verifying  : libnccl-2.8.3-1+cuda10.1.x86_64                                                                       3/3

Installed:
  libnccl.x86_64 0:2.8.3-1+cuda10.1  libnccl-devel.x86_64 0:2.8.3-1+cuda10.1  libnccl-static.x86_64 0:2.8.3-1+cuda10.1

Complete!
```

@pangyoki 非常感谢您的回复与耐心解答，谢谢
