### ISSUE TITLE
自己制作的coco数据集训练出错

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/PaddleDetection#3977]
```
[08/14 02:14:03] ppdet.engine INFO: Epoch: [0] [4540/4576] learning_rate: 0.398762 loss_qfl: 0.000000 loss_bbox: 0.000000 loss_dfl: 0.000000 loss: 0.000000 eta: 3 days, 9:31:14 batch_cost: 1.8599 data_cost: 1.5400 ips: 68.8225 images/s
[08/14 02:14:52] ppdet.engine INFO: Epoch: [0] [4560/4576] learning_rate: 0.398751 loss_qfl: 0.000000 loss_bbox: 0.000000 loss_dfl: 0.000000 loss: 0.000000 eta: 3 days, 9:30:43 batch_cost: 2.4059 data_cost: 2.0497 ips: 53.2021 images/s
ERROR: Unexpected segmentation fault encountered in DataLoader workers.
ERROR: Unexpected segmentation fault encountered in DataLoader workers.
ERROR: Unexpected segmentation fault encountered in DataLoader workers.
ERROR: Unexpected segmentation fault encountered in DataLoader workers.
ERROR: Unexpected segmentation fault encountered in DataLoader workers.
ERROR: Unexpected segmentation fault encountered in DataLoader workers.
Traceback (most recent call last):
  File "tools/train.py", line 141, in <module>
    main()
  File "tools/train.py", line 137, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 110, in run
    trainer.train(FLAGS.eval)
  File "/home/ar/shaoxiong/handpp_work/det_work/work_exps/v3_pddet_picodet_reso320_handcls27det/ppdet/engine/trainer.py", line 384, in train
    self.model.set_dict(self.ema.apply())
  File "/home/ar/shaoxiong/handpp_work/det_work/work_exps/v3_pddet_picodet_reso320_handcls27det/ppdet/optimizer.py", line 280, in apply
    v = v / (1 - self._decay**self.step)
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py36_paddle2.1/lib/python3.6/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 189, in __impl__
    return scalar_method(self, other_var)
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py36_paddle2.1/lib/python3.6/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 172, in _scalar_div_
    return _scalar_elementwise_op_(var, 1.0 / value, 0.0)
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py36_paddle2.1/lib/python3.6/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 109, in _scalar_elementwise_op_
    return core.ops.scale(var, 'scale', scale, 'bias', bias)
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py36_paddle2.1/lib/python3.6/site-packages/paddle/fluid/multiprocess_utils.py", line 138, in __handler__
    core._throw_error_if_process_failed()
SystemError: (Fatal) DataLoader process (pid 56289) exited is killed by signal: Segmentation fault. (at /paddle/paddle/fluid/imperative/data_loader.cc:181)

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py36_paddle2.1/lib/python3.6/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py36_paddle2.1/lib/python3.6/site-packages/paddle/fluid/multiprocess_utils.py", line 138, in __handler__
    core._throw_error_if_process_failed()
SystemError: (Fatal) DataLoader process (pid 56306) exited is killed by signal: Segmentation fault. (at /paddle/paddle/fluid/imperative/data_loader.cc:181)

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py36_paddle2.1/lib/python3.6/site-packages/matplotlib/_pylab_helpers.py", line 85, in destroy_all
    for manager in list(cls.figs.values()):
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py36_paddle2.1/lib/python3.6/site-packages/paddle/fluid/multiprocess_utils.py", line 138, in __handler__
    core._throw_error_if_process_failed()
SystemError: (Fatal) DataLoader process (pid 56290) exited is killed by signal: Segmentation fault. (at /paddle/paddle/fluid/imperative/data_loader.cc:181)

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py36_paddle2.1/lib/python3.6/logging/__init__.py", line 1946, in shutdown
    h.close()
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py36_paddle2.1/lib/python3.6/logging/__init__.py", line 895, in close
    _acquireLock()
  File "/home/ar/shaoxiong/envs/anaconda3/envs/py36_paddle2.1/lib/python3.6/site-packages/paddle/fluid/multiprocess_utils.py", line 138, in __handler__
    core._throw_error_if_process_failed()
SystemError: (Fatal) DataLoader process (pid 56290) exited is killed by signal: Segmentation fault. (at /paddle/paddle/fluid/imperative/data_loader.cc:181)
```

**Comment by heavengate** [comment]
看报错信息是子进程出segmentfault了，把对应的`configs/xxx/_base_/xxx_reader.yml`里的`num_workers`设置成0跑下看看报不报错呢

**Comment by youngstu** [comment]
把num_workers=0还是同样的问题。在coco数据集上验证也一样

**Comment by youngstu** [comment]
2.1+dev版本，picodet+ppyolo_tiny，coco+自己的数据集问题都存在

**Comment by youngstu** [comment]
在一些机器上运行良好，在其他机器上运行出错，可能需要检查一下代码是否依赖机器环境

**Comment by m00nLi** [comment]
真是shit一样的代码，还没解决就close了

**Comment by YinRui1991** [comment]
试试这个OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 python train.py
