### ISSUE TITLE
cutmix 运行出错

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/PaddleDetection#3988]
![Screenshot from 2021-08-16 20-36-24](https://user-images.githubusercontent.com/26452514/129565330-cced9f35-6dc5-47bf-9113-23e9f1809b28.png)

```
[08/16 20:17:17] reader WARNING: fail to map sample transform [Cutmix_46c5e7] with error: cutmix need two samples and stack:
Traceback (most recent call last):
  File "/ssd2/shaoxiong/handpp_work/det_work/work_exps/v3_1_pddet_picodet_reso320_handcls27det_exp_mosaic/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/ssd2/shaoxiong/handpp_work/det_work/work_exps/v3_1_pddet_picodet_reso320_handcls27det_exp_mosaic/ppdet/data/transform/operators.py", line 1534, in __call__
    assert len(sample) == 2, 'cutmix need two samples'
AssertionError: cutmix need two samples
```

问题：
1、cutmix 功能在其他机器上验证OK，在这个机器上运行出错
2、配置文件中没有开启cutmix功能（cutmix_epoch=-1），只是打开mosaic(mosaic_epoch=15)，但结果却报cutmix错误（在其他机器上不会存在解析错误的问题）
3、代码运行逻辑很多依赖机器环境，可能这方面要多检查一下

**Comment by yghstill** [comment]
@youngstu 多谢反馈，我们排查定位一下问题

**Comment by wangxinxin08** [comment]
如果不用cutmix，可以把cutmix这个字段去掉
