### ISSUE TITLE
使用faster_rcnn进行eval时，出现 received numel():-4 < 0  ,仅修改了config下datesets里面coco的文件路径

### ISSUE THREAD

**Issue by wxh453751461** [PaddlePaddle/PaddleDetection#3998]
Traceback (most recent call last):
  File "tools/train.py", line 139, in <module>
    main()
  File "tools/train.py", line 135, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 110, in run
    trainer.train(FLAGS.eval)
  File "/home/xddz/anaconda3/envs/wxh/lib/python3.6/site-packages/ppdet/engine/trainer.py", line 350, in train
    self._eval_with_loader(self._eval_loader)
  File "/home/xddz/anaconda3/envs/wxh/lib/python3.6/site-packages/ppdet/engine/trainer.py", line 366, in _eval_with_loader
    outs = self.model(data)
  File "/home/xddz/anaconda3/envs/wxh/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/xddz/anaconda3/envs/wxh/lib/python3.6/site-packages/ppdet/modeling/architectures/meta_arch.py", line 29, in forward
    out = self.get_pred()
  File "/home/xddz/anaconda3/envs/wxh/lib/python3.6/site-packages/ppdet/modeling/architectures/faster_rcnn.py", line 104, in get_pred
    bbox_pred, bbox_num = self._forward()
  File "/home/xddz/anaconda3/envs/wxh/lib/python3.6/site-packages/ppdet/modeling/architectures/faster_rcnn.py", line 91, in _forward
    im_shape, scale_factor)
  File "/home/xddz/anaconda3/envs/wxh/lib/python3.6/site-packages/ppdet/modeling/post_process.py", line 120, in get_pred
    scaled_bbox = pred_bbox / scale_factor_list
  File "/home/xddz/anaconda3/envs/wxh/lib/python3.6/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 250, in __impl__
    return math_op(self, other_var, 'axis', axis)
RuntimeError: (PreconditionNotMet) The Tensor's element number must be equal or greater than zero. The Tensor's shape is [-1, 4] now
  [Hint: Expected numel() >= 0, but received numel():-4 < 0:0.] (at /paddle/paddle/fluid/framework/tensor.cc:59)
  [operator < elementwise_div > error]

**Comment by wangxinxin08** [comment]
可以先检查下coco数据集路径是否设置正确

**Comment by wxh453751461** [comment]
> 可以先检查下coco数据集路径是否设置正确

路径设置没有问题，训练过程可以正常进行，但是eval不可以，很奇怪

**Comment by wangxinxin08** [comment]
可以更新下PaddleDetection的版本到release/2.2试下

**Comment by wxh453751461** [comment]
> 可以更新下PaddleDetection的版本到release/2.2试下

好 我试一下

**Comment by wxh453751461** [comment]
> 可以更新下PaddleDetection的版本到release/2.2试下

在2.2下还是不行 (wxh) xddz@xddz:/devdata/wpz/PaddleDetection$ python tools/train.py -c configs/faster_rcnn/faster_rcnn_r50_1x_coco.yml --eval
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[08/18 10:55:25] ppdet.data.source.coco WARNING: Illegal image file: dataset/coco/train2017/20200324230813-O_副本.jpg, and it will be ignored
W0818 10:55:25.800381 22507 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 10.2, Runtime API Version: 10.1
W0818 10:55:25.806576 22507 device_context.cc:422] device: 0, cuDNN Version: 7.6.
[08/18 10:55:29] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/xddz/.cache/paddle/weights/ResNet50_cos_pretrained.pdparams
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[08/18 10:55:29] ppdet.engine INFO: Epoch: [0] [ 0/95] learning_rate: 0.001000 loss_rpn_cls: 0.693745 loss_rpn_reg: 0.003066 loss_bbox_cls: 0.657217 loss_bbox_reg: 0.049328 loss: 1.403356 eta: 0:13:18 batch_cost: 0.7005 data_cost: 0.0015 ips: 1.4275 images/s
[08/18 10:55:43] ppdet.engine INFO: Epoch: [0] [20/95] learning_rate: 0.001180 loss_rpn_cls: 0.690967 loss_rpn_reg: 0.011764 loss_bbox_cls: 0.062813 loss_bbox_reg: 1344232121891902412169521659904.000000 loss: 1344232121891902412169521659904.000000 eta: 0:12:22 batch_cost: 0.6608 data_cost: 0.0003 ips: 1.5133 images/s
[08/18 10:55:56] ppdet.engine INFO: Epoch: [0] [40/95] learning_rate: 0.001360 loss_rpn_cls: 0.678847 loss_rpn_reg: 0.015017 loss_bbox_cls: 0.048135 loss_bbox_reg: 19743834359939172741244824584192.000000 loss: 19743834359939172741244824584192.000000 eta: 0:12:13 batch_cost: 0.6718 data_cost: 0.0003 ips: 1.4885 images/s
[08/18 10:56:10] ppdet.engine INFO: Epoch: [0] [60/95] learning_rate: 0.001540 loss_rpn_cls: 0.656632 loss_rpn_reg: 0.008285 loss_bbox_cls: 0.055758 loss_bbox_reg: 9011891525107668485436349771415552.000000 loss: 9011891525107668485436349771415552.000000 eta: 0:12:01 batch_cost: 0.6690 data_cost: 0.0003 ips: 1.4948 images/s
[08/18 10:56:22] ppdet.engine INFO: Epoch: [0] [80/95] learning_rate: 0.001720 loss_rpn_cls: 0.681173 loss_rpn_reg: 0.010133 loss_bbox_cls: nan loss_bbox_reg: nan loss: nan eta: 0:11:38 batch_cost: 0.6311 data_cost: 0.0002 ips: 1.5845 images/s
[08/18 10:56:34] ppdet.utils.checkpoint INFO: Save checkpoint: output/faster_rcnn_r50_1x_coco
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Traceback (most recent call last):
  File "tools/train.py", line 139, in <module>
    main()
  File "tools/train.py", line 135, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 110, in run
    trainer.train(FLAGS.eval)
  File "/home/xddz/anaconda3/envs/wxh/lib/python3.6/site-packages/ppdet/engine/trainer.py", line 350, in train
    self._eval_with_loader(self._eval_loader)
  File "/home/xddz/anaconda3/envs/wxh/lib/python3.6/site-packages/ppdet/engine/trainer.py", line 366, in _eval_with_loader
    outs = self.model(data)
  File "/home/xddz/anaconda3/envs/wxh/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/xddz/anaconda3/envs/wxh/lib/python3.6/site-packages/ppdet/modeling/architectures/meta_arch.py", line 29, in forward
    out = self.get_pred()
  File "/home/xddz/anaconda3/envs/wxh/lib/python3.6/site-packages/ppdet/modeling/architectures/faster_rcnn.py", line 104, in get_pred
    bbox_pred, bbox_num = self._forward()
  File "/home/xddz/anaconda3/envs/wxh/lib/python3.6/site-packages/ppdet/modeling/architectures/faster_rcnn.py", line 91, in _forward
    im_shape, scale_factor)
  File "/home/xddz/anaconda3/envs/wxh/lib/python3.6/site-packages/ppdet/modeling/post_process.py", line 120, in get_pred
    scaled_bbox = pred_bbox / scale_factor_list
  File "/home/xddz/anaconda3/envs/wxh/lib/python3.6/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 250, in __impl__
    return math_op(self, other_var, 'axis', axis)
RuntimeError: (PreconditionNotMet) The Tensor's element number must be equal or greater than zero. The Tensor's shape is [-1, 4] now
  [Hint: Expected numel() >= 0, but received numel():-4 < 0:0.] (at /paddle/paddle/fluid/framework/tensor.cc:59)
  [operator < elementwise_div > error]

**Comment by wangxinxin08** [comment]
你先直接用python tools/eval.py -c configs/xxx/xxx.yml -o weights=xxx.pdparams测试下看看能不能通过

**Comment by wxh453751461** [comment]
> 你先直接用python tools/eval.py -c configs/xxx/xxx.yml -o weights=xxx.pdparams测试下看看能不能通过

还是同样的错误

**Comment by wxh453751461** [comment]
> 你先直接用python tools/eval.py -c configs/xxx/xxx.yml -o weights=xxx.pdparams测试下看看能不能通过

metric: COCO
num_classes: 1

TrainDataset:
  !COCODataSet
    image_dir: train2017
    anno_path: annotations/instances_train2017.json
    dataset_dir: dataset/coco
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val2017
    anno_path: annotations/instances_val2017.json
    dataset_dir: dataset/coco

TestDataset:
  !ImageFolder
    anno_path: annotations/instances_val2017.json
这是 coco_detection的文件内容

**Comment by wangxinxin08** [comment]
看你图片数量比较少，建议使用coco的预训练吧，原因猜测是pred_bbox为空导致的，可以把snapshot_epoch设置大一些

**Comment by wxh453751461** [comment]
> 看你图片数量比较少，建议使用coco的预训练吧，原因猜测是pred_bbox为空导致的，可以把snapshot_epoch设置大一些

谢谢 我尝试一下

**Comment by wxh453751461** [comment]
> 看你图片数量比较少，建议使用coco的预训练吧，原因猜测是pred_bbox为空导致的，可以把snapshot_epoch设置大一些
我把snapshot_epoch从1->10，还是不太行，我可以把数据发给您，帮我看一下吗

**Comment by wxh453751461** [comment]
> 看你图片数量比较少，建议使用coco的预训练吧，原因猜测是pred_bbox为空导致的，可以把snapshot_epoch设置大一些

我把snapshot_epoch从1->10，还是不太行，我可以把数据发给您，帮我看一下吗

**Comment by wangxinxin08** [comment]
建议你先检查一下eval的数据，我们本地在coco上测试是没有问题的

**Comment by wxh453751461** [comment]
> 建议你先检查一下eval的数据，我们本地在coco上测试是没有问题的

我换成了标准的官方数据集，还是会出现同样的错误

**Comment by wangxinxin08** [comment]
我使用coco数据集eval没有遇到这个问题，你如果使用pip的方式安装了ppdet，可以先pip uninstall 一下，然后将PaddleDetection代码更新到release/2.2，PaddlePaddle版本2.1.2

**Comment by 827346462** [comment]
> 我使用coco数据集eval没有遇到这个问题，你如果使用pip的方式安装了ppdet，可以先pip uninstall 一下，然后将PaddleDetection代码更新到release/2.2，PaddlePaddle版本2.1.2

我觉得这个代码也有问题的。我用同一个数据集 同样的mask_rcnn的配置文件进行训练。epoch200次 就会出现这个问题。eval和test都出现tensors错误。之前以为是静态图的问题，但是我看源码加载模型就是用的paddle.load。  同样的我训练20epoch 就可以test和val（虽然结果很差）。所有为啥训练次数多了会出现这个问题？？我试过mask_rcnn的所有配置文件。
![image](https://user-images.githubusercontent.com/50097546/130381970-37340eb2-0c5b-4417-a596-5a4c3180d885.png)

都会有这个错误，甚至有的第一次可以。后面也出现同样的问题
我的配置是paddleDetection 2.2 paddlepaddle 2.1.1
我采用的是win10系统。
