### ISSUE TITLE
模型导出报错，AttributeError: 'Assign' object has no attribute 'type_comment'

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleDetection#4011]
python 3.8
paddlepaddle-gpu    2.1.1.post112

___________________

python tools/export_model.py -c configs/cascade_rcnn/cascade_rcnn_r50_vd_fpn_ssld_1x_coco.yml --output_dir=./inference_model_cascade_rcnn_r50_vd_fpn_ssld_1x  -o weights=/media/hello/3bc7a812-b6eb-46b7-b538-8a31cfee047f/PaddleDetection/output/cascade_rcnn_r50_vd_fpn_ssld_1x_coco/10.pdparams

______________________

`
python tools/export_model.py -c configs/cascade_rcnn/cascade_rcnn_r50_vd_fpn_ssld_1x_coco.yml --output_dir=./inference_model_cascade_rcnn_r50_vd_fpn_ssld_1x  -o weights=/media/hello/3bc7a812-b6eb-46b7-b538-8a31cfee047f/PaddleDetection/output/cascade_rcnn_r50_vd_fpn_ssld_1x_coco/model_final.pdparams
/media/hello/3bc7a812-b6eb-46b7-b538-8a31cfee047f/anaconda3/envs/PaddleDetection/lib/python3.8/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
/media/hello/3bc7a812-b6eb-46b7-b538-8a31cfee047f/anaconda3/envs/PaddleDetection/lib/python3.8/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
[08/18 20:08:44] ppdet.utils.checkpoint INFO: Finish loading model weights: /media/hello/3bc7a812-b6eb-46b7-b538-8a31cfee047f/PaddleDetection/output/cascade_rcnn_r50_vd_fpn_ssld_1x_coco/model_final.pdparams
[08/18 20:08:44] ppdet.engine INFO: Export inference config file to ./inference_model_cascade_rcnn_r50_vd_fpn_ssld_1x/cascade_rcnn_r50_vd_fpn_ssld_1x_coco/infer_cfg.yml
/media/hello/3bc7a812-b6eb-46b7-b538-8a31cfee047f/anaconda3/envs/PaddleDetection/lib/python3.8/site-packages/paddle/fluid/layers/utils.py:77: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  return (isinstance(seq, collections.Sequence) and
Traceback (most recent call last):
  File "tools/export_model.py", line 108, in <module>
    main()
  File "tools/export_model.py", line 104, in main
    run(FLAGS, cfg)
  File "tools/export_model.py", line 72, in run
    trainer.export(FLAGS.output_dir)
  File "/media/hello/3bc7a812-b6eb-46b7-b538-8a31cfee047f/anaconda3/envs/PaddleDetection/lib/python3.8/site-packages/paddledet-2.1.0-py3.8.egg/ppdet/engine/trainer.py", line 505, in export
    input_spec, static_model.forward.main_program,
  File "/media/hello/3bc7a812-b6eb-46b7-b538-8a31cfee047f/anaconda3/envs/PaddleDetection/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 534, in main_program
    concrete_program = self.concrete_program
  File "/media/hello/3bc7a812-b6eb-46b7-b538-8a31cfee047f/anaconda3/envs/PaddleDetection/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 454, in concrete_program
    return self.concrete_program_specify_input_spec(input_spec=None)
  File "/media/hello/3bc7a812-b6eb-46b7-b538-8a31cfee047f/anaconda3/envs/PaddleDetection/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 487, in concrete_program_specify_input_spec
    concrete_program, _ = self.get_concrete_program(
  File "/media/hello/3bc7a812-b6eb-46b7-b538-8a31cfee047f/anaconda3/envs/PaddleDetection/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/media/hello/3bc7a812-b6eb-46b7-b538-8a31cfee047f/anaconda3/envs/PaddleDetection/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/media/hello/3bc7a812-b6eb-46b7-b538-8a31cfee047f/anaconda3/envs/PaddleDetection/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 698, in _build_once
    concrete_program = ConcreteProgram.from_func_spec(
  File "<decorator-gen-65>", line 2, in from_func_spec
  File "/media/hello/3bc7a812-b6eb-46b7-b538-8a31cfee047f/anaconda3/envs/PaddleDetection/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/media/hello/3bc7a812-b6eb-46b7-b538-8a31cfee047f/anaconda3/envs/PaddleDetection/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/media/hello/3bc7a812-b6eb-46b7-b538-8a31cfee047f/anaconda3/envs/PaddleDetection/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 620, in from_func_spec
    static_func = convert_to_static(dygraph_function)
  File "/media/hello/3bc7a812-b6eb-46b7-b538-8a31cfee047f/anaconda3/envs/PaddleDetection/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 141, in convert_to_static
    static_func = _FUNCTION_CACHE.convert_with_cache(function)
  File "/media/hello/3bc7a812-b6eb-46b7-b538-8a31cfee047f/anaconda3/envs/PaddleDetection/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 78, in convert_with_cache
    static_func = self._convert(func)
  File "/media/hello/3bc7a812-b6eb-46b7-b538-8a31cfee047f/anaconda3/envs/PaddleDetection/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 122, in _convert
    create_and_update_origin_info_map(root_wrapper.node, static_func)
  File "/media/hello/3bc7a812-b6eb-46b7-b538-8a31cfee047f/anaconda3/envs/PaddleDetection/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/origin_info.py", line 163, in create_and_update_origin_info_map
    for t_node, s_node in ast_walk(transformed_node, static_node):
  File "/media/hello/3bc7a812-b6eb-46b7-b538-8a31cfee047f/anaconda3/envs/PaddleDetection/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/origin_info.py", line 241, in ast_walk
    t_node_child = getattr(t_node, field)
AttributeError: 'Assign' object has no attribute 'type_comment'

`

**Comment by lyuwenyu** [comment]
1. 查看一下 gast版本 高于0.4.0版本的话 请安装使用gast==0.4.0版本
2. 或者 升级paddle到2.1.2或者develop
