### ISSUE TITLE
训练Frcnn模型，显存溢出 

### ISSUE THREAD

**Issue by ellinyang** [PaddlePaddle/PaddleDetection#4036]
运行环境：
Linux
paddlepaddle-gpu=2.1.2
paddledetection 2.1
数据集：DOTA数据集，图片约4000*4000大小
参数配置：
模型选择：faster_rcnn_r50_vd_fpn_2x
batch_size：1
target_size:1344*1344

问题：
1.单卡训练Frcnn时，在第一个epoch,某固定step，显存溢出而失败；
2. 8卡V100进行训练，每个节点占用显存不同；在第一个epoch 固定的step，因为某节点显存溢出而失败；
![image](https://user-images.githubusercontent.com/20673237/130349858-c2c85476-490e-4a72-9a82-20322dc82fdb.png)

单卡报错细节：
```
[08/17 23:07:02] ppdet.engine INFO: Epoch: [0] [  60/1411] learning_rate: 0.000385 loss_rpn_cls: 0.329103 loss_rpn_reg: 0.442250 loss_bbox_cls: 1.050607 loss_bbox_reg: 0.385772 loss: 2.121466 eta: 3:50:44 batch_cost: 0.1540 data_cost: 0.0104 ips: 6.4938 images/s
Traceback (most recent call last):
  File "tools/train.py", line 139, in <module>
    main()
  File "tools/train.py", line 135, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 110, in run
    trainer.train(FLAGS.eval)
  File "/home/ylj/ssd1/ylj/DLcode/PaddleDetection/ppdet/engine/trainer.py", line 306, in train
    outputs = model(data)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/ylj/ssd1/ylj/DLcode/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 26, in forward
    out = self.get_loss()
  File "/home/ylj/ssd1/ylj/DLcode/PaddleDetection/ppdet/modeling/architectures/faster_rcnn.py", line 95, in get_loss
    rpn_loss, bbox_loss = self._forward()
  File "/home/ylj/ssd1/ylj/DLcode/PaddleDetection/ppdet/modeling/architectures/faster_rcnn.py", line 76, in _forward
    rois, rois_num, rpn_loss = self.rpn_head(body_feats, self.inputs)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/ylj/ssd1/ylj/DLcode/PaddleDetection/ppdet/modeling/proposal_generator/rpn_head.py", line 142, in forward
    loss = self.get_loss(scores, deltas, anchors, inputs)
  File "/home/ylj/ssd1/ylj/DLcode/PaddleDetection/ppdet/modeling/proposal_generator/rpn_head.py", line 229, in get_loss
    anchors)
  File "/home/ylj/ssd1/ylj/DLcode/PaddleDetection/ppdet/modeling/proposal_generator/target_layer.py", line 79, in __call__
    batch_size, self.ignore_thresh, is_crowd)
  File "/home/ylj/ssd1/ylj/DLcode/PaddleDetection/ppdet/modeling/proposal_generator/target.py", line 40, in rpn_anchor_target
    ignore_thresh, is_crowd_i)
  File "/home/ylj/ssd1/ylj/DLcode/PaddleDetection/ppdet/modeling/proposal_generator/target.py", line 74, in label_box
    iou = bbox_overlaps(gt_boxes, anchors)
  File "/home/ylj/ssd1/ylj/DLcode/PaddleDetection/ppdet/modeling/bbox_utils.py", line 142, in bbox_overlaps
    paddle.zeros_like(inter))
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/tensor/search.py", line 520, in where
    return core.ops.where(condition, x, y)
SystemError: (Fatal) Operator where raises an paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 1023.966797MB memory on GPU 0, 14.803345GB memory has been allocated and available memory is only 971.875000MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:79)
. (at /paddle/paddle/fluid/imperative/tracer.cc:192)
```

多卡报错细节如下：
```
I0822 16:51:11.324589 15430 gen_comm_id_helper.cc:181] Server listening on: 127.0.0.1:56316 successful.
I0822 16:51:11.626694 15430 nccl_context.cc:74] init nccl context nranks: 8 local rank: 5 gpu id: 5 ring id: 0
W0822 16:51:14.859879 15430 device_context.cc:404] Please NOTE: device: 5, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0822 16:51:14.865319 15430 device_context.cc:422] device: 5, cuDNN Version: 7.6.
I0822 16:51:21.825774 15430 nccl_context.cc:107] init nccl context nranks: 8 local rank: 5 gpu id: 5 ring id: 10
/root/miniconda3/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
2021-08-22 16:51:23,423-INFO: [topology.py:152:__init__] HybridParallelInfo: rank_id: 5, dp_degree: 8, mp_degree: 1, pp_degree: 1, dp_group: [0, 1, 2, 3, 4, 5, 6, 7], mp_group: [5], pp_group: [5], check/clip group: [5]
loading annotations into memory...
Done (t=2.01s)
creating index...
index created!
/home/ylj/ssd1/ylj/DLcode/PaddleDetection/ppdet/data/crop_utils/annotation_cropper.py:264: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  chips = np.array(chips, dtype=np.float)
/home/ylj/ssd1/ylj/DLcode/PaddleDetection/ppdet/data/crop_utils/annotation_cropper.py:294: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  high = valid_ratio_range[1] if valid_ratio_range[1] > 0 else np.finfo(np.float).max
loading annotations into memory...
Done (t=0.62s)
creating index...
index created!
loading annotations into memory...
Done (t=0.73s)
creating index...
index created!
Traceback (most recent call last):
  File "tools/train.py", line 165, in <module>
    main()
  File "tools/train.py", line 161, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 124, in run
    trainer.train(FLAGS.eval)
  File "/home/ylj/ssd1/ylj/DLcode/PaddleDetection/ppdet/engine/trainer.py", line 137, in train
    super(Trainer, self).train(validate=validate)
  File "/home/ylj/ssd1/ylj/DLcode/PaddleDetection/ppdet/engine/trainer.py", line 306, in train
    outputs = model(data)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/parallel.py", line 578, in forward
    outputs = self._layers(*inputs, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/ylj/ssd1/ylj/DLcode/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 26, in forward
    out = self.get_loss()
  File "/home/ylj/ssd1/ylj/DLcode/PaddleDetection/ppdet/modeling/architectures/faster_rcnn.py", line 95, in get_loss
    rpn_loss, bbox_loss = self._forward()
  File "/home/ylj/ssd1/ylj/DLcode/PaddleDetection/ppdet/modeling/architectures/faster_rcnn.py", line 76, in _forward
    rois, rois_num, rpn_loss = self.rpn_head(body_feats, self.inputs)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/ylj/ssd1/ylj/DLcode/PaddleDetection/ppdet/modeling/proposal_generator/rpn_head.py", line 142, in forward
    loss = self.get_loss(scores, deltas, anchors, inputs)
  File "/home/ylj/ssd1/ylj/DLcode/PaddleDetection/ppdet/modeling/proposal_generator/rpn_head.py", line 229, in get_loss
    anchors)
  File "/home/ylj/ssd1/ylj/DLcode/PaddleDetection/ppdet/modeling/proposal_generator/target_layer.py", line 79, in __call__
    batch_size, self.ignore_thresh, is_crowd)
  File "/home/ylj/ssd1/ylj/DLcode/PaddleDetection/ppdet/modeling/proposal_generator/target.py", line 40, in rpn_anchor_target
    ignore_thresh, is_crowd_i)
  File "/home/ylj/ssd1/ylj/DLcode/PaddleDetection/ppdet/modeling/proposal_generator/target.py", line 74, in label_box
    iou = bbox_overlaps(gt_boxes, anchors)
  File "/home/ylj/ssd1/ylj/DLcode/PaddleDetection/ppdet/modeling/bbox_utils.py", line 135, in bbox_overlaps
    paddle.unsqueeze(boxes1, 1)[:, :, :2], boxes2[:, :2])
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/tensor/math.py", line 570, in maximum
    x, y, axis=axis, act=act, op_name=op_type)
  File "/root/miniconda3/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 227, in __impl__
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/tensor/math.py", line 179, in _elementwise_op_in_dygraph
    out = op(x, y, 'axis', axis, 'use_mkldnn', use_mkldnn)
SystemError: (Fatal) Operator elementwise_max raises an paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError: 

Out of memory error on GPU 5. Cannot allocate 7.159521GB memory on GPU 5, 12.459595GB memory has been allocated and available memory is only 3.292847GB.

Please check whether there is any other process using GPU 5.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:79)
. (at /paddle/paddle/fluid/imperative/tracer.cc:192)

terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  (External)  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/stream/cuda_stream.cc:95)



--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::platform::NCCLCommContext::ReleaseNCCLComms()
1   paddle::platform::NCCLCommImpl::~NCCLCommImpl()
2   paddle::platform::CUDADeviceContext::~CUDADeviceContext()
3   paddle::platform::CUDADeviceContext::~CUDADeviceContext()
4   std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release()
5   std::_Sp_counted_ptr<paddle::platform::CUDAContext*, (__gnu_cxx::_Lock_policy)2>::_M_dispose()
6   paddle::platform::CUDAContext::~CUDAContext()
7   paddle::platform::stream::CUDAStream::Destroy()
8   paddle::framework::SignalHandle(char const*, int)
9   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1629622562 (unix time) try "date -d @1629622562" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3c46) received by PID 15430 (TID 0x7fdb14547740) from PID 15430 ***]

/root/miniconda3/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::Tensor::mutable_data(paddle::platform::Place const&, paddle::framework::proto::VarType_Type, unsigned long)
1   paddle::memory::AllocShared(paddle::platform::Place const&, unsigned long)
2   paddle::memory::allocation::AllocatorFacade::AllocShared(paddle::platform::Place const&, unsigned long)
3   paddle::memory::allocation::AllocatorFacade::Alloc(paddle::platform::Place const&, unsigned long)
4   paddle::memory::allocation::RetryAllocator::AllocateImpl(unsigned long)
5   paddle::framework::SignalHandle(char const*, int)
6   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1629622579 (unix time) try "date -d @1629622579" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x4223) received by PID 17013 (TID 0x7fc56f047740) from PID 16931 ***]


```

**Comment by haozech** [comment]
您好 能否提供下简单的业务无关可复现代码，方便排查问题

**Comment by jerrywgz** [comment]
通过线下沟通，问题属于显存不足，需要将模型中的一部分模块改写
