### ISSUE TITLE
人脸检测训练报错

### ISSUE THREAD

**Issue by Danvae** [PaddlePaddle/PaddleDetection#4042]
使用版本：release-0.3代码；paddle=1.7.2
报错如下：
(paddle_env) E:\PaddleDetection-release-0.3>python -u ./tools/train.py -c ./configs/face_detection/blazeface.yml -o pretrain_weights=./blazeface_original
2021-08-23 17:48:21,246-WARNING: ./blazeface_original.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2021-08-23 17:48:21,246-WARNING: ./blazeface_original.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
Traceback (most recent call last):
  File "./tools/train.py", line 368, in <module>
    main()
  File "./tools/train.py", line 199, in main
    exe, train_prog, cfg.pretrain_weights, ignore_params=ignore_params)
  File "E:\FDD\Software\Pycharm\PycharmProjects\face_detection\PaddleDetection-release-0.3\ppdet\utils\checkpoint.py", line 150, in load_params
    fluid.io.set_program_state(prog, state)
  File "C:\ProgramData\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\io.py", line 1934, in set_program_state
    "Variable [ {} ] Not found, Please make sure run startup program".format(para.name)
AssertionError: Variable [ reduce_sum_2.tmp_0 ] Not found, Please make sure run startup program

**Comment by jerrywgz** [comment]
release/0.3分支的代码比较老了，建议迁移到PaddleDetection release/2.2版本以及Paddle 2.1.2版本。另外目前动态图也已经支持blazeface模型
