### ISSUE TITLE
solov2 paddle serving 部署

### ISSUE THREAD

**Issue by zouxiaoshi** [PaddlePaddle/PaddleDetection#4066]
您好：

在用solov2 部署在 paddle serving 时出现了错误，请帮忙看下。

### test_client.py 
```python
import numpy as np
from paddle_serving_client import Client
from paddle_serving_app.reader import *
import cv2

preprocess = Sequential([
    File2Image(), 
    Resize((512, 852), interpolation=cv2.INTER_LINEAR), 
    Div(255),
    Normalize([0.485, 0.456, 0.406],[0.229, 0.224, 0.225]),
    Transpose((2, 0, 1))
])

postprocess = SegPostprocess(class_num=5)


img_path = './imgs/000363.jpg'
im = preprocess(img_path)

client = Client()
client.load_client_config("client_config/det_serving_client_conf.prototxt")
client.connect(['ip:port'])

fetch_map = client.predict(
    feed={
        "image": np.array(im),
        "im_shape": np.array(im.shape[1:]),
        "scale_factor":np.array([1.0, 1.0]),
    },
    fetch=["save_infer_model/scale_0.tmp_1",
            "save_infer_model/scale_1.tmp_1",
            "save_infer_model/scale_2.tmp_1",
            "save_infer_model/scale_3.tmp_1"
            ],
    batch=False
)
fetch_map["filename"] = img_path
postprocess(fetch_map)
```

### 报错信息：
```bash
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

  Compile Traceback (most recent call last):
    File "tools/export_model.py", line 116, in <module>
      main()
    File "tools/export_model.py", line 112, in main
      run(FLAGS, cfg)
    File "tools/export_model.py", line 78, in run
      trainer.export(FLAGS.output_dir)
    File "/root/miniconda3/lib/python3.8/site-packages/paddledet-2.2.0-py3.8.egg/ppdet/engine/trainer.py", line 576, in export
      input_spec, static_model.forward.main_program,
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 542, in main_program
      concrete_program = self.concrete_program
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 458, in concrete_program
      return self.concrete_program_specify_input_spec(input_spec=None)
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 495, in concrete_program_specify_input_spec
      concrete_program, _ = self.get_concrete_program(
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 406, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 723, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 709, in _build_once
      concrete_program = ConcreteProgram.from_func_spec(
    File "<decorator-gen-97>", line 2, in from_func_spec
      
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
      return func(*args, **kwargs)
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 662, in from_func_spec
      outputs = static_func(*inputs)
    File "/root/miniconda3/lib/python3.8/site-packages/paddledet-2.2.0-py3.8.egg/ppdet/modeling/architectures/meta_arch.py", line 23, in forward
      self.model_arch()
    File "/root/miniconda3/lib/python3.8/site-packages/paddledet-2.2.0-py3.8.egg/ppdet/modeling/architectures/solov2.py", line 67, in model_arch
      body_feats = self.backbone(self.inputs)
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 907, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/root/miniconda3/lib/python3.8/site-packages/paddledet-2.2.0-py3.8.egg/ppdet/modeling/backbones/resnet.py", line 582, in forward
      conv1 = self.conv1(x)
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 907, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/container.py", line 98, in forward
      input = layer(input)
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 907, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/tmp/tmpo4hxct88.py", line 32, in forward
      out = paddle.jit.dy2static.convert_ifelse(self.norm_type in ['bn',
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/root/miniconda3/lib/python3.8/site-packages/paddledet-2.2.0-py3.8.egg/ppdet/modeling/backbones/resnet.py", line 133, in forward
      out = self.norm(out)
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 907, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/nn/layer/norm.py", line 1126, in forward
      self._helper.append_op(
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layer_object_helper.py", line 47, in append_op
      return self.main_program.current_block().append_op(
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3108, in append_op
      op = Operator(
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2161, in __init__
      for frame in traceback.extract_stack():

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------

----------------------
Error Message Summary:
----------------------
NotFoundError: Operator (sync_batch_norm) does not have kernel for data_type[float]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN].
  [Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] (at /paddle/paddle/fluid/framework/operator.cc:1276)
  [operator < sync_batch_norm > error]
```

环境如下：
paddle-serving-app        0.6.1
paddle-serving-client     0.6.1
paddle-serving-server-gpu 0.6.1.post102
paddlepaddle-gpu          2.1.2

**Comment by zouxiaoshi** [comment]
试了各种preprocess，都是报上面的错误：
``` bash
NotFoundError: Operator (sync_batch_norm) does not have kernel for data_type[float]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN].
  [Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] (at /paddle/paddle/fluid/framework/operator.cc:1276)
  [operator < sync_batch_norm > error]
```

所以，感觉错误跟导出的模型相关，
训练环境：
paddledet                 2.2.0              
paddlepaddle-gpu       2.1.2

通过*deploy/python/infer.py* 的方式，可以进行推理的，seving 导出的话，也是正常导出。
版本的话，基本都是全新的。
所以很迷惑，不知道问题出哪里了。

**Comment by lyuwenyu** [comment]
部署的是什么机器，sync_batch_norm在cpu上跑不了吧  报错信息时在cpu上了

**Comment by zouxiaoshi** [comment]
> 部署的是什么机器，sync_batch_norm在cpu上跑不了吧 报错信息时在cpu上了

原来如此，GPU显存不够了，所以临时部署在CPU上，测试一下，然后就出现了
上述的报错。 好的，谢谢，我先用GPU试一下。

您帮我看看， 这个preprocess正确吗，我看 infer_cfg.yml 上还有个 PadStride, 但我引入padstride（stride为32）后会报错，信息如下：
```bash
InvalidArgumentError: The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 32, the input's shape is [1, 32, 1080, 1568]; the filter's channels is 3, the filter's shape is [32, 3, 3, 3]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting.
  [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:32 != filter_dims[1] * groups:3.] (at /paddle/paddle/fluid/operators/conv_op.cc:100)
  [operator < conv2d > error]
```
附 上 solov2 的 infer_cfg.yml 文件
```yaml
mode: fluid
draw_threshold: 0.5
metric: COCO
use_dynamic_shape: true
arch: SOLOv2
min_subgraph_size: 60
Preprocess:
- is_scale: true
  mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
  type: NormalizeImage
- interp: 1
  keep_ratio: true
  target_size:
  - 512
  - 852
  type: Resize
- type: Permute
- stride: 32
  type: PadStride
```

**Comment by zouxiaoshi** [comment]
> 部署的是什么机器，sync_batch_norm在cpu上跑不了吧 报错信息时在cpu上了

用GPU试了下，可以运行。 
但是获取fetch values的时候出现了问题：
```python
fetch_map = client.predict(
    feed={
        "image": np.array(im),
        "im_shape": np.array(im.shape[1:]),
        "scale_factor":np.array([1.0, 1.0]),
    },
    fetch=["save_infer_model/scale_0.tmp_1",
            "save_infer_model/scale_1.tmp_1",
            "save_infer_model/scale_2.tmp_1",
            "save_infer_model/scale_3.tmp_1"],
    batch=False
)
```
#### 当fetch 包含 "save_infer_model/scale_0.tmp_1" 时 报错如下：
```bash
Traceback (most recent call last):
  File "test_model.py", line 25, in <module>
    fetch_map = client.predict(
  File "/usr/local/lib/python3.8/site-packages/paddle_serving_client/client.py", line 482, in predict
    result_map[name] = result_batch_handle.get_int32_by_name(
AttributeError: 'paddle_serving_client.serving_client.PredictorRes' object has no attribute 'get_int32_by_name'
```
#### 当fetch  包含 "save_infer_model/scale_3.tmp_1"时报错：
```bash
Traceback (most recent call last):
  File "test_model.py", line 25, in <module>
    fetch_map = client.predict(
  File "/usr/local/lib/python3.8/site-packages/paddle_serving_client/client.py", line 457, in predict
    raise ValueError(
ValueError: Failed to fetch, maybe the type of [save_infer_model/scale_3.tmp_1] is wrong, please check the model file
```
我看了下，缺少 "save_infer_model/scale_3.tmp_1" 的 fetch_type。

serving_server_conf.prototxt  文件如下：
```text
feed_var {
  name: "im_shape"
  alias_name: "im_shape"
  is_lod_tensor: false
  feed_type: 1
  shape: 2
}
feed_var {
  name: "image"
  alias_name: "image"
  is_lod_tensor: false
  feed_type: 1
  shape: 3
}
feed_var {
  name: "scale_factor"
  alias_name: "scale_factor"
  is_lod_tensor: false
  feed_type: 1
  shape: 2
}
fetch_var {
  name: "save_infer_model/scale_0.tmp_1"
  alias_name: "save_infer_model/scale_0.tmp_1"
  is_lod_tensor: true
  fetch_type: 2
  shape: -1
}
fetch_var {
  name: "save_infer_model/scale_1.tmp_1"
  alias_name: "save_infer_model/scale_1.tmp_1"
  is_lod_tensor: true
  fetch_type: 0
  shape: -1
}
fetch_var {
  name: "save_infer_model/scale_2.tmp_1"
  alias_name: "save_infer_model/scale_2.tmp_1"
  is_lod_tensor: true
  fetch_type: 1
  shape: -1
}
fetch_var {
  name: "save_infer_model/scale_3.tmp_1"
  alias_name: "save_infer_model/scale_3.tmp_1"
  is_lod_tensor: true
  shape: -1
}

```

**Comment by lyuwenyu** [comment]
```
InvalidArgumentError: The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 32, the input's shape is [1, 32, 1080, 1568]; the filter's channels is 3, the filter's shape is [32, 3, 3, 3]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting.
  [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:32 != filter_dims[1] * groups:3.] (at /paddle/paddle/fluid/operators/conv_op.cc:100)
```

你怎么引入的   看着错误信息是channels 对不上啊

**Comment by zouxiaoshi** [comment]
> ```
> InvalidArgumentError: The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 32, the input's shape is [1, 32, 1080, 1568]; the filter's channels is 3, the filter's shape is [32, 3, 3, 3]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting.
>   [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:32 != filter_dims[1] * groups:3.] (at /paddle/paddle/fluid/operators/conv_op.cc:100)
> ```
> 
> 你怎么引入的 看着错误信息是channels 对不上啊

preprocess = Sequential([
    File2Image(), 
    Resize((512,864)),
    Div(255),
    Normalize([0.485, 0.456, 0.406],[0.229, 0.224, 0.225]),
    PadStride(32),
    Transpose((2, 0, 1))
])


我后来把padstride 干掉，可以运行了。
但是 solo 有四个fetch var, 其中
“save_infer_model/scale_0.tmp_1” 和 “save_infer_model/scale_3.tmp_1” 会导致报错


```python
fetch_map = client.predict(
    feed={
        "image": np.array(im),
        "im_shape": np.array(im.shape[1:]),
        "scale_factor":np.array([1.0, 1.0]),
    },
    fetch=["save_infer_model/scale_0.tmp_1",
            "save_infer_model/scale_1.tmp_1",
            "save_infer_model/scale_2.tmp_1",
            "save_infer_model/scale_3.tmp_1"],
    batch=False
)
```

#### fetch 中包含 “save_infer_model/scale_0.tmp_1”  时
```bash
Traceback (most recent call last):
  File "test_model.py", line 25, in <module>
    fetch_map = client.predict(
  File "/usr/local/lib/python3.8/site-packages/paddle_serving_client/client.py", line 482, in predict
    result_map[name] = result_batch_handle.get_int32_by_name(
AttributeError: 'paddle_serving_client.serving_client.PredictorRes' object has no attribute 'get_int32_by_name'
```

#### fetch 中包含 “save_infer_model/scale_3.tmp_1”  时
```bash
Traceback (most recent call last):
  File "test_model.py", line 25, in <module>
    fetch_map = client.predict(
  File "/usr/local/lib/python3.8/site-packages/paddle_serving_client/client.py", line 457, in predict
    raise ValueError(
ValueError: Failed to fetch, maybe the type of [save_infer_model/scale_3.tmp_1] is wrong, please check the model file
```


可否给出个solo模型调用rpc服务的样例，方便 solo 模型部署在paddle serving上。

**Comment by zouxiaoshi** [comment]
> ```
> InvalidArgumentError: The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 32, the input's shape is [1, 32, 1080, 1568]; the filter's channels is 3, the filter's shape is [32, 3, 3, 3]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting.
>   [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:32 != filter_dims[1] * groups:3.] (at /paddle/paddle/fluid/operators/conv_op.cc:100)
> ```
> 
> 你怎么引入的 看着错误信息是channels 对不上啊

看了下 padstride 的源码。。才知道 padstride 操作是基于 nchw 数据格式，而不是nhwc， 所以，先转格式后，就可以运行了。

solo 完整的预处理如下：
```python
from paddle_serving_app.reader import *
preprocess = Sequential([
    File2Image(), 
    BGR2RGB(),
    Div(255),
    Resize((512,512)),
    Normalize([0.485, 0.456, 0.406],[0.229, 0.224, 0.225]),
    Transpose((2, 0, 1)),
    PadStride(32),
])
```
以上预处理是可跑通的，现在就差fetch var部分了，
求大佬指点啊。

**Comment by lyuwenyu** [comment]
fetch var啥问题啊

**Comment by zouxiaoshi** [comment]
> fetch var啥问题啊

代码如下：
```python
from paddle_serving_client import Client
from paddle_serving_app.reader import *

preprocess = Sequential([
    File2Image(), 
    BGR2RGB(),
    Div(255),
    Resize((512,512)),
    Normalize([0.485, 0.456, 0.406],[0.229, 0.224, 0.225]),
    Transpose((2, 0, 1)),
    PadStride(32),
])

img_path = './imgs/000363.jpg'
im = preprocess(img_path)

client = Client()
client.load_client_config("client_config/serving_client_conf.prototxt")
client.connect(['10.25.131.11:9007'])

fetch_map = client.predict(
    feed={
        "image": np.array(im).astype(np.float32),
        "im_shape": np.array([512,512]),
        "scale_factor":np.array([1, 1]),
    },
    fetch=[
             "save_infer_model/scale_0.tmp_1", # segm
            "save_infer_model/scale_1.tmp_1", # category id
            "save_infer_model/scale_2.tmp_1", # score
             "save_infer_model/scale_3.tmp_1" # box num
            ],
    batch=False
)
print(fetch_map)
```

### fetch 中包含 “save_infer_model/scale_0.tmp_1” 时
```bash
Traceback (most recent call last):
  File "test_model.py", line 25, in <module>
    fetch_map = client.predict(
  File "/usr/local/lib/python3.8/site-packages/paddle_serving_client/client.py", line 482, in predict
    result_map[name] = result_batch_handle.get_int32_by_name(
AttributeError: 'paddle_serving_client.serving_client.PredictorRes' object has no attribute 'get_int32_by_name'
```

###  fetch 中包含 “save_infer_model/scale_3.tmp_1” 时
```bash
Traceback (most recent call last):
  File "test_model.py", line 25, in <module>
    fetch_map = client.predict(
  File "/usr/local/lib/python3.8/site-packages/paddle_serving_client/client.py", line 457, in predict
    raise ValueError(
ValueError: Failed to fetch, maybe the type of [save_infer_model/scale_3.tmp_1] is wrong, please check the model file
```

serving_server_conf.prototxt 文件如下：
```text
feed_var {
  name: "im_shape"
  alias_name: "im_shape"
  is_lod_tensor: false
  feed_type: 1
  shape: 2
}
feed_var {
  name: "image"
  alias_name: "image"
  is_lod_tensor: false
  feed_type: 1
  shape: 3
}
feed_var {
  name: "scale_factor"
  alias_name: "scale_factor"
  is_lod_tensor: false
  feed_type: 1
  shape: 2
}
fetch_var {
  name: "save_infer_model/scale_0.tmp_1"
  alias_name: "save_infer_model/scale_0.tmp_1"
  is_lod_tensor: true
  fetch_type: 2
  shape: -1
}
fetch_var {
  name: "save_infer_model/scale_1.tmp_1"
  alias_name: "save_infer_model/scale_1.tmp_1"
  is_lod_tensor: true
  fetch_type: 0
  shape: -1
}
fetch_var {
  name: "save_infer_model/scale_2.tmp_1"
  alias_name: "save_infer_model/scale_2.tmp_1"
  is_lod_tensor: true
  fetch_type: 1
  shape: -1
}
fetch_var {
  name: "save_infer_model/scale_3.tmp_1"
  alias_name: "save_infer_model/scale_3.tmp_1"
  is_lod_tensor: true
  shape: -1
}
```

**Comment by lyuwenyu** [comment]
着急的话先去问问 https://github.com/PaddlePaddle/Serving/issues 吧，有进展了在这留下言

**Comment by zouxiaoshi** [comment]
> 着急的话先去问问 https://github.com/PaddlePaddle/Serving/issues 吧，有进展了在这留下言

好的。 已在serving处提了issue， THX。

**Comment by zouxiaoshi** [comment]
> 着急的话先去问问 https://github.com/PaddlePaddle/Serving/issues 吧，有进展了在这留下言


更新进展： 
2021-09-01 ：  后续会在Serving 的 develop分支进行更正。 更正完成后，我会在这里更新留言，并关闭issue。
2021-09-09:  已在dev分支修正。目前提供 py3.8 cuda10.2的编译版本，具体信息请参阅这个[issue](https://github.com/PaddlePaddle/Serving/issues/1365)  [周末会进行测试，测试通过后，会更新并关闭此issue]
2021-09-12： 测试后，还是未能跑通。
1.  修正了int32数据未识别问题
2. 存在 **Failed to fetch, maybe the type of [save_infer_model/scale_3.tmp_1] is wrong,**
不知道为什么这个fetch var 导出后没有 fetch_type：
```bash
fetch_var {
  name: "save_infer_model/scale_3.tmp_1"
  alias_name: "save_infer_model/scale_3.tmp_1"
  is_lod_tensor: true
  shape: -1
}
```

**Comment by zouxiaoshi** [comment]
@lyuwenyu  能帮我看看 为什么 solov2 模型导出时， “save_infer_model/scale_3.tmp_1” 没有 fetch_type吗？
paddle serving 那边修正int32数据未识别问题，但是依然剩下
```bash
Failed to fetch, maybe the type of [save_infer_model/scale_3.tmp_1] is wrong
```
我感觉是由于 这个fetch var 没有fetch_type有关。

```bash
fetch_var {
  name: "save_infer_model/scale_3.tmp_1"
  alias_name: "save_infer_model/scale_3.tmp_1"
  is_lod_tensor: true
  shape: -1
}

```
