### ISSUE TITLE
【论文复现】训练一定轮次后出现错误 Cuda error(719), unspecified launch failure.

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/PaddleDetection#4068]
在aistudio的脚本任务上基于PaddleDetection套件进行多卡训练，训练到epoch序号接近6时， 出现下面的cuda错误，请帮忙分析下问题 可能出在哪里？

```
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 110, in run
    trainer.train(FLAGS.eval)
  File "/root/paddlejob/workspace/code/ppdet/engine/trainer.py", line 335, in train
    outputs = model(data)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/parallel.py", line 578, in forward
    outputs = self._layers(*inputs, **kwargs)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/root/paddlejob/workspace/code/ppdet/modeling/architectures/meta_arch.py", line 26, in forward
    out = self.get_loss()
  File "/root/paddlejob/workspace/code/ppdet/modeling/architectures/yolox.py", line 86, in get_loss
    return self._forward()
  File "/root/paddlejob/workspace/code/ppdet/modeling/architectures/yolox.py", line 52, in _forward
    fpn_outs, targets, input_img
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/root/paddlejob/workspace/code/ppdet/modeling/architectures/yolox_utils/yolo_head.py", line 171, in forward
    dtype=xin[0].dtype,
  File "/root/paddlejob/workspace/code/ppdet/modeling/architectures/yolox_utils/yolo_head.py", line 334, in get_losses
    imgs,
  File "<decorator-gen-278>", line 2, in get_assignments
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 331, in _decorate_function
    return func(*args, **kwargs)
  File "/root/paddlejob/workspace/code/ppdet/modeling/architectures/yolox_utils/yolo_head.py", line 567, in get_assignments
    ) = self.dynamic_k_matching(cost, pair_wise_ious, gt_classes, num_gt, fg_mask)
  File "/root/paddlejob/workspace/code/ppdet/modeling/architectures/yolox_utils/yolo_head.py", line 688, in dynamic_k_matching
    cost[gt_idx], k=dynamic_ks[gt_idx].item(), largest=False
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 432, in item
    return self._getitem_from_offset(*args).item()
OSError: (External)  Cuda error(719), unspecified launch failure.
  [Advise: Please search for the error code(719) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/gpu_info.cc:394)
```

**Comment by thunder95** [comment]
这个错误是后续代码实现时产生的，还是nn.BCEWithLogitsLoss里cuda核函数引发的？ @qingqing01

**Comment by thunder95** [comment]
```
expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
INFO 2021-08-27 03:39:38,961 launch_utils.py:327] terminate all the procs
ERROR 2021-08-27 03:39:38,961 launch_utils.py:584] ABORT!!! Out of all 4 trainers, the trainer process with rank=[1, 3] was aborted. Please check its log.
INFO 2021-08-27 03:39:41,964 launch_utils.py:327] terminate all the procs
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
```
打印了很多bce的error，然后中途多卡训练时就abort了

**Comment by thunder95** [comment]
已转提到Paddle官方issue

**Comment by wjplove8** [comment]
请问这个问题解决了吗？我也遇到这个问题了

**Comment by ChenjieXu** [comment]
我也遇到这个问题
