### ISSUE TITLE
paddle detection用yolov3_r34_voc 训练自己的数据报错

### ISSUE THREAD

**Issue by Redlyliu** [PaddlePaddle/PaddleDetection#407]
你好，我paddle detection用yolov3_r34_voc 训练自己的数据，出现下面的错误，运行环境是windos10 RTX20206 6G，python3.6.10   paddle 1.7.1，CUDA 9.0 ，CUDNN 7.3.1
error:
2020-03-27 14:20:07,666-INFO: iter: 17200, lr: 0.001000, 'loss': '14.405443', time: 0.527, eta: 7:43:53
2020-03-27 14:20:11,634-INFO: fail to map op [RandomFlipImage_545aca] with error: RandomFlipImage_545aca: invalid box, x2 should be greater than x1 and stack:
Traceback (most recent call last):
  File "D:\ai_nvidia\ai_code\Paddle\PaddleDetection-release-0.2\ppdet\data\reader.py", line 45, in __call__
    data = f(data, ctx)
  File "D:\ai_nvidia\ai_code\Paddle\PaddleDetection-release-0.2\ppdet\data\transform\operators.py", line 427, in __call__
    raise BboxError(m)
ppdet.data.transform.operators.BboxError: RandomFlipImage_545aca: invalid box, x2 should be greater than x1

2020-03-27 14:20:11,646-WARNING: recv endsignal from outq with errmsg[consumer[consumer-05f-2] failed to map with error:[RandomFlipImage_545aca: invalid box, x2 should be greater than x1]]
2020-03-27 14:20:18,789-INFO: iter: 17220, lr: 0.001000, 'loss': '14.676455', time: 0.595, eta: 8:43:36
2020-03-27 14:20:32,041-INFO: iter: 17240, lr: 0.001000, 'loss': '14.626053', time: 0.643, eta: 9:25:01
2020-03-27 14:20:32,511-WARNING: recv endsignal from outq with errmsg[consumer[consumer-05f-1] exits for reason[consumer[consumer-05f-2] failed to map with error:[RandomFlipImage_545aca: invalid box, x2 should be greater than x1]]]
2020-03-27 14:20:40,244-WARNING: recv endsignal from outq with errmsg[consumer[consumer-05f-3] exits for reason[consumer[consumer-05f-1] exits for reason[consumer[consumer-05f-2] failed to map with error:[RandomFlipImage_545aca: invalid box, x2 should be greater than x1]]]]
2020-03-27 14:20:41,087-WARNING: recv endsignal from outq with errmsg[consumer[consumer-05f-4] exits for reason[consumer[consumer-05f-3] exits for reason[consumer[consumer-05f-1] exits for reason[consumer[consumer-05f-2] failed to map with error:[RandomFlipImage_545aca: invalid box, x2 should be greater than x1]]]]]
2020-03-27 14:20:42,242-WARNING: recv endsignal from outq with errmsg[consumer[consumer-05f-0] exits for reason[consumer[consumer-05f-4] exits for reason[consumer[consumer-05f-3] exits for reason[consumer[consumer-05f-1] exits for reason[consumer[consumer-05f-2] failed to map with error:[RandomFlipImage_545aca: invalid box, x2 should be greater than x1]]]]]]
2020-03-27 14:20:42,627-WARNING: recv endsignal from outq with errmsg[consumer[consumer-05f-5] exits for reason[consumer[consumer-05f-0] exits for reason[consumer[consumer-05f-4] exits for reason[consumer[consumer-05f-3] exits for reason[consumer[consumer-05f-1] exits for reason[consumer[consumer-05f-2] failed to map with error:[RandomFlipImage_545aca: invalid box, x2 should be greater than x1]]]]]]]
2020-03-27 14:20:42,779-WARNING: recv endsignal from outq with errmsg[consumer[consumer-05f-7] exits for reason[consumer[consumer-05f-5] exits for reason[consumer[consumer-05f-0] exits for reason[consumer[consumer-05f-4] exits for reason[consumer[consumer-05f-3] exits for reason[consumer[consumer-05f-1] exits for reason[consumer[consumer-05f-2] failed to map with error:[RandomFlipImage_545aca: invalid box, x2 should be greater than x1]]]]]]]]
2020-03-27 14:20:42,810-WARNING: recv endsignal from outq with errmsg[consumer[consumer-05f-6] exits for reason[consumer[consumer-05f-7] exits for reason[consumer[consumer-05f-5] exits for reason[consumer[consumer-05f-0] exits for reason[consumer[consumer-05f-4] exits for reason[consumer[consumer-05f-3] exits for reason[consumer[consumer-05f-1] exits for reason[consumer[consumer-05f-2] failed to map with error:[RandomFlipImage_545aca: invalid box, x2 should be greater than x1]]]]]]]]]
2020-03-27 14:20:42,810-WARNING: Your reader has raised an exception!
Exception in thread Thread-21:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\reader.py", line 805, in __thread_main__
    six.reraise(*sys.exc_info())
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\reader.py", line 785, in __thread_main__
    for tensors in self._tensor_reader():
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\reader.py", line 853, in __tensor_reader_impl__
    for slots in paddle_reader():
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\data_feeder.py", line 488, in __reader_creator__
    for item in reader():
  File "D:\ai_nvidia\ai_code\Paddle\PaddleDetection-release-0.2\ppdet\data\reader.py", line 417, in _reader
    reader.reset()
  File "D:\ai_nvidia\ai_code\Paddle\PaddleDetection-release-0.2\ppdet\data\parallel_map.py", line 253, in reset
    assert not self._exit, "cannot reset for already stopped dataset"
AssertionError: cannot reset for already stopped dataset

C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\executor.py:782: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "my_train.py", line 323, in <module>
    main()
  File "my_train.py", line 233, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\executor.py", line 783, in run
    six.reraise(*sys.exc_info())
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\executor.py", line 778, in run
    use_program_cache=use_program_cache)
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\executor.py", line 843, in _run_impl
    return_numpy=return_numpy)
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\executor.py", line 677, in _run_parallel
    tensors = exe.run(fetch_var_names)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\reader.py", line 733, in _init_non_iterable
    outputs={'Out': self._feed_list})
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\reader.py", line 646, in __init__
    self._init_non_iterable()
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\reader.py", line 280, in from_generator
    iterable, return_list)
  File "D:\ai_nvidia\ai_code\Paddle\PaddleDetection-release-0.2\ppdet\modeling\architectures\yolov3.py", line 152, in build_inputs
    iterable=iterable) if use_dataloader else None
  File "my_train.py", line 115, in main
    feed_vars, train_loader = model.build_inputs(**inputs_def)
  File "my_train.py", line 323, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (D:\1.7.1\paddle\paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]

**Comment by heavengate** [comment]
`RandomFlipImage_545aca: invalid box, x2 should be greater than x1` 报错信息，请检查一下数据集里面是否有不合法的bbox，或者配置文件里面`RandomFlipImage`里的`is_normalized`是否设置正确

**Comment by Redlyliu** [comment]
RandomFlipImage里的is_normalized设置的是默认的false，对么？这个数据集用keras版的yolov3训练是没问题的，bbox应该是没问题的。

**Comment by heavengate** [comment]
> RandomFlipImage里的is_normalized设置的是默认的false，对么？这个数据集用keras版的yolov3训练是没问题的，bbox应该是没问题的。

麻烦问下你是使用`configs/yolov3_reader.py`里面数据预处理的默认pipline么，有修改预处理设置么

**Comment by heavengate** [comment]
报错报在这一行
https://github.com/PaddlePaddle/PaddleDetection/blob/a3eb2de17b89527f18f69ef33e91da85e16ba0d2/ppdet/data/transform/operators.py#L423
就是翻转图像的时候发现bbox的左上角点的坐标大于右下角点的坐标

**Comment by Redlyliu** [comment]
> > RandomFlipImage里的is_normalized设置的是默认的false，对么？这个数据集用keras版的yolov3训练是没问题的，bbox应该是没问题的。
> 
> 麻烦问下你是使用`configs/yolov3_reader.py`里面数据预处理的默认pipline么，有修改预处理设置么

我用的配置文件是yolov3_r34_voc.yml，只修改了其中的num_classes，另外dataset用的是voc，修改了creat_list.py需要用到的类别名称。
我在想是不是我creat_list不对呢？

**Comment by Redlyliu** [comment]
> 报错报在这一行
> https://github.com/PaddlePaddle/PaddleDetection/blob/a3eb2de17b89527f18f69ef33e91da85e16ba0d2/ppdet/data/transform/operators.py#L423
> 
> 
> 就是翻转图像的时候发现bbox的左上角点的坐标大于右下角点的坐标

好的，那我再仔细检查下数据集，另外想问一下，voc_utils.py里面 def _walk_voc_dir(devkit_dir, year, output_dir)函数中if re.match('[a-z]+_trainval\.txt', fname): ，[a-z]是不是'ImageSets/Main'里面各个类别的.txt文件呢，如person_trainval.txt.

**Comment by heavengate** [comment]
跟`create_list`没有关系，现在报错在bbox invalid，不是list的问题

**Comment by heavengate** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/a3eb2de17b89527f18f69ef33e91da85e16ba0d2/ppdet/data/transform/operators.py#L423
可以在这一行报错的地方把sample的信息打出来，里面会有im_id, im_path等信息，再确认下

**Comment by RedlyL** [comment]
> PaddleDetection/ppdet/data/transform/operators.py
>     
>     
>          Line 423
>       in
>       a3eb2de
>     
>     
>     
>     
> 
>         
>           
>            if gt_bbox.shape[0] != 0 and ( 
>         
>     
>   
> 
> 
> 可以在这一行报错的地方把sample的信息打出来，里面会有im_id, im_path等信息，再确认下

好的，我试试看，谢谢！

**Comment by heavengate** [comment]
麻烦问下问题最后确认了么？

**Comment by Redlyliu** [comment]
> 麻烦问下问题最后确认了么？

按照您给的方法，我查看了报错的im_id和im_path，发现每次报错的图片都不一样，目前还没确定问题，这两天电脑坏了，还没有继续往下查看。

**Comment by heavengate** [comment]
如果你没有修改预处理的pipline的话感觉应该是数据源的问题，报错的im_id可以去查看一下那个im_id对应的annotation，确认下里面的bbox标注是否非法

**Comment by Redlyliu** [comment]
> 如果你没有修改预处理的pipline的话感觉应该是数据源的问题，报错的im_id可以去查看一下那个im_id对应的annotation，确认下里面的bbox标注是否非法

查看了annotation，bbox没有问题的。

**Comment by heavengate** [comment]
确定没有修改`configs/yolov3_reader.yml`里面的数据处理的`sample_transform` `batch_transform`这些么，你的数据集里的格式和VOC是一致的么

**Comment by heavengate** [comment]
麻烦问下你用的Paddle和PaddleDetection是哪个版本，还有报错的那张图的对应的annotation麻烦贴一下，我跑下看看

**Comment by Redlyliu** [comment]
> 麻烦问下你用的Paddle和PaddleDetection是哪个版本，还有报错的那张图的对应的annotation麻烦贴一下，我跑下看看

Paddle1.7.1，PaddleDetection_0.2版
我试了好几次，报错的im_id是不一样的，电脑坏了，只记得链接中的这张图了。


[SF_dataset_000021.zip](https://github.com/PaddlePaddle/PaddleDetection/files/4413883/SF_dataset_000021.zip)

**Comment by Redlyliu** [comment]
> 确定没有修改`configs/yolov3_reader.yml`里面的数据处理的`sample_transform` `batch_transform`这些么，你的数据集里的格式和VOC是一致的么

确定是没有修改的，我只修改了迭代的次数、保存的路径和类别数，数据是按照VOC的格式制作的。

**Comment by AN-ZE** [comment]
是相同问题，不过已经找到原因，是xml中的size为0造成的。以前没在意，以为会重新读取图片的size。

**Comment by qingqing01** [comment]
感谢大家反馈，如果有问题，可以开新的issue
