### ISSUE TITLE
yolov3 serving部署出错

### ISSUE THREAD

**Issue by huilin16** [PaddlePaddle/PaddleDetection#4081]
在运行服务器端部署案例 PaddleDetection/deploy/serving/ ， 运行test_client.py时，报错不存在PredictorRes：

```
Traceback (most recent call last):
  File "../../deploy/serving/test_client.py", line 27, in <module>
    client = Client()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle_serving_client/client.py", line 146, in __init__
    from .serving_client import PredictorRes
ImportError: libcrypto.so.10: cannot open shared object file: No such file or directory
```

**Comment by qingqing01** [comment]
参考 https://github.com/PaddlePaddle/PaddleOCR/issues/1994 ， 可以更新下PaddleServing版本。

**Comment by huilin16** [comment]
您好，我的环境：
paddlepaddle-gpu==2.1.2
paddle-serving-app==0.6.3
paddle-serving-client==0.6.3
paddle-serving-server==0.6.3

请问应该更新到哪一个版本呢？

![image](https://user-images.githubusercontent.com/36887207/131291028-c9f64518-0e76-4a24-a0b0-a9abaf5a11f2.png)

**Comment by bjjwwang** [comment]
应该是用的镜像不对，libssl版本不对 可以这样 
```
wget https://paddle-serving.bj.bcebos.com/others/centos_ssl.tar && \
    tar xf centos_ssl.tar && rm -rf centos_ssl.tar && \
    mv libcrypto.so.1.0.2k /usr/lib/libcrypto.so.1.0.2k && mv libssl.so.1.0.2k /usr/lib/libssl.so.1.0.2k && \
    ln -sf /usr/lib/libcrypto.so.1.0.2k /usr/lib/libcrypto.so.10 && \
    ln -sf /usr/lib/libssl.so.1.0.2k /usr/lib/libssl.so.10 && \
    ln -sf /usr/lib/libcrypto.so.10 /usr/lib/libcrypto.so && \
    ln -sf /usr/lib/libssl.so.10 /usr/lib/libssl.so
```
