### ISSUE TITLE
BBoxLibraAssigner问题：

### ISSUE THREAD

**Issue by jackie8310** [PaddlePaddle/PaddleDetection#4092]
用CascadeRCNN结构，其中采用BBoxLibraAssigner，配置如下：
BBoxLibraAssigner:
  batch_size_per_im: 512
  bg_thresh: 0.5
  fg_thresh: 0.5
  fg_fraction: 0.25
  cascade_iou: [0.5, 0.6, 0.7]
  use_random: True
训练时报错：
Traceback (most recent call last):
  File "/home/aistudio/PaddleDetection-release-2.2/tools/train.py", line 138, in <module>
    main()
  File "/home/aistudio/PaddleDetection-release-2.2/tools/train.py", line 134, in main
    run(FLAGS, cfg)
  File "/home/aistudio/PaddleDetection-release-2.2/tools/train.py", line 109, in run
    trainer.train(FLAGS.eval)
  File "/home/aistudio/PaddleDetection-release-2.2/ppdet/engine/trainer.py", line 358, in train
    outputs = model(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleDetection-release-2.2/ppdet/modeling/architectures/meta_arch.py", line 26, in forward
    out = self.get_loss()
  File "/home/aistudio/PaddleDetection-release-2.2/ppdet/modeling/architectures/cascade_rcnn.py", line 125, in get_loss
    rpn_loss, bbox_loss, mask_loss = self._forward()
  File "/home/aistudio/PaddleDetection-release-2.2/ppdet/modeling/architectures/cascade_rcnn.py", line 94, in _forward
    self.inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleDetection-release-2.2/ppdet/modeling/heads/cascade_head.py", line 222, in forward
    rois, rois_num, inputs, i, is_cascade=True)
  File "/home/aistudio/PaddleDetection-release-2.2/ppdet/modeling/proposal_generator/target_layer.py", line 223, in __call__
    self.use_random, is_cascade, self.cascade_iou[stage], self.num_bins)
  File "/home/aistudio/PaddleDetection-release-2.2/ppdet/modeling/proposal_generator/target.py", line 627, in libra_generate_proposal_target
    max_overlap = max_overlaps[i] if is_cascade_rcnn else None
TypeError: 'float' object is not subscriptable
请教哪里问题呢？是不是只能在fasterRCNN中用Libra-sampling?

**Comment by jerrywgz** [comment]
目前还只支持了faster rcnn的libra sample, 基于cascade的需要调整下
