### ISSUE TITLE
不加载预训练参数，训练模型，eval时报错

### ISSUE THREAD

**Issue by rock4you** [PaddlePaddle/PaddleDetection#4112]
不加载预训练参数，训练模型，eval时报错：

loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2021-09-03 10:42:48,428-WARNING: The number of valid mask detected is zero.
             Please use reasonable model and check input data.
Traceback (most recent call last):
  File "tools/train_multi_machine.py", line 384, in <module>
    main()
  File "tools/train_multi_machine.py", line 312, in main
    if box_ap_stats[0] > best_box_ap_list[0]:
TypeError: 'NoneType' object is not subscriptable
terminate called without an active exception

请问应该怎么解决？

**Comment by lyuwenyu** [comment]
什么模型  建议把eval间隔的变大

**Comment by rock4you** [comment]
solov2
