### ISSUE TITLE
学习率以及策略问题

### ISSUE THREAD

**Issue by Kaitosama7** [PaddlePaddle/PaddleDetection#4116]
您好，请问我应该如何修改Optimizer中的配置，例如我想固定学习率为0.0001，还有就是OptimizerBuilder是什么设置呢，谢谢！

**Comment by ghostxsl** [comment]
如果你只想用固定学习率，建议你把PiecewiseDecay.milestones改成和总epoch一致，同时设置use_warmup=False，例如：

```epoch: 24

LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [24]
    use_warmup: False
```

以上是一个固定学习率的例子，OptimizerBuilder的实现请参考：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/ppdet/optimizer.py#L209

**Comment by Kaitosama7** [comment]
谢谢，那我需要使用余弦退火的话应该是怎么样的呢？我在Optimizer.py只找到了CosineDecay这个方法

**Comment by ghostxsl** [comment]
CosineDecay就是余弦退火

**Comment by Kaitosama7** [comment]
epoch: 50
LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [50]
    use_warmup: False

报错Traceback (most recent call last):
  File "tools/train.py", line 142, in <module>
    main()
  File "tools/train.py", line 138, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 104, in run
    trainer = Trainer(cfg, mode='train')
  File "/home/aistudio/PaddleDetection/ppdet/engine/trainer.py", line 87, in __init__
    self.lr = create('LearningRate')(steps_per_epoch)
  File "/home/aistudio/PaddleDetection/ppdet/optimizer.py", line 173, in __call__
    step_per_epoch=step_per_epoch)
  File "/home/aistudio/PaddleDetection/ppdet/optimizer.py", line 120, in __call__
    return optimizer.lr.PiecewiseDecay(boundary, value)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/lr.py", line 369, in __init__
    last_epoch=last_epoch, verbose=verbose)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/lr.py", line 90, in __init__
    self.step()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/lr.py", line 113, in step
    self.last_lr = self.get_lr()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/lr.py", line 374, in get_lr
    return self.values[i]
TypeError: 'NoneType' object is not subscriptable

**Comment by ghostxsl** [comment]
你是不是改动代码了？我这边试了是可以跑通的
