### ISSUE TITLE
安装后 test_architectures报错

### ISSUE THREAD

**Issue by xiaomujiang** [PaddlePaddle/PaddleDetection#416]
普通用户在执行下面一行的时候报错。这是要什么权限？ paddle版本1.7.1
(paddle) [zhangshilin@JHL-q PaddleDetection]$ python ppdet/modeling/tests/test_architectures.py
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 22, in <module>
    import paddle.fluid as fluid
  File "/home/zhangshilin/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/__init__.py", line 30, in <module>
    import paddle.dataset
  File "/home/zhangshilin/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/dataset/__init__.py", line 28, in <module>
    import paddle.dataset.mq2007
  File "/home/zhangshilin/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/dataset/mq2007.py", line 30, in <module>
    import rarfile
  File "/home/zhangshilin/anaconda3/envs/paddle/lib/python3.7/site-packages/rarfile.py", line 2950, in <module>
    _check_unrar_tool()
  File "/home/zhangshilin/anaconda3/envs/paddle/lib/python3.7/site-packages/rarfile.py", line 2931, in _check_unrar_tool
    custom_check([ORIG_UNRAR_TOOL], True)
  File "/home/zhangshilin/anaconda3/envs/paddle/lib/python3.7/site-packages/rarfile.py", line 2823, in custom_check
    p = custom_popen(cmd)
  File "/home/zhangshilin/anaconda3/envs/paddle/lib/python3.7/site-packages/rarfile.py", line 2813, in custom_popen
    creationflags=creationflags)
  File "/home/zhangshilin/anaconda3/envs/paddle/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/zhangshilin/anaconda3/envs/paddle/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'unrar'

**Comment by qingqing01** [comment]
```
File "/home/zhangshilin/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/init.py", line 30, in
import paddle.dataset
File "/home/zhangshilin/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/dataset/init.py", line 28, in
import paddle.dataset.mq2007
File "/home/zhangshilin/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/dataset/mq2007.py", line 30, in
import rarfile
F
```

@xiaomujiang 看错误是`rarfile`引起，这个是paddle框架的导入引起的。 你可以在

`/home/zhangshilin/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/dataset/init.py", line 28 `

这行注释掉 `import paddle.dataset.mq2007`。

或者将

/home/zhangshilin/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/dataset/mq2007.py

中 `import rarfile` 移动到 44行之前。

**Comment by qingqing01** [comment]
@xiaomujiang 请问上述方案能否解决？如何可以的话，我们在Paddle框架上也做下升级。

**Comment by xiaomujiang** [comment]
hi
&nbsp; &nbsp; 我采用了把import放到了44前面，然后问题解决了

---原始邮件---
发件人: "qingqing01"<notifications@github.com&gt;
发送时间: 2020年3月31日(周二) 下午5:23
收件人: "PaddlePaddle/PaddleDetection"<PaddleDetection@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"mujiang"<962296332@qq.com&gt;;
主题: Re: [PaddlePaddle/PaddleDetection] 安装后 test_architectures报错 (#416)




 
@xiaomujiang 请问上述方案能否解决？如何可以的话，我们在Paddle框架上也做下升级。
