### ISSUE TITLE
keypoint模型导出报错

### ISSUE THREAD

**Issue by sinoboy168** [PaddlePaddle/PaddleDetection#4162]
我在使用/tools/export_model.py导出BottomUp类的keypoin预训练模型时报错，似乎要加载COCO数据库？我只是想看看infer的结果，所以，没有下载数据，也没有训练。按逻辑说应该预测也是不需要下载训练数据的吧？而我试了另外的 Top-Down模型就可以直接导出。

```
loading annotations into memory...
Error when construct KeypointBottomUpCocoDataset instance from yaml config
Traceback (most recent call last):
  File "/kaggle/input/paddledect/tools/export_model.py", line 113, in <module>
    main()
  File "/kaggle/input/paddledect/tools/export_model.py", line 96, in main
    cfg = load_config(FLAGS.config)
  File "/kaggle/input/paddledect/ppdet/core/workspace.py", line 114, in load_config
    cfg = _load_config_with_base(file_path)
  File "/kaggle/input/paddledect/ppdet/core/workspace.py", line 79, in _load_config_with_base
    file_cfg = yaml.load(f, Loader=yaml.Loader)
  File "/opt/conda/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/opt/conda/lib/python3.7/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/opt/conda/lib/python3.7/site-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/opt/conda/lib/python3.7/site-packages/yaml/constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/opt/conda/lib/python3.7/site-packages/yaml/constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/opt/conda/lib/python3.7/site-packages/yaml/constructor.py", line 143, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/opt/conda/lib/python3.7/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/kaggle/input/paddledect/ppdet/core/config/yaml_helpers.py", line 45, in python_constructor
    raise ex
  File "/kaggle/input/paddledect/ppdet/core/config/yaml_helpers.py", line 41, in python_constructor
    return cls(**kwargs)
  File "/kaggle/input/paddledect/ppdet/data/source/keypoint_coco.py", line 140, in __init__
    self.coco = COCO(ann_file)
  File "/opt/conda/lib/python3.7/site-packages/pycocotools/coco.py", line 84, in __init__
    with open(annotation_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/coco/annotations/person_keypoints_train2017.json'
```

**Comment by zhiboniu** [comment]
这个问题前段时间刚修复过，请跟repo develop分支同步一下应该就可以了
