### ISSUE TITLE
yolov3_r34 使用联合策略压缩后导出模型报错

### ISSUE THREAD

**Issue by usuixingyili** [PaddlePaddle/PaddleDetection#4173]
[09/13 10:00:35] ppdet.utils.checkpoint INFO: Finish loading model weights: workspace/electric_assembly/output/extensions_782/paddle_model/yolov
3_r34_coco_distill_prune/best_model.pdparams
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[09/13 10:00:35] ppdet.engine INFO: Export inference config file to output_inference\yolov3_r34_coco_distill_prune\infer_cfg.yml
Traceback (most recent call last):
  File "tools\export_model.py", line 105, in <module>
    main()
  File "tools\export_model.py", line 101, in main
    run(FLAGS, cfg)
  File "tools\export_model.py", line 69, in run
    trainer.export(FLAGS.output_dir)
  File "D:\softwares\Anaconda3\envs\ppdet\lib\site-packages\ppdet\engine\trainer.py", line 501, in export
    if 'slim' not in self.cfg or self.cfg['slim_type'] != 'QAT':
KeyError: 'slim_type'

**Comment by ghostxsl** [comment]
请提供一下你的运行命令及运行环境

你如果要导出压缩后的模型，请在命令中加入 `--slim_config` 指定slim的config文件

**Comment by usuixingyili** [comment]
> 请提供一下你的运行命令及运行环境
> 
> 你如果要导出压缩后的模型，请在命令中加入 `--slim_config` 指定slim的config文件

裁剪模型导出没问题，联合策略导出报错，PaddlePaddle 2.1.2 ppdet 2.1.0
python tools\export_model.py -c configs/yolov3/yolov3_r34_270e_coco.yml --slim_config configs/slim/extensions/yolov3_r34_coco_distill_prune.yml -o weights=output/extensions_782/paddle_model/yolov3_r34_coco_distill_prune/best_model.pdparams

**Comment by ghostxsl** [comment]
请参考：https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/slim/extensions/yolov3_mobilenet_v1_coco_distill_prune.yml
检查一下你的yolov3_r34_coco_distill_prune.yml配置文件是否写的有问题
