### ISSUE TITLE
FairMot模型导出后，能否对单张图片进行预测？

### ISSUE THREAD

**Issue by rock4you** [PaddlePaddle/PaddleDetection#4189]
文档中提到：“注意: 跟踪模型是对视频进行预测，不支持单张图的预测”
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/configs/mot/README_cn.md

目前模型导出后，能否支持对单张图片的预测？
能否保存预测结果为文本格式？

**Comment by nemonameless** [comment]
单张图的预测是只输出检测结果吗？测速度的时候单张图片形式也可以，但单张图片做跟踪没有意义。
导出后在deploy下infer也支持视频和图片文件夹两种形式，都可以保存预测结果为txt文本格式的，如文档所示加 --save_mot_txts

**Comment by rock4you** [comment]
需要导入视频流，预测后将结果实时推出去显示为视频，目前计划是对单张图片进行预测。

**Comment by rock4you** [comment]
> 单张图的预测是只输出检测结果吗？测速度的时候单张图片形式也可以，但单张图片做跟踪没有意义。
> 导出后在deploy下infer也支持视频和图片文件夹两种形式，都可以保存预测结果为txt文本格式的，如文档所示加 --save_mot_txts

能否麻烦您提供一个预测命令的示例？我这边对单张图片infer后找不到输出的txt

**Comment by nemonameless** [comment]
对单张图infer是需要做什么用呢，对于跟踪来说没有意义啊，只纯检测吗？
```
CUDA_VISIBLE_DEVICES=0 python3.7 deploy/python/mot_jde_infer.py --model_dir=output_inference/fairmot_dla34_30e_1088x608 --image_file=demo/000000014439.jpg --device=GPU 
```
你是想每一帧的结果都输出来打印出来 而不是最后打印在整个txt里吗？

**Comment by nemonameless** [comment]
现在还不支持单张图写结果txt。
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/deploy/python/mot_jde_infer.py#L263    把这个if 移动到240行下，write_mot_results(result_filename, results[-1]) 应该就可以了。待提PR更新。

**Comment by rock4you** [comment]
> 现在还不支持单张图写结果txt。
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/deploy/python/mot_jde_infer.py#L263 把这个if 移动到240行下，write_mot_results(result_filename, results[-1]) 应该就可以了。待提PR更新。

原始代码:

240：results.append((frame_id + 1, online_tlwhs, online_scores, online_ids))
241：fps = 1. / timer.average_time
...
263: if FLAGS.save_mot_txts:
264: result_filename = os.path.join(FLAGS.output_dir,
265:                                video_name.split('.')[-2] + '.txt')


修改后是下面这样吗？

240: results.append((frame_id + 1, online_tlwhs, online_scores, online_ids))
241: if FLAGS.save_mot_txts:
242:        write_mot_results(result_filename, results[-1]) 
243: fps = 1. / timer.average_time
...


那如果想做实时的视频跟踪，推流进行预测，再把预测结果推流，PaddleDetection目前有没有可用的方案呢？

**Comment by rock4you** [comment]
240：results.append((frame_id + 1, online_tlwhs, online_scores, online_ids))
241：fps = 1. / timer.average_time

**Comment by YixinKristy** [comment]
您好，请问您的具体应用场景是？

**Comment by rock4you** [comment]
> 您好，请问您的具体应用场景是？

视频流，进行实时目标跟踪，将预测结果以视频流输出

**Comment by YixinKristy** [comment]
您好,我是PaddleDetection的产品经理，请问是否方便加一下您的微信，具体了解一下~

**Comment by rock4you** [comment]
> 您好,我是PaddleDetection的产品经理，请问是否方便加一下您的微信，具体了解一下~

可以，我加你，你的微信号是什么

**Comment by rock4you** [comment]
构造自己的数据（有些帧没有目标），训练FairMot模型，报错如下所示，
请问可能是什么原因？

------------------------------------------------
launch train in GPU mode!
launch proc_id:17948 idx:0
launch proc_id:17951 idx:1
launch proc_id:17954 idx:2
launch proc_id:17957 idx:3
/usr/local/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
W0917 20:47:01.000313 17948 gen_comm_id_helper.cc:120] connect addr=127.0.0.1:60012 failed 1 times with reason: Connection refused retry after 0.5 seconds
I0917 20:47:01.500905 17948 nccl_context.cc:74] init nccl context nranks: 4 local rank: 0 gpu id: 0 ring id: 0
W0917 20:47:02.135898 17948 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.2, Runtime API Version: 10.1
W0917 20:47:02.140527 17948 device_context.cc:422] device: 0, cuDNN Version: 7.6.
[09/17 20:47:05] ppdet.data.source.mot INFO: ================================================================================
[09/17 20:47:05] ppdet.data.source.mot INFO: MOT dataset summary: 
[09/17 20:47:05] ppdet.data.source.mot INFO: OrderedDict([('mydata.train', 263)])
[09/17 20:47:05] ppdet.data.source.mot INFO: total images: 1639
[09/17 20:47:05] ppdet.data.source.mot INFO: image start index: OrderedDict([('mydata.train', 0)])
[09/17 20:47:05] ppdet.data.source.mot INFO: total identities: 264
[09/17 20:47:05] ppdet.data.source.mot INFO: identity start index: OrderedDict([('mydata.train', 0)])
[09/17 20:47:05] ppdet.data.source.mot INFO: ================================================================================
[09/17 20:47:06] reader WARNING: fail to map sample transform [RandomFlip_f7f897] with error: 'NoneType' object is not subscriptable and stack:
Traceback (most recent call last):
  File "/root/paddlejob/workspace/env_run/4-p40/paddleDet-2.1/ppdet/data/reader.py", line 55, in __call__
    data = f(data)
  File "/root/paddlejob/workspace/env_run/4-p40/paddleDet-2.1/ppdet/data/transform/operators.py", line 100, in __call__
    sample = self.apply(sample, context)
  File "/root/paddlejob/workspace/env_run/4-p40/paddleDet-2.1/ppdet/data/transform/operators.py", line 565, in apply
    im = sample['image']
TypeError: 'NoneType' object is not subscriptable

ERROR:root:DataLoader reader thread raised an exception!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 391, in _thread_loop
    batch = self._get_data()
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 505, in _get_data
    batch.reraise()
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 168, in reraise
    raise self.exc_type(msg)
TypeError: DataLoader worker(2) caught TypeError with message:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 320, in _worker_loop
    batch = fetcher.fetch(indices)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 106, in fetch
    data = [self.dataset[idx] for idx in batch_indices]
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 106, in <listcomp>
    data = [self.dataset[idx] for idx in batch_indices]
  File "/root/paddlejob/workspace/env_run/4-p40/paddleDet-2.1/ppdet/data/source/dataset.py", line 87, in __getitem__
    return self.transform(roidb)
  File "/root/paddlejob/workspace/env_run/4-p40/paddleDet-2.1/ppdet/data/reader.py", line 61, in __call__
    raise e
  File "/root/paddlejob/workspace/env_run/4-p40/paddleDet-2.1/ppdet/data/reader.py", line 55, in __call__
    data = f(data)
  File "/root/paddlejob/workspace/env_run/4-p40/paddleDet-2.1/ppdet/data/transform/operators.py", line 100, in __call__
    sample = self.apply(sample, context)
  File "/root/paddlejob/workspace/env_run/4-p40/paddleDet-2.1/ppdet/data/transform/operators.py", line 565, in apply
    im = sample['image']
TypeError: 'NoneType' object is not subscriptable


[09/17 20:47:06] reader WARNING: fail to map sample transform [RandomFlip_f7f897] with error: 'NoneType' object is not subscriptable and stack:
Traceback (most recent call last):
  File "/root/paddlejob/workspace/env_run/4-p40/paddleDet-2.1/ppdet/data/reader.py", line 55, in __call__
    data = f(data)
  File "/root/paddlejob/workspace/env_run/4-p40/paddleDet-2.1/ppdet/data/transform/operators.py", line 100, in __call__
    sample = self.apply(sample, context)
  File "/root/paddlejob/workspace/env_run/4-p40/paddleDet-2.1/ppdet/data/transform/operators.py", line 565, in apply
    im = sample['image']
TypeError: 'NoneType' object is not subscriptable

[09/17 20:47:06] reader WARNING: fail to map sample transform [RandomFlip_f7f897] with error: 'NoneType' object is not subscriptable and stack:
Traceback (most recent call last):
  File "/root/paddlejob/workspace/env_run/4-p40/paddleDet-2.1/ppdet/data/reader.py", line 55, in __call__
    data = f(data)
  File "/root/paddlejob/workspace/env_run/4-p40/paddleDet-2.1/ppdet/data/transform/operators.py", line 100, in __call__
    sample = self.apply(sample, context)
  File "/root/paddlejob/workspace/env_run/4-p40/paddleDet-2.1/ppdet/data/transform/operators.py", line 565, in apply
    im = sample['image']
TypeError: 'NoneType' object is not subscriptable

[09/17 20:47:06] reader WARNING: fail to map sample transform [BboxXYXY2XYWH_7948ae] with error: argument of type 'NoneType' is not iterable and stack:
Traceback (most recent call last):
  File "/root/paddlejob/workspace/env_run/4-p40/paddleDet-2.1/ppdet/data/reader.py", line 55, in __call__
    data = f(data)
  File "/root/paddlejob/workspace/env_run/4-p40/paddleDet-2.1/ppdet/data/transform/operators.py", line 100, in __call__
    sample = self.apply(sample, context)
  File "/root/paddlejob/workspace/env_run/4-p40/paddleDet-2.1/ppdet/data/transform/operators.py", line 1692, in apply
    assert 'gt_bbox' in sample
TypeError: argument of type 'NoneType' is not iterable

[09/17 20:47:07] reader WARNING: fail to map sample transform [RandomFlip_f7f897] with error: 'NoneType' object is not subscriptable and stack:
Traceback (most recent call last):
  File "/root/paddlejob/workspace/env_run/4-p40/paddleDet-2.1/ppdet/data/reader.py", line 55, in __call__
    data = f(data)
  File "/root/paddlejob/workspace/env_run/4-p40/paddleDet-2.1/ppdet/data/transform/operators.py", line 100, in __call__
    sample = self.apply(sample, context)
  File "/root/paddlejob/workspace/env_run/4-p40/paddleDet-2.1/ppdet/data/transform/operators.py", line 565, in apply
    im = sample['image']
TypeError: 'NoneType' object is not subscriptable

[09/17 20:47:08] ppdet.utils.checkpoint INFO: reid.classifier.weight not used, shape [128, 14455] unmatched with [128, 264] in model.
[09/17 20:47:08] ppdet.utils.checkpoint INFO: reid.classifier.bias not used, shape [14455] unmatched with [264] in model.
[09/17 20:47:08] ppdet.utils.checkpoint INFO: Finish loading model weights: /root/.cache/paddle/weights/fairmot_dla34_crowdhuman_pretrained.pdparams
Traceback (most recent call last):
  File "tools/train.py", line 139, in <module>
    main()
  File "tools/train.py", line 135, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 110, in run
    trainer.train(FLAGS.eval)
  File "/root/paddlejob/workspace/env_run/4-p40/paddleDet-2.1/ppdet/engine/trainer.py", line 288, in train
    for step_id, data in enumerate(self.loader):
  File "/root/paddlejob/workspace/env_run/4-p40/paddleDet-2.1/ppdet/data/reader.py", line 210, in __next__
INFO 2021-09-17 20:47:17,394 launch_utils.py:327] terminate all the procs
ERROR 2021-09-17 20:47:17,394 launch_utils.py:584] ABORT!!! Out of all 4 trainers, the trainer process with rank=[0, 1, 2, 3] was aborted. Please check its log.

-----------------------------------------------------------------------------------------

构造自己的数据（有些帧没有目标），训练FairMot模型，报错如上所示，
请问可能是什么原因？

**Comment by YixinKristy** [comment]
> > 您好,我是PaddleDetection的产品经理，请问是否方便加一下您的微信，具体了解一下~
> 
> 可以，我加你，你的微信号是什么

18108656919 还麻烦您加一下，感谢~~
