### ISSUE TITLE
导出模型出错

### ISSUE THREAD

**Issue by jacbson** [PaddlePaddle/PaddleDetection#4214]
python tools/export_model.py -c static/configs/rcnn_enhance/generic/cascade_rcnn_dcn_r101_vd_fpn_gen_server_side.yml --export_serving_model=True --output_dir=./inference_model -o weights=cascade_rcnn_dcn_r101_vd_fpn_gen_server_side.pdparams

出错信息：

```
Traceback (most recent call last):
  File "tools/export_model.py", line 113, in <module>
    main()
  File "tools/export_model.py", line 96, in main
    cfg = load_config(FLAGS.config)
  File "C:\Users\jacbs\PaddleDetection\ppdet\core\workspace.py", line 114, in load_config
    cfg = _load_config_with_base(file_path)
  File "C:\Users\jacbs\PaddleDetection\ppdet\core\workspace.py", line 79, in _load_config_with_base
    file_cfg = yaml.load(f, Loader=yaml.Loader)
  File "C:\Users\jacbs\Anaconda3\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Users\jacbs\Anaconda3\lib\site-packages\yaml\constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "C:\Users\jacbs\Anaconda3\lib\site-packages\yaml\constructor.py", line 52, in construct_document
    for dummy in generator:
  File "C:\Users\jacbs\Anaconda3\lib\site-packages\yaml\constructor.py", line 400, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "C:\Users\jacbs\Anaconda3\lib\site-packages\yaml\constructor.py", line 122, in construct_sequence
    for child in node.value]
  File "C:\Users\jacbs\Anaconda3\lib\site-packages\yaml\constructor.py", line 122, in <listcomp>
    for child in node.value]
  File "C:\Users\jacbs\Anaconda3\lib\site-packages\yaml\constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "C:\Users\jacbs\Anaconda3\lib\site-packages\yaml\constructor.py", line 421, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!DecodeImage'
  in "static/configs/rcnn_enhance/generic/cascade_rcnn_dcn_r101_vd_fpn_gen_server_side.yml", line 122, column 5

(base) C:\Users\jacbs\PaddleDetection>python tools/export_model.py -c static/configs/rcnn_enhance/generic/cascade_rcnn_dcn_r101_vd_fpn_gen_server_side.yml --export_serving_model=True --output_dir=./inference_model -o weights=cascade_rcnn_dcn_r101_vd_fpn_gen_server_side.pdparams
Traceback (most recent call last):
  File "tools/export_model.py", line 113, in <module>
    main()
  File "tools/export_model.py", line 96, in main
    cfg = load_config(FLAGS.config)
  File "C:\Users\jacbs\PaddleDetection\ppdet\core\workspace.py", line 114, in load_config
    cfg = _load_config_with_base(file_path)
  File "C:\Users\jacbs\PaddleDetection\ppdet\core\workspace.py", line 79, in _load_config_with_base
    file_cfg = yaml.load(f, Loader=yaml.Loader)
  File "C:\Users\jacbs\Anaconda3\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Users\jacbs\Anaconda3\lib\site-packages\yaml\constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "C:\Users\jacbs\Anaconda3\lib\site-packages\yaml\constructor.py", line 52, in construct_document
    for dummy in generator:
  File "C:\Users\jacbs\Anaconda3\lib\site-packages\yaml\constructor.py", line 400, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "C:\Users\jacbs\Anaconda3\lib\site-packages\yaml\constructor.py", line 122, in construct_sequence
    for child in node.value]
  File "C:\Users\jacbs\Anaconda3\lib\site-packages\yaml\constructor.py", line 122, in <listcomp>
    for child in node.value]
  File "C:\Users\jacbs\Anaconda3\lib\site-packages\yaml\constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "C:\Users\jacbs\Anaconda3\lib\site-packages\yaml\constructor.py", line 421, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!DecodeImage'
  in "static/configs/rcnn_enhance/generic/cascade_rcnn_dcn_r101_vd_fpn_gen_server_side.yml", line 122, column 5
```

**Comment by qingqing01** [comment]
`static/configs/rcnn_enhance/generic/cascade_rcnn_dcn_r101_vd_fpn_gen_server_side.yml`  是静态图，您需要cd到static文件里，使用静态图的代码导模型、部署。  动态图、静态图是2套代码。如果默认pip安装了动态图的paddledet，使用静态图如果未能优先使用static文件夹下的源码，注意卸载动态图。

**Comment by jacbson** [comment]
谢谢
