### ISSUE TITLE
[Other General Issues] sparse_rcnn导出报错

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleDetection#4234]
其他的没有报错
就是这个sparse_rcnn_r50_fpn_3x_pro300模型报错了

导出模型的时候 报错
```

[09/24 23:00:33] ppdet.utils.checkpoint INFO: Finish loading model weights: output/sparse_rcnn_r50_fpn_3x_pro300_voc/34.pdparams
[09/24 23:00:33] ppdet.engine INFO: Export inference config file to ./inference_model\sparse_rcnn_r50_fpn_3x_pro300_voc\infer_cfg.yml
E:\anaconda3\envs\paddlepaddle\lib\site-packages\paddle\fluid\layers\utils.py:77: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  return (isinstance(seq, collections.Sequence) and
Traceback (most recent call last):
  File "tools/export_model.py", line 113, in <module>
    main()
  File "tools/export_model.py", line 109, in main
    run(FLAGS, cfg)
  File "tools/export_model.py", line 77, in run
    trainer.export(FLAGS.output_dir)
  File "F:\PaddleDetection\ppdet\engine\trainer.py", line 573, in export
    input_spec, static_model.forward.main_program,
  File "E:\anaconda3\envs\paddlepaddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 537, in main_program
    concrete_program = self.concrete_program
  File "E:\anaconda3\envs\paddlepaddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 453, in concrete_program
    return self.concrete_program_specify_input_spec(input_spec=None)
  File "E:\anaconda3\envs\paddlepaddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 490, in concrete_program_specify_input_spec
    concrete_program, _ = self.get_concrete_program(
  File "E:\anaconda3\envs\paddlepaddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 401, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "E:\anaconda3\envs\paddlepaddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 714, in __getitem__
    self._caches[item] = self._build_once(item)
  File "E:\anaconda3\envs\paddlepaddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 701, in _build_once
    concrete_program = ConcreteProgram.from_func_spec(
  File "E:\anaconda3\envs\paddlepaddle\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "E:\anaconda3\envs\paddlepaddle\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "E:\anaconda3\envs\paddlepaddle\lib\site-packages\paddle\fluid\dygraph\base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "E:\anaconda3\envs\paddlepaddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 661, in from_func_spec
    error_data.raise_new_exception()
  File "E:\anaconda3\envs\paddlepaddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\error.py", line 192, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
KeyError: 'In transformed code:\n\n    File "C:\\Users\\mm\\AppData\\Local\\Temp\\tmpom4z4zwy.py", line 28, in forward\n\tout = paddle.jit.dy2static.convert_ifelse(self.training, true_fn_1,\n    File "E:\\anaconda3\\envs\\paddlepaddle\\lib\\site-packages\\paddle\\fluid\\dygraph\\dygraph_to_static\\convert_operators.py", line 210, in convert_ifelse\n\treturn _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)\n    File "E:\\anaconda3\\envs\\paddlepaddle\\lib\\site-packages\\paddle\\fluid\\dygraph\\dygraph_to_static\\convert_operators.py", line 235, in _run_py_ifelse\n\treturn true_fn(*true_args) if pred else false_fn(*false_args)\n    File "F:\\PaddleDetection\\ppdet\\modeling\\architectures\\meta_arch.py", line 28, in forward (* user code *)\n\tout = self.get_pred()\n    File "F:\\PaddleDetection\\ppdet\\modeling\\architectures\\sparse_rcnn.py", line 97, in get_pred (* user code *)\n\tbbox_pred, bbox_num = self._forward()\n    File "F:\\PaddleDetection\\ppdet\\modeling\\architectures\\sparse_rcnn.py", line 60, in _forward (* user code *)\n\thead_outs = self.head(fpn_feats, self.inputs["img_whwh"])\n    KeyError: \'img_whwh\'\n'

```

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?
 python tools/export_model.py -c configs/sparse_rcnn/sparse_rcnn_r50_fpn_3x_pro300_voc.yml --output_dir=./inference_model  -o weights=output/sparse_rcnn_r50_fpn_3x_pro300_voc/34

3. 您使用的数据集是？/What dataset did you use?
VOC

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
paddledet                         2.2.0
paddlepaddle-gpu                  2.1.3.post112

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：
Win11

4. 请问您使用的Python版本是？/ Please provide the version of Python you used.
Python 3.8.11

5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.
CUDA11.2  

如果您的issue是关于安装或环境，您可以先查询[安装文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)尝试解决~

**Comment by yghstill** [comment]
@monkeycc sparse_rcnn目前不支持导出预测部署，这个我们将跟进下。
