### ISSUE TITLE
保存静态图模型

### ISSUE THREAD

**Issue by yubinyes** [PaddlePaddle/PaddleDetection#4263]
ppyolotiny模型，训练和推理都正常，保存模型时一直提示错误，不知道是什么问题。
input_spec1 = InputSpec(shape = [None, 3, 160, 320], dtype='float32', name="image")
paddle.jit.save(net, "model/model", [input_spec1])

错误提示：
W0930 22:13:14.814828 1789658 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.4, Runtime API Version: 10.2
W0930 22:13:14.817953 1789658 device_context.cc:422] device: 0, cuDNN Version: 7.6.
/home/moumou/.local/lib/python3.8/site-packages/paddle/fluid/layers/utils.py:77: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  return (isinstance(seq, collections.Sequence) and
Traceback (most recent call last):
  File "/media/moumou/predict_images.py", line 130, in <module>
    paddle.jit.save(net, "model/model", [input_spec1])
  File "/home/moumou/.local/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/moumou/.local/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/moumou/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/home/moumou/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/jit.py", line 736, in save
    concrete_program = static_forward.concrete_program
  File "/home/moumou/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 453, in concrete_program
    return self.concrete_program_specify_input_spec(input_spec=None)
  File "/home/moumou/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 490, in concrete_program_specify_input_spec
    concrete_program, _ = self.get_concrete_program(
  File "/home/moumou/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 401, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/home/moumou/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 714, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/home/moumou/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 701, in _build_once
    concrete_program = ConcreteProgram.from_func_spec(
  File "/home/moumou/.local/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/moumou/.local/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/moumou/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/home/moumou/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 623, in from_func_spec
    static_func = convert_to_static(dygraph_function)
  File "/home/moumou/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 140, in convert_to_static
    static_func = _FUNCTION_CACHE.convert_with_cache(function)
  File "/home/moumou/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 77, in convert_with_cache
    static_func = self._convert(func)
  File "/home/moumou/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 115, in _convert
    root_wrapper = self._dygraph_to_static.get_static_ast(root)
  File "/home/moumou/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/ast_transformer.py", line 61, in get_static_ast
    self.transfer_from_node_type(self.static_analysis_root)
  File "/home/moumou/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/ast_transformer.py", line 92, in transfer_from_node_type
    self._apply(transformer, node_wrapper, log_level=index + 1)
  File "/home/moumou/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/ast_transformer.py", line 65, in _apply
    transformer(node_wrapper).transform()
  File "/home/moumou/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/tensor_shape_transformer.py", line 118, in transform
    self.visit(self.root)
  File "/home/moumou/miniconda3/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/home/moumou/miniconda3/lib/python3.8/ast.py", line 439, in generic_visit
    value = self.visit(value)
  File "/home/moumou/miniconda3/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/home/moumou/miniconda3/lib/python3.8/ast.py", line 439, in generic_visit
    value = self.visit(value)
  File "/home/moumou/miniconda3/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/home/moumou/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/tensor_shape_transformer.py", line 173, in visit_If
    self.generic_visit(node)
  File "/home/moumou/miniconda3/lib/python3.8/ast.py", line 439, in generic_visit
    value = self.visit(value)
  File "/home/moumou/miniconda3/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/home/moumou/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/tensor_shape_transformer.py", line 186, in visit_For
    self.generic_visit(node)
  File "/home/moumou/miniconda3/lib/python3.8/ast.py", line 439, in generic_visit
    value = self.visit(value)
  File "/home/moumou/miniconda3/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/home/moumou/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/tensor_shape_transformer.py", line 121, in visit_Assign
    update_static_shape_var_node = self._update_name_to_var_shape(node)
  File "/home/moumou/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/tensor_shape_transformer.py", line 387, in _update_name_to_var_shape
    static_shape_var_node = gast.parse(static_shape_var_name).body[
  File "/home/moumou/.local/lib/python3.8/site-packages/gast/gast.py", line 300, in parse
    return ast_to_gast(_ast.parse(*args, **kwargs))
  File "/home/moumou/miniconda3/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    inputs_shape[i, 0]__static_convert_var_shape_suffix_0
                      ^
SyntaxError: invalid syntax

**Comment by nemonameless** [comment]
是160x320尺度训练的吗？还是导出或保存模型时才采用160x320？
另外建议使用代码根目录下默认的动态图ppyolotiny，release/2.2分支或develop分支。

**Comment by wangxinxin08** [comment]
请问你是如何保存为静态图模型的？可以使用以下命令直接转换为静态图模型：
python tools/export_model.py -c configs/ppyolo/ppyolo_tiny_650e_coco.yml -o weights=https://paddledet.bj.bcebos.com/models/ppyolo_tiny_650e_coco.pdparams
