### ISSUE TITLE
[Feature Request]S2anet  以onnx格式导出

### ISSUE THREAD

**Issue by Unknown-parameters** [PaddlePaddle/PaddleDetection#4289]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## 描述问题/Describe the bug
希望将paddlepaddle 框架下的S2anet 以onnx格式导出

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?
   
   在文件 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0/ppdet/modeling/heads/s2anet_head.py
  希望将s2anet 以onnx 格式导出，却总是提示错误
```none
model = S2ANetHead()
input_spec = paddle.static.InputSpec([None,256], 'float32', 'image')
paddle.jit.save(layer=model,path='paddlestatic/linear.model',input_spec=[input_spec])

```
2.会提示如下错误：

Traceback (most recent call last):
  File "D:\codewz\pds2anet.py", line 1106, in <module>
    paddle.jit.save(layer=model,path='paddlestatic/linear.model',input_spec=[input_spec])
  File "D:\apps\anaconda\envs\paddle\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\apps\anaconda\envs\paddle\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\apps\anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "D:\apps\anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\jit.py", line 736, in save
    concrete_program = static_forward.concrete_program
  File "D:\apps\anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 453, in concrete_program
    return self.concrete_program_specify_input_spec(input_spec=None)
  File "D:\apps\anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 491, in concrete_program_specify_input_spec
    *desired_input_spec)
  File "D:\apps\anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 401, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "D:\apps\anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 714, in __getitem__
    self._caches[item] = self._build_once(item)
  File "D:\apps\anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 705, in _build_once
    class_instance=cache_key.class_instance)
  File "D:\apps\anaconda\envs\paddle\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\apps\anaconda\envs\paddle\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\apps\anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "D:\apps\anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 623, in from_func_spec
    static_func = convert_to_static(dygraph_function)
  File "D:\apps\anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 140, in convert_to_static
    static_func = _FUNCTION_CACHE.convert_with_cache(function)
  File "D:\apps\anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 77, in convert_with_cache
    static_func = self._convert(func)
  File "D:\apps\anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 115, in _convert
    root_wrapper = self._dygraph_to_static.get_static_ast(root)
  File "D:\apps\anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\ast_transformer.py", line 61, in get_static_ast
    self.transfer_from_node_type(self.static_analysis_root)
  File "D:\apps\anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\ast_transformer.py", line 92, in transfer_from_node_type
    self._apply(transformer, node_wrapper, log_level=index + 1)
  File "D:\apps\anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\ast_transformer.py", line 65, in _apply
    transformer(node_wrapper).transform()
  File "D:\apps\anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\tensor_shape_transformer.py", line 118, in transform
    self.visit(self.root)
  File "D:\apps\anaconda\envs\paddle\lib\ast.py", line 253, in visit
    return visitor(node)
  File "D:\apps\anaconda\envs\paddle\lib\ast.py", line 308, in generic_visit
    value = self.visit(value)
  File "D:\apps\anaconda\envs\paddle\lib\ast.py", line 253, in visit
    return visitor(node)
  File "D:\apps\anaconda\envs\paddle\lib\ast.py", line 308, in generic_visit
    value = self.visit(value)
  File "D:\apps\anaconda\envs\paddle\lib\ast.py", line 253, in visit
    return visitor(node)
  File "D:\apps\anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\tensor_shape_transformer.py", line 186, in visit_For
    self.generic_visit(node)
  File "D:\apps\anaconda\envs\paddle\lib\ast.py", line 308, in generic_visit
    value = self.visit(value)
  File "D:\apps\anaconda\envs\paddle\lib\ast.py", line 253, in visit
    return visitor(node)
  File "D:\apps\anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\tensor_shape_transformer.py", line 121, in visit_Assign
    update_static_shape_var_node = self._update_name_to_var_shape(node)
  File "D:\apps\anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\tensor_shape_transformer.py", line 372, in _update_name_to_var_shape
    static_shape_var_name).body[0].value
  File "D:\apps\anaconda\envs\paddle\lib\site-packages\gast\gast.py", line 298, in parse
    return ast_to_gast(_ast.parse(*args, **kwargs))
  File "D:\apps\anaconda\envs\paddle\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    self_featmap_sizes[i]__static_convert_var_shape_suffix_0
                                                           ^
SyntaxError: invalid syntax

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
   Package                           Version
--------------------------------- ---------
astor                             0.8.1
Babel                             2.9.1
backports.entry-points-selectable 1.1.0
bce-python-sdk                    0.8.62
brotlipy                          0.7.0
cached-property                   1.5.2
certifi                           2021.5.30
cffi                              1.14.6
cfgv                              3.3.1
charset-normalizer                2.0.4
click                             8.0.1
colorama                          0.4.4
colorlog                          6.4.1
cryptography                      3.4.7
cycler                            0.10.0
Cython                            0.29.24
dataclasses                       0.8
decorator                         5.0.9
dill                              0.3.4
distlib                           0.3.3
easydict                          1.9
filelock                          3.0.12
flake8                            3.9.2
Flask                             2.0.1
Flask-Babel                       2.0.0
flatbuffers                       2.0
future                            0.18.2
gast                              0.3.3
gitdb                             4.0.7
GitPython                         3.1.18
h5py                              3.1.0
identify                          2.2.15
idna                              3.2
importlib-metadata                4.8.1
importlib-resources               5.2.2
itsdangerous                      2.0.1
jieba                             0.42.1
Jinja2                            3.0.1
joblib                            1.0.1
kiwisolver                        1.3.1
lap                               0.4.0
MarkupSafe                        2.0.1
matplotlib                        3.3.4
mccabe                            0.6.1
mkl-fft                           1.3.0
mkl-random                        1.1.1
mkl-service                       2.3.0
multiprocess                      0.70.12.2
nodeenv                           1.6.0
numpy                             1.19.2
olefile                           0.46
onnx                              1.9.0
onnxruntime                       1.9.0
opencv-python                     4.5.3.56
packaging                         21.0
paddle2onnx                       0.8.2
paddlehub                         2.1.0
paddlenlp                         2.0.8
paddlepaddle                      2.1.3
pandas                            1.1.5
Pillow                            8.3.1
pip                               21.0.1
platformdirs                      2.4.0
pre-commit                        2.15.0
protobuf                          3.17.2
pycocotools                       2.0.2
pycodestyle                       2.7.0
pycparser                         2.20
pycryptodome                      3.10.4
pyflakes                          2.3.1
pyOpenSSL                         20.0.1
pyparsing                         2.4.7
PySocks                           1.7.1
python-dateutil                   2.8.2
pytz                              2021.1
PyYAML                            5.4.1
pyzmq                             22.3.0
rarfile                           4.0
requests                          2.26.0
scikit-learn                      0.24.2
scipy                             1.5.4
seqeval                           1.2.2
setuptools                        58.0.4
shellcheck-py                     0.7.2.1
six                               1.16.0
smmap                             4.0.0
tensorboardX                      2.4
terminaltables                    3.1.0
threadpoolctl                     2.2.0
toml                              0.10.2
torch                             1.9.1
torchvision                       0.10.1
tqdm                              4.62.3
typing-extensions                 3.10.0.2
urllib3                           1.26.6
virtualenv                        20.8.1
visualdl                          2.2.1
Werkzeug                          2.0.1
wheel                             0.37.0
win-inet-pton                     1.1.0
wincertstore                      0.2
zipp                              3.5.0

2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：
   没有

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：
   win10

4. 请问您使用的Python版本是？/ Please provide the version of Python you used.
     Python 3.6.13 

5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.

   没有显卡，ONNX 格式导出，也需是cpu版本。
如果您的issue是关于安装或环境，您可以先查询[安装文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)尝试解决~

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL.md

**Comment by qingqing01** [comment]
收到需求，能问下您导出ONNX后在什么设备上部署嘛？ Paddle的推理引擎能否满足？

**Comment by Unknown-parameters** [comment]
> 收到需求，能问下您导出ONNX后在什么设备上部署嘛？ Paddle的推理引擎能否满足？

paddle的推理引擎就可以。

**Comment by Unknown-parameters** [comment]
> 收到需求，能问下您导出ONNX后在什么设备上部署嘛？ Paddle的推理引擎能否满足？

希望导出模型踢出GPU加速的部分配置。
