### ISSUE TITLE
PPYOLO在训练一段时间后报错

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/PaddleDetection#4293]
- PaddlePaddle 2.1.3
 - PaddleDetection 2.2

PaddleDetection 2.1不会报错，PaddleDetection2.2会报错。

错误如下：
```
WARNING:root:DataLoader reader thread raised an exception.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\envs\PaddlePaddle\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "E:\ProgramData\Anaconda3\envs\PaddlePaddle\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\ProgramData\Anaconda3\envs\PaddlePaddle\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 192, in _thread_loop
    six.reraise(*sys.exc_info())
  File "E:\ProgramData\Anaconda3\envs\PaddlePaddle\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "E:\ProgramData\Anaconda3\envs\PaddlePaddle\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 160, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices)
  File "E:\ProgramData\Anaconda3\envs\PaddlePaddle\lib\site-packages\paddle\fluid\dataloader\fetcher.py", line 106, in fetch
    data = [self.dataset[idx] for idx in batch_indices]
  File "E:\ProgramData\Anaconda3\envs\PaddlePaddle\lib\site-packages\paddle\fluid\dataloader\fetcher.py", line 106, in <listcomp>
    data = [self.dataset[idx] for idx in batch_indices]
  File "E:\ProgramData\Anaconda3\envs\PaddlePaddle\lib\site-packages\ppdet\data\source\dataset.py", line 87, in __getitem__
    return self.transform(roidb)
  File "E:\ProgramData\Anaconda3\envs\PaddlePaddle\lib\site-packages\ppdet\data\reader.py", line 60, in __call__
    raise e
  File "E:\ProgramData\Anaconda3\envs\PaddlePaddle\lib\site-packages\ppdet\data\reader.py", line 54, in __call__
    data = f(data)
  File "E:\ProgramData\Anaconda3\envs\PaddlePaddle\lib\site-packages\ppdet\data\transform\operators.py", line 1619, in __call__
    gt_bbox = np.concatenate((gt_bbox1, gt_bbox2), axis=0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

[10/12 14:17:43] reader WARNING: fail to map sample transform [Mixup_439636] with error: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s) and stack:
Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\envs\PaddlePaddle\lib\site-packages\ppdet\data\reader.py", line 54, in __call__
    data = f(data)
  File "E:\ProgramData\Anaconda3\envs\PaddlePaddle\lib\site-packages\ppdet\data\transform\operators.py", line 1619, in __call__
    gt_bbox = np.concatenate((gt_bbox1, gt_bbox2), axis=0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

[10/12 14:17:45] ppdet.engine INFO: Epoch: [0] [120/148] learning_rate: 0.000030 loss_xy: 8.550854 loss_wh: 9.193151 loss_iou: 60.228333 loss_iou_aware: 6.010039 loss_obj: 50.832211 loss_cls: 54.918388 loss: 193.208923 eta: 9:18:18 batch_cost: 0.5549 data_cost: 0.0001 ips: 7.2087 images/s
Traceback (most recent call last):
  File "D:/yeyupiaoling/PyCharm/detection2/train.py", line 102, in <module>
    main()
  File "D:/yeyupiaoling/PyCharm/detection2/train.py", line 98, in main
    run(FLAGS, cfg)
  File "D:/yeyupiaoling/PyCharm/detection2/train.py", line 71, in run
    trainer.train(FLAGS.eval)
  File "E:\ProgramData\Anaconda3\envs\PaddlePaddle\lib\site-packages\ppdet\engine\trainer.py", line 340, in train
    for step_id, data in enumerate(self.loader):
  File "E:\ProgramData\Anaconda3\envs\PaddlePaddle\lib\site-packages\ppdet\data\reader.py", line 209, in __next__
    return next(self.loader)
  File "E:\ProgramData\Anaconda3\envs\PaddlePaddle\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 197, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at C:\home\workspace\Paddle_release\paddle/fluid/operators/reader/blocking_queue.h:166)

```

**Comment by wangxinxin08** [comment]
使用的数据集是voc格式的数据集吗？建议拉取一下最新的代码，这个是由于有些图片中不存在标注框，导致concat两张图片的标注框报错，这个已经修复了

**Comment by yeyupiaoling** [comment]
我是用pip安装的，是VOC格式。好的
