### ISSUE TITLE
'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by Viperwd** [PaddlePaddle/PaddleDetection#4401]
Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 102, in run
    trainer = Trainer(cfg, mode='train')
  File "/home/aistudio/PaddleDetection/ppdet/engine/trainer.py", line 74, in __init__
    self.dataset, cfg.worker_num)
  File "/home/aistudio/PaddleDetection/ppdet/data/reader.py", line 170, in __call__
    self.dataset.parse_dataset()
  File "/home/aistudio/PaddleDetection/ppdet/data/source/voc.py", line 107, in parse_dataset
    im_w = float(tree.find('size').find('width').text)
AttributeError: 'NoneType' object has no attribute 'find'

以上是报错，我是在本地环境先划分好训练集和测试集然后上传到aistudio中训练，请问这是什么原因呢？

**Comment by ghostxsl** [comment]
看报错信息，可能是环境的问题，也可能是数据格式的问题，你可以排查一下看看呢？

**Comment by Viperwd** [comment]
> 看报错信息，可能是环境的问题，也可能是数据格式的问题，你可以排查一下看看呢？

我排查了一下，环境应该不可能出问题，因为之前跑过另外的数据集，数据格式是voc，我在本地将train.txt那些都生成好了，从报错上来看应该是找不到xml文件中width元素，但是我看了源文件里面是有的啊？难道是生成的路径有问题吗？现在还是没有搞定

**Comment by longranger2** [comment]
我也遇到这个问题，想问下题主解决了吗

**Comment by Kodp** [comment]
我也有这个问题,在/home/aistudio/PaddleDetection/ppdet/data/source/voc.py里面111行 print(xml_file) 打印了一下文件,去找到对于的xml发现是没有标注好的数据集. 把这些没标好的数据集剔除就正常工作了 
正常的vocxml:
```xml
<annotation>
	<folder>CCC</folder>
	<filename>CCC.jpg</filename>
	<path>D:\XXXX\CCC</path>
	<source>
		<database>Unknown</database>
	</source>
	<size>
		<width>500</width>
		<height>334</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>kite</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>204</xmin>
			<ymin>100</ymin>
			<xmax>254</xmax>
			<ymax>161</ymax>
		</bndbox>
	</object>
	<object>
		<name>dog</name>
		<pose>Unspecified</pose>
		<truncated>1</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>1</xmin>
			<ymin>80</ymin>
			<xmax>89</xmax>
			<ymax>163</ymax>
		</bndbox>
	</object>
	<object>
		<name>person</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>166</xmin>
			<ymin>204</ymin>
			<xmax>223</xmax>
			<ymax>264</ymax>
		</bndbox>
	</object>
	<object>
		<name>person</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>439</xmin>
			<ymin>179</ymin>
			<xmax>472</xmax>
			<ymax>213</ymax>
		</bndbox>
	</object>
	<object>
		<name>person</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>423</xmin>
			<ymin>137</ymin>
			<xmax>454</xmax>
			<ymax>164</ymax>
		</bndbox>
	</object>
	<object>
		<name>person</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>318</xmin>
			<ymin>128</ymin>
			<xmax>349</xmax>
			<ymax>157</ymax>
		</bndbox>
	</object>
	<object>
		<name>person</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>340</xmin>
			<ymin>123</ymin>
			<xmax>377</xmax>
			<ymax>153</ymax>
		</bndbox>
	</object>
	<object>
		<name>person</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>113</xmin>
			<ymin>96</ymin>
			<xmax>156</xmax>
			<ymax>141</ymax>
		</bndbox>
	</object>
</annotation>

```
出错的xml
```
<?xml version="1.0" ?>
<doc>
	<path>D:\XXXXX\CCCC\VOCdevkit\VOC2007\JPEGImages\CCCC.jpg</path>
	<outputs></outputs>
	<time_labeled>0</time_labeled>
	<labeled>false</labeled>
</doc>
```
