### ISSUE TITLE
PP-PicoDet 配置好环境之后运行不了！

### ISSUE THREAD

**Issue by sunmooncode** [PaddlePaddle/PaddleDetection#4476]
感谢您做出的贡献，我是第一次使用paddledetection。在我根据安装文档配置好环境之后运行了第一个测试代码，可以运行，但当我运行第二个测试代码的时候，模型输出与文档不相同
![000000014439](https://user-images.githubusercontent.com/86471590/140446100-78b2799e-dbb9-42e6-974a-26dfbcfb82c2.jpg)
在我运行**python tools/train.py -c configs/picodet/picodet_l_640_coco.yml --eva**回报一下错误

**Comment by sunmooncode** [comment]
loading annotations into memory...
Done (t=0.32s)
creating index...
index created!
W1105 10:00:04.103955  7538 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 10.2, Runtime API Version: 10.2
W1105 10:00:04.106922  7538 device_context.cc:465] device: 0, cuDNN Version: 7.6.
[11/05 10:00:14] ppdet.utils.checkpoint INFO: ['_fc.bias', '_fc.weight', '_last_conv._batch_norm._mean', '_last_conv._batch_norm._variance', '_last_conv._batch_norm.bias', '_last_conv._batch_norm.weight', '_last_conv._conv.weight', 'last_conv.weight'] in pretrained weight is not used in the model, and its will not be loaded
[11/05 10:00:14] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/zhangtao/.cache/paddle/weights/ESNet_x1_25_pretrained.pdparams
Traceback (most recent call last):
  File "tools/train.py", line 171, in <module>
    main()
  File "tools/train.py", line 167, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/home/zhangtao/Object_Detection/PaddleDetection/ppdet/engine/trainer.py", line 393, in train
    outputs = model(data)
  File "/home/zhangtao/anaconda3/envs/pp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/zhangtao/Object_Detection/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 54, in forward
    out = self.get_loss()
  File "/home/zhangtao/Object_Detection/PaddleDetection/ppdet/modeling/architectures/picodet.py", line 78, in get_loss
    head_outs, _ = self._forward()
  File "/home/zhangtao/Object_Detection/PaddleDetection/ppdet/modeling/architectures/picodet.py", line 64, in _forward
    fpn_feats = self.neck(body_feats)
  File "/home/zhangtao/anaconda3/envs/pp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/zhangtao/Object_Detection/PaddleDetection/ppdet/modeling/necks/csp_pan.py", line 334, in forward
    paddle.concat([upsample_feat, feat_low], 1))
  File "/home/zhangtao/anaconda3/envs/pp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/zhangtao/Object_Detection/PaddleDetection/ppdet/modeling/necks/csp_pan.py", line 216, in forward
    x_main = self.blocks(x_main)
  File "/home/zhangtao/anaconda3/envs/pp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/zhangtao/anaconda3/envs/pp/lib/python3.6/site-packages/paddle/fluid/dygraph/container.py", line 98, in forward
    input = layer(input)
  File "/home/zhangtao/anaconda3/envs/pp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/zhangtao/Object_Detection/PaddleDetection/ppdet/modeling/necks/csp_pan.py", line 162, in forward
    out = self.conv2(out)
  File "/home/zhangtao/anaconda3/envs/pp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/zhangtao/Object_Detection/PaddleDetection/ppdet/modeling/necks/csp_pan.py", line 112, in forward
    x = self.act_func(self.bn2(self.pwconv(x)))
  File "/home/zhangtao/anaconda3/envs/pp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/zhangtao/anaconda3/envs/pp/lib/python3.6/site-packages/paddle/nn/layer/conv.py", line 677, in forward
    use_cudnn=self._use_cudnn)
  File "/home/zhangtao/anaconda3/envs/pp/lib/python3.6/site-packages/paddle/nn/functional/conv.py", line 123, in _conv_nd
    pre_bias = getattr(_C_ops, op_type)(x, weight, *attrs)
SystemError: (Fatal) Operator conv2d raises an paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 18.906494MB memory on GPU 0, 10.758118GB memory has been allocated and available memory is only 3.125000MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:79)
. (at /paddle/paddle/fluid/imperative/tracer.cc:221)

**Comment by sunmooncode** [comment]
loading annotations into memory...
Done (t=0.32s)
creating index...
index created!
W1105 10:00:04.103955  7538 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 10.2, Runtime API Version: 10.2
W1105 10:00:04.106922  7538 device_context.cc:465] device: 0, cuDNN Version: 7.6.
[11/05 10:00:14] ppdet.utils.checkpoint INFO: ['_fc.bias', '_fc.weight', '_last_conv._batch_norm._mean', '_last_conv._batch_norm._variance', '_last_conv._batch_norm.bias', '_last_conv._batch_norm.weight', '_last_conv._conv.weight', 'last_conv.weight'] in pretrained weight is not used in the model, and its will not be loaded
[11/05 10:00:14] ppdet.utils.checkpoint INFO: Finish loading model weights: /home//.cache/paddle/weights/ESNet_x1_25_pretrained.pdparams
Traceback (most recent call last):
  File "tools/train.py", line 171, in <module>
    main()
  File "tools/train.py", line 167, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/home//Object_Detection/PaddleDetection/ppdet/engine/trainer.py", line 393, in train
    outputs = model(data)
  File "/home//anaconda3/envs/pp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home//Object_Detection/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 54, in forward
    out = self.get_loss()
  File "/home//Object_Detection/PaddleDetection/ppdet/modeling/architectures/picodet.py", line 78, in get_loss
    head_outs, _ = self._forward()
  File "/home//Object_Detection/PaddleDetection/ppdet/modeling/architectures/picodet.py", line 64, in _forward
    fpn_feats = self.neck(body_feats)
  File "/home//anaconda3/envs/pp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home//Object_Detection/PaddleDetection/ppdet/modeling/necks/csp_pan.py", line 334, in forward
    paddle.concat([upsample_feat, feat_low], 1))
  File "/home//anaconda3/envs/pp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home//Object_Detection/PaddleDetection/ppdet/modeling/necks/csp_pan.py", line 216, in forward
    x_main = self.blocks(x_main)
  File "/home//anaconda3/envs/pp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home//anaconda3/envs/pp/lib/python3.6/site-packages/paddle/fluid/dygraph/container.py", line 98, in forward
    input = layer(input)
  File "/home//anaconda3/envs/pp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home//Object_Detection/PaddleDetection/ppdet/modeling/necks/csp_pan.py", line 162, in forward
    out = self.conv2(out)
  File "/home//anaconda3/envs/pp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home//Object_Detection/PaddleDetection/ppdet/modeling/necks/csp_pan.py", line 112, in forward
    x = self.act_func(self.bn2(self.pwconv(x)))
  File "/home//anaconda3/envs/pp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home//anaconda3/envs/pp/lib/python3.6/site-packages/paddle/nn/layer/conv.py", line 677, in forward
    use_cudnn=self._use_cudnn)
  File "/home//anaconda3/envs/pp/lib/python3.6/site-packages/paddle/nn/functional/conv.py", line 123, in _conv_nd
    pre_bias = getattr(_C_ops, op_type)(x, weight, *attrs)
SystemError: (Fatal) Operator conv2d raises an paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 18.906494MB memory on GPU 0, 10.758118GB memory has been allocated and available memory is only 3.125000MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:79)
. (at /paddle/paddle/fluid/imperative/tracer.cc:221)

**Comment by sunmooncode** [comment]
loading annotations into memory...
Done (t=0.32s)
creating index...
index created!
W1105 10:00:04.103955  7538 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 10.2, Runtime API Version: 10.2
W1105 10:00:04.106922  7538 device_context.cc:465] device: 0, cuDNN Version: 7.6.
[11/05 10:00:14] ppdet.utils.checkpoint INFO: ['_fc.bias', '_fc.weight', '_last_conv._batch_norm._mean', '_last_conv._batch_norm._variance', '_last_conv._batch_norm.bias', '_last_conv._batch_norm.weight', '_last_conv._conv.weight', 'last_conv.weight'] in pretrained weight is not used in the model, and its will not be loaded
[11/05 10:00:14] ppdet.utils.checkpoint INFO: Finish loading model weights: /home//.cache/paddle/weights/ESNet_x1_25_pretrained.pdparams
Traceback (most recent call last):
  File "tools/train.py", line 171, in <module>
    main()
  File "tools/train.py", line 167, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/home//Object_Detection/PaddleDetection/ppdet/engine/trainer.py", line 393, in train
    outputs = model(data)
  File "/home//anaconda3/envs/pp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home//Object_Detection/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 54, in forward
    out = self.get_loss()
  File "/home//Object_Detection/PaddleDetection/ppdet/modeling/architectures/picodet.py", line 78, in get_loss
    head_outs, _ = self._forward()
  File "/home//Object_Detection/PaddleDetection/ppdet/modeling/architectures/picodet.py", line 64, in _forward
    fpn_feats = self.neck(body_feats)
  File "/home//anaconda3/envs/pp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home//Object_Detection/PaddleDetection/ppdet/modeling/necks/csp_pan.py", line 334, in forward
    paddle.concat([upsample_feat, feat_low], 1))
  File "/home//anaconda3/envs/pp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home//Object_Detection/PaddleDetection/ppdet/modeling/necks/csp_pan.py", line 216, in forward
    x_main = self.blocks(x_main)
  File "/home//anaconda3/envs/pp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home//anaconda3/envs/pp/lib/python3.6/site-packages/paddle/fluid/dygraph/container.py", line 98, in forward
    input = layer(input)
  File "/home//anaconda3/envs/pp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home//Object_Detection/PaddleDetection/ppdet/modeling/necks/csp_pan.py", line 162, in forward
    out = self.conv2(out)
  File "/home//anaconda3/envs/pp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home//Object_Detection/PaddleDetection/ppdet/modeling/necks/csp_pan.py", line 112, in forward
    x = self.act_func(self.bn2(self.pwconv(x)))
  File "/home//anaconda3/envs/pp/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home//anaconda3/envs/pp/lib/python3.6/site-packages/paddle/nn/layer/conv.py", line 677, in forward
    use_cudnn=self._use_cudnn)
  File "/home//anaconda3/envs/pp/lib/python3.6/site-packages/paddle/nn/functional/conv.py", line 123, in _conv_nd
    pre_bias = getattr(_C_ops, op_type)(x, weight, *attrs)
SystemError: (Fatal) Operator conv2d raises an paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 18.906494MB memory on GPU 0, 10.758118GB memory has been allocated and available memory is only 3.125000MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:79)
. (at /paddle/paddle/fluid/imperative/tracer.cc:221)
显卡是2080ti并无其他进程占用，batch_size=8
多GPU是同样的错误

**Comment by sunmooncode** [comment]
好像是显存不够的原因 但是为什么两张2080ti跑不起来batch_size=8 的picodet_l_640模型呢？

**Comment by lyuwenyu** [comment]
![image](https://user-images.githubusercontent.com/17582080/140448498-d0b6c6d0-a318-4b74-b92f-7c8c63f88604.png)

你把bs调小点  你的单卡GPU显存多大啊  另外你这个命令是单卡的执行命令  

https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/picodet/picodet_l_640_coco.yml#L38

**Comment by sunmooncode** [comment]
![image](https://user-images.githubusercontent.com/86471590/140448704-01e5af10-b976-4679-8d76-a3087c6c1d06.png)
我能跑起来s_320_coco的模型。显存占用如下
![image](https://user-images.githubusercontent.com/86471590/140449159-544d3b77-5342-4d14-a13f-4bb4ad23b173.png)

**Comment by sunmooncode** [comment]
@lyuwenyu 感谢你的帮助 已经解决了 我降低了batch_size可以运行了 但是显存基本满了，可以利用率却很低，跑完250个epoch需要一天多，这个正常吗？
![image](https://user-images.githubusercontent.com/86471590/140449753-9b77bac3-5823-4ce6-832d-76b2164642fe.png)

**Comment by lyuwenyu** [comment]
这个利用率你得持续刷新看一下  动态在变的   利用率低也可能和*cpu读取处理数据慢*有关系的  <可以试着调节下reader num>， 训练感觉时间还行啊
