### ISSUE TITLE
[BUG]sniper训练出错

### ISSUE THREAD

**Issue by fanweiya** [PaddlePaddle/PaddleDetection#4481]
我使用sniper训练自己的voc数据，出现这个错误
```
  File "F:\paddle\PaddleDetection\ppdet\data\reader.py", line 54, in __call__
    data = f(data)
  File "F:\paddle\PaddleDetection\ppdet\data\transform\operators.py", line 254, in __call__
    chip = sample['chip']
KeyError: 'chip'

WARNING:root:DataLoader reader thread raised an exception.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "F:\Anaconda\envs\tf2\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "F:\Anaconda\envs\tf2\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "F:\Anaconda\envs\tf2\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 192, in _thread_loop
    six.reraise(*sys.exc_info())
  File "F:\Anaconda\envs\tf2\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "F:\Anaconda\envs\tf2\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 160, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices)
  File "F:\Anaconda\envs\tf2\lib\site-packages\paddle\fluid\dataloader\fetcher.py", line 106, in fetch
    data = [self.dataset[idx] for idx in batch_indices]
  File "F:\Anaconda\envs\tf2\lib\site-packages\paddle\fluid\dataloader\fetcher.py", line 106, in <listcomp>
    data = [self.dataset[idx] for idx in batch_indices]
  File "F:\paddle\PaddleDetection\ppdet\data\source\dataset.py", line 87, in __getitem__
    return self.transform(roidb)
  File "F:\paddle\PaddleDetection\ppdet\data\reader.py", line 60, in __call__
    raise e
  File "F:\paddle\PaddleDetection\ppdet\data\reader.py", line 54, in __call__
    data = f(data)
  File "F:\paddle\PaddleDetection\ppdet\data\transform\operators.py", line 254, in __call__
    chip = sample['chip']
KeyError: 'chip'
```

**Comment by lyuwenyu** [comment]
1. 目前只支持coco `SniperCOCODataSet`  可以先把voc 转成coco格式   tools下有工具
2. 在reader里decode时候要使用 `SniperDecodeCrop`
