### ISSUE TITLE
ABORT!!! Out of all 4 trainers

### ISSUE THREAD

**Issue by wjplove8** [PaddlePaddle/PaddleDetection#4488]
四显卡，训练一会儿就会报错
ERROR:root:DataLoader reader thread raised an exception!
ERROR:root:DataLoader reader thread failed((Unavailable) Memory map failed when rebuild shared memory.
  [Hint: Expected ptr != ((void *) -1), but received ptr:0xffffffffffffffff == ((void *) -1):0xffffffffffffffff.] (at /paddle/paddle/fluid/memory/allocation/mmap_allocator.cc:97)
) to read data from workers' result queue.
Exception in thread Thread-1376:
Traceback (most recent call last):
  File "/root/Downloads/enter/envs/paddle/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/root/Downloads/enter/envs/paddle/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/root/Downloads/enter/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 411, in _thread_loop
    batch = self._get_data()
  File "/root/Downloads/enter/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 508, in _get_data
    six.reraise(*sys.exc_info())
  File "/root/Downloads/enter/envs/paddle/lib/python3.6/site-packages/six.py", line 719, in reraise
    raise value
  File "/root/Downloads/enter/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 482, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/root/Downloads/enter/envs/paddle/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
RuntimeError: (Unavailable) Memory map failed when rebuild shared memory.
  [Hint: Expected ptr != ((void *) -1), but received ptr:0xffffffffffffffff == ((void *) -1):0xffffffffffffffff.] (at /paddle/paddle/fluid/memory/allocation/mmap_allocator.cc:97)

[11/05 20:37:28] ppdet.utils.checkpoint INFO: Save checkpoint: output/yolov3_mobilenet_v1_270e_coco_ppk
[11/05 20:37:28] ppdet.engine INFO: Epoch: [14210] [0/6] learning_rate: 0.000010 loss_xy: 22.927473 loss_wh: 5.088367 loss_obj: 5.117811 loss_cls: 7.450146 loss: 41.700451 eta: 6:54:29 batch_cost: 0.5585 data_cost: 0.2699 ips: 7.1616 images/s
INFO 2021-11-05 20:38:03,581 launch_utils.py:327] terminate all the procs
ERROR 2021-11-05 20:38:03,581 launch_utils.py:584] ABORT!!! Out of all 4 trainers, the trainer process with rank=[1, 3] was aborted. Please check its log.
INFO 2021-11-05 20:38:06,584 launch_utils.py:327] terminate all the procs

**Comment by lyuwenyu** [comment]
把reader里的 shared memory关掉吧

**Comment by wjplove8** [comment]
> 把reader里的 shared memory关掉吧

谢谢，搞定了。

**Comment by wjplove8** [comment]
> > 把reader里的 shared memory关掉吧
> 
> 谢谢，搞定了。

又报另一个错误了
[11/06 16:03:07] ppdet.utils.checkpoint INFO: Save checkpoint: output/yolov3_mobilenet_v1_270e_coco_ppk
INFO 2021-11-06 16:03:27,655 launch_utils.py:327] terminate all the procs
ERROR 2021-11-06 16:03:27,656 launch_utils.py:584] ABORT!!! Out of all 4 trainers, the trainer process with rank=[2] was aborted. Please check its log.
INFO 2021-11-06 16:03:30,659 launch_utils.py:327] terminate all the procs
这个怎么搞定啊？
