### ISSUE TITLE
输入数据未初始化

### ISSUE THREAD

**Issue by wjplove8** [PaddlePaddle/PaddleDetection#4495]
InvalidArgumentError: The Tensor in the conv2d Op's Input Variable Input(image) is not initialized.
      [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at /paddle/paddle/fluid/framework/operator.cc:1570)
      [operator < conv2d > error]

代码
import argparse
import numpy as np

# 引用 paddle inference 预测库
import paddle.inference as paddle_infer

def main():
    args = parse_args()

    # 创建 config
    config = paddle_infer.Config('inference_model/yolov3_mobilenet_v1_270e_coco_ppk/model.pdmodel', 'inference_model/yolov3_mobilenet_v1_270e_coco_ppk/model.pdiparams')
    config.disable_gpu()

    # 根据 config 创建 predictor
    predictor = paddle_infer.create_predictor(config)

    # 获取输入的名称
    input_names = predictor.get_input_names()
    input_handle = predictor.get_input_handle(input_names[0])

    # 设置输入
    fake_input = np.random.randn(args.batch_size, 3, 318, 318).astype("float32")
    input_handle.reshape([1, 3, 318, 318])
    input_handle.copy_from_cpu(fake_input)

    # 运行predictor
    predictor.run()

    # 获取输出
    output_names = predictor.get_output_names()
    output_handle = predictor.get_output_handle(output_names[0])
    output_data = output_handle.copy_to_cpu() # numpy.ndarray类型
    print("Output data size is {}".format(output_data.size))
    print("Output data shape is {}".format(output_data.shape))

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--model_file", type=str, help="model filename")
    parser.add_argument("--params_file", type=str, help="parameter filename")
    parser.add_argument("--batch_size", type=int, default=1, help="batch size")
    return parser.parse_args()

if __name__ == "__main__":
    main()

运行记录
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [layer_norm_fuse_pass]
---    Fused 0 subgraphs into layer_norm op.
--- Running IR pass [attention_lstm_fuse_pass]
--- Running IR pass [seqconv_eltadd_relu_fuse_pass]
--- Running IR pass [seqpool_cvm_concat_fuse_pass]
--- Running IR pass [mul_lstm_fuse_pass]
--- Running IR pass [fc_gru_fuse_pass]
--- Running IR pass [mul_gru_fuse_pass]
--- Running IR pass [seq_concat_fc_fuse_pass]
--- Running IR pass [squeeze2_matmul_fuse_pass]
--- Running IR pass [reshape2_matmul_fuse_pass]
--- Running IR pass [flatten2_matmul_fuse_pass]
--- Running IR pass [map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [repeated_fc_relu_fuse_pass]
--- Running IR pass [squared_mat_sub_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
I1106 18:31:26.704246  2066 graph_pattern_detector.cc:91] ---  detected 34 subgraphs
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [conv_transpose_bn_fuse_pass]
--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]
--- Running IR pass [is_test_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [ir_graph_to_program_pass]
I1106 18:31:26.783437  2066 analysis_predictor.cc:636] ======= optimize end =======
I1106 18:31:26.785154  2066 naive_executor.cc:98] ---  skip [feed], feed -> scale_factor
I1106 18:31:26.785178  2066 naive_executor.cc:98] ---  skip [feed], feed -> image
I1106 18:31:26.785187  2066 naive_executor.cc:98] ---  skip [feed], feed -> im_shape
I1106 18:31:26.787674  2066 naive_executor.cc:98] ---  skip [save_infer_model/scale_0.tmp_1], fetch -> fetch
I1106 18:31:26.787695  2066 naive_executor.cc:98] ---  skip [save_infer_model/scale_1.tmp_1], fetch -> fetch
Traceback (most recent call last):
  File "infertest.py", line 44, in <module>
    main()
  File "infertest.py", line 27, in main
    predictor.run()
ValueError: In user code:

    File "tools/export_model.py", line 105, in <module>
      main()
    File "tools/export_model.py", line 101, in main
      run(FLAGS, cfg)
    File "tools/export_model.py", line 69, in run
      trainer.export(FLAGS.output_dir)
    File "/root/Documents/PaddleDetection-2.1.0/ppdet/engine/trainer.py", line 507, in export
      input_spec, static_model.forward.main_program,
    File "/root/Downloads/enter/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 534, in main_program
      concrete_program = self.concrete_program
    File "/root/Downloads/enter/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 454, in concrete_program
      return self.concrete_program_specify_input_spec(input_spec=None)
    File "/root/Downloads/enter/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program_specify_input_spec
      *desired_input_spec)
    File "/root/Downloads/enter/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/root/Downloads/enter/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/root/Downloads/enter/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 702, in _build_once
      class_instance=cache_key.class_instance)
    File "<decorator-gen-65>", line 2, in from_func_spec
      
    File "/root/Downloads/enter/envs/paddle/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/root/Downloads/enter/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
      return func(*args, **kwargs)
    File "/root/Downloads/enter/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 652, in from_func_spec
      outputs = static_func(*inputs)
    File "/tmp/tmpdw10dem3.py", line 27, in forward
      false_fn_1, (), (), (out,))
    File "/root/Downloads/enter/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/root/Downloads/enter/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/root/Documents/PaddleDetection-2.1.0/ppdet/modeling/architectures/meta_arch.py", line 29, in forward
      out = self.get_pred()
    File "/root/Documents/PaddleDetection-2.1.0/ppdet/modeling/architectures/yolo.py", line 104, in get_pred
      return self._forward()
    File "/root/Documents/PaddleDetection-2.1.0/ppdet/modeling/architectures/yolo.py", line 63, in _forward
      body_feats = self.backbone(self.inputs)
    File "/root/Downloads/enter/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/root/Documents/PaddleDetection-2.1.0/ppdet/modeling/backbones/mobilenet_v1.py", line 391, in forward
      y = self.conv1(inputs['image'])
    File "/root/Downloads/enter/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/root/Documents/PaddleDetection-2.1.0/ppdet/modeling/backbones/mobilenet_v1.py", line 75, in forward
      x = self._conv(x)
    File "/root/Downloads/enter/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/root/Downloads/enter/envs/paddle/lib/python3.6/site-packages/paddle/nn/layer/conv.py", line 667, in forward
      use_cudnn=self._use_cudnn)
    File "/root/Downloads/enter/envs/paddle/lib/python3.6/site-packages/paddle/nn/functional/conv.py", line 139, in _conv_nd
      type=op_type, inputs=inputs, outputs=outputs, attrs=attrs)
    File "/root/Downloads/enter/envs/paddle/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/root/Downloads/enter/envs/paddle/lib/python3.6/site-packages/paddle/fluid/framework.py", line 3232, in append_op
      attrs=kwargs.get("attrs", None))
    File "/root/Downloads/enter/envs/paddle/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2312, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The Tensor in the conv2d Op's Input Variable Input(image) is not initialized.
      [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at /paddle/paddle/fluid/framework/operator.cc:1570)
      [operator < conv2d > error]
求告知解决办法！

**Comment by nemonameless** [comment]
请使用Paddle的最新版本，以及PaddleDetection的release/2.3分支或develop分支最新代码再试试。

**Comment by blackwilliam** [comment]
请问楼主上述问题解决了么？

**Comment by wjplove8** [comment]
> 请问楼主上述问题解决了么？

输入数据精度或者shape有问题

**Comment by ghazalli** [comment]
> 输入数据精度或者shape有问题

Hi, can you please tell me how to fix it? I am facing the same issue

**Comment by akemi0301** [comment]
> 输入数据精度或者shape有问题

Hi, can you please tell me how to fix it? I am facing the same issue

**Comment by rexzhengzhihong** [comment]
最后怎么解决的?
