### ISSUE TITLE
不能分配内存

### ISSUE THREAD

**Issue by wjplove8** [PaddlePaddle/PaddleDetection#4505]
Traceback (most recent call last):
  File "/root/Documents/PaddleDetection-2.1.0/ppdet/data/reader.py", line 211, in __next__
    return next(self.loader)
  File "/root/Downloads/enter/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 609, in __next__
    six.reraise(*sys.exc_info())
  File "/root/Downloads/enter/envs/paddle/lib/python3.6/site-packages/six.py", line 719, in reraise
    raise value
  File "/root/Downloads/enter/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 585, in __next__
    data = self._reader.read_next_var_list()
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 111, in run
    trainer.train(FLAGS.eval)
  File "/root/Documents/PaddleDetection-2.1.0/ppdet/engine/trainer.py", line 289, in train
    for step_id, data in enumerate(self.loader):
  File "/root/Documents/PaddleDetection-2.1.0/ppdet/data/reader.py", line 213, in __next__
    self.loader = iter(self.dataloader)
  File "/root/Downloads/enter/envs/paddle/lib/python3.6/site-packages/paddle/fluid/reader.py", line 426, in __iter__
    return _DataLoaderIterMultiProcess(self)
  File "/root/Downloads/enter/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 283, in __init__
    self._init_workers()
  File "/root/Downloads/enter/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 317, in _init_workers
    indices_queue = multiprocessing.Queue()
  File "/root/Downloads/enter/envs/paddle/lib/python3.6/multiprocessing/context.py", line 102, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/root/Downloads/enter/envs/paddle/lib/python3.6/multiprocessing/queues.py", line 48, in __init__
    self._sem = ctx.BoundedSemaphore(maxsize)
  File "/root/Downloads/enter/envs/paddle/lib/python3.6/multiprocessing/context.py", line 87, in BoundedSemaphore
    return BoundedSemaphore(value, ctx=self.get_context())
  File "/root/Downloads/enter/envs/paddle/lib/python3.6/multiprocessing/synchronize.py", line 146, in __init__
    SemLock.__init__(self, SEMAPHORE, value, value, ctx=ctx)
  File "/root/Downloads/enter/envs/paddle/lib/python3.6/multiprocessing/synchronize.py", line 60, in __init__
    unlink_now)
OSError: [Errno 12] Cannot allocate memory
Exception ignored in: <bound method _DataLoaderIterMultiProcess.__del__ of <paddle.fluid.dataloader.dataloader_iter._DataLoaderIterMultiProcess object at 0x7f653c4f3da0>>
Traceback (most recent call last):
  File "/root/Downloads/enter/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 566, in __del__
    self._try_shutdown_all()
  File "/root/Downloads/enter/envs/paddle/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 371, in _try_shutdown_all
    if not self._shutdown:
AttributeError: '_DataLoaderIterMultiProcess' object has no attribute '_shutdown'

**Comment by ghostxsl** [comment]
可以试一下Paddle 2.2 + PaddleDetection 2.3

**Comment by wjplove8** [comment]
> 可以试一下Paddle 2.2 + PaddleDetection 2.3

Paddle develop版本是2.2？

**Comment by ghostxsl** [comment]
你这个是用的今天Paddle的develop版本？那PaddleDetection版本呢？

**Comment by wjplove8** [comment]
> 你这个是用的今天Paddle的develop版本？那PaddleDetection版本呢？

我用的是Paddle2.1，PaddleDetection

**Comment by wjplove8** [comment]
> 你这个是用的今天Paddle的develop版本？那PaddleDetection版本呢？

我用的是Paddle2.1，PaddleDetection2.2

**Comment by ghostxsl** [comment]
首先，建议您先把版本更新到最新版本试一下；其次，您可以用df -h查看一下shm剩余空间是否充足，可以做一下清理，如果不行的话，建议您设置use_shared_memory: false
