### ISSUE TITLE
PicoDet_LCNet在AIStudio在线平台多卡训练会卡住不动

### ISSUE THREAD

**Issue by gaorui999** [PaddlePaddle/PaddleDetection#4537]
使用环境：AIStudio多卡环境，4卡V100

项目只换了数据集，其他均没动

出现的问题：先卡在下方报错信息处住不动，然后出现报错信息
`INFO 2021-11-10 16:05:13,396 launch_utils.py:514] details abouts PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0`
复现链接https://aistudio.baidu.com/aistudio/clusterprojectdetail/2604746

报错信息

```
-----------  Configuration Arguments -----------
gpus: None
heter_worker_num: None
heter_workers: 
http_port: None
ips: 127.0.0.1
log_dir: log
nproc_per_node: None
run_mode: None
server_num: None
servers: 
training_script: tools/train.py
training_script_args: ['-c', 'configs/picodet/more_config/picodet_lcnet_1_5x_416_coco.yml', '--eval', '--use_vdl=True', '--vdl_log_dir=./output_vdl']
worker_num: None
workers: 
------------------------------------------------
launch train in GPU mode!
launch proc_id:575 idx:0
launch proc_id:578 idx:1
launch proc_id:581 idx:2
launch proc_id:584 idx:3
/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/matplotlib/__init__.py:107: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping
/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/matplotlib/rcsetup.py:20: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, Mapping
/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/matplotlib/colors.py:53: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Sized
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
W1110 16:05:19.432087   575 gen_comm_id_helper.cc:120] connect addr=127.0.0.1:36148 failed 1 times with reason: Connection refused retry after 0.5 seconds
I1110 16:05:19.932402   575 nccl_context.cc:74] init nccl context nranks: 4 local rank: 0 gpu id: 0 ring id: 0
W1110 16:05:20.867942   575 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W1110 16:05:20.872742   575 device_context.cc:422] device: 0, cuDNN Version: 7.6.
[11/10 16:05:32] ppdet.utils.checkpoint INFO: Finish loading model weights: /root/.cache/paddle/weights/LCNet_x1_5_pretrained.pdparams
[11/10 16:05:42] ppdet.engine INFO: Epoch: [0] [ 0/36] learning_rate: 0.040000 loss_vfl: 1.058675 loss_bbox: 1.150959 loss_dfl: 0.526002 loss: 2.735636 eta: 1 day, 5:06:00 batch_cost: 9.7000 data_cost: 3.5743 ips: 8.2474 images/s
[11/10 16:06:26] ppdet.engine INFO: Epoch: [0] [20/36] learning_rate: 0.064000 loss_vfl: 1.131893 loss_bbox: 0.954573 loss_dfl: 0.409348 loss: 2.493075 eta: 7:22:33 batch_cost: 2.1014 data_cost: 0.0015 ips: 38.0707 images/s
[11/10 16:07:03] ppdet.engine INFO: Epoch: [1] [ 0/36] learning_rate: 0.083200 loss_vfl: 0.831147 loss_bbox: 0.847894 loss_dfl: 0.311841 loss: 1.968768 eta: 6:56:44 batch_cost: 2.0769 data_cost: 0.2520 ips: 38.5197 images/s
[11/10 16:07:47] ppdet.engine INFO: Epoch: [1] [20/36] learning_rate: 0.107200 loss_vfl: 0.960380 loss_bbox: 0.666163 loss_dfl: 0.299931 loss: 1.934374 eta: 6:38:41 batch_cost: 2.0480 data_cost: 0.0016 ips: 39.0625 images/s
[11/10 16:08:24] ppdet.engine INFO: Epoch: [2] [ 0/36] learning_rate: 0.126400 loss_vfl: 1.000886 loss_bbox: 0.608110 loss_dfl: 0.281977 loss: 1.875407 eta: 6:34:33 batch_cost: 2.0901 data_cost: 0.3384 ips: 38.2764 images/s
[11/10 16:09:08] ppdet.engine INFO: Epoch: [2] [20/36] learning_rate: 0.150400 loss_vfl: 1.007146 loss_bbox: 0.550765 loss_dfl: 0.265372 loss: 1.825643 eta: 6:27:33 batch_cost: 2.0435 data_cost: 0.0015 ips: 39.1495 images/s
[11/10 16:09:44] ppdet.engine INFO: Epoch: [3] [ 0/36] learning_rate: 0.169600 loss_vfl: 1.003227 loss_bbox: 0.528359 loss_dfl: 0.258924 loss: 1.793429 eta: 6:23:18 batch_cost: 2.0064 data_cost: 0.2177 ips: 39.8718 images/s
[11/10 16:10:30] ppdet.engine INFO: Epoch: [3] [20/36] learning_rate: 0.193600 loss_vfl: 1.001270 loss_bbox: 0.485682 loss_dfl: 0.237464 loss: 1.734013 eta: 6:24:01 batch_cost: 2.2032 data_cost: 0.0015 ips: 36.3110 images/s
[11/10 16:11:09] ppdet.engine INFO: Epoch: [4] [ 0/36] learning_rate: 0.212800 loss_vfl: 1.011781 loss_bbox: 0.468566 loss_dfl: 0.227161 loss: 1.709629 eta: 6:24:12 batch_cost: 2.1906 data_cost: 0.2433 ips: 36.5192 images/s
[11/10 16:11:53] ppdet.engine INFO: Epoch: [4] [20/36] learning_rate: 0.236800 loss_vfl: 1.025020 loss_bbox: 0.438414 loss_dfl: 0.220344 loss: 1.681251 eta: 6:21:43 batch_cost: 2.0818 data_cost: 0.0015 ips: 38.4287 images/s
[11/10 16:12:31] ppdet.engine INFO: Epoch: [5] [ 0/36] learning_rate: 0.256000 loss_vfl: 1.000936 loss_bbox: 0.420318 loss_dfl: 0.210942 loss: 1.627643 eta: 6:20:41 batch_cost: 2.1035 data_cost: 0.3219 ips: 38.0311 images/s
[11/10 16:13:12] ppdet.engine INFO: Epoch: [5] [20/36] learning_rate: 0.280000 loss_vfl: 0.968056 loss_bbox: 0.408644 loss_dfl: 0.213700 loss: 1.596188 eta: 6:16:17 batch_cost: 1.9416 data_cost: 0.0016 ips: 41.2038 images/s
[11/10 16:13:50] ppdet.engine INFO: Epoch: [6] [ 0/36] learning_rate: 0.299200 loss_vfl: 0.999736 loss_bbox: 0.386705 loss_dfl: 0.201358 loss: 1.597884 eta: 6:15:59 batch_cost: 2.0420 data_cost: 0.2398 ips: 39.1780 images/s
[11/10 16:14:36] ppdet.engine INFO: Epoch: [6] [20/36] learning_rate: 0.323200 loss_vfl: 0.966027 loss_bbox: 0.382793 loss_dfl: 0.203804 loss: 1.560536 eta: 6:15:48 batch_cost: 2.1677 data_cost: 0.0016 ips: 36.9054 images/s
[11/10 16:15:11] ppdet.engine INFO: Epoch: [7] [ 0/36] learning_rate: 0.342400 loss_vfl: 0.953037 loss_bbox: 0.382199 loss_dfl: 0.205187 loss: 1.541156 eta: 6:13:26 batch_cost: 1.9536 data_cost: 0.3305 ips: 40.9497 images/s
[11/10 16:15:57] ppdet.engine INFO: Epoch: [7] [20/36] learning_rate: 0.366400 loss_vfl: 0.951935 loss_bbox: 0.358023 loss_dfl: 0.191601 loss: 1.503792 eta: 6:14:00 batch_cost: 2.2233 data_cost: 0.0015 ips: 35.9825 images/s
[11/10 16:16:34] ppdet.engine INFO: Epoch: [8] [ 0/36] learning_rate: 0.385600 loss_vfl: 0.945749 loss_bbox: 0.352588 loss_dfl: 0.202400 loss: 1.496670 eta: 6:13:15 batch_cost: 2.0901 data_cost: 0.2297 ips: 38.2752 images/s
[11/10 16:17:19] ppdet.engine INFO: Epoch: [8] [20/36] learning_rate: 0.399198 loss_vfl: 0.954820 loss_bbox: 0.352271 loss_dfl: 0.187174 loss: 1.492702 eta: 6:12:55 batch_cost: 2.1639 data_cost: 0.0015 ips: 36.9698 images/s
[11/10 16:17:56] ppdet.engine INFO: Epoch: [9] [ 0/36] learning_rate: 0.399112 loss_vfl: 0.943213 loss_bbox: 0.349240 loss_dfl: 0.191201 loss: 1.488216 eta: 6:11:38 batch_cost: 2.0198 data_cost: 0.2950 ips: 39.6074 images/s
[11/10 16:18:40] ppdet.engine INFO: Epoch: [9] [20/36] learning_rate: 0.399000 loss_vfl: 0.912806 loss_bbox: 0.342342 loss_dfl: 0.186754 loss: 1.444996 eta: 6:10:11 batch_cost: 2.0541 data_cost: 0.0016 ips: 38.9462 images/s
[11/10 16:19:06] ppdet.utils.checkpoint INFO: Save checkpoint: output/picodet_lcnet_1_5x_416_coco
ERROR:root:DataLoader reader thread raised an exception!
Traceback (most recent call last):
  File "tools/train.py", line 171, in <module>
    main()
  File "tools/train.py", line 167, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/root/paddlejob/workspace/code/PaddleDetection-release-2.3/ppdet/engine/trainer.py", line 442, in train
    self._eval_with_loader(self._eval_loader)
  File "/root/paddlejob/workspace/code/PaddleDetection-release-2.3/ppdet/engine/trainer.py", line 458, in _eval_with_loader
    for step_id, data in enumerate(loader):
  File "/root/paddlejob/workspace/code/PaddleDetection-release-2.3/ppdet/data/reader.py", line 209, in __next__
    return next(self.loader)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 565, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

Exception in thread Thread-14:
Traceback (most recent call last):
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
INFO 2021-11-10 16:19:17,360 launch_utils.py:327] terminate all the procs
ERROR 2021-11-10 16:19:17,360 launch_utils.py:584] ABORT!!! Out of all 4 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-11-10 16:19:20,363 launch_utils.py:327] terminate all the procs
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 391, in _thread_loop
    batch = self._get_data()
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 505, in _get_data
    batch.reraise()
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 168, in reraise
    raise self.exc_type(msg)
ValueError: DataLoader worker(3) caught ValueError with message:
Traceback (most recent call last):
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 320, in _worker_loop
    batch = fetcher.fetch(indices)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 117, in fetch
    data = self.collate_fn(data)
  File "/root/paddlejob/workspace/code/PaddleDetection-release-2.3/ppdet/data/reader.py", line 91, in __call__
    batch_data = default_collate_fn(data)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 70, in default_collate_fn
    for key in sample
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 70, in <dictcomp>
    for key in sample
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 58, in default_collate_fn
    batch = np.stack(batch, axis=0)
  File "<__array_function__ internals>", line 6, in stack
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/numpy/core/shape_base.py", line 427, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape
```

**Comment by yghstill** [comment]
@gaorui999 参考voc的配置，加下这两行https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/picodet/picodet_s_320_voc.yml#L36-L37
