### ISSUE TITLE
mask_rcnn_r50_fpn_1x_qat 推理部署

### ISSUE THREAD

**Issue by usuixingyili** [PaddlePaddle/PaddleDetection#4549]
预训练fp32模型和裁剪模型推理都没问题，量化模型推理报错，调用的是deploy文件夹下的infer.py，predict_image函数
ppdet release/2.1

Traceback (most recent call last):
  File "D:/softwares/PaddleDetection/workspace/dl_project.py", line 325, in <module>
    Endoscope(task_name='task5_2_2783').BatchPredict()
  File "D:/softwares/PaddleDetection/workspace/dl_project.py", line 221, in BatchPredict
    dict_results, _ = predict_image(detector, image_list, threshold=0.6)
  File "D:\softwares\PaddleDetection\workspace\deploy\infer.py", line 499, in predict_image
    results = detector.predict(batch_image_list, threshold)
  File "D:\softwares\PaddleDetection\workspace\deploy\infer.py", line 153, in predict
    self.predictor.run()
ValueError: In user code:

    File "tools\export_model.py", line 105, in <module>
      main()
    File "tools\export_model.py", line 101, in main
      run(FLAGS, cfg)
    File "tools\export_model.py", line 69, in run
      trainer.export(FLAGS.output_dir)
    File "D:\softwares\Anaconda3\envs\ppdet\lib\site-packages\ppdet\engine\trainer.py", line 573, in export
      input_spec, static_model.forward.main_program,
    File "D:\softwares\Anaconda3\envs\ppdet\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 537, in main_program
      concrete_program = self.concrete_program
    File "D:\softwares\Anaconda3\envs\ppdet\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 453, in concrete_program
      return self.concrete_program_specify_input_spec(input_spec=None)
    File "D:\softwares\Anaconda3\envs\ppdet\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 491, in concrete_program_specify_input_spec
      *desired_input_spec)
    File "D:\softwares\Anaconda3\envs\ppdet\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 401, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "D:\softwares\Anaconda3\envs\ppdet\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 714, in __getitem__
      self._caches[item] = self._build_once(item)
    File "D:\softwares\Anaconda3\envs\ppdet\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 705, in _build_once
      class_instance=cache_key.class_instance)
    File "<decorator-gen-64>", line 2, in from_func_spec
      
    File "D:\softwares\Anaconda3\envs\ppdet\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "D:\softwares\Anaconda3\envs\ppdet\lib\site-packages\paddle\fluid\dygraph\base.py", line 40, in __impl__
      return func(*args, **kwargs)
    File "D:\softwares\Anaconda3\envs\ppdet\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 655, in from_func_spec
      outputs = static_func(*inputs)
    File "C:\Users\xingyili\AppData\Local\Temp\tmp3brzrq16.py", line 29, in forward
      false_fn_1, (), (), (out,))
    File "D:\softwares\Anaconda3\envs\ppdet\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "D:\softwares\Anaconda3\envs\ppdet\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "D:\softwares\Anaconda3\envs\ppdet\lib\site-packages\ppdet\modeling\architectures\meta_arch.py", line 28, in forward
      out = self.get_pred()
    File "D:\softwares\Anaconda3\envs\ppdet\lib\site-packages\ppdet\modeling\architectures\mask_rcnn.py", line 133, in get_pred
      bbox_pred, bbox_num, mask_pred = self._forward()
    File "C:\Users\xingyili\AppData\Local\Temp\tmp7vq7o68e.py", line 69, in _forward
      rois, rois_num))
    File "D:\softwares\Anaconda3\envs\ppdet\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "D:\softwares\Anaconda3\envs\ppdet\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "D:\softwares\Anaconda3\envs\ppdet\lib\site-packages\ppdet\modeling\architectures\mask_rcnn.py", line 103, in _forward
      rois, rois_num, _ = self.rpn_head(body_feats, self.inputs)
    File "D:\softwares\Anaconda3\envs\ppdet\lib\site-packages\paddle\fluid\dygraph\layers.py", line 902, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "D:\softwares\Anaconda3\envs\ppdet\lib\site-packages\ppdet\modeling\proposal_generator\rpn_head.py", line 133, in forward
      rois, rois_num = self._gen_proposal(scores, deltas, anchors, inputs)
    File "C:\Users\xingyili\AppData\Local\Temp\tmpozp30v86.py", line 102, in _gen_proposal
      bbox_deltas, scores, im_shape, i, anchors, bs_rois_num_collect])
    File "D:\softwares\Anaconda3\envs\ppdet\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 42, in convert_while_loop
      loop_vars = _run_paddle_while_loop(cond, body, loop_vars)
    File "D:\softwares\Anaconda3\envs\ppdet\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 52, in _run_paddle_while_loop
      loop_vars = control_flow.while_loop(cond, body, loop_vars)
    File "D:\softwares\Anaconda3\envs\ppdet\lib\site-packages\paddle\fluid\layers\control_flow.py", line 1203, in while_loop
      output_vars = body(*new_loop_vars)
    File "D:\softwares\Anaconda3\envs\ppdet\lib\site-packages\ppdet\modeling\proposal_generator\rpn_head.py", line 168, in _gen_proposal
      anchors=anchor,
    File "D:\softwares\Anaconda3\envs\ppdet\lib\site-packages\paddle\fluid\framework.py", line 1683, in __getitem__
      return _getitem_impl_(self, item)
    File "D:\softwares\Anaconda3\envs\ppdet\lib\site-packages\paddle\fluid\variable_index.py", line 225, in _getitem_impl_
      attrs=attrs)
    File "D:\softwares\Anaconda3\envs\ppdet\lib\site-packages\paddle\fluid\framework.py", line 2967, in append_op
      attrs=kwargs.get("attrs", None))
    File "D:\softwares\Anaconda3\envs\ppdet\lib\site-packages\paddle\fluid\framework.py", line 2039, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The tensor Input (Input) of Slice op is not initialized.
      [Hint: Expected in_tensor.IsInitialized() == true, but received in_tensor.IsInitialized():0 != true:1.] (at C:/home/workspace/Paddle_release/paddle/fluid/operators/slice_op.cc:178)
      [operator < slice > error]

**Comment by jerrywgz** [comment]
我们这边目前正在排查中，尽快给您反馈
