### ISSUE TITLE
yolo剪裁敏感度分析时报错

### ISSUE THREAD

**Issue by hp-cuiwb** [PaddlePaddle/PaddleDetection#457]
nohup python3 ./slim/prune/sensitive.py -c ./configs/yolov3_darknet_voc.yml --pruned_params "yolo_input.conv.weights,yolo_input.downsample.conv.weights,stage.0.0.0.conv.weights,stage.0.0.1.conv.weights,stage.0.downsample.conv.weights,stage.1.0.0.conv.weights,stage.1.0.1.conv.weights,stage.1.1.0.conv.weights,stage.1.1.1.conv.weights,stage.1.downsample.conv.weights,stage.2.0.0.conv.weights,stage.2.0.1.conv.weights,stage.2.1.0.conv.weights,stage.2.1.1.conv.weights,stage.2.2.0.conv.weights,stage.2.2.1.conv.weights,stage.2.3.0.conv.weights,stage.2.3.1.conv.weights,stage.2.4.0.conv.weights,stage.2.4.1.conv.weights,stage.2.5.0.conv.weights,stage.2.5.1.conv.weights,stage.2.6.0.conv.weights,stage.2.6.1.conv.weights,stage.2.7.0.conv.weights,stage.2.7.1.conv.weights,stage.2.downsample.conv.weights,stage.3.0.0.conv.weights,stage.3.0.1.conv.weights,stage.3.1.0.conv.weights,stage.3.1.1.conv.weights,stage.3.2.0.conv.weights,stage.3.2.1.conv.weights,stage.3.3.0.conv.weights,stage.3.3.1.conv.weights,stage.3.4.0.conv.weights,stage.3.4.1.conv.weights,stage.3.5.0.conv.weights,stage.3.5.1.conv.weights,stage.3.6.0.conv.weights,stage.3.6.1.conv.weights,stage.3.7.0.conv.weights,stage.3.7.1.conv.weights,stage.3.downsample.conv.weights,stage.4.0.0.conv.weights,stage.4.0.1.conv.weights,stage.4.1.0.conv.weights,stage.4.1.1.conv.weights,stage.4.2.0.conv.weights,stage.4.2.1.conv.weights,stage.4.3.0.conv.weights,stage.4.3.1.conv.weights,yolo_block.0.0.0.conv.weights,yolo_block.0.0.1.conv.weights,yolo_block.0.1.0.conv.weights,yolo_block.0.1.1.conv.weights,yolo_block.0.2.conv.weights,yolo_block.0.tip.conv.weights,yolo_transition.0.conv.weights,yolo_block.1.0.0.conv.weights,yolo_block.1.0.1.conv.weights,yolo_block.1.1.0.conv.weights,yolo_block.1.1.1.conv.weights,yolo_block.1.2.conv.weights,yolo_block.1.tip.conv.weights,yolo_transition.1.conv.weights,yolo_block.2.0.0.conv.weights,yolo_block.2.0.1.conv.weights,yolo_block.2.1.0.conv.weights,yolo_block.2.1.1.conv.weights,yolo_block.2.2.conv.weights,yolo_block.2.tip.conv.weights" --sensitivities_file "./demo.data" -o https://paddlemodels.bj.bcebos.com/object_detection/yolov3_darknet_voc.tar

**Comment by hp-cuiwb** [comment]
Traceback (most recent call last):
  File "./slim/prune/sensitive.py", line 213, in <module>
    main()
  File "./slim/prune/sensitive.py", line 122, in main
    checkpoint.load_params(exe, eval_prog, cfg.weights)
  File "/home/cwb/14/PaddleDetection/ppdet/utils/checkpoint.py", line 142, in load_params
    fluid.io.set_program_state(prog, state)
  File "/home/cwb/.local/lib/python3.7/site-packages/paddle/fluid/io.py", line 1943, in set_program_state
    .format(orig_para_np.shape, para.name, new_para_np.shape)
AssertionError: Shape not matching: the Program requires a parameter with a shape of ((512,)), while the loaded parameter (namely [ stage.3.5.1.bn.scale ]) has a shape of  ((358,)).
Traceback (most recent call last):
  File "./slim/prune/sensitive.py", line 212, in <module>
    FLAGS = parser.parse_args()
  File "/home/cwb/14/PaddleDetection/ppdet/utils/cli.py", line 58, in parse_args
    args.opt = self._parse_opt(args.opt)
  File "/home/cwb/14/PaddleDetection/ppdet/utils/cli.py", line 67, in _parse_opt
    k, v = s.split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)
