### ISSUE TITLE
[BUG] DETR模型测试报错，默认配置文件只改了VOC数据集

### ISSUE THREAD

**Issue by gaorui9999** [PaddlePaddle/PaddleDetection#4704]
```
Traceback (most recent call last):
  File "tools/train.py", line 171, in <module>
    main()
  File "tools/train.py", line 167, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/home/aistudio/PaddleDetection-release-2.3/ppdet/engine/trainer.py", line 361, in train
    self._flops(self.loader)
  File "/home/aistudio/PaddleDetection-release-2.3/ppdet/engine/trainer.py", line 704, in _flops
    flops = flops(self.model, input_spec) / (1000**3)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/analysis/flops.py", line 133, in dygraph_flops
    program = dygraph2program(model, inputs)
  File "<decorator-gen-415>", line 2, in dygraph2program
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 229, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/core/dygraph.py", line 120, in dygraph2program
    original_outputs = layer(*inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleDetection-release-2.3/ppdet/modeling/architectures/meta_arch.py", line 56, in forward
    out = self.get_pred()
  File "/home/aistudio/PaddleDetection-release-2.3/ppdet/modeling/architectures/detr.py", line 88, in get_pred
    bbox_pred, bbox_num = self._forward()
  File "/home/aistudio/PaddleDetection-release-2.3/ppdet/modeling/architectures/detr.py", line 68, in _forward
    out_transformer = self.transformer(body_feats, self.inputs['pad_mask'])
KeyError: 'pad_mask'
```

**Comment by ghostxsl** [comment]
你需要在Reader里加上PadMaskBatch操作，参考：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/detr/_base_/detr_reader.yml#L31

**Comment by gaorui999** [comment]
我看了一下Reader里的内容，里面是包含PadMaskBatch操作的
```
worker_num: 1
TrainReader:
  sample_transforms:
  - Decode: {}
  - RandomFlip: {prob: 0.5}
  - RandomSelect: { transforms1: [ RandomShortSideResize: { short_side_sizes: [ 480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800 ], max_size: 1333 } ],
                    transforms2: [
                        RandomShortSideResize: { short_side_sizes: [ 400, 500, 600 ] },
                        RandomSizeCrop: { min_size: 384, max_size: 600 },
                        RandomShortSideResize: { short_side_sizes: [ 480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800 ], max_size: 1333 } ]
  }
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - NormalizeBox: {}
  - BboxXYXY2XYWH: {}
  - Permute: {}
  batch_transforms:
  - PadMaskBatch: {pad_to_stride: -1, return_pad_mask: true}
  batch_size: 1
  shuffle: true
  drop_last: true
  collate_batch: false
  use_shared_memory: false


EvalReader:
  sample_transforms:
  - Decode: {}
  - Resize: {target_size: [800, 1333], keep_ratio: True}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadMaskBatch: {pad_to_stride: -1, return_pad_mask: true}
  batch_size: 1
  shuffle: false
  drop_last: false
  drop_empty: false


TestReader:
  sample_transforms:
  - Decode: {}
  - Resize: {target_size: [800, 1333], keep_ratio: True}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadMaskBatch: {pad_to_stride: -1, return_pad_mask: true}
  batch_size: 1
  shuffle: false
  drop_last: false
```

**Comment by ghostxsl** [comment]
你用DETR在VOC上训练不报错吗？

**Comment by gaorui999** [comment]
我是用DETR在VOC上报错

**Comment by ghostxsl** [comment]
发一下你修改后的yml，以及运行命令

**Comment by gaorui999** [comment]
detr_r50.yml，optimizer_1x.yml都是使用系统默认的。

detr_reader.yml
```
worker_num: 1
TrainReader:
  sample_transforms:
  - Decode: {}
  - RandomFlip: {prob: 0.5}
  - RandomSelect: { transforms1: [ RandomShortSideResize: { short_side_sizes: [ 480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800 ], max_size: 1333 } ],
                    transforms2: [
                        RandomShortSideResize: { short_side_sizes: [ 400, 500, 600 ] },
                        RandomSizeCrop: { min_size: 384, max_size: 600 },
                        RandomShortSideResize: { short_side_sizes: [ 480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800 ], max_size: 1333 } ]
  }
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - NormalizeBox: {}
  - BboxXYXY2XYWH: {}
  - Permute: {}
  batch_transforms:
  - PadMaskBatch: {pad_to_stride: -1, return_pad_mask: true}
  batch_size: 1
  shuffle: true
  drop_last: true
  collate_batch: false
  use_shared_memory: false


EvalReader:
  sample_transforms:
  - Decode: {}
  - Resize: {target_size: [800, 1333], keep_ratio: True}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadMaskBatch: {pad_to_stride: -1, return_pad_mask: true}
  batch_size: 1
  shuffle: false
  drop_last: false
  drop_empty: false


TestReader:
  sample_transforms:
  - Decode: {}
  - Resize: {target_size: [800, 1333], keep_ratio: True}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadMaskBatch: {pad_to_stride: -1, return_pad_mask: true}
  batch_size: 1
  shuffle: false
  drop_last: false
```
detr_r50_1x_coco.yml

```
_BASE_: [
  '../datasets/voc.yml',
  '../runtime.yml',
  '_base_/optimizer_1x.yml',
  '_base_/detr_r50.yml',
  '_base_/detr_reader.yml',
]
weights: output/detr_r50_1x_coco/model_final
```
optimizer_1x.yml
```
epoch: 500

LearningRate:
  base_lr: 0.0001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [400]
    use_warmup: false

OptimizerBuilder:
  clip_grad_by_norm: 0.1
  regularizer: false
  optimizer:
    type: AdamW
    weight_decay: 0.0001
```
detr_r50.yml
```
architecture: DETR
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_vb_normal_pretrained.pdparams
hidden_dim: 256


DETR:
  backbone: ResNet
  transformer: DETRTransformer
  detr_head: DETRHead
  post_process: DETRBBoxPostProcess


ResNet:
  # index 0 stands for res2
  depth: 50
  norm_type: bn
  freeze_at: 0
  return_idx: [3]
  lr_mult_list: [0.0, 0.1, 0.1, 0.1]
  num_stages: 4


DETRTransformer:
  num_queries: 100
  position_embed_type: sine
  nhead: 8
  num_encoder_layers: 6
  num_decoder_layers: 6
  dim_feedforward: 2048
  dropout: 0.1
  activation: relu


DETRHead:
  num_mlp_layers: 3


DETRLoss:
  loss_coeff: {class: 1, bbox: 5, giou: 2, no_object: 0.1, mask: 1, dice: 1}
  aux_loss: True


HungarianMatcher:
  matcher_coeff: {class: 1, bbox: 5, giou: 2}
```

**Comment by ghostxsl** [comment]
我这里用你这个配置运行没有报错，请问你是一开始就报错还是训了一段时间才报错的呢？

**Comment by gaorui999** [comment]
一开始就报错，请问您使用的VOC数据集吗

**Comment by ghostxsl** [comment]
是的，我是复制你的配置拉到我本地跑的

**Comment by ghostxsl** [comment]
看报错信息，肯定是Mask那个op没生效，你可以debug看看，有可能你更改的配置没生效之类的

**Comment by gaorui999** [comment]
感谢您的回复，我是在AIStudio平台跑的，我再创建个项目试试。

**Comment by ghostxsl** [comment]
AIStudio环境配置经常出问题😓

**Comment by gaorui999** [comment]
用了develop这个分支跑起来的，2.3这个分支会报错

**Comment by ghostxsl** [comment]
我这边试了2.3和develop分支都能跑起来～

**Comment by gaorui999** [comment]
感觉您的回复，我还有一个问题，我把batch_size=8,lr=0.01调成了这俩，就会报这个错误，是什么问题啊？
```
Traceback (most recent call last):
  File "tools/train.py", line 171, in <module>
    main()
  File "tools/train.py", line 167, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/home/aistudio/paddle-detection1125/ppdet/engine/trainer.py", line 399, in train
    outputs = model(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/paddle-detection1125/ppdet/modeling/architectures/meta_arch.py", line 58, in forward
    out = self.get_loss()
  File "/home/aistudio/paddle-detection1125/ppdet/modeling/architectures/detr.py", line 80, in get_loss
    losses = self._forward()
  File "/home/aistudio/paddle-detection1125/ppdet/modeling/architectures/detr.py", line 72, in _forward
    return self.detr_head(out_transformer, body_feats, self.inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/paddle-detection1125/ppdet/modeling/heads/detr_head.py", line 286, in forward
    gt_mask=gt_mask)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/paddle-detection1125/ppdet/modeling/losses/detr_loss.py", line 205, in forward
    gt_bbox, gt_class)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/paddle-detection1125/ppdet/modeling/transformers/matchers.py", line 122, in forward
    for i, c in enumerate(C)
  File "/home/aistudio/paddle-detection1125/ppdet/modeling/transformers/matchers.py", line 122, in <listcomp>
    for i, c in enumerate(C)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/scipy/optimize/_lsap.py", line 101, in linear_sum_assignment
    a, b = _lsap_module.calculate_assignment(cost_matrix.T)
ValueError: matrix contains invalid numeric entries
```

**Comment by ghostxsl** [comment]
看报错信息的话是挂在了计算二分图匹配的地方，应该是之前计算loss matrix的时候出nan了，你debug一下看看是不是梯度爆炸了或者可是输入非法数据了？
