### ISSUE TITLE
导入IterableDataset 报错

### ISSUE THREAD

**Issue by Yan-Xiaodi** [PaddlePaddle/PaddleDetection#4710]
您好，我在配置完环境后尝试运行PaddleDetection中的`test_architectures.py`文件，但是出现下面的报错
```
Traceback (most recent call last):
  File "test_architectures.py", line 20, in <module>
    import ppdet
  File "/home/yanxiaodi/segmentation/PaddleDetection/ppdet/__init__.py", line 15, in <module>
    from . import (core, data, engine, modeling, model_zoo, optimizer, metrics,
  File "/home/yanxiaodi/segmentation/PaddleDetection/ppdet/data/__init__.py", line 15, in <module>
    from . import source
  File "/home/yanxiaodi/segmentation/PaddleDetection/ppdet/data/source/__init__.py", line 15, in <module>
    from . import coco
  File "/home/yanxiaodi/segmentation/PaddleDetection/ppdet/data/source/coco.py", line 18, in <module>
    from .dataset import DetDataset
  File "/home/yanxiaodi/segmentation/PaddleDetection/ppdet/data/source/dataset.py", line 22, in <module>
    from paddle.io import Dataset
  File "/home/yanxiaodi/anaconda3/lib/python3.7/site-packages/paddle/io/__init__.py", line 19, in <module>
    from ..fluid.dataloader import IterableDataset  # noqa: F401
ImportError: cannot import name 'IterableDataset' from 'paddle.fluid.dataloader' (/home/yanxiaodi/anaconda3/lib/python3.7/site-packages/paddle/fluid/dataloader/__init__.py)
```
我进入到`paddle/fluid/dataloader`文件夹中对相应的模块进行搜索，的确没有`IterableDataset`这个模块，请问这是什么问题呢？
paddle version：2.2.0

**Comment by qingqing01** [comment]
看起来像是Paddle版本不对应，请查看下运行时的Paddle版本吧

```
import paddle
print(paddle.__version__)
```

**Comment by Yan-Xiaodi** [comment]
> 
版本就是2.2.0呀，按着教程安装的

**Comment by Yan-Xiaodi** [comment]
> 看起来像是Paddle版本不对应，请查看下运行时的Paddle版本吧
> 
> ```
> import paddle
> print(paddle.__version__)
> ```

版本就是2.2.0呀，按着教程安装的

**Comment by qingqing01** [comment]
我本地测试正常，2.2版本是有的

https://github.com/PaddlePaddle/Paddle/blob/14fd53d5840fb1bdce6b8d3fad04087982824f06/python/paddle/fluid/dataloader/dataset.py#L21
