### ISSUE TITLE
关于 TensorRT 动态 shape 问题

### ISSUE THREAD

**Issue by FL77N** [PaddlePaddle/PaddleDetection#4735]
您好，TensorRT 版本是 7.2.3 已经设置了动态 shape 
infer_mode:norm
infer_quant:False
inference:deploy/python/infer.py
--device:gpu|cpu
--enable_mkldnn:False|True
--cpu_threads:1|4
--batch_size:1
--use_tensorrt:null
--run_mode:fluid|trt_fp32|trt_fp16
--model_dir:./test_tipc/output/norm_train_gpus_0_autocast_null/fast_rcnn_r50_fpn_1x_coco
--image_dir:./test_tipc/demo
--save_log_path:null
--run_benchmark:True
--trt_max_shape:1333
--trt_min_shape:200
--trt_opt_shape:640

并且在输出也体现了
-----------  Model Configuration -----------
Model Arch: RCNN
Transform Order: 
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--transform op: PadStride

{'image': [1, 3, 200, 200]} {'image': [1, 3, 1333, 1333]} {'image': [1, 3, 640, 640]}
trt set dynamic shape done!

但是依然报错
Traceback (most recent call last):
  File "deploy/python/infer.py", line 678, in <module>
    main()
  File "deploy/python/infer.py", line 618, in main
    enable_mkldnn=FLAGS.enable_mkldnn)
  File "deploy/python/infer.py", line 93, in __init__
    enable_mkldnn=enable_mkldnn)
  File "deploy/python/infer.py", line 465, in load_predictor
    predictor = create_predictor(config)
ValueError: (InvalidArgument) some trt inputs dynamic shape info not set, check the INFO log above for more details.
  [Hint: Expected all_dynamic_shape_set == true, but received all_dynamic_shape_set:0 != true:1.] (at /paddle/paddle/fluid/inference/tensorrt/convert/op_converter.h:245)

**Comment by ghostxsl** [comment]
您好，可以参考文档：https://github.com/PaddlePaddle/PaddleDetection/blob/develop/deploy/TENSOR_RT.md

**Comment by FL77N** [comment]
> 您好，可以参考文档：https://github.com/PaddlePaddle/PaddleDetection/blob/develop/deploy/TENSOR_RT.md

棒！通过 min_subgraph_size 解决了，想问一下第二种设置子图的动态 shape 有参考吗

**Comment by ghostxsl** [comment]
目前暂时没有，第二种方法是要获取模型的图结构，单独设置一些节点的shape，这个偏向模型trt的定制优化，可能要具体模型具体分析

**Comment by ghostxsl** [comment]
我可以给你举个例子：比如我现在已知一个模型的图结构有两个节点：“tmp.0”，“tmp.1”
参考下面的代码，你可以设置动态shape：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/deploy/python/infer.py#L548

比如：
max_input_shape = {
    'tmp.0': [10, 3, 1000, 1000],
    'tmp.1': [10, 100, 100, 100]
}
config.set_trt_dynamic_shape_info(min_input_shape, max_input_shape,
                                  opt_input_shape)
min, max, opt你都可以自己写好dict，通过调用set_trt_dynamic_shape_info()这个api去设置trt的动态shape

**Comment by FL77N** [comment]
> 我可以给你举个例子：比如我现在已知一个模型的图结构有两个节点：“tmp.0”，“tmp.1” 参考下面的代码，你可以设置动态shape： https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/deploy/python/infer.py#L548
> 
> 比如： max_input_shape = { 'tmp.0': [10, 3, 1000, 1000], 'tmp.1': [10, 100, 100, 100] } config.set_trt_dynamic_shape_info(min_input_shape, max_input_shape, opt_input_shape) min, max, opt你都可以自己写好dict，通过调用set_trt_dynamic_shape_info()这个api去设置trt的动态shape

懂了，谢谢你！
