### ISSUE TITLE
[BUG]训练transformer模型，AttributeError: 'dict' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by xupengao** [PaddlePaddle/PaddleDetection#4752]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://paddledetection.readthedocs.io/FAQ.html) /I have read the [FAQ documentation](https://paddledetection.readthedocs.io/FAQ.html) but cannot get the expected help.
3. 确认bug是否在新版本里还未修复/The bug has not been fixed in the latest version.

## 描述问题/Describe the bug
训练transformer模型出现问题，一直报错
## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?
python  tools/train.py -c configs/faster_rcnn/faster_rcnn_swin_tiny_fpn_1x_coco.yml --eval

```none
请填写命令/A placeholder for the command.
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.
无
3. 您使用的数据集是？/What dataset did you use?
自定义数据集
4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.
Traceback (most recent call last):
  File "tools/train.py", line 171, in <module>
    main()
  File "tools/train.py", line 167, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 118, in run
    trainer = Trainer(cfg, mode='train')
  File "/data/xupengao/PaddleDetection/ppdet/engine/trainer.py", line 121, in __init__
    self.optimizer = create('OptimizerBuilder')(self.lr, self.model)
  File "/data/xupengao/PaddleDetection/ppdet/optimizer.py", line 269, in __call__
    **optim_args)
  File "/data/zhangxuanxuan/anaconda3/envs/paddle2.2/lib/python3.7/site-packages/paddle/optimizer/adamw.py", line 145, in __init__
    multi_precision=multi_precision)
  File "/data/zhangxuanxuan/anaconda3/envs/paddle2.2/lib/python3.7/site-packages/paddle/optimizer/adam.py", line 160, in __init__
    name=name)
  File "/data/zhangxuanxuan/anaconda3/envs/paddle2.2/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/data/zhangxuanxuan/anaconda3/envs/paddle2.2/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 276, in __impl__
    return func(*args, **kwargs)
  File "/data/zhangxuanxuan/anaconda3/envs/paddle2.2/lib/python3.7/site-packages/paddle/optimizer/optimizer.py", line 150, in __init__
    self._dtype = self._parameter_list[0].dtype
AttributeError: 'dict' object has no attribute 'dtype'

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
paddle2.2 paddledetection-release/2.3分支
2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：
linux
4. 请问您使用的Python版本是？/ Please provide the version of Python you used.
python3.7
5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.

cuda11.2 
如果您的issue是关于安装或环境，您可以先查询[安装文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)尝试解决~

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL.md

**Comment by ACFFF** [comment]
同样问题+1，手动修改获取dtype后又会遇到其他错误

**Comment by yangrisheng** [comment]
这个issue为什么关闭了
