### ISSUE TITLE
ONNX文件转换tflite文件时出现错误

### ISSUE THREAD

**Issue by YY-GAO** [PaddlePaddle/PaddleDetection#4753]
使用代码
`python tools/export_model.py -c configs/ppyolo/ppyolo_tiny_650e_coco.yml -o weights=output/ppyolo_tiny_650e_coco/model_final.pdparams TestReader.inputs_def.image_shape=[3,320,320]`
导出之后，尝试用
`paddle2onnx --model_dir output_inference/ppyolo_tiny_650e_coco/ --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 11 --save_file ppyolo_tiny.onnx`
代码导出ONNX，然后使用onnx_tf转换时，出现

Traceback (most recent call last):
  File "/home/gyy/Documents/onnx-tensorflow/trans.py", line 7, in <module>
    tf_rep.export_graph("./home/gyy/Documents/")  # export the model
  File "/home/gyy/Documents/onnx-tensorflow/onnx_tf/backend_rep.py", line 143, in export_graph
    signatures=self.tf_module.__call__.get_concrete_function(
  File "/home/gyy/.conda/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 1259, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/home/gyy/.conda/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 1239, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/home/gyy/.conda/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 780, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/home/gyy/.conda/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 3157, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/home/gyy/.conda/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 3557, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/gyy/.conda/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 3392, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/home/gyy/.conda/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py", line 1143, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/gyy/.conda/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/eager/def_function.py", line 672, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/gyy/.conda/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/eager/function.py", line 4095, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "/home/gyy/.conda/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py", line 1129, in autograph_handler
    raise e.ag_error_metadata.to_exception(e)
RuntimeError: in user code:
    File "/home/gyy/Documents/onnx-tensorflow/onnx_tf/backend_tf_module.py", line 99, in __call__  *
        output_ops = self.backend._onnx_node_to_tensorflow_op(onnx_node,
    File "/home/gyy/Documents/onnx-tensorflow/onnx_tf/backend.py", line 347, in _onnx_node_to_tensorflow_op  *
        return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
    File "/home/gyy/Documents/onnx-tensorflow/onnx_tf/handlers/handler.py", line 58, in handle  *
        cls.args_check(node, **kwargs)
    File "/home/gyy/Documents/onnx-tensorflow/onnx_tf/handlers/backend/resize.py", line 133, in args_check  *
        exception.OP_UNSUPPORTED_EXCEPT(
    File "/home/gyy/Documents/onnx-tensorflow/onnx_tf/common/exception.py", line 50, in __call__  *
        raise self._func(self.get_message(op, framework))
    RuntimeError: Resize coordinate_transformation_mode=half_pixel and  mode=nearest is not supported in Tensorflow.

的错误
请问大神们怎么解决= =

**Comment by yghstill** [comment]
@YY-GAO resize这个OP在tf中不支持mode=nearest这种情况，需要修改下。
