### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gaocheng** [PaddlePaddle/PaddleDetection#4777]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://paddledetection.readthedocs.io/FAQ.html) /I have read the [FAQ documentation](https://paddledetection.readthedocs.io/FAQ.html) but cannot get the expected help.
3. 确认bug是否在新版本里还未修复/The bug has not been fixed in the latest version.

## 描述问题/Describe the bug

[12/02 01:11:48] ppdet.utils.checkpoint INFO: Save checkpoint: output/picodet_s_320_coco
[12/02 01:11:48] ppdet.engine INFO: Eval iter: 0
[12/02 01:11:58] ppdet.engine INFO: Eval iter: 100
Traceback (most recent call last):
  File "/home/PaddleDetection/tools/train.py", line 171, in <module>
    main()
  File "/home/PaddleDetection/tools/train.py", line 167, in main
    run(FLAGS, cfg)
  File "/home/PaddleDetection/tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/home/PaddleDetection/ppdet/engine/trainer.py", line 442, in train
    self._eval_with_loader(self._eval_loader)
  File "/home/PaddleDetection/ppdet/engine/trainer.py", line 466, in _eval_with_loader
    metric.update(data, outs)
  File "/home/PaddleDetection/ppdet/metrics/metrics.py", line 106, in update
    outs, self.clsid2catid, bias=self.bias)
  File "/home/PaddleDetection/ppdet/metrics/coco_utils.py", line 53, in get_infer_results
    outs['bbox'], outs['bbox_num'], im_id, catid, bias=bias)
  File "/home/PaddleDetection/ppdet/metrics/json_results.py", line 30, in get_det_res
    category_id = label_to_cat_id_map[int(num_id)]
KeyError: 1

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?
python tools/train.py -c /home/PaddleDetection/configs/picodet/picodet_s_320_coco.yml --use_vdl=true --vdl_log_dir=/home/PaddleDetection/vdl_log_dir --eval
```
python tools/train.py -c /home/PaddleDetection/configs/picodet/picodet_s_320_coco.yml --use_vdl=true --vdl_log_dir=/home/PaddleDetection/vdl_log_dir --eval
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.

3. 您使用的数据集是？/What dataset did you use?
coco
4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
2021.11.03: 发布[release/2.3版本]
2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：
无
3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：
ubuntu 18
4. 请问您使用的Python版本是？/ Please provide the version of Python you used.
3.7.3
5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_21:12:58_PST_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0
如果您的issue是关于安装或环境，您可以先查询[安装文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)尝试解决~

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL.md

**Comment by ghostxsl** [comment]
你这是用自己的数据集训练的吗？看报错信息是你的annotation里label_to_cat_id不对

**Comment by gaocheng** [comment]
是的，用的我自己的训练集合，我的label只有一个，修改哪里的label_to_cat_id呢？

**Comment by ghostxsl** [comment]
你这个是用的coco数据集的格式吗？如果是的话，可以参考coco数据格式修改你自己的annotation就可以了

**Comment by gaocheng** [comment]
我是用voc格式转换成coco数据格式，coco数据格式是这里有问题吗？"categories": [{"supercategory": "none", "id": 1, "name": "ball"}]

**Comment by ghostxsl** [comment]
有点奇怪，你这里明明写了"id": 1，但是报错是在dict里找不到key=1，你能把label_to_cat_id_map print出来吗？

**Comment by gaocheng** [comment]
{0: 1}
0.0
{0: 1}
0.0
{0: 1}
0.0
{0: 1}
0.0
{0: 1}
0.0
{0: 1}
0.0
{0: 1}
0.0
{0: 1}
0.0
{0: 1}
0.0
{0: 1}
1.0
Traceback (most recent call last):
  File "/home/PaddleDetection/tools/train.py", line 171, in <module>
    main()
  File "/home/PaddleDetection/tools/train.py", line 167, in main
    run(FLAGS, cfg)
  File "/home/PaddleDetection/tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/home/PaddleDetection/ppdet/engine/trainer.py", line 442, in train
    self._eval_with_loader(self._eval_loader)
  File "/home/PaddleDetection/ppdet/engine/trainer.py", line 466, in _eval_with_loader
    metric.update(data, outs)
  File "/home/PaddleDetection/ppdet/metrics/metrics.py", line 106, in update
    outs, self.clsid2catid, bias=self.bias)
  File "/home/PaddleDetection/ppdet/metrics/coco_utils.py", line 53, in get_infer_results
    outs['bbox'], outs['bbox_num'], im_id, catid, bias=bias)
  File "/home/PaddleDetection/ppdet/metrics/json_results.py", line 32, in get_det_res
    category_id = label_to_cat_id_map[int(num_id)]
KeyError: 1

**Comment by ghostxsl** [comment]
你是几分类任务啊？是不是只有一个类别？

**Comment by gaocheng** [comment]
一个lable，重新生成了train.json文件之后问题解决了
