### ISSUE TITLE
[Other General Issues]在MultiClassDiouNMS静态图转动态图时预测报错

### ISSUE THREAD

**Issue by gaorui999** [PaddlePaddle/PaddleDetection#4807]
1、报错内容如下
```
Traceback (most recent call last):
  File "tools/infer.py", line 170, in <module>
    main()
  File "tools/infer.py", line 166, in main
    run(FLAGS, cfg)
  File "tools/infer.py", line 134, in run
    save_txt=FLAGS.save_txt)
  File "/home/aistudio/paddle-detection1125/ppdet/engine/trainer.py", line 522, in predict
    outs = self.model(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/paddle-detection1125/ppdet/modeling/architectures/meta_arch.py", line 70, in forward
    outs.append(self.get_pred())
  File "/home/aistudio/paddle-detection1125/ppdet/modeling/architectures/picodet.py", line 89, in get_pred
    bbox_pred, bbox_num = self._forward()
  File "/home/aistudio/paddle-detection1125/ppdet/modeling/architectures/picodet.py", line 72, in _forward
    scale_factor)
  File "/home/aistudio/paddle-detection1125/ppdet/modeling/heads/gfl_head.py", line 479, in post_process
    bbox_pred, bbox_num, _ = self.nms(bboxes, score)
  File "/home/aistudio/paddle-detection1125/ppdet/modeling/ops.py", line 1760, in __call__
    pred_result=_diou_nms(bboxes, scores)
  File "/home/aistudio/paddle-detection1125/ppdet/modeling/ops.py", line 1731, in _diou_nms
    dets_j = np.hstack((scores_j[:, np.newaxis], rois_j)).astype(
  File "<__array_function__ internals>", line 6, in hstack
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numpy/core/shape_base.py", line 346, in hstack
    return _nx.concatenate(arrs, 1)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 2 dimension(s)

```
2、MultiClassDiouNMS静态图转动态图代码如下
```
@register
@serializable
class MultiClassDiouNMS(object):
    def __init__(
            self,
            score_threshold=0.05,
            keep_top_k=100,
            nms_threshold=0.5,
            normalized=False,
            background_label=0, ):
        super(MultiClassDiouNMS, self).__init__()
        self.score_threshold = score_threshold
        self.nms_threshold = nms_threshold
        self.keep_top_k = keep_top_k
        self.normalized = normalized
        self.background_label = background_label

    def __call__(self, bboxes, scores):

        

        def _calc_diou_term(dets1, dets2):#计算了P , G 两个框的最远顶点与框中心距离的比值
            eps = 1.e-10
            eta = 0 if self.normalized else 1

            x1, y1, x2, y2 = dets1[0], dets1[1], dets1[2], dets1[3]
            x1g, y1g, x2g, y2g = dets2[0], dets2[1], dets2[2], dets2[3]

            cx = (x1 + x2) / 2
            cy = (y1 + y2) / 2
            w = x2 - x1 + eta
            h = y2 - y1 + eta

            cxg = (x1g + x2g) / 2
            cyg = (y1g + y2g) / 2
            wg = x2g - x1g + eta
            hg = y2g - y1g + eta

            x2 = np.maximum(x1, x2)
            y2 = np.maximum(y1, y2)

            # A or B
            xc1 = np.minimum(x1, x1g)
            yc1 = np.minimum(y1, y1g)
            xc2 = np.maximum(x2, x2g)
            yc2 = np.maximum(y2, y2g)

            # DIOU term  距离的比值
            dist_intersection = (cx - cxg)**2 + (cy - cyg)**2
            dist_union = (xc2 - xc1)**2 + (yc2 - yc1)**2
            diou_term = (dist_intersection + eps) / (dist_union + eps)
            return diou_term

        def _diou_nms_for_cls(dets, thres):
            """_diou_nms_for_cls"""
            scores = dets[:, 0]
            x1 = dets[:, 1]
            y1 = dets[:, 2]
            x2 = dets[:, 3]
            y2 = dets[:, 4]
            eta = 0 if self.normalized else 1
            #求目标面积
            areas = (x2 - x1 + eta) * (y2 - y1 + eta)

            dt_num = dets.shape[0]
            #range(x)计数到X结束 range(0,x) 后展开[0,1,2,3,4,..,x]
            order = np.array(range(dt_num))

            keep = []
            while order.size > 0:
                i = order[0]#先把第一个放进i去
                keep.append(i)
                #比较第一个框与第二个框的IOU
                xx1 = np.maximum(x1[i], x1[order[1:]])
                yy1 = np.maximum(y1[i], y1[order[1:]])
                xx2 = np.minimum(x2[i], x2[order[1:]])
                yy2 = np.minimum(y2[i], y2[order[1:]])

                w = np.maximum(0.0, xx2 - xx1 + eta)
                h = np.maximum(0.0, yy2 - yy1 + eta)
                
                inter = w * h
                ovr = inter / (areas[i] + areas[order[1:]] - inter)#IOU

                diou_term = _calc_diou_term([x1[i], y1[i], x2[i], y2[i]], [
                    x1[order[1:]], y1[order[1:]], x2[order[1:]], y2[order[1:]]
                ])
                
                inds = np.where(ovr - diou_term <= thres)[0]
                #返回满足条件的索引

                order = order[inds + 1]

            dets_final = dets[keep]
            return dets_final

        def _diou_nms(bboxes, scores):
            bboxes = np.array(bboxes)
            scores = np.array(scores)
            class_nums = scores.shape[-1]

            score_threshold = self.score_threshold
            nms_threshold = self.nms_threshold
            keep_top_k = self.keep_top_k

            cls_boxes = [[] for _ in range(class_nums)]
            cls_ids = [[] for _ in range(class_nums)]
            #print(scores.shape)#(1, 8, 2500)
            #print(bboxes.shape)#(1, 2500, 4)
            start_idx = 1 if self.background_label == 0 else 0
            for j in range(start_idx, class_nums):
                inds = np.where(scores[:, j] >= score_threshold)[0]
                #print(inds)
                #print(inds.shape)18
                scores_j = scores[inds, j]
                print(scores_j)
                #print(scores_j.shape) (18, 2500)
                rois_j = bboxes[inds, j, :]
                print(rois_j)
                #print(rois_j.shape)(18, 4)
                dets_j = np.hstack((scores_j[:, np.newaxis], rois_j)).astype(
                #dets_j = np.hstack((scores_j, rois_j)).astype(
                    np.float32, copy=False)
                cls_rank = np.argsort(-dets_j[:, 0])
                dets_j = dets_j[cls_rank]

                cls_boxes[j] = _diou_nms_for_cls(dets_j, thres=nms_threshold)
                cls_ids[j] = np.array([j] * cls_boxes[j].shape[0]).reshape(-1,
                                                                           1)

            cls_boxes = np.vstack(cls_boxes[start_idx:])
            cls_ids = np.vstack(cls_ids[start_idx:])
            pred_result = np.hstack([cls_ids, cls_boxes]).astype(np.float32)

            # Limit to max_per_image detections **over all classes**
            image_scores = cls_boxes[:, 0]
            if len(image_scores) > keep_top_k:
                image_thresh = np.sort(image_scores)[-keep_top_k]
                keep = np.where(cls_boxes[:, 0] >= image_thresh)[0]
                pred_result = pred_result[keep, :]

            res = fluid.LoDTensor()
            res.set_lod([[0, pred_result.shape[0]]])
            if pred_result.shape[0] == 0:
                pred_result = np.array([[1]], dtype=np.float32)
            res.set(pred_result, fluid.CPUPlace())

            return res

        pred_result=_diou_nms(bboxes, scores)
        return pred_result
```

**Comment by jerrywgz** [comment]
从报错信息来看，是score和roi拼接的时候纬度不一致导致的，单类别时roi的shape应该是[N,4] score的shape是[N,1]
