### ISSUE TITLE
[BUG] WSL2 - ubuntu20.04 无法使用多进程读取数据

### ISSUE THREAD

**Issue by jeffzhengye** [PaddlePaddle/PaddleDetection#4869]
configs/yolov3下面配置位置中配置多进程读取数据（worker_num: 8）总是会崩溃，请问是怎么回事？

[12/10 23:43:30] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/jeffye/.cache/paddle/weights/yolov3_mobilenet_v1_270e_coco.pdparams
Traceback (most recent call last):
  File "/home/jeffye/anaconda3/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 584, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/home/jeffye/anaconda3/lib/python3.8/multiprocessing/queues.py", line 108, in get
    raise Empty
_queue.Empty
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/jeffye/anaconda3/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 584, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/home/jeffye/anaconda3/lib/python3.8/multiprocessing/queues.py", line 108, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jeffye/anaconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/jeffye/anaconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jeffye/anaconda3/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 506, in _thread_loop
    batch = self._get_data()
  File "/home/jeffye/anaconda3/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 601, in _get_data
    raise RuntimeError("DataLoader {} workers exit unexpectedly, " \
RuntimeError: DataLoader 1 workers exit unexpectedly, pids: 18337
Traceback (most recent call last):
  File "tools/train.py", line 171, in <module>
    main()
  File "tools/train.py", line 167, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/home/jeffye/code/image/PaddleDetection/ppdet/engine/trainer.py", line 380, in train
    for step_id, data in enumerate(self.loader):
  File "/home/jeffye/code/image/PaddleDetection/ppdet/data/reader.py", line 209, in __next__
    return next(self.loader)
  File "/home/jeffye/anaconda3/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 700, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

同样的代码配置，1. 如果worker_num: 1 可以正常训练；2.不在wsl2下面，在存ubuntu 主机运行也是没有问题。

请问是不是WSL2 这个环境有bug啊？

**Comment by ghostxsl** [comment]
请问您使用的paddle的版本和paddledetection的版本是什么？

**Comment by jeffzhengye** [comment]
> 

paddle 用的是2.2.1, paddledetection 2.2 2.3 devlop 都用过，都一样啊。

**Comment by ghostxsl** [comment]
我这边使用和您一样的配置是可以成功运行的，您看看您那边有没有其他的环境可以再跑一下看看呢？

**Comment by jeffzhengye** [comment]
> 我这边使用和您一样的配置是可以成功运行的，您看看您那边有没有其他的环境可以再跑一下看看呢？

我有其它纯linux 环境都没问题啊。

你能帮我远程登录调试看下吗？
wx: yezheng

**Comment by ghostxsl** [comment]
是说你在其他linux环境下能跑通？建议可以尝试docker来运行，这样可以保证环境的一致性

**Comment by jeffzhengye** [comment]
> 是说你在其他linux环境下能跑通？建议可以尝试docker来运行，这样可以保证环境的一致性

1. 其它linux 都可以跑通。
2. worker_num: 1 时时没有问题的啊。所以基本环境和数据不该有问题

docker 不也得在wsl2下运行吗？（对docker 不太熟悉啊）

**Comment by jeffzhengye** [comment]
其实还有很多设计错误就是为什么程序抛出的可debug异常要屏蔽掉呢？

报错下面这个错误没有意义啊

SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
[Hint: Expected killed != true, but received killed:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

**Comment by jeffzhengye** [comment]
用wsl2 + docker 也是同样问题。

感觉应该是多进程读取数据有bug，因为1. 单进程训练没有问题； 2. 可以训练10多个epoch，然后随机突然出问题。3. 进程数越少可以训练越多epoch，然后才报错。

**Comment by jeffzhengye** [comment]
以一个意想不到的方式解决了
是cudnn 的问题，cudnn以deb形式安装就没有问题，不要直接解压tar.gz安装包然后拷贝。

以前在纯linux环境（非wsl2 linux），直接解压都没有问题。

**Comment by kaixin-bai** [comment]
> 以一个意想不到的方式解决了 是cudnn 的问题，cudnn以deb形式安装就没有问题，不要直接解压tar.gz安装包然后拷贝。
> 
> 以前在纯linux环境（非wsl2 linux），直接解压都没有问题。

可是这是为什么呀？感觉不应该啊……没有sudo安装不了deb只能tar.gz解压在本地怎么办啊
