### ISSUE TITLE
train.py 放其他目录，不能训练

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleDetection#4897]
PaddleDetection\tools\train.py

train.py 
放其他目录，不能训练
怎么办~

```

Traceback (most recent call last):
  File "f:/PaddleDetection/train.py", line 30, in <module>
    import paddle
  File "E:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\__init__.py", line 25, in <module>
    from .fluid import monkey_patch_variable
  File "E:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\__init__.py", line 45, in <module>
    from . import dataset
  File "E:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dataset.py", line 19, in <module>
    from ..utils import deprecated
  File "E:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\utils\__init__.py", line 27, in <module>
    from . import image_util  # noqa: F401
  File "E:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\utils\image_util.py", line 16, in <module>
    from PIL import Image
  File "f:\PIL\Image.py", line 109, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (f:\PIL\__init__.py)
```

**Comment by wangxinxin08** [comment]
根据报错结果来看应该是PIL的版本太低，可以考虑使用`pip install -U Pillow`升级一下
