### ISSUE TITLE
sparse_rcnn_r50_fpn_3x_pro300_coco 导出模型报错

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleDetection#4916]
` python tools/export_model.py -c configs\sparse_rcnn\sparse_rcnn_r50_fpn_3x_pro300_coco.yml  --output_dir=./inference_model  -o weights=D:\PaddleDetection\output\sparse_rcnn_r50_fpn_3x_pro300_coco\model_final.pdparams`

```

Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
[12/16 15:24:53] ppdet.utils.checkpoint INFO: Finish loading model weights: D:\PaddleDetection\output\sparse_rcnn_r50_fpn_3x_pro300_coco\model_final.pdparams
[12/16 15:24:53] ppdet.engine INFO: Export inference config file to ./inference_model\sparse_rcnn_r50_fpn_3x_pro300_coco\infer_cfg.yml
Traceback (most recent call last):
  File "tools/export_model.py", line 115, in <module>
    main()
  File "tools/export_model.py", line 111, in main
    run(FLAGS, cfg)
  File "tools/export_model.py", line 77, in run
    trainer.export(FLAGS.output_dir)
  File "D:\PaddleDetection\ppdet\engine\trainer.py", line 656, in export
    save_dir)
  File "D:\PaddleDetection\ppdet\engine\trainer.py", line 633, in _get_infer_cfg_and_input_spec
    input_spec, static_model.forward.main_program,
  File "D:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 542, in main_program
    concrete_program = self.concrete_program
  File "D:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 458, in concrete_program
    return self.concrete_program_specify_input_spec(input_spec=None)
  File "D:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 496, in concrete_program_specify_input_spec
    *desired_input_spec)
  File "D:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 406, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "D:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 723, in __getitem__
    self._caches[item] = self._build_once(item)
  File "D:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 714, in _build_once
    **cache_key.kwargs)
  File "D:\anaconda3\envs\PaddleDetection\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "D:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 668, in from_func_spec
    error_data.raise_new_exception()
  File "D:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
KeyError: 'In transformed code:\n\n    File "D:\\PaddleDetection\\ppdet\\modeling\\architectures\\meta_arch.py", line 56, in forward\n\tout = self.get_pred()\n    File "D:\\PaddleDetection\\ppdet\\modeling\\architectures\\sparse_rcnn.py", line 97, in get_pred\n\tbbox_pred, bbox_num = self._forward()\n    File "D:\\PaddleDetection\\ppdet\\modeling\\architectures\\sparse_rcnn.py", line 60, in _forward\n        body_feats = self.backbone(self.inputs)\n        fpn_feats = self.neck(body_feats)\n        head_outs = self.head(fpn_feats, self.inputs["img_whwh"])\n        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE\n\n        if not self.training:\n\n\n    KeyError: \'img_whwh\'\n'
```

**Comment by lyuwenyu** [comment]
这个模型暂时不支持导出
