### ISSUE TITLE
[Other General Issues] ValueError: (InvalidArgument) The variable to insert is NULL.

### ISSUE THREAD

**Issue by moshanshan** [PaddlePaddle/PaddleDetection#4924]
可以普通训练，使用量化训练时报错 paddle=2.2，paddledec=2.3，paddleslim=2.2
python tools/train.py -c configs/ppyolo/ppyolov2_r50vd_dcn_voc.yml --slim_config configs/slim/quant/ppyolov2_r50vd_dcn_qat.yml

Traceback (most recent call last):
  File "tools/train.py", line 171, in <module>
    main()
  File "tools/train.py", line 167, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/media/zn/f/2.3/PaddleDetection/ppdet/engine/trainer.py", line 366, in train
    self._flops(self.loader)
  File "/media/zn/f/2.3/PaddleDetection/ppdet/engine/trainer.py", line 713, in _flops
    flops = flops(self.model, input_spec) / (1000**3)
  File "/home/zn/anaconda3/envs/paddle/lib/python3.7/site-packages/paddleslim/analysis/flops.py", line 133, in dygraph_flops
    program = dygraph2program(model, inputs)
  File "/home/zn/anaconda3/envs/paddle/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/zn/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/zn/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/framework.py", line 229, in __impl__
    return func(*args, **kwargs)
  File "/home/zn/anaconda3/envs/paddle/lib/python3.7/site-packages/paddleslim/core/dygraph.py", line 119, in dygraph2program
    original_outputs = layer(*inputs)
  File "/home/zn/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/media/zn/f/2.3/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 56, in forward
    out = self.get_pred()
  File "/media/zn/f/2.3/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 124, in get_pred
    return self._forward()
  File "/media/zn/f/2.3/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 79, in _forward
    body_feats = self.backbone(self.inputs)
  File "/home/zn/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/media/zn/f/2.3/PaddleDetection/ppdet/modeling/backbones/resnet.py", line 582, in forward
    conv1 = self.conv1(x)
  File "/home/zn/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/zn/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/container.py", line 98, in forward
    input = layer(input)
  File "/home/zn/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/media/zn/f/2.3/PaddleDetection/ppdet/modeling/backbones/resnet.py", line 122, in forward
    out = self.conv(inputs)
  File "/home/zn/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/zn/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/nn/quant/quant_layers.py", line 678, in forward
    out = self._layer(*inputs, **kwargs)
  File "/home/zn/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/zn/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/nn/quant/quant_layers.py", line 460, in forward
    quant_input = self._fake_quant_input(input)
  File "/home/zn/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/zn/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/nn/quant/quant_layers.py", line 192, in forward
    accum, *attrs)
ValueError: (InvalidArgument) The variable to insert is NULL.
  [Hint: new_var should not be null.] (at /paddle/paddle/fluid/imperative/jit/program_desc_tracer.cc:223)

**Comment by yghstill** [comment]
@moshanshan 先将print_flops关闭吧，这个问题我们看下

**Comment by moshanshan** [comment]
非常感谢，print_flops改为false之后就可以了

**Comment by lionelZhaowy** [comment]
请问print_flops在哪里进行修改？
