### ISSUE TITLE
[BUG]AttributeError: 'dict' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by yangrisheng** [PaddlePaddle/PaddleDetection#4947]
Traceback (most recent call last):
  File "tools/train.py", line 171, in <module>
    main()
  File "tools/train.py", line 167, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 118, in run
    trainer = Trainer(cfg, mode='train')
  File "/home/aistudio/work/PaddleDetection/ppdet/engine/trainer.py", line 121, in __init__
    self.optimizer = create('OptimizerBuilder')(self.lr, self.model)
  File "/home/aistudio/work/PaddleDetection/ppdet/optimizer.py", line 269, in __call__
    **optim_args)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/adamw.py", line 145, in __init__
    multi_precision=multi_precision)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/adam.py", line 160, in __init__
    name=name)
  File "<decorator-gen-186>", line 2, in __init__
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 276, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/optimizer.py", line 150, in __init__
    self._dtype = self._parameter_list[0].dtype
AttributeError: 'dict' object has no attribute 'dtype'

我用的是aistudio。然后`!python tools/train.py -c configs/faster_rcnn/faster_rcnn_swin_tiny_fpn_1x_coco.yml --use_vdl=true --vdl_log_dir=vdl_dir/scalar --eval`这是训练命令。数据是由x2coco.py从voc转过来的。这个文件没改啥东西。训练其他的没问题。transformer的这个有问题。

**Comment by yangrisheng** [comment]
最新版本的paddle没有问题。paddle2.2.1.我之前用的paddle2.1.2。
