### ISSUE TITLE
怎样将paddledetection的动态图模型放在脚本文件中运行？

### ISSUE THREAD

**Issue by dawnzhang0** [PaddlePaddle/PaddleDetection#5022]
类似于静态图的模型文件有"__model__","__params__",我可以在脚本文件中使用下面的命令进行运行：
place = fluid.CUDAPlace(0) if train_parameters['use_gpu'] else fluid.CPUPlace()
exe = fluid.Executor(place)
path = "../output/ppyolo"
[inference_program, feed_target_names, fetch_targets] = fluid.io.load_inference_model(dirname=path, executor=exe,
                                                                                      model_filename='__model__',
                                                                                      params_filename='__params__')

但是如果将其中的"__model__","__params__"替换成“.pdmodel”,“.pdiparams”的动态图模型后就会报错：
Traceback (most recent call last):
  File "D:/Users/Administrator/Desktop/Pythonfile/Video_test/workfile/video_img_video.py", line 60, in <module>
    GetObj(images_initial, images_final)
  File "D:/Users/Administrator/Desktop/Pythonfile/Video_test/workfile/video_img_video.py", line 32, in GetObj
    result = a.infer(img_paths, '/%d.jpg' % i)
  File "D:\Users\Administrator\Desktop\Pythonfile\Video_test\workfile\people_det_demo.py", line 121, in infer
    batch_outputs = exe.run(inference_program,
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 1268, in run
    six.reraise(*sys.exc_info())
  File "D:\Anaconda3\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 1256, in run
    return self._run_impl(
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 1466, in _run_impl
    return self._run_program(
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 1544, in _run_program
    program = self._add_feed_fetch_ops(
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 759, in _add_feed_fetch_ops
    if not has_feed_operators(global_block, feed, feed_var_name):
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 281, in has_feed_operators
    raise Exception("'feed_targets' does not have {} variable".
Exception: 'feed_targets' does not have scale_factor variable
这是为什么？

**Comment by dawnzhang0** [comment]
我该怎么在脚本中调用动态图的模型呢

**Comment by EveningLin** [comment]
我也是这个问题 你解决了吗

**Comment by 2018-Summer** [comment]
请问这个问题解决了没有
