### ISSUE TITLE
picoDet量化报错 ValueError: (InvalidArgument) The variable to insert is NULL.

### ISSUE THREAD

**Issue by xiuyangleiasp** [PaddlePaddle/PaddleDetection#5035]
如题，当我使用https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/picodet/README.md
中的命令：python tools/train.py -c configs/picodet/picodet_s_320_coco.yml \
          --slim_config configs/slim/quant/picodet_s_quant.yml --eval
尝试对picodet_s_320_coco量化时，
报如下错误：

/home/lxy/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/tensor/creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Traceback (most recent call last):
  File "/home/lxy/PaddleDetection/tools/train.py", line 171, in <module>
    main()
  File "/home/lxy/PaddleDetection/tools/train.py", line 167, in main
    run(FLAGS, cfg)
  File "/home/lxy/PaddleDetection/tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/home/lxy/PaddleDetection/ppdet/engine/trainer.py", line 366, in train
    self._flops(self.loader)
  File "/home/lxy/PaddleDetection/ppdet/engine/trainer.py", line 714, in _flops
    flops = flops(self.model, input_spec) / (1000**3)
  File "/home/lxy/anaconda3/envs/paddle/lib/python3.9/site-packages/paddleslim/analysis/flops.py", line 133, in dygraph_flops
    program = dygraph2program(model, inputs)
  File "/home/lxy/anaconda3/envs/paddle/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/lxy/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/lxy/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/framework.py", line 229, in __impl__
    return func(*args, **kwargs)
  File "/home/lxy/anaconda3/envs/paddle/lib/python3.9/site-packages/paddleslim/core/dygraph.py", line 120, in dygraph2program
    original_outputs = layer(*inputs)
  File "/home/lxy/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/lxy/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 56, in forward
    out = self.get_pred()
  File "/home/lxy/PaddleDetection/ppdet/modeling/architectures/picodet.py", line 89, in get_pred
    bbox_pred, bbox_num = self._forward()
  File "/home/lxy/PaddleDetection/ppdet/modeling/architectures/picodet.py", line 63, in _forward
    body_feats = self.backbone(self.inputs)
  File "/home/lxy/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/lxy/PaddleDetection/ppdet/modeling/backbones/esnet.py", line 278, in forward
    y = self._conv1(inputs['image'])
  File "/home/lxy/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/lxy/PaddleDetection/ppdet/modeling/backbones/shufflenet_v2.py", line 61, in forward
    y = self._conv(inputs)
  File "/home/lxy/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/lxy/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/nn/quant/quant_layers.py", line 678, in forward
    out = self._layer(*inputs, **kwargs)
  File "/home/lxy/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/lxy/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/nn/quant/quant_layers.py", line 460, in forward
    quant_input = self._fake_quant_input(input)
  File "/home/lxy/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/lxy/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/nn/quant/quant_layers.py", line 190, in forward
    out, _, _, _ = _C_ops.fake_quantize_dequantize_moving_average_abs_max(
ValueError: (InvalidArgument) The variable to insert is NULL.
  [Hint: new_var should not be null.] (at /paddle/paddle/fluid/imperative/jit/program_desc_tracer.cc:223)

其中PaddleSlim是最新版本

**Comment by yghstill** [comment]
@xiuyangleiasp 量化训练PaddlePaddle版本要求2.2以上，你的PaddlePaddle版本是多少？

**Comment by xiuyangleiasp** [comment]
@yghstill 我的paddlepaddle版本是2.2.0

**Comment by yghstill** [comment]
@xiuyangleiasp 我验证了如下环境的picodet量化训练，是正常的，再更新下试试
```shell
>> pip3.7 list|grep paddle
paddlepaddle-gpu    2.2.1
paddleslim          2.2.1
```

**Comment by xiuyangleiasp** [comment]
@yghstill 更新到和你的一样了之后，QAT还是不行
![image](https://user-images.githubusercontent.com/9282338/147736930-7b6a3a28-6ff4-4123-b98a-c885c5d68aa5.png)

不过，刚试验了下，post_quant可以正常运行
我的cuda是10.2 cudnn是7.6

**Comment by yghstill** [comment]
@xiuyangleiasp post_quant离线量化精度有问题，现在还在适配，先用量化训练吧，量化训练可以跑通了吗？

**Comment by xiuyangleiasp** [comment]
@yghstill 重新pull代码后，QAT跑你们官方的picodet模型跑通了，不过跑我自己“魔改”的backbone还是一样的问题。

**Comment by xiuyangleiasp** [comment]
@yghstill hello，我想问下：https://github.com/PaddlePaddle/Paddle/blob/81e702ac835964227bbab0f4ac49ffddb6ff0a6d/python/paddle/nn/quant/quant_layers.py#L179
中的 is_test字段需要在哪里配置？
因为，根据我的debug，用你们官方的模型QAT时，self.training为True，即is_test为False，而用自己魔改的模型，则self.training为false，故我初步怀疑是此问题导致无法量化训练。

**Comment by xiuyangleiasp** [comment]
> 

目前跟踪到，发现QAT是走了了paddle/fluid/dygraph/layers.py中的eval函数，而不是train函数；
但奇怪的是build_slim_model中的mode=="train"

**Comment by xiuyangleiasp** [comment]
@yghstill 问题找到了，将模型配置文件中，将"print_flops:True"字段删除，即可正常QAT；一般而言，打印模型的参数量，不应该影响到模型是“train”模式或者“eval”模式才对。
