### ISSUE TITLE
pp-picodet 模型剪枝训练出错，TypeError: __init__() got an unexpected keyword argument 'local_sparsity'

### ISSUE THREAD

**Issue by LMR2018** [PaddlePaddle/PaddleDetection#5056]
python -m paddle.distributed.launch --log_dir=log_test --gpus 0,1 tools/train.py -c configs/picodet/pruner/picodet_s_320_coco_pruner.yml --slim_config configs/slim/prune/picodet_s_unstructured_prune_75.yml --eval

PaddleSlim==2.2.1
是什么原因？怎么解决这个错误？

```
Traceback (most recent call last):
  File "tools/train.py", line 171, in <module>
    main()
  File "tools/train.py", line 167, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 118, in run
    trainer = Trainer(cfg, mode='train')
  File "/home/alg/ai/PaddleDetection-release-2.3/ppdet/engine/trainer.py", line 125, in __init__
    steps_per_epoch)
  File "/home/alg/ai/PaddleDetection-release-2.3/ppdet/slim/unstructured_prune.py", line 64, in __call__
    configs=configs)
TypeError: __init__() got an unexpected keyword argument 'local_sparsity'
```

**Comment by minghaoBD** [comment]
> python -m paddle.distributed.launch --log_dir=log_test --gpus 0,1 tools/train.py -c configs/picodet/pruner/picodet_s_320_coco_pruner.yml --slim_config configs/slim/prune/picodet_s_unstructured_prune_75.yml --eval
> 
> PaddleSlim==2.2.1 是什么原因？怎么解决这个错误？
> 
> ```
> Traceback (most recent call last):
>   File "tools/train.py", line 171, in <module>
>     main()
>   File "tools/train.py", line 167, in main
>     run(FLAGS, cfg)
>   File "tools/train.py", line 118, in run
>     trainer = Trainer(cfg, mode='train')
>   File "/home/alg/ai/PaddleDetection-release-2.3/ppdet/engine/trainer.py", line 125, in __init__
>     steps_per_epoch)
>   File "/home/alg/ai/PaddleDetection-release-2.3/ppdet/slim/unstructured_prune.py", line 64, in __call__
>     configs=configs)
> TypeError: __init__() got an unexpected keyword argument 'local_sparsity'
> ```

您好，请按以下命令安装develop版本的PaddleSlim。
git clone https://github.com/PaddlePaddle/PaddleSlim
git checkout develop
pip install -r requirements.txt
python setup.py build && python setup.py install

**Comment by LMR2018** [comment]
> > python -m paddle.distributed.launch --log_dir=log_test --gpus 0,1 tools/train.py -c configs/picodet/pruner/picodet_s_320_coco_pruner.yml --slim_config configs/slim/prune/picodet_s_unstructured_prune_75.yml --eval
> > PaddleSlim==2.2.1 是什么原因？怎么解决这个错误？
> > ```
> > Traceback (most recent call last):
> >   File "tools/train.py", line 171, in <module>
> >     main()
> >   File "tools/train.py", line 167, in main
> >     run(FLAGS, cfg)
> >   File "tools/train.py", line 118, in run
> >     trainer = Trainer(cfg, mode='train')
> >   File "/home/alg/ai/PaddleDetection-release-2.3/ppdet/engine/trainer.py", line 125, in __init__
> >     steps_per_epoch)
> >   File "/home/alg/ai/PaddleDetection-release-2.3/ppdet/slim/unstructured_prune.py", line 64, in __call__
> >     configs=configs)
> > TypeError: __init__() got an unexpected keyword argument 'local_sparsity'
> > ```
> 
> 您好，请按以下命令安装develop版本的PaddleSlim。 git clone https://github.com/PaddlePaddle/PaddleSlim git checkout develop pip install -r requirements.txt python setup.py build && python setup.py install


@minghaoBD  你这方法不行啊，出现新的错误
2022-01-05 09:39:34,208-WARNING: load() missing 1 required positional argument: 'Loader'
2022-01-05 09:39:34,208-WARNING: If you want to use training-aware and post-training quantization, please use Paddle >= 1.8.4 or develop version
Traceback (most recent call last):
  File "tools/train.py", line 171, in <module>
    main()
  File "tools/train.py", line 167, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 124, in run
    trainer.load_weights(cfg.pretrain_weights)
  File "/home/alg/ai/PaddleDetection-release-2.3/ppdet/engine/trainer.py", line 315, in load_weights
    load_pretrain_weight(self.model, weights)
  File "/home/alg/ai/PaddleDetection-release-2.3/ppdet/utils/checkpoint.py", line 196, in load_pretrain_weight
    model.set_dict(param_state_dict)
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 281, in wrapper
    return func(*args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 1440, in set_state_dict
    param.set_value(state)
  File "<decorator-gen-127>", line 2, in set_value
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 229, in __impl__
    return func(*args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 174, in set_value
    self.name, self_tensor_np.dtype, value_np.dtype)
AssertionError: Variable dtype not match, Variable [ generated_tensor_8 ] need tensor with dtype float32  but load tensor with dtype bool
INFO 2022-01-05 09:39:45,664 launch_utils.py:340] terminate all the procs
ERROR 2022-01-05 09:39:45,665 launch_utils.py:603] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0, 1] was aborted. Please check its log.
INFO 2022-01-05 09:39:49,669 launch_utils.py:340] terminate all the procs
INFO 2022-01-05 09:39:49,669 launch.py:304] Local processes completed.

**Comment by yghstill** [comment]
@LMR2018 你的PaddlePaddle版本是多少？更新到2.2.1再试下呢

**Comment by LMR2018** [comment]
> @LMR2018 你的PaddlePaddle版本是多少？更新到2.2.1再试下呢

@yghstill   我的版本是paddledet==2.3.0，paddlelite==2.10，paddlepaddle-gpu==2.2.0.post110，
 安照这个方法安装有问题 git clone https://github.com/PaddlePaddle/PaddleSlim
git checkout develop
pip install -r requirements.txt
python setup.py build && python setup.py install

我估计这一步下去，它直接调用的PaddlePaddle不是我本身安装的paddlepaddle-gpu==2.2.0.post110，而是1.0了，因为安装的PaddleSlim==1.0

**Comment by yghstill** [comment]
@LMR2018 不编译安装PaddleSlim，通过下面指定python路径的方式指定最新PaddleSlim路径试试：
```shell
export PYTHONPATH=/path/to/PaddleSlim/:$PYTHONPATH
```

**Comment by minghaoBD** [comment]
@LMR2018 请问安装PaddleSlim有什么问题呢？

另外，PaddleSlim==1.0.0就是develop版本安装成功了，和2.2.0的paddle可以共存。我这边在这个环境下测试了启动命令，可以正常训练。
![image](https://user-images.githubusercontent.com/79566150/148150035-e12ea30e-4bd9-4edc-ab60-4b64b2a21e4d.png)

**Comment by LMR2018** [comment]
> @LMR2018 请问安装PaddleSlim有什么问题呢？
> 
> 另外，PaddleSlim==1.0.0就是develop版本安装成功了，和2.2.0的paddle可以共存。我这边在这个环境下测试了启动命令，可以正常训练。 ![image](https://user-images.githubusercontent.com/79566150/148150035-e12ea30e-4bd9-4edc-ab60-4b64b2a21e4d.png)

@minghaoBD  我按你的方法安装完是这样的，但是就是出现了这个错误
2022-01-05 10:23:14,986-WARNING: load() missing 1 required positional argument: 'Loader'
2022-01-05 10:23:14,986-WARNING: If you want to use training-aware and post-training quantization, please use Paddle >= 1.8.4 or develop version
Traceback (most recent call last):
  File "tools/train.py", line 171, in <module>
    main()
  File "tools/train.py", line 167, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 124, in run
    trainer.load_weights(cfg.pretrain_weights)
  File "/home/alg/ai/PaddleDetection-release-2.3/ppdet/engine/trainer.py", line 315, in load_weights
    load_pretrain_weight(self.model, weights)
  File "/home/alg/ai/PaddleDetection-release-2.3/ppdet/utils/checkpoint.py", line 196, in load_pretrain_weight
    model.set_dict(param_state_dict)
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 281, in wrapper
    return func(*args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 1440, in set_state_dict
    param.set_value(state)
  File "<decorator-gen-127>", line 2, in set_value
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 229, in __impl__
    return func(*args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 174, in set_value
    self.name, self_tensor_np.dtype, value_np.dtype)
AssertionError: Variable dtype not match, Variable [ generated_tensor_8 ] need tensor with dtype float32  but load tensor with dtype bool
![Snipaste_2022-01-05_10-24-26](https://user-images.githubusercontent.com/37955893/148150833-fbd7342f-5d98-42fa-b83a-2c4f9c33254c.png)

**Comment by LMR2018** [comment]
@yghstill   @minghaoBD   我的版本是paddlelite==2.10，paddlepaddle-gpu==2.2.1，
paddleslim==1.0.0，现在可以跑了，之前的错误是因为我改了picodet_s_320_coco_pruner.yml和picodet_s_unstructured_prune_75.yml配置的预训练模型，我将他们改为已经剪枝训练过的模型了

2022-01-05 10:23:14,986-WARNING: load() missing 1 required positional argument: 'Loader'
2022-01-05 10:23:14,986-WARNING: If you want to use training-aware and post-training quantization, please use Paddle >= 1.8.4 or develop version
Traceback (most recent call last):
File "tools/train.py", line 171, in
main()
File "tools/train.py", line 167, in main
run(FLAGS, cfg)
File "tools/train.py", line 124, in run
trainer.load_weights(cfg.pretrain_weights)
File "/home/alg/ai/PaddleDetection-release-2.3/ppdet/engine/trainer.py", line 315, in load_weights
load_pretrain_weight(self.model, weights)
File "/home/alg/ai/PaddleDetection-release-2.3/ppdet/utils/checkpoint.py", line 196, in load_pretrain_weight
model.set_dict(param_state_dict)
File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 281, in wrapper
return func(*args, **kwargs)
File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 1440, in set_state_dict
param.set_value(state)
File "", line 2, in set_value
File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in impl
return wrapped_func(*args, **kwargs)
File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 229, in impl
return func(*args, **kwargs)
File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 174, in set_value
self.name, self_tensor_np.dtype, value_np.dtype)
AssertionError: Variable dtype not match, Variable [ generated_tensor_8 ] need tensor with dtype float32 but load tensor with dtype bool

**Comment by awl-vuong-nguyen** [comment]
@LMR2018 how did you fix it?  
I am evaluating trained model using configs picodet_s_320_voc_yml and slim_config picodet_s_320_unstructured_prune.yml. 
Error: Variable dtype not match, Variable [ generated_tensor_18 ] need tensor with dtype float32  but load tensor with dtype bool

**Comment by minghaoBD** [comment]
@awl-vuong-nguyen
I am fixing this issue in this PR https://github.com/PaddlePaddle/PaddleDetection/pull/5122. 
Thanks for your question about unstructured pruner.

**Comment by awl-vuong-nguyen** [comment]
@LMR2018 Why is the model heavier after pruner. Did I train wrong somewhere?

**Comment by minghaoBD** [comment]
> ```shell
> export PYTHONPATH=/path/to/PaddleSlim/:$PYTHONPATH
> ```

Please open a new issue for further discussion : ) 
I will help you there.

**Comment by minghaoBD** [comment]
> 



> @LMR2018 Why is the model heavier after pruner. Did I train wrong somewhere?

@awl-vuong-nguyen Please open a new issue for further discussion : )
I will help you there.

**Comment by LMR2018** [comment]
> @LMR2018为什么剪枝后模型变重了。我不是在某个地方训练错了？

@awl-vuong-nguyen 我训练的模型也是这样变重了，说是正常的，里面保存了一些权重参数，方便后面继续训练

**Comment by LMR2018** [comment]
> @LMR2018你是怎么解决的？ 我正在使用配置评估测试测试的模型：picodet_s_320_voc.yml 和 slim_config picodet_s_320_unstructured_prune.yml 。

@awl-vuong-nguyen 
请问，你解决了吗？
请按以下命令安装开发版本的PaddleSlim。
git clone https://github.com/PaddlePaddle/PaddleSlim
git checkout develop
pip install -r requirements.txt
python setup.py build && python setup.py install

**Comment by awl-vuong-nguyen** [comment]
@LMR2018 thank you, i solved it

**Comment by nemonameless** [comment]
#5138

**Comment by awl-vuong-nguyen** [comment]
> > @LMR2018 Why does the model get heavier after pruning. Am I training wrong somewhere?
> 
> @awl-vuong-nguyen The model I trained has also become heavier, it is normal, and some weight parameters are saved in it, so that it is convenient to continue training later

so why do we need prune models?
