### ISSUE TITLE
执行python ppdet/modeling/tests/test_architectures.py失败，GFL和PicoDet未注册

### ISSUE THREAD

**Issue by Jiangyangya** [PaddlePaddle/PaddleDetection#5105]
bml@jupyter-54f38f93977838f0-0:~/storage/mnt/v-algorithm/org/jiangyang/PaddleDetection-release-2.3$ python ppdet/modeling/tests/test_architectures.py
W0113 15:16:02.753834    71 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0113 15:16:02.757192    71 device_context.cc:465] device: 0, cuDNN Version: 7.6.
..F.F..
======================================================================
FAIL: test_trainer (__main__.TestGFL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 35, in test_trainer
    trainer = ppdet.engine.Trainer(cfg, mode='test')
  File "/opt/conda/lib/python3.6/site-packages/paddledet-2.0.0-py3.6.egg/ppdet/engine/trainer.py", line 59, in __init__
    self.model = create(cfg.architecture)
  File "/opt/conda/lib/python3.6/site-packages/paddledet-2.0.0-py3.6.egg/ppdet/core/workspace.py", line 216, in create
    "the module {} is not registered".format(name)
AssertionError: the module GFL is not registered

======================================================================
FAIL: test_trainer (__main__.TestPicoDet)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 35, in test_trainer
    trainer = ppdet.engine.Trainer(cfg, mode='test')
  File "/opt/conda/lib/python3.6/site-packages/paddledet-2.0.0-py3.6.egg/ppdet/engine/trainer.py", line 59, in __init__
    self.model = create(cfg.architecture)
  File "/opt/conda/lib/python3.6/site-packages/paddledet-2.0.0-py3.6.egg/ppdet/core/workspace.py", line 216, in create
    "the module {} is not registered".format(name)
AssertionError: the module PicoDet is not registered

----------------------------------------------------------------------
Ran 7 tests in 2.872s

FAILED (failures=2)
之前测试2.1版本是成功的，也可以运行ppocr2.4版本
代码版本2.3，paddle版本2.2.0，cuda10.1，是哪里还需要更新吗？

**Comment by heavengate** [comment]
你是否是pip安装了你paddledet的，可以试下`pip uninstall paddledet`试下，确保你用的是当前目录下的代码

**Comment by Jiangyangya** [comment]
好的谢谢，已经解决了，paddledet版本问题
