### ISSUE TITLE
训练tinypose出现报NAN错误

### ISSUE THREAD

**Issue by mutouoa** [PaddlePaddle/PaddleDetection#5115]
fail to map sample transform [<ppdet.data.transform.keypoint_operators.ToHeatmapsTopDown_DARK object at 0x7f6d3008ff70>] with error: cannot convert float NaN to integer and stack:
Traceback (most recent call last):
  File "/data/qyh/code/keypoints/new/PaddleDetection/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/data/qyh/code/keypoints/new/PaddleDetection/ppdet/data/transform/keypoint_operators.py", line 774, in __call__
    ul = [int(mu_x - tmp_size), int(mu_y - tmp_size)]
ValueError: cannot convert float NaN to integer

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/qinyh/anaconda3/envs/py38/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/qinyh/anaconda3/envs/py38/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/qinyh/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 505, in _thread_loop
    batch = self._get_data()
  File "/home/qinyh/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 634, in _get_data
    batch.reraise()
  File "/home/qinyh/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dataloader/worker.py", line 169, in reraise
    raise self.exc_type(msg)
ValueError: DataLoader worker(0) caught ValueError with message:
Traceback (most recent call last):
  File "/home/qinyh/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dataloader/worker.py", line 329, in _worker_loop
    batch = fetcher.fetch(indices)
  File "/home/qinyh/anaconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dataloader/fetcher.py", line 121, in fetch
    data.append(self.dataset[idx])
  File "/data/qyh/code/keypoints/new/PaddleDetection/ppdet/data/source/keypoint_coco.py", line 384, in __getitem__
    records = self.transform(records)
  File "/data/qyh/code/keypoints/new/PaddleDetection/ppdet/data/reader.py", line 60, in __call__
    raise e
  File "/data/qyh/code/keypoints/new/PaddleDetection/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/data/qyh/code/keypoints/new/PaddleDetection/ppdet/data/transform/keypoint_operators.py", line 774, in __call__
    ul = [int(mu_x - tmp_size), int(mu_y - tmp_size)]
ValueError: cannot convert float NaN to integer

**Comment by mutouoa** [comment]
@ZeyuChen @QingshuChen

**Comment by APeiZou** [comment]
@mutouoa me too , 我也遇到了同样的问题？我是训练了50几个iter之后出现的问题，后来怎么解决的啊？
