### ISSUE TITLE
单卡训练报错RuntimeError: DataLoader 1 workers exit unexpectedly, pids: 5118

### ISSUE THREAD

**Issue by Jiangyangya** [PaddlePaddle/PaddleDetection#5186]
## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/docs/tutorials/FAQ) /I have read the [FAQ documentation](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/docs/tutorials/FAQ) but cannot get the expected help.

## 描述问题/Describe the bug
A clear and concise description of what the bug is.目前使用单卡训练一直会报错..

## 复现/Reproduction

1. 您使用的命令是？
```
单卡
export CUDA_VISIBLE_DEVICES=0
python tools/train.py -c configs/ppyolo/ppyolov2_r50vd_dcn_365e_coco.yml
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。
只修改过数据集文件路径，其他配置采用的默认配置
3. 您使用的数据集是？/What dataset did you use?
数据集使用xcoco转换的coco数据集
4. 请提供您出现的报错信息及相关log。
Traceback (most recent call last):
  File "tools/train.py", line 173, in <module>
    main()
  File "tools/train.py", line 169, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/home/bml/.storage/mnt/v-algorithm/org/jiangyang/PaddleDetection-release-2.3/ppdet/engine/trainer.py", line 381, in train
    for step_id, data in enumerate(self.loader):
  File "/home/bml/.storage/mnt/v-algorithm/org/jiangyang/PaddleDetection-release-2.3/ppdet/data/reader.py", line 209, in __next__
    return next(self.loader)
  File "/opt/conda/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 697, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 583, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/opt/conda/lib/python3.6/multiprocessing/queues.py", line 105, in get
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 505, in _thread_loop
    batch = self._get_data()
  File "/opt/conda/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 599, in _get_data
    "pids: {}".format(len(failed_workers), pids))
RuntimeError: DataLoader 1 workers exit unexpectedly, pids: 5118
## 环境/Environment

paddle版本2.2.1，paddledetection版本2.3，cuda是10.1，cudnn7，之前的安装测试是通过了的

如果您的issue是关于安装或环境，您可以先查询[安装文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)尝试解决~

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL.md

**Comment by Jiangyangya** [comment]
我尝试把数据集数量降低了，worker调为了0，训练到40左右被kill了，不会是资源上的问题吧，之前数据集图片最大是7M的

**Comment by lyuwenyu** [comment]
这个是文档出现的嘛 把config里的share mem注释掉试一下

**Comment by Jiangyangya** [comment]
> 

谢谢，已经解决了，将share mem改成了false

**Comment by AreckOVO** [comment]
> 

这是在哪个文件里修改呀
