### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by whtwhtw** [PaddlePaddle/PaddleDetection#5205]
在自己电脑上训练picodet模型，跟AI studio中完全一样的数据集和命令。开始可用正常训练并每隔10个epoch存一次模型，运行内存在此过程中越用越多（32G系统内存），最后就申请内存申请不到而退出，修改了worker_num少一点也一样到epoch=89的时候出现内存不足。提示如下：
[02/14 10:31:04] ppdet.engine INFO: Eval iter: 100
Traceback (most recent call last):
  File "/media/wht-gpu/F/python_program/PaddlePaddle_models/PaddleCV/PaddleDetection_develop/ppdet/data/reader.py", line 209, in __next__
    return next(self.loader)
  File "/home/wht-gpu/.local/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 609, in __next__
    six.reraise(*sys.exc_info())
  File "/home/wht-gpu/.local/lib/python3.6/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/wht-gpu/.local/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 585, in __next__
    data = self._reader.read_next_var_list()
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/wht-gpu/F/python_program/PaddlePaddle_models/PaddleCV/PaddleDetection_develop/tools/train.py", line 171, in <module>
    main()
  File "/media/wht-gpu/F/python_program/PaddlePaddle_models/PaddleCV/PaddleDetection_develop/tools/train.py", line 167, in main
    run(FLAGS, cfg)
  File "/media/wht-gpu/F/python_program/PaddlePaddle_models/PaddleCV/PaddleDetection_develop/tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/media/wht-gpu/F/python_program/PaddlePaddle_models/PaddleCV/PaddleDetection_develop/ppdet/engine/trainer.py", line 450, in train
    self._eval_with_loader(self._eval_loader)
  File "/media/wht-gpu/F/python_program/PaddlePaddle_models/PaddleCV/PaddleDetection_develop/ppdet/engine/trainer.py", line 466, in _eval_with_loader
    for step_id, data in enumerate(loader):
  File "/media/wht-gpu/F/python_program/PaddlePaddle_models/PaddleCV/PaddleDetection_develop/ppdet/data/reader.py", line 211, in __next__
    self.loader = iter(self.dataloader)
  File "/home/wht-gpu/.local/lib/python3.6/site-packages/paddle/fluid/reader.py", line 426, in __iter__
    return _DataLoaderIterMultiProcess(self)
  File "/home/wht-gpu/.local/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 283, in __init__
    self._init_workers()
  File "/home/wht-gpu/.local/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 327, in _init_workers
    worker.start()
  File "/usr/local/python3.6/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/local/python3.6/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/python3.6/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/python3.6/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/python3.6/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
Exception ignored in: <bound method _DataLoaderIterMultiProcess.__del__ of <paddle.fluid.dataloader.dataloader_iter._DataLoaderIterMultiProcess object at 0x7f9c73760f60>>
Traceback (most recent call last):
  File "/home/wht-gpu/.local/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 566, in __del__
    self._try_shutdown_all()
  File "/home/wht-gpu/.local/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 371, in _try_shutdown_all
    if not self._shutdown:
AttributeError: '_DataLoaderIterMultiProcess' object has no attribute '_shutdown'

**Comment by zoooo0820** [comment]
请问目前paddle及paddle detection的版本分别是多少呢。是否尝试过paddle2.2 + paddledetection 2.3

**Comment by whtwhtw** [comment]
> 请问目前paddle及paddle detection的版本分别是多少呢。是否尝试过paddle2.2 + paddledetection 2.3

用的paddle2.1,改成paddle2.2后问题解决，占用系统内存基本稳定在10G上下，没有再出现内存申请失败的情况。
