### ISSUE TITLE
疑似Dataloader内存溢出

### ISSUE THREAD

**Issue by RockyHoo1209** [PaddlePaddle/PaddleDetection#5233]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/docs/tutorials/FAQ) /I have read the [FAQ documentation](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/docs/tutorials/FAQ) but cannot get the expected help.

## 描述问题/Describe the bug
在使用Dataloader进行batch size划分时，当batchsize>32时(如果不做batch划分，全部数据一次训练没有内存异常),出现报错。

## 复现/Reproduction

```python

BATCH_SIZE=2048
BATCH_NUM=int(len(X_train)/BATCH_SIZE)
dataset=GetDataset(X_train,y_train,BATCH_NUM * BATCH_SIZE)
loader = DataLoader(dataset,
                    batch_size=BATCH_SIZE,
                    shuffle=True,
                    drop_last=True,
                    persistent_workers=True,
                    num_workers=0)

'''以下为单独调用loader测试用的代码，会出现内存占用持续上升,直到内存占用90%后提示noteboook重启'''
for i, (feature, label) in enumerate(loader()):
    print(feature,label)

'''训练代码'''
with fluid.dygraph.guard():
        model = MyDNN()
        model.train()
        max_f1=0
        metric_recall = fluid.metrics.Recall()
        metric_precision=fluid.metrics.Precision()
        lr = fluid.dygraph.ExponentialDecay(learning_rate=0.01,decay_steps=1000,decay_rate=0.5,staircase=True)
        opt = fluid.optimizer.Adam(learning_rate=lr, parameter_list=model.parameters()) 
        epochs_num = 20 #迭代次数
        for pass_num in range(epochs_num):
            for i, (feature, label) in enumerate(loader()):
                with LogWriter(logdir="./log/train_"+str(pass_num)) as writer:
                    # 类型需要统一
                    inputs = fluid.dygraph.to_variable(feature.astype(np.float32))
                    label = fluid.dygraph.to_variable(label.astype(np.int64))
                    test_inputs = fluid.dygraph.to_variable(X_test.values.astype(np.float32))
                    test_label = fluid.dygraph.to_variable(y_test.values.astype(np.int64))
                    y_pred,y_label = model(inputs)
                    test_y_pred,test_y_label=model(test_inputs)
                    loss = fluid.layers.cross_entropy(y_pred, label)
                    test_loss = fluid.layers.cross_entropy(test_y_pred, test_label)
                    avg_loss = fluid.layers.mean(loss) # 获取loss值
                    acc = fluid.layers.accuracy(y_pred, label) # 计算精度
                    metric_recall.update(preds=np.array(y_label.tolist()), labels=np.array(label.tolist()))
                    metric_precision.update(preds=np.array(y_label.tolist()), labels=np.array(label.tolist()))
                    recall=metric_recall.eval()
                    precision=metric_precision.eval()
                    f1=0
                    if precision+recall!=0:
                        f1=(2*precision*recall)/(precision+recall)

                    metric_recall.update(preds=np.array(test_y_label.tolist()), labels=np.array(test_label.tolist()))
                    metric_precision.update(preds=np.array(test_y_label.tolist()), labels=np.array(test_label.tolist()))
                    test_recall=metric_recall.eval()
                    test_precision=metric_precision.eval()
                    test_f1=0
                    if test_precision+test_recall!=0:
                        test_f1=(2*test_precision*test_recall)/(test_precision+test_recall)


                    test_avg_loss = fluid.layers.mean(test_loss) # 获取loss值
                    test_acc = fluid.layers.accuracy(test_y_pred, test_label) # 计
                    # auc = fluid.layers.auc(input=y_pred, label=label)
                    # 向记录器添加一个tag为`acc`的数据
                    writer.add_scalar(tag="acc", step=i, value=acc)
                    # 向记录器添加一个tag为`loss`的数据
                    writer.add_scalar(tag="loss", step=i, value=avg_loss)
                    writer.add_scalar(tag="test_acc", step=i, value=test_acc)
                    # 向记录器添加一个tag为`loss`的数据
                    writer.add_scalar(tag="test_loss", step=i, value=test_avg_loss)
                    writer.add_scalar(tag="test_f1",step=i,value=test_f1)
                    writer.add_scalar(tag="f1",step=i,value=f1)
                    avg_loss.backward()       
                    opt.minimize(avg_loss)    # 优化器对象的minimize方法对参数进行更新 
                    model.clear_gradients()   # model.clear_gradients()来重置梯度

                    if i % 20 == 0:
                        print("epoch:{},train_loss:{},train_acc:{},test_acc:{},test_loss:{},lr:{},f1:{},test_f1：{}".format(i,avg_loss.numpy(),acc.numpy(),test_acc.numpy(),test_avg_loss.numpy(),opt.current_step_lr(),f1,test_f1))
                    if test_f1>max_f1:
                        max_f1=test_f1
                        fluid.save_dygraph(model.state_dict(),'MyDNN2')#保存模型

```none
请填写命令/A placeholder for the command.
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.
否

3. 您使用的数据集是？/What dataset did you use?

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.
Exception in thread Thread-8:

```shell
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 583, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 505, in _thread_loop
    batch = self._get_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 599, in _get_data
    "pids: {}".format(len(failed_workers), pids))
RuntimeError: DataLoader 1 workers exit unexpectedly, pids: 317

---------------------------------------------------------------------------
SystemError                               Traceback (most recent call last)
/tmp/ipykernel_190/1273691028.py in <module>
      9         epochs_num = 20 #迭代次数
     10         for pass_num in range(epochs_num):
---> 11             for i, (feature, label) in enumerate(loader()):
     12                 with LogWriter(logdir="./log/train_"+str(pass_num)) as writer:
     13                     # 类型需要统一

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py in __next__(self)
    695 
    696             if in_dygraph_mode():
--> 697                 data = self._reader.read_next_var_list()
    698                 data = _restore_batch(data, self._structure_infos.pop(0))
    699             else:

SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166


## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
ai studio 32G版本

**Comment by nemonameless** [comment]
paddle版本具体是什么呢？建议使用paddle官网默认的动态图版本，https://www.paddlepaddle.org.cn/install/quick/zh/2.0rc-linux-source?docurl=/documentation/docs/zh/install/pip/linux-pip.html

**Comment by RockyHoo1209** [comment]
> 

paddle 2.2.2的版本

**Comment by RockyHoo1209** [comment]
没有人看看吗/(ㄒoㄒ)/~~

**Comment by ericCHxia** [comment]
![image](https://user-images.githubusercontent.com/52739449/163656898-3e7b6150-773b-43af-bff6-a24a1d6a0e63.png)

这就离谱我刚开始训练7G内存训练13个EPOCH后上升到了22G
