### ISSUE TITLE
数据集加载错误，paddlepaddle==2.2.2，paddledetection==2.3，能看一下是什么问题吗

### ISSUE THREAD

**Issue by czyczyczy** [PaddlePaddle/PaddleDetection#5245]
Traceback (most recent call last):
  File "/home/chenziyi/miniconda3/envs/paddle_env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/chenziyi/miniconda3/envs/paddle_env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chenziyi/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 536, in _thread_loop
    six.reraise(*sys.exc_info())
  File "/home/chenziyi/miniconda3/envs/paddle_env/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/chenziyi/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 528, in _thread_loop
    tmp.set(slot, core.CPUPlace())
ValueError: (InvalidArgument) Input object type error or incompatible array data type. tensor.set() supports array with bool, float16, float32, float64, int8, int16, int32, int64, uint8 or uint16, please check your input or input array data type. (at /paddle/paddle/fluid/pybind/tensor_py.h:411)

[02/22 17:12:23] ppdet.utils.checkpoint INFO: ['_fc.bias', '_fc.weight', '_last_conv._batch_norm._mean', '_last_conv._batch_norm._variance', '_last_conv._batch_norm.bias', '_last_conv._batch_norm.weight', '_last_conv._conv.weight', 'last_conv.weight'] in pretrained weight is not used in the model, and its will not be loaded
[02/22 17:12:23] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/chenziyi/.cache/paddle/weights/ESNet_x0_75_pretrained.pdparams
Traceback (most recent call last):
  File "tools/train.py", line 177, in <module>
    main()
  File "tools/train.py", line 173, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/home/chenziyi/PaddleDetection/ppdet/engine/trainer.py", line 381, in train
    for step_id, data in enumerate(self.loader):
  File "/home/chenziyi/PaddleDetection/ppdet/data/reader.py", line 209, in __next__
    return next(self.loader)
  File "/home/chenziyi/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 697, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

**Comment by ghostxsl** [comment]
您是训练的什么模型？加载的什么数据集？

**Comment by czyczyczy** [comment]
> 您是训练的什么模型？加载的什么数据集？

模型是picodet，数据集是COCO格式的

**Comment by zhiboniu** [comment]
是自己的数据做成coco格式吗？检查一下数据类型对不对。
ValueError: (InvalidArgument) Input object type error or incompatible array data type. tensor.set() supports array with bool, float16, float32, float64, int8, int16, int32, int64, uint8 or uint16, please check your input or input array data type
