### ISSUE TITLE
训练过程中总是突然停掉吗，已经试了很多次。fail to map batch transform [Gt2YoloTarget_6a0f3f]

### ISSUE THREAD

**Issue by xk503775229** [PaddlePaddle/PaddleDetection#5269]
请问这是因为什么呢？报错信息如下：

版本2.3。自建coco类型数据

03/01 00:34:35] ppdet.engine INFO: Epoch: [5] [ 440/2964] learning_rate: 0.002500 loss_xy: 8.643393 loss_wh: 9.077515 loss_iou: 35.186317 loss_iou_aware: 6.146228 loss_obj: 47.617775 loss_cls: 12.512911 loss: 119.323303 eta: 3 days, 18:31:23 batch_cost: 1.0464 data_cost: 0.4236 ips: 15.2905 images/s
[03/01 00:34:54] reader WARNING: fail to map batch transform [Gt2YoloTarget_6a0f3f] with error: index 96 is out of bounds for axis 3 with size 96 and stack:
Traceback (most recent call last):
  File "/home/xiaokang/projectCode/OCR/PaddleDetection/ppdet/data/reader.py", line 209, in __next__
    return next(self.loader)
  File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 589, in __next__
    six.reraise(*sys.exc_info())
  File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 565, in __next__
    data = self._reader.read_next_var_list()
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xiaokang/projectCode/OCR/PaddleDetection/ppdet/data/reader.py", line 73, in __call__
    data = f(data)
  File "/home/xiaokang/projectCode/OCR/PaddleDetection/ppdet/data/transform/batch_operators.py", line 232, in __call__
    target[best_n, 0, gj, gi] = gx * grid_w - gi
IndexError: index 96 is out of bounds for axis 3 with size 96

ERROR:root:DataLoader reader thread raised an exception!
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 391, in _thread_loop
    batch = self._get_data()
  File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 505, in _get_data
    batch.reraise()
  File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 168, in reraise
    raise self.exc_type(msg)
IndexError: DataLoader worker(3) caught IndexError with message:
Traceback (most recent call last):
  File "/home/xiaokang/projectCode/OCR/PaddleDetection/ppdet/data/reader.py", line 209, in __next__
    return next(self.loader)
  File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 589, in __next__
    six.reraise(*sys.exc_info())
  File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 565, in __next__
    data = self._reader.read_next_var_list()
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 320, in _worker_loop
    batch = fetcher.fetch(indices)
  File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 117, in fetch
    data = self.collate_fn(data)
  File "/home/xiaokang/projectCode/OCR/PaddleDetection/ppdet/data/reader.py", line 79, in __call__
    raise e
  File "/home/xiaokang/projectCode/OCR/PaddleDetection/ppdet/data/reader.py", line 73, in __call__
    data = f(data)
  File "/home/xiaokang/projectCode/OCR/PaddleDetection/ppdet/data/transform/batch_operators.py", line 232, in __call__
    target[best_n, 0, gj, gi] = gx * grid_w - gi
IndexError: index 96 is out of bounds for axis 3 with size 96

Traceback (most recent call last):
  File "tools/train.py", line 177, in <module>
    main()
  File "tools/train.py", line 173, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/home/xiaokang/projectCode/OCR/PaddleDetection/ppdet/engine/trainer.py", line 381, in train
    for step_id, data in enumerate(self.loader):
  File "/home/xiaokang/projectCode/OCR/PaddleDetection/ppdet/data/reader.py", line 209, in __next__
    return next(self.loader)
  File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 565, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

**Comment by yghstill** [comment]
@xk503775229 根据报错：
```shell
File "/home/xiaokang/projectCode/OCR/PaddleDetection/ppdet/data/transform/batch_operators.py", line 232, in call
target[best_n, 0, gj, gi] = gx * grid_w - gi
IndexError: index 96 is out of bounds for axis 3 with size 96
```
在报错位置附近打印下log，排查下coco数据的gt信息是否有误

**Comment by xk503775229** [comment]
> @xk503775229 根据报错：
> 
> ```shell
> File "/home/xiaokang/projectCode/OCR/PaddleDetection/ppdet/data/transform/batch_operators.py", line 232, in call
> target[best_n, 0, gj, gi] = gx * grid_w - gi
> IndexError: index 96 is out of bounds for axis 3 with size 96
> ```
> 
> 在报错位置附近打印下log，排查下coco数据的gt信息是否有误

好的，我检查下。

**Comment by xk503775229** [comment]
> @xk503775229 根据报错：
> 
> ```shell
> File "/home/xiaokang/projectCode/OCR/PaddleDetection/ppdet/data/transform/batch_operators.py", line 232, in call
> target[best_n, 0, gj, gi] = gx * grid_w - gi
> IndexError: index 96 is out of bounds for axis 3 with size 96
> ```
> 
> 在报错位置附近打印下log，排查下coco数据的gt信息是否有误

你好，训练了多轮后出现这个错误，也是数据的问题嘛？大概再Epoch: [14]的时候又跳出了这个错误。出现这样的错误，是否主要是BBox的边界问题？

**Comment by gg22mm** [comment]
> 请问这是因为什么呢？报错信息如下：
> 
> 版本2.3。自建coco类型数据
> 
> 03/01 00:34:35] ppdet.engine INFO: Epoch: [5] [ 440/2964] learning_rate: 0.002500 loss_xy: 8.643393 loss_wh: 9.077515 loss_iou: 35.186317 loss_iou_aware: 6.146228 loss_obj: 47.617775 loss_cls: 12.512911 loss: 119.323303 eta: 3 days, 18:31:23 batch_cost: 1.0464 data_cost: 0.4236 ips: 15.2905 images/s [03/01 00:34:54] reader WARNING: fail to map batch transform [Gt2YoloTarget_6a0f3f] with error: index 96 is out of bounds for axis 3 with size 96 and stack: Traceback (most recent call last): File "/home/xiaokang/projectCode/OCR/PaddleDetection/ppdet/data/reader.py", line 209, in **next** return next(self.loader) File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 589, in **next** six.reraise(*sys.exc_info()) File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/six.py", line 719, in reraise raise value File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 565, in **next** data = self._reader.read_next_var_list() StopIteration
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/xiaokang/projectCode/OCR/PaddleDetection/ppdet/data/reader.py", line 73, in **call** data = f(data) File "/home/xiaokang/projectCode/OCR/PaddleDetection/ppdet/data/transform/batch_operators.py", line 232, in **call** target[best_n, 0, gj, gi] = gx * grid_w - gi IndexError: index 96 is out of bounds for axis 3 with size 96
> 
> ERROR:root:DataLoader reader thread raised an exception! Exception in thread Thread-6: Traceback (most recent call last): File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/threading.py", line 926, in _bootstrap_inner self.run() File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/threading.py", line 870, in run self._target(*self._args, **self._kwargs) File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 391, in _thread_loop batch = self._get_data() File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 505, in _get_data batch.reraise() File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 168, in reraise raise self.exc_type(msg) IndexError: DataLoader worker(3) caught IndexError with message: Traceback (most recent call last): File "/home/xiaokang/projectCode/OCR/PaddleDetection/ppdet/data/reader.py", line 209, in **next** return next(self.loader) File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 589, in **next** six.reraise(*sys.exc_info()) File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/six.py", line 719, in reraise raise value File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 565, in **next** data = self._reader.read_next_var_list() StopIteration
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 320, in _worker_loop batch = fetcher.fetch(indices) File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 117, in fetch data = self.collate_fn(data) File "/home/xiaokang/projectCode/OCR/PaddleDetection/ppdet/data/reader.py", line 79, in **call** raise e File "/home/xiaokang/projectCode/OCR/PaddleDetection/ppdet/data/reader.py", line 73, in **call** data = f(data) File "/home/xiaokang/projectCode/OCR/PaddleDetection/ppdet/data/transform/batch_operators.py", line 232, in **call** target[best_n, 0, gj, gi] = gx * grid_w - gi IndexError: index 96 is out of bounds for axis 3 with size 96
> 
> Traceback (most recent call last): File "tools/train.py", line 177, in main() File "tools/train.py", line 173, in main run(FLAGS, cfg) File "tools/train.py", line 127, in run trainer.train(FLAGS.eval) File "/home/xiaokang/projectCode/OCR/PaddleDetection/ppdet/engine/trainer.py", line 381, in train for step_id, data in enumerate(self.loader): File "/home/xiaokang/projectCode/OCR/PaddleDetection/ppdet/data/reader.py", line 209, in **next** return next(self.loader) File "/home/xiaokang/miniconda3/envs/OCR/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 565, in **next** data = self._reader.read_next_var_list() SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception. [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

应该是：configs/*/*.yml 中的 '../datasets/voc_***.yml',  中的分类数不对:  IndexError: index 96 is out of bounds for axis 3 with size 96   ，应该是根据： ./dataset/*/labels.txt 看人分类数来定的，从1开始数
