### ISSUE TITLE
[Other General Issues]单机多卡训练中突然报错并停止运行

### ISSUE THREAD

**Issue by gaorui999** [PaddlePaddle/PaddleDetection#5302]
（1）使用版本：Python：3.7；Paddle：2.2.2；PaddleDetection：devolop分支
（2）问题描述：在AIStudio平台使用单机多卡的方式运行cascade_rcnn模型时，突然报错并停止运行，除数据集外均使用默认参数
    os.system("cd paddle-detection1125-develop && python -m paddle.distributed.launch  tools/train.py -c configs/cascade_rcnn/cascade_rcnn_r50_vd_fpn_ssld_2x_coco.yml --eval --use_vdl=True --vdl_log_dir='./output_vdl'")

（3）报错内容：
```
[03/04 16:28:22] ppdet.engine INFO: Epoch: [0] [ 449/4839] learning_rate: 0.005041 loss_rpn_cls: 0.047363 loss_rpn_reg: 0.013439 loss_bbox_cls_stage0: 0.037025 loss_bbox_reg_stage0: 0.030165 loss_bbox_cls_stage1: 0.018077 loss_bbox_reg_stage1: 0.003935 loss_bbox_cls_stage2: 0.003636 loss_bbox_reg_stage2: 0.000000 loss: 0.153642 eta: 7:07:54 batch_cost: 0.1470 data_cost: 0.0003 ips: 6.8020 images/s
Traceback (most recent call last):
  File "tools/train.py", line 177, in <module>
    main()
  File "tools/train.py", line 173, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/root/paddlejob/workspace/code/paddle-detection1125-develop/ppdet/engine/trainer.py", line 417, in train
    outputs = model(data)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/parallel.py", line 708, in forward
    list(self._find_varbase(outputs)))
RuntimeError: (PreconditionNotMet) A serious error has occurred here. Please set find_unused_parameters=True to traverse backward graph in each step to prepare reduce in advance. If you have set, There may be several reasons for this error: 1) Please note that all forward outputs derived from the module parameters must participate in the calculation of losses and subsequent gradient calculations. If not, the wrapper will hang, waiting for autograd to generate gradients for these parameters. you can use detach or stop_gradient to make the unused parameters detached from the autograd graph. 2) Used multiple forwards and one backward. You may be able to wrap multiple forwards in a model.
INFO 2022-03-04 16:28:27,142 launch_utils.py:320] terminate process group gid:658
INFO 2022-03-04 16:28:27,142 launch_utils.py:320] terminate process group gid:664
INFO 2022-03-04 16:28:31,147 launch_utils.py:341] terminate all the procs
ERROR 2022-03-04 16:28:31,148 launch_utils.py:604] ABORT!!! Out of all 4 trainers, the trainer process with rank=[0, 2] was aborted. Please check its log.
INFO 2022-03-04 16:28:35,152 launch_utils.py:341] terminate all the procs
INFO 2022-03-04 16:28:35,152 launch.py:311] Local processes completed.
  [Hint: Expected groups_need_finalize_ == false, but received groups_need_finalize_:1 != false:0.] (at /paddle/paddle/fluid/imperative/reducer.cc:573)

```

**Comment by ghostxsl** [comment]
看着像是环境的问题，我稍后在自己的开发机上复现一下看看～

**Comment by gaorui999** [comment]
可以麻烦帮我看下吗？

**Comment by wstchhwp** [comment]
怎么解决的？

**Comment by ZhiXianZ** [comment]
你们可以这个问题排查出来了吗

**Comment by lyuwenyu** [comment]
在config里加上 `find_unused_parameters: True`
