### ISSUE TITLE
[Other General Issues]训练自己VOC格式数据出错

### ISSUE THREAD

**Issue by kingkingofall** [PaddlePaddle/PaddleDetection#5308]
数据的目录
dataset
-mydata
--JPEGImages
--Annotations
-train.txt
-val.txt
-label_list.txt

运行训练脚本会报错
ValueError: invalid literal for int() with base 10: 'Unspecified'

**Comment by kingkingofall** [comment]
完整报错
Traceback (most recent call last):
  File "tools/train.py", line 177, in <module>
    main()
  File "tools/train.py", line 173, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 118, in run
    trainer = Trainer(cfg, mode='train')
  File "/content/PaddleDetection/ppdet/engine/trainer.py", line 77, in __init__
    self.dataset, cfg.worker_num)
  File "/content/PaddleDetection/ppdet/data/reader.py", line 163, in __call__
    self.dataset.parse_dataset()
  File "/content/PaddleDetection/ppdet/data/source/voc.py", line 146, in parse_dataset
    _difficult.text) if _difficult is not None else 0
ValueError: invalid literal for int() with base 10: 'Unspecified'

**Comment by zhiboniu** [comment]
看起来像是数据格式有问题，你在出错行前面打印一下相关内容呢

**Comment by kingkingofall** [comment]
我把PaddleDetection/ppdet/data/source/voc.py中识别difficult字段的代码都注释了，然后就可以跑了，这是什么原因
