### ISSUE TITLE
剪枝打印模型参数时候报错ValueError: Module class already registered: Pruner

### ISSUE THREAD

**Issue by cv-nlp** [PaddlePaddle/PaddleDetection#5316]
```
ject` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Traceback (most recent call last):
  File "prune.py", line 37, in <module>
    class Pruner(object):
  File "/data/xxx/conda/envs/ppdetection/lib/python3.8/site-packages/ppdet/core/workspace.py", line 193, in register
    raise ValueError("Module class already registered: {}".format(
ValueError: Module class already registered: Pruner
```

**Comment by yghstill** [comment]
@cv-nlp 运行指令可以发下吗？

**Comment by cv-nlp** [comment]
> @cv-nlp 运行指令可以发下吗？

python prune.py \
-c ../../configs/yolov3_mobilenet_v1_voc.yml \
--print_params
这个剪枝的命令

**Comment by yghstill** [comment]
@cv-nlp 请更新代码到最新release/2.3。同时，运行时在PaddleDetection/static的根目录，执行：
```shell
python slim/prune/prune.py \
-c ./configs/yolov3_mobilenet_v1_voc.yml \
--print_params
```
