### ISSUE TITLE
[BUG]module 'numpy.random' has no attribute 'BitGenerator'

### ISSUE THREAD

**Issue by Jaren-Li** [PaddlePaddle/PaddleDetection#5356]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://paddledetection.readthedocs.io/FAQ.html) /I have read the [FAQ documentation](https://paddledetection.readthedocs.io/FAQ.html) but cannot get the expected help.
3. 确认bug是否在新版本里还未修复/The bug has not been fixed in the latest version.

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?

```none
python tools/train.py -c configs/picodet/picodet_s_320_coco.yml --eval
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.
我这边之前碰到了'numpy.float64' object cannot be interpreted as an integer这个错误，我根据issue上面的提示，把numpy版本降为1.17.4，关掉eval后，模型训练出来了，但是在导出onnx的时候报出错误

3. 您使用的数据集是？/What dataset did you use?

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.
Traceback (most recent call last):
  File "tools/train.py", line 32, in <module>
    from ppdet.core.workspace import load_config, merge_config
  File "E:\DataSet\PaddleDetection-release-2.3\ppdet\__init__.py", line 15, in <module>
    from . import (core, data, engine, modeling, model_zoo, optimizer, metrics,
  File "E:\DataSet\PaddleDetection-release-2.3\ppdet\engine\__init__.py", line 15, in <module>
    from . import trainer
  File "E:\DataSet\PaddleDetection-release-2.3\ppdet\engine\trainer.py", line 38, in <module>
    from ppdet.metrics import Metric, COCOMetric, VOCMetric, WiderFaceMetric, get_infer_results, KeyPointTopDownCOCOEval, KeyPointTopDownMPIIEval
  File "E:\DataSet\PaddleDetection-release-2.3\ppdet\metrics\__init__.py", line 27, in <module>
    from . import mcmot_metrics
  File "E:\DataSet\PaddleDetection-release-2.3\ppdet\metrics\mcmot_metrics.py", line 24, in <module>
    from motmetrics.math_util import quiet_divide
  File "E:\anaconda\envs\openvino\lib\site-packages\motmetrics\__init__.py", line 28, in <module>
    from motmetrics import io
  File "E:\anaconda\envs\openvino\lib\site-packages\motmetrics\io.py", line 18, in <module>
    import pandas as pd
  File "E:\anaconda\envs\openvino\lib\site-packages\pandas\__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev
  File "E:\anaconda\envs\openvino\lib\site-packages\pandas\compat\__init__.py", line 14, in <module>
    from pandas._typing import F
  File "E:\anaconda\envs\openvino\lib\site-packages\pandas\_typing.py", line 120, in <module>
    np.random.BitGenerator,
AttributeError: module 'numpy.random' has no attribute 'BitGenerator'

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
paddlepaddle-gpu==2.2.2

2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：
win10
4. 请问您使用的Python版本是？/ Please provide the version of Python you used.
python3.8
5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.
cuda = 10.2

如果您的issue是关于安装或环境，您可以先查询[安装文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)尝试解决~

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL.md

我这边不太清楚是不是因为自己的配置上的一些问题，但我是根据paddle文档的指令去进行安装的

**Comment by Jaren-Li** [comment]
emmm，解决了，应该是numpy库那边的错误
我的解决办法是在“”File "E:\anaconda\envs\openvino\lib\site-packages\pandas\_typing.py", 这个文件里添加
`import numpy`
`numpy.random.bit_generator = numpy.random._bit_generator`
即可解决问题，--eval就可以使用了
