### ISSUE TITLE
[Other General Issues]

### ISSUE THREAD

**Issue by OrangeAILab** [PaddlePaddle/PaddleDetection#5416]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/docs/tutorials/FAQ) /I have read the [FAQ documentation](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/docs/tutorials/FAQ) but cannot get the expected help.

## 描述问题/Describe the bug
使用PaddleDetection的PPYOLO训练报错'ascii' codec can't decode byte 0xef in position 133: ordinal not in range(128)**
(PaddlePaddle) [user@ PaddleDetection-release-2.3]$ python tools/train.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml\
                        --use_vdl=true \
                        --vdl_log_dir=ppyolo \
                        --eval
Traceback (most recent call last):
  File "tools/train.py", line 177, in <module>
    main()
  File "tools/train.py", line 132, in main
    cfg = load_config(FLAGS.config)
  File "/home/PaddleDetection-release-2.3/ppdet/core/workspace.py", line 114, in load_config
    cfg = _load_config_with_base(file_path)
  File "/home/PaddleDetection-release-2.3/ppdet/core/workspace.py", line 92, in _load_config_with_base
    base_cfg = _load_config_with_base(base_yml)
  File "/home/PaddleDetection-release-2.3/ppdet/core/workspace.py", line 79, in _load_config_with_base
    file_cfg = yaml.load(f, Loader=yaml.Loader)
  File "/home/.conda/envs/PaddlePaddle/lib/python3.6/site-packages/yaml/__init__.py", line 79, in load
    loader = Loader(stream)
  File "/home/.conda/envs/PaddlePaddle/lib/python3.6/site-packages/yaml/loader.py", line 44, in __init__
    Reader.__init__(self, stream)
  File "/home/.conda/envs/PaddlePaddle/lib/python3.6/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/home/.conda/envs/PaddlePaddle/lib/python3.6/site-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/home/.conda/envs/PaddlePaddle/lib/python3.6/site-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "/home/.conda/envs/PaddlePaddle/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
**UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 133: ordinal not in range(128)**

**Comment by wangxinxin08** [comment]
报错原因是yaml无法读取配置文件，可能的问题是pyyaml版本太低或者yaml文件有问题
