### ISSUE TITLE
[Other General Issues] 运行指令报错！

### ISSUE THREAD

**Issue by 19920716** [PaddlePaddle/PaddleDetection#5420]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/docs/tutorials/FAQ) /I have read the [FAQ documentation](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/docs/tutorials/FAQ) but cannot get the expected help.

## 描述问题/Describe the bug

CPU执行这个命令没有问题，GPU执行卡很久报错。

(venv) D:\Python_Projects\PaddleSpeech>paddlespeech tts --input "你好，欢迎使用飞桨输出深度学习框架！" --output output.wav
phones_dict: None
[2022-03-22 10:23:29,025] [    INFO] - File C:\Users\admin\.paddlespeech\models\fastspeech2_csmsc-zh\fastspeech2_nosil_baker_ckpt_0.4.zip md5 checking...
[2022-03-22 10:23:29,757] [    INFO] - Use pretrained model stored in: C:\Users\admin\.paddlespeech\models\fastspeech2_csmsc-zh\fastspeech2_nosil_baker_ckpt_0.4
self.phones_dict: C:\Users\admin\.paddlespeech\models\fastspeech2_csmsc-zh\fastspeech2_nosil_baker_ckpt_0.4\phone_id_map.txt
[2022-03-22 10:23:29,757] [    INFO] - C:\Users\admin\.paddlespeech\models\fastspeech2_csmsc-zh\fastspeech2_nosil_baker_ckpt_0.4
[2022-03-22 10:23:29,758] [    INFO] - C:\Users\admin\.paddlespeech\models\fastspeech2_csmsc-zh\fastspeech2_nosil_baker_ckpt_0.4\default.yaml
[2022-03-22 10:23:29,758] [    INFO] - C:\Users\admin\.paddlespeech\models\fastspeech2_csmsc-zh\fastspeech2_nosil_baker_ckpt_0.4\snapshot_iter_76000.pdz
self.phones_dict: C:\Users\admin\.paddlespeech\models\fastspeech2_csmsc-zh\fastspeech2_nosil_baker_ckpt_0.4\phone_id_map.txt
[2022-03-22 10:23:29,758] [    INFO] - File C:\Users\admin\.paddlespeech\models\pwgan_csmsc-zh\pwg_baker_ckpt_0.4.zip md5 checking...
[2022-03-22 10:23:29,783] [    INFO] - Use pretrained model stored in: C:\Users\admin\.paddlespeech\models\pwgan_csmsc-zh\pwg_baker_ckpt_0.4
[2022-03-22 10:23:29,783] [    INFO] - C:\Users\admin\.paddlespeech\models\pwgan_csmsc-zh\pwg_baker_ckpt_0.4
[2022-03-22 10:23:29,783] [    INFO] - C:\Users\admin\.paddlespeech\models\pwgan_csmsc-zh\pwg_baker_ckpt_0.4\pwg_default.yaml
[2022-03-22 10:23:29,783] [    INFO] - C:\Users\admin\.paddlespeech\models\pwgan_csmsc-zh\pwg_baker_ckpt_0.4\pwg_snapshot_iter_400000.pdz
vocab_size: 268
frontend done!
W0322 10:23:29.825428  2452 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 10.2
W0322 10:23:29.842411  2452 device_context.cc:465] device: 0, cuDNN Version: 7.6.
[2022-03-22 10:38:59,456] [   ERROR] - (Fatal) Operator uniform_random raises an class thrust::system::system_error exception.
The exception content is
:parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device. (at ..\paddle\fluid\imperative\tracer.cc:221)
Traceback (most recent call last):
  File "d:\python_projects\paddlespeech\venv\lib\site-packages\paddlespeech\cli\tts\infer.py", line 623, in execute
    res = self(
  File "d:\python_projects\paddlespeech\venv\lib\site-packages\paddlespeech\cli\utils.py", line 335, in _warpper
    return executor_func(self, *args, **kwargs)
  File "d:\python_projects\paddlespeech\venv\lib\site-packages\paddlespeech\cli\tts\infer.py", line 671, in __call__
    self._init_from_path(
  File "d:\python_projects\paddlespeech\venv\lib\site-packages\paddlespeech\cli\tts\infer.py", line 481, in _init_from_path
    am = am_class(
  File "d:\python_projects\paddlespeech\venv\lib\site-packages\paddlespeech\t2s\models\fastspeech2\fastspeech2.py", line 306, in __init__
    encoder_input_layer = nn.Embedding(
  File "d:\python_projects\paddlespeech\venv\lib\site-packages\paddle\nn\layer\common.py", line 1386, in __init__
    self.weight = self.create_parameter(
  File "d:\python_projects\paddlespeech\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 421, in create_parameter
    return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
  File "d:\python_projects\paddlespeech\venv\lib\site-packages\paddle\fluid\layer_helper_base.py", line 373, in create_parameter
    return self.main_program.global_block().create_parameter(
  File "d:\python_projects\paddlespeech\venv\lib\site-packages\paddle\fluid\framework.py", line 3137, in create_parameter
    initializer(param, self)
  File "d:\python_projects\paddlespeech\venv\lib\site-packages\paddle\fluid\initializer.py", line 557, in __call__
    op = block.append_op(
  File "d:\python_projects\paddlespeech\venv\lib\site-packages\paddle\fluid\framework.py", line 3163, in append_op
    _dygraph_tracer().trace_op(type,
  File "d:\python_projects\paddlespeech\venv\lib\site-packages\paddle\fluid\dygraph\tracer.py", line 43, in trace_op
    self.trace(type, inputs, outputs, attrs,
SystemError: (Fatal) Operator uniform_random raises an class thrust::system::system_error exception.
The exception content is
:parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device. (at ..\paddle\fluid\imperative\tracer.cc:221)

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?
  paddlespeech tts --input "你好，欢迎使用飞桨输出深度学习框架！" --output output.wav

```none
请填写命令/A placeholder for the command.
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.

3. 您使用的数据集是？/What dataset did you use?

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
   
2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：
   Windows 10 企业版本 操作系统内核 19042.1586    RTX 3080显卡
4. 请问您使用的Python版本是？/ Please provide the version of Python you used.
   Python 3.9
5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.
   CUDA 10.2  + cudnn-10.2-windows10-x64-v7.6.5.32

如果您的issue是关于安装或环境，您可以先查询[安装文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)尝试解决~

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL.md

**Comment by lyuwenyu** [comment]
paddle版本是什么
