### ISSUE TITLE
Faster-RCNN 导出模型进行推理时有关shape错误

### ISSUE THREAD

**Issue by Rhett98** [PaddlePaddle/PaddleDetection#5482]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## 描述问题/Describe the bug
我在PaddleDetection上在对Voc的person数据进行训练，数据集只有person一个类别
`python tools/train.py -c configs/faster_rcnn/faster_rcnn_swin_tiny_fpn_2x_coco.yml --eval --use_vdl=true`
除数据集中num_class从80改到1，其他均未改动
完成训练后通过以下命令导出模型
`python tools/export_model.py -c configs\faster_rcnn\faster_rcnn_swin_tiny_fpn_2x_coco.yml --output_dir=./inference_model -o weights=weights\rcnn.pdparams`
利用该导出模型在python端推理报错：
`Found 5 inference images in total.
Traceback (most recent call last):
  File ".\deploy\demo.py", line 8, in <module>
    doInference(model='rcnn', mode='image', input='demo', output_dir='output')
  File "H:\Desktop\YOLO_SSD_RCNN\deploy\infer.py", line 527, in doInference
    predict_image(detector, img_list, output_dir)
  File "H:\Desktop\YOLO_SSD_RCNN\deploy\infer.py", line 438, in predict_image
    results = detector.predict(batch_image_list, 0.5)
  File "H:\Desktop\YOLO_SSD_RCNN\deploy\infer.py", line 145, in predict
    self.predictor.run()
ValueError: In user code:
    File "tools/export_model.py", line 115, in <module>
      main()
    File "tools/export_model.py", line 111, in main
      run(FLAGS, cfg)
    File "tools/export_model.py", line 77, in run
      trainer.export(FLAGS.output_dir)
    File "H:\Desktop\PaddleDetection\ppdet\engine\trainer.py", line 661, in export
      static_model, pruned_input_spec = self._get_infer_cfg_and_input_spec(
    File "H:\Desktop\PaddleDetection\ppdet\engine\trainer.py", line 639, in _get_infer_cfg_and_input_spec
      input_spec, static_model.forward.main_program,
    File "H:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_transla
      concrete_program = self.concrete_program
    File "H:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_transla
      return self.concrete_program_specify_input_spec(input_spec=None)
    File "H:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_transla
      concrete_program, _ = self.get_concrete_program(
    File "H:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_transla
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "H:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_transla
      self._caches[item] = self._build_once(item)
    File "H:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_transla
      concrete_program = ConcreteProgram.from_func_spec(
    File "H:\Anaconda3\envs\paddle\lib\site-packages\decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "H:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl
      return wrapped_func(*args, **kwargs)
    File "H:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "H:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_transla
      outputs = static_func(*inputs)
    File "C:\Users\Zxy\AppData\Local\Temp\tmp0h3j_a2w.py", line 42, in forward
      out = paddle.jit.dy2static.convert_ifelse(self.training, true_fn_2,
    File "H:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operato
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "H:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operato
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "H:\Desktop\PaddleDetection\ppdet\modeling\architectures\meta_arch.py", line 56, in forward
      out = self.get_pred()
    File "H:\Desktop\PaddleDetection\ppdet\modeling\architectures\faster_rcnn.py", line 104, in get_pred
      bbox_pred, bbox_num = self._forward()
    File "H:\Desktop\PaddleDetection\ppdet\modeling\architectures\faster_rcnn.py", line 72, in _forward
      body_feats = self.backbone(self.inputs)
    File "H:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "H:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph
      outputs = self.forward(*inputs, **kwargs)
    File "H:\Desktop\PaddleDetection\ppdet\modeling\backbones\swin_transformer.py", line 710, in forward
      x = self.patch_embed(x['image'])
    File "H:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "H:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph
      outputs = self.forward(*inputs, **kwargs)
    File "C:\Users\Zxy\AppData\Local\Temp\tmpl65yqna2.py", line 71, in forward
      x = paddle.jit.dy2static.convert_ifelse(self.norm is not None,
    File "H:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operato
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "H:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operato
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "H:\Desktop\PaddleDetection\ppdet\modeling\backbones\swin_transformer.py", line 553, in forward
      x = self.norm(x)
)
    File "H:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 3178, in append_op
      op = Operator(
    File "H:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The 'shape' attribute in ReshapeOp is invalid. The input tensor X'size must be divisible by known capacity of 'shape'. But received X's shape = [1, 96, 19200], X's size = 1843200, 'shape' is [-1, 96, 16ze = 1843200, 'shape' is [-1, 96, 160, 160], known capacity of 'shape' is -2457600.
      [Hint: Expected output_shape[unk_dim_idx] * capacity == -in_size, but received output_shape[unk_dim_idx] * capacity:0 != -in_size:-1843200.] (at ..\paddle/fluid/operators/reshape_op.cc:210)10)
      [operator < reshape2 > error]`

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
paddlepaddle-gpu 2.2.2.post101
paddledet           2.3.0
3. 请提供您使用的操作系统信息，
Windows 10
4. 请问您使用的Python版本是
Python3.8
5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.
CUDA10.1
cuDNN 7.6.5
TensorRT6.0.1.5

##输出模型的infer.yml
`mode: fluid
draw_threshold: 0.5
metric: VOC
use_dynamic_shape: false
arch: RCNN
min_subgraph_size: 40
Preprocess:
- interp: 2
  keep_ratio: true
  target_size:
  - 640
  - 640
  type: Resize
- is_scale: true
  mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
  type: NormalizeImage
- type: Permute
- stride: 32
  type: PadStride
label_list:
- person
`
尝试将use_dynamic_shape设置为true仍相同报错

**Comment by SkyrimTB** [comment]
same problem here

**Comment by Rhett98** [comment]
这是来自QQ邮箱的自动回复邮件。你好，我已收到你的邮件，我查看后会尽快给你回复。

**Comment by SkyrimTB** [comment]
@Rhett98 Try set keep_ratio: true to keep_ratio: false fixed my problem.
You should try that as well.

**Comment by NanyuZhang0812** [comment]
我遇到和你相同的问题，请问你解决了吗

**Comment by Rhett98** [comment]
这是来自QQ邮箱的自动回复邮件。你好，我已收到你的邮件，我查看后会尽快给你回复。
