### ISSUE TITLE
[BUG] No such file or directory: 'configs/picodet/picodet_s_320_coco.yml'

### ISSUE THREAD

**Issue by wangxinRS** [PaddlePaddle/PaddleDetection#5497]
release 2.4. 
安装完毕后使用验证命令 python ppdet/modeling/tests/test_architectures.py，报错

ERROR: test_trainer (__main__.TestPicoDet)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 34, in test_trainer
    cfg = ppdet.core.workspace.load_config(self.cfg_file)
  File "/home/wangxin/anaconda3/envs/paddle-env/lib/python3.8/site-packages/paddledet-2.4.0-py3.8.egg/ppdet/core/workspace.py", line 114, in load_config
    cfg = _load_config_with_base(file_path)
  File "/home/wangxin/anaconda3/envs/paddle-env/lib/python3.8/site-packages/paddledet-2.4.0-py3.8.egg/ppdet/core/workspace.py", line 78, in _load_config_with_base
    with open(file_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/picodet/picodet_s_320_coco.yml'

----------------------------------------------------------------------
Ran 7 tests in 5.453s

FAILED (errors=1)

错误原因在于该版本的configs/picodet/picodet_s_320_coco.yml名称已经改为configs/picodet/picodet_s_320_coco_lcnet.yml

希望将ppdet/modeling/tests/test_architectures.py中的第65行configs/picodet/picodet_s_320_coco.yml名称改为configs/picodet/picodet_s_320_coco_lcnet.yml

**Comment by jerrywgz** [comment]
已经提pr修复，感谢反馈！
