### ISSUE TITLE
导出模型时报错，yaml.constructor.ConstructorError: could not determine a constructor for the tag '!DecodeImage'

### ISSUE THREAD

**Issue by linkewei0580** [PaddlePaddle/PaddleDetection#5499]
```
python tools/export_model.py -c models/cascade_rcnn_dcn_r101_vd_fpn_gen_server_side.yml --output_dir=./inference_model -o weights=models/cascade_rcnn_dcn_r101_vd_fpn_gen_server_side.pdparams
```

```
(paddle_env) E:\PaddleDetection>python tools/export_model.py -c models/cascade_rcnn_dcn_r101_vd_fpn_gen_server_side.yml --output_dir=./inference_model -o weights=models/cascade_rcnn_dcn_r101_vd_fpn_gen_server_side.pdparams
d:\Anaconda3\envs\paddle_env\lib\site-packages\paddle\tensor\creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Traceback (most recent call last):
  File "tools/export_model.py", line 115, in <module>
    main()
  File "tools/export_model.py", line 96, in main
    cfg = load_config(FLAGS.config)
  File "E:\PaddleDetection\ppdet\core\workspace.py", line 114, in load_config
    cfg = _load_config_with_base(file_path)
  File "E:\PaddleDetection\ppdet\core\workspace.py", line 79, in _load_config_with_base
    file_cfg = yaml.load(f, Loader=yaml.Loader)
  File "d:\Anaconda3\envs\paddle_env\lib\site-packages\yaml\__init__.py", line 72, in load
    return loader.get_single_data()
  File "d:\Anaconda3\envs\paddle_env\lib\site-packages\yaml\constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "d:\Anaconda3\envs\paddle_env\lib\site-packages\yaml\constructor.py", line 46, in construct_document
    for dummy in generator:
  File "d:\Anaconda3\envs\paddle_env\lib\site-packages\yaml\constructor.py", line 393, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "d:\Anaconda3\envs\paddle_env\lib\site-packages\yaml\constructor.py", line 115, in construct_sequence
    return [self.construct_object(child, deep=deep)
  File "d:\Anaconda3\envs\paddle_env\lib\site-packages\yaml\constructor.py", line 115, in <listcomp>
    return [self.construct_object(child, deep=deep)
  File "d:\Anaconda3\envs\paddle_env\lib\site-packages\yaml\constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "d:\Anaconda3\envs\paddle_env\lib\site-packages\yaml\constructor.py", line 412, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!DecodeImage'
  in "models/cascade_rcnn_dcn_r101_vd_fpn_gen_server_side.yml", line 122, column 5
```

**Comment by jerrywgz** [comment]
这个模型在static/下，是静态图模型，现在tools/下的功能对应动态图，无法使用静态图配置做导出

**Comment by y-x-x123** [comment]
> 这个模型在static/下，是静态图模型，现在tools/下的功能对应动态图，无法使用静态图配置做导出

终于找到答案了
