### ISSUE TITLE
AttributeError: module 'paddle.nn.functional' has no attribute 'mish

### ISSUE THREAD

**Issue by bzcl** [PaddlePaddle/PaddleDetection#5508]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://paddledetection.readthedocs.io/FAQ.html) /I have read the [FAQ documentation](https://paddledetection.readthedocs.io/FAQ.html) but cannot get the expected help.

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?

```none
请填写命令/A placeholder for the command.
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.

3. 您使用的数据集是？/What dataset did you use?

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：

2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：

4. 请问您使用的Python版本是？/ Please provide the version of Python you used.

5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.

如果您的issue是关于安装或环境，您可以先查询[安装文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)尝试解决~

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL.md

**Comment by bzcl** [comment]
使用自己的数据集训练，运行“export CUDA_VISIBLE_DEVICES=0,1,2,3 
python tools/train.py -c configs/ppyolo/ppyolov2_r50vd_dcn_365e_coco.yml --eval”命令时报错“AttributeError: module 'paddle.nn.functional' has no attribute 'mish'”
完整的报错信息如：
Traceback (most recent call last):
  File "tools/train.py", line 177, in <module>
    main()
  File "tools/train.py", line 173, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/home/prir1005/.PRIRMSERdata/prir1005/bzc/PaddleDetection/ppdet/engine/trainer.py", line 425, in train
    outputs = model(data)
  File "/home/prir1005/.PRIRMSERdata/prir1005/HeranWu/.virtualenvs/OCR/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/prir1005/.PRIRMSERdata/prir1005/bzc/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 58, in forward
    out = self.get_loss()
  File "/home/prir1005/.PRIRMSERdata/prir1005/bzc/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 125, in get_loss
    return self._forward()
  File "/home/prir1005/.PRIRMSERdata/prir1005/bzc/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 80, in _forward
    neck_feats = self.neck(body_feats, self.for_mot)
  File "/home/prir1005/.PRIRMSERdata/prir1005/HeranWu/.virtualenvs/OCR/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/prir1005/.PRIRMSERdata/prir1005/bzc/PaddleDetection/ppdet/modeling/necks/yolo_fpn.py", line 952, in forward
    route, tip = self.fpn_blocks[i](block)
  File "/home/prir1005/.PRIRMSERdata/prir1005/HeranWu/.virtualenvs/OCR/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/prir1005/.PRIRMSERdata/prir1005/bzc/PaddleDetection/ppdet/modeling/necks/yolo_fpn.py", line 370, in forward
    conv_left = self.conv1(inputs)
  File "/home/prir1005/.PRIRMSERdata/prir1005/HeranWu/.virtualenvs/OCR/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/prir1005/.PRIRMSERdata/prir1005/bzc/PaddleDetection/ppdet/modeling/backbones/darknet.py", line 81, in forward
    out = getattr(F, self.act)(out)
AttributeError: module 'paddle.nn.functional' has no attribute 'mish'
