### ISSUE TITLE
[Other General Issues]

### ISSUE THREAD

**Issue by bzcl** [PaddlePaddle/PaddleDetection#5509]
使用自己的数据集训练，运行“export CUDA_VISIBLE_DEVICES=0,1,2,3
python tools/tra[i](https://github.com/PaddlePaddle/PaddleDetection/issues/block)n.py -c configs/ppyolo/ppyolov2_r50vd_dcn_365e_coco.yml --eval”命令时报错“AttributeError: module 'paddle.nn.functional' has no attribute 'mish'”
完整的报错信息如：
Traceback (most recent call last):
File "tools/train.py", line 177, in
main()
File "tools/train.py", line 173, in main
run(FLAGS, cfg)
File "tools/train.py", line 127, in run
trainer.train(FLAGS.eval)
File "/home/prir1005/.PRIRMSERdata/prir1005/bzc/PaddleDetection/ppdet/engine/trainer.py", line 425, in train
outputs = model(data)
File "/home/prir1005/.PRIRMSERdata/prir1005/HeranWu/.virtualenvs/OCR/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in call
outputs = self.forward(*inputs, **kwargs)
File "/home/prir1005/.PRIRMSERdata/prir1005/bzc/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 58, in forward
out = self.get_loss()
File "/home/prir1005/.PRIRMSERdata/prir1005/bzc/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 125, in get_loss
return self._forward()
File "/home/prir1005/.PRIRMSERdata/prir1005/bzc/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 80, in _forward
neck_feats = self.neck(body_feats, self.for_mot)
File "/home/prir1005/.PRIRMSERdata/prir1005/HeranWu/.virtualenvs/OCR/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in call
outputs = self.forward(*inputs, **kwargs)
File "/home/prir1005/.PRIRMSERdata/prir1005/bzc/PaddleDetection/ppdet/modeling/necks/yolo_fpn.py", line 952, in forward
route, tip = self.fpn_blocksi
File "/home/prir1005/.PRIRMSERdata/prir1005/HeranWu/.virtualenvs/OCR/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in call
outputs = self.forward(*inputs, **kwargs)
File "/home/prir1005/.PRIRMSERdata/prir1005/bzc/PaddleDetection/ppdet/modeling/necks/yolo_fpn.py", line 370, in forward
conv_left = self.conv1(inputs)
File "/home/prir1005/.PRIRMSERdata/prir1005/HeranWu/.virtualenvs/OCR/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in call
outputs = self.forward(*inputs, **kwargs)
File "/home/prir1005/.PRIRMSERdata/prir1005/bzc/PaddleDetection/ppdet/modeling/backbones/darknet.py", line 81, in forward
out = getattr(F, self.act)(out)
AttributeError: module 'paddle.nn.functional' has no attribute 'mish'

**Comment by yghstill** [comment]
@bzcl 你的PaddlePaddle版本是多少？更新到2.2.2再试下吧。

**Comment by bzcl** [comment]
问题已解决，确实是版本问题，谢谢您！



---- 回复的原邮件 ----
| 发件人 | Guanghua ***@***.***> |
| 日期 | 2022年03月30日 10:13 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleDetection] [Other General Issues] (Issue #5509) |

@bzcl 你的PaddlePaddle版本是多少？更新到2.2.2再试下吧。
