### ISSUE TITLE
运行 SSDLite 时，运行报错

### ISSUE THREAD

**Issue by yuanpengcheng** [PaddlePaddle/PaddleDetection#558]
```W0426 15:57:45.886034 192205 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.2, Runtime API Version: 9.0        
W0426 15:57:45.889879 192205 device_context.cc:245] device: 0, cuDNN Version: 7.6.                                                                         
loading annotations into memory...                                                                                                                         
Done (t=16.81s)                                                                                                                                            
creating index...                                                                                                                                          
index created!                                                                                                                                             
2020-04-26 15:58:06,831-WARNING: Found an invalid bbox in annotations: im_id: 200365, area: 0.0 x1: 296.65, y1: 388.33, x2: 296.67999999999995, y2: 388.33.
2020-04-26 15:58:11,744-WARNING: Found an invalid bbox in annotations: im_id: 550395, area: 0.0 x1: 9.98, y1: 188.56, x2: 14.52, y2: 188.56.               
2020-04-26 15:58:14,492-INFO: 118287 samples in file dataset/coco/annotations/instances_train2017.json                                                     
2020-04-26 15:58:30,685-INFO: places would be ommited when DataLoader is not iterable  
```
出现 places would be ommited when DataLoader is not iterable  问题

**Comment by still-wait** [comment]
@yuanpengcheng 这个不是报错，这个是DataLoader使用pyreader的方式，这种方式做了数据读取的加速，比iterable迭代方式快，请查阅 [DataLoader文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/DataLoader_cn.html#dataloader)

**Comment by yuanpengcheng** [comment]
但是打印完这个之后，程序直接就会结束，或者一直卡在这里，请问是什么原因？

**Comment by yuanpengcheng** [comment]
> @yuanpengcheng 这个不是报错，是`INFO`信息，训练程序会继续正常执行，这个是DataLoader使用pyreader的方式，这种方式做了数据读取的加速，比iterable迭代方式快，请查阅 [DataLoader文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/DataLoader_cn.html#dataloader)
运行脚本：
```
export PYTHONPATH=./:$PYTHONPATH                                                                                                                           
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7                                                                                                                                                                                                                                                                                  
python -m paddle.distributed.launch  ./tools/train.py -c configs/ssd/ssdlite_mobilenet_v2_nas_v1.yml --resume_checkpoint output/ssdlite_mobilenet_v2_nas_v1/140000 --eval 
```
加上 resume_checkpoint就会出现训练停止，不加 resume 就可以重头开始训练

**Comment by still-wait** [comment]
@yuanpengcheng hang住时请检查CPU进程与GPU进程情况，可能内存资源不足，可适当调小num work数等。加上resume_checkpoint后报什么错呢，resume之后会首先进行eval，如果内存等资源不足，会报错。

**Comment by yuanpengcheng** [comment]
```
Exception ignored in: <function Image.__del__ at 0x7f09966b2830>                                                                                           
Traceback (most recent call last):                                                                                                                         
  File "/root/paddlejob/workspace/env_run/env/paddle_env_py37_1.7/lib/python3.7/site-packages/PIL/Image.py", line 633, in __del__                          
    def __del__(self):                                                                                                                                     
  File "/root/paddlejob/workspace/env_run/PaddleDetection/ppdet/data/parallel_map.py", line 169, in <lambda>                                               
    signal.signal(signal.SIGTERM, lambda signum, frame: sys.exit())       
```
改下 numwork 后，又会报这个错误

```
EvalReader:                                                                                                                                                
  inputs_def:                                                                                                                                              
    image_shape: [3, 320, 320]                                                                                                                             
    fields: ['image', 'gt_bbox', 'gt_class', 'im_shape', 'im_id']                                                                                          
  dataset:                                                                                                                                                 
    !COCODataSet                                                                                                                                           
    dataset_dir: dataset/coco_org                                                                                                                          
    anno_path: annotations/instances_val2017.json                                                                                                          
    image_dir: val2017                                                                                                                                     
  sample_transforms:                                                                                                                                       
  - !DecodeImage                                                                                                                                           
    to_rgb: true                                                                                                                                           
  - !NormalizeBox {}                                                                                                                                       
  - !ResizeImage                                                                                                                                           
    interp: 1                                                                                                                                              
    target_size: 320                                                                                                                                       
    use_cv2: false                                                                                                                                         
  - !NormalizeImage                                                                                                                                        
    mean: [0.485, 0.456, 0.406]                                                                                                                            
    std: [0.229, 0.224, 0.225]                                                                                                                             
    is_scale: true                                                                                                                                         
    is_channel_first: false                                                                                                                                
  - !Permute                                                                                                                                               
    to_bgr: false                                                                                                                                          
    channel_first: True                                                                                                                                    
  batch_size: 8                                                                                                                                            
  worker_num: 2                                                                                                                                            
  bufsize: 32                                                                                                                                              
  use_process: false  
```

**Comment by still-wait** [comment]
@yuanpengcheng 这个还是数据reader的原因，如果内存等资源不足，将`--eval`参数取消，等模型完全训完之后再eval评估，另外再将TrainReader中的`worker_num `适当调小。
