### ISSUE TITLE
Process finished with exit code -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by Wei-JL** [PaddlePaddle/PaddleDetection#5590]
复现yolov4 在计算iou损失的时候  代码调试 什么也没做 内存暴涨 直到报 **Process finished with exit code -1073741819 (0xC0000005)** 的错  非常奇怪  调试时 运行完paddle.argmax(self.calculate_iou(gt_box, anchor_shapes), axis=-1)  找到iou最大下标后 for循环完 卡主 什么也没见到执行 内存一直上涨到爆  知道是内存溢出 也看了复现指南https://github.com/PaddlePaddle/models/blob/release%2F2.2/tutorials/article-implementation/ArticleReproduction_CV.md
里面的几个方法  试过了 都没用

**Comment by zoooo0820** [comment]
这部分代码是自己写的吗？如果确定问题出在IOULoss相关的部分，可以尝试下其他使用相同Loss的模型，对比验证下具体问题的来源。

**Comment by Wei-JL** [comment]
> 这部分代码是自己写的吗？如果确定问题出在IOULoss相关的部分，可以尝试下其他使用相同Loss的模型，对比验证下具体问题的来源。

没太明白诶~  其实在之前2个月前 我这个还能train起来  但是 中间有些轮次loss是nan  我找了很久没找出来 就先搁置了  现在知道官方有复现指南 我再打开了  发现train不起来了  内存暴涨  我也没改过代码

**Comment by zoooo0820** [comment]
之前的训练和当前的区别在哪里，是代码做了改动，还是更新了Paddle版本或是PaddleDetection的版本呢。可以控制变量做一下对比

**Comment by Wei-JL** [comment]
> 之前的训练和当前的区别在哪里，是代码做了改动，还是更新了Paddle版本或是PaddleDetection的版本呢。可以控制变量做一下对比

没有升级  我刚刚发现我c盘满了 全是python.exe.1168.dmp 这种文件  占几个G  系统缓存 应该就是我跑这个代码的问题
请问有见过吗

**Comment by Wei-JL** [comment]
请问我可以把项目给您看一下吗  我调试他都没见有问题 一直卡主  确实不知道怎么解决了   第一次遇见这样的问题  卡2天了  一般报错我还是能很快解决的  这个确实不知道问题在哪

**Comment by Wei-JL** [comment]
#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# Copyright (c) Megvii, Inc. and its affiliates.

import paddle
import paddle.nn as nn
import paddle.nn.functional as F


class IOUloss(nn.Layer):
    def __init__(self, reduction="none", loss_type="iou"):
        super(IOUloss, self).__init__()
        self.reduction = reduction
        self.loss_type = loss_type

    def forward(self, pred, target):
        assert pred.shape[0] == target.shape[0]

        pred = pred.reshape(-1, 4)
        target = target.reshape(-1, 4)
        tl = paddle.max(
            paddle.stack([pred[:, :2] - pred[:, 2:] / 2, target[:, :2] - target[:, 2:] / 2], axis=0), axis=0
        )

        br = paddle.min(
            paddle.stack([pred[:, :2] + pred[:, 2:] / 2, target[:, :2] + target[:, 2:] / 2], axis=0), axis=0
        )

        area_p = paddle.prod(pred[:, 2:], 1)
        area_g = paddle.prod(target[:, 2:], 1)

        en = (tl < br).astype(tl.astype()).prod(axis=1)
        area_i = paddle.prod(br - tl, 1) * en
        area_u = area_p + area_g - area_i
        iou = (area_i) / (area_u + 1e-16)

        if self.loss_type == "iou":
            loss = 1 - iou ** 2
        elif self.loss_type == "giou":
            c_tl = paddle.min(
                paddle.stack([pred[:, :2] - pred[:, 2:] / 2, target[:, :2] - target[:, 2:] / 2], axis=0), axis=0
            )
            c_br = paddle.max(
                paddle.stack([pred[:, :2] + pred[:, 2:] / 2, target[:, :2] + target[:, 2:] / 2], axis=0), axis=0
            )
            area_c = paddle.prod(c_br - c_tl, 1)
            giou = iou - (area_c - area_u) / area_c.clamp(1e-16)
            loss = 1 - giou.clamp(min=-1.0, max=1.0)

        if self.reduction == "mean":
            loss = loss.mean()
        elif self.reduction == "sum":
            loss = loss.sum()

        return loss


class YOLOLoss(nn.Layer):
    def __init__(self, num_classes, strides=[8, 16, 32]):
        super().__init__()
        self.num_classes = num_classes
        self.strides = strides

        self.bcewithlog_loss = nn.BCEWithLogitsLoss(reduction="none")
        self.iou_loss = IOUloss(reduction="none")
        self.grids = [paddle.zeros([1])] * len(strides)

    def forward(self, inputs, labels=None):
        outputs = []
        x_shifts = []
        y_shifts = []
        expanded_strides = []

        # -----------------------------------------------#
        # inputs    [[batch_size, num_classes + 5, 20, 20]
        #            [batch_size, num_classes + 5, 40, 40]
        #            [batch_size, num_classes + 5, 80, 80]]
        # outputs   [[batch_size, 400, num_classes + 5]
        #            [batch_size, 1600, num_classes + 5]
        #            [batch_size, 6400, num_classes + 5]]
        # x_shifts  [[batch_size, 400]
        #            [batch_size, 1600]
        #            [batch_size, 6400]]
        # -----------------------------------------------#
        for k, (stride, output) in enumerate(zip(self.strides, inputs)):
            output, grid = self.get_output_and_grid(output, k, stride)
            x_shifts.append(grid[:, :, 0])
            y_shifts.append(grid[:, :, 1])
            expanded_strides.append(paddle.ones_like(grid[:, :, 0]) * stride)
            outputs.append(output)

        return self.get_losses(x_shifts, y_shifts, expanded_strides, labels, paddle.concat(outputs, 1))

    def get_output_and_grid(self, output, k, stride):
        grid = self.grids[k]
        hsize, wsize = output.shape[-2:]
        if grid.shape[2:4] != output.shape[2:4]:
            yv, xv = paddle.meshgrid([paddle.arange(hsize), paddle.arange(wsize)])
            # grid = paddle.stack([xv, yv], 2).unsqueeze(0).astype(output.dtype)
            grid = paddle.stack([xv, yv], 2).reshape([1, hsize, wsize, 2]).astype(output.dtype)

            self.grids[k] = grid
        grid = grid.reshape([1, -1, 2])

        output = output.flatten(2).transpose([0, 2, 1])
        output[..., :2] = (output[..., :2] + grid) * stride
        output[..., 2:4] = paddle.exp(output[..., 2:4]) * stride
        return output, grid

    def get_losses(self, x_shifts, y_shifts, expanded_strides, labels, outputs):
        # -----------------------------------------------#
        #   [batch, n_anchors_all, 4]
        # -----------------------------------------------#
        bbox_preds = outputs[:, :, :4]
        # -----------------------------------------------#
        #   [batch, n_anchors_all, 1]
        # -----------------------------------------------#
        obj_preds = outputs[:, :, 4:5]
        # -----------------------------------------------#
        #   [batch, n_anchors_all, n_cls]
        # -----------------------------------------------#
        cls_preds = outputs[:, :, 5:]

        total_num_anchors = outputs.shape[1]
        # -----------------------------------------------#
        #   x_shifts            [1, n_anchors_all]
        #   y_shifts            [1, n_anchors_all]
        #   expanded_strides    [1, n_anchors_all]
        # -----------------------------------------------#
        x_shifts = paddle.concat(x_shifts, 1)
        y_shifts = paddle.concat(y_shifts, 1)
        expanded_strides = paddle.concat(expanded_strides, 1)

        cls_targets = []
        reg_targets = []
        obj_targets = []
        fg_masks = []

        num_fg = 0.0
        for batch_idx in range(outputs.shape[0]):
            num_gt = len(labels[batch_idx])
            if num_gt == 0:
                cls_target = outputs.new_zeros((0, self.num_classes))
                reg_target = outputs.new_zeros((0, 4))
                obj_target = outputs.new_zeros((total_num_anchors, 1))
                fg_mask = outputs.new_zeros(total_num_anchors).bool()
            else:
                # -----------------------------------------------#
                #   gt_bboxes_per_image     [num_gt, num_classes]
                #   gt_classes              [num_gt]
                #   bboxes_preds_per_image  [n_anchors_all, 4]
                #   cls_preds_per_image     [n_anchors_all, num_classes]
                #   obj_preds_per_image     [n_anchors_all, 1]
                # -----------------------------------------------#
                gt_bboxes_per_image = labels[batch_idx][..., :4]
                gt_classes = labels[batch_idx][..., 4]
                bboxes_preds_per_image = bbox_preds[batch_idx]
                cls_preds_per_image = cls_preds[batch_idx]
                obj_preds_per_image = obj_preds[batch_idx]

                gt_matched_classes, fg_mask, pred_ious_this_matching, matched_gt_inds, num_fg_img = self.get_assignments(
                    num_gt, total_num_anchors, gt_bboxes_per_image, gt_classes, bboxes_preds_per_image,
                    cls_preds_per_image, obj_preds_per_image,
                    expanded_strides, x_shifts, y_shifts,
                )
                # paddle.cuda.empty_cache()
                num_fg += num_fg_img
                cls_target = F.one_hot(gt_matched_classes.astype('int64'),
                                       self.num_classes).astype('float32') * pred_ious_this_matching.unsqueeze(-1)
                obj_target = fg_mask.unsqueeze(-1)
                reg_target = gt_bboxes_per_image[matched_gt_inds]
            cls_targets.append(cls_target)
            reg_targets.append(reg_target)
            obj_targets.append(obj_target.astype(cls_target.astype()))
            fg_masks.append(fg_mask)

        cls_targets = paddle.concat(cls_targets, 0)
        reg_targets = paddle.concat(reg_targets, 0)
        obj_targets = paddle.concat(obj_targets, 0)
        fg_masks = paddle.concat(fg_masks, 0)

        num_fg = max(num_fg, 1)
        loss_iou = (self.iou_loss(bbox_preds.reshape(-1, 4)[fg_masks], reg_targets)).sum()
        loss_obj = (self.bcewithlog_loss(obj_preds.reshape(-1, 1), obj_targets)).sum()
        loss_cls = (self.bcewithlog_loss(cls_preds.reshape(-1, self.num_classes)[fg_masks], cls_targets)).sum()
        reg_weight = 5.0
        loss = reg_weight * loss_iou + loss_obj + loss_cls

        return loss / num_fg

    @paddle.no_grad()
    def get_assignments(self, num_gt, total_num_anchors, gt_bboxes_per_image, gt_classes, bboxes_preds_per_image,
                        cls_preds_per_image, obj_preds_per_image, expanded_strides, x_shifts, y_shifts):
        # -------------------------------------------------------#
        #   fg_mask                 [n_anchors_all]
        #   is_in_boxes_and_center  [num_gt, len(fg_mask)]
        # -------------------------------------------------------#
        fg_mask, is_in_boxes_and_center = self.get_in_boxes_info(gt_bboxes_per_image, expanded_strides, x_shifts,
                                                                 y_shifts, total_num_anchors, num_gt)

        # -------------------------------------------------------#
        #   fg_mask                 [n_anchors_all]
        #   bboxes_preds_per_image  [fg_mask, 4]
        #   cls_preds_              [fg_mask, num_classes]
        #   obj_preds_              [fg_mask, 1]
        # -------------------------------------------------------#
        bboxes_preds_per_image = bboxes_preds_per_image[fg_mask]
        cls_preds_ = cls_preds_per_image[fg_mask]
        obj_preds_ = obj_preds_per_image[fg_mask]
        num_in_boxes_anchor = bboxes_preds_per_image.shape[0]

        # -------------------------------------------------------#
        #   pair_wise_ious      [num_gt, fg_mask]
        # -------------------------------------------------------#
        pair_wise_ious = self.bboxes_iou(gt_bboxes_per_image, bboxes_preds_per_image, False)
        pair_wise_ious_loss = -paddle.log(pair_wise_ious + 1e-8)

        # -------------------------------------------------------#
        #   cls_preds_          [num_gt, fg_mask, num_classes]
        #   gt_cls_per_image    [num_gt, fg_mask, num_classes]
        # -------------------------------------------------------#
        cls_preds_ = nn.functional.sigmoid(
            nn.functional.sigmoid(cls_preds_.astype('float32').unsqueeze(0).expand([num_gt, -1, -1])) *
            obj_preds_.unsqueeze(0).expand([num_gt, -1, -1])
        )
        gt_cls_per_image = F.one_hot(gt_classes.astype('int64'), self.num_classes).astype('float32').unsqueeze(
            1).expand([-1,
                       num_in_boxes_anchor,
                       -1])
        pair_wise_cls_loss = F.binary_cross_entropy(cls_preds_.sqrt_(), gt_cls_per_image, reduction="none").sum(-1)
        del cls_preds_

        cost = pair_wise_cls_loss + 3.0 * pair_wise_ious_loss + 100000.0 * (~is_in_boxes_and_center).astype('float32')

        num_fg, gt_matched_classes, pred_ious_this_matching, matched_gt_inds = self.dynamic_k_matching(cost,
                                                                                                       pair_wise_ious,
                                                                                                       gt_classes,
                                                                                                       num_gt, fg_mask)
        del pair_wise_cls_loss, cost, pair_wise_ious, pair_wise_ious_loss
        return gt_matched_classes, fg_mask, pred_ious_this_matching, matched_gt_inds, num_fg

    def bboxes_iou(self, bboxes_a, bboxes_b, xyxy=True):
        if bboxes_a.shape[1] != 4 or bboxes_b.shape[1] != 4:
            raise IndexError

        def deal_m(b_a, b_b):
            """
            处理tensor维度，保证可以适配paddle(max，min)
            """
            b1 = b_a.expand([-1, b_b.shape[0], -1])
            b2 = b_b.expand([b_a.shape[0], -1, -1])

            return b1, b2
        
        if xyxy:
            tl = paddle.max(paddle.stack([bboxes_a[:, None, :2], bboxes_b[:, :2]], axis=0), axis=0)
            br = paddle.min(paddle.stack([bboxes_a[:, None, 2:], bboxes_b[:, 2:]], axis=0), axis=0)
            area_a = paddle.prod(bboxes_a[:, 2:] - bboxes_a[:, :2], 1)
            area_b = paddle.prod(bboxes_b[:, 2:] - bboxes_b[:, :2], 1)
        else:

            max_b1, max_b2 = deal_m(bboxes_a[:, None, :2] - bboxes_a[:, None, 2:] / 2,
                                    bboxes_b[:, :2] - bboxes_b[:, 2:] / 2)
            tl = paddle.max(
                paddle.stack([max_b1, max_b2], axis=0), axis=0
            )

            min_b1, min_b2 = deal_m(bboxes_a[:, None, :2] + bboxes_a[:, None, 2:] / 2,
                                    bboxes_b[:, :2] + bboxes_b[:, 2:] / 2)
            br = paddle.min(
                paddle.stack([min_b1, min_b2], axis=0), axis=0
            )

            area_a = paddle.prod(bboxes_a[:, 2:], 1)
            area_b = paddle.prod(bboxes_b[:, 2:], 1)
        en = (tl < br).astype(tl.dtype).prod(axis=2)
        area_i = paddle.prod(br - tl, 2) * en
        return area_i / (area_a[:, None] + area_b - area_i)

    def get_in_boxes_info(self, gt_bboxes_per_image, expanded_strides, x_shifts, y_shifts, total_num_anchors, num_gt,
                          center_radius=2.5):
        # -------------------------------------------------------#
        #   expanded_strides_per_image  [n_anchors_all]
        #   x_centers_per_image         [num_gt, n_anchors_all]
        #   x_centers_per_image         [num_gt, n_anchors_all]
        # -------------------------------------------------------#
        expanded_strides_per_image = expanded_strides[0]
        x_centers_per_image = ((x_shifts[0] + 0.5) * expanded_strides_per_image).unsqueeze(0)
        x_centers_per_image = x_centers_per_image.expand([num_gt, x_centers_per_image.shape[-1]])
        y_centers_per_image = ((y_shifts[0] + 0.5) * expanded_strides_per_image).unsqueeze(0)
        y_centers_per_image = y_centers_per_image.expand([num_gt, y_centers_per_image.shape[-1]])

        # -------------------------------------------------------#
        #   gt_bboxes_per_image_x       [num_gt, n_anchors_all]
        # -------------------------------------------------------#
        gt_bboxes_per_image_l = (gt_bboxes_per_image[:, 0] - 0.5 * gt_bboxes_per_image[:, 2]).unsqueeze(1)
        gt_bboxes_per_image_l = gt_bboxes_per_image_l.expand([gt_bboxes_per_image_l.shape[0], total_num_anchors])

        gt_bboxes_per_image_r = (gt_bboxes_per_image[:, 0] + 0.5 * gt_bboxes_per_image[:, 2]).unsqueeze(1)
        gt_bboxes_per_image_r = gt_bboxes_per_image_r.expand([gt_bboxes_per_image_r.shape[0], total_num_anchors])

        gt_bboxes_per_image_t = (gt_bboxes_per_image[:, 1] - 0.5 * gt_bboxes_per_image[:, 3]).unsqueeze(1)
        gt_bboxes_per_image_t = gt_bboxes_per_image_t.expand([gt_bboxes_per_image_t.shape[0], total_num_anchors])

        gt_bboxes_per_image_b = (gt_bboxes_per_image[:, 1] + 0.5 * gt_bboxes_per_image[:, 3]).unsqueeze(1)
        gt_bboxes_per_image_b = gt_bboxes_per_image_b.expand([gt_bboxes_per_image_b.shape[0], total_num_anchors])

        # -------------------------------------------------------#
        #   bbox_deltas     [num_gt, n_anchors_all, 4]
        # -------------------------------------------------------#
        b_l = x_centers_per_image - gt_bboxes_per_image_l
        b_r = gt_bboxes_per_image_r - x_centers_per_image
        b_t = y_centers_per_image - gt_bboxes_per_image_t
        b_b = gt_bboxes_per_image_b - y_centers_per_image
        bbox_deltas = paddle.stack([b_l, b_t, b_r, b_b], 2)

        # -------------------------------------------------------#
        #   is_in_boxes     [num_gt, n_anchors_all]
        #   is_in_boxes_all [n_anchors_all]
        # -------------------------------------------------------#
        is_in_boxes = bbox_deltas.min(axis=-1) > 0.0
        is_in_boxes_all = is_in_boxes.sum(axis=0) > 0

        gt_bboxes_per_image_l = (gt_bboxes_per_image[:, 0]).unsqueeze(1)
        gt_bboxes_per_image_l = gt_bboxes_per_image_l.expand(
            [gt_bboxes_per_image_l.shape[0], total_num_anchors]) - center_radius * expanded_strides_per_image.unsqueeze(
            0)

        gt_bboxes_per_image_r = (gt_bboxes_per_image[:, 0]).unsqueeze(1)
        gt_bboxes_per_image_r = gt_bboxes_per_image_r.expand(
            [gt_bboxes_per_image_r.shape[0], total_num_anchors]) + center_radius * expanded_strides_per_image.unsqueeze(
            0)

        gt_bboxes_per_image_t = (gt_bboxes_per_image[:, 1]).unsqueeze(1)
        gt_bboxes_per_image_t = gt_bboxes_per_image_t.expand(
            [gt_bboxes_per_image_t.shape[0], total_num_anchors]) - center_radius * expanded_strides_per_image.unsqueeze(
            0)

        gt_bboxes_per_image_b = (gt_bboxes_per_image[:, 1]).unsqueeze(1)
        gt_bboxes_per_image_b = gt_bboxes_per_image_b.expand(
            [gt_bboxes_per_image_b.shape[0], total_num_anchors]) + center_radius * expanded_strides_per_image.unsqueeze(
            0)
        # -------------------------------------------------------#
        #   center_deltas   [num_gt, n_anchors_all, 4]
        # -------------------------------------------------------#
        c_l = x_centers_per_image - gt_bboxes_per_image_l
        c_r = gt_bboxes_per_image_r - x_centers_per_image
        c_t = y_centers_per_image - gt_bboxes_per_image_t
        c_b = gt_bboxes_per_image_b - y_centers_per_image
        center_deltas = paddle.stack([c_l, c_t, c_r, c_b], 2)

        # -------------------------------------------------------#
        #   is_in_centers       [num_gt, n_anchors_all]
        #   is_in_centers_all   [n_anchors_all]
        # -------------------------------------------------------#
        is_in_centers = center_deltas.min(axis=-1) > 0.0
        is_in_centers_all = is_in_centers.sum(axis=0) > 0

        # -------------------------------------------------------#
        #   is_in_boxes_anchor      [n_anchors_all]
        #   is_in_boxes_and_center  [num_gt, is_in_boxes_anchor]
        # -------------------------------------------------------#
        is_in_boxes_anchor = is_in_boxes_all | is_in_centers_all

        def deal(is_in_boxes, is_in_boxes_anchor):

            _index = 0
            first = 0
            in_boxes = 0

            for i in is_in_boxes_anchor:
                _bool = bool(i[0].numpy())
                if _bool:
                    if first == 0:
                        in_boxes = is_in_boxes[:, _index]
                        in_boxes = in_boxes.reshape([in_boxes.shape[0], 1])
                        first += 1
                        _index += 1
                        continue
                    new = is_in_boxes[:, _index]
                    in_boxes = paddle.concat([in_boxes, new.reshape([new.shape[0], 1])], axis=1)
                _index += 1
                # print("wjl: ", bool(i[0].numpy()), _index)

            return in_boxes

        _boxes = deal(is_in_boxes, is_in_boxes_anchor)
        _centers = deal(is_in_centers, is_in_boxes_anchor)
        is_in_boxes_and_center = _boxes & _centers
        # wjl check
        # is_in_boxes_and_center = is_in_boxes[:, is_in_boxes_anchor] & is_in_centers[:, is_in_boxes_anchor]
        return is_in_boxes_anchor, is_in_boxes_and_center

    def dynamic_k_matching(self, cost, pair_wise_ious, gt_classes, num_gt, fg_mask):
        # -------------------------------------------------------#
        #   cost                [num_gt, fg_mask]
        #   pair_wise_ious      [num_gt, fg_mask]
        #   gt_classes          [num_gt]        
        #   fg_mask             [n_anchors_all]
        #   matching_matrix     [num_gt, fg_mask]
        # -------------------------------------------------------#
        matching_matrix = paddle.zeros_like(cost)

        # ------------------------------------------------------------#
        #   选取iou最大的n_candidate_k个点
        #   然后求和，判断应该有多少点用于该框预测
        #   topk_ious           [num_gt, n_candidate_k]
        #   dynamic_ks          [num_gt]
        #   matching_matrix     [num_gt, fg_mask]
        # ------------------------------------------------------------#
        n_candidate_k = min(10, pair_wise_ious.shape[1])
        topk_ious, _ = paddle.topk(pair_wise_ious, n_candidate_k, axis=1)
        dynamic_ks = paddle.clip(topk_ious.sum(1).astype("int32"), min=1)
        # wjl 数字太小，换相同的图片测试

        for gt_idx in range(num_gt):
            # ------------------------------------------------------------#
            #   给每个真实框选取最小的动态k个点
            # ------------------------------------------------------------#
            _, pos_idx = paddle.topk(cost[gt_idx], k=dynamic_ks[gt_idx].item(), largest=False)
            matching_matrix[gt_idx][pos_idx] = 1.0
        del topk_ious, dynamic_ks, pos_idx

        # ------------------------------------------------------------#
        #   anchor_matching_gt  [fg_mask]
        # ------------------------------------------------------------#
        anchor_matching_gt = matching_matrix.sum(0)
        if (anchor_matching_gt > 1).sum() > 0:
            # ------------------------------------------------------------#
            #   当某一个特征点指向多个真实框的时候
            #   选取cost最小的真实框。
            # ------------------------------------------------------------#
            _, cost_argmin = paddle.min(cost[:, anchor_matching_gt > 1], axis=0)
            matching_matrix[:, anchor_matching_gt > 1] *= 0.0
            matching_matrix[cost_argmin, anchor_matching_gt > 1] = 1.0
        # ------------------------------------------------------------#
        #   fg_mask_inboxes  [fg_mask]
        #   num_fg为正样本的特征点个数
        # ------------------------------------------------------------#
        fg_mask_inboxes = matching_matrix.sum(0) > 0.0
        num_fg = fg_mask_inboxes.sum().item()

        # ------------------------------------------------------------#
        #   对fg_mask进行更新
        # ------------------------------------------------------------#

        fg_mask[fg_mask.clone()] = fg_mask_inboxes

        # ------------------------------------------------------------#
        #   获得特征点对应的物品种类
        # ------------------------------------------------------------#
        matched_gt_inds = matching_matrix[:, fg_mask_inboxes].argmax(0)
        gt_matched_classes = gt_classes[matched_gt_inds]

        pred_ious_this_matching = (matching_matrix * pair_wise_ious).sum(0)[fg_mask_inboxes]
        return num_fg, gt_matched_classes, pred_ious_this_matching, matched_gt_inds


# def weights_init(net, init_type='normal', init_gain=0.02):
#     def init_func(m):
#         classname = m.__class__.__name__
#         if hasattr(m, 'weight') and classname.find('Conv') != -1:
#             if init_type == 'normal':
#                 paddle.nn.init.normal_(m.weight.data, 0.0, init_gain)
#             elif init_type == 'xavier':
#                 paddle.nn.init.xavier_normal_(m.weight.data, gain=init_gain)
#             elif init_type == 'kaiming':
#                 paddle.nn.init.kaiming_normal_(m.weight.data, a=0, mode='fan_in')
#             elif init_type == 'orthogonal':
#                 paddle.nn.init.orthogonal_(m.weight.data, gain=init_gain)
#             else:
#                 raise NotImplementedError('initialization method [%s] is not implemented' % init_type)
#         elif classname.find('BatchNorm2d') != -1:
#             paddle.nn.init.normal_(m.weight.data, 1.0, 0.02)
#             paddle.nn.init.constant_(m.bias.data, 0.0)
#
#     print('initialize network with %s astype' % init_type)
#     net.apply(init_func)

def weights_init(net, init_type='normal', init_gain=0.02):
    def init_func(m):
        classname = m.__class__.__name__
        if hasattr(m, 'weight') and classname.find('Conv') != -1:
            if init_type == 'normal':
                m.weight.data = paddle.framework.ParamAttr(
                    name="normal",
                    initializer=paddle.nn.initializer.Normal(mean=0.0, std=init_gain))
            elif init_type == 'xavier':
                m.weight.data = paddle.framework.ParamAttr(
                    name="xavier",
                    initializer=paddle.nn.initializer.XavierNormal() * 2)
            elif init_type == 'kaiming':
                m.weight.data = nn.initializer.KaimingNormal()

            elif init_type == 'orthogonal':
                m.weight.data = paddle.framework.ParamAttr(
                    name="normal",
                    initializer=paddle.nn.initializer.Normal(mean=0.0, std=init_gain))
            else:
                raise NotImplementedError('initialization method [%s] is not implemented' % init_type)
        elif classname.find('BatchNorm2d') != -1:
            m.weight.data = paddle.framework.ParamAttr(
                name="normal",
                initializer=paddle.nn.initializer.Normal(mean=1.0, std=0.02))
            m.bias.data = paddle.framework.ParamAttr(
                name="linear_bias",
                initializer=paddle.nn.initializer.Normal(mean=0.0, std=2.0))

    print('initialize network with %s astype' % init_type)
    net.apply(init_func)
在第92行哪里卡死   感觉是构建梯度的问题

**Comment by zoooo0820** [comment]
上面格式已经乱了，另外从代码很难直接看出问题在哪里。能否尽量给出最小化可复现这个问题的代码呢？另外可以提供一下具体的运行环境（paddle/paddledet版本，系統、cuda版本等等）

**Comment by Wei-JL** [comment]
系统win11 paddle版本如下
import paddle
print("paddleversion", paddle.__version__)
paddle.utils.run_check()

输出：
paddleversion 0.0.0
Running verify PaddlePaddle program ... 
W0406 18:21:44.535634 18644 device_context.cc:479] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.2
W0406 18:21:44.543635 18644 device_context.cc:497] device: 0, cuDNN Version: 8.2.
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

最小复现的话，这次估计很难  因为我也不知道哪出了问题，我现在正在尝试上传到BML上跑。

**Comment by Wei-JL** [comment]
paddle                        1.0.2                   pypi_0    pypi                                                       
paddlepaddle             2.2.0                   pypi_0    pypi                                                       
paddlepaddle-gpu      0.0.0.post112     pypi_0    pypi      
这是我刚刚在anaconda上复制的

**Comment by Wei-JL** [comment]
您好，我把代码上传到了BML上，会报错 。不太清楚为什么自己电脑上不会 。可能跟python版本有关系  我试了3.6版本也会报错。我这个是3.8版本。

Traceback (most recent call last):
  File "train.py", line 231, in <module>
    epoch_step, epoch_step_val, gen, gen_val, end_epoch, Cuda)
  File "/home/aistudio/yolov4/utils/utils_fit.py", line 42, in fit_one_epoch
    loss_item, num_pos = yolo_loss(l, outputs[l], targets)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/yolov4/nets/yolo_training.py", line 213, in forward
    ciou = (1 - self.box_ciou(pred_boxes[y_true[..., 4] == 1], y_true[..., :4][y_true[..., 4] == 1])) * \
  File "/home/aistudio/yolov4/nets/yolo_training.py", line 87, in box_ciou
    intersect_mins = paddle.max(paddle.stack([b1_mins, b2_mins], axis=0), axis=0)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/manipulation.py", line 798, in stack
    return layers.stack(x, axis, name)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 10184, in stack
    return _C_ops.stack(x, 'axis', axis)
ValueError: (InvalidArgument) x dim number should greater than 0, but received value is: 0
  [Hint: Expected x_dim > 0, but received x_dim:0 <= 0:0.] (at /paddle/paddle/fluid/platform/gpu_launch_config.h:107)
  [operator < stack > error]

**Comment by zoooo0820** [comment]
理论上python版本不会影响的，0.0.0通常是develop包无法确定paddle的版本情况，优先保证paddle版本一致。也可以先根据当前的报错信息debug。

**Comment by Wei-JL** [comment]
非常感谢~~  还有一个问题 就是我电脑一买来 对着视频安装了cuda11.4  最新的 然后发现paddle那时候最多出了11.2吧？   这样安装会有什么问题出现吗

**Comment by zoooo0820** [comment]
目前官方支持的版本如下
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/windows-pip.html

从前述信息来看，win11,cuda11.4不在列表中，虽然仍然可以运行，但是并没有经过严格测试，可能会有未知的错误。

**Comment by Wei-JL** [comment]
> 目前官方支持的版本如下 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/windows-pip.html 
> 从前述信息来看，win11,cuda11.4不在列表中，虽然仍然可以运行，但是并没有经过严格测试，可能会有未知的错误。

非常感谢~~~ 我重新建了一个anaconda仓库 ，现在能报错了  不再是内存溢出异常终止了
paddleversion 2.2.2
Running verify PaddlePaddle program ... 
W0406 18:49:31.769846 21912 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.2
W0406 18:49:32.035907 21912 device_context.cc:465] device: 0, cuDNN Version: 8.2.
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

**Comment by Wei-JL** [comment]
正好还有个问题~   我可以一起问了吗

torch : fg_mask[fg_mask.clone()] = fg_mask_inboxes
 paddle ： fg_mask[fg_mask.clone()] = fg_mask_inboxes

File "D:\PyCharm\YOLO\paddle_fuxian\yolox_paddle\nets\yolo_training.py", line 447, in dynamic_k_matching
    fg_mask[fg_mask.clone()] = fg_mask_inboxes
  File "D:\Anaconda3\envs\paddle2-2-2g\lib\site-packages\paddle\fluid\dygraph\varbase_patch_methods.py", line 637, in __setitem__
    return _setitem_impl_(self, item, value)
  File "D:\Anaconda3\envs\paddle2-2-2g\lib\site-packages\paddle\fluid\variable_index.py", line 584, in _setitem_impl_
    return set_value_for_bool_tensor(var, slice_item, value)
  File "D:\Anaconda3\envs\paddle2-2-2g\lib\site-packages\paddle\fluid\variable_index.py", line 683, in set_value_for_bool_tensor
    "but received {}.".format(var.dtype))
TypeError: Only support float and double tensor for bool index, but received paddle.bool.

就是复现的时候 发现torch的里面"tensor[ ]"里面可以写另一个bool类型索引，paddle不行  这个该怎么复现

**Comment by zoooo0820** [comment]
2.2 的paddle应该是支持这种写法的，麻烦再确认一下版本是否对得上呢。如果还不行，请给出各变量具体的值供复现问题。

**Comment by Wei-JL** [comment]
好嘞~  我试试  刚刚试了不行的 看能不能最小化复现
