### ISSUE TITLE
[BUG]训练集中加入负样本，训练ppyoloe会报错

### ISSUE THREAD

**Issue by chenhaohan88** [PaddlePaddle/PaddleDetection#5656]
如题，训练集中加入负样本，训练ppyoloe会报错

**Comment by lyuwenyu** [comment]
具体说说你怎么做的  是加入了不带标签的数据嘛？

**Comment by chenhaohan88** [comment]
数据集格式是voc，加入了负样本，把PaddleDetection/ppdet/data/source/voc.py第58行allow_empty改成True

**Comment by chenhaohan88** [comment]
可能是dataloader读取负样本标签之后输入到one_hot函数的输入数据类型有问题

**Comment by ghostxsl** [comment]
bug修复参考PR：#5665

**Comment by m00nLi** [comment]
@qingqing01 @ghostxsl @wangxinxin08 该bug并没有被修复，加入负样本训练仍会报错。可自行制造小批量数据测试复现
```
Exception in thread Thread-1 (_thread_loop):
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/paddle251py310/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/user/anaconda3/envs/paddle251py310/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/anaconda3/envs/paddle251py310/lib/python3.10/site-packages/paddle/io/dataloader/dataloader_iter.py", line 637, in _thread_loop
    raise e
  File "/home/user/anaconda3/envs/paddle251py310/lib/python3.10/site-packages/paddle/io/dataloader/dataloader_iter.py", line 618, in _thread_loop
    array.append(tensor)
RuntimeError: (PreconditionNotMet) Tensor holds no memory. Call Tensor::mutable_data firstly.
  [Hint: holder_ should not be null.] (at ../paddle/phi/core/dense_tensor_impl.cc:44)

[09/19 14:36:41] ppdet.engine INFO: Epoch: [0] [15/32] learning_rate: 0.000234 loss: 3.862626 loss_cls: 2.157756 loss_iou: 0.444050 loss_dfl: 1.189487 loss_l1: 0.800069 eta: 0:22:31 batch_cost: 0.2753 data_cost: 0.1896 ips: 3.6321 images/s
Traceback (most recent call last):
  File "/home/user/workspace/PaddleDetection/tools/train.py", line 202, in <module>
    main()
  File "/home/user/workspace/PaddleDetection/tools/train.py", line 198, in main
    run(FLAGS, cfg)
  File "/home/user/workspace/PaddleDetection/tools/train.py", line 151, in run
    trainer.train(FLAGS.eval)
  File "/home/user/workspace/PaddleDetection/ppdet/engine/trainer.py", line 482, in train
    for step_id, data in enumerate(self.loader):
  File "/home/user/workspace/PaddleDetection/ppdet/data/reader.py", line 214, in __next__
    return next(self.loader)
  File "/home/user/anaconda3/envs/paddle251py310/lib/python3.10/site-packages/paddle/io/dataloader/dataloader_iter.py", line 825, in __next__
    self._reader.read_next_list()[0]
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at ../paddle/fluid/operators/reader/blocking_queue.h:175)
```

**Comment by DormouseLi** [comment]
这个怎么解决呀，同样的问题
