### ISSUE TITLE
trouble on installing paddle detection  in paddle serving container

### ISSUE THREAD

**Issue by Pastuzo** [PaddlePaddle/PaddleDetection#5695]
Hi, I try to install paddle detection in the paddle serving container. The steps are 

docker pull paddlepaddle/serving:0.7.0-devel
docker run -p 9292:9292 --name test -dit paddlepaddle/serving:0.7.0-devel bash
docker exec -it test bash
git clone https://github.com/PaddlePaddle/Serving
cd Serving
pip3 install -r python/requirements.txt
pip3 install paddlepaddle==2.2.0
git clone https://github.com/PaddlePaddle/PaddleDetection.git
# 安装其他依赖
cd PaddleDetection
pip3 install -r requirements.txt
# 编译安装paddledet
python3 setup.py install
However, I run python3 ppdet/modeling/tests/test_architectures.py, the results are as follows:

grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 20, in <module>
    import ppdet
  File "/usr/local/lib/python3.6/site-packages/paddledet-2.4.0-py3.6.egg/ppdet/__init__.py", line 15, in <module>
    from . import (core, data, engine, modeling, model_zoo, optimizer, metrics,
  File "/usr/local/lib/python3.6/site-packages/paddledet-2.4.0-py3.6.egg/ppdet/engine/__init__.py", line 15, in <module>
    from . import trainer
  File "/usr/local/lib/python3.6/site-packages/paddledet-2.4.0-py3.6.egg/ppdet/engine/trainer.py", line 40, in <module>
    from ppdet.metrics import Metric, COCOMetric, VOCMetric, WiderFaceMetric, get_infer_results, KeyPointTopDownCOCOEval, KeyPointTopDownMPIIEval
  File "/usr/local/lib/python3.6/site-packages/paddledet-2.4.0-py3.6.egg/ppdet/metrics/__init__.py", line 27, in <module>
    from . import mcmot_metrics
  File "/usr/local/lib/python3.6/site-packages/paddledet-2.4.0-py3.6.egg/ppdet/metrics/mcmot_metrics.py", line 24, in <module>
    from motmetrics.math_util import quiet_divide
  File "/usr/local/lib/python3.6/site-packages/motmetrics/__init__.py", line 28, in <module>
    from motmetrics import io
  File "/usr/local/lib/python3.6/site-packages/motmetrics/io.py", line 18, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.6/site-packages/pandas/__init__.py", line 55, in <module>
    from pandas.core.api import (
  File "/usr/local/lib/python3.6/site-packages/pandas/core/api.py", line 24, in <module>
    from pandas.core.groupby import Grouper, NamedAgg
  File "/usr/local/lib/python3.6/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (  # noqa: F401
  File "/usr/local/lib/python3.6/site-packages/pandas/core/groupby/generic.py", line 44, in <module>
    from pandas.core.frame import DataFrame
  File "/usr/local/lib/python3.6/site-packages/pandas/core/frame.py", line 115, in <module>
    from pandas.core.series import Series
  File "/usr/local/lib/python3.6/site-packages/pandas/core/series.py", line 84, in <module>
    import pandas.plotting
  File "/usr/local/lib/python3.6/site-packages/pandas/plotting/__init__.py", line 59, in <module>
    from pandas.plotting._core import (
  File "/usr/local/lib/python3.6/site-packages/pandas/plotting/_core.py", line 17, in <module>
    import pandas.plotting._matplotlib  # noqa
  File "/usr/local/lib/python3.6/site-packages/pandas/plotting/_matplotlib/__init__.py", line 3, in <module>
    from pandas.plotting._matplotlib.boxplot import (
  File "/usr/local/lib/python3.6/site-packages/pandas/plotting/_matplotlib/boxplot.py", line 4, in <module>
    from matplotlib.artist import setp
  File "/usr/local/lib/python3.6/site-packages/matplotlib/__init__.py", line 107, in <module>
    from . import cbook, rcsetup
  File "/usr/local/lib/python3.6/site-packages/matplotlib/rcsetup.py", line 28, in <module>
    from matplotlib.fontconfig_pattern import parse_fontconfig_pattern
  File "/usr/local/lib/python3.6/site-packages/matplotlib/fontconfig_pattern.py", line 15, in <module>
    from pyparsing import (Literal, ZeroOrMore, Optional, Regex, StringEnd,
  File "/usr/local/lib/python3.6/site-packages/pyparsing/__init__.py", line 130, in <module>
    __version__ = __version_info__.__version__

**Comment by zhiboniu** [comment]
你好，看起来像是pandas版本问题，换个版本试试呢？

**Comment by Pastuzo** [comment]
paddle Serving 版本{v0.8.3}
PaddleDetection {release/2.4}
那pandas用什么版本呢
