### ISSUE TITLE
[BUG]PaddleDetection对yolov3_darknet53进行PTQ量化时，调用paddle函数报错：AttributeError: 'Blocks' object has no attribute 'downsample.conv_bn_layer.conv'

### ISSUE THREAD

**Issue by Disciple7** [PaddlePaddle/PaddleDetection#5696]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://paddledetection.readthedocs.io/FAQ.html) /I have read the [FAQ documentation](https://paddledetection.readthedocs.io/FAQ.html) but cannot get the expected help.
3. 确认bug是否在新版本里还未修复/The bug has not been fixed in the latest version.

## 描述问题/Describe the bug
PaddleDetection对yolov3_darknet53_270e_voc进行PTQ量化时，调用paddle函数报错：AttributeError: 'Blocks' object has no attribute 'downsample.conv_bn_layer.conv'

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?

```
python tools/post_quant.py \
-c configs/yolov3/yolov3_darknet53_270e_voc.yml \
--slim_config configs/slim/post_quant/yolov3_darknet53_ptq.yml \
-o weights=./inference_model/yolov3_darknet53_270e_voc_origin/model.pdiparams

```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.

否。

3. 您使用的数据集是？/What dataset did you use?

voc数据集。

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.

```
[W0412 11:22:02.655656 27416 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 10.1, Runtime API Version: 10.1
W0412 11:22:02.660704 27416 device_context.cc:465] device: 0, cuDNN Version: 7.6.
[04/12 11:22:12] ppdet.utils.checkpoint INFO: The shape [255] in pretrained weight yolo_head.yolo_output.0.bias is unmatched with the shape [21] in model yolo_head.yolo_output.0.bias. And the weight yolo_head.yolo_output.0.bias will not be loaded
[04/12 11:22:12] ppdet.utils.checkpoint INFO: The shape [255, 1024, 1, 1] in pretrained weight yolo_head.yolo_output.0.weight is unmatched with the shape [21, 1024, 1, 1] in model yolo_head.yolo_output.0.weight. And the weight yolo_head.yolo_output.0.weight will not be loaded
[04/12 11:22:12] ppdet.utils.checkpoint INFO: The shape [255] in pretrained weight yolo_head.yolo_output.1.bias is unmatched with the shape [21] in model yolo_head.yolo_output.1.bias. And the weight yolo_head.yolo_output.1.bias will not be loaded
[04/12 11:22:12] ppdet.utils.checkpoint INFO: The shape [255, 512, 1, 1] in pretrained weight yolo_head.yolo_output.1.weight is unmatched with the shape [21, 512, 1, 1] in model yolo_head.yolo_output.1.weight. And the weight yolo_head.yolo_output.1.weight will not be loaded
[04/12 11:22:12] ppdet.utils.checkpoint INFO: The shape [255] in pretrained weight yolo_head.yolo_output.2.bias is unmatched with the shape [21] in model yolo_head.yolo_output.2.bias. And the weight yolo_head.yolo_output.2.bias will not be loaded
[04/12 11:22:12] ppdet.utils.checkpoint INFO: The shape [255, 256, 1, 1] in pretrained weight yolo_head.yolo_output.2.weight is unmatched with the shape [21, 256, 1, 1] in model yolo_head.yolo_output.2.weight. And the weight yolo_head.yolo_output.2.weight will not be loaded
[04/12 11:22:13] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/ubuntu/.cache/paddle/weights/yolov3_darknet53_270e_coco.pdparams
activation_quantizer HistQuantizer
2022-04-12 11:22:13,588-INFO: The layers to be fused:
2022-04-12 11:22:13,588-INFO: ['backbone.conv0.conv', 'backbone.conv0.batch_norm']
2022-04-12 11:22:13,588-INFO: ['backbone.downsample0.conv_bn_layer.conv', 'backbone.downsample0.conv_bn_layer.batch_norm']
2022-04-12 11:22:13,589-INFO: ['backbone.stage.0.basicblock0.conv1.conv', 'backbone.stage.0.basicblock0.conv1.batch_norm']
2022-04-12 11:22:13,589-INFO: ['backbone.stage.0.basicblock0.conv2.conv', 'backbone.stage.0.basicblock0.conv2.batch_norm']
2022-04-12 11:22:13,589-INFO: ['backbone.stage.1.basicblock0.conv1.conv', 'backbone.stage.1.basicblock0.conv1.batch_norm']
2022-04-12 11:22:13,589-INFO: ['backbone.stage.1.basicblock0.conv2.conv', 'backbone.stage.1.basicblock0.conv2.batch_norm']
2022-04-12 11:22:13,589-INFO: ['backbone.stage.1.stage.1.1.conv1.conv', 'backbone.stage.1.stage.1.1.conv1.batch_norm']
2022-04-12 11:22:13,589-INFO: ['backbone.stage.1.stage.1.1.conv2.conv', 'backbone.stage.1.stage.1.1.conv2.batch_norm']
2022-04-12 11:22:13,589-INFO: ['backbone.stage.2.basicblock0.conv1.conv', 'backbone.stage.2.basicblock0.conv1.batch_norm']
2022-04-12 11:22:13,589-INFO: ['backbone.stage.2.basicblock0.conv2.conv', 'backbone.stage.2.basicblock0.conv2.batch_norm']
2022-04-12 11:22:13,589-INFO: ['backbone.stage.2.stage.2.1.conv1.conv', 'backbone.stage.2.stage.2.1.conv1.batch_norm']
2022-04-12 11:22:13,589-INFO: ['backbone.stage.2.stage.2.1.conv2.conv', 'backbone.stage.2.stage.2.1.conv2.batch_norm']
2022-04-12 11:22:13,589-INFO: ['backbone.stage.2.stage.2.2.conv1.conv', 'backbone.stage.2.stage.2.2.conv1.batch_norm']
2022-04-12 11:22:13,589-INFO: ['backbone.stage.2.stage.2.2.conv2.conv', 'backbone.stage.2.stage.2.2.conv2.batch_norm']
2022-04-12 11:22:13,589-INFO: ['backbone.stage.2.stage.2.3.conv1.conv', 'backbone.stage.2.stage.2.3.conv1.batch_norm']
2022-04-12 11:22:13,589-INFO: ['backbone.stage.2.stage.2.3.conv2.conv', 'backbone.stage.2.stage.2.3.conv2.batch_norm']
2022-04-12 11:22:13,589-INFO: ['backbone.stage.2.stage.2.4.conv1.conv', 'backbone.stage.2.stage.2.4.conv1.batch_norm']
2022-04-12 11:22:13,589-INFO: ['backbone.stage.2.stage.2.4.conv2.conv', 'backbone.stage.2.stage.2.4.conv2.batch_norm']
2022-04-12 11:22:13,589-INFO: ['backbone.stage.2.stage.2.5.conv1.conv', 'backbone.stage.2.stage.2.5.conv1.batch_norm']
2022-04-12 11:22:13,589-INFO: ['backbone.stage.2.stage.2.5.conv2.conv', 'backbone.stage.2.stage.2.5.conv2.batch_norm']
2022-04-12 11:22:13,589-INFO: ['backbone.stage.2.stage.2.6.conv1.conv', 'backbone.stage.2.stage.2.6.conv1.batch_norm']
2022-04-12 11:22:13,590-INFO: ['backbone.stage.2.stage.2.6.conv2.conv', 'backbone.stage.2.stage.2.6.conv2.batch_norm']
2022-04-12 11:22:13,590-INFO: ['backbone.stage.2.stage.2.7.conv1.conv', 'backbone.stage.2.stage.2.7.conv1.batch_norm']
2022-04-12 11:22:13,590-INFO: ['backbone.stage.2.stage.2.7.conv2.conv', 'backbone.stage.2.stage.2.7.conv2.batch_norm']
2022-04-12 11:22:13,590-INFO: ['backbone.stage.3.basicblock0.conv1.conv', 'backbone.stage.3.basicblock0.conv1.batch_norm']
2022-04-12 11:22:13,590-INFO: ['backbone.stage.3.basicblock0.conv2.conv', 'backbone.stage.3.basicblock0.conv2.batch_norm']
2022-04-12 11:22:13,590-INFO: ['backbone.stage.3.stage.3.1.conv1.conv', 'backbone.stage.3.stage.3.1.conv1.batch_norm']
2022-04-12 11:22:13,590-INFO: ['backbone.stage.3.stage.3.1.conv2.conv', 'backbone.stage.3.stage.3.1.conv2.batch_norm']
2022-04-12 11:22:13,590-INFO: ['backbone.stage.3.stage.3.2.conv1.conv', 'backbone.stage.3.stage.3.2.conv1.batch_norm']
2022-04-12 11:22:13,590-INFO: ['backbone.stage.3.stage.3.2.conv2.conv', 'backbone.stage.3.stage.3.2.conv2.batch_norm']
2022-04-12 11:22:13,590-INFO: ['backbone.stage.3.stage.3.3.conv1.conv', 'backbone.stage.3.stage.3.3.conv1.batch_norm']
2022-04-12 11:22:13,590-INFO: ['backbone.stage.3.stage.3.3.conv2.conv', 'backbone.stage.3.stage.3.3.conv2.batch_norm']
2022-04-12 11:22:13,590-INFO: ['backbone.stage.3.stage.3.4.conv1.conv', 'backbone.stage.3.stage.3.4.conv1.batch_norm']
2022-04-12 11:22:13,590-INFO: ['backbone.stage.3.stage.3.4.conv2.conv', 'backbone.stage.3.stage.3.4.conv2.batch_norm']
2022-04-12 11:22:13,590-INFO: ['backbone.stage.3.stage.3.5.conv1.conv', 'backbone.stage.3.stage.3.5.conv1.batch_norm']
2022-04-12 11:22:13,590-INFO: ['backbone.stage.3.stage.3.5.conv2.conv', 'backbone.stage.3.stage.3.5.conv2.batch_norm']
2022-04-12 11:22:13,590-INFO: ['backbone.stage.3.stage.3.6.conv1.conv', 'backbone.stage.3.stage.3.6.conv1.batch_norm']
2022-04-12 11:22:13,590-INFO: ['backbone.stage.3.stage.3.6.conv2.conv', 'backbone.stage.3.stage.3.6.conv2.batch_norm']
2022-04-12 11:22:13,590-INFO: ['backbone.stage.3.stage.3.7.conv1.conv', 'backbone.stage.3.stage.3.7.conv1.batch_norm']
2022-04-12 11:22:13,590-INFO: ['backbone.stage.3.stage.3.7.conv2.conv', 'backbone.stage.3.stage.3.7.conv2.batch_norm']
2022-04-12 11:22:13,590-INFO: ['backbone.stage.4.basicblock0.conv1.conv', 'backbone.stage.4.basicblock0.conv1.batch_norm']
2022-04-12 11:22:13,590-INFO: ['backbone.stage.4.basicblock0.conv2.conv', 'backbone.stage.4.basicblock0.conv2.batch_norm']
2022-04-12 11:22:13,591-INFO: ['backbone.stage.4.stage.4.1.conv1.conv', 'backbone.stage.4.stage.4.1.conv1.batch_norm']
2022-04-12 11:22:13,591-INFO: ['backbone.stage.4.stage.4.1.conv2.conv', 'backbone.stage.4.stage.4.1.conv2.batch_norm']
2022-04-12 11:22:13,591-INFO: ['backbone.stage.4.stage.4.2.conv1.conv', 'backbone.stage.4.stage.4.2.conv1.batch_norm']
2022-04-12 11:22:13,591-INFO: ['backbone.stage.4.stage.4.2.conv2.conv', 'backbone.stage.4.stage.4.2.conv2.batch_norm']
2022-04-12 11:22:13,591-INFO: ['backbone.stage.4.stage.4.3.conv1.conv', 'backbone.stage.4.stage.4.3.conv1.batch_norm']
2022-04-12 11:22:13,591-INFO: ['backbone.stage.4.stage.4.3.conv2.conv', 'backbone.stage.4.stage.4.3.conv2.batch_norm']
2022-04-12 11:22:13,591-INFO: ['backbone.stage.0.downsample.conv_bn_layer.conv', 'backbone.stage.0.downsample.conv_bn_layer.batch_norm']
2022-04-12 11:22:13,591-INFO: ['backbone.stage.1.downsample.conv_bn_layer.conv', 'backbone.stage.1.downsample.conv_bn_layer.batch_norm']
2022-04-12 11:22:13,591-INFO: ['backbone.stage.2.downsample.conv_bn_layer.conv', 'backbone.stage.2.downsample.conv_bn_layer.batch_norm']
2022-04-12 11:22:13,591-INFO: ['backbone.stage.3.downsample.conv_bn_layer.conv', 'backbone.stage.3.downsample.conv_bn_layer.batch_norm']
2022-04-12 11:22:13,591-INFO: ['neck.yolo_block.0.conv_module.conv0.conv', 'neck.yolo_block.0.conv_module.conv0.batch_norm']
2022-04-12 11:22:13,591-INFO: ['neck.yolo_block.0.conv_module.conv1.conv', 'neck.yolo_block.0.conv_module.conv1.batch_norm']
2022-04-12 11:22:13,591-INFO: ['neck.yolo_block.0.conv_module.conv2.conv', 'neck.yolo_block.0.conv_module.conv2.batch_norm']
2022-04-12 11:22:13,591-INFO: ['neck.yolo_block.0.conv_module.conv3.conv', 'neck.yolo_block.0.conv_module.conv3.batch_norm']
2022-04-12 11:22:13,591-INFO: ['neck.yolo_block.0.conv_module.route.conv', 'neck.yolo_block.0.conv_module.route.batch_norm']
2022-04-12 11:22:13,591-INFO: ['neck.yolo_block.0.tip.conv', 'neck.yolo_block.0.tip.batch_norm']
2022-04-12 11:22:13,591-INFO: ['neck.yolo_transition.0.conv', 'neck.yolo_transition.0.batch_norm']
2022-04-12 11:22:13,591-INFO: ['neck.yolo_block.1.conv_module.conv0.conv', 'neck.yolo_block.1.conv_module.conv0.batch_norm']
2022-04-12 11:22:13,591-INFO: ['neck.yolo_block.1.conv_module.conv1.conv', 'neck.yolo_block.1.conv_module.conv1.batch_norm']
2022-04-12 11:22:13,591-INFO: ['neck.yolo_block.1.conv_module.conv2.conv', 'neck.yolo_block.1.conv_module.conv2.batch_norm']
2022-04-12 11:22:13,591-INFO: ['neck.yolo_block.1.conv_module.conv3.conv', 'neck.yolo_block.1.conv_module.conv3.batch_norm']
2022-04-12 11:22:13,592-INFO: ['neck.yolo_block.1.conv_module.route.conv', 'neck.yolo_block.1.conv_module.route.batch_norm']
2022-04-12 11:22:13,592-INFO: ['neck.yolo_block.1.tip.conv', 'neck.yolo_block.1.tip.batch_norm']
2022-04-12 11:22:13,592-INFO: ['neck.yolo_transition.1.conv', 'neck.yolo_transition.1.batch_norm']
2022-04-12 11:22:13,592-INFO: ['neck.yolo_block.2.conv_module.conv0.conv', 'neck.yolo_block.2.conv_module.conv0.batch_norm']
2022-04-12 11:22:13,592-INFO: ['neck.yolo_block.2.conv_module.conv1.conv', 'neck.yolo_block.2.conv_module.conv1.batch_norm']
2022-04-12 11:22:13,592-INFO: ['neck.yolo_block.2.conv_module.conv2.conv', 'neck.yolo_block.2.conv_module.conv2.batch_norm']
2022-04-12 11:22:13,592-INFO: ['neck.yolo_block.2.conv_module.conv3.conv', 'neck.yolo_block.2.conv_module.conv3.batch_norm']
2022-04-12 11:22:13,592-INFO: ['neck.yolo_block.2.conv_module.route.conv', 'neck.yolo_block.2.conv_module.route.batch_norm']
2022-04-12 11:22:13,592-INFO: ['neck.yolo_block.2.tip.conv', 'neck.yolo_block.2.tip.batch_norm']
Traceback (most recent call last):
  File "tools/post_quant.py", line 96, in <module>
    main()
  File "tools/post_quant.py", line 84, in main
    cfg = build_slim_model(cfg, FLAGS.slim_config, mode='test')
  File "/home/ubuntu/lxd-storage/xzy/PaddleCV/PaddleDetection/ppdet/slim/__init__.py", line 59, in build_slim_model
    cfg['model'] = slim(model)
  File "/home/ubuntu/lxd-storage/xzy/PaddleCV/PaddleDetection/ppdet/slim/quant.py", line 75, in __call__
    model, fuse=self.fuse, fuse_list=self.fuse_list)
  File "/home/ubuntu/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddleslim/dygraph/quant/ptq.py", line 97, in quantize
    model=model, inplace=inplace, fuse=fuse, fuse_list=fuse_list)
  File "/home/ubuntu/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/contrib/slim/quantization/imperative/ptq.py", line 83, in quantize
    model = fuse_utils.fuse_layers(model, fuse_list)
  File "/home/ubuntu/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/contrib/slim/quantization/imperative/fuse_utils.py", line 51, in fuse_layers
    _fuse_layers(model, layers)
  File "/home/ubuntu/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/contrib/slim/quantization/imperative/fuse_utils.py", line 61, in _fuse_layers
    layer_list.append(getattr(parent_layer, sub_name))
  File "/home/ubuntu/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 1110, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Blocks' object has no attribute 'downsample.conv_bn_layer.conv'
```

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：

Paddle=2.2.2；PaddleDetection=2.3

2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：

Ubuntu

4. 请问您使用的Python版本是？/ Please provide the version of Python you used.

Python 3.7

5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.

10.1

---
补充：
追踪堆栈后发现该layer存在，认为是函数逻辑问题。

问题函数为find_parent_layer_and_sub_name，位于/paddle/fluid/contrib/slim/quantization/imperative/utils.py。该函数尝试找到”backbone.stage.0.downsample.conv_bn_layer.conv“对象，并返回该layer的上一layer，以及该层对象名。
该函数按照'.'切分名字，并逐步尝试当前layer的子layer是否有该名字。例如：当前层为"backbone"，则查找子layer”stage“，没有，则查找子layer”stage.0“。查找到”stage.0“则设置当前层为”stage.0“，继续查找。

在yolov3_darknet53模型中，backbone下同时具有stage.0和stage.0.downsample层。该对象应位于stage.0.downsample下。但函数会查找到”stage.0“layer，并返回对象parent_layer=Block stage.0和sub_name="downsample.conv_bn_layer.conv“。后续再次在stage.0中查找sub_name时就会报错。

不确定是否有其他模型存在相同问题。建议修改该函数逻辑，或制定好的命名方法使导出的layer_name具有唯一性。

**Comment by yghstill** [comment]
@Disciple7 感谢反馈，该问题我们修复下，请先使用QAT量化训练吧。

**Comment by czczmr** [comment]
AttributeError: 'Blocks' object has no attribute 'downsample.conv_bn_layer.conv'
这个问题还没有修复？
