### ISSUE TITLE
执行评估python tools/eval.py.....时的错误,求问如何解决？

### ISSUE THREAD

**Issue by HDU-CarryStar** [PaddlePaddle/PaddleDetection#5712]
.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/PPt/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/user/anaconda3/envs/PPt/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/anaconda3/envs/PPt/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 505, in _thread_loop
    batch = self._get_data()
  File "/home/user/anaconda3/envs/PPt/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 634, in _get_data
    batch.reraise()
  File "/home/user/anaconda3/envs/PPt/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 169, in reraise
    raise self.exc_type(msg)
ValueError: DataLoader worker(4) caught ValueError with message:
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/PPt/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 329, in _worker_loop
    batch = fetcher.fetch(indices)
  File "/home/user/anaconda3/envs/PPt/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 134, in fetch
    data = self.collate_fn(data)
  File "/media/user/date/DaXu/PaddleDetection/ppdet/data/reader.py", line 91, in __call__
    batch_data = default_collate_fn(data)
  File "/home/user/anaconda3/envs/PPt/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 70, in default_collate_fn
    for key in sample
  File "/home/user/anaconda3/envs/PPt/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 70, in <dictcomp>
    for key in sample
  File "/home/user/anaconda3/envs/PPt/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 58, in default_collate_fn
    batch = np.stack(batch, axis=0)
  File "<__array_function__ internals>", line 6, in stack
  File "/home/user/anaconda3/envs/PPt/lib/python3.7/site-packages/numpy/core/shape_base.py", line 426, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape

[04/15 16:38:49] ppdet.utils.checkpoint INFO: Finish loading model weights: output/picodet_l_416_voc_200/model_final.pdparams
Traceback (most recent call last):
  File "tools/eval.py", line 145, in <module>
    main()
  File "tools/eval.py", line 141, in main
    run(FLAGS, cfg)
  File "tools/eval.py", line 106, in run
    trainer.evaluate()
  File "/media/user/date/DaXu/PaddleDetection/ppdet/engine/trainer.py", line 492, in evaluate
    self._eval_with_loader(self.loader)
  File "/media/user/date/DaXu/PaddleDetection/ppdet/engine/trainer.py", line 466, in _eval_with_loader
    for step_id, data in enumerate(loader):
  File "/media/user/date/DaXu/PaddleDetection/ppdet/data/reader.py", line 209, in __next__
    return next(self.loader)
  File "/home/user/anaconda3/envs/PPt/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 697, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

**Comment by zoooo0820** [comment]
能否补充一下这些信息，方便我们排查定位一下具体问题：
- Paddle 及 PaddleDetection的版本
- 完整的执行命令
- 使用的数据集情况（格式、是否是自定义的数据等）或是代码上改动了哪些位置
