### ISSUE TITLE
🚀  PP-YOLOE高精度云边一体模型已经发布，欢迎大家试用讨论

### ISSUE THREAD

**Issue by wangxinxin08** [PaddlePaddle/PaddleDetection#5730]
🚀  PP-YOLOE是基于PP-YOLOv2的卓越的单阶段Anchor-free模型，超越了多种流行的yolo模型，更多细节可以参考[**PP-YOLOE文档**](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/ppyoloe/README_cn.md)以及技术报告[**PP-YOLOE论文**](https://arxiv.org/abs/2203.16250)。概括的说，PP-YOLOE具有以下特点：
1. **精度速度双高**
   - PP-YOLOE-l在COCO test-dev上精度可达**51.4 mAP**，速度可达**149FPS**
   - 精度速度性价比超越**YOLOv5, YOLOX**
2. **部署友好**
   - 具有**s/m/l/x**一系列的模型，可以适配不同算力的硬件，**V100，T4等服务端GPU**以及**Jetson系列和FPGA等边缘端芯片**
   - 避免使用DCN, Matrix NMS等特殊算子，方便部署到更多的硬件上
   - 支持**TensorRT部署**以及**ONNX导出**，提升部署易用性
3. **训练速度大幅提升**
   - 混合精度训练等优化大幅提升训练速度，相较于PP-YOLOv2**训练速度提升30%以上**
<img width="500" alt="ppyoloe_map_fps" src="https://user-images.githubusercontent.com/69842442/165039851-f5d3eed0-0939-4a38-8ffc-7ddd7c801413.png">
为了方便大家相互交流沟通，欢迎大家扫码加入微信群，相关意见、建议和使用中的疑问可以在微信群中交流或者在github中提issue

<img width="400" alt="wechat" src="https://user-images.githubusercontent.com/69842442/177932227-30022865-fff3-4971-84a2-fdf06ec86b71.jpg">

**Comment by trefoil0219** [comment]
![mmexport1650550595197](https://user-images.githubusercontent.com/55016894/164477993-83392f90-d544-4df6-a52d-839bed8a94b3.png)
从图上看不到这个节点的上下文，tvm解析时不知道该怎么做。

**Comment by wangxinxin08** [comment]
@populustremble 感谢反馈，该问题正在解决中

**Comment by wangxinxin08** [comment]
@populustremble paddle2onnx专门升级以修复了这个问题，请按照以下命令进行操作，稍后我们会加入到文档中
``` bash
pip install -U paddle2onnx
python -m paddle2onnx.optimize --input_model model.onnx --output_model new_model.onnx
```

**Comment by Reatris** [comment]
二维码过期辣

**Comment by wangxinxin08** [comment]
> 二维码过期辣

已经更新

**Comment by usmile1234** [comment]
二维码过期了

**Comment by jerrywgz** [comment]
二维码已更新

**Comment by janelu9** [comment]
https://github.com/PaddlePaddle/PaddleDetection/issues/5932
我有个问题在这里

**Comment by Liu2022** [comment]
二维码过期了 麻烦更新谢谢！

**Comment by YixinKristy** [comment]
二维码已更新

**Comment by zhangyingying520** [comment]
麻烦问一下，我用ppyolov2和ppyoloe使用相同的数据集，几乎都是使用套件里的默认配置，为什么ppyolov2能接近0.8，而ppyoloe只有0.5左右

**Comment by sdreamforchen** [comment]
大佬。请教个问题。  TOOD原文是没有在loss中除以t的，loss的格式整体和yoloe是不一样的（先不关心dfl）。为什么需要除以这个t呢？这俩精度差有多少呢？

**Comment by wangxinxin08** [comment]
t作为权重是乘到loss里面的，一般计算loss时会除以样本的数量，这里也就会额外除以t.sum，可以看TOOD的官方实现，这里是一致的

**Comment by triple-mu** [comment]
二维码过期了 麻烦更新谢谢！

**Comment by hhxdestiny** [comment]
> 二维码已更新

又过期了，麻烦更新一下

**Comment by wangxinxin08** [comment]
@triple-Mu @hhxdestiny 已经更新

**Comment by hhxdestiny** [comment]
**请问使用paddle inference推理耗时特别长，可能是什么原因？**

导出：python tools/export_model.py -c configs/ppyoloe/ppyoloe_crn_l_300e_coco.yml -o weights=https://paddledet.bj.bcebos.com/models/ppyoloe_crn_l_300e_coco.pdparams
测试（Windows **CPU**）：**deploy/cpp**
日志（每条/每张）:
```bash
det_times[0]: 8.983800ms, det_times[1]: 2206.521729ms, det_times[2]: 0.035300ms
det_times[0]: 6.902300ms, det_times[1]: 2199.024658ms, det_times[2]: 0.027300ms
det_times[0]: 7.725600ms, det_times[1]: 2197.617188ms, det_times[2]: 0.026800ms
det_times[0]: 7.406300ms, det_times[1]: 2196.207764ms, det_times[2]: 0.026600ms
det_times[0]: 8.291901ms, det_times[1]: 2204.030029ms, det_times[2]: 0.026000ms
det_times[0]: 7.019200ms, det_times[1]: 2198.109375ms, det_times[2]: 0.024400ms
```

**Comment by wangxinxin08** [comment]
> **请问使用paddle inference推理耗时特别长，可能是什么原因？**
> 
> 导出：python tools/export_model.py -c configs/ppyoloe/ppyoloe_crn_l_300e_coco.yml -o weights=https://paddledet.bj.bcebos.com/models/ppyoloe_crn_l_300e_coco.pdparams 测试（Windows **CPU**）：**deploy/cpp** 日志（每条/每张）:
> 
> ```shell
> det_times[0]: 8.983800ms, det_times[1]: 2206.521729ms, det_times[2]: 0.035300ms
> det_times[0]: 6.902300ms, det_times[1]: 2199.024658ms, det_times[2]: 0.027300ms
> det_times[0]: 7.725600ms, det_times[1]: 2197.617188ms, det_times[2]: 0.026800ms
> det_times[0]: 7.406300ms, det_times[1]: 2196.207764ms, det_times[2]: 0.026600ms
> det_times[0]: 8.291901ms, det_times[1]: 2204.030029ms, det_times[2]: 0.026000ms
> det_times[0]: 7.019200ms, det_times[1]: 2198.109375ms, det_times[2]: 0.024400ms
> ```

我们在Intel Xeon 6148上测过ppyoloe_l的速度为450ms左右，你可以打开mkldnn, 设置线程为4，并打开测速选项试下，--run_benchmark=True

**Comment by hhxdestiny** [comment]
> > **请问使用paddle inference推理耗时特别长，可能是什么原因？**
> > 导出：python tools/export_model.py -c configs/ppyoloe/ppyoloe_crn_l_300e_coco.yml -o weights=https://paddledet.bj.bcebos.com/models/ppyoloe_crn_l_300e_coco.pdparams 测试（Windows **CPU**）：**deploy/cpp** 日志（每条/每张）:
> > ```shell
> > det_times[0]: 8.983800ms, det_times[1]: 2206.521729ms, det_times[2]: 0.035300ms
> > det_times[0]: 6.902300ms, det_times[1]: 2199.024658ms, det_times[2]: 0.027300ms
> > det_times[0]: 7.725600ms, det_times[1]: 2197.617188ms, det_times[2]: 0.026800ms
> > det_times[0]: 7.406300ms, det_times[1]: 2196.207764ms, det_times[2]: 0.026600ms
> > det_times[0]: 8.291901ms, det_times[1]: 2204.030029ms, det_times[2]: 0.026000ms
> > det_times[0]: 7.019200ms, det_times[1]: 2198.109375ms, det_times[2]: 0.024400ms
> > ```
> 
> 我们在Intel Xeon 6148上测过ppyoloe_l的速度为450ms左右，你可以打开mkldnn, 设置线程为4，并打开测速选项试下，--run_benchmark=True

谢谢，我试试！另外我在导出onnx的时候也出现了问题：
NoteBook
```bash
# build deploy/cpp failed! export to onnx
# !pip install paddle2onnx
!cd work/PaddleDetection && paddle2onnx --model_dir output_inference/ppyoloe_crn_l_300e_coco --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 11 --save_file ppyoloe_crn_l_300e_coco.onnx
```
日志
```shell
2022-06-24 10:41:47 [WARNING]	[Deprecated] `paddle2onnx.command.program2onnx` will be deprecated in the future version, the recommended usage is `paddle2onnx.export`
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/bin/paddle2onnx", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/command.py", line 224, in main
    auto_update_opset=args.enable_auto_update_opset)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/command.py", line 144, in program2onnx
    from paddle2onnx.legacy.command import program2onnx
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/legacy/__init__.py", line 19, in <module>
    from .convert import dygraph2onnx, program2onnx
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/legacy/convert.py", line 23, in <module>
    from paddle2onnx.legacy.graph import PaddleGraph, ONNXGraph
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/legacy/graph/__init__.py", line 17, in <module>
    from .onnx_graph import ONNXGraph, ONNXNode
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/legacy/graph/onnx_graph.py", line 22, in <module>
    from paddle2onnx.legacy.constant import NodeDomain, PRODUCER, dtypes
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/legacy/constant/dtypes.py", line 17, in <module>
    from onnx import helper
ModuleNotFoundError: No module named 'onnx'
```

**Comment by wangxinxin08** [comment]
@hhxdestiny 看提示，没有安装onnx

**Comment by jiguanglu** [comment]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.


### bug描述 Describe the Bug

使用 ppyoloe_crn_s_400e_coco.yml   
训练8000多张1200*1600的图片, 单卡3090训练，base_lr: 0.005.    batch_size: 32
因为训练中出现一次错误，查了一下 issues 所以把ppyoloe_reader.yml里面的 num_works 设置为0；
 然后可以正常训练，但是训练时间提示为5天，而且lr变成0.024，不知道是什么情况；
![企业微信截图_79222c2d-b42f-4fd3-9404-345b394e0d30](https://user-images.githubusercontent.com/16578290/177682931-3af8aa2d-307e-410b-8402-932b0376f2fc.png)



### 复现环境 Environment

- PaddlePaddle: 2.2.2
- PaddleDetection: release/2.4
- Pyhton: 3.7.13
- CUDA: 11.1
- CUDNN: 8.0.2

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by wangxinxin08** [comment]
学习率的话，可以看下是不是配置被覆盖了，这里https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/ppyoloe/ppyoloe_crn_s_400e_coco.yml#L26 设置的学习率会覆盖optimizer的，另外，你的data_cost太大了，可以考虑把num_worker设置成4，另外，原先遇到了什么错误，可以发下看下

**Comment by jiguanglu** [comment]
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/ppyoloe/ppyoloe_crn_s_400e_coco.yml#L26

原先遇到的是下面链接里的问题：
https://github.com/PaddlePaddle/PaddleDetection/issues/6302

datacost 开始是3.4多，请问这里有什么设置技巧呢？
num_worker=4的话我会出现上面链接里的问题；
下面是我的配置信息，您看一下：
![企业微信截图_0541e4fe-d0fc-45e7-bf02-e977427e4144](https://user-images.githubusercontent.com/16578290/177722742-714446a4-514f-44d2-8705-35dceaa36dba.png)

**Comment by wangxinxin08** [comment]
学习率设置在26行，你自己设置的是0.025，然后你发的那个issue的问题和worker_num无关，worker_num设置成CPU核数一般就可以，可以4，6，8试下，看哪个data cost比较低

**Comment by jiguanglu** [comment]
> 学习率设置在26行，你自己设置的是0.025，然后你发的那个issue的问题和worker_num无关，worker_num设置成CPU核数一般就可以，可以4，6，8试下，看哪个data cost比较低

当我把worker_num设置为4之后，又出现了上面的错误；
![企业微信截图_82a2e3e0-48e5-4495-bb8f-ab6ec6a6e84b](https://user-images.githubusercontent.com/16578290/177734892-5ae8ed2e-79fd-4fcf-aeb2-be929907c8e7.png)

**Comment by wangxinxin08** [comment]
你可以设置下use_shared_memory等于False试下

**Comment by jiguanglu** [comment]
> 你可以设置下use_shared_memory等于False试下

设置了，还是会出现上面的问题；

**Comment by jiguanglu** [comment]
二维码过期，请更新一下哈；

**Comment by wangxinxin08** [comment]
> > 你可以设置下use_shared_memory等于False试下
> 
> 设置了，还是会出现上面的问题；

报错还有其他信息吗？截图信息看不出来问题是什么

**Comment by wangxinxin08** [comment]
> 二维码过期，请更新一下哈；

已经更新

**Comment by jiguanglu** [comment]
> 

没有其它错误了，我把num_work改回0了，就没事了；

> > > 你可以设置下use_shared_memory等于False试下
> > 
> > 
> > 设置了，还是会出现上面的问题；
> 
> 报错还有其他信息吗？截图信息看不出来问题是什么

没有其它错误了，我把num_work改回0了，就没事了；

**Comment by a18330229251** [comment]
大神 帮下忙 我使用Serving部署后 测试的时候报这个错:
failed to predict. Log_id: 0  Raise_msg:  invalid arg list  ClassName: Op.process.<locals>.feed_fetch_list_check_helper  FunctionName: feed_fetch_list_check_helper. **Please check the input dict** and checkout PipelineServingLogs/pipeline.log for more details.'
web_service.py:
![webservice](https://user-images.githubusercontent.com/15342896/184677777-b9c3451e-446b-481e-820d-d6d13ababb52.png)
http_test.py:
![http_test](https://user-images.githubusercontent.com/15342896/184677844-185a9b9b-a9cc-47c2-839e-e328a0d05379.png)

**Comment by rlewkowicz** [comment]
How do I train custom data? I'd say ultralytics yolov5 is one of the most popular yolo implementations, and they use the label/images split. So anyone coming here looking to explore a new yolo implementation, coming from the more popular implementations is going to be used to that data split. 

I converted my set to a coco format, but I don't know what this is: https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/configs/datasets/coco_instance.yml#L9
which is called here:
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/configs/ppyoloe/ppyoloe_plus_crn_s_80e_coco.yml#L2

I went and pulled the coco annotations, and this doesn't even exist. 

```
(base) ➜  annotations cat instances_val2017.json | jq '.' | grep gt_bbox
(base) ➜  annotations cat instances_train2017.json | jq '.' | grep gt_bbox
```
I'm not sure what I should be correlating here. Is there documentation on preparing a custom data set for training? Or especially converting a traditional yolo set to the coco format you're looking for. 

edit: never mind, I have to go read this https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/docs/feature_models/YOLOSERIES_MODEL_en.md#customdataset

**Comment by wangxinxin08** [comment]
@rlewkowicz Actually, all you need to do is converting your dataset to coco format or voc format while training your custom dataset. The data fields defined in [coco_detection.yml](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/configs/datasets/coco_detection.yml#L9) or [coco_instance.yml](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/configs/datasets/coco_instance.yml#L9) are extracted from the COCO dataset in [coco.py](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/ppdet/data/source/coco.py). Specially, [coco_detection.yml](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/configs/datasets/coco_detection.yml) is only for detection task while [coco_instance.yml](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/configs/datasets/coco_instance.yml) is also for instance segmentation task.

**Comment by 392875** [comment]
二维码过期，请更新一下
