### ISSUE TITLE
ValueError: (InvalidArgument) Input(X) of GridSampleOp should be 4-D Tensor, but received X dimension size(5)[Other General Issues]

### ISSUE THREAD

**Issue by GMfatcat** [PaddlePaddle/PaddleDetection#5747]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## 描述问题/Describe the bug
訓練mask_rcnn_res2net50_vd_26w_4s_fpn_2x_coco時一切正常，但是在eval.py 和 infer.py時出現這個錯誤

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?
   python tools/eval.py -c configs/res2net/mask_rcnn_res2net50_vd_26w_4s_fpn_2x_coco.yml -o weights=output/mask_rcnn_res2net50_vd_26w_4s_fpn_2x_coco/model_final.pdparams --classwise

   python tools/infer.py -c configs/res2net/mask_rcnn_res2net50_vd_26w_4s_fpn_2x_coco.yml --infer_dir=ship_test_img/ --output_dir=infer_output/ -o weights=output/mask_rcnn_res2net50_vd_26w_4s_fpn_2x_coco/model_final.pdparams --save_txt=Ture

2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.
無

3. 您使用的数据集是？/What dataset did you use?
自製的COCO格式數據集，只有一類，包含polygon 和 bbox。

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.
![image](https://user-images.githubusercontent.com/58526756/163914662-ee63d2c0-9b0d-4527-b5fb-aaf7210aa5d2.png)

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：

   paddledet            2.4.0
   paddlepaddle-gpu     2.2.2

3. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：
無

4. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：
Windows + conda

5. 请问您使用的Python版本是？/ Please provide the version of Python you used.
3.7.13

6. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.
CUDA 11.4
cuDNN 7.6

**Comment by jerrywgz** [comment]
可以发下配置文件和infer的启动命令嘛，我这边测试了下coco数据集上mask_rcnn_res2net50_vd_26w_4s_fpn_2x_coco 模型的eval和infer是正常的，用的paddledet release/2.4 分支，paddle 2.2.2版本

**Comment by GMfatcat** [comment]
config檔(github 不支援.yml 所以用.txt)
mask_rcnn_res2net50_vd_26w_4s_fpn_2x_coco.yml:
[coco_yml.txt](https://github.com/PaddlePaddle/PaddleDetection/files/8518136/coco_yml.txt)

optimizer_1x:
[optimizer_1x.txt](https://github.com/PaddlePaddle/PaddleDetection/files/8518138/optimizer_1x.txt)

coco_instance:
[coco_instance_yml.txt](https://github.com/PaddlePaddle/PaddleDetection/files/8518139/coco_instance_yml.txt)


mask_fpn_reader:
[mask_fpn_reader.txt](https://github.com/PaddlePaddle/PaddleDetection/files/8518142/mask_fpn_reader.txt)

mask_rcnn_r50_fpn:
[mask_rcnn_r50_fpn.txt](https://github.com/PaddlePaddle/PaddleDetection/files/8518143/mask_rcnn_r50_fpn.txt)

==================eval & infer command========================

python tools/eval.py -c configs/res2net/mask_rcnn_res2net50_vd_26w_4s_fpn_2x_coco.yml -o weights=output/mask_rcnn_res2net50_vd_26w_4s_fpn_2x_coco/model_final.pdparams --classwise

python tools/infer.py -c configs/res2net/mask_rcnn_res2net50_vd_26w_4s_fpn_2x_coco.yml --infer_dir=ship_test_img/ --output_dir=infer_output/ -o weights=output/mask_rcnn_res2net50_vd_26w_4s_fpn_2x_coco/model_final.pdparams --save_txt=Ture

**Comment by geekplusaa** [comment]
训练的时候遇到同样的问题
训练脚本
python -u tools/train.py -c configs/mask_rcnn/mask_rcnn_r50_vd_fpn_2x_coco_yumi.yml \
                        --use_vdl=true \
                        --vdl_log_dir=vdl_dir/scalar \
                        --eval \
                        -o use_gpu=true


报错信息
Traceback (most recent call last):
  File "tools/train.py", line 177, in <module>
    main()
  File "tools/train.py", line 173, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/home/geekplusa/ai/projects/github/paddle/PaddleDetection/ppdet/engine/trainer.py", line 485, in train
    self._eval_with_loader(self._eval_loader)
  File "/home/geekplusa/ai/projects/github/paddle/PaddleDetection/ppdet/engine/trainer.py", line 508, in _eval_with_loader
    outs = self.model(data)
  File "/home/geekplusa/anaconda3/envs/paddledet/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/geekplusa/anaconda3/envs/paddledet/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/geekplusa/ai/projects/github/paddle/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 75, in forward
    outs.append(self.get_pred())
  File "/home/geekplusa/ai/projects/github/paddle/PaddleDetection/ppdet/modeling/architectures/mask_rcnn.py", line 133, in get_pred
    bbox_pred, bbox_num, mask_pred = self._forward()
  File "/home/geekplusa/ai/projects/github/paddle/PaddleDetection/ppdet/modeling/architectures/mask_rcnn.py", line 119, in _forward
    origin_shape)
  File "/home/geekplusa/ai/projects/github/paddle/PaddleDetection/ppdet/modeling/post_process.py", line 239, in __call__
    im_h, im_w)
  File "/home/geekplusa/ai/projects/github/paddle/PaddleDetection/ppdet/modeling/post_process.py", line 212, in paste_mask
    img_masks = F.grid_sample(masks, grid, align_corners=False)
  File "/home/geekplusa/anaconda3/envs/paddledet/lib/python3.7/site-packages/paddle/nn/functional/vision.py", line 277, in grid_sample
    out = getattr(_C_ops, 'grid_sampler')(x, grid, *attrs)
ValueError: (InvalidArgument) Input(X) of GridSampleOp should be 4-D Tensor, but received X dimension size(5)
  [Hint: Expected x_dims.size() == 4, but received x_dims.size():5 != 4:4.] (at /paddle/paddle/fluid/operators/grid_sampler_op.cc:46)
  [operator < grid_sampler > error]

**Comment by geekplusaa** [comment]
paddlepaddle-gpu   2.2.2.post112

**Comment by wj1017090777** [comment]
我也遇到相同的问题

**Comment by wj1017090777** [comment]
@GMfatcat @jerrywgz 请问解决问题了吗  我是训练自己的数据集 出错，在类别为1，在训练时不会报错，只要一加上--eval就会报错，这使得我无法导出模型以及无法推理模型查看具体效果。有趣的是，我在验证时，将类别修改为2，就能导出模型并且 eval成功，但是map等为0

**Comment by GMfatcat** [comment]
@wj1017090777  我試了你的方法，類別修改之後還是不能跑。目前在ppdet已放棄訓練所有有mask的model，都訓練bbox而已

**Comment by tiancailin** [comment]
https://github.com/PaddlePaddle/PaddleDetection/pull/5649
这个up修复了这个bug，我昨天跑过，可通过eval、tools\infer 、 deploy\python\infer
pr没通过审核呢但是有具体修改方式，照抄即可

**Comment by GMfatcat** [comment]
@tiancailin 感謝提供，修改那兩行之後的確可以開始進入iter 0 之eval, 但隨即出現下列錯誤。
不過infer可以成功匯出帶有mask跟bbox之圖片。
![image](https://user-images.githubusercontent.com/58526756/169679271-40496f55-f2d3-4bcf-8ad5-bbc457cdbd4b.png)
