### ISSUE TITLE
PP-Tracking训练时进行eval报错

### ISSUE THREAD

**Issue by LegendSun0** [PaddlePaddle/PaddleDetection#5821]
运行命令：
CUDA_VISIBLE_DEVICES=3 python tools/train.py --config configs/mot/vehicle/fairmot_hrnetv2_w18_dlafpn_30e_576x320_bdd100kmot_vehicle.yml --use_vdl=True --vdl_log_dir=output/vdl_dir/scalar --eval

跑完一个epoch以后报错：
[04/24 08:52:26] ppdet.data.source.mot INFO: MOT dataset summary: 
[04/24 08:52:26] ppdet.data.source.mot INFO: OrderedDict([('car1.train', 33)])
[04/24 08:52:26] ppdet.data.source.mot INFO: Total images: 100
[04/24 08:52:26] ppdet.data.source.mot INFO: Image start index: OrderedDict([('car1.train', 0)])
[04/24 08:52:26] ppdet.data.source.mot INFO: Total identities: 34
[04/24 08:52:26] ppdet.data.source.mot INFO: Identity start index: OrderedDict([('car1.train', 0)])
[04/24 08:52:26] reader WARNING: Shared memory size is less than 1G, disable shared_memory in DataLoader
W0424 08:52:27.036528 22457 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.2, Runtime API Version: 10.2
W0424 08:52:27.043077 22457 device_context.cc:465] device: 0, cuDNN Version: 7.6.
[04/24 08:52:35] ppdet.utils.checkpoint INFO: Finish loading model weights: /root/.cache/paddle/weights/HRNet_W18_C_pretrained.pdparams
https://paddledet.bj.bcebos.com/models/pretrained/HRNet_W18_C_pretrained.pdparams
[04/24 08:52:35] ppdet.engine INFO: Epoch: [0] [0/8] learning_rate: 0.000000 loss: 15.519042 heatmap_loss: 2.984292 size_loss: 2.176330 offset_loss: 0.449540 det_loss: 3.651464 reid_loss: 3.749733 eta: 0:00:30 batch_cost: 0.7746 data_cost: 0.0004 ips: 15.4910 images/s
[04/24 08:52:46] ppdet.utils.checkpoint INFO: Save checkpoint: output/save_model_output
Traceback (most recent call last):
  File "tools/train.py", line 260, in <module>
    main()
  File "tools/train.py", line 254, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 192, in run
    trainer.train(FLAGS.eval)
  File "/home/nfs/syj/PaddleDetection/ppdet/engine/trainer.py", line 453, in train
    self._eval_dataset = self.cfg.EvalDataset
  File "/home/nfs/syj/PaddleDetection/ppdet/core/workspace.py", line 68, in __getattr__
    raise AttributeError("object has no attribute '{}'".format(key))
AttributeError: object has no attribute 'EvalDataset'

**Comment by LegendSun0** [comment]
我在https://github.com/PaddlePaddle/PaddleDetection/issues/3179中找到相关问题，但没有找到解决方法。

**Comment by nemonameless** [comment]
fairmot跟踪暂不支持--eval边训边验证，MOTA一般都最后epoch最高，建议训完后单独手动eval，
```
CUDA_VISIBLE_DEVICES=0 python tools/eval_mot.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml -o weights=output/fairmot_dla34_30e_1088x608/model_final.pdparams
```

**Comment by LegendSun0** [comment]
> 

好的，感谢您的回复！

**Comment by LegendSun0** [comment]
> fairmot暂不跟踪-评估边边验证，MOTA一般都一个时期，建议训练完后单独手动评估，
> 
> ```
> CUDA_VISIBLE_DEVICES=0 python tools/eval_mot.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml -o weights=output/fairmot_dla34_30e_1088x608/model_final.pdparams
> ```

好，谢谢您的回复！
