### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gong-bit** [PaddlePaddle/PaddleDetection#5826]
PPYOLOE训练时ValueError: (InvalidArgument) Currently, VarBase.__getitem__() only allows indexing by Integers, Slices, and tuples of these types, but received ellipsis in 1th slice item

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
W0424 19:56:40.440253  7483 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0424 19:56:40.445101  7483 device_context.cc:422] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "PaddleDetection/tools/train.py", line 177, in <module>
    main()
  File "PaddleDetection/tools/train.py", line 173, in main
    run(FLAGS, cfg)
  File "PaddleDetection/tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/home/aistudio/PaddleDetection/ppdet/engine/trainer.py", line 443, in train
    outputs = model(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 59, in forward
    out = self.get_loss()
  File "/home/aistudio/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 125, in get_loss
    return self._forward()
  File "/home/aistudio/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 88, in _forward
    yolo_losses = self.yolo_head(neck_feats, self.inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleDetection/ppdet/modeling/heads/ppyoloe_head.py", line 217, in forward
    return self.forward_train(feats, targets)
  File "/home/aistudio/PaddleDetection/ppdet/modeling/heads/ppyoloe_head.py", line 160, in forward_train
    ], targets)
  File "/home/aistudio/PaddleDetection/ppdet/modeling/heads/ppyoloe_head.py", line 319, in get_loss
    pred_bboxes=pred_bboxes.detach() * stride_tensor)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "<decorator-gen-278>", line 2, in forward
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 331, in _decorate_function
    return func(*args, **kwargs)
  File "/home/aistudio/PaddleDetection/ppdet/modeling/assigners/atss_assigner.py", line 139, in forward
    gt_centers = bbox_center(gt_bboxes.reshape([-1, 4])).unsqueeze(1)
  File "/home/aistudio/PaddleDetection/ppdet/modeling/bbox_utils.py", line 751, in bbox_center
    boxes_cx = (boxes[..., 0] + boxes[..., 2]) / 2
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 569, in __getitem__
    return self._getitem_index_not_tensor(item)
ValueError: (InvalidArgument) Currently, VarBase.__getitem__() only allows indexing by Integers, Slices, and tuples of these types, but received ellipsis in 1th slice item
  [Hint: Expected PyCheckInteger(slice_item) || ((((PyObject*)(slice_item))->ob_type) == &PySlice_Type) == true, but received PyCheckInteger(slice_item) || ((((PyObject*)(slice_item))->ob_type) == &PySlice_Type):0 != true:1.] (at /paddle/paddle/fluid/pybind/imperative.cc:430)

**Comment by ghostxsl** [comment]
请升级Paddle版本到2.2.2
