### ISSUE TITLE
PPYOLOE矩形训练及矩形推理问题

### ISSUE THREAD

**Issue by ForBetterDl** [PaddlePaddle/PaddleDetection#5831]
1.矩形训练问题，训练自己的数据集1024*256，转换为coco格式

默认方形训练时ppyoloe_reader.yml中batch_transforms:
    - BatchRandomResize: {target_size: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768], random_size: True, random_interp: True, **keep_ratio: False**}
   **此时可以正常训练。**

改为矩形训练时，修改**keep_ratio: True，**其他不变。
batch_transforms:
    - BatchRandomResize: {target_size: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768], random_size: True, random_interp: True, keep_ratio: True}
    
    - 使用 python tools/train.py -c configs/ppyoloe/ppyoloe_crn_s_300e_coco.yml --amp  --eval --use_vdl USE_VDL训练报错：
loading annotations into memory...
Done (t=0.17s)
creating index...
index created!
W0425 20:44:49.502167 13804 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.5, Runtime API Version: 11.1
W0425 20:44:49.515132 13804 device_context.cc:465] device: 0, cuDNN Version: 8.1.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "D:\Anaconda3\envs\Paddle\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\Anaconda3\envs\Paddle\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Anaconda3\envs\Paddle\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 212, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices,
  File "D:\Anaconda3\envs\Paddle\lib\site-packages\paddle\fluid\dataloader\fetcher.py", line 134, in fetch
    data = self.collate_fn(data)
  File "D:\Anaconda3\envs\Paddle\Project\PaddleMain\PaddleDetection2.4\ppdet\data\reader.py", line 91, in __call__
    batch_data = default_collate_fn(data)
  File "D:\Anaconda3\envs\Paddle\lib\site-packages\paddle\fluid\dataloader\collate.py", line 68, in default_collate_fn
    return {
  File "D:\Anaconda3\envs\Paddle\lib\site-packages\paddle\fluid\dataloader\collate.py", line 69, in <dictcomp>
    key: default_collate_fn([d[key] for d in batch])
  File "D:\Anaconda3\envs\Paddle\lib\site-packages\paddle\fluid\dataloader\collate.py", line 58, in default_collate_fn
    batch = np.stack(batch, axis=0)
  File "<__array_function__ internals>", line 5, in stack
  File "D:\Anaconda3\envs\Paddle\lib\site-packages\numpy\core\shape_base.py", line 427, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape
[04/25 20:44:52] ppdet.utils.checkpoint INFO: Finish loading model weights: output/ppyoloe_crn_s_300e_coco/best_model.pdparams

2.验证集矩形推理
是否直接修改ppyoloe_reader.yml
eval_height: &eval_height 640   ->&eval_height 160
eval_width: &eval_width 640
就是直接进行640*160的矩形推理了？

**Comment by wangxinxin08** [comment]
1. 训练keep_ratio为True需要加padding，建议你将BatchRandomResize的target_size设置成[[h1, w1], [h2, w2], [h3, w3]]
2. 验证集推理直接修改eval_height和eval_width即可

**Comment by ForBetterDl** [comment]
> 1. 训练keep_ratio为True需要加padding，建议你将BatchRandomResize的target_size设置成[[h1, w1], [h2, w2], [h3, w3]]
> 2. 验证集推理直接修改eval_height和eval_width即可

您的意思是keep_ratio为True时，resize到前面target_size大小时，需要padding短边到32的倍数，而代码中时没有自动做这个操作的。
可以使用keep_ratio为False,target_size设置成[[h1, w1], [h2, w2], [h3, w3]],其中新设置的宽，高都为32的整倍数。达到不需padding即可实现矩形训练，我的理解对吗？

**Comment by wangxinxin08** [comment]
@ForBetterDl 是的，keep_ratio为True的时候需要加上一个算子
