### ISSUE TITLE
关于由swin transformer作backbone的picodet导出及基于python预测的疑问

### ISSUE THREAD

**Issue by hobeter** [PaddlePaddle/PaddleDetection#5836]
尝试将picodet的backbone换成swin transformer。在`tools/train.py`以及`tools/eval.py`时训练、验证均正常(将得到的bbox可视化后认为应该是正常的)......但是在`tools/export.py`后，在基于python预测时，运行`deploy/python/infer.py`报错如下：

Traceback (most recent call last):

>   File "infer.py", line 560, in <module>
>     main()
>   File "infer.py", line 541, in main
>     detector.predict_image(img_list,visual=thevisual)
>   File "infer.py", line 214, in predict_image
>     result = self.predict()
>   File "infer.py", line 162, in predict
>     self.predictor.run()

ValueError: In user code:

>     File "tools/export_model.py", line 111, in <module>
>       main()
>     File "tools/export_model.py", line 107, in main
>       run(FLAGS, cfg)
>     File "tools/export_model.py", line 73, in run
>       trainer.export(FLAGS.output_dir)
>     File "/root/autodl-tmp/PaddleDetection/ppdet/engine/trainer.py", line 718, in export
>       static_model, pruned_input_spec = self._get_infer_cfg_and_input_spec(
>     File "/root/autodl-tmp/PaddleDetection/ppdet/engine/trainer.py", line 696, in _get_infer_cfg_and_input_spec
>       input_spec, static_model.forward.main_program,
>     File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 563, in main_program
>       concrete_program = self.concrete_program
>     File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 479, in concrete_program
>       return self.concrete_program_specify_input_spec(input_spec=None)
>     File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 516, in concrete_program_specify_input_spec
>       concrete_program, _ = self.get_concrete_program(
>     File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 427, in get_concrete_program
>       concrete_program, partial_program_layer = self._program_cache[cache_key]
>     File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 723, in __getitem__
>       self._caches[item] = self._build_once(item)
>     File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 709, in _build_once
>       concrete_program = ConcreteProgram.from_func_spec(
>     File "/root/miniconda3/lib/python3.8/site-packages/decorator.py", line 232, in fun
>       return caller(func, *(extras + args), **kw)
>     File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
>       return wrapped_func(*args, **kwargs)
>     File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
>       return func(*args, **kwargs)
>     File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 662, in from_func_spec
>       outputs = static_func(*inputs)
>     File "/tmp/tmpyy7cvy2r.py", line 99, in forward
>       out = paddle.jit.dy2static.convert_ifelse(self.training, true_fn_5,
>     File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
>       out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
>     File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
>       return true_fn(*true_args) if pred else false_fn(*false_args)
>     File "/tmp/tmpyy7cvy2r.py", line 82, in false_fn_5
>       ] = paddle.jit.dy2static.convert_while_loop(for_loop_condition_0,
>     File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 45, in convert_while_loop
>       loop_vars = _run_py_while(cond, body, loop_vars)
>     File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 59, in _run_py_while
>       loop_vars = body(*loop_vars)
>     File "/root/autodl-tmp/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 74, in forward
>       self.inputs = inp
>     File "/tmp/tmppdaach19.py", line 42, in get_pred
>       __return_value_0 = paddle.jit.dy2static.convert_ifelse(paddle.jit.
>     File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
>       out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
>     File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
>       return true_fn(*true_args) if pred else false_fn(*false_args)
>     File "/tmp/tmppdaach19.py", line 38, in false_fn_7
>       __return_value_0, output = paddle.jit.dy2static.convert_ifelse(self
>     File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
>       out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
>     File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
>       return true_fn(*true_args) if pred else false_fn(*false_args)
>     File "/root/autodl-tmp/PaddleDetection/ppdet/modeling/architectures/picodet.py", line 90, in get_pred
>       bbox_pred, bbox_num = self._forward()
>     File "/root/autodl-tmp/PaddleDetection/ppdet/modeling/architectures/picodet.py", line 64, in _forward
>       body_feats = self.backbone(self.inputs)
>     File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
>       return self._dygraph_call_func(*inputs, **kwargs)
>     File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
>       outputs = self.forward(*inputs, **kwargs)
>     File "/tmp/tmpf5ngivd9.py", line 64, in forward
>       [Ww, i, self, x, Wh] = paddle.jit.dy2static.convert_while_loop(
>     File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 45, in convert_while_loop
>       loop_vars = _run_py_while(cond, body, loop_vars)
>     File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 59, in _run_py_while
>       loop_vars = body(*loop_vars)
>     File "/root/autodl-tmp/PaddleDetection/ppdet/modeling/backbones/swin_transformer.py", line 727, in forward
>       layer = self.layers[i]
>     File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
>       return self._dygraph_call_func(*inputs, **kwargs)
>     File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
>       outputs = self.forward(*inputs, **kwargs)
>     File "/tmp/tmp3yhjwa6j.py", line 99, in forward
>       ] = paddle.jit.dy2static.convert_while_loop(for_loop_condition_4,
>     File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 45, in convert_while_loop
>       loop_vars = _run_py_while(cond, body, loop_vars)
>     File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 59, in _run_py_while
>       loop_vars = body(*loop_vars)
>     File "/root/autodl-tmp/PaddleDetection/ppdet/modeling/backbones/swin_transformer.py", line 512, in forward
>       blk.H, blk.W = H, W
>     File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
>       return self._dygraph_call_func(*inputs, **kwargs)
>     File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
>       outputs = self.forward(*inputs, **kwargs)
>     File "/root/autodl-tmp/PaddleDetection/ppdet/modeling/backbones/swin_transformer.py", line 345, in forward
>       x_windows, mask=attn_mask)  # nW*B, window_size*window_size, C
>     File "/root/autodl-tmp/PaddleDetection/ppdet/modeling/backbones/swin_transformer.py", line 132, in window_reverse
>       x = windows.reshape(
>     File "/root/miniconda3/lib/python3.8/site-packages/paddle/tensor/manipulation.py", line 2001, in reshape
>       return paddle.fluid.layers.reshape(x=x, shape=shape, name=name)
>     File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/layers/nn.py", line 6268, in reshape
>       helper.append_op(
>     File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
>       return self.main_program.current_block().append_op(*args, **kwargs)
>     File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3178, in append_op
>       op = Operator(
>     File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2224, in __init__
>       for frame in traceback.extract_stack():
> 
>     InvalidArgumentError: The 'shape' attribute in ReshapeOp is invalid. The input tensor X'size must be divisible by known capacity of 'shape'. But received X's shape = [529, 7, 7, 96], X's size = 2488416, 'shape' is [0, 23, 23, 7, 7, -1], known capacity of 'shape' is -13712209.
>       [Hint: Expected output_shape[unk_dim_idx] * capacity == -in_size, but received output_shape[unk_dim_idx] * capacity:0 != -in_size:-2488416.] (at /paddle/paddle/fluid/operators/reshape_op.cc:210)
>       [operator < reshape2 > error]

配置的EvalReader和TestReader如下：

> EvalReader:
>   sample_transforms:
>   - Decode: {}
>   - Resize: {interp: 2, target_size: [320, 320], keep_ratio: False}
>   - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
>   - Permute: {}
>   batch_transforms:
>   - PadBatch: {pad_to_stride: 32}
>   batch_size: 8
>   shuffle: false
> 
> 
> TestReader:
>   inputs_def:
>     image_shape: [1, 3, 320, 320]
>   sample_transforms:
>   - Decode: {}
>   - Resize: {interp: 2, target_size: [320, 320], keep_ratio: False}
>   - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
>   - Permute: {}
>   batch_transforms:
>   - PadBatch: {pad_to_stride: 32}
>   batch_size: 1
>   shuffle: false

EvalReader和TestReader基本一致，然而 tools/eval.py正常 但 导出后python/eval.py就报错了 ,,,
请问这是什么原因啊？是TestReader 的`image_shape: [1, 3, 320, 320]`有问题吗？还是???

请问该怎么解决啊🤔？

**Comment by hobeter** [comment]
经查看，似乎大概可能好像是这里
https://github.com/PaddlePaddle/PaddleDetection/blob/d2cfe893d984b744981083fb5b6e9fae45fb015a/ppdet/modeling/backbones/swin_transformer.py#L121-L135
其中的B会出现问题(会出现0和-1)
我将https://github.com/PaddlePaddle/PaddleDetection/blob/d2cfe893d984b744981083fb5b6e9fae45fb015a/ppdet/modeling/backbones/swin_transformer.py#L131
替换成
`    B=1`
就可以正常运行(当然，是在确定batch为1的情况下)

不是很熟练掌握swin transformer的原理,,,请问这样改ok吗？有更好的修改方法吗？
