### ISSUE TITLE
去掉学习率衰减否定 trainpy文件无法运行

### ISSUE THREAD

**Issue by mursance** [PaddlePaddle/PaddleDetection#5841]
！PiecewiseDecay 否定！去掉后!python tools/train.py -c ../configs/ppyolov2_r50vd_dcn_voc.yml 命令无法运行
LearningRate:
  base_lr: 0.00333
  schedulers:
  - PiecewiseDecay
    gamma: 0.1
    milestones:
    - 466
    - 516
  - !LinearWarmup
    start_factor: 0.
    steps: 4000
----------------------------------------------------------------------------------------------------------------
下面是报错
Traceback (most recent call last):
  File "tools/train.py", line 177, in <module>
    main()
  File "tools/train.py", line 132, in main
    cfg = load_config(FLAGS.config)
  File "/home/aistudio/PaddleDetection/ppdet/core/workspace.py", line 114, in load_config
    cfg = _load_config_with_base(file_path)
  File "/home/aistudio/PaddleDetection/ppdet/core/workspace.py", line 79, in _load_config_with_base
    file_cfg = yaml.load(f, Loader=yaml.Loader)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/constructor.py", line 41, in get_single_data
    node = self.get_single_node()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/parser.py", line 403, in parse_indentless_sequence_entry
    if self.check_token(BlockEntryToken):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/yaml/scanner.py", line 579, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "../configs/ppyolov2_r50vd_dcn_voc.yml", line 28, column 10

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/optimizer.py#L267
PiecewiseDecay是必选项，如果不想用衰减，可以设置 milestones 为一个巨大的或至少大于epoch数的值
https://github.com/PaddlePaddle/PaddleDetection/blob/f06c929055c6979f8b1ca2bb3e97751f18fcfb2c/ppdet/optimizer.py#L114
