### ISSUE TITLE
[yolov4 裁减] RecursionError: maximum recursion depth exceeded in __subclasscheck__

### ISSUE THREAD

**Issue by jiaerwang0328** [PaddlePaddle/PaddleDetection#5898]
**PaddleDetection team appreciate any suggestion or problem you delivered~**
## 描述问题/Describe the bug
反复执行prune_walker中函数。

```
W0507 11:11:37.409078 31916 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.4, Runtime API Version: 10.1
W0507 11:11:37.449249 31916 device_context.cc:465] device: 0, cuDNN Version: 7.6.
INFO:__main__:pruned params: ['yolo_output.2.conv.1.weights']
INFO:__main__:pruned ratios: [0.5]
2022-05-07 11:11:39,945-INFO: pruning: yolo_output.2.conv.1.weights
Traceback (most recent call last):
  File "slim/prune/prune.py", line 427, in <module>
    main()
  File "slim/prune/prune.py", line 227, in main
    only_graph=False)[0]
  File "/media/wrr/E/linux/software_package/soft_install/anaconda3/envs/paddleslim/lib/python3.7/site-packages/paddleslim/prune/pruner.py", line 98, in prune
    visited)[0]  # [(name, axis, pruned_idx)]
  File "/media/wrr/E/linux/software_package/soft_install/anaconda3/envs/paddleslim/lib/python3.7/site-packages/paddleslim/prune/group_param.py", line 88, in collect_convs
    walker.prune(param, pruned_axis=0, pruned_idx=[])
  File "/media/wrr/E/linux/software_package/soft_install/anaconda3/envs/paddleslim/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 57, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/media/wrr/E/linux/software_package/soft_install/anaconda3/envs/paddleslim/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 163, in _prune
    self._prune_op(op, output_var, channel_axis, pruned_idx)
  File "/media/wrr/E/linux/software_package/soft_install/anaconda3/envs/paddleslim/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 103, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/media/wrr/E/linux/software_package/soft_install/anaconda3/envs/paddleslim/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 57, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/media/wrr/E/linux/software_package/soft_install/anaconda3/envs/paddleslim/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 308, in _prune
    self._visit_and_search(in_var, y_pruned_axis, pruned_idx)
  File "/media/wrr/E/linux/software_package/soft_install/anaconda3/envs/paddleslim/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 77, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/media/wrr/E/linux/software_package/soft_install/anaconda3/envs/paddleslim/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 103, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/media/wrr/E/linux/software_package/soft_install/anaconda3/envs/paddleslim/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 57, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/media/wrr/E/linux/software_package/soft_install/anaconda3/envs/paddleslim/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 604, in _prune
    self._prune_op(op, out_var, pruned_axis, pruned_idx)
  File "/media/wrr/E/linux/software_package/soft_install/anaconda3/envs/paddleslim/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 103, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/media/wrr/E/linux/software_package/soft_install/anaconda3/envs/paddleslim/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 57, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/media/wrr/E/linux/software_package/soft_install/anaconda3/envs/paddleslim/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 437, in _prune
    self._prune_op(op, in_var, pruned_axis, pruned_idx)
  File "/media/wrr/E/linux/software_package/soft_install/anaconda3/envs/paddleslim/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 103, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/media/wrr/E/linux/software_package/soft_install/anaconda3/envs/paddleslim/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 57, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/media/wrr/E/linux/software_package/soft_install/anaconda3/envs/paddleslim/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 292, in _prune
    self._visit_and_search(in_var, actual_axis, pruned_idx)
  File "/media/wrr/E/linux/software_package/soft_install/anaconda3/envs/paddleslim/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 74, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/media/wrr/E/linux/software_package/soft_install/anaconda3/envs/paddleslim/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 103, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/media/wrr/E/linux/software_package/soft_install/anaconda3/envs/paddleslim/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 57, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/media/wrr/E/linux/software_package/soft_install/anaconda3/envs/paddleslim/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 442, in _prune
    self._prune_op(op, out_var, pruned_axis, pruned_idx)
  File "/media/wrr/E/linux/software_package/soft_install/anaconda3/envs/paddleslim/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 103, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/media/wrr/E/linux/software_package/soft_install/anaconda3/envs/paddleslim/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 57, in prune
    self._prune(var, pruned_axis, pruned_idx)
  File "/media/wrr/E/linux/software_package/soft_install/anaconda3/envs/paddleslim/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 367, in _prune
    self._visit_and_search(out_var, pruned_axis, pruned_idx)
  File "/media/wrr/E/linux/software_package/soft_install/anaconda3/envs/paddleslim/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 77, in _visit_and_search
    self._prune_op(op, var, axis, transforms)
  File "/media/wrr/E/linux/software_package/soft_install/anaconda3/envs/paddleslim/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 103, in _prune_op
    walker.prune(var, pruned_axis, pruned_idx)
  File "/media/wrr/E/linux/software_package/soft_install/anaconda3/envs/paddleslim/lib/python3.7/site-packages/paddleslim/prune/prune_walker.py", line 57, in prune

..........
RecursionError: maximum recursion depth exceeded while calling a Python object

```

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?

```
python slim/prune/prune.py   -c  ./configs/yolov4/yolov4_cspdarknet_boat.yml \
--pruned_params="yolo_output.2.conv.1.weights" \
--pruned_ratios="0.5"  \
-o pretrain_weights=output/yolov4_cspdarknet_boat_0.001/model_final
```

2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.

3. 您使用的数据集是？/What dataset did you use?
个人数据集
4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
Paddle2.2,PaddleDetection2.4
2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：
Linux
4. 请问您使用的Python版本是？/ Please provide the version of Python you used.
python3.7
5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.
cuda10.2，cudnn7.6

**Comment by lrp123456** [comment]
@jiaerwang0328 您好，请问您是如何解决这个问题的，我出现了类似的问题
