### ISSUE TITLE
敏感度分析 AttributeError: 'NoneType' object has no attribute '_var'

### ISSUE THREAD

**Issue by liupeng0606** [PaddlePaddle/PaddleDetection#5900]
执行文档中的

```
python slim/prune/prune.py \
-c ./configs/yolov3_mobilenet_v1_voc.yml \
--pruned_params "yolo_block.0.0.0.conv.weights,yolo_block.0.0.1.conv.weights,yolo_block.0.1.0.conv.weights" \
--pruned_ratios="0.2,0.3,0.4"
```

出现下面的问题：

```
Traceback (most recent call last):
  File "slim/prune/prune.py", line 427, in <module>
    main()
  File "slim/prune/prune.py", line 221, in main
    train_prog = pruner.prune(
  File "/home/liu/anaconda3/envs/padd/lib/python3.8/site-packages/paddleslim/prune/pruner.py", line 88, in prune
    collections = StaticPruningCollections(params, graph)
  File "/home/liu/anaconda3/envs/padd/lib/python3.8/site-packages/paddleslim/prune/collections.py", line 243, in __init__
    self._collections = self.create_pruning_collections(
  File "/home/liu/anaconda3/envs/padd/lib/python3.8/site-packages/paddleslim/prune/collections.py", line 182, in create_pruning_collections
    leaves = self._find_leaves(graph)
  File "/home/liu/anaconda3/envs/padd/lib/python3.8/site-packages/paddleslim/prune/collections.py", line 136, in _find_leaves
    if len(_var.outputs()) == 0:
  File "/home/liu/anaconda3/envs/padd/lib/python3.8/site-packages/paddleslim/core/graph_wrapper.py", line 103, in outputs
    if self in op.all_inputs():
  File "/home/liu/anaconda3/envs/padd/lib/python3.8/site-packages/paddleslim/core/graph_wrapper.py", line 67, in __eq__
    return self._var.name == other._var.name
AttributeError: 'NoneType' object has no attribute '_var'

```

**Comment by yangdhll** [comment]
我也出现了这个问题，兄弟解决了嘛
