### ISSUE TITLE
[Other General Issues] 新版本picodet 使用 keep_ratio: True 训练报错

### ISSUE THREAD

**Issue by Gmgge** [PaddlePaddle/PaddleDetection#5937]
如果使用keep_ratio: False 训练正常；
如果使用keep_ratio: True，并根据先前问题讨论在resize之后添加- PadBatch: {pad_to_stride: 32}
依然报错
Traceback (most recent call last):
  File "/opt/anaconda3/envs/gm_py37/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 329, in _worker_loop
    batch = fetcher.fetch(indices)
  File "/opt/anaconda3/envs/gm_py37/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 134, in fetch
    data = self.collate_fn(data)
  File "/data0/gm/project/detect/PaddleDetection-release-2.4/ppdet/data/reader.py", line 79, in __call__
    raise e
  File "/data0/gm/project/detect/PaddleDetection-release-2.4/ppdet/data/reader.py", line 73, in __call__
    data = f(data)
  File "/data0/gm/project/detect/PaddleDetection-release-2.4/ppdet/data/transform/operators.py", line 103, in __call__
    sample[i] = self.apply(sample[i], context)
  File "/data0/gm/project/detect/PaddleDetection-release-2.4/ppdet/data/transform/operators.py", line 392, in apply
    im -= mean
ValueError: operands could not be broadcast together with shapes (448,448,32) (1,1,3) (448,448,32)
是否是因为最后一个维度也pad到32维度的倍数了？

**Comment by Gmgge** [comment]
#4774

**Comment by Gmgge** [comment]
[根据](https://github.com/PaddlePaddle/PaddleDetection/blob/a6acb959926e2dceae09ccb250d388558b9b90ed/docs/advanced_tutorials/READER_en.md#3data-preprocessing)此处说明 PadBatch被建议放在Permute之后，因为PadBatch默认图像为CHW
