### ISSUE TITLE
SSD_mobilenet_V1的剪枝效果差

### ISSUE THREAD

**Issue by Jiashuhao518** [PaddlePaddle/PaddleDetection#5983]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

之前已经根据静态图分析的敏感度调整pruned ratios，但是FLOPS 的pruned ratio很少只有0.02，相比官方给的yolo3demo 0.几的剪切率相差太多了

**Comment by zhiboniu** [comment]
你好，mobilenet网络结构本身已经非常稀疏，所以相比普通卷积的模型可裁剪性本身少很多。

**Comment by Jiashuhao518** [comment]
> 你好，mobilenet网络结构本身已经非常稀疏，所以相比普通卷积的模型可裁剪性本身少很多。

好的，还想请教一下您 mobilenetV1在模型压缩上还有什么可行的方法，因为需要部署在边缘端（目前只做了8bit量化 然后剪枝效果一般）

**Comment by w77779999** [comment]
你好，想问一下你是怎么分析SSD_mobilenet_V1中的可分离卷积层的敏感度的呢？因为原来的静态图分析敏感度的ppdet好像只支持普通卷积层的分析

**Comment by Jiashuhao518** [comment]
> 你好，想问一下你是怎么分析SSD_mobilenet_V1中的可分离卷积层的敏感度的呢？因为原来的静态图分析敏感度的ppdet好像只支持普通卷积层的分析

分析普通卷积层 他会关联到附近的DW卷积层

**Comment by w77779999** [comment]
> > 你好，想问一下你是怎么分析SSD_mobilenet_V1中的可分离卷积层的敏感度的呢？因为原来的静态图分析敏感度的ppdet好像只支持普通卷积层的分析
> 
> 分析普通卷积层 他会关联到附近的DW卷积层

SSD_mobilenet_V1这边除了第一层conv1_weights，后面从conv2_1_dw_weights一直到conv7_4_extra2_weights应该都是可分离卷积层，这中间的单独拿出dw或者sep层去分析敏感度都会报错，好像跟参数配置有关，想请教一下你是怎么解决的

**Comment by Jiashuhao518** [comment]
> 的

sep层和conv7_1之后的层肯定是可以分析的 而且分析是在静态图下做的 一般不会有问题

**Comment by Jiashuhao518** [comment]
> > > 你好，想问一下你是怎么分析SSD_mobilenet_V1中的可分离卷积层的敏感度的呢？因为原来的静态图分析敏感度的ppdet好像只支持普通卷积层的分析
> > 
> > 
> > 分析普通卷积层 他会关联到附近的DW卷积层
> 
> SSD_mobilenet_V1这边除了第一层conv1_weights，后面从conv2_1_dw_weights一直到conv7_4_extra2_weights应该都是可分离卷积层，这中间的单独拿出dw或者sep层去分析敏感度都会报错，好像跟参数配置有关，想请教一下你是怎么解决的

sep层和conv7_1之后的层肯定是可以分析的 而且分析是在静态图下做的 一般不会有问题

**Comment by w77779999** [comment]
我目前是使用paddledetection 2.4 static文件夹内的ppdet以及config里的ssd_mobilenetv1的yml文件，paddleslim目前采用2.1.0版本，如果更高版本出现过key error[0]的问题，如下
Traceback (most recent call last):
  File "slim/sensitive/sensitive.py", line 203, in <module>
    main()
  File "slim/sensitive/sensitive.py", line 160, in main
    pruned_ratios=pruned_ratios)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/sensitive.py", line 103, in sensitivity
    param_backup=True)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/pruner.py", line 101, in prune
    ratios)  # name, axis, idx, transform
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/idx_selector.py", line 50, in default_idx_selector
    score = scores[name][axis]
KeyError: 0

用2.1.0版本的paddleslim分析conv7_1_extra1_weights敏感度时会出现Unsupport for pruning depthwise conv2d directly错误。
你那边是使用什么配置以及有哪些修改呢

**Comment by Jiashuhao518** [comment]
> 我目前是使用paddledetection 2.4 static文件夹内的ppdet以及config里的ssd_mobilenetv1的yml文件，paddleslim目前采用2.1.0版本，如果更高版本出现过key error[0]的问题，如下 Traceback (most recent call last): File "slim/sensitive/sensitive.py", line 203, in main() File "slim/sensitive/sensitive.py", line 160, in main pruned_ratios=pruned_ratios) File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/sensitive.py", line 103, in sensitivity param_backup=True) File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/pruner.py", line 101, in prune ratios) # name, axis, idx, transform File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/idx_selector.py", line 50, in default_idx_selector score = scores[name][axis] KeyError: 0
> 
> 用2.1.0版本的paddleslim分析conv7_1_extra1_weights敏感度时会出现Unsupport for pruning depthwise conv2d directly错误。 你那边是使用什么配置以及有哪些修改呢

你尝试一下paddledetection2.1 因为可能有版本对应的问题

**Comment by w77779999** [comment]
好的，问题已解决，感谢你的回答

**Comment by w77779999** [comment]
你好，想问一下你有碰到过某几层的敏感度分析从0.1到0.9损失全是0的情况吗？

**Comment by Jiashuhao518** [comment]
> 你好，想问一下你有碰到过某几层的敏感度分析从0.1到0.9损失全是0的情况吗？

有的

**Comment by Jiashuhao518** [comment]
> 你好，想问一下你有碰到过某几层的敏感度分析从0.1到0.9损失全是0的情况吗？

不知道你有没有遇到剪枝后评估的时候 通道数不匹配的问题 我现在还解决不了

**Comment by w77779999** [comment]
> 

我这边是分析完之后拿到正式的地方去剪，算出来的计算量减少的很少，跟预期不太符合

**Comment by Jiashuhao518** [comment]
> > 
> 
> 我这边是分析完之后拿到正式的地方去剪，算出来的计算量减少的很少，跟预期不太符合

动态图吗  动态图我不知道如何把剪枝和量化做在一起 因为没有提供联合策略

**Comment by w77779999** [comment]
> > > 
> > 
> > 
> > 我这边是分析完之后拿到正式的地方去剪，算出来的计算量减少的很少，跟预期不太符合
> 
> 动态图吗 动态图我不知道如何把剪枝和量化做在一起 因为没有提供联合策略

可以参考那个蒸馏加剪枝的来写，但是试过来不太行

**Comment by Jiashuhao518** [comment]
> > > > 
> > > 
> > > 
> > > 我这边是分析完之后拿到正式的地方去剪，算出来的计算量减少的很少，跟预期不太符合
> > 
> > 
> > 动态图吗 动态图我不知道如何把剪枝和量化做在一起 因为没有提供联合策略
> 
> 可以参考那个蒸馏加剪枝的来写，但是试过来不太行

那么分开怎么做呢 是先做剪枝 然后在量化的yml里面把预训练权重换成剪枝后的权重吗

**Comment by w77779999** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 我这边是分析完之后拿到正式的地方去剪，算出来的计算量减少的很少，跟预期不太符合
> > > 
> > > 
> > > 动态图吗 动态图我不知道如何把剪枝和量化做在一起 因为没有提供联合策略
> > 
> > 
> > 可以参考那个蒸馏加剪枝的来写，但是试过来不太行
> 
> 那么分开怎么做呢 是先做剪枝 然后在量化的yml里面把预训练权重换成剪枝后的权重吗

它的剪枝其实在build_slim_config的时候如果你设置了就直接做掉了，量化好像只是加入了fake还有moving的节点，我是先剪了然后量化

**Comment by w77779999** [comment]
你把静态图的权重拿过去分析，分析出来的map是对的吗？我这边好像是不行

**Comment by Jiashuhao518** [comment]
> 你把静态图的权重拿过去分析，分析出来的map是对的吗？我这边好像是不行

你先去打印动态图的权重 再去对比一下静态图的命名  其实就是名字不一样

**Comment by w77779999** [comment]
> 

名字不一样我知道，我的意思是敏感度分析它会先分析原来权重的精准度，这里你拿静态图的权重过去分析准确率没问题吗，我这边会就0.01map

**Comment by Jiashuhao518** [comment]
> > 
> 
> 名字不一样我知道，我的意思是敏感度分析它会先分析原来权重的精准度，这里你拿静态图的权重过去分析准确率没问题吗，我这边会就0.01map

我之前动态图剪的结果是map 68% 静态图剪了却不能评估

**Comment by w77779999** [comment]
> 

这就不太清楚了，我这边原本提供的预训练权重如果直接拿过去分析敏感度，算出来的map也是0.01

**Comment by w77779999** [comment]
我现在分析过来好像有些层就算写在剪枝里面它也不会去剪，不知道你有没有碰到这种情况

**Comment by Jiashuhao518** [comment]
> 我现在分析过来好像有些层就算写在剪枝里面它也不会去剪，不知道你有没有碰到这种情况

有这种情况的

**Comment by Jiashuhao518** [comment]
> > 
> 
> 这就不太清楚了，我这边原本提供的预训练权重如果直接拿过去分析敏感度，算出来的map也是0.01

是不是剪的太多了呢

**Comment by w77779999** [comment]
> 

不是，就拿32位啥也没做的权重过去分析的

**Comment by w77779999** [comment]
敏感度分析这边我看backbone的层基本上都不太能减的样子，损失挺大的好像

**Comment by Jiashuhao518** [comment]
> 敏感度分析这边我看backbone的层基本上都不太能减的样子，损失挺大的好像

mobilenet的特点 因为本身就很稀疏 没啥可以剪的

**Comment by w77779999** [comment]
> > 敏感度分析这边我看backbone的层基本上都不太能减的样子，损失挺大的好像
> 
> mobilenet的特点 因为本身就很稀疏 没啥可以剪的

分析出来能剪的层好像有些paddledetection都不剪，导致整体剪枝率挺低的感觉，还有你动态图剪完map 68，剪枝率高吗

**Comment by Jiashuhao518** [comment]
> > > 敏感度分析这边我看backbone的层基本上都不太能减的样子，损失挺大的好像
> > 
> > 
> > mobilenet的特点 因为本身就很稀疏 没啥可以剪的
> 
> 分析出来能剪的层好像有些paddledetection都不剪，导致整体剪枝率挺低的感觉，还有你动态图剪完map 68，剪枝率高吗

剪枝率0.21

**Comment by w77779999** [comment]
> > > > 敏感度分析这边我看backbone的层基本上都不太能减的样子，损失挺大的好像
> > > 
> > > 
> > > mobilenet的特点 因为本身就很稀疏 没啥可以剪的
> > 
> > 
> > 分析出来能剪的层好像有些paddledetection都不剪，导致整体剪枝率挺低的感觉，还有你动态图剪完map 68，剪枝率高吗
> 
> 剪枝率0.21

你是剪哪些层啊，感觉那些backbone不剪之后剩下的层按敏感度分析过来感觉剪枝率高不到哪里去

**Comment by Jiashuhao518** [comment]
> > > > > 敏感度分析这边我看backbone的层基本上都不太能减的样子，损失挺大的好像
> > > > 
> > > > 
> > > > mobilenet的特点 因为本身就很稀疏 没啥可以剪的
> > > 
> > > 
> > > 分析出来能剪的层好像有些paddledetection都不剪，导致整体剪枝率挺低的感觉，还有你动态图剪完map 68，剪枝率高吗
> > 
> > 
> > 剪枝率0.21
> 
> 你是剪哪些层啊，感觉那些backbone不剪之后剩下的层按敏感度分析过来感觉剪枝率高不到哪里去

我是剪了backbone的  我最大的疑惑是 动态图可以剪backbone后评估结果  但是静态图剪了backbone不能评估

**Comment by w77779999** [comment]
你的不能评估是什么意思，是map特别低吗？

**Comment by Jiashuhao518** [comment]
> 你的不能评估是什么意思，是map特别低吗？

不是 静态图评估直接报错 因为剪了backbone会导致通道数不匹配
InvalidArgumentError: The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 32, the input's shape is [32, 32, 150, 150]; the filter's channels is 1, the filter's shape is [32, 1, 3, 3]; the groups is 26, the data_format is NCHW. The error may come from wrong data_format setting.
  [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:32 != filter_dims[1] * groups:26.] (at /paddle/paddle/fluid/operators/conv_op.cc:119)
  [operator < depthwise_conv2d > error]

**Comment by w77779999** [comment]
感觉paddledetection写的时候不太支持静态的剪？因为paddle剪动态的时候伴随通道调整，静态这里有点像是没调整好的样子？还有就是动静剪的方式不太一样可能用的指令不太对？

**Comment by Jiashuhao518** [comment]
> 感觉paddledetection写的时候不太支持静态的剪？因为paddle剪动态的时候伴随通道调整，静态这里有点像是没调整好的样子？还有就是动静剪的方式不太一样可能用的指令不太对？
请问你能告诉我一下 从动态图剪枝后到量化的步骤吗  我还是不怎么清楚怎么做 谢谢

**Comment by Jiashuhao518** [comment]
https://github.com/PaddlePaddle/PaddleSlim/issues/900  不知道paddle有没有在paddleslim 2.1修复这个问题

**Comment by Jiashuhao518** [comment]
> 你好，mobilenet网络结构本身已经非常稀疏，所以相比普通卷积的模型可裁剪性本身少很多。

请问一下 InvalidArgumentError: The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 256, the input's shape is [32, 256, 125, 4]; the filter's channels is 1, the filter's shape is [256, 1, 3, 3]; the groups is 205, the data_format is NCHW. The error may come from wrong data_format setting.
[Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:256 != filter_dims[1] * groups:205.] (at D:\v2.0.1\paddle\paddle\fluid\operators\conv_op.cc:96)
[operator < depthwise_conv2d > error]
在静态图中对ssd mobilenetv1剪枝出现的通道不匹配问题该如何解决

**Comment by w77779999** [comment]
> 请问你能告诉我一下 从动态图剪枝后到量化的步骤吗 我还是不怎

我自己做就是参考那个蒸馏加剪枝的，因为创建剪枝和量化都是调用ppdet里slim的init那个py，里面会检测你slim的类别，可以自己输入一个类别，检测到后做指定的操作，做的也不一定对就是了

**Comment by Jiashuhao518** [comment]
> > 请问你能告诉我一下 从动态图剪枝后到量化的步骤吗 我还是不怎
> 
> 我自己做就是参考那个蒸馏加剪枝的，因为创建剪枝和量化都是调用ppdet里slim的init那个py，里面会检测你slim的类别，可以自己输入一个类别，检测到后做指定的操作，做的也不一定对就是了

我也是这么做的  我创建了一个 QATPrune的类 但是运行的时候说没有registered什么的

**Comment by w77779999** [comment]
给create传的参数不能是QATPrune，这个只能用于判断slim_load_cfg['slim']是否是你这个情况，下面传的参数要换成普通的QAT，Prune这些

**Comment by w77779999** [comment]
静态图剪枝你是在paddledetection上面做吗，还是在自己这边重新搭建模型用paddleslim做的？

**Comment by Jiashuhao518** [comment]
> 静态图剪枝你是在paddledetection上面做吗，还是在自己这边重新搭建模型用paddleslim做的？

静态图是static文件下做的

**Comment by w77779999** [comment]
> > 静态图剪枝你是在paddledetection上面做吗，还是在自己这边重新搭建模型用paddleslim做的？
> 
> 静态图是static文件下做的

static下面那指令呢？因为动转静后生成的文件有4个，infer_cfg.yml，model.pdiparams，model.pdiparams.info，model.pdmodel，在config的yml里面weight你是直接指向存这四个文件的文件夹这样吗？
因为static里面ssd的yml和外面的yml其实写的不太一样，你拿动态图训练好转成静态图生成这些文件后，拿这些文件到静态图去算卷积敏感度，最开始算出来的map是和你原本动态图训练出来的map一样是吗

**Comment by Jiashuhao518** [comment]
> > > 静态图剪枝你是在paddledetection上面做吗，还是在自己这边重新搭建模型用paddleslim做的？
> > 
> > 
> > 静态图是static文件下做的
> 
> static下面那指令呢？因为动转静后生成的文件有4个，infer_cfg.yml，model.pdiparams，model.pdiparams.info，model.pdmodel，在config的yml里面weight你是直接指向存这四个文件的文件夹这样吗？ 因为static里面ssd的yml和外面的yml其实写的不太一样，你拿动态图训练好转成静态图生成这些文件后，拿这些文件到静态图去算卷积敏感度，最开始算出来的map是和你原本动态图训练出来的map一样是吗
我也是参考的这个 并没有按照你说的做的
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/static/slim/prune/README.md

**Comment by w77779999** [comment]
参考这个的话，不管指定没训练过的权重(预训练权重)，或者是量化完的权重，或者是导出静态图之后的文件，在敏感度分析这边最开始算出的map都是0.0几，就很奇怪

**Comment by Jiashuhao518** [comment]
> 参考这个的话，不管指定没训练过的权重(预训练权重)，或者是量化完的权重，或者是导出静态图之后的文件，在敏感度分析这边最开始算出的map都是0.0几，就很奇怪

我用的是预训练权重 并且作出了敏感度分析的图的

**Comment by w77779999** [comment]
> > 参考这个的话，不管指定没训练过的权重(预训练权重)，或者是量化完的权重，或者是导出静态图之后的文件，在敏感度分析这边最开始算出的map都是0.0几，就很奇怪
> 
> 我用的是预训练权重 并且作出了敏感度分析的图的

我拿预训练权重去分析最开始的map就是0.0几就不对。。就没什么办法。我现在是在static下再训练出精度达到要求的权重，对这个权重再进行敏感度分析这样

**Comment by w77779999** [comment]
但是按照这个分析来说，反正backbone剪0.1，精度就能掉个6，7点的样子感觉

**Comment by Jiashuhao518** [comment]
> 但是按照这个分析来说，反正backbone剪0.1，精度就能掉个6，7点的样子感觉

但是剪枝后要训练恢复精度的啊

**Comment by w77779999** [comment]
> > 反正backbone剪0.1，精度就能掉个6，7点的样子感觉
> 
> 但是剪枝后要训练恢复精度的啊

你训练了多少epoch呢？感觉120训完准确率也就那样

**Comment by Jiashuhao518** [comment]
> > > 反正backbone剪0.1，精度就能掉个6，7点的样子感觉
> > 
> > 
> > 但是剪枝后要训练恢复精度的啊
> 
> 你训练了多少epoch呢？感觉120训完准确率也就那样

我也是120  240还没有试过 感觉也不会有多少提升

**Comment by Jiashuhao518** [comment]
> 给create传的参数不能是QATPrune，这个只能用于判断slim_load_cfg['slim']是否是你这个情况，下面传的参数要换成普通的QAT，Prune这些

能帮我看看我的问题在哪里吗 我这样写只能执行量化  想法是先剪枝后量化 但是直接跳过了剪枝
    elif slim_load_cfg['slim'] == 'QAT':
        load_config(slim_cfg)
        model = create(cfg.architecture)
        if mode == 'train':
            load_pretrain_weight(model, cfg.pretrain_weights)
        slim = create(cfg.slim)
        if slim == 'qat':
            pruner = create(cfg.pruner)
            model = pruner(model)
            slim =create(cfg.slim)
            cfg['slim_type'] = cfg.slim
            cfg['model'] = slim(model)
            cfg['slim'] = slim
        if mode != 'train':
            load_pretrain_weight(cfg['model'], cfg.weights)

**Comment by SunYF-0729** [comment]
https://github.com/PaddlePaddle/PaddleDetection/issues/6453#issue-1306564809 @Jiashuhao518 @w77779999 问下两位，我在静态剪裁后评估时遇到这个问题，你们知道怎么解决吗？

**Comment by SunYF-0729** [comment]
> > > 静态图剪枝你是在paddledetection上面做吗，还是在自己这边重新搭建模型用paddleslim做的？
> > 
> > 
> > 静态图是static文件下做的
> 
> static下面那指令呢？因为动转静后生成的文件有4个，infer_cfg.yml，model.pdiparams，model.pdiparams.info，model.pdmodel，在config的yml里面weight你是直接指向存这四个文件的文件夹这样吗？ 因为static里面ssd的yml和外面的yml其实写的不太一样，你拿动态图训练好转成静态图生成这些文件后，拿这些文件到静态图去算卷积敏感度，最开始算出来的map是和你原本动态图训练出来的map一样是吗

我也是这个问题，static中config和我在动态图训练中yml文件不一样，我用训练好的动态图转化为静态图，去static中算卷积敏感度会出错，不知道怎么解决

**Comment by SunYF-0729** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 我这边是分析完之后拿到正式的地方去剪，算出来的计算量减少的很少，跟预期不太符合
> > > > 
> > > > 
> > > > 动态图吗 动态图我不知道如何把剪枝和量化做在一起 因为没有提供联合策略
> > > 
> > > 
> > > 可以参考那个蒸馏加剪枝的来写，但是试过来不太行
> > 
> > 
> > 那么分开怎么做呢 是先做剪枝 然后在量化的yml里面把预训练权重换成剪枝后的权重吗
> 
> 它的剪枝其实在build_slim_config的时候如果你设置了就直接做掉了，量化好像只是加入了fake还有moving的节点，我是先剪了然后量化

您好，我想问下，这个剪裁+量化到底怎么做啊用动态图，训练出来全精度模型然后呢

**Comment by Jiashuhao518** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > 我这边是分析完之后拿到正式的地方去剪，算出来的计算量减少的很少，跟预期不太符合
> > > > > 
> > > > > 
> > > > > 动态图吗 动态图我不知道如何把剪枝和量化做在一起 因为没有提供联合策略
> > > > 
> > > > 
> > > > 可以参考那个蒸馏加剪枝的来写，但是试过来不太行
> > > 
> > > 
> > > 那么分开怎么做呢 是先做剪枝 然后在量化的yml里面把预训练权重换成剪枝后的权重吗
> > 
> > 
> > 它的剪枝其实在build_slim_config的时候如果你设置了就直接做掉了，量化好像只是加入了fake还有moving的节点，我是先剪了然后量化
> 
> 您好，我想问下，这个剪裁+量化到底怎么做啊用动态图，训练出来全精度模型然后呢

现在官方已经给出了动态图下剪枝+量化的联合策略了 你去看最新版本的ppdet/slim/init.py的代码 参考一下怎么写
