### ISSUE TITLE
s2anet现在可支持eval吗，用的2.4貌似还是不支持

### ISSUE THREAD

**Issue by 939979325** [PaddlePaddle/PaddleDetection#5993]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

s2anet在2.4版本无法支持eval

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by heavengate** [comment]
S2ANet一直是支持eval的，你是做eval报错了么，可以贴一下命令和报错信息等

**Comment by 939979325** [comment]
你好，我这边运行的话报错了
  File "pycocotools\_mask.pyx", line 214, in pycocotools._mask.iou
  File "pycocotools\_mask.pyx", line 193, in pycocotools._mask.iou._preproc
Exception: list input can be bounding box (Nx4) or RLEs ([RLE])

**Comment by WANGYong-NJ** [comment]
我也遇到同样的问题，请问怎么解决这个bug啊？有大神知道吗？

**Comment by wangxinxin08** [comment]
@WANGYong-NJ s2anet一直是支持eval的，你可以贴下报什么错误

**Comment by WANGYong-NJ** [comment]
@wangxinxin08  多谢回复！

与上面报的错误一样，如果需要完整的错误，我稍后再跑一遍，把完整错误贴上来。

File "pycocotools_mask.pyx", line 214, in pycocotools._mask.iou
File "pycocotools_mask.pyx", line 193, in pycocotools._mask.iou._preproc
Exception: list input can be bounding box (Nx4) or RLEs ([RLE])

**Comment by WANGYong-NJ** [comment]
@wangxinxin08 完整输出如下：

/home/aistudio/PaddleDetection
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
W1114 17:23:12.113780   730 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 10.1
W1114 17:23:12.118444   730 device_context.cc:422] device: 0, cuDNN Version: 7.6.
loading annotations into memory...
Done (t=0.06s)
creating index...
index created!
[11/14 17:23:14] ppdet.utils.checkpoint INFO: Finish loading model weights: output/s2anet_1x_spine/model_final.pdparams
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
[11/14 17:23:15] ppdet.engine INFO: Eval iter: 0
[11/14 17:23:57] ppdet.engine INFO: Eval iter: 100
[11/14 17:24:40] ppdet.engine INFO: Eval iter: 200
..........
[11/14 18:12:30] ppdet.engine INFO: Eval iter: 6900
[11/14 18:12:58] ppdet.metrics.metrics INFO: The bbox result is saved to bbox.json.
loading annotations into memory...
Done (t=0.11s)
creating index...
index created!
[11/14 18:12:58] ppdet.metrics.coco_utils INFO: Start evaluate...
Loading and preparing results...
DONE (t=0.20s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
Traceback (most recent call last):
  File "tools/eval.py", line 134, in <module>
    main()
  File "tools/eval.py", line 130, in main
    run(FLAGS, cfg)
  File "tools/eval.py", line 105, in run
    trainer.evaluate()
  File "/home/aistudio/PaddleDetection/ppdet/engine/trainer.py", line 354, in evaluate
    self._eval_with_loader(self.loader)
  File "/home/aistudio/PaddleDetection/ppdet/engine/trainer.py", line 347, in _eval_with_loader
    metric.accumulate()
  File "/home/aistudio/PaddleDetection/ppdet/metrics/metrics.py", line 116, in accumulate
    classwise=self.classwise)
  File "/home/aistudio/PaddleDetection/ppdet/metrics/coco_utils.py", line 96, in cocoapi_eval
    coco_eval.evaluate()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pycocotools/cocoeval.py", line 149, in evaluate
    for imgId in p.imgIds
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pycocotools/cocoeval.py", line 150, in <dictcomp>
    for catId in catIds}
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pycocotools/cocoeval.py", line 189, in computeIoU
    ious = maskUtils.iou(d,g,iscrowd)
  File "pycocotools/_mask.pyx", line 214, in pycocotools._mask.iou
  File "pycocotools/_mask.pyx", line 193, in pycocotools._mask.iou._preproc
Exception: list input can be bounding box (Nx4) or RLEs ([RLE])

**Comment by wangxinxin08** [comment]
这里需要注意，旋转框的评估不能使用COCO评估，你是不是数据集配置里面没有正确设置metric为RBox，比如https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/datasets/dota.yml#L1，

**Comment by WANGYong-NJ** [comment]
@wangxinxin08 多谢解答，修改以后出现以下提示，是不是我的数据格式错误了？请指点一下，多谢！

/home/aistudio/PaddleDetection
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
W1115 09:59:43.019330  2219 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 10.1
W1115 09:59:43.024107  2219 device_context.cc:422] device: 0, cuDNN Version: 7.6.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
/home/aistudio/PaddleDetection/ppdet/engine/trainer.py:178: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  self.cfg.metric))
[11/15 09:59:45] ppdet.engine WARNING: Metric not support for metric type RBOX
[11/15 09:59:46] ppdet.utils.checkpoint INFO: Finish loading model weights: output/s2anet_1x_spine/model_final.pdparams
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
[11/15 09:59:47] ppdet.engine INFO: Eval iter: 0
[11/15 09:59:51] ppdet.engine INFO: Total sample number: 11, averge FPS: 2.3052382034235506

**Comment by WANGYong-NJ** [comment]
@wangxinxin08 非常感谢解答，已解决！
