### ISSUE TITLE
PicoDet 预测视频及图片 postprocess出错

### ISSUE THREAD

**Issue by relic-yuexi** [PaddlePaddle/PaddleDetection#5996]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

postprocess 中出错，传进的boxes_num是三维的数据，和下面的np_boxes_num[0] <= 0 不符

```
Traceback (most recent call last):
File "deploy/python/infer.py", line 910,in <module>
main()
File "deploy/python/infer.py" , line 883, in main
img_list，FLAGS.run_benchmark,repeats=100,save_file=save_file)File "deploy/python/infer.py",line 284,in predict_image
result = self.postprocess(inputs, result)
File "deploy/python/infer.py", line 169,in postprocessif np_boxes_num[0]<= 0:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all

```

![image](https://user-images.githubusercontent.com/53668275/168807055-264b8152-c3b8-499d-bfec-eb2c8ca9cb40.png)

调用语句如下：
![image](https://user-images.githubusercontent.com/53668275/168807500-22f707af-87e7-4926-b1e8-da208e36bca5.png)

图片大小是 宽度640像素x高度480像素

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by relic-yuexi** [comment]
解决了，不能导出模型后在infer，应该直接对那个检测。

**Comment by relic-yuexi** [comment]
> 

搞错了，后面用tools/eval.py 能成功，但是 deploy 里的依然不行。

**Comment by relic-yuexi** [comment]
原来是将nms取消掉了，所以无法直接用infer，建议未来在代码中加入判断
