### ISSUE TITLE
使用ppyoloe的配置文件以及自己的数据集，在runtime.yml中设置print_flops: true，在训练的时候报错误，但是相同的条件下，使用YOLOv3就不存在这个问题！

### ISSUE THREAD

**Issue by mingheyuemankong** [PaddlePaddle/PaddleDetection#5999]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

D:\SoftWare2\Miniconda\envs\PaddleShop\python.exe D:/LastCode/PaddleDetection-release-2.4/tools/train.py -c configs/ppyoloe/ppyoloe_crn_s_300e_coco.yml --eval --use_vdl True
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
loading annotations into memory...
Done (t=0.15s)
creating index...
index created!
W0517 20:40:38.080041 21660 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.0
W0517 20:40:38.086042 21660 device_context.cc:465] device: 0, cuDNN Version: 8.0.
[05/17 20:40:41] ppdet.utils.checkpoint INFO: Finish loading model weights: C:\Users\YYF/.cache/paddle/weights\CSPResNetb_s_pretrained.pdparams
loading annotations into memory...
Done (t=0.17s)
creating index...
index created!
Traceback (most recent call last):
  File "D:/LastCode/PaddleDetection-release-2.4/tools/train.py", line 177, in <module>
    main()
  File "D:/LastCode/PaddleDetection-release-2.4/tools/train.py", line 173, in main
    run(FLAGS, cfg)
  File "D:/LastCode/PaddleDetection-release-2.4/tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "D:\LastCode\PaddleDetection-release-2.4\ppdet\engine\trainer.py", line 423, in train
    self._flops(flops_loader)
  File "D:\LastCode\PaddleDetection-release-2.4\ppdet\engine\trainer.py", line 839, in _flops
    flops = flops(self.model, input_spec) / (1000**3)
  File "D:\SoftWare2\Miniconda\envs\PaddleShop\lib\site-packages\paddleslim\analysis\flops.py", line 133, in dygraph_flops
    program = dygraph2program(model, inputs)
  File "D:\SoftWare2\Miniconda\envs\PaddleShop\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\SoftWare2\Miniconda\envs\PaddleShop\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\SoftWare2\Miniconda\envs\PaddleShop\lib\site-packages\paddle\fluid\framework.py", line 229, in __impl__
    return func(*args, **kwargs)
  File "D:\SoftWare2\Miniconda\envs\PaddleShop\lib\site-packages\paddleslim\core\dygraph.py", line 119, in dygraph2program
    original_outputs = layer(*inputs)
  File "D:\SoftWare2\Miniconda\envs\PaddleShop\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\SoftWare2\Miniconda\envs\PaddleShop\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\LastCode\PaddleDetection-release-2.4\ppdet\modeling\architectures\meta_arch.py", line 75, in forward
    outs.append(self.get_pred())
  File "D:\LastCode\PaddleDetection-release-2.4\ppdet\modeling\architectures\yolo.py", line 128, in get_pred
    return self._forward()
  File "D:\LastCode\PaddleDetection-release-2.4\ppdet\modeling\architectures\yolo.py", line 117, in _forward
    bbox, bbox_num = self.yolo_head.post_process(
  File "D:\LastCode\PaddleDetection-release-2.4\ppdet\modeling\heads\ppyoloe_head.py", line 370, in post_process
    pred_bboxes = batch_distance2bbox(anchor_points,
  File "D:\LastCode\PaddleDetection-release-2.4\ppdet\modeling\bbox_utils.py", line 767, in batch_distance2bbox
    x1y1 = -lt + points
  File "D:\SoftWare2\Miniconda\envs\PaddleShop\lib\site-packages\paddle\fluid\dygraph\math_op_patch.py", line 264, in __impl__
    return math_op(self, other_var, 'axis', axis)
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 4725, 2] and the shape of Y = [8400, 2]. Received [4725] in X is not equal to [8400] in Y at i:1.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at ..\paddle/fluid/operators/elementwise/elementwise_op_function.h:240)
  [operator < elementwise_add > error]

Process finished with exit code 1

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
1. 如果你只是想跑通的话 可以把reader里的注释掉
```
eval_height: &eval_height 640
eval_width: &eval_width 640
eval_size: &eval_size [*eval_height, *eval_width]
```

2. 如果你想测flops建议不要在train mode下加print_flops, 这里数据会random resize 测不准的

**Comment by sdreamforchen** [comment]
> 1. 如果你只是想跑通的话 可以把reader里的注释掉
> 
> ```
> eval_height: &eval_height 640
> eval_width: &eval_width 640
> eval_size: &eval_size [*eval_height, *eval_width]
> ```
> 
> 2. 如果你想测flops建议不要在train mode下加print_flops, 这里数据会random resize 测不准的

那是否支持这些情况：
1 在train过程中的eval进行FLOPS计算，这个如何修改，目前我看训练过程中的eval是没有打印出来FLOPS的；
2 在训练完后，进行eval，infer操作的时候增加FLOPS计算。
感谢！
