### ISSUE TITLE
PP-YOLOE training

### ISSUE THREAD

**Issue by BakingBrains** [PaddlePaddle/PaddleDetection#6048]
### 问题描述 Please describe your issue

Thanks for the great repo.
I am trying to train a detection model using PP-YOLOE
I am using **ppyoloe_crn_l_300e_coco.yml** and when I start training the loss is increasing.

```
[05/23 23:13:07] ppdet.utils.checkpoint INFO: Finish loading model weights: D:/pycharmprojects/PaddleDetection/pretrained_weights/ppyoloe_crn_l_300e_coco.pdparams
[05/23 23:13:09] ppdet.engine INFO: Epoch: [0] [  0/125] learning_rate: 0.000000 loss: 4.790312 loss_cls: 1.754835 loss_iou: 0.683292 loss_dfl: 2.654493 loss_l1: 2.539874 eta: 22:26:36 batch_cost: 2.1546 data_cost: 0.0000 ips: 1.8565 images/s
Found inf or nan, current scale is: 1024.0, decrease to: 1024.0*0.5
Found inf or nan, current scale is: 512.0, decrease to: 512.0*0.5
[05/23 23:18:57] ppdet.engine INFO: Epoch: [0] [100/125] learning_rate: 0.004000 loss: 4.623284 loss_cls: 2.262472 loss_iou: 0.598493 loss_dfl: 1.972686 loss_l1: 1.912855 eta: 1 day, 10:56:17 batch_cost: 3.3751 data_cost: 2.8800 ips: 1.1851 images/s
[05/23 23:20:28] ppdet.engine INFO: Epoch: [1] [  0/125] learning_rate: 0.005000 loss: 4.951453 loss_cls: 2.408223 loss_iou: 0.605821 loss_dfl: 1.990910 loss_l1: 2.226703 eta: 1 day, 11:16:20 batch_cost: 3.3546 data_cost: 2.8552 ips: 1.1924 images/s
[05/23 23:26:03] ppdet.engine INFO: Epoch: [1] [100/125] learning_rate: 0.009000 loss: 16.701651 loss_cls: 14.378147 loss_iou: 0.547133 loss_dfl: 1.790975 loss_l1: 1.322968 eta: 1 day, 10:26:53 batch_cost: 3.2382 data_cost: 2.7768 ips: 1.2353 images/s
[05/23 23:27:29] ppdet.engine INFO: Epoch: [2] [  0/125] learning_rate: 0.010000 loss: 19.556190 loss_cls: 17.005377 loss_iou: 0.540205 loss_dfl: 1.729805 loss_l1: 1.244727 eta: 1 day, 10:24:17 batch_cost: 3.2464 data_cost: 2.7773 ips: 1.2321 images/s
Found inf or nan, current scale is: 256.0, decrease to: 256.0*0.5
[05/23 23:32:45] ppdet.engine INFO: Epoch: [2] [100/125] learning_rate: 0.014000 loss: 33.748528 loss_cls: 31.449738 loss_iou: 0.541084 loss_dfl: 1.675597 loss_l1: 1.137323 eta: 1 day, 9:30:18 batch_cost: 3.0504 data_cost: 2.5883 ips: 1.3113 images/s
[05/23 23:34:16] ppdet.engine INFO: Epoch: [3] [  0/125] learning_rate: 0.015000 loss: 34.406448 loss_cls: 32.170582 loss_iou: 0.542427 loss_dfl: 1.648838 loss_l1: 1.103503 eta: 1 day, 9:40:22 batch_cost: 3.1583 data_cost: 2.6849 ips: 1.2665 images/s
Found inf or nan, current scale is: 128.0, decrease to: 128.0*0.5
```

Any suggestions here.

Thank you

**Comment by ghostxsl** [comment]
Please remove '--amp' and try it first~

**Comment by BakingBrains** [comment]
Sure, I will try that. 

@ghostxsl Thank you

**Comment by BakingBrains** [comment]
@ghostxsl  If I set "--amp" to false while training its throwing below mentioned error

```
Epoch: [0] [  0/500] learning_rate: 0.000000 loss: 4.218230 loss_cls: 0.600962 loss_iou: 0.880264 loss_dfl: 2.833214 loss_l1: 4.310324 eta: 1 day, 11:13:38 batch_cost: 0.8455 data_cost: 0.0005 ips: 1.1828 images/s
Error: ../paddle/phi/kernels/gpu/bce_loss_kernel.cu:42 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: ../paddle/phi/kernels/gpu/bce_loss_kernel.cu:42 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: ../paddle/phi/kernels/gpu/bce_loss_kernel.cu:42 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: ../paddle/phi/kernels/gpu/bce_loss_kernel.cu:42 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: ../paddle/phi/kernels/gpu/bce_loss_kernel.cu:42 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Traceback (most recent call last):
  File "D:/pycharmprojects/PaddleDetection/tools/train.py", line 178, in <module>
    main()
  File "D:/pycharmprojects/PaddleDetection/tools/train.py", line 174, in main
    run(FLAGS, cfg)
  File "D:/pycharmprojects/PaddleDetection/tools/train.py", line 128, in run
    trainer.train(FLAGS.eval)
  File "D:\pycharmprojects\PaddleDetection\ppdet\engine\trainer.py", line 448, in train
    outputs = model(data)
  File "D:\Environments\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Environments\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\pycharmprojects\PaddleDetection\ppdet\modeling\architectures\meta_arch.py", line 59, in forward
    out = self.get_loss()
  File "D:\pycharmprojects\PaddleDetection\ppdet\modeling\architectures\yolo.py", line 125, in get_loss
    return self._forward()
  File "D:\pycharmprojects\PaddleDetection\ppdet\modeling\architectures\yolo.py", line 88, in _forward
    yolo_losses = self.yolo_head(neck_feats, self.inputs)
  File "D:\Environments\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Environments\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\pycharmprojects\PaddleDetection\ppdet\modeling\heads\ppyoloe_head.py", line 217, in forward
    return self.forward_train(feats, targets)
  File "D:\pycharmprojects\PaddleDetection\ppdet\modeling\heads\ppyoloe_head.py", line 160, in forward_train
    ], targets)
  File "D:\pycharmprojects\PaddleDetection\ppdet\modeling\heads\ppyoloe_head.py", line 355, in get_loss
    assigned_scores_sum)
  File "D:\pycharmprojects\PaddleDetection\ppdet\modeling\heads\ppyoloe_head.py", line 267, in _bbox_loss
    if num_pos > 0:
  File "D:\Environments\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\varbase_patch_methods.py", line 668, in __bool__
    return self.__nonzero__()
  File "D:\Environments\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\varbase_patch_methods.py", line 665, in __nonzero__
    return bool(np.all(tensor.__array__() > 0))
OSError: (External) CUDA error(719), unspecified launch failure. 
  [Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at ..\paddle\phi\backends\gpu\cuda\cuda_info.cc:258)
```

I verified the annotations.json file, changed the number of class as well, the annotation file works with other detection models as well, but here its throwing that error.

Any suggestions?
Thank you

**Comment by ghostxsl** [comment]
What is the version of your Paddle and PaddleDetection?

**Comment by BakingBrains** [comment]
@ghostxsl 
>>> import paddle
>>> print(paddle.__version__)
2.3.0

>>> print(ppdet.__version__)
2.4.0

**Comment by ghostxsl** [comment]
try set "-o TrainReader.use_shared_memory=False"

**Comment by BakingBrains** [comment]
@ghostxsl,  Still the same issue. I don't know what's going wrong

**Comment by BakingBrains** [comment]
@ghostxsl I changed to ppyoloe_crn_m_300e_coco.pdparams it started the training, but still the loss value is increasing.

```
[05/24 16:55:42] ppdet.engine INFO: Epoch: [0] [  0/166] learning_rate: 0.000000 loss: 4.831001 loss_cls: 1.623000 loss_iou: 0.746897 loss_dfl: 2.681520 loss_l1: 2.082105 eta: 16:21:30 batch_cost: 1.1825 data_cost: 0.1905 ips: 2.5369 images/s
[05/24 17:00:25] ppdet.engine INFO: Epoch: [0] [100/166] learning_rate: 0.004217 loss: 4.718459 loss_cls: 2.129966 loss_iou: 0.665714 loss_dfl: 2.090601 loss_l1: 2.087489 eta: 1 day, 12:32:16 batch_cost: 2.6612 data_cost: 1.5758 ips: 1.1273 images/s
[05/24 17:03:29] ppdet.engine INFO: Epoch: [1] [  0/166] learning_rate: 0.007000 loss: 8.422877 loss_cls: 5.889220 loss_iou: 0.651913 loss_dfl: 2.083613 loss_l1: 2.060118 eta: 1 day, 12:22:24 batch_cost: 2.5678 data_cost: 1.3366 ips: 1.1683 images/s
[05/24 17:07:54] ppdet.engine INFO: Epoch: [1] [100/166] learning_rate: 0.011217 loss: 21.496906 loss_cls: 19.170841 loss_iou: 0.541128 loss_dfl: 1.721369 loss_l1: 1.121590 eta: 1 day, 11:31:50 batch_cost: 2.4889 data_cost: 1.3846 ips: 1.2054 images/s
````

Should I wait for some epochs?
Any suggestions?

Thanks

**Comment by ghostxsl** [comment]
Turn down the learning rate, maybe it works.

**Comment by BakingBrains** [comment]
Yeah, I am doing that, 
Thank you

**Comment by BakingBrains** [comment]
@ghostxsl Thanks
Learning rate 0.01 working fine so far. ( for ppyoloe_crn_s_300e_coco )

**Comment by Wulx2050** [comment]
Found inf or nan 
1.add --amp   2.Turn down the learning rate， lr/10，lr/100 ，lr/1000

I also have this problem. Is there any problem with the optimization algorithm of PP-YOLOE?

**Comment by BakingBrains** [comment]
@Wulx2050 I'm not sure why, may be there is a problem with that.

**Comment by Wulx2050** [comment]
> @Wulx2050 I'm not sure why, may be there is a problem with that.

Maybe he's right. See  issues/4049 训练不稳定，有些算子尚未支持。

话说用PaddlePaddle的应该都是中国人吧。我直接发汉字了

**Comment by nemonameless** [comment]
You can also try to modify the epoch or step of warmup if fintune.

**Comment by Wulx2050** [comment]
> You can also try to modify the epoch or step of warmup if fintune.

这些好像都没有用，我只能跑10epoch就断点续训，而且最后的loss降到了1.6左右，验证集精度也不高，只有33%，和COCOtest2017数据集精度51.4%差距太多[PP-YOLOE的l版本]，可能是某些地方出错了。而我使用faster rcnn验证集精度达到了42%。等有空了，我换个数据集试试看。

`Translate by google:`
These seem to be useless. I can only run 10 epochs to continue the training, and the final loss drops to about 1.6. The accuracy of the validation set is not high, only 33%, which is too far from the accuracy of the COCOtest2017 dataset of 51.4% [PP- YOLOE's l version], maybe something went wrong. And I used the faster rcnn validation set to achieve 42% accuracy. When I have time, I will try another dataset.

**Comment by 875052544** [comment]
我也是同样的问题，用的是PPYOLOE的x版本 s和l版本都没这个问题

**Comment by top18981725185** [comment]
我使用了EIOU损失在m模型上会出现nan，在s没有出现nan，在s上使用了mixup数据增强又出现nan了

**Comment by hhxdestiny** [comment]
单卡需要降低学习率（lr/8），loss一开始确实是在增加，但在十个epoch左右后会开始下降

**Comment by Nioolek** [comment]
这个问题我也出现过。原因出现在这里：
```
assigned_scores_sum = assigned_scores.sum()
loss_cls /= assigned_scores_sum
```
如果使用的卡数量特别少，且因为显存限制，只能把batchsize设置的很小，那么会偶发assigned_scores_sum特别小的情况，小到甚至接近于1。
这种情况就会导致loss_cls在这个batch特别的大，反向传播之后会导致下个iter中loss_cls更加飙升。
所以综合而言，解决措施：
1\增加batchsize
2\多卡训练
卡少需要降低学习率，但仅靠调小lr解决不了本质问题

**Comment by ycyinchao** [comment]
> 这个问题我也出现过。原因出现在这里：
> 
> ```
> assigned_scores_sum = assigned_scores.sum()
> loss_cls /= assigned_scores_sum
> ```
> 
> 如果使用的卡数量特别少，且因为显存限制，只能把batchsize设置的很小，那么会偶发assigned_scores_sum特别小的情况，小到甚至接近于1。 这种情况就会导致loss_cls在这个batch特别的大，反向传播之后会导致下个iter中loss_cls更加飙升。 所以综合而言，解决措施： 1\增加batchsize 2\多卡训练 卡少需要降低学习率，但仅靠调小lr解决不了本质问题

对，尤其是对于ppyoloe，bs=1时无论如何设置lr，都会报以下两个错误之一：
bce_loss_kernel.cu:42 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.

one_hot_kernel.cu:38 Assertion `p_in_data[idx] >= 0 && p_in_data[idx] < depth` failed. Illegal index value, Input(input) value should be greater than or equal to 0, and less than depth [5376], but received [94079760226976].

**Comment by Vergissmeinnic** [comment]
我把配置文件LearningRate中的的base_lr调小就可以正常运行了，之前是0.01报错了，我现在设置的是0.005，正常运行了。

**Comment by piupuer** [comment]
我遇到类似问题，ppyoloe_plus_sod_crn_s_80e_visdrone.yml，去除--amp就不报错了
