### ISSUE TITLE
paddle detection训练visdrone数据集报错 KeyError: 10

### ISSUE THREAD

**Issue by wenzonghui** [PaddlePaddle/PaddleDetection#6089]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

![截屏2022-05-29 19 33 51](https://user-images.githubusercontent.com/31688486/170865826-c7c8743f-111b-4ba6-a359-a624b371385a.png)

Traceback (most recent call last):
  File "tools/train.py", line 177, in <module>
    main()
  File "tools/train.py", line 173, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 118, in run
    trainer = Trainer(cfg, mode='train')
  File "/root/PaddleDetection/ppdet/engine/trainer.py", line 87, in __init__
    self.loader = create('{}Reader'.format(capital_mode))(
  File "/root/PaddleDetection/ppdet/data/reader.py", line 163, in __call__
    self.dataset.parse_dataset()
  File "/root/PaddleDetection/ppdet/data/source/coco.py", line 184, in parse_dataset
    gt_class[i][0] = self.catid2clsid[catid]
KeyError: 10
INFO 2022-05-29 19:23:38,033 launch_utils.py:320] terminate process group gid:1469
INFO 2022-05-29 19:23:42,038 launch_utils.py:341] terminate all the procs
ERROR 2022-05-29 19:23:42,038 launch_utils.py:602] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2022-05-29 19:23:46,042 launch_utils.py:341] terminate all the procs
INFO 2022-05-29 19:23:46,043 launch.py:311] Local processes completed.

### 复现环境 Environment

paddle 2.2.3
cuda 10.2

已经将visdrone转换成coco数据格式。
visdrone
 - train
   - xxxx.jpg
 - valid
   - xxxx.jpg
 - annotations
   - train.json
   - valid.json

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by wenzonghui** [comment]
是数据集转换问题。
这是9类的visdrone 按coco格式处理后的 https://bj.bcebos.com/v1/paddledet/data/VisDrone2019_coco.tar
