### ISSUE TITLE
PPYoloel 导出模型指定image_shape后报错

### ISSUE THREAD

**Issue by todaysky1234** [PaddlePaddle/PaddleDetection#6105]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

在PaddleDetection release/2.4和PaddleDetection: develop下都进行了实验，问题一致；

在指定图像大小是 [3,640,640]时正常，指定为[3,960,960]或[3,1280,1280]时均报错

```yml
TestReader:
  inputs_def:
    image_shape: [3,960, 960]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: *eval_size, keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 1

```

```shell
python tools/export_model.py -c configs/ppyoloe/ppyoloe_crn_l_300e_coco.yml -o weights=https://paddledet.bj.bcebos.com/models/ppyoloe_crn_l_300e_coco.pdparams

```
错误信息

```txt
$ python tools/export_model.py -c configs/ppyoloe/ppyoloe_crn_l_300e_coco.yml -o weights=https://paddledet.bj.bcebos.com/models/ppyoloe_crn_l_300e_coco.pdparams
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
[05/31 22:24:12] ppdet.utils.checkpoint INFO: ['yolo_head.anchor_points', 'yolo_head.stride_tensor'] in pretrained weight is not used in the model, and its will not be loaded
[05/31 22:24:12] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/aaa/.cache/paddle/weights/ppyoloe_crn_l_300e_coco.pdparams
[05/31 22:24:13] ppdet.data.source.category WARNING: anno_file 'dataset/coco/annotations/instances_val2017.json' is None or not set or not exist, please recheck TrainDataset/EvalDataset/TestDataset.anno_path, otherwise the default categories will be used by metric_type.
[05/31 22:24:13] ppdet.data.source.category WARNING: metric_type: COCO, load default categories of COCO.
[05/31 22:24:13] ppdet.engine INFO: Export inference config file to output_inference/ppyoloe_crn_l_300e_coco/infer_cfg.yml
Traceback (most recent call last):
  File "tools/export_model.py", line 111, in <module>
    main()
  File "tools/export_model.py", line 107, in main
    run(FLAGS, cfg)
  File "tools/export_model.py", line 73, in run
    trainer.export(FLAGS.output_dir)
  File "/home/aaa/work/PaddleDetection_dev/PaddleDetection/ppdet/engine/trainer.py", line 775, in export
    save_dir)
  File "/home/aaa/work/PaddleDetection_dev/PaddleDetection/ppdet/engine/trainer.py", line 752, in _get_infer_cfg_and_input_spec
    input_spec, static_model.forward.main_program,
  File "/home/aaa/anaconda3/envs/paddleDetection24/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 563, in main_program
    concrete_program = self.concrete_program
  File "/home/aaa/anaconda3/envs/paddleDetection24/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 479, in concrete_program
    return self.concrete_program_specify_input_spec(input_spec=None)
  File "/home/aaa/anaconda3/envs/paddleDetection24/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 517, in concrete_program_specify_input_spec
    *desired_input_spec)
  File "/home/aaa/anaconda3/envs/paddleDetection24/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 427, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/home/aaa/anaconda3/envs/paddleDetection24/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 723, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/home/aaa/anaconda3/envs/paddleDetection24/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 714, in _build_once
    **cache_key.kwargs)
  File "/home/aaa/anaconda3/envs/paddleDetection24/lib/python3.6/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/aaa/anaconda3/envs/paddleDetection24/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/aaa/anaconda3/envs/paddleDetection24/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "/home/aaa/anaconda3/envs/paddleDetection24/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 668, in from_func_spec
    error_data.raise_new_exception()
  File "/home/aaa/anaconda3/envs/paddleDetection24/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
ValueError: In transformed code:

    File "/home/aaa/work/PaddleDetection_dev/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 128, in get_pred
        return self._forward()
    File "/home/aaa/work/PaddleDetection_dev/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 119, in _forward
        self.inputs['scale_factor'])
    File "/home/aaa/work/PaddleDetection_dev/PaddleDetection/ppdet/modeling/heads/ppyoloe_head.py", line 371, in post_process
        pred_dist.transpose([0, 2, 1]))
    File "/home/aaa/work/PaddleDetection_dev/PaddleDetection/ppdet/modeling/bbox_utils.py", line 766, in batch_distance2bbox
        """
        lt, rb = paddle.split(distance, 2, -1)
        # while tensor add parameters, parameters should be better placed on the second place
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        x1y1 = -lt + points
        x2y2 = rb + points

    File "/home/aaa/anaconda3/envs/paddleDetection24/lib/python3.6/site-packages/paddle/fluid/layers/math_op_patch.py", line 347, in __impl__
        attrs={'axis': axis})
    File "/home/aaa/anaconda3/envs/paddleDetection24/lib/python3.6/site-packages/paddle/fluid/framework.py", line 3184, in append_op
        attrs=kwargs.get("attrs", None))
    File "/home/aaa/anaconda3/envs/paddleDetection24/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2344, in __init__
        self.desc.infer_shape(self.block.desc)

    ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [-1, 18900, 2] and the shape of Y = [8400, 2]. Received [18900] in X is not equal to [8400] in Y at i:1.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:240)
  [operator < elementwise_add > error]


```

### 复现环境 Environment

- PaddlePaddle:2.2.2
- PaddleDetection: release/2.4    and PaddleDetection: Dev
- Python：3.6.0
- CUDA: 10.2 

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
改一下reader里的eval_height 和 eval_width https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/ppyoloe/_base_/ppyoloe_reader.yml
