### ISSUE TITLE
ppyoloe图像输入尺寸864x480，使用TensorRT预测的时候报错

### ISSUE THREAD

**Issue by heyiamarthur** [PaddlePaddle/PaddleDetection#6111]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

训练ppyoloe，数据集原始尺寸是1280x720。
如果在配置文件里，设置模型（Train、Eval、Test）输入尺寸是640x640，导出模型之后使用`--run_mode=paddle`或者`--run_mode=trt_fp32`都能够进行预测。
如果在配置文件里，设置模型（Train、Eval、Test）输入尺寸是864x480（keep_ratio=False)，导出模型之后，使用`--run_mode=paddle`能够正常预测。使用`--run_mode=trt_fp32`，只能成功预测几张图片，其余图片报错：
```
python3 deploy/python/infer.py --model_dir=output_inference/0531ppyoloe_s_864480_150e --image_dir=dataset/uav0531/JPEGImages --device=GPU --run_mode=trt_fp32
-----------  Running Arguments -----------
action_file: None
batch_size: 1
camera_id: -1
cpu_threads: 1
device: GPU
enable_mkldnn: False
enable_mkldnn_bfloat16: False
image_dir: dataset/uav0531/JPEGImages
image_file: None
model_dir: output_inference/0531ppyoloe_s_864480_150e
output_dir: output
random_pad: False
reid_batch_size: 50
reid_model_dir: None
run_benchmark: False
run_mode: trt_fp32
save_images: False
save_mot_txt_per_img: False
save_mot_txts: False
save_results: False
scaled: False
threshold: 0.5
tracker_config: None
trt_calib_mode: False
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
use_dark: True
use_gpu: False
video_file: None
window_size: 50
------------------------------------------
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order: 
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
Found 2893 inference images in total.
predicting... /home/ubuntu/PaddleDetection/dataset/uav0531/JPEGImages/100007472.jpg
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "deploy/python/infer.py", line 910, in <module>
    main()
  File "deploy/python/infer.py", line 882, in main
    detector.predict_image(
  File "deploy/python/infer.py", line 279, in predict_image
    result = self.predict()
  File "deploy/python/infer.py", line 206, in predict
    self.predictor.run()
ValueError: In user code:

    File "tools/export_model.py", line 111, in <module>
      main()
    File "tools/export_model.py", line 107, in main
      run(FLAGS, cfg)
    File "tools/export_model.py", line 73, in run
      trainer.export(FLAGS.output_dir)
    File "/home/ubuntu/PaddleDetection/ppdet/engine/trainer.py", line 774, in export
      static_model, pruned_input_spec = self._get_infer_cfg_and_input_spec(
    File "/home/ubuntu/PaddleDetection/ppdet/engine/trainer.py", line 752, in _get_infer_cfg_and_input_spec
      input_spec, static_model.forward.main_program,
    File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 580, in main_program
      concrete_program = self.concrete_program
    File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program
      return self.concrete_program_specify_input_spec(input_spec=None)
    File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 527, in concrete_program_specify_input_spec
      concrete_program, _ = self.get_concrete_program(
    File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
      self._caches[item_id] = self._build_once(item)
    File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 785, in _build_once
      concrete_program = ConcreteProgram.from_func_spec(
    File "/home/ubuntu/.local/lib/python3.8/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 733, in from_func_spec
      outputs = static_func(*inputs)
    File "/tmp/tmp11eu54cv.py", line 100, in forward
      out = paddle.jit.dy2static.convert_ifelse(self.training, true_fn_5,
    File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/tmp/tmp11eu54cv.py", line 83, in false_fn_5
      ] = paddle.jit.dy2static.convert_while_loop(for_loop_condition_0,
    File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 45, in convert_while_loop
      loop_vars = _run_py_while(cond, body, loop_vars)
    File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 59, in _run_py_while
      loop_vars = body(*loop_vars)
    File "/home/ubuntu/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 75, in forward
      outs.append(self.get_pred())
    File "/home/ubuntu/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 128, in get_pred
      return self._forward()
    File "/tmp/tmp1jlbdu10.py", line 113, in _forward
      __return_value_0 = paddle.jit.dy2static.convert_ifelse(self.training,
    File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/tmp/tmp1jlbdu10.py", line 106, in false_fn_11
      bbox, bbox_num, output = paddle.jit.dy2static.convert_ifelse(self.
    File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/tmp/tmp1jlbdu10.py", line 101, in false_fn_10
      bbox, bbox_num = paddle.jit.dy2static.convert_ifelse(self.
    File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/tmp/tmp1jlbdu10.py", line 97, in false_fn_9
      bbox, bbox_num = paddle.jit.dy2static.convert_ifelse(self.
    File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/home/ubuntu/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 117, in _forward
      bbox, bbox_num = self.yolo_head.post_process(
    File "/tmp/tmpb2aid70r.py", line 36, in post_process
      __return_value_3 = paddle.jit.dy2static.convert_ifelse(self.exclude_nms,
    File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/home/ubuntu/PaddleDetection/ppdet/modeling/heads/ppyoloe_head.py", line 382, in post_process
      bbox_pred, bbox_num, _ = self.nms(pred_bboxes, pred_scores)
    File "/tmp/tmpjlss7s_0.py", line 91, in __call__
      __return_value_4 = paddle.jit.dy2static.convert_ifelse(paddle.jit.
    File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/home/ubuntu/PaddleDetection/ppdet/modeling/layers.py", line 485, in __call__
      bbox = paddle.masked_select(bbox, mask).reshape((-1, 6))
    File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/tensor/manipulation.py", line 2139, in reshape
      return paddle.fluid.layers.reshape(x=x, shape=shape, name=name)
    File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/layers/nn.py", line 6445, in reshape
      helper.append_op(
    File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/layer_helper.py", line 44, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3615, in append_op
      op = Operator(
    File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2635, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The 'shape' attribute in ReshapeOp is invalid. The input tensor X'size must be divisible by known capacity of 'shape'. But received X's shape = [532], X's size = 532, 'shape' is [-1, 6], known capacity of 'shape' is -6.
      [Hint: Expected output_shape[unk_dim_idx] * capacity == -in_size, but received output_shape[unk_dim_idx] * capacity:-528 != -in_size:-532.] (at /paddle/paddle/fluid/operators/reshape_op.cc:190)
      [operator < reshape2 > error]
```

配置文件Reader部分如下：
```
worker_num: 8
eval_height: &eval_height 480
eval_width: &eval_width 864
eval_size: &eval_size [*eval_height, *eval_width]

TrainReader:
  sample_transforms:
    - Decode: {}
    - RandomDistort: {}
    - RandomExpand: {fill_value: [123.675, 116.28, 103.53]}
    - RandomCrop: {}
    - RandomFlip: {}
  batch_transforms:
    - BatchRandomResize: {target_size: *eval_size, keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
    - PadGT: {}
  batch_size: 16
  shuffle: true
  drop_last: true
  use_shared_memory: true
  collate_batch: true

EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: *eval_size, keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 1

TestReader:
  inputs_def:
    image_shape: [3, *eval_height, *eval_width]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: *eval_size, keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 1
```

### 复现环境 Environment

- PaddlePaddle 2.3
- PaddleDetection 2.4
- Python 3.8
- Ubuntu 20.04
- CUDA 11.2
- cuDNN v8.2.1
- TensorRT 8.2.5.1
- Paddle Inference：manylinux_cuda11.2_cudnn8.2_avx_mkl_trt8_gcc8.2、linux-cuda11.2-cudnn8.2-trt8-gcc8.2

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
trt预测命令里加上```--trt_max_shape=864 --trt_min_shape=480 --trt_opt_shape=640```试试

**Comment by heyiamarthur** [comment]
你好，加了`--trt_max_shape=864 --trt_min_shape=480 --trt_opt_shape=640`以后还是会报一样的错误。

**Comment by heyiamarthur** [comment]
排查问题发现是在TensorRT上运行MultiClassNMS存在问题：
```
class MultiClassNMS(object):
    def __init__(self,
                 score_threshold=.05,
                 nms_top_k=-1,
                 keep_top_k=100,
                 nms_threshold=.5,
                 normalized=True,
                 nms_eta=1.0,
                 return_index=False,
                 return_rois_num=True,
                 trt=False):
        super(MultiClassNMS, self).__init__()
        self.score_threshold = score_threshold
        self.nms_top_k = nms_top_k
        self.keep_top_k = keep_top_k
        self.nms_threshold = nms_threshold
        self.normalized = normalized
        self.nms_eta = nms_eta
        self.return_index = return_index
        self.return_rois_num = return_rois_num
        self.trt = trt

    def __call__(self, bboxes, score, background_label=-1):
        """
        bboxes (Tensor|List[Tensor]): 1. (Tensor) Predicted bboxes with shape 
                                         [N, M, 4], N is the batch size and M
                                         is the number of bboxes
                                      2. (List[Tensor]) bboxes and bbox_num,
                                         bboxes have shape of [M, C, 4], C
                                         is the class number and bbox_num means
                                         the number of bboxes of each batch with
                                         shape [N,] 
        score (Tensor): Predicted scores with shape [N, C, M] or [M, C]
        background_label (int): Ignore the background label; For example, RCNN
                                is num_classes and YOLO is -1. 
        """
        kwargs = self.__dict__.copy()
        if isinstance(bboxes, tuple):
            bboxes, bbox_num = bboxes
            kwargs.update({'rois_num': bbox_num})
        if background_label > -1:
            kwargs.update({'background_label': background_label})
        kwargs.pop('trt')
        # TODO(wangxinxin08): paddle version should be develop or 2.3 and above to run nms on tensorrt
        if self.trt and (int(paddle.version.major) == 0 or
                         (int(paddle.version.major) >= 2 and
                          int(paddle.version.minor) >= 3)):
            # TODO(wangxinxin08): tricky switch to run nms on tensorrt
            kwargs.update({'nms_eta': 1.1})
            bbox, bbox_num, _ = ops.multiclass_nms(bboxes, score, **kwargs)
            mask = paddle.slice(bbox, [-1], [0], [1]) != -1
            bbox = paddle.masked_select(bbox, mask).reshape((-1, 6))
            return bbox, bbox_num, None
        else:
            return ops.multiclass_nms(bboxes, score, **kwargs)
```

**Comment by NanyuZhang0812** [comment]
你好，我遇到和你一样的报错，请问你最后是怎么解决的？

**Comment by heyiamarthur** [comment]
我这回复你看得到不。我觉得是他代码写了一个，2.3之后的paddlepaddle，multiclassnms在tensorrt上运行，这儿报错了。你顺着报错信息能找到，把那段代码注释掉就行。
在PaddleDetection/ppdet/modeling/layers.py的485行附近，让他走else那里返回那个算子就行。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月6日(周三) 晚上10:55
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleDetection] ppyoloe图像输入尺寸864x480，使用TensorRT预测的时候报错 (Issue #6111)




 
你好，我遇到和你一样的报错，请问你最后是怎么解决的？
