### ISSUE TITLE
训练测试评估正常，导出模型出错

### ISSUE THREAD

**Issue by Jeling-W** [PaddlePaddle/PaddleDetection#6112]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我对Picodet的主干网络ESNet做了一些改动，改动后的整个网络训练测试评估都是正常的，但是使用export_model.py导出模型时出错了，出错原因如下：

[06/01 19:42:38] ppdet.engine INFO: Export inference config file to inference/picodet_l_640_coco/infer_cfg.yml
Traceback (most recent call last):
  File "/media/wlj/soft_E/WLJ/PD24/tools/export_model.py", line 111, in <module>
    main()
  File "/media/wlj/soft_E/WLJ/PD24/tools/export_model.py", line 107, in main
    run(FLAGS, cfg)
  File "/media/wlj/soft_E/WLJ/PD24/tools/export_model.py", line 73, in run
    trainer.export(FLAGS.output_dir)
  File "/media/wlj/soft_E/WLJ/PD24/ppdet/engine/trainer.py", line 719, in export
    save_dir)
  File "/media/wlj/soft_E/WLJ/PD24/ppdet/engine/trainer.py", line 696, in _get_infer_cfg_and_input_spec
    input_spec, static_model.forward.main_program,
  File "/home/wlj/anaconda3/envs/pd/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 542, in main_program
    concrete_program = self.concrete_program
  File "/home/wlj/anaconda3/envs/pd/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 458, in concrete_program
    return self.concrete_program_specify_input_spec(input_spec=None)
  File "/home/wlj/anaconda3/envs/pd/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 496, in concrete_program_specify_input_spec
    *desired_input_spec)
  File "/home/wlj/anaconda3/envs/pd/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 406, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/home/wlj/anaconda3/envs/pd/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 723, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/home/wlj/anaconda3/envs/pd/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 714, in _build_once
    **cache_key.kwargs)
  File "/home/wlj/anaconda3/envs/pd/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/wlj/anaconda3/envs/pd/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/wlj/anaconda3/envs/pd/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/home/wlj/anaconda3/envs/pd/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 668, in from_func_spec
    error_data.raise_new_exception()
  File "/home/wlj/anaconda3/envs/pd/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
IndentationError: In transformed code:

    File "/media/wlj/soft_E/WLJ/PD24/ppdet/modeling/architectures/picodet.py", line 90, in get_pred
	bbox_pred, bbox_num = self._forward()
    File "/media/wlj/soft_E/WLJ/PD24/ppdet/modeling/architectures/picodet.py", line 64, in _forward
	body_feats = self.backbone(self.inputs)
    File "/media/wlj/soft_E/WLJ/PD24/ppdet/modeling/backbones/esanet.py", line 446, in forward
        outs = []
        for i, inv in enumerate(self._block_list):
            y = inv(y)
            ~~~~~~~~~~ <--- HERE
            if i + 2 in self.feature_maps:
                outs.append(y)

    File "/home/wlj/anaconda3/envs/pd/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_call_func.py", line 239, in convert_call
	forward_func = convert_to_static(forward_func)
    File "/home/wlj/anaconda3/envs/pd/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 140, in convert_to_static
	static_func = _FUNCTION_CACHE.convert_with_cache(function)
    File "/home/wlj/anaconda3/envs/pd/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 77, in convert_with_cache
	static_func = self._convert(func)
    File "/home/wlj/anaconda3/envs/pd/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 113, in _convert
	root = gast.parse(source_code)
    File "/home/wlj/anaconda3/envs/pd/lib/python3.7/site-packages/paddle/utils/gast/gast.py", line 524, in parse
	return ast_to_gast(_ast.parse(*args, **kwargs))
    File "/home/wlj/anaconda3/envs/pd/lib/python3.7/ast.py", line 35, in parse
	return compile(source, filename, mode, PyCF_ONLY_AST)

      File "<unknown>", line 1

        def forward(self, inputs):

        ^

    IndentationError: unexpected indent


Process finished with exit code 1

**Comment by nemonameless** [comment]
``` ~~~~~~~~~~ <--- HERE```的地方就是报错，动转静导出报错需要看上下文很多关联代码，建议把esanet.py整个代码或forward函数内容展示下方便排错。
