### ISSUE TITLE
cannot import name 'ShapeSpec'

### ISSUE THREAD

**Issue by BainOuO** [PaddlePaddle/PaddleDetection#6134]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

python ppdet/modeling/tests/test_architectures.py

Ran 1 test in 0.000s

FAILED (errors=1)

Error
Traceback (most recent call last):
  File "D:\Users\bby\anaconda3\envs\paddle_env\lib\unittest\loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_architectures
Traceback (most recent call last):
  File "D:\Users\bby\anaconda3\envs\paddle_env\lib\unittest\loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "E:\ppdet\PaddleDetection\ppdet\modeling\tests\test_architectures.py", line 24, in <module>
    import ppdet
  File "E:\ppdet\PaddleDetection\ppdet\__init__.py", line 15, in <module>
    from . import (core, data, engine, modeling, model_zoo, optimizer, metrics,
  File "E:\ppdet\PaddleDetection\ppdet\data\__init__.py", line 16, in <module>
    from . import transform
  File "E:\ppdet\PaddleDetection\ppdet\data\transform\__init__.py", line 15, in <module>
    from . import operators
  File "E:\ppdet\PaddleDetection\ppdet\data\transform\operators.py", line 44, in <module>
    from ppdet.modeling import bbox_utils
  File "E:\ppdet\PaddleDetection\ppdet\modeling\__init__.py", line 20, in <module>
    from . import backbones
  File "E:\ppdet\PaddleDetection\ppdet\modeling\backbones\__init__.py", line 24, in <module>
    from . import senet
  File "E:\ppdet\PaddleDetection\ppdet\modeling\backbones\senet.py", line 23, in <module>
    from .. import ShapeSpec
ImportError: cannot import name 'ShapeSpec'

### 复现环境 Environment

paddle 2.2.2
cuda 10.1
python 3.6

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by heavengate** [comment]
你好，你用的哪个版本呢
