### ISSUE TITLE
训练过程中报错异常退出

### ISSUE THREAD

**Issue by DevilMay-Cry** [PaddlePaddle/PaddleDetection#6161]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用命令 nohup /usr/local/bin/python3 tools/train.py -c configs/ppyolo/ppyolov2_r50vd_dcn_365e_coco.yml --eval >train0608.out 2>&1 &训练模型 
然后模型会异常退出

Traceback (most recent call last):
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 616, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/usr/local/python3.7.0/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3.7.0/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3.7.0/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 530, in _thread_loop
    batch = self._get_data()
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 632, in _get_data
    "pids: {}".format(len(failed_workers), pids))
RuntimeError: DataLoader 1 workers exit unexpectedly, pids: 461

Traceback (most recent call last):
  File "tools/train.py", line 177, in <module>
    main()
  File "tools/train.py", line 173, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/paddle/PaddleDetection/ppdet/engine/trainer.py", line 428, in train
    for step_id, data in enumerate(self.loader):
  File "/paddle/PaddleDetection/ppdet/data/reader.py", line 209, in __next__
    return next(self.loader)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 742, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

我是使用的docker方式部署的paddleDetection，coco数据集

**Comment by yghstill** [comment]
@DevilMay-Cry PaddlePaddle和PaddleDetection的版本分别是多少？将worker_num设成0再试下呢？https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/ppyolo/_base_/ppyolov2_reader.yml#L1

**Comment by DevilMay-Cry** [comment]
> @DevilMay-Cry PaddlePaddle和PaddleDetection的版本分别是多少？将worker_num设成0再试下呢？https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/ppyolo/_base_/ppyolov2_reader.yml#L1
paddlepaddle 版本2.3  paddleDetection2.4 按你说的改完后不在报错  感谢

**Comment by DevilMay-Cry** [comment]
运行一段时间后出现了一个新的报错
Traceback (most recent call last):
  File "tools/train.py", line 177, in <module>
    main()
  File "tools/train.py", line 173, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/paddle/PaddleDetection/ppdet/engine/trainer.py", line 452, in train
    self.optimizer.step()
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 299, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/framework.py", line 434, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/optimizer/optimizer.py", line 1220, in step
    loss=None, startup_program=None, params_grads=params_grads)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/optimizer/optimizer.py", line 952, in _apply_optimize
    params_grads = self._grad_clip(params_grads)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/clip.py", line 193, in __call__
    return self._dygraph_clip(params_grads)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 299, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/clip.py", line 500, in _dygraph_clip
    sum_square = _squared_l2_norm(merge_grad)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/clip.py", line 80, in _squared_l2_norm
    return _C_ops.squared_l2_norm(x)
OSError: (External) CUDA error(701), too many resources requested for launch. 
  [Hint: 'cudaErrorLaunchOutOfResources'. This indicates that a launch did not occur because it did not have appropriate resources. Although this error is similar tocudaErrorInvalidConfiguration, this error usually indicates that the user has attempted to pass too many arguments to the device kernel, or the kernellaunch specifies too many threads for the kernel's register count.] (at /paddle/paddle/fluid/operators/math/squared_l2_norm.h:77)
  [operator < squared_l2_norm > error]

**Comment by DevilMay-Cry** [comment]
> @DevilMay-Cry PaddlePaddle和PaddleDetection的版本分别是多少？将worker_num设成0再试下呢？https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/configs/ppyolo/_base_/ppyolov2_reader.yml#L1

您好 可以帮忙看下新的异常是什么问题吗
