### ISSUE TITLE
多卡训练 module 'paddle.fluid.core_avx.ops' has no attribute 'c_broadcast'

### ISSUE THREAD

**Issue by heyiamarthur** [PaddlePaddle/PaddleDetection#6183]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

使用PaddleDetection双卡训练PPYOLOE，报错信息如下：
```
ubuntu@ubuntu-Predator-PO9-920:~/PaddleDetection$ python3 -m paddle.distributed.launch --gpus 0,1 tools/train.py -c experiments/ppyoloe.yml --eval --use_vdl=true --vdl_log_dir=vdl_log
LAUNCH INFO 2022-06-09 20:19:33,609 -----------  Configuration  ----------------------
LAUNCH INFO 2022-06-09 20:19:33,609 devices: None
LAUNCH INFO 2022-06-09 20:19:33,609 elastic_level: -1
LAUNCH INFO 2022-06-09 20:19:33,609 elastic_timeout: 30
LAUNCH INFO 2022-06-09 20:19:33,609 gloo_port: 6767
LAUNCH INFO 2022-06-09 20:19:33,609 host: None
LAUNCH INFO 2022-06-09 20:19:33,609 job_id: default
LAUNCH INFO 2022-06-09 20:19:33,609 legacy: False
LAUNCH INFO 2022-06-09 20:19:33,609 log_dir: log
LAUNCH INFO 2022-06-09 20:19:33,609 log_level: INFO
LAUNCH INFO 2022-06-09 20:19:33,609 master: None
LAUNCH INFO 2022-06-09 20:19:33,609 max_restart: 3
LAUNCH INFO 2022-06-09 20:19:33,609 nnodes: 1
LAUNCH INFO 2022-06-09 20:19:33,609 nproc_per_node: None
LAUNCH INFO 2022-06-09 20:19:33,609 rank: -1
LAUNCH INFO 2022-06-09 20:19:33,609 run_mode: collective
LAUNCH INFO 2022-06-09 20:19:33,609 server_num: None
LAUNCH INFO 2022-06-09 20:19:33,609 servers: 
LAUNCH INFO 2022-06-09 20:19:33,609 trainer_num: None
LAUNCH INFO 2022-06-09 20:19:33,609 trainers: 
LAUNCH INFO 2022-06-09 20:19:33,609 training_script: 0,1
LAUNCH INFO 2022-06-09 20:19:33,609 training_script_args: ['tools/train.py', '-c', 'experiments/ppyoloe.yml', '--eval', '--use_vdl=true', '--vdl_log_dir=vdl_log']
LAUNCH INFO 2022-06-09 20:19:33,609 with_gloo: 0
LAUNCH INFO 2022-06-09 20:19:33,609 --------------------------------------------------
LAUNCH WARNING 2022-06-09 20:19:33,609 Compatible mode enable with args ['--gpus']
-----------  Configuration Arguments -----------
backend: auto
cluster_topo_path: None
elastic_pre_hook: None
elastic_server: None
enable_auto_mapping: False
force: False
gpus: 0,1
heter_devices: 
heter_worker_num: None
heter_workers: 
host: None
http_port: None
ips: 127.0.0.1
job_id: None
log_dir: log
np: None
nproc_per_node: None
rank_mapping_path: None
run_mode: None
scale: 0
server_num: None
servers: 
training_script: tools/train.py
training_script_args: ['-c', 'experiments/ppyoloe.yml', '--eval', '--use_vdl=true', '--vdl_log_dir=vdl_log']
worker_num: None
workers: 
------------------------------------------------
WARNING 2022-06-09 20:19:33,610 launch.py:518] Not found distinct arguments and compiled with cuda or xpu or npu or mlu. Default use collective mode
WARNING 2022-06-09 20:19:33,610 launch.py:518] Not found distinct arguments and compiled with cuda or xpu or npu or mlu. Default use collective mode
launch train in GPU mode!
INFO 2022-06-09 20:19:33,611 launch_utils.py:558] Local start 2 processes. First process distributed environment info (Only For Debug): 
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:49547               |
    |                     PADDLE_TRAINERS_NUM                        2                      |
    |                PADDLE_TRAINER_ENDPOINTS         127.0.0.1:49547,127.0.0.1:55735       |
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                       0,1                     |
    |                     FLAGS_selected_gpus                        0                      |
    |             FLAGS_selected_accelerators                        0                      |
    +=======================================================================================+

INFO 2022-06-09 20:19:33,611 launch_utils.py:558] Local start 2 processes. First process distributed environment info (Only For Debug): 
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:49547               |
    |                     PADDLE_TRAINERS_NUM                        2                      |
    |                PADDLE_TRAINER_ENDPOINTS         127.0.0.1:49547,127.0.0.1:55735       |
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                       0,1                     |
    |                     FLAGS_selected_gpus                        0                      |
    |             FLAGS_selected_accelerators                        0                      |
    +=======================================================================================+

INFO 2022-06-09 20:19:33,611 launch_utils.py:563] details about PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
INFO 2022-06-09 20:19:33,611 launch_utils.py:563] details about PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
launch proc_id:12124 idx:0
launch proc_id:12129 idx:1
/home/ubuntu/.local/lib/python3.8/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:55735']
I0609 20:19:38.698607 12124 nccl_context.cc:83] init nccl context nranks: 2 local rank: 0 gpu id: 0 ring id: 0
W0609 20:19:38.904320 12124 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.2
W0609 20:19:38.906757 12124 gpu_context.cc:306] device: 0, cuDNN Version: 8.2.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[06/09 20:19:40] ppdet.utils.checkpoint INFO: ['yolo_head.anchor_points', 'yolo_head.stride_tensor'] in pretrained weight is not used in the model, and its will not be loaded
[06/09 20:19:40] ppdet.utils.checkpoint INFO: The shape [80] in pretrained weight yolo_head.pred_cls.0.bias is unmatched with the shape [2] in model yolo_head.pred_cls.0.bias. And the weight yolo_head.pred_cls.0.bias will not be loaded
[06/09 20:19:40] ppdet.utils.checkpoint INFO: The shape [80, 384, 3, 3] in pretrained weight yolo_head.pred_cls.0.weight is unmatched with the shape [2, 384, 3, 3] in model yolo_head.pred_cls.0.weight. And the weight yolo_head.pred_cls.0.weight will not be loaded
[06/09 20:19:40] ppdet.utils.checkpoint INFO: The shape [80] in pretrained weight yolo_head.pred_cls.1.bias is unmatched with the shape [2] in model yolo_head.pred_cls.1.bias. And the weight yolo_head.pred_cls.1.bias will not be loaded
[06/09 20:19:40] ppdet.utils.checkpoint INFO: The shape [80, 192, 3, 3] in pretrained weight yolo_head.pred_cls.1.weight is unmatched with the shape [2, 192, 3, 3] in model yolo_head.pred_cls.1.weight. And the weight yolo_head.pred_cls.1.weight will not be loaded
[06/09 20:19:40] ppdet.utils.checkpoint INFO: The shape [80] in pretrained weight yolo_head.pred_cls.2.bias is unmatched with the shape [2] in model yolo_head.pred_cls.2.bias. And the weight yolo_head.pred_cls.2.bias will not be loaded
[06/09 20:19:40] ppdet.utils.checkpoint INFO: The shape [80, 96, 3, 3] in pretrained weight yolo_head.pred_cls.2.weight is unmatched with the shape [2, 96, 3, 3] in model yolo_head.pred_cls.2.weight. And the weight yolo_head.pred_cls.2.weight will not be loaded
[06/09 20:19:41] ppdet.utils.checkpoint INFO: Finish loading model weights: weights/ppyoloe_crn_s_300e_coco.pdparams
Traceback (most recent call last):
  File "tools/train.py", line 177, in <module>
    main()
  File "tools/train.py", line 173, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/home/ubuntu/PaddleDetection/ppdet/engine/trainer.py", line 392, in train
    model = paddle.DataParallel(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/parallel.py", line 620, in __init__
    sync_params_buffers(self._layers)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 299, in __impl__
    return func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/framework.py", line 434, in __impl__
    return func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/parallel.py", line 400, in sync_params_buffers
    paddle.distributed.broadcast(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/distributed/collective.py", line 570, in broadcast
    return _C_ops.c_broadcast(tensor, tensor, 'root', gsrc,
AttributeError: module 'paddle.fluid.core_avx.ops' has no attribute 'c_broadcast'
INFO 2022-06-09 20:19:42,647 launch_utils.py:322] terminate process group gid:12129
INFO 2022-06-09 20:19:42,647 launch_utils.py:322] terminate process group gid:12129
INFO 2022-06-09 20:19:46,651 launch_utils.py:343] terminate all the procs
INFO 2022-06-09 20:19:46,651 launch_utils.py:343] terminate all the procs
ERROR 2022-06-09 20:19:46,652 launch_utils.py:640] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0] was aborted. Please check its log.
ERROR 2022-06-09 20:19:46,652 launch_utils.py:640] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2022-06-09 20:19:50,656 launch_utils.py:343] terminate all the procs
INFO 2022-06-09 20:19:50,656 launch_utils.py:343] terminate all the procs
INFO 2022-06-09 20:19:50,657 launch.py:402] Local processes completed.
INFO 2022-06-09 20:19:50,657 launch.py:402] Local processes completed.
```

目前使用的是Paddle2.3.0（linux-cuda11.2-cudnn8.2-trt8-gcc8.2），多卡训练报错。在上一个版本，即Paddle2.2（linux-cuda11.1-cudnn8.1-trt7-gcc8.2）是能够正常启动ppyoloe的多卡训练的。

### 复现环境 Environment

- PaddlePaddle 2.3
- PaddleDetection 2.4
- Python 3.8
- CUDA 11.2
- cuDnn 8.2.1
- NCCL ubuntu2004-2.8.4-cuda11.2
- TensorRT8.2.5.1
- RTX 3090双卡

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
你下载的paddle有问题，应该是没有开distributed。建议先换回原先能正常运行的版本。
也可以向paddle提issue，https://github.com/PaddlePaddle/Paddle/issues

**Comment by TerryMat1999** [comment]
![image](https://user-images.githubusercontent.com/47450804/173233995-bafc94a9-373e-41fe-bf4c-483106ac9701.png)
我又下了一遍，还是不行啊。
