### ISSUE TITLE
安装后测试test_architectures.py报错

### ISSUE THREAD

**Issue by Aurora-vu** [PaddlePaddle/PaddleDetection#6219]
### 问题描述 Please describe your issue

安装paddledetection前面的过程很顺利，但是测试时运行python test_architectures.py出现如下报错：（求大佬解答）

home/zhou/anaconda3/lib/python3.8/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
EW0617 12:01:41.747937 361302 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.2, Runtime API Version: 11.2
W0617 12:01:41.751001 361302 gpu_context.cc:306] device: 0, cuDNN Version: 7.6.
EEEEEE
======================================================================
ERROR: test_trainer (__main__.TestCascadeRCNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_architectures.py", line 34, in test_trainer
    cfg = ppdet.core.workspace.load_config(self.cfg_file)
  File "/home/zhou/anaconda3/lib/python3.8/site-packages/paddledet-2.4.0-py3.8.egg/ppdet/core/workspace.py", line 114, in load_config
    cfg = _load_config_with_base(file_path)
  File "/home/zhou/anaconda3/lib/python3.8/site-packages/paddledet-2.4.0-py3.8.egg/ppdet/core/workspace.py", line 78, in _load_config_with_base
    with open(file_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/cascade_rcnn/cascade_rcnn_r50_fpn_1x_coco.yml'

======================================================================
ERROR: test_trainer (__main__.TestFasterRCNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_architectures.py", line 35, in test_trainer
    trainer = ppdet.engine.Trainer(cfg, mode='test')
  File "/home/zhou/anaconda3/lib/python3.8/site-packages/paddledet-2.4.0-py3.8.egg/ppdet/engine/trainer.py", line 102, in __init__
    self.model = create(cfg.architecture)
  File "/home/zhou/anaconda3/lib/python3.8/site-packages/paddledet-2.4.0-py3.8.egg/ppdet/core/workspace.py", line 246, in create
    cls_kwargs.update(cls.from_config(config, **kwargs))
  File "/home/zhou/anaconda3/lib/python3.8/site-packages/paddledet-2.4.0-py3.8.egg/ppdet/modeling/architectures/faster_rcnn.py", line 56, in from_config
    backbone = create(cfg['backbone'])
  File "/home/zhou/anaconda3/lib/python3.8/site-packages/paddledet-2.4.0-py3.8.egg/ppdet/core/workspace.py", line 283, in create
    return cls(**cls_kwargs)
  File "/home/zhou/anaconda3/lib/python3.8/site-packages/paddledet-2.4.0-py3.8.egg/ppdet/modeling/backbones/resnet.py", line 514, in __init__
    ConvNormLayer(
  File "/home/zhou/anaconda3/lib/python3.8/site-packages/paddledet-2.4.0-py3.8.egg/ppdet/modeling/backbones/resnet.py", line 61, in __init__
    self.conv = nn.Conv2D(
  File "/home/zhou/anaconda3/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 644, in __init__
    super(Conv2D, self).__init__(
  File "/home/zhou/anaconda3/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 133, in __init__
    self.weight = self.create_parameter(
  File "/home/zhou/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 423, in create_parameter
    return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
  File "/home/zhou/anaconda3/lib/python3.8/site-packages/paddle/fluid/layer_helper_base.py", line 376, in create_parameter
    return self.main_program.global_block().create_parameter(
  File "/home/zhou/anaconda3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3572, in create_parameter
    initializer(param, self)
  File "/home/zhou/anaconda3/lib/python3.8/site-packages/paddle/fluid/initializer.py", line 365, in __call__
    out_var = _C_ops.gaussian_random(
OSError: (External) CUBLAS error(7). 
  [Hint: 'CUBLAS_STATUS_INVALID_VALUE'.  An unsupported value or parameter was passed to the function (a negative vector size, for example). To correct: ensure that all the parameters being passed have valid values. ] (at /paddle/paddle/phi/backends/gpu/gpu_context.cc:424)
  [operator < gaussian_random > error]

======================================================================
ERROR: test_trainer (__main__.TestGFL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_architectures.py", line 34, in test_trainer
    cfg = ppdet.core.workspace.load_config(self.cfg_file)
  File "/home/zhou/anaconda3/lib/python3.8/site-packages/paddledet-2.4.0-py3.8.egg/ppdet/core/workspace.py", line 114, in load_config
    cfg = _load_config_with_base(file_path)
  File "/home/zhou/anaconda3/lib/python3.8/site-packages/paddledet-2.4.0-py3.8.egg/ppdet/core/workspace.py", line 78, in _load_config_with_base
    with open(file_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/gfl/gfl_r50_fpn_1x_coco.yml'

======================================================================
ERROR: test_trainer (__main__.TestMaskRCNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_architectures.py", line 34, in test_trainer
    cfg = ppdet.core.workspace.load_config(self.cfg_file)
  File "/home/zhou/anaconda3/lib/python3.8/site-packages/paddledet-2.4.0-py3.8.egg/ppdet/core/workspace.py", line 114, in load_config
    cfg = _load_config_with_base(file_path)
  File "/home/zhou/anaconda3/lib/python3.8/site-packages/paddledet-2.4.0-py3.8.egg/ppdet/core/workspace.py", line 78, in _load_config_with_base
    with open(file_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.yml'

======================================================================
ERROR: test_trainer (__main__.TestPicoDet)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_architectures.py", line 34, in test_trainer
    cfg = ppdet.core.workspace.load_config(self.cfg_file)
  File "/home/zhou/anaconda3/lib/python3.8/site-packages/paddledet-2.4.0-py3.8.egg/ppdet/core/workspace.py", line 114, in load_config
    cfg = _load_config_with_base(file_path)
  File "/home/zhou/anaconda3/lib/python3.8/site-packages/paddledet-2.4.0-py3.8.egg/ppdet/core/workspace.py", line 78, in _load_config_with_base
    with open(file_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/picodet/picodet_s_320_coco_lcnet.yml'

======================================================================
ERROR: test_trainer (__main__.TestSSD)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_architectures.py", line 34, in test_trainer
    cfg = ppdet.core.workspace.load_config(self.cfg_file)
  File "/home/zhou/anaconda3/lib/python3.8/site-packages/paddledet-2.4.0-py3.8.egg/ppdet/core/workspace.py", line 114, in load_config
    cfg = _load_config_with_base(file_path)
  File "/home/zhou/anaconda3/lib/python3.8/site-packages/paddledet-2.4.0-py3.8.egg/ppdet/core/workspace.py", line 78, in _load_config_with_base
    with open(file_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/ssd/ssd_vgg16_300_240e_voc.yml'

======================================================================
ERROR: test_trainer (__main__.TestYolov3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_architectures.py", line 34, in test_trainer
    cfg = ppdet.core.workspace.load_config(self.cfg_file)
  File "/home/zhou/anaconda3/lib/python3.8/site-packages/paddledet-2.4.0-py3.8.egg/ppdet/core/workspace.py", line 114, in load_config
    cfg = _load_config_with_base(file_path)
  File "/home/zhou/anaconda3/lib/python3.8/site-packages/paddledet-2.4.0-py3.8.egg/ppdet/core/workspace.py", line 78, in _load_config_with_base
    with open(file_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/yolov3/yolov3_darknet53_270e_coco.yml'

----------------------------------------------------------------------
Ran 7 tests in 40.179s

**Comment by jerrywgz** [comment]
python ppdet/modeling/tests/test_architectures.py 需要在PaddleDetection目录下运行

**Comment by Aurora-vu** [comment]
> python ppdet/modeling/tests/test_architectures.py 需要在PaddleDetection目录下运行
按照你的办法来做还是出现上面同样的报错......
