### ISSUE TITLE
训练PPYOLOE失败！

### ISSUE THREAD

**Issue by hhxdestiny** [PaddlePaddle/PaddleDetection#6233]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

使用BML CodeLab训练PPYOLOE失败！

执行代码(notebook)
```python
# clone code
# !cd /home/aistudio/work && git clone -b release/2.4 https://github.com/PaddlePaddle/PaddleDetection.git
# install depends
!cd /home/aistudio/work/PaddleDetection && pip install -r requirements.txt
# train
!cd /home/aistudio/work/PaddleDetection && python tools/train.py -c configs/ppyoloe/ppyoloe_crn_l_300e_coco.yml --amp
```

shell
```shell
Traceback (most recent call last):
  File "tools/train.py", line 32, in <module>
    from ppdet.core.workspace import load_config, merge_config
  File "/home/aistudio/work/PaddleDetection/ppdet/__init__.py", line 15, in <module>
    from . import (core, data, engine, modeling, model_zoo, optimizer, metrics,
  File "/home/aistudio/work/PaddleDetection/ppdet/data/__init__.py", line 16, in <module>
    from . import transform
  File "/home/aistudio/work/PaddleDetection/ppdet/data/transform/__init__.py", line 15, in <module>
    from . import operators
  File "/home/aistudio/work/PaddleDetection/ppdet/data/transform/operators.py", line 44, in <module>
    from ppdet.modeling import bbox_utils
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/__init__.py", line 23, in <module>
    from . import heads
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/heads/__init__.py", line 17, in <module>
    from . import yolo_head
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/heads/yolo_head.py", line 26, in <module>
    from ..losses import IouLoss
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/losses/__init__.py", line 26, in <module>
    from . import detr_loss
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/losses/detr_loss.py", line 24, in <module>
    from ..transformers import bbox_cxcywh_to_xyxy, sigmoid_focal_loss
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/transformers/__init__.py", line 17, in <module>
    from . import matchers
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/transformers/matchers.py", line 25, in <module>
    from scipy.optimize import linear_sum_assignment
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/scipy/__init__.py", line 153, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/scipy/_lib/_ccallback.py", line 1, in <module>
    from . import _ccallback_c
ImportError: /home/aistudio/.data/webide/pip/lib/python3.7/site-packages/scipy/_lib/_ccallback_c.cpython-37m-x86_64-linux-gnu.so: invalid ELF header
```

### 复现环境 Environment

- Platform: BML CodeLab
- PaddlePaddle 2.3.0
- PaddleDetection release/2.4

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
python版本是是多少，另外建议重新安装一下scipy试一下

**Comment by hhxdestiny** [comment]
> python版本是是多少，另外建议重新安装一下scipy试一下

重装scipy后可以了，降了版本scipy 1.7.3 -> scipy 1.6.3，感谢
```bash
aistudio@jupyter-553237-4247323:~$ pip uninstall scipy
Found existing installation: scipy 1.7.3
Uninstalling scipy-1.7.3:
  Would remove:
    /home/aistudio/.data/webide/pip/lib/python3.7/site-packages/scipy-1.7.3.dist-info/*
    /home/aistudio/.data/webide/pip/lib/python3.7/site-packages/scipy.libs/libgfortran-2e0d59d6.so.5.0.0
    /home/aistudio/.data/webide/pip/lib/python3.7/site-packages/scipy.libs/libopenblasp-r0-2d23e62b.3.17.so
    /home/aistudio/.data/webide/pip/lib/python3.7/site-packages/scipy.libs/libquadmath-2d0c479f.so.0.0.0
    /home/aistudio/.data/webide/pip/lib/python3.7/site-packages/scipy/*
Proceed (Y/n)? y
  Successfully uninstalled scipy-1.7.3
aistudio@jupyter-553237-4247323:~$ pip install scipy
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: scipy in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (1.6.3)
Requirement already satisfied: numpy<1.23.0,>=1.16.5 in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from scipy) (1.19.5)
```
