### ISSUE TITLE
CrossEntropyWithSoftmaxCUDAKernel

### ISSUE THREAD

**Issue by cccrice** [PaddlePaddle/PaddleDetection#6263]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

Traceback (most recent call last):
  File "G:/学习/飞桨学习课程/语义分割/case_pet_seg/Unet.py", line 163, in <module>
    batch_size=2)
  File "C:\Program Files\Python36\lib\site-packages\paddle\hapi\model.py", line 1767, in fit
    logs = self._run_one_epoch(train_loader, cbks, 'train')
  File "C:\Program Files\Python36\lib\site-packages\paddle\hapi\model.py", line 2097, in _run_one_epoch
    outs = getattr(self, mode + '_batch')(*_inputs)
  File "C:\Program Files\Python36\lib\site-packages\paddle\hapi\model.py", line 1093, in train_batch
    loss = self._adapter.train_batch(inputs, labels, update)
  File "C:\Program Files\Python36\lib\site-packages\paddle\hapi\model.py", line 730, in train_batch
    losses = self.model._loss(*(to_list(outputs) + labels))
  File "C:\Program Files\Python36\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\paddle\nn\layer\loss.py", line 406, in forward
    name=self.name)
  File "C:\Program Files\Python36\lib\site-packages\paddle\nn\functional\loss.py", line 1734, in cross_entropy
    'use_softmax', use_softmax)
SystemError: (Fatal) Operator softmax_with_cross_entropy raises an struct paddle::PD_Exception exception.
The exception content is
:function "CrossEntropyWithSoftmaxCUDAKernel" is not implemented for data type `float32`
  [../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1544]. (at ..\paddle\fluid\imperative\tracer.cc:307)

### 复现环境 Environment

- PaddlePaddle: GPU 2.3.0
- Windows: 10
- CUDA: 10.2
- CUDNN: 7.6

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by zoooo0820** [comment]
你好，看起来是算子数据类型支持的问题。因为是分割任务的内容，详细情况辛苦移步PaddleSeg提一个issue呢。 https://github.com/PaddlePaddle/PaddleSeg/issues
