### ISSUE TITLE
静态图模型敏感度分析时的问题

### ISSUE THREAD

**Issue by wangplin** [PaddlePaddle/PaddleDetection#6333]
### 问题描述 Please describe your issue

我是用的是paddleslim 2.1ppdet 2.1.0 static下的sensitive来做 configs下的ssd_mobilenet_v1_voc的敏感度分析，在执行分析时，一直报以下的错误。

Traceback (most recent call last):
  File "sensitive.py", line 203, in <module>
    main()
  File "sensitive.py", line 160, in main
    pruned_ratios=pruned_ratios)
  File "/home/wyx/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddleslim/prune/sensitive.py", line 103, in sensitivity
    param_backup=True)
  File "/home/wyx/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddleslim/prune/pruner.py", line 101, in prune
    ratios)  # name, axis, idx, transform
  File "/home/wyx/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddleslim/prune/idx_selector.py", line 50, in default_idx_selector
    score = scores[name][axis]
KeyError: 0

我在其他issue里看到说是ppdet 和 paddleslim 版本要对应，但我也检查了版本是没问题的。

**Comment by wangplin** [comment]
这个问题暂时解决了，但还是有时会出现。

**Comment by SunYF-0729** [comment]
你好，我在做ssd_mobilenet_v1的静态图剪裁的时候也有这个问题，兄弟你怎么解决的？
![SWIE5~1 $S@B~8Y@%TW$7CC](https://user-images.githubusercontent.com/109390344/179315276-a9a10b70-7d36-4674-beb3-30830e1ab47b.png)

**Comment by SunYF-0729** [comment]
你好，请问怎么解决的，我也碰到这个问题了 @wangplin
