### ISSUE TITLE
推理时开启--save_results报错

### ISSUE THREAD

**Issue by DLlearn** [PaddlePaddle/PaddleDetection#6367]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

使用的是paddledetection12.4版本，在完成模型训练后，调用python tools/infer.py -c configs/something -o weights=something --save_results=True报错，不加这个参数，其它的都能正常运行，画出图片的结果。本意是想要把推理的结果保存到文档的。
报错内容：
[07/06 14:21:33] ppdet.utils.checkpoint INFO: Finish loading model weights: output/picodet_l_640_voc_lcnet_my/4.pdparams
Traceback (most recent call last):
  File "tools/infer.py", line 177, in <module>
    main()
  File "tools/infer.py", line 173, in main
    run(FLAGS, cfg)
  File "tools/infer.py", line 134, in run
    save_results=FLAGS.save_results)
  File "/home/tl/PaddleDetection/ppdet/engine/trainer.py", line 591, in predict
    metrics = setup_metrics_for_loader()
  File "/home/tl/PaddleDetection/ppdet/engine/trainer.py", line 573, in setup_metrics_for_loader
    self._init_metrics()
  File "/home/tl/PaddleDetection/ppdet/engine/trainer.py", line 280, in _init_metrics
    label_list=self.dataset.get_label_list(),
AttributeError: 'ImageFolder' object has no attribute 'get_label_list'

### 复现环境 Environment

- paddle 2.2.2
- paddledetction release/2.4
- python3.7.12
- cuda 11.3
- cudnn 8 

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by seyosum** [comment]
请问这个问题您解决了嘛 我今天也是想保存推理结果 加了save_results就会报这个错 求助！！！

**Comment by DLlearn** [comment]
> 请问这个问题您解决了嘛 我今天也是想保存推理结果 加了save_results就会报这个错 求助！！！

没有解决，这个应该是这部分代码有错误，不想自己改了。可以使用deploy中的infer.py 里边也有一个保存结果的方法，我找到一个博客https://blog.csdn.net/u011119817/article/details/125665410?spm=1001.2014.3001.5501 你可以看看

**Comment by seyosum** [comment]
太感谢啦！！！
