### ISSUE TITLE
faster_rcnn_swin_tiny_fpn_3x_coco 模型导出后推理报错

### ISSUE THREAD

**Issue by NanyuZhang0812** [PaddlePaddle/PaddleDetection#6373]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我导出了一个训练好的faster_rcnn_swin_tiny_fpn_3x_coco模型，使用deploy\python\infer.py进行推理时报错
`Traceback (most recent call last):
  File ".\deploy\python\infer.py", line 909, in <module>
    main()
  File ".\deploy\python\infer.py", line 881, in main
    detector.predict_image(
  File ".\deploy\python\infer.py", line 278, in predict_image
    result = self.predict()
  File ".\deploy\python\infer.py", line 206, in predict
    self.predictor.run()
ValueError: In user code:

    File ".\tools\export_model.py", line 111, in <module>
      main()
    File ".\tools\export_model.py", line 107, in main
      run(FLAGS, cfg)
    File ".\tools\export_model.py", line 73, in run
      trainer.export(FLAGS.output_dir)
    File "E:\Graduation-project\PaddleDetection\ppdet\engine\trainer.py", line 774, in export
      static_model, pruned_input_spec = self._get_infer_cfg_and_input_spec(
    File "E:\Graduation-project\PaddleDetection\ppdet\engine\trainer.py", line 752, in _get_infer_cfg_and_input_spec
      input_spec, static_model.forward.main_program,
    File "E:\anaconda3\envs\cv\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 563, in main_program
      concrete_program = self.concrete_program
    File "E:\anaconda3\envs\cv\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 479, in concrete_program
      return self.concrete_program_specify_input_spec(input_spec=None)
    File "E:\anaconda3\envs\cv\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 516, in concrete_program_specify_input_spec
      concrete_program, _ = self.get_concrete_program(
    File "E:\anaconda3\envs\cv\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 427, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "E:\anaconda3\envs\cv\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 723, in __getitem__
      self._caches[item] = self._build_once(item)
    File "E:\anaconda3\envs\cv\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 709, in _build_once
      concrete_program = ConcreteProgram.from_func_spec(
    File "E:\anaconda3\envs\cv\lib\site-packages\decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "E:\anaconda3\envs\cv\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "E:\anaconda3\envs\cv\lib\site-packages\paddle\fluid\dygraph\base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "E:\anaconda3\envs\cv\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 662, in from_func_spec
      outputs = static_func(*inputs)
    File "C:\Users\Youzi\AppData\Local\Temp\tmpv6lyrwkj.py", line 99, in forward
      out = paddle.jit.dy2static.convert_ifelse(self.training, true_fn_5,
    File "E:\anaconda3\envs\cv\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "E:\anaconda3\envs\cv\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "C:\Users\Youzi\AppData\Local\Temp\tmpv6lyrwkj.py", line 82, in false_fn_5
      ] = paddle.jit.dy2static.convert_while_loop(for_loop_condition_0,
    File "E:\anaconda3\envs\cv\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 45, in convert_while_loop
      loop_vars = _run_py_while(cond, body, loop_vars)
    File "E:\anaconda3\envs\cv\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 59, in _run_py_while
      loop_vars = body(*loop_vars)
    File "E:\Graduation-project\PaddleDetection\ppdet\modeling\architectures\meta_arch.py", line 74, in forward
      self.inputs = inp
    File "E:\Graduation-project\PaddleDetection\ppdet\modeling\architectures\faster_rcnn.py", line 104, in get_pred
      bbox_pred, bbox_num = self._forward()
    File "E:\Graduation-project\PaddleDetection\ppdet\modeling\architectures\faster_rcnn.py", line 72, in _forward
      body_feats = self.backbone(self.inputs)
    File "E:\anaconda3\envs\cv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "E:\anaconda3\envs\cv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "E:\Graduation-project\PaddleDetection\ppdet\modeling\backbones\swin_transformer.py", line 715, in forward
      x = self.patch_embed(x['image'])
    File "E:\anaconda3\envs\cv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "E:\anaconda3\envs\cv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "C:\Users\Youzi\AppData\Local\Temp\tmpb836poo9.py", line 71, in forward
      x = paddle.jit.dy2static.convert_ifelse(self.norm is not None,
    File "E:\anaconda3\envs\cv\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "E:\anaconda3\envs\cv\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "E:\Graduation-project\PaddleDetection\ppdet\modeling\backbones\swin_transformer.py", line 558, in forward
      x = self.norm(x)
    File "E:\anaconda3\envs\cv\lib\site-packages\paddle\tensor\manipulation.py", line 2001, in reshape
      return paddle.fluid.layers.reshape(x=x, shape=shape, name=name)
    File "E:\anaconda3\envs\cv\lib\site-packages\paddle\fluid\layers\nn.py", line 6268, in reshape
      helper.append_op(
    File "E:\anaconda3\envs\cv\lib\site-packages\paddle\fluid\layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "E:\anaconda3\envs\cv\lib\site-packages\paddle\fluid\framework.py", line 3178, in append_op
      op = Operator(
    File "E:\anaconda3\envs\cv\lib\site-packages\paddle\fluid\framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The 'shape' attribute in ReshapeOp is invalid. The input tensor X'size must be divisible by known capacity of 'shape'. But received X's shape = [1, 96, 19200], X's size = 1843200, 'shape' is [-1, 96, 160, 160], known capacity of 'shape' is -2457600.
      [Hint: Expected output_shape[unk_dim_idx] * capacity == -in_size, but received output_shape[unk_dim_idx] * capacity:0 != -in_size:-1843200.] (at ..\paddle/fluid/operators/reshape_op.cc:210)
      [operator < reshape2 > error]`

模型导出前可正常推理，导出后预测使用的图片是验证集中相同图片

**Comment by lyuwenyu** [comment]
你怎么导出的 改什么了没

**Comment by NanyuZhang0812** [comment]
> 你怎么导出的 改什么了没
参考官方文档导出的，只在训练过程中更改过学习率。issues有几个和我一样的问题也没解决

**Comment by lyuwenyu** [comment]
好的 我们最近看下 是不是升级导致的

**Comment by lyuwenyu** [comment]
已更新 https://github.com/PaddlePaddle/PaddleDetection/pull/6399 请看这个PR  @Yz773
