### ISSUE TITLE
ppyolo 预测list index out of range问题

### ISSUE THREAD

**Issue by 1chang37** [PaddlePaddle/PaddleDetection#6395]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

环境：
paddlepaddle 2.2
kylin v10
os：ft2000+
paddledetection：2.4

指令：python3 deploy/python/infer.py --model_dir=output_inference/ppyolo_r50vd_dcn_1x_coco --image_dir=demo  --device=CPU
报错日志：
-----------  Running Arguments -----------
batch_size: 1
camera_id: -1
cpu_threads: 1
device: CPU
enable_mkldnn: False
image_dir: demo
image_file: None
model_dir: output_inference/ppyolo_r50vd_dcn_1x_coco
output_dir: output
reid_batch_size: 50
reid_model_dir: None
run_benchmark: False
run_mode: paddle
save_images: False
save_mot_txt_per_img: False
save_mot_txts: False
scaled: False
threshold: 0.5
trt_calib_mode: False
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
use_dark: True
use_gpu: False
video_file: None
------------------------------------------
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order: 
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
---    Fused 0 subgraphs into layer_norm op.
Found 10 inference images in total.
class_id:0, confidence:1.0000, left_top:[0.00,113.84],right_bottom:[639.00,113.84]
class_id:0, confidence:1.0000, left_top:[0.00,309.32],right_bottom:[639.00,309.32]
class_id:0, confidence:1.0000, left_top:[0.00,208.58],right_bottom:[639.00,208.58]
class_id:0, confidence:1.0000, left_top:[0.00,12.47],right_bottom:[639.00,12.47]
class_id:0, confidence:1.0000, left_top:[0.00,259.11],right_bottom:[639.00,259.11]
class_id:0, confidence:1.0000, left_top:[0.00,467.53],right_bottom:[639.00,467.53]
class_id:0, confidence:1.0000, left_top:[0.00,233.53],right_bottom:[639.00,233.53]
class_id:0, confidence:1.0000, left_top:[0.00,126.47],right_bottom:[639.00,126.47]
class_id:0, confidence:1.0000, left_top:[0.00,158.05],right_bottom:[639.00,158.05]
class_id:0, confidence:1.0000, left_top:[0.00,202.26],right_bottom:[639.00,202.26]
class_id:0, confidence:1.0000, left_top:[0.00,473.84],right_bottom:[639.00,473.84]
class_id:0, confidence:1.0000, left_top:[622.95,315.95],right_bottom:[622.95,315.95]
class_id:0, confidence:1.0000, left_top:[622.95,290.68],right_bottom:[622.95,290.68]
class_id:0, confidence:1.0000, left_top:[0.00,189.63],right_bottom:[639.00,189.63]
class_id:0, confidence:1.0000, left_top:[0.00,372.79],right_bottom:[639.00,372.79]
class_id:0, confidence:1.0000, left_top:[0.00,183.00],right_bottom:[639.00,183.00]
class_id:0, confidence:1.0000, left_top:[0.00,50.68],right_bottom:[639.00,50.68]
class_id:0, confidence:1.0000, left_top:[0.00,31.74],right_bottom:[639.00,31.74]
class_id:0, confidence:1.0000, left_top:[0.00,315.95],right_bottom:[639.00,315.95]
class_id:0, confidence:1.0000, left_top:[0.00,265.11],right_bottom:[639.00,265.11]
class_id:0, confidence:1.0000, left_top:[0.00,50.84],right_bottom:[639.00,50.84]
class_id:0, confidence:1.0000, left_top:[0.00,233.84],right_bottom:[639.00,233.84]
class_id:0, confidence:1.0000, left_top:[0.00,177.00],right_bottom:[639.00,177.00]
class_id:0, confidence:1.0000, left_top:[0.00,278.05],right_bottom:[639.00,278.05]
class_id:0, confidence:1.0000, left_top:[0.00,271.74],right_bottom:[639.00,271.74]
class_id:0, confidence:1.0000, left_top:[0.00,328.26],right_bottom:[639.00,328.26]
class_id:0, confidence:1.0000, left_top:[0.00,290.68],right_bottom:[639.00,290.68]
class_id:0, confidence:1.0000, left_top:[622.95,385.42],right_bottom:[622.95,385.42]
class_id:0, confidence:1.0000, left_top:[0.00,0.00],right_bottom:[639.00,-0.16]
class_id:0, confidence:1.0000, left_top:[622.95,94.89],right_bottom:[622.95,94.89]
class_id:0, confidence:1.0000, left_top:[622.95,50.68],right_bottom:[622.95,50.68]
class_id:0, confidence:1.0000, left_top:[0.00,221.21],right_bottom:[639.00,221.21]
class_id:0, confidence:1.0000, left_top:[0.00,353.37],right_bottom:[639.00,353.37]
class_id:0, confidence:1.0000, left_top:[622.95,158.05],right_bottom:[622.95,158.05]
class_id:0, confidence:1.0000, left_top:[0.00,119.84],right_bottom:[639.00,119.84]
class_id:0, confidence:1.0000, left_top:[0.00,284.37],right_bottom:[639.00,284.37]
class_id:0, confidence:1.0000, left_top:[0.00,151.74],right_bottom:[639.00,151.74]
class_id:0, confidence:1.0000, left_top:[0.00,170.68],right_bottom:[639.00,170.68]
class_id:0, confidence:1.0000, left_top:[0.00,195.63],right_bottom:[639.00,195.63]
class_id:0, confidence:1.0000, left_top:[0.00,82.26],right_bottom:[639.00,82.26]
class_id:0, confidence:1.0000, left_top:[0.00,214.58],right_bottom:[639.00,214.58]
class_id:0, confidence:1.0000, left_top:[0.00,360.16],right_bottom:[639.00,360.16]
class_id:0, confidence:1.0000, left_top:[0.00,145.42],right_bottom:[639.00,145.42]
class_id:0, confidence:1.0000, left_top:[0.00,120.16],right_bottom:[639.00,120.16]
class_id:0, confidence:1.0000, left_top:[34.11,189.16],right_bottom:[34.11,189.16]
class_id:0, confidence:1.0000, left_top:[0.00,461.21],right_bottom:[639.00,461.21]
class_id:0, confidence:1.0000, left_top:[622.95,139.11],right_bottom:[622.95,139.11]
class_id:0, confidence:1.0000, left_top:[0.00,435.84],right_bottom:[639.00,435.84]
class_id:0, confidence:1.0000, left_top:[0.00,467.05],right_bottom:[-0.29,467.05]
class_id:0, confidence:1.0000, left_top:[0.00,0.00],right_bottom:[639.00,-0.16]
class_id:0, confidence:1.0000, left_top:[0.00,265.42],right_bottom:[639.00,265.42]
class_id:0, confidence:1.0000, left_top:[0.00,227.53],right_bottom:[639.00,227.53]
class_id:0, confidence:1.0000, left_top:[0.00,321.95],right_bottom:[639.00,321.95]
class_id:0, confidence:1.0000, left_top:[0.00,233.84],right_bottom:[639.00,233.84]
class_id:0, confidence:1.0000, left_top:[0.00,427.51],right_bottom:[639.00,427.51]
class_id:0, confidence:1.0000, left_top:[0.00,94.58],right_bottom:[639.00,94.58]
class_id:0, confidence:1.0000, left_top:[0.00,214.89],right_bottom:[639.00,214.89]
class_id:0, confidence:1.0000, left_top:[0.00,322.26],right_bottom:[639.00,322.26]
class_id:0, confidence:1.0000, left_top:[0.00,164.37],right_bottom:[639.00,164.37]
class_id:0, confidence:1.0000, left_top:[622.95,435.95],right_bottom:[622.95,435.95]
class_id:0, confidence:1.0000, left_top:[0.00,195.95],right_bottom:[639.00,195.95]
class_id:0, confidence:1.0000, left_top:[0.00,0.00],right_bottom:[639.00,-0.16]
class_id:0, confidence:1.0000, left_top:[0.00,398.05],right_bottom:[639.00,398.05]
class_id:0, confidence:1.0000, left_top:[0.00,0.00],right_bottom:[639.00,-0.16]
class_id:0, confidence:1.0000, left_top:[622.95,404.37],right_bottom:[622.95,404.37]
class_id:0, confidence:1.0000, left_top:[0.00,57.00],right_bottom:[639.00,57.00]
class_id:0, confidence:1.0000, left_top:[0.00,403.89],right_bottom:[639.00,403.89]
class_id:0, confidence:1.0000, left_top:[0.00,63.32],right_bottom:[639.00,63.32]
class_id:0, confidence:1.0000, left_top:[622.95,391.74],right_bottom:[622.95,391.74]
class_id:0, confidence:1.0000, left_top:[0.00,252.79],right_bottom:[639.00,252.79]
class_id:0, confidence:1.0000, left_top:[0.00,341.21],right_bottom:[639.00,341.21]
class_id:0, confidence:1.0000, left_top:[0.00,94.89],right_bottom:[639.00,94.89]
class_id:0, confidence:1.0000, left_top:[0.00,391.26],right_bottom:[639.00,391.26]
class_id:0, confidence:1.0000, left_top:[622.95,410.68],right_bottom:[622.95,410.68]
class_id:0, confidence:1.0000, left_top:[0.00,353.84],right_bottom:[639.00,353.84]
class_id:0, confidence:1.0000, left_top:[0.00,0.00],right_bottom:[639.00,-0.16]
class_id:0, confidence:1.0000, left_top:[622.95,183.32],right_bottom:[622.95,183.32]
class_id:0, confidence:1.0000, left_top:[0.00,170.37],right_bottom:[639.00,170.37]
class_id:0, confidence:1.0000, left_top:[0.00,328.58],right_bottom:[639.00,328.58]
class_id:0, confidence:1.0000, left_top:[34.11,151.26],right_bottom:[34.11,151.26]
class_id:0, confidence:1.0000, left_top:[0.00,429.63],right_bottom:[639.00,429.63]
class_id:0, confidence:1.0000, left_top:[0.00,164.05],right_bottom:[639.00,164.05]
class_id:0, confidence:1.0000, left_top:[0.00,75.95],right_bottom:[639.00,75.95]
class_id:0, confidence:1.0000, left_top:[0.00,334.89],right_bottom:[639.00,334.89]
class_id:0, confidence:1.0000, left_top:[0.00,303.32],right_bottom:[639.00,303.32]
class_id:0, confidence:1.0000, left_top:[0.00,157.74],right_bottom:[639.00,157.74]
class_id:0, confidence:1.0000, left_top:[0.00,107.53],right_bottom:[639.00,107.53]
class_id:0, confidence:1.0000, left_top:[0.00,290.37],right_bottom:[639.00,290.37]
class_id:0, confidence:1.0000, left_top:[0.00,0.00],right_bottom:[639.00,-0.16]
class_id:0, confidence:1.0000, left_top:[0.00,0.00],right_bottom:[639.00,-0.16]
class_id:0, confidence:1.0000, left_top:[0.00,69.63],right_bottom:[639.00,69.63]
class_id:0, confidence:1.0000, left_top:[0.00,183.32],right_bottom:[639.00,183.32]
class_id:0, confidence:1.0000, left_top:[0.00,340.89],right_bottom:[639.00,340.89]
class_id:0, confidence:1.0000, left_top:[0.00,132.79],right_bottom:[639.00,132.79]
class_id:0, confidence:1.0000, left_top:[0.00,25.11],right_bottom:[639.00,25.11]
class_id:0, confidence:1.0000, left_top:[0.00,0.00],right_bottom:[639.00,-0.16]
class_id:0, confidence:1.0000, left_top:[0.00,0.00],right_bottom:[639.00,-0.16]
class_id:0, confidence:1.0000, left_top:[0.00,284.05],right_bottom:[639.00,284.05]
class_id:0, confidence:1.0000, left_top:[622.95,366.47],right_bottom:[622.95,366.47]
class_id:0, confidence:1.0000, left_top:[622.95,347.53],right_bottom:[622.95,347.53]
save result to: output/000000087038.jpg
class_id:0, confidence:1.0000, left_top:[0.00,0.00],right_bottom:[639.00,-0.16]
class_id:0, confidence:1.0000, left_top:[0.00,0.00],right_bottom:[639.00,-0.16]
class_id:0, confidence:1.0000, left_top:[0.00,0.00],right_bottom:[639.00,-0.16]
class_id:0, confidence:1.0000, left_top:[0.00,480.16],right_bottom:[639.00,479.00]
class_id:0, confidence:1.0000, left_top:[0.00,0.00],right_bottom:[639.00,-0.16]
class_id:0, confidence:1.0000, left_top:[0.00,0.00],right_bottom:[639.00,-0.16]
class_id:0, confidence:1.0000, left_top:[0.00,0.00],right_bottom:[639.00,-0.16]
class_id:0, confidence:1.0000, left_top:[0.00,0.00],right_bottom:[639.00,-0.16]
class_id:0, confidence:1.0000, left_top:[0.00,0.00],right_bottom:[639.00,-0.16]
class_id:0, confidence:1.0000, left_top:[0.00,0.00],right_bottom:[639.00,-0.16]
class_id:0, confidence:1.0000, left_top:[0.00,0.00],right_bottom:[639.00,-0.16]
class_id:0, confidence:1.0000, left_top:[0.00,0.00],right_bottom:[639.00,-0.16]
class_id:0, confidence:1.0000, left_top:[0.00,0.00],right_bottom:[639.00,-0.16]
class_id:0, confidence:1.0000, left_top:[0.00,480.16],right_bottom:[639.00,479.00]
Traceback (most recent call last):
  File "deploy/python/infer.py", line 778, in <module>
    main()
  File "deploy/python/infer.py", line 738, in main
    predict_image(detector, img_list, FLAGS.batch_size)
  File "deploy/python/infer.py", line 664, in predict_image
    threshold=FLAGS.threshold)
  File "deploy/python/infer.py", line 622, in visualize
    image_file, im_results, labels, threshold=threshold)
  File "/workspace/PaddleDetection/deploy/python/visualize.py", line 47, in visualize_box_mask
    im = draw_box(im, results['boxes'], labels, threshold=threshold)
  File "/workspace/PaddleDetection/deploy/python/visualize.py", line 136, in draw_box
    clsid2color[clsid] = color_list[clsid]
IndexError: list index out of range

**Comment by ghostxsl** [comment]
output_inference/ppyolo_r50vd_dcn_1x_coco这个目录下的infer_cfg.yml里的label_list请替换成自己数据集对应的标签

**Comment by 1chang37** [comment]
采用的也是uncategorized ，这块没有问题啊

**Comment by Dat0901** [comment]
> Please replace the label_list in infer_cfg.yml in the directory output_inference/ppyolo_r50vd_dcn_1x_coco with the label corresponding to your own data set.

I have tried this but then it only detect human with the label cell phone
Here is what I change in the infer_cfg.yml file:
mode: paddle
draw_threshold: 0.5
metric: COCO
use_dynamic_shape: false
arch: YOLO
min_subgraph_size: 3
Preprocess:
- interp: 2
  keep_ratio: false
  target_size:
    - 640
    - 640
  type: Resize
- mean:
    - 0.0
    - 0.0
    - 0.0
  norm_type: none
  std:
    - 1.0
    - 1.0
    - 1.0
  type: NormalizeImage
- type: Permute
label_list:
   - cell phone

here I want to only detect the cell phone in label_list. Is this the right way?
