### ISSUE TITLE
Faster RCNN Window 预测 报错

### ISSUE THREAD

**Issue by qingchunnianshao** [PaddlePaddle/PaddleDetection#6410]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

下载的已经编译好的paddle_inference库，支持本地电脑的版本以及cuda cudnn tensorRT版本
CUDA version: 10.2
CUDNN version: v7.6
CXX compiler version: 19.16.27045.0
WITH_TENSORRT: ON
TensorRT version: v7
显卡RTX2070Super

使用export_modle.py 导出导出faster_rcnn_r50_1x_voc.yml训练的模型
infer_cfg.yml如下：
mode: trt_fp32
draw_threshold: 0.5
metric: VOC
use_dynamic_shape: true
arch: RCNN
min_subgraph_size: 40
Preprocess:
- interp: 2
  keep_ratio: true
  target_size:
  - 2500
  - 2500
  type: Resize
- is_scale: true
  mean:
  - 0.6596901986291833
  - 0.6596901986291833
  std:
  - 0.10138360185013484
  - 0.10138360185013484
  type: NormalizeImage
- type: Permute
- stride: -1
  type: PadStride
label_list:
- "\u5D29\u89D2"
- "\u5212\u75D5"
- "\u88C2\u7EB9"
- "\u8868\u9762\u6742\u7269”

当mode:fluid时预测一切正常，但当将mode改为trt_fp16或者trt_fp32时 第一张图能够正常预测，但第二张（或者再次预测第一张图）预测会报错如下：
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: decrease dim should be 1
  [Hint: Expected out_dims[decrease_axis[i]] == 1, but received out_dims[decrease_axis[i]]:0 != 1:1.] (at C:/home/workspace/Paddle_release5/paddle/fluid/operators/slice_op.cc:147)
  [operator < slice > error]

详细堆栈信息：
Compile Traceback (most recent call last):
    File "/snap/pycharm-community/286/plugins/python-ce/helpers/pydev/pydevd.py"
, line 2181, in <module>
      main()
    File "/snap/pycharm-community/286/plugins/python-ce/helpers/pydev/pydevd.py"
, line 2172, in main
      globals = debugger.run(setup['file'], None, None, is_module)
    File "/snap/pycharm-community/286/plugins/python-ce/helpers/pydev/pydevd.py"
, line 1484, in run
      return self._exec(is_module, entry_point_fn, module_name, file, globals, l
ocals)
    File "/snap/pycharm-community/286/plugins/python-ce/helpers/pydev/pydevd.py"
, line 1491, in _exec
      pydev_imports.execfile(file, globals, locals)  # execute the script
    File "/snap/pycharm-community/286/plugins/python-ce/helpers/pydev/_pydev_imp
s/_pydev_execfile.py", line 18, in execfile
      exec(compile(contents+"\n", file, 'exec'), glob, loc)
    File "/home/tjzn/Downloads/PaddleDetection-release-2.3/tools/export_model.py
", line 115, in <module>
      main()
    File "/home/tjzn/Downloads/PaddleDetection-release-2.3/tools/export_model.py
", line 111, in main
      run(FLAGS, cfg)
    File "/home/tjzn/Downloads/PaddleDetection-release-2.3/tools/export_model.py
", line 77, in run
      trainer.export(FLAGS.output_dir)
    File "/home/tjzn/Downloads/PaddleDetection-release-2.3/ppdet/engine/trainer.
py", line 686, in export
      static_model, pruned_input_spec = self._get_infer_cfg_and_input_spec(
    File "/home/tjzn/Downloads/PaddleDetection-release-2.3/ppdet/engine/trainer.
py", line 664, in _get_infer_cfg_and_input_spec
      input_spec, static_model.forward.main_program,
    File "/home/tjzn/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/
dygraph_to_static/program_translator.py", line 563, in main_program
      concrete_program = self.concrete_program
    File "/home/tjzn/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/
dygraph_to_static/program_translator.py", line 479, in concrete_program
      return self.concrete_program_specify_input_spec(input_spec=None)
    File "/home/tjzn/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/
dygraph_to_static/program_translator.py", line 516, in concrete_program_specify_
input_spec
      concrete_program, _ = self.get_concrete_program(
    File "/home/tjzn/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/
dygraph_to_static/program_translator.py", line 427, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/home/tjzn/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/
dygraph_to_static/program_translator.py", line 744, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/home/tjzn/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/
dygraph_to_static/program_translator.py", line 730, in _build_once
      concrete_program = ConcreteProgram.from_func_spec(
    File "<decorator-gen-206>", line 2, in from_func_spec

    File "/home/tjzn/anaconda3/lib/python3.8/site-packages/paddle/fluid/wrapped_
decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/home/tjzn/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/
base.py", line 40, in __impl__
      return func(*args, **kwargs)
    File "/home/tjzn/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/
dygraph_to_static/program_translator.py", line 683, in from_func_spec
      outputs = static_func(*inputs)
    File "/tmp/tmpqpqzpt3g.py", line 42, in forward
      out = paddle.jit.dy2static.convert_ifelse(self.training, true_fn_2,
    File "/home/tjzn/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/
dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/home/tjzn/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/
dygraph_to_static/convert_operators.py", line 271, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/home/tjzn/Downloads/PaddleDetection-release-2.3/ppdet/modeling/archit
ectures/meta_arch.py", line 72, in forward
      out = self.get_pred()
    File "/home/tjzn/Downloads/PaddleDetection-release-2.3/ppdet/modeling/archit
ectures/faster_rcnn.py", line 104, in get_pred
      bbox_pred, bbox_num = self._forward()
    File "/tmp/tmp4dutrvx3.py", line 53, in _forward
      _, __return_value_0, rois, rois_num = paddle.jit.dy2static.convert_ifelse(

    File "/home/tjzn/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/
dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/home/tjzn/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/
dygraph_to_static/convert_operators.py", line 271, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/home/tjzn/Downloads/PaddleDetection-release-2.3/ppdet/modeling/archit
ectures/faster_rcnn.py", line 81, in _forward
      rois, rois_num, _ = self.rpn_head(body_feats, self.inputs)
    File "/home/tjzn/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/
layers.py", line 914, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/home/tjzn/Downloads/PaddleDetection-release-2.3/ppdet/modeling/propos
al_generator/rpn_head.py", line 131, in forward
      anchors = self.anchor_generator(rpn_feats)
    File "/home/tjzn/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/
layers.py", line 914, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/home/tjzn/Downloads/PaddleDetection-release-2.3/ppdet/modeling/propos
al_generator/anchor_generator.py", line 125, in forward
      anchors_over_all_feature_maps = self._grid_anchors(grid_sizes)
    File "/home/tjzn/Downloads/PaddleDetection-release-2.3/ppdet/modeling/propos
al_generator/anchor_generator.py", line 113, in _grid_anchors
      shift_x, shift_y = self._create_grid_offsets(size, stride,
    File "/home/tjzn/Downloads/PaddleDetection-release-2.3/ppdet/modeling/propos
al_generator/anchor_generator.py", line 99, in _create_grid_offsets
      grid_height, grid_width = size[0], size[1]
    File "/home/tjzn/anaconda3/lib/python3.8/site-packages/paddle/fluid/framewor
k.py", line 1783, in __getitem__
      return _getitem_impl_(self, item)
    File "/home/tjzn/anaconda3/lib/python3.8/site-packages/paddle/fluid/variable
_index.py", line 459, in _getitem_impl_
      target_block.append_op(
    File "/home/tjzn/anaconda3/lib/python3.8/site-packages/paddle/fluid/framewor
k.py", line 3178, in append_op
      op = Operator(
    File "/home/tjzn/anaconda3/lib/python3.8/site-packages/paddle/fluid/framewor
k.py", line 2224, in __init__
      for frame in traceback.extract_stack():

**Comment by zhiboniu** [comment]
你好，从报错无法定位，能否提供一下测试模型和脚本？

**Comment by qingchunnianshao** [comment]
你好，整个代码可能太多了，环境也比较复杂，我把这一块相关的代码整理出来到时发你帮我看下
