### ISSUE TITLE
最近的PPhuman V2 Reid 聚类阶段报错

### ISSUE THREAD

**Issue by liuguicen** [PaddlePaddle/PaddleDetection#6449]
### 问题确认 Search before asking

- [x] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

使用教程代码 多镜头文件夹里面放了多个视频

Traceback (most recent call last):
  File "/snap/pycharm-professional/290/plugins/python/helpers/pydev/pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-professional/290/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/D/tools/PaddleDetection/deploy/pipeline/pipeline.py", line 1021, in <module>
    main()
  File "/D/tools/PaddleDetection/deploy/pipeline/pipeline.py", line 1010, in main
    pipeline.run()
  File "/D/tools/PaddleDetection/deploy/pipeline/pipeline.py", line 159, in run
    mtmct_process(
  File "/D/tools/PaddleDetection/deploy/pipeline/pphuman/mtmct.py", line 335, in mtmct_process
    map_tid = sub_cluster(cid_tid_dict)
  File "/D/tools/PaddleDetection/deploy/pipeline/pphuman/mtmct.py", line 267, in sub_cluster
    clu = get_labels(cid_tid_dict, cid_tids)
  File "/D/tools/PaddleDetection/deploy/pipeline/pphuman/mtmct.py", line 244, in get_labels
    cost_matrix = get_sim_matrix_new(cid_tid_dict, cid_tids)
  File "/D/tools/PaddleDetection/deploy/pipeline/pphuman/mtmct.py", line 208, in get_sim_matrix_new
    distmat = get_dist_mat(q_arr, g_arr, func_name="cosine")
  File "/D/tools/PaddleDetection/deploy/pipeline/pphuman/mtmct.py", line 182, in get_dist_mat
    dist_mat = get_cosine(x, y)
  File "/D/tools/PaddleDetection/deploy/pipeline/pphuman/mtmct.py", line 176, in get_cosine
    sim_mt = cosine_similarity(x, y, eps)
  File "/D/tools/PaddleDetection/deploy/pipeline/pphuman/mtmct.py", line 160, in cosine_similarity
    x_n, y_n = np.linalg.norm(
  File "<__array_function__ internals>", line 5, in norm
  File "/home/lgc/anaconda3/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 2560, in norm
    return sqrt(add.reduce(s, axis=axis, keepdims=keepdims))
numpy.AxisError: axis 1 is out of bounds for array of dimension 1

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by zhiboniu** [comment]
你好，这个应该是x、y变量内容为空引起的，辛苦顺着流程打印一下变量看看，是哪里的原因导致的元素为空。
因为视频没有检测到目标的情况在mtmct.py的L332做过了判断，需要看看有什么别的原因引起的 。
    if len(cid_tid_dict) == 0:
        print("no tracking result found, mtmct will be skiped.")
        return

**Comment by weilenglxl** [comment]
你好，请问issue解决了吗？我也是聚类阶段报这个错，Unbuntu18.04+cuda10.2+cudnn7.6.5。

**Comment by dFuong** [comment]
@zhiboniu 
When I meet 
![image](https://user-images.githubusercontent.com/48349629/220561263-b94f0fc5-d3ad-4c4c-9d7b-8be4a9cd4159.png)
It doesn't work, how to fix this ?
