### ISSUE TITLE
PP-Human v2 自定义目标检测模型不读取类别

### ISSUE THREAD

**Issue by KirigiriSuzumiya** [PaddlePaddle/PaddleDetection#6457]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

- 替换了mot模型地址为自己的ppyoloe模型，可以正常预测但是可视化后的视频检测框中仍然显示pedestrian。

- 另外，在替换配置文件`infer_cfg_pphuman.yml`中的`ID_BASED_DETACTION`模型地址后，报错：(这个报错只出现在我自定义的模型检测到目标时，前置的mot任务似乎正常)
```
Traceback (most recent call last):
  File "C:\Users\boyif\Desktop\paddle\PaddleDetection\deploy\pipeline\pipeline.py", line 1098, in <module>
    main()
  File "C:\Users\boyif\Desktop\paddle\PaddleDetection\deploy\pipeline\pipeline.py", line 1087, in main
    pipeline.run()
  File "C:\Users\boyif\Desktop\paddle\PaddleDetection\deploy\pipeline\pipeline.py", line 175, in run
    self.predictor.run(self.input)
  File "C:\Users\boyif\Desktop\paddle\PaddleDetection\deploy\pipeline\pipeline.py", line 585, in run
    self.predict_video(input)
  File "C:\Users\boyif\Desktop\paddle\PaddleDetection\deploy\pipeline\pipeline.py", line 801, in predict_video
    self.pipeline_res.update(det_action_res, 'det_action')
  File "C:\Users\boyif\Desktop\paddle\PaddleDetection\deploy\pipeline\datacollector.py", line 36, in update
    self.res_dict[name].update(res)
ValueError: dictionary update sequence element #0 has length 0; 2 is required
```

怀疑是没有读取目标检测模型的类别标签导致的两个问题。

### 复现环境 Environment

infer_cfg_pphuman.yml
```
crop_thresh: 0.5
attr_thresh: 0.5
kpt_thresh: 0.2
visual: True
warmup_frame: 50

DET:
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/mot_ppyoloe_l_36e_pipeline.zip
  batch_size: 1

MOT:
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/mot_ppyoloe_l_36e_pipeline.zip
  tracker_config: deploy/pipeline/config/tracker_config.yml
  batch_size: 1
  basemode: "idbased"
  enable: True

KPT:
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/dark_hrnet_w32_256x192.zip
  batch_size: 8

ATTR:
  model_dir:  https://bj.bcebos.com/v1/paddledet/models/pipeline/PPLCNet_x1_0_person_attribute_945_infer.zip
  batch_size: 8
  basemode: "idbased"
  enable: False

VIDEO_ACTION:
  model_dir: https://videotag.bj.bcebos.com/PaddleVideo-release2.3/ppTSM_fight.zip
  batch_size: 1
  frame_len: 8
  sample_freq: 7
  short_size: 340
  target_size: 320
  basemode: "videobased"
  enable: False

SKELETON_ACTION:
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/STGCN.zip
  batch_size: 1
  max_frames: 50
  display_frames: 80
  coord_size: [384, 512]
  basemode: "skeletonbased"
  enable: False

ID_BASED_DETACTION:
  model_dir:  C:\Users\boyif\Desktop\paddle\football\model\7-16
  batch_size: 1
  basemode: "idbased"
  threshold: 0.5
  display_frames: 80
  skip_frame_num: 2
  enable: True

ID_BASED_CLSACTION:
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/PPHGNet_tiny_calling_halfbody.zip
  batch_size: 8
  basemode: "idbased"
  threshold: 0.8
  display_frames: 80
  skip_frame_num: 2
  enable: False

REID:
  model_dir:  https://bj.bcebos.com/v1/paddledet/models/pipeline/reid_model.zip
  batch_size: 16
  basemode: "idbased"
  enable: False
```

### 是否愿意提交PR Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
已复现，会尽快修复。

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/pull/6466

**Comment by KirigiriSuzumiya** [comment]
> #6466

mot追踪的问题修复了

- 但是`ID_BASED_DETACTION`也就是原香烟识别的问题没有解决（检出行为仍显示`smoking`）

- 且替换模型之后所有人的标注框全部都显示`smoking`（这个也有可能是我模型的问题，待确认）

- 还有就是能请问一下替换这个香烟识别的模型是一定要有两类的检测模型吗，使用只有一个类的检测模型会报错。

- 如果是一定要两类的话，空类的标注要框什么内容呢

**Comment by zoooo0820** [comment]
将检测模型的结果转化为行为识别结果的后处理过程请参考[这里](https://github.com/PaddlePaddle/PaddleDetection/blob/develop/deploy/pipeline/pphuman/action_infer.py#L338)，检测模型不限类别，需要根据模型情况，将检测结果对应转为行为识别结果；
此外关于对应行为类型的展示，请对应修改[此处](https://github.com/PaddlePaddle/PaddleDetection/blob/develop/deploy/pipeline/pipeline.py#L1030)

**Comment by KirigiriSuzumiya** [comment]
谢谢，已解决
