### ISSUE TITLE
关键点检测 LiteHRNet-18 联合部署推理报错

### ISSUE THREAD

**Issue by wyyfffff** [PaddlePaddle/PaddleDetection#6488]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

用yolo 和 LiteHRNet-18 联合部署检测视频，刚开始正常预测，预测到700多帧时突然报错，不太理解为什么正常预测到中途会报错，不太清楚原因
```
-----------  Running Arguments -----------
camera_id: -1
cpu_threads: 1
det_model_dir: output_inference/ppyolov2_r50vd_dcn_365e_coco/
det_threshold: 0.5
device: gpu
enable_mkldnn: False
image_dir: None
image_file: None
keypoint_batch_size: 8
keypoint_model_dir: output_inference/lite_hrnet_18_rat_coco/
keypoint_threshold: 0.5
output_dir: output
run_benchmark: False
run_mode: paddle
save_res: False
trt_calib_mode: False
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
use_dark: True
video_file: dataset/rat_temperature.mp4
------------------------------------------
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order: 
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
-----------  Model Configuration -----------
Model Arch: HRNet
Transform Order: 
--transform op: TopDownEvalAffine
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
fps: 30, frame_count: 6760
detect frame: 1
detect frame: 2
detect frame: 3
detect frame: 4
...
detect frame: 707
detect frame: 708
detect frame: 709
detect frame: 710
detect frame: 711
Traceback (most recent call last):
  File "deploy/python/det_keypoint_unite_infer.py", line 270, in <module>
    main()
  File "deploy/python/det_keypoint_unite_infer.py", line 235, in main
    FLAGS.save_res)
  File "deploy/python/det_keypoint_unite_infer.py", line 163, in topdown_unite_predict_video
    FLAGS.run_benchmark)
  File "deploy/python/det_keypoint_unite_infer.py", line 47, in predict_with_given_det
    rec_images, run_benchmark, repeats=10, visual=False)
  File "/home/chenmin/workspace/PaddleDetection/deploy/python/keypoint_infer.py", line 240, in predict_image
    results = self.merge_batch_result(results)
  File "/home/chenmin/workspace/PaddleDetection/deploy/python/infer.py", line 221, in merge_batch_result
    res_key = batch_result[0].keys()
IndexError: list index out of range
```

### 复现环境 Environment

- PaddlePaddle : 2.3.0
- PaddleDetection : release/2.4
- Python : 3.6.13
- CUDA : 11.2.2
- CUDNN : 8.1.0.77

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by zoooo0820** [comment]
你好，参考 [#5552](https://github.com/PaddlePaddle/PaddleDetection/issues/5552)，请先把PaddleDetection代码更新到release-2.4的最新版试下呢，如果仍然报错的话辛苦再反馈一下

**Comment by wyyfffff** [comment]
> 你好，参考 [#5552](https://github.com/PaddlePaddle/PaddleDetection/issues/5552)，请先把PaddleDetection代码更新到release-2.4的最新版试下呢，如果仍然报错的话辛苦再反馈一下

您好，我重新建了一个环境，也重新clone了一下，还是报同样的错误信息

**Comment by zoooo0820** [comment]
能否提供一下测试视频呢，我们复现一下问题

**Comment by wyyfffff** [comment]
> 能否提供一下测试视频呢，我们复现一下问题

请问我要如何把视频传给你呢？可否提供一个邮箱，我通过邮箱传给你

**Comment by wyyfffff** [comment]
> > 能否提供一下测试视频呢，我们复现一下问题
> 
> 请问我要如何把视频传给你呢？可否提供一个邮箱，我通过邮箱传给你

我使用的是自定义的数据集，格式是coco的但是关键点不一样，但是我没用预训练的权重，是自己训练的，不知道是不是这个问题？

**Comment by zoooo0820** [comment]
zoooo0820@qq.com 另外邮箱可能会有附件大小问题，可否给一个百度云盘的分享链接？方便的话最好把修改后的模型一并分享一下，方便复现问题。

**Comment by zoooo0820** [comment]
@wyyfffff 
你好，测试了下给到的视频和模型，问题原因如下：
目前联合部署默认的流程为：检测模型检测“人”-> 切分出目标人物检测框->关键点模型检测关键点；由于给到的测试视频中出现了非”人“的检测框类型，导致这个逻辑报错，这部分逻辑我们会优化一下，以正确抛出错误。

但是对于你的这个场景，直接复用现有代码仍是不够的，需要额外做下面几个工作：
1. 训练一个目标检测网络，以检测该场景下的特殊目标对象
2. 根据目标类别的编号，修改[切分框的代码](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/deploy/python/keypoint_preprocess.py#L231) 。（这里默认是取编号0的类，在coco中是`person`）
3. 由于自定义关键点数据修改了点的定义，请对应修改[可视化程序部分](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/deploy/python/visualize.py#L252)以实现正确的可视化效果

**Comment by wyyfffff** [comment]
> @wyyfffff 你好，测试了下给到的视频和模型，问题原因如下： 目前联合部署默认的流程为：检测模型检测“人”-> 切分出目标人物检测框->关键点模型检测关键点；由于给到的测试视频中出现了非”人“的检测框类型，导致这个逻辑报错，这部分逻辑我们会优化一下，以正确抛出错误。
> 
> 但是对于你的这个场景，直接复用现有代码仍是不够的，需要额外做下面几个工作：
> 
> 1. 训练一个目标检测网络，以检测该场景下的特殊目标对象
> 2. 根据目标类别的编号，修改[切分框的代码](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/deploy/python/keypoint_preprocess.py#L231) 。（这里默认是取编号0的类，在coco中是`person`）
> 3. 由于自定义关键点数据修改了点的定义，请对应修改[可视化程序部分](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/deploy/python/visualize.py#L252)以实现正确的可视化效果

十分感谢！我去改正一下
