### ISSUE TITLE
CUBLAS_STATUS_NOT_INITIALIZED错误

### ISSUE THREAD

**Issue by dbtzy** [PaddlePaddle/PaddleDetection#6496]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

按照PaddleDetection教程安装后出现下面报错。
系统：Win11，paddlepaddle：2.3.0，显卡：MX450，CUDA11.2，cuDNN8.2.1

命令'python ppdet/modeling/tests/test_architectures.py'可以正常运行
命令'python tools/infer.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml -o use_gpu=false weights=https://paddledet.bj.bcebos.com/models/ppyolo_r50vd_dcn_1x_coco.pdparams --infer_img=demo/000000014439.jpg'也可正常运行
但无法在调用GPU的情况下运行，报错如下

PS D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\PaddleDetection> python tools/infer.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml -o use_gpu=true weights=https://paddledet.bj.bcebos.com/models/ppyolo_r50vd_dcn_1x_coco.pdparams --infer_img=demo/000000014439.jpg   
W0722 14:51:59.881991 26776 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.5, Runtime API Version: 11.2
W0722 14:51:59.897964 26776 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
[07/22 14:52:01] ppdet.utils.checkpoint INFO: Finish loading model weights: C:\Users\dbtzy/.cache/paddle/weights\ppyolo_r50vd_dcn_1x_coco.pdparams
[07/22 14:52:01] ppdet.data.source.category WARNING: anno_file 'dataset/coco\annotations/instances_val2017.json' is None or not set or not exist, please recheck TrainDataset/EvalDataset/TestDataset.anno_path, otherwise the default categories will be used by metric_type.      
[07/22 14:52:01] ppdet.data.source.category WARNING: metric_type: COCO, load default categories of COCO.
  0%|                                                                                                              | 0/1 [00:41<?, ?it/s] 
Traceback (most recent call last):
  File "tools/infer.py", line 177, in <module>
    main()
  File "tools/infer.py", line 173, in main
    run(FLAGS, cfg)
  File "tools/infer.py", line 130, in run
    trainer.predict(
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\PaddleDetection\ppdet\engine\trainer.py", line 616, in predict
    outs = self.model(data)
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\PaddleDetection\ppdet\modeling\architectures\meta_arch.py", line 75, in forward
    outs.append(self.get_pred())
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\PaddleDetection\ppdet\modeling\architectures\yolo.py", line 128, in get_pred
    return self._forward()
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\PaddleDetection\ppdet\modeling\architectures\yolo.py", line 79, in _forward 
    body_feats = self.backbone(self.inputs)
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\PaddleDetection\ppdet\modeling\backbones\resnet.py", line 582, in forward   
    x = stage(x)
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\PaddleDetection\ppdet\modeling\backbones\resnet.py", line 423, in forward   
    block_out = block(block_out)
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\PaddleDetection\ppdet\modeling\backbones\resnet.py", line 361, in forward   
    out = self.branch2b(out)
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\PaddleDetection\ppdet\modeling\backbones\resnet.py", line 126, in forward   
    out = self.conv(inputs, offset, mask=mask)
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\venv\lib\site-packages\paddle\vision\ops.py", line 820, in forward
    out = deform_conv2d(
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\venv\lib\site-packages\paddle\vision\ops.py", line 578, in deform_conv2d    
    pre_bias = getattr(_C_ops, op_type)(x, offset, mask, weight, *attrs)
OSError: (External) CUBLAS error(1).
  [Hint: 'CUBLAS_STATUS_NOT_INITIALIZED'.  The cuBLAS library was not initialized. This is usually caused by the lack of a prior cublasCre
ate() call, an error in the CUDA Runtime API called by the cuBLAS routine, or an error in the hardware setup.  To correct: call cublasCrea
te() prior to the function call; and check that the hardware, an appropriate version of the driver, and the cuBLAS library are correctly installed.  ] (at ..\paddle\phi\backends\gpu\gpu_resources.cc:140)
  [operator < deformable_conv > error]

**Comment by zoooo0820** [comment]
辛苦先看下这两点：
1. 执行`paddle.utils.run_check()`能否正常运行出结果
2. 换一个其他的模型试下能否跑通呢，例如`mask_rcnn`

**Comment by dbtzy** [comment]
1. 执行`paddle.utils.run_check()`可以正确执行，输出
W0722 18:03:18.255875 14904 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.5, Runtime API Version: 11.2
W0722 18:03:19.001876 14904 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

2. 换成模型`mask_rcnn`也不能正常运行，但报错不一致，为`Out of memory error on GPU 0. Cannot allocate 765.625000MB memory on GPU 0, 1.999756GB memory has been allocated and available memory is only 0.000000B.`
PS D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\PaddleDetection> python tools/infer.py -c configs/mask_rcnn/mask_rcnn_r50_1x_coco.yml -o use_gpu=true weights=https://paddledet.bj.bcebos.com/models/mask_rcnn_r50_1x_coco.pdparams --infer_img=demo/000000014439.jpg      
W0722 18:11:39.384850 21600 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.5, Runtime API Version: 11.2
W0722 18:11:39.400835 21600 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
[07/22 18:11:39] ppdet.utils.download INFO: Downloading mask_rcnn_r50_1x_coco.pdparams from https://paddledet.bj.bcebos.com/models/mask_rcnn_r50_1x_coco.pdparams
100%|██████████████████████████████████████████████████████████████████████████████████████████| 212245/212245 [00:45<00:00, 4675.60KB/s]
[07/22 18:12:26] ppdet.utils.checkpoint INFO: Finish loading model weights: C:\Users\dbtzy/.cache/paddle/weights\mask_rcnn_r50_1x_coco.pdparams
[07/22 18:12:26] ppdet.data.source.category WARNING: anno_file 'dataset/coco\annotations/instances_val2017.json' is None or not set or not exist, please recheck TrainDataset/EvalDataset/TestDataset.anno_path, otherwise the default categories will be used by metric_type.      
[07/22 18:12:26] ppdet.data.source.category WARNING: metric_type: COCO, load default categories of COCO.
  0%|                                                                                                              | 0/1 [00:13<?, ?it/s] 
Traceback (most recent call last):
  File "tools/infer.py", line 177, in <module>
    main()
  File "tools/infer.py", line 173, in main
    run(FLAGS, cfg)
  File "tools/infer.py", line 130, in run
    trainer.predict(
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\PaddleDetection\ppdet\engine\trainer.py", line 616, in predict
    outs = self.model(data)
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\PaddleDetection\ppdet\modeling\architectures\meta_arch.py", line 75, in forward
    outs.append(self.get_pred())
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\PaddleDetection\ppdet\modeling\architectures\mask_rcnn.py", line 133, in get_pred
    bbox_pred, bbox_num, mask_pred = self._forward()
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\PaddleDetection\ppdet\modeling\architectures\mask_rcnn.py", line 104, in _forward
    preds, feat_func = self.bbox_head(body_feats, rois, rois_num, None)
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\PaddleDetection\ppdet\modeling\heads\bbox_head.py", line 241, in forward    
    rois_feat = self.roi_extractor(body_feats, rois, rois_num)
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\PaddleDetection\ppdet\modeling\heads\roi_extractor.py", line 79, in __call__
    rois_feat = paddle.vision.ops.roi_align(
  File "D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\venv\lib\site-packages\paddle\vision\ops.py", line 1252, in roi_align       
    align_out = _C_ops.roi_align(
SystemError: (Fatal) Operator roi_align raises an struct paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError:

Out of memory error on GPU 0. Cannot allocate 765.625000MB memory on GPU 0, 1.999756GB memory has been allocated and available memory is only 0.000000B.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model.

 (at ..\paddle\fluid\memory\allocation\cuda_allocator.cc:87)
. (at ..\paddle\fluid\imperative\tracer.cc:307)

**Comment by zoooo0820** [comment]
后面这个报错是显存不足导致的，可以尝试下小一些的模型再看看能否正确推理（如`picodet`），也辛苦有结果的话也在这个issue里同步一下。
初步看起来这个问题与环境安装有关，我们尝试看有没有类似环境复现一下是否与`deformable_conv`算子有关。

**Comment by dbtzy** [comment]
使用`picodet`可以得到输出结果，但是请问这是否意味着我以后只能使用类似的小模型进行推理呢

PS D:\CODE_SPACE\Python\DeepLearning_paddlepaddle\PaddleDetection> python tools/infer.py -c configs/picodet/picodet_xs_320_coco_lcnet.yml -o use_gpu=true weights=https://paddledet.bj.bcebos.com/models/picodet_xs_320_coco_lcnet.pdparams --infer_img=demo/000000014439.jpg

W0723 17:50:43.595997 36296 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.5, Runtime API Version: 11.2
W0723 17:50:43.603205 36296 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
[07/23 17:50:44] ppdet.utils.checkpoint INFO: Finish loading model weights: C:\Users\dbtzy/.cache/paddle/weights\picodet_xs_320_coco_lcnet.pdparams
[07/23 17:50:44] ppdet.data.source.category WARNING: anno_file 'dataset/coco\annotations/instances_val2017.json' is None or not set or not exist, please recheck TrainDataset/EvalDataset/TestDataset.anno_path, otherwise the default categories will be used by metric_type.      
[07/23 17:50:44] ppdet.data.source.category WARNING: metric_type: COCO, load default categories of COCO.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.70s/it] 
[07/23 17:50:45] ppdet.engine INFO: Detection bbox results save in output\000000014439.jpg

**Comment by GuitarYourself** [comment]
所以，cublas的报错问题还是没有解决吧? @zoooo0820 @dbtzy
