### ISSUE TITLE
训练时报错，使用Windows平台正常，linuex报错

### ISSUE THREAD

**Issue by hice1207** [PaddlePaddle/PaddleDetection#6503]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Traceback (most recent call last):
  File "tools/train.py", line 177, in <module>
    main()
  File "tools/train.py", line 173, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/home/haokun/h1ce/PaddleDetection-release-2.4/ppdet/engine/trainer.py", line 506, in train
    self._eval_with_loader(self._eval_loader)
  File "/home/haokun/h1ce/PaddleDetection-release-2.4/ppdet/engine/trainer.py", line 533, in _eval_with_loader
    metric.update(data, outs)
  File "/home/haokun/h1ce/PaddleDetection-release-2.4/ppdet/metrics/metrics.py", line 113, in update
    outs, self.clsid2catid, bias=self.bias)
  File "/home/haokun/h1ce/PaddleDetection-release-2.4/ppdet/metrics/coco_utils.py", line 53, in get_infer_results
    outs['bbox'], outs['bbox_num'], im_id, catid, bias=bias)
  File "/home/haokun/h1ce/PaddleDetection-release-2.4/ppdet/metrics/json_results.py", line 30, in get_det_res
    category_id = label_to_cat_id_map[int(num_id)]
KeyError: 1

**Comment by hice1207** [comment]
发现一个问题，刚刚的报错是多GPU情况下，使用单GPU后没有再报错

**Comment by lyuwenyu** [comment]
数据集一致嘛 ， 另外类别改了没  看提示label_to_cat_id_map出错

**Comment by hice1207** [comment]
> 数据集一致嘛 ， 另外类别改了没 看提示label_to_cat_id_map出错

数据集一致，最奇怪的是昨晚成功了...今天一直有这个bug...

**Comment by hice1207** [comment]
> 数据集一致嘛 ， 另外类别改了没 看提示label_to_cat_id_map出错

通过对json_results.py文件中line 30行中的num_id强行赋值为0之后成功得到预测结果，查看代码运行后当num_id == 1时会发生错误，这是预测的种类错误吗？
