### ISSUE TITLE
RuntimeError: ffmpeg process video: test.mp4 error

### ISSUE THREAD

**Issue by zhuangqirong** [PaddlePaddle/PaddleDetection#6519]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

[07/26 19:18:47] ppdet.utils.checkpoint INFO: Finish resuming model weights: weights/fairmot_dla34_30e_1088x608.pdparams
'ffmpeg' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
Traceback (most recent call last):
  File "D:/zhaohang/GitHub/PaddleDetection-release-2.4/infer_mot.py", line 157, in <module>
    main()
  File "D:/zhaohang/GitHub/PaddleDetection-release-2.4/infer_mot.py", line 153, in main
    run(FLAGS, cfg)
  File "D:/zhaohang/GitHub/PaddleDetection-release-2.4/infer_mot.py", line 107, in run
    tracker.mot_predict_seq(
  File "D:\zhaohang\GitHub\PaddleDetection-release-2.4\ppdet\engine\tracker.py", line 518, in mot_predict_seq
    self.dataset.set_video(video_file, frame_rate)
  File "D:\zhaohang\GitHub\PaddleDetection-release-2.4\ppdet\data\source\mot.py", line 574, in set_video
    self.roidbs = self._load_video_images()
  File "D:\zhaohang\GitHub\PaddleDetection-release-2.4\ppdet\data\source\mot.py", line 506, in _load_video_images
    frames_path = video2frames(self.video_file, output_path,
  File "D:\zhaohang\GitHub\PaddleDetection-release-2.4\ppdet\data\source\mot.py", line 607, in video2frames
    raise RuntimeError('ffmpeg process video: {} error'.format(video_path))
RuntimeError: ffmpeg process video: test.mp4 error

**Comment by nemonameless** [comment]
请检查一下test.mp4路径是否真实存在，ffmpeg是否安装成功，以及视频能否单独被ffmpeg命令抽帧，如以下命令
```
ffmpeg -i test.mp4 -f image2 -vf fps=20 -qscale:v 2  %06d.jpg
```

**Comment by zhuangqirong** [comment]
> 请检查一下test.mp4路径是否真实存在，ffmpeg是否安装成功，以及视频能否单独被ffmpeg命令抽帧，如以下命令
> 
> ```
> ffmpeg -i test.mp4 -f image2 -vf fps=20 -qscale:v 2  %06d.jpg
> ```

谢谢您的回复，我windows的，直接Pip install ffmpeg，不能使用，需要按照这个方法(https://blog.csdn.net/zymill/article/details/110500944)正确安装ffmpeg

**Comment by xiatian114** [comment]
> > 请检查一下test.mp4路径是否真实存在，ffmpeg是否安装成功，以及视频能否单独被ffmpeg命令抽帧，如以下命令
> > ```
> > ffmpeg -i test.mp4 -f image2 -vf fps=20 -qscale:v 2  %06d.jpg
> > ```
> 
> 谢谢您的回复，我windows的，直接Pip install ffmpeg，不能使用，需要按照这个方法([https://blog.csdn.net/zymill/article/details/110500944)正确安装ffmpeg](https://blog.csdn.net/zymill/article/details/110500944)%E6%AD%A3%E7%A1%AE%E5%AE%89%E8%A3%85ffmpeg)

我跟着你这方法做了一遍，还是有错

**Comment by xiatian114** [comment]
> > 请检查一下test.mp4路径是否真实存在，ffmpeg是否安装成功，以及视频能否单独被ffmpeg命令抽帧，如以下命令
> > ```
> > ffmpeg -i test.mp4 -f image2 -vf fps=20 -qscale:v 2  %06d.jpg
> > ```
> 
> 谢谢您的回复，我windows的，直接Pip install ffmpeg，不能使用，需要按照这个方法([https://blog.csdn.net/zymill/article/details/110500944)正确安装ffmpeg](https://blog.csdn.net/zymill/article/details/110500944)%E6%AD%A3%E7%A1%AE%E5%AE%89%E8%A3%85ffmpeg)

(PaddleDete) D:\PaddleDete>python tools/infer_mot.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml -o weights=output/fairmot_dla34_30e_1088x608.pdparams --video_file=./work/来客分
析/来客分析1.mp4  --save_videos
W0124 08:30:02.492044 16824 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.6, Runtime API Version: 11.6
W0124 08:30:02.496031 16824 gpu_resources.cc:91] device: 0, cuDNN Version: 8.6.
[01/24 08:30:04] ppdet.utils.checkpoint INFO: Finish resuming model weights: output/fairmot_dla34_30e_1088x608.pdparams
'ffmpeg' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Traceback (most recent call last):
  File "tools/infer_mot.py", line 146, in <module>
    main()
  File "tools/infer_mot.py", line 142, in main
    run(FLAGS, cfg)
  File "tools/infer_mot.py", line 99, in run
    tracker.mot_predict_seq(
  File "D:\PaddleDete\ppdet\engine\tracker.py", line 547, in mot_predict_seq
    self.dataset.set_video(video_file, frame_rate)
  File "D:\PaddleDete\ppdet\data\source\mot.py", line 579, in set_video
    self.roidbs = self._load_video_images()
  File "D:\PaddleDete\ppdet\data\source\mot.py", line 511, in _load_video_images
    frames_path = video2frames(self.video_file, output_path,
  File "D:\PaddleDete\ppdet\data\source\mot.py", line 613, in video2frames
    raise RuntimeError('ffmpeg process video: {} error'.format(video_path))
RuntimeError: ffmpeg process video: ./work/来客分析/来客分析1.mp4 error

**Comment by xiatian114** [comment]
> > > 请检查一下test.mp4路径是否真实存在，ffmpeg是否安装成功，以及视频能否单独被ffmpeg命令抽帧，如以下命令
> > > ```
> > > ffmpeg -i test.mp4 -f image2 -vf fps=20 -qscale:v 2  %06d.jpg
> > > ```
> > 
> > 
> > 谢谢您的回复，我windows的，直接Pip install ffmpeg，不能使用，需要按照这个方法([https://blog.csdn.net/zymill/article/details/110500944)正确安装ffmpeg](https://blog.csdn.net/zymill/article/details/110500944)%E6%AD%A3%E7%A1%AE%E5%AE%89%E8%A3%85ffmpeg)
> 
> 我跟着你这方法做了一遍，还是有错

没有变化
