### ISSUE TITLE
onnx ShapeInferenceError when using onnxsim

### ISSUE THREAD

**Issue by MoonBunnyZZZ** [PaddlePaddle/PaddleDetection#6527]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

1、paddle2onnx导出ppyoloe模型的onnx文件
2、使用onnxsim优化前述onnx模型，报错onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:Gather, node name: Gather_12): [ShapeInferenceError] Inferred shape and existing shape differ in dimension 0: (1) vs (-1)
3、使用paddle2onnx.optimize制定input shape，无效

```shell
 onnxsim ppyoloe_crn_l_300e_coco.onnx ppyoloe_crn_l_300e_coco_sim.onnx                                                                                      
Simplifying...                                                                                                                                                
Traceback (most recent call last):                                                                                                                            
  File "/home/wx/miniconda3/envs/pd/bin/onnxsim", line 8, in <module>                                                                                         
    sys.exit(main())                                                                                                                                          
  File "/home/wx/miniconda3/envs/pd/lib/python3.7/site-packages/onnxsim/onnx_simplifier.py", line 444, in main                                                
    args.tensor_size_threshold,                                                                                                                               
  File "/home/wx/miniconda3/envs/pd/lib/python3.7/site-packages/onnxsim/onnx_simplifier.py", line 189, in simplify                                            
    tensor_size_threshold,                                                                                                                                    
onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:Gather, node name: Gather_12): [ShapeInferenceError] Inferred shape and
 existing shape differ in dimension 0: (1) vs (-1)
```

### 复现环境 Environment

- PaddlePaddle 2.3.1
- PaddleDet 2.4.0
- Paddle2ONNX 0.9.8

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
看这个报错是不支持动态batch嘛  可以试一下固定batch导出，或者在onnxslim提个issue

**Comment by MoonBunnyZZZ** [comment]
> 看这个报错是不支持动态batch嘛 可以试一下固定batch导出，或者在onnxslim提个issue

好的谢谢
