### ISSUE TITLE
使用DETR和DeformableDETR训练自己的数据集时，无法打印GFLOPS，在runtime.yml文件里设置print_flops: true，会报错误

### ISSUE THREAD

**Issue by mingheyuemankong** [PaddlePaddle/PaddleDetection#6532]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用DETR和DeformableDETR训练自己的数据集，在验证过程中，无法打印GFLOPS，在runtime.yml文件里设置print_flops: true，会报下面的错误。
[07-27 21:08:49 MainThread @logger.py:242] Argv: tools/eval.py -c configs/detr/detr_r50_1x_coco.yml -o weights=output/detr_r50_1x_coco/model_final
[07-27 21:08:49 MainThread @utils.py:79] WRN paddlepaddle version: 2.3.1. The dynamic graph version of PARL is under development, not fully tested and supported
<class 'ppdet.modeling.architectures.detr.DETR'>
Traceback (most recent call last):
  File "tools/eval.py", line 153, in <module>
    main()
  File "tools/eval.py", line 149, in main
    run(FLAGS, cfg)
  File "tools/eval.py", line 107, in run
    trainer.evaluate()
  File "/home/aistudio/PaddleDetection-release-2.4/ppdet/engine/trainer.py", line 578, in evaluate
    self._eval_with_loader(self.loader)
  File "/home/aistudio/PaddleDetection-release-2.4/ppdet/engine/trainer.py", line 547, in _eval_with_loader
    self._flops(flops_loader)
  File "/home/aistudio/PaddleDetection-release-2.4/ppdet/engine/trainer.py", line 855, in _flops
    flops = flops(self.model, input_spec) / (1000**3)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/analysis/flops.py", line 133, in dygraph_flops
    program = dygraph2program(model, inputs)
  File "<decorator-gen-442>", line 2, in dygraph2program
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 434, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/core/dygraph.py", line 162, in dygraph2program
    original_outputs = layer(*inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleDetection-release-2.4/ppdet/modeling/architectures/meta_arch.py", line 75, in forward
    outs.append(self.get_pred())
  File "/home/aistudio/PaddleDetection-release-2.4/ppdet/modeling/architectures/detr.py", line 88, in get_pred
    bbox_pred, bbox_num = self._forward()
  File "/home/aistudio/PaddleDetection-release-2.4/ppdet/modeling/architectures/detr.py", line 68, in _forward
    out_transformer = self.transformer(body_feats, self.inputs['pad_mask'])
KeyError: 'pad_mask'

**Comment by lyuwenyu** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/ppdet/modeling/architectures/detr.py#L68  这行改成下面试一下 
```
        # Transformer
        src_mask = self.inputs['pad_mask'] if 'pad_mask' in self.inputs else None
        out_transformer = self.transformer(body_feats, src_mask)
```

**Comment by mingheyuemankong** [comment]
谢谢回答，该问题已解决
