### ISSUE TITLE
目标跟踪报错：cudaErrorLaunchFailure （719）

### ISSUE THREAD

**Issue by XuLei0** [PaddlePaddle/PaddleDetection#6535]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

预测所有的 目标跟踪 模型都会报：
OSError: (External) CUDA error(719), unspecified launch failure.
  [Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bound
s shared memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent
 state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at ..\paddle\phi\backends\gpu\gpu_context.cc:435)
  [operator < multiclass_nms3 > error]

**Comment by nemonameless** [comment]
请先检查paddle版本是否安装正确，先试试检测模型如ppyoloe的预测命令能否运行顺利。

**Comment by XuLei0** [comment]
ppyoloe、行人检测、车辆检测都可以运行，目标跟踪GPU就是不行，报上面的错，但是cpu可以运行




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月28日(星期四) 下午5:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] 目标跟踪报错：cudaErrorLaunchFailure （719） (Issue #6535)





 
请先检查paddle版本是否安装正确，先试试检测模型如ppyoloe的预测命令能否运行顺利。

**Comment by XuLei0** [comment]
运行命令： CUDA_VISIBLE_DEVICES=0 python tools/infer_mot.py -c configs/mot/jde/jde_darknet53_30e_1088x608.yml -o weights=https://paddledet.bj.bcebos.com/models/mot/jde_darknet53_30e_1088x608.pdparams --video_file=E:/PaddleDetection/dataset/my_test_data/videos/MOT16_small.mp4&nbsp; --save_videos


W0728 21:37:06.386767 18188 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.6
W0728 21:37:06.401937 18188 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
[07/28 21:37:08] ppdet.utils.checkpoint INFO: Finish resuming model weights: C:\Users\xulei/.cache/paddle/weights\jde_darknet53_30e_1088x608.pdparams
[07/28 21:37:08] ppdet.data.source.mot INFO: Length of the video: 160 frames.
[07/28 21:37:08] ppdet.engine.tracker INFO: Starting tracking video E:/PaddleDetection/dataset/my_test_data/videos/MOT16_small.mp4
&nbsp; 0%|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; | 0/160 [00:02<?, ?it/s]
Traceback (most recent call last):
&nbsp; File "tools/infer_mot.py", line 150, in <module&gt;
&nbsp; &nbsp; main()
&nbsp; File "tools/infer_mot.py", line 146, in main
&nbsp; &nbsp; run(FLAGS, cfg)
&nbsp; File "tools/infer_mot.py", line 100, in run
&nbsp; &nbsp; tracker.mot_predict_seq(
&nbsp; File "E:\PaddleDetection\ppdet\engine\tracker.py", line 544, in mot_predict_seq
&nbsp; &nbsp; results, nf, ta, tc = self._eval_seq_jde(
&nbsp; File "E:\PaddleDetection\ppdet\engine\tracker.py", line 147, in _eval_seq_jde
&nbsp; &nbsp; pred_dets, pred_embs = self.model(data)
&nbsp; File "D:\Miniconda\envs\Paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
&nbsp; &nbsp; return self._dygraph_call_func(*inputs, **kwargs)
&nbsp; File "D:\Miniconda\envs\Paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
&nbsp; &nbsp; outputs = self.forward(*inputs, **kwargs)
&nbsp; File "E:\PaddleDetection\ppdet\modeling\architectures\meta_arch.py", line 75, in forward
&nbsp; &nbsp; outs.append(self.get_pred())
&nbsp; File "E:\PaddleDetection\ppdet\modeling\architectures\jde.py", line 110, in get_pred
&nbsp; &nbsp; return self._forward()
&nbsp; File "E:\PaddleDetection\ppdet\modeling\architectures\jde.py", line 68, in _forward
&nbsp; &nbsp; det_outs = self.detector(self.inputs)
&nbsp; File "D:\Miniconda\envs\Paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
&nbsp; &nbsp; return self._dygraph_call_func(*inputs, **kwargs)
&nbsp; File "D:\Miniconda\envs\Paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
&nbsp; &nbsp; outputs = self.forward(*inputs, **kwargs)
&nbsp; File "E:\PaddleDetection\ppdet\modeling\architectures\meta_arch.py", line 75, in forward
&nbsp; &nbsp; outs.append(self.get_pred())
&nbsp; File "E:\PaddleDetection\ppdet\modeling\architectures\yolo.py", line 128, in get_pred
&nbsp; &nbsp; return self._forward()
&nbsp; File "E:\PaddleDetection\ppdet\modeling\architectures\yolo.py", line 99, in _forward
&nbsp; &nbsp; boxes_idx, bbox, bbox_num, nms_keep_idx = self.post_process(
&nbsp; File "D:\Miniconda\envs\Paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
&nbsp; &nbsp; return self._dygraph_call_func(*inputs, **kwargs)
&nbsp; File "D:\Miniconda\envs\Paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
&nbsp; &nbsp; outputs = self.forward(*inputs, **kwargs)
&nbsp; File "E:\PaddleDetection\ppdet\modeling\post_process.py", line 459, in forward
&nbsp; &nbsp; bbox_pred, bbox_num, nms_keep_idx = self.nms(
&nbsp; File "E:\PaddleDetection\ppdet\modeling\layers.py", line 488, in __call__
&nbsp; &nbsp; return ops.multiclass_nms(bboxes, score, **kwargs)
&nbsp; File "E:\PaddleDetection\ppdet\modeling\ops.py", line 725, in multiclass_nms
&nbsp; &nbsp; helper.append_op(
&nbsp; File "D:\Miniconda\envs\Paddle\lib\site-packages\paddle\fluid\layer_helper.py", line 44, in append_op
&nbsp; &nbsp; return self.main_program.current_block().append_op(*args, **kwargs)
&nbsp; File "D:\Miniconda\envs\Paddle\lib\site-packages\paddle\fluid\framework.py", line 3599, in append_op
&nbsp; &nbsp; _dygraph_tracer().trace_op(type,
&nbsp; File "D:\Miniconda\envs\Paddle\lib\site-packages\paddle\fluid\dygraph\tracer.py", line 307, in trace_op
&nbsp; &nbsp; self.trace(type, inputs, outputs, attrs,
OSError: (External) CUDA error(719), unspecified launch failure.
&nbsp; [Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bound
s shared memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent
&nbsp;state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at ..\paddle\phi\backends\gpu\gpu_context.cc:435)
&nbsp; [operator < multiclass_nms3 &gt; error]







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月28日(星期四) 下午5:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleDetection] 目标跟踪报错：cudaErrorLaunchFailure （719） (Issue #6535)





 
请先检查paddle版本是否安装正确，先试试检测模型如ppyoloe的预测命令能否运行顺利。
