### ISSUE TITLE
训练的时候报 error: (-5:Bad argument) in function 'resize'  应该是某张图片太小导致

### ISSUE THREAD

**Issue by gg22mm** [PaddlePaddle/PaddleDetection#6537]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

训练的时候报 error: (-5:Bad argument) in function 'resize'  应该是某张图片太小导致
图片是：60 * 80 的，不知道是不是这个原因

07/28 17:52:35] ppdet.engine INFO: Epoch: [0] [1680/3659] learning_rate: 0.001000 loss_xy: 1.808574 loss_wh: 0.511621 loss_obj: 2.223001 loss_cls: 0.019930 loss: 4.701416 eta: 510 days, 19:01:52 batch_cost: 9.8036 data_cost: 9.1857 ips: 0.8160 images/s
[07/28 17:55:39] reader WARNING: fail to map batch transform [BatchRandomResize_428ae5] with error: OpenCV(4.6.0) :-1: error: (-5:Bad argument) in function 'resize'
> Overload resolution failed:
>  - Conversion error: src
>  - Expected Ptr<cv::UMat> for argument 'src'
 and stack:
Traceback (most recent call last):
  File "D:\dzkj\PaddleDetection\ppdet\data\reader.py", line 73, in __call__
    data = f(data)
  File "D:\dzkj\PaddleDetection\ppdet\data\transform\batch_operators.py", line 172, in __call__
    return resizer(samples, context=context)
  File "D:\dzkj\PaddleDetection\ppdet\data\transform\operators.py", line 103, in __call__
    sample[i] = self.apply(sample[i], context)
  File "D:\dzkj\PaddleDetection\ppdet\data\transform\operators.py", line 826, in apply
    im = self.apply_image(sample['image'], [im_scale_x, im_scale_y])
  File "D:\dzkj\PaddleDetection\ppdet\data\transform\operators.py", line 744, in apply_image
    interpolation=self.interp)
cv2.error: OpenCV(4.6.0) :-1: error: (-5:Bad argument) in function 'resize'
> Overload resolution failed:
>  - Conversion error: src
>  - Expected Ptr<cv::UMat> for argument 'src'

Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\paddleGpu\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\paddleGpu\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\paddleGpu\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 218, in _thread_loop
    self._thread_done_event)
  File "C:\ProgramData\Anaconda3\envs\paddleGpu\lib\site-packages\paddle\fluid\dataloader\fetcher.py", line 134, in fetch
    data = self.collate_fn(data)
  File "D:\dzkj\PaddleDetection\ppdet\data\reader.py", line 79, in __call__
    raise e
  File "D:\dzkj\PaddleDetection\ppdet\data\reader.py", line 73, in __call__
    data = f(data)
  File "D:\dzkj\PaddleDetection\ppdet\data\transform\batch_operators.py", line 172, in __call__
    return resizer(samples, context=context)
  File "D:\dzkj\PaddleDetection\ppdet\data\transform\operators.py", line 103, in __call__
    sample[i] = self.apply(sample[i], context)
  File "D:\dzkj\PaddleDetection\ppdet\data\transform\operators.py", line 826, in apply
    im = self.apply_image(sample['image'], [im_scale_x, im_scale_y])
  File "D:\dzkj\PaddleDetection\ppdet\data\transform\operators.py", line 744, in apply_image
    interpolation=self.interp)
cv2.error: OpenCV(4.6.0) :-1: error: (-5:Bad argument) in function 'resize'
> Overload resolution failed:
>  - Conversion error: src
>  - Expected Ptr<cv::UMat> for argument 'src'

### 复现环境 Environment

platform: Windows-10-10.0.17763-SP0
Python: 3.7.13 (default, Mar 28 2022, 08:03:21) [MSC v.1916 64 bit (AMD64)]
Paddle compiled with cuda: True
GPU: ['GPU 0: Tesla K80', 'GPU 1: Tesla K80']
PaddleSeg: 2.6.0
PaddlePaddle: 2.3.1
OpenCV: 4.4.0

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
opencv版本换下试试，降低点比如4.2

**Comment by gg22mm** [comment]
现在没有这个问题了，不知道之前是怎么回事

**Comment by Ssakura-go** [comment]
> opencv版本换下试试，降低点比如4.2

谢谢~问题解决了(#^.^#)
