### ISSUE TITLE
训练中断报错

### ISSUE THREAD

**Issue by zhuoxun-xun** [PaddlePaddle/PaddleDetection#6550]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

你好，在训练模型的途中，突然就中断了。是因为显卡的memory不够吗？那要怎么解决呢？
以下是报错信息：
Traceback (most recent call last):
  File "tools/train.py", line 172, in <module>
    main()
  File "tools/train.py", line 168, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 132, in run
    trainer.train(FLAGS.eval)
  File "/home/paddle_develop/ppdet/engine/trainer.py", line 489, in train
    outputs = model(data)
  File "/home/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/paddle_develop/ppdet/modeling/architectures/meta_arch.py", line 59, in forward
    out = self.get_loss()
  File "/home/paddle_develop/ppdet/modeling/architectures/yolo.py", line 124, in get_loss
    return self._forward()
  File "/home/paddle_develop/ppdet/modeling/architectures/yolo.py", line 88, in _forward
    yolo_losses = self.yolo_head(neck_feats, self.inputs)
  File "/home/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/paddle_develop/ppdet/modeling/heads/ppyoloe_head.py", line 216, in forward
    return self.forward_train(feats, targets)
  File "/home/paddle_develop/ppdet/modeling/heads/ppyoloe_head.py", line 158, in forward_train
    return self.get_loss([
  File "/home/paddle_develop/ppdet/modeling/heads/ppyoloe_head.py", line 352, in get_loss
    self._bbox_loss(pred_distri, pred_bboxes, anchor_points_s,
  File "/home/paddle_develop/ppdet/modeling/heads/ppyoloe_head.py", line 284, in _bbox_loss
    pred_dist_pos = paddle.masked_select(
  File "/home/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/tensor/search.py", line 665, in masked_select
    return _C_ops.masked_select(x, mask)
SystemError: (Fatal) Operator masked_select raises an thrust::system::detail::bad_alloc exception.
The exception content is
:std::bad_alloc: cudaErrorMemoryAllocation: out of memory. (at /paddle/paddle/fluid/imperative/tracer.cc:221)

### 复现环境 Environment

-PaddlePaddle: 2.2.2
-PAddleDetection: develop
-Python: 3.8
-CUDA: 11.2
-CUDNN: 8.1

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by ghostxsl** [comment]
看错误信息是显存溢出了，建议调小batch size

**Comment by cheesezoella** [comment]
好的，谢谢！！

**Comment by zhuoxun-xun** [comment]
我的显卡是RTX 3080 Ti 12GB。请问你有什么建议的配置来训练吗？谢谢

**Comment by ghostxsl** [comment]
请问你运行的命令是什么？

**Comment by zhuoxun-xun** [comment]
我的运行命令是 python -m paddle.distributed.launch --gpus 0 tools/train.py -c configs/pphuman/ppyoloe_crn_s_80e_smoking_visdrone.yml --eval
我大概有1万多张照片。

**Comment by ghostxsl** [comment]
如果你是跑单卡的话，可以不用调分布式的module，可以运行：python tools/train.py -c configs/pphuman/ppyoloe_crn_s_80e_smoking_visdrone.yml --eval -o TrainReader.batch_size=8
把bs调小一点再试试呢

**Comment by zhuoxun-xun** [comment]
好的，谢谢！我会试一试。 ：）
