### ISSUE TITLE
检测等任务可行，但是目标跟踪会有报错

### ISSUE THREAD

**Issue by jklkid** [PaddlePaddle/PaddleDetection#6584]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

复现环境：
win10系统
cuda 11.6
cudnn 8.4
python 3.9
paddlepaddle-gpu==2.3.1.post116 windows版本

检测任务都可以正常训练与推理，但是跟踪任务在训练和推理时都会报错。
以fairmot模型为例，按照官方流程进行MOT16的训练推理：
训练时会报错：ValueError: Target xxx(数值不定) is out of lower bound.
直接下载官方提供权重文件进行推理会报错：OSError: (External) CUDA error(719), unspecified launch failure.

**Comment by nemonameless** [comment]
请提供更多截图报错信息，可以看到哪一行报错的那种，训练和推理分别报什么错。

**Comment by jklkid** [comment]
> 请提供更多截图报错信息，可以看到哪一行报错的那种，训练和推理分别报什么错。
训练报错：
Traceback (most recent call last):
  File "D:\Project_pptracking\PaddleDetection-release-2.4\tools\train.py", line 177, in <module>
    main()
  File "D:\Project_pptracking\PaddleDetection-release-2.4\tools\train.py", line 173, in main
    run(FLAGS, cfg)
  File "D:\Project_pptracking\PaddleDetection-release-2.4\tools\train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\engine\trainer.py", line 454, in train
    outputs = model(data)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\architectures\meta_arch.py", line 59, in forward
    out = self.get_loss()
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\architectures\fairmot.py", line 99, in get_loss
    loss = self._forward()
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\architectures\fairmot.py", line 78, in _forward
    reid_loss = self.reid(neck_feat, self.inputs)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\reid\fairmot_embedding_head.py", line 115, in forward
    loss = self.get_loss(reid_feat, inputs)
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\reid\fairmot_embedding_head.py", line 163, in get_loss
    loss = self.reid_loss(logit, target)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\nn\layer\loss.py", line 397, in forward
    ret = paddle.nn.functional.cross_entropy(
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\nn\functional\loss.py", line 1722, in cross_entropy
    raise ValueError("Target {} is out of upper bound.".format(
ValueError: Target 4578971296541297966 is out of upper bound.
推理报错：
Traceback (most recent call last):
  File "D:\Project_pptracking\PaddleDetection-release-2.4\tools\infer_mot.py", line 149, in <module>
    main()
  File "D:\Project_pptracking\PaddleDetection-release-2.4\tools\infer_mot.py", line 145, in main
    run(FLAGS, cfg)
  File "D:\Project_pptracking\PaddleDetection-release-2.4\tools\infer_mot.py", line 99, in run
    tracker.mot_predict_seq(
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\engine\tracker.py", line 544, in mot_predict_seq
    results, nf, ta, tc = self._eval_seq_jde(
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\engine\tracker.py", line 147, in _eval_seq_jde
    pred_dets, pred_embs = self.model(data)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\architectures\meta_arch.py", line 75, in forward
    outs.append(self.get_pred())
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\architectures\fairmot.py", line 95, in get_pred
    output = self._forward()
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\architectures\fairmot.py", line 75, in _forward
    det_outs = self.detector(self.inputs)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\architectures\meta_arch.py", line 75, in forward
    outs.append(self.get_pred())
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\architectures\centernet.py", line 82, in get_pred
    bbox, bbox_inds, topk_clses = self.post_process(
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\post_process.py", line 507, in __call__
    scores, inds, topk_clses, ys, xs = self._topk(heat)
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\layers.py", line 836, in _topk
    topk_xs = topk_inds % width
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\math_op_patch.py", line 299, in __impl__
    return math_op(self, other_var, 'axis', axis)
OSError: (External) CUDA error(719), unspecified launch failure.
  [Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at ..\paddle\phi\backends\gpu\gpu_context.cc:435)
  [operator < elementwise_mod > error]

**Comment by jklkid** [comment]
> 请提供更多截图报错信息，可以看到哪一行报错的那种，训练和推理分别报什么错。

训练报错：
Traceback (most recent call last):
  File "D:\Project_pptracking\PaddleDetection-release-2.4\tools\train.py", line 177, in <module>
    main()
  File "D:\Project_pptracking\PaddleDetection-release-2.4\tools\train.py", line 173, in main
    run(FLAGS, cfg)
  File "D:\Project_pptracking\PaddleDetection-release-2.4\tools\train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\engine\trainer.py", line 454, in train
    outputs = model(data)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\architectures\meta_arch.py", line 59, in forward
    out = self.get_loss()
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\architectures\fairmot.py", line 99, in get_loss
    loss = self._forward()
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\architectures\fairmot.py", line 78, in _forward
    reid_loss = self.reid(neck_feat, self.inputs)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\reid\fairmot_embedding_head.py", line 115, in forward
    loss = self.get_loss(reid_feat, inputs)
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\reid\fairmot_embedding_head.py", line 163, in get_loss
    loss = self.reid_loss(logit, target)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\nn\layer\loss.py", line 397, in forward
    ret = paddle.nn.functional.cross_entropy(
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\nn\functional\loss.py", line 1722, in cross_entropy
    raise ValueError("Target {} is out of upper bound.".format(
ValueError: Target 4578971296541297966 is out of upper bound.
推理报错：
Traceback (most recent call last):
  File "D:\Project_pptracking\PaddleDetection-release-2.4\tools\infer_mot.py", line 149, in <module>
    main()
  File "D:\Project_pptracking\PaddleDetection-release-2.4\tools\infer_mot.py", line 145, in main
    run(FLAGS, cfg)
  File "D:\Project_pptracking\PaddleDetection-release-2.4\tools\infer_mot.py", line 99, in run
    tracker.mot_predict_seq(
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\engine\tracker.py", line 544, in mot_predict_seq
    results, nf, ta, tc = self._eval_seq_jde(
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\engine\tracker.py", line 147, in _eval_seq_jde
    pred_dets, pred_embs = self.model(data)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\architectures\meta_arch.py", line 75, in forward
    outs.append(self.get_pred())
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\architectures\fairmot.py", line 95, in get_pred
    output = self._forward()
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\architectures\fairmot.py", line 75, in _forward
    det_outs = self.detector(self.inputs)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\architectures\meta_arch.py", line 75, in forward
    outs.append(self.get_pred())
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\architectures\centernet.py", line 82, in get_pred
    bbox, bbox_inds, topk_clses = self.post_process(
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\post_process.py", line 507, in __call__
    scores, inds, topk_clses, ys, xs = self._topk(heat)
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\layers.py", line 836, in _topk
    topk_xs = topk_inds % width
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\math_op_patch.py", line 299, in __impl__
    return math_op(self, other_var, 'axis', axis)
OSError: (External) CUDA error(719), unspecified launch failure.
  [Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at ..\paddle\phi\backends\gpu\gpu_context.cc:435)
  [operator < elementwise_mod > error]

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/search?q=out+of+bound&type=issues
win上请暂时安装paddle 2.2.2版本
