### ISSUE TITLE
KeyError: 'target0' 

### ISSUE THREAD

**Issue by czczmr** [PaddlePaddle/PaddleDetection#6601]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

!export CUDA_VISIBLE_DEVICES=0 #windows和Mac下不需要执行该命令
%cd /home/aistudio/work/PaddleDetection
!python3.7 tools/post_quant.py -c configs/yolov3/yolov3_darknet53_270e_voc.yml --slim_config configs/slim/quant/yolov3_darknet_qat.yml
模型是按照官网教程训练的，离线量化不持支，结果在线量化也报错。
![image](https://user-images.githubusercontent.com/75561356/183326370-bcf4e975-925c-4753-9dd3-69df59a4fd6f.png)

**Comment by ghostxsl** [comment]
yolov3模型离线量化是已知问题，我们技术人员正在修复，建议使用ppyolo_mbv3_large_coco试一下

**Comment by czczmr** [comment]
这个是在线量化的报错，好像是target标注没传进去，但是我训练测试都很正常啊，为什么我量化报这个错误。
您的意思是模型最好用你们示例中的，数据集最好用coco?

**Comment by ghostxsl** [comment]
在线量化我这边本地复现没问题，你可以检查一下你的数据格式是否有误

**Comment by czczmr** [comment]
![image](https://user-images.githubusercontent.com/75561356/183330444-d02b2f3c-46b4-4aa6-933e-b08445429770.png)
我发现训练时候有几个无效的标注，我把这几个样本删除一下。
数据格式应该没问题，和标准的voc数据集一样。

**Comment by czczmr** [comment]
没有效果，你用的是voc的数据集吗

**Comment by czczmr** [comment]
#3350和这个问题类似，但是也没解决

**Comment by czczmr** [comment]
Traceback (most recent call last):
  File "tools/post_quant.py", line 96, in <module>
    main()
  File "tools/post_quant.py", line 92, in main
    run(FLAGS, cfg)
  File "tools/post_quant.py", line 72, in run
    trainer.post_quant(FLAGS.output_dir)
  File "/home/aistudio/work/PaddleDetection/ppdet/engine/trainer.py", line 803, in post_quant
    self.model(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 59, in forward
    out = self.get_loss()
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 125, in get_loss
    return self._forward()
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 88, in _forward
    yolo_losses = self.yolo_head(neck_feats, self.inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/heads/yolo_head.py", line 121, in forward
    return self.loss(yolo_outputs, targets, self.anchors)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/quant/quant_layers.py", line 678, in forward
    out = self._layer(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/losses/yolo_loss.py", line 187, in forward
    gt_targets = [targets['target{}'.format(i)] for i in range(np)]
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/losses/yolo_loss.py", line 187, in <listcomp>
    gt_targets = [targets['target{}'.format(i)] for i in range(np)]
KeyError: 'target0'
