### ISSUE TITLE
deploy/python/infer.py

### ISSUE THREAD

**Issue by lling-2021** [PaddlePaddle/PaddleDetection#6617]
python deploy/python/infer.py 出现下列错误
Traceback (most recent call last):
  File "deploy/python/infer.py", line 909, in <module>
    main()
  File "deploy/python/infer.py", line 856, in main
    detector = eval(detector_func)(
  File "deploy/python/infer.py", line 120, in __init__
    self.predictor, self.config = load_predictor(
  File "deploy/python/infer.py", line 770, in load_predictor
    predictor = create_predictor(config)
ValueError: (InvalidArgument) The inverse of Fused batch norm variance should be finite. Found nonfinite values! Please check batch_norm2d_0.w_2
  [Hint: Expected std::isfinite(variance_array[i]) == true, but received std::isfinite(variance_array[i]):0 != true:1.] (at /paddle/paddle/fluid/framework/ir/conv_bn_fuse_pass.cc:105)

**Comment by jerrywgz** [comment]
请提供下模型导出命令，deploy infer的启动命令已经依赖的paddle版本

**Comment by lling-2021** [comment]
> 

python tools/export_model.py -c configs/yolov3/yolov3_mobilenet_v1 -o weights=outout/
用的paddlepaddle-gpu   2.3.1
