### ISSUE TITLE
Target 4578971296541297966 is out of upper bound错误

### ISSUE THREAD

**Issue by jklkid** [PaddlePaddle/PaddleDetection#6619]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

复现环境：
win10系统
cuda 11.6
cudnn 8.4
python 3.9
paddlepaddle-gpu==2.3.1.post116 windows版本
按照教程进行fairmot目标跟踪训练，发生如下报错：
Traceback (most recent call last):
  File "D:\Project_pptracking\PaddleDetection-release-2.4\tools\train.py", line 177, in <module>
    main()
  File "D:\Project_pptracking\PaddleDetection-release-2.4\tools\train.py", line 173, in main
    run(FLAGS, cfg)
  File "D:\Project_pptracking\PaddleDetection-release-2.4\tools\train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\engine\trainer.py", line 454, in train
    outputs = model(data)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func    outputs = self.forward(*inputs, **kwargs)
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\architectures\meta_arch.py", line 59, in forward
    out = self.get_loss()
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\architectures\fairmot.py", line 99, in get_loss    loss = self._forward()
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\architectures\fairmot.py", line 78, in _forward    reid_loss = self.reid(neck_feat, self.inputs)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func    outputs = self.forward(*inputs, **kwargs)
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\reid\fairmot_embedding_head.py", line 115, in forward
    loss = self.get_loss(reid_feat, inputs)
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\reid\fairmot_embedding_head.py", line 163, in get_loss
    loss = self.reid_loss(logit, target)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func    outputs = self.forward(*inputs, **kwargs)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\nn\layer\loss.py", line 397, in forward
    ret = paddle.nn.functional.cross_entropy(
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\nn\functional\loss.py", line 1722, in cross_entropy
    raise ValueError("Target {} is out of upper bound.".format(
ValueError: Target 4578971296541297966 is out of upper bound.

**Comment by nemonameless** [comment]
paddle 2.3.1 训了下没有这个报错，也没遇到过这个问题。建议看一下numpy版本，我的是1.21.5。

**Comment by nemonameless** [comment]
win下建议先使用paddle2.2版本
