### ISSUE TITLE
Unable to Download FairMOT DLA-34

### ISSUE THREAD

**Issue by aqx95** [PaddlePaddle/PaddleDetection#6637]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

I was looking to run head tracking and i tried to download one of the pretrained model, FairMOT DLA-34, using the provided link https://paddledet.bj.bcebos.com/models/mot/fairmot_dla34_30e_1088x608_headtracking21.pdparams. However, i kept running into the below issue:
```
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
W0812 10:31:42.709268 16300 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.2, Runtim
e API Version: 10.2
W0812 10:31:42.712399 16300 device_context.cc:465] device: 0, cuDNN Version: 7.6.
[08/12 10:31:46] ppdet.utils.download WARNING: File /home/std/.cache/paddle/weights/fairmot_dla34_30e_1088x608_headtracking21.pdparams m
d5 check failed, 3323319f736604c25819046f8eedd851(calc) != 5c013491241ab53f35645284942ee881(base)
[08/12 10:31:46] ppdet.utils.download INFO: Downloading fairmot_dla34_30e_1088x608_headtracking21.pdparams from https://paddledet.bj.bcebos.com/models/mot/fairmot_dla34_30e_1088x608_headtracking21.pdparams
 31%|████████████████████████████▉                                                                | 24576/78970 [19:19<42:46, 21.19KB/s]
Traceback (most recent call last):
  File "/data/work/Paddle_20_01_2022/venv/lib/python3.7/site-packages/paddle/framework/io.py", line 935, in load
    load_result = pickle.load(f, encoding='latin1')
_pickle.UnpicklingError: pickle data was truncated

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/work/Paddle_20_01_2022/venv/lib/python3.7/site-packages/paddle/framework/io.py", line 961, in load
    tensor, _ = _load_selected_rows(path)
  File "/data/work/Paddle_20_01_2022/venv/lib/python3.7/site-packages/paddle/framework/io.py", line 522, in _load_selected_rows
    _seek = core.load_selected_rows(temp_sr, file_name)
ValueError: (InvalidArgument) Only version 0 SelectedRows is supported.
  [Hint: Expected version == 0U, but received version:3650421888 != 0U:0.] (at /paddle/paddle/fluid/framework/selected_rows.cc:139)

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/data/work/Paddle_20_01_2022/venv/lib/python3.7/site-packages/paddle/framework/io.py", line 965, in load
    tensor, _ = _load_lod_tensor(path)
  File "/data/work/Paddle_20_01_2022/venv/lib/python3.7/site-packages/paddle/framework/io.py", line 483, in _load_lod_tensor
    _seek = paddle.fluid.core.load_lod_tensor(temp_t, file_name)
ValueError: (InvalidArgument) Deserialize to tensor failed, maybe the loaded file is not a paddle model(expected file format: 0, but 365
0421888 found).
  [Hint: Expected version == 0U, but received version:3650421888 != 0U:0.] (at /paddle/paddle/fluid/framework/lod_tensor.cc:329)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/work/Paddle_20_01_2022/venv/lib/python3.7/site-packages/paddle/framework/io.py", line 977, in load
    program_desc_str)
  File "/data/work/Paddle_20_01_2022/venv/lib/python3.7/site-packages/paddle/fluid/framework.py", line 5292, in parse_from_string
    p.desc = core.ProgramDesc(binary_str)
ValueError: (InvalidArgument) Failed to parse program_desc from binary string.
  [Hint: Expected desc_.ParseFromString(binary_str) == true, but received desc_.ParseFromString(binary_str):0 != true:1.] (at /paddle/pa
ddle/fluid/framework/program_desc.cc:103)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/infer_mot.py", line 136, in <module>
    main()
  File "tools/infer_mot.py", line 132, in main
    run(FLAGS, cfg)
  File "tools/infer_mot.py", line 103, in run
    tracker.load_weights_jde(cfg.weights)
  File "/data/work/Paddle_20_01_2022/PaddleDetection/ppdet/engine/tracker.py", line 107, in load_weights_jde
    load_weight(self.model, weights, self.optimizer)
  File "/data/work/Paddle_20_01_2022/PaddleDetection/ppdet/utils/checkpoint.py", line 75, in load_weight
    param_state_dict = paddle.load(pdparam_path)
  File "/data/work/Paddle_20_01_2022/venv/lib/python3.7/site-packages/paddle/framework/io.py", line 982, in load
    path))
ValueError: `paddle.load` can not parse the file:/home/std/.cache/paddle/weights/fairmot_dla34_30e_1088x608_headtracking21.pdparams.
```

### 复现环境 Environment

- PaddlePaddle: 2.2.1
- PaddleDetection: 2.3.0
- Python: 3.7.10
- CUDA: 10.2
- CuDNN: 7.6

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
看看是不是网络问题。这个链接离线下载是可以的。

**Comment by aqx95** [comment]
换另一个网络就能下载了，确实是网络问题。谢谢🙏
