### ISSUE TITLE
ValueError: The additional config (onnx_format) of `paddle.jit.save` is not supported.

### ISSUE THREAD

**Issue by czczmr** [PaddlePaddle/PaddleDetection#6647]
### 问题描述 Please describe your issue

# Weights of yolov3_mobilenet_v1_voc
pretrain_weights: /root/autodl-tmp/pd/output/yolov3_mobilenet_v3_large_270e_coco/model_final.pdparams
slim: PrunerQAT

PrunerQAT:
  criterion: fpgm
  pruned_params: ['conv2d_52.w_0', 'conv2d_53.w_0', 'conv2d_54.w_0',
                  'conv2d_55.w_0', 'conv2d_56.w_0', 'conv2d_57.w_0',
                  'conv2d_59.w_0', 'conv2d_60.w_0', 'conv2d_61.w_0',
                  'conv2d_62.w_0', 'conv2d_63.w_0', 'conv2d_64.w_0',
                  'conv2d_66.w_0', 'conv2d_67.w_0', 'conv2d_68.w_0',
                  'conv2d_69.w_0', 'conv2d_70.w_0', 'conv2d_71.w_0']
  pruned_ratios: [0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.875,0.875,0.875,0.875,0.875,0.875]
  print_prune_params: False
  quant_config: {
    'weight_quantize_type': 'channel_wise_abs_max', 'activation_quantize_type': 'moving_average_abs_max',
    'weight_bits': 8, 'activation_bits': 8, 'dtype': 'int8', 'window_size': 10000, 'moving_rate': 0.9,
    'quantizable_layer_type': ['Conv2D', 'Linear']}
  print_qat_model: False

改写的剪枝量化模型，训练正常。在导出模型时，出现了：
[08/15 12:21:06] ppdet.engine INFO: Export inference config file to /root/autodl-tmp/infer/yolov3_mobilenetv3_prune_qat/yolov3_mobilenetv3_prune_qat/infer_cfg.yml
Traceback (most recent call last):
  File "tools/export_model.py", line 108, in <module>
    main()
  File "tools/export_model.py", line 104, in main
    run(FLAGS, cfg)
  File "tools/export_model.py", line 73, in run
    trainer.export(FLAGS.output_dir)
  File "/root/autodl-tmp/pd/ppdet/engine/trainer.py", line 869, in export
    self.cfg.slim.save_quantized_model(
  File "/root/autodl-tmp/pd/ppdet/slim/prune.py", line 150, in save_quantized_model
    self.quanter.save_quantized_model(
  File "/root/miniconda3/lib/python3.8/site-packages/paddleslim/dygraph/quant/qat.py", line 289, in save_quantized_model
    self.imperative_qat.save_quantized_model(
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/contrib/slim/quantization/imperative/qat.py", line 262, in save_quantized_model
    self._quantize_outputs.save_quantized_model(layer, path, input_spec,
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/contrib/slim/quantization/imperative/qat.py", line 465, in save_quantized_model
    paddle.jit.save(layer=model, path=path, input_spec=input_spec, **config)
  File "/root/miniconda3/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/jit.py", line 731, in save
    configs = _parse_save_configs(configs)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/jit.py", line 376, in _parse_save_configs
    raise ValueError(
ValueError: The additional config (onnx_format) of `paddle.jit.save` is not supported.

导出代码如下：
!# 导出YOLOv3模型
!export CUDA_VISIBLE_DEVICES=0 #windows和Mac下不需要执行该命令
%cd /root/autodl-tmp/pd
!python tools/export_model.py -c configs/yolov3/yolov3_mobilenet_v3_large_270e_coco.yml \
     --slim_config configs/slim/extensions/yolov3_mobilenetv3_prune_qat.yml\
     --output_dir=/root/autodl-tmp/infer/yolov3_mobilenetv3_prune_qat \
     -o weights=output/yolov3_mobilenetv3_prune_qat/model_final.pdparams

**Comment by czczmr** [comment]
有人解答下吗
