### ISSUE TITLE
PPTracking 多相机追踪

### ISSUE THREAD

**Issue by lqsweet** [PaddlePaddle/PaddleDetection#6649]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

```
ffmpeg processing of video ./mtmct-demo/c004.mp4
start tracking seq: c004
Tracking frame: 0
Tracking frame: 10
Tracking frame: 20
Tracking frame: 30
Tracking frame: 40
Tracking frame: 50
Tracking frame: 60
Tracking frame: 70
Tracking frame: 80
Tracking frame: 90
Tracking frame: 100
Traceback (most recent call last):
  File "deploy/pptracking/python/mot_sde_infer.py", line 755, in <module>
    main()
  File "deploy/pptracking/python/mot_sde_infer.py", line 724, in main
    detector.predict_mtmct(FLAGS.mtmct_dir, mtmct_cfg)
  File "deploy/pptracking/python/mot_sde_infer.py", line 656, in predict_mtmct
    map_tid = sub_cluster(
  File "/home/nodes/Database/deepleaning/gitclone/PaddleDetection-release-2.4/deploy/pptracking/python/mot/mtmct/postprocess.py", line 114, in sub_cluster
    clu = get_labels(
  File "/home/nodes/Database/deepleaning/gitclone/PaddleDetection-release-2.4/deploy/pptracking/python/mot/mtmct/utils.py", line 532, in get_labels
    sim_matrix = get_sim_matrix(
  File "/home/nodes/Database/deepleaning/gitclone/PaddleDetection-release-2.4/deploy/pptracking/python/mot/mtmct/utils.py", line 509, in get_sim_matrix
    q_arr = normalize(q_arr, axis=1)
  File "/home/nodes/Database/deepleaning/gitclone/PaddleDetection-release-2.4/deploy/pptracking/python/mot/mtmct/utils.py", line 377, in normalize
    nparray = preprocessing.normalize(nparray, norm='l2', axis=axis)
  File "/home/nodes/Database/deepleaning/gitclone/PaddleDetection-release-2.4/.venv/lib/python3.8/site-packages/sklearn/preprocessing/_data.py", line 1786, in normalize
    X = check_array(
  File "/home/nodes/Database/deepleaning/gitclone/PaddleDetection-release-2.4/.venv/lib/python3.8/site-packages/sklearn/utils/validation.py", line 879, in check_array
    raise ValueError(
ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
```

### 是否愿意提交PR Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by lqsweet** [comment]
复现环境 ubutnu20.04，python3.8，cuda11.1，PaddleDetection2.4

**Comment by nemonameless** [comment]
改了什么地方也请说明下谢谢

**Comment by lqsweet** [comment]
> 改了什么地方也请说明下谢谢
没有修改代码

**Comment by lqsweet** [comment]
> 改了什么地方也请说明下谢谢

没有修改代码

**Comment by lqsweet** [comment]
> 改了什么地方也请说明下谢谢
ppyolov2 导出模型的infer_cfg_.yml修改
修改内容
label_list改为只有car一个类别

label_list:
 - car

**Comment by lqsweet** [comment]
![88e07aeaf85c7bc11fd151e6ce272b2](https://user-images.githubusercontent.com/38726025/184840037-ac2179b5-0a1b-4605-8a83-e509456bdf80.png)
没改这前是这个错误

**Comment by lqsweet** [comment]
> 改了什么地方也请说明下谢谢

改了什么地方也请说明下谢谢
ppyolov2 导出模型的infer_cfg_.yml修改
修改内容
label_list改为只有car一个类别

label_list:

car

没改之前是这个错误
![88e07aeaf85c7bc11fd151e6ce272b2](https://user-images.githubusercontent.com/38726025/184840385-14b19991-d319-45d0-8e1e-d8b5f17729c1.png)

**Comment by nemonameless** [comment]
请使用develop分支 [4. 跨境跟踪模型的导出和预测](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/deploy/pptracking/python#4-%E8%B7%A8%E5%A2%83%E8%B7%9F%E8%B8%AA%E6%A8%A1%E5%9E%8B%E7%9A%84%E5%AF%BC%E5%87%BA%E5%92%8C%E9%A2%84%E6%B5%8B) 
使用这个车辆模型 https://bj.bcebos.com/v1/paddledet/models/pipeline/mot_ppyoloe_l_36e_ppvehicle.zip

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/issues/5967

**Comment by lqsweet** [comment]
> #5967

修改后会出如下错误
‘’’
ffmpeg processing of video ./mtmct-demo/c004.mp4
start tracking seq: c004
Tracking frame: 0
Tracking frame: 10
Tracking frame: 20
Tracking frame: 30
Tracking frame: 40
Tracking frame: 50
Tracking frame: 60
Tracking frame: 70
Tracking frame: 80
Tracking frame: 90
Tracking frame: 100
Traceback (most recent call last):
  File "deploy/pptracking/python/mot_sde_infer.py", line 755, in <module>
    main()
  File "deploy/pptracking/python/mot_sde_infer.py", line 724, in main
    detector.predict_mtmct(FLAGS.mtmct_dir, mtmct_cfg)
  File "deploy/pptracking/python/mot_sde_infer.py", line 656, in predict_mtmct
    map_tid = sub_cluster(
  File "/home/nodes/Database/deepleaning/gitclone/PaddleDetection-release-2.4/deploy/pptracking/python/mot/mtmct/postprocess.py", line 114, in sub_cluster
    clu = get_labels(
  File "/home/nodes/Database/deepleaning/gitclone/PaddleDetection-release-2.4/deploy/pptracking/python/mot/mtmct/utils.py", line 532, in get_labels
    sim_matrix = get_sim_matrix(
  File "/home/nodes/Database/deepleaning/gitclone/PaddleDetection-release-2.4/deploy/pptracking/python/mot/mtmct/utils.py", line 509, in get_sim_matrix
    q_arr = normalize(q_arr, axis=1)
  File "/home/nodes/Database/deepleaning/gitclone/PaddleDetection-release-2.4/deploy/pptracking/python/mot/mtmct/utils.py", line 377, in normalize
    nparray = preprocessing.normalize(nparray, norm='l2', axis=axis)
  File "/home/nodes/Database/deepleaning/gitclone/PaddleDetection-release-2.4/.venv/lib/python3.8/site-packages/sklearn/preprocessing/_data.py", line 1786, in normalize
    X = check_array(
  File "/home/nodes/Database/deepleaning/gitclone/PaddleDetection-release-2.4/.venv/lib/python3.8/site-packages/sklearn/utils/validation.py", line 879, in check_array
    raise ValueError(
ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
‘’’

**Comment by lqsweet** [comment]
> 请使用develop分支 [4. 跨境跟踪模型的导出和预测](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/deploy/pptracking/python#4-%E8%B7%A8%E5%A2%83%E8%B7%9F%E8%B8%AA%E6%A8%A1%E5%9E%8B%E7%9A%84%E5%AF%BC%E5%87%BA%E5%92%8C%E9%A2%84%E6%B5%8B) 使用这个车辆模型 https://bj.bcebos.com/v1/paddledet/models/pipeline/mot_ppyoloe_l_36e_ppvehicle.zip

![image](https://user-images.githubusercontent.com/38726025/185035441-868d06fd-65cc-491f-a3f1-bdd19f3c7558.png)

**Comment by lqsweet** [comment]
> 请使用develop分支 [4. 跨境跟踪模型的导出和预测](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/deploy/pptracking/python#4-%E8%B7%A8%E5%A2%83%E8%B7%9F%E8%B8%AA%E6%A8%A1%E5%9E%8B%E7%9A%84%E5%AF%BC%E5%87%BA%E5%92%8C%E9%A2%84%E6%B5%8B) 使用这个车辆模型 https://bj.bcebos.com/v1/paddledet/models/pipeline/mot_ppyoloe_l_36e_ppvehicle.zip

![image](https://user-images.githubusercontent.com/38726025/185079947-691a67bd-029a-4028-b5cb-d836ac8d6c02.png)

**Comment by lqsweet** [comment]
> > 请使用develop分支 [4. 跨境跟踪模型的导出和预测](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/deploy/pptracking/python#4-%E8%B7%A8%E5%A2%83%E8%B7%9F%E8%B8%AA%E6%A8%A1%E5%9E%8B%E7%9A%84%E5%AF%BC%E5%87%BA%E5%92%8C%E9%A2%84%E6%B5%8B) 使用这个车辆模型 https://bj.bcebos.com/v1/paddledet/models/pipeline/mot_ppyoloe_l_36e_ppvehicle.zip
> 
> ![image](https://user-images.githubusercontent.com/38726025/185079947-691a67bd-029a-4028-b5cb-d836ac8d6c02.png)

报错文件148行添加一个数组越界处理
![image](https://user-images.githubusercontent.com/38726025/185283454-229a2fb8-09e3-4134-885c-1e872542a27d.png)

**Comment by Mrzhang155123** [comment]
怎么解决呢，哭死~
-----------  Running Arguments -----------
batch_size: 1
camera_id: -1
cpu_threads: 1
device: GPU
do_entrance_counting: False
draw_center_traj: False
enable_mkldnn: False
image_dir: None
image_file: None
model_dir: output_inference/ppyolov2_r50vd_dcn_365e_aic21mtmct_vehicle/
mtmct_cfg: deploy/pptracking/python/mtmct_cfg.yml
mtmct_dir: mtmct-demo
output_dir: output
reid_batch_size: 50
reid_model_dir: output_inference/deepsort_pplcnet_vehicle
run_benchmark: False
run_mode: paddle
save_images: True
save_mot_txts: True
scaled: True
secs_interval: 2
threshold: 0.5
trt_calib_mode: False
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
video_file: None
------------------------------------------
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order:
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
E0124 18:58:15.374557 31108 analysis_config.cc:125] Please use PaddlePaddle with GPU version.
-----------  Model Configuration -----------
Model Arch: DeepSORT
Transform Order:
--transform op: LetterBoxResize
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
E0124 18:58:16.369859 31108 analysis_config.cc:125] Please use PaddlePaddle with GPU version.
Totally 106 frames found in seq c003.
Processing frame 0 of seq c003.
Processing frame 10 of seq c003.
Processing frame 20 of seq c003.
Processing frame 30 of seq c003.
Processing frame 40 of seq c003.
Processing frame 50 of seq c003.
Processing frame 60 of seq c003.
Processing frame 70 of seq c003.
Processing frame 80 of seq c003.
Processing frame 90 of seq c003.
Processing frame 100 of seq c003.
MOT results save in output\c003.txt
ffmpeg processing of video mtmct-demo\c003.mp4
Totally 106 frames found in seq c003.
Processing frame 0 of seq c003.
Processing frame 10 of seq c003.
Processing frame 20 of seq c003.
Processing frame 30 of seq c003.
Processing frame 40 of seq c003.
Processing frame 50 of seq c003.
Processing frame 60 of seq c003.
Processing frame 70 of seq c003.
Processing frame 80 of seq c003.
Processing frame 90 of seq c003.
Processing frame 100 of seq c003.
MOT results save in output\c003.txt
Totally 102 frames found in seq c004.
Processing frame 0 of seq c004.
Processing frame 10 of seq c004.
Processing frame 20 of seq c004.
Processing frame 30 of seq c004.
Processing frame 40 of seq c004.
Processing frame 50 of seq c004.
Processing frame 60 of seq c004.
Processing frame 70 of seq c004.
Processing frame 80 of seq c004.
Processing frame 90 of seq c004.
Processing frame 100 of seq c004.
MOT results save in output\c004.txt
ffmpeg processing of video mtmct-demo\c004.mp4
Totally 102 frames found in seq c004.
Processing frame 0 of seq c004.
Processing frame 10 of seq c004.
Processing frame 20 of seq c004.
Processing frame 30 of seq c004.
Processing frame 40 of seq c004.
Processing frame 50 of seq c004.
Processing frame 60 of seq c004.
Processing frame 70 of seq c004.
Processing frame 80 of seq c004.
Processing frame 90 of seq c004.
Processing frame 100 of seq c004.
MOT results save in output\c004.txt
current use ff finetuned parameters....
feat3:0/91
feat3:0/91
current use ff finetuned parameters....
feat3:0/91
feat3:0/91
gen_res: write file in output\mtmct_result.txt
Traceback (most recent call last):
  File "E:\paddlepaddle\mm\PaddleDetection\deploy\pptracking\python\mot_sde_infer.py", line 1110, in <module>
    main()
  File "E:\paddlepaddle\mm\PaddleDetection\deploy\pptracking\python\mot_sde_infer.py", line 1059, in main
    predict_mtmct(
  File "E:\paddlepaddle\mm\PaddleDetection\deploy\pptracking\python\mot_sde_infer.py", line 931, in predict_mtmct
    camera_results, cid_tid_fid_res = get_mtmct_matching_results(
  File "E:\paddlepaddle\mm\PaddleDetection\deploy\pptracking\python\mot\mtmct\postprocess.py", line 215, in get_mtmct_matching_results
    camera_ids = list(map(int, np.unique(res[:, 0])))
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

**Comment by wyd1520** [comment]
> ## 怎么解决呢，哭死~
> ----------- Running Arguments -----------
> batch_size: 1
> camera_id: -1
> cpu_threads: 1
> device: GPU
> do_entrance_counting: False
> draw_center_traj: False
> enable_mkldnn: False
> image_dir: None
> image_file: None
> model_dir: output_inference/ppyolov2_r50vd_dcn_365e_aic21mtmct_vehicle/
> mtmct_cfg: deploy/pptracking/python/mtmct_cfg.yml
> mtmct_dir: mtmct-demo
> output_dir: output
> reid_batch_size: 50
> reid_model_dir: output_inference/deepsort_pplcnet_vehicle
> run_benchmark: False
> run_mode: paddle
> save_images: True
> save_mot_txts: True
> scaled: True
> secs_interval: 2
> threshold: 0.5
> trt_calib_mode: False
> trt_max_shape: 1280
> trt_min_shape: 1
> trt_opt_shape: 640
> video_file: None
> ## ----------- Model Configuration -----------
> Model Arch: YOLO
> Transform Order:
> --transform op: Resize
> --transform op: NormalizeImage
> --transform op: Permute
> ## E0124 18:58:15.374557 31108 analysis_config.cc:125] Please use PaddlePaddle with GPU version.
> ----------- Model Configuration -----------
> Model Arch: DeepSORT
> Transform Order:
> --transform op: LetterBoxResize
> --transform op: NormalizeImage
> --transform op: Permute
> E0124 18:58:16.369859 31108 analysis_config.cc:125] Please use PaddlePaddle with GPU version. Totally 106 frames found in seq c003. Processing frame 0 of seq c003. Processing frame 10 of seq c003. Processing frame 20 of seq c003. Processing frame 30 of seq c003. Processing frame 40 of seq c003. Processing frame 50 of seq c003. Processing frame 60 of seq c003. Processing frame 70 of seq c003. Processing frame 80 of seq c003. Processing frame 90 of seq c003. Processing frame 100 of seq c003. MOT results save in output\c003.txt ffmpeg processing of video mtmct-demo\c003.mp4 Totally 106 frames found in seq c003. Processing frame 0 of seq c003. Processing frame 10 of seq c003. Processing frame 20 of seq c003. Processing frame 30 of seq c003. Processing frame 40 of seq c003. Processing frame 50 of seq c003. Processing frame 60 of seq c003. Processing frame 70 of seq c003. Processing frame 80 of seq c003. Processing frame 90 of seq c003. Processing frame 100 of seq c003. MOT results save in output\c003.txt Totally 102 frames found in seq c004. Processing frame 0 of seq c004. Processing frame 10 of seq c004. Processing frame 20 of seq c004. Processing frame 30 of seq c004. Processing frame 40 of seq c004. Processing frame 50 of seq c004. Processing frame 60 of seq c004. Processing frame 70 of seq c004. Processing frame 80 of seq c004. Processing frame 90 of seq c004. Processing frame 100 of seq c004. MOT results save in output\c004.txt ffmpeg processing of video mtmct-demo\c004.mp4 Totally 102 frames found in seq c004. Processing frame 0 of seq c004. Processing frame 10 of seq c004. Processing frame 20 of seq c004. Processing frame 30 of seq c004. Processing frame 40 of seq c004. Processing frame 50 of seq c004. Processing frame 60 of seq c004. Processing frame 70 of seq c004. Processing frame 80 of seq c004. Processing frame 90 of seq c004. Processing frame 100 of seq c004. MOT results save in output\c004.txt current use ff finetuned parameters.... feat3:0/91 feat3:0/91 current use ff finetuned parameters.... feat3:0/91 feat3:0/91 gen_res: write file in output\mtmct_result.txt Traceback (most recent call last): File "E:\paddlepaddle\mm\PaddleDetection\deploy\pptracking\python\mot_sde_infer.py", line 1110, in main() File "E:\paddlepaddle\mm\PaddleDetection\deploy\pptracking\python\mot_sde_infer.py", line 1059, in main predict_mtmct( File "E:\paddlepaddle\mm\PaddleDetection\deploy\pptracking\python\mot_sde_infer.py", line 931, in predict_mtmct camera_results, cid_tid_fid_res = get_mtmct_matching_results( File "E:\paddlepaddle\mm\PaddleDetection\deploy\pptracking\python\mot\mtmct\postprocess.py", line 215, in get_mtmct_matching_results camera_ids = list(map(int, np.unique(res[:, 0]))) IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

解决了吗
