### ISSUE TITLE
训练中加载数据异常中止

### ISSUE THREAD

**Issue by monsterlyg** [PaddlePaddle/PaddleDetection#6666]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

训练到第160个epoch程序就中止了，报错信息如下，load数据那里，看不懂细节原因

loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
{'freighter': 0, 'fishermen': 1, 'nonMotor': 2}
ERROR: Unexpected segmentation fault encountered in DataLoader workers.
Exception in thread Thread-162:
Traceback (most recent call last):
  File "/root/new_mount_2/lyg/conda/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 620, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/root/new_mount_2/lyg/conda/envs/paddle_env/lib/python3.8/multiprocessing/queues.py", line 108, in get
Traceback (most recent call last):
  File "tools/train.py", line 196, in <module>
    raise Empty
_queue    .main()Empty
  File "tools/train.py", line 192, in main

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/new_mount_2/lyg/conda/envs/paddle_env/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    run(FLAGS, cfg)
  File "tools/train.py", line 145, in run
    trainer.train(FLAGS.eval)
      File "/home/paddleflow/storage/mnt/lyg/Projects/PaddleDetection/ppdet/engine/incre_trainer.py", line 433, in train
self.run()
  File "/root/new_mount_2/lyg/conda/envs/paddle_env/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/new_mount_2/lyg/conda/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 534, in _thread_loop
    batch = self._get_data()    
for step_id, data in enumerate(self.loader):  File "/root/new_mount_2/lyg/conda/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 635, in _get_data

  File "/home/paddleflow/storage/mnt/lyg/Projects/PaddleDetection/ppdet/data/reader.py", line 209, in __next__
    raise RuntimeError("DataLoader {} workers exit unexpectedly, " \
RuntimeError: DataLoader 1 workers exit unexpectedly, pids: 25225
    return next(self.loader)
  File "/root/new_mount_2/lyg/conda/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 746, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

**Comment by zhiboniu** [comment]
看起来是有空数据导致的，先查查数据有没有问题吧，或者数据增强有没有导致空数据的可能
