### ISSUE TITLE
训练过程中出现报错OSError: (External) CUDA error(999), unknown error

### ISSUE THREAD

**Issue by ClassmateXiaoyu** [PaddlePaddle/PaddleDetection#6792]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

环境：
paddlepaddle-gpu              2.3.1
paddledet                     2.4.0

显卡：GTX 1070 8G
CUDA     10.2
cudnn     7.6.5

数据集：自定义数据集，COCO格式，图片格式为JPG

代码如下：
```
(python38) E:\AI_projecs\pac_identification\V2>python tools/train.py -c configs/ppyolo/ppyolov2_r101vd_dcn_365e_coco.yml
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
W0829 17:29:59.399045 15216 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.2, Runtime API Version: 10.2
W0829 17:29:59.439047 15216 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
[08/29 17:30:03] ppdet.utils.checkpoint INFO: Finish loading model weights: C:\Users\yhy/.cache/paddle/weights\ResNet101_vd_ssld_pretrained.pdparams
[08/29 17:30:06] ppdet.engine INFO: Epoch: [0] [ 0/32] learning_rate: 0.000000 loss_xy: 2.398562 loss_wh: 13.457909 loss_iou: 9.439013 loss_iou_aware: 1.867091 loss_obj: 21850.132812 loss_cls: 5.447876 loss: 21882.742188 eta: 4:48:34 batch_cost: 3.6072 data_cost: 0.0000 ips: 0.5544 images/s
[08/29 17:30:27] ppdet.engine INFO: Epoch: [0] [10/32] learning_rate: 0.000008 loss_xy: 3.053678 loss_wh: 11.517223 loss_iou: 12.724132 loss_iou_aware: 2.116462 loss_obj: 16094.050781 loss_cls: 7.076260 loss: 16138.867188 eta: 2:02:04 batch_cost: 1.3213 data_cost: 0.0002 ips: 1.5137 images/s
[08/29 17:30:48] ppdet.engine INFO: Epoch: [0] [20/32] learning_rate: 0.000015 loss_xy: 2.776784 loss_wh: 9.722041 loss_iou: 10.544098 loss_iou_aware: 2.225593 loss_obj: 11327.802734 loss_cls: 7.315646 loss: 11361.541992 eta: 1:56:54 batch_cost: 1.3996 data_cost: 0.0003 ips: 1.4290 images/s
[08/29 17:31:07] ppdet.engine INFO: Epoch: [0] [30/32] learning_rate: 0.000023 loss_xy: 3.456446 loss_wh: 11.567091 loss_iou: 13.852726 loss_iou_aware: 2.336302 loss_obj: 16976.078125 loss_cls: 8.916719 loss: 17018.533203 eta: 1:50:30 batch_cost: 1.2274 data_cost: 0.0000 ips: 1.6295 images/s
[08/29 17:31:12] ppdet.engine INFO: Epoch: [1] [ 0/32] learning_rate: 0.000025 loss_xy: 3.210438 loss_wh: 10.256889 loss_iou: 12.561707 loss_iou_aware: 1.914630 loss_obj: 19656.015625 loss_cls: 8.410213 loss: 19692.189453 eta: 1:52:24 batch_cost: 1.3358 data_cost: 0.1189 ips: 1.4973 images/s
[08/29 17:31:32] ppdet.engine INFO: Epoch: [1] [10/32] learning_rate: 0.000032 loss_xy: 3.692497 loss_wh: 11.925137 loss_iou: 10.633288 loss_iou_aware: 1.640993 loss_obj: 12537.815430 loss_cls: 7.130577 loss: 12561.986328 eta: 1:49:52 batch_cost: 1.2893 data_cost: 0.0001 ips: 1.5513 images/s
Traceback (most recent call last):
  File "tools/train.py", line 177, in <module>
    main()
  File "tools/train.py", line 173, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "D:\Anaconda3\envs\python38\lib\site-packages\paddledet-2.4.0-py3.8.egg\ppdet\engine\trainer.py", line 458, in train
    self.optimizer.step()
  File "D:\Anaconda3\envs\python38\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\Anaconda3\envs\python38\lib\site-packages\paddle\fluid\dygraph\base.py", line 299, in __impl__
    return func(*args, **kwargs)
  File "D:\Anaconda3\envs\python38\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\Anaconda3\envs\python38\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\Anaconda3\envs\python38\lib\site-packages\paddle\fluid\framework.py", line 434, in __impl__
    return func(*args, **kwargs)
  File "D:\Anaconda3\envs\python38\lib\site-packages\paddle\optimizer\optimizer.py", line 1219, in step
    self._apply_optimize(
  File "D:\Anaconda3\envs\python38\lib\site-packages\paddle\optimizer\optimizer.py", line 952, in _apply_optimize
    params_grads = self._grad_clip(params_grads)
  File "D:\Anaconda3\envs\python38\lib\site-packages\paddle\fluid\clip.py", line 193, in __call__
    return self._dygraph_clip(params_grads)
  File "D:\Anaconda3\envs\python38\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\Anaconda3\envs\python38\lib\site-packages\paddle\fluid\dygraph\base.py", line 299, in __impl__
    return func(*args, **kwargs)
  File "D:\Anaconda3\envs\python38\lib\site-packages\paddle\fluid\clip.py", line 500, in _dygraph_clip
    sum_square = _squared_l2_norm(merge_grad)
  File "D:\Anaconda3\envs\python38\lib\site-packages\paddle\fluid\clip.py", line 80, in _squared_l2_norm
    return _C_ops.squared_l2_norm(x)
OSError: (External) CUDA error(999), unknown error.
  [Hint: 'cudaErrorUnknown'. This indicates that an unknown internal error has occurred. ] (at ../paddle/fluid/operators/math/squared_l2_norm.h:77)
  [operator < squared_l2_norm > error]
```

**Comment by nemonameless** [comment]
win上请使用paddle2.2.2稳定版本

**Comment by ClassmateXiaoyu** [comment]
> win上请使用paddle2.2.2稳定版本

那就是删除2.3.1版本，重新安装2.2.2版本对吧

**Comment by nemonameless** [comment]
win下请安装最新develop版本的paddle。
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/windows-pip.html
