### ISSUE TITLE
ImportError: cannot import name '_legacy_C_ops' from 'paddle' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/__init__.py)

### ISSUE THREAD

**Issue by flyzxm5177** [PaddlePaddle/PaddleDetection#6855]
### 问题描述 Please describe your issue

!python tools/train.py -c configs/ppyoloe/ppyoloe_plus_crn_x_80e_coco.yml --use_vdl=True --vdl_log_dir=./ppyoloe-p-X/ --eval --amp

Traceback (most recent call last):
  File "tools/train.py", line 32, in <module>
    from ppdet.core.workspace import load_config, merge_config
  File "/home/aistudio/PaddleDetection/ppdet/__init__.py", line 15, in <module>
    from . import (core, data, engine, modeling, model_zoo, optimizer, metrics,
  File "/home/aistudio/PaddleDetection/ppdet/data/__init__.py", line 16, in <module>
    from . import transform
  File "/home/aistudio/PaddleDetection/ppdet/data/transform/__init__.py", line 15, in <module>
    from . import operators
  File "/home/aistudio/PaddleDetection/ppdet/data/transform/operators.py", line 53, in <module>
    from ppdet.modeling.keypoint_utils import get_affine_transform, affine_transform
  File "/home/aistudio/PaddleDetection/ppdet/modeling/__init__.py", line 19, in <module>
    from . import ops
  File "/home/aistudio/PaddleDetection/ppdet/modeling/ops.py", line 20, in <module>
    from paddle import _C_ops, _legacy_C_ops
ImportError: cannot import name '_legacy_C_ops' from 'paddle' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/__init__.py)

**Comment by nemonameless** [comment]
建议使用默认release/2.5分支。develop版本这个部分代码依赖特定paddle版本。

**Comment by flyzxm5177** [comment]
> 

执行!git checkout -b release/2.5， 还是报错

**Comment by flyzxm5177** [comment]
> 建议使用默认release/2.5分支。develop版本这个部分代码依赖特定paddle版本。


执行!git checkout -b release/2.5， 还是报错

**Comment by nemonameless** [comment]
git checkout release/2.5 切换分支。paddle版本可使用2.2.2稳定版本。
另外提问请遵循issue模板和，说明下改动了什么，版本和环境是什么，以便排查问题。

**Comment by XYZ-916** [comment]
paddle2.2.2版本，PaddleDetection develop分支还是有同样的错误。

**Comment by deeplearning666** [comment]
请问问题解决了吗？我也遇到相同的错误

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/develop/docs/tutorials/INSTALL_cn.md
请按照这个安装合适版本
