### ISSUE TITLE
在华为昇腾910环境下做预测任务，报argument 'bboxes' (position 0) must be Tensor 错误。

### ISSUE THREAD

**Issue by sgfCrazy** [PaddlePaddle/PaddleDetection#6856]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

用tools下的infer.py 执行预测命令，报以下的错误
报错：
[09/04 00:55:36] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/nfs/appnfs/sgf/model/20220903-232033-0x12fc/v1/ckpt/model_final.pdparams

[09/04 00:55:36] train INFO: Found 4 inference images in total.

0%| | 0/4 [00:00<?, ?it/s] 0%| | 0/4 [03:30<?, ?it/s]

Traceback (most recent call last):

File "/home/nfs/appnfs/sgf/code/702/paddle_back/PaddleDetection/tools/infer.py", line 255, in <module>

main()

File "/home/nfs/appnfs/sgf/code/702/paddle_back/PaddleDetection/tools/infer.py", line 251, in main

run(FLAGS, cfg)

File "/home/nfs/appnfs/sgf/code/702/paddle_back/PaddleDetection/tools/infer.py", line 194, in run

visualize=FLAGS.visualize)

File "/home/nfs/appnfs/sgf/code/702/paddle_back/PaddleDetection/ppdet/engine/trainer.py", line 877, in predict

outs = self.model(data)

File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 950, in __call__

return self._dygraph_call_func(*inputs, **kwargs)

File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 935, in _dygraph_call_func

outputs = self.forward(*inputs, **kwargs)

File "/home/nfs/appnfs/sgf/code/702/paddle_back/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 75, in forward

outs.append(self.get_pred())

File "/home/nfs/appnfs/sgf/code/702/paddle_back/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 127, in get_pred

return self._forward()

File "/home/nfs/appnfs/sgf/code/702/paddle_back/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 115, in _forward

self.inputs['im_shape'], self.inputs['scale_factor'])

File "/home/nfs/appnfs/sgf/code/702/paddle_back/PaddleDetection/ppdet/modeling/post_process.py", line 71, in __call__

bbox_pred, bbox_num, _ = self.nms(bboxes, score, self.num_classes)

File "/home/nfs/appnfs/sgf/code/702/paddle_back/PaddleDetection/ppdet/modeling/layers.py", line 564, in __call__

return ops.multiclass_nms(bboxes, score, **kwargs)

File "/home/nfs/appnfs/sgf/code/702/paddle_back/PaddleDetection/ppdet/modeling/ops.py", line 500, in multiclass_nms

rois_num, *attrs)

ValueError:

--------------------------------------

C++ Traceback (most recent call last):

--------------------------------------

0 phi::enforce::EnforceNotMet::EnforceNotMet(phi::ErrorSummary const&, char const*, int)

1 phi::enforce::GetCurrentTraceBackString(bool)

----------------------

Error Message Summary:

----------------------

InvalidArgumentError: multiclass_nms3(): argument 'bboxes' (position 0) must be Tensor, but got Tensor (at /home/nfs/appnfs/sgf/code/702/paddle/Paddle/paddle/fluid/pybind/eager_utils.cc:891)

请问这是什么原因造成的？该如何解决？感谢！

**Comment by zhiboniu** [comment]
请提供一下完整的预测命令吧，方便复现问题
