### ISSUE TITLE
paddledetection中使用TensorRT的问题

### ISSUE THREAD

**Issue by JinhengCV** [PaddlePaddle/PaddleDetection#6858]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

安装了几遍tensorrt和paddle，一直报RuntimeError: (NotFound) Tensor named layer_norm_3.w_0 is not found in TRT engine的错误（cuda10.1，cudnn7.6，python3.7。所有版本都是按照教程的，paddle也是带trt的2.3.1版本）

python deploy/python/infer.py --model_dir=XXX --image_dir=XXX --output_dir=XXX --device=gpu --run_benchmark=True --run_mode=trt_fp32
-----------  Running Arguments -----------
action_file: None
batch_size: 1
camera_id: -1
cpu_threads: 1
device: gpu
enable_mkldnn: False
enable_mkldnn_bfloat16: False
image_dir: demo/
image_file: None
model_dir: output/trt/yolox_l_convnext
output_dir: demo/outputs
random_pad: False
reid_batch_size: 50
reid_model_dir: None
run_benchmark: True
run_mode: trt_fp32
save_images: False
save_mot_txt_per_img: False
save_mot_txts: False
save_results: False
scaled: False
threshold: 0.5
tracker_config: None
trt_calib_mode: False
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
use_dark: True
use_gpu: False
video_file: None
window_size: 50
------------------------------------------
-----------  Model Configuration -----------
Model Arch: YOLOX
Transform Order: 
--transform op: Resize
--transform op: Pad
--transform op: Permute
--------------------------------------------
Traceback (most recent call last):
  File "deploy/python/infer.py", line 920, in <module>
    main()
  File "deploy/python/infer.py", line 880, in main
    output_dir=FLAGS.output_dir)
  File "deploy/python/infer.py", line 136, in __init__
    delete_shuffle_pass=delete_shuffle_pass)
  File "deploy/python/infer.py", line 781, in load_predictor
    predictor = create_predictor(config)
RuntimeError: (NotFound) Tensor named layer_norm_3.w_0 is not found in TRT engine
  [Hint: Expected itensor_map_.count(name) == true, but received itensor_map_.count(name):0 != true:1.] (at /paddle/paddle/fluid/inference/tensorrt/engine.cc:391)

**Comment by zhiboniu** [comment]
请问跑的是什么模型呢？请提供一下完整的命令吧，方便复现问题

**Comment by JinhengCV** [comment]
跑的是YOLOX-ConvNeXt模型
运行指令是python deploy/python/infer.py --model_dir=output/trt/yolox_l_convnext --image_dir=demo/ --output_dir=demo/outputs --device=gpu --run_benchmark=True --run_mode=trt_fp32

**Comment by nemonameless** [comment]
convnext 暂不支持trt部署。convnext速度会很慢，开trt意义也不大。

**Comment by JinhengCV** [comment]
> convnext 暂不支持trt部署。convnext速度会很慢，开trt意义也不大。

好的，谢谢。我评估的结果展示，它比原模型倒是没慢多少
那后面还会更新  支持convnext的trt的部署吗

**Comment by lyuwenyu** [comment]
什么版本的trt

**Comment by nemonameless** [comment]
会更新的。现阶段建议导出onnx再试trt。
```
model_type=convnext
job_name=yolox_convnext_s_36e_coco
config=configs/${model_type}/${job_name}.yml
weights=https://bj.bcebos.com/v1/paddledet/models/${job_name}.pdparams
# export
CUDA_VISIBLE_DEVICES=0 python tools/export_model.py -c ${config} -o weights=${weights} exclude_nms=True trt=True

# export onnx
paddle2onnx --model_dir output_inference/${job_name} --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 12 --save_file ${job_name}.onnx

# onnx test speed
/usr/local/TensorRT-8.0.3.4/bin/trtexec --onnx=${job_name}.onnx --workspace=4096 --avgRuns=10 --shapes=input:1x3x640x640 --fp16
```
导出onnx测速以及原生paddle的trt_fp16测速一般是不会导出NMS的。
如果需要infer出结果的，需自己接个NMS，使用参照[demo_onnx_trt](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/deploy/third_engine/demo_onnx_trt)

**Comment by JinhengCV** [comment]
> 

我用onnx导出了一下，前面几步没有报错，但是最后一步报错了

/media/customer/CCA30E2E0234694C/LJH/Tensorrt/TensorRT-6.0.1.5/bin/trtexec --onnx=./output/trt/yolox_l_convnext.onnx --workspace=4096 --avgRuns=10 --shapes=input:1x3x640x640 --fp16
&&&& RUNNING TensorRT.trtexec # /media/customer/CCA30E2E0234694C/LJH/Tensorrt/TensorRT-6.0.1.5/bin/trtexec --onnx=./output/trt/yolox_l_convnext.onnx --workspace=4096 --avgRuns=10 --shapes=input:1x3x640x640 --fp16
[08/05/2022-17:26:07] [I] === Model Options ===
[08/05/2022-17:26:07] [I] Format: ONNX
[08/05/2022-17:26:07] [I] Model: ./output/trt/yolox_l_convnext.onnx
[08/05/2022-17:26:07] [I] Output:
[08/05/2022-17:26:07] [I] === Build Options ===
[08/05/2022-17:26:07] [I] Max batch: explicit
[08/05/2022-17:26:07] [I] Workspace: 4096 MB
[08/05/2022-17:26:07] [I] minTiming: 1
[08/05/2022-17:26:07] [I] avgTiming: 8
[08/05/2022-17:26:07] [I] Precision: FP16
[08/05/2022-17:26:07] [I] Calibration: 
[08/05/2022-17:26:07] [I] Safe mode: Disabled
[08/05/2022-17:26:07] [I] Save engine: 
[08/05/2022-17:26:07] [I] Load engine: 
[08/05/2022-17:26:07] [I] Inputs format: fp32:CHW
[08/05/2022-17:26:07] [I] Outputs format: fp32:CHW
[08/05/2022-17:26:07] [I] Input build shape: input=1x3x640x640+1x3x640x640+1x3x640x640
[08/05/2022-17:26:07] [I] === System Options ===
[08/05/2022-17:26:07] [I] Device: 0
[08/05/2022-17:26:07] [I] DLACore: 
[08/05/2022-17:26:07] [I] Plugins:
[08/05/2022-17:26:07] [I] === Inference Options ===
[08/05/2022-17:26:07] [I] Batch: Explicit
[08/05/2022-17:26:07] [I] Iterations: 10 (200 ms warm up)
[08/05/2022-17:26:07] [I] Duration: 10s
[08/05/2022-17:26:07] [I] Sleep time: 0ms
[08/05/2022-17:26:07] [I] Streams: 1
[08/05/2022-17:26:07] [I] Spin-wait: Disabled
[08/05/2022-17:26:07] [I] Multithreading: Enabled
[08/05/2022-17:26:07] [I] CUDA Graph: Disabled
[08/05/2022-17:26:07] [I] Skip inference: Disabled
[08/05/2022-17:26:07] [I] === Reporting Options ===
[08/05/2022-17:26:07] [I] Verbose: Disabled
[08/05/2022-17:26:07] [I] Averages: 10 inferences
[08/05/2022-17:26:07] [I] Percentile: 99
[08/05/2022-17:26:07] [I] Dump output: Disabled
[08/05/2022-17:26:07] [I] Profile: Disabled
[08/05/2022-17:26:07] [I] Export timing to JSON file: 
[08/05/2022-17:26:07] [I] Export profile to JSON file: 
[08/05/2022-17:26:07] [I] 
----------------------------------------------------------------
Input filename:   ./output/trt/yolox_l_convnext.onnx
ONNX IR version:  0.0.8
Opset version:    12
Producer name:    
Producer version: 
Domain:           
Model version:    0
Doc string:       
----------------------------------------------------------------
WARNING: ONNX model has a newer ir_version (0.0.8) than this parser was built against (0.0.3).
[08/05/2022-17:26:07] [E] [TRT] (Unnamed Layer* 0) [Convolution]: at least 4 dimensions are required for input
While parsing node number 634 [ReduceMean]:
ERROR: onnx2trt_utils.hpp:347 In function convert_axis:
[8] Assertion failed: axis >= 0 && axis < nbDims
[08/05/2022-17:26:07] [E] Failed to parse onnx file
[08/05/2022-17:26:07] [E] Parsing model failed
[08/05/2022-17:26:07] [E] Engine could not be created
&&&& FAILED TensorRT.trtexec # /media/customer/CCA30E2E0234694C/LJH/Tensorrt/TensorRT-6.0.1.5/bin/trtexec --onnx=./output/trt/yolox_l_convnext.onnx --workspace=4096 --avgRuns=10 --shapes=input:1x3x640x640 --fp16

我还用其他官方模型yolox_l_300e_coco试了一下，也报错了：
/media/customer/CCA30E2E0234694C/LJH/Tensorrt/TensorRT-6.0.1.5/bin/trtexec --onnx=./output/trt/yolox_l.onnx --workspace=4096 --avgRuns=10 --shapes=input:1x3x640x640 --fp16
&&&& RUNNING TensorRT.trtexec # /media/customer/CCA30E2E0234694C/LJH/Tensorrt/TensorRT-6.0.1.5/bin/trtexec --onnx=./output/trt/yolox_l.onnx --workspace=4096 --avgRuns=10 --shapes=input:1x3x640x640 --fp16
[08/05/2022-16:59:18] [I] === Model Options ===
[08/05/2022-16:59:18] [I] Format: ONNX
[08/05/2022-16:59:18] [I] Model: ./output/trt/yolox_l.onnx
[08/05/2022-16:59:18] [I] Output:
[08/05/2022-16:59:18] [I] === Build Options ===
[08/05/2022-16:59:18] [I] Max batch: explicit
[08/05/2022-16:59:18] [I] Workspace: 4096 MB
[08/05/2022-16:59:18] [I] minTiming: 1
[08/05/2022-16:59:18] [I] avgTiming: 8
[08/05/2022-16:59:18] [I] Precision: FP16
[08/05/2022-16:59:18] [I] Calibration: 
[08/05/2022-16:59:18] [I] Safe mode: Disabled
[08/05/2022-16:59:18] [I] Save engine: 
[08/05/2022-16:59:18] [I] Load engine: 
[08/05/2022-16:59:18] [I] Inputs format: fp32:CHW
[08/05/2022-16:59:18] [I] Outputs format: fp32:CHW
[08/05/2022-16:59:18] [I] Input build shape: input=1x3x640x640+1x3x640x640+1x3x640x640
[08/05/2022-16:59:18] [I] === System Options ===
[08/05/2022-16:59:18] [I] Device: 0
[08/05/2022-16:59:18] [I] DLACore: 
[08/05/2022-16:59:18] [I] Plugins:
[08/05/2022-16:59:18] [I] === Inference Options ===
[08/05/2022-16:59:18] [I] Batch: Explicit
[08/05/2022-16:59:18] [I] Iterations: 10 (200 ms warm up)
[08/05/2022-16:59:18] [I] Duration: 10s
[08/05/2022-16:59:18] [I] Sleep time: 0ms
[08/05/2022-16:59:18] [I] Streams: 1
[08/05/2022-16:59:18] [I] Spin-wait: Disabled
[08/05/2022-16:59:18] [I] Multithreading: Enabled
[08/05/2022-16:59:18] [I] CUDA Graph: Disabled
[08/05/2022-16:59:18] [I] Skip inference: Disabled
[08/05/2022-16:59:18] [I] === Reporting Options ===
[08/05/2022-16:59:18] [I] Verbose: Disabled
[08/05/2022-16:59:18] [I] Averages: 10 inferences
[08/05/2022-16:59:18] [I] Percentile: 99
[08/05/2022-16:59:18] [I] Dump output: Disabled
[08/05/2022-16:59:18] [I] Profile: Disabled
[08/05/2022-16:59:18] [I] Export timing to JSON file: 
[08/05/2022-16:59:18] [I] Export profile to JSON file: 
[08/05/2022-16:59:18] [I] 
----------------------------------------------------------------
Input filename:   ./output/trt/yolox_l.onnx
ONNX IR version:  0.0.8
Opset version:    12
Producer name:    
Producer version: 
Domain:           
Model version:    0
Doc string:       
----------------------------------------------------------------
WARNING: ONNX model has a newer ir_version (0.0.8) than this parser was built against (0.0.3).
[08/05/2022-16:59:19] [E] [TRT] (Unnamed Layer* 4) [Concatenation]: all concat input tensors must have the same dimensions except on the concatenation axis (0), but dimensions mismatched at input 1 at index 1. Input 0 shape: [3,2,320], Input 1 shape: [3,1,320]
While parsing node number 643 [Conv]:
ERROR: builtin_op_importers.cpp:788 In function importConv:
[8] Assertion failed: (nbSpatialDims == 2 && kernel_weights.shape.nbDims == 4) || (nbSpatialDims == 3 && kernel_weights.shape.nbDims == 5)
[08/05/2022-16:59:19] [E] Failed to parse onnx file
[08/05/2022-16:59:19] [E] Parsing model failed
[08/05/2022-16:59:19] [E] Engine could not be created
&&&& FAILED TensorRT.trtexec # /media/customer/CCA30E2E0234694C/LJH/Tensorrt/TensorRT-6.0.1.5/bin/trtexec --onnx=./output/trt/yolox_l.onnx --workspace=4096 --avgRuns=10 --shapes=input:1x3x640x640 --fp16

**Comment by nemonameless** [comment]
trt版本太低，建议使用trt8。

**Comment by skyeyeCV** [comment]
@nemonameless  请问yolov6推断模型目前支持python tensorrt fp32运行吗？

**Comment by nemonameless** [comment]
支持的，--run_mode=trt_fp32即可。参考https://github.com/PaddlePaddle/PaddleYOLO/tree/release/2.5/configs/yolov6
需要安装的带trt的paddle版本，可以这里下载，https://paddleinference.paddlepaddle.org.cn/v2.2/user_guides/download_lib.html
