### ISSUE TITLE
mask_rcnn_r50_vd_fpn_2x_coco训练报错,AssertionError: Invalid segm type: <class 'NoneType'>

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleDetection#6971]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

```
(PaddleDetection) PS I:\Paddle\PaddleDetection> python tools/train.py -c  configs\mask_rcnn\mask_rcnn_r50_vd_fpn_2x_coco.yml
loading annotations into memory...
Done (t=0.03s)
creating index...
index created!
W0919 21:45:34.928529  4672 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.2
W0919 21:45:34.934513  4672 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
[09/19 21:45:34] reader WARNING: fail to map sample transform [RandomResize_5a7530] with error: Invalid segm type: <class 'NoneType'> and stack:
Traceback (most recent call last):
  File "I:\Paddle\PaddleDetection\ppdet\data\reader.py", line 54, in __call__
    data = f(data)
  File "I:\Paddle\PaddleDetection\ppdet\data\transform\operators.py", line 104, in __call__
    sample = self.apply(sample, context)
  File "I:\Paddle\PaddleDetection\ppdet\data\transform\operators.py", line 974, in apply
    return resizer(sample, context=context)
  File "I:\Paddle\PaddleDetection\ppdet\data\transform\operators.py", line 104, in __call__
    sample = self.apply(sample, context)
  File "I:\Paddle\PaddleDetection\ppdet\data\transform\operators.py", line 839, in apply
    sample['gt_poly'] = self.apply_segm(sample['gt_poly'], im_shape[:2],
  File "I:\Paddle\PaddleDetection\ppdet\data\transform\operators.py", line 774, in apply_segm
    if is_poly(segm):
  File "I:\Paddle\PaddleDetection\ppdet\data\transform\op_helper.py", line 411, in is_poly
    assert isinstance(segm, (list, dict)), \
AssertionError: Invalid segm type: <class 'NoneType'>

Exception in thread Thread-3:
Traceback (most recent call last):
  File "D:\anaconda308\envs\PaddleDetection\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\anaconda308\envs\PaddleDetection\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\anaconda308\envs\PaddleDetection\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 217, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices,
  File "D:\anaconda308\envs\PaddleDetection\lib\site-packages\paddle\fluid\dataloader\fetcher.py", line 121, in fetch
    data.append(self.dataset[idx])
  File "I:\Paddle\PaddleDetection\ppdet\data\source\dataset.py", line 96, in __getitem__
    return self.transform(roidb)
  File "I:\Paddle\PaddleDetection\ppdet\data\reader.py", line 60, in __call__
    raise e
  File "I:\Paddle\PaddleDetection\ppdet\data\reader.py", line 54, in __call__
    data = f(data)
  File "I:\Paddle\PaddleDetection\ppdet\data\transform\operators.py", line 104, in __call__
    sample = self.apply(sample, context)
  File "I:\Paddle\PaddleDetection\ppdet\data\transform\operators.py", line 974, in apply
    return resizer(sample, context=context)
  File "I:\Paddle\PaddleDetection\ppdet\data\transform\operators.py", line 104, in __call__
    sample = self.apply(sample, context)
  File "I:\Paddle\PaddleDetection\ppdet\data\transform\operators.py", line 839, in apply
    sample['gt_poly'] = self.apply_segm(sample['gt_poly'], im_shape[:2],
  File "I:\Paddle\PaddleDetection\ppdet\data\transform\operators.py", line 774, in apply_segm
    if is_poly(segm):
  File "I:\Paddle\PaddleDetection\ppdet\data\transform\op_helper.py", line 411, in is_poly
    assert isinstance(segm, (list, dict)), \
AssertionError: Invalid segm type: <class 'NoneType'>
[09/19 21:45:36] ppdet.utils.checkpoint INFO: Finish loading model weights: C:\Users\MM/.cache/paddle/weights\ResNet50_vd_pretrained.pdparams
```

```

```

metric: COCO
num_classes: 1

TrainDataset:
  !COCODataSet
    image_dir: Train
    anno_path: I:/2022/MsCOCO_dataset/Annotation/Train.json
    dataset_dir: I:/2022/MsCOCO_dataset/
    data_fields: ['image', 'gt_bbox', 'gt_class', 'gt_poly', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: Val
    anno_path: I:/2022/MsCOCO_dataset/Annotation/Val.json
    dataset_dir: I:/2022/MsCOCO_dataset/

TestDataset:
  !ImageFolder
    image_dir: Test
    anno_path: I:/2022/MsCOCO_dataset/Annotation/Test.json # also support txt (like VOC's label_list.txt)
    dataset_dir: I:/2022/MsCOCO_dataset/ # if set, anno_path will be 'dataset_dir/anno_path'

```
```

**Comment by nemonameless** [comment]
报bug请按[模板](https://github.com/PaddlePaddle/PaddleDetection/issues/new?assignees=&labels=type%2Fbug-report%2Cstatus%2Fnew-issue&template=1_bug-report.yml)提问谢谢，自定义数据集请先自查制作和可视化gt，确保没问题后再训练。
