### ISSUE TITLE
跨镜头目标追踪，如何接入rtsp 视频流

### ISSUE THREAD

**Issue by llaidl** [PaddlePaddle/PaddleDetection#6973]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

例子里面只能配置多个视频文件，请问如何接入多个视频流

**Comment by zhiboniu** [comment]
目前的跨镜跟踪不支持在线实时的跟踪，所以对于视频流方式还有些问题

**Comment by YaoOOoooolin** [comment]
> 



> 目前的跨镜跟踪不支持在线实时的跟踪，所以对于视频流方式还有些问题

您好，请问识别摔倒可以用摄像头了吗？我现在开启摄像头会报错
Traceback (most recent call last):
  File "C:\Users\13708\PaddleDetection\deploy\pipeline\pipeline.py", line 1103, in <module>
    main()
  File "C:\Users\13708\PaddleDetection\deploy\pipeline\pipeline.py", line 1088, in main
    pipeline = Pipeline(FLAGS, cfg)
  File "C:\Users\13708\PaddleDetection\deploy\pipeline\pipeline.py", line 89, in __init__
    self.predictor.set_file_name(self.input)
  File "C:\Users\13708\PaddleDetection\deploy\pipeline\pipeline.py", line 476, in set_file_name
    self.file_name = os.path.split(path)[-1]
  File "C:\Users\13708\AppData\Local\Programs\Python\Python39\lib\ntpath.py", line 185, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not int
