### ISSUE TITLE
训练时报错

### ISSUE THREAD

**Issue by rsj123** [PaddlePaddle/PaddleDetection#6974]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training

### Bug描述 Describe the Bug

```
Traceback (most recent call last):
  File "/home/aistudio/PaddleDetection/tools/train.py", line 172, in <module>
    main()
  File "/home/aistudio/PaddleDetection/tools/train.py", line 168, in main
    run(FLAGS, cfg)
  File "/home/aistudio/PaddleDetection/tools/train.py", line 123, in run
    trainer = Trainer(cfg, mode='train')
  File "/home/aistudio/PaddleDetection/ppdet/engine/trainer.py", line 109, in __init__
    self.model = create(cfg.architecture)
  File "/home/aistudio/PaddleDetection/ppdet/core/workspace.py", line 256, in create
    if 'name' not in target_key.keys():
AttributeError: 'SchemaValue' object has no attribute 'keys'
```

### 复现环境 Environment

- PaddlePaddle: 2.3.2
- PaddleDetection: 2.5

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by ghostxsl** [comment]
具体运行的命令是什么？有自己改动过什么吗？

**Comment by rsj123** [comment]
已解决，配置文件有误
