### ISSUE TITLE
COCO数据集问题,数据集是PaddleX转换的

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleDetection#6982]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

```
(PaddleDetection) PS I:\Paddle\PaddleDetection> python tools/train.py -c  configs\mask_rcnn\mask_rcnn_r50_vd_fpn_2x_coco.yml
[09/20 19:46:36] ppdet.utils.download WARNING: Config annotation I:\dataset_MSCOCO/train.json is not a file, dataset config is not valid
[09/20 19:46:36] ppdet.utils.download INFO: Dataset I:\dataset_MSCOCO is not valid for reason above, try searching C:\Users\Intsoft/.cache/paddle/dataset or downloading dataset...
Traceback (most recent call last):
  File "tools/train.py", line 172, in <module>
    main()
  File "tools/train.py", line 168, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 123, in run
    trainer = Trainer(cfg, mode='train')
  File "I:\Paddle\PaddleDetection\ppdet\engine\trainer.py", line 94, in __init__
    self.loader = create('{}Reader'.format(capital_mode))(
  File "I:\Paddle\PaddleDetection\ppdet\data\reader.py", line 162, in __call__
    self.dataset.check_or_download_dataset()
  File "I:\Paddle\PaddleDetection\ppdet\data\source\dataset.py", line 99, in check_or_download_dataset
    self.dataset_dir = get_dataset_path(self.dataset_dir, self.anno_path,
  File "I:\Paddle\PaddleDetection\ppdet\utils\download.py", line 225, in get_dataset_path
    raise ValueError(
ValueError: Dataset I:/dataset_MSCOCO/ is not valid and cannot parse dataset type '' for automaticly downloading, which only supports 'voc' , 'coco', 'wider_face', 'fruit', 'roadsign_voc' and 'mot' currently

```

```
metric: COCO
num_classes: 1

TrainDataset:
  !COCODataSet
    image_dir: I:/dataset_MSCOCO/JPEGImages/
    anno_path: I:/dataset_MSCOCO/train.json
    dataset_dir: I:/dataset_MSCOCO/
    data_fields: ['image', 'gt_bbox', 'gt_class', 'gt_poly', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: I:/dataset_MSCOCO/JPEGImages/
    anno_path: I:/dataset_MSCOCO/val.json
    dataset_dir: I:/dataset_MSCOCO/

TestDataset:
  !ImageFolder
    anno_path: I:/dataset_MSCOCO/test.json
    dataset_dir: I:/dataset_MSCOCO/

```
PaddleX 转换为 coco 数据集  实例分割用

数据集结构：
-- JPEGImages
- train.json
- val.json
- test.json

```

{"annotations": [{"segmentation": [[482.60533065742595, 412.46818429506624, 486.5735846256799, 385.48405731093925, 482.60533065742595, 331.11897794585985, 469.11326716536246, 288.6586604855424, 447.2878703399657, 263.261835088717, 438.95453700663234]],
 "iscrowd": 0, "image_id": 2160, "bbox": [257.0, 367.0, 451.0, 119.0], "area": 53669.0, "category_id": 1, "id": 2800}], "images": [{"height": 1024, "width": 1024, "id": 3100, "file_name": "MMfg_278_9.jpg"}, {"height": 601, "width": 1024, "id": 3584, "file_name": "MMfg_46_12.jpg"}, {"height": 1365, "width": 2048, "id": 1096, "file_name": "AAImage20220624162133367_5.jpg"}, {"height": 682, "width": 1024, "id": 2775, "file_name": "MMfg_256_4.jpg"}, {"height": 682, "width": 1024, "id": 1817, "file_name": "MMfg_175_6.jpg"}, {"height": 601, "width": 1024, "id": 3473, "file_name": "MMfg_34_20.jpg"}, {"height": 1024, "width": 1024, "id": 2953, "file_name": "MMfg_269_20.jpg"}, {"height": 769, "width": 1024, "id": 3817, "file_name": "MMfg_86_6.jpg"}, {"height": 769, "width": 1024, "id": 3806, "file_name": "MMfg_86_14.jpg"}, {"height": 601, "width": 1024, "id": 3466, "file_name": "MMfg_34_14.jpg"}, {"height": 682, "width": 1024, "id": 2200, "file_name": "MMfg_199_9.jpg"}, {"height": 261, "width": 1024, "id": 1305, "file_name": "MMfg_113_13.jpg"}, {"height": 601, "width": 1024, "id": 1724, "file_name": "MMfg_16_12.jpg"}, {"height": 882, "width": 1024, "id": 3123, "file_name": "MMfg_280_11.jpg"}, {"height": 682, "width": 1024, "id": 2840, "file_name": "MMfg_260_9.jpg"}, {"height": 970, "width": 1652, "id": 145, "file_name": "AA09MM44_13.jpg"}, {"height": 682, "width": 1024, "id": 1642, "file_name": "MMfg_166_10.jpg"}, {"height": 261, "width": 1024, "id": 1301, "file_name": "MMfg_113_1.jpg"}, {"height": 970, "width": 1652, "id": 557, "file_name": "AA09MM73_6.jpg"}, {"height": 705, "width": 1024, "id": 2997, "file_name": "MMfg_270_6.jpg"}, {"height": 682, "width": 1024, "id": 1905, "file_name": "MMfg_180_13.jpg"}, {"height": 769, "width": 1024, "id": 3721, "file_name": "MMfg_69_1.jpg"}, {"height": 1094, "width": 1642, "id": 3913, "file_name": "MM_16_A_20.jpg"}, {"height": 682, "width": 1024, "id": 2047, "file_name": "MMfg_191_15.jpg"}, {"height": 682, "width": 1024, "id": 2445, "file_name": "MMfg_228_13.jpg"}, {"height": 970, "width": 1652, "id": 100, "file_name": "AA09MM40_9.jpg"}, {"height": 682, "width": 1024, "id": 2148, "file_name": "MMfg_196_16.jpg"}, {"height": 970, "width": 1652, "id": 124, "file_name": "AA09MM43_12.jpg"}, {"height": 601, "width": 1024, "id": 1726, "file_name": "MMfg_16_14.jpg"}, {"height": 970, "width": 1652, "id": 516, "file_name": "AA09MM71_5.jpg"}, {"height": 682, "width": 1024, "id": 2117, "file_name": "MMfg_194_6.jpg"}, {"height": 970, "width": 1652, "id": 202, "file_name": "AA09MM47_10.jpg"}, {"height": 682, "width": 1024, "id": 2521, "file_name": "MMfg_234_1.jpg"}, {"height": 682, "width": 1024, "id": 2653, "file_name": "MMfg_249_20.jpg"}, {"height": 970, "width": 1652, "id": 206, "file_name": "AA09MM47_14.jpg"}, {"height": 601, "width": 1024, "id": 1299, "file_name": "MMfg_10_8.jpg"}, {"height": 1365, "width": 2048, "id": 817, "file_name": "AAImage20220624161223271_6.jpg"}, {"height": 682, "width": 1024, "id": 3020, "file_name": "MMfg_271_9.jpg"}, {"height": 601, "width": 1024, "id": 1732, "file_name": "MMfg_16_2.jpg"}, {"height": 970, "width": 1652, "id": 233, "file_name": "AA09MM48_20.jpg"}, {"height": 682, "width": 1024, "id": 2748, "file_name": "MMfg_255_16.jpg"}, {"height": 682, "width": 1024, "id": 2712, "file_name": "MMfg_253_2.jpg"}, {"height": 682, "width": 1024, "id": 2554, "file_name": "MMfg_236_3.jpg"}, {"height": 970, "width": 1652, "id": 259, "file_name": "AA09MM49_8.jpg"}, {"height": 768, "width": 1024, "id": 3232, "file_name": "MMfg_286_2.jpg"}, {"height": 601, "width": 1024, "id": 3440, "file_name": "MMfg_321_9.jpg"}, {"height": 1365, "width": 2048, "id": 1164, "file_name": "AAImage20220624162603583_12.jpg"}, {"height": 716, "width": 1024, "id": 3021, "file_name": "MMfg_273_1.jpg"}, {"height": 970, "width": 1652, "id": 389, "file_name": "AA09MM60_17.jpg"}, {"height": 682, "width": 1024, "id": 3001, "file_name": "MMfg_271_1.jpg"}, {"height": 769, "width": 1024, "id": 3728, "file_name": "MMfg_69_16.jpg"}, {"height": 970, "width": 1652, "id": 86, "file_name": "AA09MM40_14.jpg"}, {"height": 1024, "width": 1024, "id": 3281, "file_name": "MMfg_295_1.jpg"}, {"height": 601, "width": 1024, "id": 3480, "file_name": "MMfg_34_9.jpg"}, {"height": 682, "width": 1024, "id": 1825, "file_name": "MMfg_176_13.jpg"}, {"height": 601, "width": 1024, "id": 3571, "file_name": "MMfg_40_19.jpg"}, {"height": 970, "width": 1652, "id": 16, "file_name": "AA09MM100_5.jpg"}, {"height": 682, "width": 1024, "id": 2284, "file_name": "MMfg_210_12.jpg"}, {"height": 1365, "width": 2048, "id": 1029, "file_name": "AAImage20220624161632471_17.jpg"}, {"height": 601, "width": 1024, "id": 1328, "file_name": "MMfg_11_16.jpg"}, {"height": 682, "width": 1024, "id": 1610, "file_name": "MMfg_164_18.jpg"}, {"height": 601, "width": 1024, "id": 2964, "file_name": "MMfg_26_12.jpg"}, {"height": 682, "width": 1024, "id": 2274, "file_name": "MMfg_204_3.jpg"}, {"height": 601, "width": 1024, "id": 1454, "file_name": "MMfg_14_3.jpg"}, {"height": 682, "width": 1024, "id": 1865, "file_name": "MMfg_178_13.jpg"}, {"height": 1365, "width": 2048, "id": 1051, "file_name": "AAImage20220624161650631_19.jpg"}, 
{"height": 970, "width": 1652, "id": 531, "file_name": "AA09MM72_19.jpg"}, {"height": 601, "width": 1024, "id": 3590, "file_name": "MMfg_46_18.jpg"}, {"height": 970, "width": 1652, "id": 551, "file_name": "AA09MM73_19.jpg"}, {"height": 601, "width": 1024, "id": 3631, "file_name": "MMfg_4_19.jpg"}, 
{"height": 1024, "width": 1024, "id": 1492, "file_name": "MMfg_154_2.jpg"},  {"height": 682, "width": 1024, "id": 2160, "file_name": "MMfg_196_9.jpg"}], 
"categories": [{"supercategory": "component", "id": 1, "name": "MM"}]}
```

**Comment by monkeycc** [comment]
路径错误
