### ISSUE TITLE
autoaugment算子疑似存在问题

### ISSUE THREAD

**Issue by DietDietDiet** [PaddlePaddle/PaddleDetection#7019]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

DataProcess

### Bug描述 Describe the Bug

报错代码如下：
fail to map sample transform [AutoAugment_e4cecf] with error: index can't contain negative values and stack:
Traceback (most recent call last):
  File "/home/vis/zhaoyilin/code/01_work/01_weizhang_detection/PaddleDetection/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/home/vis/zhaoyilin/code/01_work/01_weizhang_detection/PaddleDetection/ppdet/data/transform/operators.py", line 105, in __call__
    sample = self.apply(sample, context)
  File "/home/vis/zhaoyilin/code/01_work/01_weizhang_detection/PaddleDetection/ppdet/data/transform/operators.py", line 601, in apply
    self.autoaug_type)
  File "/home/vis/zhaoyilin/code/01_work/01_weizhang_detection/PaddleDetection/ppdet/data/transform/autoaugment_utils.py", line 1586, in distort_image_with_autoaugment
    augmentation_hparams)
  File "/home/vis/zhaoyilin/code/01_work/01_weizhang_detection/PaddleDetection/ppdet/data/transform/autoaugment_utils.py", line 1548, in build_and_apply_nas_policy
    tf_policies, image, bboxes)
  File "/home/vis/zhaoyilin/code/01_work/01_weizhang_detection/PaddleDetection/ppdet/data/transform/autoaugment_utils.py", line 1496, in select_and_apply_random_policy
    image, bboxes = policy(image, bboxes)
  File "/home/vis/zhaoyilin/code/01_work/01_weizhang_detection/PaddleDetection/ppdet/data/transform/autoaugment_utils.py", line 1540, in final_policy
    prob, bboxes_)
  File "/home/vis/zhaoyilin/code/01_work/01_weizhang_detection/PaddleDetection/ppdet/data/transform/autoaugment_utils.py", line 1484, in _apply_func_with_prob
    augmented_image, augmented_bboxes = func(image, bboxes, *args)
  File "/home/vis/zhaoyilin/code/01_work/01_weizhang_detection/PaddleDetection/ppdet/data/transform/autoaugment_utils.py", line 747, in translate_y_only_bboxes
    image, bboxes, prob, translate_y, func_changes_bbox, pixels, replace)
  File "/home/vis/zhaoyilin/code/01_work/01_weizhang_detection/PaddleDetection/ppdet/data/transform/autoaugment_utils.py", line 706, in _apply_multi_bbox_augmentation_wrapper
    new_image, new_bboxes, prob, aug_func, func_changes_bbox, *args)
  File "/home/vis/zhaoyilin/code/01_work/01_weizhang_detection/PaddleDetection/ppdet/data/transform/autoaugment_utils.py", line 687, in _apply_multi_bbox_augmentation
    idx, (image, new_bboxes) = body(idx, (image, new_bboxes))
  File "/home/vis/zhaoyilin/code/01_work/01_weizhang_detection/PaddleDetection/ppdet/data/transform/autoaugment_utils.py", line 685, in <lambda>
    _images_and_bboxes[1])]
  File "/home/vis/zhaoyilin/code/01_work/01_weizhang_detection/PaddleDetection/ppdet/data/transform/autoaugment_utils.py", line 655, in <lambda>
    wrapped_aug_func = lambda _image, bbox, _new_bboxes: _apply_bbox_augmentation_wrapper(_image, bbox, _new_bboxes, prob, aug_func, func_changes_bbox, *args)
  File "/home/vis/zhaoyilin/code/01_work/01_weizhang_detection/PaddleDetection/ppdet/data/transform/autoaugment_utils.py", line 611, in _apply_bbox_augmentation_wrapper
    augmentation_func, *args)
  File "/home/vis/zhaoyilin/code/01_work/01_weizhang_detection/PaddleDetection/ppdet/data/transform/autoaugment_utils.py", line 543, in _apply_bbox_augmentation
    constant_values=1)
  File "<__array_function__ internals>", line 6, in pad
  File "/home/vis/zhaoyilin/anaconda3/envs/paddle2.3/lib/python3.7/site-packages/numpy/lib/arraypad.py", line 743, in pad
    pad_width = _as_pairs(pad_width, array.ndim, as_index=True)
  File "/home/vis/zhaoyilin/anaconda3/envs/paddle2.3/lib/python3.7/site-packages/numpy/lib/arraypad.py", line 514, in _as_pairs
    raise ValueError("index can't contain negative values")
ValueError: index can't contain negative values

### 复现环境 Environment

paddle 2.3.1
release 2.4

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by wangxinxin08** [comment]
你可以在相关的报错位置通过print的方式定位下问题
