### ISSUE TITLE
【PP-YOLOE速度测试】设置exclude_nms=True后推理报错

### ISSUE THREAD

**Issue by yunxi1** [PaddlePaddle/PaddleDetection#7025]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

命令：
python tools/export_model.py -c configs/ppyoloe/ppyoloe_plus_crn_s_80e_coco.yml -o weights=ppyoloe_plus_crn_s_80e_coco.pdparams exclude_nms=True

CUDA_VISIBLE_DEVICES=0 python deploy/python/infer.py --model_dir=output_inference/ppyoloe_plus_crn_s_80e_coco --run_mode=paddle --device=gpu --run_benchmark=True --image_dir=/coco2017_yolo/images/val2017

报错信息：
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

完整日志：
-----------  Running Arguments -----------
action_file: None
batch_size: 1
camera_id: -1
combine_method: nms
cpu_threads: 1
device: gpu
enable_mkldnn: False
enable_mkldnn_bfloat16: False
image_dir: /home/ma-user/work/coco2017_yolo/images/val2017/
image_file: None
match_metric: ios
match_threshold: 0.6
model_dir: output_inference/ppyoloe_plus_crn_s_80e_coco
output_dir: output
overlap_ratio: [0.25, 0.25]
random_pad: False
reid_batch_size: 50
reid_model_dir: None
run_benchmark: True
run_mode: paddle
save_images: True
save_mot_txt_per_img: False
save_mot_txts: False
save_results: False
scaled: False
slice_infer: False
slice_size: [640, 640]
threshold: 0.5
tracker_config: None
trt_calib_mode: False
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
use_coco_category: False
use_dark: True
use_gpu: False
video_file: None
window_size: 50
------------------------------------------
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order: 
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
Found 5000 inference images in total.
Traceback (most recent call last):
  File "deploy/python/infer.py", line 1031, in <module>
    main()
  File "deploy/python/infer.py", line 1004, in main
    save_results=FLAGS.save_results)
  File "deploy/python/infer.py", line 371, in predict_image
    result_warmup = self.postprocess(inputs, result)  # warmup
  File "deploy/python/infer.py", line 155, in postprocess
    if sum(np_boxes_num) <= 0:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by ghostxsl** [comment]
https://github.com/PaddlePaddle/PaddleDetection/pull/7028
问题已修复，请使用最新develop分支试一下～

**Comment by yunxi1** [comment]
可以work了，但是使用v100*1 推理了coco val 花费了一个多小时好夸张啊，一般不是几十秒吗？这是什么原因导致的呢？
虽然结果显示推理时间是5.7ms

2022-09-27 16:27:15,752 - benchmark_utils - INFO - Paddle Inference benchmark log will be saved to /home/ma-user/work/PaddleDetection-release-2.5/deploy/python/../../output/ppyoloe_plus_crn_s_80e_coco.log
2022-09-27 16:27:15,752 - benchmark_utils - INFO - 

2022-09-27 16:27:15,753 - benchmark_utils - INFO - ---------------------- Paddle info ----------------------
2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] paddle_version: 2.2.2
2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] paddle_commit: b031c389938bfa15e15bb20494c76f86289d77b0
2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] paddle_branch: HEAD
2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] log_api_version: 1.0.3
2022-09-27 16:27:15,753 - benchmark_utils - INFO - ----------------------- Conf info -----------------------
2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] runtime_device: gpu
2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] ir_optim: True
2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] enable_memory_optim: True
2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] enable_tensorrt: False
2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] enable_mkldnn: False
2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] cpu_math_library_num_threads: 1
2022-09-27 16:27:15,753 - benchmark_utils - INFO - ----------------------- Model info ----------------------
2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] model_name: ppyoloe_plus_crn_s_80e_coco
2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] precision: paddle
2022-09-27 16:27:15,753 - benchmark_utils - INFO - ----------------------- Data info -----------------------
2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] batch_size: 1
2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] input_shape: dynamic_shape
2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] data_num: 5000
2022-09-27 16:27:15,753 - benchmark_utils - INFO - ----------------------- Perf info -----------------------
2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] cpu_rss(MB): 9060, cpu_vms: 0, cpu_shared_mb: 0, cpu_dirty_mb: 0, cpu_util: 0%
2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] gpu_rss(MB): 1185, gpu_util: 9.23%, gpu_mem_util: 0%
2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] total time spent(s): 88.794
2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] preprocess_time(ms): 11.8, inference_time(ms): 5.7, postprocess_time(ms): 0.3

**Comment by ghostxsl** [comment]
> 可以work了，但是使用v100*1 推理了coco val 花费了一个多小时好夸张啊，一般不是几十秒吗？这是什么原因导致的呢？ 虽然结果显示推理时间是5.7ms
> 
> 2022-09-27 16:27:15,752 - benchmark_utils - INFO - Paddle Inference benchmark log will be saved to /home/ma-user/work/PaddleDetection-release-2.5/deploy/python/../../output/ppyoloe_plus_crn_s_80e_coco.log 2022-09-27 16:27:15,752 - benchmark_utils - INFO -
> 
> 2022-09-27 16:27:15,753 - benchmark_utils - INFO - ---------------------- Paddle info ---------------------- 2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] paddle_version: 2.2.2 2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] paddle_commit: [b031c38](https://github.com/PaddlePaddle/PaddleDetection/commit/b031c389938bfa15e15bb20494c76f86289d77b0) 2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] paddle_branch: HEAD 2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] log_api_version: 1.0.3 2022-09-27 16:27:15,753 - benchmark_utils - INFO - ----------------------- Conf info ----------------------- 2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] runtime_device: gpu 2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] ir_optim: True 2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] enable_memory_optim: True 2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] enable_tensorrt: False 2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] enable_mkldnn: False 2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] cpu_math_library_num_threads: 1 2022-09-27 16:27:15,753 - benchmark_utils - INFO - ----------------------- Model info ---------------------- 2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] model_name: ppyoloe_plus_crn_s_80e_coco 2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] precision: paddle 2022-09-27 16:27:15,753 - benchmark_utils - INFO - ----------------------- Data info ----------------------- 2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] batch_size: 1 2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] input_shape: dynamic_shape 2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] data_num: 5000 2022-09-27 16:27:15,753 - benchmark_utils - INFO - ----------------------- Perf info ----------------------- 2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] cpu_rss(MB): 9060, cpu_vms: 0, cpu_shared_mb: 0, cpu_dirty_mb: 0, cpu_util: 0% 2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] gpu_rss(MB): 1185, gpu_util: 9.23%, gpu_mem_util: 0% 2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] total time spent(s): 88.794 2022-09-27 16:27:15,753 - benchmark_utils - INFO - [DET] preprocess_time(ms): 11.8, inference_time(ms): 5.7, postprocess_time(ms): 0.3

你是怎么跑的coco val？命令发一下看看

**Comment by yunxi1** [comment]
按照readme中速度测试的命令分两步
python tools/export_model.py -c configs/ppyoloe/ppyoloe_plus_crn_s_80e_coco.yml -o weights=ppyoloe_plus_crn_s_80e_coco.pdparams exclude_nms=True

CUDA_VISIBLE_DEVICES=0 python deploy/python/infer.py --model_dir=output_inference/ppyoloe_plus_crn_s_80e_coco --run_mode=paddle --device=gpu --run_benchmark=True --image_dir=/coco2017_yolo/images/val2017

**Comment by ghostxsl** [comment]
> 按照readme中速度测试的命令分两步 python tools/export_model.py -c configs/ppyoloe/ppyoloe_plus_crn_s_80e_coco.yml -o weights=ppyoloe_plus_crn_s_80e_coco.pdparams exclude_nms=True
> 
> CUDA_VISIBLE_DEVICES=0 python deploy/python/infer.py --model_dir=output_inference/ppyoloe_plus_crn_s_80e_coco --run_mode=paddle --device=gpu --run_benchmark=True --image_dir=/coco2017_yolo/images/val2017

你如果只是想在coco val数据集上跑出结果计算指标的话，请不要加`--run_benchmark=True`，使用如下命令可以获得coco结果：
`CUDA_VISIBLE_DEVICES=0 python deploy/python/infer.py --model_dir=output_inference/ppyoloe_plus_crn_s_80e_coco --run_mode=paddle --device=gpu --image_dir=/coco2017_yolo/images/val2017 --save_images=False --save_results --use_coco_category`
评估的结果会保存在当前目录`output/bbox.json`
如果想获得coco评估指标，使用上述的json文件+如下命令：
python tools/eval.py -c configs/ppyoloe/ppyoloe_plus_crn_s_80e_coco.yml --json_eval --output_eval=output

命令中添加`--run_benchmark=True`仅仅用来测速，这个参数会run 100次取平均输出推理耗时

**Comment by yunxi1** [comment]
嗯，那应该就是这个参数的原因吧，我确实是为了测速，run100次好狠，
测精度使用了
python tools/eval.py -c configs/ppyoloe/ppyoloe_plus_crn_s_80e_coco.yml -o weights=ppyoloe_plus_crn_s_80e_coco.pdparams

速度还可以。
W0927 16:38:57.494518  9607 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.2, Runtime API Version: 10.2
W0927 16:38:57.504567  9607 device_context.cc:465] device: 0, cuDNN Version: 7.6.
loading annotations into memory...
Done (t=0.55s)
creating index...
index created!
[09/27 16:39:02] ppdet.utils.checkpoint INFO: Finish loading model weights: ppyoloe_plus_crn_s_80e_coco.pdparams
[09/27 16:39:02] ppdet.engine INFO: Eval iter: 0
[09/27 16:39:08] ppdet.engine INFO: Eval iter: 100
[09/27 16:39:14] ppdet.engine INFO: Eval iter: 200
[09/27 16:39:20] ppdet.engine INFO: Eval iter: 300
[09/27 16:39:26] ppdet.engine INFO: Eval iter: 400
[09/27 16:39:31] ppdet.engine INFO: Eval iter: 500
[09/27 16:39:37] ppdet.engine INFO: Eval iter: 600
[09/27 16:39:43] ppdet.engine INFO: Eval iter: 700
[09/27 16:39:49] ppdet.engine INFO: Eval iter: 800
[09/27 16:39:55] ppdet.engine INFO: Eval iter: 900
[09/27 16:40:01] ppdet.engine INFO: Eval iter: 1000
[09/27 16:40:07] ppdet.engine INFO: Eval iter: 1100
[09/27 16:40:13] ppdet.engine INFO: Eval iter: 1200
[09/27 16:40:19] ppdet.engine INFO: Eval iter: 1300
[09/27 16:40:25] ppdet.engine INFO: Eval iter: 1400
[09/27 16:40:31] ppdet.engine INFO: Eval iter: 1500
[09/27 16:40:36] ppdet.engine INFO: Eval iter: 1600
[09/27 16:40:43] ppdet.engine INFO: Eval iter: 1700
[09/27 16:40:49] ppdet.engine INFO: Eval iter: 1800
[09/27 16:40:54] ppdet.engine INFO: Eval iter: 1900
[09/27 16:41:00] ppdet.engine INFO: Eval iter: 2000
[09/27 16:41:06] ppdet.engine INFO: Eval iter: 2100
[09/27 16:41:12] ppdet.engine INFO: Eval iter: 2200
[09/27 16:41:18] ppdet.engine INFO: Eval iter: 2300
[09/27 16:41:24] ppdet.engine INFO: Eval iter: 2400
[09/27 16:41:49] ppdet.metrics.metrics INFO: The bbox result is saved to bbox.json.
loading annotations into memory...
Done (t=0.41s)
creating index...
index created!
[09/27 16:41:50] ppdet.metrics.coco_utils INFO: Start evaluate...
Loading and preparing results...
DONE (t=11.23s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=101.04s).
Accumulating evaluation results...
DONE (t=20.89s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.437
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.606
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.479
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.265
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.475
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.590
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.352
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.590
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.653
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.467
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.715
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.817
[09/27 16:44:06] ppdet.engine INFO: Total sample number: 4952, averge FPS: 33.73444329478612

**Comment by ghostxsl** [comment]
你如果只是测速度的话，命令中就不要指定`--image_dir`，可以指定`--image_file=demo/000000014439.jpg`
如果只是单纯测精度，tools/eval.py确实够用了，但是想用导出模型测精度就只能用刚才说的方法了

**Comment by yunxi1** [comment]
好的，感谢解答！

**Comment by yunxi1** [comment]
最后想请教下 params， flops，fps等参数推理时怎么开启呢？利用推理时间推算fps似乎精度不够，5.7ms只精确到小数点后一位

**Comment by yunxi1** [comment]
> > 按照readme中速度测试的命令分两步 python tools/export_model.py -c configs/ppyoloe/ppyoloe_plus_crn_s_80e_coco.yml -o weights=ppyoloe_plus_crn_s_80e_coco.pdparams exclude_nms=True
> > CUDA_VISIBLE_DEVICES=0 python deploy/python/infer.py --model_dir=output_inference/ppyoloe_plus_crn_s_80e_coco --run_mode=paddle --device=gpu --run_benchmark=True --image_dir=/coco2017_yolo/images/val2017
> 
> 你如果只是想在coco val数据集上跑出结果计算指标的话，请不要加`--run_benchmark=True`，使用如下命令可以获得coco结果： `CUDA_VISIBLE_DEVICES=0 python deploy/python/infer.py --model_dir=output_inference/ppyoloe_plus_crn_s_80e_coco --run_mode=paddle --device=gpu --image_dir=/coco2017_yolo/images/val2017 --save_images=False --save_results --use_coco_category` 评估的结果会保存在当前目录`output/bbox.json` 如果想获得coco评估指标，使用上述的json文件+如下命令： python tools/eval.py -c configs/ppyoloe/ppyoloe_plus_crn_s_80e_coco.yml --json_eval --output_eval=output
> 
> 命令中添加`--run_benchmark=True`仅仅用来测速，这个参数会run 100次取平均输出推理耗时

如果不加`--run_benchmark=True` 将会出现以下错误=，请解决下Bug

Traceback (most recent call last):
  File "deploy/python/infer.py", line 1038, in <module>
    main()
  File "deploy/python/infer.py", line 1011, in main
    save_results=FLAGS.save_results)
  File "deploy/python/infer.py", line 417, in predict_image
    image_list, results, use_coco_category=FLAGS.use_coco_category)
  File "deploy/python/infer.py", line 475, in save_coco_results
    boxes = results['boxes'][idx:idx + box_num].tolist()
TypeError: only integer scalar arrays can be converted to a scalar index

**Comment by ghostxsl** [comment]
> > > 按照readme中速度测试的命令分两步 python tools/export_model.py -c configs/ppyoloe/ppyoloe_plus_crn_s_80e_coco.yml -o weights=ppyoloe_plus_crn_s_80e_coco.pdparams exclude_nms=True
> > > CUDA_VISIBLE_DEVICES=0 python deploy/python/infer.py --model_dir=output_inference/ppyoloe_plus_crn_s_80e_coco --run_mode=paddle --device=gpu --run_benchmark=True --image_dir=/coco2017_yolo/images/val2017
> > 
> > 
> > 你如果只是想在coco val数据集上跑出结果计算指标的话，请不要加`--run_benchmark=True`，使用如下命令可以获得coco结果： `CUDA_VISIBLE_DEVICES=0 python deploy/python/infer.py --model_dir=output_inference/ppyoloe_plus_crn_s_80e_coco --run_mode=paddle --device=gpu --image_dir=/coco2017_yolo/images/val2017 --save_images=False --save_results --use_coco_category` 评估的结果会保存在当前目录`output/bbox.json` 如果想获得coco评估指标，使用上述的json文件+如下命令： python tools/eval.py -c configs/ppyoloe/ppyoloe_plus_crn_s_80e_coco.yml --json_eval --output_eval=output
> > 命令中添加`--run_benchmark=True`仅仅用来测速，这个参数会run 100次取平均输出推理耗时
> 
> 如果不加`--run_benchmark=True` 将会出现以下错误=，请解决下Bug
> 
> Traceback (most recent call last): File "deploy/python/infer.py", line 1038, in main() File "deploy/python/infer.py", line 1011, in main save_results=FLAGS.save_results) File "deploy/python/infer.py", line 417, in predict_image image_list, results, use_coco_category=FLAGS.use_coco_category) File "deploy/python/infer.py", line 475, in save_coco_results boxes = results['boxes'][idx:idx + box_num].tolist() TypeError: only integer scalar arrays can be converted to a scalar index

这个不是bug，你如果导出模型的时候加了`exclude_nms=True`参数的话，那么这个模型只能用来测速，不能去掉`--run_benchmark=True`
如果你想推理的话，请重新导出不加`exclude_nms=True`参数的模型

**Comment by yunxi1** [comment]
确实是这样的
