### ISSUE TITLE
onnx infer.py not worked ; request ORT provider

### ISSUE THREAD

**Issue by MyraBaba** [PaddlePaddle/PaddleDetection#7034]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

CUDA_VISIBLE_DEVICES=0 python3 deploy/third_engine/onnx/infer.py  --infer_cfg output_inference/ppyoloe_crn_l_80e_sliced_visdrone_640_025/infer_cfg.yml  --onnx_file sliced_visdrone.onnx --image_file demo/000000014439.jpg

"onnxruntime.InferenceSession(..., providers={}, ...)".format(available_providers)
ValueError: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)

### 复现环境 Environment

linux
paddle 2.2
onnxruntime-gpu

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by MyraBaba** [comment]
change to infer.py to : 

    predictor = InferenceSession(FLAGS.onnx_file, providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])
at lien 144

now complains gone.

But there is a new one:

> CUDA_VISIBLE_DEVICES=0 python3 deploy/third_engine/onnx/infer.py  --infer_cfg output_inference/ppyoloe_crn_l_80e_sliced_visdrone_640_025/infer_cfg.yml  --onnx_file sliced_visdrone.onnx --image_file demo/000000014439.jpg
2022-09-27 07:45:57.157955673 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:566 CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements to ensure all dependencies are met.
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order:
--transform op: Resize
--transform op: Permute
--------------------------------------------
Traceback (most recent call last):
  File "deploy/third_engine/onnx/infer.py", line 148, in <module>
    predict_image(infer_config, predictor, img_list)
  File "deploy/third_engine/onnx/infer.py", line 126, in predict_image
    outputs = predictor.run(output_names=None, input_feed=inputs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(uint8)) , expected: (tensor(float))

**Comment by MyraBaba** [comment]
changed infer.py line 125 to 👍 
`        inputs['image'] = inputs['image'].astype(np.float32)
`

now its inferring .

But I didnt see the the class output ? it gives the bbox only??

**Comment by lyuwenyu** [comment]
you can `print` all outputs and check the output `shape`

**Comment by MyraBaba** [comment]
shape is 6 

where s the : 
labels & confidence score ?

**Comment by MyraBaba** [comment]
Is 1st one is label and the second one is the score ?



<img width="1038" alt="Screen Shot 2022-09-27 at 11 32 27" src="https://user-images.githubusercontent.com/17505439/192475707-2a397f44-087a-47fd-bd87-2a310f809d9b.png">
