### ISSUE TITLE
IndexError in running tracking demo

### ISSUE THREAD

**Issue by Hyperjunct** [PaddlePaddle/PaddleDetection#7046]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

start tracking seq: c003
Tracking frame: 0
Traceback (most recent call last):
  File "D:\THICV\Project\PaddleDetection\deploy\pptracking\python\mot_sde_infer.py", line 882, in <module>
    main()
  File "D:\THICV\Project\PaddleDetection\deploy\pptracking\python\mot_sde_infer.py", line 851, in main
    detector.predict_mtmct(FLAGS.mtmct_dir, mtmct_cfg)
  File "D:\THICV\Project\PaddleDetection\deploy\pptracking\python\mot_sde_infer.py", line 761, in predict_mtmct
    mot_features_dict = self.predict_image(
  File "D:\THICV\Project\PaddleDetection\deploy\pptracking\python\mot_sde_infer.py", line 488, in predict_image
    det_result = self.postprocess(inputs, result)
  File "D:\THICV\Project\PaddleDetection\deploy\pptracking\python\mot_sde_infer.py", line 238, in postprocess
    result['boxes'] = result['boxes'][keep_idx]
IndexError: boolean index did not match indexed array along dimension 1; dimension is 6400 but corresponding boolean dimension is 80

There is an IndexError that the boolean index didn't match.
I don't know how to fix this index bug.

**Comment by nemonameless** [comment]
Please report the bug  according to the template, thanks.
https://github.com/PaddlePaddle/PaddleDetection/issues/new?assignees=&labels=type%2Fbug-report%2Cstatus%2Fnew-issue&template=1_bug-report.yml
