### ISSUE TITLE
根据paddle detection的faster rcnn里面的文件修改训练voc数据集报错

### ISSUE THREAD

**Issue by xxPete** [PaddlePaddle/PaddleDetection#7066]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

- 我想使用voc格式的数据集跑faster rcnn测试，只把coco数据集改成了voc数据集，其他没动，无法运行，也没见过这种报错
### 我的训练配置文件
```python
_BASE_: [
  'coco_demo.yml',
]
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_vd_pretrained.pdparams
weights: output/faster_rcnn_r50_vd_fpn_1x_coco/model_final

ResNet:
  # index 0 stands for res2
  depth: 50
  variant: d
  norm_type: bn
  freeze_at: 0
  return_idx: [0,1,2,3]
  num_stages: 4
```
### coco_demo的配置文件
```python
_BASE_: [
  '../datasets/voc_demo.yml',
  '../runtime.yml',
  '_base_/optimizer_1x.yml',
  '_base_/faster_rcnn_r50.yml',
  '_base_/faster_reader.yml',
]
- weights: output/faster_rcnn_r50_1x_coco/model_final
```
### voc_demo的配置文件
```python
metric: VOC
map_type: 11point
num_classes: 6

TrainDataset:
  !VOCDataSet
    dataset_dir: dataset/coco_demo
    anno_path: train_list.txt
    label_list: labels.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

EvalDataset:
  !VOCDataSet
    dataset_dir: dataset/coco_demo
    anno_path: val_list.txt
    label_list: labels.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

TestDataset:
  !ImageFolder
    anno_path: dataset/coco_demo/val_list.txt
```
- 这个数据集跑voc的是没问题的，没用过coco数据集的配置，还有什么地方需要修改的吗，我用官方的x2coco把voc格式的数据集转成coco的也不对
### 报错信息如下
```python
W1008 11:02:16.883631  3996 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.6
W1008 11:02:16.888631  3996 gpu_resources.cc:91] device: 0, cuDNN Version: 8.1.
Traceback (most recent call last):
  File ".\tools\train.py", line 172, in <module>
    main()
  File ".\tools\train.py", line 168, in main
    run(FLAGS, cfg)
  File ".\tools\train.py", line 129, in run
    trainer.load_weights(cfg.pretrain_weights)
  File "D:\Project\paddle\PaddleDetection\ppdet\engine\trainer.py", line 375, in load_weights
    load_pretrain_weight(self.model, weights)
  File "D:\Project\paddle\PaddleDetection\ppdet\utils\checkpoint.py", line 215, in load_pretrain_weight
    param_state_dict = match_state_dict(model_dict, param_state_dict)
  File "D:\Project\paddle\PaddleDetection\ppdet\utils\checkpoint.py", line 194, in match_state_dict
    weight_key]))
ValueError: Ambiguity weight backbone.res5.res5a.branch2a.conv.weight loaded, it matches at least bbox_head.head.res5.res5a.branch2a.conv.weight and backbone.res5.res5a.branch2a.conv.weight in the model
```
### 数据集的配置文件如下
```python
metric: COCO
num_classes: 6

TrainDataset:
  !COCODataSet
    image_dir: JPEGImages
    anno_path: train.json
    dataset_dir: dataset/coco_demo
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: JPEGImages
    anno_path: val.json
    dataset_dir: dataset/coco_demo

TestDataset:
  !ImageFolder
    anno_path: val.json # also support txt (like VOC's label_list.txt)
    dataset_dir: dataset/coco_demo # if set, anno_path will be 'dataset_dir/anno_path'
```
- coco_demo数据集的格式如下
- --coco_demo
- ----Annotations
- ----JPEGImages
- ----train.json
- ----val.json
- json内容中的file_name为'{"file_name": "_202207261730340524.jpg", "height": 1024.0, "width": 2048.0, "id": 0}',我不清楚是不是路径不对，除了数据集的地方进行修改，其他的配置文件为faster_rcnn_r34_fpn_1x_coco.yml，只修改了datasets里的配置文件，报错信息为:
```python
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
W1008 11:08:24.253907   356 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.6
W1008 11:08:24.258906   356 gpu_resources.cc:91] device: 0, cuDNN Version: 8.1.
[10/08 11:08:25] ppdet.utils.checkpoint INFO: Finish loading model weights: C:\Users\ps/.cache/paddle/weights\ResNet34_pretrained.pdparams
W1008 11:08:25.682456   356 gpu_resources.cc:201] WARNING: device: . The installed Paddle is compiled with CUDNN 8.4, but CUDNN version in your machine is 8.1, which may cause serious incompatible bug. Please recompile or reinstall 
Paddle with compatible CUDNN version.
Traceback (most recent call last):
  File ".\tools\train.py", line 172, in <module>
    main()
  File ".\tools\train.py", line 168, in main
    run(FLAGS, cfg)
  File ".\tools\train.py", line 132, in run
    trainer.train(FLAGS.eval)
  File "D:\Project\paddle\PaddleDetection\ppdet\engine\trainer.py", line 506, in train
    outputs = model(data)
  File "D:\Project\paddle\PaddleDetection\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Project\paddle\PaddleDetection\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Project\paddle\PaddleDetection\ppdet\modeling\architectures\meta_arch.py", line 59, in forward
    out = self.get_loss()
  File "D:\Project\paddle\PaddleDetection\ppdet\modeling\architectures\faster_rcnn.py", line 95, in get_loss
    rpn_loss, bbox_loss = self._forward()
  File "D:\Project\paddle\PaddleDetection\ppdet\modeling\architectures\faster_rcnn.py", line 76, in _forward
    rois, rois_num, rpn_loss = self.rpn_head(body_feats, self.inputs)
  File "D:\Project\paddle\PaddleDetection\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Project\paddle\PaddleDetection\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Project\paddle\PaddleDetection\ppdet\modeling\proposal_generator\rpn_head.py", line 143, in forward
    loss = self.get_loss(scores, deltas, anchors, inputs)
  File "D:\Project\paddle\PaddleDetection\ppdet\modeling\proposal_generator\rpn_head.py", line 281, in get_loss
    pos_ind = paddle.nonzero(pos_mask)
  File "D:\Project\paddle\PaddleDetection\venv\lib\site-packages\paddle\tensor\search.py", line 402, in nonzero
    outs = _C_ops.where_index(x)
OSError: (External) CUDA error(700), an illegal memory access was encountered.
  [Hint: 'cudaErrorIllegalAddress'. The device encountered a load or store instruction on an invalid memory address. This leaves the process in an inconsistentstate and any further CUDA work will return the same error. To continue u
sing CUDA, the process must be terminated and relaunched. ] (at ..\paddle\phi\backends\gpu\cuda\cuda_info.cc:251)
  [operator < where_index > error]
```

**Comment by ghostxsl** [comment]
你是在AI Studio上跑的吗？看报错应该是环境有问题，可以换个环境试试呢

**Comment by xxPete** [comment]
> 你是在AI Studio上跑的吗？看报错应该是环境有问题，可以换个环境试试呢

本地跑的，我感觉也是环境的问题，但是不知道该怎么换，cuda版本换成11.2的吗还是换paddle paddle的版本，我用现在的版本跑voc格式的数据集的检测是没问题的
