### ISSUE TITLE
OSError: (External) CUDA error(700), an illegal memory access was encountered

### ISSUE THREAD

**Issue by xxPete** [PaddlePaddle/PaddleDetection#7068]
### 问题描述 Please describe your issue

- 使用paddle detection，用自己的coco数据集跑faster rcnn模型出现的问题，只有使用gpu的时候出现该报错，cpu下可以正常训练
### 报错信息
```python
(venv) PS D:\Project\paddle\PaddleDetection> python .\tools\train.py -c .\configs\faster_rcnn\faster_rcnn_r34_fpn_1x_coco.yml --eval
Warning: Unable to use JDE/FairMOT/ByteTrack, please install lap, for example: `pip install lap`, see https://github.com/gatagat/lap
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
W1008 14:41:32.427362 11228 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.6
W1008 14:41:32.430361 11228 gpu_resources.cc:91] device: 0, cuDNN Version: 8.6.
[10/08 14:41:33] ppdet.utils.checkpoint INFO: Finish loading model weights: C:\Users\ps/.cache/paddle/weights\ResNet34_pretrained.pdparams
Traceback (most recent call last):
  File ".\tools\train.py", line 172, in <module>
    main()
  File ".\tools\train.py", line 168, in main
    run(FLAGS, cfg)
  File ".\tools\train.py", line 132, in run
    trainer.train(FLAGS.eval)
  File "D:\Project\paddle\PaddleDetection\ppdet\engine\trainer.py", line 506, in train
    outputs = model(data)
  File "D:\Project\paddle\PaddleDetection\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Project\paddle\PaddleDetection\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Project\paddle\PaddleDetection\ppdet\modeling\architectures\meta_arch.py", line 59, in forward
    out = self.get_loss()
  File "D:\Project\paddle\PaddleDetection\ppdet\modeling\architectures\faster_rcnn.py", line 95, in get_loss
    rpn_loss, bbox_loss = self._forward()
  File "D:\Project\paddle\PaddleDetection\ppdet\modeling\architectures\faster_rcnn.py", line 76, in _forward
    rois, rois_num, rpn_loss = self.rpn_head(body_feats, self.inputs)
  File "D:\Project\paddle\PaddleDetection\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Project\paddle\PaddleDetection\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Project\paddle\PaddleDetection\ppdet\modeling\proposal_generator\rpn_head.py", line 143, in forward
    loss = self.get_loss(scores, deltas, anchors, inputs)
  File "D:\Project\paddle\PaddleDetection\ppdet\modeling\proposal_generator\rpn_head.py", line 281, in get_loss
    pos_ind = paddle.nonzero(pos_mask)
  File "D:\Project\paddle\PaddleDetection\venv\lib\site-packages\paddle\tensor\search.py", line 402, in nonzero
    outs = _C_ops.where_index(x)
OSError: (External) CUDA error(700), an illegal memory access was encountered.
  [Hint: 'cudaErrorIllegalAddress'. The device encountered a load or store instruction on an invalid memory address. This leaves the process in an inconsistentstate and any further CUDA work will return the same error. To continue u
sing CUDA, the process must be terminated and relaunched. ] (at ..\paddle\phi\backends\gpu\cuda\cuda_info.cc:251)
  [operator < where_index > error]
```
### 虚拟环境如下
```python
Package            Version
------------------ -------------
astor              0.8.1
Babel              2.10.3
bce-python-sdk     0.8.74
certifi            2022.9.24
chardet            5.0.0
charset-normalizer 2.1.1
click              8.1.3
colorama           0.4.5
cycler             0.11.0
Cython             0.29.32
decorator          5.1.1
dill               0.3.5.1
filterpy           1.4.5
Flask              2.2.2
Flask-Babel        2.0.0
fonttools          4.37.3
future             0.18.2
idna               3.4
importlib-metadata 4.12.0
itsdangerous       2.1.2
Jinja2             3.1.2
joblib             1.2.0
kiwisolver         1.4.4
lap                0.4.0
MarkupSafe         2.1.1
matplotlib         3.5.3
motmetrics         1.2.5
multiprocess       0.70.13
numpy              1.19.3
opencv-python      4.6.0.66
opt-einsum         3.3.0
packaging          21.3
paddle-bfloat      0.1.7
paddledet          2.5.0
paddlepaddle-gpu   2.3.2.post116
paddleslim         2.1.1
paddlex            2.0.0
pandas             1.3.5
Pillow             9.2.0
pip                22.2.2
protobuf           3.20.0
pyclipper          1.3.0.post3
pycocotools        2.0.5
pycryptodome       3.15.0
pyparsing          3.0.9
python-dateutil    2.8.2
pytz               2022.2.1
PyYAML             6.0
pyzmq              24.0.1
requests           2.28.1
scikit-learn       0.23.2
scipy              1.7.3
setuptools         47.1.0
Shapely            1.8.4
six                1.16.0
sklearn            0.0
terminaltables     3.1.10
threadpoolctl      3.1.0
tqdm               4.64.1
typeguard          2.13.3
typing_extensions  4.3.0
urllib3            1.26.12
visualdl           2.4.1
Werkzeug           2.2.2
xmltodict          0.13.0
zipp               3.8.1
```
- cuda: 11.6 cudnn: 8.6.0

**Comment by zhiboniu** [comment]
先确认下显存有没有满，如果没满的话可以抓一下出错时的pos_mask，然后再Paddle的主repo里给nonzero api提个issue

**Comment by github2016-yuan** [comment]
@zhiboniu @xxPete  same question.
win11 cuda11.2 cudnn 8.2
paddlepaddle-gpu   2.3.2.post112
paddledet 2.4.0 

While training voc dataset,I run into the same quesetion and try to set batch_size = 64/32/16/8/1
My gpu is 3070Ti so it is **not related to gpu memo**.
Someone has solved it?
