### ISSUE TITLE
2.5版本 s2anet训练报错

### ISSUE THREAD

**Issue by mrljwlm** [PaddlePaddle/PaddleDetection#7091]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

2.5版本 s2anet训练报错：

python tools\train.py -c configs\rotate\s2anet\test_s2anet_alignconv_2x_dota.yml --eval  -o use_gpu=true
Warning: Unable to use JDE/FairMOT/ByteTrack, please install lap, for example: `pip install lap`, see https://github.com/gatagat/lap
Warning: Unable to use OC-SORT, please install filterpy, for example: `pip install filterpy`, see https://github.com/rlabbe/filterpy
Warning: Unable to use MOT metric, please install motmetrics, for example: `pip install motmetrics`, see https://github.com/longcw/py-motmetrics
Warning: Unable to use MCMOT metric, please install motmetrics, for example: `pip install motmetrics`, see https://github.com/longcw/py-motmetrics
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
loading annotations into memory...
Done (t=0.30s)
creating index...
index created!
W1010 10:41:12.869786 18520 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.2
W1010 10:41:12.871786 18520 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
[10/10 10:41:14] ppdet.utils.checkpoint INFO: ['backbone.conv1.conv1.conv.weight', 'backbone.conv1.conv1.norm._mean', 'backbone.conv1.conv1.norm._variance', 'backbone.conv1.conv1.norm.bias', 'backbone.conv1.conv1.norm.weight', 'backbone.res3.res3a.short.conv.weight', 'backbone.res3.res3a.short.norm._mean', 'backbone.res3.res3a.short.norm._variance', 'backbone.res3.res3a.short.norm.bias', 'backbone.res3.res3a.short.norm.weight', 'backbone.res4.res4a.short.conv.weight', 'backbone.res4.res4a.short.norm._mean', 'backbone.res4.res4a.short.norm._variance', 'backbone.res4.res4a.short.norm.bias', 'backbone.res4.res4a.short.norm.weight', 'backbone.res5.res5a.short.conv.weight', 'backbone.res5.res5a.short.norm._mean', 'backbone.res5.res5a.short.norm._variance', 'backbone.res5.res5a.short.norm.bias', 'backbone.res5.res5a.short.norm.weight', 's2anet_head.align_conv.bias', 's2anet_head.align_conv.weight'] in pretrained weight is not used in the model, and its will not be loaded
[10/10 10:41:14] ppdet.utils.checkpoint INFO: The shape (15,) in pretrained weight s2anet_head.fam_cls.bias is unmatched with the shape [16] in model s2anet_head.fam_cls.bias. And the weight s2anet_head.fam_cls.bias will not be loaded
[10/10 10:41:14] ppdet.utils.checkpoint INFO: The shape (15, 256, 1, 1) in pretrained weight s2anet_head.fam_cls.weight is unmatched with the shape [16, 256, 1, 1] in model s2anet_head.fam_cls.weight. And the weight s2anet_head.fam_cls.weight will not be loaded
[10/10 10:41:14] ppdet.utils.checkpoint INFO: The shape (15,) in pretrained weight s2anet_head.odm_cls.bias is unmatched with the shape [16] in model s2anet_head.odm_cls.bias. And the weight s2anet_head.odm_cls.bias will not be loaded
[10/10 10:41:14] ppdet.utils.checkpoint INFO: The shape (15, 256, 3, 3) in pretrained weight s2anet_head.odm_cls.weight is unmatched with the shape [16, 256, 3, 3] in model s2anet_head.odm_cls.weight. And the weight s2anet_head.odm_cls.weight will not be loaded
[10/10 10:41:14] ppdet.utils.checkpoint INFO: Finish loading model weights: I:/DeepLearningSystem/PaddleDetection/weights/s2anet_conv_1x_dota.pdparams
Traceback (most recent call last):
  File "I:\DeepLearningSystem\PaddleDetection\tools\train.py", line 172, in <module>
    main()
  File "I:\DeepLearningSystem\PaddleDetection\tools\train.py", line 168, in main
    run(FLAGS, cfg)
  File "I:\DeepLearningSystem\PaddleDetection\tools\train.py", line 132, in run
    trainer.train(FLAGS.eval)
  File "I:\DeepLearningSystem\PaddleDetection\ppdet\engine\trainer.py", line 506, in train
    outputs = model(data)
  File "C:\Program Files\Python\Python39\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\Program Files\Python\Python39\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "I:\DeepLearningSystem\PaddleDetection\ppdet\modeling\architectures\meta_arch.py", line 59, in forward
    out = self.get_loss()
  File "I:\DeepLearningSystem\PaddleDetection\ppdet\modeling\architectures\s2anet.py", line 78, in get_loss
    loss = self._forward()
  File "I:\DeepLearningSystem\PaddleDetection\ppdet\modeling\architectures\s2anet.py", line 62, in _forward
    loss = self.s2anet_head(body_feats, self.inputs)
  File "C:\Program Files\Python\Python39\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\Program Files\Python\Python39\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "I:\DeepLearningSystem\PaddleDetection\ppdet\modeling\heads\s2anet_head.py", line 313, in forward
    return self.get_loss([
  File "I:\DeepLearningSystem\PaddleDetection\ppdet\modeling\heads\s2anet_head.py", line 630, in get_loss
    gt_bboxes = paddle.gather(inputs['gt_rbox'][i], gt_idx).numpy()
OSError: (External) CUDA error(700), an illegal memory access was encountered.
  [Hint: 'cudaErrorIllegalAddress'. The device encountered a load or store instruction on an invalid memory address. This leaves the process in an inconsistentstate and any further CUDA work will return the same error. To continue using CUDA, the process must be terminated and relaunched. ] (at ..\paddle\phi\backends\gpu\cuda\cuda_info.cc:258)

使用DOTA数据集，用[DOTA2COCO](https://github.com/CAPTAIN-WHU/DOTA_devkit/blob/master/DOTA2COCO.py)进行转换
报错信息最后提示的
  File "I:\DeepLearningSystem\PaddleDetection\ppdet\modeling\heads\s2anet_head.py", line 630, in get_loss
    gt_bboxes = paddle.gather(inputs['gt_rbox'][i], gt_idx).numpy()
但是根据 configs\datasets\dota.yml，数据里好像没有'gt_rbox'这一项，dota.yml如下：
```
metric: RBOX
num_classes: 16

TrainDataset:
  !COCODataSet
    image_dir: images/train
    anno_path: labels/train.json
    dataset_dir: F:/DOTA_dataset/data_obb/
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd', 'gt_poly']

EvalDataset:
  !COCODataSet
    image_dir: images/vali
    anno_path: labels/vali.json
    dataset_dir: F:/DOTA_dataset/data_obb/
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd', 'gt_poly']

TestDataset:
  !ImageFolder
    anno_path: labels/vali.json
    dataset_dir: F:/DOTA_dataset/data_obb/
```

请问怎么处理这个报错

**Comment by XYZ-916** [comment]
'gt_rbox'这一项应该是数据预处理部分生成的，并不会体现在配置文件里。

**Comment by mrljwlm** [comment]
> 'gt_rbox'这一项应该是数据预处理部分生成的，并不会体现在配置文件里。

要怎么进行预处理？

**Comment by XYZ-916** [comment]
> 
可以看下这里Poly2RBox类：
https://github.com/PaddlePaddle/PaddleDetection/blob/ede22043927a944bb4cbea0e9455dd9c91b295f0/ppdet/data/transform/rotated_operators.py

另外你的这个错误请关注下index是不是超出范围。

**Comment by wangxinxin08** [comment]
2.5版本s2anet进行了重构，数据预处理也发生了变化，具体可参考https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/configs/rotate/s2anet/_base_/s2anet_reader.yml#L8
