### ISSUE TITLE
Missing `init_anno_cropper` method in `COCODataSet` class

### ISSUE THREAD

**Issue by derrkater** [PaddlePaddle/PaddleDetection#7097]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training

### Bug描述 Describe the Bug

I'm trying default training command for picodet model with a custom coco-format data. It doesn't let me run my data in `COCODataSet` object:

`Traceback (most recent call last):
  File "tools/train.py", line 172, in <module>
    main()
  File "tools/train.py", line 168, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 123, in run
    trainer = Trainer(cfg, mode='train')
  File "/home/PaddleDetection/ppdet/engine/trainer.py", line 191, in __init__
    self._init_callbacks()
  File "/home/PaddleDetection/ppdet/engine/trainer.py", line 203, in _init_callbacks
    self._callbacks.append(SniperProposalsGenerator(self))
  File "/home/PaddleDetection/ppdet/engine/callbacks.py", line 441, in __init__
    self.dataset = self._create_new_dataset(ori_dataset)
  File "/home/PaddleDetection/ppdet/engine/callbacks.py", line 449, in _create_new_dataset
    dataset.init_anno_cropper()
AttributeError: 'COCODataSet' object has no attribute 'init_anno_cropper'`

### 复现环境 Environment

Docker image: registry.baidubce.com/paddlepaddle/paddle:2.3.2-gpu-cuda11.2-cudnn8
local cuda 11.4

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by jerrywgz** [comment]
The log shows that you used save_proposals in your config file, you could just modify the dataset config part based on https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/configs/picodet/picodet_l_320_coco_lcnet.yml

**Comment by derrkater** [comment]
@jerrywgz I've just modified config and used SniperCOCODataSet class to load the data but I'd think that proper behavior would be for COCODataSet to also work. Is it intended that it is missing the aforementioned method - `init_anno_cropper`?
