### ISSUE TITLE
Solov2 在训练的时候没问题，eval的时候fpn报错

### ISSUE THREAD

**Issue by Reatris** [PaddlePaddle/PaddleDetection#7102]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Validation

### Bug描述 Describe the Bug

Solov2 在训练的时候没问题，eval的时候fpn报错

报错情况如下

```
[10/12 14:10:43] ppdet.engine INFO: Epoch: [0] [580/619] learning_rate: 0.005800 loss_ins: 1.680151 loss_cate: 0.601243 loss: 2.251669 eta: 0:09:59 batch_cost: 0.9482 data_cost: 0.0003 ips: 8.4374 images/s
[10/12 14:11:02] ppdet.engine INFO: Epoch: [0] [600/619] learning_rate: 0.006000 loss_ins: 1.559526 loss_cate: 0.581711 loss: 2.123541 eta: 0:09:41 batch_cost: 0.9156 data_cost: 0.0003 ips: 8.7375 images/s
[10/12 14:11:21] utils.checkpoint INFO: Save checkpoint: output/Solov2
loading annotations into memory...
Done (t=1.02s)
creating index...
index created!
loading annotations into memory...
Done (t=0.89s)
creating index...
index created!
Traceback (most recent call last):
  File "train.py", line 93, in <module>
    main()
  File "train.py", line 89, in main
    run(args, cfg)
  File "train.py", line 57, in run
    trainer.train(args.eval)
  File "/home/aistudio/ppdet-solov2/core/trainer.py", line 284, in train
    self._eval_with_loader(self._eval_loader)
  File "/home/aistudio/ppdet-solov2/core/trainer.py", line 347, in _eval_with_loader
    outs = self.model(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/ppdet-solov2/modeling/architectures/solov2.py", line 159, in forward
    self.model_arch()
  File "/home/aistudio/ppdet-solov2/modeling/architectures/solov2.py", line 85, in model_arch
    body_feats = self.neck(body_feats)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/ppdet-solov2/modeling/necks/fpn.py", line 194, in forward
    laterals[lvl - 1] += upsample
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 299, in __impl__
    return math_op(self, other_var, 'axis', axis)
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 256, 32, 49] and the shape of Y = [1, 256, 32, 50]. Received [49] in X is not equal to [50] in Y at i:3.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/phi/kernels/funcs/common_shape.h:84)
  [operator < elementwise_add > error]
aistudio@jupyter-206265-4612726:~/ppdet-solov2$ 
```

这个是我的yml里面reader配置

```
# reader

 {}
  - RandomDistoworker_num: 2
      TrainReader:
        sample_transforms:
            - Decode: { }
              - Poly2Mask:rt: {}
  - RandomCrop: {}
  - RandomResize: {interp: 1,
                     target_size: [[352, 852], [384, 852], [416, 852], [448, 852], [480, 852], [512, 852]],
                     keep_ratio: True}
  - RandomFlip: {}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  - Gt2Solov2Target: {num_grids: [40, 36, 24, 16, 12],
                        scale_ranges: [[1, 96], [48, 192], [96, 384], [192, 768], [384, 2048]],
                        coord_sigma: 0.2}
  batch_size: 8
  shuffle: true
  drop_last: true


EvalReader:
  sample_transforms:
  - Decode: {}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Resize: {interp: 1, target_size: [512, 852], keep_ratio: True}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  batch_size: 1
  shuffle: false
  drop_last: True


TestReader:
  sample_transforms:
  - Decode: {}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Resize: {interp: 1, target_size: [512, 852], keep_ratio: True}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  batch_size: 1
  shuffle: false
  drop_last: True
```

### 复现环境 Environment

-os linux

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by wangxinxin08** [comment]
看起来是纬度不一致导致的，可以在代码中打印下两个相加的tensor的shape

**Comment by Reatris** [comment]
错误信息里面提示确实是不一样，但是我又需要怎么改动呢，我并没有动过源码

**Comment by wangxinxin08** [comment]
先打印下tensor的shape信息定位下问题

**Comment by Reatris** [comment]
```
Done (t=0.55s)
creating index...
index created!
/home/aistudio/ppdet-solov2/data/dataset.py:279: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  if not np.array(box['segmentation']
[10/12 15:33:46] utils.checkpoint INFO: Finish loading model weights: output/Solov2/model_final.pdparams
shape upsample:[1, 256, 32, 50]
shape laterals[lvl - 1]:[1, 256, 32, 49]
Traceback (most recent call last):
  File "eval.py", line 118, in <module>
    main()
  File "eval.py", line 114, in main
    run(args, cfg)
  File "eval.py", line 82, in run
    trainer.evaluate()
  File "/home/aistudio/ppdet-solov2/core/trainer.py", line 375, in evaluate
    self._eval_with_loader(self.loader)
  File "/home/aistudio/ppdet-solov2/core/trainer.py", line 347, in _eval_with_loader
    outs = self.model(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/ppdet-solov2/modeling/architectures/solov2.py", line 159, in forward
    self.model_arch()
  File "/home/aistudio/ppdet-solov2/modeling/architectures/solov2.py", line 85, in model_arch
    body_feats = self.neck(body_feats)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/ppdet-solov2/modeling/necks/fpn.py", line 196, in forward
    laterals[lvl - 1] += upsample
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 299, in __impl__
    return math_op(self, other_var, 'axis', axis)
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 256, 32, 49] and the shape of Y = [1, 256, 32, 50]. Received [49] in X is not equal to [50] in Y at i:3.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/phi/kernels/funcs/common_shape.h:84)
  [operator < elementwise_add > error]
aistudio@jupyter-206265-4612726:~/ppdet-solov2$ 
```

**Comment by Reatris** [comment]
shape 在上面打印出来了

shape upsample:[1, 256, 32, 50]
shape laterals[lvl - 1]:[1, 256, 32, 49]

**Comment by wangxinxin08** [comment]
出现这个问题一般在于输入的图片的宽度或者高度不是32的整数倍，在Reader中已经设置PadBatch为32的整数倍了，你需要看下是不是做了什么改动导致输入的图像不是32的证书倍

**Comment by Reatris** [comment]
可是这个问题在train的时候没有出现，我检查了reader的配置，我即使改变padBatch这个问题也还是出现

**Comment by wangxinxin08** [comment]
你可以打印看下PadBatch之后的输入图像的shape，看下PadBatch是不是没有生效

**Comment by Reatris** [comment]
感谢，解决了，确实是PadBatch没生效(,- _-、)

**Comment by mrljwlm** [comment]
> 实是PadBatch没生效(,- _-、)

我也遇到一样的问题，你是怎么解决的？怎么让PadBatch生效？
