### ISSUE TITLE
python deploy/python/infer.py 预测推理是batchsize 大于1，会报错

### ISSUE THREAD

**Issue by zgsxwsdxg** [PaddlePaddle/PaddleDetection#7131]
### 问题描述 Please describe your issue

python deploy/python/infer.py 预测推理是batchsize 大于1，会报错：如下：
  Running Arguments -----------
action_file: None
batch_size: 1
camera_id: -1
cpu_threads: 1
device: cpu
enable_mkldnn: False
enable_mkldnn_bfloat16: False
image_dir: images
image_file: None
model_dir: weights
output_dir: output
random_pad: False
reid_batch_size: 50
reid_model_dir: None
run_benchmark: False
run_mode: paddle
save_images: False
save_mot_txt_per_img: False
save_mot_txts: False
save_results: False
scaled: False
threshold: 0.5
tracker_config: None
trt_calib_mode: False
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
use_dark: True
use_gpu: False
video_file: None
window_size: 50
------------------------------------------
-----------  Model Configuration -----------
Model Arch: S2ANet
Transform Order:
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--transform op: PadStride
--------------------------------------------
Found 3 inference images in total.
Traceback (most recent call last):
  File ".\infer.py", line 896, in <module>
    main()
  File ".\infer.py", line 868, in main
    img_list, FLAGS.run_benchmark, repeats=100, save_file=save_file)
  File ".\infer.py", line 264, in predict_image
    result = self.predict()
  File ".\infer.py", line 192, in predict
    self.predictor.run()
ValueError: In user code:

    File "tools/export_model.py", line 111, in <module>
      main()
    File "tools/export_model.py", line 107, in main
      run(FLAGS, cfg)
    File "tools/export_model.py", line 73, in run
      trainer.export(FLAGS.output_dir)
    File "/data/duxiaogang/PaddleDetection/ppdet/engine/trainer.py", line 781, in export
      save_dir)
    File "/data/duxiaogang/PaddleDetection/ppdet/engine/trainer.py", line 758, in _get_infer_cfg_and_input_spec
      input_spec, static_model.forward.main_program,
    File "/data/duxiaogang/anaconda3/envs/paddle-detection/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 580, in main_program
      concrete_program = self.concrete_program
    File "/data/duxiaogang/anaconda3/envs/paddle-detection/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program
      return self.concrete_program_specify_input_spec(input_spec=None)
    File "/data/duxiaogang/anaconda3/envs/paddle-detection/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 528, in concrete_program_specify_input_spec        
      *desired_input_spec, with_hook=with_hook)
    File "/data/duxiaogang/anaconda3/envs/paddle-detection/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/data/duxiaogang/anaconda3/envs/paddle-detection/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
      self._caches[item_id] = self._build_once(item)
    File "/data/duxiaogang/anaconda3/envs/paddle-detection/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 790, in _build_once
      **cache_key.kwargs)
    File "/data/duxiaogang/anaconda3/envs/paddle-detection/lib/python3.7/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/data/duxiaogang/anaconda3/envs/paddle-detection/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/data/duxiaogang/anaconda3/envs/paddle-detection/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/data/duxiaogang/anaconda3/envs/paddle-detection/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 733, in from_func_spec
      outputs = static_func(*inputs)
    File "/tmp/tmphvoyg_vj.py", line 101, in forward
      false_fn_5, (), (inputs, self), (out,))
    File "/data/duxiaogang/anaconda3/envs/paddle-detection/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/data/duxiaogang/anaconda3/envs/paddle-detection/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/tmp/tmphvoyg_vj.py", line 84, in false_fn_5
      for_loop_body_0, [inputs_list, __for_loop_var_index_0])
    File "/data/duxiaogang/anaconda3/envs/paddle-detection/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 45, in convert_while_loop
      loop_vars = _run_py_while(cond, body, loop_vars)
    File "/data/duxiaogang/anaconda3/envs/paddle-detection/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 59, in _run_py_while
      loop_vars = body(*loop_vars)
    File "/tmp/tmphvoyg_vj.py", line 79, in for_loop_body_0
      dy2static.convert_call(self.get_pred)())
    File "/data/duxiaogang/PaddleDetection/ppdet/modeling/architectures/s2anet.py", line 101, in get_pred
      output = self._forward()
    File "/data/duxiaogang/PaddleDetection/ppdet/modeling/architectures/s2anet.py", line 73, in _forward
      self.s2anet_head(body_feats)
    File "/data/duxiaogang/anaconda3/envs/paddle-detection/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/data/duxiaogang/anaconda3/envs/paddle-detection/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/tmp/tmpgo1di3vq.py", line 152, in forward
      for_loop_condition_7, for_loop_body_7, [feat_idx, feats])
    File "/data/duxiaogang/anaconda3/envs/paddle-detection/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 45, in convert_while_loop
      loop_vars = _run_py_while(cond, body, loop_vars)
    File "/data/duxiaogang/anaconda3/envs/paddle-detection/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 59, in _run_py_while
      loop_vars = body(*loop_vars)
    File "/tmp/tmpgo1di3vq.py", line 68, in for_loop_body_7
      init_anchors), (refine_anchor,))
    File "/data/duxiaogang/anaconda3/envs/paddle-detection/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/data/duxiaogang/anaconda3/envs/paddle-detection/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/data/duxiaogang/PaddleDetection/ppdet/modeling/heads/s2anet_head.py", line 454, in forward
      refine_anchor = self.bbox_decode(fam_reg, init_anchors)
    File "/data/duxiaogang/PaddleDetection/ppdet/modeling/heads/s2anet_head.py", line 941, in bbox_decode
      bboxes = self.delta2rbox(anchors, bbox_delta)
    File "/data/duxiaogang/PaddleDetection/ppdet/modeling/heads/s2anet_head.py", line 918, in delta2rbox
      rroi_angle) + rroi_x
    File "/data/duxiaogang/anaconda3/envs/paddle-detection/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py", line 347, in __impl__
      attrs={'axis': axis})
    File "/data/duxiaogang/anaconda3/envs/paddle-detection/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3621, in append_op
      attrs=kwargs.get("attrs", None))
    File "/data/duxiaogang/anaconda3/envs/paddle-detection/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2635, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [32768] and the shape of Y = [16384]. Received [32768] in X is not equal to [16384] in 
Y at i:0.
      [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <
= 1:0 != true:1.] (at C:\home\workspace\Paddle_release\paddle/phi/kernels/funcs/common_shape.h:84)
      [operator < elementwise_mul > error]

我是这样的操作，我新建了一个图片目录，图片目录下放三张图片，
然后运行 python deploy/python/infer.py，其中batchsize 设置为2报错，batchsize=1没有问题，是否deploy/python/infer.py不支持batch操作预测？谢谢！！！

**Comment by XYZ-916** [comment]
请问您的推理模型是？

**Comment by zgsxwsdxg** [comment]
> 请问您的推理模型是？

推理模型是通过tools/export_model.py 转的，模型是用S2ANet的

我的运行命令是： python deploy/python/infer.py --model_dir=output_inference/s2anet_1x_spine/ --image_dir=cases --device=GPU --batch_size=2

**Comment by zgsxwsdxg** [comment]
> 请问您的推理模型是？

bath_size=1, 是可以的，batch_size=2 就会报错，cases是我的图像目录下面放了三张图片

**Comment by wangxinxin08** [comment]
你好，请问你的PaddlePaddle版本和PaddleDetection版本是什么？

**Comment by zgsxwsdxg** [comment]
> 你好，请问你的PaddlePaddle版本和PaddleDetection版本是什么？

PaddlePaddle 2.3.1
PaddleDetection 2.4.0

**Comment by wangxinxin08** [comment]
PaddleDetection 2.5.0开始支持batch_size > 1的哈，切换成PaddleDetection 2.5试下呢

**Comment by zgsxwsdxg** [comment]
> PaddleDetection 2.5.0开始支持batch_size > 1的哈，切换成PaddleDetection 2.5试下呢

但是，我感觉逻辑上说不过去，既然我都通过export_model.py 导出模型了，不应该再依赖paddledetection的东西了，是不？export_model不就是为了 只用paddle部署推理么？

**Comment by zgsxwsdxg** [comment]
> PaddleDetection 2.5.0开始支持batch_size > 1的哈，切换成PaddleDetection 2.5试下呢

我的模型训完，已经通过export_model.py转为paddle的部署模型，还依赖paddleDetection，我看了部署代码deploy/python/infer.py 中，好像没有关于PaddleDetection的东西

**Comment by wangxinxin08** [comment]
导出的模型是根据PaddleDetection中模型的定义导出的，在PaddleDetection 2.5之前，S2ANet的组网就只支持batch_size =1

**Comment by zgsxwsdxg** [comment]
> 导出的模型是根据PaddleDetection中模型的定义导出的，在PaddleDetection 2.5之前，S2ANet的组网就只支持batch_size =1

谢谢，你的耐心解释，那我明白了，我基于2.5版本重新训练试试。有问题再请教你。

**Comment by wangxinxin08** [comment]
@zgsxwsdxg 应该不用重新训练，你直接加载模型在PaddleDetection 2.5下试试，因为其实模型整体变化不大，权重的名字也没有修改，你可以先用tool/infer.py测试下，如果和原先结果一致，则可以直接用PaddleDetection 2.5和你原先训练的权重导出模型

**Comment by zgsxwsdxg** [comment]
> @zgsxwsdxg 应该不用重新训练，你直接加载模型在PaddleDetection 2.5下试试，因为其实模型整体变化不大，权重的名字也没有修改，你可以先用tool/infer.py测试下，如果和原先结果一致，则可以直接用PaddleDetection 2.5和你原先训练的权重导出模型

非常感谢，我换了2.5.0 PaddleDetection可以用了。

**Comment by zgsxwsdxg** [comment]
> @zgsxwsdxg 应该不用重新训练，你直接加载模型在PaddleDetection 2.5下试试，因为其实模型整体变化不大，权重的名字也没有修改，你可以先用tool/infer.py测试下，如果和原先结果一致，则可以直接用PaddleDetection 2.5和你原先训练的权重导出模型

你好，问下你，solov2算法好像在batch_size大于时，在PaddleDetection2.5.0 环境还是会报同样的错，期待你的解答，谢谢

**Comment by wangxinxin08** [comment]
@zgsxwsdxg solov2部署时batch_size大于1确实是不支持的

**Comment by zgsxwsdxg** [comment]
> @zgsxwsdxg solov2部署时batch_size大于1确实是不支持的

后期会增加这个batch_size大于1的推理么？我猜想是不是因为solov2算法结果输出图太多，占用cpu和gpu太大，不好弄成batch_size大于1的推理？期待你的解答，谢谢

**Comment by wangxinxin08** [comment]
> > @zgsxwsdxg solov2部署时batch_size大于1确实是不支持的
> 
> 后期会增加这个batch_size大于1的推理么？我猜想是不是因为solov2算法结果输出图太多，占用cpu和gpu太大，不好弄成batch_size大于1的推理？期待你的解答，谢谢

应该是组网方式的差异带来，后续支持与否需要评估

**Comment by withkun** [comment]
MASK-RCNN如何支持batchsize大于1的推理
使用预训练模型进行了导出测试， batchsize大于1时报错

版本信息：
paddlepaddle-gpu          2.4.1.post117
PaddleDetection>git log
commit 607c64ce7ca404bba50f0668fe6f801ef5574133 (HEAD -> release/2.5, origin/release/2.5, origin/HEAD)

导出命令：
python tools/export_model.py --config=configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.yml --output_dir=./output/pretrain_weights -o weights=https://paddledet.bj.bcebos.com/models/mask_rcnn_r50_fpn_1x_coco.pdparams

推理命令：
python deploy/python/infer.py --device=GPU --model_dir=output/pretrain_weights/mask_rcnn_r50_fpn_1x_coco --output_dir=output/model_inference --image_dir=C:/WORK/PaddleDeploy/Images/ --batch_size=2

报错信息：
-----------  Model Configuration -----------
Model Arch: RCNN
Transform Order:
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--transform op: PadStride
--------------------------------------------
Found 4 inference images in total.
Traceback (most recent call last):
  File "C:\DeepLearning\PaddleDetection\deploy\python\infer.py", line 1034, in <module>
    main()
  File "C:\DeepLearning\PaddleDetection\deploy\python\infer.py", line 1002, in main
    detector.predict_image(
  File "C:\DeepLearning\PaddleDetection\deploy\python\infer.py", line 392, in predict_image
    result = self.predict()
  File "C:\DeepLearning\PaddleDetection\deploy\python\infer.py", line 196, in predict
    self.predictor.run()
ValueError: (InvalidArgument) The value (4) of the non-singleton dimension does not match the corresponding value (2) in shape for expand_v2 op.
  [Hint: Expected vec_in_dims[i] == expand_shape[i], but received vec_in_dims[i]:4 != expand_shape[i]:2.] (at ../paddle/phi/kernels/impl/expand_kernel_impl.h:61)
  [operator < expand_v2 > error]
