### ISSUE TITLE
摔倒检测示例错误，TypeError: '>' not supported between instances of 'tuple' and 'int'

### ISSUE THREAD

**Issue by jiangxinufo** [PaddlePaddle/PaddleDetection#7140]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

摔倒检测，环境配置完成，运行测试代码出现以下报错：
 python deploy/pipeline/pipeline.py --config deploy/pipeline/config/infer_cfg_pphuman.yml --video_file=demo/videoplayback3.mp4 --device=gpu
错误如下：
deploy/pipeline/pipeline.py:24: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Sequence, defaultdict
-----------  Running Arguments -----------
ATTR:
  batch_size: 8
  enable: false
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/PPLCNet_x1_0_person_attribute_945_infer.zip
DET:
  batch_size: 1
  model_dir: output_inference/mot_ppyoloe_l_36e_pipeline
ID_BASED_CLSACTION:
  batch_size: 8
  display_frames: 80
  enable: false
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/PPHGNet_tiny_calling_halfbody.zip
  skip_frame_num: 2
  threshold: 0.8
ID_BASED_DETACTION:
  batch_size: 8
  display_frames: 80
  enable: false
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/ppyoloe_crn_s_80e_smoking_visdrone.zip
  skip_frame_num: 2
  threshold: 0.6
KPT:
  batch_size: 8
  model_dir: output_inference/dark_hrnet_w32_256x192
MOT:
  batch_size: 1
  enable: false
  model_dir: output_inference/mot_ppyoloe_l_36e_pipeline
  skip_frame_num: -1
  tracker_config: deploy/pipeline/config/tracker_config.yml
REID:
  batch_size: 16
  enable: false
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/reid_model.zip
SKELETON_ACTION:
  batch_size: 1
  coord_size:
  - 384
  - 512
  display_frames: 80
  enable: true
  max_frames: 50
  model_dir: output_inference/STGCN
VIDEO_ACTION:
  batch_size: 1
  enable: false
  frame_len: 8
  model_dir: https://videotag.bj.bcebos.com/PaddleVideo-release2.3/ppTSM_fight.zip
  sample_freq: 7
  short_size: 340
  target_size: 320
attr_thresh: 0.5
crop_thresh: 0.5
kpt_thresh: 0.2
visual: true
warmup_frame: 50

------------------------------------------
SkeletonAction Recognition enabled
DET  model dir:  output_inference/mot_ppyoloe_l_36e_pipeline
mot_model_dir model_dir:  output_inference/mot_ppyoloe_l_36e_pipeline
KPT  model dir:  output_inference/dark_hrnet_w32_256x192
SKELETON_ACTION  model dir:  output_inference/STGCN
-----------  Model Configuration -----------
Model Arch: STGCN
Transform Order:
--transform op: AutoPadding
--------------------------------------------
-----------  Model Configuration -----------
Model Arch: HRNet
Transform Order:
--transform op: TopDownEvalAffine
--transform op: Permute
--------------------------------------------
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order:
--transform op: Resize
--transform op: Permute
--------------------------------------------
video fps: 25, frame_count: 2229
Thread: 0; frame id: 0
Thread: 0; trackid number: 13
Traceback (most recent call last):
  File "deploy/pipeline/pipeline.py", line 1084, in <module>
    main()
  File "deploy/pipeline/pipeline.py", line 1071, in main
    pipeline.run_multithreads()
  File "deploy/pipeline/pipeline.py", line 169, in run_multithreads
    self.predictor.run(self.input)
  File "deploy/pipeline/pipeline.py", line 483, in run
    self.predict_video(input, thread_idx=thread_idx)
  File "deploy/pipeline/pipeline.py", line 806, in predict_video
    skeleton_action_input = parse_mot_keypoint(
  File "E:\Paddle-release-2.2\PaddleDetection-2.5.0\deploy\pipeline\pipe_utils.py", line 243, in parse_mot_keypoint
    skeleton.append(refine_keypoint_coordinary(kpts, bbox, coord_size))
  File "E:\Paddle-release-2.2\PaddleDetection-2.5.0\deploy\pipeline\pipe_utils.py", line 225, in refine_keypoint_coordinary
    tl = np.expand_dims(np.transpose(tl, (1, 0)), (2, 3))
  File "<__array_function__ internals>", line 5, in expand_dims
  File "C:\ProgramData\Anaconda3\envs\paddledetection\lib\site-packages\numpy\lib\shape_base.py", line 577, in expand_dims
    if axis > a.ndim or axis < -a.ndim - 1:
TypeError: '>' not supported between instances of 'tuple' and 'int'

**Comment by jiangxinufo** [comment]
已解决，numpy升级到1.22.4，paddle-gpu升级到2.3.2
