### ISSUE TITLE
训练自己的coco关键点数据集，执行infer.py报错

### ISSUE THREAD

**Issue by SongHeX** [PaddlePaddle/PaddleDetection#7159]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在colab中执行：!CUDA_VISIBLE_DEVICES=0 python3 tools/infer.py \                 
 -c /content/PaddleDetection/configs/keypoint/hrnet/hrnet_w32_384x288.yml \                  
-o weights=/content/PaddleDetection/output/hrnet_w32_384x288/model_final.pdparams \                 
 --infer_dir=/content/drive/MyDrive/Colab-Notebooks/coco-7/val/ \                  
--draw_threshold=0.5 \                  
--save_results=True
报错

W1020 07:56:11.114243  6820 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.2, Runtime API Version: 11.2
W1020 07:56:11.122241  6820 device_context.cc:465] device: 0, cuDNN Version: 8.1.
[10/20 07:56:15] ppdet.utils.checkpoint INFO: Finish loading model weights: /content/PaddleDetection/output/hrnet_w32_384x288/model_final.pdparams
[10/20 07:56:15] train INFO: Found 84 inference images in total.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[10/20 07:56:15] ppdet.data.source.category WARNING: anno_file 'dataset/coco/keypoint_imagelist.txt' is None or not set or not exist, please recheck TrainDataset/EvalDataset/TestDataset.anno_path, otherwise the default categories will be used by metric_type.
  0% 0/84 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "tools/infer.py", line 226, in <module>
    main()
  File "tools/infer.py", line 222, in main
    run(FLAGS, cfg)
  File "tools/infer.py", line 187, in run
    visualize=FLAGS.visualize)
  File "/content/PaddleDetection/ppdet/engine/trainer.py", line 882, in predict
    _m.update(data, outs)
  File "/content/PaddleDetection/ppdet/metrics/keypoint_metrics.py", line 75, in update
    inputs['center'], paddle.Tensor) else inputs['center'][:, 0:2]
KeyError: 'center'

**Comment by zhiboniu** [comment]
数据集提供的数据中缺少了'center'信息，可以打log对比原来的数据集的做法

**Comment by NikolaTeslein** [comment]
我遇到了同样问题，并且这个问题在ppdet2.1版本中没见过，看来是普遍的问题。太坑了，小白放弃了。

**Comment by Bradly-s** [comment]
你好，请问这个问题是如何解决的？
