### ISSUE TITLE
多gpu训练报错

### ISSUE THREAD

**Issue by ionescofung** [PaddlePaddle/PaddleDetection#7175]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用 2张显卡训练提示错误

PS D:\python\envs\paddle2\paddledetection> python -m paddle.distributed.launch --gpus 0,1 tools/train.py -c configs/yolov3/yolov3_mobilenet_v1_roadsign.yml
LAUNCH INFO 2022-10-24 14:53:51,624 -----------  Configuration  ----------------------
LAUNCH INFO 2022-10-24 14:53:51,625 devices: None
LAUNCH INFO 2022-10-24 14:53:51,625 elastic_level: -1
LAUNCH INFO 2022-10-24 14:53:51,626 elastic_timeout: 30
LAUNCH INFO 2022-10-24 14:53:51,626 gloo_port: 6767
LAUNCH INFO 2022-10-24 14:53:51,626 host: None
LAUNCH INFO 2022-10-24 14:53:51,626 job_id: default
LAUNCH INFO 2022-10-24 14:53:51,627 legacy: False
LAUNCH INFO 2022-10-24 14:53:51,627 log_dir: log
LAUNCH INFO 2022-10-24 14:53:51,627 log_level: INFO
LAUNCH INFO 2022-10-24 14:53:51,627 master: None
LAUNCH INFO 2022-10-24 14:53:51,627 max_restart: 3
LAUNCH INFO 2022-10-24 14:53:51,627 nnodes: 1
LAUNCH INFO 2022-10-24 14:53:51,628 nproc_per_node: None
LAUNCH INFO 2022-10-24 14:53:51,628 rank: -1
LAUNCH INFO 2022-10-24 14:53:51,628 run_mode: collective
LAUNCH INFO 2022-10-24 14:53:51,628 server_num: None
LAUNCH INFO 2022-10-24 14:53:51,628 servers:
LAUNCH INFO 2022-10-24 14:53:51,629 trainer_num: None
LAUNCH INFO 2022-10-24 14:53:51,629 trainers:
LAUNCH INFO 2022-10-24 14:53:51,629 training_script: 0,1
LAUNCH INFO 2022-10-24 14:53:51,629 training_script_args: ['tools/train.py', '-c', 'configs/yolov3/yolov3_mobilenet_v1_roadsign.yml']
LAUNCH INFO 2022-10-24 14:53:51,629 with_gloo: 0
LAUNCH INFO 2022-10-24 14:53:51,629 --------------------------------------------------
LAUNCH WARNING 2022-10-24 14:53:51,630 Compatible mode enable with args ['--gpus']
-----------  Configuration Arguments -----------
backend: auto
cluster_topo_path: None
elastic_pre_hook: None
elastic_server: None
enable_auto_mapping: False
force: False
gpus: 0,1
heter_devices:
heter_worker_num: None
heter_workers:
host: None
http_port: None
ips: 127.0.0.1
job_id: None
log_dir: log
np: None
nproc_per_node: None
rank_mapping_path: None
run_mode: None
scale: 0
server_num: None
servers:
training_script: tools/train.py
training_script_args: ['-c', 'configs/yolov3/yolov3_mobilenet_v1_roadsign.yml']
worker_num: None
workers:
------------------------------------------------
WARNING 2022-10-24 14:53:51,634 launch.py:518] Not found distinct arguments and compiled with cuda or xpu or npu or mlu. Default use collective mode
WARNING 2022-10-24 14:53:51,634 launch.py:518] Not found distinct arguments and compiled with cuda or xpu or npu or mlu. Default use collective mode
launch train in GPU mode!
INFO 2022-10-24 14:53:51,635 launch_utils.py:558] Local start 2 processes. First process distributed environment info (Only For Debug):
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:1635                |
    |                     PADDLE_TRAINERS_NUM                        2                      |
    |                PADDLE_TRAINER_ENDPOINTS          127.0.0.1:1635,127.0.0.1:1636        |
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                       0,1                     |
    |                     FLAGS_selected_gpus                        0                      |
    |             FLAGS_selected_accelerators                        0                      |
    +=======================================================================================+

INFO 2022-10-24 14:53:51,635 launch_utils.py:558] Local start 2 processes. First process distributed environment info (Only For Debug):
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:1635                |
    |                     PADDLE_TRAINERS_NUM                        2                      |
    |                PADDLE_TRAINER_ENDPOINTS          127.0.0.1:1635,127.0.0.1:1636        |
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                       0,1                     |
    |                     FLAGS_selected_gpus                        0                      |
    |             FLAGS_selected_accelerators                        0                      |
    +=======================================================================================+

INFO 2022-10-24 14:53:51,636 launch_utils.py:563] details about PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
INFO 2022-10-24 14:53:51,636 launch_utils.py:563] details about PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
子目录或文件 -p 已经存在。
处理: -p 时出错。
子目录或文件 log 已经存在。
处理: log 时出错。
'rm' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
子目录或文件 -p 已经存在。
处理: -p 时出错。
子目录或文件 log 已经存在。
处理: log 时出错。
'rm' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
launch proc_id:2984 idx:0
launch proc_id:4072 idx:1
Traceback (most recent call last):
  File "tools/train.py", line 172, in <module>
    main()
  File "tools/train.py", line 168, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 117, in run
    init_parallel_env()
  File "D:\python\envs\paddle2\paddledetection\ppdet\engine\env.py", line 44, in init_parallel_env
    paddle.distributed.init_parallel_env()
  File "C:\Users\62845\.conda\envs\paddle2\lib\site-packages\paddle\distributed\parallel.py", line 300, in init_parallel_env
    core.NCCLParallelContext(strategy, place))
AttributeError: module 'paddle.fluid.core_avx' has no attribute 'NCCLParallelContext'
INFO 2022-10-24 14:53:57,702 launch_utils.py:343] terminate all the procs
INFO 2022-10-24 14:53:57,702 launch_utils.py:343] terminate all the procs
ERROR 2022-10-24 14:53:57,705 launch_utils.py:640] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0, 1] was aborted. Please check its log.
ERROR 2022-10-24 14:53:57,705 launch_utils.py:640] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0, 1] was aborted. Please check its log.
INFO 2022-10-24 14:54:00,709 launch_utils.py:343] terminate all the procs
INFO 2022-10-24 14:54:00,709 launch_utils.py:343] terminate all the procs
INFO 2022-10-24 14:54:00,713 launch.py:402] Local processes completed.
INFO 2022-10-24 14:54:00,713 launch.py:402] Local processes completed.

**Comment by XYZ-916** [comment]
请问你的Paddle版本是？

**Comment by ionescofung** [comment]
2.3.2

**Comment by ionescofung** [comment]
> 


2.3.2
