### ISSUE TITLE
ByteTrack 添加ReID网络报错

### ISSUE THREAD

**Issue by SunnyGrocery** [PaddlePaddle/PaddleDetection#7184]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

当修改`configs/mot/bytetrack/bytetrack_yolox.yml`部分（从DeepSort中copy来的）：
```
ByteTrack:
  detector: YOLOX
#  reid: None
  reid: PPLCNetEmbedding
  tracker: JDETracker
det_weights: https://bj.bcebos.com/v1/paddledet/models/mot/yolox_x_24e_800x1440_mix_det.pdparams
#reid_weights: None
reid_weights: https://paddledet.bj.bcebos.com/models/mot/deepsort_pplcnet.pdparams

PPLCNetEmbedding:
  input_ch: 1280
  output_ch: 512
```
后进行推理，会在一定轮次后报如下错
```
              File "/home/aistudio/work/PaddleDetection/ppdet/modeling/mot/tracker/jde_tracker.py", line 144, in update
                pred_embs_dict[cls_id] = pred_embs[cls_idx]
              IndexError: boolean index did not match indexed array along dimension 0; dimension is 99 but corresponding boolean dimension is 100
```
可能是ReID网络输出了未知的class？
求助：如果希望在bytetrack中加入ReID网络，请问如何更改配置文件？

**Comment by nemonameless** [comment]
参考
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/configs/mot/bytetrack/bytetrack_ppyoloe_pplcnet.yml

**Comment by moonnyeon** [comment]
i also meet same issue 
how did you solve this problem????

i did this command:
1. python tools/train.py -c ./configs/snmot/bytetrack/detector/ppyoloe_crn_l_36e_640x640.yml
2. python tools/train.py -c ./configs/snmot/bytetrack/bytetrack_ppyoloe_pplcnet.yml
3. python tools/infer_mot.py -c ./configs/snmot/bytetrack/bytetrack_ppyoloe_pplcnet.yml -o weights=./output/bytetrack_ppyoloe_pplcnet/model_final --image_dir ./my_image --save_video

and get this error


Traceback (most recent call last):
  File "tools/infer_mot.py", line 149, in <module>
    main()
  File "tools/infer_mot.py", line 145, in main
    run(FLAGS, cfg)
  File "tools/infer_mot.py", line 113, in run
    draw_threshold=FLAGS.draw_threshold)
  File "/mnt/disk2/SoccerTracking/SoccerNet_Tracking_PaddleDetection/PaddleDetection/ppdet/engine/tracker.py", line 700, in mot_predict_seq
    draw_threshold=draw_threshold)
  File "/mnt/disk2/SoccerTracking/SoccerNet_Tracking_PaddleDetection/PaddleDetection/ppdet/engine/tracker.py", line 458, in _eval_seq_sde
    online_targets_dict = tracker.update(pred_dets_old, pred_embs)
  File "/mnt/disk2/SoccerTracking/SoccerNet_Tracking_PaddleDetection/PaddleDetection/ppdet/modeling/mot/tracker/jde_tracker.py", line 144, in update
    pred_embs_dict[cls_id] = pred_embs[cls_idx]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 16 but corresponding boolean dimension is 100
