### ISSUE TITLE
请问这个错误是什么原因呢？

### ISSUE THREAD

**Issue by cassiaaaaaa** [PaddlePaddle/PaddleDetection#72]
paddle1.6：
2019-12-05 15:32:27,163-WARNING: Your reader has raised an exception!
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/home/vis/wangping/envs/env_py3.6_torch1.0/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/vis/wangping/envs/env_py3.6_torch1.0/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vis/wangping/envs/env_py3.6_torch1.0/lib/python3.6/site-packages/paddle/fluid/reader.py", line 488, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/home/vis/wangping/envs/env_py3.6_torch1.0/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/vis/wangping/envs/env_py3.6_torch1.0/lib/python3.6/site-packages/paddle/fluid/reader.py", line 468, in __thread_main__
    for tensors in self._tensor_reader():
  File "/home/vis/wangping/envs/env_py3.6_torch1.0/lib/python3.6/site-packages/paddle/fluid/reader.py", line 542, in __tensor_reader_impl__
    for slots in paddle_reader():
  File "/home/vis/wangping/envs/env_py3.6_torch1.0/lib/python3.6/site-packages/paddle/fluid/data_feeder.py", line 454, in __reader_creator__
    for item in reader():
  File "/home/vis/wangping/workspace/food/code/PaddleDetection-master/ppdet/data/reader.py", line 103, in _reader
    for _batch in batched_ds:
  File "/home/vis/wangping/workspace/food/code/PaddleDetection-master/ppdet/data/dataset.py", line 30, in __next__
    return self.next()
  File "/home/vis/wangping/workspace/food/code/PaddleDetection-master/ppdet/data/transform/transformer.py", line 44, in _proxy_method
    return func(*args, **kwargs)
  File "/home/vis/wangping/workspace/food/code/PaddleDetection-master/ppdet/data/transform/transformer.py", line 57, in next
    sample = self._ds.next()
  File "/home/vis/wangping/workspace/food/code/PaddleDetection-master/ppdet/data/transform/transformer.py", line 44, in _proxy_method
    return func(*args, **kwargs)
  File "/home/vis/wangping/workspace/food/code/PaddleDetection-master/ppdet/data/transform/transformer.py", line 99, in next
    out = self._ds.next()
  File "/home/vis/wangping/workspace/food/code/PaddleDetection-master/ppdet/data/transform/transformer.py", line 44, in _proxy_method
    return func(*args, **kwargs)
  File "/home/vis/wangping/workspace/food/code/PaddleDetection-master/ppdet/data/transform/parallel_map.py", line 191, in next
    raise ValueError("all consumers exited, no more samples")
ValueError: all consumers exited, no more samples

2019-12-05 15:32:48,322-INFO: iter: 3320, lr: 0.000001, 'loss': '11.461334', time: 2.233, eta: 7:14:41
Traceback (most recent call last):
  File "tools/train.py", line 340, in <module>
    main()
  File "tools/train.py", line 246, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "/home/vis/wangping/envs/env_py3.6_torch1.0/lib/python3.6/site-packages/paddle/fluid/executor.py", line 775, in run
    six.reraise(*sys.exc_info())
  File "/home/vis/wangping/envs/env_py3.6_torch1.0/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/vis/wangping/envs/env_py3.6_torch1.0/lib/python3.6/site-packages/paddle/fluid/executor.py", line 770, in run
    use_program_cache=use_program_cache)
  File "/home/vis/wangping/envs/env_py3.6_torch1.0/lib/python3.6/site-packages/paddle/fluid/executor.py", line 829, in _run_impl
    return_numpy=return_numpy)
  File "/home/vis/wangping/envs/env_py3.6_torch1.0/lib/python3.6/site-packages/paddle/fluid/executor.py", line 669, in _run_parallel
    tensors = exe.run(fetch_var_names)._move_to_list()
paddle.fluid.core_avx.EOFException: There is no next data. at [/paddle/paddle/fluid/operators/reader/read_op.cc:90]

**Comment by heavengate** [comment]
reader读数据错误，你是否修改了data reader相关的代码，若使用自己的数据集请检查一下数据集是否正确，是否有的图像有annotation却图像文件缺失之类的

**Comment by cassiaaaaaa** [comment]
> reader读数据错误，你是否修改了data reader相关的代码，若使用自己的数据集请检查一下数据集是否正确，是否有的图像有annotation却图像文件缺失之类的

谢谢回复！我没有修改data reader相关的代码，但是用了自己的数据集。检查过数据集，没有发现这种情况。这个错误是在跑完许多个epoch之后出现的，并且每次重新跑的出现位置不定，这个正常吗？

**Comment by heavengate** [comment]
看报错是consumer exit了，可能是transform的时候出错了，你训练过程中是否配置`use_process:  True`，可以配置`use_process: False`看下是否有报错
