### ISSUE TITLE
预测视频和图片准确率相差过大

### ISSUE THREAD

**Issue by lhy823436493** [PaddlePaddle/PaddleDetection#720]
在训练完模型之后，预测图片效果不错，导出模型后预测视频，几乎没有检测正确的，请问是什么原因。

**Comment by qingqing01** [comment]
@lhy823436493 导出模型后，可以先排查下预测图片是否正常

**Comment by lhy823436493** [comment]
Traceback (most recent call last):
  File "tools/infer.py", line 560, in <module>
    predict_video()
  File "tools/infer.py", line 518, in predict_video
    results = detector.predict(frame, FLAGS.threshold)
  File "tools/infer.py", line 483, in predict
    np_boxes, np_masks, im_info, threshold=threshold)
  File "tools/infer.py", line 436, in postprocess
    expect_boxes = np_boxes[:, 1] > threshold
IndexError: index 1 is out of bounds for axis 1 with size 1

**Comment by lhy823436493** [comment]
这样的报错是什么原因呢

**Comment by lhy823436493** [comment]
模型训练结束的时候报了这样的错误。
WARNING: fail to map op [CropImage_8cd9bd] with error: too many indices for array and stack:
Traceback (most recent call last):
  File "/home/aistudio/PaddleDetection/ppdet/data/transform/transformer.py", line 44, in _proxy_method
    return func(*args, **kwargs)
  File "/home/aistudio/PaddleDetection/ppdet/data/dataset.py", line 48, in reset
    (self.__class__.__name__))
NotImplementedError: MappedDataset.reset not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aistudio/PaddleDetection/ppdet/data/transform/transformer.py", line 44, in _proxy_method
    return func(*args, **kwargs)
  File "/home/aistudio/PaddleDetection/ppdet/data/dataset.py", line 48, in reset
    (self.__class__.__name__))
NotImplementedError: BatchedDataset.reset not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aistudio/PaddleDetection/ppdet/data/transform/__init__.py", line 77, in _mapper
    out = f(sample, ctx)
  File "/home/aistudio/PaddleDetection/ppdet/data/transform/operators.py", line 699, in __call__
    im = im[ymin:ymax, xmin:xmax]
IndexError: too many indices for array

**Comment by qingqing01** [comment]
```
 File "tools/infer.py", line 518, in predict_video
```

这个代码是你自己写的吧。

```
expect_boxes = np_boxes[:, 1] > threshold
IndexError: index 1 is out of bounds for axis 1 with size 1
```

这个里的错误看着是`np_boxes`的shape不对

**Comment by lhy823436493** [comment]
https://github.com/PaddlePaddle/PaddleDetection/tree/master/deploy/python 用的这里的代码，其他导出的模型都没有问题，可以正常使用，这次自己训练的数据集后出现这个问题。打印的np_boxes是【【-1.】】

**Comment by qingqing01** [comment]
np_boxes是[-1]的话，表示没有检测到框，输出的是空的。建议导出自己模型后，先预测单张图片确保正确性。

**Comment by lhy823436493** [comment]
好的好的
