### ISSUE TITLE
报错：InvalidArgumentError: The 'shape' attribute in ReshapeOp is invalid.

### ISSUE THREAD

**Issue by zhuoxun-xun** [PaddlePaddle/PaddleDetection#7206]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

pp-human的video action recognition 用自己训练的模型以下的错误:    
'''
InvalidArgumentError: The 'shape' attribute in ReshapeOp is invalid. The input tensor X'size must be divisible by known capacity of 'shape'. But received X's shape = [1, 1, 1, 8, 3, 320, 320], X's size = 2457600, 'shape' is [-1, 3, 224, 224], known capacity of 'shape' is -150528.
      [Hint: Expected output_shape[unk_dim_idx] * capacity == -in_size, but received output_shape[unk_dim_idx] * capacity:-2408448 != -in_size:-2457600.] (at /paddle/paddle/fluid/operators/reshape_op.cc:210)
      [operator < reshape2 > error]
'''

### 复现环境 Environment

- PaddlePaddle: 2.2.2
- PaddleDetection: develop

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
有修改什么东西嘛 看着是因为输入的尺寸不对导致的吧，

**Comment by chenyangMl** [comment]
> 有修改什么东西嘛 看着是因为输入的尺寸不对导致的吧，

遇到同样的问题.
代码分支: release/2.5
cd dataset
wget https://paddle-qa.bj.bcebos.com/PaddleDetection/coco.zip
unzip coco.zip

运行文档单卡训练命令
python tools/train.py -c configs/picodet/picodet_s_320_coco_lcnet.yml --eval

错误log:

Warning: Unable to use JDE/FairMOT/ByteTrack, please install lap, for example: `pip install lap`, see https://github.com/gatagat/lap
Warning: Unable to use OC-SORT, please install filterpy, for example: `pip install filterpy`, see https://github.com/rlabbe/filterpy
Warning: Unable to use MOT metric, please install motmetrics, for example: `pip install motmetrics`, see https://github.com/longcw/py-motmetrics
Warning: Unable to use MCMOT metric, please install motmetrics, for example: `pip install motmetrics`, see https://github.com/longcw/py-motmetrics
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
W1117 17:01:34.880887  3391 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 10.2
W1117 17:01:34.887300  3391 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
[11/17 17:01:35] ppdet.utils.checkpoint INFO: ['last_conv.weight'] in pretrained weight is not used in the model, and its will not be loaded
[11/17 17:01:35] ppdet.utils.checkpoint INFO: The shape [1000] in pretrained weight fc.bias is unmatched with the shape [96] in model head.conv_feat.se.0.fc.bias. And the weight fc.bias will not be loaded
[11/17 17:01:35] ppdet.utils.checkpoint INFO: The shape [1280, 1000] in pretrained weight fc.weight is unmatched with the shape [96, 96, 1, 1] in model head.conv_feat.se.0.fc.weight. And the weight fc.weight will not be loaded
[11/17 17:01:35] ppdet.utils.checkpoint INFO: The shape [1000] in pretrained weight fc.bias is unmatched with the shape [96] in model head.conv_feat.se.1.fc.bias. And the weight fc.bias will not be loaded
[11/17 17:01:35] ppdet.utils.checkpoint INFO: The shape [1280, 1000] in pretrained weight fc.weight is unmatched with the shape [96, 96, 1, 1] in model head.conv_feat.se.1.fc.weight. And the weight fc.weight will not be loaded
[11/17 17:01:35] ppdet.utils.checkpoint INFO: The shape [1000] in pretrained weight fc.bias is unmatched with the shape [96] in model head.conv_feat.se.2.fc.bias. And the weight fc.bias will not be loaded
[11/17 17:01:35] ppdet.utils.checkpoint INFO: The shape [1280, 1000] in pretrained weight fc.weight is unmatched with the shape [96, 96, 1, 1] in model head.conv_feat.se.2.fc.weight. And the weight fc.weight will not be loaded
[11/17 17:01:35] ppdet.utils.checkpoint INFO: The shape [1000] in pretrained weight fc.bias is unmatched with the shape [96] in model head.conv_feat.se.3.fc.bias. And the weight fc.bias will not be loaded
[11/17 17:01:35] ppdet.utils.checkpoint INFO: The shape [1280, 1000] in pretrained weight fc.weight is unmatched with the shape [96, 96, 1, 1] in model head.conv_feat.se.3.fc.weight. And the weight fc.weight will not be loaded
[11/17 17:01:35] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/appuser/.cache/paddle/weights/PPLCNet_x0_75_pretrained.pdparams
Traceback (most recent call last):
  File "tools/train.py", line 172, in <module>
    main()
  File "tools/train.py", line 168, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 132, in run
    trainer.train(FLAGS.eval)
  File "/mnt2/cy/works/PaddleDetection/ppdet/engine/trainer.py", line 506, in train
    outputs = model(data)
  File "/home/appuser/miniconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/appuser/miniconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/mnt2/cy/works/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 59, in forward
    out = self.get_loss()
  File "/mnt2/cy/works/PaddleDetection/ppdet/modeling/architectures/picodet.py", line 78, in get_loss
    head_outs, _ = self._forward()
  File "/mnt2/cy/works/PaddleDetection/ppdet/modeling/architectures/picodet.py", line 66, in _forward
    head_outs = self.head(fpn_feats, self.export_post_process)
  File "/home/appuser/miniconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/appuser/miniconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/mnt2/cy/works/PaddleDetection/ppdet/modeling/heads/pico_head.py", line 551, in forward
    return self.forward_train(fpn_feats)
  File "/mnt2/cy/works/PaddleDetection/ppdet/modeling/heads/pico_head.py", line 581, in forward_train
    bbox_pred = bbox_pred.reshape([b, cell_h * cell_w, 4])
  File "/home/appuser/miniconda3/envs/py38/lib/python3.8/site-packages/paddle/tensor/manipulation.py", line 2139, in reshape
    return paddle.fluid.layers.reshape(x=x, shape=shape, name=name)
  File "/home/appuser/miniconda3/envs/py38/lib/python3.8/site-packages/paddle/fluid/layers/nn.py", line 6373, in reshape
    out, _ = _C_ops.reshape2(x, None, 'shape', shape)
ValueError: (InvalidArgument) The 'shape' in ReshapeOp is invalid. The input tensor X'size must be equal to the capacity of 'shape'. But received X's shape = [65536, 4], X's size = 262144, 'shape' is [64, 1066474765, 4], the capacity of 'shape' is 273017539840.
  [Hint: Expected capacity == in_size, but received capacity:273017539840 != in_size:262144.] (at /paddle/paddle/fluid/operators/reshape_op.cc:204)
  [operator < reshape2 > error]

**Comment by chenyangMl** [comment]
切到2.3版本就没可以

loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
W1117 17:29:02.457630 56089 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 10.2
W1117 17:29:02.465134 56089 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
[11/17 17:29:02] ppdet.utils.download INFO: Downloading ESNet_x0_75_pretrained.pdparams from https://paddledet.bj.bcebos.com/models/pretrained/ESNet_x0_75_pretrained.pdparams
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 14101/14101 [05:40<00:00, 41.40KB/s]
[11/17 17:34:44] ppdet.utils.checkpoint INFO: ['_fc.bias', '_fc.weight', '_last_conv._batch_norm._mean', '_last_conv._batch_norm._variance', '_last_conv._batch_norm.bias', '_last_conv._batch_norm.weight', '_last_conv._conv.weight', 'last_conv.weight'] in pretrained weight is not used in the model, and its will not be loaded
[11/17 17:34:44] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/appuser/.cache/paddle/weights/ESNet_x0_75_pretrained.pdparams
[11/17 17:34:47] ppdet.utils.checkpoint INFO: Save checkpoint: output/picodet_s_320_coco
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
E1117 17:36:40.200119 56089 top_k_function_cuda.h:916] TopKOP failed as could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to calculate temp_storage_bytes, status: invalid device function
E1117 17:36:40.378402 56089 top_k_function_cuda.h:916] TopKOP failed as could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to calculate temp_storage_bytes, status: invalid device function
E1117 17:36:40.408003 56089 top_k_function_cuda.h:916] TopKOP failed as could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to calculate temp_storage_bytes, status: invalid device function
E1117 17:36:40.434123 56089 top_k_function_cuda.h:916] TopKOP failed as could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to calculate temp_storage_bytes, status: invalid device function
E1117 17:36:40.459311 56089 top_k_function_cuda.h:916] TopKOP failed as could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to calculate temp_storage_bytes, status: invalid device function
E1117 17:36:40.483808 56089 top_k_function_cuda.h:916] TopKOP failed as could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to calculate temp_storage_bytes, status: invalid device function
E1117 17:36:40.508206 56089 top_k_function_cuda.h:916] TopKOP failed as could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to calculate temp_storage_bytes, status: invalid device function
E1117 17:36:40.536990 56089 top_k_function_cuda.h:916] TopKOP failed as could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to calculate temp_storage_bytes, status: invalid device function
[11/17 17:36:40] ppdet.engine INFO: Eval iter: 0
[11/17 17:36:40] ppdet.engine INFO: Total sample number: 8, averge FPS: 0.07079355289300246

**Comment by Hezy0204** [comment]
> 有修改什么东西嘛 看着是因为输入的尺寸不对导致的吧，

在最新发布的ppyoloe-R和ppyoloe-sod两个项目中遇到了同样的问题。报错形式类似上边两位同学，tensor超出下界，初步分析不像单纯是输入图像尺寸问题，超下界数值异常。另外我配置环境过程严格参照项目文档进行，编译测试都通过了，在运行项目文档内对脊椎数据训练demo时出错，同时用develop分支运行ppyoloe-sod项目训练代码时有同样问题。
复现环境 Environment
PaddlePaddle: gpu 2.3.2
cuda 10.2 cudnn 7.6.5 显卡 3060ti
PaddleDetection: develop
运行手把手教你使用PP-YOLOE-R进行旋转框检测文档脊椎数据单卡训练命令
python tools/train.py -c configs/rotate/ppyoloe_r/ppyoloe_r_crn_s_3x_spine.yml --eval
错误日志
(paddle-env) genius@MyUbuntu:~/Projects/PaddleDetection$ python tools/train.py -c configs/rotate/ppyoloe_r/ppyoloe_r_crn_s_3x_spine.yml --eval
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
W1121 09:29:13.317978 13138 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.8, Runtime API Version: 10.2
W1121 09:29:13.322356 13138 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
[11/21 09:29:14] ppdet.utils.checkpoint INFO: The shape [15] in pretrained weight yolo_head.pred_cls.0.bias is unmatched with the shape [9] in model yolo_head.pred_cls.0.bias. And the weight yolo_head.pred_cls.0.bias will not be loaded
[11/21 09:29:14] ppdet.utils.checkpoint INFO: The shape [15, 384, 3, 3] in pretrained weight yolo_head.pred_cls.0.weight is unmatched with the shape [9, 384, 3, 3] in model yolo_head.pred_cls.0.weight. And the weight yolo_head.pred_cls.0.weight will not be loaded
[11/21 09:29:14] ppdet.utils.checkpoint INFO: The shape [15] in pretrained weight yolo_head.pred_cls.1.bias is unmatched with the shape [9] in model yolo_head.pred_cls.1.bias. And the weight yolo_head.pred_cls.1.bias will not be loaded
[11/21 09:29:14] ppdet.utils.checkpoint INFO: The shape [15, 192, 3, 3] in pretrained weight yolo_head.pred_cls.1.weight is unmatched with the shape [9, 192, 3, 3] in model yolo_head.pred_cls.1.weight. And the weight yolo_head.pred_cls.1.weight will not be loaded
[11/21 09:29:14] ppdet.utils.checkpoint INFO: The shape [15] in pretrained weight yolo_head.pred_cls.2.bias is unmatched with the shape [9] in model yolo_head.pred_cls.2.bias. And the weight yolo_head.pred_cls.2.bias will not be loaded
[11/21 09:29:14] ppdet.utils.checkpoint INFO: The shape [15, 96, 3, 3] in pretrained weight yolo_head.pred_cls.2.weight is unmatched with the shape [9, 96, 3, 3] in model yolo_head.pred_cls.2.weight. And the weight yolo_head.pred_cls.2.weight will not be loaded
[11/21 09:29:14] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/genius/.cache/paddle/weights/ppyoloe_r_crn_s_3x_dota_ms.pdparams
Traceback (most recent call last):
  File "tools/train.py", line 188, in <module>
    main()
  File "tools/train.py", line 184, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 137, in run
    trainer.train(FLAGS.eval)
  File "/home/genius/Projects/PaddleDetection/ppdet/engine/trainer.py", line 527, in train
    outputs = model(data)
  File "/home/genius/Anaconda/envs/paddle-env/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/genius/Anaconda/envs/paddle-env/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/genius/Projects/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 59, in forward
    out = self.get_loss()
  File "/home/genius/Projects/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 127, in get_loss
    return self._forward()
  File "/home/genius/Projects/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 91, in _forward
    yolo_losses = self.yolo_head(neck_feats, self.inputs)
  File "/home/genius/Anaconda/envs/paddle-env/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/genius/Anaconda/envs/paddle-env/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/genius/Projects/PaddleDetection/ppdet/modeling/heads/ppyoloe_r_head.py", line 177, in forward
    return self.forward_train(feats, targets)
  File "/home/genius/Projects/PaddleDetection/ppdet/modeling/heads/ppyoloe_r_head.py", line 182, in forward_train
    anchor_points, stride_tensor, num_anchors_list = self._generate_anchors(
  File "/home/genius/Projects/PaddleDetection/ppdet/modeling/heads/ppyoloe_r_head.py", line 165, in _generate_anchors
    paddle.full(
  File "/home/genius/Anaconda/envs/paddle-env/lib/python3.8/site-packages/paddle/tensor/creation.py", line 500, in full
    return fill_constant(shape=shape, dtype=dtype, value=fill_value, name=name)
  File "/home/genius/Anaconda/envs/paddle-env/lib/python3.8/site-packages/paddle/fluid/layers/tensor.py", line 783, in fill_constant
    _C_ops.fill_constant(out, 'value',
ValueError: (InvalidArgument) Each value of attribute 'shape' is expected to be no less than 0. But recieved: shape[1] = -1131213806; shape = [1, -1131213806, 1].
  [Hint: Expected shape[i] >= 0, but received shape[i]:-1131213806 < 0:0.] (at /paddle/paddle/fluid/operators/fill_constant_op.cc:36)
  [operator < fill_constant > error]

**Comment by Hezy0204** [comment]
> 

代码完全未改动，yml文件按照项目文件内要求粘贴的，只修改了bs和lr结果是一样的。另外补充复现环境信息：Ubuntu18.04，python 3.8.13

**Comment by hua1024** [comment]
同发现，蹲一下

**Comment by Hezy0204** [comment]
> 

我隐约觉得是一个底层的问题，我排故发现是paddle貌似不支持tensor直接用*（乘法符号）相乘，貌似只支持matmul

**Comment by pcycccccc** [comment]
> 切到2.3版本就没可以
> 
> loading annotations into memory... Done (t=0.01s) creating index... index created! W1117 17:29:02.457630 56089 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 10.2 W1117 17:29:02.465134 56089 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2. [11/17 17:29:02] ppdet.utils.download INFO: Downloading ESNet_x0_75_pretrained.pdparams from https://paddledet.bj.bcebos.com/models/pretrained/ESNet_x0_75_pretrained.pdparams 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 14101/14101 [05:40<00:00, 41.40KB/s] [11/17 17:34:44] ppdet.utils.checkpoint INFO: ['_fc.bias', '_fc.weight', '_last_conv._batch_norm._mean', '_last_conv._batch_norm._variance', '_last_conv._batch_norm.bias', '_last_conv._batch_norm.weight', '_last_conv._conv.weight', 'last_conv.weight'] in pretrained weight is not used in the model, and its will not be loaded [11/17 17:34:44] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/appuser/.cache/paddle/weights/ESNet_x0_75_pretrained.pdparams [11/17 17:34:47] ppdet.utils.checkpoint INFO: Save checkpoint: output/picodet_s_320_coco loading annotations into memory... Done (t=0.00s) creating index... index created! loading annotations into memory... Done (t=0.00s) creating index... index created! E1117 17:36:40.200119 56089 top_k_function_cuda.h:916] TopKOP failed as could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to calculate temp_storage_bytes, status: invalid device function E1117 17:36:40.378402 56089 top_k_function_cuda.h:916] TopKOP failed as could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to calculate temp_storage_bytes, status: invalid device function E1117 17:36:40.408003 56089 top_k_function_cuda.h:916] TopKOP failed as could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to calculate temp_storage_bytes, status: invalid device function E1117 17:36:40.434123 56089 top_k_function_cuda.h:916] TopKOP failed as could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to calculate temp_storage_bytes, status: invalid device function E1117 17:36:40.459311 56089 top_k_function_cuda.h:916] TopKOP failed as could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to calculate temp_storage_bytes, status: invalid device function E1117 17:36:40.483808 56089 top_k_function_cuda.h:916] TopKOP failed as could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to calculate temp_storage_bytes, status: invalid device function E1117 17:36:40.508206 56089 top_k_function_cuda.h:916] TopKOP failed as could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to calculate temp_storage_bytes, status: invalid device function E1117 17:36:40.536990 56089 top_k_function_cuda.h:916] TopKOP failed as could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to calculate temp_storage_bytes, status: invalid device function [11/17 17:36:40] ppdet.engine INFO: Eval iter: 0 [11/17 17:36:40] ppdet.engine INFO: Total sample number: 8, averge FPS: 0.07079355289300246

请问一下你的PaddleDetection是哪个版本的？是否需要和PaddleSlim版本一致？我前几天在量化的过程中报错，后面搜索到需要将PaddleDetection和PaddleSlim版本相对应，我原本PaddleDetection是2.5，所以修改PaddleSlim到2.5 release版后，报错消失，能够量化，但是量化到一半的时候（已经跑了一段时间了）却遇到了这个问题，感觉也没咋大改配置文件
![image](https://github.com/PaddlePaddle/PaddleDetection/assets/108455796/72e81157-1d1d-4617-8a54-7abd4540262c)

**Comment by clintonfang** [comment]
> > 切到2.3版本就没可以
> > loading annotations into memory... Done (t=0.01s) creating index... index created! W1117 17:29:02.457630 56089 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 10.2 W1117 17:29:02.465134 56089 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2. [11/17 17:29:02] ppdet.utils.download INFO: Downloading ESNet_x0_75_pretrained.pdparams from https://paddledet.bj.bcebos.com/models/pretrained/ESNet_x0_75_pretrained.pdparams 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 14101/14101 [05:40<00:00, 41.40KB/s] [11/17 17:34:44] ppdet.utils.checkpoint INFO: ['_fc.bias', '_fc.weight', '_last_conv._batch_norm._mean', '_last_conv._batch_norm._variance', '_last_conv._batch_norm.bias', '_last_conv._batch_norm.weight', '_last_conv._conv.weight', 'last_conv.weight'] in pretrained weight is not used in the model, and its will not be loaded [11/17 17:34:44] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/appuser/.cache/paddle/weights/ESNet_x0_75_pretrained.pdparams [11/17 17:34:47] ppdet.utils.checkpoint INFO: Save checkpoint: output/picodet_s_320_coco loading annotations into memory... Done (t=0.00s) creating index... index created! loading annotations into memory... Done (t=0.00s) creating index... index created! E1117 17:36:40.200119 56089 top_k_function_cuda.h:916] TopKOP failed as could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to calculate temp_storage_bytes, status: invalid device function E1117 17:36:40.378402 56089 top_k_function_cuda.h:916] TopKOP failed as could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to calculate temp_storage_bytes, status: invalid device function E1117 17:36:40.408003 56089 top_k_function_cuda.h:916] TopKOP failed as could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to calculate temp_storage_bytes, status: invalid device function E1117 17:36:40.434123 56089 top_k_function_cuda.h:916] TopKOP failed as could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to calculate temp_storage_bytes, status: invalid device function E1117 17:36:40.459311 56089 top_k_function_cuda.h:916] TopKOP failed as could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to calculate temp_storage_bytes, status: invalid device function E1117 17:36:40.483808 56089 top_k_function_cuda.h:916] TopKOP failed as could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to calculate temp_storage_bytes, status: invalid device function E1117 17:36:40.508206 56089 top_k_function_cuda.h:916] TopKOP failed as could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to calculate temp_storage_bytes, status: invalid device function E1117 17:36:40.536990 56089 top_k_function_cuda.h:916] TopKOP failed as could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to calculate temp_storage_bytes, status: invalid device function [11/17 17:36:40] ppdet.engine INFO: Eval iter: 0 [11/17 17:36:40] ppdet.engine INFO: Total sample number: 8, averge FPS: 0.07079355289300246
> 
> 请问一下你的PaddleDetection是哪个版本的？是否需要和PaddleSlim版本一致？我前几天在量化的过程中报错，后面搜索到需要将PaddleDetection和PaddleSlim版本相对应，我原本PaddleDetection是2.5，所以修改PaddleSlim到2.5 release版后，报错消失，能够量化，但是量化到一半的时候（已经跑了一段时间了）却遇到了这个问题，感觉也没咋大改配置文件 ![image](https://private-user-images.githubusercontent.com/108455796/282344066-72e81157-1d1d-4617-8a54-7abd4540262c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2ODQyNzQsIm5iZiI6MTcwNTY4Mzk3NCwicGF0aCI6Ii8xMDg0NTU3OTYvMjgyMzQ0MDY2LTcyZTgxMTU3LTFkMWQtNDYxNy04YTU0LTdhYmQ0NTQwMjYyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQxNzA2MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jN2YwNzdmOGQ5YTdhMGJiM2I4YTY5YjAxMzE3NmU0OGVkYjYwNTlkYmJlZmY5ZTE5MTUyMjE3MDRhMzJhOTUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VfQvUWLeHKnTPFs5CNcjLzW0RWThAX-XEALgMwGzwfo)

PPYoloe+这个问题从2.4到2.5到2.6，全都测试过，官方提供的或自己训练好的model使用PaddleSlim的QAT量化都会出现，而在训练过程中直接加slim，无法使用混合精度训练，并且训练过程中的模型识别率几乎接近于0，并且训练一定时间一定会报错（'Termination signal' is detected by the operating system.）

**Comment by God-song** [comment]
> 几天在量化的基础上报错，后面搜索到需要将PaddleDetection和PaddleSlim版本相对应，我原来以为PaddleDetection是2.5，所以修改PaddleSlim到2.5发布版本后，报错消失，能够量化，但是量化到一半的时候（已经跑了一段时间了）却遇到了这个问题，感觉也没咋大改配

请问问题解决了吗，我也遇到一样的问题
