### ISSUE TITLE
solov2训练rle编码的COCO数据集报错“assert 'gt_poly' in sample”

### ISSUE THREAD

**Issue by kaixin-bai** [PaddlePaddle/PaddleDetection#7223]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training

### Bug描述 Describe the Bug

使用`solov2`训练COCO数据集，报错`assert 'gt_poly' in sample`。
COCO数据集格式无误，其中实例分割结果参见[此图](https://user-images.githubusercontent.com/38804949/197993131-32ca8b34-722c-4fcf-b778-fefd1f8e38fd.png)。

配置的`solov2_r101_vd_fpn_3x_coco.yml`如下，其中`../datasets/coco_detection_obj1texture.yml`可用来正确训练yolov3模型无误：
```bash
_BASE_: [
  '../datasets/coco_detection_obj1texture.yml',
  '../runtime.yml',
  '_base_/solov2_r50_fpn.yml',
  '_base_/optimizer_1x.yml',
  '_base_/solov2_reader.yml',
]
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet101_vd_pretrained.pdparams
weights: output/solov2_r101_vd_fpn_3x_obj1texture_coco/model_final
epoch: 36
use_ema: true
ema_decay: 0.9998

ResNet:
  depth: 101
  variant: d
  freeze_at: 0
  return_idx: [0,1,2,3]
  dcn_v2_stages: [1,2,3]
  num_stages: 4

SOLOv2Head:
  seg_feat_channels: 512
  stacked_convs: 4
  num_grids: [40, 36, 24, 16, 12]
  kernel_out_channels: 256
  solov2_loss: SOLOv2Loss
  mask_nms: MaskMatrixNMS
  dcn_v2_stages: [0, 1, 2, 3]

SOLOv2MaskHead:
  mid_channels: 128
  out_channels: 256
  start_level: 0
  end_level: 3
  use_dcn_in_tower: True


LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [24, 33]
  - !LinearWarmup
    start_factor: 0.
    steps: 2000

TrainReader:
  sample_transforms:
  - Decode: {}
  - Poly2Mask: {}
  - RandomResize: {interp: 1,
                     target_size: [[640, 1333], [672, 1333], [704, 1333], [736, 1333], [768, 1333], [800, 1333]],
                     keep_ratio: True}
  - RandomFlip: {}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  - Gt2Solov2Target: {num_grids: [40, 36, 24, 16, 12],
                        scale_ranges: [[1, 96], [48, 192], [96, 384], [192, 768], [384, 2048]],
                        coord_sigma: 0.2}
  batch_size: 2
  shuffle: true
  drop_last: true
```

训练命令行为：
```bash
python3 tools/train.py -c ./configs/solov2/solov2_r101_vd_fpn_3x_obj1texture_coco.yml --use_vdl=true --vdl_log_dir=vdl_dir/solov2obj1texture/scalar
```

报错信息为：
```bash
[10/29 19:35:34] reader WARNING: fail to map sample transform [Poly2Mask_b94098] with error:  and stack:
Traceback (most recent call last):
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 104, in __call__
    sample = self.apply(sample, context)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 2090, in apply
    assert 'gt_poly' in sample
AssertionError

[10/29 19:35:34] reader WARNING: fail to map sample transform [Poly2Mask_b94098] with error:  and stack:
Traceback (most recent call last):
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 104, in __call__
    sample = self.apply(sample, context)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 2090, in apply
    assert 'gt_poly' in sample
AssertionError

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/data-r10/kb/anaconda3/envs/mmdet/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/data-r10/kb/anaconda3/envs/mmdet/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/data-r10/kb/anaconda3/envs/mmdet/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 534, in _thread_loop
    batch = self._get_data()
  File "/data-r10/kb/anaconda3/envs/mmdet/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 671, in _get_data
    batch.reraise()
  File "/data-r10/kb/anaconda3/envs/mmdet/lib/python3.6/site-packages/paddle/fluid/dataloader/worker.py", line 169, in reraise
    raise self.exc_type(msg)
AssertionError: DataLoader worker(6) caught AssertionError with message:
Traceback (most recent call last):
  File "/data-r10/kb/anaconda3/envs/mmdet/lib/python3.6/site-packages/paddle/fluid/dataloader/worker.py", line 336, in _worker_loop
    batch = fetcher.fetch(indices)
  File "/data-r10/kb/anaconda3/envs/mmdet/lib/python3.6/site-packages/paddle/fluid/dataloader/fetcher.py", line 121, in fetch
    data.append(self.dataset[idx])
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/source/dataset.py", line 96, in __getitem__
    return self.transform(roidb)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/reader.py", line 60, in __call__
    raise e
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 104, in __call__
    sample = self.apply(sample, context)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 2090, in apply
    assert 'gt_poly' in sample
AssertionError


[10/29 19:35:34] reader WARNING: fail to map sample transform [Poly2Mask_b94098] with error:  and stack:
Traceback (most recent call last):
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 104, in __call__
    sample = self.apply(sample, context)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 2090, in apply
    assert 'gt_poly' in sample
AssertionError

[10/29 19:35:34] reader WARNING: fail to map sample transform [Poly2Mask_b94098] with error:  and stack:
Traceback (most recent call last):
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 104, in __call__
    sample = self.apply(sample, context)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 2090, in apply
    assert 'gt_poly' in sample
AssertionError

[10/29 19:35:34] reader WARNING: fail to map sample transform [Poly2Mask_b94098] with error:  and stack:
Traceback (most recent call last):
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 104, in __call__
    sample = self.apply(sample, context)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 2090, in apply
    assert 'gt_poly' in sample
AssertionError

[10/29 19:35:34] reader WARNING: fail to map sample transform [Poly2Mask_b94098] with error:  and stack:
Traceback (most recent call last):
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 104, in __call__
    sample = self.apply(sample, context)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 2090, in apply
    assert 'gt_poly' in sample
AssertionError

[10/29 19:35:34] reader WARNING: fail to map sample transform [Poly2Mask_b94098] with error:  and stack:
Traceback (most recent call last):
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 104, in __call__
    sample = self.apply(sample, context)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 2090, in apply
    assert 'gt_poly' in sample
AssertionError

[10/29 19:35:34] reader WARNING: fail to map sample transform [Poly2Mask_b94098] with error:  and stack:
Traceback (most recent call last):
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 104, in __call__
    sample = self.apply(sample, context)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 2090, in apply
    assert 'gt_poly' in sample
AssertionError

[10/29 19:35:34] reader WARNING: fail to map sample transform [Poly2Mask_b94098] with error:  and stack:
Traceback (most recent call last):
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 104, in __call__
    sample = self.apply(sample, context)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 2090, in apply
    assert 'gt_poly' in sample
AssertionError

[10/29 19:35:34] reader WARNING: fail to map sample transform [Poly2Mask_b94098] with error:  and stack:
Traceback (most recent call last):
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 104, in __call__
    sample = self.apply(sample, context)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 2090, in apply
    assert 'gt_poly' in sample
AssertionError
[10/29 19:35:34] reader WARNING: fail to map sample transform [Poly2Mask_b94098] with error:  and stack:
Traceback (most recent call last):
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 104, in __call__
    sample = self.apply(sample, context)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 2090, in apply
    assert 'gt_poly' in sample
AssertionError


[10/29 19:35:34] reader WARNING: fail to map sample transform [Poly2Mask_b94098] with error:  and stack:
Traceback (most recent call last):
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 104, in __call__
    sample = self.apply(sample, context)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 2090, in apply
    assert 'gt_poly' in sample
AssertionError

[10/29 19:35:34] reader WARNING: fail to map sample transform [Poly2Mask_b94098] with error:  and stack:
Traceback (most recent call last):
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 104, in __call__
    sample = self.apply(sample, context)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 2090, in apply
    assert 'gt_poly' in sample
AssertionError

[10/29 19:35:34] reader WARNING: fail to map sample transform [Poly2Mask_b94098] with error:  and stack:
Traceback (most recent call last):
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 104, in __call__
    sample = self.apply(sample, context)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 2090, in apply
    assert 'gt_poly' in sample
AssertionError

[10/29 19:35:34] reader WARNING: fail to map sample transform [Poly2Mask_b94098] with error:  and stack:
Traceback (most recent call last):
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 104, in __call__
    sample = self.apply(sample, context)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 2090, in apply
    assert 'gt_poly' in sample
AssertionError

[10/29 19:35:34] reader WARNING: fail to map sample transform [Poly2Mask_b94098] with error:  and stack:
Traceback (most recent call last):
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 104, in __call__
    sample = self.apply(sample, context)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/transform/operators.py", line 2090, in apply
    assert 'gt_poly' in sample
AssertionError

[10/29 19:35:40] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/kb/.cache/paddle/weights/ResNet101_vd_pretrained.pdparams
Traceback (most recent call last):
  File "tools/train.py", line 172, in <module>
    main()
  File "tools/train.py", line 168, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 132, in run
    trainer.train(FLAGS.eval)
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/engine/trainer.py", line 453, in train
    for step_id, data in enumerate(self.loader):
  File "/data-r10/kb/Projects/SynDataGen/PaddleDetection/ppdet/data/reader.py", line 209, in __next__
    return next(self.loader)
  File "/data-r10/kb/anaconda3/envs/mmdet/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 746, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)


```

### 复现环境 Environment

- ubuntu 18.04
- paddle-bfloat           0.1.7
- paddlepaddle-gpu        2.3.2
- paddleslim              2.2.1
- paddlex                 2.1.0

```bash
W1029 19:35:34.560168 28338 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.6, Runtime API Version: 10.2
W1029 19:35:34.567206 28338 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
```

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by kaixin-bai** [comment]
当前paddledetection是否支持is_crowd: True即rle格式的实例分割？如支持，需额外做什么设置？我这里的COCO数据集的实例分割不是使用polygon而是rle

**Comment by kaixin-bai** [comment]
调试更新：
在`PaddleDetection/ppdet/data/source/coco.py`的[206](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/ppdet/data/source/coco.py#L206)中原本的`gt_rec`其中是有`gt_poly`的，后面经过这段的处理就没有了，原因是在配置文件的`data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']`中没有设置`'gt_poly'`，加上后变成`data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd', 'gt_poly']`.

从源码来看，不设置`gt_poly`的话，会默认认为数据集中无`segmentation`，所以实例分割任务必须要设置这个。
新的问题为`lr`变为0.00，`loss`变为`nan`：
```bash
[11/01 17:15:42] ppdet.engine INFO: Epoch: [0] [  0/900] learning_rate: 0.000000 loss_ins: nan loss_cate: 0.000704 loss: nan eta: 17:16:31 batch_cost: 1.9195 data_cost: 0.0018 ips: 0.5210 images/s
```
已经按照FAQ的建议更改了配置文件中的学习率从0.01到0.00125甚至到0.000125了，结果`loss`还是`nan`：
```bash
LearningRate:
  base_lr: 0.000125  # 0.01
```

继续想一下是什么原因……
