### ISSUE TITLE
ERROR 2022-11-02 08:42:32,186 launch_utils.py:604] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.

### ISSUE THREAD

**Issue by qingyou97** [PaddlePaddle/PaddleDetection#7252]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用paddledetection下的ppyoloe进行训练，后出现这个问题

> Traceback (most recent call last):
  File "tools/train.py", line 172, in <module>
    main()
  File "tools/train.py", line 168, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 132, in run
    trainer.train(FLAGS.eval)
  File "/mnt/PaddleDetection/ppdet/engine/trainer.py", line 453, in train
    for step_id, data in enumerate(self.loader):
  File "/mnt/PaddleDetection/ppdet/data/reader.py", line 209, in __next__
    return next(self.loader)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 697, in __next__
    data = self._reader.read_next_var_list()
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/multiprocess_utils.py", line 134, in __handler__
    core._throw_error_if_process_failed()
SystemError: (Fatal) DataLoader process (pid 1104) exited is killed by signal: Killed. (at /paddle/paddle/fluid/imperative/data_loader.cc:181)

> INFO 2022-11-02 08:42:32,186 launch_utils.py:341] terminate all the procs

> ERROR 2022-11-02 08:42:32,186 launch_utils.py:604] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
> INFO 2022-11-02 08:42:36,191 launch_utils.py:341] terminate all the procs
> INFO 2022-11-02 08:42:36,191 launch.py:311] Local processes completed.

rank是代表显卡出现问题嘛？我是用的docker，只有一颗gpu，请问该怎么解决呢？

**Comment by wangxinxin08** [comment]
只有单卡的话，不建议使用paddle.distributed.launch启动，直接使用```python tools/train.py -c configs/xxx/xxx```启动训练即可
