### ISSUE TITLE
TypeError: 'numpy.float32' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by Syunraii** [PaddlePaddle/PaddleDetection#7287]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

参考安装文档 安装2.3.2 paddlepaddle-gpu
```
PS D:\Syunraii\PaddlePaddle> python
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ...
W1108 10:56:42.732224  8568 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.6, Runtime API Version: 10.2
W1108 10:56:42.738245  8568 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
>>> exit()
PS D:\Syunraii\PaddlePaddle> python -c "import paddle; print(paddle.__version__)"
2.3.2
```

安装PaddleDetection
```
PS D:\Syunraii\PaddlePaddle\PaddleDetection> python ppdet/modeling/tests/test_architectures.py
W1108 10:59:05.094449  5012 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.6, Runtime API Version: 10.2
W1108 10:59:05.106418  5012 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
.......
----------------------------------------------------------------------
Ran 7 tests in 1.252s

OK
PS D:\Syunraii\PaddlePaddle\PaddleDetection> 
```

到 '快速体验' 步骤中，执行
出现错误,log如下:
```
PS D:\Syunraii\PaddlePaddle\PaddleDetection> python tools/infer.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml -o use_gpu=true weights=https://paddledet.bj.bcebos.com/models/ppyolo_r50vd_dcn_1x_coco.pdparams --infer_img=demo/000000014439.jpg
W1108 10:59:50.621414 12624 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.6, Runtime API Version: 10.2
W1108 10:59:50.627621 12624 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
[11/08 10:59:52] ppdet.utils.checkpoint INFO: Finish loading model weights: C:\Users\x/.cache/paddle/weights\ppyolo_r50vd_dcn_1x_coco.pdparams
[11/08 10:59:52] ppdet.data.source.category WARNING: anno_file 'dataset/coco\annotations/instances_val2017.json' is None or not set or not exist, please recheck TrainDataset/EvalDataset/TestDataset.anno_path, otherwise the default categories will be used by metric_type.
[11/08 10:59:52] ppdet.data.source.category WARNING: metric_type: COCO, load default categories of COCO.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.08it/s]
Traceback (most recent call last):
  File "D:\Syunraii\PaddlePaddle\PaddleDetection\tools\infer.py", line 226, in <module>
    main()
  File "D:\Syunraii\PaddlePaddle\PaddleDetection\tools\infer.py", line 222, in main
    run(FLAGS, cfg)
  File "D:\Syunraii\PaddlePaddle\PaddleDetection\tools\infer.py", line 182, in run
    trainer.predict(
  File "D:\Syunraii\PaddlePaddle\PaddleDetection\ppdet\engine\trainer.py", line 924, in predict
    image = visualize_results(
  File "D:\Syunraii\PaddlePaddle\PaddleDetection\ppdet\utils\visualizer.py", line 44, in visualize_results
    image = draw_bbox(image, im_id, catid2name, bbox_res, threshold)
  File "D:\Syunraii\PaddlePaddle\PaddleDetection\ppdet\utils\visualizer.py", line 106, in draw_bbox
    draw.line(
  File "D:\Syunraii\Env\Python\Python310\lib\site-packages\PIL\ImageDraw.py", line 171, in line
    ink = self._getink(fill)[0]
  File "D:\Syunraii\Env\Python\Python310\lib\site-packages\PIL\ImageDraw.py", line 129, in _getink
    ink = self.draw.draw_ink(ink)
TypeError: 'numpy.float32' object cannot be interpreted as an integer
```

### 复现环境 Environment

-OS:Win10
-PaddlePaddle:2.3.2
-PaddleDetection:release/2.5
-Python:3.10.6
-CUDA:10.2
-cuDNN:7.6.5.32
-GCC: mingw 8.1.0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Syunraii** [comment]
参考 [#2901](https://github.com/PaddlePaddle/PaddleDetection/issues/2901 )得知deprecated

``` 
DeprecationWarning: an integer is required (got type numpy.float32). Implicit conversion to integers using int is deprecated, and may be removed in a future version of Python.
ink = self.draw.draw_ink(ink)
```

修改权重为 
weight=https://paddledet.bj.bcebos.com/models/ppyolov2_r50vd_dcn_365e_coco.pdparams

输入:
```
python tools/infer.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml -o use_gpu=true weights=https://paddlemodels.bj.bcebos.com/object_detection/ppyolo.pdparams --infer_img=demo/000000014439.jpg
```

输出日志如下:
```
[11/08 11:22:14] ppdet.utils.checkpoint INFO: Finish loading model weights: C:\Users\x/.cache/paddle/weights\ppyolov2_r50vd_dcn_365e_coco.pdparams
[11/08 11:22:14] ppdet.data.source.category WARNING: anno_file 'dataset/coco\annotations/instances_val2017.json' is None or not set or not exist, please recheck 
TrainDataset/EvalDataset/TestDataset.anno_path, otherwise the default categories will be used by metric_type.                                                    0:01<00:00,  1.37s/it]
[11/08 11:22:14] ppdet.data.source.category WARNING: metric_type: COCO, load default categories of COCO.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.37s/it]
[11/08 11:22:15] ppdet.engine INFO: Detection bbox results save in output\000000014439.jpg
```

输出结果(没有任何检测，应该是错误的):

![000000014439](https://user-images.githubusercontent.com/79300447/200469880-0fbc5260-d310-4850-9331-41e42f44cb98.jpg)



请更新安装文档

**Comment by Syunraii** [comment]
参考[PaddlePaddle快速安装文档](https://www.paddlepaddle.org.cn/install/quick)
对比[安装说明](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/docs/tutorials/INSTALL_cn.md)


尝试将paddlepaddle-gpu降级2.2.2 , 将python3.10降级为3.9

**Comment by Syunraii** [comment]
降级python 3.9.13后正常 
应该是paddledetection需要安装的是2.2.2版本的paddlepaddle

**Comment by Zhang-Junzhi** [comment]
这个问题不应当关闭。
飞桨不支持Python 3.10，属于飞桨要解决的问题。

**Comment by Zhang-Junzhi** [comment]
飞桨官方明确写明了2.4版支持Python 3.10，而实际上我用的2.4和Python 3.10.9，结果报了上面的错，跟官方描述不符。是BUG。

**Comment by Zhang-Junzhi** [comment]
重开了此问题。见：
https://github.com/PaddlePaddle/PaddleDetection/issues/7799
