### ISSUE TITLE
casacade + dcn 多尺度推理时报异常： File "/home/work_space/PaddleDetection/ppdet/data/reader.py", line 94, in __call__     for k in data[0].keys(): AttributeError: 'list' object has no attribute 'keys' 

### ISSUE THREAD

**Issue by aiyodiulehuner** [PaddlePaddle/PaddleDetection#7322]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/python3.7.0/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3.7.0/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 530, in _thread_loop
    batch = self._get_data()
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 667, in _get_data
    batch.reraise()
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 169, in reraise
    raise self.exc_type(msg)
AttributeError: DataLoader worker(1) caught AttributeError with message:
Traceback (most recent call last):
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 329, in _worker_loop
    batch = fetcher.fetch(indices)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 134, in fetch
    data = self.collate_fn(data)
  File "/home/work_space/PaddleDetection/ppdet/data/reader.py", line 94, in __call__
    for k in data[0].keys():
AttributeError: 'list' object has no attribute 'keys'

[11/14 04:57:07] ppdet.utils.checkpoint INFO: Finish loading model weights: output/cascade_rcnn_dcn_r50_fpn_2x_coco_lbfh_ori_mutil_scale/model_final.pdparams
Traceback (most recent call last):
  File "tools/eval.py", line 193, in <module>
    main()
  File "tools/eval.py", line 189, in main
    run(FLAGS, cfg)
  File "tools/eval.py", line 154, in run
    trainer.evaluate()
  File "/home/work_space/PaddleDetection/ppdet/engine/trainer.py", line 621, in evaluate
    self._eval_with_loader(self.loader)
  File "/home/work_space/PaddleDetection/ppdet/engine/trainer.py", line 583, in _eval_with_loader
    for step_id, data in enumerate(loader):
  File "/home/work_space/PaddleDetection/ppdet/data/reader.py", line 209, in __next__
    return next(self.loader)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 742, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

**Comment by XYZ-916** [comment]
看上去应该是数据处理出了问题，请问您做了哪些改动？data[0]是list，但是需要是dict，可以debug看下哪里出了问题。

**Comment by aiyodiulehuner** [comment]
数据没有做改动，只是配置文件换成了mutil_scale，不改多尺度正常推理




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年11月14日 19:37 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleDetection] casacade + dcn 多尺度推理时报异常： File "/home/work_space/PaddleDetection/ppdet/data/reader.py", line 94, in __call__     for k in data[0].keys(): AttributeError: 'list' object has no attribute 'keys'  (Issue #7322) |

看上去应该是数据处理出了问题，请问您做了哪些改动？data[0]是list，但是需要是dict，可以debug看下哪里出了问题。
