### ISSUE TITLE
ppyoloe_r 训练报错

### ISSUE THREAD

**Issue by mrljwlm** [PaddlePaddle/PaddleDetection#7324]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用了最新的develop代码训练ppyoloe_r，config 文件为 ppyoloe_r_crn_m_3x_dota_ms.yml
报错信息：
```
[INFO   ] callbacks:on_step_end:144 - Epoch: [0] [0/1] learning_rate: 0.000000 loss: 2.697993 loss_cls: 1.812733 loss_iou: 0.282950 loss_dfl: 3.557695 eta: 0:00:33 batch_cost: 1.6730 data_cost: 0.0000 ips: 9.5636 images/s
[11/14 13:35:51] train INFO: Epoch: [0] [0/1] learning_rate: 0.000000 loss: 2.697993 loss_cls: 1.812733 loss_iou: 0.282950 loss_dfl: 3.557695 eta: 0:00:33 batch_cost: 1.6730 data_cost: 0.0000 ips: 9.5636 images/s
[INFO   ] callbacks:on_step_end:144 - Epoch: [1] [0/1] learning_rate: 0.000500 loss: 2.756227 loss_cls: 1.893280 loss_iou: 0.272531 loss_dfl: 3.632372 eta: 0:00:22 batch_cost: 1.1610 data_cost: 0.1560 ips: 13.7812 images/s
[11/14 13:35:52] train INFO: Epoch: [1] [0/1] learning_rate: 0.000500 loss: 2.756227 loss_cls: 1.893280 loss_iou: 0.272531 loss_dfl: 3.632372 eta: 0:00:22 batch_cost: 1.1610 data_cost: 0.1560 ips: 13.7812 images/s
[11/14 13:35:53] ppdet.utils.checkpoint INFO: Save checkpoint: F:\DOTA_dataset\xdx\train_ppyoloe-r
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Program Files\Python\Python39\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python\Python39\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python\Python39\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 212, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices,
  File "C:\Program Files\Python\Python39\lib\site-packages\paddle\fluid\dataloader\fetcher.py", line 134, in fetch
    data = self.collate_fn(data)
  File "I:\DeepLearningSystem\PaddleDetection\ppdet\data\reader.py", line 91, in __call__
    batch_data = default_collate_fn(data)
  File "I:\DeepLearningSystem\PaddleDetection\ppdet\data\utils.py", line 60, in default_collate_fn
    return {
  File "I:\DeepLearningSystem\PaddleDetection\ppdet\data\utils.py", line 61, in <dictcomp>
    key: default_collate_fn([d[key] for d in batch])
  File "I:\DeepLearningSystem\PaddleDetection\ppdet\data\utils.py", line 52, in default_collate_fn
    batch = np.stack(batch, axis=0)
  File "<__array_function__ internals>", line 5, in stack
  File "C:\Program Files\Python\Python39\lib\site-packages\numpy\core\shape_base.py", line 427, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape
```

**Comment by wangxinxin08** [comment]
可以发下修改后的配置文件，以及使用的数据集看下

**Comment by mrljwlm** [comment]
我修改了一下ppyoloe_r_reader.yml 增加了个参数问题就解决了
```
EvalReader:
  sample_transforms:
    - Decode: {}
    - Poly2Array: {}
    - RResize: {target_size: *image_size, keep_ratio: True, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_transforms:
    - PadBatch: {pad_to_stride: 32}
  batch_size: 2
  collate_batch: false       #<----------------增加的参数
```
