### ISSUE TITLE
Ambiguity weight backbone.res5.res5a.branch2a.norm._mean loaded, it matches at least bbox_head.head.res5.res5a.branch2a.norm._mean and backbone.res5.res5a.branch2a.norm._mean in the model

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleDetection#7331]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training

### Bug描述 Describe the Bug

`python tools/train.py -c configs/faster_rcnn/faster_rcnn_r34_vd_fpn_1x_VOC.yml --eval -o use_gpu=true`

```

W1114 23:07:29.199206 18108 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.6
W1114 23:07:30.581168 18108 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
[11/14 23:07:31] ppdet.utils.checkpoint INFO: The shape [512, 256, 3, 3] in pretrained weight backbone.res5.res5a.branch2a.conv.weight is unmatched with the shape [512, 1024, 1, 1] in model bbox_head.head.res5.res5a.branch2a.conv.weight. And the weight backbone.res5.res5a.branch2a.conv.weight will not be loaded
Traceback (most recent call last):
  File "tools/train.py", line 172, in <module>
    main()
  File "tools/train.py", line 168, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 129, in run
    trainer.load_weights(cfg.pretrain_weights)
  File "D:\0SDXX\PaddleDetection\ppdet\engine\trainer.py", line 375, in load_weights
    load_pretrain_weight(self.model, weights)
  File "D:\0SDXX\PaddleDetection\ppdet\utils\checkpoint.py", line 215, in load_pretrain_weight
    param_state_dict = match_state_dict(model_dict, param_state_dict)
  File "D:\0SDXX\PaddleDetection\ppdet\utils\checkpoint.py", line 194, in match_state_dict
    weight_key]))
ValueError: Ambiguity weight backbone.res5.res5a.branch2a.norm._mean loaded, it matches at least bbox_head.head.res5.res5a.branch2a.norm._mean and backbone.res5.res5a.branch2a.norm._mean in the model
```

### 复现环境 Environment

win11
python3.7
paddlepaddle-gpu   2.3.2.post116
paddledet          2.5.0
```

├── annotations
│   ├── road0.xml
│   ├── road1.xml
│   ├── road10.xml
│   |   ...
├── images
│   ├── road0.jpg
│   ├── road1.jpg
│   ├── road2.jpg
│   |   ...
├── label_list.txt
├── test.txt
├── train.txt
└── valid.txt
```
`pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet34_vd_pretrained.pdparams
`
### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
faster_rcnn_r34_vd_fpn_1x_coco.yml 测试过无误，还改动了什么请说明。

**Comment by monkeycc** [comment]
应该配置错误,已解决
