### ISSUE TITLE
ValueError: label should not out of bound, but gotTensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,        [3]

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleDetection#7340]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

```
 python tools/train.py -c configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.yml --eval -o use_gpu=true


D:\anaconda31114\envs\PaddleDetection\lib\site-packages\paddle\vision\transforms\functional_pil.py:36: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  'nearest': Image.NEAREST,
D:\anaconda31114\envs\PaddleDetection\lib\site-packages\paddle\vision\transforms\functional_pil.py:37: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  'bilinear': Image.BILINEAR,
D:\anaconda31114\envs\PaddleDetection\lib\site-packages\paddle\vision\transforms\functional_pil.py:38: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  'bicubic': Image.BICUBIC,
D:\anaconda31114\envs\PaddleDetection\lib\site-packages\paddle\vision\transforms\functional_pil.py:39: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead.
  'box': Image.BOX,
D:\anaconda31114\envs\PaddleDetection\lib\site-packages\paddle\vision\transforms\functional_pil.py:40: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  'lanczos': Image.LANCZOS,
D:\anaconda31114\envs\PaddleDetection\lib\site-packages\paddle\vision\transforms\functional_pil.py:41: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead.
  'hamming': Image.HAMMING
Warning: Unable to use JDE/FairMOT/ByteTrack, please install lap, for example: `pip install lap`, see https://github.com/gatagat/lap
W1115 22:43:45.619787  6272 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.2
W1115 22:43:45.635514  6272 device_context.cc:465] device: 0, cuDNN Version: 8.2.
[11/15 22:43:48] ppdet.utils.checkpoint INFO: Finish loading model weights: C:\Users\monke/.cache/paddle/weights\ResNet50_cos_pretrained.pdparams
Traceback (most recent call last):
  File "tools/train.py", line 172, in <module>
    main()
  File "tools/train.py", line 168, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 132, in run
    trainer.train(FLAGS.eval)
  File "D:\0SDXX\PaddleDetection\ppdet\engine\trainer.py", line 506, in train
    outputs = model(data)
  File "D:\anaconda31114\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\anaconda31114\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\0SDXX\PaddleDetection\ppdet\modeling\architectures\meta_arch.py", line 59, in forward
    out = self.get_loss()
  File "D:\0SDXX\PaddleDetection\ppdet\modeling\architectures\faster_rcnn.py", line 95, in get_loss
    rpn_loss, bbox_loss = self._forward()
  File "D:\0SDXX\PaddleDetection\ppdet\modeling\architectures\faster_rcnn.py", line 78, in _forward
    self.inputs)
  File "D:\anaconda31114\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\anaconda31114\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\0SDXX\PaddleDetection\ppdet\modeling\heads\bbox_head.py", line 261, in forward
    loss_normalize_pos=self.loss_normalize_pos)
  File "D:\0SDXX\PaddleDetection\ppdet\modeling\heads\bbox_head.py", line 299, in get_loss
    input=scores, label=tgt_labels, reduction='mean')
  File "D:\anaconda31114\envs\PaddleDetection\lib\site-packages\paddle\nn\functional\loss.py", line 1662, in cross_entropy
    format(label_max))
ValueError: label should not out of bound, but gotTensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
       [3])
```

```

metric: VOC
map_type: 11point
num_classes: 1

TrainDataset:
  !VOCDataSet
    dataset_dir: F:/00Biaozhu/
    anno_path: train_list.txt
    label_list: labels.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

EvalDataset:
  !VOCDataSet
    dataset_dir: F:/00Biaozhu/
    anno_path: val_list.txt
    label_list: labels.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

TestDataset:
  !ImageFolder
    anno_path: F:/00Biaozhu/labels.txt

```

**Comment by monkeycc** [comment]
num_classes 标签错误
