### ISSUE TITLE
linux test_architectures.py 报错,TypeError: __init__() got an unexpected keyword argument 'post_threshold'

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleDetection#7369]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

deepin
cuda 11.6
cudnn 8.4

最新的paddle和PaddleDetection

```
python ppdet/modeling/tests/test_architectures.py

W1119 09:57:22.097754 12773 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.6
W1119 09:57:22.100551 12773 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
...E.EEEE
======================================================================
ERROR: test_trainer (__main__.TestPPYOLOv2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 35, in test_trainer
    trainer = ppdet.engine.Trainer(cfg, mode='test')
  File "/home/AI/anaconda3/envs/PaddleDetection/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/engine/trainer.py", line 88, in __init__
    self.model = create(cfg.architecture)
  File "/home/AI/anaconda3/envs/PaddleDetection/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/core/workspace.py", line 275, in create
    cls_kwargs[k] = create(target_key)
  File "/home/AI/anaconda3/envs/PaddleDetection/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/core/workspace.py", line 269, in create
    cls_kwargs[k] = create(inject_name)
  File "/home/AI/anaconda3/envs/PaddleDetection/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/core/workspace.py", line 283, in create
    return cls(**cls_kwargs)
TypeError: __init__() got an unexpected keyword argument 'nms_threshold'

======================================================================
ERROR: test_trainer (__main__.TestYOLOv3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 35, in test_trainer
    trainer = ppdet.engine.Trainer(cfg, mode='test')
  File "/home/AI/anaconda3/envs/PaddleDetection/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/engine/trainer.py", line 88, in __init__
    self.model = create(cfg.architecture)
  File "/home/AI/anaconda3/envs/PaddleDetection/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/core/workspace.py", line 275, in create
    cls_kwargs[k] = create(target_key)
  File "/home/AI/anaconda3/envs/PaddleDetection/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/core/workspace.py", line 269, in create
    cls_kwargs[k] = create(inject_name)
  File "/home/AI/anaconda3/envs/PaddleDetection/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/core/workspace.py", line 283, in create
    return cls(**cls_kwargs)
TypeError: __init__() got an unexpected keyword argument 'post_threshold'

======================================================================
ERROR: test_trainer (__main__.TestYOLOv5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 35, in test_trainer
    trainer = ppdet.engine.Trainer(cfg, mode='test')
  File "/home/AI/anaconda3/envs/PaddleDetection/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/engine/trainer.py", line 88, in __init__
    self.model = create(cfg.architecture)
  File "/home/AI/anaconda3/envs/PaddleDetection/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/core/workspace.py", line 246, in create
    cls_kwargs.update(cls.from_config(config, **kwargs))
  File "/home/AI/anaconda3/envs/PaddleDetection/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/modeling/architectures/yolov5.py", line 64, in from_config
    yolo_head = create(cfg['yolo_head'], **kwargs)
  File "/home/AI/anaconda3/envs/PaddleDetection/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/core/workspace.py", line 269, in create
    cls_kwargs[k] = create(inject_name)
  File "/home/AI/anaconda3/envs/PaddleDetection/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/core/workspace.py", line 283, in create
    return cls(**cls_kwargs)
TypeError: __init__() got an unexpected keyword argument 'post_threshold'

======================================================================
ERROR: test_trainer (__main__.TestYOLOv6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 35, in test_trainer
    trainer = ppdet.engine.Trainer(cfg, mode='test')
  File "/home/AI/anaconda3/envs/PaddleDetection/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/engine/trainer.py", line 88, in __init__
    self.model = create(cfg.architecture)
  File "/home/AI/anaconda3/envs/PaddleDetection/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/core/workspace.py", line 246, in create
    cls_kwargs.update(cls.from_config(config, **kwargs))
  File "/home/AI/anaconda3/envs/PaddleDetection/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/modeling/architectures/yolov5.py", line 64, in from_config
    yolo_head = create(cfg['yolo_head'], **kwargs)
  File "/home/AI/anaconda3/envs/PaddleDetection/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/core/workspace.py", line 269, in create
    cls_kwargs[k] = create(inject_name)
  File "/home/AI/anaconda3/envs/PaddleDetection/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/core/workspace.py", line 283, in create
    return cls(**cls_kwargs)
TypeError: __init__() got an unexpected keyword argument 'post_threshold'

======================================================================
ERROR: test_trainer (__main__.TestYOLOv7)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 35, in test_trainer
    trainer = ppdet.engine.Trainer(cfg, mode='test')
  File "/home/AI/anaconda3/envs/PaddleDetection/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/engine/trainer.py", line 88, in __init__
    self.model = create(cfg.architecture)
  File "/home/AI/anaconda3/envs/PaddleDetection/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/core/workspace.py", line 246, in create
    cls_kwargs.update(cls.from_config(config, **kwargs))
  File "/home/AI/anaconda3/envs/PaddleDetection/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/modeling/architectures/yolov5.py", line 64, in from_config
    yolo_head = create(cfg['yolo_head'], **kwargs)
  File "/home/AI/anaconda3/envs/PaddleDetection/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/core/workspace.py", line 269, in create
    cls_kwargs[k] = create(inject_name)
  File "/home/AI/anaconda3/envs/PaddleDetection/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/core/workspace.py", line 283, in create
    return cls(**cls_kwargs)
TypeError: __init__() got an unexpected keyword argument 'post_threshold'

----------------------------------------------------------------------
Ran 9 tests in 1.382s

FAILED (errors=5)

```

**Comment by nemonameless** [comment]
单测继承的时候，MatrixNMS和MultiClassNMS不一致问题，已修复，本身也不影响使用。
PaddleYOLO的问题请提问在 https://github.com/PaddlePaddle/PaddleYOLO/issues
