### ISSUE TITLE
PaddleDetection训练数据提示Target out of upper bound,请教如何处理？

### ISSUE THREAD

**Issue by koksoft** [PaddlePaddle/PaddleDetection#7371]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

win10+英伟达3080显卡，训练数据报错。如果use_gpu=false，关闭gpu就正常的

执行命令：python tools/train.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml -o use_gpu=true

信息提示如下

[11/18 16:16:14] ppdet.data.source.mot INFO: MOT dataset summary:
[11/18 16:16:14] ppdet.data.source.mot INFO: OrderedDict([('mot16.train', 55)])
[11/18 16:16:14] ppdet.data.source.mot INFO: Total images: 600
[11/18 16:16:14] ppdet.data.source.mot INFO: Image start index: OrderedDict([('mot16.train', 0)])
[11/18 16:16:14] ppdet.data.source.mot INFO: Total identities: 56
[11/18 16:16:14] ppdet.data.source.mot INFO: Identity start index: OrderedDict([('mot16.train', 0)])
W1118 16:16:15.058755 10392 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.6
W1118 16:16:15.086740 10392 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
[11/18 16:16:16] ppdet.utils.checkpoint INFO: The shape [14455] in pretrained weight reid.classifier.bias is unmatched with the shape [56] in model reid.classifier.bias. And the weight reid.classifier.bias will not be loaded
[11/18 16:16:16] ppdet.utils.checkpoint INFO: The shape [128, 14455] in pretrained weight reid.classifier.weight is unmatched with the shape [128, 56] in model reid.classifier.weight. And the weight reid.classifier.weight will not be loaded
[11/18 16:16:16] ppdet.utils.checkpoint INFO: Finish loading model weights: C:\Users\Administrator/.cache/paddle/weights\fairmot_dla34_crowdhuman_pretrained.pdparams
[11/18 16:16:26] ppdet.engine INFO: Epoch: [0] [ 0/100] learning_rate: 0.000100 loss: 9.432942 heatmap_loss: 1.201442 size_loss: 0.913217 offset_loss: 0.230315 det_loss: 1.523079 reid_loss: 4.227031 eta: 8:28:41 batch_cost: 10.1738 data_cost: 0.0000 ips: 0.5897 images/s
Traceback (most recent call last):
File "E:\PaddlePaddle\PaddleDetection\tools\train.py", line 177, in
main()
File "E:\PaddlePaddle\PaddleDetection\tools\train.py", line 173, in main
run(FLAGS, cfg)
File "E:\PaddlePaddle\PaddleDetection\tools\train.py", line 127, in run
trainer.train(FLAGS.eval)
File "E:\PaddlePaddle\PaddleDetection\ppdet\engine\trainer.py", line 454, in train
outputs = model(data)
File "D:\Python39\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
return self._dygraph_call_func(*inputs, **kwargs)
File "D:\Python39\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
outputs = self.forward(*inputs, **kwargs)
File "E:\PaddlePaddle\PaddleDetection\ppdet\modeling\architectures\meta_arch.py", line 59, in forward
out = self.get_loss()
File "E:\PaddlePaddle\PaddleDetection\ppdet\modeling\architectures\fairmot.py", line 99, in get_loss
loss = self._forward()
File "E:\PaddlePaddle\PaddleDetection\ppdet\modeling\architectures\fairmot.py", line 78, in _forward
reid_loss = self.reid(neck_feat, self.inputs)
File "D:\Python39\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
return self._dygraph_call_func(*inputs, **kwargs)
File "D:\Python39\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
outputs = self.forward(*inputs, **kwargs)
File "E:\PaddlePaddle\PaddleDetection\ppdet\modeling\reid\fairmot_embedding_head.py", line 115, in forward
loss = self.get_loss(reid_feat, inputs)
File "E:\PaddlePaddle\PaddleDetection\ppdet\modeling\reid\fairmot_embedding_head.py", line 163, in get_loss
loss = self.reid_loss(logit, target)
File "D:\Python39\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
return self._dygraph_call_func(*inputs, **kwargs)
File "D:\Python39\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
outputs = self.forward(*inputs, **kwargs)
File "D:\Python39\lib\site-packages\paddle\nn\layer\loss.py", line 397, in forward
ret = paddle.nn.functional.cross_entropy(
File "D:\Python39\lib\site-packages\paddle\nn\functional\loss.py", line 1722, in cross_entropy
raise ValueError("Target {} is out of upper bound.".format(
ValueError: Target 4547114506196783481 is out of upper bound.

**Comment by mzb157** [comment]
我也是这样 奇了怪了 用 aistudio一点问题没有 本地就完蛋

**Comment by mzb157** [comment]
找到问题了 paddlepaddle-gpu 2.3.2 有bug 换成2.2.2就可以了

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/search?q=out+of+bound&type=issues 

win下请安装最新develop版本的paddle，版本号为0.0.0
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/windows-pip.html

**Comment by koksoft** [comment]
> 找到问题了 paddlepaddle-gpu 2.3.2 有bug 换成2.2.2就可以了

非常感谢，验证过了，改成2.2.2就正常了

**Comment by wobenxiaoyaoKurt** [comment]
> 找到问题了 paddlepaddle-gpu 2.3.2 有bug 换成2.2.2就可以了

为什么云端2.3.2可以 本地就不行？

**Comment by cunjing56** [comment]
> https://github.com/PaddlePaddle/PaddleDetection/search?q=out+of+bound&type=issues
> 
> win下请安装最新develop版本的paddle，版本号为0.0.0 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/windows-pip.html

现在官方配置的cuda11.6 是2.4， 不止11.6是2.4， gpu的都是2.4的了，我重新建环境，配置cuda11.6, paddle-gpu2.2.2，报错，安装不了。。。怎么办？

**Comment by cunjing56** [comment]
> https://github.com/PaddlePaddle/PaddleDetection/search?q=out+of+bound&type=issues
> 
> win下请安装最新develop版本的paddle，版本号为0.0.0 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/windows-pip.html

我按照上述更新了paddleppaddle-gpu ,然后版本成000了，再训练就报这个错误。路径没有中文。。啥问题呢？
(paddle) D:\pkg\PaddleDetection>python tools/train.py -c configs/smalldet/ppyoloe_crn_l_80e_sliced_rice_640_025.yml -o LearningRate.base_lr=0.00125 worker_num=1  --eval
Traceback (most recent call last):
  File "tools/train.py", line 30, in <module>
    import paddle
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\framework\__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\framework\random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\__init__.py", line 52, in <module>
    from . import io
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\io.py", line 31, in <module>
    from paddle.fluid import layers
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\layers\__init__.py", line 17, in <module>
    from . import ops
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\layers\ops.py", line 82, in <module>
    globals()['_scale'] = generate_layer_fn('scale')
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\layers\layer_function_generator.py", line 149, in generate_layer_fn
    op_proto = OpProtoHolder.instance().get_op_proto(op_type)
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 2560, in instance
    cls._instance = cls()
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 2567, in __init__
    op_protos = get_all_op_protos()
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 2547, in get_all_op_protos
    op_proto = framework_pb2.OpProto.FromString(six.binary_type(pbstr))
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\google\protobuf\internal\python_message.py", line 801, in FromString
    message.MergeFromString(s)
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\google\protobuf\internal\python_message.py", line 1128, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\google\protobuf\internal\python_message.py", line 1195, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\google\protobuf\internal\decoder.py", line 705, in DecodeRepeatedField
    if value.add()._InternalParse(buffer, pos, new_pos) != new_pos:
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\google\protobuf\internal\python_message.py", line 1195, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\google\protobuf\internal\decoder.py", line 591, in DecodeField
    field_dict[key] = _ConvertToUnicode(buffer[pos:new_pos])
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\google\protobuf\internal\decoder.py", line 553, in _ConvertToUnicode
    value = str(byte_str, 'utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 325-326: 'utf-8' codec can't decode bytes in position 325-326: invalid continuation byte in field: paddle.framework.proto.OpProto.Attr.comment
