### ISSUE TITLE
自己训练的模型paddleserving部署导出时失败

### ISSUE THREAD

**Issue by mcl-stone** [PaddlePaddle/PaddleDetection#738]
使用detection0.2 版本yolov3_darknet_voc训练出的模型，再使用了最新版本的detection0.3，按照paddleserving部署模型导出时报错。
```
/PaddleDetection-release-0.3# python3 tools/export_serving_model.py -c configs/dcn/yolov3_darknet_voc_diy.yml --output_dir=./inference_model -o weights=/home/mcl/Desktop/dir_bestmodel/yolov3_darknet_voc_diy/model_final
2020-05-19 20:59:41,330-INFO: The 'num_classes'(number of classes) you set is 1, and 'with_background' in 'dataset' sets False.
So please note the actual number of categories is 1.
2020-05-19 20:59:44,537-INFO: save_inference_model pruned unused feed variables im_id
2020-05-19 20:59:44,537-INFO: Export serving model to ./inference_model, client side: ./inference_model/serving_client, server side: ./inference_model/serving_server. input: ['image', 'im_size'], output: ['multiclass_nms_0.tmp_0']...
Traceback (most recent call last):
  File "tools/export_serving_model.py", line 97, in <module>
    main()
  File "tools/export_serving_model.py", line 84, in main
    save_serving_model(FLAGS, exe, feed_vars, test_fetches, infer_prog)
  File "tools/export_serving_model.py", line 54, in save_serving_model
    infer_prog)
  File "/usr/local/lib/python3.6/dist-packages/paddle_serving_client/io/__init__.py", line 42, in save_model
    main_program=main_program)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/io.py", line 1217, in save_inference_model
    feeded_var_names=feeded_var_names, targets=target_vars)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/framework.py", line 4125, in _prune_with_input
    raise ValueError("All targets of prune() can only be "
ValueError: All targets of prune() can only be Variable or Operator.
```

求帮助

**Comment by wangjiawei04** [comment]
好的 我马上复现一下

**Comment by mcl-stone** [comment]
测试发现使用tools/export_model.py导出是可以的，但使用tools/export_serving_model.py导出是失败的，您看看咋回事吧
![image](https://user-images.githubusercontent.com/62418900/82411658-c1811e00-9aa4-11ea-950d-6abe2f963231.png)

**Comment by mcl-stone** [comment]
![image](https://user-images.githubusercontent.com/62418900/82411695-d52c8480-9aa4-11ea-934e-a4a420c1a81c.png)

**Comment by mcl-stone** [comment]
> 好的 我马上复现一下

您那测试怎么样？

**Comment by mcl-stone** [comment]
![image](https://user-images.githubusercontent.com/62418900/82520400-a40c8c80-9b56-11ea-8b5c-f25a09b7edbe.png)
这是tools/export_model.py导出是可以的，tools/export_serving_model.py导出是失败的

**Comment by mcl-stone** [comment]
更换paddle1.8可以了，感谢
