### ISSUE TITLE
进行模型预测时出现 KeyError: 2

### ISSUE THREAD

**Issue by A-xiong** [PaddlePaddle/PaddleDetection#739]
我是一个新手，当我使用tools/infer.py进行多张图片模型预测时，出现以下错误：

```
2020-05-19 21:43:34,885-INFO: Infer iter 24
Traceback (most recent call last):
  File "tools/infer.py", line 304, in <module>
    main()
  File "tools/infer.py", line 205, in main
    x1y1x2y2_result,bbox_results = bbox2out([res], clsid2catid, is_bbox_normalized)
  File "/home/aistudio/PaddleDetection/ppdet/utils/coco_eval.py", line 270, in bbox2out
    catid = (clsid2catid[int(clsid)])
KeyError: 2
```
这是为什么呢，我暂时找不到原因。要是能帮到我，我真的非常感谢。

**Comment by jerrywgz** [comment]
请问你是如果进行预测的呢，可以确认下预测时的with_background和训练是否保持一致

**Comment by qingqing01** [comment]
@A-xiong 你是换了数据集吗？也需要注意配置文件里，TestReader的`anno_path`配置正确。

**Comment by A-xiong** [comment]
嗯嗯，我换了数据集。好的，我再去试试，非常感谢。

**Comment by akingyin1987** [comment]
2021-03-24 16:08:51,703 - INFO - Load categories from dataset/water_meter_voc/la
bel_list.txt
2021-03-24 16:08:52,817 - INFO - Infer iter 0
Traceback (most recent call last):
  File "tools/infer.py", line 272, in <module>
    main()
  File "tools/infer.py", line 195, in main
    bbox_results = bbox2out([res], clsid2catid, is_bbox_normalized)
  File "E:\Development\StudioApp\PaddleDetection\ppdet\utils\coco_eval.py", line
 315, in bbox2out
    catid = (clsid2catid[int(clsid)])
KeyError: 1
