### ISSUE TITLE
使用pp-yoloe-r训练自定义数据集时报错？

### ISSUE THREAD

**Issue by CachCheng** [PaddlePaddle/PaddleDetection#7392]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/cash/anaconda3/envs/py37/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/cash/anaconda3/envs/py37/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cash/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 505, in _thread_loop
    batch = self._get_data()
  File "/home/cash/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 634, in _get_data
    batch.reraise()
  File "/home/cash/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 169, in reraise
    raise self.exc_type(msg)
ValueError: DataLoader worker(0) caught ValueError with message:
Traceback (most recent call last):
  File "/home/cash/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 329, in _worker_loop
    batch = fetcher.fetch(indices)
  File "/home/cash/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 121, in fetch
    data.append(self.dataset[idx])
  File "/data/source_code/paddle/PaddleDetection/ppdet/data/source/dataset.py", line 96, in __getitem__
    return self.transform(roidb)
  File "/data/source_code/paddle/PaddleDetection/ppdet/data/reader.py", line 60, in __call__
    raise e
  File "/data/source_code/paddle/PaddleDetection/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/data/source_code/paddle/PaddleDetection/ppdet/data/transform/operators.py", line 104, in __call__
    sample = self.apply(sample, context)
  File "/data/source_code/paddle/PaddleDetection/ppdet/data/transform/rotated_operators.py", line 251, in apply
    sample['gt_poly'], dtype=np.float32).reshape((-1, 8))
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (12, 1) + inhomogeneous part.

Traceback (most recent call last):
  File "tools/train.py", line 188, in <module>
    main()
  File "tools/train.py", line 184, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 137, in run
    trainer.train(FLAGS.eval)
  File "/data/source_code/paddle/PaddleDetection/ppdet/engine/trainer.py", line 474, in train
    for step_id, data in enumerate(self.loader):
  File "/data/source_code/paddle/PaddleDetection/ppdet/data/reader.py", line 209, in __next__
    return next(self.loader)
  File "/home/cash/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 697, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

**Comment by CachCheng** [comment]
完整的错误如下：



[11/22 23:36:52] ppdet.engine INFO: Epoch: [0] [ 0/43] learning_rate: 0.000000 loss: 2.778403 loss_cls: 1.831606 loss_iou: 0.308671 loss_dfl: 3.502424 eta: 0:27:46 batch_cost: 1.0767 data_cost: 0.0001 ips: 7.4302 images/s
[11/22 23:36:55] reader WARNING: fail to map sample transform [Poly2Array_1bade3] with error: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (12, 1) + inhomogeneous part. and stack:
Traceback (most recent call last):
  File "/data/source_code/paddle/PaddleDetection/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/data/source_code/paddle/PaddleDetection/ppdet/data/transform/operators.py", line 104, in __call__
    sample = self.apply(sample, context)
  File "/data/source_code/paddle/PaddleDetection/ppdet/data/transform/rotated_operators.py", line 251, in apply
    sample['gt_poly'], dtype=np.float32).reshape((-1, 8))
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (12, 1) + inhomogeneous part.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/cash/anaconda3/envs/py37/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/cash/anaconda3/envs/py37/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cash/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 505, in _thread_loop
    batch = self._get_data()
  File "/home/cash/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 634, in _get_data
    batch.reraise()
  File "/home/cash/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 169, in reraise
    raise self.exc_type(msg)
ValueError: DataLoader worker(0) caught ValueError with message:
Traceback (most recent call last):
  File "/home/cash/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 329, in _worker_loop
    batch = fetcher.fetch(indices)
  File "/home/cash/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 121, in fetch
    data.append(self.dataset[idx])
  File "/data/source_code/paddle/PaddleDetection/ppdet/data/source/dataset.py", line 96, in __getitem__
    return self.transform(roidb)
  File "/data/source_code/paddle/PaddleDetection/ppdet/data/reader.py", line 60, in __call__
    raise e
  File "/data/source_code/paddle/PaddleDetection/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/data/source_code/paddle/PaddleDetection/ppdet/data/transform/operators.py", line 104, in __call__
    sample = self.apply(sample, context)
  File "/data/source_code/paddle/PaddleDetection/ppdet/data/transform/rotated_operators.py", line 251, in apply
    sample['gt_poly'], dtype=np.float32).reshape((-1, 8))
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (12, 1) + inhomogeneous part.


Traceback (most recent call last):
  File "tools/train.py", line 188, in <module>
    main()
  File "tools/train.py", line 184, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 137, in run
    trainer.train(FLAGS.eval)
  File "/data/source_code/paddle/PaddleDetection/ppdet/engine/trainer.py", line 474, in train
    for step_id, data in enumerate(self.loader):
  File "/data/source_code/paddle/PaddleDetection/ppdet/data/reader.py", line 209, in __next__
    return next(self.loader)
  File "/home/cash/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 697, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

**Comment by wangxinxin08** [comment]
看报错信息，数据没准备好，segmentation字段需要是4个点的坐标，8个数值

**Comment by CachCheng** [comment]
pp-yoloe-r训练的模型转onnx和tensorrt能跑通的教程有么？

**Comment by cr1127** [comment]
@CachCheng 您好，请问您这个问题解决了吗？ 自定义的数据集是如何制作的？

**Comment by wlpczsz** [comment]
@CachCheng 您好，请问您编译ppdet/ext_op时没有碰到问题么？

**Comment by wangxinxin08** [comment]
> @CachCheng 您好，请问您这个问题解决了吗？ 自定义的数据集是如何制作的？

这个应该是数据集的问题，你可以用labelme， labelstudio等进行标注，然后转换成COCO格式即可，注意标注旋转框需要且仅需要4个点的坐标，存储在coco的segmentation字段中

**Comment by wangxinxin08** [comment]
> @CachCheng 您好，请问您编译ppdet/ext_op时没有碰到问题么？

你遇到什么问题？

**Comment by wlpczsz** [comment]
> 
具体问题如下描述：
https://github.com/PaddlePaddle/PaddleDetection/issues/7435
您有空的话请帮忙解答一下。
报错信息如下所示：
/home/hpg/anaconda3/envs/paddle/compiler_compat/ld: DWARF error: could not find variable specification at offset 1cc1

**Comment by Zhengxulion** [comment]
> 完整的错误如下：
> 
> [11/22 23:36:52] ppdet.engine INFO: Epoch: [0] [ 0/43] learning_rate: 0.000000 loss: 2.778403 loss_cls: 1.831606 loss_iou: 0.308671 loss_dfl: 3.502424 eta: 0:27:46 batch_cost: 1.0767 data_cost: 0.0001 ips: 7.4302 images/s [11/22 23:36:55] reader WARNING: fail to map sample transform [Poly2Array_1bade3] with error: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (12, 1) + inhomogeneous part. and stack: Traceback (most recent call last): File "/data/source_code/paddle/PaddleDetection/ppdet/data/reader.py", line 54, in **call** data = f(data) File "/data/source_code/paddle/PaddleDetection/ppdet/data/transform/operators.py", line 104, in **call** sample = self.apply(sample, context) File "/data/source_code/paddle/PaddleDetection/ppdet/data/transform/rotated_operators.py", line 251, in apply sample['gt_poly'], dtype=np.float32).reshape((-1, 8)) ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (12, 1) + inhomogeneous part.
> 
> Exception in thread Thread-1: Traceback (most recent call last): File "/home/cash/anaconda3/envs/py37/lib/python3.7/threading.py", line 926, in _bootstrap_inner self.run() File "/home/cash/anaconda3/envs/py37/lib/python3.7/threading.py", line 870, in run self._target(*self._args, **self._kwargs) File "/home/cash/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 505, in _thread_loop batch = self._get_data() File "/home/cash/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 634, in _get_data batch.reraise() File "/home/cash/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 169, in reraise raise self.exc_type(msg) ValueError: DataLoader worker(0) caught ValueError with message: Traceback (most recent call last): File "/home/cash/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 329, in _worker_loop batch = fetcher.fetch(indices) File "/home/cash/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 121, in fetch data.append(self.dataset[idx]) File "/data/source_code/paddle/PaddleDetection/ppdet/data/source/dataset.py", line 96, in **getitem** return self.transform(roidb) File "/data/source_code/paddle/PaddleDetection/ppdet/data/reader.py", line 60, in **call** raise e File "/data/source_code/paddle/PaddleDetection/ppdet/data/reader.py", line 54, in **call** data = f(data) File "/data/source_code/paddle/PaddleDetection/ppdet/data/transform/operators.py", line 104, in **call** sample = self.apply(sample, context) File "/data/source_code/paddle/PaddleDetection/ppdet/data/transform/rotated_operators.py", line 251, in apply sample['gt_poly'], dtype=np.float32).reshape((-1, 8)) ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (12, 1) + inhomogeneous part.
> 
> Traceback (most recent call last): File "tools/train.py", line 188, in main() File "tools/train.py", line 184, in main run(FLAGS, cfg) File "tools/train.py", line 137, in run trainer.train(FLAGS.eval) File "/data/source_code/paddle/PaddleDetection/ppdet/engine/trainer.py", line 474, in train for step_id, data in enumerate(self.loader): File "/data/source_code/paddle/PaddleDetection/ppdet/data/reader.py", line 209, in **next** return next(self.loader) File "/home/cash/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 697, in **next** data = self._reader.read_next_var_list() SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception. [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

你好，我出现了和你一样的问题，使用的官方脚本x2coco.py来转化为coco格式的，是四个点八个数值。该如何修改呢？
