### ISSUE TITLE
KeyError: 'im_file' 基于ai studio PP-YOLOE的案例训练自己数据报错

### ISSUE THREAD

**Issue by cunjing56** [PaddlePaddle/PaddleDetection#7411]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

!python tools/train.py -c configs/ppyoloe/application/ppyoloe_plus_crn_m_80e_obj365_pretrained_rice.yml -o LearningRate.base_lr=0.000125 -o snapshot_epoch=1 -o worker_num=1 --eval

输出内容过长， 已自动对输出内容进行截断
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
W1125 10:27:06.861737  6879 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 11.2
[11/25 10:27:06] reader WARNING: fail to map sample transform [Decode_d86f5c] with error: 'im_file' and stack:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/data/transform/operators.py", line 104, in __call__
    sample = self.apply(sample, context)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/data/transform/operators.py", line 121, in apply
    with open(sample['im_file'], 'rb') as f:
KeyError: 'im_file'

[11/25 10:27:06] reader WARNING: fail to map sample transform [Decode_d86f5c] with error: 'im_file' and stack:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/data/transform/operators.py", line 104, in __call__
    sample = self.apply(sample, context)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/data/transform/operators.py", line 121, in apply
    with open(sample['im_file'], 'rb') as f:
KeyError: 'im_file'

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 534, in _thread_loop
    batch = self._get_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 671, in _get_data
    batch.reraise()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 169, in reraise
    raise self.exc_type(msg)
KeyError: 'DataLoader worker(0) caught KeyError with message:\nTraceback (most recent call last):\n  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 336, in _worker_loop\n    batch = fetcher.fetch(indices)\n  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 121, in fetch\n    data.append(self.dataset[idx])\n  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/data/source/dataset.py", line 96, in __getitem__\n    return self.transform(roidb)\n  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/data/reader.py", line 60, in __call__\n    raise e\n  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/data/reader.py", line 54, in __call__\n    data = f(data)\n  File "/opt/conda/envs/python35-paddle120-

W1125 10:27:06.870728  6879 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
[11/25 10:27:08] ppdet.utils.download INFO: Downloading ppyoloe_crn_m_obj365_pretrained.pdparams from https://bj.bcebos.com/v1/paddledet/models/pretrained/ppyoloe_crn_m_obj365_pretrained.pdparams
100%|███████████████████████████████████| 91665/91665 [00:41<00:00, 2195.42KB/s]
[11/25 10:27:51] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/aistudio/.cache/paddle/weights/ppyoloe_crn_m_obj365_pretrained.pdparams
Traceback (most recent call last):
  File "tools/train.py", line 172, in <module>
    main()
  File "tools/train.py", line 168, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 132, in run
    trainer.train(FLAGS.eval)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/engine/trainer.py", line 453, in train
    for step_id, data in enumerate(self.loader):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddledet-2.5.0-py3.7.egg/ppdet/data/reader.py", line 209, in __next__
    return next(self.loader)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 746, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

### 复现环境 Environment

device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 11.2

数据是labelme 标注，用x2coco转成coco, 再用sahi分割成640*640的。官方的数据跑模型，不报错，自己的数据就报错，已经修改了配置项为自己的数据。

aistudio.baidu.com/bd-gpu-04/user/3050086/5118255/lab/tree/main.ipynb

我的识别码:550764879
使用向日葵即可对我发起远程协助
向日葵下载地址:http://url.oray.com/tGJdas/

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
训练你自己的数据 得符合json的格式，你的json里有file_name这个字段嘛  另外check一下 数据的路径配置对没

**Comment by cunjing56** [comment]
> 训练你自己的数据 得符合json的格式，你的json里有file_name这个字段嘛 另外check一下 数据的路径配置对没

有file_name字段，print路径了，看着没问题，print路径是否exist ，返回的也是true. 还可能是什么问题呢？我已经换了四个案例了，都是这个问题，感觉是不是文件配置的问题？coco会比voc更容易出错吗？我就是想实现大图像小目标的训练部署，切图完成了，现在换啥模型都不能训练，是为什么呢？
以下是切图后的json (节选了前三个，可能存在误删括号什么的。但是结构我看着跟案例的一样啊

{"images":[{"height":640,"width":640,"id":1,"file_name":"uva0001_0_0_640_640.jpg"},{"height":640,"width":640,"id":2,"file_name":"uva0001_480_0_1120_640.jpg"},{"height":640,"width":640,"id":3,"file_name":"uva0001_960_0_1600_640.jpg"}],
"annotations":
[{"iscrowd":0,"image_id":1,"bbox":[3,12,46,93],"segmentation":[[2,105,48,105,48,12,2,12]],"category_id":1,"id":1,"area":4265},{"iscrowd":0,"image_id":1,"bbox":[69,18,110,103],"segmentation":[[69,120,179,120,179,18,69,18]],"category_id":1,"id":2,"area":11277},
{"iscrowd":0,"image_id":1,"bbox":[201,26,79,110],"segmentation":[[201,136,280,136,280,26,201,26]],"category_id":1,"id":3,"area":8686}],
"categories":
[{"supercategory":"component","id":1,"name":"ricePlant"}]}

**Comment by cunjing56** [comment]
问题解决了，又是来自之前网友的解决方案，那就是配置文件里的data_fields 不要改，无论是voc, 还是coco格式的数据，都不要改，不是你的标签内容！！！

**Comment by GDbbq** [comment]
data_fields 不能改
