### ISSUE TITLE
安装体验paddledet报错

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/PaddleDetection#7429]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Installation

### Bug描述 Describe the Bug

使用官网安装说明的,python tools/infer.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml -o use_gpu=true weights=https://paddledet.bj.bcebos.com/models/ppyolo_r50vd_dcn_1x_coco.pdparams --infer_img=demo/000000014439.jpg,结果报错.
报错信息:```W1130 11:41:44.911846 13072 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 5.2, Driver API Version: 12.0, Runtime API Version: 10.2
W1130 11:41:44.921849 13072 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
[11/30 11:41:46] ppdet.utils.download INFO: Downloading ppyolo_r50vd_dcn_1x_coco.pdparams from https://paddledet.bj.bcebos.com/models/ppyolo_r50vd_dcn_1x_coco.pdparams
100%|████████████████████████████████████████████████████████████████████████| 277591/277591 [00:34<00:00, 8070.35KB/s]
[11/30 11:42:23] ppdet.utils.checkpoint INFO: Finish loading model weights: C:\Users\Administrator/.cache/paddle/weights\ppyolo_r50vd_dcn_1x_coco.pdparams
[11/30 11:42:23] ppdet.data.source.category WARNING: anno_file 'dataset/coco\annotations/instances_val2017.json' is None or not set or not exist, please recheck TrainDataset/EvalDataset/TestDataset.anno_path, otherwise the default categories will be used by metric_type.
[11/30 11:42:23] ppdet.data.source.category WARNING: metric_type: COCO, load default categories of COCO.
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.51s/it]
Traceback (most recent call last):
  File "C:\Users\Administrator\PaddleDetection\tools\infer.py", line 226, in <module>
    main()
  File "C:\Users\Administrator\PaddleDetection\tools\infer.py", line 222, in main
    run(FLAGS, cfg)
  File "C:\Users\Administrator\PaddleDetection\tools\infer.py", line 182, in run
    trainer.predict(
  File "C:\Users\Administrator\PaddleDetection\ppdet\engine\trainer.py", line 924, in predict
    image = visualize_results(
  File "C:\Users\Administrator\PaddleDetection\ppdet\utils\visualizer.py", line 44, in visualize_results
    image = draw_bbox(image, im_id, catid2name, bbox_res, threshold)
  File "C:\Users\Administrator\PaddleDetection\ppdet\utils\visualizer.py", line 106, in draw_bbox
    draw.line(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\ImageDraw.py", line 171, in line
    ink = self._getink(fill)[0]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\ImageDraw.py", line 129, in _getink
    ink = self.draw.draw_ink(ink)
TypeError: 'numpy.float32' object cannot be interpreted as an integer```

export CUDA_VISIBLE_DEVICES=0语句也报错
报错信息:```export : 无法将“export”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径
正确，然后再试一次。
所在位置 行:1 字符: 1
+ export CUDA_VISIBLE_DEVICES=0
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (export:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException```

### 复现环境 Environment

64位windows10系统
cuda10.2
cudnn7.6.5
PaddlePaddle2.4.0,gpu,10.2版本
python3.10.8

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Syunraii** [comment]
export CUDA_VISIBLE_DEVICES=0 是在linux环境下用的
win用set，或者在环境变量设置CUDA_VISIBLE_DEVICES 值为 0

TypeError: 'numpy.float32' object cannot be interpreted as an integer
是版本问题，然后通过降级py版本和paddle版本匹配就行了#7287
