### ISSUE TITLE
win下安装最新develop版本的paddle，版本号为0.0.0报错

### ISSUE THREAD

**Issue by cunjing56** [PaddlePaddle/PaddleDetection#7446]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

我本来是“PaddleDetection训练数据提示Target out of upper bound”
参考issues解决方案，让安装最新develop版本的paddle，版本号为0.0.0
https://github.com/PaddlePaddle/PaddleDetection/issues/7371

我按照上述更新了paddleppaddle-gpu ,然后版本成000了，再训练就报这个错误。路径没有中文。。啥问题呢？
(paddle) D:\pkg\PaddleDetection>python tools/train.py -c configs/smalldet/ppyoloe_crn_l_80e_sliced_rice_640_025.yml -o LearningRate.base_lr=0.00125 worker_num=1 --eval
Traceback (most recent call last):
File "tools/train.py", line 30, in
import paddle
File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle_init_.py", line 25, in
from .framework import monkey_patch_variable
File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\framework_init_.py", line 17, in
from . import random # noqa: F401
File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\framework\random.py", line 16, in
import paddle.fluid as fluid
File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\fluid_init_.py", line 52, in
from . import io
File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\io.py", line 31, in
from paddle.fluid import layers
File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\layers_init_.py", line 17, in
from . import ops
File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\layers\ops.py", line 82, in
globals()['_scale'] = generate_layer_fn('scale')
File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\layers\layer_function_generator.py", line 149, in generate_layer_fn
op_proto = OpProtoHolder.instance().get_op_proto(op_type)
File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 2560, in instance
cls._instance = cls()
File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 2567, in init
op_protos = get_all_op_protos()
File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 2547, in get_all_op_protos
op_proto = framework_pb2.OpProto.FromString(six.binary_type(pbstr))
File "D:\soft\anaconda3\envs\paddle\lib\site-packages\google\protobuf\internal\python_message.py", line 801, in FromString
message.MergeFromString(s)
File "D:\soft\anaconda3\envs\paddle\lib\site-packages\google\protobuf\internal\python_message.py", line 1128, in MergeFromString
if self._InternalParse(serialized, 0, length) != length:
File "D:\soft\anaconda3\envs\paddle\lib\site-packages\google\protobuf\internal\python_message.py", line 1195, in InternalParse
pos = field_decoder(buffer, new_pos, end, self, field_dict)
File "D:\soft\anaconda3\envs\paddle\lib\site-packages\google\protobuf\internal\decoder.py", line 705, in DecodeRepeatedField
if value.add()._InternalParse(buffer, pos, new_pos) != new_pos:
File "D:\soft\anaconda3\envs\paddle\lib\site-packages\google\protobuf\internal\python_message.py", line 1195, in InternalParse
pos = field_decoder(buffer, new_pos, end, self, field_dict)
File "D:\soft\anaconda3\envs\paddle\lib\site-packages\google\protobuf\internal\decoder.py", line 591, in DecodeField
field_dict[key] = _ConvertToUnicode(buffer[pos:new_pos])
File "D:\soft\anaconda3\envs\paddle\lib\site-packages\google\protobuf\internal\decoder.py", line 553, in _ConvertToUnicode
value = str(byte_str, 'utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 325-326: 'utf-8' codec can't decode bytes in position 325-326: invalid continuation byte in field: paddle.framework.proto.OpProto.Attr.comment

还有个解决方案是安装2.2.2的paddle, cuda11.6环境咋安装2,2,2？
现在官方配置的cuda11.6 是2.4， 不止11.6是2.4， gpu的都是2.4的了，我重新建环境，配置cuda11.6, paddle-gpu2.2.2，报错，安装不了。。。怎么办？

### 复现环境 Environment

win
cuda11.6

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by wangxinxin08** [comment]
这个报错是protobuf报的错，你看下你的protobuf版本是多少呢？遇到问题不要慌，可以先上网搜索找下答案

**Comment by cunjing56** [comment]
&nbsp;3.20.0



我在issue里没看到相关答案啊，如果你看到了，可以发给我吗？
------------------
BY:AnnieYang


&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Send time:&nbsp;Friday, Dec 2, 2022 3:42 PM
***@***.***&gt;; 
***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [PaddlePaddle/PaddleDetection] win下安装最新develop版本的paddle，版本号为0.0.0报错 (Issue #7446)





 
这个报错是protobuf报的错，你看下你的protobuf版本是多少呢？遇到问题不要慌，可以先上网搜索找下答案

**Comment by wangxinxin08** [comment]
可以降级下protobuf试下呢，3.17或者3.19
