### ISSUE TITLE
YOLO v7 多卡训练yaml格式问题报错

### ISSUE THREAD

**Issue by linhandev** [PaddlePaddle/PaddleDetection#7451]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training

### Bug描述 Describe the Bug

paddleyolo repo，下面的config文件在单卡训练的时候是没有报错的，但是在使用 paddle.distributed.launch 训练的时候，因为yaml格式报错。

yolov7_l_300e_coco.yml

```yaml
_BASE_: [
    # '../datasets/coco_detection.yml',
    "../datasets/ped_signal.yml",
    "../runtime.yml",
    "_base_/optimizer_300e.yml",
    "_base_/yolov7_elannet.yml",
    "_base_/yolov7_reader.yml",
  ]

log_iter: 1
snapshot_epoch: 5

arch: L

TrainReader:
  batch_size: 64
```

先是最后的trainreader部分，log前面有smi和utils.run_check()的输出

```shell
train_yolo_v7_l_100e_nomasic_64_2
Sun Dec  4 18:57:17 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 8000     On   | 00000000:06:00.0 Off |                    0 |
| N/A   48C    P8    15W / 250W |      0MiB / 46080MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Quadro RTX 8000     On   | 00000000:86:00.0 Off |                    0 |
| N/A   26C    P8    14W / 250W |      0MiB / 46080MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
W1204 18:57:28.410248 4103644 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.6, Runtime API Version: 11.6
W1204 18:57:29.816383 4103644 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
W1204 18:57:40.873917 4103644 fuse_all_reduce_op_pass.cc:76] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
Running verify PaddlePaddle program ... 
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 2 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
LAUNCH INFO 2022-12-04 18:57:43,540 -----------  Configuration  ----------------------
INFO 2022-12-04 18:57:43,540 __init__.py:21] -----------  Configuration  ----------------------
LAUNCH INFO 2022-12-04 18:57:43,540 devices: None
INFO 2022-12-04 18:57:43,540 __init__.py:23] devices: None
LAUNCH INFO 2022-12-04 18:57:43,540 elastic_level: -1
INFO 2022-12-04 18:57:43,540 __init__.py:23] elastic_level: -1
LAUNCH INFO 2022-12-04 18:57:43,540 elastic_timeout: 30
INFO 2022-12-04 18:57:43,540 __init__.py:23] elastic_timeout: 30
LAUNCH INFO 2022-12-04 18:57:43,540 gloo_port: 6767
INFO 2022-12-04 18:57:43,540 __init__.py:23] gloo_port: 6767
LAUNCH INFO 2022-12-04 18:57:43,540 host: None
INFO 2022-12-04 18:57:43,540 __init__.py:23] host: None
LAUNCH INFO 2022-12-04 18:57:43,540 job_id: default
INFO 2022-12-04 18:57:43,540 __init__.py:23] job_id: default
LAUNCH INFO 2022-12-04 18:57:43,540 legacy: False
INFO 2022-12-04 18:57:43,540 __init__.py:23] legacy: False
LAUNCH INFO 2022-12-04 18:57:43,540 log_dir: log
INFO 2022-12-04 18:57:43,540 __init__.py:23] log_dir: log
LAUNCH INFO 2022-12-04 18:57:43,540 log_level: INFO
INFO 2022-12-04 18:57:43,540 __init__.py:23] log_level: INFO
LAUNCH INFO 2022-12-04 18:57:43,540 master: None
INFO 2022-12-04 18:57:43,540 __init__.py:23] master: None
LAUNCH INFO 2022-12-04 18:57:43,540 max_restart: 3
INFO 2022-12-04 18:57:43,540 __init__.py:23] max_restart: 3
LAUNCH INFO 2022-12-04 18:57:43,544 nnodes: 1
INFO 2022-12-04 18:57:43,544 __init__.py:23] nnodes: 1
LAUNCH INFO 2022-12-04 18:57:43,544 nproc_per_node: None
INFO 2022-12-04 18:57:43,544 __init__.py:23] nproc_per_node: None
LAUNCH INFO 2022-12-04 18:57:43,544 rank: -1
INFO 2022-12-04 18:57:43,544 __init__.py:23] rank: -1
LAUNCH INFO 2022-12-04 18:57:43,544 run_mode: collective
INFO 2022-12-04 18:57:43,544 __init__.py:23] run_mode: collective
LAUNCH INFO 2022-12-04 18:57:43,544 server_num: None
INFO 2022-12-04 18:57:43,544 __init__.py:23] server_num: None
LAUNCH INFO 2022-12-04 18:57:43,544 servers: 
INFO 2022-12-04 18:57:43,544 __init__.py:23] servers: 
LAUNCH INFO 2022-12-04 18:57:43,544 trainer_num: None
INFO 2022-12-04 18:57:43,544 __init__.py:23] trainer_num: None
LAUNCH INFO 2022-12-04 18:57:43,544 trainers: 
INFO 2022-12-04 18:57:43,544 __init__.py:23] trainers: 
LAUNCH INFO 2022-12-04 18:57:43,544 training_script: 0,1
INFO 2022-12-04 18:57:43,544 __init__.py:23] training_script: 0,1
LAUNCH INFO 2022-12-04 18:57:43,544 training_script_args: ['-c', 'configs/yolov7/yolov7_l_300e_coco.yml', '--amp', '--eval', '--use_wandb', 'True', '-o', 'weights=/scratch/xxx/weights/yolov7_l_300e_coco.pdparams', '-o', 'save_dir=output/train_yolo_v7_l_100e_nomasic_64_2']
INFO 2022-12-04 18:57:43,544 __init__.py:23] training_script_args: ['-c', 'configs/yolov7/yolov7_l_300e_coco.yml', '--amp', '--eval', '--use_wandb', 'True', '-o', 'weights=/scratch/xxx/weights/yolov7_l_300e_coco.pdparams', '-o', 'save_dir=output/train_yolo_v7_l_100e_nomasic_64_2']
LAUNCH INFO 2022-12-04 18:57:43,544 with_gloo: 0
INFO 2022-12-04 18:57:43,544 __init__.py:23] with_gloo: 0
LAUNCH INFO 2022-12-04 18:57:43,544 --------------------------------------------------
INFO 2022-12-04 18:57:43,544 __init__.py:24] --------------------------------------------------
LAUNCH WARNING 2022-12-04 18:57:43,544 Compatible mode enable with args ['--gpus']
WARNING 2022-12-04 18:57:43,544 __init__.py:47] Compatible mode enable with args ['--gpus']
WARNING 2022-12-04 18:57:43,545 launch.py:518] Not found distinct arguments and compiled with cuda or xpu or npu or mlu. Default use collective mode
WARNING 2022-12-04 18:57:43,545 launch.py:518] Not found distinct arguments and compiled with cuda or xpu or npu or mlu. Default use collective mode
INFO 2022-12-04 18:57:43,545 launch_utils.py:676] Change selected_gpus into reletive values. --ips:0,1 will change into relative_ips:[0, 1] according to your CUDA_VISIBLE_DEVICES:['0', '1']
INFO 2022-12-04 18:57:43,545 launch_utils.py:676] Change selected_gpus into reletive values. --ips:0,1 will change into relative_ips:[0, 1] according to your CUDA_VISIBLE_DEVICES:['0', '1']
INFO 2022-12-04 18:57:43,546 launch_utils.py:558] Local start 2 processes. First process distributed environment info (Only For Debug): 
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:53151               |
    |                     PADDLE_TRAINERS_NUM                        2                      |
    |                PADDLE_TRAINER_ENDPOINTS         127.0.0.1:53151,127.0.0.1:46471       |
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                       0,1                     |
    |                     FLAGS_selected_gpus                        0                      |
    |             FLAGS_selected_accelerators                        0                      |
    +=======================================================================================+

INFO 2022-12-04 18:57:43,546 launch_utils.py:558] Local start 2 processes. First process distributed environment info (Only For Debug): 
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:53151               |
    |                     PADDLE_TRAINERS_NUM                        2                      |
    |                PADDLE_TRAINER_ENDPOINTS         127.0.0.1:53151,127.0.0.1:46471       |
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                       0,1                     |
    |                     FLAGS_selected_gpus                        0                      |
    |             FLAGS_selected_accelerators                        0                      |
    +=======================================================================================+

INFO 2022-12-04 18:57:43,546 launch_utils.py:563] details about PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
INFO 2022-12-04 18:57:43,546 launch_utils.py:563] details about PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
INFO 2022-12-04 18:57:50,771 launch_utils.py:343] terminate all the procs
INFO 2022-12-04 18:57:50,771 launch_utils.py:343] terminate all the procs
ERROR 2022-12-04 18:57:50,772 launch_utils.py:640] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0, 1] was aborted. Please check its log.
ERROR 2022-12-04 18:57:50,772 launch_utils.py:640] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0, 1] was aborted. Please check its log.
INFO 2022-12-04 18:57:54,776 launch_utils.py:343] terminate all the procs
INFO 2022-12-04 18:57:54,776 launch_utils.py:343] terminate all the procs
INFO 2022-12-04 18:57:54,776 launch.py:402] Local processes completed.
INFO 2022-12-04 18:57:54,776 launch.py:402] Local processes completed.
-----------  Configuration Arguments -----------
backend: auto
cluster_topo_path: None
elastic_pre_hook: None
elastic_server: None
enable_auto_mapping: False
force: False
gpus: 0,1
heter_devices: 
heter_worker_num: None
heter_workers: 
host: None
http_port: None
ips: 127.0.0.1
job_id: None
log_dir: log
np: None
nproc_per_node: None
rank_mapping_path: None
run_mode: None
scale: 0
server_num: None
servers: 
training_script: configs/yolov7/yolov7_l_300e_coco.yml
training_script_args: ['--amp', '--eval', '--use_wandb', 'True', '-o', 'weights=/scratch/xxx/weights/yolov7_l_300e_coco.pdparams', '-o', 'save_dir=output/train_yolo_v7_l_100e_nomasic_64_2']
worker_num: None
workers: 
------------------------------------------------
launch train in GPU mode!
launch proc_id:4103812 idx:0
launch proc_id:4103817 idx:1
  File "/scratch/xxx/git/eye/PaddleYOLO/configs/yolov7/yolov7_l_300e_coco.yml", line 15
    TrainReader:
                ^
SyntaxError: invalid syntax
```

之后我注掉了trainreader的两行，转到跑脚本的时候-o 传参 batchsize，上面的arch部分报错
```shell
-----------  Configuration Arguments -----------
backend: auto
cluster_topo_path: None
elastic_pre_hook: None
elastic_server: None
enable_auto_mapping: False
force: False
gpus: 0,1
heter_devices: 
heter_worker_num: None
heter_workers: 
host: None
http_port: None
ips: 127.0.0.1
job_id: None
log_dir: log
np: None
nproc_per_node: None
rank_mapping_path: None
run_mode: None
scale: 0
server_num: None
servers: 
training_script: configs/yolov7/yolov7_l_300e_coco.yml
training_script_args: ['--amp', '--eval', '--use_wandb', 'True', '-o', 'weights=/scratch/xxx/weights/yolov7_l_300e_coco.pdparams', '-o', 'save_dir=output/train_yolo_v7_l_100e_nomasic_32_2', '-o', 'batch_size=32', '-o', 'epoch=100']
worker_num: None
workers: 
------------------------------------------------
launch train in GPU mode!
launch proc_id:4104879 idx:0
launch proc_id:4104884 idx:1
Traceback (most recent call last):
  File "/scratch/xxx/git/eye/PaddleYOLO/configs/yolov7/yolov7_l_300e_coco.yml", line 13, in <module>
    arch: L
NameError: name 'L' is not defined

```

### 复现环境 Environment

python 3.9

paddlepaddle-gpu 2.3.2
PyYAML   6.0
ruamel-yaml-conda      0.15.100 # 这个不知道是否相关，看也带yaml就也放这了

Singularity> uname
Linux
Singularity> uname -r 
4.18.0-305.28.1.el8_4.x86_64
Singularity>   cat /etc/issue
Ubuntu 20.04.4 LTS \n \l

release/2.5

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
完整训练命令也发一下

**Comment by linhandev** [comment]
脚本后来改了，大概是这个

```shell
python -m paddle.distributed.launch --gpus 0,1 \
        -c configs/yolov7/yolov7_l_300e_coco.yml \
        --amp \
        --eval \
        -o pretrain_weights=/scratch/xxx/weights/yolov7_l_300e_coco.pdparams \
        -o save_dir=output/${name} \
        -o epoch=200
```
我这边再提交一个训练任务确定一下，不过请两个gpu要等比较久

**Comment by nemonameless** [comment]
发全了吗？ tools/train.py 都没有写？

**Comment by linhandev** [comment]
唉！我查查，莫非真是因为没有写那个 /汗 第一次多卡

**Comment by linhandev** [comment]
这可尴尬了 /笑哭

**Comment by linhandev** [comment]
```shell
  python -m paddle.distributed.launch --gpus 0,1 tools/train.py \
      -c configs/yolov7/yolov7_l_300e_coco.yml \
      --amp \
      --eval \
      -o pretrain_weights=/scratch/lh3317/weights/yolov7_l_300e_coco.pdparams \
      -o save_dir=output/${name} \
      -o epoch=200
```
用这个重新交了，等会看看

**Comment by linhandev** [comment]
想插着问一句，训练bs能 -o 指定嘛，训练bs是在TrainReader下面，不在最外面一级，和 weights 之类的不一样。我试了几个格式貌似都没生效

**Comment by nemonameless** [comment]
-o TrainReader.batch_size=32
-o 写一个就行

**Comment by linhandev** [comment]
6的6的，感谢。



> ```shell
>   python -m paddle.distributed.launch --gpus 0,1 tools/train.py \
>       -c configs/yolov7/yolov7_l_300e_coco.yml \
>       --amp \
>       --eval \
>       -o pretrain_weights=/scratch/lh3317/weights/yolov7_l_300e_coco.pdparams \
>       -o save_dir=output/${name} \
>       -o epoch=200
> ```
> 
> 用这个重新交了，等会看看

这个提交成功报了一个显存不够的问题，大概真是我没写tools/train.py，太。。了 /笑哭

这块没问题
