### ISSUE TITLE
YOLO V7 训练过程中 loss 报错

### ISSUE THREAD

**Issue by linhandev** [PaddlePaddle/PaddleDetection#7452]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training

### Bug描述 Describe the Bug

```shell
[12/04 22:11:48] ppdet.engine INFO: Epoch: [8] [10/54] eta: 9:54:41 lr: 0.009370 loss_box: 0.029181 loss_obj: 0.002040 loss_cls: 0.000000 loss: 1.998167 batch_cost: 2.2707 data_cost: 0.0008 ips: 28.1848 images/s
Traceback (most recent call last):
  File "/scratch/xxx/git/eye/PaddleYOLO/tools/train.py", line 172, in <module>
    main()
  File "/scratch/xxx/git/eye/PaddleYOLO/tools/train.py", line 168, in main
    run(FLAGS, cfg)
  File "/scratch/xxx/git/eye/PaddleYOLO/tools/train.py", line 132, in run
    trainer.train(FLAGS.eval)
  File "/scratch/xxx/git/eye/PaddleYOLO/ppdet/engine/trainer.py", line 403, in train
    outputs = model(data)
  File "/ext3/miniconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/ext3/miniconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/scratch/xxx/git/eye/PaddleYOLO/ppdet/modeling/architectures/meta_arch.py", line 59, in forward
    out = self.get_loss()
  File "/scratch/xxx/git/eye/PaddleYOLO/ppdet/modeling/architectures/yolov5.py", line 94, in get_loss
    return self._forward()
  File "/scratch/xxx/git/eye/PaddleYOLO/ppdet/modeling/architectures/yolov5.py", line 79, in _forward
    yolo_losses = self.yolo_head(neck_feats, self.inputs)
  File "/ext3/miniconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/ext3/miniconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/scratch/xxx/git/eye/PaddleYOLO/ppdet/modeling/heads/yolov7_head.py", line 208, in forward
    return self.loss(yolo_outputs, targets, self.anchors)
  File "/ext3/miniconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/ext3/miniconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/scratch/xxx/git/eye/PaddleYOLO/ppdet/modeling/losses/yolov7_loss.py", line 118, in forward
    bs, as_, gjs, gis, targets, anchors = self.build_targets(
  File "/scratch/xxx/git/eye/PaddleYOLO/ppdet/modeling/losses/yolov7_loss.py", line 300, in build_targets
    matching_matrix[gt_idx, pos_idx] = 1.0
IndexError: index 140722276668800 is out of bounds for axis 1 with size 3
```
```shell
python tools/train.py \
    -c configs/yolov7/yolov7_l_300e_coco.yml \
    --amp \
    --eval \
    -o pretrain_weights=/scratch/xxx/weights/yolov7_l_300e_coco.pdparams \
    save_dir=output/${name} \
    TrainReader.batch_size=64 \
    epoch=200
```

这个问题在我这复现了几次，epoch 4结束已经进行了一次eval是正常的。

### 复现环境 Environment

python 3.9

paddlepaddle-gpu 2.3.2

Singularity> uname
Linux
Singularity> uname -r
4.18.0-305.28.1.el8_4.x86_64
Singularity> cat /etc/issue
Ubuntu 20.04.4 LTS \n \l

release/2.5

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [x] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
可以分享下数据集或ai studio链接吗？coco上无法复现这个报错

**Comment by nemonameless** [comment]
已经修复了，请拉最新代码试试
