### ISSUE TITLE
PP-YOLOE-R本地环境中执行预测，报编码错误？

### ISSUE THREAD

**Issue by liang-stu** [PaddlePaddle/PaddleDetection#7467]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

当执行命令 ：python tools/infer.py -c configs/rotate/ppyoloe_r/ppyoloe_r_crn_s_3x_jiantou.yml -o weights=output/ppyoloe_r_crn_s_3x_jiantou/best_model --infer_img=demo/159.jpg --draw_threshold=0.5
报错：
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
Traceback (most recent call last):
  File "tools/infer.py", line 236, in <module>
    main()
  File "tools/infer.py", line 192, in main
    cfg = load_config(FLAGS.config)
  File "D:\Codes\PaddleDetection-develop\ppdet\core\workspace.py", line 114, in load_config
    cfg = _load_config_with_base(file_path)
  File "D:\Codes\PaddleDetection-develop\ppdet\core\workspace.py", line 79, in _load_config_with_base
    file_cfg = yaml.load(f, Loader=yaml.Loader)
  File "D:\ProgramData\Anaconda3\envs\CNN2\lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
  File "D:\ProgramData\Anaconda3\envs\CNN2\lib\site-packages\yaml\loader.py", line 44, in __init__
    Reader.__init__(self, stream)
  File "D:\ProgramData\Anaconda3\envs\CNN2\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "D:\ProgramData\Anaconda3\envs\CNN2\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "D:\ProgramData\Anaconda3\envs\CNN2\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 52: illegal multibyte sequence

**Comment by XYZ-916** [comment]
请检查配置文件中是否存在中文。

**Comment by liang-stu** [comment]
删除配置文件中的中文注释。
