### ISSUE TITLE
ImportError: cannot import name 'get_pose3d_res' from 'ppdet.metrics.json_results' (/home/aistudio/PaddleDetection/ppdet/metrics/json_results.py)

### ISSUE THREAD

**Issue by cunjing56** [PaddlePaddle/PaddleDetection#7516]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

**PPYOLOE：又快又好的小目标检测训练与部署实现**

# 执行批量预测，并生成含有预测结果的bbox.json文件
!python tools/infer.py -c configs/visdrone/ppyoloe_crn_l_alpha_largesize_80e_visdrone.yml -o weights=output/ppyoloe_crn_l_alpha_largesize_80e_visdrone/best_model --infer_dir=../data/test --save_results=True

Warning: Unable to use OC-SORT, please install filterpy, for example: `pip install filterpy`, see https://github.com/rlabbe/filterpy
Traceback (most recent call last):
  File "tools/infer.py", line 19, in <module>
    from ppdet.core.workspace import load_config, merge_config
  File "/home/aistudio/PaddleDetection/ppdet/__init__.py", line 15, in <module>
    from . import (core, data, engine, modeling, model_zoo, optimizer, metrics,
  File "/home/aistudio/PaddleDetection/ppdet/engine/__init__.py", line 15, in <module>
    from . import trainer
  File "/home/aistudio/PaddleDetection/ppdet/engine/trainer.py", line 41, in <module>
    from ppdet.metrics import Metric, COCOMetric, VOCMetric, WiderFaceMetric, get_infer_results, KeyPointTopDownCOCOEval, KeyPointTopDownMPIIEval, Pose3DEval
  File "/home/aistudio/PaddleDetection/ppdet/metrics/__init__.py", line 15, in <module>
    from . import metrics
  File "/home/aistudio/PaddleDetection/ppdet/metrics/metrics.py", line 29, in <module>
    from .coco_utils import get_infer_results, cocoapi_eval
  File "/home/aistudio/PaddleDetection/ppdet/metrics/coco_utils.py", line 24, in <module>
    from ppdet.metrics.json_results import get_det_res, get_det_poly_res, get_seg_res, get_solov2_segm_res, get_keypoint_res, get_pose3d_res
ImportError: cannot import name 'get_pose3d_res' from 'ppdet.metrics.json_results' (/home/aistudio/PaddleDetection/ppdet/metrics/json_results.py)

### 复现环境 Environment

aistudio

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by cunjing56** [comment]
![image](https://user-images.githubusercontent.com/112528302/208808297-80f0fe3c-bc25-47ba-85d9-547e8e6efd48.png)
我已经pip install 这个filterpy了，还是报错。请求支援这个案例能正常运行啊，小白学部署太难了。。。
Traceback (most recent call last):
  File "tools/infer.py", line 19, in <module>
    from ppdet.core.workspace import load_config, merge_config
  File "/home/aistudio/PaddleDetection/ppdet/__init__.py", line 15, in <module>
    from . import (core, data, engine, modeling, model_zoo, optimizer, metrics,
  File "/home/aistudio/PaddleDetection/ppdet/engine/__init__.py", line 15, in <module>
    from . import trainer
  File "/home/aistudio/PaddleDetection/ppdet/engine/trainer.py", line 41, in <module>
    from ppdet.metrics import Metric, COCOMetric, VOCMetric, WiderFaceMetric, get_infer_results, KeyPointTopDownCOCOEval, KeyPointTopDownMPIIEval, Pose3DEval
  File "/home/aistudio/PaddleDetection/ppdet/metrics/__init__.py", line 15, in <module>
    from . import metrics
  File "/home/aistudio/PaddleDetection/ppdet/metrics/metrics.py", line 29, in <module>
    from .coco_utils import get_infer_results, cocoapi_eval
  File "/home/aistudio/PaddleDetection/ppdet/metrics/coco_utils.py", line 24, in <module>
    from ppdet.metrics.json_results import get_det_res, get_det_poly_res, get_seg_res, get_solov2_segm_res, get_keypoint_res, get_pose3d_res
ImportError: cannot import name 'get_pose3d_res' from 'ppdet.metrics.json_results' (/home/aistudio/PaddleDetection/ppdet/metrics/json_results.py)

**Comment by zhiboniu** [comment]
检查一下json_results文件里的get_pose3d_res函数吧，看看是否丢失了。是否有修改文件内容或者删减文件的情况。
