### ISSUE TITLE
开始训练的时候 reader WARNING: fail to map batch transform [Gt2FairMOTTarget_b5d4c7] with error: index 500 is out of bounds for axis 0 with size 500 and stack:

### ISSUE THREAD

**Issue by APJayChan** [PaddlePaddle/PaddleDetection#7533]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

版本2.3 ，数据集使用的是人头追踪的headtracking21并按照相关文档更改了yml文件，请问这是因为什么呢？报错信息如下：

[12/21 16:18:11] reader WARNING: fail to map batch transform [Gt2FairMOTTarget_b5d4c7] with error: index 500 is out of bounds for axis 0 with size 500 and stack:
Traceback (most recent call last):
  File "/home/aistudio/PaddleDetection/ppdet/data/reader.py", line 73, in __call__
    data = f(data)
  File "/home/aistudio/PaddleDetection/ppdet/data/transform/mot_operators.py", line 599, in __call__
    bbox_amodal[2] - ct[0], bbox_amodal[3] - ct[1]
IndexError: index 500 is out of bounds for axis 0 with size 500

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 527, in _thread_loop
    batch = self._get_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 664, in _get_data
    batch.reraise()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 169, in reraise
    raise self.exc_type(msg)
IndexError: DataLoader worker(3) caught IndexError with message:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 329, in _worker_loop
    batch = fetcher.fetch(indices)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 134, in fetch
    data = self.collate_fn(data)
  File "/home/aistudio/PaddleDetection/ppdet/data/reader.py", line 79, in __call__
    raise e
  File "/home/aistudio/PaddleDetection/ppdet/data/reader.py", line 73, in __call__
    data = f(data)
  File "/home/aistudio/PaddleDetection/ppdet/data/transform/mot_operators.py", line 599, in __call__
    bbox_amodal[2] - ct[0], bbox_amodal[3] - ct[1]
IndexError: index 500 is out of bounds for axis 0 with size 500

[12/21 16:18:11] reader WARNING: fail to map batch transform [Gt2FairMOTTarget_b5d4c7] with error: index 500 is out of bounds for axis 0 with size 500 and stack:
Traceback (most recent call last):
  File "/home/aistudio/PaddleDetection/ppdet/data/reader.py", line 73, in __call__
    data = f(data)
  File "/home/aistudio/PaddleDetection/ppdet/data/transform/mot_operators.py", line 599, in __call__
    bbox_amodal[2] - ct[0], bbox_amodal[3] - ct[1]
IndexError: index 500 is out of bounds for axis 0 with size 500

[12/21 16:18:11] reader WARNING: fail to map batch transform [Gt2FairMOTTarget_b5d4c7] with error: index 500 is out of bounds for axis 0 with size 500 and stack:
Traceback (most recent call last):
  File "/home/aistudio/PaddleDetection/ppdet/data/reader.py", line 73, in __call__
    data = f(data)
  File "/home/aistudio/PaddleDetection/ppdet/data/transform/mot_operators.py", line 599, in __call__
    bbox_amodal[2] - ct[0], bbox_amodal[3] - ct[1]
IndexError: index 500 is out of bounds for axis 0 with size 500

[12/21 16:18:13] reader WARNING: fail to map batch transform [Gt2FairMOTTarget_b5d4c7] with error: index 500 is out of bounds for axis 0 with size 500 and stack:
Traceback (most recent call last):
  File "/home/aistudio/PaddleDetection/ppdet/data/reader.py", line 73, in __call__
    data = f(data)
  File "/home/aistudio/PaddleDetection/ppdet/data/transform/mot_operators.py", line 599, in __call__
    bbox_amodal[2] - ct[0], bbox_amodal[3] - ct[1]
IndexError: index 500 is out of bounds for axis 0 with size 500

[12/21 16:18:13] reader WARNING: fail to map batch transform [Gt2FairMOTTarget_b5d4c7] with error: index 500 is out of bounds for axis 0 with size 500 and stack:
Traceback (most recent call last):
  File "/home/aistudio/PaddleDetection/ppdet/data/reader.py", line 73, in __call__
    data = f(data)
  File "/home/aistudio/PaddleDetection/ppdet/data/transform/mot_operators.py", line 599, in __call__
    bbox_amodal[2] - ct[0], bbox_amodal[3] - ct[1]
IndexError: index 500 is out of bounds for axis 0 with size 500

[12/21 16:18:14] ppdet.utils.download INFO: Downloading fairmot_dla34_crowdhuman_pretrained.pdparams from https://paddledet.bj.bcebos.com/models/pretrained/fairmot_dla34_crowdhuman_pretrained.pdparams

  0%|          | 0/127930 [00:00<?, ?KB/s]
  4%|▎         | 4731/127930 [00:00<00:02, 47260.35KB/s]
 10%|▉         | 12184/127930 [00:00<00:01, 63292.20KB/s]
 15%|█▌        | 19729/127930 [00:00<00:01, 68838.96KB/s]
 21%|██▏       | 27203/127930 [00:00<00:01, 71162.20KB/s]
 27%|██▋       | 34593/127930 [00:00<00:01, 72146.97KB/s]
 33%|███▎      | 41808/127930 [00:00<00:01, 72110.73KB/s]
 39%|███▊      | 49368/127930 [00:00<00:01, 73247.67KB/s]
 44%|████▍     | 56875/127930 [00:00<00:00, 73824.34KB/s]
 50%|█████     | 64258/127930 [00:00<00:00, 73490.83KB/s]
 56%|█████▌    | 71840/127930 [00:01<00:00, 74204.59KB/s]
 62%|██████▏   | 79261/127930 [00:01<00:00, 73992.26KB/s]
 68%|██████▊   | 86661/127930 [00:01<00:00, 73539.18KB/s]
 74%|███████▎  | 94107/127930 [00:01<00:00, 73811.75KB/s]
 79%|███████▉  | 101619/127930 [00:01<00:00, 74195.24KB/s]
 85%|████████▌ | 109040/127930 [00:01<00:00, 73758.71KB/s]
 91%|█████████ | 116655/127930 [00:01<00:00, 74471.49KB/s]
 97%|█████████▋| 124208/127930 [00:01<00:00, 74786.79KB/s]
100%|██████████| 127930/127930 [00:01<00:00, 72596.34KB/s]
[12/21 16:18:17] ppdet.utils.checkpoint INFO: The shape [14455] in pretrained weight reid.classifier.bias is unmatched with the shape [2712] in model reid.classifier.bias. And the weight reid.classifier.bias will not be loaded
[12/21 16:18:17] ppdet.utils.checkpoint INFO: The shape [128, 14455] in pretrained weight reid.classifier.weight is unmatched with the shape [128, 2712] in model reid.classifier.weight. And the weight reid.classifier.weight will not be loaded
[12/21 16:18:17] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/aistudio/.cache/paddle/weights/fairmot_dla34_crowdhuman_pretrained.pdparams
Traceback (most recent call last):
  File "tools/train.py", line 171, in <module>
    main()
  File "tools/train.py", line 167, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/home/aistudio/PaddleDetection/ppdet/engine/trainer.py", line 379, in train
    for step_id, data in enumerate(self.loader):
  File "/home/aistudio/PaddleDetection/ppdet/data/reader.py", line 209, in __next__
    return next(self.loader)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 738, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

INFO 2022-12-21 16:18:23,031 launch_utils.py:343] terminate all the procs
INFO 2022-12-21 16:18:23,031 launch_utils.py:343] terminate all the procs
ERROR 2022-12-21 16:18:23,032 launch_utils.py:642] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
ERROR 2022-12-21 16:18:23,032 launch_utils.py:642] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2022-12-21 16:18:27,034 launch_utils.py:343] terminate all the procs
INFO 2022-12-21 16:18:27,034 launch_utils.py:343] terminate all the procs
INFO 2022-12-21 16:18:27,034 launch.py:402] Local processes completed.
INFO 2022-12-21 16:18:27,034 launch.py:402] Local processes completed.

**Comment by ghostxsl** [comment]
看报错信息应该是数据有问题，可以debug下看看数据格式是否正确呢

**Comment by APJayChan** [comment]
已解决，是生成的labels_with_ids文件出现错误，重新生成就可以训练了

**Comment by hu-qi** [comment]
> 已解决，是生成的labels_with_ids文件出现错误，重新生成就可以训练了

遇到类似的问题 #7683 ，请问您说的 ”labels_with_ids文件出现错误“ 具体是什么错误，怎么修正？ 

感谢！

```
2.4.1
/home/ma-user/work/ma_share/bdd100k2mot_min/PaddleDetection
LAUNCH INFO 2023-02-17 14:08:35,589 -----------  Configuration  ----------------------
LAUNCH INFO 2023-02-17 14:08:35,589 devices: 0
LAUNCH INFO 2023-02-17 14:08:35,589 elastic_level: -1
LAUNCH INFO 2023-02-17 14:08:35,589 elastic_timeout: 30
LAUNCH INFO 2023-02-17 14:08:35,589 gloo_port: 6767
LAUNCH INFO 2023-02-17 14:08:35,589 host: None
LAUNCH INFO 2023-02-17 14:08:35,589 ips: None
LAUNCH INFO 2023-02-17 14:08:35,589 job_id: default
LAUNCH INFO 2023-02-17 14:08:35,589 legacy: False
LAUNCH INFO 2023-02-17 14:08:35,589 log_dir: ./fairmot_dla34_30e_1088x608_bdd100kmot_vehicle-2023021701/
LAUNCH INFO 2023-02-17 14:08:35,589 log_level: INFO
LAUNCH INFO 2023-02-17 14:08:35,589 master: None
LAUNCH INFO 2023-02-17 14:08:35,589 max_restart: 3
LAUNCH INFO 2023-02-17 14:08:35,589 nnodes: 1
LAUNCH INFO 2023-02-17 14:08:35,589 nproc_per_node: None
LAUNCH INFO 2023-02-17 14:08:35,589 rank: -1
LAUNCH INFO 2023-02-17 14:08:35,589 run_mode: collective
LAUNCH INFO 2023-02-17 14:08:35,589 server_num: None
LAUNCH INFO 2023-02-17 14:08:35,589 servers: 
LAUNCH INFO 2023-02-17 14:08:35,589 start_port: 6070
LAUNCH INFO 2023-02-17 14:08:35,589 trainer_num: None
LAUNCH INFO 2023-02-17 14:08:35,590 trainers: 
LAUNCH INFO 2023-02-17 14:08:35,590 training_script: tools/train.py
LAUNCH INFO 2023-02-17 14:08:35,590 training_script_args: ['-c', 'configs/mot/vehicle/fairmot_dla34_30e_1088x608_bdd100kmot_vehicle.yml']
LAUNCH INFO 2023-02-17 14:08:35,590 with_gloo: 1
LAUNCH INFO 2023-02-17 14:08:35,590 --------------------------------------------------
LAUNCH INFO 2023-02-17 14:08:35,595 Job: default, mode collective, replicas 1[1:1], elastic False
LAUNCH INFO 2023-02-17 14:08:35,606 Run Pod: nfqoja, replicas 1, status ready
LAUNCH INFO 2023-02-17 14:08:35,620 Watching Pod: nfqoja, replicas 1, status running
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
[02/17 14:08:40] ppdet.data.source.mot INFO: MOT dataset summary: 
[02/17 14:08:40] ppdet.data.source.mot INFO: OrderedDict([('bdd100kmot_vehicle.train', 84638)])
[02/17 14:08:40] ppdet.data.source.mot INFO: Total images: 1619
[02/17 14:08:40] ppdet.data.source.mot INFO: Image start index: OrderedDict([('bdd100kmot_vehicle.train', 0)])
[02/17 14:08:40] ppdet.data.source.mot INFO: Total identities: 84639
[02/17 14:08:40] ppdet.data.source.mot INFO: Identity start index: OrderedDict([('bdd100kmot_vehicle.train', 0)])
W0217 14:08:42.418386 15058 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.0, Driver API Version: 10.2, Runtime API Version: 10.2
W0217 14:08:42.424360 15058 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
[02/17 14:08:42] reader WARNING: fail to map batch transform [Gt2FairMOTTarget_cc476e] with error: index 2 is out of bounds for axis 0 with size 1 and stack:
Traceback (most recent call last):
  File "/home/ma-user/work/ma_share/bdd100k2mot_min/PaddleDetection/ppdet/data/reader.py", line 78, in __call__
    data = f(data)
  File "/home/ma-user/work/ma_share/bdd100k2mot_min/PaddleDetection/ppdet/data/transform/mot_operators.py", line 596, in __call__
    self.draw_truncate_gaussian(heatmap[cls_id], ct_int, radius,radius)
IndexError: index 2 is out of bounds for axis 0 with size 1

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ma-user/anaconda3/envs/python-3.7.10/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/ma-user/anaconda3/envs/python-3.7.10/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ma-user/anaconda3/envs/python-3.7.10/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 218, in _thread_loop
    self._thread_done_event)
  File "/home/ma-user/anaconda3/envs/python-3.7.10/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 138, in fetch
    data = self.collate_fn(data)
  File "/home/ma-user/work/ma_share/bdd100k2mot_min/PaddleDetection/ppdet/data/reader.py", line 84, in __call__
    raise e
  File "/home/ma-user/work/ma_share/bdd100k2mot_min/PaddleDetection/ppdet/data/reader.py", line 78, in __call__
    data = f(data)
  File "/home/ma-user/work/ma_share/bdd100k2mot_min/PaddleDetection/ppdet/data/transform/mot_operators.py", line 596, in __call__
    self.draw_truncate_gaussian(heatmap[cls_id], ct_int, radius,radius)
IndexError: index 2 is out of bounds for axis 0 with size 1
```

**Comment by hu-qi** [comment]
> 已解决，是生成的labels_with_ids文件出现错误，重新生成就可以训练了

如 @APJayChan 大大所说，确实是生成的 label 文件有问题，估计是我没处理好
