### ISSUE TITLE
PicoDet训练时出现问题：must be tensor but got tensor

### ISSUE THREAD

**Issue by DurableFrank** [PaddlePaddle/PaddleDetection#7623]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

!python tools/train.py -c configs/picodet/picodet_l_640_coco.yml --eval

Traceback (most recent call last):
  File "tools/train.py", line 171, in <module>
    main()
  File "tools/train.py", line 167, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/home/aistudio/PaddleDetection-2.3.0/ppdet/engine/trainer.py", line 450, in train
    self._eval_with_loader(self._eval_loader)
  File "/home/aistudio/PaddleDetection-2.3.0/ppdet/engine/trainer.py", line 470, in _eval_with_loader
    outs = self.model(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleDetection-2.3.0/ppdet/modeling/architectures/meta_arch.py", line 56, in forward
    out = self.get_pred()
  File "/home/aistudio/PaddleDetection-2.3.0/ppdet/modeling/architectures/picodet.py", line 89, in get_pred
    bbox_pred, bbox_num = self._forward()
  File "/home/aistudio/PaddleDetection-2.3.0/ppdet/modeling/architectures/picodet.py", line 72, in _forward
    scale_factor)
  File "/home/aistudio/PaddleDetection-2.3.0/ppdet/modeling/heads/gfl_head.py", line 479, in post_process
    bbox_pred, bbox_num, _ = self.nms(bboxes, score)
  File "/home/aistudio/PaddleDetection-2.3.0/ppdet/modeling/layers.py", line 473, in __call__
    return ops.multiclass_nms(bboxes, score, **kwargs)
  File "/home/aistudio/PaddleDetection-2.3.0/ppdet/modeling/ops.py", line 984, in multiclass_nms
    rois_num, *attrs)
ValueError: (InvalidArgument) multiclass_nms3(): argument 'BBoxes' (position 0) must be Tensor, but got Tensor (at /paddle/paddle/fluid/pybind/op_function_common.cc:818)

**Comment by jerrywgz** [comment]
需要更新下paddledetection的版本到release/2.5

**Comment by DurableFrank** [comment]
> 需要更新下paddledetection的版本到release/2.5

早上试着更新了，但还是出现相同的问题

**Comment by JamesLim-sy** [comment]
@jerrywgz  Please help check this issue.

**Comment by DurableFrank** [comment]
@jerrywgz 可以更新以后出现同样的问题，请问是哪里不对呢

**Comment by lyuwenyu** [comment]
paddle用的是那个版本？

`ppdet 2.5, paddle 2.4.1` 这样搭配试一下
