### ISSUE TITLE
paddle-gpu1.7.1,最新版本的paddleDetection安装后按照readme中的提示去检测，结果不通过

### ISSUE THREAD

**Issue by zouxiaokun** [PaddlePaddle/PaddleDetection#763]
(paddlle) D:\Users\paddlepaddle\PaddleDetection>python ppdet/modeling/tests/test_architectures.py
ssD:\Users\paddlepaddle\PaddleDetection\ppdet\core\workspace.py:117: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.
abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  isinstance(merge_dct[k], collections.Mapping)):
........EE
======================================================================
ERROR: test_test (__main__.TestYolov3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Users\paddlepaddle\PaddleDetection\ppdet\modeling\tests\decorator_helper.py", line 29, in __fn__
    fn(*args, **kwargs)
  File "ppdet/modeling/tests/test_architectures.py", line 57, in test_test
    test_fetches = model.eval(feed_vars)
  File "D:\Users\paddlepaddle\PaddleDetection\ppdet\modeling\architectures\yolo.py", line 159, in eval
    return self.build(feed_vars, mode='test')
  File "D:\Users\paddlepaddle\PaddleDetection\ppdet\modeling\architectures\yolo.py", line 91, in build
    return self.yolo_head.get_prediction(body_feats, im_size)
  File "D:\Users\paddlepaddle\PaddleDetection\ppdet\modeling\anchor_heads\yolo_head.py", line 330, in get_prediction
    scale_x_y=scale_x_y)
TypeError: yolo_box() got an unexpected keyword argument 'scale_x_y'

======================================================================
ERROR: test_train (__main__.TestYolov3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Users\paddlepaddle\PaddleDetection\ppdet\modeling\tests\decorator_helper.py", line 29, in __fn__
    fn(*args, **kwargs)
  File "ppdet/modeling/tests/test_architectures.py", line 49, in test_train
    train_fetches = model.train(feed_vars)
  File "D:\Users\paddlepaddle\PaddleDetection\ppdet\modeling\architectures\yolo.py", line 156, in train
    return self.build(feed_vars, mode='train')
  File "D:\Users\paddlepaddle\PaddleDetection\ppdet\modeling\architectures\yolo.py", line 85, in build
    gt_score, targets)
  File "D:\Users\paddlepaddle\PaddleDetection\ppdet\modeling\anchor_heads\yolo_head.py", line 294, in get_loss
    self.prefix_name)
  File "D:\Users\paddlepaddle\PaddleDetection\ppdet\modeling\losses\yolo_loss.py", line 88, in __call__
    name=prefix_name + "yolo_loss" + str(i))
TypeError: yolov3_loss() got an unexpected keyword argument 'scale_x_y'

----------------------------------------------------------------------
Ran 12 tests in 6.169s

FAILED (errors=2, skipped=2)

**Comment by heavengate** [comment]
最新的master分支需要依赖Paddle 2.0版本，使用Paddle1.7版本的话可以用release/0.3分支。
安装Paddle2.0版本：
```
pip install paddlepaddle-gpu==2.0.0.a0
```
