### ISSUE TITLE
导出模型时候有误

### ISSUE THREAD

**Issue by yzl19940819** [PaddlePaddle/PaddleDetection#764]
导出模型时候报错  export.py

The 'num_classes'(number of classes) you set is 80, and 'with_background' in 'dataset' sets False.
So please note the actual number of categories is 80

**Comment by still-wait** [comment]
@yzl19940819 这个信息不是报错，是让你确认你的真实类别数是否确认。

**Comment by yzl19940819** [comment]
2020-05-22 21:58:30,567-INFO: The 'num_classes'(number of classes) you set is 80, and 'with_background' in 'dataset' sets False.
So please note the actual number of categories is 80.
Traceback (most recent call last):
  File "tools/export_model.py", line 215, in <module>
    main()
  File "tools/export_model.py", line 196, in main
    test_fetches = model.test(feed_vars)
  File "E:\0522\PaddleDetection-master\ppdet\modeling\architectures\yolo.py", line 162, in test
    return self.build(feed_vars, mode='test')
  File "E:\0522\PaddleDetection-master\ppdet\modeling\architectures\yolo.py", line 91, in build
    return self.yolo_head.get_prediction(body_feats, im_size)
  File "E:\0522\PaddleDetection-master\ppdet\modeling\anchor_heads\yolo_head.py", line 330, in get_prediction
    scale_x_y=scale_x_y)
TypeError: yolo_box() got an unexpected keyword argument 'scale_x_y'


相关的错误内容应该是这些    使用的是master分支

**Comment by qingqing01** [comment]
@yzl19940819  Release/0.3分支可以使用paddle >=1.7, 1.8版本的。 master分支，给YOLOv4添加了scale_x_y的配置，需要使用paddle 2.0-alpha版本。

**Comment by yzl19940819** [comment]
目前我看到官网上提示最新的下载版本是1.8.1，2.0在哪里下载，还有就是关于paddle的版本和版本查询，版本升级的方式是否有文档

**Comment by qingqing01** [comment]
@yzl19940819 

2.0-alpha版本:
https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-alpha/install/index_cn.htm
 
```
# 安装GPU
python -m pip install paddlepaddle-gpu==2.0.0a0 -i https://mirror.baidu.com/pypi/simple
# 安装CPU:
python -m pip install paddlepaddle==2.0.0a0 -i https://mirror.baidu.com/pypi/simple
```

版本查询：

```
import paddle
print(paddle.__version__)
```

官网的查询：左上角有个版本切换

<img width="1103" alt="图片" src="https://user-images.githubusercontent.com/7845005/82725123-6d2ca700-9d0d-11ea-9dfb-44a9c0f9b6ea.png">

**Comment by yzl19940819** [comment]
@qingqing01 非常感谢
