### ISSUE TITLE
LayoutAnalysis training Issue in Model Arch.

### ISSUE THREAD

**Issue by TapendraBaduwal** [PaddlePaddle/PaddleDetection#7644]
When model inference is complete then i get Model Arch: GFL
----------- Model Configuration -----------
Model Arch: GFL

But i want Model Arch: PicoDet
----------- Model Configuration -----------
Model Arch: PicoDet

MY picodet_lcnet_x1_0_layout.yml file contain
PicoDet:
backbone: LCNet
neck: CSPPAN
head: PicoHead

But But after training i got infer_cfg.yml in which arch is GFL
mode: paddle
draw_threshold: 0.5
metric: COCO
use_dynamic_shape: false
arch: GFL

I have already tested my layout analysis model in PaddlePaddle version 2.4.1 and 2.3.2, but I am still encountering the same error.
PaddleDetection=latest code

**Comment by nemonameless** [comment]
see https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/ppdet/engine/export_utils.py#L191
same issue #7643  #7642

**Comment by TapendraBaduwal** [comment]
@nemonameless Error at Model inference

After running below script 
python3 deploy/python/infer.py \
    --model_dir=output_inference/picodet_lcnet_x1_0_layout/ \
    --image_file=./docs/images/layout.jpg \
    --device=CPU

Error msg

batch_size: 1
camera_id: -1
combine_method: nms
cpu_threads: 1
device: CPU
enable_mkldnn: False
enable_mkldnn_bfloat16: False
image_dir: None
image_file: ./docs/images/layout.jpg
match_metric: ios
match_threshold: 0.6
model_dir: output_inference/picodet_lcnet_x1_0_layout/
output_dir: output
overlap_ratio: [0.25, 0.25]
random_pad: False
reid_batch_size: 50
reid_model_dir: None
run_benchmark: False
run_mode: paddle
save_images: True
save_mot_txt_per_img: False
save_mot_txts: False
save_results: False
scaled: False
slice_infer: False
slice_size: [640, 640]
threshold: 0.5
tracker_config: None
trt_calib_mode: False
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
use_coco_category: False
use_dark: True
use_gpu: False
video_file: None
window_size: 50
------------------------------------------
-----------  Model Configuration -----------
Model Arch: PicoDet
Transform Order: 
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--transform op: PadStride
--------------------------------------------
Traceback (most recent call last):
  File "deploy/python/infer.py", line 1054, in <module>
    main()
  File "deploy/python/infer.py", line 1022, in main
    detector.predict_image(
  File "deploy/python/infer.py", line 402, in predict_image
    result = self.postprocess(inputs, result)
  File "deploy/python/infer.py", line 658, in postprocess
    np_boxes, np_boxes_num = postprocessor(np_score_list, np_boxes_list)
  File "/content/PaddleDetection/deploy/python/picodet_postprocess.py", line 160, in __call__
    box_distance = np.sum(box_distance, axis=1).reshape((-1, 4))
ValueError: cannot reshape array of size 1 into shape (4)
