### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by liu824** [PaddlePaddle/PaddleDetection#766]
使用yolov3_mobilenet_v3进行训练出现以下错误

```
Traceback (most recent call last):
  File "PaddleDetection-release-0.3/tools/train.py", line 365, in <module>
    FLAGS = parser.parse_args()
  File "/home/aistudio/PaddleDetection-release-0.3/ppdet/utils/cli.py", line 58, in parse_args
    args.opt = self._parse_opt(args.opt)
  File "/home/aistudio/PaddleDetection-release-0.3/ppdet/utils/cli.py", line 67, in _parse_opt
    k, v = s.split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

模型训练配置如下：

```
!python -u PaddleDetection-release-0.3/tools/train.py -c PaddleDetection-release-0.3/configs/yolov3_mobilenet_v3.yml\
                                                    -o num_classes 1\
                                                    -o num_max_boxes 505\
                                                    -o dataset_dir /home/aistudio/PaddleDetection-release-0.3/dataset/density/body_train\
                                                    -o anno_path train.txt\
                                                    -o image_dir JPEGImages
```

**Comment by qingqing01** [comment]
`-o`只加一个即可，` -o num_classes=1 xx=xx` 这样写。 建议您直接在 `PaddleDetection-release-0.3/configs/yolov3_mobilenet_v3.yml` 中更改num_class, num_max_boxes, dataset_dir, anno_path, image_dir等，注意reader相关配置中也要修改num_max_boxes这些参数。

**Comment by liu824** [comment]
我发现yoloreader.yml中只有coco数据集格式才能读取，这个不能设置为voc数据集吗？

**Comment by liu824** [comment]
谢谢，我还有一个问题，为什么有的设置是用等号，有的设置是上面我用的那样呢

**Comment by qingqing01** [comment]
@liu824 
1. VOC的参考 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/configs/yolov3_r34_voc.yml#L70
2.  -o的参数参考： https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/docs/tutorials/GETTING_STARTED_cn.md#%E5%8F%AF%E9%80%89%E5%8F%82%E6%95%B0%E5%88%97%E8%A1%A8  作用是，通过命令行配置YML配置文件里的参数， 非YML里的参数不加-o。
