### ISSUE TITLE
"ValueError: setting an array element with a sequence." When training on coco data.

### ISSUE THREAD

**Issue by 95maddycode** [PaddlePaddle/PaddleDetection#7668]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

DataProcess

### Bug描述 Describe the Bug

While loading annotations into memory, I get the following error:

Traceback (most recent call last):
  File "PaddleDetection\train.py", line 107, in <module>
    main()
  File "PaddleDetection\train.py", line 103, in main
    run(FLAGS, cfg)
  File "PaddleDetection\train.py", line 48, in run
    trainer = Trainer(cfg, mode='train')
  File "PaddleDetection\ppdet\engine\trainer.py", line 94, in __init__
    self.loader = create('{}Reader'.format(capital_mode))(
  File "PaddleDetection\ppdet\data\reader.py", line 163, in __call__
    self.dataset.parse_dataset()
  File "PaddleDetection\ppdet\data\source\coco.py", line 187, in parse_dataset       
    if not np.array(box['segmentation']
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

When checking what is in some of the box['segmentation'] values, I see the following outcomes: 

box['segmentation']: [[500.49, 473.53, 599.73, 419.6, 612.67, 375.37, 608.36, 354.88, 528.54, 269.66, 457.35, 201.71, 420.67, 187.69, 389.39, 192.0, 19.42, 360.27, 1.08, 389.39, 2.16, 427.15, 20.49, 473.53]]

box['segmentation']: [[357.03, 69.03, 311.73, 15.1, 550.11, 4.31, 631.01, 62.56, 629.93, 88.45, 595.42, 185.53, 513.44, 230.83, 488.63, 232.99, 437.93, 190.92, 429.3, 189.84, 434.7, 148.85, 410.97, 121.89, 359.19, 74.43, 358.11, 65.8]]

box['segmentation']: [[249.6, 348.99, 267.67, 311.72, 291.39, 294.78, 304.94, 294.78, 326.4, 283.48, 345.6, 273.32, 368.19, 269.93, 385.13, 268.8, 388.52, 257.51, 393.04, 250.73, 407.72, 240.56, 425.79, 230.4, 441.6, 229.27, 447.25, 237.18, 447.25, 256.38, 456.28, 254.12, 475.48, 263.15, 486.78, 271.06, 495.81, 264.28, 498.07, 257.51, 500.33, 255.25, 507.11, 259.76, 513.88, 266.54, 513.88, 273.32, 513.88, 276.71, 526.31, 276.71, 526.31, 286.87, 519.53, 291.39, 519.53, 297.04, 524.05, 306.07, 525.18, 315.11, 529.69, 329.79, 529.69, 337.69, 530.82, 348.99, 536.47, 339.95, 545.51, 350.12, 555.67, 360.28, 557.93, 380.61, 561.32, 394.16, 565.84, 413.36, 522.92, 441.6, 469.84, 468.71, 455.15, 474.35, 307.2, 474.35, 316.24, 464.19, 330.92, 438.21, 325.27, 399.81, 310.59, 378.35, 301.55, 371.58, 252.99, 350.12]]

NOTE: In the next example, the list exists of TWO SEPERATE lists!!!!
box['segmentation']: [[434.48, 152.33, 433.51, 184.93, 425.44, 189.45, 376.7, 195.58, 266.94, 248.53, 179.78, 290.17, 51.62, 346.66, 16.43, 366.68, 1.9, 388.63, 0.0, 377.33, 0.0, 357.64, 0.0, 294.04, 22.56, 294.37, 56.14, 300.82, 83.58, 300.82, 109.08, 289.2, 175.26, 263.38, 216.9, 243.36, 326.34, 197.52, 387.03, 172.34, 381.54, 162.33, 380.89, 147.16, 380.89, 140.06, 370.89, 102.29, 330.86, 61.94, 318.91, 48.38, 298.57, 47.41, 287.28, 37.73, 259.51, 33.85, 240.14, 32.56, 240.14, 28.36, 247.57, 24.17, 271.46, 15.13, 282.11, 13.51, 296.96, 18.68, 336.34, 55.48, 391.55, 106.81, 432.87, 147.16], [62.46, 97.21, 130.25, 69.77, 161.25, 59.12, 183.52, 52.02, 180.94, 59.12, 170.93, 78.17, 170.28, 90.76, 157.05, 95.92, 130.25, 120.78, 119.92, 129.49, 102.17, 115.29, 64.72, 119.81, 0.0, 137.89, 0.0, 120.13, 0.0, 117.87]]

There is no error in the first three, only the last one gets an error. It seems that it is not possible to execute the code: np.array(box['segmentation']) in line 187 for this last one, because this list consists of two seperate lists. 

This is the data that is downloaded directly from the coco website. I did not alter this data. It seems like the script to prepare this coco data, hence does not work.

### 复现环境 Environment

OS: Windows
PaddlePaddle: 2.3.1
PaddleDetection: release/2.5
Python: 3.9.16
CUDA: 11.1
CUDNN: 7.6

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by 710350964** [comment]
问题相似，同样训练coco数据集。我是在电脑上用cmd方式调用python程序，报错。环境配置：paddle==2.4.1，detection==2.5，python=3.9.16

**Comment by TimeYWL** [comment]
In this issue: #7539
