### ISSUE TITLE
请教 bdd100kmot 数据集处理 img1 文件夹不能正常生成文件的问题

### ISSUE THREAD

**Issue by hu-qi** [PaddlePaddle/PaddleDetection#7683]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

参考文档：[数据集准备和处理](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/mot/vehicle#%E6%95%B0%E6%8D%AE%E9%9B%86%E5%87%86%E5%A4%87%E5%92%8C%E5%A4%84%E7%90%86)

操作步骤：
1. 数据准备：鉴于数据集太大，只选取了 bdd100kmot 一个tarin2和一个val1的数据
![image](https://user-images.githubusercontent.com/17986122/216837596-8befbed4-b108-45d5-b749-d82f0475b037.png)

2. tools 代码准备：gen_bdd100kmot_vehicle.sh class只保留了 2 ; bdd100k2mot.py cp 操作加了文件存在才执行的判断; gen_labels_MOT.py 注释了移除labels_with_ids的操作
![image](https://user-images.githubusercontent.com/17986122/216838046-f92cc25d-8a0a-48f0-9d04-b9afc17c5f09.png)

3.sh gen_bdd100kmot_vehicle.sh 运行结果

![image](https://user-images.githubusercontent.com/17986122/216838177-76196464-637e-4ee5-8828-986b266c56fe.png)

想请教一下这个 img1 文件夹下不能生成文件一般是什么原因？如何修正？

感谢！

-------------------------------------------------
训练日志：
```
Warning: Unable to use JDE/FairMOT/ByteTrack, please install lap, for example: `pip install lap`, see https://github.com/gatagat/lap
Warning: Unable to use OC-SORT, please install filterpy, for example: `pip install filterpy`, see https://github.com/rlabbe/filterpy
Warning: Unable to use MOT metric, please install motmetrics, for example: `pip install motmetrics`, see https://github.com/longcw/py-motmetrics
Warning: Unable to use MCMOT metric, please install motmetrics, for example: `pip install motmetrics`, see https://github.com/longcw/py-motmetrics
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
[02/06 02:04:05] ppdet.data.source.mot INFO: MOT dataset summary: 
[02/06 02:04:05] ppdet.data.source.mot INFO: OrderedDict([('bdd100kmot_vehicle.train', 112819)])
[02/06 02:04:05] ppdet.data.source.mot INFO: Total images: 278079
[02/06 02:04:05] ppdet.data.source.mot INFO: Image start index: OrderedDict([('bdd100kmot_vehicle.train', 0)])
[02/06 02:04:05] ppdet.data.source.mot INFO: Total identities: 112820
[02/06 02:04:05] ppdet.data.source.mot INFO: Identity start index: OrderedDict([('bdd100kmot_vehicle.train', 0)])
[02/06 02:04:05] ppdet.data.source.mot WARNING: Illegal image file: dataset/mot/bdd100k/bdd100kmot_vehicle/images/train/0000f77c-6257be58/img1/0000f77c-6257be58-0000001.jpg, and it will be ignored
[02/06 02:04:05] ppdet.data.source.mot WARNING: Illegal image file: dataset/mot/bdd100k/bdd100kmot_vehicle/images/train/0000f77c-6257be58/img1/0000f77c-6257be58-0000002.jpg, and it will be ignored
[02/06 02:04:05] ppdet.data.source.mot WARNING: Illegal image file: dataset/mot/bdd100k/bdd100kmot_vehicle/images/train/0000f77c-6257be58/img1/0000f77c-6257be58-0000003.jpg, and it will be ignored
[02/06 02:04:05] ppdet.data.source.mot WARNING: Illegal image file: dataset/mot/bdd100k/bdd100kmot_vehicle/images/train/0000f77c-6257be58/img1/0000f77c-6257be58-0000004.jpg, and it will be ignored
[02/06 02:04:05] ppdet.data.source.mot WARNING: Illegal image file: dataset/mot/bdd100k/bdd100kmot_vehicle/images/train/0000f77c-6257be58/img1/0000f77c-6257be58-0000005.jpg, and it will be ignored
[02/06 02:04:05] ppdet.data.source.mot WARNING: Illegal image file: dataset/mot/bdd100k/bdd100kmot_vehicle/images/train/0000f77c-6257be58/img1/0000f77c-6257be58-0000006.jpg, and it will be ignored
[02/06 02:04:05] ppdet.data.source.mot WARNING: Illegal image file: dataset/mot/bdd100k/bdd100kmot_vehicle/images/train/0000f77c-6257be58/img1/0000f77c-6257be58-0000007.jpg, and it will be ignored
......
[02/06 02:04:17] ppdet.data.source.mot WARNING: Illegal image file: dataset/mot/bdd100k/bdd100kmot_vehicle/images/train/03d93dd6-990f83bb/img1/03d93dd6-990f83bb-0000201.jpg, and it will be ignored
[02/06 02:04:17] ppdet.data.source.mot WARNING: Illegal image file: dataset/mot/bdd100k/bdd100kmot_vehicle/images/train/03d93dd6-990f83bb/img1/03d93dd6-990f83bb-0000202.jpg, and it will be ignored
Traceback (most recent call last):
  File "tools/train.py", line 172, in <module>
    main()
  File "tools/train.py", line 168, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 123, in run
    trainer = Trainer(cfg, mode='train')
  File "/home/ma-user/work/PaddleDetection/ppdet/engine/trainer.py", line 95, in __init__
    self.dataset, cfg.worker_num)
  File "/home/ma-user/work/PaddleDetection/ppdet/data/reader.py", line 163, in __call__
    self.dataset.parse_dataset()
  File "/home/ma-user/work/PaddleDetection/ppdet/data/source/mot.py", line 227, in parse_dataset
    self.image_lists)
AssertionError: not found any mot record in ['bdd100kmot_vehicle.train']

```

**Comment by nemonameless** [comment]
训练报错log是数据集路径不对，先把这个改过来吧，bdd100kmot_vehicle.train 显示27.8万张是所有训练集的，你只选了一部分去训就需要改 bdd100kmot_vehicle.train。img1 文件夹下的是eval用的，就是把原始图片移动进去，不按提供的脚本自己写一个也不难的。

**Comment by hu-qi** [comment]
> 训练报错log是数据集路径不对，先把这个改过来吧，bdd100kmot_vehicle.train 显示27.8万张是所有训练集的，你只选了一部分去训就需要改 bdd100kmot_vehicle.train。img1 文件夹下的是eval用的，就是把原始图片移动进去，不按提供的脚本自己写一个也不难的。

感谢您的解答。我这边处理完数据之后，运行训练脚本
`CUDA_VISIBLE_DEVICES=0 python  tools/train.py   -c configs/mot/vehicle/fairmot_dla34_30e_1088x608_bdd100kmot_vehicle.yml`
时报如下的错：

```
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
[02/07 09:41:03] ppdet.data.source.mot INFO: MOT dataset summary: 
[02/07 09:41:03] ppdet.data.source.mot INFO: OrderedDict([('bdd100kmot_vehicle.train', 112741)])
[02/07 09:41:03] ppdet.data.source.mot INFO: Total images: 39990
[02/07 09:41:03] ppdet.data.source.mot INFO: Image start index: OrderedDict([('bdd100kmot_vehicle.train', 0)])
[02/07 09:41:03] ppdet.data.source.mot INFO: Total identities: 112742
[02/07 09:41:03] ppdet.data.source.mot INFO: Identity start index: OrderedDict([('bdd100kmot_vehicle.train', 0)])
W0207 09:41:18.153070 19687 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.0, Driver API Version: 10.2, Runtime API Version: 10.2
W0207 09:41:18.158303 19687 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
[02/07 09:41:18] reader WARNING: fail to map sample transform [RandomFlip_5f91aa] with error: 'NoneType' object is not subscriptable and stack:
Traceback (most recent call last):
  File "/home/ma-user/work/PaddleDetection/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/home/ma-user/work/PaddleDetection/ppdet/data/transform/operators.py", line 104, in __call__
    sample = self.apply(sample, context)
  File "/home/ma-user/work/PaddleDetection/ppdet/data/transform/operators.py", line 686, in apply
    im = sample['image']
TypeError: 'NoneType' object is not subscriptable

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ma-user/anaconda3/envs/python-3.7.10/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/ma-user/anaconda3/envs/python-3.7.10/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ma-user/anaconda3/envs/python-3.7.10/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 536, in _thread_loop
    batch = self._get_data()
  File "/home/ma-user/anaconda3/envs/python-3.7.10/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 674, in _get_data
    batch.reraise()
  File "/home/ma-user/anaconda3/envs/python-3.7.10/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 172, in reraise
    raise self.exc_type(msg)
TypeError: DataLoader worker(1) caught TypeError with message:
Traceback (most recent call last):
  File "/home/ma-user/anaconda3/envs/python-3.7.10/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 339, in _worker_loop
    batch = fetcher.fetch(indices)
  File "/home/ma-user/anaconda3/envs/python-3.7.10/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 125, in fetch
    data.append(self.dataset[idx])
  File "/home/ma-user/work/PaddleDetection/ppdet/data/source/dataset.py", line 96, in __getitem__
    return self.transform(roidb)
  File "/home/ma-user/work/PaddleDetection/ppdet/data/reader.py", line 60, in __call__
    raise e
  File "/home/ma-user/work/PaddleDetection/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/home/ma-user/work/PaddleDetection/ppdet/data/transform/operators.py", line 104, in __call__
    sample = self.apply(sample, context)
  File "/home/ma-user/work/PaddleDetection/ppdet/data/transform/operators.py", line 686, in apply
    im = sample['image']
TypeError: 'NoneType' object is not subscriptable


[02/07 09:41:18] reader WARNING: fail to map sample transform [RandomFlip_5f91aa] with error: 'NoneType' object is not subscriptable and stack:
Traceback (most recent call last):
  File "/home/ma-user/work/PaddleDetection/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/home/ma-user/work/PaddleDetection/ppdet/data/transform/operators.py", line 104, in __call__
    sample = self.apply(sample, context)
  File "/home/ma-user/work/PaddleDetection/ppdet/data/transform/operators.py", line 686, in apply
    im = sample['image']
TypeError: 'NoneType' object is not subscriptable

[02/07 09:41:18] reader WARNING: fail to map sample transform [BboxXYXY2XYWH_e84786] with error: argument of type 'NoneType' is not iterable and stack:
Traceback (most recent call last):
  File "/home/ma-user/work/PaddleDetection/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/home/ma-user/work/PaddleDetection/ppdet/data/transform/operators.py", line 104, in __call__
    sample = self.apply(sample, context)
  File "/home/ma-user/work/PaddleDetection/ppdet/data/transform/operators.py", line 1804, in apply
    assert 'gt_bbox' in sample
TypeError: argument of type 'NoneType' is not iterable

[02/07 09:41:18] reader WARNING: fail to map sample transform [RandomFlip_5f91aa] with error: 'NoneType' object is not subscriptable and stack:
Traceback (most recent call last):
  File "/home/ma-user/work/PaddleDetection/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/home/ma-user/work/PaddleDetection/ppdet/data/transform/operators.py", line 104, in __call__
    sample = self.apply(sample, context)
  File "/home/ma-user/work/PaddleDetection/ppdet/data/transform/operators.py", line 686, in apply
    im = sample['image']
TypeError: 'NoneType' object is not subscriptable

[02/07 09:41:18] reader WARNING: fail to map batch transform [Gt2FairMOTTarget_cd36bc] with error: index 3 is out of bounds for axis 0 with size 1 and stack:
Traceback (most recent call last):
  File "/home/ma-user/work/PaddleDetection/ppdet/data/reader.py", line 73, in __call__
    data = f(data)
  File "/home/ma-user/work/PaddleDetection/ppdet/data/transform/mot_operators.py", line 596, in __call__
    self.draw_truncate_gaussian(heatmap[cls_id], ct_int, radius,
IndexError: index 3 is out of bounds for axis 0 with size 1

[02/07 09:41:19] reader WARNING: fail to map batch transform [Gt2FairMOTTarget_cd36bc] with error: index 2 is out of bounds for axis 0 with size 1 and stack:
Traceback (most recent call last):
  File "/home/ma-user/work/PaddleDetection/ppdet/data/reader.py", line 73, in __call__
    data = f(data)
  File "/home/ma-user/work/PaddleDetection/ppdet/data/transform/mot_operators.py", line 596, in __call__
    self.draw_truncate_gaussian(heatmap[cls_id], ct_int, radius,
IndexError: index 2 is out of bounds for axis 0 with size 1

[02/07 09:41:19] reader WARNING: fail to map batch transform [Gt2FairMOTTarget_cd36bc] with error: index 2 is out of bounds for axis 0 with size 1 and stack:
Traceback (most recent call last):
  File "/home/ma-user/work/PaddleDetection/ppdet/data/reader.py", line 73, in __call__
    data = f(data)
  File "/home/ma-user/work/PaddleDetection/ppdet/data/transform/mot_operators.py", line 596, in __call__
    self.draw_truncate_gaussian(heatmap[cls_id], ct_int, radius,
IndexError: index 2 is out of bounds for axis 0 with size 1

[02/07 09:41:19] reader WARNING: fail to map batch transform [Gt2FairMOTTarget_cd36bc] with error: index 2 is out of bounds for axis 0 with size 1 and stack:
Traceback (most recent call last):
  File "/home/ma-user/work/PaddleDetection/ppdet/data/reader.py", line 73, in __call__
    data = f(data)
  File "/home/ma-user/work/PaddleDetection/ppdet/data/transform/mot_operators.py", line 596, in __call__
    self.draw_truncate_gaussian(heatmap[cls_id], ct_int, radius,
IndexError: index 2 is out of bounds for axis 0 with size 1
```

请问这一般是什么原因？如何修正？

```
paddlepaddle-gpu       2.4.1
paddledet              2.5.0
```

**Comment by nemonameless** [comment]
第一个报错的地方是RandomFlip里的，说明没有读到图片，建议再自查下路径，调试的时候可以单卡训练，reader配置文件里的worker_num设置为0，会打印更详细信息。

**Comment by hu-qi** [comment]
感谢 已解决 确实是数据处理不当
