### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8

### ISSUE THREAD

**Issue by 11140045** [PaddlePaddle/PaddleDetection#7788]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

求救：ubuntu系统运行ppyolo-e模型训练代码时报错，数据集是coco格式的，标注文件是json文件，
报错：
 (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 631: invalid continuation byte

自己查看系统支持编码是
>>> import sys
>>> sys.getdefaultencoding()
'utf-8'
>>> print(chr(0xc8))
È
部分报错代码如下：
Traceback (most recent call last):
  File "/home/huyue/PaddleDetection-release-2.5/tools/train.py", line 172, in <module>
    main()
  File "/home/huyue/PaddleDetection-release-2.5/tools/train.py", line 137, in main
    cfg = load_config(FLAGS.config)
  File "/home/huyue/PaddleDetection-release-2.5/ppdet/core/workspace.py", line 114, in load_config
    cfg = _load_config_with_base(file_path)
  File "/home/huyue/PaddleDetection-release-2.5/ppdet/core/workspace.py", line 92, in _load_config_with_base
    base_cfg = _load_config_with_base(base_yml)
  File "/home/huyue/PaddleDetection-release-2.5/ppdet/core/workspace.py", line 79, in _load_config_with_base
    file_cfg = yaml.load(f, Loader=yaml.Loader)
  File "/home/huyue/anaconda3/envs/Huyue_paddle_env/lib/python3.9/site-packages/yaml/__init__.py", line 79, in load
    loader = Loader(stream)
  File "/home/huyue/anaconda3/envs/Huyue_paddle_env/lib/python3.9/site-packages/yaml/loader.py", line 44, in __init__
    Reader.__init__(self, stream)
  File "/home/huyue/anaconda3/envs/Huyue_paddle_env/lib/python3.9/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/home/huyue/anaconda3/envs/Huyue_paddle_env/lib/python3.9/site-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/home/huyue/anaconda3/envs/Huyue_paddle_env/lib/python3.9/site-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "/home/huyue/anaconda3/envs/Huyue_paddle_env/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 631: invalid continuation byte
LAUNCH INFO 2023-02-19 10:01:07,421 Exit code -15

**Comment by 11140045** [comment]
已解决，因为配置文件中有中文注释

**Comment by 11140045** [comment]
哎paddle框架真的很麻烦啊，issue也没人回答问题

**Comment by thinkthinking** [comment]
> 哎paddle框架真的很麻烦啊，issue也没人回答问题

你好，issue区是有人每天值班的，保证48h之内是有回复的。

**Comment by jerrywgz** [comment]
可以提供下带中文的配置文件吗，我们这边测试了下中文注释是支持的

**Comment by 11140045** [comment]
您好，是配置文件 ppyoloe_reader.yml 中，我之前在 batch_size ：16 后面用中文注释了“ #原来是16”，就发生了报错，后来删去注释之后就没有报错了。
worker_num: 4
eval_height: &eval_height 640
eval_width: &eval_width 640
eval_size: &eval_size [*eval_height, *eval_width]

TrainReader:
  sample_transforms:
    - Decode: {}
    - RandomDistort: {}
    - RandomExpand: {fill_value: [123.675, 116.28, 103.53]}
    - RandomCrop: {}
    - RandomFlip: {}
  batch_transforms:
    - BatchRandomResize: {target_size: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
    - PadGT: {}
  batch_size: 16
  shuffle: true
  drop_last: true
  use_shared_memory: true
  collate_batch: true

EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: *eval_size, keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 2

TestReader:
  inputs_def:
    image_shape: [3, *eval_height, *eval_width]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: *eval_size, keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 1
