### ISSUE TITLE
使用tensorboard出现错误

### ISSUE THREAD

**Issue by JensenHJS** [PaddlePaddle/PaddleDetection#779]
tensorboard  是2.2.0  tb-paddle 是 0.4.0
使用命令tensorboard --helpful出现以下错误，之前是可以用tensorboard的
TensorFlow installation not found - running with reduced feature set.
Traceback (most recent call last):
  File "/home/hjs/anaconda3/bin/tensorboard", line 11, in <module>
    sys.exit(run_main())
  File "/home/hjs/anaconda3/lib/python3.6/site-packages/tensorboard/main.py", line 59, in run_main
    program.get_default_assets_zip_provider())
  File "/home/hjs/anaconda3/lib/python3.6/site-packages/tensorboard/program.py", line 145, in __init__
    self.plugin_loaders = [make_loader(p) for p in plugins]
  File "/home/hjs/anaconda3/lib/python3.6/site-packages/tensorboard/program.py", line 145, in <listcomp>
    self.plugin_loaders = [make_loader(p) for p in plugins]
  File "/home/hjs/anaconda3/lib/python3.6/site-packages/tensorboard/program.py", line 144, in make_loader
    raise ValueError("Not a TBLoader or TBPlugin subclass: %s" % plugin)
ValueError: Not a TBLoader or TBPlugin subclass: <class 'tensorboard_plugin_wit.wit_plugin_loader.WhatIfToolPluginLoader'>

**Comment by jerrywgz** [comment]
看起来像是tensorboard安装错误，可以参考这里的回答https://github.com/tensorflow/tensorboard/issues/3549

**Comment by qingqing01** [comment]
@JensenHJS 请问是否还有问题，现在以更新程VisualDL了，欢迎使用。

**Comment by JensenHJS** [comment]
之前解决了
