### ISSUE TITLE
ppyoloer 训练自己的数据类别只有一类，loss权重比例如何设置？

### ISSUE THREAD

**Issue by zgsxwsdxg** [PaddlePaddle/PaddleDetection#7792]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

ppyoloer 训练自己的数据类别只有一类，loss权重如何设置？
文件
https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/rotate/ppyoloe_r/_base_/ppyoloe_r_crn.yml
中 loss_weight: {class: 1.0, iou: 2.5, dfl: 0.05} 如何设置？class设置多少比例比较合适？有什么经验公式么？谢谢

**Comment by xmzhuxm** [comment]
按默认的就行

**Comment by zgsxwsdxg** [comment]
> 按默认的就行

谢谢您！再咨询的个问题如下：
文件
https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/rotate/ppyoloe_r/_base_/ppyoloe_r_reader.yml 中
`TrainReader:
  sample_transforms:
    - Decode: {}
    - Poly2Array: {}
    - RandomRFlip: {}
    - RandomRRotate: {angle_mode: 'value', angle: [0, 90, 180, -90]}
    - RandomRRotate: {angle_mode: 'value', angle: [30, 60], rotate_prob: 0.5}
    - RResize: {target_size: *image_size, keep_ratio: True, interp: 2}
    - Poly2RBox: {filter_threshold: 2, filter_mode: 'edge', rbox_type: 'oc'}
  batch_transforms:
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
    - PadRGT: {}
    - PadBatch: {pad_to_stride: 32}
  batch_size: 2
  shuffle: true
  drop_last: true
  use_shared_memory: true
  collate_batch: true`
 use_shared_memory 设置为true，训练报错如下：
loading annotations into memory...
Done (t=10.42s)
creating index...
index created!
W0220 17:14:15.887986 98951 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 11.2
W0220 17:14:16.016237 98951 gpu_resources.cc:91] device: 0, cuDNN Version: 8.1.
Process Process-10:
Traceback (most recent call last):
  File "/data/duxiaogang/anaconda3/envs/pdet-dev/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/data/duxiaogang/anaconda3/envs/pdet-dev/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/data/duxiaogang/anaconda3/envs/pdet-dev/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 368, in _worker_loop
    six.reraise(*sys.exc_info())
  File "/data/duxiaogang/anaconda3/envs/pdet-dev/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/data/duxiaogang/anaconda3/envs/pdet-dev/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 358, in _worker_loop
    else tensor_share_memory(b) for b in batch
  File "/data/duxiaogang/anaconda3/envs/pdet-dev/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 358, in <listcomp>
    else tensor_share_memory(b) for b in batch
RuntimeError: (Unavailable) Memory map failed when create shared memory.
  [Hint: Expected ptr != ((void *) -1), but received ptr:0xffffffffffffffff == ((void *) -1):0xffffffffffffffff.] (at /paddle/paddle/fluid/memory/allocation/mmap_allocator.cc:230)

Traceback (most recent call last):
  File "tools/train.py", line 188, in <module>
    main()
  File "tools/train.py", line 184, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 123, in run
    trainer = Trainer(cfg, mode='train')
  File "/data/duxiaogang/PaddleDetection-dev/ppdet/engine/trainer.py", line 109, in __init__
    self.model = create(cfg.architecture)
  File "/data/duxiaogang/PaddleDetection-dev/ppdet/core/workspace.py", line 246, in create
    cls_kwargs.update(cls.from_config(config, **kwargs))
  File "/data/duxiaogang/PaddleDetection-dev/ppdet/modeling/architectures/yolo.py", line 62, in from_config
    backbone = create(cfg['backbone'])
  File "/data/duxiaogang/PaddleDetection-dev/ppdet/core/workspace.py", line 283, in create
    return cls(**cls_kwargs)
  File "/data/duxiaogang/PaddleDetection-dev/ppdet/modeling/backbones/cspresnet.py", line 258, in __init__
    3, channels[0] // 2, 3, stride=2, padding=1, act=act)),
  File "/data/duxiaogang/PaddleDetection-dev/ppdet/modeling/backbones/cspresnet.py", line 51, in __init__
    bias_attr=False)
  File "/data/duxiaogang/anaconda3/envs/pdet-dev/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 657, in __init__
    data_format=data_format)
  File "/data/duxiaogang/anaconda3/envs/pdet-dev/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 136, in __init__
    default_initializer=_get_default_param_initializer())
  File "/data/duxiaogang/anaconda3/envs/pdet-dev/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 424, in create_parameter
    default_initializer)
  File "/data/duxiaogang/anaconda3/envs/pdet-dev/lib/python3.7/site-packages/paddle/fluid/layer_helper_base.py", line 381, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/data/duxiaogang/anaconda3/envs/pdet-dev/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3572, in create_parameter
    initializer(param, self)
  File "/data/duxiaogang/anaconda3/envs/pdet-dev/lib/python3.7/site-packages/paddle/fluid/initializer.py", line 367, in __call__
    'std', self._std_dev, 'seed', self._seed, 'use_mkldnn', False)
  File "/data/duxiaogang/anaconda3/envs/pdet-dev/lib/python3.7/site-packages/paddle/fluid/multiprocess_utils.py", line 134, in __handler__
    core._throw_error_if_process_failed()
SystemError: (Fatal) DataLoader process (pid 98991) exited unexpectedly with code 1. Error detailed are lost due to multiprocessing. Rerunning with:
  1. If run DataLoader by DataLoader.from_generator(...), run with DataLoader.from_generator(..., use_multiprocess=False) may give better error trace.
  2. If run DataLoader by DataLoader(dataset, ...), run with DataLoader(dataset, ..., num_workers=0) may give better error trace (at /paddle/paddle/fluid/imperative/data_loader.cc:156)

期待您的回答！非常感谢！
我把use_shared_memory 设置为false可以训练，就是太慢了，该怎么办？
