### ISSUE TITLE
paddleDetecion2.5 export_model.py error TypeError: function takes exactly 5 arguments (1 given)

### ISSUE THREAD

**Issue by wmtlhb2023** [PaddlePaddle/PaddleDetection#7823]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

执行python tools/export_model.py -c alvaConfigs/mot/bytetrack/detector/yolox_x_24e_800x1440_mix_mot_ch.yml -o weights=https://bj.bcebos.com/v1/paddledet/models/mot/yolox_x_24e_800x1440_mix_mot_ch.pdparams报错如下：
Traceback (most recent call last):
  File "C:\Users\**\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 733, in from_func_spec
    outputs = static_func(*inputs)
  File "C:\Users\**\AppData\Local\Temp\tmpdjj_yzn0.py", line 101, in forward
    false_fn_5, (), (inputs, self), (out,))
  File "C:\Users\**\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 211, in convert_ifelse
    out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
  File "C:\Users\**\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 257, in _run_py_ifelse
    return true_fn(*true_args) if pred else false_fn(*false_args)
  File "C:\Users\**\AppData\Local\Temp\tmpdjj_yzn0.py", line 84, in false_fn_5
    for_loop_body_0, [inputs_list, __for_loop_var_index_0])
  File "C:\Users\**\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 45, in convert_while_loop
    loop_vars = _run_py_while(cond, body, loop_vars)
  File "C:\Users\**\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 59, in _run_py_while
    loop_vars = body(*loop_vars)
  File "C:\Users\**\AppData\Local\Temp\tmpdjj_yzn0.py", line 79, in for_loop_body_0
    dy2static.convert_call(self.get_pred)())
  File "C:\Users\**\AppData\Local\Temp\tmpb89i14fj.py", line 7, in get_pred
    return paddle.jit.dy2static.convert_call(self._forward)()
  File "C:\Users\**\AppData\Local\Temp\tmpnztir5jj.py", line 47, in _forward
    neck_feats, self), (__return_0, __return_value_0, bbox, bbox_num)))
  File "C:\Users\**\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 211, in convert_ifelse
    out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
  File "C:\Users\**\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 257, in _run_py_ifelse
    return true_fn(*true_args) if pred else false_fn(*false_args)
  File "C:\Users\**\AppData\Local\Temp\tmpnztir5jj.py", line 39, in false_fn_7
    head_outs = paddle.jit.dy2static.convert_call(self.head)(neck_feats)
  File "C:\Users\**\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_call_func.py", line 246, in convert_call
    forward_func = convert_to_static(forward_func)
  File "C:\Users\**\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 140, in convert_to_static
    static_func = _FUNCTION_CACHE.convert_with_cache(function)
  File "C:\Users\**\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 77, in convert_with_cache
    static_func = self._convert(func)
  File "C:\Users\**\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 104, in _convert
    source_code = func_to_source_code(func)
  File "C:\Users\**\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\utils.py", line 550, in func_to_source_code
    source_code_list, _ = inspect.getsourcelines(function)
  File "C:\Users\**\anaconda3\envs\paddle\lib\inspect.py", line 955, in getsourcelines
    lines, lnum = findsource(object)
  File "C:\Users\**\anaconda3\envs\paddle\lib\inspect.py", line 782, in findsource
    lines = linecache.getlines(file, module.__dict__)
  File "C:\Users\**\anaconda3\envs\paddle\lib\linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "C:\Users\**\anaconda3\envs\paddle\lib\linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "C:\Users\**\anaconda3\envs\paddle\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 2134: invalid start byte
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\**\anaconda3\envs\paddle\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\**\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 6889, in _dygraph_guard
    yield
  File "C:\Users\**\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "C:\Users\**\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\jit.py", line 857, in save
    inner_input_spec, with_hook=with_hook)
  File "C:\Users\**\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 528, in concrete_program_specify_input_spec
    *desired_input_spec, with_hook=with_hook)
  File "C:\Users\**\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 436, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "C:\Users\**\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 801, in __getitem__
    self._caches[item_id] = self._build_once(item)
  File "C:\Users\**\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 790, in _build_once
    **cache_key.kwargs)
  File "C:\Users\**\anaconda3\envs\paddle\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\Users\**\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "C:\Users\**\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "C:\Users\**\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 740, in from_func_spec
    error_data.raise_new_exception()
  File "C:\Users\**\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\error.py", line 327, in raise_new_exception
    new_exception = self.create_exception()
  File "C:\Users\**\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\error.py", line 161, in create_exception
    new_exception = self.error_type(message)
TypeError: function takes exactly 5 arguments (1 given)

debug打印
C:\Users\**\anaconda3\envs\paddle\Lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\error.py内class ErrorData -> create_exception -> message如下：
In transformed code:

    File "C:\Project\PaddleDetection-release-2.5\ppdet\modeling\architectures\yolox.py", line 109, in get_pred
	return self._forward()
    File "C:\Project\PaddleDetection-release-2.5\ppdet\modeling\architectures\yolox.py", line 100, in _forward
            return yolox_losses
        else:
            head_outs = self.head(neck_feats)
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
            bbox, bbox_num = self.head.post_process(
                head_outs, self.inputs['im_shape'], self.inputs['scale_factor'])

    File "C:\Users\**\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_call_func.py", line 246, in convert_call
	forward_func = convert_to_static(forward_func)
    File "C:\Users\**\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 140, in convert_to_static
	static_func = _FUNCTION_CACHE.convert_with_cache(function)
    File "C:\Users\**\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 77, in convert_with_cache
	static_func = self._convert(func)
    File "C:\Users\**\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 104, in _convert
	source_code = func_to_source_code(func)
    File "C:\Users\**\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\utils.py", line 550, in func_to_source_code
	source_code_list, _ = inspect.getsourcelines(function)
    File "C:\Users\**\anaconda3\envs\paddle\lib\inspect.py", line 955, in getsourcelines
	lines, lnum = findsource(object)
    File "C:\Users\**\anaconda3\envs\paddle\lib\inspect.py", line 782, in findsource
	lines = linecache.getlines(file, module.__dict__)
    File "C:\Users\**\anaconda3\envs\paddle\lib\linecache.py", line 47, in getlines
	return updatecache(filename, module_globals)
    File "C:\Users\**\anaconda3\envs\paddle\lib\linecache.py", line 137, in updatecache
	lines = fp.readlines()
    File "C:\Users\**\anaconda3\envs\paddle\lib\codecs.py", line 322, in decode
	(result, consumed) = self._buffer_decode(data, self.errors, final)

    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 2134: invalid start byte
    
我查了下报错位置如下C:\Project\PaddleDetection-release-2.5\alvaTrain\trainer.py 241：
        if prune_input:
            static_model = paddle.jit.to_static(
                self.model, input_spec=input_spec)
            # NOTE: dy2st do not pruned program, but jit.save will prune program
            # input spec, prune input spec here and save with pruned input spec
            pruned_input_spec = _prune_input_spec(
                input_spec, static_model.forward.main_program,
                static_model.forward.outputs)
以上是Error信息，运行的环境python=3.7 GPU=11.1，请问这个报这个Error的是怎么导致的，该怎么解决呢？

**Comment by nemonameless** [comment]
linux上测试release/2.5没问题。请使用最新release/2.6 或develop分支代码试试。win上请安装paddle develop版本
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html

**Comment by wmtlhb2023** [comment]
> 请使用最新release/2.6 或develop分支代码试试。win上请安装paddle develop版本 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html

2.6转换成功了，谢谢
