### ISSUE TITLE
训练到中途报错 OSError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by dium6i** [PaddlePaddle/PaddleDetection#7831]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

训练环境：
代码库：PaddleDetection-2.4
镜像：PaddlePaddle-2.3.1-GPU

使用相同的配置文件，此前训练未出现过此问题。是数据的问题么？如果是，可能是哪方面的问题呢？

在训练中途报错，完整报错如下：

```[02/25 05:00:27] ppdet.engine INFO: Epoch: [78] [110/578] learning_rate: 0.074239 loss_vfl: 0.706303 loss_bbox: 0.331251 loss_dfl: 0.353399 loss: 1.375721 eta: 1 day, 10:56:23 batch_cost: 0.5464 data_cost: 0.0004 ips: 51.2463 images/s
[02/25 05:00:33] reader WARNING: fail to map sample transform [Decode_17c63a] with error: [Errno 5] Input/output error and stack:
Traceback (most recent call last):
  File "/work/QinW/0_Train/PaddleDetection-2.4.0/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/work/QinW/0_Train/PaddleDetection-2.4.0/ppdet/data/transform/operators.py", line 105, in __call__
    sample = self.apply(sample, context)
  File "/work/QinW/0_Train/PaddleDetection-2.4.0/ppdet/data/transform/operators.py", line 123, in apply
    sample['image'] = f.read()
OSError: [Errno 5] Input/output error

Traceback (most recent call last):
  File "tools/train.py", line 177, in <module>
    main()
  File "tools/train.py", line 173, in main
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/python3.7.0/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3.7.0/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 534, in _thread_loop
    batch = self._get_data()
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 671, in _get_data
    batch.reraise()
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 169, in reraise
    raise self.exc_type(msg)
OSError: DataLoader worker(1) caught OSError with message:
Traceback (most recent call last):
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 336, in _worker_loop
    batch = fetcher.fetch(indices)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 121, in fetch
    data.append(self.dataset[idx])
  File "/work/QinW/0_Train/PaddleDetection-2.4.0/ppdet/data/source/dataset.py", line 87, in __getitem__
    return self.transform(roidb)
  File "/work/QinW/0_Train/PaddleDetection-2.4.0/ppdet/data/reader.py", line 60, in __call__
    raise e
  File "/work/QinW/0_Train/PaddleDetection-2.4.0/ppdet/data/reader.py", line 54, in __call__
    data = f(data)
  File "/work/QinW/0_Train/PaddleDetection-2.4.0/ppdet/data/transform/operators.py", line 105, in __call__
    sample = self.apply(sample, context)
  File "/work/QinW/0_Train/PaddleDetection-2.4.0/ppdet/data/transform/operators.py", line 123, in apply
    sample['image'] = f.read()
OSError: [Errno 5] Input/output error


    run(FLAGS, cfg)
  File "tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/work/QinW/0_Train/PaddleDetection-2.4.0/ppdet/engine/trainer.py", line 425, in train
    for step_id, data in enumerate(self.loader):
  File "/work/QinW/0_Train/PaddleDetection-2.4.0/ppdet/data/reader.py", line 209, in __next__
    return next(self.loader)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 746, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)
```

搜索有类似的提问 https://github.com/PaddlePaddle/PaddleDetection/issues/6332 同时尝试了取消 --eval 后依然如此。

**Comment by ghostxsl** [comment]
看报错信息应该是在读取图像的时候报的错，可以检查一下是不是图像文件有损坏？

**Comment by dium6i** [comment]
> 看报错信息应该是在读取图像的时候报的错，可以检查一下是不是图像文件有损坏？

我检查一下。但是如果是图片有损坏，前77个epoch却跑得很顺利，很奇怪。

**Comment by ghostxsl** [comment]
<img width="901" alt="image" src="https://user-images.githubusercontent.com/23647349/221358983-8aa52538-c8f0-468a-a024-0d33e9299b18.png">
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/ppdet/data/transform/operators.py#L123

**Comment by dium6i** [comment]
> <img alt="image" width="901" src="https://user-images.githubusercontent.com/23647349/221358983-8aa52538-c8f0-468a-a024-0d33e9299b18.png">
> 
> https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/ppdet/data/transform/operators.py#L123

我在这行代码上面做了输出，输出sample['im_file']后去查看图片，文件并没有损坏；并且每次报错的图片还都不一样，应该不是图片损坏……
