### ISSUE TITLE
打电话识别out of index 报错

### ISSUE THREAD

**Issue by hq0709** [PaddlePaddle/PaddleDetection#7833]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在进行行为识别模型中打电话识别的复现过程中报错：
``` shell
Traceback (most recent call last):
  File "deploy/pipeline/pipeline.py", line 1103, in <module>
    main()
  File "deploy/pipeline/pipeline.py", line 1090, in main
    pipeline.run_multithreads()
  File "deploy/pipeline/pipeline.py", line 170, in run_multithreads
    self.predictor.run(self.input)
  File "deploy/pipeline/pipeline.py", line 488, in run
    self.predict_video(input, thread_idx=thread_idx)
  File "deploy/pipeline/pipeline.py", line 773, in predict_video
    det_action_res = self.det_action_predictor.predict(
  File "/workspace/PaddleDetection-release-2.5/deploy/pipeline/pphuman/action_infer.py", line 357, in predict
    det_result = self.detector.predict_image(images, visual=False)
  File "/workspace/PaddleDetection-release-2.5/deploy/python/infer.py", line 392, in predict_image
    result = self.predict()
  File "/workspace/PaddleDetection-release-2.5/deploy/python/infer.py", line 200, in predict
    boxes_num = self.predictor.get_output_handle(output_names[1])
IndexError: list index out of range
```
请问一下报错的原因和解决方法

**Comment by zhiboniu** [comment]
看起来是output_names里保存的变量不对，可能是没有获取到输出名称，请问模型或者代码有变化吗？检查一下名称outpu_names变量
