### ISSUE TITLE
ppyoloe-r无法推理

### ISSUE THREAD

**Issue by LLsmile** [PaddlePaddle/PaddleDetection#7847]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

训练好的ppyoloe-r无法推理，看着像是模型无法解析：
python tools/infer.py -c configs/rotate/ppyoloe_r/ppyoloe_r_crn_m_3x_dota.yml -o output/ppyoloe_r_crn_m_3x_dota/12.pdparams --infer_img=demo/P0861__1.0__1154___824.png --draw_threshold=0.5
Traceback (most recent call last):
  File "/home/liaolin/01_det/PaddleDetection/tools/infer.py", line 236, in <module>
    main()
  File "/home/liaolin/01_det/PaddleDetection/tools/infer.py", line 191, in main
    FLAGS = parse_args()
  File "/home/liaolin/01_det/PaddleDetection/tools/infer.py", line 123, in parse_args
    args = parser.parse_args()
  File "/home/liaolin/01_det/PaddleDetection/ppdet/utils/cli.py", line 58, in parse_args
    args.opt = self._parse_opt(args.opt)
  File "/home/liaolin/01_det/PaddleDetection/ppdet/utils/cli.py", line 67, in _parse_opt
    k, v = s.split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by LLsmile** [comment]
paddle是2.4.1，paddledetection用的release/2.6，刚pull过的最新代码

**Comment by wangxinxin08** [comment]
命令写错了，-o weights=/path/to/weight，自己对照文档的命令看下就能发现问题
