### ISSUE TITLE
visualdl的日志查看

### ISSUE THREAD

**Issue by gyc137** [PaddlePaddle/PaddleDetection#7925]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

用PP-YOLOE+R训练DOTA数据集。
用了visualdl之后会生成log文件，log文件的图片可视化没有问题，但是尝试利用LogReader查看日志数据却报错。

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gyc/anaconda3/envs/yoloer/lib/python3.8/site-packages/visualdl/reader/reader.py", line 86, in __init__
    self.read_log_data(remain=remain)
  File "/home/gyc/anaconda3/envs/yoloer/lib/python3.8/site-packages/visualdl/reader/reader.py", line 336, in read_log_data
    component, dir, tag, record = self.parse_from_bin(item)
  File "/home/gyc/anaconda3/envs/yoloer/lib/python3.8/site-packages/visualdl/reader/reader.py", line 178, in parse_from_bin
    path = bfile.join(self.reader.dir, tag)
  File "/home/gyc/anaconda3/envs/yoloer/lib/python3.8/site-packages/visualdl/io/bfile.py", line 712, in join
    return default_file_factory.get_filesystem(path).join(path, *paths)
  File "/home/gyc/anaconda3/envs/yoloer/lib/python3.8/site-packages/visualdl/io/bfile.py", line 57, in get_filesystem
    if path.startswith(
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by gyc137** [comment]
用的命令如下
>>> from visualdl import LogReader
>>> reader = LogReader(file_path='/home/gyc/PaddleDetection/vdl_log_dir/scalar/100epoch/vdlrecords.1.log')

**Comment by LokeZhou** [comment]
可以试一下最新版本的visualdl,如果还报错，可以在这里提[issues](https://github.com/PaddlePaddle/VisualDL/issues)

**Comment by gyc137** [comment]
之前用的visualdl是2.5.0的，报错了。更新为2.5.1，问题解决。
