### ISSUE TITLE
确认测试通过时出现问题

### ISSUE THREAD

**Issue by Qian1995** [PaddlePaddle/PaddleDetection#793]
输入：python ppdet/modeling/tests/test_architectures.py
运行结果：
ss........EE
======================================================================
ERROR: test_test (__main__.TestYolov3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/project/PaddleDetection/ppdet/modeling/tests/decorator_helper.py", line 29, in __fn__
    fn(*args, **kwargs)
  File "ppdet/modeling/tests/test_architectures.py", line 57, in test_test
    test_fetches = model.eval(feed_vars)
  File "/project/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 159, in eval
    return self.build(feed_vars, mode='test')
  File "/project/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 91, in build
    return self.yolo_head.get_prediction(body_feats, im_size)
  File "/project/PaddleDetection/ppdet/modeling/anchor_heads/yolo_head.py", line 330, in get_prediction
    scale_x_y=scale_x_y)
TypeError: yolo_box() got an unexpected keyword argument 'scale_x_y'

======================================================================
ERROR: test_train (__main__.TestYolov3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/project/PaddleDetection/ppdet/modeling/tests/decorator_helper.py", line 29, in __fn__
    fn(*args, **kwargs)
  File "ppdet/modeling/tests/test_architectures.py", line 49, in test_train
    train_fetches = model.train(feed_vars)
  File "/project/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 156, in train
    return self.build(feed_vars, mode='train')
  File "/project/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 85, in build
    gt_score, targets)
  File "/project/PaddleDetection/ppdet/modeling/anchor_heads/yolo_head.py", line 294, in get_loss
    self.prefix_name)
  File "/project/PaddleDetection/ppdet/modeling/losses/yolo_loss.py", line 88, in __call__
    name=prefix_name + "yolo_loss" + str(i))
TypeError: yolov3_loss() got an unexpected keyword argument 'scale_x_y'

----------------------------------------------------------------------
Ran 12 tests in 4.010s

FAILED (errors=2, skipped=2)

**Comment by willthefrog** [comment]
master分支需要用paddle 2.0 alpha版本以上，`scale_x_y`是最近添加的。

**Comment by Qian1995** [comment]
好的 感谢回复！对于这样的问题是选择注释掉scale_x_y还是提高版本呢？我注释掉scale _x_y之后 就没有在出错了




在2020年05月27日 14:38，Yang Zhang 写道：

master分支需要用paddle 2.0 alpha版本以上，scale_x_y是最近添加的。

**Comment by willthefrog** [comment]
或者可以使用 release/0.3 分支
