### ISSUE TITLE
solov2训练自定义数据集eval的AP结果很差

### ISSUE THREAD

**Issue by blurmemo** [PaddlePaddle/PaddleDetection#7939]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

电脑环境
单gpu 2080

数据集相关环境
我的数据集只有一个类别，原始数据集是1022张图片，经过镜像、旋转、高斯模糊增强到8176张，按照8:2划分训练集和验证集

solov2配置文件相关修改

## solov2_r50_enhance_coco.yml的修改
拷贝../datasets/coco_instance.yml到solov2_r50_enhance_coco.yml里面修改
![image](https://user-images.githubusercontent.com/92586621/224898118-e87414d2-b982-4f6c-b2de-38475f67978f.png)
num_classes修改为1
TrainDataset里面的image_dir、anno_path、dataset_dir修改为我自己数据集的路径
EvalDataset里面的image_dir、anno_path、dataset_dir修改为我自己数据集的路径
TestDataset里面的anno_path、dataset_dir修改为我自己数据集的路径

![image](https://user-images.githubusercontent.com/92586621/224898939-399449a6-830e-456c-a35e-4312777cea89.png)
只修改了epoch为10其余是官方原始配置

![image](https://user-images.githubusercontent.com/92586621/224899397-1d8c9a11-b55c-4988-b043-ea6d708cd219.png)
base_lr按照我都gpu个数和batch size修改为0.00125

  '../runtime.yml'
  '_base_/solov2_r50_fpn.yml'
  '_base_/optimizer_1x.yml'
  '_base_/solov2_light_reader.yml'
这些文件里面的东西均没有修改

上面是我的具体配置，训练时候eval测得的AP结果很差，基本上在1%，请问是什么原因造成的吗

**Comment by nemonameless** [comment]
总bs最好保持16不变。训练自定义数据集，最好加载coco权重做预训练去finetune，且lr改小为原先1/10

**Comment by blurmemo** [comment]
> 总bs最好保持16不变。训练自定义数据集，最好加载coco权重做预训练去finetune，且lr改小为原先1/10

我发问题是grid设置不合理，但是我修改num_grid时候提示我报错？

Traceback (most recent call last):
  File "tools/train.py", line 202, in <module>
    main()
  File "tools/train.py", line 198, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 151, in run
    trainer.train(FLAGS.eval)
  File "F:\workspaces\EN\obstacle-avoidance-research\PaddleDetection\ppdet\engine\trainer.py", line 539, in train
    outputs = model(data)
  File "E:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "F:\workspaces\EN\obstacle-avoidance-research\PaddleDetection\ppdet\modeling\architectures\meta_arch.py", line 60, in forward
    out = self.get_loss()
  File "F:\workspaces\EN\obstacle-avoidance-research\PaddleDetection\ppdet\modeling\architectures\solov2.py", line 94, in get_loss
    gt_ins_labels, gt_cate_labels, gt_grid_orders, fg_num)
  File "F:\workspaces\EN\obstacle-avoidance-research\PaddleDetection\ppdet\modeling\heads\solov2_head.py", line 405, in get_loss
    ins_pred_list, ins_labels, flatten_cate_preds, cate_labels, num_ins)
  File "F:\workspaces\EN\obstacle-avoidance-research\PaddleDetection\ppdet\modeling\losses\solov2_loss.py", line 99, in __call__
    alpha=self.focal_loss_alpha)
  File "E:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\nn\functional\loss.py", line 3086, in sigmoid_focal_loss
    logit, label, False, -100
ValueError: (InvalidArgument) Input(X) and Input(Label) shall have the same shape except the last dimension. But received: the shape of Input(X) is [30976, 1], the shape of Input(Label) is [7744, 1].
  [Hint: Expected phi::slice_ddim(x_dims, 0, rank) == phi::slice_ddim(labels_dims, 0, rank), but received phi::slice_ddim(x_dims, 0, rank):30976, 1 != phi::slice_ddim(labels_dims, 0, rank):7744, 1.] (at ..\paddle\phi\infermeta\binary.cc:2419)

**Comment by blurmemo** [comment]
> 总bs最好保持16不变。训练自定义数据集，最好加载coco权重做预训练去finetune，且lr改小为原先1/10

https://github.com/PaddlePaddle/PaddleDetection/issues/7939#issuecomment-1467833334

这个是我修改的
