### ISSUE TITLE
ppyoloe使用python推理时带tensorrt会报错(InvalidArgument) Pass preln_embedding_eltwise_layernorm_fuse_pass has not been registered.

### ISSUE THREAD

**Issue by zmmhz** [PaddlePaddle/PaddleDetection#7961]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Inference, Export

### Bug描述 Describe the Bug

1、推理ppyoloe，python推理，带tensorrt，推理时会报错
Traceback (most recent call last):
  File "deploy/python/infer.py", line 1084, in <module>
    main()
  File "deploy/python/infer.py", line 1031, in main
    output_dir=FLAGS.output_dir)
  File "deploy/python/infer.py", line 122, in __init__
    delete_shuffle_pass=delete_shuffle_pass)
  File "deploy/python/infer.py", line 932, in load_predictor
    predictor = create_predictor(config)
ValueError: (InvalidArgument) Pass preln_embedding_eltwise_layernorm_fuse_pass has not been registered.
  [Hint: Expected Has(pass_type) == true, but received Has(pass_type):0 != true:1.] (at /paddle/paddle/fluid/framework/ir/pass.h:242)

排错思路：
1、推理不带tensorrt时可正常输出结果
2、tensorrt路劲也正确加载了

### 复现环境 Environment

Ubuntu18.04
cuda11.1
cudnn8.1
tensorrt7.2.3.4
paddlepaddle_gpu-2.3.2.post111-cp37-cp37m-linux_x86_64

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
你用的是带transformer结构的neck吧  使用paddle2.4.2再试一下

**Comment by zmmhz** [comment]
> 你用的是带transformer结构的neck吧 使用paddle2.4.2再试一下

没有用到transformer，这个结构就是普通卷积
