### ISSUE TITLE
YOLOv8 training not supported yet.

### ISSUE THREAD

**Issue by maybe2122** [PaddlePaddle/PaddleDetection#7963]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
Traceback (most recent call last):
  File "tools/train.py", line 188, in <module>
    main()
  File "tools/train.py", line 184, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 128, in run
    trainer = Trainer(cfg, mode='train')
  File "/home/sz/models/PaddleYOLO-release-2.6/ppdet/engine/trainer.py", line 74, in __init__
    raise NotImplementedError('{} training not supported yet.'.format(
NotImplementedError: YOLOv8 training not supported yet.

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleYOLO/issues/103  

谢谢关注。由于工作安排问题，我们是将YOLOv8的训练实现放到了 [飞桨黑客松论文复现赛](https://github.com/PaddlePaddle/Paddle/issues/51281#detection) 里，具体比赛可看[PaddlePaddle Hackathon 飞桨黑客马拉松第四期](https://aistudio.baidu.com/aistudio/competition/detail/776/0/introduction)。我们也会及时评估选手的进度，必要时辅助选手或自行实现，由于比赛原因预计4月底才可以公布实现。

就当前性能来看，PPYOLOE+ 模型只训80epoch的情况下还是可以略胜YOLOv8的500epoch，你可以训更多epoch试试。

此外PPYOLOE+的小目标、旋转框、密集检测、半监督检测、检测蒸馏、tiny版本、obj365预训练、transformer等超大型backbone、各种人车工业垂类应用都很齐全，欢迎使用。
https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/ppyoloe 
https://github.com/PaddlePaddle/PaddleDetection/releases/tag/v2.6.0
