### ISSUE TITLE
预测test数据集报错

### ISSUE THREAD

**Issue by gyc137** [PaddlePaddle/PaddleDetection#7965]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

- python tools/infer.py -c configs/rotate/ppyoloe_r/ppyoloe_r_crn_l_3x_dota.yml -o weights=/home/gyc/PaddleDetection/PP-YOLOE-R_result/原始PP-YOLOE-R/每epoch模型/best_model.pdparams --infer_dir=/home/gyc/PaddleDetection/outputdata/test1024/images --output_dir=output_ppyoloe_r --visualize=False --save_results=True
- 
W0319 15:02:20.555184 11913 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 12.0, Runtime API Version: 10.2
W0319 15:02:20.556067 11913 gpu_resources.cc:91] device: 0, cuDNN Version: 8.7.
[03/19 15:02:22] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/gyc/PaddleDetection/PP-YOLOE-R_result/原始PP-YOLOE-R/每epoch模型/best_model.pdparams
[03/19 15:02:22] train INFO: Found 10833 inference images in total.
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
 23%|████████▌                             | 2450/10833 [04:54<16:09,  8.65it/s]libpng error: bad adaptive filter value
[03/19 15:07:16] reader WARNING: fail to map sample transform [Decode_91ba48] with error: 'bytes' object has no attribute 'shape' and stack:
Traceback (most recent call last):
  File "/home/gyc/PaddleDetection/ppdet/data/reader.py", line 59, in __call__
    data = f(data)
  File "/home/gyc/PaddleDetection/ppdet/data/transform/operators.py", line 105, in __call__
    sample = self.apply(sample, context)
  File "/home/gyc/PaddleDetection/ppdet/data/transform/operators.py", line 138, in apply
    sample['h'] = im.shape[0]
AttributeError: 'bytes' object has no attribute 'shape'

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/gyc/anaconda3/envs/yoloer/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/gyc/anaconda3/envs/yoloer/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gyc/anaconda3/envs/yoloer/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 217, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices,
  File "/home/gyc/anaconda3/envs/yoloer/lib/python3.8/site-packages/paddle/fluid/dataloader/fetcher.py", line 121, in fetch
    data.append(self.dataset[idx])
  File "/home/gyc/PaddleDetection/ppdet/data/source/dataset.py", line 102, in __getitem__
    return self.transform(roidb)
  File "/home/gyc/PaddleDetection/ppdet/data/reader.py", line 65, in __call__
    raise e
  File "/home/gyc/PaddleDetection/ppdet/data/reader.py", line 59, in __call__
    data = f(data)
  File "/home/gyc/PaddleDetection/ppdet/data/transform/operators.py", line 105, in __call__
    sample = self.apply(sample, context)
  File "/home/gyc/PaddleDetection/ppdet/data/transform/operators.py", line 138, in apply
    sample['h'] = im.shape[0]
AttributeError: 'bytes' object has no attribute 'shape'
 23%|████████▌                             | 2455/10833 [04:54<15:30,  9.00it/s]

- 以上是内容和报错信息，背景为用PP-YOLOE-R对DOTA的test数据集进行预测，但是预测一段时间后会停止，报以上错误。
- paddle版本为2.3.2-gpu

**Comment by nemonameless** [comment]
读到的那张图片可能损坏或有问题，infer都是顺序的，可以找出那张图看看或用opencv读下，有问题就先排除掉。

**Comment by gyc137** [comment]
如果infer是按顺序的话那就奇怪了，因为infer中断的位置并不一致，有时15%就报错了，有时98%才报错。
这个问题在训练环节也出现了，报了同样的错误，但问题是之前是完整跑过一次训练的，并没有报错。
会不会是其中的某个步骤会对图片进行处理，导致图片损坏？
现在采用了try except暂时规避了这个问题。

**Comment by Sweewangyu** [comment]
> 
请问你是怎么用try except暂时规避了这个问题的，望告知

**Comment by linchen111** [comment]
> 如果infer是按顺序的话那就奇怪了，因为infer中断的位置并不一致，有时15%就报错了，有时98%才报错。 这个问题在训练环节也出现了，报了同样的错误，但问题是之前是完整跑过一次训练的，并没有报错。 会不会是其中的某个步骤会对图片进行处理，导致图片损坏？ 现在采用了try except暂时规避了这个问题。

同问如何处理的
