### ISSUE TITLE
batch_size =1是可以成功运行，batch_size>1报错

### ISSUE THREAD

**Issue by samaritan1998** [PaddlePaddle/PaddleDetection#7978]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

模型是yolov3 
loader.set_sample_list_generator(train_reader)    paddle1.8版本 设置batch_size=1的时候是可以的，batch_size>1会报异常，train_reader返回的数据中一个batch里的图片尺寸是一样的，不同batch图片尺寸不一样，报错信息
/root/anaconda3/envs/paddle_env3/lib/python3.7/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tools/train.py", line 402, in <module>
    main()
  File "tools/train.py", line 273, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "/root/anaconda3/envs/paddle_env3/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/root/anaconda3/envs/paddle_env3/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/root/anaconda3/envs/paddle_env3/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/root/anaconda3/envs/paddle_env3/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1167, in _run_impl
    return_merged=return_merged)
  File "/root/anaconda3/envs/paddle_env3/lib/python3.7/site-packages/paddle/fluid/executor.py", line 879, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/root/anaconda3/envs/paddle_env3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/root/anaconda3/envs/paddle_env3/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1080, in _init_non_iterable
    attrs={'drop_last': self._drop_last})
  File "/root/anaconda3/envs/paddle_env3/lib/python3.7/site-packages/paddle/fluid/reader.py", line 978, in __init__
    self._init_non_iterable()
  File "/root/anaconda3/envs/paddle_env3/lib/python3.7/site-packages/paddle/fluid/reader.py", line 620, in from_generator
    iterable, return_list, drop_last)
  File "/home/code/text_yolo_pres/text-yolo/ppdet/modeling/architectures/yolo.py", line 295, in build_inputs
    iterable=iterable) if use_dataloader else None
  File "tools/train.py", line 135, in main
    feed_vars, train_loader = model.build_inputs(**inputs_def)
  File "tools/train.py", line 402, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]

**Comment by samaritan1998** [comment]
补充一下
xception in thread Thread-2:
Traceback (most recent call last):
  File "/root/anaconda3/envs/paddle_env3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/envs/paddle_env3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda3/envs/paddle_env3/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1145, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/root/anaconda3/envs/paddle_env3/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/root/anaconda3/envs/paddle_env3/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1125, in __thread_main__
    for tensors in self._tensor_reader():
  File "/root/anaconda3/envs/paddle_env3/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1195, in __tensor_reader_impl__
    for slots in paddle_reader():
  File "/root/anaconda3/envs/paddle_env3/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 507, in __reader_creator__
    yield self.feed(item)
  File "/root/anaconda3/envs/paddle_env3/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 348, in feed
    ret_dict[each_name] = each_converter.done()
  File "/root/anaconda3/envs/paddle_env3/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 157, in done
    arr = np.array(self.data, dtype=self.dtype)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 9) + inhomogeneous part.

**Comment by wangxinxin08** [comment]
建议使用PaddleDetetcion最新的2.6版本，静态图的方式目前已经不再提供支持
