### ISSUE TITLE
工具：tools/box_distribution.py使用报错

### ISSUE THREAD

**Issue by lrp123456** [PaddlePaddle/PaddleDetection#7979]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Traceback (most recent call last):
  File "PaddleDetection/tools/box_distribution.py", line 147, in <module>
    main()
  File "PaddleDetection/tools/box_distribution.py", line 143, in main
    get_ratio_infos(args.json_path, args.out_img, args.eval_size, args.small_stride)
  File "PaddleDetection/tools/box_distribution.py", line 125, in get_ratio_infos
    draw_distribution(ratio_w, ratio_h, out_img)
  File "PaddleDetection/tools/box_distribution.py", line 41, in draw_distribution
    plt.hist(width, bins=w_bins, color='green')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/pyplot.py", line 3137, in hist
    stacked=stacked, normed=normed, data=data, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/__init__.py", line 1867, in inner
    return func(ax, *args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 6639, in hist
    m, bins = np.histogram(x[i], bins, weights=w[i], **hist_kwargs)
  File "<__array_function__ internals>", line 6, in histogram
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numpy/lib/histograms.py", line 792, in histogram
    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numpy/lib/histograms.py", line 424, in _get_bin_edges
    raise ValueError('`bins` must be positive, when an integer')
ValueError: `bins` must be positive, when an integer

核查后发现plt.hist(width, bins=w_bins, color='green')中w_bins为0

print(max(width)):7.378270270270269
print(min(width)):4.386499999999999
print((max(width)-min(width))//10):0.0

**Comment by nemonameless** [comment]
请大致描述下你的数据集的情况，比如图片尺寸都大致多少，目标都很大还是很小之类的

**Comment by lrp123456** [comment]
图片：2034*1296
目标都很小
