### ISSUE TITLE
pptsm打架识别复现，抽帧报错

### ISSUE THREAD

**Issue by blueWall8** [PaddlePaddle/PaddleDetection#7987]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

参考这个文档进行打架识别的复现：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/docs/advanced_tutorials/customization/action_recognotion/videobased_rec.md

在执行以下抽帧命令是出现报错：
python data/ucf101/extract_rawframes.py dataset/ rawframes/ --level 2 --ext mp4

报错内容：
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
File "D:\Anaconda3\envs\PPVideo_1\lib\multiprocessing\pool.py", line 121, in worker
result = (True, func(*args, **kwds))
File "D:\Anaconda3\envs\PPVideo_1\lib\multiprocessing\pool.py", line 44, in mapstar
return list(map(*args))
File "D:\code_tools\python_all\py_projects_path\PaddleVideo-develop\data\ucf101\extract_rawframes.py", line 14, in dump_frames
out_full_path = osp.join(args.out_dir, vid_name)
NameError: name 'args' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "data/ucf101/extract_rawframes.py", line 99, in
pool.map(dump_frames, zip(fullpath_list, vid_list, range(len(vid_list))))
File "D:\Anaconda3\envs\PPVideo_1\lib\multiprocessing\pool.py", line 268, in map
return self._map_async(func, iterable, mapstar, chunksize).get()
File "D:\Anaconda3\envs\PPVideo_1\lib\multiprocessing\pool.py", line 657, in get
raise self._value
NameError: name 'args' is not defined

**Comment by blueWall8** [comment]
@zhiboniu 请问我的问题该怎么解决呢？谢谢

**Comment by zhiboniu** [comment]
把args.out_dir换成自己保存路径的字符串吧

**Comment by blueWall8** [comment]
> 把args.out_dir换成自己保存路径的字符串吧

谢谢，我把文件路径换成绝对路径就行了
