### ISSUE TITLE
使用PicoDet网络训练WiderFace数据集，train与infer均正常，但是eval报错维度问题，不知道是哪里出了问题

### ISSUE THREAD

**Issue by Jiuyueyyy** [PaddlePaddle/PaddleDetection#7989]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

boss@boss-209:~/UAV/paddle/PaddleDetection$ python -u tools/eval.py -c /home/boss/UAV/paddle/PaddleDetection/configs/picodet/legacy_model/application/pedestrian_detection/picodet_s_640_pedestrian_face.yml -o weights=/home/boss/UAV/paddle/PaddleDetection/output/picodet_s_640_pedestrian_face/model_final multi_scale=True 
W0323 23:20:39.404310 42082 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.1
W0323 23:20:39.407267 42082 gpu_resources.cc:91] device: 0, cuDNN Version: 8.0.
params:  Tensor(shape=[1], dtype=int64, place=Place(gpu:0), stop_gradient=True,
       [962455])
[03/23 23:20:41] ppdet.data.source.category WARNING: anno_file 'None' is None or not set or not exist, please recheck TrainDataset/EvalDataset/TestDataset.anno_path, otherwise the default categories will be used by metric_type.
[03/23 23:20:41] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/boss/UAV/paddle/PaddleDetection/output/picodet_s_640_pedestrian_face/model_final.pdparams
[03/23 23:20:41] ppdet.metrics.widerface_utils INFO: The ground truth file load 3226 images
W0323 23:20:41.993058 42082 gpu_resources.cc:217] WARNING: device: . The installed Paddle is compiled with CUDNN 8.2, but CUDNN version in your machine is 8.0, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
Traceback (most recent call last):
  File "tools/eval.py", line 203, in <module>
    main()
  File "tools/eval.py", line 199, in main
    run(FLAGS, cfg)
  File "tools/eval.py", line 154, in run
    trainer.evaluate()
  File "/home/boss/UAV/paddle/PaddleDetection/ppdet/engine/trainer.py", line 674, in evaluate
    self._eval_with_loader(self.loader)
  File "/home/boss/UAV/paddle/PaddleDetection/ppdet/engine/trainer.py", line 618, in _eval_with_loader
    self._compose_callback.on_epoch_begin(self.status)
  File "/home/boss/UAV/paddle/PaddleDetection/ppdet/engine/callbacks.py", line 82, in on_epoch_begin
    c.on_epoch_begin(status)
  File "/home/boss/UAV/paddle/PaddleDetection/ppdet/engine/callbacks.py", line 251, in on_epoch_begin
    metric.update(self.model.model)
  File "/home/boss/UAV/paddle/PaddleDetection/ppdet/metrics/metrics.py", line 341, in update
    face_eval_run(
  File "/home/boss/UAV/paddle/PaddleDetection/ppdet/metrics/widerface_utils.py", line 61, in face_eval_run
    det0 = detect_face(model, image, shrink)
  File "/home/boss/UAV/paddle/PaddleDetection/ppdet/metrics/widerface_utils.py", line 99, in detect_face
    detection = model(data)
  File "/home/boss/anaconda3/envs/paddleUAV/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/boss/UAV/paddle/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 76, in forward
    outs.append(self.get_pred())
  File "/home/boss/UAV/paddle/PaddleDetection/ppdet/modeling/architectures/picodet.py", line 89, in get_pred
    bbox_pred, bbox_num = self._forward()
  File "/home/boss/UAV/paddle/PaddleDetection/ppdet/modeling/architectures/picodet.py", line 65, in _forward
    fpn_feats = self.neck(body_feats)
  File "/home/boss/anaconda3/envs/paddleUAV/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/boss/UAV/paddle/PaddleDetection/ppdet/modeling/necks/csp_pan.py", line 332, in forward
    paddle.concat([upsample_feat, feat_low], 1))
  File "/home/boss/anaconda3/envs/paddleUAV/lib/python3.8/site-packages/paddle/tensor/manipulation.py", line 1140, in concat
    return _C_ops.concat(input, axis)
ValueError: (InvalidArgument) The 2-th dimension of input[0] and input[1] is expected to be equal.But received input[0]'s shape = [1, 96, 44, 64], input[1]'s shape = [1, 96, 43, 64].
  [Hint: Expected inputs_dims[0][j] == inputs_dims[i][j], but received inputs_dims[0][j]:44 != inputs_dims[i][j]:43.] (at /paddle/paddle/phi/kernels/funcs/concat_funcs.h:83)

**Comment by lyuwenyu** [comment]
数据预处理一样嘛  输入搞成32的倍数试一下

**Comment by Jiuyueyyy** [comment]
一样的，320的模型BatchRandomResize的target_size只留一组320还是报一样的错，也是44和43
BatchRandomResize: {target_size: [320], random_size: True, random_interp: True, keep_ratio: False}

**Comment by Jiuyueyyy** [comment]
> 数据预测处理一样嘛 输入搞成32的倍数试一下

一样的，320的模型BatchRandomResize的target_size只留一组320还是报一样的错误，也是44和43
BatchRandomResize: {target_size: [320], random_size: True, random_interp: True, keep_ratio: False}
![image](https://user-images.githubusercontent.com/112086553/227420958-54cf03b1-4905-46a6-9eb6-63e2ab1d5c1a.png)
![image](https://user-images.githubusercontent.com/112086553/227421083-ba765320-d4e3-42d9-a0b0-249faa2b8637.png)
