### ISSUE TITLE
ValueError: The module PPYOLOE is not registered

### ISSUE THREAD

**Issue by iDra9on** [PaddlePaddle/PaddleDetection#8019]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

请问这是什么原因，配置文件里面明明有PPYOLOE的定义的：
Traceback (most recent call last):
  File "tools/train.py", line 172, in <module>
    main()
  File "tools/train.py", line 159, in main
    cfg = build_slim_model(cfg, FLAGS.slim_config)
  File "/home/aistudio/work/PaddleDetection/ppdet/slim/__init__.py", line 41, in build_slim_model
    model = DistillModel(cfg, slim_cfg)
  File "/home/aistudio/work/PaddleDetection/ppdet/slim/distill.py", line 36, in __init__
    self.student_model = create(cfg.architecture)
  File "/home/aistudio/work/PaddleDetection/ppdet/core/workspace.py", line 220, in create
    raise ValueError("The module {} is not registered".format(name))
ValueError: The module PPYOLOE is not registered

**Comment by nemonameless** [comment]
PPYOLOE的蒸馏见 https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/ppyoloe/distill ，已是精度最高的方法了。
报bug请按模板提问，并说明代码改动和运行命令，以便排查谢谢，https://github.com/PaddlePaddle/PaddleDetection/issues/new?assignees=&labels=bug&template=1_bug-report.yml
