### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'items'

### ISSUE THREAD

**Issue by samiechan** [PaddlePaddle/PaddleDetection#8022]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Deploy

### Bug描述 Describe the Bug

Command: `python deploy/pipeline/pipeline.py --config deploy/pipeline/config/examples/infer_cfg_human_attr.yml -o visual=False --rtsp rtsp://localhost:8554/mystream  --device=gpu`
Error: `Traceback (most recent call last):
  File "deploy/pipeline/pipeline.py", line 1321, in <module>
    main()
  File "deploy/pipeline/pipeline.py", line 1303, in main
    cfg = merge_cfg(FLAGS)  # use command params to update config
  File "/mnt/c/Users/xrock/projects/PaddleDetection/deploy/pipeline/cfg_utils.py", line 212, in merge_cfg
    pred_config = merge_opt(pred_config, args_dict)
  File "/mnt/c/Users/xrock/projects/PaddleDetection/deploy/pipeline/cfg_utils.py", line 202, in merge_opt
    for sub_k, sub_v in value.items():
AttributeError: 'bool' object has no attribute 'items'`

### 复现环境 Environment

OS: Windows
PaddlePaddle: 2.2.2
PaddleDetection: release/2.6
Python: 3.8.0
CUDA: 10.1
CUDNN: 7.6.5
GCC: 9.4.0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by 827346462** [comment]
i have same error. os ubuntu20.04 env:paddlepaddle-gpu    2.4.2.post117

**Comment by todesti2** [comment]
我也有类似的错误：AttributeError: 'ImageDraw' object has no attribute 'textsize'

**Comment by elbadaernU404** [comment]
相同的错误
```shell
(py39_vio) [root@jdz PaddleDetection]# python deploy/pipeline/pipeline.py --config deploy/pipeline/config/examples/infer_cfg_human_attr.yml -o visual=False --rtsp rtsp://192.168.9.165:554/34020000002000000207_34020000001320000131 --device=cpu
/root/anaconda3/envs/py39_vio/lib/python3.9/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
/root/anaconda3/envs/py39_vio/lib/python3.9/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/root/anaconda3/envs/py39_vio/lib/python3.9/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
Traceback (most recent call last):
  File "/exp/work/video/PaddleDetection/deploy/pipeline/pipeline.py", line 1321, in <module>
    main()
  File "/exp/work/video/PaddleDetection/deploy/pipeline/pipeline.py", line 1303, in main
    cfg = merge_cfg(FLAGS)  # use command params to update config
  File "/exp/work/video/PaddleDetection/deploy/pipeline/cfg_utils.py", line 212, in merge_cfg
    pred_config = merge_opt(pred_config, args_dict)
  File "/exp/work/video/PaddleDetection/deploy/pipeline/cfg_utils.py", line 202, in merge_opt
    for sub_k, sub_v in value.items():
AttributeError: 'bool' object has no attribute 'items'
```

**Comment by elbadaernU404** [comment]
> 相同的错误
> 
> ```shell
> (py39_vio) [root@jdz PaddleDetection]# python deploy/pipeline/pipeline.py --config deploy/pipeline/config/examples/infer_cfg_human_attr.yml -o visual=False --rtsp rtsp://192.168.9.165:554/34020000002000000207_34020000001320000131 --device=cpu
> /root/anaconda3/envs/py39_vio/lib/python3.9/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
>   warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
> /root/anaconda3/envs/py39_vio/lib/python3.9/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
> Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
>   declare_namespace(pkg)
> /root/anaconda3/envs/py39_vio/lib/python3.9/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
> Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
>   declare_namespace(pkg)
> Traceback (most recent call last):
>   File "/exp/work/video/PaddleDetection/deploy/pipeline/pipeline.py", line 1321, in <module>
>     main()
>   File "/exp/work/video/PaddleDetection/deploy/pipeline/pipeline.py", line 1303, in main
>     cfg = merge_cfg(FLAGS)  # use command params to update config
>   File "/exp/work/video/PaddleDetection/deploy/pipeline/cfg_utils.py", line 212, in merge_cfg
>     pred_config = merge_opt(pred_config, args_dict)
>   File "/exp/work/video/PaddleDetection/deploy/pipeline/cfg_utils.py", line 202, in merge_opt
>     for sub_k, sub_v in value.items():
> AttributeError: 'bool' object has no attribute 'items'
> ```

去除参数 -o visual=False就正常了

**Comment by WangShengFeng1** [comment]
相同的错误加一
