### ISSUE TITLE
蒸馏报错

### ISSUE THREAD

**Issue by Feng1909** [PaddlePaddle/PaddleDetection#8036]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

根据 [PPYOLOE+蒸馏文档](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.6/configs/slim/distill#ppyoloe%E6%A8%A1%E5%9E%8B%E8%92%B8%E9%A6%8F) ，使用命令进行蒸馏训练
```
python tools/train.py -c configs/ppyoloe/distill/ppyoloe_plus_crn_l_80e_coco_distill.yml --slim_config configs/slim/distill/ppyoloe_plus_distill_x_distill_l.yml
```
报错：
```
python tools/train.py -c configs/ppyoloe/distill/ppyoloe_plus_crn_l_80e_coco_distill.yml --slim_config configs/slim/distill/ppyoloe_plus_distill_x_distill_l.yml
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
W0404 12:36:21.461179 234441 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.1
W0404 12:36:21.464303 234441 gpu_resources.cc:91] device: 0, cuDNN Version: 8.0.
[04/04 12:36:23] ppdet.utils.checkpoint INFO: Finish loading model weights: /mnt/cfs/algorithm/yunji.feng/go_1_dog/models/ppyoloe_plus_crn_l_30e_voc_001/best_model.pdparams
[04/04 12:36:23] ppdet.slim.distill_model INFO: Student model has loaded pretrain weights!
[04/04 12:36:24] ppdet.utils.checkpoint INFO: The shape [80] in pretrained weight yolo_head.pred_cls.0.bias is unmatched with the shape [5] in model yolo_head.pred_cls.0.bias. And the weight yolo_head.pred_cls.0.bias will not be loaded
[04/04 12:36:24] ppdet.utils.checkpoint INFO: The shape [80, 960, 3, 3] in pretrained weight yolo_head.pred_cls.0.weight is unmatched with the shape [5, 960, 3, 3] in model yolo_head.pred_cls.0.weight. And the weight yolo_head.pred_cls.0.weight will not be loaded
[04/04 12:36:24] ppdet.utils.checkpoint INFO: The shape [80] in pretrained weight yolo_head.pred_cls.1.bias is unmatched with the shape [5] in model yolo_head.pred_cls.1.bias. And the weight yolo_head.pred_cls.1.bias will not be loaded
[04/04 12:36:24] ppdet.utils.checkpoint INFO: The shape [80, 480, 3, 3] in pretrained weight yolo_head.pred_cls.1.weight is unmatched with the shape [5, 480, 3, 3] in model yolo_head.pred_cls.1.weight. And the weight yolo_head.pred_cls.1.weight will not be loaded
[04/04 12:36:24] ppdet.utils.checkpoint INFO: The shape [80] in pretrained weight yolo_head.pred_cls.2.bias is unmatched with the shape [5] in model yolo_head.pred_cls.2.bias. And the weight yolo_head.pred_cls.2.bias will not be loaded
[04/04 12:36:24] ppdet.utils.checkpoint INFO: The shape [80, 240, 3, 3] in pretrained weight yolo_head.pred_cls.2.weight is unmatched with the shape [5, 240, 3, 3] in model yolo_head.pred_cls.2.weight. And the weight yolo_head.pred_cls.2.weight will not be loaded
[04/04 12:36:25] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/yunji.feng/.cache/paddle/weights/ppyoloe_plus_crn_x_80e_coco.pdparams
[04/04 12:36:25] ppdet.slim.distill_model INFO: Teacher model has loaded pretrain weights!
loading annotations into memory...
Done (t=0.22s)
creating index...
index created!
[04/04 12:36:26] ppdet.data.source.coco INFO: Load [12749 samples valid, 1 samples invalid] in file /mnt/cfs/algorithm/yunji.feng/go_1_dog/robot_dog_dataset_copy/data_coco/VOC/Annotations/train.json.
W0404 12:36:27.857709 234441 gpu_resources.cc:201] WARNING: device: . The installed Paddle is compiled with CUDNN 8.1, but CUDNN version in your machine is 8.0, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
[04/04 12:36:31] ppdet.engine INFO: Epoch: [0] [   0/1593] learning_rate: 0.000000 loss: 6.050016 loss_cls: 6.551647 loss_iou: 0.614634 loss_dfl: 2.255900 loss_l1: 2.518432 det_loss: 9.216183 logits_loss: 38.780678 feat_loss: 0.403270 eta: 5 days, 12:24:17 batch_cost: 3.7402 data_cost: 0.0022 ips: 2.1389 images/s
Traceback (most recent call last):
  File "tools/train.py", line 202, in <module>
    main()
  File "tools/train.py", line 198, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 151, in run
    trainer.train(FLAGS.eval)
  File "/mnt/cfs/algorithm/yunji.feng/go_1_dog/PaddleDetection/ppdet/engine/trainer.py", line 539, in train
    outputs = model(data)
  File "/mnt/cfs/algorithm/yunji.feng/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/mnt/cfs/algorithm/yunji.feng/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/mnt/cfs/algorithm/yunji.feng/go_1_dog/PaddleDetection/ppdet/slim/distill_model.py", line 344, in forward
    self.student_model)
  File "/mnt/cfs/algorithm/yunji.feng/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/mnt/cfs/algorithm/yunji.feng/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/mnt/cfs/algorithm/yunji.feng/go_1_dog/PaddleDetection/ppdet/slim/distill_loss.py", line 418, in forward
    loss_module(stu_feats[i], tea_feats[i], inputs))
  File "/mnt/cfs/algorithm/yunji.feng/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/mnt/cfs/algorithm/yunji.feng/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/mnt/cfs/algorithm/yunji.feng/go_1_dog/PaddleDetection/ppdet/slim/distill_loss.py", line 709, in forward
    wmax[i][j] + 1, area_recip[0][j])
  File "/mnt/cfs/algorithm/yunji.feng/go_1_dog/PaddleDetection/ppdet/slim/distill_loss.py", line 630, in mask_value
    mask[xl:xr, yl:yr] = paddle.maximum(mask[xl:xr, yl:yr], value)
  File "/mnt/cfs/algorithm/yunji.feng/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/tensor/math.py", line 619, in maximum
    x, y, axis=axis, act=act, op_name=op_type)
  File "/mnt/cfs/algorithm/yunji.feng/miniconda3/envs/paddle/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/mnt/cfs/algorithm/yunji.feng/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/mnt/cfs/algorithm/yunji.feng/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/framework.py", line 434, in __impl__
    return func(*args, **kwargs)
  File "/mnt/cfs/algorithm/yunji.feng/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/tensor/math.py", line 218, in _elementwise_op_in_dygraph
    out = op(x, y, 'axis', axis, 'use_mkldnn', use_mkldnn)
RuntimeError: (PreconditionNotMet) The meta data must be valid when call the mutable data function. (at /paddle/paddle/phi/core/dense_tensor.cc:105)
  [operator < elementwise_max > error]
```

PPYOLOE_plus的l和x模型单独训练没有问题，更改了`coco_detection.yml`的数据路径，未更改其他配置文件

**Comment by nemonameless** [comment]
请说明paddle版本，或直接安装2.4.2或最新的paddle再试试。另外单卡训总bs太小了，训了精度也不高，不建议单卡训。
可以直接设置feat_distill: False，不使用FGD feature蒸馏，这个精度增益本身也很小。

**Comment by Feng1909** [comment]
升级2.4.2后仍然会报错，去掉FGD feature后可正常训练，谢谢！
