### ISSUE TITLE
yolo环境安装与调用

### ISSUE THREAD

**Issue by cunjing56** [PaddlePaddle/PaddleDetection#8049]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

**我想用在jetson上部署模型，之前训练的fasterRcnn不能部署，说可以用yolo
我在win,参考官方文档，安装了paddle develop版本--为了yolo, 但是训练的时候报错**

ValueError: (InvalidArgument) multiclass_nms3(): argument (position 4) must be double, but got str (at ..\paddle\fluid\pybind\op_function_common.cc:241)

(yologpu) D:\pkg\PaddleYOLO>python tools/train.py -c configs/yolov5/yolov5_s_300e_rice.yml --use_vdl=True  --eval
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
W0406 16:03:03.479086  7912 gpu_resources.cc:85] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.8, Runtime API Version: 11.2
W0406 16:03:03.483085  7912 gpu_resources.cc:115] device: 0, cuDNN Version: 8.2.
[04/06 16:03:09] ppdet.engine INFO: Epoch: [0] [ 0/17] eta: 3:34:48 lr: 0.000000 loss_box: 0.112053 loss_obj: 3.855213 loss_cls: 1.085340 loss: 80.841705 batch_cost: 2.5271 data_cost: 0.0000 ips: 6.3314 images/s
。。。。。。。。。。。。。
[04/06 16:04:44] ppdet.utils.checkpoint INFO: Save checkpoint: output\yolov5_s_300e_rice
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[04/06 16:04:44] ppdet.engine INFO: Eval loader length is 4, eval batch_size is 8.
[04/06 16:04:44] ppdet.engine INFO: Starting evaluation ......

Traceback (most recent call last):
  File "tools/train.py", line 172, in <module>
    main()
  File "tools/train.py", line 168, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 132, in run
    trainer.train(FLAGS.eval)
  File "D:\pkg\PaddleYOLO\ppdet\engine\trainer.py", line 468, in train
    self._eval_with_loader(self._eval_loader)
  File "D:\pkg\PaddleYOLO\ppdet\engine\trainer.py", line 503, in _eval_with_loader
    outs = self.model(data)
  File "D:\soft\anaconda3\envs\yologpu\lib\site-packages\paddle\nn\layer\layers.py", line 1246, in __call__
    return self.forward(*inputs, **kwargs)
  File "D:\pkg\PaddleYOLO\ppdet\modeling\architectures\meta_arch.py", line 75, in forward
    outs.append(self.get_pred())
  File "D:\pkg\PaddleYOLO\ppdet\modeling\architectures\yolov5.py", line 95, in get_pred
    return self._forward()
  File "D:\pkg\PaddleYOLO\ppdet\modeling\architectures\yolov5.py", line 86, in _forward
    bbox, bbox_num = self.yolo_head.post_process(
  File "D:\pkg\PaddleYOLO\ppdet\modeling\heads\yolov5_head.py", line 195, in post_process
    bbox_pred, bbox_num, _ = self.nms(pred_bboxes, pred_scores)
  File "D:\pkg\PaddleYOLO\ppdet\modeling\layers.py", line 214, in __call__
    return ops.multiclass_nms(bboxes, score, **kwargs)
  File "D:\pkg\PaddleYOLO\ppdet\modeling\ops.py", line 228, in multiclass_nms
    output, index, nms_rois_num = _C_ops.multiclass_nms3(bboxes, scores,
ValueError: (InvalidArgument) multiclass_nms3(): argument (position 4) must be double, but got str (at ..\paddle\fluid\pybind\op_function_common.cc:241)

**我转战linux, 安装paddle报错**
root@YANGJINGDL:/# python3
Python 3.8.16 (default, Mar 23 2023, 17:40:49)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
Error: Can not import paddle core while this file exists: /usr/local/lib/python3.8/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/usr/local/lib/python3.8/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/usr/local/lib/python3.8/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/core.py", line 338, in <module>
    raise e
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/core.py", line 274, in <module>
    from . import libpaddle
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

我该怎么办

### 复现环境 Environment

windows
python -m pip install paddlepaddle-gpu==0.0.0.post112 -f https://www.paddlepaddle.org.cn/whl/windows/gpu/develop.html
python3.8
cuda runtime 11.2

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
PaddleYOLO用的是那个版本

**Comment by nemonameless** [comment]
请使用最新PaddleYOLO的代码，2.6分支或develop分支都可以。报错的位置的代码`_C_ops`很早就移除了。
你在linux上安装的paddle版本不匹配，请再仔细检查你的环境里真正的cuda版本
