### ISSUE TITLE
使用ppyolo的命令行测试时出现错误 AssertionError: configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml is not a directory

### ISSUE THREAD

**Issue by LiaoChengkk** [PaddlePaddle/PaddleDetection#8085]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

 

>命令行： python tools/infer.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml -o use_gpu=true weights=weights/ppyolo_r50vd_dcn_1x_coco.pdparams --infer_img=demo/000000014439.jpg
结果：
W0414 16:56:08.598922 38084 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 11.4, Runtime API Version: 10.1
W0414 16:56:08.603125 38084 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
[04/14 16:56:10] ppdet.utils.checkpoint INFO: Finish loading model weights: weights/ppyolo_r50vd_dcn_1x_coco.pdparams
Traceback (most recent call last):
  File "tools/infer.py", line 177, in <module>
    main()
  File "tools/infer.py", line 173, in main
    run(FLAGS, cfg)
  File "tools/infer.py", line 127, in run
    images = get_test_images(FLAGS.infer_dir, FLAGS.infer_img)
  File "tools/infer.py", line 97, in get_test_images
    "{} is not a directory".format(infer_dir)
**AssertionError: configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml is not a directory**

使用的PaddleDetection版本是2.4.0， paddle版本是2.3

**Comment by nemonameless** [comment]
大概率是命令敲错了，你是不是把yml敲在了infer_img或infer_dir后面。重新照着文档输一遍试试
