### ISSUE TITLE
blazeface.yml人脸训练报错

### ISSUE THREAD

**Issue by yran1011** [PaddlePaddle/PaddleDetection#810]
环境: cuda10.0  cudnn7.6  RTX2080ti  PaddlePaddle 1.8.1
使用配置文件: blazeface.yml  数据集:wider_face
修改学习率  batch_size 等都报同样错误
2020-05-29 11:48:35,923-INFO: iter: 840, lr: 0.001000, 'loss': '6.801611', time: 0.514, eta: 1 day, 21:36:46
2020-05-29 11:48:46,167-INFO: iter: 860, lr: 0.001000, 'loss': '6.761255', time: 0.505, eta: 1 day, 20:45:01
2020-05-29 11:48:57,223-INFO: iter: 880, lr: 0.001000, 'loss': '6.585557', time: 0.561, eta: 2 days, 1:41:11
2020-05-29 11:49:07,257-INFO: iter: 900, lr: 0.001000, 'loss': '6.676511', time: 0.506, eta: 1 day, 20:49:45
2020-05-29 11:49:19,619-INFO: iter: 920, lr: 0.001000, 'loss': '6.596319', time: 0.615, eta: 2 days, 6:29:31
2020-05-29 11:49:31,520-INFO: iter: 940, lr: 0.001000, 'loss': '6.578011', time: 0.583, eta: 2 days, 3:38:20
2020-05-29 11:49:44,018-INFO: iter: 960, lr: 0.001000, 'loss': '6.779737', time: 0.639, eta: 2 days, 8:37:10
2020-05-29 11:49:54,386-INFO: iter: 980, lr: 0.001000, 'loss': '6.576465', time: 0.513, eta: 1 day, 21:29:59
2020-05-29 11:50:05,546-INFO: iter: 1000, lr: 0.001000, 'loss': '6.522973', time: 0.559, eta: 2 days, 1:31:14
2020-05-29 11:50:17,470-INFO: iter: 1020, lr: 0.001000, 'loss': '6.584724', time: 0.601, eta: 2 days, 5:16:22
2020-05-29 11:50:26,784-INFO: iter: 1040, lr: 0.001000, 'loss': '6.423560', time: 0.437, eta: 1 day, 14:43:18
2020-05-29 11:50:36,031-INFO: iter: 1060, lr: 0.001000, 'loss': '6.354516', time: 0.491, eta: 1 day, 19:31:08
2020-05-29 11:50:37,214-INFO: fail to map op [CropImageWithDataAchorSampling_c097e9] with error: Unable to allocate 49.5 GiB for an array with shape (47081, 47081, 3) and data type float64 and stack:
Traceback (most recent call last):
  File "/home/terrywang/RanYu/PaddleDetection/ppdet/data/reader.py", line 45, in __call__
    data = f(data, ctx)
  File "/home/terrywang/RanYu/PaddleDetection/ppdet/data/transform/operators.py", line 924, in __call__
    image_height, self.target_size)
  File "/home/terrywang/RanYu/PaddleDetection/ppdet/data/transform/op_helper.py", line 382, in crop_image_sampling
    sample_img = np.zeros((height, width, 3))
MemoryError: Unable to allocate 49.5 GiB for an array with shape (47081, 47081, 3) and data type float64

2020-05-29 11:50:37,236-WARNING: recv endsignal from outq with errmsg[consumer[consumer-aef-1] failed to map with error:[Unable to allocate 49.5 GiB for an array with shape (47081, 47081, 3) and data type float64]]
2020-05-29 11:50:38,315-WARNING: recv endsignal from outq with errmsg[consumer[consumer-aef-4] exits for reason[consumer[consumer-aef-1] failed to map with error:[Unable to allocate 49.5 GiB for an array with shape (47081, 47081, 3) and data type float64]]]
2020-05-29 11:50:40,888-WARNING: recv endsignal from outq with errmsg[consumer[consumer-aef-0] exits for reason[consumer[consumer-aef-4] exits for reason[consumer[consumer-aef-1] failed to map with error:[Unable to allocate 49.5 GiB for an array with shape (47081, 47081, 3) and data type float64]]]]

**Comment by yran1011** [comment]
2020-05-29 11:30:34,752-INFO: iter: 3460, lr: 0.000250, 'loss': '6.569792', time: 0.538, eta: 8 days, 22:40:34
2020-05-29 11:30:48,574-INFO: iter: 3480, lr: 0.000250, 'loss': '6.537301', time: 0.662, eta: 11 days, 0:21:15
2020-05-29 11:31:00,020-INFO: iter: 3500, lr: 0.000250, 'loss': '6.559053', time: 0.598, eta: 9 days, 22:44:05
2020-05-29 11:31:12,179-INFO: iter: 3520, lr: 0.000250, 'loss': '6.521289', time: 0.587, eta: 9 days, 18:01:40
2020-05-29 11:31:15,964-INFO: fail to map op [CropImageWithDataAchorSampling_141dbd] with error: Unable to allocate 49.2 GiB for an array with shape (46935, 46935, 3) and data type float64 and stack:
Traceback (most recent call last):
  File "/home/terrywang/RanYu/PaddleDetection/ppdet/data/reader.py", line 45, in __call__
    data = f(data, ctx)
  File "/home/terrywang/RanYu/PaddleDetection/ppdet/data/transform/operators.py", line 924, in __call__
    image_height, self.target_size)
  File "/home/terrywang/RanYu/PaddleDetection/ppdet/data/transform/op_helper.py", line 382, in crop_image_sampling
    sample_img = np.zeros((height, width, 3))
MemoryError: Unable to allocate 49.2 GiB for an array with shape (46935, 46935, 3) and data type float64

2020-05-29 11:31:16,204-WARNING: recv endsignal from outq with errmsg[consumer[consumer-acb-1] failed to map with error:[Unable to allocate 49.2 GiB for an array with shape (46935, 46935, 3) and data type float64]]
2020-05-29 11:31:20,024-WARNING: recv endsignal from outq with errmsg[consumer[consumer-acb-6] exits for reason[consumer[consumer-acb-1] failed to map with error:[Unable to allocate 49.2 GiB for an array with shape (46935, 46935, 3) and data type float64]]]
2020-05-29 11:31:22,213-WARNING: recv endsignal from outq with errmsg[consumer[consumer-acb-7] exits for reason[consumer[consumer-acb-6] exits for reason[consumer[consumer-acb-1] failed to map with error:[Unable to allocate 49.2 GiB for an array with shape (46935, 46935, 3) and data type float64]]]]
2020-05-29 11:31:23,563-INFO: iter: 3540, lr: 0.000250, 'loss': '6.519371', time: 0.545, eta: 9 days, 1:18:16
2020-05-29 11:31:23,833-WARNING: recv endsignal from outq with errmsg[consumer[consumer-acb-3] exits for reason[consumer[consumer-acb-7] exits for reason[consumer[consumer-acb-6] exits for reason[consumer[consumer-acb-1] failed to map with error:[Unable to allocate 49.2 GiB for an array with shape (46935, 46935, 3) and data type float64]]]]]
2020-05-29 11:31:26,663-WARNING: recv endsignal from outq with errmsg[consumer[consumer-acb-5] exits for reason[consumer[consumer-acb-3] exits for reason[consumer[consumer-acb-7] exits for reason[consumer[consumer-acb-6] exits for reason[consumer[consumer-acb-1] failed to map with error:[Unable to allocate 49.2 GiB for an array with shape (46935, 46935, 3) and data type float64]]]]]]
2020-05-29 11:31:29,499-WARNING: recv endsignal from outq with errmsg[consumer[consumer-acb-0] exits for reason[consumer[consumer-acb-5] exits for reason[consumer[consumer-acb-3] exits for reason[consumer[consumer-acb-7] exits for reason[consumer[consumer-acb-6] exits for reason[consumer[consumer-acb-1] failed to map with error:[Unable to allocate 49.2 GiB for an array with shape (46935, 46935, 3) and data type float64]]]]]]]
2020-05-29 11:31:33,823-WARNING: recv endsignal from outq with errmsg[consumer[consumer-acb-2] exits for reason[consumer[consumer-acb-0] exits for reason[consumer[consumer-acb-5] exits for reason[consumer[consumer-acb-3] exits for reason[consumer[consumer-acb-7] exits for reason[consumer[consumer-acb-6] exits for reason[consumer[consumer-acb-1] failed to map with error:[Unable to allocate 49.2 GiB for an array with shape (46935, 46935, 3) and data type float64]]]]]]]]
2020-05-29 11:31:39,752-WARNING: recv endsignal from outq with errmsg[consumer[consumer-acb-4] exits for reason[consumer[consumer-acb-2] exits for reason[consumer[consumer-acb-0] exits for reason[consumer[consumer-acb-5] exits for reason[consumer[consumer-acb-3] exits for reason[consumer[consumer-acb-7] exits for reason[consumer[consumer-acb-6] exits for reason[consumer[consumer-acb-1] failed to map with error:[Unable to allocate 49.2 GiB for an array with shape (46935, 46935, 3) and data type float64]]]]]]]]]
2020-05-29 11:31:39,756-WARNING: Your reader has raised an exception!
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/work/anaconda3/envs/paddle/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/work/anaconda3/envs/paddle/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/work/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1156, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/work/anaconda3/envs/paddle/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/work/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1136, in __thread_main__
    for tensors in self._tensor_reader():
  File "/work/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1206, in __tensor_reader_impl__
    for slots in paddle_reader():
  File "/work/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 506, in __reader_creator__
    for item in reader():
  File "/home/terrywang/RanYu/PaddleDetection/ppdet/data/reader.py", line 421, in _reader
    reader.reset()
  File "/home/terrywang/RanYu/PaddleDetection/ppdet/data/parallel_map.py", line 259, in reset
    assert not self._exit, "cannot reset for already stopped dataset"
AssertionError: cannot reset for already stopped dataset

/work/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tools/train.py", line 366, in <module>
    main()
  File "tools/train.py", line 239, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "/work/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/work/anaconda3/envs/paddle/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/work/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/work/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1167, in _run_impl
    return_merged=return_merged)
  File "/work/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/executor.py", line 879, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/work/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/work/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1078, in _init_non_iterable
    attrs={'drop_last': self._drop_last})
  File "/work/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/reader.py", line 976, in __init__
    self._init_non_iterable()
  File "/work/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/reader.py", line 608, in from_generator
    iterable, return_list, drop_last)
  File "/home/terrywang/RanYu/PaddleDetection/ppdet/modeling/architectures/blazeface.py", line 203, in build_inputs
    iterable=iterable) if use_dataloader else None
  File "tools/train.py", line 112, in main
    feed_vars, train_loader = model.build_inputs(**inputs_def)
  File "tools/train.py", line 366, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]

**Comment by qingqing01** [comment]
@yran1011  看错信息是`CropImageWithDataAchorSampling`里出错，导致分配的内存过大导致。 你是基于WiderFace数据吗？ 我们排查下。 你训练时，也可以去掉此预处理:

https://github.com/PaddlePaddle/PaddleDetection/blob/7bb04787ce99889331973811a1063cf6e3689914/configs/face_detection/blazeface.yml#L63-L72

**Comment by yran1011** [comment]
@qingqing01 是WiderFace数据集，把这个预处理注释之后可以正常训练了，注释了之后对检测效果会有多少影响呢？

**Comment by qingqing01** [comment]
@yran1011 对小人脸精度有一些影响，应该不是特别大。很奇怪，我们自己跑的时候没发现错误，我们尽快排查下。

**Comment by Payne214** [comment]
参考文档 https://aistudio.baidu.com/aistudio/projectdetail/528204 训练人脸检测模型出现MemoryError 异常

MemoryError: Unable to allocate 62.4 GiB for an array with shape (52831, 52831, 3) and data type float64

2020-06-05 10:52:48,889-WARNING: recv endsignal from outq with errmsg[consumer[consumer-13d-5] failed to map with error:[Unable to allocate 62.4 GiB for an array with shape (52831, 52831, 3) and data type float64]]
2020-06-05 10:52:49,521-WARNING: recv endsignal from outq with errmsg[consumer[consumer-13d-0] exits for reason[consumer[consumer-13d-5] failed to map with error:[Unable to allocate 62.4 GiB for an array with shape (52831, 52831, 3) and data type float64]]]

**Comment by Payne214** [comment]
将batch_size设置为1时，可以训练，但loss为“nan"

2020-06-05 11:19:12,698-INFO: iter: 2380, lr: 0.000250, 'loss': '10.066326', time: 0.108, eta: 0:53:22
2020-06-05 11:19:15,765-INFO: iter: 2400, lr: 0.000250, 'loss': '12.178331', time: 0.146, eta: 1:11:52
2020-06-05 11:19:20,285-INFO: iter: 2420, lr: 0.000250, 'loss': '10.595432', time: 0.241, eta: 1:58:55
2020-06-05 11:19:22,492-INFO: iter: 2440, lr: 0.000250, 'loss': '11.308760', time: 0.108, eta: 0:53:16
2020-06-05 11:19:24,922-INFO: iter: 2460, lr: 0.000250, 'loss': '10.203234', time: 0.118, eta: 0:58:04
2020-06-05 11:19:27,099-INFO: iter: 2480, lr: 0.000250, 'loss': 'nan', time: 0.108, eta: 0:53:14
2020-06-05 11:19:29,509-INFO: iter: 2500, lr: 0.000250, 'loss': 'nan', time: 0.127, eta: 1:02:34
2020-06-05 11:19:32,698-INFO: iter: 2520, lr: 0.000250, 'loss': 'nan', time: 0.149, eta: 1:13:03
2020-06-05 11:19:35,468-INFO: iter: 2540, lr: 0.000250, 'loss': 'nan', time: 0.144, eta: 1:10:29
2020-06-05 11:19:38,325-INFO: iter: 2560, lr: 0.000250, 'loss': 'nan', time: 0.149, eta: 1:12:57

**Comment by yja1** [comment]
train blazeface.yml also CropImageWithDataAchorSampling_7d6846 error
have delete CropImageWithDataAchorSampling in blazeface.yml ,but same error


architecture: BlazeFace
max_iters: 320000
pretrain_weights:
use_gpu: true
snapshot_iter: 10000
log_smooth_window: 20
log_iter: 20
metric: WIDERFACE
save_dir: output
weights: output/blazeface/model_final
# 1(label_class) + 1(background)
num_classes: 2

BlazeFace:
  backbone: BlazeNet
  output_decoder:
    keep_top_k: 750
    nms_threshold: 0.3
    nms_top_k: 5000
    score_threshold: 0.01
  min_sizes: [[16.,24.], [32., 48., 64., 80., 96., 128.]]
  use_density_prior_box: false

BlazeNet:
  with_extra_blocks: true
  lite_edition: false

LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [240000, 300000]

OptimizerBuilder:
  optimizer:
    momentum: 0.0
    type: RMSPropOptimizer
  regularizer:
    factor: 0.0005
    type: L2

TrainReader:
  inputs_def:
    image_shape: [3, 640, 640]
    fields: ['image', 'gt_bbox', 'gt_class']
  dataset:
    !WIDERFaceDataSet
    dataset_dir: dataset/wider_face
    anno_path: wider_face_split/wider_face_train_bbx_gt.txt
    image_dir: WIDER_train/images
  sample_transforms:
  - !DecodeImage
    to_rgb: true
  - !NormalizeBox {}
  - !RandomDistort
    brightness_lower: 0.875
    brightness_upper: 1.125
    is_order: true
  - !ExpandImage
    max_ratio: 4
    prob: 0.5
#  - !CropImageWithDataAchorSampling
#    anchor_sampler:
#    - [1, 10, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.2, 0.0]
#    batch_sampler:
#    - [1, 50, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0]
#    - [1, 50, 0.3, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0]
#    - [1, 50, 0.3, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0]
#    - [1, 50, 0.3, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0]
#    - [1, 50, 0.3, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0]
#    target_size: 640
  - !RandomInterpImage
    target_size: 640
  - !RandomFlipImage
    is_normalized: true
  - !Permute {}
  - !NormalizeImage
    is_scale: false
    mean: [104, 117, 123]
    std: [127.502231, 127.502231, 127.502231]
  batch_size: 8
  use_process: true
  worker_num: 8
  shuffle: true

EvalReader:
  inputs_def:
    fields: ['image', 'im_id']
  dataset:
    !WIDERFaceDataSet
    dataset_dir: dataset/wider_face
    anno_path: wider_face_split/wider_face_val_bbx_gt.txt
    image_dir: WIDER_val/images
  sample_transforms:
  - !DecodeImage
    to_rgb: true
  - !NormalizeBox {}
  - !Permute {}
  - !NormalizeImage
    is_scale: false
    mean: [104, 117, 123]
    std: [127.502231, 127.502231, 127.502231]
  batch_size: 1

TestReader:
  inputs_def:
    fields: ['image', 'im_id', 'im_shape']
  dataset:
    !ImageFolder
    use_default_label: true
  sample_transforms:
  - !DecodeImage
    to_rgb: true
  - !Permute {}
  - !NormalizeImage
    is_scale: false
    mean: [104, 117, 123]
    std: [127.502231, 127.502231, 127.502231]
  batch_size: 1
