### ISSUE TITLE
paddle  模型导出报错

### ISSUE THREAD

**Issue by chenjf2015103095** [PaddlePaddle/PaddleDetection#8149]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

对于RT-DETR算法正常训练的结果进行模型导出报错（可以正常训练，模型评估），但是导出报错
执行命令如下：
python3 tools/export_model.py -c configs/rtdetr/rtdetr_r50vd_6x_coco.yml               -o weights=/media/PaddleDetection/output/rtdetr_r50vd_6x_coco/best_model                --output_dir=output_inference
报错信息如下：

loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[04/25 16:56:07] ppdet.engine INFO: Export inference config file to output_inference/rtdetr_r50vd_6x_coco/infer_cfg.yml
Traceback (most recent call last):
  File "tools/export_model.py", line 116, in <module>
    main()
  File "tools/export_model.py", line 112, in main
    run(FLAGS, cfg)
  File "tools/export_model.py", line 79, in run
    trainer.export(FLAGS.output_dir)
  File "/media/PaddleDetection/ppdet/engine/trainer.py", line 1177, in export
    static_model, pruned_input_spec = self._get_infer_cfg_and_input_spec(
  File "/media/PaddleDetection/ppdet/engine/trainer.py", line 1137, in _get_infer_cfg_and_input_spec
    input_spec, static_model.forward.main_program,
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 580, in main_program
    concrete_program = self.concrete_program
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program
    return self.concrete_program_specify_input_spec(input_spec=None)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 527, in concrete_program_specify_input_spec
    concrete_program, _ = self.get_concrete_program(
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
    self._caches[item_id] = self._build_once(item)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 785, in _build_once
    concrete_program = ConcreteProgram.from_func_spec(
  File "/usr/local/lib/python3.8/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 740, in from_func_spec
    error_data.raise_new_exception()
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
UnboundLocalError: In transformed code:

    File "/media/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 76, in forward
	outs.append(self.get_pred())
    File "/media/PaddleDetection/ppdet/modeling/architectures/detr.py", line 116, in get_pred
	return self._forward()
    File "/media/PaddleDetection/ppdet/modeling/architectures/detr.py", line 83, in _forward
        # Neck
        if self.neck is not None:
            body_feats = self.neck(body_feats)
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE

        # Transformer

    File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
	return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
	outputs = self.forward(*inputs, **kwargs)
    File "/tmp/tmp65vgjdrs.py", line 65, in forward
	num_encoder_layers > 0, true_fn_17, false_fn_17, (i, proj_feats,

    UnboundLocalError: local variable 'i' referenced before assignment



### 复现环境 Environment

-os：linux/docker
-paddlepaddle：2.3.2
-paddledetection：release/develop
-python:3.8

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.


### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by khwengXU** [comment]
我这边导出模型时，也有相同的问题

**Comment by chenjf2015103095** [comment]
> 

你好，请问解决了吗

**Comment by lyuwenyu** [comment]
<img width="801" alt="image" src="https://user-images.githubusercontent.com/17582080/234488176-d4d65ef9-b0ef-420c-b133-5298162c4bca.png">

**Comment by wokaikaixinxin** [comment]
相同的问题。+1。插眼。

**Comment by khwengXU** [comment]
> [wokaikaixinxin](/wokaikaixinxin)

我这边按照 [lyuwenyu](https://github.com/lyuwenyu) 的方式更新版本就可以了
