### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'prob'

### ISSUE THREAD

**Issue by graysuki** [PaddlePaddle/PaddleDetection#8150]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我的python环境是3.8.10
在执行rtdetr文件里提供的训练指令python3 tools/train.py -c configs/rtdetr/rtdetr_r50vd_6x_coco.yml --eval时报如下错误
Traceback (most recent call last):
  File "tools/train.py", line 202, in <module>
    main()
  File "tools/train.py", line 198, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 142, in run
    trainer = Trainer(cfg, mode='train')
  File "/home/gray/code/PaddleDetection/ppdet/engine/trainer.py", line 98, in __init__
    self.loader = create('{}Reader'.format(capital_mode))(
  File "/home/gray/code/PaddleDetection/ppdet/core/workspace.py", line 292, in create
    return cls(**cls_kwargs)
  File "/home/gray/code/PaddleDetection/ppdet/data/reader.py", line 237, in __init__
    super(TrainReader, self).__init__(sample_transforms, batch_transforms,
  File "/home/gray/code/PaddleDetection/ppdet/data/reader.py", line 149, in __init__
    self._sample_transforms = Compose(
  File "/home/gray/code/PaddleDetection/ppdet/data/reader.py", line 50, in __init__
    f = op_cls(**v)
TypeError: __init__() got an unexpected keyword argument 'prob'
请问我该怎么做

**Comment by lyuwenyu** [comment]
最新的代码 + 默认的配置， 复现不了你说的问题，先确保在官方的配置和代码下能跑通

**Comment by zbtang1999** [comment]
你好，我遇到了和你一模一样的错误，想问一下你解决了吗

**Comment by graysuki** [comment]
> 你好，我遇到了和你一模一样的错误，想问一下你解决了吗

我应该是分支搞错了，切到develop分支就好了

**Comment by lxy-ben** [comment]
> > 你好，我遇到了和你一模一样的错误，想问一下你解决了吗
> 
> 我应该是分支搞错了，切到develop分支就好了

我也遇到了一样的问题，切到develop是什么意思？

**Comment by Todayonlymyself** [comment]
我也遇到了一样的问题
