### ISSUE TITLE
paddle_serving部署模型，test_client.py 报错“KeyError: 'multiclass_nms3_0.tmp_0.lod'”

### ISSUE THREAD

**Issue by leizhu900516** [PaddlePaddle/PaddleDetection#8164]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

paddle_serving部署模型，test_client.py 报错“KeyError: 'multiclass_nms3_0.tmp_0.lod'”
具体报错如下
`fetch_map= {'multiclass_nms3_0.tmp_0': array([[0.0000000e+00, 9.5639348e-01, 4.0252359e+02, 3.9090063e+02,
        5.0326431e+02, 5.3184894e+02],
       [0.0000000e+00, 1.6476010e-01, 5.1402698e+02, 2.1841096e+02,
        5.5258704e+02, 3.1683002e+02],
       [0.0000000e+00, 1.4482307e-01, 5.6169171e+02, 0.0000000e+00,
        6.0550348e+02, 1.1732089e+02],
       [0.0000000e+00, 4.6245132e-02, 5.2218506e+02, 2.5613760e+02,
        5.5459241e+02, 3.2566800e+02]], dtype=float32), 'image': '../../demo/seal004.jpg'}
Traceback (most recent call last):
  File "test_client.py", line 46, in <module>
    postprocess(fetch_map)
  File "/usr/local/python3/lib/python3.7/site-packages/paddle_serving_app/reader/image_reader.py", line 431, in __call__
    self.clsid2catid)
  File "/usr/local/python3/lib/python3.7/site-packages/paddle_serving_app/reader/image_reader.py", line 347, in _get_bbox_result
    lod = [fetch_map[fetch_name + '.lod']]
KeyError: 'multiclass_nms3_0.tmp_0.lod'`

serving_client_conf.prototxt 配置如下
`feed_var {
  name: "im_shape"
  alias_name: "im_shape"
  is_lod_tensor: false
  feed_type: 1
  shape: 2
}
feed_var {
  name: "image"
  alias_name: "image"
  is_lod_tensor: false
  feed_type: 1
  shape: 3
  shape: 608
  shape: 608
}
feed_var {
  name: "scale_factor"
  alias_name: "scale_factor"
  is_lod_tensor: false
  feed_type: 1
  shape: 2
}
fetch_var {
  name: "multiclass_nms3_0.tmp_0"
  alias_name: "multiclass_nms3_0.tmp_0"
  is_lod_tensor: false
  fetch_type: 1
  shape: 6
}
fetch_var {
  name: "multiclass_nms3_0.tmp_2"
  alias_name: "multiclass_nms3_0.tmp_2"
  is_lod_tensor: false
  fetch_type: 2
}`

**Comment by guiltylelouch** [comment]
解决了吗？
