### ISSUE TITLE
YOLOv5训练报错

### ISSUE THREAD

**Issue by gyc137** [PaddlePaddle/PaddleDetection#8173]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training

### Bug描述 Describe the Bug

我从DOTA数据集中挑选个别图片作为新数据集，此前用PP-YOLOE-R能够正常训练，而现在用YOLOv5进行训练报错了。
训练命令为python -m paddle.distributed.launch tools/train.py -c configs/yolov5/yolov5_l_300e_coco.yml --eval --use_vdl True --vdl_log_dir output/yolov5_l_100e_dota/scalar

以下为报错内容:
Exception in thread Thread-1:
Traceback (most recent call last):
File "/home/gyc/anaconda3/envs/yoloer/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
File "/home/gyc/anaconda3/envs/yoloer/lib/python3.8/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "/home/gyc/anaconda3/envs/yoloer/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 217, in _thread_loop
batch = self._dataset_fetcher.fetch(indices,
File "/home/gyc/anaconda3/envs/yoloer/lib/python3.8/site-packages/paddle/fluid/dataloader/fetcher.py", line 134, in fetch
data = self.collate_fn(data)
File "/home/gyc/PaddleYOLO/ppdet/data/reader.py", line 91, in call
batch_data = default_collate_fn(data)
File "/home/gyc/PaddleYOLO/ppdet/data/utils.py", line 60, in default_collate_fn
return {
File "/home/gyc/PaddleYOLO/ppdet/data/utils.py", line 61, in
key: default_collate_fn([d[key] for d in batch])
File "/home/gyc/PaddleYOLO/ppdet/data/utils.py", line 67, in default_collate_fn
raise RuntimeError(
RuntimeError: fileds number not same among samples in a batch

### 复现环境 Environment

PaddlePaddle版本为2.3.2，其余环境都为推荐配置。

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by gyc137** [comment]
我在https://github.com/PaddlePaddle/PaddleYOLO/issues/131 中也进行了提问，对方回复PaddleYOLO不支持旋转框。请问想继续使用YOLOv5或YOLOX对旋转框数据集训练是要把数据集的标注文件改为水平框吗?有没有格式转换的参考文件呢?

**Comment by lyuwenyu** [comment]
这个是数据准备的文章 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.6/docs/tutorials/data

**Comment by gyc137** [comment]
> 这个是数据准备的文章 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.6/docs/tutorials/data

我想问的是有没有旋转框标注转为水平框标注的参考文件，这个数据准备中好像没有相关内容?
