### ISSUE TITLE
RTDETR模型导出存在BUG

### ISSUE THREAD

**Issue by neverstoplearn** [PaddlePaddle/PaddleDetection#8184]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Export

### Bug描述 Describe the Bug

利用python tools/export_model.py -c configs/rtdetr/rtdetr_hgnetv2_l_6x_coco.yml  -o weights=output/rtdetr_hgnetv2_l_6x_coco/best_model.pdparams  trt=True --output_dir=output_inference导出模型。
报告：
Traceback (most recent call last):
  File "tools/export_model.py", line 116, in <module>
    main()
  File "tools/export_model.py", line 112, in main
    run(FLAGS, cfg)
  File "tools/export_model.py", line 79, in run
    trainer.export(FLAGS.output_dir)
  File "/home/root123/zx/PaddleDetection/ppdet/engine/trainer.py", line 1177, in export
    static_model, pruned_input_spec = self._get_infer_cfg_and_input_spec(
  File "/home/root123/zx/PaddleDetection/ppdet/engine/trainer.py", line 1137, in _get_infer_cfg_and_input_spec
    input_spec, static_model.forward.main_program,
  File "/home/root123/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 580, in main_program
    concrete_program = self.concrete_program
  File "/home/root123/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program
    return self.concrete_program_specify_input_spec(input_spec=None)
  File "/home/root123/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 527, in concrete_program_specify_input_spec
    concrete_program, _ = self.get_concrete_program(
  File "/home/root123/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/home/root123/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
    self._caches[item_id] = self._build_once(item)
  File "/home/root123/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 785, in _build_once
    concrete_program = ConcreteProgram.from_func_spec(
  File "/home/root123/anaconda3/envs/paddle/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/root123/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/root123/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "/home/root123/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 740, in from_func_spec
    error_data.raise_new_exception()
  File "/home/root123/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
UnboundLocalError: In transformed code:

    File "/home/root123/zx/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 76, in forward
	outs.append(self.get_pred())
    File "/home/root123/zx/PaddleDetection/ppdet/modeling/architectures/detr.py", line 116, in get_pred
	return self._forward()
    File "/home/root123/zx/PaddleDetection/ppdet/modeling/architectures/detr.py", line 83, in _forward
        # Neck
        if self.neck is not None:
            body_feats = self.neck(body_feats)
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE

        # Transformer

    File "/home/root123/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
	return self._dygraph_call_func(*inputs, **kwargs)
    File "/home/root123/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
	outputs = self.forward(*inputs, **kwargs)
    File "/tmp/tmpzpdjy4xc.py", line 65, in forward
	num_encoder_layers > 0, true_fn_16, false_fn_16, (i, proj_feats,

    UnboundLocalError: local variable 'i' referenced before assignment


### 复现环境 Environment

OS：Linux
CUDA: 11.1
PaddlePaddle: 2.3.2
Python: 3.8.16


### Bug描述确认 Bug description confirmation

- [x] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.


### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
paddle版本  >= 2.4.1

**Comment by neverstoplearn** [comment]
> paddle版本 >= 2.4.1

已解决
