### ISSUE TITLE
导出的TinyPose模型中，shuffle channel全部被转换为底层的操作。这导致了大量transpose，实机性能较差。

### ISSUE THREAD

**Issue by Celeste-cj** [PaddlePaddle/PaddleDetection#8241]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Export

### Bug描述 Describe the Bug

![image](https://github.com/PaddlePaddle/PaddleDetection/assets/46734081/9ea49d3d-0428-4619-bd1a-e8c586126566)
自己训练并导出的模型如上图，shuffle channel是一堆底层的transpose、reshape操作。

![image](https://github.com/PaddlePaddle/PaddleDetection/assets/46734081/4e72c6ca-adb4-499c-814e-57b61d647bd3)
官方提供的预训练权重⬆️，shuffle channel是正常的算子。

复现步骤：
1. 训练一个256x192的TinyPose模型
2. 命令行执行
```bash
python tools/export_model.py -c configs/${model_type}/${model_name}.yml -o weights=output/${model_name}/best_model TestReader.fuse_normalize=true --output_dir=output_inference/

paddle_lite_opt --model_file=output_inference/${model_name}/model.pdmodel --param_file=output_inference/${model_name}/model.pdiparams --optimize_out=output_inference/${model_name}_arm/model --valid_targets=arm --optimize_out_type=naive_buffer 
```

### 复现环境 Environment

PaddlePaddle：2.4.2
PaddleDet：2.6.0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Celeste-cj** [comment]
补充：
从官网下载的pdmodel，shuffle channel也是由reshape、transpose实现的，但是没有fill_constant的操作
![image](https://github.com/PaddlePaddle/PaddleDetection/assets/46734081/30877402-d9ec-4f6f-ac19-40679adf6443)

将这个模型用下面的命令导出到arm，能够正常转换为shuffle channel
```bash
paddle_lite_opt --model_dir=tinypose_256x192 --optimize_out=output3 --valid_targets=arm  --optimize_out_type=naive_buffer
```
![image](https://github.com/PaddlePaddle/PaddleDetection/assets/46734081/91d0859c-e58d-4ffb-9c71-a5c4b9d9efd7)

**Comment by Celeste-cj** [comment]
- 环境：
PaddlePaddle-GPU：2.3.2
PaddleDet: 2.6.0

- 错误信息
```
Traceback (most recent call last):
  File "tools/export_model.py", line 110, in <module>
    main()
  File "tools/export_model.py", line 106, in main
    run(FLAGS, cfg)
  File "tools/export_model.py", line 73, in run
    trainer.export(FLAGS.output_dir)
  File "/data/chenjing/PaddleDetection/ppdet/engine/trainer.py", line 1230, in export
    static_model, pruned_input_spec = self._get_infer_cfg_and_input_spec(
  File "/data/chenjing/PaddleDetection/ppdet/engine/trainer.py", line 1190, in _get_infer_cfg_and_input_spec
    input_spec, static_model.forward.main_program,
  File "/home/chenjing/anaconda3/envs/pp/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 580, in main_program
    concrete_program = self.concrete_program
  File "/home/chenjing/anaconda3/envs/pp/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program
    return self.concrete_program_specify_input_spec(input_spec=None)
  File "/home/chenjing/anaconda3/envs/pp/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 527, in concrete_program_specify_input_spec
    concrete_program, _ = self.get_concrete_program(
  File "/home/chenjing/anaconda3/envs/pp/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/home/chenjing/anaconda3/envs/pp/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
    self._caches[item_id] = self._build_once(item)
  File "/home/chenjing/anaconda3/envs/pp/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 785, in _build_once
    concrete_program = ConcreteProgram.from_func_spec(
  File "/home/chenjing/anaconda3/envs/pp/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/chenjing/anaconda3/envs/pp/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/chenjing/anaconda3/envs/pp/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "/home/chenjing/anaconda3/envs/pp/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 740, in from_func_spec
    error_data.raise_new_exception()
```
