### ISSUE TITLE
RT-DETR部署转模型报错

### ISSUE THREAD

**Issue by GDbbq** [PaddlePaddle/PaddleDetection#8243]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Deploy

### Bug描述 Describe the Bug

[root@plp-algorithm01 PaddleDetection]# python tools/export_model.py -c configs/rtdetr/rtdetr_r50vd_6x_coco.yml               -o weights=https://bj.bcebos.com/v1/paddledet/models/rtdetr_r50vd_6x_coco.pdparams trt=True               --output_dir=output_inference
[05/15 17:04:29] ppdet.utils.checkpoint INFO: Finish loading model weights: /root/.cache/paddle/weights/rtdetr_r50vd_6x_coco.pdparams
[05/15 17:04:30] ppdet.data.source.category WARNING: anno_file 'dataset/coco/annotations/instances_val2017.json' is None or not set or not exist, please recheck TrainDataset/EvalDataset/TestDataset.anno_path, otherwise the default categories will be used by metric_type.
[05/15 17:04:30] ppdet.data.source.category WARNING: metric_type: COCO, load default categories of COCO.
[05/15 17:04:30] ppdet.engine INFO: Export inference config file to output_inference/rtdetr_r50vd_6x_coco/infer_cfg.yml
Traceback (most recent call last):
  File "tools/export_model.py", line 116, in <module>
    main()
  File "tools/export_model.py", line 112, in main
    run(FLAGS, cfg)
  File "tools/export_model.py", line 79, in run
    trainer.export(FLAGS.output_dir)
  File "/data/linjiahui/projects/PaddleDetection/ppdet/engine/trainer.py", line 1177, in export
    static_model, pruned_input_spec = self._get_infer_cfg_and_input_spec(
  File "/data/linjiahui/projects/PaddleDetection/ppdet/engine/trainer.py", line 1137, in _get_infer_cfg_and_input_spec
    input_spec, static_model.forward.main_program,
  File "/root/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 580, in main_program
    concrete_program = self.concrete_program
  File "/root/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program
    return self.concrete_program_specify_input_spec(input_spec=None)
  File "/root/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 527, in concrete_program_specify_input_spec
    concrete_program, _ = self.get_concrete_program(
  File "/root/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/root/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
    self._caches[item_id] = self._build_once(item)
  File "/root/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 785, in _build_once
    concrete_program = ConcreteProgram.from_func_spec(
  File "/root/anaconda3/envs/paddle/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/root/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/root/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 740, in from_func_spec
    error_data.raise_new_exception()
  File "/root/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
UnboundLocalError: In transformed code:

    File "/data/linjiahui/projects/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 76, in forward
        outs.append(self.get_pred())
    File "/data/linjiahui/projects/PaddleDetection/ppdet/modeling/architectures/detr.py", line 118, in get_pred
        return self._forward()
    File "/data/linjiahui/projects/PaddleDetection/ppdet/modeling/architectures/detr.py", line 83, in _forward
        # Neck
        if self.neck is not None:
            body_feats = self.neck(body_feats)
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE

        # Transformer

    File "/root/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
        return self._dygraph_call_func(*inputs, **kwargs)
    File "/root/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
        outputs = self.forward(*inputs, **kwargs)
    File "/tmp/tmpu6z5i0ha.py", line 65, in forward
        num_encoder_layers > 0, true_fn_19, false_fn_19, (i, proj_feats,

    UnboundLocalError: local variable 'i' referenced before assignment


### 复现环境 Environment

linux


### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.


### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
paddle>=2.41
