### ISSUE TITLE
ppyoloer 使用 deploy 推理时， 指定 save_result  保存json文件，坐标点不正确

### ISSUE THREAD

**Issue by xueyeyu** [PaddlePaddle/PaddleDetection#8254]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Deploy

### Bug描述 Describe the Bug

根据  deploy/python/infer.py 部署推理，加入--save_results参数时，保存依然为4个浮点数。

示例
{"image_id": 0, "category_id": 0, "file_name": "XXXXX.JPG", "bbox": [3648.358642578125, 1576.3292236328125, -3063.8885498046875, -174.1773681640625], "score": 0.8258764743804932}, 

### 复现环境 Environment

paddledetection develop 版本  看了下代码好像2.6版本也有此问题
paddle  2.3.2版本

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by xueyeyu** [comment]
临时用的这个代码。

 def save_coco_results  函数中
 ```             
# 'bbox': [box[2], box[3], box[4] - box[2],
#      box[5] - box[3]],  # xyxy -> xywh
'bbox': [box[2], box[3], box[4], box[5],box[6],box[7],box[8],box[9]],
```

**Comment by AntyRia** [comment]
> 临时用的这个代码。
> 
> def save_coco_results 函数中
> 
> ```
> # 'bbox': [box[2], box[3], box[4] - box[2],
> #      box[5] - box[3]],  # xyxy -> xywh
> 'bbox': [box[2], box[3], box[4], box[5],box[6],box[7],box[8],box[9]],
> ```

这个临时代码好像不可以，在使用回报越界
Traceback (most recent call last):
  File "deploy/python/infer_1.py", line 870, in <module>
    main()
  File "deploy/python/infer_1.py", line 842, in main
    save_results=FLAGS.save_results)
  File "deploy/python/infer_1.py", line 301, in predict_image
    image_list, results, use_coco_category=FLAGS.use_coco_category)
  File "deploy/python/infer_1.py", line 325, in save_coco_results
    'score': box[1]} for box in boxes])
  File "deploy/python/infer_1.py", line 325, in <listcomp>
    'score': box[1]} for box in boxes])
IndexError: list index out of range

**Comment by AntyRia** [comment]
补充说明：
使用版本：2.6
![image](https://github.com/PaddlePaddle/PaddleDetection/assets/75578545/2aeb6123-ec51-4713-a0f9-4699bdc0f756)
同样出现只显示浮点数
![image](https://github.com/PaddlePaddle/PaddleDetection/assets/75578545/468544be-d187-4d59-a1fc-ee9ef1697675)

**Comment by xueyeyu** [comment]
> 补充说明： 使用版本：2.6 ![image](https://user-images.githubusercontent.com/75578545/239676803-2aeb6123-ec51-4713-a0f9-4699bdc0f756.png) 同样出现只显示浮点数 ![image](https://user-images.githubusercontent.com/75578545/239676867-468544be-d187-4d59-a1fc-ee9ef1697675.png)

我看你用的是好像是 ppyoloeplus 不是ppyoloer  ， ppyoloer 是旋转框检测，有4个点
