### ISSUE TITLE
Yolov3在NPU上训练，loss不收敛

### ISSUE THREAD

**Issue by chenqion** [PaddlePaddle/PaddleDetection#8263]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training

### Bug描述 Describe the Bug

npu上训练yolov3-mobilenet, loss跑飞， 添加 FLAGS_npu_check_nan_inf环境变量定位溢出算子， **精度溢出算子**为： SigmoidCrossEntropyWithLogitsGrad

****报错信息****如下：
Traceback (most recent call last):
  File "tools/train.py", line 204, in <module>
    main()
  File "tools/train.py", line 200, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 153, in run
    trainer.train(FLAGS.eval)
  File "/PaddleDetection/ppdet/engine/trainer.py", line 543, in train
    loss.backward()
  File "/opt/py37env/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/opt/py37env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/py37env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 536, in __impl__
    return func(*args, **kwargs)
  File "/opt/py37env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 329, in backward
    core.eager.run_backward([self], grad_tensor, retain_graph)
RuntimeError: (PreconditionNotMet) Operator SigmoidCrossEntropyWithLogitsGrad contains Nan/Inf. (at /******/PaddleCustomDevice/backends/npu/kernels/funcs/npu_op_runner.cc:652)

### 复现环境 Environment

Linux
PaddleCustomDevice:master
PaddleDetection:develop  v2.6.0 v2.4.0
Cann:6.0.0.alpha005
Python 3.7.16
gcc:8.2.0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
这个得找相关卡的去咨询 在gpu训练没问题
