### ISSUE TITLE
我在AIstudio中用RTDETR实现目标检测，但是在训练时rtdetr_transformer.py中出现报错,并且用其他模型训练不会报错

### ISSUE THREAD

**Issue by liminggao2333** [PaddlePaddle/PaddleDetection#8275]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

这是我遇到的问题
Traceback (most recent call last):
  File "/home/aistudio/PaddleDetection/tools/train.py", line 204, in <module>
    main()
  File "/home/aistudio/PaddleDetection/tools/train.py", line 200, in main
    run(FLAGS, cfg)
  File "/home/aistudio/PaddleDetection/tools/train.py", line 144, in run
    trainer = Trainer(cfg, mode='train')
  File "/home/aistudio/PaddleDetection/ppdet/engine/trainer.py", line 113, in __init__
    self.model = create(cfg.architecture)
  File "/home/aistudio/PaddleDetection/ppdet/core/workspace.py", line 255, in create
    cls_kwargs.update(cls.from_config(config, **kwargs))
  File "/home/aistudio/PaddleDetection/ppdet/modeling/architectures/detr.py", line 61, in from_config
    transformer = create(cfg['transformer'], **kwargs)
  File "/home/aistudio/PaddleDetection/ppdet/core/workspace.py", line 292, in create
    return cls(**cls_kwargs)
  File "/home/aistudio/PaddleDetection/ppdet/modeling/transformers/rtdetr_transformer.py", line 345, in __init__
    self._reset_parameters()
  File "/home/aistudio/PaddleDetection/ppdet/modeling/transformers/rtdetr_transformer.py", line 367, in _reset_parameters
    xavier_uniform_(l[0].weight)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/container.py", line 82, in __getitem__
    return self._sub_layers[str(name)]
KeyError: '0'

**Comment by lyuwenyu** [comment]
改啥了？ 是用的ppdet develop分支嘛

**Comment by liminggao2333** [comment]
> 改啥了？ 是用的ppdet develop分支嘛

是因为我的paddle版本用的是2.2，paddleDetection2.6需要paddle2.4支持，paddle2.4多出了几个函数，所以以前的模型都可以用，新模型RTDETR没法初始化

**Comment by yushanshan05** [comment]
我也有同样的问题，用的是develop分支
