### ISSUE TITLE
【论文复现156】代码在2.5版本可以训练，合入到develop后出现bug

### ISSUE THREAD

**Issue by Atlantisming** [PaddlePaddle/PaddleDetection#8277]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在trainer.py 训练过程 的self.optimizer.step() 时报错。请问有排查的建议吗？
```
Traceback (most recent call last):
  File "tools/train.py", line 204, in <module>
    main()
  File "tools/train.py", line 200, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 153, in run
    trainer.train(FLAGS.eval)
  File "/home/a401-2/PycharmProjects/PaddleDetection/ppdet/engine/trainer.py", line 544, in train
    self.optimizer.step()
  File "/home/a401-2/anaconda3/envs/paddlegpu/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/a401-2/anaconda3/envs/paddlegpu/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 319, in __impl__
    return func(*args, **kwargs)
  File "/home/a401-2/anaconda3/envs/paddlegpu/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/a401-2/anaconda3/envs/paddlegpu/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/a401-2/anaconda3/envs/paddlegpu/lib/python3.8/site-packages/paddle/fluid/framework.py", line 534, in __impl__
    return func(*args, **kwargs)
  File "/home/a401-2/anaconda3/envs/paddlegpu/lib/python3.8/site-packages/paddle/optimizer/adamw.py", line 578, in step
    optimize_ops = self._apply_optimize(loss=None,
  File "/home/a401-2/anaconda3/envs/paddlegpu/lib/python3.8/site-packages/paddle/optimizer/optimizer.py", line 1166, in _apply_optimize
    optimize_ops = self._create_optimization_pass(
  File "/home/a401-2/anaconda3/envs/paddlegpu/lib/python3.8/site-packages/paddle/optimizer/optimizer.py", line 947, in _create_optimization_pass
    self._append_optimize_op(
  File "/home/a401-2/anaconda3/envs/paddlegpu/lib/python3.8/site-packages/paddle/optimizer/adamw.py", line 432, in _append_optimize_op
    lr = self._create_param_lr(param_and_grad)
  File "/home/a401-2/anaconda3/envs/paddlegpu/lib/python3.8/site-packages/paddle/optimizer/optimizer.py", line 668, in _create_param_lr
    return self._global_learning_rate() * param_lr
  File "/home/a401-2/anaconda3/envs/paddlegpu/lib/python3.8/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 256, in __impl__
    other_var = create_scalar(value=other_var,
  File "/home/a401-2/anaconda3/envs/paddlegpu/lib/python3.8/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 86, in create_scalar
    return create_tensor(value, dtype, shape=[1])
  File "/home/a401-2/anaconda3/envs/paddlegpu/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/a401-2/anaconda3/envs/paddlegpu/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 319, in __impl__
    return func(*args, **kwargs)
  File "/home/a401-2/anaconda3/envs/paddlegpu/lib/python3.8/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 75, in create_tensor
    out = _C_ops.full(shape, value, dtype,
ValueError: (InvalidArgument) full(): argument (position 2) must be int, float, bool or Tensor, but got NoneType (at /paddle/paddle/fluid/pybind/eager_utils.cc:1281)

```
代码在 https://github.com/PaddlePaddle/PaddleDetection/pull/8276

**Comment by lyuwenyu** [comment]
使用的paddle版本一样嘛

**Comment by Atlantisming** [comment]
> 使用的paddle版本一样嘛

都是 develop 版本，问题定位在了 transformer encoder 的部分，原因是在合入分支到 develop 版本时删除了逻辑相同的重复性代码，目前已经解决，只要原文件中有 encoder 部分的代码就不会出现这个报错，如果从 Deformable_transformer.py import 进来的话就会出现这个错误。具体原因尚不清楚。
