### ISSUE TITLE
导出maskrcnn训练的模型，infer_cfg.yml与自己的类不匹配

### ISSUE THREAD

**Issue by xxPete** [PaddlePaddle/PaddleDetection#8292]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

- 今天用paddle detection训练一个maskrcnn的模型，用的x2coco转换的数据集，配置文件中的数据集路径相对路径和绝对路径都试过，但是导出来的infer_cfg.yml的类别都是coco的80类标签，麻烦帮我看一下是哪个地方出问题了
```python
mode: paddle
draw_threshold: 0.5
metric: COCO
use_dynamic_shape: true
arch: RCNN
min_subgraph_size: 40
mask: true
Preprocess:
- interp: 2
  keep_ratio: true
  target_size:
  - 800
  - 1333
  type: Resize
- is_scale: true
  mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
  type: NormalizeImage
- type: Permute
- stride: -1
  type: PadStride
label_list:
- person
- bicycle
- car
- motorcycle
- airplane
- bus
- train
- truck
- boat
- traffic light
- fire hydrant
- stop sign
- parking meter
- bench
- bird
- cat
- dog
- horse
- sheep
- cow
- elephant
- bear
- zebra
- giraffe
- backpack
- umbrella
- handbag
- tie
- suitcase
- frisbee
- skis
- snowboard
- sports ball
- kite
- baseball bat
- baseball glove
- skateboard
- surfboard
- tennis racket
- bottle
- wine glass
- cup
- fork
- knife
- spoon
- bowl
- banana
- apple
- sandwich
- orange
- broccoli
- carrot
- hot dog
- pizza
- donut
- cake
- chair
- couch
- potted plant
- bed
- dining table
- toilet
- tv
- laptop
- mouse
- remote
- keyboard
- cell phone
- microwave
- oven
- toaster
- sink
- refrigerator
- book
- clock
- vase
- scissors
- teddy bear
- hair drier
- toothbrush
```

- 我的配置路径如下
```python
_BASE_: [
  'D:/Project/PaddleDetection/configs/datasets/bottle2.yml',
  'D:/Project/PaddleDetection/configs/runtime.yml',
  'D:/Project/PaddleDetection/configs/mask_rcnn/_base_/optimizer_1x.yml',
  'D:/Project/PaddleDetection/configs/mask_rcnn/_base_/mask_rcnn_r50.yml',
  'D:/Project/PaddleDetection/configs/mask_rcnn/_base_/mask_reader.yml',
]
weights: output/mask_rcnn_r50_1x_coco/model_final
```
-这是数据集的路径
```python
metric: COCO
num_classes: 3 

TrainDataset:
  name: COCODataSet
  image_dir: train #
  anno_path: annotations/instance_train.json #
  dataset_dir: dataset/bottle_demo
  data_fields: ['image', 'gt_bbox', 'gt_class', 'gt_poly', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: val #
  anno_path: annotations/instance_val.json #
  dataset_dir: dataset/bottle_demo

TestDataset:
  name: ImageFolder
  image_dir: val #
  anno_path: annotations/instance_val.json # also support txt (like VOC's label_list.txt) #
  dataset_dir: dataset/bottle_demo # if set, anno_path will be 'dataset_dir/anno_path'
```
- 这是数据集的路径
![image](https://github.com/PaddlePaddle/PaddleDetection/assets/98084551/8cd1ace5-5baf-4534-a1f6-10d52624ce3a)
- 在paddledetection的路径下使用命令行` python .\tools\train.py -c .\configs\mask_rcnn\bottle.yml `训练的，我不知道哪个地方出了问题

**Comment by lyuwenyu** [comment]
看下是不是get_categories默认走了coco?
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/ppdet/data/source/category.py

**Comment by xxPete** [comment]
> 看下是不是get_categories默认走了coco? https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/ppdet/data/source/category.py

我看了一下，训练时的类是对的，现在训练出来推理的时候报的错误如下
```python
[06/01 17:22:37] ppdet.data.source.category WARNING: anno_file 'None' is None or not set or not exist, please recheck TrainDataset/EvalDataset/TestDataset.anno_path, otherwise the default categories will be used by metric_type.
[06/01 17:22:37] ppdet.data.source.category WARNING: metric_type: COCO, load default categories of COCO.
  0%|                                                                                                                                                                                                            | 0/1 [00:00<?, ?it/s]W
0601 17:22:37.687211  7860 gpu_resources.cc:201] WARNING: device: . The installed Paddle is compiled with CUDNN 8.1, but CUDNN version in your machine is 8.0, which may cause serious incompatible bug. Please recompile or reinstall P
addle with compatible CUDNN version.
  0%|                                                                                                                                                                                                            | 0/1 [00:12<?, ?it/s]
Traceback (most recent call last):
  File ".\tools\infer.py", line 226, in <module>
    main()
  File ".\tools\infer.py", line 222, in main
    run(FLAGS, cfg)
  File ".\tools\infer.py", line 187, in run
    visualize=FLAGS.visualize)
  File "D:\Project\PaddleDetection\ppdet\engine\trainer.py", line 880, in predict
    outs = self.model(data)
  File "D:\Project\PaddleDetection\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Project\PaddleDetection\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Project\PaddleDetection\ppdet\modeling\architectures\meta_arch.py", line 75, in forward
    outs.append(self.get_pred())
  File "D:\Project\PaddleDetection\ppdet\modeling\architectures\mask_rcnn.py", line 133, in get_pred
    bbox_pred, bbox_num, mask_pred = self._forward()
  File "D:\Project\PaddleDetection\ppdet\modeling\architectures\mask_rcnn.py", line 119, in _forward
    origin_shape)
  File "D:\Project\PaddleDetection\ppdet\modeling\post_process.py", line 270, in __call__
    bboxes_i[:, 2:], im_h, im_w)
  File "D:\Project\PaddleDetection\ppdet\modeling\post_process.py", line 226, in paste_mask
    img_masks = F.grid_sample(masks, grid, align_corners=False)
  File "D:\Project\PaddleDetection\venv\lib\site-packages\paddle\nn\functional\vision.py", line 278, in grid_sample
    out = getattr(_C_ops, 'grid_sampler')(x, grid, *attrs)
SystemError: (Fatal) Operator grid_sampler raises an struct paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError:

Out of memory error on GPU 0. Cannot allocate 800.000000MB memory on GPU 0, 11.999390GB memory has been allocated and available memory is only 0.000000B.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model.

 (at ..\paddle\fluid\memory\allocation\cuda_allocator.cc:87)
. (at ..\paddle\fluid\imperative\tracer.cc:307)

```

**Comment by Kitzzaaa** [comment]
请问最后是怎么解决的？
