### ISSUE TITLE
尝试将mask_rcnn_r50_vd_fpn_2x的coco数据集读取换成voc数据集读取报错

### ISSUE THREAD

**Issue by liu824** [PaddlePaddle/PaddleDetection#830]
020-06-01 11:14:55,711-INFO: The 'num_classes'(number of classes) you set is 2, and 'with_background' in 'dataset' sets True.
So please note the actual number of categories is 1.
2020-06-01 11:14:56,151-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000100] in Optimizer will not take effect, and it will only be applied to other Parameters!
W0601 11:14:56.285560   428 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 9.0
W0601 11:14:56.290141   428 device_context.cc:260] device: 0, cuDNN Version: 7.3.
2020-06-01 11:14:59,402-WARNING: /home/aistudio/.cache/paddle/weights/ResNet50_vd_pretrained.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-06-01 11:14:59,720-WARNING: /home/aistudio/.cache/paddle/weights/ResNet50_vd_pretrained.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-06-01 11:14:59,728-WARNING: variable file [ /home/aistudio/.cache/paddle/weights/ResNet50_vd_pretrained/fc_0.b_0 /home/aistudio/.cache/paddle/weights/ResNet50_vd_pretrained/fc_0.w_0 ] not used
2020-06-01 11:15:01,387-INFO: places would be ommited when DataLoader is not iterable
2020-06-01 11:15:01,547-WARNING: recv endsignal from outq with errmsg[consumer[consumer-851-0] exits for reason[producer[producer-851] failed with error: ]]
2020-06-01 11:15:01,547-WARNING: recv endsignal from outq with errmsg[consumer[consumer-851-1] exits for reason[consumer[consumer-851-0] exits for reason[producer[producer-851] failed with error: ]]]
2020-06-01 11:15:01,547-WARNING: Your reader has raised an exception!
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1156, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1136, in __thread_main__
    for tensors in self._tensor_reader():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1206, in __tensor_reader_impl__
    for slots in paddle_reader():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 505, in __reader_creator__
    for item in reader():
  File "/home/aistudio/PaddleDetection-release-0.3/ppdet/data/reader.py", line 421, in _reader
    reader.reset()
  File "/home/aistudio/PaddleDetection-release-0.3/ppdet/data/parallel_map.py", line 259, in reset
    assert not self._exit, "cannot reset for already stopped dataset"
AssertionError: cannot reset for already stopped dataset

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "PaddleDetection-release-0.3/tools/train.py", line 366, in <module>
    main()
  File "PaddleDetection-release-0.3/tools/train.py", line 239, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1167, in _run_impl
    return_merged=return_merged)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 879, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1078, in _init_non_iterable
    attrs={'drop_last': self._drop_last})
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 976, in __init__
    self._init_non_iterable()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 608, in from_generator
    iterable, return_list, drop_last)
  File "/home/aistudio/PaddleDetection-release-0.3/ppdet/modeling/architectures/mask_rcnn.py", line 329, in build_inputs
    iterable=iterable) if use_dataloader else None
  File "PaddleDetection-release-0.3/tools/train.py", line 112, in main
    feed_vars, train_loader = model.build_inputs(**inputs_def)
  File "PaddleDetection-release-0.3/tools/train.py", line 366, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]

我主要更改了mask_rcnn_r50_vd_fpn_2x.yml和mask_fpn_reader.yml文件夹的配制。
mask_rcnn_r50_vd_fpn_2x.yml文件只改;
metric: VOC 
mask_fpn_reader.yml文件改动：
TrainReader:
  inputs_def:
    fields: ['image', 'im_info', 'im_id', 'gt_bbox', 'gt_class', 'is_crowd', 'gt_mask']
  dataset:
    !VOCDataSet
    anno_path: train.txt
    dataset_dir: PaddleDetection-release-0.3/dataset/Traffic_light_identification/train

**Comment by qingqing01** [comment]
@liu824 

关于在RCNN模型上用VOC数据，可以参考 https://github.com/PaddlePaddle/PaddleDetection/issues/787#issuecomment-634476062

但在[读取VOC源数据]( https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/ppdet/data/source/voc.py )时，没有读取分割的数据，所以直接用默认的`VOCDataSet`无法训练MaskRCNN的模型。

**Comment by liu824** [comment]
那应该如何做，转化为coco数据集吗？

**Comment by qingqing01** [comment]
@liu824 如果您要训练实例分割的话，需要转换成COCO数据格式。

**Comment by liu824** [comment]
我只是想试一下mask_rcnn的目标检测效果
