### ISSUE TITLE
'SharedMemoryMgr' object has no attribute '_allocator'

### ISSUE THREAD

**Issue by wusj18** [PaddlePaddle/PaddleDetection#834]
按照教程训练fruit数据集，报错'SharedMemoryMgr' object has no attribute '_allocator'，但是机器上还有40G空间的。

```
2020-06-01 17:35:20,953-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000500] in Optimizer will not take effect, and it will only be applied to other Parameters!
W0601 17:35:21.420003  8053 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 35, Driver API Version: 9.0, Runtime API Version: 9.0
W0601 17:35:21.422808  8053 device_context.cc:260] device: 0, cuDNN Version: 5.1.
W0601 17:35:22.815994  8053 device_context.h:155] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.3, but CUDNN version in your machine is 5.1, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
2020-06-01 17:35:23,185-WARNING: ./paddle/weights/yolov3_mobilenet_v1.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-06-01 17:35:23,618-WARNING: variable yolo_output.1.conv.bias not used
2020-06-01 17:35:23,618-WARNING: variable yolo_output.1.conv.weights not used
2020-06-01 17:35:23,618-WARNING: variable yolo_output.2.conv.bias not used
2020-06-01 17:35:23,618-WARNING: variable yolo_output.2.conv.weights not used
2020-06-01 17:35:23,619-WARNING: variable yolo_output.0.conv.bias not used
2020-06-01 17:35:23,619-WARNING: variable yolo_output.0.conv.weights not used
Traceback (most recent call last):
  File "tools/train.py", line 366, in <module>
    main()
  File "tools/train.py", line 203, in main
    devices_num=devices_num)
  File "/***/layout_detection/PaddleDetection/ppdet/data/reader.py", line 410, in create_reader
    reader = Reader(**cfg)()
  File "/***/layout_detection/PaddleDetection/ppdet/data/reader.py", line 263, in __init__
    use_process, memsize)
  File "/***/layout_detection/PaddleDetection/ppdet/data/parallel_map.py", line 86, in __init__
    self._setup()
  File "/***/layout_detection/PaddleDetection/ppdet/data/parallel_map.py", line 106, in _setup
    self._outq = Queue(bufsize, memsize=memsize)
  File "/***/layout_detection/PaddleDetection/ppdet/data/shared_queue/queue.py", line 63, in __init__
    capacity=memsize, pagesize=pagesize)
  File "/***/layout_detection/PaddleDetection/ppdet/data/shared_queue/sharedmemory.py", line 415, in __init__
    self._setup()
  File "/***/layout_detection/PaddleDetection/ppdet/data/shared_queue/sharedmemory.py", line 418, in _setup
    self._shared_mem = RawArray('c', self._cap)
  File "/***/python_paddle/lib/python3.6/multiprocessing/context.py", line 129, in RawArray
    return RawArray(typecode_or_type, size_or_initializer)
  File "/***/python_paddle/lib/python3.6/multiprocessing/sharedctypes.py", line 60, in RawArray
    obj = _new_value(type_)
  File "/***/python_paddle/lib/python3.6/multiprocessing/sharedctypes.py", line 40, in _new_value
    wrapper = heap.BufferWrapper(size)
  File "/***/python_paddle/lib/python3.6/multiprocessing/heap.py", line 248, in __init__
    block = BufferWrapper._heap.malloc(size)
  File "/***/python_paddle/lib/python3.6/multiprocessing/heap.py", line 230, in malloc
    (arena, start, stop) = self._malloc(size)
  File "/***/python_paddle/lib/python3.6/multiprocessing/heap.py", line 128, in _malloc
    arena = Arena(length)
  File "/***/python_paddle/lib/python3.6/multiprocessing/heap.py", line 77, in __init__
    f.write(zeros)
OSError: [Errno 28] No space left on device
Exception ignored in: <bound method SharedMemoryMgr.__del__ of <ppdet.data.shared_queue.sharedmemory.SharedMemoryMgr object at 0x7f1732470c50>>
Traceback (most recent call last):
  File "/***/layout_detection/PaddleDetection/ppdet/data/shared_queue/sharedmemory.py", line 524, in __del__
    if not self._released and not self._allocator.empty():
AttributeError: 'SharedMemoryMgr' object has no attribute '_allocator'

```

**Comment by qingqing01** [comment]
> OSError: [Errno 28] No space left on device

这个错误是像是本地磁盘不够。  另外，您使用的PaddleDetection版本是那个呢？ 建议再TrainReader里改下配置看下：

```
  mixup_epoch: -1
  worker_num: -1
  use_process: false
```

**Comment by wusj18** [comment]
本地40+GB应该够用吧，另外PaddleDetection是 release v0.3。

使用「worker_num: -1」和」「use_process: false」之后会报错说：
W0601 18:19:59.606346 26998 init.cc:216] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0601 18:19:59.606396 26998 init.cc:218] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0601 18:19:59.606403 26998 init.cc:221] The detail failure signal is:

W0601 18:19:59.606410 26998 init.cc:224] *** Aborted at 1591006799 (unix time) try "date -d @1591006799" if you are using GNU date ***
W0601 18:19:59.608932 26998 init.cc:224] PC: @                0x0 (unknown)
W0601 18:19:59.609477 26998 init.cc:224] *** SIGSEGV (@0x0) received by PID 26654 (TID 0x7f4f4ad34700) from PID 0; stack trace: ***
W0601 18:19:59.613369 26998 init.cc:224]     @     0x7f504b9bd160 (unknown)
W0601 18:19:59.615409 26998 init.cc:224]     @                0x0 (unknown)

**Comment by wusj18** [comment]
又试了一台硬盘余量300G的机器，也是这个错

**Comment by wusj18** [comment]
尝试把PaddleDetection版本回退到release v0.2，还是这个错。

**Comment by wusj18** [comment]
尝试PaddleDetection版本回退到release v0.2，加上worker_num: -1、use_process: false两句，解决了。感谢！

**Comment by heavengate** [comment]
可以跑下`free -h`看下，看报错原因是运行内存不够

**Comment by wusj18** [comment]
free -g 结果：
             total       used       free     shared    buffers     cached
Mem:           157         82         74          0          1         36
-/+ buffers/cache:         44        112
Swap:            0          0          0

**Comment by imistyrain** [comment]
df -h 和 df -i 都查过了，有的是空间；
free -m 显示有100多的G内存空闲；
和上面相同的是都没有swap分区，这是啥原因导致的呢？

**Comment by qingqing01** [comment]
@wusj18  参考这个 https://github.com/PaddlePaddle/PaddleDetection/issues/874#issuecomment-639229449 使用非共享内存的queue试下吧。
