### ISSUE TITLE
AttributeError: 'bytes' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Wisdom2wisdom** [PaddlePaddle/PaddleDetection#8347]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\D_installation_packet\Anaconda\installion_package\envs\ppyolo\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\D_installation_packet\Anaconda\installion_package\envs\ppyolo\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\ppyolo\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 217, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices,
  File "C:\D_installation_packet\Anaconda\installion_package\envs\ppyolo\lib\site-packages\paddle\fluid\dataloader\fetcher.py", line 125, in fetch
    data.append(self.dataset[idx])
  File "E:\executable_code\YOLO\ppyolo\PaddleDetection-release-2.6\ppdet\data\source\dataset.py", line 102, in __getitem__
    return self.transform(roidb)
  File "E:\executable_code\YOLO\ppyolo\PaddleDetection-release-2.6\ppdet\data\reader.py", line 65, in __call__
    raise e
  File "E:\executable_code\YOLO\ppyolo\PaddleDetection-release-2.6\ppdet\data\reader.py", line 59, in __call__
    data = f(data)
  File "E:\executable_code\YOLO\ppyolo\PaddleDetection-release-2.6\ppdet\data\transform\operators.py", line 105, in __call__
    sample = self.apply(sample, context)
  File "E:\executable_code\YOLO\ppyolo\PaddleDetection-release-2.6\ppdet\data\transform\operators.py", line 139, in apply
    elif sample['h'] != im.shape[0]:
AttributeError: 'bytes' object has no attribute 'shape'

### 复现环境 Environment

Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\D_installation_packet\Anaconda\installion_package\envs\ppyolo\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\D_installation_packet\Anaconda\installion_package\envs\ppyolo\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\D_installation_packet\Anaconda\installion_package\envs\ppyolo\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 217, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices,
  File "C:\D_installation_packet\Anaconda\installion_package\envs\ppyolo\lib\site-packages\paddle\fluid\dataloader\fetcher.py", line 125, in fetch
    data.append(self.dataset[idx])
  File "E:\executable_code\YOLO\ppyolo\PaddleDetection-release-2.6\ppdet\data\source\dataset.py", line 102, in __getitem__
    return self.transform(roidb)
  File "E:\executable_code\YOLO\ppyolo\PaddleDetection-release-2.6\ppdet\data\reader.py", line 65, in __call__
    raise e
  File "E:\executable_code\YOLO\ppyolo\PaddleDetection-release-2.6\ppdet\data\reader.py", line 59, in __call__
    data = f(data)
  File "E:\executable_code\YOLO\ppyolo\PaddleDetection-release-2.6\ppdet\data\transform\operators.py", line 105, in __call__
    sample = self.apply(sample, context)
  File "E:\executable_code\YOLO\ppyolo\PaddleDetection-release-2.6\ppdet\data\transform\operators.py", line 139, in apply
    elif sample['h'] != im.shape[0]:
AttributeError: 'bytes' object has no attribute 'shape'

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by todesti2** [comment]
我也存在这样的问题，请问您解决了吗

**Comment by syriacus99** [comment]
我也存在这样的问题，请问您解决了吗
