### ISSUE TITLE
导出ppyoloe模型出错

### ISSUE THREAD

**Issue by zhenhuamo** [PaddlePaddle/PaddleDetection#8373]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Traceback (most recent call last):
  File "tools/export_model.py", line 110, in <module>
    main()
  File "tools/export_model.py", line 106, in main
    run(FLAGS, cfg)
  File "tools/export_model.py", line 64, in run
    trainer = Trainer(cfg, mode='test')
  File "G:\PaddleDetection-release-2.6\ppdet\engine\trainer.py", line 86, in __init__
    self.dataset = self.cfg['{}Dataset'.format(capital_mode)] = create(
  File "G:\PaddleDetection-release-2.6\ppdet\core\workspace.py", line 292, in create
    return cls(**cls_kwargs)
  File "G:\PaddleDetection-release-2.6\ppdet\data\source\dataset.py", line 279, in __init__
    self.dataset = getattr(source, type)(**dataset_args)
AttributeError: module 'ppdet.data.source' has no attribute 'JPEGImages'

**Comment by lyuwenyu** [comment]
改config了嘛， 可以使用最新版本的代码试一下
