### ISSUE TITLE
Develop版本运行测试RT-DETR，运行命令python ppdet/modeling/tests/test_architectures.py时报错

### ISSUE THREAD

**Issue by LYKlyk** [PaddlePaddle/PaddleDetection#8389]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

======================================================================
ERROR: test_trainer (__main__.TestCascadeRCNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 35, in test_trainer
    trainer = ppdet.engine.Trainer(cfg, mode='test')
  File "/home/lyk/anaconda3/envs/paddle/lib/python3.8/site-packages/paddledet-2.5.0-py3.8.egg/ppdet/engine/trainer.py", line 88, in __init__
    self.model = create(cfg.architecture)
  File "/home/lyk/anaconda3/envs/paddle/lib/python3.8/site-packages/paddledet-2.5.0-py3.8.egg/ppdet/core/workspace.py", line 220, in create
    raise ValueError("The module {} is not registered".format(name))
ValueError: The module CascadeRCNN is not registered

======================================================================
ERROR: test_trainer (__main__.TestFasterRCNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 35, in test_trainer
    trainer = ppdet.engine.Trainer(cfg, mode='test')
  File "/home/lyk/anaconda3/envs/paddle/lib/python3.8/site-packages/paddledet-2.5.0-py3.8.egg/ppdet/engine/trainer.py", line 79, in __init__
    self.dataset = self.cfg['{}Dataset'.format(capital_mode)] = create(
  File "/home/lyk/anaconda3/envs/paddle/lib/python3.8/site-packages/paddledet-2.5.0-py3.8.egg/ppdet/core/workspace.py", line 220, in create
    raise ValueError("The module {} is not registered".format(name))
ValueError: The module TestDataset is not registered

======================================================================
ERROR: test_trainer (__main__.TestGFL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 35, in test_trainer
    trainer = ppdet.engine.Trainer(cfg, mode='test')
  File "/home/lyk/anaconda3/envs/paddle/lib/python3.8/site-packages/paddledet-2.5.0-py3.8.egg/ppdet/engine/trainer.py", line 79, in __init__
    self.dataset = self.cfg['{}Dataset'.format(capital_mode)] = create(
  File "/home/lyk/anaconda3/envs/paddle/lib/python3.8/site-packages/paddledet-2.5.0-py3.8.egg/ppdet/core/workspace.py", line 220, in create
    raise ValueError("The module {} is not registered".format(name))
ValueError: The module TestDataset is not registered

======================================================================
ERROR: test_trainer (__main__.TestMaskRCNN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 35, in test_trainer
    trainer = ppdet.engine.Trainer(cfg, mode='test')
  File "/home/lyk/anaconda3/envs/paddle/lib/python3.8/site-packages/paddledet-2.5.0-py3.8.egg/ppdet/engine/trainer.py", line 79, in __init__
    self.dataset = self.cfg['{}Dataset'.format(capital_mode)] = create(
  File "/home/lyk/anaconda3/envs/paddle/lib/python3.8/site-packages/paddledet-2.5.0-py3.8.egg/ppdet/core/workspace.py", line 220, in create
    raise ValueError("The module {} is not registered".format(name))
ValueError: The module TestDataset is not registered

======================================================================
ERROR: test_trainer (__main__.TestPicoDet)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 35, in test_trainer
    trainer = ppdet.engine.Trainer(cfg, mode='test')
  File "/home/lyk/anaconda3/envs/paddle/lib/python3.8/site-packages/paddledet-2.5.0-py3.8.egg/ppdet/engine/trainer.py", line 79, in __init__
    self.dataset = self.cfg['{}Dataset'.format(capital_mode)] = create(
  File "/home/lyk/anaconda3/envs/paddle/lib/python3.8/site-packages/paddledet-2.5.0-py3.8.egg/ppdet/core/workspace.py", line 220, in create
    raise ValueError("The module {} is not registered".format(name))
ValueError: The module TestDataset is not registered

======================================================================
ERROR: test_trainer (__main__.TestSSD)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 35, in test_trainer
    trainer = ppdet.engine.Trainer(cfg, mode='test')
  File "/home/lyk/anaconda3/envs/paddle/lib/python3.8/site-packages/paddledet-2.5.0-py3.8.egg/ppdet/engine/trainer.py", line 79, in __init__
    self.dataset = self.cfg['{}Dataset'.format(capital_mode)] = create(
  File "/home/lyk/anaconda3/envs/paddle/lib/python3.8/site-packages/paddledet-2.5.0-py3.8.egg/ppdet/core/workspace.py", line 220, in create
    raise ValueError("The module {} is not registered".format(name))
ValueError: The module TestDataset is not registered

======================================================================
ERROR: test_trainer (__main__.TestYolov3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ppdet/modeling/tests/test_architectures.py", line 35, in test_trainer
    trainer = ppdet.engine.Trainer(cfg, mode='test')
  File "/home/lyk/anaconda3/envs/paddle/lib/python3.8/site-packages/paddledet-2.5.0-py3.8.egg/ppdet/engine/trainer.py", line 79, in __init__
    self.dataset = self.cfg['{}Dataset'.format(capital_mode)] = create(
  File "/home/lyk/anaconda3/envs/paddle/lib/python3.8/site-packages/paddledet-2.5.0-py3.8.egg/ppdet/core/workspace.py", line 220, in create
    raise ValueError("The module {} is not registered".format(name))
ValueError: The module TestDataset is not registered

我安装的是develop版本，想要运行测试RT-DETR，但是在运行命令python ppdet/modeling/tests/test_architectures.py时报上述错误，请问该如何解决？

**Comment by lyuwenyu** [comment]
直接跑训练试一下能不能行
