### ISSUE TITLE
蒸馏报错

### ISSUE THREAD

**Issue by m00nLi** [PaddlePaddle/PaddleDetection#8395]
```
  File "/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 1234, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'PPYOLOEHead' object has no attribute 'distill_pairs'
```

**Comment by nemonameless** [comment]
请使用最新develop分支代码。报错请按模板提问以便排查谢谢
https://github.com/PaddlePaddle/PaddleDetection/issues/new?assignees=&labels=bug&projects=&template=1_bug-report.yml

**Comment by m00nLi** [comment]
# 环境
- OS Ubuntu 22.04
- CDUA 12.0
- CUDNN 8.4
- Python 3.9
- PaddlePaddle 2.4.2.post117
- PaddelDetection 2.6-develop
- PaddleSlim 2.4.1

使用ppyoloep-l蒸馏ppyoloep-m
```
python -m paddle.distributed.launch --gpus 0,1,2,3,4,5,6,7 \
tools/train.py \
--eval  --amp \
-c configs/ppyoloe/distill/ppyoloe_plus_crn_m_80e_coco_distill.yml \
--slim_config configs/slim/distill/ppyoloe_plus_distill_l_distill_m_coco.yml
```
运行后报错：
 ```
ppdet.engine INFO: Epoch: [0 ] [  0/179] learning_rate: 0.000000 loss: nan loss_cls: 2.017496 loss_iou: 0.425727 loss_dfl: 1.669147 loss_l1: 1.974291 det_loss: 3.916386 logits_loss: 7.839193 feat_loss: nan eta: 3 days, 23:08:57 batch_cost: 23.9202 data_cost: 15.0045 ips: 0.6689 images/s
Found inf or nan, current scale is: 1024.0, decrease to: 1024.0*0.5
Found inf or nan, current scale is: 512.0, decrease to: 512.0*0.5
Found inf or nan, current scale is: 256.0, decrease to: 256.0*0.5
Found inf or nan, current scale is: 128.0, decrease to: 128.0*0.5
Found inf or nan, current scale is: 64.0, decrease to: 64.0*0.5
Found inf or nan, current scale is: 32.0, decrease to: 32.0*0.5
Found inf or nan, current scale is: 16.0, decrease to: 16.0*0.5
Found inf or nan, current scale is: 8.0, decrease to: 8.0*0.5
Found inf or nan, current scale is: 4.0, decrease to: 4.0*0.5
Found inf or nan, current scale is: 2.0, decrease to: 2.0*0.5
Found inf or nan, current scale is: 1.0, decrease to: 1.0*0.5
Found inf or nan, current scale is: 0.5, decrease to: 0.5*0.5
Found inf or nan, current scale is: 0.25, decrease to: 0.25*0.5
Found inf or nan, current scale is: 0.125, decrease to: 0.125*0.5
Found inf or nan, current scale is: 0.0625, decrease to: 0.0625*0.5
Found inf or nan, current scale is: 0.03125, decrease to: 0.03125*0.5
Found inf or nan, current scale is: 0.015625, decrease to: 0.015625*0.5
Found inf or nan, current scale is: 0.0078125, decrease to: 0.0078125*0.5
Found inf or nan, current scale is: 0.00390625, decrease to: 0.00390625*0.5
Found inf or nan, current scale is: 0.001953125, decrease to: 0.001953125*0.5
Found inf or nan, current scale is: 0.0009765625, decrease to: 0.0009765625*0.5
Found inf or nan, current scale is: 0.00048828125, decrease to: 0.00048828125*0.5
Found inf or nan, current scale is: 0.000244140625, decrease to: 0.000244140625*0.5
Found inf or nan, current scale is: 0.0001220703125, decrease to: 0.0001220703125*0.5
Found inf or nan, current scale is: 6.103515625e-05, decrease to: 6.103515625e-05*0.5
Found inf or nan, current scale is: 3.0517578125e-05, decrease to: 3.0517578125e-05*0.5
Found inf or nan, current scale is: 1.52587890625e-05, decrease to: 1.52587890625e-05*0.5
Found inf or nan, current scale is: 7.62939453125e-06, decrease to: 7.62939453125e-06*0.5
Found inf or nan, current scale is: 3.814697265625e-06, decrease to: 3.814697265625e-06*0.5
Found inf or nan, current scale is: 1.9073486328125e-06, decrease to: 1.9073486328125e-06*0.5
Found inf or nan, current scale is: 9.5367431640625e-07, decrease to: 9.5367431640625e-07*0.5
Found inf or nan, current scale is: 4.76837158203125e-07, decrease to: 4.76837158203125e-07*0.5
Found inf or nan, current scale is: 2.384185791015625e-07, decrease to: 2.384185791015625e-07*0.5
Found inf or nan, current scale is: 1.1920928955078125e-07, decrease to: 1.1920928955078125e-07*0.5
Found inf or nan, current scale is: 5.960464477539063e-08, decrease to: 5.960464477539063e-08*0.5
Found inf or nan, current scale is: 2.9802322387695312e-08, decrease to: 2.9802322387695312e-08*0.5
Found inf or nan, current scale is: 1.4901161193847656e-08, decrease to: 1.4901161193847656e-08*0.5
Found inf or nan, current scale is: 7.450580596923828e-09, decrease to: 7.450580596923828e-09*0.5
...
Traceback (most recent call last):
  File "~/PaddleDetection/tools/train.py", line 204, in <module>
    main()
  File "~/PaddleDetection/tools/train.py", line 200, in main
    run(FLAGS, cfg)
  File "~/PaddleDetection/tools/train.py", line 153, in run
    trainer.train(FLAGS.eval)
  File "~/PaddleDetection/ppdet/engine/trainer.py", line 552, in train
    outputs = model(data)
  File "~/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "~/python3.9/site-packages/paddle/fluid/dygraph/parallel.py", line 774, in forward
    outputs = self._layers(*inputs, **kwargs)
  File "~/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "~/PaddleDetection/ppdet/slim/distill_model.py", line 342, in forward
    logits_loss, feat_loss = self.distill_loss(self.teacher_model,
  File "~/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "~/PaddleDetection/ppdet/slim/distill_loss.py", line 418, in forward
    loss_module(stu_feats[i], tea_feats[i], inputs))
  File "~/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "~/PaddleDetection/ppdet/slim/distill_loss.py", line 707, in forward
    mask_fg[i] = self.mask_value(
  File "~/PaddleDetection/ppdet/slim/distill_loss.py", line 630, in mask_value
    mask[xl:xr, yl:yr] = paddle.maximum(mask[xl:xr, yl:yr], value)
  File "~/python3.9/site-packages/paddle/tensor/math.py", line 944, in maximum
    return _C_ops.maximum(x, y)
RuntimeError: (PreconditionNotMet) The meta data must be valid when call the mutable data function. (at /paddle/paddle/phi/core/dense_tensor.cc:111)

```
第一轮学习率几乎是0了，但是loss还是nan

**Comment by m00nLi** [comment]
关闭amp混合精度训练，仍然报上述的错误

**Comment by nemonameless** [comment]
看nan的loss，可以关闭feature蒸馏，设置为false
https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/slim/distill/ppyoloe_plus_distill_l_distill_m.yml#L48
训的数据集应该不是coco吧？量级太小了容易过拟合。而且自定义数据集蒸馏，你的teacher权重需要是自己数据集训完后的权重，而不是coco训完的权重。

**Comment by m00nLi** [comment]
好的，我再试试，是训练自己的数据

**Comment by m00nLi** [comment]
使用自己的数据已经训练完YOLOEP-L模型，使用L蒸馏M，8卡 batch-size 16, 训练了几个batch后报错, Loss看上去是正常的：

```
[07/13 12:54:26] ppdet.engine INFO: Epoch: [0] [   0/2000] learning_rate: 0.000000 loss: 0.966462 loss_cls: 1.888785 loss_iou: 0.080378 loss_dfl: 0.369520 loss_l1: 0.116490 det_loss: 2.274491 logits_loss: 4.909387 feat_loss: 0.547817 eta: 51 days, 10:23:58 batch_cost: 25.8603 data_cost: 18.0063 ips: 0.4640 images/s
LAUNCH INFO 2023-07-13 13:14:47,491 Pod failed
[2023-07-13 13:14:47,491] [    INFO] controller.py:109 - Pod failed
LAUNCH ERROR 2023-07-13 13:14:47,491 Container failed !!!

Traceback (most recent call last):
  File "~/PaddleDetection/tools/train.py", line 204, in <module>
    main()
  File "~/PaddleDetection/tools/train.py", line 200, in main
    run(FLAGS, cfg)
  File "~/PaddleDetection/tools/train.py", line 153, in run
    trainer.train(FLAGS.eval)
  File "~/PaddleDetection/ppdet/engine/trainer.py", line 573, in train
    outputs = model(data)
  File "anaconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "anaconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/parallel.py", line 774, in forward
    outputs = self._layers(*inputs, **kwargs)
  File "anaconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "~/PaddleDetection/ppdet/slim/distill_model.py", line 342, in forward
    logits_loss, feat_loss = self.distill_loss(self.teacher_model,
  File "anaconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "~/PaddleDetection/ppdet/slim/distill_loss.py", line 418, in forward
    loss_module(stu_feats[i], tea_feats[i], inputs))
  File "anaconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "~/PaddleDetection/ppdet/slim/distill_loss.py", line 707, in forward
    mask_fg[i] = self.mask_value(
  File "~/PaddleDetection/ppdet/slim/distill_loss.py", line 630, in mask_value
    mask[xl:xr, yl:yr] = paddle.maximum(mask[xl:xr, yl:yr], value)
  File "anaconda3/lib/python3.9/site-packages/paddle/tensor/math.py", line 944, in maximum
    return _C_ops.maximum(x, y)
RuntimeError: (PreconditionNotMet) The meta data must be valid when call the mutable data function. (at /paddle/paddle/phi/core/dense_tensor.cc:111)
```

**Comment by lyuwenyu** [comment]
还有问题嘛
