### ISSUE TITLE
输入单视频可以使用DeepSort 来实现REID 么？

### ISSUE THREAD

**Issue by JialiGithub** [PaddlePaddle/PaddleDetection#8447]
对一段视频运行Enable REID 的行人检测（运行MOT 时会存在行人被遮挡，再次出现时，ID被更新，造成重复计数。为缓解这个问题，尝试使用REID）。
在配置文件PaddleDetection/deploy/pipeline/config/tracker_config.yml 中写明“type: BOTSORTTracker” 可以正常运行，并实现检测和结果可视化；但是将type更改为：“type: DeepSORTTracker” 就会报下边的错误：

Traceback (most recent call last):
  File "deploy/pipeline/pipeline.py", line 1331, in <module>
    main()
  File "deploy/pipeline/pipeline.py", line 1318, in main
    pipeline.run_multithreads()
  File "deploy/pipeline/pipeline.py", line 179, in run_multithreads
    self.predictor.run(self.input)
  File "deploy/pipeline/pipeline.py", line 534, in run
    self.predict_video(input, thread_idx=thread_idx)
  File "deploy/pipeline/pipeline.py", line 757, in predict_video
    res = self.mot_predictor.predict_image(
  File "/mnt/workspace/xinluo/PaddleDetection/deploy/pptracking/python/mot_sde_infer.py", line 563, in predict_image
    tracking_outs = self.tracking(det_result)
  File "/mnt/workspace/xinluo/PaddleDetection/deploy/pptracking/python/mot_sde_infer.py", line 319, in tracking
    online_targets = self.tracker.update(pred_dets, pred_embs)
  File "/mnt/workspace/xinluo/PaddleDetection/deploy/pptracking/python/mot/tracker/deepsort_tracker.py", line 105, in update
    for tlwh, score, feat, cls_id in zip(pred_tlwhs, pred_scores,
TypeError: 'NoneType' object is not iterable

想请问为什么会出现这个问题，以及应该怎么解？
版本信息：
paddlepaddle-gpu==2.4.2

**Comment by JialiGithub** [comment]
对一段视频运行Enable REID 的行人检测（运行MOT 时会存在行人被遮挡，再次出现时，ID被更新，造成重复计数。为缓解这个问题，尝试使用REID）。
在配置文件PaddleDetection/deploy/pipeline/config/tracker_config.yml 中写明“type: BOTSORTTracker” 可以正常运行，并实现检测和结果可视化；但是将type更改为：“type: DeepSORTTracker” 就会报下边的错误：

Traceback (most recent call last):
File "deploy/pipeline/pipeline.py", line 1331, in
main()
File "deploy/pipeline/pipeline.py", line 1318, in main
pipeline.run_multithreads()
File "deploy/pipeline/pipeline.py", line 179, in run_multithreads
self.predictor.run(self.input)
File "deploy/pipeline/pipeline.py", line 534, in run
self.predict_video(input, thread_idx=thread_idx)
File "deploy/pipeline/pipeline.py", line 757, in predict_video
res = self.mot_predictor.predict_image(
File "/mnt/workspace/xinluo/PaddleDetection/deploy/pptracking/python/mot_sde_infer.py", line 563, in predict_image
tracking_outs = self.tracking(det_result)
File "/mnt/workspace/xinluo/PaddleDetection/deploy/pptracking/python/mot_sde_infer.py", line 319, in tracking
online_targets = self.tracker.update(pred_dets, pred_embs)
File "/mnt/workspace/xinluo/PaddleDetection/deploy/pptracking/python/mot/tracker/deepsort_tracker.py", line 105, in update
for tlwh, score, feat, cls_id in zip(pred_tlwhs, pred_scores,
TypeError: 'NoneType' object is not iterable

想请问为什么会出现这个问题，以及应该怎么解？
版本信息：
paddlepaddle-gpu==2.4.2

**Comment by lyuwenyu** [comment]
这个你换的tracker的返回值有none吧 可以确认一下

**Comment by columbia617** [comment]
1. #https://github.com/PaddlePaddle/PaddleDetection/issues/6740#issuecomment-1226679189
2. 
![image](https://github.com/user-attachments/assets/c02b54f9-f245-4cb4-a3b3-068468c7a348)
多处都出现推荐MTMCT任务使用deepsort跟踪，但是使用之后就会出现上面的报错
