### ISSUE TITLE
Picodet在mosaic数据增强下，蒸馏训练出现BUG

### ISSUE THREAD

**Issue by GuoQuanhao** [PaddlePaddle/PaddleDetection#8448]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

```yaml
TrainReader:
  sample_transforms:
  - Decode: {}
  - Mosaic:
      prob: 1.0
      input_dim: [864, 608]
      degrees: [-10, 10]
      scale: [0.1, 2.0]
      shear: [-2, 2]
      translate: [-0.1, 0.1]
      enable_mixup: True
  batch_transforms:
  - BatchRandomResize: {target_size: [[832, 576], [864, 608], [890, 640]], random_size: True, random_interp: True, keep_ratio: False}
  - NormalizeImage: {is_scale: true, mean: [0.95803734, 0.9582161, 0.95844575], std: [0.1263065, 0.12556979, 0.12469532]}
  - Permute: {}
  - PadGT: {}
  batch_size: 32
  mosaic_epoch: 180
  shuffle: true
  drop_last: false
  use_shared_memory: true
```
出现如下报错
```
[07/18 15:58:40] ppdet.data.source.coco INFO: Load [396 samples valid, 0 samples invalid] in file cluster_dataset/layout_analysis_500_by_layout/annotations/train.json.
Traceback (most recent call last):
  File "tools/train.py", line 202, in <module>
    main()
  File "tools/train.py", line 198, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 151, in run
    trainer.train(FLAGS.eval)
  File "/home/aistudio/PaddleDetection/ppdet/engine/trainer.py", line 537, in train
    outputs = model(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleDetection/ppdet/slim/distill_model.py", line 143, in forward
    t_neck_feats[idx], inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleDetection/ppdet/slim/distill_loss.py", line 709, in forward
    wmax[i][j] + 1, area_recip[0][j])
  File "/home/aistudio/PaddleDetection/ppdet/slim/distill_loss.py", line 630, in mask_value
    mask[xl:xr, yl:yr] = paddle.maximum(mask[xl:xr, yl:yr], value)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/math.py", line 944, in maximum
    return _C_ops.maximum(x, y)
RuntimeError: (PreconditionNotMet) The meta data must be valid when call the mutable data function. (at /paddle/paddle/phi/core/dense_tensor.cc:111)
```
进一步发现，`ppdet/slim/distill_loss.py`中`mask_value`函数在实现`mask[xl:xr, yl:yr]`时，`xl`的以及`yl`的大小有时会超过`mask.shape`，导致`mask[xl:xr, yl:yr]`的某一维度出现零，如`mask[xl:xr, yl:yr].shape=[10, 0]`这种，导致`maximum` API出现问题，为了解决这个问题，对705行进行如下简单修改
```python
for j in range(len(gt_bboxes[i])):
    if (gt_bboxes[i][j].sum() > 0) and (wmin[i][j].item() < mask_fg[i].shape[1]) and (hmin[i][j].item() < mask_fg[i].shape[0]):
        mask_fg[i] = self.mask_value(
            mask_fg[i], hmin[i][j], hmax[i][j] + 1, wmin[i][j],
            wmax[i][j] + 1, area_recip[0][j])
```
但是不知道这种简单的修改方式是否会影响模型性能

### 复现环境 Environment

环境：利用的AIStudio平台
版本：PaddleDetection==2.6

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by luooluo** [comment]
请问这样修改后训练有影响吗

**Comment by GuoQuanhao** [comment]
能跑通，并且能得到正常的训练推理结果，但是不知道会不会造成错误的训练情况
