### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by FrankMMMMMM** [PaddlePaddle/PaddleDetection#8450]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

您好

我按照安装文档进行PaddleDetection安装（PaddlePaddle==2.5.2）并进行测试通过

我按照（[https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.6/deploy/pptracking/python#4-%E8%BD%A6%E8%BE%86%E8%B7%A8%E9%95%9C%E5%A4%B4%E8%B7%9F%E8%B8%AA%E6%A8%A1%E5%9E%8B%E5%AF%BC%E5%87%BA%E5%92%8C%E9%A2%84%E6%B5%8B）的步骤运行代码，除tracker外没有更改任何地方。但是出现如下错误，该如何解决？](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.6/deploy/pptracking/python#4-%E8%BD%A6%E8%BE%86%E8%B7%A8%E9%95%9C%E5%A4%B4%E8%B7%9F%E8%B8%AA%E6%A8%A1%E5%9E%8B%E5%AF%BC%E5%87%BA%E5%92%8C%E9%A2%84%E6%B5%8B%EF%BC%89%E7%9A%84%E6%AD%A5%E9%AA%A4%E8%BF%90%E8%A1%8C%E4%BB%A3%E7%A0%81%EF%BC%8C%E9%99%A4tracker%E5%A4%96%E6%B2%A1%E6%9C%89%E6%9B%B4%E6%94%B9%E4%BB%BB%E4%BD%95%E5%9C%B0%E6%96%B9%E3%80%82%E4%BD%86%E6%98%AF%E5%87%BA%E7%8E%B0%E5%A6%82%E4%B8%8B%E9%94%99%E8%AF%AF%EF%BC%8C%E8%AF%A5%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3%EF%BC%9F)

我在RTX 2080 Ti(11GB) 上运行代码，第一次成功运行，第二次出现以下错误（与第一次运行方式一致、且除输出目录外没有任何其他更改）

“
Traceback (most recent call last):
File "deploy/pptracking/python/mot_sde_infer.py", line 952, in
main()
File "deploy/pptracking/python/mot_sde_infer.py", line 921, in main
detector.predict_mtmct(FLAGS.mtmct_dir, mtmct_cfg)
File "deploy/pptracking/python/mot_sde_infer.py", line 865, in predict_mtmct
roi_dir=roi_dir)
File "/home/aistudio/MTMCT/PaddleDetection-release-2.6/deploy/pptracking/python/mot/mtmct/postprocess.py", line 148, in gen_res
cid = scene_cluster[idx]
IndexError: list index out of range
”

![image](https://github.com/PaddlePaddle/PaddleDetection/assets/92253265/4a137578-358e-40a3-81e2-18ba3c908f95)

**Comment by oushilu** [comment]
请问解决了吗，遇到了同样的问题

**Comment by lyuwenyu** [comment]
是最新的ppdet代码嘛

**Comment by Totoro-wen** [comment]
> 是最新的ppdet代码嘛

我也遇到了相同的问题，采用的是最新的ppdet最新的代码

**Comment by zearo-github** [comment]
我也是同样的问题，scene_cluster和mot_list_breaks长度不一致，如果简单的跳过不匹配的索引：
```
def gen_res(output_dir_filename,
            scene_cluster,
            map_tid,
            mot_list_breaks,
            use_roi=False,
            roi_dir=''):
    f_w = open(output_dir_filename, 'w')
    for idx, mot_feature in enumerate(mot_list_breaks):
        if idx >= len(scene_cluster):
            print(f"Index {idx} is out of range for scene_cluster with length {len(scene_cluster)}")
            continue  # 跳过不匹配的索引
        cid = scene_cluster[idx]
```
会导致最后绘制的检测框偏离目标：
![00091](https://github.com/user-attachments/assets/b0d3a30a-d97e-4a76-a158-772cfbff5368)

大家有什么好办法吗？

**Comment by zearo-github** [comment]
我找到真正的原因和解决办法了：
在第一次运行前，PaddleDetection/mtmct-demo中只有c004.mp4、c003.mp4，运行正常，在第一次运行完之后这个文件夹中会出现拆帧后的 图片文件夹c004、c003

在第二次运行的时候，deploy/pptracking/python/mot_sde_infer.py的798 行 <span style="color: #0000ff;">def</span> <span style="color: #795e26;">predict_mtmct</span><span style="color: #3b3b3b;">(</span><span style="color: #001080;">detector</span><span style="color: #3b3b3b;">,</span> <span style="color: #001080;">reid_model</span><span style="color: #3b3b3b;">,</span> <span style="color: #001080;">mtmct_dir</span><span style="color: #3b3b3b;">,</span> <span style="color: #001080;">mtmct_cfg</span><span style="color: #3b3b3b;">):函数中，</span>

<span style="color: #3b3b3b;"><span style="color: #001080;">scene_cluster</span></span>和第一次一样，还是两个成员，[3, 4]

但是，用于生成<span style="color: #001080;">mot_list_breaks的循环：831 行 <span style="color: #af00db;">for</span> <span style="color: #001080;">seq</span> <span style="color: #af00db;">in</span> <span style="color: #001080;">seqs</span><span style="color: #3b3b3b;">: 却有了四个成员：['c003', 'c003.mp4', 'c004', 'c004.mp4'] ，这就造成了gen_res中scene_cluster、mot_list_breaks长度不匹配的问题，导致了错误：IndexError: list index out of range

解决办法很简单，运行第二遍的时候删除图片文件夹c004、c003就可以了
