### ISSUE TITLE
使用res50vd-dcn-db-iouloss-object365 报错

### ISSUE THREAD

**Issue by soldier828** [PaddlePaddle/PaddleDetection#846]
辛苦帮看一下bug可能在什么位置，看不懂。。。
我得coco数据类别22

```
Traceback (most recent call last):
  File "tools/train_v1.py", line 364, in <module>
    main()
  File "tools/train_v1.py", line 129, in main
    train_fetches = model.train(feed_vars)
  File "/ssd1/xubokun/0312_ppdet17/PaddleDetection/ppdet/modeling/architectures/yolov3.py", line 156, in train
    return self.build(feed_vars, mode='train')
  File "/ssd1/xubokun/0312_ppdet17/PaddleDetection/ppdet/modeling/architectures/yolov3.py", line 85, in build
    gt_score, targets)
  File "/ssd1/xubokun/0312_ppdet17/PaddleDetection/ppdet/modeling/anchor_heads/yolo_head.py", line 285, in get_loss
    self.prefix_name)
  File "/ssd1/xubokun/0312_ppdet17/PaddleDetection/ppdet/modeling/losses/yolo_loss.py", line 59, in __call__
    mask_anchors, self._ignore_thresh)
  File "/ssd1/xubokun/0312_ppdet17/PaddleDetection/ppdet/modeling/losses/yolo_loss.py", line 122, in _get_fine_grained_loss
    num_classes)
  File "/ssd1/xubokun/0312_ppdet17/PaddleDetection/ppdet/modeling/losses/yolo_loss.py", line 240, in _split_output
    clss, axis=1), perm=[0, 1, 3, 4, 2])
  File "/home/users/xubokun/xubokun/0312_ppdet17/small_pytorch10/python_368_gcc5_torch101/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 9166, in stack
    attrs={'axis': axis})
  File "/home/users/xubokun/xubokun/0312_ppdet17/small_pytorch10/python_368_gcc5_torch101/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/users/xubokun/xubokun/0312_ppdet17/small_pytorch10/python_368_gcc5_torch101/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/users/xubokun/xubokun/0312_ppdet17/small_pytorch10/python_368_gcc5_torch101/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1880, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::StackOp::InferShape(paddle::framework::InferShapeContext*) const
3   paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/users/xubokun/xubokun/0312_ppdet17/small_pytorch10/python_368_gcc5_torch101/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/users/xubokun/xubokun/0312_ppdet17/small_pytorch10/python_368_gcc5_torch101/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/users/xubokun/xubokun/0312_ppdet17/small_pytorch10/python_368_gcc5_torch101/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 9166, in stack
    attrs={'axis': axis})
  File "/ssd1/xubokun/0312_ppdet17/PaddleDetection/ppdet/modeling/losses/yolo_loss.py", line 240, in _split_output
    clss, axis=1), perm=[0, 1, 3, 4, 2])
  File "/ssd1/xubokun/0312_ppdet17/PaddleDetection/ppdet/modeling/losses/yolo_loss.py", line 122, in _get_fine_grained_loss
    num_classes)
  File "/ssd1/xubokun/0312_ppdet17/PaddleDetection/ppdet/modeling/losses/yolo_loss.py", line 59, in __call__
    mask_anchors, self._ignore_thresh)
  File "/ssd1/xubokun/0312_ppdet17/PaddleDetection/ppdet/modeling/anchor_heads/yolo_head.py", line 285, in get_loss
    self.prefix_name)
  File "/ssd1/xubokun/0312_ppdet17/PaddleDetection/ppdet/modeling/architectures/yolov3.py", line 85, in build
    gt_score, targets)
  File "/ssd1/xubokun/0312_ppdet17/PaddleDetection/ppdet/modeling/architectures/yolov3.py", line 156, in train
    return self.build(feed_vars, mode='train')
  File "tools/train_v1.py", line 129, in main
    train_fetches = model.train(feed_vars)
  File "tools/train_v1.py", line 364, in <module>
    main()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: Dims of all Inputs(X) must be the same, but received input 2 dim is:-1, 21, -1, -1 not equal to input 0 dim:-1, 22, -1, -1.
  [Hint: Expected input_dims[i] == input_dims[0], but received input_dims[i]:-1, 21, -1, -1 != input_dims[0]:-1, 22, -1, -1.] at (/paddle/paddle/fluid/operators/stack_op.cc:46)
  [operator < stack > error]
```

**Comment by heavengate** [comment]
配置文件里面的`num_classes`修改了么，看着像是`num_classes`配置和实际数据集里的类别数不一致

**Comment by soldier828** [comment]
> 配置文件里面的`num_classes`修改了么，看着像是`num_classes`配置和实际数据集里的类别数不一致

改了诶。
![image](https://user-images.githubusercontent.com/10766225/83493238-0d8d8300-a4e7-11ea-9f3f-dbf502f8a4ff.png)

**Comment by heavengate** [comment]
是不是实际数据集里面只有21类，除了数据集还有修改啥么，看报错就是有的地方`num_classes`配置是21，有的地方是22
```
InvalidArgumentError: Dims of all Inputs(X) must be the same, but received input 2 dim is:-1, 21, -1, -1 not equal to input 0 dim:-1, 22, -1, -1.
```
