### ISSUE TITLE
Error: /paddle/paddle/phi/kernels/funcs/gather.cu.h:68

### ISSUE THREAD

**Issue by guchenqionguai** [PaddlePaddle/PaddleDetection#8468]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

换了好几个coco格式的数据集，完全按照操作手册来的，都是在训练过程中的第30轮报这个错误

Error: /paddle/paddle/phi/kernels/funcs/gather.cu.h:68 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [4] and greater than or equal to 0, but received [0]
Error: /paddle/paddle/phi/kernels/funcs/gather.cu.h:68 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [4] and greater than or equal to 0, but received [0]
Error: /paddle/paddle/phi/kernels/funcs/gather.cu.h:68 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [4] and greater than or equal to 0, but received [0]
Error: /paddle/paddle/phi/kernels/funcs/gather.cu.h:68 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [4] and greater than or equal to 0, but received [0]
Traceback (most recent call last):
  File "/tmp/PaddleDetection-release-2.6/tools/train.py", line 202, in <module>
    main()
  File "/tmp/PaddleDetection-release-2.6/tools/train.py", line 198, in main
    run(FLAGS, cfg)
  File "/tmp/PaddleDetection-release-2.6/tools/train.py", line 151, in run
    trainer.train(FLAGS.eval)
  File "/tmp/PaddleDetection-release-2.6/ppdet/engine/trainer.py", line 516, in train
    outputs = model(data)
  File "/root/miniconda3/envs/paddle/lib/python3.10/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/tmp/PaddleDetection-release-2.6/ppdet/modeling/architectures/meta_arch.py", line 60, in forward
    out = self.get_loss()
  File "/tmp/PaddleDetection-release-2.6/ppdet/modeling/architectures/yolo.py", line 147, in get_loss
    return self._forward()
  File "/tmp/PaddleDetection-release-2.6/ppdet/modeling/architectures/yolo.py", line 93, in _forward
    yolo_losses = self.yolo_head(neck_feats, self.inputs)
  File "/root/miniconda3/envs/paddle/lib/python3.10/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/tmp/PaddleDetection-release-2.6/ppdet/modeling/heads/ppyoloe_head.py", line 264, in forward
    return self.forward_train(feats, targets, aux_pred)
  File "/tmp/PaddleDetection-release-2.6/ppdet/modeling/heads/ppyoloe_head.py", line 198, in forward_train
    return self.get_loss([
  File "/tmp/PaddleDetection-release-2.6/ppdet/modeling/heads/ppyoloe_head.py", line 417, in get_loss
    self.assigner(
  File "/root/miniconda3/envs/paddle/lib/python3.10/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/miniconda3/envs/paddle/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/root/miniconda3/envs/paddle/lib/python3.10/site-packages/paddle/fluid/dygraph/base.py", line 375, in _decorate_function
    return func(*args, **kwargs)
  File "/tmp/PaddleDetection-release-2.6/ppdet/modeling/assigners/task_aligned_assigner.py", line 148, in forward
    is_in_topk = gather_topk_anchors(
  File "/tmp/PaddleDetection-release-2.6/ppdet/modeling/assigners/utils.py", line 105, in gather_topk_anchors
    return is_in_topk * topk_mask
  File "/root/miniconda3/envs/paddle/lib/python3.10/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 304, in __impl__
    return math_op(self, other_var, -1)
OSError: (External) CUDA error(719), unspecified launch failure. 
  [Hint: Please search for the error code(719) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:259)

**Comment by Plusmile** [comment]
你好，有什么进展吗？我报一样的错

**Comment by guchenqionguai** [comment]
> 你好，有什么进展吗？我报一样的错
还没解决，已经换模型了

**Comment by Plusmile** [comment]
把配置文件的，frozen啥啥改为false即可

---Original---
From: ***@***.***&gt;
Date: Sun, Sep 10, 2023 10:09 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [PaddlePaddle/PaddleDetection] Error:/paddle/paddle/phi/kernels/funcs/gather.cu.h:68 (Issue #8468)




  
你好，有什么进展吗？我报一样的错
 还没解决，已经换模型了

**Comment by HuangJi1019** [comment]
请问具体怎么修改呢？

> 把配置文件的，frozen啥啥改为false即可
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Sun, Sep 10, 2023 10:09 AM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [PaddlePaddle/PaddleDetection] Error:/paddle/paddle/phi/kernels/funcs/gather.cu.h:68 (Issue #8468) 你好，有什么进展吗？我报一样的错 还没解决，已经换模型了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

**Comment by kankj** [comment]
我找到了这篇问答[https://gitee.com/paddlepaddle/PaddleDetection/issues/I66CA2](url)，里面说是datasets中的num_classes数量配置错误导致的
