### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by felixgalaxy** [PaddlePaddle/PaddleDetection#849]
![image](https://user-images.githubusercontent.com/49911457/83490209-32332c00-a4e2-11ea-9f62-837561657777.png)
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]

**Comment by jerrywgz** [comment]
可以把完整log发下吗，这个只能看出是reader部分的问题

**Comment by felixgalaxy** [comment]
> 可以把完整log发下吗，这个只能看出是reader部分的问题

您好，整个工程这样的
2020-06-02 14:50:00,034-INFO: fail to map op [ResizeImage_f96a2d] with error: ResizeImage_f96a2d: min size of image is 0 and stack:
Traceback (most recent call last):
  File "/public/home/felix/myproject/Paddle/PaddleDetection/ppdet/data/reader.py", line 45, in __call__
    data = f(data, ctx)
  File "/public/home/felix/myproject/Paddle/PaddleDetection/ppdet/data/transform/operators.py", line 291, in __call__
    raise ZeroDivisionError('{}: min size of image is 0'.format(self))
ZeroDivisionError: ResizeImage_f96a2d: min size of image is 0

2020-06-02 14:50:00,037-WARNING: recv endsignal from outq with errmsg[consumer[consumer-b18-0] failed to map with error:[ResizeImage_f96a2d: min size of image is 0]]
2020-06-02 14:50:01,561-INFO: fail to map op [RandomExpand_d0ffaa] with error: could not broadcast input array from shape (1920,1080,3) into shape (1080,1920,3) and stack:
Traceback (most recent call last):
  File "/public/home/felix/myproject/Paddle/PaddleDetection/ppdet/data/reader.py", line 45, in __call__
    data = f(data, ctx)
  File "/public/home/felix/myproject/Paddle/PaddleDetection/ppdet/data/transform/operators.py", line 1268, in __call__
    canvas[y:y + height, x:x + width, :] = img.astype(np.uint8)
ValueError: could not broadcast input array from shape (1920,1080,3) into shape (1080,1920,3)

2020-06-02 14:50:01,566-WARNING: recv endsignal from outq with errmsg[consumer[consumer-b18-2] failed to map with error:[could not broadcast input array from shape (1920,1080,3) into shape (1080,1920,3)]]
2020-06-02 14:50:02,033-INFO: fail to map op [RandomExpand_d0ffaa] with error: could not broadcast input array from shape (1920,1080,3) into shape (1080,1920,3) and stack:
Traceback (most recent call last):
  File "/public/home/felix/myproject/Paddle/PaddleDetection/ppdet/data/reader.py", line 45, in __call__
    data = f(data, ctx)
  File "/public/home/felix/myproject/Paddle/PaddleDetection/ppdet/data/transform/operators.py", line 1268, in __call__
    canvas[y:y + height, x:x + width, :] = img.astype(np.uint8)
ValueError: could not broadcast input array from shape (1920,1080,3) into shape (1080,1920,3)

2020-06-02 14:50:02,038-WARNING: recv endsignal from outq with errmsg[consumer[consumer-b18-1] failed to map with error:[could not broadcast input array from shape (1920,1080,3) into shape (1080,1920,3)]]
2020-06-02 14:50:07,211-INFO: fail to map op [RandomExpand_d0ffaa] with error: could not broadcast input array from shape (1920,1080,3) into shape (1080,1920,3) and stack:
Traceback (most recent call last):
  File "/public/home/felix/myproject/Paddle/PaddleDetection/ppdet/data/reader.py", line 45, in __call__
    data = f(data, ctx)
  File "/public/home/felix/myproject/Paddle/PaddleDetection/ppdet/data/transform/operators.py", line 1268, in __call__
    canvas[y:y + height, x:x + width, :] = img.astype(np.uint8)
ValueError: could not broadcast input array from shape (1920,1080,3) into shape (1080,1920,3)

2020-06-02 14:50:07,215-WARNING: recv endsignal from outq with errmsg[consumer[consumer-b18-6] failed to map with error:[could not broadcast input array from shape (1920,1080,3) into shape (1080,1920,3)]]
2020-06-02 14:50:08,063-WARNING: recv endsignal from outq with errmsg[consumer[consumer-b18-7] exits for reason[consumer[consumer-b18-0] failed to map with error:[ResizeImage_f96a2d: min size of image is 0]]]
2020-06-02 14:50:08,376-INFO: iter: 0, lr: 0.001000, 'loss': '26.717461', time: 0.304, eta: 2:21:52
2020-06-02 14:50:08,666-WARNING: recv endsignal from outq with errmsg[consumer[consumer-b18-4] exits for reason[consumer[consumer-b18-2] failed to map with error:[could not broadcast input array from shape (1920,1080,3) into shape (1080,1920,3)]]]
2020-06-02 14:50:09,151-WARNING: recv endsignal from outq with errmsg[consumer[consumer-b18-5] exits for reason[consumer[consumer-b18-1] failed to map with error:[could not broadcast input array from shape (1920,1080,3) into shape (1080,1920,3)]]]
2020-06-02 14:50:09,853-WARNING: recv endsignal from outq with errmsg[consumer[consumer-b18-3] exits for reason[consumer[consumer-b18-6] failed to map with error:[could not broadcast input array from shape (1920,1080,3) into shape (1080,1920,3)]]]
2020-06-02 14:50:09,853-WARNING: Your reader has raised an exception!
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/public/home/felix/anaconda3/envs/tf/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/public/home/felix/anaconda3/envs/tf/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/public/home/felix/anaconda3/envs/tf/lib/python3.6/site-packages/paddle/fluid/reader.py", line 805, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/public/home/felix/anaconda3/envs/tf/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/public/home/felix/anaconda3/envs/tf/lib/python3.6/site-packages/paddle/fluid/reader.py", line 785, in __thread_main__
    for tensors in self._tensor_reader():
  File "/public/home/felix/anaconda3/envs/tf/lib/python3.6/site-packages/paddle/fluid/reader.py", line 853, in __tensor_reader_impl__
    for slots in paddle_reader():
  File "/public/home/felix/anaconda3/envs/tf/lib/python3.6/site-packages/paddle/fluid/data_feeder.py", line 488, in __reader_creator__
    for item in reader():
  File "/public/home/felix/myproject/Paddle/PaddleDetection/ppdet/data/reader.py", line 417, in _reader
    reader.reset()
  File "/public/home/felix/myproject/Paddle/PaddleDetection/ppdet/data/parallel_map.py", line 253, in reset
    assert not self._exit, "cannot reset for already stopped dataset"
AssertionError: cannot reset for already stopped dataset

/public/home/felix/anaconda3/envs/tf/lib/python3.6/site-packages/paddle/fluid/executor.py:782: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tools/train.py", line 324, in <module>
    main()
  File "tools/train.py", line 234, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "/public/home/felix/anaconda3/envs/tf/lib/python3.6/site-packages/paddle/fluid/executor.py", line 783, in run
    six.reraise(*sys.exc_info())
  File "/public/home/felix/anaconda3/envs/tf/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/public/home/felix/anaconda3/envs/tf/lib/python3.6/site-packages/paddle/fluid/executor.py", line 778, in run
    use_program_cache=use_program_cache)
  File "/public/home/felix/anaconda3/envs/tf/lib/python3.6/site-packages/paddle/fluid/executor.py", line 843, in _run_impl
    return_numpy=return_numpy)
  File "/public/home/felix/anaconda3/envs/tf/lib/python3.6/site-packages/paddle/fluid/executor.py", line 677, in _run_parallel
    tensors = exe.run(fetch_var_names)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/public/home/felix/anaconda3/envs/tf/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/public/home/felix/anaconda3/envs/tf/lib/python3.6/site-packages/paddle/fluid/reader.py", line 733, in _init_non_iterable
    outputs={'Out': self._feed_list})
  File "/public/home/felix/anaconda3/envs/tf/lib/python3.6/site-packages/paddle/fluid/reader.py", line 646, in __init__
    self._init_non_iterable()
  File "/public/home/felix/anaconda3/envs/tf/lib/python3.6/site-packages/paddle/fluid/reader.py", line 280, in from_generator
    iterable, return_list)
  File "/public/home/felix/myproject/Paddle/PaddleDetection/ppdet/modeling/architectures/ssd.py", line 123, in build_inputs
    iterable=iterable) if use_dataloader else None
  File "tools/train.py", line 116, in main
    feed_vars, train_loader = model.build_inputs(**inputs_def)
  File "tools/train.py", line 324, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]

**Comment by heavengate** [comment]
报错有两个
1. 有图像的宽和高的标注尺寸是0
```
File "/public/home/felix/myproject/Paddle/PaddleDetection/ppdet/data/transform/operators.py", line 291, in call
raise ZeroDivisionError('{}: min size of image is 0'.format(self))
ZeroDivisionError: ResizeImage_f96a2d: min size of image is 0

2020-06-02 14:50:00,037-WARNING: recv endsignal from outq with errmsg[consumer[consumer-b18-0] failed to map with error:[ResizeImage_f96a2d: min size of image is 0]]
```
2. 有图像的宽和高的标注值和图像实际宽高值是反的
```
File "/public/home/felix/myproject/Paddle/PaddleDetection/ppdet/data/transform/operators.py", line 1268, in call
canvas[y:y + height, x:x + width, :] = img.astype(np.uint8)
ValueError: could not broadcast input array from shape (1920,1080,3) into shape (1080,1920,3)
```

**Comment by felixgalaxy** [comment]
> 报错有两个
> 
> 1. 有图像的宽和高的标注尺寸是0
> 
> ```
> File "/public/home/felix/myproject/Paddle/PaddleDetection/ppdet/data/transform/operators.py", line 291, in call
> raise ZeroDivisionError('{}: min size of image is 0'.format(self))
> ZeroDivisionError: ResizeImage_f96a2d: min size of image is 0
> 
> 2020-06-02 14:50:00,037-WARNING: recv endsignal from outq with errmsg[consumer[consumer-b18-0] failed to map with error:[ResizeImage_f96a2d: min size of image is 0]]
> ```
> 
> 1. 有图像的宽和高的标注值和图像实际宽高值是反的
> 
> ```
> File "/public/home/felix/myproject/Paddle/PaddleDetection/ppdet/data/transform/operators.py", line 1268, in call
> canvas[y:y + height, x:x + width, :] = img.astype(np.uint8)
> ValueError: could not broadcast input array from shape (1920,1080,3) into shape (1080,1920,3)
> ```
感谢
