### ISSUE TITLE
gpu报错

### ISSUE THREAD

**Issue by QL-AR** [PaddlePaddle/PaddleDetection#8493]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

显卡1060，PaddleDetectino2.6，cuda12.0，cudnn8.9.1 报错：
Traceback (most recent call last):
  File "F:\PaddleDetection-release-2.6\deploy\python\infer.py", line 1084, in <module>
    main()
  File "F:\PaddleDetection-release-2.6\deploy\python\infer.py", line 1018, in main
    detector = eval(detector_func)(
  File "F:\PaddleDetection-release-2.6\deploy\python\infer.py", line 107, in __init__
    self.predictor, self.config = load_predictor(
  File "F:\PaddleDetection-release-2.6\deploy\python\infer.py", line 932, in load_predictor
    predictor = create_predictor(config)
OSError: (External) CUDA error(35), CUDA driver version is insufficient for CUDA runtime version.
  [Hint: 'cudaErrorInsufficientDriver'. This indicates that the installed NVIDIA CUDA driver is older than the CUDA runtime library. This is not a supported configuration.Users should install an updated NVIDIA display driver to allow the application to run.] (at ..\paddle\phi\backends\gpu\cuda\cuda_info.cc:67)
怎么回事？

**Comment by LokeZhou** [comment]
从报错显示看，是cuda驱动版本不匹配的问题，自查一下cuda版本与paddle是否匹配
