### ISSUE TITLE
按官方步骤来的，数据集格式没有问题，求解

### ISSUE THREAD

**Issue by NGIWS830** [PaddlePaddle/PaddleDetection#8515]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

[08/07 11:31:43] reader WARNING: fail to map sample transform [Decode_bf5711] with error: 'bytes' object has no attribute 'shape' and stack:
Traceback (most recent call last):
  File "/home/aistudio/work/PaddleDetection/ppdet/data/reader.py", line 59, in __call__
    data = f(data)
  File "/home/aistudio/work/PaddleDetection/ppdet/data/transform/operators.py", line 103, in __call__
    sample[i] = self.apply(sample[i], context)
  File "/home/aistudio/work/PaddleDetection/ppdet/data/transform/operators.py", line 139, in apply
    elif sample['h'] != im.shape[0]:
AttributeError: 'bytes' object has no attribute 'shape'

Traceback (most recent call last):
  File "tools/train.py", line 202, in <module>
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 505, in _thread_loop
    batch = self._get_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 634, in _get_data
    batch.reraise()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 169, in reraise
    raise self.exc_type(msg)
AttributeError: DataLoader worker(0) caught AttributeError with message:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 329, in _worker_loop
    batch = fetcher.fetch(indices)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 121, in fetch
    data.append(self.dataset[idx])
  File "/home/aistudio/work/PaddleDetection/ppdet/data/source/dataset.py", line 102, in __getitem__
    return self.transform(roidb)
  File "/home/aistudio/work/PaddleDetection/ppdet/data/reader.py", line 65, in __call__
    raise e
  File "/home/aistudio/work/PaddleDetection/ppdet/data/reader.py", line 59, in __call__
    data = f(data)
  File "/home/aistudio/work/PaddleDetection/ppdet/data/transform/operators.py", line 103, in __call__
    sample[i] = self.apply(sample[i], context)
  File "/home/aistudio/work/PaddleDetection/ppdet/data/transform/operators.py", line 139, in apply
    elif sample['h'] != im.shape[0]:
AttributeError: 'bytes' object has no attribute 'shape'

**Comment by hukelin** [comment]
我也遇到了，是预测推理阶段

**Comment by hukelin** [comment]
解决了吗

**Comment by kitterive** [comment]
同样问题，有解决的吗

**Comment by yistiger** [comment]
已解决，到PaddleDetection/ppdet/data/transform/operators.py，原代码：with open(sample['im_file'], 'rb') as f:
            #     sample['image'] = f.read() 改为 sample['image'] = cv2.imread(sample['im_file'])
            打印sample print("image",sample["image"])
             print(sample)，会发现有image是为None的，把None的图片在数据集、标注文件删除掉就可以了

**Comment by buqi2yu** [comment]
牛

**Comment by syriacus99** [comment]
同样的问题，解决了吗

**Comment by yistiger** [comment]
> 同样的问题，解决了吗

解决了 参考我上面给别人的回复哈

**Comment by syriacus99** [comment]
> > 同样的问题，解决了吗
> 
> 解决了 参考我上面给别人的回复哈

那可能还是有不一样的问题，你说的那个我其实试了的，直接cv2.imread(sample['im_file'])读出来每个都是None，然后fread其实内存读到了同样大的数据，就是无法解码。最后我用docker环境了，我实在不知道是啥问题导致的，这段代码甚至单独拎出来都能成功读取到图片。
