### ISSUE TITLE
PaddleDetection:deploy/python/infer.py的batch_size设置>1便报错

### ISSUE THREAD

**Issue by black-zyp** [PaddlePaddle/PaddleDetection#8520]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

PaddleDetection:deploy/python/infer.py的batch_size设置>1遍报错
具体的报错信息如下：
Traceback (most recent call last):
  File "/home/zyp/program/pdf_ocr/PaddleDetection-release-2.6/deploy/python/infer.py", line 1097, in <module>
    main()
  File "/home/zyp/program/pdf_ocr/PaddleDetection-release-2.6/deploy/python/infer.py", line 1063, in main
    save_results=FLAGS.save_results)
  File "/home/zyp/program/pdf_ocr/PaddleDetection-release-2.6/deploy/python/infer.py", line 413, in predict_image
    result = self.postprocess(inputs, result)
  File "/home/zyp/program/pdf_ocr/PaddleDetection-release-2.6/deploy/python/infer.py", line 682, in postprocess
    np_boxes, np_boxes_num = postprocessor(np_score_list, np_boxes_list)
  File "/home/zyp/program/pdf_ocr/PaddleDetection-release-2.6/deploy/python/picodet_postprocess.py", line 166, in __call__
    center = center[topk_idx]
IndexError: index 165237 is out of bounds for axis 0 with size 7600

使用的模型是：picodet_lcnet_x1_0_fgd_layout_cdla_infer

**Comment by black-zyp** [comment]
有没有大佬解答一下

**Comment by black-zyp** [comment]
在（https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/deploy/README.md）有说明，刚看到gg，是我用的模型不对

1.2 使用PaddleInference进行预测
Python部署 支持CPU、GPU和XPU环境，支持，windows、linux系统，支持NV Jetson嵌入式设备上部署。参考文档[python部署](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/deploy/python/README.md)
C++部署 支持CPU、GPU和XPU环境，支持，windows、linux系统，支持NV Jetson嵌入式设备上部署。参考文档[C++部署](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/deploy/cpp/README.md)
PaddleDetection支持TensorRT加速,相关文档请参考[TensorRT预测部署教程](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/deploy/TENSOR_RT.md)
**注意: Paddle预测库版本需要>=2.1，batch_size>1仅支持YOLOv3和PP-YOLO。**
