### ISSUE TITLE
pphuman LANE_SEG模型加上 run_mode=trt_fp16报错

### ISSUE THREAD

**Issue by truthsun22** [PaddlePaddle/PaddleDetection#8522]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

在运行pphuman车辆检测加车牌识别时，加上了 --run_mode=trt_fp16后报如下错误
Traceback (most recent call last):
  File "D:\ai\paddle\pddetect\pipeline\pipeline.py", line 1849, in <module>
    main()
  File "D:\ai\paddle\pddetect\pipeline\pipeline.py", line 1828, in main
    pipeline = Pipeline(FLAGS, cfg)
  File "D:\ai\paddle\pddetect\pipeline\pipeline.py", line 103, in __init__
    self.predictor = PipePredictor(args, cfg, self.is_video)
  File "D:\ai\paddle\pddetect\pipeline\pipeline.py", line 393, in __init__
    self.vehicleplate_detector = PlateRecognizer(args, vehicleplate_cfg)
  File "D:\ai\paddle\pddetect\pipeline\ppvehicle\vehicle_plate.py", line 245, in __init__
    self.textrecognizer = TextRecognizer(args, cfg, use_gpu=use_gpu)
  File "D:\ai\paddle\pddetect\pipeline\ppvehicle\vehicle_plate.py", line 163, in __init__
    create_predictor(args, cfg, 'rec')
  File "D:\ai\paddle\pddetect\pipeline\ppvehicle\vehicle_plateutils.py", line 178, in create_predictor
    predictor = inference.create_predictor(config)
RuntimeError: (NotFound) Operator (preln_residual_bias) is not registered.
  [Hint: op_info_ptr should not be null.] (at ..\paddle/fluid/framework/op_info.h:156)

### 复现环境 Environment

paddle2.4

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by truthsun22** [comment]
标题描述不准确，不是LANE_SEG模型模型的问题，是车牌检测或识别模型在trt16下报错

**Comment by lyuwenyu** [comment]
导出onnx然后转fp16试一下
