### ISSUE TITLE
vidualdl使用报错

### ISSUE THREAD

**Issue by HGD-ai** [PaddlePaddle/PaddleDetection#8542]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

我再ubuntu20.04上训练完成后想查看训练中的loss的变化曲线，ubuntu的服务器地址是 192.168.34.188 在服务器上执行了
visualdl  logdir=vdl_log_dir/scalar/ --host 192.168.34.188
我在本地输入网址 http://192.168.34.188:8040/后出现了如下错误。
‘’‘
[ERROR 2023-08-16 10:01:21,732 lib.py:637] Unexpected error: <class 'AttributeError'>
'LogReader' object has no attribute '_model'
<traceback object at 0x7f07e6c99f00>
[ERROR 2023-08-16 10:01:23,734 lib.py:637] Unexpected error: <class 'AttributeError'>
'LogReader' object has no attribute '_model'
<traceback object at 0x7f07e6f884c0>
Traceback (most recent call last):
  File "/home/software/anaconda3/envs/PaddlePaddle/lib/python3.10/site-packages/visualdl/server/lib.py", line 633, in retry
    return function(*args, **kwargs)
  File "/home/software/anaconda3/envs/PaddlePaddle/lib/python3.10/site-packages/visualdl/server/lib.py", line 585, in get_static_graph
    if log_reader.model:
  File "/home/software/anaconda3/envs/PaddlePaddle/lib/python3.10/site-packages/visualdl/reader/reader.py", line 100, in model
    return self._model
AttributeError: 'LogReader' object has no attribute '_model'
[ERROR 2023-08-16 10:01:25,737 api.py:75] Internal server error. Retry later.
’‘’‘

### 复现环境 Environment

-OS linux
VisualDL 2.5.3
PaddleDetection-release-2.6

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [x] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by zhiboniu** [comment]
你好，可以到框架repo中提问visualdl相关问题
