### ISSUE TITLE
./mtmct-demo/c003 has no images.

### ISSUE THREAD

**Issue by tonglingwen** [PaddlePaddle/PaddleDetection#8550]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我是用PaddleDetetion2.6  按照这个方法https://aistudio.baidu.com/projectdetail/3022582   运行PP-Tracing时出现一下错误：
--------------------------------------------
Traceback (most recent call last):
  File "deploy/pptracking/python/mot_sde_infer.py", line 953, in <module>
    main()
  File "deploy/pptracking/python/mot_sde_infer.py", line 922, in main
    detector.predict_mtmct(FLAGS.mtmct_dir, mtmct_cfg)
  File "deploy/pptracking/python/mot_sde_infer.py", line 830, in predict_mtmct
    mot_features_dict = self.predict_image(
  File "deploy/pptracking/python/mot_sde_infer.py", line 559, in predict_image
    det_result = self.reidprocess(det_result)
  File "deploy/pptracking/python/mot_sde_infer.py", line 288, in reidprocess
    w, h = self.tracker.input_size
AttributeError: 'BOTSORTTracker' object has no attribute 'input_size'

我使用的命令为：
python deploy/pptracking/python/mot_sde_infer.py --model_dir=output_inference/ppyolov2_r50vd_dcn_365e_aic21mtmct_vehicle/ --reid_model_dir=output_inference/deepsort_pplcnet_vehicle/ --mtmct_dir=./mtmct-demo --device=CPU --mtmct_cfg=deploy/pptracking/python/mtmct_cfg.yml --scaled=True --save_mot_txts --save_images  --tracker_config=deploy/pptracking/python/tracker_config.yml

注：命令中tracker_config 是我后加的 不加会报找不到tracker_config.yml的错误，paddle我是用的是CPU的版本

**Comment by Dstudying** [comment]
@tonglingwen 请问解决了吗，官方教程也够离谱的。相同的步骤，同样的问题。我是用paddle-gpu的版本

**Comment by Dstudying** [comment]
@tonglingwen 我解决了，注意这里的注释。改成DeepSORTTracker就成功了。https://github.com/PaddlePaddle/PaddleDetection/blob/e717debfd302e6a17ec3c7b7a366d694b2a18c07/deploy/pptracking/python/tracker_config.yml#L6C1-L6C1

**Comment by 15690860529** [comment]
> @tonglingwen 我解决了，注意这里的注释。改成DeepSORTTracker就成功了。https://github.com/PaddlePaddle/PaddleDetection/blob/e717debfd302e6a17ec3c7b7a366d694b2a18c07/deploy/pptracking/python/tracker_config.yml#L6C1-L6C1

@Dstudying 怎么解决的，没看懂什么意思

**Comment by Dstudying** [comment]
> > @tonglingwen 我解决了，注意这里的注释。改成DeepSORTTracker就成功了。https://github.com/PaddlePaddle/PaddleDetection/blob/e717debfd302e6a17ec3c7b7a366d694b2a18c07/deploy/pptracking/python/tracker_config.yml#L6C1-L6C1
> 
> @Dstudying 怎么解决的，没看懂什么意思

type: BOTSORTTracker 换成 type: DeepSORTTracker
为什么要这样做呢？下面有个注释
`When using for MTMCT(Multi-Target Multi-Camera Tracking), you should modify to 'DeepSORTTracker'`

**Comment by zhiboniu** [comment]
感谢楼上回复
