### ISSUE TITLE
ppyoloe_r 支持导出onnx吗

### ISSUE THREAD

**Issue by Myxrf** [PaddlePaddle/PaddleDetection#8565]
### 问题确认 Search before asking

- [x] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

ppyoloe_r 支持导出onnx吗，目前尝试都是导出失败

**Comment by lyuwenyu** [comment]
报啥错  后处理不支持的

**Comment by Myxrf** [comment]
重试了一下，导出可以导出，但是推理有问题，这是卡在后处理吗
python deploy/third_engine/onnx/infer.py   --infer_cfg inference_model/ppyoloe_r_crn_l_3x_dota/infer_cfg.yml  --onnx_file yolov_r.onnx  --image_file demo/3_3.png


Traceback (most recent call last):
  File "deploy/third_engine/onnx/infer.py", line 148, in <module>
    predict_image(infer_config, predictor, img_list)
  File "deploy/third_engine/onnx/infer.py", line 126, in predict_image
    outputs = predictor.run(output_names=None, input_feed=inputs)
  File "D:\anaconda\envs\paddet2\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 219, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Split node. Name:'p2o.Split.6' Status Message: Cannot split using values in 'split' attribute. Axis=2 Input shape={1,5376,8} NumOutputs=4 Num entries in 'split' (must equal number of outputs) was 4 Sum of sizes in 'split' (must equal size of selected axis) was 4

**Comment by zzzzz1231** [comment]
我也出现了这个问题，请问您解决了吗

**Comment by LokeZhou** [comment]
导出的问题可以到paddle2onnx提issues
