### ISSUE TITLE
如何只跨境跟踪单类目标？

### ISSUE THREAD

**Issue by XIEBELL** [PaddlePaddle/PaddleDetection#8654]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

你好，我已经可以运行跨镜头追踪的案例，可以检测coco的80个种类，我想自己修改为只跨境追踪一类目标的时候报错。
我尝试了两种方案，
1。在mcmt中改预测到的boxes，删为仅id==0的人类
2。重新训练一个新的模型只包含人,来进行检测的部分
都会报错：
MOT results save in output\c02.txt
current use ff finetuned parameters....
feat3:0/7
feat3:0/7
current use rerank finetuned parameters....
k = ?' 21
axis_size== 14
Traceback (most recent call last):
  File "deploy/pptracking/python/mot_sde_infer.py", line 1173, in <module>
    main()
  File "deploy/pptracking/python/mot_sde_infer.py", line 1120, in main
    save_mot_txts=FLAGS.save_mot_txts)
  File "deploy/pptracking/python/mot_sde_infer.py", line 964, in predict_mtmct
    use_st_filter=use_st_filter)
  File "G:\bsh\PaddleDetection-release-2.3\deploy\pptracking\python\mot\mtmct\postprocess.py", line 119, in sub_cluster
    use_st_filter=use_st_filter)
  File "G:\bsh\PaddleDetection-release-2.3\deploy\pptracking\python\mot\mtmct\utils.py", line 541, in get_labels
    use_st_filter=use_st_filter)
  File "G:\bsh\PaddleDetection-release-2.3\deploy\pptracking\python\mot\mtmct\utils.py", line 520, in get_sim_matrix
    q_arr, g_arr, cid_tids, use_ff=use_ff, use_rerank=use_rerank)
  File "G:\bsh\PaddleDetection-release-2.3\deploy\pptracking\python\mot\mtmct\utils.py", line 372, in visual_rerank
    sims = ReRank2(prb_feats, gal_feats, 20, 3, 0.3)
  File "G:\bsh\PaddleDetection-release-2.3\deploy\pptracking\python\mot\mtmct\utils.py", line 293, in ReRank2
    initial_rank = batch_numpy_topk(feat, feat, k1 + 1, N=6000)
  File "G:\bsh\PaddleDetection-release-2.3\deploy\pptracking\python\mot\mtmct\utils.py", line 235, in batch_numpy_topk
    find_topk(temp_qd, k=k1, axis=1, largest=False, sorted=True)[1])
  File "G:\bsh\PaddleDetection-release-2.3\deploy\pptracking\python\mot\mtmct\utils.py", line 198, in find_topk
    assert 1 <= k <= axis_size
AssertionError

请问我该怎么办？

**Comment by XIEBELL** [comment]
current use ff finetuned parameters....
feat3:0/7
feat3:0/7
current use rerank finetuned parameters....
k = ?' 21
axis_size== 14
Traceback (most recent call last):
  File "deploy/pptracking/python/mot_sde_infer.py", line 1173, in <module>
    main()
  File "deploy/pptracking/python/mot_sde_infer.py", line 1120, in main
    save_mot_txts=FLAGS.save_mot_txts)
  File "deploy/pptracking/python/mot_sde_infer.py", line 964, in predict_mtmct
    use_st_filter=use_st_filter)
  File "G:\bsh\PaddleDetection-release-2.3\deploy\pptracking\python\mot\mtmct\postprocess.py", line 119, in sub_cluster
    use_st_filter=use_st_filter)
  File "G:\bsh\PaddleDetection-release-2.3\deploy\pptracking\python\mot\mtmct\utils.py", line 541, in get_labels
    use_st_filter=use_st_filter)
  File "G:\bsh\PaddleDetection-release-2.3\deploy\pptracking\python\mot\mtmct\utils.py", line 520, in get_sim_matrix
    q_arr, g_arr, cid_tids, use_ff=use_ff, use_rerank=use_rerank)
  File "G:\bsh\PaddleDetection-release-2.3\deploy\pptracking\python\mot\mtmct\utils.py", line 372, in visual_rerank
    sims = ReRank2(prb_feats, gal_feats, 20, 3, 0.3)
  File "G:\bsh\PaddleDetection-release-2.3\deploy\pptracking\python\mot\mtmct\utils.py", line 293, in ReRank2
    initial_rank = batch_numpy_topk(feat, feat, k1 + 1, N=6000)
  File "G:\bsh\PaddleDetection-release-2.3\deploy\pptracking\python\mot\mtmct\utils.py", line 235, in batch_numpy_topk
    find_topk(temp_qd, k=k1, axis=1, largest=False, sorted=True)[1])
  File "G:\bsh\PaddleDetection-release-2.3\deploy\pptracking\python\mot\mtmct\utils.py", line 198, in find_topk
    assert 1 <= k <= axis_size
AssertionError
(paddle) PS G:\bsh\PaddleDetection-releas

我把报错的k和axis_size 打印了出来，不知道这两个变量是什么意思，请教一下，谢谢

**Comment by XIEBELL** [comment]
我把k修改为1或者2，或者其他，程序可以正常运行了，但是程序检测数量变化，会偶尔出现bug，请问应该怎么修改k来自适应呢？
 File "F:\APP\miniconda\envs\paddle\lib\site-packages\sklearn\utils\validation.py", line 116, in _assert_all_finite
    type_err, msg_dtype if msg_dtype is not None else X.dtype
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

**Comment by zhiboniu** [comment]
你好，看起来k的数值并不正常，可以先检查是什么原因导致的k数值异常
