### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'items'

### ISSUE THREAD

**Issue by in-moonshadow** [PaddlePaddle/PaddleDetection#8659]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training

### Bug描述 Describe the Bug

RT-DETR，在第一轮训练结束后出现如下错误：
'''Traceback (most recent call last):
  File "tools/train.py", line 209, in <module>
    main()
  File "tools/train.py", line 205, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 158, in run
    trainer.train(FLAGS.eval)
  File "/home/moon/PaddleDetection/ppdet/engine/trainer.py", line 639, in train
    self._eval_with_loader(self._eval_loader)
  File "/home/moon/PaddleDetection/ppdet/engine/trainer.py", line 676, in _eval_with_loader
    metric.update(data, outs)
  File "/home/moon/PaddleDetection/ppdet/metrics/metrics.py", line 103, in update
    for k, v in outputs.items():
AttributeError: 'Tensor' object has no attribute 'items'
'''

### 复现环境 Environment

-Linux
-CUDA11.4
-CUDNN8.2

### Bug描述确认 Bug description confirmation

- [ ] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by zzlz233** [comment]
昨天训练时出现了同样问题

**Comment by zhiboniu** [comment]
你好，可以查看下代码逻辑output应该是一个dict
