### ISSUE TITLE
multiscaletest报错

### ISSUE THREAD

**Issue by yinggo** [PaddlePaddle/PaddleDetection#868]
使用的是cascade_rcnn_r50_fpn_1x_ms_test
数据集读取部分改动：
```
_READER_: 'faster_fpn_reader.yml'
TrainReader:
  batch_size: 2
  inputs_def:
    fields: ['image', 'im_info', 'im_id', 'gt_bbox', 'gt_class', 'is_crowd']
  dataset:
    !VOCDataSet
    anno_path: train.txt   #annotations/instances_train2017.json
    dataset_dir: dataset/voc

EvalReader:
  batch_size: 1
  inputs_def:
    fields: ['image', 'im_info', 'im_id',  'im_shape', 'gt_bbox', 'gt_class', 'is_difficult']
    multi_scale: true
    num_scales: 18
    use_flip: true
  dataset:
    !VOCDataSet
    dataset_dir: dataset/voc
    anno_path: val.txt   
```
是带--eval训练，在eval中报错：
```
Traceback (most recent call last):
  File "tools/train.py", line 366, in <module>
    main()
  File "tools/train.py", line 284, in main
    resolution=resolution)
  File "/home/ds1/anaconda3/envs/paddle2/PaddleDetection/ppdet/utils/eval_utils.py", line 139, in eval_run
    cfg.num_classes)
  File "/home/ds1/anaconda3/envs/paddle2/PaddleDetection/ppdet/utils/post_process.py", line 214, in mstest_box_post_process
    im_shape = result['im_shape'][0]
KeyError: 'im_shape'

ERROR 2020-06-04 10:56:42,445 utils.py:422] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0] was aborted. Please check its log.
Traceback (most recent call last):
  File "/home/ds1/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle/distributed/utils.py", line 406, in watch_local_trainers
    terminate_local_procs(procs)
  File "/home/ds1/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle/distributed/utils.py", line 257, in terminate_local_procs
    p.proc.join(timeout=1)
AttributeError: 'Popen' object has no attribute 'join'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ds1/anaconda3/envs/paddle2/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ds1/anaconda3/envs/paddle2/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ds1/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle/distributed/launch.py", line 237, in <module>
    launch(args)
  File "/home/ds1/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle/distributed/launch.py", line 220, in launch
    alive = watch_local_trainers(procs, cluster.trainers_nranks())
  File "/home/ds1/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle/distributed/utils.py", line 423, in watch_local_trainers
    terminate_local_procs(procs)
  File "/home/ds1/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle/distributed/utils.py", line 257, in terminate_local_procs
    p.proc.join(timeout=1)
AttributeError: 'Popen' object has no attribute 'join'
```

**Comment by jerrywgz** [comment]
目前multiscale test还不支持边训练边测试，可以通过单尺度先验证模型效果，再通过eval.py进行多尺度测试

**Comment by yinggo** [comment]
好的 谢谢
