### ISSUE TITLE
paddleDetection 30分钟入门中通过json文件评估是什么意思

### ISSUE THREAD

**Issue by keeper-jie** [PaddlePaddle/PaddleDetection#8704]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

操作参考链接：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/docs/tutorials/GETTING_STARTED_cn.md

`docker run --name dev --runtime=nvidia -v $PWD:/mnt -p 8888:8888 -it paddlecloud/paddledetection:2.4-gpu-cuda10.2-cudnn7-e9a542 /bin/bash`使用docker运行以下命令报错：
```
export CUDA_VISIBLE_DEVICES=0 #windows和Mac下不需要执行该命令
python tools/eval.py -c configs/yolov3/yolov3_mobilenet_v1_roadsign.yml \
             --json_eval \
             --output_eval evaluation/
```
报错信息如下：
```
Traceback (most recent call last):
  File "tools/eval.py", line 152, in <module>
    main()
  File "tools/eval.py", line 148, in main
    run(FLAGS, cfg)
  File "tools/eval.py", line 93, in run
    dataset=cfg['EvalDataset'])
  File "/home/PaddleDetection/ppdet/metrics/coco_utils.py", line 169, in json_eval_results
    assert metric == 'COCO'
AssertionError
```
问题：报错原因以及示例的JSON格式是怎么样的，可以怎么修改

**Comment by LokeZhou** [comment]
检查一下metric 的值是不是coco
