### ISSUE TITLE
fcos模型使用出现nan

### ISSUE THREAD

**Issue by yinggo** [PaddlePaddle/PaddleDetection#871]
```
2020-06-04 14:04:36,042-INFO: iter: 0, lr: 0.003333, 'loss_centerness': '0.707450', 'loss_cls': '1.153195', 'loss_box': '8604.718750', 'loss': '8606.579102', time: 0.000, eta: 0:00:01
2020-06-04 14:04:43,885-INFO: iter: 20, lr: 0.003600, 'loss_centerness': '416.278137', 'loss_cls': '10.299585', 'loss_box': '7611.416992', 'loss': '9316.037109', time: 0.439, eta: 10:58:12
2020-06-04 14:04:51,708-INFO: iter: 40, lr: 0.003867, 'loss_centerness': 'nan', 'loss_cls': 'nan', 'loss_box': '7982.696289', 'loss': 'nan', time: 0.391, eta: 9:45:29
2020-06-04 14:04:59,772-INFO: iter: 60, lr: 0.004133, 'loss_centerness': 'nan', 'loss_cls': 'nan', 'loss_box': '22842.406250', 'loss': 'nan', time: 0.403, eta: 10:04:24
2020-06-04 14:05:07,863-INFO: iter: 80, lr: 0.004400, 'loss_centerness': 'nan', 'loss_cls': 'nan', 'loss_box': '22561.207031', 'loss': 'nan', time: 0.404, eta: 10:06:11
2020-06-04 14:05:16,058-INFO: iter: 100, lr: 0.004667, 'loss_centerness': 'nan', 'loss_cls': 'nan', 'loss_box': '22724.001953', 'loss': 'nan', time: 0.410, eta: 10:13:37
```
已经减小了base_lr from 0.01 to 0.0001……
请问需要怎么调整模型？

**Comment by jerrywgz** [comment]
请问你的配置文件有做过什么修改吗，也建议使用fcos在coco上的训练结果作为预训练模型 具体模型可以从这里下载 https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.3/configs/anchor_free

**Comment by yinggo** [comment]
@jerrywgz  您好，使用的是默认配置和预训练模型，因为自己的数据集是voc格式所以在reader部分做了一些改动，这里是配置文件[https://github.com/yinggo/PaddleDetection/blob/release/0.2/configs/fcos_dcn_r50_fpn_1x_city2.yml](url)

**Comment by CodesFarmer** [comment]
你好，你训练用的是几张卡？我看你batch_size设置的是1，我们在coco上训练的时候，batch_size=2，8卡，相当于batch_size=16，FCOS现在batch_size过小会导致匹配ground truth的时候没有ground truth被匹配到，导致loss出nan，建议调大batch_size看看

**Comment by yinggo** [comment]
谢谢，调大batch_size之后解决了loss问题！ 
有个新问题是eval时出现，应该是我使用的数据格式是voc而不是coco：
```
2020-06-04 17:13:53,289-INFO: Start evaluate...
Traceback (most recent call last):
  File "tools/train.py", line 366, in <module>
    main()
  File "tools/train.py", line 288, in main
    cfg['EvalReader']['dataset'])
  File "/home/ds1/anaconda3/envs/paddle/PaddleDetection/ppdet/utils/eval_utils.py", line 236, in eval_results
    map_type=map_type)
  File "/home/ds1/anaconda3/envs/paddle/PaddleDetection/ppdet/utils/voc_eval.py", line 71, in bbox_eval
    gt_boxes = t['gt_bbox'][0]
KeyError: 'gt_bbox'
```
我将eval_reader部分修改[这里](https://github.com/yinggo/PaddleDetection/commit/f59a36ea46a8f820367e7998b6c51123757cd61d)后报错：
```
2020-06-04 17:20:24,504-WARNING: recv endsignal from outq with errmsg[consumer[consumer-677-0] failed to map with error:[labels0 not in samples]]
2020-06-04 17:20:24,505-WARNING: Your reader has raised an exception!
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/home/ds1/anaconda3/envs/paddle/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/ds1/anaconda3/envs/paddle/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ds1/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/reader.py", line 805, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/home/ds1/anaconda3/envs/paddle/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/ds1/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/reader.py", line 785, in __thread_main__
    for tensors in self._tensor_reader():
  File "/home/ds1/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/reader.py", line 853, in __tensor_reader_impl__
    for slots in paddle_reader():
  File "/home/ds1/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 488, in __reader_creator__
    for item in reader():
  File "/home/ds1/anaconda3/envs/paddle/PaddleDetection/ppdet/data/reader.py", line 421, in _reader
    reader.reset()
  File "/home/ds1/anaconda3/envs/paddle/PaddleDetection/ppdet/data/parallel_map.py", line 259, in reset
    assert not self._exit, "cannot reset for already stopped dataset"
AssertionError: cannot reset for already stopped dataset
```
请问该怎么调整？

**Comment by qingqing01** [comment]
@yinggo  对于VOC的评估方式，EvalReader的fileds配置不同，参考：  https://github.com/PaddlePaddle/PaddleDetection/issues/773#issuecomment-633460585

**Comment by yinggo** [comment]
您好，可能我之前的表述不太清楚，
我已将eval_reader部分进行了修改
```
EvalReader:
  inputs_def:
    fields: ['image', 'im_info', 'im_id', 'im_shape', 'gt_bbox' , 'gt_class', 'is_difficult'] 
```
config文件是[这样](https://github.com/yinggo/PaddleDetection/blob/f59a36ea46a8f820367e7998b6c51123757cd61d/configs/fcos_dcn_r50_fpn_1x_city2.yml)
报错：
```
2020-06-04 17:20:24,504-WARNING: recv endsignal from outq with errmsg[consumer[consumer-677-0] 
failed to map with error:[labels0 not in samples]]
2020-06-04 17:20:24,505-WARNING: Your reader has raised an exception!
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/home/ds1/anaconda3/envs/paddle/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/ds1/anaconda3/envs/paddle/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ds1/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/reader.py", line 805, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/home/ds1/anaconda3/envs/paddle/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/ds1/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/reader.py", line 785, in __thread_main__
    for tensors in self._tensor_reader():
  File "/home/ds1/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/reader.py", line 853, in __tensor_reader_impl__
    for slots in paddle_reader():
  File "/home/ds1/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 488, in __reader_creator__
    for item in reader():
  File "/home/ds1/anaconda3/envs/paddle/PaddleDetection/ppdet/data/reader.py", line 421, in _reader
    reader.reset()
  File "/home/ds1/anaconda3/envs/paddle/PaddleDetection/ppdet/data/parallel_map.py", line 259, in reset
    assert not self._exit, "cannot reset for already stopped dataset"
AssertionError: cannot reset for already stopped dataset
```
请问您那边会复现出这个错误吗？

**Comment by jerrywgz** [comment]
是的，目前fcos对voc数据集格式支持的还不好，我们尽快修复下，如果现在需要可以先在eval阶段暂时将https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/ppdet/modeling/architectures/fcos.py#L161-L164 这部分代码删除解决，注意训练时还是需要的

**Comment by yinggo** [comment]
好的，谢谢

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/pull/902 已支持fcos在voc数据集上的训练测试
