### ISSUE TITLE
Paddle model convert to ONNX

### ISSUE THREAD

**Issue by Eric-Fung** [PaddlePaddle/PaddleDetection#8712]
### 问题确认 Search before asking

- [x] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

您好，我根据[文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/deploy/EXPORT_ONNX_MODEL.md)提供的命令转换*faster_rcnn_r50_fpn_1x_coco*模型为ONNX时，遇到了如下报错，其中部署模型导出的命令与文档提供的一致

```bash
[Paddle2ONNX] Oops, there are some operators not supported yet, including distribute_fpn_proposals,generate_proposals_v2,
[ERROR] Due to the unsupported operators, the conversion is aborted.
Aborted (core dumped)
```
当我根据[PaddlePaddle/Paddle2ONNX#1152](https://github.com/PaddlePaddle/Paddle2ONNX/issues/1152)中提到的方法在模型导出时加入`--enable_dev_version False`命令时，报错为如下
```bash
2023-11-13 09:41:20 [WARNING]   [Deprecated] `paddle2onnx.command.program2onnx` will be deprecated in the future version, the recommended usage is `paddle2onnx.export`
I1113 09:41:22.241979  2296 interpretercore.cc:237] New Executor is Running.
/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/fluid/variable_index.py:591: UserWarning: Warning: In Tensor '__getitem__', if the number of scalar elements in the index is equal to the rank of the Tensor, the output should be 0-D. In order to be consistent with the behavior of previous versions, it will be processed to 1-D. But it is not correct and will be removed in release 2.6. If 1-D is still wanted, please modify the index element from scalar to slice (e.g. 'x[i]' => 'x[i:i+1]').
  warnings.warn(
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/bin/paddle2onnx", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle2onnx/command.py", line 268, in main
    program2onnx(
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle2onnx/command.py", line 182, in program2onnx
    return program2onnx(model_dir, save_file, model_filename, params_filename,
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle2onnx/legacy/command.py", line 200, in program2onnx
    p2o.program2onnx(
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle2onnx/convert.py", line 84, in program2onnx
    return program2onnx(program, scope, save_file, feed_var_names, target_vars,
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle2onnx/legacy/convert.py", line 95, in program2onnx
    return export_onnx(
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle2onnx/legacy/convert.py", line 35, in export_onnx
    onnx_graph = ONNXGraph.build(paddle_graph, opset_version,
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle2onnx/legacy/graph/onnx_graph.py", line 323, in build
    onnx_graph = ONNXGraph(
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle2onnx/legacy/graph/onnx_graph.py", line 85, in __init__
    self.update_opset_version()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle2onnx/legacy/graph/onnx_graph.py", line 202, in update_opset_version
    self.opset_version = OpMapper.get_recommend_opset_version(
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle2onnx/legacy/op_mapper/op_mapper.py", line 147, in get_recommend_opset_version
    custom_paddle_graph, output_results = custom_paddle_op.get_paddle_graph(
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle2onnx/legacy/op_mapper/op_mapper.py", line 262, in get_paddle_graph
    res = self.forward()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle2onnx/legacy/op_mapper/custom_paddle_op/generate_proposals.py", line 209, in forward
    new_scores, proposals = self.proposal_for_single_sample(
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle2onnx/legacy/op_mapper/custom_paddle_op/generate_proposals.py", line 178, in proposal_for_single_sample
    out = layers.multiclass_nms(
AttributeError: module 'paddle.fluid.layers' has no attribute 'multiclass_nms'
```

我也尝试了[PaddlePaddle/PaddleDetection#5884](https://github.com/PaddlePaddle/PaddleDetection/issues/5884)中提到的解决方法，但依然不起效果。

**Comment by LokeZhou** [comment]
这个报错看这像paddle版本的问题，可以试一下paddle2.5
