### ISSUE TITLE
如何校验coco数据集？

### ISSUE THREAD

**Issue by LLsmile** [PaddlePaddle/PaddleDetection#8718]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

将自己标注的数据集转成coco格式后，可以正常训练，但是测试的时候会报错：

'''
[11/15 07:21:17] ppdet.engine INFO: Epoch: [0] [ 0/13] learning_rate: 0.000000 loss: 11.489943 loss_cls: 2.577307 loss_obj: 5.539050 loss_iou: 0.674717 loss_l1: 0.000000 size: 640.000000 eta: 8:38:47 batch_cost: 7.9815 data_cost: 3.9561 ips: 2.0046 images/s
[11/15 07:21:36] ppdet.engine INFO: Epoch: [1] [ 0/13] learning_rate: 0.000400 loss: 11.390427 loss_cls: 2.587557 loss_obj: 5.441662 loss_iou: 0.673435 loss_l1: 0.000000 size: 640.000000 eta: 1:59:15 batch_cost: 1.8410 data_cost: 0.9997 ips: 8.6911 images/s
[11/15 07:21:52] ppdet.utils.checkpoint INFO: Save checkpoint: output/yolox_s_300e_coco
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
[11/15 07:21:52] ppdet.data.source.coco INFO: Load [215 samples valid, 0 samples invalid] in file /media/ssd4t/liaolin/02_bag/temp/instances_train2017.json.
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/liaolin/anaconda3/envs/paddledetection/lib/python3.9/threading.py", line 980, in _bootstrap_inner
Traceback (most recent call last):
  File "/home/liaolin/01_det/PaddleDetection/tools/train.py", line 202, in <module>
    main()
  File "/home/liaolin/01_det/PaddleDetection/tools/train.py", line 198, in main
    run(FLAGS, cfg)
  File "/home/liaolin/01_det/PaddleDetection/tools/train.py", line 151, in run
    trainer.train(FLAGS.eval)
  File "/home/liaolin/01_det/PaddleDetection/ppdet/engine/trainer.py", line 601, in train
    self._eval_with_loader(self._eval_loader)
  File "/home/liaolin/01_det/PaddleDetection/ppdet/engine/trainer.py", line 621, in _eval_with_loader
    for step_id, data in enumerate(loader):
  File "/home/liaolin/01_det/PaddleDetection/ppdet/data/reader.py", line 214, in __next__
    return next(self.loader)
  File "/home/liaolin/anaconda3/envs/paddledetection/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 745, in __next__
    self._reader.read_next_list()[0])
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:175)

    self.run()
  File "/home/liaolin/anaconda3/envs/paddledetection/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/liaolin/anaconda3/envs/paddledetection/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 536, in _thread_loop
    batch = self._get_data()
  File "/home/liaolin/anaconda3/envs/paddledetection/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 674, in _get_data
    batch.reraise()
  File "/home/liaolin/anaconda3/envs/paddledetection/lib/python3.9/site-packages/paddle/fluid/dataloader/worker.py", line 172, in reraise
    raise self.exc_type(msg)
ValueError: DataLoader worker(0) caught ValueError with message:
Traceback (most recent call last):
  File "/home/liaolin/anaconda3/envs/paddledetection/lib/python3.9/site-packages/paddle/fluid/dataloader/worker.py", line 339, in _worker_loop
    batch = fetcher.fetch(indices)
  File "/home/liaolin/anaconda3/envs/paddledetection/lib/python3.9/site-packages/paddle/fluid/dataloader/fetcher.py", line 138, in fetch
    data = self.collate_fn(data)
  File "/home/liaolin/01_det/PaddleDetection/ppdet/data/reader.py", line 96, in __call__
    batch_data = default_collate_fn(data)
  File "/home/liaolin/01_det/PaddleDetection/ppdet/data/utils.py", line 60, in default_collate_fn
    return {
  File "/home/liaolin/01_det/PaddleDetection/ppdet/data/utils.py", line 61, in <dictcomp>
    key: default_collate_fn([d[key] for d in batch])
  File "/home/liaolin/01_det/PaddleDetection/ppdet/data/utils.py", line 52, in default_collate_fn
    batch = np.stack(batch, axis=0)
  File "<__array_function__ internals>", line 180, in stack
  File "/home/liaolin/anaconda3/envs/paddledetection/lib/python3.9/site-packages/numpy/core/shape_base.py", line 426, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape
'''
[instances_train2017.json](https://github.com/PaddlePaddle/PaddleDetection/files/13361501/instances_train2017.json)

这是标注文件

**Comment by LLsmile** [comment]
train和val使用相同的数据
