### ISSUE TITLE
使用PP-YOLOE-R训练自定义数据集报错：not found any coco record in coco/annotations/voc_train.json

### ISSUE THREAD

**Issue by yuanjim** [PaddlePaddle/PaddleDetection#8729]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

PP-YOLOE-R是一个高效的单阶段Anchor-free旋转框检测模型。
环境：
ubuntu20.04
paddle2.5.2
paddledetection2.6
配置文件：ppyoloe_r_crn_l_3x_dota_ms.yml
```
_BASE_: [
  '../../datasets/dota_ms.yml',
  '../../runtime.yml',
  '_base_/optimizer_3x.yml',
  '_base_/ppyoloe_r_reader.yml',
  '_base_/ppyoloe_r_crn.yml'
]

log_iter: 50
snapshot_epoch: 1
weights: output/ppyoloe_r_crn_l_3x_dota_ms_clamp_wire/model_final

# pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/CSPResNetb_l_pretrained.pdparams
pretrain_weights: pretrained/CSPResNetb_l_pretrained.pdparams
depth_mult: 1.0
width_mult: 1.0

# 如果GPU卡数或者batch size发生了改变，你需要按照公式 lrnew = lrdefault * (batch_sizenew * GPU_numbernew) / (batch_sizedefault * GPU_numberdefault) 调整学习率。
LearningRate:
  base_lr: 0.001 # 显卡由8卡变为单卡 0.008 变为 0.001

TrainReader:
  batch_size: 2

metric: RBOX
num_classes: 2

TrainDataset:
  !COCODataSet
    image_dir: train
    anno_path: annotations/voc_train.json
    dataset_dir: coco
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd', 'gt_poly']

EvalDataset:
  !COCODataSet
    image_dir: val
    anno_path: annotations/voc_val.json
    dataset_dir: coco
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd', 'gt_poly']

TestDataset:
  !ImageFolder
    anno_path: annotations/voc_val.json
    dataset_dir: coco
```
自定义标注文件：
```
{
    "images": [
        {
            "file_name": "DJI_20230510170433_0007_T.jpg",
            "height": 512.0,
            "width": 640.0,
            "id": 1
        },
        {
            "file_name": "DJI_20230510170511_0009_T.jpg",
            "height": 512.0,
            "width": 640.0,
            "id": 2
        },
    ],
    "type": "instances",
    "annotations": [
        {
            "segmentation": [
                [
                    214.0,
                    311.0,
                    274.0,
                    311.0,
                    274.0,
                    363.0,
                    214.0,
                    363.0
                ]
            ],
            "area": 3120.0,
            "iscrowd": 0,
            "bbox": [],
            "category_id": 1,
            "ignore": 0,
            "image_id": 1,
            "id": 1
        },
        {
            "segmentation": [
                [
                    217.0,
                    339.5,
                    283.0,
                    339.5,
                    283.0,
                    394.5,
                    217.0,
                    394.5
                ]
            ],
            "area": 3630.0,
            "iscrowd": 0,
            "bbox": [],
            "category_id": 1,
            "ignore": 0,
            "image_id": 1,
            "id": 2
        },
    ],
    "categories": [
        {
            "supercategory": "none",
            "id": 1,
            "name": "clamp"
        },
        {
            "supercategory": "none",
            "id": 2,
            "name": "wire"
        }
    ]
}
```
训练命令：CUDA_VISIBLE_DEVICES=0 python tools/train.py -c configs/rotate/ppyoloe_r/ppyoloe_r_crn_l_3x_dota_ms.yml --eval
报错：
```
python tools/train.py -c configs/rotate/ppyoloe_r/ppyoloe_r_crn_l_3x_dota_ms.yml --eval
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Traceback (most recent call last):
  File "tools/train.py", line 202, in <module>
    main()
  File "tools/train.py", line 198, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 142, in run
    trainer = Trainer(cfg, mode='train')
  File "/home/jim/projects/0064_clamp_wire/PaddleDetection-2.6/ppdet/engine/trainer.py", line 99, in __init__
    self.dataset, cfg.worker_num)
  File "/home/jim/projects/0064_clamp_wire/PaddleDetection-2.6/ppdet/data/reader.py", line 168, in __call__
    self.dataset.parse_dataset()
  File "/home/jim/projects/0064_clamp_wire/PaddleDetection-2.6/ppdet/data/source/coco.py", line 241, in parse_dataset
    assert ct > 0, 'not found any coco record in %s' % (anno_path)
AssertionError: not found any coco record in coco/annotations/voc_train.json
```
恳请大佬解答，感谢。

**Comment by yuanjim** [comment]
已解决，需要把json文件中的"bbox": [xmin, ymin, w, h]补起来，就正常训练了。

**Comment by yangy996** [comment]
请问下选择框标注用的什么标注工具？

**Comment by yuanjim** [comment]
我已收到您的邮件。谢谢！

**Comment by zcj234** [comment]
我使用的是PaddleDetection 2.7，PP-YOLOE-R训练自定义数据集也报该错。其中，在json文件中，segmentation是旋转框的标注内容，bbox缺省。想问一下怎么解决该问题，bbox是必须要填内容吗，但我不需要bbox呀。具体标注如下：
"annotations": [
        {
            "area": 54880,
            "iscrowd": 0,
            "image_id": 24007,
            "bbox": [],
            "segmentation": [
                [
                    342.0598599268317,
                    810.4164476649078,
                    235.08633567315994,
                    843.5927209449058,
                    89.94014007316835,
                    375.58355233509224,
                    196.91366432684006,
                    342.40727905509414
                ]
            ],
            "category_id": 1,
            "id": 1,
            "ignore": 0
        },
        {
            "area": 53568,
            "iscrowd": 0,
            "image_id": 10918,
            "bbox": [],
            "segmentation": [
                [
                    407.28572618889916,
                    570.3518051410618,
                    430.358464660711,
                    663.5379024915325,
                    -111.28572618889919,
                    797.6481948589382,
                    -134.35846466071095,
                    704.4620975084675
                ]
            ],
            "category_id": 1,
            "id": 2,
            "ignore": 0
        },
