### ISSUE TITLE
训练的num_works=6，在最后一轮训练结束后，模型正常保存，但是在结束进程的时候，出现Exception in thread Thread-5:

### ISSUE THREAD

**Issue by Cuppinono** [PaddlePaddle/PaddleDetection#8732]
### 问题确认 Search before asking

- [x] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training, Validation

### Bug描述 Describe the Bug

 Synced 6 W&B file(s), 0 media file(s), 1 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20231128_104524-c62rqjrq/logs
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/zcc-dd/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 620, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/home/dell/anaconda3/envs/zcc-dd/lib/python3.9/multiprocessing/queues.py", line 114, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/zcc-dd/lib/python3.9/threading.py", line 950, in _bootstrap_inner
    self.run()
  File "/home/dell/anaconda3/envs/zcc-dd/lib/python3.9/threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dell/anaconda3/envs/zcc-dd/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 534, in _thread_loop
    batch = self._get_data()
  File "/home/dell/anaconda3/envs/zcc-dd/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 635, in _get_data
    raise RuntimeError("DataLoader {} workers exit unexpectedly, " \
RuntimeError: DataLoader 4 workers exit unexpectedly, pids: 38424, 38425, 38426, 38434
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/zcc-dd/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 620, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/home/dell/anaconda3/envs/zcc-dd/lib/python3.9/multiprocessing/queues.py", line 114, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/zcc-dd/lib/python3.9/threading.py", line 950, in _bootstrap_inner
    self.run()
  File "/home/dell/anaconda3/envs/zcc-dd/lib/python3.9/threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dell/anaconda3/envs/zcc-dd/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 534, in _thread_loop
    batch = self._get_data()
  File "/home/dell/anaconda3/envs/zcc-dd/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 635, in _get_data
    raise RuntimeError("DataLoader {} workers exit unexpectedly, " \
RuntimeError: DataLoader 6 workers exit unexpectedly, pids: 38058, 38059, 38060, 38061, 38062, 38063
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/zcc-dd/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 620, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/home/dell/anaconda3/envs/zcc-dd/lib/python3.9/multiprocessing/queues.py", line 114, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/zcc-dd/lib/python3.9/threading.py", line 950, in _bootstrap_inner
    self.run()
  File "/home/dell/anaconda3/envs/zcc-dd/lib/python3.9/threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dell/anaconda3/envs/zcc-dd/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 534, in _thread_loop
    batch = self._get_data()
  File "/home/dell/anaconda3/envs/zcc-dd/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 635, in _get_data
    raise RuntimeError("DataLoader {} workers exit unexpectedly, " \
RuntimeError: DataLoader 4 workers exit unexpectedly, pids: 38994, 38995, 38999, 39000
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/zcc-dd/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 620, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/home/dell/anaconda3/envs/zcc-dd/lib/python3.9/multiprocessing/queues.py", line 114, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/zcc-dd/lib/python3.9/threading.py", line 950, in _bootstrap_inner
    self.run()
  File "/home/dell/anaconda3/envs/zcc-dd/lib/python3.9/threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dell/anaconda3/envs/zcc-dd/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 534, in _thread_loop
    batch = self._get_data()
  File "/home/dell/anaconda3/envs/zcc-dd/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 635, in _get_data
    raise RuntimeError("DataLoader {} workers exit unexpectedly, " \
RuntimeError: DataLoader 5 workers exit unexpectedly, pids: 39312, 39313, 39316, 39320, 39321

### 复现环境 Environment

paddle-gpu 2.3.2
paddledetection-2.7
GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.1
W1128 10:45:19.038715 37668 gpu_resources.cc:91] device: 1, cuDNN Version: 8.2

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Cuppinono** [comment]
现在确定了是wandb的问题，请尝试修复

**Comment by LokeZhou** [comment]
问题是否了得到解决？
