### ISSUE TITLE
I trained faster_crnn model but I recieved an error when it called get_loss function

### ISSUE THREAD

**Issue by TuanAnhNguyenCo** [PaddlePaddle/PaddleDetection#8759]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training

### Bug描述 Describe the Bug

/mnt/disk1/anaconda3/envs/anhnct/lib/python3.8/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
/mnt/disk1/anaconda3/envs/anhnct/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/mnt/disk1/anaconda3/envs/anhnct/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
W1218 11:49:59.975874  5014 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 10.2
W1218 11:49:59.979482  5014 gpu_resources.cc:91] device: 0, cuDNN Version: 8.1.
[12/18 11:50:01] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/aiotlabws/.cache/paddle/weights/ResNet50_cos_pretrained.pdparams
Hello
Traceback (most recent call last):
  File "tools/train.py", line 209, in <module>
    main()
  File "tools/train.py", line 205, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 158, in run
    trainer.train(FLAGS.eval)
  File "/mnt/disk1/anhnct/School/MachineLearning/Project/Traffic_Sign_Detection_paddle_faster_rcnn/PaddleDetection/ppdet/engine/trainer.py", line 577, in train
    outputs = model(data)
  File "/mnt/disk1/anaconda3/envs/anhnct/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 929, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/mnt/disk1/anaconda3/envs/anhnct/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/mnt/disk1/anhnct/School/MachineLearning/Project/Traffic_Sign_Detection_paddle_faster_rcnn/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 61, in forward
    out = self.get_loss()
  File "/mnt/disk1/anhnct/School/MachineLearning/Project/Traffic_Sign_Detection_paddle_faster_rcnn/PaddleDetection/ppdet/modeling/architectures/faster_rcnn.py", line 113, in get_loss
    rpn_loss, bbox_loss = self._forward()
  File "/mnt/disk1/anhnct/School/MachineLearning/Project/Traffic_Sign_Detection_paddle_faster_rcnn/PaddleDetection/ppdet/modeling/architectures/faster_rcnn.py", line 80, in _forward
    rois, rois_num, rpn_loss = self.rpn_head(body_feats, self.inputs)
  File "/mnt/disk1/anaconda3/envs/anhnct/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 929, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/mnt/disk1/anaconda3/envs/anhnct/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/mnt/disk1/anhnct/School/MachineLearning/Project/Traffic_Sign_Detection_paddle_faster_rcnn/PaddleDetection/ppdet/modeling/proposal_generator/rpn_head.py", line 141, in forward
    rois, rois_num = self._gen_proposal(scores, deltas, anchors, inputs)
  File "/mnt/disk1/anhnct/School/MachineLearning/Project/Traffic_Sign_Detection_paddle_faster_rcnn/PaddleDetection/ppdet/modeling/proposal_generator/rpn_head.py", line 206, in _gen_proposal
    rpn_rois, rpn_rois_prob, rpn_rois_num, post_nms_top_n = prop_gen(
  File "/mnt/disk1/anhnct/School/MachineLearning/Project/Traffic_Sign_Detection_paddle_faster_rcnn/PaddleDetection/ppdet/modeling/proposal_generator/proposal_generator.py", line 70, in __call__
    rpn_rois, rpn_rois_prob, rpn_rois_num = generate_proposals(
  File "/mnt/disk1/anhnct/School/MachineLearning/Project/Traffic_Sign_Detection_paddle_faster_rcnn/PaddleDetection/ppdet/modeling/ops.py", line 1014, in generate_proposals
    rpn_rois, rpn_roi_probs, rpn_rois_num = C_ops.generate_proposals_v2(
RuntimeError: (PreconditionNotMet) The Tensor's element number must be equal or greater than zero. The Tensor's shape is [-1138971471, 4] now
  [Hint: Expected numel() >= 0, but received numel():-4555885884 < 0:0.] (at /paddle/paddle/phi/core/dense_tensor_impl.cc:108)
  [operator < generate_proposals_v2 > error]

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
paddledet的版本是那个
