### ISSUE TITLE
请问这个错误是怎么回事cuda12.0  cudnn 8.9.1

### ISSUE THREAD

**Issue by QL-AR** [PaddlePaddle/PaddleDetection#8766]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

(PaddlePaddle) PS G:\PaddleDetection-release-2.7> python deploy/python/infer.py --model_dir=inference_model/ppyoloe_crn_s_300e_coco --camera_id=0 --device=GPU
-----------  Running Arguments -----------
action_file: None
batch_size: 1
camera_id: 0
collect_trt_shape_info: False
combine_method: nms
cpu_threads: 1
device: GPU
enable_mkldnn: False
enable_mkldnn_bfloat16: False
image_dir: None
image_file: None
match_metric: ios
match_threshold: 0.6
model_dir: inference_model/ppyoloe_crn_s_300e_coco
output_dir: output
overlap_ratio: [0.25, 0.25]
random_pad: False
reid_batch_size: 50
reid_model_dir: None
run_benchmark: False
run_mode: paddle
save_images: True
save_mot_txt_per_img: False
save_mot_txts: False
save_results: False
scaled: False
slice_infer: False
slice_size: [640, 640]
threshold: 0.5
tracker_config: None
trt_calib_mode: False
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
tuned_trt_shape_file: shape_range_info.pbtxt
use_coco_category: False
use_dark: True
use_fd_format: False
use_gpu: False
video_file: None
window_size: 50
------------------------------------------
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order:
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
fps: 30, frame_count: -1
detect frame: 1
Traceback (most recent call last):
  File "G:\PaddleDetection-release-2.7\deploy\python\infer.py", line 1228, in <module>
    main()
  File "G:\PaddleDetection-release-2.7\deploy\python\infer.py", line 1179, in main
    detector.predict_video(FLAGS.video_file, FLAGS.camera_id)
  File "G:\PaddleDetection-release-2.7\deploy\python\infer.py", line 457, in predict_video
    results = self.predict_image([frame[:, :, ::-1]], visual=False)
  File "G:\PaddleDetection-release-2.7\deploy\python\infer.py", line 406, in predict_image
    result = self.predict()
  File "G:\PaddleDetection-release-2.7\deploy\python\infer.py", line 206, in predict
    self.predictor.run()
OSError: In user code:

    File "G:\PaddleDetection\tools\export_model.py", line 111, in <module>
      main()
    File "G:\PaddleDetection\tools\export_model.py", line 107, in main
      run(FLAGS, cfg)
    File "G:\PaddleDetection\tools\export_model.py", line 73, in run
      trainer.export(FLAGS.output_dir)
    File "G:\PaddleDetection\ppdet\engine\trainer.py", line 718, in export
      static_model, pruned_input_spec = self._get_infer_cfg_and_input_spec(
    File "G:\PaddleDetection\ppdet\engine\trainer.py", line 696, in _get_infer_cfg_and_input_spec
      input_spec, static_model.forward.main_program,
    File "H:\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 563, in main_program
      concrete_program = self.concrete_program
    File "H:\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 479, in concrete_program
      return self.concrete_program_specify_input_spec(input_spec=None)
    File "H:\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 516, in concrete_program_specify_input_spec
      concrete_program, _ = self.get_concrete_program(
    File "H:\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 427, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "H:\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 723, in __getitem__
      self._caches[item] = self._build_once(item)
    File "H:\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 709, in _build_once
      concrete_program = ConcreteProgram.from_func_spec(
    File "H:\Anaconda3\envs\PaddleDetection\lib\site-packages\decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "H:\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "H:\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "H:\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 662, in from_func_spec
      outputs = static_func(*inputs)
    File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp3nip284b.py", line 99, in forward
      out = paddle.jit.dy2static.convert_ifelse(self.training, true_fn_5,
    File "H:\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "H:\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp3nip284b.py", line 82, in false_fn_5
      ] = paddle.jit.dy2static.convert_while_loop(for_loop_condition_0,
    File "H:\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 45, in convert_while_loop
      loop_vars = _run_py_while(cond, body, loop_vars)
    File "H:\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 59, in _run_py_while
      loop_vars = body(*loop_vars)
    File "G:\PaddleDetection\ppdet\modeling\architectures\meta_arch.py", line 74, in forward
      self.inputs = inp
    File "G:\PaddleDetection\ppdet\modeling\architectures\yolo.py", line 128, in get_pred
      return self._forward()
    File "C:\Users\ADMINI~1\AppData\Local\Temp\tmph7jbsgl9.py", line 112, in _forward
      __return_value_0 = paddle.jit.dy2static.convert_ifelse(self.training,
    File "H:\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "H:\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "C:\Users\ADMINI~1\AppData\Local\Temp\tmph7jbsgl9.py", line 105, in false_fn_11
      bbox, bbox_num, output = paddle.jit.dy2static.convert_ifelse(self.
    File "H:\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "H:\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "C:\Users\ADMINI~1\AppData\Local\Temp\tmph7jbsgl9.py", line 100, in false_fn_10
      bbox, bbox_num = paddle.jit.dy2static.convert_ifelse(self.
    File "H:\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "H:\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "C:\Users\ADMINI~1\AppData\Local\Temp\tmph7jbsgl9.py", line 96, in false_fn_9
      bbox, bbox_num = paddle.jit.dy2static.convert_ifelse(self.
    File "H:\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "H:\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "G:\PaddleDetection\ppdet\modeling\architectures\yolo.py", line 117, in _forward
      bbox, bbox_num = self.yolo_head.post_process(
    File "C:\Users\ADMINI~1\AppData\Local\Temp\tmp9esh07ju.py", line 35, in post_process
      __return_value_3 = paddle.jit.dy2static.convert_ifelse(self.exclude_nms,
    File "H:\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "H:\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "G:\PaddleDetection\ppdet\modeling\heads\ppyoloe_head.py", line 377, in post_process
      return pred_bboxes.sum(), pred_scores.sum()
    File "G:\PaddleDetection\ppdet\modeling\layers.py", line 474, in __call__
      return ops.multiclass_nms(bboxes, score, **kwargs)
    File "G:\PaddleDetection\ppdet\modeling\ops.py", line 1034, in multiclass_nms
      helper.append_op(
    File "H:\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "H:\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\framework.py", line 3178, in append_op
      op = Operator(
    File "H:\Anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

    ExternalError: CUDA error(209), no kernel image is available for execution on the device.
      [Hint: 'cudaErrorNoKernelImageForDevice'. This indicates that there is no kernel image available that is suitable for the device. This can occur when a user specifiescode generation options for a particular CUDA source file that do not include the corresponding device configuration.] (at C:\home\workspace\Paddle\paddle\phi\kernels\gpu\multiclass_nms3_kernel.cu:606)
      [operator < multiclass_nms3 > error]
[ WARN:0@60.843] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (539) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback

**Comment by lyuwenyu** [comment]
用的paddle的版本是那个,  老版本`multiclass_nms3`没有gpu的kernel

**Comment by QL-AR** [comment]
那个版本是新的

**Comment by QL-AR** [comment]
不是2.6的吗

**Comment by LokeZhou** [comment]
可以试一下paddle2.5

**Comment by dichaoGit** [comment]
同问， 这个应该怎么解决呢？
