### ISSUE TITLE
切图脚本执行报错

### ISSUE THREAD

**Issue by David-dotcom666** [PaddlePaddle/PaddleDetection#8773]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training

### Bug描述 Describe the Bug

"""执行 python tools/slice_image.py --image_dir dataset/cocome/train --json_path dataset/cocome/annotations/instance_train.json --output_dir dataset/IMG_sliced --slice_size 640 --overlap_ratio 0.25
报错：
Slicing step is starting...
indexing coco dataset annotations...
Loading coco annotations: 100%|█████████████| 793/793 [00:00<00:00, 1257.94it/s]
 15%|█████▉                                   | 115/793 [00:27<02:40,  4.22it/s]
Traceback (most recent call last):
  File "/home/aistudio/work/PaddleDetection/tools/slice_image.py", line 56, in <module>
    main()
  File "/home/aistudio/work/PaddleDetection/tools/slice_image.py", line 51, in main
    slice_data(args.image_dir, args.json_path, args.output_dir, args.slice_size,
  File "/home/aistudio/work/PaddleDetection/tools/slice_image.py", line 29, in slice_data
    slice(
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/sahi/scripts/slice_coco.py", line 47, in slice
    coco_dict, coco_path = slice_coco(
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/sahi/slicing.py", line 478, in slice_coco
    slice_image_result = slice_image(
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/sahi/slicing.py", line 365, in slice_image
    sliced_coco_annotation_list = process_coco_annotations(coco_annotation_list, slice_bbox, min_area_ratio)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/sahi/slicing.py", line 142, in process_coco_annotations
    sliced_coco_annotation = coco_annotation.get_sliced_coco_annotation(slice_bbox)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/sahi/utils/coco.py", line 232, in get_sliced_coco_annotation
    valid = MultiPolygon([valid])
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/shapely/geometry/multipolygon.py", line 79, in __new__
    shell = ob[0]
TypeError: 'GeometryCollection' object is not subscriptable"""
数据集是自定义的，使用FasterRCNN/YOLOE+/rtdert都训练过

### 复现环境 Environment

环境1：
Aistudio/PaddlePaddle2.6.0/paddledetection2.7/
环境2：
windows11
W1228 08:57:31.629164 11152 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.7, Runtime API Version: 11.7
W1228 08:57:31.632164 11152 gpu_resources.cc:91] device: 0, cuDNN Version: 8.8.
PaddlePaddle2.4.2/paddledetection2.7/

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by David-dotcom666** [comment]
我试了Aistudio上的官方项目：https://aistudio.baidu.com/projectdetail/5036782?channelType=0&channel=0
执行切图时没有报错，但是切出的图都是0byte

**Comment by lyuwenyu** [comment]
是给的demo也跑不了嘛？

**Comment by David-dotcom666** [comment]
是的，我是修改了https://github.com/PaddlePaddle/PaddleDetection/issues/8768#issuecomment-1870929378，可以跑

**Comment by haoaZ** [comment]
您好在Aistudio上的官方项目能改sahi代码吗，我没有找到Lib\site-packages\sahi@David-dotcom666
