### ISSUE TITLE
昆仑芯XPU R200训练MOT目标跟踪模型报错 

### ISSUE THREAD

**Issue by tzhang2014** [PaddlePaddle/PaddleDetection#8779]
系统环境/System Environment：
Linux localhost.localdomain 4.19.90-23.32.v2101.ky10.aarch64
版本号/Version：
Paddle： paddlepaddle-xpu==2.5.0
PaddleDetection： release/2.7
问题相关组件/Related components：
运行指令/Command Code：
XPU_VISIBLE_DEVICES=0 python tools/train.py -c configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml
完整报错:
(paddleDet) [root@localhost PaddleDetection]# sh run_train.sh 
XPURT /root/miniforge3/envs/paddleDet/lib/python3.8/site-packages/paddle/fluid/../libs/libxpurt.so.1 loaded
XCCL /root/miniforge3/envs/paddleDet/lib/python3.8/site-packages/paddle/fluid/../libs/libbkcl.so loaded
[16:30:29][INFO][BKCL][globals.cpp:95] set BKCL timeout to 600 seconds
[16:30:29][INFO][BKCL][globals.cpp:96] set BKCL RING BUFFER SIZE to 1048576
XPURT /root/miniforge3/envs/paddleDet/lib/python3.8/site-packages/paddle/fluid/../libs/libxpurt.so loaded
[01/02 16:30:34] ppdet.data.source.mot INFO: MOT dataset summary: 
[01/02 16:30:34] ppdet.data.source.mot INFO: OrderedDict([('mot16.train', 55)])
[01/02 16:30:34] ppdet.data.source.mot INFO: Total images: 600
[01/02 16:30:34] ppdet.data.source.mot INFO: Image start index: OrderedDict([('mot16.train', 0)])
[01/02 16:30:34] ppdet.data.source.mot INFO: Total identities: 56
[01/02 16:30:34] ppdet.data.source.mot INFO: Identity start index: OrderedDict([('mot16.train', 0)])
XPURT /root/miniforge3/envs/paddleDet/lib/python3.8/site-packages/paddle/fluid/../libs/libxpurt.so.1 loaded
XCCL /root/miniforge3/envs/paddleDet/lib/python3.8/site-packages/paddle/fluid/../libs/libbkcl.so loaded
[16:30:36][INFO][BKCL][globals.cpp:95] set BKCL timeout to 600 seconds
[16:30:36][INFO][BKCL][globals.cpp:96] set BKCL RING BUFFER SIZE to 1048576
XPURT /root/miniforge3/envs/paddleDet/lib/python3.8/site-packages/paddle/fluid/../libs/libxpurt.so loaded
XPURT /root/miniforge3/envs/paddleDet/lib/python3.8/site-packages/paddle/fluid/../libs/libxpurt.so.1 loaded
XCCL /root/miniforge3/envs/paddleDet/lib/python3.8/site-packages/paddle/fluid/../libs/libbkcl.so loaded
[16:30:36][INFO][BKCL][globals.cpp:95] set BKCL timeout to 600 seconds
[16:30:36][INFO][BKCL][globals.cpp:96] set BKCL RING BUFFER SIZE to 1048576
XPURT /root/miniforge3/envs/paddleDet/lib/python3.8/site-packages/paddle/fluid/../libs/libxpurt.so loaded
XPURT /root/miniforge3/envs/paddleDet/lib/python3.8/site-packages/paddle/fluid/../libs/libxpurt.so.1 loaded
XCCL /root/miniforge3/envs/paddleDet/lib/python3.8/site-packages/paddle/fluid/../libs/libbkcl.so loaded
[16:30:37][INFO][BKCL][globals.cpp:95] set BKCL timeout to 600 seconds
[16:30:37][INFO][BKCL][globals.cpp:96] set BKCL RING BUFFER SIZE to 1048576
XPURT /root/miniforge3/envs/paddleDet/lib/python3.8/site-packages/paddle/fluid/../libs/libxpurt.so loaded
XPURT /root/miniforge3/envs/paddleDet/lib/python3.8/site-packages/paddle/fluid/../libs/libxpurt.so.1 loaded
XCCL /root/miniforge3/envs/paddleDet/lib/python3.8/site-packages/paddle/fluid/../libs/libbkcl.so loaded
[16:30:37][INFO][BKCL][globals.cpp:95] set BKCL timeout to 600 seconds
[16:30:37][INFO][BKCL][globals.cpp:96] set BKCL RING BUFFER SIZE to 1048576
XPURT /root/miniforge3/envs/paddleDet/lib/python3.8/site-packages/paddle/fluid/../libs/libxpurt.so loaded
[01/02 16:30:39] ppdet.utils.checkpoint INFO: The shape [14455] in pretrained weight reid.classifier.bias is unmatched with the shape [56] in model reid.classifier.bias. And the weight reid.classifier.bias will not be loaded
[01/02 16:30:39] ppdet.utils.checkpoint INFO: The shape [128, 14455] in pretrained weight reid.classifier.weight is unmatched with the shape [128, 56] in model reid.classifier.weight. And the weight reid.classifier.weight will not be loaded
[01/02 16:30:39] ppdet.utils.checkpoint INFO: Finish loading model weights: /root/.cache/paddle/weights/fairmot_dla34_crowdhuman_pretrained.pdparams
Traceback (most recent call last):
  File "/root/miniforge3/envs/paddleDet/lib/python3.8/site-packages/multiprocess/queues.py", line 242, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/root/miniforge3/envs/paddleDet/lib/python3.8/site-packages/multiprocess/reduction.py", line 54, in dumps
    cls(buf, protocol, *args, **kwds).dump(obj)
  File "/root/miniforge3/envs/paddleDet/lib/python3.8/site-packages/dill/_dill.py", line 498, in dump
    StockPickler.dump(self, obj)
  File "/root/miniforge3/envs/paddleDet/lib/python3.8/pickle.py", line 487, in dump
    self.save(obj)
  File "/root/miniforge3/envs/paddleDet/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/root/miniforge3/envs/paddleDet/lib/python3.8/pickle.py", line 886, in save_tuple
    save(element)
  File "/root/miniforge3/envs/paddleDet/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/root/miniforge3/envs/paddleDet/lib/python3.8/pickle.py", line 931, in save_list
    self._batch_appends(obj)
  File "/root/miniforge3/envs/paddleDet/lib/python3.8/pickle.py", line 955, in _batch_appends
    save(x)
  File "/root/miniforge3/envs/paddleDet/lib/python3.8/pickle.py", line 578, in save
    rv = reduce(self.proto)
RuntimeError: (PreconditionNotMet) Tensor is not in shared memory.Now only Tensor on shared memory can be serialized.
  [Hint: mmap_writer_allocation should not be null.] (at /workspace/paddle/fluid/pybind/tensor.cc:991)

**Comment by lyuwenyu** [comment]
其他模型可以跑嘛   建议在 https://github.com/PaddlePaddle/Paddle/issues 也问一下
