### ISSUE TITLE
VIT Backbone的PPYOLOE是否能蒸馏CRN Backbone的PP-YOLOE+

### ISSUE THREAD

**Issue by guzichen** [PaddlePaddle/PaddleDetection#8781]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我测试了distill中的ppyoloe_plus_distill_l_distill_m等几个crn架构的PPYOLOE+的蒸馏，都没有问题。当我尝试使用ppyoloe_vit_base_csppan_cae_36e_coco模型作为teacher去蒸馏ppyoloe_crn_s时，会报错显示维度不一致。报错如下。看了一下报错应该是neck输出不一致导致的，vit的PPYOLOE使用的是YOLOCSPPAN，而crn使用的是CustomPAN。

是否有办法可以让VIT Backbone的PPYOLOE蒸馏CRN Backbone的PP-YOLOE+？
```
``Traceback (most recent call last):
  File "/home/user/PaddleDetection/tools/train.py", line 202, in <module>
    main()
  File "/home/user/PaddleDetection/tools/train.py", line 198, in main
    run(FLAGS, cfg)
  File "/home/user/PaddleDetection/tools/train.py", line 151, in run
    trainer.train(FLAGS.eval)
  File "/home/user/PaddleDetection/ppdet/engine/trainer.py", line 577, in train
    outputs = model(data)
  File "/home/user/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/user/PaddleDetection/ppdet/slim/distill_model.py", line 343, in forward
    logits_loss, feat_loss = self.distill_loss(self.teacher_model,
  File "/home/user/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/user/PaddleDetection/ppdet/slim/distill_loss.py", line 380, in forward
    self.bbox_loss(student_distill_pairs['pred_bboxes_pos'],
  File "/home/user/PaddleDetection/ppdet/slim/distill_loss.py", line 319, in bbox_loss
    loss = paddle.sum(self.loss_bbox(s_bbox, t_bbox) * weight_targets)
  File "/home/user/PaddleDetection/ppdet/modeling/losses/iou_loss.py", line 118, in __call__
    iou, overlap, union = self.bbox_overlap(box1, box2, self.eps)
  File "/home/user/PaddleDetection/ppdet/modeling/losses/iou_loss.py", line 98, in bbox_overlap
    xkis1 = paddle.maximum(x1, x1g)
  File "/home/user/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/tensor/math.py", line 1110, in maximum
    return _C_ops.maximum(x, y)
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [169, 1] and the shape of Y = [159, 1]. Received [169] in X is not equal to [159] in Y at i:0.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at ../paddle/phi/kernels/funcs/common_shape.h:86)
```

是否有办法可以让VIT Backbone的PPYOLOE蒸馏CRN Backbone的PP-YOLOE+？
使用Paddle版本为2.5，Paddledetection为2.7，蒸馏时关闭了feat_distill，只保留logits_distill和logits_ld_distill。蒸馏配置如下：
```
# teacher and slim config
_BASE_: [
  './ppyoloe_vit_base_csppan_cae_36e_kj.yml',
]
depth_mult: 1.0
width_mult: 1.0
for_distill: True
architecture: PPYOLOE
PPYOLOE:
  backbone: VisionTransformer
  neck: YOLOCSPPAN
  yolo_head: PPYOLOEHead
  post_process: ~

pretrain_weights: '/home/user/PaddleDetection/output/ppyoloe_vit_base_csppan_cae_36e_kj/model_final.pdparams'
find_unused_parameters: True

worker_num: 4
TrainReader:
  sample_transforms:
    - Decode: {}
    - RandomDistort: {}
    - RandomExpand: {fill_value: [123.675, 116.28, 103.53]}
    - RandomCrop: {}
    - RandomFlip: {}
  batch_transforms:
    - BatchRandomResize: {target_size: [640], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
    - PadGT: {}
  batch_size: 8
  shuffle: True
  drop_last: True
  use_shared_memory: True
  collate_batch: True


slim: Distill
slim_method: PPYOLOEDistill
distill_loss: DistillPPYOLOELoss

DistillPPYOLOELoss: # L -> S
  loss_weight: {'logits': 4.0, 'feat': 1.0}
  logits_distill: True
  logits_loss_weight: {'class': 1.0, 'iou': 2.5, 'dfl': 0.5}
  logits_ld_distill: True
  logits_ld_params: {'weight': 20000, 'T': 10}
  feat_distill: False
  feat_distiller: 'fgd' # ['cwd', 'fgd', 'pkd', 'mgd', 'mimic']
  feat_distill_place: 'neck_feats'
  teacher_width_mult: 1.0  # L
  student_width_mult: 0.5  # S
  feat_out_channels: [768, 384, 192]  # The actual channel will multiply width_mult
```

**Comment by guzichen** [comment]
解决了，把vit的ppyoloe的neck换成CustomPAN就能蒸了
