### ISSUE TITLE
PPYOLOE训练自己的数据集报错

### ISSUE THREAD

**Issue by skming666** [PaddlePaddle/PaddleDetection#8806]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

利用自己的voc数据训练报错
oot@107491c2bfc6:/workspace/PaddleDetection# python tools/train.py -c configs/ppyoloe/ppyoloe_plus_crn_s_80e_voc.yml 
[01/30 09:01:35] reader WARNING: Shared memory size is less than 1G, disable shared_memory in DataLoader
W0130 09:01:35.799360 12216 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.0, Runtime API Version: 10.2
W0130 09:01:35.804332 12216 gpu_resources.cc:91] device: 0, cuDNN Version: 8.0.
[01/30 09:01:42] ppdet.engine INFO: Epoch: [0] [  0/350] learning_rate: 0.000000 loss: 0.000000 loss_cls: 183.144653 loss_iou: 0.000000 loss_dfl: 0.000000 loss_l1: 0.000000 eta: 1 day, 20:45:41 batch_cost: 5.7551 data_cost: 1.3438 ips: 0.3475 images/s
Traceback (most recent call last):
  File "tools/train.py", line 204, in <module>
    main()
  File "tools/train.py", line 200, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 153, in run
    trainer.train(FLAGS.eval)
  File "/workspace/PaddleDetection/ppdet/engine/trainer.py", line 542, in train
    outputs = model(data)
  File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/workspace/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 60, in forward
    out = self.get_loss()
  File "/workspace/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 147, in get_loss
    return self._forward()
  File "/workspace/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 93, in _forward
    yolo_losses = self.yolo_head(neck_feats, self.inputs)
  File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/workspace/PaddleDetection/ppdet/modeling/heads/ppyoloe_head.py", line 264, in forward
    return self.forward_train(feats, targets, aux_pred)
  File "/workspace/PaddleDetection/ppdet/modeling/heads/ppyoloe_head.py", line 198, in forward_train
    return self.get_loss([
  File "/workspace/PaddleDetection/ppdet/modeling/heads/ppyoloe_head.py", line 453, in get_loss
    assign_out_dict = self.get_loss_from_assign(
  File "/workspace/PaddleDetection/ppdet/modeling/heads/ppyoloe_head.py", line 498, in get_loss_from_assign
    self._bbox_loss(pred_distri, pred_bboxes, anchor_points_s,
  File "/workspace/PaddleDetection/ppdet/modeling/heads/ppyoloe_head.py", line 342, in _bbox_loss
    pred_bboxes_pos = paddle.masked_select(pred_bboxes,
  File "/opt/conda/lib/python3.8/site-packages/paddle/tensor/manipulation.py", line 2139, in reshape
    return paddle.fluid.layers.reshape(x=x, shape=shape, name=name)
  File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/layers/nn.py", line 6373, in reshape
    out, _ = _C_ops.reshape2(x, None, 'shape', shape)
RuntimeError: (PreconditionNotMet) The meta data must be valid when call the mutable data function. (at /paddle/paddle/phi/core/dense_tensor.cc:105)
  [operator < reshape2 > error]

**Comment by lyuwenyu** [comment]
> pred_bboxes_pos = paddle.masked_select(pred_bboxes,

可以在报错的位置打印一下输入
