### ISSUE TITLE
导出rtdetr的训练模型时出现错误

### ISSUE THREAD

**Issue by nothingws** [PaddlePaddle/PaddleDetection#8815]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\PaddleDetection-release-2.7\tools\export_model.py", line 118, in <module>
    main()
  File "C:\Users\Administrator\PycharmProjects\PaddleDetection-release-2.7\tools\export_model.py", line 114, in main
    run(FLAGS, cfg)
  File "C:\Users\Administrator\PycharmProjects\PaddleDetection-release-2.7\tools\export_model.py", line 80, in run
    trainer.export(FLAGS.output_dir, for_fd=FLAGS.for_fd)
  File "C:\Users\Administrator\PycharmProjects\PaddleDetection-release-2.7\ppdet\engine\trainer.py", line 1229, in export
    static_model, pruned_input_spec = self._get_infer_cfg_and_input_spec(
  File "C:\Users\Administrator\PycharmProjects\PaddleDetection-release-2.7\ppdet\engine\trainer.py", line 1181, in _get_infer_cfg_and_input_spec
    input_spec, static_model.forward.main_program,
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\jit\dy2static\program_translator.py", line 768, in main_program
    raise_error_template("main_program")()
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\jit\dy2static\program_translator.py", line 704, in _raise_error
    raise RuntimeError(error_template.format(func=func_str))
RuntimeError: Can't call main_program when full_graph=False. Use paddle.jit.to_static(full_graph=True) instead.

**Comment by lyuwenyu** [comment]
> RuntimeError: Can't call main_program when full_graph=False. Use paddle.jit.to_static(full_graph=True) instead.

https://github.com/PaddlePaddle/PaddleDetection/pull/8762/files 
可以先按照这个pr修改了
