### ISSUE TITLE
出错：```The conv2d_fusion Op's Input Variable Input contains uninitialized Tensor.```模型训练完导出的模型(model.pdiparams)在代码中应该如何正确使用？

### ISSUE THREAD

**Issue by BarryAlllen** [PaddlePaddle/PaddleDetection#8852]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

这是我的文件内容：
infer_cfg.yml:
```
mode: paddle
draw_threshold: 0.5
metric: COCO
use_dynamic_shape: false
arch: DETR
min_subgraph_size: 3
Preprocess:
- interp: 2
  keep_ratio: false
  target_size:
  - 640
  - 640
  type: Resize
- mean:
  - 0.0
  - 0.0
  - 0.0
  norm_type: none
  std:
  - 1.0
  - 1.0
  - 1.0
  type: NormalizeImage
- type: Permute
label_list:
xxx
```

预测模型的代码：
```
import cv2
import paddle.inference as paddle_infer
import numpy as np

def load_model(model_dir, use_gpu=True):
    # 配置模型
    config = paddle_infer.Config(model_dir + "/model.pdmodel", model_dir + "/model.pdiparams")
    if use_gpu:
        # 启用GPU
        config.enable_use_gpu(100, 0)
    else:
        # 使用CPU
        config.disable_gpu()

    # 启用内存优化
    config.enable_memory_optim()

    # 创建预测器
    predictor = paddle_infer.create_predictor(config)
    return predictor


def run_inference(predictor, input_data):
    input_names = predictor.get_input_names()
    print(f'input_names: {input_names}')
    input_handle = predictor.get_input_handle(input_names[0])
    input_handle.reshape(input_data.shape)
    input_handle.copy_from_cpu(input_data)
    print(f'input_data shape: {input_data.shape}')

    # 运行推理
    predictor.run()

    # 获取输出
    output_names = predictor.get_output_names()
    output_handle = predictor.get_output_handle(output_names[0])
    output_data = output_handle.copy_to_cpu()
    return output_data

def preprocess_image(image_path, input_size=(640, 640)):
    """
    图片预处理：读取、调整大小、归一化
    :param image_path: 图片文件路径
    :param input_size: 输入图片的尺寸，以元组(height, width)的形式
    :return: 预处理后的图片数据
    """
    image = cv2.imread(image_path)
    if image is None:
        raise FileNotFoundError("Image not found: {}".format(image_path))

    # 调整图片大小
    image = cv2.resize(image, input_size)

    # BGR转RGB，Paddle模型通常使用RGB格式
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # 归一化
    image = image.astype('float32') / 255.0

    # HWC转CHW格式
    image = image.transpose((2, 0, 1))

    # 添加批次维度
    image = np.expand_dims(image, axis=0)
    return image

# 加载模型
model_dir = "/projects/code/PaddleYOLO/inference_model/rtdetr_r101vd_6x_coco"  # 模型文件目录
predictor = load_model(model_dir, use_gpu=True)  # 根据需要设置use_gpu

# 准备输入数据，这里需要根据实际模型的输入进行调整
img_path = "/projects/datasets/valve_coco/JPEGImages/IMG_20240226_111740.jpg"
input_data = preprocess_image(img_path,(640, 640))

# 执行推理
result = run_inference(predictor, input_data)

# 处理推理结果
print(result)
```

报错:
```
Traceback (most recent call last):
  File "/projects/code/PaddleYOLO/tools/test.py", line 94, in <module>
    result = run_inference(predictor, input_data)
  File "/projects/code/PaddleYOLO/tools/test.py", line 49, in run_inference
    predictor.run()
ValueError: (InvalidArgument) The conv2d_fusion Op's Input Variable `Input` contains uninitialized Tensor.
  [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at /paddle/paddle/fluid/framework/operator.cc:2411)
  [operator < conv2d_fusion > error]
```

**Comment by EvW1998** [comment]
您好，我也遇到了类似的错误。请问您最终解决这个问题了吗
