### ISSUE TITLE
faster_rcnn模型测试集测试完成后评估结果时报错json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by 1415984987** [PaddlePaddle/PaddleDetection#886]
报错输出的结果如下：
2020-06-06 12:53:03,833-INFO: 4000 samples in file Dataset/voc/val.txt
2020-06-06 12:53:03,834-INFO: places would be ommited when DataLoader is not iterable
W0606 12:53:03.923831 29403 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 9.0
W0606 12:53:03.928755 29403 device_context.cc:260] device: 0, cuDNN Version: 7.3.
2020-06-06 12:53:07,104-INFO: Loading parameters from output/faster_rcnn_se154_voc/10000...
2020-06-06 12:53:13,564-INFO: Test iter 0
2020-06-06 12:53:21,408-INFO: Test iter 100
2020-06-06 12:53:29,237-INFO: Test iter 200
2020-06-06 12:53:37,037-INFO: Test iter 300
2020-06-06 12:53:44,777-INFO: Test iter 400
2020-06-06 12:53:52,501-INFO: Test iter 500
2020-06-06 12:54:00,237-INFO: Test iter 600
2020-06-06 12:54:07,959-INFO: Test iter 700
2020-06-06 12:54:15,675-INFO: Test iter 800
2020-06-06 12:54:23,409-INFO: Test iter 900
2020-06-06 12:54:31,169-INFO: Test iter 1000
2020-06-06 12:54:38,980-INFO: Test iter 1100
2020-06-06 12:54:46,852-INFO: Test iter 1200
2020-06-06 12:54:54,640-INFO: Test iter 1300
2020-06-06 12:55:02,397-INFO: Test iter 1400
2020-06-06 12:55:10,215-INFO: Test iter 1500
2020-06-06 12:55:18,008-INFO: Test iter 1600
2020-06-06 12:55:25,797-INFO: Test iter 1700
2020-06-06 12:55:33,573-INFO: Test iter 1800
2020-06-06 12:55:41,329-INFO: Test iter 1900
2020-06-06 12:55:49,053-INFO: Test iter 2000
2020-06-06 12:55:56,789-INFO: Test iter 2100
2020-06-06 12:56:04,686-INFO: Test iter 2200
2020-06-06 12:56:12,563-INFO: Test iter 2300
2020-06-06 12:56:20,382-INFO: Test iter 2400
2020-06-06 12:56:28,198-INFO: Test iter 2500
2020-06-06 12:56:35,997-INFO: Test iter 2600
2020-06-06 12:56:43,762-INFO: Test iter 2700
2020-06-06 12:56:51,633-INFO: Test iter 2800
2020-06-06 12:56:59,564-INFO: Test iter 2900
2020-06-06 12:57:07,313-INFO: Test iter 3000
2020-06-06 12:57:15,076-INFO: Test iter 3100
2020-06-06 12:57:22,815-INFO: Test iter 3200
2020-06-06 12:57:30,563-INFO: Test iter 3300
2020-06-06 12:57:38,324-INFO: Test iter 3400
2020-06-06 12:57:46,197-INFO: Test iter 3500
2020-06-06 12:57:53,968-INFO: Test iter 3600
2020-06-06 12:58:01,922-INFO: Test iter 3700
2020-06-06 12:58:09,731-INFO: Test iter 3800
2020-06-06 12:58:17,501-INFO: Test iter 3900
2020-06-06 12:58:25,180-INFO: Test finish iter 4000
2020-06-06 12:58:25,180-INFO: Total number of images: 4000, inference time: 12.819232320486554 fps.
loading annotations into memory...
Traceback (most recent call last):
  File "PaddleDetection/tools/eval.py", line 190, in <module>
    main()
  File "PaddleDetection/tools/eval.py", line 173, in main
    dataset=dataset)
  File "/home/aistudio/PaddleDetection/ppdet/utils/eval_utils.py", line 209, in eval_results
    is_bbox_normalized=is_bbox_normalized)
  File "/home/aistudio/PaddleDetection/ppdet/utils/coco_eval.py", line 74, in bbox_eval
    coco_gt = COCO(anno_file)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/pycocotools/coco.py", line 84, in __init__
    dataset = json.load(open(annotation_file, 'r'))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by 1415984987** [comment]
配置错误，配置文metric: COCO改为VOC。。。。
