### ISSUE TITLE
ValueError: all input arrays must have the same shape and stuck at Adding OutScale op:

### ISSUE THREAD

**Issue by mahesh11T** [PaddlePaddle/PaddleDetection#8903]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Other

### Bug描述 Describe the Bug

py'''python run.py --config_path deploy\auto_compression\configs\ppyoloe_plus_s_qat_dis.yaml --save_dir output1'''
above with custom coco dataset

shell''' 2024-04-02 12:44:20,667-INFO: devices: gpu
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Fstech\anaconda3\envs\aivision\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\Fstech\anaconda3\envs\aivision\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Fstech\anaconda3\envs\aivision\lib\site-packages\paddle\io\dataloader\dataloader_iter.py", line 235, in _thread_loop
    batch = self._dataset_fetcher.fetch(
  File "C:\Users\Fstech\anaconda3\envs\aivision\lib\site-packages\paddle\io\dataloader\fetcher.py", line 86, in fetch
    data = self.collate_fn(data)
  File "C:\Users\Fstech\anaconda3\envs\aivision\lib\site-packages\ppdet\data\reader.py", line 96, in __call__
    batch_data = default_collate_fn(data)
  File "C:\Users\Fstech\anaconda3\envs\aivision\lib\site-packages\ppdet\data\utils.py", line 60, in default_collate_fn
    return {
  File "C:\Users\Fstech\anaconda3\envs\aivision\lib\site-packages\ppdet\data\utils.py", line 61, in <dictcomp>
    key: default_collate_fn([d[key] for d in batch])
  File "C:\Users\Fstech\anaconda3\envs\aivision\lib\site-packages\ppdet\data\utils.py", line 52, in default_collate_fn
    batch = np.stack(batch, axis=0)
  File "C:\Users\Fstech\anaconda3\envs\aivision\lib\site-packages\numpy\core\shape_base.py", line 449, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape '''

Adding OutScale op:|█████████████████████████████████████████████████| 1653/1653

stuck after this line.

### 复现环境 Environment

paddlepaddle-gpu 2.5
cuda=11.7
cudnn = 8.4

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by yr-zh** [comment]
同样的问题，请问解决了吗
