### ISSUE TITLE
SSD模型代码ssd_vgg16_300_240e_voc.yml 训练代码无法运行

### ISSUE THREAD

**Issue by Zing-desire** [PaddlePaddle/PaddleDetection#8921]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training

### Bug描述 Describe the Bug

python -m paddle.distributed.launch  tools/train.py -c configs/ssd/ssd_vgg16_300_240e_voc.yml

报错
Traceback (most recent call last):
  File "tools/train.py", line 209, in <module>
    main()
  File "tools/train.py", line 205, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 145, in run
    trainer = Trainer(cfg, mode='train')
  File "D:\zengying\code\PaddleDetection\ppdet\engine\trainer.py", line 100, in __init__
    self.loader = create('{}Reader'.format(capital_mode))(
  File "D:\zengying\code\PaddleDetection\ppdet\data\reader.py", line 168, in __call__
    self.dataset.parse_dataset()
  File "D:\zengying\code\PaddleDetection\ppdet\data\source\voc.py", line 111, in parse_dataset
    img_file, xml_file = [os.path.join(image_dir, x) \
ValueError: not enough values to unpack (expected 2, got 1)
LAUNCH INFO 2024-04-14 23:55:19,245 Exit code 1

### 复现环境 Environment

最新的ppdet 

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by lyuwenyu** [comment]
请确保数据的路径配置正确
