### ISSUE TITLE
利用anchor_cluster.py聚类yolov3 anchor报错，求助

### ISSUE THREAD

**Issue by uniquecdmx** [PaddlePaddle/PaddleDetection#9019]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

![img_v3_02bk_10b9edc6-9b4f-4e54-97f3-cf58ccec6d2g](https://github.com/PaddlePaddle/PaddleDetection/assets/40234724/bcc2191d-f144-4950-a566-1795f12a88a6)
Traceback (most recent call last):
  File "tools/anchor_cluster.py", line 249, in <module>
    main()
  File "tools/anchor_cluster.py", line 222, in main
    check_version('develop')
  File "E:\AI\PaddleDetection\ppdet\utils\check.py", line 135, in check_version
    raise Exception(err)
Exception: PaddlePaddle version develop or higher is required, or a suitable develop version is satisfied as well. 
Please make sure the version is good with your code.
求助当前版本不支持吗，需要更换什么版本，还是需要改代码呢
环境：window11、nvidia 3060 laptop GPU
CUDA 12.0 paddlepaddle 2.6.0.post120 python 3.8.18

**Comment by garbo-hsing** [comment]
请问问题解决了吗
