### ISSUE TITLE
solov2在xpu上导出静态图后无法调用xpu推理，cpu推理正常。xpu推里报错IndexError:map::at.

### ISSUE THREAD

**Issue by Zikhjm** [PaddlePaddle/PaddleDetection#9033]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Deploy

### Bug描述 Describe the Bug

执行代码：python deploy/python/infer.py --model_dir output_inference/solov2_r50_enhance_coco --image_file=../test.jpg --device=xpu
报错截图
![123](https://github.com/PaddlePaddle/PaddleDetection/assets/147693772/cee69c71-490c-4691-a76f-9c2e1c8481eb)

### 复现环境 Environment

xpu环境

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Zikhjm** [comment]
有人可以回复这个问题吗？急

**Comment by hong19860320** [comment]
export GLOG_v=5 后再跑一下试试，把完整的 log 发一下。

**Comment by Zikhjm** [comment]
export GLOG_v=5 重跑的完整log，如下：

[INFO][BKCL][/root/ONLINE_SERVICE/other/ferry/task_workspace/baidu/xpu/bkcl/src/globals.cpp:52] set BKCL timeout to 600 seconds
[INFO][BKCL][/root/ONLINE_SERVICE/other/ferry/task_workspace/baidu/xpu/bkcl/src/globals.cpp:53] set BKCL RING BUFFER SIZE to 1048576
XPURT /opt/conda/lib/python3.7/site-packages/paddle/fluid/../libs/libxpurt.so.1 loaded
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0312 15:09:09.222931 16174 pybind.cc:678] recurrent has no kernels, skip
I0312 15:09:09.222983 16174 pybind.cc:678] while has no kernels, skip
I0312 15:09:09.223018 16174 pybind.cc:678] conditional_block has no kernels, skip
I0312 15:09:09.223032 16174 pybind.cc:678] py_func has no kernels, skip
I0312 15:09:09.275463 16174 dynamic_loader.cc:198] Set paddle lib path : /opt/conda/lib/python3.7/site-packages/paddle/libs
I0312 15:09:09.830060 16174 init.cc:99] Before Parse: argc is 2, Init commandline: dummy --tryfromenv=new_executor_static_build,fraction_of_cuda_pinned_memory_to_use,search_cache_max_number,check_nan_inf_level,reader_queue_speed_test_mode,use_stream_safe_cuda_allocator,init_allocated_mem,gpugraph_load_node_list_into_hbm,inner_op_parallelism,new_executor_use_local_scope,fleet_executor_with_standalone,trt_ibuilder_cache,free_when_no_cache_hit,einsum_opt,jit_engine_type,print_sub_graph_dir,max_inplace_grad_add,gpu_memory_limit_mb,gpugraph_enable_segment_merge_grads,local_exe_sub_scope_limit,rpc_send_thread_num,gpugraph_enable_gpu_direct_access,enable_unused_var_check,new_executor_sequential_run,multiple_of_cupti_buffer_size,add_dependency_for_communication_op,use_system_allocator,fuse_parameter_memory_size,benchmark,enable_all2all_use_fp16,enable_auto_detect_gpu_topo,gpugraph_dedup_pull_push_mode,communicator_is_sgd_optimizer,fuse_parameter_groups_size,tracer_mkldnn_ops_off,new_executor_serial_run,convert_all_blocks,gpugraph_storage_mode,gpu_allocator_retry_time,sort_sum_gradient,initial_gpu_memory_in_mb,fraction_of_gpu_memory_to_use,gpugraph_debug_gpu_memory,dygraph_debug,fraction_of_cpu_memory_to_use,cpu_deterministic,reallocate_gpu_memory_in_mb,prim_enabled,new_executor_use_cuda_graph,enable_opt_get_features,check_nan_inf,gpugraph_enable_hbm_table_collision_stat,tracer_profile_fname,dist_threadpool_size,use_cuda_managed_memory,gpugraph_slot_feasign_max_num,run_kp_kernel,communicator_max_merge_var_num,new_executor_use_inplace,get_host_by_name_time,enable_tracker_all2all,new_executor_log_memory_stats,enable_api_kernel_fallback,allreduce_record_one_event,fast_eager_deletion_mode,enable_sparse_inner_gather,enable_exit_when_partial_worker,eager_delete_scope,host_trace_level,graph_metapath_split_opt,enable_auto_rdma_trans,use_pinned_memory,tensor_operants_mode,low_precision_op_list,memory_fraction_of_eager_deletion,graph_load_in_parallel,graph_get_neighbor_id,allocator_strategy,gpugraph_merge_grads_segment_size,gpugraph_sparse_table_storage_mode,gpugraph_hbm_table_load_factor,call_stack_level,rocksdb_path,use_shm_cache,control_flow_use_new_executor,npu_storage_format,eager_delete_tensor_gb,tracer_mkldnn_ops_on,static_executor_perfstat_filepath,use_autotune,pe_profile_fname,selected_xpus,free_idle_chunk,paddle_num_threads,apply_pass_to_program,use_virtual_memory_auto_growth,enable_rpc_profiler,communicator_send_queue_size,use_mkldnn,initial_cpu_memory_in_mb 
I0312 15:09:09.830305 16174 init.cc:107] After Parse: argc is 1
I0312 15:09:09.830348 16174 os_info.cc:117] SetCurrentThreadName MainThread
I0312 15:09:09.830612 16174 init.cc:273] ENV [CUSTOM_DEVICE_ROOT] is empty.
I0312 15:09:09.831471 16174 pybind.cc:2024] Initialize tensor operants successfully
I0312 15:09:09.968093 16174 amp_auto_cast.cc:106] elementwise_mul_grad 22
I0312 15:09:09.968154 16174 amp_auto_cast.cc:106] split 23
I0312 15:09:09.968164 16174 amp_auto_cast.cc:106] check_finite_and_unscale 24
I0312 15:09:09.968173 16174 amp_auto_cast.cc:106] adam 25
I0312 15:09:09.968179 16174 amp_auto_cast.cc:106] where 26
I0312 15:09:09.968185 16174 amp_auto_cast.cc:106] atan_grad 27
I0312 15:09:09.968210 16174 amp_auto_cast.cc:106] pool2d_grad 28
I0312 15:09:09.968219 16174 amp_auto_cast.cc:106] log 29
I0312 15:09:09.968230 16174 amp_auto_cast.cc:106] lookup_table_v2 30
I0312 15:09:09.968235 16174 amp_auto_cast.cc:106] momentum 31
I0312 15:09:09.968242 16174 amp_auto_cast.cc:106] memcpy_h2d 32
I0312 15:09:09.968250 16174 amp_auto_cast.cc:106] grad_add 33
I0312 15:09:09.968255 16174 amp_auto_cast.cc:106] softmax_with_cross_entropy_grad 34
I0312 15:09:09.968269 16174 amp_auto_cast.cc:106] reshape2_grad_grad 35
I0312 15:09:09.968276 16174 amp_auto_cast.cc:106] strided_slice_grad 36
I0312 15:09:09.968284 16174 amp_auto_cast.cc:106] conv3d 37
I0312 15:09:09.968290 16174 amp_auto_cast.cc:106] gaussian_random 38
I0312 15:09:09.968297 16174 amp_auto_cast.cc:106] square_grad 39
I0312 15:09:09.968303 16174 amp_auto_cast.cc:106] unfold 40
I0312 15:09:09.968308 16174 amp_auto_cast.cc:106] elementwise_sub_grad 41
I0312 15:09:09.968313 16174 amp_auto_cast.cc:106] elementwise_min 42
I0312 15:09:09.968319 16174 amp_auto_cast.cc:106] matmul_v2 43
I0312 15:09:09.968324 16174 amp_auto_cast.cc:106] fill_constant 44
I0312 15:09:09.968330 16174 amp_auto_cast.cc:106] masked_select 45
I0312 15:09:09.968340 16174 amp_auto_cast.cc:106] max_pool2d_with_index_grad 46
I0312 15:09:09.968349 16174 amp_auto_cast.cc:106] fill_any 47
I0312 15:09:09.968354 16174 amp_auto_cast.cc:106] concat 48
I0312 15:09:09.968361 16174 amp_auto_cast.cc:106] squeeze2 49
I0312 15:09:09.968366 16174 amp_auto_cast.cc:106] elementwise_div_grad 50
I0312 15:09:09.968374 16174 amp_auto_cast.cc:106] unsqueeze2_grad 51
I0312 15:09:09.968379 16174 amp_auto_cast.cc:106] coalesce_tensor 52
I0312 15:09:09.968385 16174 amp_auto_cast.cc:106] reshape2 53
I0312 15:09:09.968392 16174 amp_auto_cast.cc:106] elementwise_sub 54
I0312 15:09:09.968400 16174 amp_auto_cast.cc:106] squeeze2_grad 55
I0312 15:09:09.968405 16174 amp_auto_cast.cc:106] unstack 56
I0312 15:09:09.968411 16174 amp_auto_cast.cc:106] empty 57
I0312 15:09:09.968420 16174 amp_auto_cast.cc:106] pool2d 58
I0312 15:09:09.968427 16174 amp_auto_cast.cc:106] stack 59
I0312 15:09:09.968434 16174 amp_auto_cast.cc:106] lamb 60
I0312 15:09:09.968438 16174 amp_auto_cast.cc:106] elementwise_mul 61
I0312 15:09:09.968456 16174 amp_auto_cast.cc:106] flatten_contiguous_range_grad 62
I0312 15:09:09.968469 16174 amp_auto_cast.cc:106] where_grad 63
I0312 15:09:09.968475 16174 amp_auto_cast.cc:106] share_buffer 64
I0312 15:09:09.968483 16174 amp_auto_cast.cc:106] sum 65
I0312 15:09:09.968490 16174 amp_auto_cast.cc:106] tanh_grad 66
I0312 15:09:09.968494 16174 amp_auto_cast.cc:106] dropout 67
I0312 15:09:09.968501 16174 amp_auto_cast.cc:106] unstack_grad 68
I0312 15:09:09.968508 16174 amp_auto_cast.cc:106] conv2d 69
I0312 15:09:09.968514 16174 amp_auto_cast.cc:106] conv2d_grad 70
I0312 15:09:09.968521 16174 amp_auto_cast.cc:106] dropout_grad 71
I0312 15:09:09.968529 16174 amp_auto_cast.cc:106] elementwise_max 72
I0312 15:09:09.968540 16174 amp_auto_cast.cc:106] expand_as_v2 73
I0312 15:09:09.968547 16174 amp_auto_cast.cc:106] softmax_with_cross_entropy 74
I0312 15:09:09.968556 16174 amp_auto_cast.cc:106] relu_grad 75
I0312 15:09:09.968562 16174 amp_auto_cast.cc:106] elementwise_floordiv 76
I0312 15:09:09.968571 16174 amp_auto_cast.cc:106] elementwise_mod 77
I0312 15:09:09.968580 16174 amp_auto_cast.cc:106] conv3d_grad 78
I0312 15:09:09.968585 16174 amp_auto_cast.cc:106] matmul_v2_grad 79
I0312 15:09:09.968591 16174 amp_auto_cast.cc:106] mul 80
I0312 15:09:09.968597 16174 amp_auto_cast.cc:106] gelu 81
I0312 15:09:09.968603 16174 amp_auto_cast.cc:106] silu 82
I0312 15:09:09.968608 16174 amp_auto_cast.cc:106] transpose2_grad 83
I0312 15:09:09.968613 16174 amp_auto_cast.cc:106] elementwise_div 84
I0312 15:09:09.968618 16174 amp_auto_cast.cc:106] layer_norm_grad 85
I0312 15:09:09.968623 16174 amp_auto_cast.cc:106] prelu_grad 86
I0312 15:09:09.968631 16174 amp_auto_cast.cc:106] strided_slice 87
I0312 15:09:09.968637 16174 amp_auto_cast.cc:106] square 88
I0312 15:09:09.968648 16174 amp_auto_cast.cc:106] max_pool2d_with_index 89
I0312 15:09:09.968653 16174 amp_auto_cast.cc:106] pad3d 90
I0312 15:09:09.968659 16174 amp_auto_cast.cc:106] flatten_contiguous_range 91
I0312 15:09:09.968669 16174 amp_auto_cast.cc:106] merged_momentum 92
I0312 15:09:09.968676 16174 amp_auto_cast.cc:106] elementwise_max_grad 93
I0312 15:09:09.968681 16174 amp_auto_cast.cc:106] expand_v2 94
I0312 15:09:09.968689 16174 amp_auto_cast.cc:106] pool3d 95
I0312 15:09:09.968696 16174 amp_auto_cast.cc:106] shape 96
I0312 15:09:09.968708 16174 amp_auto_cast.cc:106] layer_norm 97
I0312 15:09:09.968716 16174 amp_auto_cast.cc:106] feed 98
I0312 15:09:09.968724 16174 amp_auto_cast.cc:106] isnan_v2 99
I0312 15:09:09.968729 16174 amp_auto_cast.cc:106] concat_grad 100
I0312 15:09:09.968741 16174 amp_auto_cast.cc:106] scale 101
I0312 15:09:09.968747 16174 amp_auto_cast.cc:106] diag_v2 102
I0312 15:09:09.968756 16174 amp_auto_cast.cc:106] adamw 103
I0312 15:09:09.968761 16174 amp_auto_cast.cc:106] elementwise_pow 104
I0312 15:09:09.968768 16174 amp_auto_cast.cc:106] elementwise_add_grad 105
I0312 15:09:09.968775 16174 amp_auto_cast.cc:106] bmm_grad 106
I0312 15:09:09.968779 16174 amp_auto_cast.cc:106] set_value 107
I0312 15:09:09.968784 16174 amp_auto_cast.cc:106] reshape2_grad 108
I0312 15:09:09.968793 16174 amp_auto_cast.cc:106] tril_triu_grad 109
I0312 15:09:09.968802 16174 amp_auto_cast.cc:106] slice 110
I0312 15:09:09.968809 16174 amp_auto_cast.cc:106] fill_any_like 111
I0312 15:09:09.968816 16174 amp_auto_cast.cc:106] elementwise_add 112
I0312 15:09:09.968827 16174 amp_auto_cast.cc:106] mean_grad 113
I0312 15:09:09.968832 16174 amp_auto_cast.cc:106] masked_select_grad 114
I0312 15:09:09.968838 16174 amp_auto_cast.cc:106] assign_value 115
I0312 15:09:09.968844 16174 amp_auto_cast.cc:106] embedding_with_eltwise_add_xpu 116
I0312 15:09:09.968851 16174 amp_auto_cast.cc:106] diagonal 117
I0312 15:09:09.968858 16174 amp_auto_cast.cc:106] tanh 118
I0312 15:09:09.968863 16174 amp_auto_cast.cc:106] atan 119
I0312 15:09:09.968868 16174 amp_auto_cast.cc:106] gelu_grad 120
I0312 15:09:09.968874 16174 amp_auto_cast.cc:106] unsqueeze2 121
I0312 15:09:09.968883 16174 amp_auto_cast.cc:106] transfer_dtype 122
I0312 15:09:09.968894 16174 amp_auto_cast.cc:106] mul_grad 123
I0312 15:09:09.968900 16174 amp_auto_cast.cc:106] top_k_v2 124
I0312 15:09:09.968909 16174 amp_auto_cast.cc:106] argsort 125
I0312 15:09:09.968912 16174 amp_auto_cast.cc:106] sgd 126
I0312 15:09:09.968919 16174 amp_auto_cast.cc:106] memcpy_d2h 127
I0312 15:09:09.968930 16174 amp_auto_cast.cc:106] mean 128
I0312 15:09:09.968935 16174 amp_auto_cast.cc:106] transpose2 129
I0312 15:09:09.968940 16174 amp_auto_cast.cc:106] fc_xpu 130
I0312 15:09:09.968945 16174 amp_auto_cast.cc:106] fill_diagonal_tensor 131
I0312 15:09:09.968950 16174 amp_auto_cast.cc:106] softmax_grad 132
I0312 15:09:09.968957 16174 amp_auto_cast.cc:106] set_value_grad 133
I0312 15:09:09.968963 16174 amp_auto_cast.cc:106] cumsum 134
I0312 15:09:09.968969 16174 amp_auto_cast.cc:106] slice_grad 135
I0312 15:09:09.968973 16174 amp_auto_cast.cc:106] unfold_grad 136
I0312 15:09:09.968978 16174 amp_auto_cast.cc:106] reduce_sum 137
I0312 15:09:09.968983 16174 amp_auto_cast.cc:106] update_loss_scaling 138
I0312 15:09:09.968989 16174 amp_auto_cast.cc:106] fill_constant_batch_size_like 139
I0312 15:09:09.968995 16174 amp_auto_cast.cc:106] assign 140
I0312 15:09:09.969002 16174 amp_auto_cast.cc:106] tril_triu 141
I0312 15:09:09.969008 16174 amp_auto_cast.cc:106] multi_encoder_xpu 142
I0312 15:09:09.969013 16174 amp_auto_cast.cc:106] pool3d_grad 143
I0312 15:09:09.969018 16174 amp_auto_cast.cc:106] gather_grad 144
I0312 15:09:09.969023 16174 amp_auto_cast.cc:106] relu 145
I0312 15:09:09.969028 16174 amp_auto_cast.cc:106] bmm 146
I0312 15:09:09.969035 16174 amp_auto_cast.cc:106] silu_grad 147
I0312 15:09:09.969041 16174 amp_auto_cast.cc:106] gather 148
I0312 15:09:09.969045 16174 amp_auto_cast.cc:106] elementwise_min_grad 149
I0312 15:09:09.969051 16174 amp_auto_cast.cc:106] softmax 150
I0312 15:09:09.969056 16174 amp_auto_cast.cc:106] index_sample 151
I0312 15:09:09.969336 16174 amp_auto_cast.cc:119] -- The size of all_ops: 1166 --
I0312 15:09:09.969342 16174 amp_auto_cast.cc:120] -- The size of supported_ops: 152 --
I0312 15:09:09.969348 16174 amp_auto_cast.cc:121] -- The size of unsupported_ops: 1014 --
I0312 15:09:09.976341 16174 amp_auto_cast.cc:106] elementwise_mul_grad 9
I0312 15:09:09.976392 16174 amp_auto_cast.cc:106] elementwise_mul_triple_grad 10
I0312 15:09:09.976401 16174 amp_auto_cast.cc:106] index_select_grad 11
I0312 15:09:09.976408 16174 amp_auto_cast.cc:106] bicubic_interp_v2 12
I0312 15:09:09.976415 16174 amp_auto_cast.cc:106] split 13
I0312 15:09:09.976436 16174 amp_auto_cast.cc:106] transfer_layout 14
I0312 15:09:09.976456 16174 amp_auto_cast.cc:106] lookup_table_v2 15
I0312 15:09:09.976464 16174 amp_auto_cast.cc:106] memcpy_h2d 16
I0312 15:09:09.976480 16174 amp_auto_cast.cc:106] reshape2_grad_grad 17
I0312 15:09:09.976486 16174 amp_auto_cast.cc:106] elementwise_sub_grad_grad 18
I0312 15:09:09.976493 16174 amp_auto_cast.cc:106] uniform_random 19
I0312 15:09:09.976502 16174 amp_auto_cast.cc:106] elementwise_sub_grad 20
I0312 15:09:09.976507 16174 amp_auto_cast.cc:106] elementwise_min 21
I0312 15:09:09.976514 16174 amp_auto_cast.cc:106] fill_constant 22
I0312 15:09:09.976527 16174 amp_auto_cast.cc:106] fill_any 23
I0312 15:09:09.976533 16174 amp_auto_cast.cc:106] concat 24
I0312 15:09:09.976538 16174 amp_auto_cast.cc:106] squeeze2 25
I0312 15:09:09.976544 16174 amp_auto_cast.cc:106] unsqueeze2_grad 26
I0312 15:09:09.976550 16174 amp_auto_cast.cc:106] reshape2 27
I0312 15:09:09.976557 16174 amp_auto_cast.cc:106] elementwise_sub 28
I0312 15:09:09.976563 16174 amp_auto_cast.cc:106] squeeze2_grad 29
I0312 15:09:09.976572 16174 amp_auto_cast.cc:106] empty 30
I0312 15:09:09.976580 16174 amp_auto_cast.cc:106] stack 31
I0312 15:09:09.976586 16174 amp_auto_cast.cc:106] elementwise_mul 32
I0312 15:09:09.976595 16174 amp_auto_cast.cc:106] lookup_table_v2_grad 33
I0312 15:09:09.976606 16174 amp_auto_cast.cc:106] flatten_contiguous_range_grad 34
I0312 15:09:09.976612 16174 amp_auto_cast.cc:106] lookup_table_v2_grad 35
I0312 15:09:09.976624 16174 amp_auto_cast.cc:106] share_buffer 35
I0312 15:09:09.976632 16174 amp_auto_cast.cc:106] sum 36
I0312 15:09:09.976641 16174 amp_auto_cast.cc:106] unbind 37
I0312 15:09:09.976650 16174 amp_auto_cast.cc:106] dropout 38
I0312 15:09:09.976660 16174 amp_auto_cast.cc:106] linear_interp_v2 39
I0312 15:09:09.976668 16174 amp_auto_cast.cc:106] dropout_grad 40
I0312 15:09:09.976673 16174 amp_auto_cast.cc:106] elementwise_max 41
I0312 15:09:09.976686 16174 amp_auto_cast.cc:106] bilinear_interp_v2 42
I0312 15:09:09.976691 16174 amp_auto_cast.cc:106] lookup_table_v2_grad 43
I0312 15:09:09.976697 16174 amp_auto_cast.cc:106] linear_interp_v2_grad 43
I0312 15:09:09.976703 16174 amp_auto_cast.cc:106] nearest_interp_v2_grad 44
I0312 15:09:09.976715 16174 amp_auto_cast.cc:106] transpose2_grad 45
I0312 15:09:09.976723 16174 amp_auto_cast.cc:106] bicubic_interp_v2_grad 46
I0312 15:09:09.976730 16174 amp_auto_cast.cc:106] save 47
I0312 15:09:09.976744 16174 amp_auto_cast.cc:106] flatten_contiguous_range 48
I0312 15:09:09.976755 16174 amp_auto_cast.cc:106] elementwise_max_grad 49
I0312 15:09:09.976763 16174 amp_auto_cast.cc:106] size 50
I0312 15:09:09.976773 16174 amp_auto_cast.cc:106] memcpy 51
I0312 15:09:09.976789 16174 amp_auto_cast.cc:106] feed 52
I0312 15:09:09.976806 16174 amp_auto_cast.cc:106] scale 53
I0312 15:09:09.976821 16174 amp_auto_cast.cc:106] pad 54
I0312 15:09:09.976827 16174 amp_auto_cast.cc:106] reshape2_grad 55
I0312 15:09:09.976840 16174 amp_auto_cast.cc:106] trilinear_interp_v2_grad 56
I0312 15:09:09.976845 16174 amp_auto_cast.cc:106] slice 57
I0312 15:09:09.976851 16174 amp_auto_cast.cc:106] fill_any_like 58
I0312 15:09:09.976861 16174 amp_auto_cast.cc:106] mean_grad 59
I0312 15:09:09.976867 16174 amp_auto_cast.cc:106] lookup_table_v2_grad 60
I0312 15:09:09.976874 16174 amp_auto_cast.cc:106] bilinear_interp_v2_grad 60
I0312 15:09:09.976886 16174 amp_auto_cast.cc:106] unsqueeze2 61
I0312 15:09:09.976893 16174 amp_auto_cast.cc:106] transfer_dtype 62
I0312 15:09:09.976902 16174 amp_auto_cast.cc:106] fill_any_grad 63
I0312 15:09:09.976907 16174 amp_auto_cast.cc:106] elementwise_mul_grad_grad 64
I0312 15:09:09.976912 16174 amp_auto_cast.cc:106] trilinear_interp_v2 65
I0312 15:09:09.976919 16174 amp_auto_cast.cc:106] sgd 66
I0312 15:09:09.976925 16174 amp_auto_cast.cc:106] memcpy_d2h 67
I0312 15:09:09.976934 16174 amp_auto_cast.cc:106] mean 68
I0312 15:09:09.976940 16174 amp_auto_cast.cc:106] transpose2 69
I0312 15:09:09.976948 16174 amp_auto_cast.cc:106] index_select 70
I0312 15:09:09.976956 16174 amp_auto_cast.cc:106] stack_grad 71
I0312 15:09:09.976960 16174 amp_auto_cast.cc:106] slice_grad 72
I0312 15:09:09.976969 16174 amp_auto_cast.cc:106] save_combine 73
I0312 15:09:09.976975 16174 amp_auto_cast.cc:106] assign 74
I0312 15:09:09.976982 16174 amp_auto_cast.cc:106] gather_grad 75
I0312 15:09:09.976991 16174 amp_auto_cast.cc:106] nearest_interp_v2 76
I0312 15:09:09.976996 16174 amp_auto_cast.cc:106] gather 77
I0312 15:09:09.977001 16174 amp_auto_cast.cc:106] elementwise_min_grad 78
I0312 15:09:09.977005 16174 amp_auto_cast.cc:106] pad_grad 79
I0312 15:09:09.977324 16174 amp_auto_cast.cc:119] -- The size of all_ops: 1166 --
I0312 15:09:09.977331 16174 amp_auto_cast.cc:120] -- The size of supported_ops: 80 --
I0312 15:09:09.977336 16174 amp_auto_cast.cc:121] -- The size of unsupported_ops: 1086 --
I0312 15:09:10.130941 16174 imperative.cc:2198] Tracer(0x55cb57acde90) set expected place Place(xpu:0)
I0312 15:09:10.178701 16174 imperative.cc:2198] Tracer(0x55cb57acde90) set expected place Place(xpu:0)
-----------  Running Arguments -----------
action_file: None
batch_size: 1
camera_id: -1
combine_method: nms
cpu_threads: 1
device: xpu
enable_mkldnn: False
enable_mkldnn_bfloat16: False
image_dir: None
image_file: ../data/coco/train/DJI_0217_R.JPG
match_metric: ios
match_threshold: 0.6
model_dir: ./inference_model/solov2_r50_fpn_1x_coco/
output_dir: output
overlap_ratio: [0.25, 0.25]
random_pad: False
reid_batch_size: 50
reid_model_dir: None
run_benchmark: False
run_mode: paddle
save_images: True
save_mot_txt_per_img: False
save_mot_txts: False
save_results: False
scaled: False
slice_infer: False
slice_size: [640, 640]
threshold: 0.5
tracker_config: None
trt_calib_mode: False
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
use_coco_category: False
use_dark: True
use_gpu: False
video_file: None
window_size: 50
------------------------------------------
-----------  Model Configuration -----------
Model Arch: SOLOv2
Transform Order: 
--transform op: NormalizeImage
--transform op: Resize
--transform op: Permute
--transform op: PadStride
--------------------------------------------
Traceback (most recent call last):
  File "deploy/python/infer.py", line 1084, in <module>
    main()
  File "deploy/python/infer.py", line 1031, in main
    output_dir=FLAGS.output_dir)
  File "deploy/python/infer.py", line 578, in __init__
    threshold=threshold, )
  File "deploy/python/infer.py", line 122, in __init__
    delete_shuffle_pass=delete_shuffle_pass)
  File "deploy/python/infer.py", line 932, in load_predictor
    predictor = create_predictor(config)
IndexError: map::at
