### ISSUE TITLE
paddlepaddle==2.5.1在paddledetection模型训练的时候报数据导入问题

### ISSUE THREAD

**Issue by chinesejunzai12** [PaddlePaddle/PaddleDetection#9040]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Traceback (most recent call last):
  File "tools/train.py", line 32, in <module>
    from ppdet.core.workspace import load_config, merge_config
  File "/mnt/project/PaddleDetection/ppdet/__init__.py", line 15, in <module>
    from . import (core, data, engine, modeling, model_zoo, optimizer, metrics,
  File "/mnt/project/PaddleDetection/ppdet/data/__init__.py", line 16, in <module>
    from . import transform
  File "/mnt/project/PaddleDetection/ppdet/data/transform/__init__.py", line 15, in <module>
    from . import operators
  File "/mnt/project/PaddleDetection/ppdet/data/transform/operators.py", line 45, in <module>
    from ..reader import Compose
  File "/mnt/project/PaddleDetection/ppdet/data/reader.py", line 26, in <module>
    from paddle.fluid.dataloader.collate import default_collate_fn
ModuleNotFoundError: No module named 'paddle.fluid.dataloader'
请帮忙看一下, 谢谢, 是不是版本的问题, 文档中写到版本要大于等于2.2的

**Comment by BotAndyGao** [comment]
### 建议版本
- Python: 3.10.12
- CUDA Version: 12.1
- Paddle版本：2.5.2， 安装方式：Docker
- PaddleDetection版本： release/2.7， 安装方式：源码

这套搭配可以跑起来，亲测多个模型均可以完成训练，识别精度都不错。
