### ISSUE TITLE
在复现python tools/train.py -c configs/picodet/picodet_m_320_coco_lcnet.yml时出bug,我的版本Python3.7,paddlepaddle-gpu2.1.2.post11,numpy1.19.5,lag0.4

### ISSUE THREAD

**Issue by ykinger1** [PaddlePaddle/PaddleDetection#9203]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

(venv1) PS D:\kunsrc\Python\Dive_Into_PaddlePaddle\1_PaddleDetection\PaddleDetection> python tools/train.py -c configs/picodet/picodet_m_320_coco_lcnet.yml
D:\kunsrc\Python\Dive_Into_PaddlePaddle\venv1\lib\site-packages\setuptools\sandbox.py:13: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
D:\kunsrc\Python\Dive_Into_PaddlePaddle\venv1\lib\site-packages\pkg_resources\__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
D:\kunsrc\Python\Dive_Into_PaddlePaddle\venv1\lib\site-packages\pkg_resources\__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
Traceback (most recent call last):
  File "tools/train.py", line 32, in <module>
    from ppdet.core.workspace import load_config, merge_config
  File "D:\kunsrc\Python\Dive_Into_PaddlePaddle\1_PaddleDetection\PaddleDetection\ppdet\__init__.py", line 15, in <module>
    from . import (core, data, engine, modeling, model_zoo, optimizer, metrics,
  File "D:\kunsrc\Python\Dive_Into_PaddlePaddle\1_PaddleDetection\PaddleDetection\ppdet\data\__init__.py", line 16, in <module>
    from . import transform
  File "D:\kunsrc\Python\Dive_Into_PaddlePaddle\1_PaddleDetection\PaddleDetection\ppdet\data\transform\__init__.py", line 15, in <module>
    from . import operators
  File "D:\kunsrc\Python\Dive_Into_PaddlePaddle\1_PaddleDetection\PaddleDetection\ppdet\data\transform\operators.py", line 44, in <module>
    from ppdet.modeling import bbox_utils
  File "D:\kunsrc\Python\Dive_Into_PaddlePaddle\1_PaddleDetection\PaddleDetection\ppdet\modeling\__init__.py", line 25, in <module>
    from . import architectures
  File "D:\kunsrc\Python\Dive_Into_PaddlePaddle\1_PaddleDetection\PaddleDetection\ppdet\modeling\architectures\__init__.py", line 21, in <module>
    from . import deepsort
  File "D:\kunsrc\Python\Dive_Into_PaddlePaddle\1_PaddleDetection\PaddleDetection\ppdet\modeling\architectures\deepsort.py", line 22, in <module>
    from ppdet.modeling.mot.utils import Detection, get_crops, scale_coords, clip_box
  File "D:\kunsrc\Python\Dive_Into_PaddlePaddle\1_PaddleDetection\PaddleDetection\ppdet\modeling\mot\__init__.py", line 15, in <module>
    from . import matching
  File "D:\kunsrc\Python\Dive_Into_PaddlePaddle\1_PaddleDetection\PaddleDetection\ppdet\modeling\mot\matching\__init__.py", line 15, in <module>
    from . import jde_matching
  File "D:\kunsrc\Python\Dive_Into_PaddlePaddle\1_PaddleDetection\PaddleDetection\ppdet\modeling\mot\matching\jde_matching.py", line 18, in <module>
    import lap
  File "D:\kunsrc\Python\Dive_Into_PaddlePaddle\venv1\lib\site-packages\lap\__init__.py", line 25, in <module>
    from ._lapjv import (
  File "__init__.pxd", line 199, in init lap._lapjv
ValueError: numpy.ndarray has the wrong size, try recompiling. Expected 80, got 88

**Comment by zhangyubo0722** [comment]
建议使用最新的paddlepaddle版本和PaddleDetection的develop分支

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
