### ISSUE TITLE
量化训练后的ppyoloe+，无法使用deploy/python/infer.py推理

### ISSUE THREAD

**Issue by EvW1998** [PaddlePaddle/PaddleDetection#9225]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

根据PaddleDetection提供的[模型压缩文档](https://github.com/PaddlePaddle/PaddleDetection/blob/8377e846439a709f5ab3ac6948d768221b5cf1e6/configs/slim/README.md)，我将训练好的ppyoloe+ s模型进行量化训练，将量化后的模型导出为静态图后，使用deploy/python/infer.py推理报错。

使用的环境如下：
paddledet == develop (>= 2.8.0)
paddlepaddle-gpu == 2.6.1.post116
paddleslim == 2.6.0

导出静态图命令：
```bash
python tools/export_model.py -c ./configs/ppyoloe/ppyoloe_plus_crn_s_80e_abnormal_object.yml \
                             --output_dir=compare/ppyoloes_qat \
                             --slim_config ./configs/slim/quant/ppyoloe_s_qat_abnormal_object.yml \
                             -o weights=./output_ppyoloe_s_data1118_quant_lr0000125/best_model/model.pdparams
```

量化后的ppyoloe+ s静态图模型：
[ppyoloes_qat.zip](https://github.com/user-attachments/files/17927700/ppyoloes_qat.zip)

导出前的动态图量化模型，可正常使用tools/infer.py推理：
```bash
python tools/infer.py -c ./configs/ppyoloe/ppyoloe_plus_crn_s_80e_abnormal_object_coco.yml \
                      --slim_config /./configs/slim/quant/ppyoloe_s_qat_abnormal_object.yml \
                      -o weights=./output_ppyoloe_s_data1118_quant_lr0000125/best_model/model.pdparams \
                      --infer_img=./yiwu.png \
                      --output_dir=compare
```
![yiwu_ppyoloes_qat_dynamic](https://github.com/user-attachments/assets/0f32c2fc-708e-401b-8d0a-c11a814592da)

但是使用deploy/python/infer.py，对静态图模型，推理报错：
```bash
python deploy/python/infer.py --model_dir=./compare/ppyoloes_qat/ppyoloe_s_qat_abnormal_object \
                              --image_file=./yiwu.png \
                              --device=GPU \
                              --output_dir=compare
```

报错信息：
```shell
-----------  Running Arguments -----------
action_file: None
batch_size: 1
camera_id: -1
collect_trt_shape_info: False
combine_method: nms
cpu_threads: 1
device: GPU
enable_mkldnn: False
enable_mkldnn_bfloat16: False
image_dir: None
image_file: ./yiwu.png
match_metric: ios
match_threshold: 0.6
model_dir: ./compare/ppyoloes_qat/ppyoloe_s_qat_abnormal_object
output_dir: compare
overlap_ratio: [0.25, 0.25]
random_pad: False
reid_batch_size: 50
reid_model_dir: None
run_benchmark: False
run_mode: paddle
save_images: True
save_mot_txt_per_img: False
save_mot_txts: False
save_results: False
scaled: False
slice_infer: False
slice_size: [640, 640]
task_type: Detection
threshold: 0.5
tracker_config: None
trt_calib_mode: False
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
tuned_trt_shape_file: shape_range_info.pbtxt
use_coco_category: False
use_dark: True
use_fd_format: False
use_gpu: False
video_file: None
window_size: 50
------------------------------------------
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order: 
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
dict_keys(['image', 'im_shape', 'scale_factor'])
Traceback (most recent call last):
  File "deploy/python/infer.py", line 1268, in <module>
    main()
  File "deploy/python/infer.py", line 1236, in main
    detector.predict_image(
  File "deploy/python/infer.py", line 417, in predict_image
    result = self.predict()
  File "deploy/python/infer.py", line 212, in predict
    self.predictor.run()
ValueError: (InvalidArgument) input and filter data type should be consistent, but received input data type is float and filter type is int8_t
  [Hint: Expected input_data_type == filter_data_type, but received input_data_type:5 != filter_data_type:21.] (at ../paddle/fluid/operators/generator/get_expected_kernel_func.cc:431)
  [operator < conv2d > error]
```

但是非量化的静态图模型，可以正常使用deploy/python/infer.py推理。

另外，我尝试单独用paddle加载量化的静态图模型，可正常加载推理
```python
import paddle
import numpy as np
import cv2


def vis_detection(im, nms_results, score_threshold=0.5, line_size=2, font_size=1):
    label_ids = []
    scores = []
    boxes = []
    for r in nms_results:
        label_ids.append(int(r[0]))
        scores.append(r[1])
        boxes.append(r[2:])
        
        if r[1] >= score_threshold:
            print(list(r))
        
    result = {'label_ids': label_ids, 'scores': scores, 'boxes': boxes}
    
    max_label_id = max(result['label_ids'])
    color_map = generate_color_map(max_label_id)
    
    vis_im = im.copy()
    
    # Draw bounding boxes
    for i, box in enumerate(result['boxes']):
        if result['scores'][i] < score_threshold:
            continue
        
        x1, y1, x2, y2 = map(int, map(round, box))
        c0, c1, c2 = color_map[3 * result['label_ids'][i]:3 * result['label_ids'][i] + 3]
        rect_color = (c0, c1, c2)
        id_str = str(result['label_ids'][i])
        score = f"{result['scores'][i]:.2f}"
        text = f"{id_str}, {score}"
        
        cv2.rectangle(vis_im, (x1, y1), (x2, y2), rect_color, line_size)
        cv2.putText(vis_im, text, (x1, y1), cv2.FONT_HERSHEY_SIMPLEX, font_size, (255, 255, 255), 1)
    
    return vis_im


def generate_color_map(max_label_id):
    np.random.seed(0)
    return [int(c) for c in np.random.randint(0, 255, (max_label_id + 1) * 3)]


paddle.enable_static()

# 加载模型
[inference_program, feed_target_names, fetch_targets] = paddle.static.load_inference_model(
    path_prefix='./compare/ppyoloes_qat/ppyoloe_s_qat_abnormal_object',
    model_filename='model.pdmodel',
    params_filename='model.pdiparams',
    executor=paddle.static.Executor()
)

# 准备输入数据
frame = cv2.imread("./yiwu.png")
original_im = frame.copy()

frame = cv2.resize(frame, (640, 640))
frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB).astype(np.float32)
input_image = np.transpose(np.array([(frame-0)/255]), (0,3,1,2)) # n,c,h,w

input_scale = np.array([[1, 1]], dtype="float32")

# 创建执行器
place = paddle.CUDAPlace(0)
exe = paddle.static.Executor(place)
 
# 执行推理
results = exe.run(program=inference_program,
                  feed={feed_target_names[0]: input_image, feed_target_names[1]: input_scale},
                  fetch_list=fetch_targets)
 
print(results[0].shape, results[1].shape)
cv2.imwrite("./compare/yiwu.png", vis_detection(original_im, results[0]))
```
![yiwu_ppyoloes_qat_static](https://github.com/user-attachments/assets/e94a63a8-ab3b-4cb4-a89c-ba36d5ca9d11)

所以，deploy/python/infer.py中可能存在bug导致推理失败吗？

**Comment by cuicheng01** [comment]
有可能是推理的一些config配置导致的问题，你可以尝试修改推理的config试试呢？比如修改和对齐此处的配置https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.8/deploy/python/infer.py#L1023

**Comment by EvW1998** [comment]
发现把 `--device=GPU` 改为 `CPU`，可以推理：
```shell
-----------  Running Arguments -----------
action_file: None
batch_size: 1
camera_id: -1
collect_trt_shape_info: False
combine_method: nms
cpu_threads: 1
device: CPU
enable_mkldnn: False
enable_mkldnn_bfloat16: False
image_dir: None
image_file: ./yiwu.png
match_metric: ios
match_threshold: 0.6
model_dir: ./compare/ppyoloes_qat/ppyoloe_s_qat_abnormal_object
output_dir: compare
overlap_ratio: [0.25, 0.25]
random_pad: False
reid_batch_size: 50
reid_model_dir: None
run_benchmark: False
run_mode: paddle
save_images: True
save_mot_txt_per_img: False
save_mot_txts: False
save_results: False
scaled: False
slice_infer: False
slice_size: [640, 640]
task_type: Detection
threshold: 0.5
tracker_config: None
trt_calib_mode: False
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
tuned_trt_shape_file: shape_range_info.pbtxt
use_coco_category: False
use_dark: True
use_fd_format: False
use_gpu: False
video_file: None
window_size: 50
------------------------------------------
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order: 
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
dict_keys(['image', 'im_shape', 'scale_factor'])
class_id:0, confidence:0.9524, left_top:[42.76,354.12],right_bottom:[230.91,485.51]
class_id:1, confidence:0.8380, left_top:[94.95,160.63],right_bottom:[608.79,346.17]
save result to: compare/yiwu.png
Test iter 0
------------------ Inference Time Info ----------------------
total_time(ms): 1706.9, img_num: 1
average latency time(ms): 1706.90, QPS: 0.585857
preprocess_time(ms): 25.90, inference_time(ms): 1681.00, postprocess_time(ms): 0.00
```

或者将 `if device == 'GPU'` 中的 `config.enable_use_gpu(200, 0)` 注释掉，也可以推理
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.8/deploy/python/infer.py#L1025
```shell
-----------  Running Arguments -----------
action_file: None
batch_size: 1
camera_id: -1
collect_trt_shape_info: False
combine_method: nms
cpu_threads: 1
device: GPU
enable_mkldnn: False
enable_mkldnn_bfloat16: False
image_dir: None
image_file: ./yiwu.png
match_metric: ios
match_threshold: 0.6
model_dir: ./compare/ppyoloes_qat/ppyoloe_s_qat_abnormal_object
output_dir: compare
overlap_ratio: [0.25, 0.25]
random_pad: False
reid_batch_size: 50
reid_model_dir: None
run_benchmark: False
run_mode: paddle
save_images: True
save_mot_txt_per_img: False
save_mot_txts: False
save_results: False
scaled: False
slice_infer: False
slice_size: [640, 640]
task_type: Detection
threshold: 0.5
tracker_config: None
trt_calib_mode: False
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
tuned_trt_shape_file: shape_range_info.pbtxt
use_coco_category: False
use_dark: True
use_fd_format: False
use_gpu: False
video_file: None
window_size: 50
------------------------------------------
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order: 
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
dict_keys(['image', 'im_shape', 'scale_factor'])
class_id:0, confidence:0.9524, left_top:[42.76,354.12],right_bottom:[230.91,485.51]
class_id:1, confidence:0.8380, left_top:[94.95,160.63],right_bottom:[608.79,346.17]
save result to: compare/yiwu.png
Test iter 0
------------------ Inference Time Info ----------------------
total_time(ms): 1581.5, img_num: 1
average latency time(ms): 1581.50, QPS: 0.632311
preprocess_time(ms): 33.60, inference_time(ms): 1547.90, postprocess_time(ms): 0.00
```

**Comment by cuicheng01** [comment]
好的，这个应该是需要单独做配置的，不同的slim模型情况可能也不同，需要单独调试下

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
