### ISSUE TITLE
yolov4 推断报错

### ISSUE THREAD

**Issue by legendxty** [PaddlePaddle/PaddleDetection#938]
第二次用yolov4训练自己的数据集了，推断的命令是：
!python tools/infer.py -c configs/rotated/yolov4_cspdarknet_voc.yml --infer_dir=./dataset/rotated/JPEGImages

报错如下，请大佬帮忙看看：
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py:789: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tools/infer.py", line 254, in <module>
    main()
  File "tools/infer.py", line 173, in main
    return_numpy=False)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 790, in run
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 785, in run
    use_program_cache=use_program_cache)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 838, in _run_impl
    use_program_cache=use_program_cache)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 912, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::platform::TensorDescriptor::set(paddle::framework::Tensor const&, cudnnTensorFormat_t)
3   paddle::operators::CUDNNConvOpKernel<float>::Compute(paddle::framework::ExecutionContext const&) const
4   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::CUDNNConvOpKernel<float>, paddle::operators::CUDNNConvOpKernel<double>, paddle::operators::CUDNNConvOpKernel<paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
7   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
8   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
9   paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 1403, in conv2d
    "data_format": data_format,
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/backbones/cspdarknet.py", line 76, in _conv_norm
    bias_attr=False)
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/backbones/cspdarknet.py", line 195, in __call__
    name=self.prefix_name + "conv")
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 61, in build
    body_feats = self.backbone(im)
  File "/home/aistudio/work/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 162, in test
    return self.build(feed_vars, mode='test')
  File "tools/infer.py", line 118, in main
    test_fetches = model.test(feed_vars)
  File "tools/infer.py", line 254, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: An error occurred here. There is no accurate error hint for this error yet. We are continuously in the process of increasing hint for this kind of error check. It would be helpful if you could inform us of how this conversion went by opening a github issue. And we will resolve it with high priority.
  - New issue link: https://github.com/PaddlePaddle/Paddle/issues/new
  - Recommended issue content: all error stack information
  [Hint: CUDNN_STATUS_NOT_SUPPORTED] at (/paddle/paddle/fluid/platform/cudnn_desc.h:155)
  [operator < conv2d > error]

**Comment by heavengate** [comment]
看报错信息是`CUDNN_STATUS_NOT_SUPPORTED`，是CUDNN不可用，可以排查一下是不是CUDNN安装不正确，LD_LIBRARY_PATH没有配置CUDNN路径，或者安装的CUDNN版本和paddle需求的CUDNN版本不匹配，可以参考一下 https://www.paddlepaddle.org.cn/install/quick

**Comment by legendxty** [comment]
> 看报错信息是`CUDNN_STATUS_NOT_SUPPORTED`，是CUDNN不可用，可以排查一下是不是CUDNN安装不正确，LD_LIBRARY_PATH没有配置CUDNN路径，或者安装的CUDNN版本和paddle需求的CUDNN版本不匹配，可以参考一下 https://www.paddlepaddle.org.cn/install/quick

呃，可我是在aistudio上面运行的呀，GPU环境，训练过程都没报错呢

**Comment by legendxty** [comment]
> 看报错信息是`CUDNN_STATUS_NOT_SUPPORTED`，是CUDNN不可用，可以排查一下是不是CUDNN安装不正确，LD_LIBRARY_PATH没有配置CUDNN路径，或者安装的CUDNN版本和paddle需求的CUDNN版本不匹配，可以参考一下 https://www.paddlepaddle.org.cn/install/quick

貌似是文件夹里面的图片太多了，我拆分成32张图片/文件夹，就不会报错了
