### ISSUE TITLE
Exception: PaddlePaddle version 2.0.0 or higher is required, or a suitable develop version is satisfied as well. 

### ISSUE THREAD

**Issue by zhenghuayouarebest** [PaddlePaddle/PaddleDetection#943]
运行 python ppdet/modeling/tests/test_architectures.py 出现如标题错误，报错暂时没找到原因
ERROR: test_train (__main__.TestYolov3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Project\repos\PaddleDetection\ppdet\modeling\tests\decorator_helper.py", line 29, in __fn__
    fn(*args, **kwargs)
  File "ppdet/modeling/tests/test_architectures.py", line 45, in test_train
    model = create(self.detector_type)
  File "D:\Project\repos\PaddleDetection\ppdet\core\workspace.py", line 236, in create
    kwargs[k] = create(target_key)
  File "D:\Project\repos\PaddleDetection\ppdet\core\workspace.py", line 244, in create
    return cls(**kwargs)
  File "D:\Project\repos\PaddleDetection\ppdet\modeling\anchor_heads\yolo_head.py", line 74, in __init__
    check_version('2.0.0')
  File "D:\Project\repos\PaddleDetection\ppdet\utils\check.py", line 72, in check_version
    raise Exception(err)
Exception: PaddlePaddle version 2.0.0 or higher is required, or a suitable develop version is satisfied as well. 
Please make sure the version is good with your code.

----------------------------------------------------------------------
Ran 12 tests in 4.017s

FAILED (errors=2, skipped=2)

**Comment by jerrywgz** [comment]
yolo系列模型目前需要paddle2.0版本或develop版本
