### ISSUE TITLE
Mask_Rcnn报错

### ISSUE THREAD

**Issue by zqx1609** [PaddlePaddle/PaddleDetection#946]
在训练mask_rcnn_r50_1x时报错，ubuntu18.04系统，显卡三2070s，这边10000次迭代已经完成，测试也finish，使用的训练命令是python3 tools/eval.py -c configs/mask_rcnn_r50_1x.yml，没有形成model_final文件夹，output中只有10000.pdmodel  10000.pdopt 10000.pdparams三个文件，以下是报错信息

```
2020-06-13 10:17:13,511-INFO: Test finish iter 5000
2020-06-13 10:17:13,511-INFO: Total number of images: 5000, inference time: 7.815948707443043 fps.
loading annotations into memory...
Done (t=0.53s)
creating index...
index created!
2020-06-13 10:17:18,362-INFO: Start evaluate...
Loading and preparing results...
DONE (t=2.92s)
creating index...
index created!
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 366, in <module>
    main()
  File "tools/train.py", line 288, in main
    cfg['EvalReader']['dataset'])
  File "/paddle/PaddleDetection/ppdet/utils/eval_utils.py", line 218, in eval_results
    save_only=save_only)
  File "/paddle/PaddleDetection/ppdet/utils/coco_eval.py", line 102, in bbox_eval
    map_stats = cocoapi_eval(outfile, 'bbox', coco_gt=coco_gt)
  File "/paddle/PaddleDetection/ppdet/utils/coco_eval.py", line 194, in cocoapi_eval
    coco_eval = COCOeval(coco_gt, coco_dt, style)
  File "/usr/local/lib/python3.5/dist-packages/pycocotools/cocoeval.py", line 76, in __init__
    self.params = Params(iouType=iouType) # parameters
  File "/usr/local/lib/python3.5/dist-packages/pycocotools/cocoeval.py", line 527, in __init__
    self.setDetParams()
  File "/usr/local/lib/python3.5/dist-packages/pycocotools/cocoeval.py", line 507, in setDetParams
    self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)
  File "<__array_function__ internals>", line 6, in linspace
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.
terminate called without an active exception
W0613 10:17:28.414064   308 init.cc:216] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0613 10:17:28.414081   308 init.cc:218] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0613 10:17:28.414084   308 init.cc:221] The detail failure signal is:

W0613 10:17:28.414091   308 init.cc:224] *** Aborted at 1592043448 (unix time) try "date -d @1592043448" if you are using GNU date ***
W0613 10:17:28.418051   308 init.cc:224] PC: @                0x0 (unknown)
W0613 10:17:28.418337   308 init.cc:224] *** SIGABRT (@0x110) received by PID 272 (TID 0x7f4c47aee700) from PID 272; stack trace: ***
W0613 10:17:28.419332   308 init.cc:224]     @     0x7f4cf3cf3390 (unknown)
W0613 10:17:28.420001   308 init.cc:224]     @     0x7f4cf394d428 gsignal
W0613 10:17:28.420625   308 init.cc:224]     @     0x7f4cf394f02a abort
W0613 10:17:28.421449   308 init.cc:224]     @     0x7f4cc660e84d __gnu_cxx::__verbose_terminate_handler()
W0613 10:17:28.422082   308 init.cc:224]     @     0x7f4cc660c6b6 (unknown)
W0613 10:17:28.422539   308 init.cc:224]     @     0x7f4cc660c701 std::terminate()
W0613 10:17:28.422992   308 init.cc:224]     @     0x7f4cc660c2e0 __gxx_personality_v0
W0613 10:17:28.423486   308 init.cc:224]     @     0x7f4cd8336059 (unknown)
W0613 10:17:28.423959   308 init.cc:224]     @     0x7f4cd83363b4 _Unwind_ForcedUnwind
W0613 10:17:28.424554   308 init.cc:224]     @     0x7f4cf3cf2070 __GI___pthread_unwind
W0613 10:17:28.425287   308 init.cc:224]     @     0x7f4cf3cea845 __pthread_exit
W0613 10:17:28.425561   308 init.cc:224]     @           0x602355 PyThread_exit_thread
W0613 10:17:28.425678   308 init.cc:224]     @           0x53ba84 PyEval_RestoreThread
W0613 10:17:28.429702   308 init.cc:224]     @     0x7f4c861fb7b9 pybind11::gil_scoped_release::~gil_scoped_release()
W0613 10:17:28.430249   308 init.cc:224]     @     0x7f4c862e3c45 _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybind10BindReaderEPNS_6moduleEEUlRNS2_9operators6reader40OrderedMultiDeviceLoDTensorBlockingQueueERKSt6vectorINS2_9framework9LoDTensorESaISC_EEE2_bIS9_SG_EINS_4nameENS_9is_methodENS_7siblingENS_10call_guardIINS_18gil_scoped_releaseEEEEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNES11_
W0613 10:17:28.432379   308 init.cc:224]     @     0x7f4c86218fc9 pybind11::cpp_function::dispatcher()
W0613 10:17:28.432504   308 init.cc:224]     @           0x4ea927 PyCFunction_Call
W0613 10:17:28.432634   308 init.cc:224]     @           0x541511 PyEval_EvalFrameEx
W0613 10:17:28.432741   308 init.cc:224]     @           0x5464da PyEval_EvalCodeEx
W0613 10:17:28.432854   308 init.cc:224]     @           0x4ecab7 (unknown)
W0613 10:17:28.432946   308 init.cc:224]     @           0x5bfd87 PyObject_Call
W0613 10:17:28.433058   308 init.cc:224]     @           0x53df3b PyEval_EvalFrameEx
W0613 10:17:28.433168   308 init.cc:224]     @           0x5405e4 PyEval_EvalFrameEx
W0613 10:17:28.433277   308 init.cc:224]     @           0x5405e4 PyEval_EvalFrameEx
W0613 10:17:28.433382   308 init.cc:224]     @           0x545d8b PyEval_EvalCodeEx
W0613 10:17:28.433495   308 init.cc:224]     @           0x4ec9a3 (unknown)
W0613 10:17:28.433586   308 init.cc:224]     @           0x5bfd87 PyObject_Call
W0613 10:17:28.433699   308 init.cc:224]     @           0x4fc63e (unknown)
W0613 10:17:28.433790   308 init.cc:224]     @           0x5bfd87 PyObject_Call
W0613 10:17:28.433849   308 init.cc:224]     @           0x531200 PyEval_CallObjectWithKeywords
W0613 10:17:28.433964   308 init.cc:224]     @           0x605be2 (unknown)
W0613 10:17:28.434633   308 init.cc:224]     @     0x7f4cf3ce96ba start_thread
Aborted (core dumped)
```

**Comment by qingqing01** [comment]
@zqx1609 

1. 看下输出里有没有model_final.pdparams
2. 错误是由于numpy升级的不兼容引起的 参考 https://github.com/PaddlePaddle/PaddleDetection/issues/245

**Comment by zqx1609** [comment]
@qingqing01
改掉了numpy版本，这个错误解决了，我这是docker版本，官方怎么会默认配置了不合适的numpy呢？

**Comment by qingqing01** [comment]
@zqx1609 如果问题已解决，关闭此issue了。
