### ISSUE TITLE
下载到本地的预训练权重无法load

### ISSUE THREAD

**Issue by luuuyi** [PaddlePaddle/PaddleDetection#948]
下载到本地的预训练权重是tar结尾的，用load_params函数加载会报断言错误，只要pdparams、pdopt或者pdmodel

**Comment by qingqing01** [comment]
@luuuyi 下载本地预训练权重以tar结尾，通过`pretrain_weights`设置也是没问题的。 给下启动训练命令和详细的错误信息吧。 默认log里出现.pdparams的是wanring信息，不是错误信息。

**Comment by luuuyi** [comment]
@qingqing01 调用_decompressing方法对tar解压以后将pretrain_weights指向解压的目录，这个逻辑和在线下载.tar一样，现在是新的错误 paddle/fluid/io会报 Variable Not Found，但是解压目录下其实是有这个参数的

**Comment by qingqing01** [comment]
@luuuyi 给下详细的启动命令和预训练模型配置，以及错误信息吧。

**Comment by luuuyi** [comment]
@qingqing01 解决了，不好意思

**Comment by freesouls** [comment]
@qingqing01 遇到同样的问题了，你们这个tar跟pdparams到底有啥区别啊，把tar解压，或者tar后缀改成pdparams都解决不了问题啊
``` shell
CONFIG="./obj365/cascade_rcnn_dcnv2_se154_vd_fpn_gn_cas.yml"
# 这里将./obj365/cascade_rcnn_dcnv2_se154_vd_fpn_gn_cas_obj365.tar后缀改成了pdparams
WEIGHTS="./obj365/cascade_rcnn_dcnv2_se154_vd_fpn_gn_cas_obj365.pdparams"

INNFER_IMG="sampled/000001.jpg"
python -u ./tools/infer.py \
    -c ${CONFIG} \
    -o weights=${WEIGHTS} \
    --infer_img=${INFER_IMG}

Traceback (most recent call last):
  File "./tools/infer.py", line 254, in <module>
    main()
  File "./tools/infer.py", line 126, in main
    checkpoint.load_params(exe, infer_prog, cfg.weights)
  File "/home/data/xinrui.xbb/projects/PaddleDetection/ppdet/utils/checkpoint.py", line 125, in load_params
    state = _load_state(path)
  File "/home/data/xinrui.xbb/projects/PaddleDetection/ppdet/utils/checkpoint.py", line 91, in _load_state
    state = fluid.io.load_program_state(path)
  File "/home/data/xinrui.xbb/anaconda3/lib/python3.6/site-packages/paddle/fluid/io.py", line 1907, in load_program_state
    f, encoding='latin1')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 1046: invalid start byte
```

**Comment by freesouls** [comment]
@luuuyi 请问你具体是怎么解决的？有遇到我上面的问题吗？谢谢

**Comment by freesouls** [comment]
搞了一个低的版本，好像解决了

**Comment by TechnicalAnt** [comment]
@freesouls 请问具体怎么解决的呢？
