### ISSUE TITLE
open images 目标检测 形状设置不正确

### ISSUE THREAD

**Issue by dhlrd** [PaddlePaddle/PaddleDetection#97]
oidv5 目标检测模型，直接推理的时候报错：
Traceback (most recent call last):
  File "tools/infer.py", line 271, in <module>
    main()
  File "tools/infer.py", line 131, in main
    test_fetches = model.test(feed_vars)
  File "/Users/admin/projects/PaddleDetection/ppdet/modeling/architectures/cascade_rcnn_cls_aware.py", line 184, in test
    return self.build(feed_vars, 'test')
  File "/Users/admin/projects/PaddleDetection/ppdet/modeling/architectures/cascade_rcnn_cls_aware.py", line 88, in build
    body_feats = self.backbone(im)
  File "/Users/admin/projects/PaddleDetection/ppdet/modeling/backbones/resnet.py", line 432, in __call__
    res = self.layer_warp(res, i)
  File "/Users/admin/projects/PaddleDetection/ppdet/modeling/backbones/resnet.py", line 383, in layer_warp
    nonlocal_name + '_{}'.format(i), int(dim_in / 2) )
  File "/Users/admin/projects/PaddleDetection/ppdet/modeling/backbones/nonlocal_helper.py", line 152, in add_space_nonlocal
    conv = space_nonlocal(input, dim_in, dim_out, prefix, dim_inner)
  File "/Users/admin/projects/PaddleDetection/ppdet/modeling/backbones/nonlocal_helper.py", line 101, in space_nonlocal
    t_re = fluid.layers.reshape(t, shape=list(theta_shape), actual_shape=theta_shape_op  )
  File "/Users/admin/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 8976, in reshape
    attrs["shape"] = get_attr_shape(shape)
  File "/Users/admin/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 8949, in get_attr_shape
    "be -1. But received shape[%d] is also -1." % dim_idx)

Only one dimension value of 'shape' in reshape can be -1. But received shape[2] is also -1.

应该是配置参数不正确，怎么修改？

我使用的cpu版本的paddle，Mac OS 系统

谢谢

**Comment by littletomatodonkey** [comment]
您是master分支的代码嘛，是的话，也需要再更新一下nonlocal helper的代码~
https://github.com/PaddlePaddle/PaddleDetection/blob/497e0e277e7191cf536fdc89cf7cdfe27f38be6b/ppdet/modeling/backbones/nonlocal_helper.py#L105

**Comment by dhlrd** [comment]
好的，已经解决，谢谢
